drivers/xen-tpmfront: Fix compile issue with missing option.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [char] drivers/xen-tpmfront: Fix compile issue with missing option (Jarod Wilson) [1182709]
Rebuild_FUZZ: 99.16%
commit-author Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
commit 713efcabca1fffbbb253a33ff0f8fda532633064

Randy reports:

x86_64:

drivers/built-in.o: In function `xen_tpmfront_init':
xen-tpmfront.c:(.init.text+0x257c): undefined reference to `xenbus_register_frontend'

This is nicely fixed by selecting the XenBus frontend module.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
(cherry picked from commit 713efcabca1fffbbb253a33ff0f8fda532633064)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>