vfio: selftests: Fix VLA initialisation in vfio_pci_irq_set()
JIRA: https://issues.redhat.com/browse/RHEL-149504

commit 4f42d716707654134789a0205a050b0d022be948
Author: Manish Honap <mhonap@nvidia.com>
Date:   Tue Mar 17 10:44:02 2026 +0530

    vfio: selftests: Fix VLA initialisation in vfio_pci_irq_set()

    C does not permit an initialiser expression on a variable-length array
    (C99 Section 6.7.9 constraint: "The type of the entity to be initialized
    shall not be a variable length array type").

    vfio_pci_irq_set() declared:

          u8 buf[sizeof(struct vfio_irq_set) + sizeof(int) * count] = {};

    where `count` is a runtime function parameter, making `buf` a VLA.

    GCC rejects this with (tried with GCC-9.4.0):

          error: variable-sized object may not be initialized

    Fix by removing the `= {}` initialiser and inserting an explicit
    memset() immediately after the declaration.  memset() on a VLA is
    perfectly legal and achieves the same zero-initialisation on all
    conforming C implementations.

    Fixes: 19faf6fd969c ("vfio: selftests: Add a helper library for VFIO selftests")
    Cc: stable@vger.kernel.org
    Reviewed-by: Dave Jiang <dave.jiang@intel.com>
    Reviewed-by: David Matlack <dmatlack@google.com>
    Signed-off-by: Manish Honap <mhonap@nvidia.com>
    Link: https://lore.kernel.org/r/20260317051402.3725670-1-mhonap@nvidia.com
    Signed-off-by: Alex Williamson <alex@shazbot.org>

Signed-off-by: Cédric Le Goater <clg@redhat.com>