s390/vmlogrdr: Make use of iucv_alloc_device()
JIRA: https://issues.redhat.com/browse/RHEL-86670

commit 4ee55c956325f5b28a23c5916bfd8372042702b3
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Mon May 6 21:44:50 2024 +0200

    s390/vmlogrdr: Make use of iucv_alloc_device()

    Make use of iucv_alloc_device() to get rid of quite some code. In addition
    this also removes a cast to an incompatible function (clang W=1):

      drivers/s390/char/vmlogrdr.c:746:18: error: cast from 'void (*)(const void *)' to 'void (*)(struct device *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        746 |                 dev->release = (void (*)(struct device *))kfree;
            |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Closes: https://lore.kernel.org/r/20240417-s390-drivers-fix-cast-function-type-v1-1-fd048c9903b0@kernel.org
    Acked-by: Alexandra Winter <wintera@linux.ibm.com>
    Link: https://lore.kernel.org/r/20240506194454.1160315-3-hca@linux.ibm.com
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>