libbpf: Workaround (another) -Wmaybe-uninitialized false positive
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 8a3f14bb1e944f496d1a16096435ddb2e12e4753
Author: Sam James <sam@gentoo.org>
Date:   Fri Sep 6 14:48:14 2024 +0100

    libbpf: Workaround (another) -Wmaybe-uninitialized false positive

    We get this with GCC 15 -O3 (at least):
    ```
    libbpf.c: In function ‘bpf_map__init_kern_struct_ops’:
    libbpf.c:1109:18: error: ‘mod_btf’ may be used uninitialized [-Werror=maybe-uninitialized]
     1109 |         kern_btf = mod_btf ? mod_btf->btf : obj->btf_vmlinux;
          |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    libbpf.c:1094:28: note: ‘mod_btf’ was declared here
     1094 |         struct module_btf *mod_btf;
          |                            ^~~~~~~
    In function ‘find_struct_ops_kern_types’,
        inlined from ‘bpf_map__init_kern_struct_ops’ at libbpf.c:1102:8:
    libbpf.c:982:21: error: ‘btf’ may be used uninitialized [-Werror=maybe-uninitialized]
      982 |         kern_type = btf__type_by_id(btf, kern_type_id);
          |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    libbpf.c: In function ‘bpf_map__init_kern_struct_ops’:
    libbpf.c:967:21: note: ‘btf’ was declared here
      967 |         struct btf *btf;
          |                     ^~~
    ```

    This is similar to the other libbpf fix from a few weeks ago for
    the same modelling-errno issue (fab45b962749184e1a1a57c7c583782b78fad539).

    Signed-off-by: Sam James <sam@gentoo.org>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://bugs.gentoo.org/939106
    Link: https://lore.kernel.org/bpf/f6962729197ae7cdf4f6d1512625bd92f2322d31.1725630494.git.sam@gentoo.org

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>