selftests: fib_nexthops: Fix creation of non-FDB nexthops
JIRA: https://issues.redhat.com/browse/RHEL-115577
Upstream Status: linux.git

commit c29913109c70383cdf90b6fc792353e1009f24f5
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Sun Sep 21 18:08:23 2025 +0300

    selftests: fib_nexthops: Fix creation of non-FDB nexthops

    The test creates non-FDB nexthops without a nexthop device which leads
    to the expected failure, but for the wrong reason:

     # ./fib_nexthops.sh -t "ipv6_fdb_grp_fcnal ipv4_fdb_grp_fcnal" -v

     IPv6 fdb groups functional
     --------------------------
     [...]
     COMMAND: ip -netns me-nRsN3E nexthop add id 63 via 2001:db8:91::4
     Error: Device attribute required for non-blackhole and non-fdb nexthops.
     COMMAND: ip -netns me-nRsN3E nexthop add id 64 via 2001:db8:91::5
     Error: Device attribute required for non-blackhole and non-fdb nexthops.
     COMMAND: ip -netns me-nRsN3E nexthop add id 103 group 63/64 fdb
     Error: Invalid nexthop id.
     TEST: Fdb Nexthop group with non-fdb nexthops                       [ OK ]
     [...]

     IPv4 fdb groups functional
     --------------------------
     [...]
     COMMAND: ip -netns me-nRsN3E nexthop add id 14 via 172.16.1.2
     Error: Device attribute required for non-blackhole and non-fdb nexthops.
     COMMAND: ip -netns me-nRsN3E nexthop add id 15 via 172.16.1.3
     Error: Device attribute required for non-blackhole and non-fdb nexthops.
     COMMAND: ip -netns me-nRsN3E nexthop add id 103 group 14/15 fdb
     Error: Invalid nexthop id.
     TEST: Fdb Nexthop group with non-fdb nexthops                       [ OK ]

     COMMAND: ip -netns me-nRsN3E nexthop add id 16 via 172.16.1.2 fdb
     COMMAND: ip -netns me-nRsN3E nexthop add id 17 via 172.16.1.3 fdb
     COMMAND: ip -netns me-nRsN3E nexthop add id 104 group 14/15
     Error: Invalid nexthop id.
     TEST: Non-Fdb Nexthop group with fdb nexthops                       [ OK ]
     [...]
     COMMAND: ip -netns me-0dlhyd ro add 172.16.0.0/22 nhid 15
     Error: Nexthop id does not exist.
     TEST: Route add with fdb nexthop                                    [ OK ]

    In addition, as can be seen in the above output, a couple of IPv4 test
    cases used the non-FDB nexthops (14 and 15) when they intended to use
    the FDB nexthops (16 and 17). These test cases only passed because
    failure was expected, but they failed for the wrong reason.

    Fix the test to create the non-FDB nexthops with a nexthop device and
    adjust the IPv4 test cases to use the FDB nexthops instead of the
    non-FDB nexthops.

    Output after the fix:

     # ./fib_nexthops.sh -t "ipv6_fdb_grp_fcnal ipv4_fdb_grp_fcnal" -v

     IPv6 fdb groups functional
     --------------------------
     [...]
     COMMAND: ip -netns me-lNzfHP nexthop add id 63 via 2001:db8:91::4 dev veth1
     COMMAND: ip -netns me-lNzfHP nexthop add id 64 via 2001:db8:91::5 dev veth1
     COMMAND: ip -netns me-lNzfHP nexthop add id 103 group 63/64 fdb
     Error: FDB nexthop group can only have fdb nexthops.
     TEST: Fdb Nexthop group with non-fdb nexthops                       [ OK ]
     [...]

     IPv4 fdb groups functional
     --------------------------
     [...]
     COMMAND: ip -netns me-lNzfHP nexthop add id 14 via 172.16.1.2 dev veth1
     COMMAND: ip -netns me-lNzfHP nexthop add id 15 via 172.16.1.3 dev veth1
     COMMAND: ip -netns me-lNzfHP nexthop add id 103 group 14/15 fdb
     Error: FDB nexthop group can only have fdb nexthops.
     TEST: Fdb Nexthop group with non-fdb nexthops                       [ OK ]

     COMMAND: ip -netns me-lNzfHP nexthop add id 16 via 172.16.1.2 fdb
     COMMAND: ip -netns me-lNzfHP nexthop add id 17 via 172.16.1.3 fdb
     COMMAND: ip -netns me-lNzfHP nexthop add id 104 group 16/17
     Error: Non FDB nexthop group cannot have fdb nexthops.
     TEST: Non-Fdb Nexthop group with fdb nexthops                       [ OK ]
     [...]
     COMMAND: ip -netns me-lNzfHP ro add 172.16.0.0/22 nhid 16
     Error: Route cannot point to a fdb nexthop.
     TEST: Route add with fdb nexthop                                    [ OK ]
     [...]
     Tests passed:  30
     Tests failed:   0
     Tests skipped:  0

    Fixes: 0534c5489c11 ("selftests: net: add fdb nexthop tests")
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: David Ahern <dsahern@kernel.org>
    Link: https://patch.msgid.link/20250921150824.149157-3-idosch@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Guillaume Nault <gnault@redhat.com>