s390/uaccess: fix compile error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Heiko Carstens <hca@linux.ibm.com>
commit 3d787b392d169d4a2e3aee6ac6dfd6ec39722cf2
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-408.el8/3d787b39.failed

Compiling with e.g MARCH=z900 results in compile errors:

   arch/s390/lib/uaccess.c: In function 'copy_from_user_mvcos':
>> arch/s390/lib/uaccess.c:65:15: error: variable 'spec' has initializer but incomplete type
      65 |         union oac spec = {

Therefore make definition of union oac visible for all MARCHs.

	Reported-by: kernel test robot <lkp@intel.com>
	Cc: Nico Boehr <nrb@linux.ibm.com>
	Cc: Janis Schoetterl-Glausch <scgl@linux.ibm.com>
Fixes: 012a224e1fa3 ("s390/uaccess: introduce bit field for OAC specifier")
	Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
(cherry picked from commit 3d787b392d169d4a2e3aee6ac6dfd6ec39722cf2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/s390/include/asm/uaccess.h