ALSA: hda - Fix static checker warning in patch_hdmi.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author David Henningsson <david.henningsson@canonical.com>
commit 360a8245680053619205a3ae10e6bfe624a5da1d

The static checker warning is:

	sound/pci/hda/patch_hdmi.c:460 hdmi_eld_ctl_get()
	error: __memcpy() 'eld->eld_buffer' too small (256 vs 512)

I have a hard time figuring out if this can ever cause an information leak
(I don't think so), but nonetheless it does not hurt to increase the
robustness of the code.

Fixes: 68e03de98507 ('ALSA: hda - hdmi: Do not expose eld data when eld is invalid')
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: David Henningsson <david.henningsson@canonical.com>
	Cc: <stable@vger.kernel.org> # v3.9+
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 360a8245680053619205a3ae10e6bfe624a5da1d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>