clk: imx: Select MXC_CLK for CLK_IMX8QXP
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit 317e69c49b4ceef8aebb47d771498ccb3571bdf9
Author: Abel Vesa <abel.vesa@linaro.org>
Date:   Thu Sep 21 12:23:54 2023 +0300

    clk: imx: Select MXC_CLK for CLK_IMX8QXP

    If the i.MX8QXP clock provider is built-in but the MXC_CLK is
    built as module, build fails:

    aarch64-linux-ld: drivers/clk/imx/clk-imx8-acm.o: in function `imx8_acm_clk_probe':
    clk-imx8-acm.c:(.text+0x3d0): undefined reference to `imx_check_clk_hws'

    Fix that by selecting MXC_CLK in case of CLK_IMX8QXP.

    Fixes: c2cccb6d0b33 ("clk: imx: add imx8qxp clk driver")
    Closes: https://lore.kernel.org/all/8b77219e-b59e-40f1-96f1-980a0b2debcf@infradead.org/
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Abel Vesa <abel.vesa@linaro.org>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>