KVM: x86: Replace 0-length arrays with flexible arrays
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2177720

commit 6213b701a9df047242e69672f56eba62ba0e2d8a
Author: Kees Cook <keescook@chromium.org>
Date:   Wed Jan 18 11:59:09 2023 -0800

    KVM: x86: Replace 0-length arrays with flexible arrays

    Zero-length arrays are deprecated[1]. Replace struct kvm_nested_state's
    "data" union 0-length arrays with flexible arrays. (How are the
    sizes of these arrays verified?) Detected with GCC 13, using
    -fstrict-flex-arrays=3:

    arch/x86/kvm/svm/nested.c: In function 'svm_get_nested_state':
    arch/x86/kvm/svm/nested.c:1536:17: error: array subscript 0 is outside array bounds of 'struct kvm_svm_nested_state_data[0]' [-Werror=array-bounds=]
     1536 |                 &user_kvm_nested_state->data.svm[0];
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from include/uapi/linux/kvm.h:15,
                     from include/linux/kvm_host.h:40,
                     from arch/x86/kvm/svm/nested.c:18:
    arch/x86/include/uapi/asm/kvm.h:511:50: note: while referencing 'svm'
      511 |                 struct kvm_svm_nested_state_data svm[0];
          |                                                  ^~~

    [1] https://www.kernel.org/doc/html/latest/process/deprecated.html#zero-length-and-one-element-arrays

    Cc: Sean Christopherson <seanjc@google.com>
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>
    Cc: "Gustavo A. R. Silva" <gustavoars@kernel.org>
    Cc: x86@kernel.org
    Cc: "H. Peter Anvin" <hpa@zytor.com>
    Cc: kvm@vger.kernel.org
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Reviewed-by: Sean Christopherson <seanjc@google.com>
    Link: https://lore.kernel.org/r/20230105190548.never.323-kees@kernel.org
    Link: https://lore.kernel.org/r/20230118195905.gonna.693-kees@kernel.org
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>