ALSA: hda/ca0132: Limit values for chip addresses to 32-bit
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit d1600401faad4bc186bfdb291d8af644465e20bd

With the previous unsigned long value clang generates warnings like
this:

sound/pci/hda/patch_ca0132.c:860:37: error: implicit conversion from
'unsigned long' to 'u32' (aka 'unsigned int') changes value from
18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
        spec->curr_chip_addx = (res < 0) ? ~0UL : chip_addx;
                             ~             ^~~~

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit d1600401faad4bc186bfdb291d8af644465e20bd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>