Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Chris Ball <cjb@laptop.org>
commit 9d731e7539713acc0ec7b67a5a91357c455d2334

This reverts commit 3af9d15c719017feb63fa99f89ac6009a5a3d467, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer

(cherry picked from commit 9d731e7539713acc0ec7b67a5a91357c455d2334)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>