regulator: mp8859: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2213574

commit 334e6b85a348a79bb018003f09e1cc94accd53a2
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Mar 10 22:45:47 2023 +0100

    regulator: mp8859: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/regulator/mp8859.c:132:34: error: ‘mp8859_dt_id’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214553.275450-3-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Adrien Thierry <athierry@redhat.com>