iommu/vt-d: Fix linker error on 32-bit
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Joerg Roedel <jroedel@suse.de>
commit d6a9642bd673dd0bb2839274fe83eaa979b9207e

A recent commit broke the build on 32-bit x86. The linker throws these
messages:

	ld: drivers/iommu/intel/perf.o: in function `dmar_latency_snapshot':
	perf.c:(.text+0x40c): undefined reference to `__udivdi3'
	ld: perf.c:(.text+0x458): undefined reference to `__udivdi3'

The reason are the 64-bit divides in dmar_latency_snapshot(). Use the
div_u64() helper function for those.

Fixes: 55ee5e67a59a ("iommu/vt-d: Add common code for dmar latency performance monitors")
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
Link: https://lore.kernel.org/r/20210610083120.29224-1-joro@8bytes.org
(cherry picked from commit d6a9642bd673dd0bb2839274fe83eaa979b9207e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>