HID: bpf: doc fixes for hid_hw_request() hooks
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.12
Tested: with the hid-tools test suite and some hardware

commit c79de517a226b86419a5baa867e65e3f8118829f
Author: Benjamin Tissoires <bentiss@kernel.org>
Date:   Mon Jul 1 14:39:52 2024 +0200

    HID: bpf: doc fixes for hid_hw_request() hooks

    We had the following errors while doing make htmldocs:

    Documentation/hid/hid-bpf:185: include/linux/hid_bpf.h:167:
            ERROR: Unexpected indentation.

    Also ensure consistency with the rest of the __u64 vs u64.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Fixes: 9286675a2aed ("HID: bpf: add HID-BPF hooks for hid_hw_output_report")
    Link: https://patch.msgid.link/20240701-fix-cki-v2-4-20564e2e1393@kernel.org
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>