usb: add HAS_IOMEM dependency to USB_XHCI_HCD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_XHCI_HCD (Torez Smith) [1332712]
Rebuild_FUZZ: 94.12%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit 8f2abe808dbfe4f84412aa3bb40f97f464727641

drivers/built-in.o: In function `xhci_plat_probe':
/home/vegard/linux/drivers/usb/host/xhci-plat.c:160: undefined reference to `devm_ioremap_resource'

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 8f2abe808dbfe4f84412aa3bb40f97f464727641)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>