ASoC: amd: vangogh: fix uninitialized symbol warning in machine driver
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Vijendar Mukunda <Vijendar.Mukunda@amd.com>
commit 6f989800639a7a29ab9a02e165b04dc144dd4f2b

Fixed below smatch static checker warning.
sound/soc/amd/vangogh/acp5x-mach.c:190 acp5x_cs35l41_hw_params()
error: uninitialized symbol 'ret'.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Vijendar Mukunda <Vijendar.Mukunda@amd.com>
Link: https://lore.kernel.org/r/20220225193054.24916-4-Vijendar.Mukunda@amd.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 6f989800639a7a29ab9a02e165b04dc144dd4f2b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>