libbpf: Ensure functions with always_inline attribute are inline
Bugzilla: https://bugzilla.redhat.com/2166911

commit d25f40ff68aa61c838947bb9adee6c6b36e77453
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Wed Aug 3 09:14:03 2022 -0600

    libbpf: Ensure functions with always_inline attribute are inline
    
    GCC expects the always_inline attribute to only be set on inline
    functions, as such we should make all functions with this attribute
    use the __always_inline macro which makes the function inline and
    sets the attribute.
    
    Fixes errors like:
    /home/buildroot/bpf-next/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:439:1: error: ‘always_inline’ function might not be inlinable [-Werror=attributes]
      439 | ____##name(unsigned long long *ctx, ##args)
          | ^~~~
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20220803151403.793024-1-james.hilliard1@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>