github actions: Switch to multiline string format suggested by GA docs
The validate-kernel-commits github action has the following errors:

    Error: Process completed with exit code 1.
    Error: Unable to process file command 'output' successfully.
    Error: Invalid value. Matching delimiter not found ''EOF''

Switch to the multiline string format suggested in the github action
documentation here:
https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-a-multiline-string