net/handshake: Fix section mismatch in handshake_exit
JIRA: https://issues.redhat.com/browse/RHEL-7936

commit 6aa445e39693bff9c98b12f960e66b4e18c7378b
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Thu Apr 20 19:37:23 2023 +0200

    net/handshake: Fix section mismatch in handshake_exit

    If CONFIG_NET_NS=n (e.g. m68k/defconfig):

        WARNING: modpost: vmlinux.o: section mismatch in reference: handshake_exit (section: .exit.text) -> handshake_genl_net_ops (section: .init.data)
        ERROR: modpost: Section mismatches detected.

    Fix this by dropping the __net_initdata tag from handshake_genl_net_ops.

    Fixes: 3b3009ea8abb713b ("net/handshake: Create a NETLINK service for handling handshake requests")
    Reported-by: noreply@ellerman.id.au
    Closes: http://kisskb.ellerman.id.au/kisskb/buildresult/14912987
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reviewed-by: Chuck Lever <chuck.lever@oracle.com>
    Link: https://lore.kernel.org/r/20230420173723.3773434-1-geert@linux-m68k.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Jeffrey Layton <jlayton@redhat.com>