netfilter: kconfig: nat related expression depend on nftables core
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Florian Westphal <fw@strlen.de>
commit e0758412208960be9de11e6d2350c81ffd88410f

NF_TABLES_IPV4 is now boolean so it is possible to set

NF_TABLES=m
NF_TABLES_IPV4=y
NFT_CHAIN_NAT_IPV4=y

which causes:
nft_chain_nat_ipv4.c:(.text+0x6d): undefined reference to `nft_do_chain'

Wrap NFT_CHAIN_NAT_IPV4 and related nat expressions with NF_TABLES to
restore the dependency.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
Fixes: 02c7b25e5f54 ("netfilter: nf_tables: build-in filter chain type")
	Signed-off-by: Florian Westphal <fw@strlen.de>
	Acked-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit e0758412208960be9de11e6d2350c81ffd88410f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>