wifi: brcmsmac: ampdu: remove unused suc_mpdu variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit 2f73f04b7f93f031c94a5c473dd9b7f1cdf91bc0

clang with W=1 reports
drivers/net/wireless/broadcom/brcm80211/brcmsmac/ampdu.c:848:5: error: variable
  'suc_mpdu' set but not used [-Werror,-Wunused-but-set-variable]
        u8 suc_mpdu = 0, tot_mpdu = 0;
           ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Simon Horman <simon.horman@corigine.com>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230327151151.1771350-1-trix@redhat.com
(cherry picked from commit 2f73f04b7f93f031c94a5c473dd9b7f1cdf91bc0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>