media: pvrusb2: VIDEO_PVRUSB2 depends on DVB_CORE to use dvb_* symbols
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-526.el8
commit-author Tom Rix <trix@redhat.com>
commit 1107283b3351bef138cd12dbda1f999891cab7db
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-526.el8/1107283b.failed

A rand config causes this link error
vmlinux.o: In function `pvr2_dvb_create':
(.text+0x8af1d2): undefined reference to `dvb_register_adapter'

The rand config has
CONFIG_VIDEO_PVRUSB2=y
CONFIG_VIDEO_DEV=y
CONFIG_DVB_CORE=m

VIDEO_PVRUSB2 should also depend on DVB_CORE.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
	Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>
(cherry picked from commit 1107283b3351bef138cd12dbda1f999891cab7db)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/media/usb/pvrusb2/Kconfig