net: mdio-octeon: Fix Kconfig warnings and build errors
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit b8fb640643fcdb3bca84137c4cec0c649b25e056

After commit 171a9bae68c7 ("staging/octeon: Allow test build on
!MIPS"), the following combination of configs cause a few Kconfig
warnings and build errors (distilled from arm allyesconfig and Randy's
randconfig builds):

    CONFIG_NETDEVICES=y
    CONFIG_STAGING=y
    CONFIG_COMPILE_TEST=y

and CONFIG_OCTEON_ETHERNET as either a module or built-in.

WARNING: unmet direct dependencies detected for MDIO_OCTEON
  Depends on [n]: NETDEVICES [=y] && MDIO_DEVICE [=y] && MDIO_BUS [=y]
&& 64BIT [=n] && HAS_IOMEM [=y] && OF_MDIO [=n]
  Selected by [y]:
  - OCTEON_ETHERNET [=y] && STAGING [=y] && (CAVIUM_OCTEON_SOC ||
COMPILE_TEST [=y]) && NETDEVICES [=y]

In file included from ../drivers/net/phy/mdio-octeon.c:14:
../drivers/net/phy/mdio-cavium.h:111:36: error: implicit declaration of
function ‘writeq’; did you mean ‘writel’?
[-Werror=implicit-function-declaration]
  111 | #define oct_mdio_writeq(val, addr) writeq(val, (void *)addr)
      |                                    ^~~~~~

CONFIG_64BIT is not strictly necessary if the proper readq/writeq
definitions are included from io-64-nonatomic-lo-hi.h.

CONFIG_OF_MDIO is not needed when CONFIG_COMPILE_TEST is enabled because
of commit f9dc9ac51610 ("of/mdio: Add dummy functions in of_mdio.h.").

Fixes: 171a9bae68c7 ("staging/octeon: Allow test build on !MIPS")
	Reported-by: kbuild test robot <lkp@intel.com>
	Reported-by: Mark Brown <broonie@kernel.org>
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b8fb640643fcdb3bca84137c4cec0c649b25e056)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>