libbpf: Fix use #ifdef instead of #if to avoid compiler warning
Bugzilla: https://bugzilla.redhat.com/2120968

commit ded6dffaed5edc68f1e64b523353da14db673460
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Thu Apr 7 13:38:42 2022 -0700

    libbpf: Fix use #ifdef instead of #if to avoid compiler warning
    
    As reported by Naresh:
    
      perf build errors on i386 [1] on Linux next-20220407 [2]
    
      usdt.c:1181:5: error: "__x86_64__" is not defined, evaluates to 0
      [-Werror=undef]
       1181 | #if __x86_64__
            |     ^~~~~~~~~~
      usdt.c:1196:5: error: "__x86_64__" is not defined, evaluates to 0
      [-Werror=undef]
       1196 | #if __x86_64__
            |     ^~~~~~~~~~
      cc1: all warnings being treated as errors
    
    Use #ifdef instead of #if to avoid this.
    
    Fixes: 4c59e584d158 ("libbpf: Add x86-specific USDT arg spec parsing logic")
    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20220407203842.3019904-1-andrii@kernel.org

Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>