bnx2x: remove unused variable 'cur_data_offset'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Bill Wendling <morbo@google.com>
commit 919d527956daa3e7ad03a23ba661beb8a46cacf4

Fix the clang build warning:

  drivers/net/ethernet/broadcom/bnx2x/bnx2x_sriov.c:1862:13: error: variable 'cur_data_offset' set but not used [-Werror,-Wunused-but-set-variable]
        dma_addr_t cur_data_offset;

	Signed-off-by: Bill Wendling <morbo@google.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 919d527956daa3e7ad03a23ba661beb8a46cacf4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>