USB: OHCI: remove space before open square bracket '['
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Naveen Kumar Parna <parna.naveenkumar@gmail.com>
commit 4e4feeec4e6cf6d0e14a45470c7f232cb685336b

This patch removes following checkpatch.pl error in usb/host/ohci-pci.c file.
ERROR: space prohibited before open square bracket '['

	Signed-off-by: Naveen Kumar Parna <parna.naveenkumar@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 4e4feeec4e6cf6d0e14a45470c7f232cb685336b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>