clk: Fix undefined reference to `clk_rate_exclusive_{get,put}'
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit 2746f13f6f1df7999001d6595b16f789ecc28ad1
Author: Biju Das <biju.das.jz@bp.renesas.com>
Date:   Tue Jul 25 18:51:40 2023 +0100

    clk: Fix undefined reference to `clk_rate_exclusive_{get,put}'

    The COMMON_CLK config is not enabled in some of the architectures.
    This causes below build issues:

    pwm-rz-mtu3.c:(.text+0x114):
    undefined reference to `clk_rate_exclusive_put'
    pwm-rz-mtu3.c:(.text+0x32c):
    undefined reference to `clk_rate_exclusive_get'

    Fix these issues by moving clk_rate_exclusive_{get,put} inside COMMON_CLK
    code block, as clk.c is enabled by COMMON_CLK.

    Fixes: 55e9b8b7b806 ("clk: add clk_rate_exclusive api")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/all/202307251752.vLfmmhYm-lkp@intel.com/
    Signed-off-by: Biju Das <biju.das.jz@bp.renesas.com>
    Link: https://lore.kernel.org/r/20230725175140.361479-1-biju.das.jz@bp.renesas.com
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>