security: export security_kernel_load_data function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 83a68a06795fa47e77ea758f293a5946e9e02e84

The firmware_loader can be built as a loadable module, which now
fails when CONFIG_SECURITY is enabled, because a call to the
security_kernel_load_data() function got added, and this is
not exported to modules:

ERROR: "security_kernel_load_data" [drivers/base/firmware_loader/firmware_class.ko] undefined!

Add an EXPORT_SYMBOL_GPL() to make it available here.

Fixes: 6e852651f28e ("firmware: add call to LSM hook before firmware sysfs fallback")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: James Morris <james.morris@microsoft.com>
(cherry picked from commit 83a68a06795fa47e77ea758f293a5946e9e02e84)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>