RDMA/uverbs: Import DMA-BUF module in uverbs_std_types_dmabuf file
JIRA: https://redhat.atlassian.net/browse/RHEL-163515

commit 7c2889af823340d1d410939b9d547bf184d5fa54
Author: Leon Romanovsky <leon@kernel.org>
Date:   Wed Feb 25 15:48:59 2026 +0200

    RDMA/uverbs: Import DMA-BUF module in uverbs_std_types_dmabuf file

    Fix the following compilation error:

    ERROR: modpost: module ib_uverbs uses symbol dma_buf_move_notify
            from namespace DMA_BUF, but does not import it.

    Fixes: 0ac6f4056c4a ("RDMA/uverbs: Add DMABUF object type and operations")
    Link: https://patch.msgid.link/20260225-fix-uverbs-compilation-v1-1-acf7b3d0f9fa@nvidia.com
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>