arm64: irq: include <linux/cpumask.h>
JIRA: https://issues.redhat.com/browse/RHEL-40604

Conflicts:
	arch/arm64/include/asm/irq.h
	Conflict with RHEL-only patch

commit b95df3bd1ea31fadc9e1471a036b4c08199aa0f0
Author: Tudor Ambarus <tudor.ambarus@linaro.org>
Date: Wed, 10 Jan 2024 07:40:07 +0000

    Sorting include files in alphabetic order in
    drivers/tty/serial/samsung.c revealed the following error:

    In file included from drivers/tty/serial/samsung_tty.c:24:
    ./arch/arm64/include/asm/irq.h:9:43: error: unknown type name ‘cpumask_t’
        9 | void arch_trigger_cpumask_backtrace(const cpumask_t *mask, int exclude_cpu);
          |                                           ^~~~~~~~~

    Include cpumask.h to avoid unknown type errors for parents of irq.h that
    don't include cpumask.h.

    Acked-by: Mark Rutland <mark.rutland@arm.com>
    Signed-off-by: Tudor Ambarus <tudor.ambarus@linaro.org>
    Reviewed-by: Stephen Boyd <swboyd@chromium.org>
    Link: https://lore.kernel.org/r/20240110074007.4020016-1-tudor.ambarus@linaro.org
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>