fbdev: mb862xxfb: Fix defined but not used error
JIRA: https://issues.redhat.com/browse/RHEL-53899
Upstream Status: v6.9-rc1

commit 974191720ae76ba3613c4aa2301c297b4de27e46
Author:     Michael Ellerman <mpe@ellerman.id.au>
AuthorDate: Thu Feb 29 22:50:10 2024 +1100
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Fri Mar 15 10:01:27 2024 +0100

    socrates_gc_mode is defined at the top-level but then only used inside
    an #ifdef CONFIG_FB_MB862XX_LIME, leading to an error with some configs:

      drivers/video/fbdev/mb862xx/mb862xxfbdrv.c:36:31: error: ‘socrates_gc_mode’ defined but not used
         36 | static struct mb862xx_gc_mode socrates_gc_mode = {

    Fix it by moving socrates_gc_mode inside that ifdef, immediately prior
    to the only function where it's used.

    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>