selftests: kvm: Fix a compile error in selftests/kvm/rseq_test.c
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2119111

commit 561cafebb2cf97b0927b4fb0eba22de6200f682e
Author: Jinrong Liang <cloudliang@tencent.com>
Date:   Tue Aug 2 15:12:40 2022 +0800

    selftests: kvm: Fix a compile error in selftests/kvm/rseq_test.c

    The following warning appears when executing:
            make -C tools/testing/selftests/kvm

    rseq_test.c: In function ‘main’:
    rseq_test.c:237:33: warning: implicit declaration of function ‘gettid’; did you mean ‘getgid’? [-Wimplicit-function-declaration]
              (void *)(unsigned long)gettid());
                                     ^~~~~~
                                     getgid
    /usr/bin/ld: /tmp/ccr5mMko.o: in function `main':
    ../kvm/tools/testing/selftests/kvm/rseq_test.c:237: undefined reference to `gettid'
    collect2: error: ld returned 1 exit status
    make: *** [../lib.mk:173: ../kvm/tools/testing/selftests/kvm/rseq_test] Error 1

    Use the more compatible syscall(SYS_gettid) instead of gettid() to fix it.
    More subsequent reuse may cause it to be wrapped in a lib file.

    Signed-off-by: Jinrong Liang <cloudliang@tencent.com>
    Message-Id: <20220802071240.84626-1-cloudliang@tencent.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>