net/mlx5: SD, Handle possible devcom ERR_PTR
JIRA: https://issues.redhat.com/browse/RHEL-52869
Upstream-status: v6.9-rc5

commit aa4ac90d04f4371466000825adb44935ecb5c974
Author: Tariq Toukan <tariqt@nvidia.com>
Date:   Thu Apr 11 14:54:40 2024 +0300

    net/mlx5: SD, Handle possible devcom ERR_PTR

    Check if devcom holds an error pointer and return immediately.

    This fixes Smatch static checker warning:
    drivers/net/ethernet/mellanox/mlx5/core/lib/sd.c:221 sd_register()
    error: 'devcom' dereferencing possible ERR_PTR()

    Enhance mlx5_devcom_register_component() so it stops returning NULL,
    making it easier for its callers.

    Fixes: d3d057666090 ("net/mlx5: SD, Implement devcom communication and primary election")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Link: https://lore.kernel.org/all/f09666c8-e604-41f6-958b-4cc55c73faf9@gmail.com/T/
    Signed-off-by: Tariq Toukan <tariqt@nvidia.com>
    Reviewed-by: Gal Pressman <gal@nvidia.com>
    Link: https://lore.kernel.org/r/20240411115444.374475-3-tariqt@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@redhat.com>