net/sched: matchall: Avoid overwriting error messages
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit 0cba5c34b8f4b4b81e5102992c8a9e189ec27768
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:32 2022 +0300

    net/sched: matchall: Avoid overwriting error messages

    The various error paths of tc_setup_offload_action() now report specific
    error messages. Remove the generic messages to avoid overwriting the
    more specific ones.

    Before:

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action police rate 100Mbit burst 10000
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

    After:

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action police rate 100Mbit burst 10000
     Error: act_police: Offload not supported when conform/exceed action is "reclassify".
     We have an error talking to the kernel

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>