perf scripting python: Do not build fail on deprecation warnings
Bugzilla: https://bugzilla.redhat.com/2123229

upstream
========
commit 4ee3c4da8b1b9c225bd156a7909980e32f3b3153
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Aug 2 15:40:20 2022 -0300

description
===========
First noticed with fedora:rawhide:

  48    11.10 fedora:rawhide                : FAIL gcc version 12.1.1 20220628 (Red Hat 12.1.1-3) (GCC)
    util/scripting-engines/trace-event-python.c: In function 'python_start_script':
    util/scripting-engines/trace-event-python.c:1899:9: error: 'PySys_SetArgv' is deprecated [-Werror=deprecated-declarations]
     1899 |         PySys_SetArgv(argc + 1, command_line);

No time now to address this warning, so don't make it an error, in time
we should either add yet more ifdefs to continue supporting older
systems or just convert to whatever new infra python put in place for
argv processing, sigh.

    Acked-by: Ian Rogers <irogers@google.com>
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>