mshv: hide x86-specific functions on arm64
jira KERNEL-1029
Rebuild_History Non-Buildable kernel-6.12.0-211.7.1.el10_2
commit-author Arnd Bergmann <arnd@arndb.de>
commit 92c172ae16a2718aba0d8fec5a62fc1b8aa452dc
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-6.12.0-211.7.1.el10_2/92c172ae.failed

The hv_sleep_notifiers_register() and hv_machine_power_off() functions are
only called and declared on x86, but cause a warning on arm64:

drivers/hv/mshv_common.c:210:6: error: no previous prototype for 'hv_sleep_notifiers_register' [-Werror=missing-prototypes]
  210 | void hv_sleep_notifiers_register(void)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/hv/mshv_common.c:224:6: error: no previous prototype for 'hv_machine_power_off' [-Werror=missing-prototypes]
  224 | void hv_machine_power_off(void)
      |      ^~~~~~~~~~~~~~~~~~~~

Hide both inside of an #ifdef block.

Fixes: f0be2600ac55 ("mshv: Use reboot notifier to configure sleep state")
Fixes: 615a6e7d83f9 ("mshv: Cleanly shutdown root partition with MSHV")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Wei Liu <wei.liu@kernel.org>
(cherry picked from commit 92c172ae16a2718aba0d8fec5a62fc1b8aa452dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/hv/mshv_common.c