net/mlxfw: Improve FSM err message reporting and return codes
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Saeed Mahameed <saeedm@mellanox.com>
commit 86a1270fd79f99e7aa85c2c81cd59d0eab92112f

Report unique and standard error codes corresponding to the specific
FW flash error. In addition, add a more detailed error messages to
netlink.

Before:
$ devlink dev flash pci/0000:05:00.0 file ...
Error: mlxfw: Firmware flash failed.
devlink answers: Invalid argument

After:
$ devlink dev flash pci/0000:05:00.0 file ...
Error: mlxfw: Firmware flash failed: pending reset.
devlink answers: Device busy

	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
	Reviewed-by: Ido Schimmel <idosch@mellanox.com>
	Acked-by: Jiri Pirko <jiri@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 86a1270fd79f99e7aa85c2c81cd59d0eab92112f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>