rtnetlink: Make per-netns RTNL dereference helpers to macro.
JIRA: https://issues.redhat.com/browse/RHEL-150155
Upstream Status: linux.git

commit 9cb7e40d388d6c0e4677809c6b2950bc67fd8830
Author: Kuniyuki Iwashima <kuniyu@amazon.com>
Date:   Mon Oct 21 11:32:28 2024 -0700

    rtnetlink: Make per-netns RTNL dereference helpers to macro.

    When CONFIG_DEBUG_NET_SMALL_RTNL is off, rtnl_net_dereference() is the
    static inline wrapper of rtnl_dereference() returning a plain (void *)
    pointer to make sure net is always evaluated as requested in [0].

    But, it makes sparse complain [1] when the pointer has __rcu annotation:

      net/ipv4/devinet.c:674:47: sparse: warning: incorrect type in argument 2 (different address spaces)
      net/ipv4/devinet.c:674:47: sparse:    expected void *p
      net/ipv4/devinet.c:674:47: sparse:    got struct in_ifaddr [noderef] __rcu *

    Also, if we evaluate net as (void *) in a macro, then the compiler
    in turn fails to build due to -Werror=unused-value.

      #define rtnl_net_dereference(net, p)                  \
            ({                                              \
                    (void *)net;                            \
                    rtnl_dereference(p);                    \
            })

      net/ipv4/devinet.c: In function ‘inet_rtm_deladdr’:
      ./include/linux/rtnetlink.h:154:17: error: statement with no effect [-Werror=unused-value]
        154 |                 (void *)net;                            \
      net/ipv4/devinet.c:674:21: note: in expansion of macro ‘rtnl_net_dereference’
        674 |              (ifa = rtnl_net_dereference(net, *ifap)) != NULL;
            |                     ^~~~~~~~~~~~~~~~~~~~

    Let's go back to the original simplest macro.

    Note that checkpatch complains about this approach, but it's one-shot and
    less noisy than the other two.

      WARNING: Argument 'net' is not used in function-like macro
      #76: FILE: include/linux/rtnetlink.h:142:
      +#define rtnl_net_dereference(net, p)                 \
      +     rtnl_dereference(p)

    Fixes: 844e5e7e656d ("rtnetlink: Add assertion helpers for per-netns RTNL.")
    Link: https://lore.kernel.org/netdev/20241004132145.7fd208e9@kernel.org/ [0]
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202410200325.SaEJmyZS-lkp@intel.com/ [1]
    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Antoine Tenart <atenart@redhat.com>