x86/Kconfig: Fix an unused variable error in dell-smm-hwmon
Bugzilla: https://bugzilla.redhat.com/2163809

commit ef775a0e36c6a81c5b07cb228c02f967133fe768
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Fri Sep 10 00:19:21 2021 -0700

    x86/Kconfig: Fix an unused variable error in dell-smm-hwmon

    When CONFIG_PROC_FS is not set, there is a build warning (turned
    into an error):

      ../drivers/hwmon/dell-smm-hwmon.c: In function 'i8k_init_procfs':
      ../drivers/hwmon/dell-smm-hwmon.c:624:24: error: unused variable 'data' [-Werror=unused-variable]
        struct dell_smm_data *data = dev_get_drvdata(dev);

    Make I8K depend on PROC_FS and HWMON (instead of selecting HWMON -- it
    is strongly preferred to not select entire subsystems).

    Build tested in all possible combinations of SENSORS_DELL_SMM, I8K, and
    PROC_FS.

    Fixes: 039ae58503f3 ("hwmon: Allow to compile dell-smm-hwmon driver without /proc/i8k")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Pali Rohár <pali@kernel.org>
    Link: https://lkml.kernel.org/r/20210910071921.16777-1-rdunlap@infradead.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>