[redhat-rt] remove unused and unpackaged file modules.kvm
Bugzilla: INTERNAL
Upstream Status: RHEL only

The existence of the unused and unpackaged file modules.kvm resulted in
the following build error:

    Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/kernel-rt-5.14.0-284.rt14.284.el9.x86_64
    error: Installed (but unpackaged) file(s) found:
       /lib/modules/5.14.0-284.rt14.284.el9.x86_64+debug/modules.kvm
       /lib/modules/5.14.0-284.rt14.284.el9.x86_64/modules.kvm

Signed-off-by: Luis Claudio R. Goncalves <lgoncalv@redhat.com>