selftests/bpf: Silence unused-but-set build warnings
JIRA: https://issues.redhat.com/browse/RHEL-139985

commit c67f4ae73798b6f9f41921b2dc81c0055f470e41
Author: Tiezhu Yang <yangtiezhu@loongson.cn>
Date:   Sat Oct 18 16:28:15 2025 +0800

    selftests/bpf: Silence unused-but-set build warnings
    
    There are some set but not used build errors when compiling bpf selftests
    with the latest upstream mainline GCC, at the beginning add the attribute
    __maybe_unused for the variables, but it is better to just add the option
    -Wno-unused-but-set-variable to CFLAGS in Makefile to disable the errors
    instead of hacking the tests.
    
      tools/testing/selftests/bpf/map_tests/lpm_trie_map_basic_ops.c:229:36:
      error: variable ‘n_matches_after_delete’ set but not used [-Werror=unused-but-set-variable=]
    
      tools/testing/selftests/bpf/map_tests/lpm_trie_map_basic_ops.c:229:25:
      error: variable ‘n_matches’ set but not used [-Werror=unused-but-set-variable=]
    
      tools/testing/selftests/bpf/prog_tests/bpf_cookie.c:426:22:
      error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
    
      tools/testing/selftests/bpf/prog_tests/find_vma.c:52:22:
      error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
    
      tools/testing/selftests/bpf/prog_tests/perf_branches.c:67:22:
      error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
    
      tools/testing/selftests/bpf/prog_tests/perf_link.c:15:22:
      error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
    
    Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
    Link: https://lore.kernel.org/r/20251018082815.20622-1-yangtiezhu@loongson.cn
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>