arm64: avoid BUILD_BUG_ON() in alternative-macros
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2167398

commit 0072dc1b53c39fb7c4cfc5c9e5d5a30622198613
Author: Mark Rutland <mark.rutland@arm.com>
Date: Tue, 20 Sep 2022 15:00:44 +0100

    Nathan reports that the build fails when using clang and LTO:

    |  In file included from kernel/bounds.c:10:
    |  In file included from ./include/linux/page-flags.h:10:
    |  In file included from ./include/linux/bug.h:5:
    |  In file included from ./arch/arm64/include/asm/bug.h:26:
    |  In file included from ./include/asm-generic/bug.h:5:
    |  In file included from ./include/linux/compiler.h:248:
    |  In file included from ./arch/arm64/include/asm/rwonce.h:11:
    |  ./arch/arm64/include/asm/alternative-macros.h:224:2: error: call to undeclared function 'BUILD_BUG_ON'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    |          BUILD_BUG_ON(feature >= ARM64_NCAPS);
    |          ^
    |  ./arch/arm64/include/asm/alternative-macros.h:241:2: error: call to undeclared function 'BUILD_BUG_ON'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    |          BUILD_BUG_ON(feature >= ARM64_NCAPS);
    |          ^
    |  2 errors generated.

    ... the problem being that when LTO is enabled, <asm/rwonce.h> includes
    <asm/alternative-macros.h>, and causes a circular include dependency
    through <linux/bug.h>. This manifests as BUILD_BUG_ON() not being
    defined when used within <asm/alternative-macros.h>.

    This patch avoids the problem and simplifies the include dependencies by
    using compiletime_assert() instead of BUILD_BUG_ON().

    Signed-off-by: Mark Rutland <mark.rutland@arm.com>
    Fixes: 21fb26bfb01f ("arm64: alternatives: add alternative_has_feature_*()")
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Tested-by: Nathan Chancellor <nathan@kernel.org>
    Link: http://lore.kernel.org/r/YyigTrxhE3IRPzjs@dev-arch.thelio-3990X
    Cc: Ard Biesheuvel <ardb@kernel.org>
    Cc: James Morse <james.morse@arm.com>
    Cc: Joey Gouly <joey.gouly@arm.com>
    Cc: Marc Zyngier <maz@kernel.org>
    Cc: Will Deacon <will@kernel.org>
    Reviewed-by: Ard Biesheuvel <ardb@kernel.org>
    Acked-by: Marc Zyngier <maz@kernel.org>
    Link: https://lore.kernel.org/r/20220920140044.1709073-1-mark.rutland@arm.com
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>