ACPI / NUMA: Add stub function for pxm_to_node()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 4849bc777049b568a35d5d63ae326e93f0fff9de

After commit 01feba590cd6 ("ACPI: Do not create new NUMA domains from
ACPI static tables that are not SRAT"):

$ scripts/config --file arch/x86/configs/x86_64_defconfig -d NUMA -e ACPI_NFIT

$ make -skj"$(nproc)" distclean defconfig drivers/acpi/nfit/
drivers/acpi/nfit/core.c: In function ‘acpi_nfit_register_region’:
drivers/acpi/nfit/core.c:3010:27: error: implicit declaration of
function ‘pxm_to_node’; did you mean ‘xa_to_node’?
[-Werror=implicit-function-declaration]
 3010 |   ndr_desc->target_node = pxm_to_node(spa->proximity_domain);
      |                           ^~~~~~~~~~~
      |                           xa_to_node
cc1: some warnings being treated as errors
...

Add a stub function like acpi_map_pxm_to_node() had so that the build
continues to work.

Fixes: 01feba590cd6 ("ACPI: Do not create new NUMA domains from ACPI static tables that are not SRAT")
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
	Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 4849bc777049b568a35d5d63ae326e93f0fff9de)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>