s390/kasan: adapt disabled_wait usage to avoid build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Vasily Gorbik <gor@linux.ibm.com>
commit 184c460fbab4d3bf23d31ac5adba21540f756b6d

Fix the following build error when the kernel is built with CONFIG_KASAN
broken since commit 98587c2d894c ("s390: simplify disabled_wait"):

arch/s390/mm/kasan_init.c: In function 'kasan_early_panic':
arch/s390/mm/kasan_init.c:31:2: error: too many arguments to function
'disabled_wait'
   31 |  disabled_wait(0);

Fixes: 98587c2d894c ("s390: simplify disabled_wait")
	Reported-by: Benjamin Block <bblock@linux.ibm.com>
	Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>
	Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
(cherry picked from commit 184c460fbab4d3bf23d31ac5adba21540f756b6d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>