pwm: tegra: Fix 32 bit build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181001

commit dd1f1da4ada5d8ac774c2ebe97230637820b3323
Author: Steven Price <steven.price@arm.com>
Date: Thu, 10 Nov 2022 11:45:48 +0000

    The value of NSEC_PER_SEC << PWM_DUTY_WIDTH doesn't fix within a 32 bit
    integer causing a build warning/error (and the value truncated):

      drivers/pwm/pwm-tegra.c: In function ‘tegra_pwm_config’:
      drivers/pwm/pwm-tegra.c:148:53: error: result of ‘1000000000 << 8’ requires 39 bits to represent, but ‘long int’ only has 32 bits [-Werror=shift-overflow=]
        148 |   required_clk_rate = DIV_ROUND_UP_ULL(NSEC_PER_SEC << PWM_DUTY_WIDTH,
            |                                                     ^~

    Explicitly cast to a u64 to ensure the correct result.

    Fixes: cfcb68817fb3 ("pwm: tegra: Improve required rate calculation")
    Signed-off-by: Steven Price <steven.price@arm.com>
    Reviewed-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
    Reviewed-by: Jon Hunter <jonathanh@nvidia.com>

Signed-off-by: Mark Salter <msalter@redhat.com>