btrfs: Use __u64 in exported linux/btrfs.h.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [fs] btrfs: Use __u64 in exported linux/btrfs.h (Bill O'Donnell) [1437489]
Rebuild_FUZZ: 98.82%
commit-author Vinson Lee <vlee@freedesktop.org>
commit 1691cf160048c0753036d0b3fad7f239234dab56

This patch fixes this build error.

/usr/include/linux/btrfs.h:121:3: error: unknown type name ‘u64’
   u64 devid;
   ^~~

Fixes: 6b526ed70cf1 ("btrfs: introduce device delete by devid")
	Signed-off-by: Vinson Lee <vlee@freedesktop.org>
	Signed-off-by: David Sterba <dsterba@suse.com>
(cherry picked from commit 1691cf160048c0753036d0b3fad7f239234dab56)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>