ASoC: cht_bsw_max98090_ti: Remove unused function cht_get_codec_dai()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: cht_bsw_max98090_ti: Remove unused function cht_get_codec_dai() (Jaroslav Kysela) [1463624]
Rebuild_FUZZ: 95.83%
commit-author Matthias Kaehlcke <mka@chromium.org>
commit 140385d87adce8d00864667f5132770ac5a13dac

Looks like the function has never been used since it was added by commit
17119a465706 ("ASoC: Intel: Add Cherrytrail & Braswell machine driver
cht_bsw_max98090_ti"). Removing it fixes the following warning when
building with clang:

sound/soc/intel/boards/cht_bsw_max98090_ti.c:42:35: error: unused
    function 'cht_get_codec_dai' [-Werror,-Wunused-function]

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 140385d87adce8d00864667f5132770ac5a13dac)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>