x86/quirks: Include linux/pnp.h for arch_pnpbios_disabled()
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 056b44a4d10907ec8153863b2a0564e808ef1440
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:38 2023 +0200

    x86/quirks: Include linux/pnp.h for arch_pnpbios_disabled()

    arch_pnpbios_disabled() is defined in architecture code on x86, but this
    does not include the appropriate header, causing a warning:

    arch/x86/kernel/platform-quirks.c:42:13: error: no previous prototype for 'arch_pnpbios_disabled' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-10-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>