xfs: call roundup_64() to calculate the min_logblks
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
commit-author Jie Liu <jeff.liu@oracle.com>
commit 2c2bcc0735f4ab052559b539f3fcab4087187232

Replace roundup() with roundup_64() as we calculate min_logblks
with 64-bit divisions.  Hence, call roundup() will cause the
following error while compiling a 32-bit kernel:

fs/built-in.o: In function `xfs_log_calc_minimum_size':
fs/xfs/xfs_log_rlimit.c:140: undefined reference to `__udivdi3'

	Reported-by: Fengguang Wu <fengguang.wu@intel.com>
	Cc: Dave Chinner <dchinner@redhat.com>
	Signed-off-by: Jie Liu <jeff.liu@oracle.com>
	Reviewed-by: Dave Chinner <dchinner@redhat.com>
	Signed-off-by: Ben Myers <bpm@sgi.com>

(cherry picked from commit 2c2bcc0735f4ab052559b539f3fcab4087187232)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>