ALSA: portman2x4: remove unused portman_read_command,data functions
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Tom Rix <trix@redhat.com>
commit 6aa9b1d071bf62e7489601f57a13da55b1a96add

clang with W=1 reports
sound/drivers/portman2x4.c:185:18: error: unused function
  'portman_read_command' [-Werror,-Wunused-function]
static inline u8 portman_read_command(struct portman *pm)
                 ^
sound/drivers/portman2x4.c:195:18: error: unused function
  'portman_read_data' [-Werror,-Wunused-function]
static inline u8 portman_read_data(struct portman *pm)
                 ^
These static functions are not used, so remove them.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230318135229.1685266-1-trix@redhat.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 6aa9b1d071bf62e7489601f57a13da55b1a96add)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>