ASoC: fsl_sai: add IMX_SCMI_MISC_DRV dependency
JIRA: https://issues.redhat.com/browse/RHEL-168082

commit 742048f2e128c06d0ef89ffc334519cb8e991f66
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Feb 2 10:53:50 2026 +0100

    ASoC: fsl_sai: add IMX_SCMI_MISC_DRV dependency

    The sai driver now links against the SCMI code directly, causing a
    link failure when that is in a loadable module:

    aarch64-linux-ld: sound/soc/fsl/fsl_sai.o: in function `fsl_sai_probe':
    fsl_sai.c:(.text+0x1fe4): undefined reference to `scmi_imx_misc_ctrl_set'

    Move the dependency from SND_SOC_FSL_MQS to SND_SOC_FSL_SAI. The MQS
    driver depends on the SAI one, so it still gets the same dependency
    indirectly.

    All other drivers that select the SAI symbol need the same dependency
    in turn, though that could probably get replaced with a 'depends on
    SND_SOC_FSL_SAI' to keep it simpler.

    Fixes: 19b08fd23b20 ("ASoC: fsl_sai: Add AUDMIX mode support on i.MX952")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260202095353.1233963-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>