wifi: rtw88: remove unused rtw_pci_get_tx_desc function
Bugzilla: https://bugzilla.redhat.com/2196821

commit c9b6111a6f94bd186d1f0f7a04a9b37030a27738
Author: Tom Rix <trix@redhat.com>
Date:   Mon Mar 20 19:34:48 2023 -0400

    wifi: rtw88: remove unused rtw_pci_get_tx_desc function
    
    clang with W=1 reports
    drivers/net/wireless/realtek/rtw88/pci.c:92:21: error:
      unused function 'rtw_pci_get_tx_desc' [-Werror,-Wunused-function]
    static inline void *rtw_pci_get_tx_desc(struct rtw_pci_tx_ring *tx_ring, u8 idx)
                        ^
    This function is not used, so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230320233448.1729899-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>