smb: client: fix sbflags initialization
jira KERNEL-1468
Rebuild_History Non-Buildable kernel-5.14.0-687.38.1.el9_8
commit-author Arnd Bergmann <arnd@arndb.de>
commit fae11330dc0642065568d6c0045322293fe59bc6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-5.14.0-687.38.1.el9_8/fae11330.failed

The newly introduced variable is initialized in an #ifdef block
but used outside of it, leading to undefined behavior when
CONFIG_CIFS_ALLOW_INSECURE_LEGACY is disabled:

fs/smb/client/dir.c:417:9: error: variable 'sbflags' is uninitialized when used here [-Werror,-Wuninitialized]
  417 |                                 if (sbflags & CIFS_MOUNT_DYNPERM)
      |                                     ^~~~~~~

Move the initialization into the declaration, the same way as the
other similar function do it.

Fixes: 4fc3a433c139 ("smb: client: use atomic_t for mnt_cifs_flags")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Paulo Alcantara (Red Hat) <pc@manguebit.org>
	Signed-off-by: Steve French <stfrench@microsoft.com>
(cherry picked from commit fae11330dc0642065568d6c0045322293fe59bc6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	fs/smb/client/dir.c