perf tools: Handle PERF_RECORD_KSYMBOL
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Song Liu <songliubraving@fb.com>
commit 9aa0bfa370b278a539077002b3c660468d66b5e7

This patch handles PERF_RECORD_KSYMBOL in perf record/report.
Specifically, map and symbol are created for ksymbol register, and
removed for ksymbol unregister.

This patch also sets perf_event_attr.ksymbol properly. The flag is ON by
default.

Committer notes:

Use proper inttypes.h for u64, fixing the build in some environments
like in the android NDK r15c targetting ARM 32-bit.

I.e. fixing this build error:

  util/event.c: In function 'perf_event__fprintf_ksymbol':
  util/event.c:1489:10: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'u64' [-Werror=format=]
            event->ksymbol_event.flags, event->ksymbol_event.name);
            ^
  cc1: all warnings being treated as errors

	Signed-off-by: Song Liu <songliubraving@fb.com>
	Reviewed-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Alexei Starovoitov <ast@kernel.org>
	Cc: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: kernel-team@fb.com
	Cc: netdev@vger.kernel.org
Link: http://lkml.kernel.org/r/20190117161521.1341602-6-songliubraving@fb.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 9aa0bfa370b278a539077002b3c660468d66b5e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>