perf tools: Copy uapi/asm/perf_regs.h from the kernel for MIPS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Tiezhu Yang <yangtiezhu@loongson.cn>
commit 6c1ced2f701618e912be6c549139d58c180419ea

To allow the build to complete on older systems, where those files are
either not uptodate, lacking some recent additions or not present at
all.

And check if the copy drifts from the kernel.

This commit is similar with
commit 12f020338a2c ("tools: Copy uapi/asm/perf_regs.h from the kernel")

With this commit, we can avoid the following build error in any case:

tools/perf/arch/mips/include/perf_regs.h:7:10:
fatal error: asm/perf_regs.h: No such file or directory
 #include <asm/perf_regs.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

	Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Xuefeng Li <lixuefeng@loongson.cn>
Link: http://lore.kernel.org/lkml/1622548436-12472-1-git-send-email-yangtiezhu@loongson.cn
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 6c1ced2f701618e912be6c549139d58c180419ea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>