RDMA/iw_cxgb4: Fix the unchecked ep dereference
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Raju Rangoju <rajur@chelsio.com>
commit 3352976c892301fd576a2e9ff0ac7337b2e2ca48

The patch 944661dd97f4: "RDMA/iw_cxgb4: atomically lookup ep and get a
reference" from May 6, 2016, leads to the following Smatch complaint:

    drivers/infiniband/hw/cxgb4/cm.c:2953 terminate()
    error: we previously assumed 'ep' could be null (see line 2945)

Fixes: 944661dd97f4 ("RDMA/iw_cxgb4: atomically lookup ep and get a reference")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Raju Rangoju <rajur@chelsio.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 3352976c892301fd576a2e9ff0ac7337b2e2ca48)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>