RDMA/nldev: Add missing break in rdma_nl_notify_err_msg()
JIRA: https://issues.redhat.com/browse/RHEL-56245

commit 7acad3c442df6d5158c5b732a7a0ccf3a01d9b30
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Sep 16 06:24:34 2024 -0700

    RDMA/nldev: Add missing break in rdma_nl_notify_err_msg()

    Clang warns (or errors with CONFIG_WERROR=y):

      drivers/infiniband/core/nldev.c:2795:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
       2795 |         default:
            |         ^

    Clang is a little more pedantic than GCC, which does not warn when
    falling through to a case that is just break or return. Clang's version
    is more in line with the kernel's own stance in deprecated.rst, which
    states that all switch/case blocks must end in either break,
    fallthrough, continue, goto, or return. Add the missing break to silence
    the warning.

    Fixes: 9cbed5aab5ae ("RDMA/nldev: Add support for RDMA monitoring")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://patch.msgid.link/20240916-rdma-fix-clang-fallthrough-nl_notify_err_msg-v1-1-89de6a7423f1@kernel.org
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>