mm: shrinkers: add missing includes for undeclared types
JIRA: https://issues.redhat.com/browse/RHEL-48221
Conflicts:
    * minor context difference due to RHEL-only commit e7a279acd5cd
      ("kABI: Exclude memcg pointer from shrinker")

This patch is a backport of the following upstream commit:
commit b7217a0bbe00a98a8f4b15ebc2a8355a31a59e1e
Author: T.J. Mercier <tjmercier@google.com>
Date:   Mon Nov 14 23:59:49 2022 +0000

    mm: shrinkers: add missing includes for undeclared types

    The shrinker.h header depends on a user including other headers before it
    for types used by shrinker.h.  Fix this by including the appropriate
    headers in shrinker.h.

    ./include/linux/shrinker.h:13:9: error: unknown type name `gfp_t'
       13 |         gfp_t gfp_mask;
          |         ^~~~~
    ./include/linux/shrinker.h:71:26: error: field `list' has incomplete type
       71 |         struct list_head list;
          |                          ^~~~
    ./include/linux/shrinker.h:82:9: error: unknown type name `atomic_long_t'
       82 |         atomic_long_t *nr_deferred;
          |

    Link: https://lkml.kernel.org/r/20221114235949.201749-1-tjmercier@google.com
    Fixes: 83aeeada7c69 ("vmscan: use atomic-long for shrinker batching")
    Fixes: b0d40c92adaf ("superblock: introduce per-sb cache shrinker infrastructure")
    Signed-off-by: T.J. Mercier <tjmercier@google.com>
    Cc: Al Viro <viro@zeniv.linux.org.uk>
    Cc: Dave Chinner <dchinner@redhat.com>
    Cc: Konstantin Khlebnikov <khlebnikov@openvz.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>