fbdev: Fix recursive dependencies wrt BACKLIGHT_CLASS_DEVICE
JIRA: https://issues.redhat.com/browse/RHEL-75959
Upstream Status: v6.13-rc4

commit 8fc38062be3f692ff8816da84fde71972530bcc4
Author:     Thomas Zimmermann <tzimmermann@suse.de>
AuthorDate: Mon Dec 16 08:42:47 2024 +0100
Commit:     Thomas Zimmermann <tzimmermann@suse.de>
CommitDate: Tue Dec 17 18:06:10 2024 +0100

    Do not select BACKLIGHT_CLASS_DEVICE from FB_BACKLIGHT. The latter
    only controls backlight support within fbdev core code and data
    structures.

    Make fbdev drivers depend on BACKLIGHT_CLASS_DEVICE and let users
    select it explicitly. Fixes warnings about recursive dependencies,
    such as

    error: recursive dependency detected!
    	symbol BACKLIGHT_CLASS_DEVICE is selected by FB_BACKLIGHT
    	symbol FB_BACKLIGHT is selected by FB_SH_MOBILE_LCDC
    	symbol FB_SH_MOBILE_LCDC depends on FB_DEVICE
    	symbol FB_DEVICE depends on FB_CORE
    	symbol FB_CORE is selected by DRM_GEM_DMA_HELPER
    	symbol DRM_GEM_DMA_HELPER is selected by DRM_PANEL_ILITEK_ILI9341
    	symbol DRM_PANEL_ILITEK_ILI9341 depends on BACKLIGHT_CLASS_DEVICE

    BACKLIGHT_CLASS_DEVICE is user-selectable, so making drivers adapt to
    it is the correct approach in any case. For most drivers, backlight
    support is also configurable separately.

    v3:
    - Select BACKLIGHT_CLASS_DEVICE in PowerMac defconfigs (Christophe)
    - Fix PMAC_BACKLIGHT module dependency corner cases (Christophe)
    v2:
    - s/BACKLIGHT_DEVICE_CLASS/BACKLIGHT_CLASS_DEVICE (Helge)
    - Fix fbdev driver-dependency corner case (Arnd)

    Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241216074450.8590-2-tzimmermann@suse.de

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>