ASoC: SOF: Intel: select SND_SOC_SDW_UTILS=y from SND_SOC_SOF_HDA_GENERIC=y
JIRA: https://issues.redhat.com/browse/RHEL-193253

commit 67805f57e5b1a8589f89bd48936c65cbbaeec300
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Jun 11 15:23:05 2026 +0200

    ASoC: SOF: Intel: select SND_SOC_SDW_UTILS=y from SND_SOC_SOF_HDA_GENERIC=y

    When SND_SOC_SOF_HDA_GENERIC=y but SND_SOC_SOF_INTEL_SOUNDWIRE=m, the
    SND_SOC_SDW_UTILS is also set to =m even though there is a direct link
    dependency from the hda.c:

    aarch64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_machine_select':
    hda.c:(.text+0x21ac): undefined reference to `codec_info_list'
    hda.c:(.text+0x241c): undefined reference to `asoc_sdw_get_dai_type'
    hda.c:(.text+0x25b4): undefined reference to `asoc_sdw_get_codec_info_list_count'
    hda.c:(.text+0x25d8): undefined reference to `asoc_sdw_get_codec_info_list_count'

    Change this the same way as the other related 'select' statements
    to allow linking against it.

    Fixes: 2b4d53eb5cf3 ("ASoC: SOF: Intel: select SND_SOC_SDW_UTILS in SND_SOC_SOF_HDA_GENERIC")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Tested-by: Julian Braha <julianbraha@gmail.com>
    Link: https://patch.msgid.link/20260611132310.137688-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>