x86/vdso: Include vdso/processor.h
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 3e0bd4dd35406a130de02c1660e32f6c40121d35
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:45 2023 +0200

    x86/vdso: Include vdso/processor.h

    __vdso_getcpu is declared in a header but this is not included
    before the definition, causing a W=1 warning:

    arch/x86/entry/vdso/vgetcpu.c:13:1: error: no previous prototype for '__vdso_getcpu' [-Werror=missing-prototypes]
    arch/x86/entry/vdso/vdso32/../vgetcpu.c:13:1: error: no previous prototype for '__vdso_getcpu' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-17-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>