PCI: Stub __pci_ioport_map() for arches that don't support it at all
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2124638
Upstream Status: 933c5a4f87d92a865d1db76caf190f1a4a1927f9

commit 933c5a4f87d92a865d1db76caf190f1a4a1927f9
Author: Stafford Horne <shorne@gmail.com>
Date:   Sat Jul 23 06:22:48 2022 +0900

    PCI: Stub __pci_ioport_map() for arches that don't support it at all

    When building OpenRISC PCI, which has no ioport_map(), we get the following
    build error:

      lib/pci_iomap.c: In function 'pci_iomap_range':
        CC      drivers/i2c/i2c-core-base.o
      ./include/asm-generic/pci_iomap.h:29:41: error: implicit declaration of function 'ioport_map'; did you mean 'ioremap'? [-Werror=implicit-function-declaration]
         29 | #define __pci_ioport_map(dev, port, nr) ioport_map((port), (nr))
            |                                         ^~~~~~~~~~
      lib/pci_iomap.c:44:24: note: in expansion of macro '__pci_ioport_map'
         44 |                 return __pci_ioport_map(dev, start, len);
            |                        ^~~~~~~~~~~~~~~~

    Add a NULL definition of __pci_ioport_map() for architectures that do not
    support ioport_map().

    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20220722212248.802500-1-shorne@gmail.com
    Signed-off-by: Stafford Horne <shorne@gmail.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>