idpf: avoid compiler padding in virtchnl2_ptype struct
JIRA: https://issues.redhat.com/browse/RHEL-29553

commit f0588b157f48b9c6277a75c9f14650e86d969e03
Author: Pavan Kumar Linga <pavan.kumar.linga@intel.com>
Date:   Wed Jan 31 14:22:40 2024 -0800

    idpf: avoid compiler padding in virtchnl2_ptype struct

    In the arm random config file, kconfig option 'CONFIG_AEABI' is
    disabled which results in adding the compiler flag '-mabi=apcs-gnu'.
    This causes the compiler to add padding in virtchnl2_ptype
    structure to align it to 8 bytes, resulting in the following
    size check failure:

    include/linux/build_bug.h:78:41: error: static assertion failed: "(6) == sizeof(struct virtchnl2_ptype)"
          78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
             |                                         ^~~~~~~~~~~~~~
    include/linux/build_bug.h:77:34: note: in expansion of macro '__static_assert'
          77 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
             |                                  ^~~~~~~~~~~~~~~
    drivers/net/ethernet/intel/idpf/virtchnl2.h:26:9: note: in expansion of macro 'static_assert'
          26 |         static_assert((n) == sizeof(struct X))
             |         ^~~~~~~~~~~~~
    drivers/net/ethernet/intel/idpf/virtchnl2.h:982:1: note: in expansion of macro 'VIRTCHNL2_CHECK_STRUCT_LEN'
         982 | VIRTCHNL2_CHECK_STRUCT_LEN(6, virtchnl2_ptype);
             | ^~~~~~~~~~~~~~~~~~~~~~~~~~

    Avoid the compiler padding by using "__packed" structure
    attribute for the virtchnl2_ptype struct. Also align the
    structure by using "__aligned(2)" for better code optimization.

    Fixes: 0d7502a9b4a7 ("virtchnl: add virtchnl version 2 ops")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202312220250.ufEm8doQ-lkp@intel.com
    Reviewed-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Reviewed-by: Paul Menzel <pmenzel@molgen.mpg.de>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Signed-off-by: Pavan Kumar Linga <pavan.kumar.linga@intel.com>
    Tested-by: Krishneil Singh  <krishneil.k.singh@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
    Link: https://lore.kernel.org/r/20240131222241.2087516-1-anthony.l.nguyen@intel.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>