perf tools: Add missing headers needed by util/data.h
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit 4d27cf1d9de5becfa4d1efb2ea54dba1b9fc962a
Author: Yang Jihong <yangjihong1@huawei.com>
Date: Fri Apr 29 17:05:39 2022 +0800

description
===========
'struct perf_data' in util/data.h uses the "u64" data type, which is
defined in "linux/types.h".

If we only include util/data.h, the following compilation error occurs:

  util/data.h:38:3: error: unknown type name ‘u64’
     u64    version;
     ^~~

Solution: include "linux/types.h." to add the needed type definitions.

Fixes: 258031c017c353e8 ("perf header: Add DIR_FORMAT feature to describe directory data")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>