net: ieee802154: Fix compilation error when CONFIG_IEEE802154_NL802154_EXPERIMENTAL is disabled
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2175249

commit 8254393663f9b8cb8b84cdce1abb118833c22a54
Author: Gal Pressman <gal@nvidia.com>
Date:   Thu Sep 1 20:06:20 2022 -0700

    net: ieee802154: Fix compilation error when CONFIG_IEEE802154_NL802154_EXPERIMENTAL is disabled

    When CONFIG_IEEE802154_NL802154_EXPERIMENTAL is disabled,
    NL802154_CMD_DEL_SEC_LEVEL is undefined and results in a compilation
    error:
    net/ieee802154/nl802154.c:2503:19: error: 'NL802154_CMD_DEL_SEC_LEVEL' undeclared here (not in a function); did you mean 'NL802154_CMD_SET_CCA_ED_LEVEL'?
     2503 |  .resv_start_op = NL802154_CMD_DEL_SEC_LEVEL + 1,
          |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
          |                   NL802154_CMD_SET_CCA_ED_LEVEL

    Unhide the experimental commands, having them defined in an enum
    makes no difference.

    Fixes: 9c5d03d36251 ("genetlink: start to validate reserved header bytes")
    Signed-off-by: Gal Pressman <gal@nvidia.com>
    Acked-by: Stefan Schmidt <stefan@datenfreihafen.org>
    Tested-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
    Link: https://lore.kernel.org/r/20220902030620.2737091-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>