selftests/bpf: Fix a btf_dump selftest failure
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 3d650ab5e7d9c4d7306e4c116f8aa9980bf13295
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Fri Aug 2 11:54:34 2024 -0700

    selftests/bpf: Fix a btf_dump selftest failure

    Jakub reported bpf selftest "btf_dump" failure after forwarding to
    v6.11-rc1 with netdev.
      Error: #33 btf_dump
      Error: #33/15 btf_dump/btf_dump: var_data
        btf_dump_data:FAIL:find type id unexpected find type id: actual -2 < expected 0

    The reason for the failure is due to
      commit 94ede2a3e913 ("profiling: remove stale percpu flip buffer variables")
    where percpu static variable "cpu_profile_flip" is removed.

    Let us replace "cpu_profile_flip" with a variable in bpf subsystem
    so whenever that variable gets deleted or renamed, we can detect the
    failure immediately. In this case, I picked a static percpu variable
    "bpf_cgrp_storage_busy" which is defined in kernel/bpf/bpf_cgrp_storage.c.

    Reported-by: Jakub Kicinski <kuba@kernel.org>
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20240802185434.1749056-1-yonghong.song@linux.dev

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>