device-dax: Tell kbuild DEV_DAX_PMEM depends on DEV_DAX
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Mike Galbraith <efault@gmx.de>
commit 74d71a01abef37f71d914f2105a4cb8712a2beb8

ERROR: "devm_create_dev_dax" [drivers/dax/dax_pmem.ko] undefined!
ERROR: "alloc_dax_region" [drivers/dax/dax_pmem.ko] undefined!
ERROR: "dax_region_put" [drivers/dax/dax_pmem.ko] undefined!

	Signed-off-by: Mike Galbraith <efault@gmx.de>
	Signed-off-by: Dan Williams <dan.j.williams@intel.com>
(cherry picked from commit 74d71a01abef37f71d914f2105a4cb8712a2beb8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>