ACPI: require CRC32 to build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 04662bac0067e2fd7f243d6abaa4d779bce14114

ACPI core now requires crc32() but the kernel build can fail when
CRC32 is not set/enabled, so select it in the ACPI Kconfig entry.

Fixes this build error:

ia64-linux-ld: drivers/acpi/scan.o: in function `acpi_store_pld_crc':
include/acpi/platform/aclinuxex.h:62: undefined reference to `crc32_le'

Fixes: 882c982dada4 ("acpi: Store CRC-32 hash of the _PLD in struct acpi_device")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Reported-by: Guenter Roeck <linux@roeck-us.net>
	Reviewed-by: Guenter Roeck <linux@roeck-us.net>
	Tested-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 04662bac0067e2fd7f243d6abaa4d779bce14114)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>