ASoC: amd: vangogh: select CONFIG_SND_AMD_ACP_CONFIG
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit fd0a7ec379dbf21b7bfd81914381ae5281706ef5
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Jun 5 10:58:29 2023 +0200

    ASoC: amd: vangogh: select CONFIG_SND_AMD_ACP_CONFIG

    The vangogh driver just gained a link time dependency that now causes
    randconfig builds to fail:

    x86_64-linux-ld: sound/soc/amd/vangogh/pci-acp5x.o: in function `snd_acp5x_probe':
    pci-acp5x.c:(.text+0xbb): undefined reference to `snd_amd_acp_find_config'

    Fixes: e89f45edb747e ("ASoC: amd: vangogh: Add check for acp config flags in vangogh platform")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230605085839.2157268-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>