PCI: Remove unused attr variable in pci_dma_configure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 664204410afb3b0f538d176ad0c2713b04abd4b9

Clang warns:

drivers/pci/pci-driver.c:1603:21: error: unused variable 'attr'
[-Werror,-Wunused-variable]

Commit e5361ca29f2f ("ACPI / scan: Refactor _CCA enforcement") removed
attr's use and replaced it with its assigned value so it is no longer
needed.

	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit 664204410afb3b0f538d176ad0c2713b04abd4b9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>