dpll: zl3073x: Increase maximum size of flash utility
JIRA: https://issues.redhat.com/browse/RHEL-138352

commit f3426ac54c42c3260096ddc50b5470eb179fb06a
Author: Ivan Vecera <ivecera@redhat.com>
Date:   Wed Oct 8 16:14:18 2025 +0200

    dpll: zl3073x: Increase maximum size of flash utility

    Newer firmware bundles contain a flash utility whose size exceeds
    the currently allowed limit. Increase the maximum allowed size
    to accommodate the newer utility version.

    Without this patch:
     # devlink dev flash i2c/1-0070 file fw_nosplit_v3.hex
     Failed to load firmware
     Flashing failed
     Error: zl3073x: FW load failed: [utility] component is too big (11000 bytes)

    Fixes: ca017409da694 ("dpll: zl3073x: Add firmware loading functionality")
    Suggested-by: Prathosh Satish <Prathosh.Satish@microchip.com>
    Signed-off-by: Ivan Vecera <ivecera@redhat.com>
    Reviewed-by: Vadim Fedorenko <vadim.fedorenko@linux.dev>
    Link: https://patch.msgid.link/20251008141418.841053-1-ivecera@redhat.com
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>