perf tools: Free 'printk' string in parse_ftrace_printk()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Sanskriti Sharma <sansharm@redhat.com>
commit 9c8a182e5a73e01afd11742a2ab887bf338fdafd
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1062.el7/9c8a182e.failed

parse_ftrace_printk() tokenizes and parses a line, calling strdup() each
iteration.  Add code to free this temporary format string duplicate.

Fixes the following coverity complaints:

  Error: RESOURCE_LEAK (CWE-772):
  tools/perf/util/trace-event-parse.c:158: overwrite_var: Overwriting
  "printk" in "printk = strdup(fmt + 1)" leaks the storage that "printk"
  points to.

  tools/perf/util/trace-event-parse.c:162: leaked_storage: Variable
  "printk" going out of scope leaks the storage it points to.

	Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
	Reviewed-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Joe Lawrence <joe.lawrence@redhat.com>
Link: http://lkml.kernel.org/r/1538490554-8161-4-git-send-email-sansharm@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 9c8a182e5a73e01afd11742a2ab887bf338fdafd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/perf/util/trace-event-parse.c