selftests/bpf: Fix compilation errors: Assign a value to a constant
Bugzilla: https://bugzilla.redhat.com/2221599

commit 11e456cae91e9044cb12c2b037b52c9b268925f7
Author: Rong Tao <rongtao@cestc.cn>
Date:   Fri Feb 24 23:10:02 2023 +0800

    selftests/bpf: Fix compilation errors: Assign a value to a constant
    
    Commit bc292ab00f6c("mm: introduce vma->vm_flags wrapper functions")
    turns the vm_flags into a const variable.
    
    Added bpf_find_vma test in commit f108662b27c9("selftests/bpf: Add tests
    for bpf_find_vma") to assign values to variables that declare const in
    find_vma_fail1.c programs, which is an error to the compiler and does not
    test BPF verifiers. It is better to replace 'const vm_flags_t vm_flags'
    with 'unsigned long vm_start' for testing.
    
        $ make -C tools/testing/selftests/bpf/ -j8
        ...
        progs/find_vma_fail1.c:16:16: error: cannot assign to non-static data
        member 'vm_flags' with const-qualified type 'const vm_flags_t' (aka
        'const unsigned long')
                vma->vm_flags |= 0x55;
                ~~~~~~~~~~~~~ ^
        ../tools/testing/selftests/bpf/tools/include/vmlinux.h:1898:20:
        note: non-static data member 'vm_flags' declared const here
                        const vm_flags_t vm_flags;
                        ~~~~~~~~~~~`~~~~~~^~~~~~~~
    
    Signed-off-by: Rong Tao <rongtao@cestc.cn>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/tencent_CB281722B3C1BD504C16CDE586CACC2BE706@qq.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>