powerpc/eeh: Fix build with STACKTRACE=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [powerpc] eeh: Fix build with STACKTRACE=n (Gustavo Duarte) [1524642]
Rebuild_FUZZ: 88.89%
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit 1b7f3b6c43675ef2cfb9d8f48bde057794820f7c
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-193.el8/1b7f3b6c.failed

The build breaks when STACKTRACE=n, eg. skiroot_defconfig:

  arch/powerpc/kernel/eeh_event.c:124:23: error: implicit declaration of function 'stack_trace_save'

Fix it with some ifdefs for now.

Fixes: 25baf3d81614 ("powerpc/eeh: Defer printing stack trace")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 1b7f3b6c43675ef2cfb9d8f48bde057794820f7c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/include/asm/eeh.h
#	arch/powerpc/kernel/eeh_driver.c
#	arch/powerpc/kernel/eeh_event.c