sched: Make task_vruntime_update() prototype visible
JIRA: https://issues.redhat.com/browse/RHEL-1536

commit f7df852ad6dbb84644e75df7402d9a34f39f31bd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon May 22 21:50:20 2023 +0200

    sched: Make task_vruntime_update() prototype visible

    Having the prototype next to the caller but not visible to the callee causes
    a W=1 warning:

    kernel/sched/fair.c:11985:6: error: no previous prototype for 'task_vruntime_update' [-Werror=missing-prototypes]

    Move this to a header, as we do for all other function declarations.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Vincent Guittot <vincent.guittot@linaro.org>
    Link: https://lore.kernel.org/r/20230522195021.3456768-5-arnd@kernel.org

Signed-off-by: Phil Auld <pauld@redhat.com>