scsi: ufs: qcom: fix platform_msi_domain_free_irqs() reference
Bugzilla: https://bugzilla.redhat.com/2185234

commit 49f262bc3c7ab90bdb3491a659b28c0b397d52e8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jan 26 22:17:31 2023 +0100

    scsi: ufs: qcom: fix platform_msi_domain_free_irqs() reference

    The newly added MSI support is mostly hidden inside of an #ifdef,
    except for one line that now causes a build failure when MSI
    is disabled:

    drivers/ufs/host/ufs-qcom.c: In function 'ufs_qcom_remove':
    drivers/ufs/host/ufs-qcom.c:1698:9: error: implicit declaration of function 'platform_msi_domain_free_irqs' [-Werror=i]
     1698 |         platform_msi_domain_free_irqs(hba->dev);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Above that, the symbol that guards the other call was recently removed, so
    that is all dead code at the moment.

    Remove the incorrect #ifdef and instead of a Kconfig dependency to only
    allow building the driver when CONFIG_GENERIC_MSI_IRQ is enabled. This
    symbol is always present when PCI_MSI or ARM_GIC_V3_ITS are enabled, both
    of which should be present on kernels that can run on Qualcomm SoCs.

    The 'select RESET_CONTROLLER' in combination with this dependency
    unfortunately causes a dependency loop and this is a user-visible symbol,
    so it's better to change both to 'depends on'.

    Link: https://lore.kernel.org/r/20230126211831.2274211-1-arnd@kernel.org
    Fixes: 519b6274a777 ("scsi: ufs: qcom: Add MCQ ESI config vendor specific ops")
    Fixes: 13e7accb81d6 ("genirq: Get rid of GENERIC_MSI_IRQ_DOMAIN")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Manivannan Sadhasivam <mani@kernel.org>
    Acked-by: Can Guo <quic_cang@quicinc.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>