ALSA: asihpi: remove unused loop_count variable
Bugzilla: https://bugzilla.redhat.com/2179848

commit 84f02f3363382d45b8ab75361f7d69beb8f27f32
Author: Tom Rix <trix@redhat.com>
Date: Sun Mar 26 16:57:12 2023 -0400

    ALSA: asihpi: remove unused loop_count variable

    clang with W=1 reports
    sound/pci/asihpi/hpi6000.c:1256:6: error: variable
      'loop_count' set but not used [-Werror,-Wunused-but-set-variable]
            u32 loop_count = 0;
                ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230326205712.1358918-1-trix@redhat.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>