samples/bpf: Fix tracex2 error: No such file or directory
Bugzilla: https://bugzilla.redhat.com/2177177

commit 1baa7e38002111aee62b489ac343960ae75ce2e9
Author: Rong Tao <rongtao@cestc.cn>
Date:   Sat Oct 29 17:11:13 2022 +0800

    samples/bpf: Fix tracex2 error: No such file or directory

    since commit c504e5c2f964("net: skb: introduce kfree_skb_reason()")
    kfree_skb() is replaced by kfree_skb_reason() and kfree_skb() is set to
    the inline function. So, we replace kprobe/kfree_skb with
    kprobe/kfree_skb_reason to solve the tracex2 error.

     $ cd samples/bpf
     $ sudo ./tracex2
     libbpf: prog 'bpf_prog2': failed to create kprobe 'kfree_skb+0x0' perf event: No such file or directory
     ERROR: bpf_program__attach failed

    Signed-off-by: Rong Tao <rongtao@cestc.cn>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/tencent_0F0DAE84C0B3C42E0B550E5E9F47A9114D09@qq.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>