rbd: silence bogus uninitialized use warning in rbd_acquire_lock()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Kefeng Wang <wangkefeng.wang@huawei.com>
commit 37f13252579389a659ae3ceec8c60f15bdf70f0c

  drivers/block/rbd.c: In function 'rbd_acquire_lock':
  drivers/block/rbd.c:3602:44: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Silence the warning, found it when built old kernel(3.10) with
OBS(opensuse build service).

	Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
	Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit 37f13252579389a659ae3ceec8c60f15bdf70f0c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>