usb: gadget: fsl: fix link error against usb-gadget module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 2100e3ca3676e894fa48b8f6f01d01733387fe81

The dependency to ensure this driver links correctly fails since
it can not be a loadable module:

drivers/usb/phy/phy-fsl-usb.o: In function `fsl_otg_set_peripheral':
phy-fsl-usb.c:(.text+0x2224): undefined reference to `usb_gadget_vbus_disconnect'

Make the option 'tristate' so it can work correctly.

Fixes: 5a8d651a2bde ("usb: gadget: move gadget API functions to udc-core")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>
(cherry picked from commit 2100e3ca3676e894fa48b8f6f01d01733387fe81)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>