wifi: ray_cs: Replace 1-element array with flexible array
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 1d7dd5aa35474e553b8671b58579e0749b560779
Author: Kees Cook <keescook@chromium.org>
Date:   Fri Jul 28 16:13:02 2023 -0700

    wifi: ray_cs: Replace 1-element array with flexible array
    
    The trailing array member of struct tx_buf was defined as a 1-element
    array, but used as a flexible array. This was resulting in build warnings:
    
        In function 'fortify_memset_chk',
            inlined from 'memset_io' at /kisskb/src/arch/mips/include/asm/io.h:486:2,
            inlined from 'build_auth_frame' at /kisskb/src/drivers/net/wireless/legacy/ray_cs.c:2697:2:
        /kisskb/src/include/linux/fortify-string.h:493:25: error: call to '__write_overflow_field' declared with attribute warning:
    detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
          493 |                         __write_overflow_field(p_size_field, size);
              |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Replace it with an actual flexible array. Binary difference comparison
    shows a single change in output:
    
    │  drivers/net/wireless/legacy/ray_cs.c:883
    │       lea    0x1c(%rbp),%r13d
    │ -     cmp    $0x7c3,%r13d
    │ +     cmp    $0x7c4,%r13d
    
    This is from:
    
            if (len + TX_HEADER_LENGTH > TX_BUF_SIZE) {
    
    specifically:
    
     #define TX_BUF_SIZE (2048 - sizeof(struct tx_msg))
    
    This appears to have been originally buggy, so the change is correct.
    
    Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Closes: https://lore.kernel.org/all/88f83d73-781d-bdc-126-aa629cb368c@linux-m68k.org
    Cc: Kalle Valo <kvalo@kernel.org>
    Cc: linux-wireless@vger.kernel.org
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230728231245.never.309-kees@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>