tracing: fprobe: Initialize ret valiable to fix smatch error
JIRA: https://issues.redhat.com/browse/RHEL-64700

Conflicts: 3cc4e2c5fbae ("fprobe: make fprobe_kprobe_handler recursion free")
           was previously backported out-of-order

commit 6049674b5720edbbb13a7cb3e2f3d2affaa40c19
Author: Masami Hiramatsu (Google) <mhiramat@kernel.org>
Date:   Sun Apr 9 11:28:31 2023 +0900

    tracing: fprobe: Initialize ret valiable to fix smatch error

    The commit 39d954200bf6 ("fprobe: Skip exit_handler if entry_handler returns
    !0") introduced a hidden dependency of 'ret' local variable in the
    fprobe_handler(), Smatch warns the `ret` can be accessed without
    initialization.

            kernel/trace/fprobe.c:59 fprobe_handler()
            error: uninitialized symbol 'ret'.

    kernel/trace/fprobe.c
        49                 fpr->entry_ip = ip;
        50                 if (fp->entry_data_size)
        51                         entry_data = fpr->data;
        52         }
        53
        54         if (fp->entry_handler)
        55                 ret = fp->entry_handler(fp, ip, ftrace_get_regs(fregs), entry_data);

    ret is only initialized if there is an ->entry_handler

        56
        57         /* If entry_handler returns !0, nmissed is not counted. */
        58         if (rh) {

    rh is only true if there is an ->exit_handler.  Presumably if you have
    and ->exit_handler that means you also have a ->entry_handler but Smatch
    is not smart enough to figure it out.

    --> 59                 if (ret)
                               ^^^
    Warning here.

        60                         rethook_recycle(rh);
        61                 else
        62                         rethook_hook(rh, ftrace_get_regs(fregs), true);
        63         }
        64 out:
        65         ftrace_test_recursion_unlock(bit);
        66 }

    Link: https://lore.kernel.org/all/168100731160.79534.374827110083836722.stgit@devnote2/

    Reported-by: Dan Carpenter <error27@gmail.com>
    Link: https://lore.kernel.org/all/85429a5c-a4b9-499e-b6c0-cbd313291c49@kili.mountain
    Fixes: 39d954200bf6 ("fprobe: Skip exit_handler if entry_handler returns !0")
    Acked-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>