x86/KASLR: Use the right memcpy() implementation
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [x86] kaslr: Use the right memcpy() implementation (Baoquan He) [1440928]
Rebuild_FUZZ: 95.65%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5b8b9cf76add98e19ff8ceb4247c2920687591a0
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-693.el7/5b8b9cf7.failed

The decompressor has its own implementation of the string functions,
but has to include the right header to get those, while implicitly
including linux/string.h may result in a link error:

  arch/x86/boot/compressed/kaslr.o: In function `choose_random_location':
  kaslr.c:(.text+0xf51): undefined reference to `_mmx_memcpy'

This has appeared now as KASLR started using memcpy(), via:

	d52e7d5a952c ("x86/KASLR: Parse all 'memmap=' boot option entries")

Other files in the decompressor already do the same thing.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Baoquan He <bhe@redhat.com>
	Cc: Dave Jiang <dave.jiang@intel.com>
	Cc: Kees Cook <keescook@chromium.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Thomas Garnier <thgarnie@google.com>
	Cc: Thomas Gleixner <tglx@linutronix.de>
Link: http://lkml.kernel.org/r/20170530091446.1000183-1-arnd@arndb.de
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 5b8b9cf76add98e19ff8ceb4247c2920687591a0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/x86/boot/compressed/kaslr.c