sh: mach-x3proto: Add missing #include <linux/gpio/driver.h>
Bugzilla: https://bugzilla.redhat.com/2183344

commit d94ffb99a379a6307af99b6f59b08ec3d58eb958
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Thu Mar 9 15:41:13 2023 +0100

    sh: mach-x3proto: Add missing #include <linux/gpio/driver.h>

    shx3_defconfig:

        arch/sh/boards/mach-x3proto/setup.c: In function ‘x3proto_devices_setup’:
        arch/sh/boards/mach-x3proto/setup.c:246:62: error: invalid use of undefined type ‘struct gpio_chip’
          246 |                 baseboard_buttons[i].gpio = x3proto_gpio_chip.base + i;
              |                                                              ^

    Fix this by replacing the include of the legacy <linux/gpio.h> by
    <linux/gpio/driver.h>.

    Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
    Link: https://lore.kernel.org/r/CA+G9fYs7suzGsEDK40G0pzxXyR1o2V4Pn-oy1owTsTWRVEVHog@mail.gmail.com
    Fixes: 21d9526d13b5467b ("gpiolib: Make the legacy <linux/gpio.h> consumer-only")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Reviewed-by: Linus Walleij <linus.walleij@linaro.org>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>

Signed-off-by: Shaoqin Huang <shahuang@redhat.com>