arm64: mark (__)cpus_have_const_cap as __always_inline
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [arm64] mark (__)cpus_have_const_cap as __always_inline (Auger Eric) [1882794]
Rebuild_FUZZ: 93.07%
commit-author Masahiro Yamada <yamada.masahiro@socionext.com>
commit 02166b88d376f21ea5caac26e7e8f74ab5578986

This prepares to move CONFIG_OPTIMIZE_INLINING from x86 to a common
place.  We need to eliminate potential issues beforehand.

If it is enabled for arm64, the following errors are reported:

  In file included from include/linux/compiler_types.h:68,
                   from <command-line>:
  arch/arm64/include/asm/jump_label.h: In function 'cpus_have_const_cap':
  include/linux/compiler-gcc.h:120:38: warning: asm operand 0 probably doesn't match constraints
   #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                        ^~~
  arch/arm64/include/asm/jump_label.h:32:2: note: in expansion of macro 'asm_volatile_goto'
    asm_volatile_goto(
    ^~~~~~~~~~~~~~~~~
  include/linux/compiler-gcc.h:120:38: error: impossible constraint in 'asm'
   #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                        ^~~
  arch/arm64/include/asm/jump_label.h:32:2: note: in expansion of macro 'asm_volatile_goto'
    asm_volatile_goto(
    ^~~~~~~~~~~~~~~~~

Link: http://lkml.kernel.org/r/20190423034959.13525-3-yamada.masahiro@socionext.com
	Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
	Tested-by: Mark Rutland <mark.rutland@arm.com>
	Cc: Arnd Bergmann <arnd@arndb.de>
	Cc: Benjamin Herrenschmidt <benh@kernel.crashing.org>
	Cc: Boris Brezillon <bbrezillon@kernel.org>
	Cc: Borislav Petkov <bp@suse.de>
	Cc: Brian Norris <computersforpeace@gmail.com>
	Cc: Christophe Leroy <christophe.leroy@c-s.fr>
	Cc: David Woodhouse <dwmw2@infradead.org>
	Cc: Heiko Carstens <heiko.carstens@de.ibm.com>
	Cc: "H. Peter Anvin" <hpa@zytor.com>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Marek Vasut <marek.vasut@gmail.com>
	Cc: Mathieu Malaterre <malat@debian.org>
	Cc: Miquel Raynal <miquel.raynal@bootlin.com>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Ralf Baechle <ralf@linux-mips.org>
	Cc: Richard Weinberger <richard@nod.at>
	Cc: Russell King <rmk+kernel@arm.linux.org.uk>
	Cc: Stefan Agner <stefan@agner.ch>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 02166b88d376f21ea5caac26e7e8f74ab5578986)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>