firmware: arm_ffa: Remove unused 'compat_version' variable
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071830
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2071840
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  At this stage, this
 has been tested by ensuring we can survive the CI/CD loop -- i.e.,
 that we have not broken anything else, and a simple boot test.  When
 sufficient drivers have been brought in for i.MX8M, we will be able
 to run further tests.

commit 01537a078b86917c7bb69aa4b756b42b980c158b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 26 10:33:50 2021 +0200

    firmware: arm_ffa: Remove unused 'compat_version' variable

    The newly added ffa_compatible_version_find() function causes a
    build warning because of a variable that is never used:

    drivers/firmware/arm_ffa/driver.c:180:6: error: unused variable 'compat_version' [-Werror,-Wunused-variable]
            u32 compat_version;

    Link: https://lore.kernel.org/r/20211026083400.3444946-1-arnd@kernel.org
    Fixes: 8e3f9da608f1 ("firmware: arm_ffa: Handle compatibility with different firmware versions")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
    (cherry picked from commit 01537a078b86917c7bb69aa4b756b42b980c158b)

Signed-off-by: Al Stone <ahs3@redhat.com>