wifi: brcmfmac: add missing header include for brcmf_dbg
JIRA: https://issues.redhat.com/browse/RHEL-79791

commit b05d30c2b6df7e2172b18bf1baee9b202f9c6b53
Author: Marcel Hamer <marcel.hamer@windriver.com>
Date:   Wed Dec 11 14:36:18 2024 +0100

    wifi: brcmfmac: add missing header include for brcmf_dbg
    
    Including the fwil.h header file can lead to a build error:
    
    drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwil.h: \
            In function ‘brcmf_fil_cmd_int_set’:
    drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwil.h:90:9: error: implicit \
            declaration of function ‘brcmf_dbg’ [-Werror=implicit-function-declaration]
       90 |         brcmf_dbg(FIL, "ifidx=%d, cmd=%d, value=%d\n", ifp->ifidx, cmd, data);
          |         ^~~~~~~~~
    
    The error is often avoided because the debug.h header file is included
    before the fwil.h header file.
    
    This makes sure the header include order is irrelevant by explicitly adding the
    debug.h header.
    
    Fixes: 31343230abb1 ("wifi: brcmfmac: export firmware interface functions")
    Signed-off-by: Marcel Hamer <marcel.hamer@windriver.com>
    Acked-by: Arend van Spriel <arend.vanspriel@broadcom.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://patch.msgid.link/20241211133618.2014083-1-marcel.hamer@windriver.com

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>