vhost-vdpa: print warning when vhost_vdpa_alloc_domain fails
JIRA: https://issues.redhat.com/browse/RHEL-806

commit 6830a6aba9d40f1491f991d7b31bb2b90187111c
Author: Alvaro Karsz <alvaro.karsz@solid-run.com>
Date:   Thu Feb 2 10:42:12 2023 +0200

    vhost-vdpa: print warning when vhost_vdpa_alloc_domain fails

    Add a print explaining why vhost_vdpa_alloc_domain failed if the device
    is not IOMMU cache coherent capable.

    Without this print, we have no hint why the operation failed.

    For example:

    $ virsh start <domain>
            error: Failed to start domain <domain>
            error: Unable to open '/dev/vhost-vdpa-<idx>' for vdpa device:
                   Unknown error 524

    Suggested-by: Eugenio Perez Martin <eperezma@redhat.com>
    Signed-off-by: Alvaro Karsz <alvaro.karsz@solid-run.com>

    Message-Id: <20230202084212.1328530-1-alvaro.karsz@solid-run.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
    Acked-by: Eugenio Pérez Martin <eperezma@redhat.com>

Signed-off-by: Laurent Vivier <lvivier@redhat.com>