bridge: Allow deleting FDB entries with non-existent VLAN
JIRA: https://issues.redhat.com/browse/RHEL-75594

Conflict:
 A conflict occurs due to code differences because patch 42575ad5aab9
 ("ndo_fdb_del: Add a parameter to report whether notification was sent")
 was applied before this patch.

commit 774ca6d3bf24287ff60b7d6dd4171ebb6e47760a
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Tue Nov 5 15:39:54 2024 +0200

    bridge: Allow deleting FDB entries with non-existent VLAN

    It is currently impossible to delete individual FDB entries (as opposed
    to flushing) that were added with a VLAN that no longer exists:

     # ip link add name dummy1 up type dummy
     # ip link add name br1 up type bridge vlan_filtering 1
     # ip link set dev dummy1 master br1
     # bridge fdb add 00:11:22:33:44:55 dev dummy1 master static vlan 1
     # bridge vlan del vid 1 dev dummy1
     # bridge fdb get 00:11:22:33:44:55 br br1 vlan 1
     00:11:22:33:44:55 dev dummy1 vlan 1 master br1 static
     # bridge fdb del 00:11:22:33:44:55 dev dummy1 master vlan 1
     RTNETLINK answers: Invalid argument
     # bridge fdb get 00:11:22:33:44:55 br br1 vlan 1
     00:11:22:33:44:55 dev dummy1 vlan 1 master br1 static

    This is in contrast to MDB entries that can be deleted after the VLAN
    was deleted:

     # bridge vlan add vid 10 dev dummy1
     # bridge mdb add dev br1 port dummy1 grp 239.1.1.1 permanent vid 10
     # bridge vlan del vid 10 dev dummy1
     # bridge mdb get dev br1 grp 239.1.1.1 vid 10
     dev br1 port dummy1 grp 239.1.1.1 permanent vid 10
     # bridge mdb del dev br1 port dummy1 grp 239.1.1.1 permanent vid 10
     # bridge mdb get dev br1 grp 239.1.1.1 vid 10
     Error: bridge: MDB entry not found.

    Align the two interfaces and allow user space to delete FDB entries that
    were added with a VLAN that no longer exists:

     # ip link add name dummy1 up type dummy
     # ip link add name br1 up type bridge vlan_filtering 1
     # ip link set dev dummy1 master br1
     # bridge fdb add 00:11:22:33:44:55 dev dummy1 master static vlan 1
     # bridge vlan del vid 1 dev dummy1
     # bridge fdb get 00:11:22:33:44:55 br br1 vlan 1
     00:11:22:33:44:55 dev dummy1 vlan 1 master br1 static
     # bridge fdb del 00:11:22:33:44:55 dev dummy1 master vlan 1
     # bridge fdb get 00:11:22:33:44:55 br br1 vlan 1
     Error: Fdb entry not found.

    Add a selftest to make sure this behavior does not regress:

     # ./rtnetlink.sh -t kci_test_fdb_del
     PASS: bridge fdb del

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Andy Roulin <aroulin@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Acked-by: Nikolay Aleksandrov <razor@blackwall.org>
    Link: https://patch.msgid.link/20241105133954.350479-1-idosch@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Heib <mheib@redhat.com>