ASoC: SOF: nocodec: fix undefined reference
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: SOF: nocodec: fix undefined reference (Jaroslav Kysela) [1738610]
Rebuild_FUZZ: 93.48%
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 8d01c3c73cefbb5bacffe804427daed3e6051435

The nocodec option can be selected individually, leading to the following
issue:

sound/soc/sof/core.o: In function `snd_sof_device_probe':
core.c:(.text+0x4af): undefined reference to `sof_nocodec_setup'

Fix by selecting the SND_SOF_NOCODEC option as needed.

	Reported-by: Hulk Robot <hulkci@huawei.com>
	Reported-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 8d01c3c73cefbb5bacffe804427daed3e6051435)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>