drm/vc4: hdmi: Fix build error for implicit function declaration
Bugzilla: https://bugzilla.redhat.com/2138240

commit 6fed53de560768bde6d701a7c79c253b45b259e3
Author: Hui Tang <tanghui20@huawei.com>
Date:   Tue May 10 21:51:48 2022 +0800

    drm/vc4: hdmi: Fix build error for implicit function declaration

    drivers/gpu/drm/vc4/vc4_hdmi.c: In function ‘vc4_hdmi_connector_detect’:
    drivers/gpu/drm/vc4/vc4_hdmi.c:228:7: error: implicit declaration of function ‘gpiod_get_value_cansleep’; did you mean ‘gpio_get_value_cansleep’? [-Werror=implicit-function-declaration]
       if (gpiod_get_value_cansleep(vc4_hdmi->hpd_gpio))
           ^~~~~~~~~~~~~~~~~~~~~~~~
           gpio_get_value_cansleep
      CC [M]  drivers/gpu/drm/vc4/vc4_validate.o
      CC [M]  drivers/gpu/drm/vc4/vc4_v3d.o
      CC [M]  drivers/gpu/drm/vc4/vc4_validate_shaders.o
      CC [M]  drivers/gpu/drm/vc4/vc4_debugfs.o
    drivers/gpu/drm/vc4/vc4_hdmi.c: In function ‘vc4_hdmi_bind’:
    drivers/gpu/drm/vc4/vc4_hdmi.c:2883:23: error: implicit declaration of function ‘devm_gpiod_get_optional’; did you mean ‘devm_clk_get_optional’? [-Werror=implicit-function-declaration]
      vc4_hdmi->hpd_gpio = devm_gpiod_get_optional(dev, "hpd", GPIOD_IN);
                           ^~~~~~~~~~~~~~~~~~~~~~~
                           devm_clk_get_optional
    drivers/gpu/drm/vc4/vc4_hdmi.c:2883:59: error: ‘GPIOD_IN’ undeclared (first use in this function); did you mean ‘GPIOF_IN’?
      vc4_hdmi->hpd_gpio = devm_gpiod_get_optional(dev, "hpd", GPIOD_IN);
                                                               ^~~~~~~~
                                                               GPIOF_IN
    drivers/gpu/drm/vc4/vc4_hdmi.c:2883:59: note: each undeclared identifier is reported only once for each function it appears in
    cc1: all warnings being treated as errors

    Fixes: 6800234ceee0 ("drm/vc4: hdmi: Convert to gpiod")
    Signed-off-by: Hui Tang <tanghui20@huawei.com>
    Signed-off-by: Maxime Ripard <maxime@cerno.tech>
    Link: https://patchwork.freedesktop.org/patch/msgid/20220510135148.247719-1-tanghui20@huawei.com

Signed-off-by: Adrien Thierry <athierry@redhat.com>