thunderbolt: Use correct type in tb_port_is_clx_enabled() prototype
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2212495
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d31137619776f9c173a46a79bc7733a2b106061f

commit d31137619776f9c173a46a79bc7733a2b106061f
Author: "Jiri Slaby (SUSE)" <jirislaby@kernel.org>
Date: Mon, 12 Dec 2022 11:29:36 +0100

  tb_port_is_clx_enabled() generates a valid warning with gcc-13:
    drivers/thunderbolt/switch.c:1286:6: error: conflicting types for 'tb_port_is_clx_enabled' due to enum/integer mismatch; have 'bool(struct tb_port *, unsigned int)' ...
    drivers/thunderbolt/tb.h:1050:6: note: previous declaration of 'tb_port_is_clx_enabled' with type 'bool(struct tb_port *, enum tb_clx)' ...

  I.e. the type of the 2nd parameter of tb_port_is_clx_enabled() in the
  declaration is unsigned int, while the definition spells enum tb_clx.
  Synchronize them to the former as the parameter is in fact a mask of the
  enum values.

  Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
  Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>