infiniband: mlx5: fix build errors when INFINIBAND_USER_ACCESS=m
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [infiniband] mlx5: fix build errors when INFINIBAND_USER_ACCESS=m (Alaa Hleihel) [1642498]
Rebuild_FUZZ: 89.66%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit b3fe6c62bc66868c45b5bb16050e6bcb333af337

Fix build errors when INFINIBAND_USER_ACCESS=m and MLX5_INFINIBAND=y.
The build error occurs when the mlx5 driver code attempts to use
USER_ACCESS interfaces, which are built as a loadable module.

Fixes these build errors:

drivers/infiniband/hw/mlx5/main.o: In function `populate_specs_root':
../drivers/infiniband/hw/mlx5/main.c:4982: undefined reference to `uverbs_default_get_objects'
../drivers/infiniband/hw/mlx5/main.c:4994: undefined reference to `uverbs_alloc_spec_tree'
drivers/infiniband/hw/mlx5/main.o: In function `depopulate_specs_root':
../drivers/infiniband/hw/mlx5/main.c:5001: undefined reference to `uverbs_free_spec_tree'

Build-tested with multiple config combinations.

Fixes: 8c84660bb437 ("IB/mlx5: Initialize the parsing tree root without the help of uverbs")
	Cc: stable@vger.kernel.org # reported against 4.16
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit b3fe6c62bc66868c45b5bb16050e6bcb333af337)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>