samples/bpf: Fix compilation failure for samples/bpf on LoongArch Fedora
JIRA: https://issues.redhat.com/browse/RHEL-78202

commit 548762f05d19c5542db7590bcdfb9be1fb928376
Author: Haoran Jiang <jianghaoran@kylinos.cn>
Date:   Fri Apr 25 17:50:42 2025 +0800

    samples/bpf: Fix compilation failure for samples/bpf on LoongArch Fedora
    
    When building the latest samples/bpf on LoongArch Fedora
    
         make M=samples/bpf
    
    There are compilation errors as follows:
    
    In file included from ./linux/samples/bpf/sockex2_kern.c:2:
    In file included from ./include/uapi/linux/in.h:25:
    In file included from ./include/linux/socket.h:8:
    In file included from ./include/linux/uio.h:9:
    In file included from ./include/linux/thread_info.h:60:
    In file included from ./arch/loongarch/include/asm/thread_info.h:15:
    In file included from ./arch/loongarch/include/asm/processor.h:13:
    In file included from ./arch/loongarch/include/asm/cpu-info.h:11:
    ./arch/loongarch/include/asm/loongarch.h:13:10: fatal error: 'larchintrin.h' file not found
             ^~~~~~~~~~~~~~~
    1 error generated.
    
    larchintrin.h is included in /usr/lib64/clang/14.0.6/include,
    and the header file location is specified at compile time.
    
    Test on LoongArch Fedora:
    https://github.com/fedora-remix-loongarch/releases-info
    
    Signed-off-by: Haoran Jiang <jianghaoran@kylinos.cn>
    Signed-off-by: zhangxi <zhangxi@kylinos.cn>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20250425095042.838824-1-jianghaoran@kylinos.cn

Signed-off-by: Gregory Bell <grbell@redhat.com>