riscv: Avoid fortify warning in syscall_get_arguments()
JIRA: https://issues.redhat.com/browse/RHEL-147291

commit adf53771a3123df99ca26e38818760fbcf5c05d0
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed, 9 Apr 2025 14:24:46 -0700

    riscv: Avoid fortify warning in syscall_get_arguments()

    When building with CONFIG_FORTIFY_SOURCE=y and W=1, there is a warning
    because of the memcpy() in syscall_get_arguments():

      In file included from include/linux/string.h:392,
                       from include/linux/bitmap.h:13,
                       from include/linux/cpumask.h:12,
                       from arch/riscv/include/asm/processor.h:55,
                       from include/linux/sched.h:13,
                       from kernel/ptrace.c:13:
      In function 'fortify_memcpy_chk',
          inlined from 'syscall_get_arguments.isra' at arch/riscv/include/asm/syscall.h:66:2:
      include/linux/fortify-string.h:580:25: error: call to '__read_overflow2_field' declared with attribute warning: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror=attribute-warning]
        580 |                         __read_overflow2_field(q_size_field, size);
            |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors

    The fortified memcpy() routine enforces that the source is not overread
    and the destination is not overwritten if the size of either field and
    the size of the copy are known at compile time. The memcpy() in
    syscall_get_arguments() intentionally overreads from a1 to a5 in
    'struct pt_regs' but this is bigger than the size of a1.

    Normally, this could be solved by wrapping a1 through a5 with
    struct_group() but there was already a struct_group() applied to these
    members in commit bba547810c66 ("riscv: tracing: Fix
    __write_overflow_field in ftrace_partial_regs()").

    Just avoid memcpy() altogether and write the copying of args from regs
    manually, which clears up the warning at the expense of three extra
    lines of code.

    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Dmitry V. Levin <ldv@strace.io>
    Fixes: e2c0cdfba7f6 ("RISC-V: User-facing API")
    Cc: stable@vger.kernel.org
    Link: https://lore.kernel.org/r/20250409-riscv-avoid-fortify-warning-syscall_get_arguments-v1-1-7853436d4755@kernel.org
    Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>

Signed-off-by: Jennifer Berringer <jberring@redhat.com>