media: uvcvideo: Fix dereference of out-of-bound list iterator
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Daniel W. S. Almeida <dwlsalmeida@gmail.com>
commit f875bcc375c738bf2f599ff2e1c5b918dbd07c45

Fixes the following coccinelle report:

drivers/media/usb/uvc/uvc_ctrl.c:1860:5-11:
ERROR: invalid reference to the index variable of the iterator on line 1854

by adding a boolean variable to check if the loop has found the

Found using - Coccinelle (http://coccinelle.lip6.fr)

[Replace cursor variable with bool found]

	Signed-off-by: Daniel W. S. Almeida <dwlsalmeida@gmail.com>
	Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
	Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
(cherry picked from commit f875bcc375c738bf2f599ff2e1c5b918dbd07c45)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>