drm/panic: clean Clippy warning
JIRA: https://issues.redhat.com/browse/RHEL-75952

commit fc71fa9e080a445e5a26692740df2b63387ce96b
Author: Miguel Ojeda <ojeda@kernel.org>
Date:   Mon Mar 3 10:32:42 2025 +0100

    drm/panic: clean Clippy warning

    [ Upstream commit 57145afa3326947154c3a890b1118774b55212a0 ]

    Clippy warns:

        error: manual implementation of an assign operation
           --> drivers/gpu/drm/drm_panic_qr.rs:418:25
            |
        418 |                         self.carry = self.carry % pow;
            |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `self.carry %= pow`
            |
            = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assign_op_pattern

    Thus clean it up.

    Fixes: dbed4a797e00 ("drm/panic: Better binary encoding in QR code")
    Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
    Reviewed-by: Alice Ryhl <aliceryhl@google.com>
    Reviewed-by: Jocelyn Falempe <jfalempe@redhat.com>
    Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20250303093242.1011790-1-ojeda@kernel.org
    Stable-dep-of: 675008f196ca ("drm/panic: Use a decimal fifo to avoid u64 by u64 divide")
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Robert Foss <rfoss@redhat.com>