tpm: xen-tpmfront: fix missing declaration of xen_domain
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Rob Herring <rob.herring@calxeda.com>
commit 8702c675319b838346a4fbaf4bbb783a563fa9a6

xen-tpmfront fails to build on arm64 with the following error:

drivers/char/tpm/xen-tpmfront.c: In function ‘xen_tpmfront_init’:
drivers/char/tpm/xen-tpmfront.c:422:2: error: implicit declaration of function ‘xen_domain’ [-Werror=implicit-function-declaration]

Add include of xen/xen.h to fix this.

	Signed-off-by: Rob Herring <rob.herring@calxeda.com>
	Signed-off-by: Stefano Stabellini <stefano.stabellini@eu.citrix.com>
	Reviewed-by: Ashley Lai <adlai@linux.vnet.ibm.com>
	Acked-by: Ashley Lai <adlai@linux.vnet.ibm.com>
	Cc: Leonidas Da Silva Barbosa <leosilva@linux.vnet.ibm.com>
	Cc: Rajiv Andrade <mail@srajiv.net>
	Cc: Marcel Selhorst <tpmdd@selhorst.net>
	Cc: Sirrix AG <tpmdd@sirrix.com>
	Cc: tpmdd-devel@lists.sourceforge.net
(cherry picked from commit 8702c675319b838346a4fbaf4bbb783a563fa9a6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>