RDMA/srp: Move large values to a new enum for gcc13
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-490.el8
commit-author Jiri Slaby (SUSE) <jirislaby@kernel.org>
commit 56c5dab20a6391604df9521f812c01d1e3fe1bd0

Since gcc13, each member of an enum has the same type as the enum [1]. And
that is inherited from its members. Provided these two:
  SRP_TAG_NO_REQ        = ~0U,
  SRP_TAG_TSK_MGMT	= 1U << 31
all other members are unsigned ints.

Esp. with SRP_MAX_SGE and SRP_TSK_MGMT_SQ_SIZE and their use in min(),
this results in the following warnings:
  include/linux/minmax.h:20:35: error: comparison of distinct pointer types lacks a cast
  drivers/infiniband/ulp/srp/ib_srp.c:563:42: note: in expansion of macro 'min'

  include/linux/minmax.h:20:35: error: comparison of distinct pointer types lacks a cast
  drivers/infiniband/ulp/srp/ib_srp.c:2369:27: note: in expansion of macro 'min'

So move the large values away to a separate enum, so that they don't
affect other members.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36113

Link: https://lore.kernel.org/r/20221212120411.13750-1-jirislaby@kernel.org
	Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
	Reviewed-by: Bart Van Assche <bvanassche@acm.org>
	Signed-off-by: Leon Romanovsky <leon@kernel.org>
(cherry picked from commit 56c5dab20a6391604df9521f812c01d1e3fe1bd0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>