xdrgen: Extend error reporting to AST transformation phase
JIRA: https://issues.redhat.com/browse/RHEL-171581

commit 63a5425ff5e077c54eb2719c735108e2aa1f9eb6
Author: Chuck Lever <chuck.lever@oracle.com>
Date:   Fri Dec 26 10:19:33 2025 -0500

    xdrgen: Extend error reporting to AST transformation phase

    Commit 277df18d7df9 ("xdrgen: Improve parse error reporting") added
    clean, compiler-style error messages for syntax errors detected during
    parsing. However, semantic errors discovered during AST transformation
    still produce verbose Python stack traces.

    When an XDR specification references an undefined type, the transformer
    raises a VisitError wrapping a KeyError. Before this change:

      Traceback (most recent call last):
        File ".../lark/visitors.py", line 124, in _call_userfunc
          return f(children)
        ...
      KeyError: 'fsh4_mode'
      ...
      lark.exceptions.VisitError: Error trying to process rule "basic":
      'fsh4_mode'

    After this change:

      file.x:156:2: semantic error
      Undefined type 'fsh4_mode'

            fsh4_mode       mode;
                  ^

    The new handle_transform_error() function extracts position information
    from the Lark tree node metadata and formats the error consistently with
    parse error messages.

    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Olga Kornievskaia <okorniev@redhat.com>