scsi: lpfc: Use struct_group to isolate cast to larger object
Bugzilla: https://bugzilla.redhat.com/2166789

commit c167dd0b2a7afcf2c25e44b9b6168cba3a51d27d
Author: Kees Cook <keescook@chromium.org>
Date:   Fri Dec 3 14:33:51 2021 -0800

    scsi: lpfc: Use struct_group to isolate cast to larger object

    When building under -Warray-bounds, a warning is generated when casting a
    u32 into MAILBOX_t (which is larger). This warning is conservative, but
    it's not an unreasonable change to make to improve future robustness. Use a
    tagged struct_group that can refer to either the specific fields or the
    first u32 separately, silencing this warning:

    drivers/scsi/lpfc/lpfc_sli.c: In function 'lpfc_reset_barrier':
    drivers/scsi/lpfc/lpfc_sli.c:4787:29: error: array subscript 'MAILBOX_t[0]' is partly outside array bounds of 'volatile uint32_t[1]' {aka 'volatile unsigned int[1]'} [-Werror=array-bounds]
     4787 |         ((MAILBOX_t *)&mbox)->mbxCommand = MBX_KILL_BOARD;
          |                             ^~
    drivers/scsi/lpfc/lpfc_sli.c:4752:27: note: while referencing 'mbox'
     4752 |         volatile uint32_t mbox;
          |                           ^~~~

    There is no change to the resulting executable instruction code.

    Link: https://lore.kernel.org/r/20211203223351.107323-1-keescook@chromium.org
    Reviewed-by: James Smart <jsmart2021@gmail.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Eric Chanudet <echanude@redhat.com>