iommu/ipmmu-vmsa: Remove ipmmu_utlb_disable()
JIRA: https://issues.redhat.com/browse/RHEL-10094
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 584d334b139325aa7468fc2eb045864f260298d1
Author: Joerg Roedel <jroedel@suse.de>
Date:   Fri Jan 13 19:56:40 2023 +0100

    iommu/ipmmu-vmsa: Remove ipmmu_utlb_disable()

    The function is unused after commit 1b932ceddd19 ("iommu:
    Remove detach_dev callbacks") and so compilation fails with

    drivers/iommu/ipmmu-vmsa.c:305:13: error: ‘ipmmu_utlb_disable’ defined but not used [-Werror=unused-function]
      305 | static void ipmmu_utlb_disable(struct ipmmu_vmsa_domain *domain,
	  |             ^~~~~~~~~~~~~~~~~~

    Remove the function to fix the compile error.

    Fixes: 1b932ceddd19 ("iommu: Remove detach_dev callbacks")
    Signed-off-by: Joerg Roedel <jroedel@suse.de>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Link: https://lore.kernel.org/r/20230113185640.8050-1-joro@8bytes.org

(cherry picked from commit 584d334b139325aa7468fc2eb045864f260298d1)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>