perf intel-pt: Synthesize CFE (Control Flow Event) / EVD (Event Data) event
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit ef3b2ba9640d0e1e6991b8a5c0ddece2fc3e4d23
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Mon Jan 24 10:41:50 2022 +0200

description
===========
Synthesize an attribute event and sample events for Intel PT Event Trace
events represented by CFE and EVD packets.

Committer notes:

Make 'struct perf_synth_intel_evd evd[]' evd[0] at the end of 'struct
perf_synth_intel_evt' as it is breaking the build with in many compilers
with (e.g. clang version 13.0.0 (Fedora 13.0.0-3.fc35)):

  util/intel-pt.c:2213:31: error: field 'cfe' with variable sized type 'struct perf_synth_intel_evt' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
                  struct perf_synth_intel_evt cfe;
                                              ^

Signed-off-by: Michael Petlan <mpetlan@redhat.com>