wifi: iwlwifi: Avoid disabling GCC specific flag with clang
Bugzilla: https://bugzilla.redhat.com/2196821

commit 499183cc3b52613f06cf4ce70809546971c96ed8
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Mar 15 20:28:29 2023 -0700

    wifi: iwlwifi: Avoid disabling GCC specific flag with clang
    
    Clang errors:
    
      drivers/net/wireless/intel/iwlwifi/iwl-devtrace.c:15:32: error: unknown warning group '-Wsuggest-attribute=format', ignored [-Werror,-Wunknown-warning-option]
      #pragma GCC diagnostic ignored "-Wsuggest-attribute=format"
                                     ^
      1 error generated.
    
    The warning being disabled by this pragma is GCC specific. Guard its use
    with CONFIG_CC_IS_GCC so that it is not used with clang to clear up the
    error.
    
    Fixes: 4eca8cbf7ba8 ("wifi: iwlwifi: suppress printf warnings in tracing")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1818
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20230315-iwlwifi-fix-pragma-v1-1-ad23f92c4739@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>