HID: i2c-hid: add more DRM dependencies
JIRA: https://issues.redhat.com/browse/RHEL-23851
Upstream Status: since v6.6
Tested: with the hid-tools test suite and some hardware

commit a0769f25a3a621e8bbfb5e2a26e8ae462c761e33
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Aug 2 14:49:40 2023 +0200

    HID: i2c-hid: add more DRM dependencies

    When a symbol is selected that has extra dependencies,
    anything that selects it must have the same dependencies.
    With the added CONFIG_DRM reference from I2C_HID_CORE,
    this broke a couple of drivers that now also depend
    on DRM:

    WARNING: unmet direct dependencies detected for I2C_HID_CORE
      Depends on [m]: HID_SUPPORT [=y] && I2C_HID [=y] && (DRM [=m] || !DRM [=m])
      Selected by [y]:
      - I2C_HID_OF [=y] && HID_SUPPORT [=y] && I2C_HID [=y]
      - I2C_HID_ACPI [=y] && HID_SUPPORT [=y] && I2C_HID [=y] && ACPI [=y]
      - I2C_HID_OF_GOODIX [=y] && HID_SUPPORT [=y] && I2C_HID [=y] && OF [=y]
    x86_64-linux-ld: vmlinux.o: in function `i2c_hid_core_remove':
    (.text+0xfc8826): undefined reference to `drm_panel_remove_follower'
    x86_64-linux-ld: vmlinux.o: in function `i2c_hid_core_probe':
    (.text+0xfc8da0): undefined reference to `drm_is_panel_follower'

    Add the corresponding DRM||!DRM dependencies on each one that
    is affected.

    Fixes: 96a37bfd232ae ("HID: i2c-hid: Support being a panel follower")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Douglas Anderson <dianders@chromium.org>
    Signed-off-by: Douglas Anderson <dianders@chromium.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20230802124947.1355415-1-arnd@kernel.org

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>