x86/qspinlock: Fix compile error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Peter Zijlstra <peterz@infradead.org>
commit b987ffc18fb3b3b76b059aa9e372dbee26f7c4f2

With a compiler that has asm-goto but not asm-cc-output and
CONFIG_PROFILE_ALL_BRANCHES=y we get a compiler error:

  arch/x86/include/asm/rmwcc.h:23:17: error: jump into statement expression

Fix this by writing the if() as a boolean multiplication instead.

	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: Will Deacon <will.deacon@arm.com>
	Cc: linux-kernel@vger.kernel.org
Fixes: 7aa54be29765 ("locking/qspinlock, x86: Provide liveness guarantee")
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit b987ffc18fb3b3b76b059aa9e372dbee26f7c4f2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>