ASoC: Intel: atom: remove static analysis false positive
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 71d76768fbe72aa70dd61d5714a5579dc4ca61cb
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Mon Jul 31 16:37:47 2023 -0500

    ASoC: Intel: atom: remove static analysis false positive

    make KCFLAGS='-fanalyzer' sound/soc/intel/atom/ reports a possible
    NULL pointer dereference.

    sound/soc/intel/atom/sst/sst_stream.c:221:40: error: dereference of
    NULL ‘block’ [CWE-476] [-Werror=analyzer-null-dereference]
      221 |                         unsigned char *r = block->data;

    This is a false-positive, the GCC analyzer generated that report by
    considering if (bytes->block) as true in some cases and false in
    others.

    We can simplify the code and use a local variable so that static
    analysis does not try to look for cases where bytes->block can be
    modified concurrently.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Reviewed-by: Rander Wang <rander.wang@intel.com>
    Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
    Reviewed-by: Yaochun Hung <yc.hung@mediatek.com>
    Link: https://lore.kernel.org/r/20230731213748.440285-8-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>