perf probe: Fix --list option to show events only with uprobe events
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [tools] perf/probe: Fix --list option to show events only with uprobe events (Jiri Olsa) [1169436]
Rebuild_FUZZ: 98.53%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 5e45187cc94814d2a5324bc18af994efc4fb4f7c

Current perf probe --list doesn't work if only CONFIG_UPROBE_EVENTS=y
because it aborts when it fails to open kprobe_events file before
checking uprobe_events file.

This fixes --list option to show dynamic events if it can open either
kprobe_events or uprobe_events. Only if it failed to open both of them,
it shows an error message and aborts.

Without this patch, if we run perf probe -l on the kernel configured
with CONFIG_KPROBE_EVENTS=n and CONFIG_UPROBE_EVENTS=y,

  # perf probe -l
  /sys/kernel/debug/tracing/kprobe_events file does not exist - please rebuild ker
    Error: Failed to show event list.

With this patch,

  # perf probe -l
    probe_perf:alloc_event (on alloc_event@lib/traceevent/event-parse.c in /home/fedora/ksrc/linux-3/tools/perf/perf)

Changes in v2:
 - Use strerror_r instead of strerror.

	Reported-by: Naohiro Aota <naota@elisp.net>
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Naohiro Aota <naota@elisp.net>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: http://lkml.kernel.org/r/20140813161248.26440.84370.stgit@kbuild-fedora.novalocal
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 5e45187cc94814d2a5324bc18af994efc4fb4f7c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>