perf tools: Fix pmu object compilation error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [tools] perf: Fix pmu object compilation error (Jiri Olsa) [1134356]
Rebuild_FUZZ: 92.68%
commit-author Jiri Olsa <jolsa@redhat.com>
commit 7c2f8164e5415ef48954f6929f4acae5764afdb4

After applying some patches got another shadowing error:

  CC       util/pmu.o
util/pmu.c: In function ‘pmu_alias_terms’:
util/pmu.c:287:35: error: declaration of ‘clone’ shadows a global declaration [-Werror=shadow]

Renaming clone to cloned.

	Acked-by: David Ahern <dsahern@gmail.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
Link: http://lkml.kernel.org/r/1397674818-27054-1-git-send-email-jolsa@redhat.com
	Signed-off-by: Jiri Olsa <jolsa@redhat.com>
(cherry picked from commit 7c2f8164e5415ef48954f6929f4acae5764afdb4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>