efi: Fix build error due to enum collision between efi.h and ima.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Anders Roxell <anders.roxell@linaro.org>
commit 5c418dc789a3898717ebf2caa5716ba91a7150b2

The following commit:

  a893ea15d764 ("tpm: move tpm_chip definition to include/linux/tpm.h")

introduced a build error when both IMA and EFI are enabled:

    In file included from ../security/integrity/ima/ima_fs.c:30:
    ../security/integrity/ima/ima.h:176:7: error: redeclaration of enumerator "NONE"

What happens is that both headers (ima.h and efi.h) defines the same
'NONE' constant, and it broke when they started getting included from
the same file:

Rework to prefix the EFI enum with 'EFI_*'.

	Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
	Signed-off-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: linux-efi@vger.kernel.org
Link: http://lkml.kernel.org/r/20190215165551.12220-2-ard.biesheuvel@linaro.org
[ Cleaned up the changelog a bit. ]
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 5c418dc789a3898717ebf2caa5716ba91a7150b2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>