ASoC: amd: ps: Fix uninitialized ret in create_acp64_platform_devs()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit de1cae22898cf10aacc735a21d799b5bbce4496c

Clang warns:

  sound/soc/amd/ps/pci-ps.c:218:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
          default:
          ^~~~~~~
  sound/soc/amd/ps/pci-ps.c:239:9: note: uninitialized use occurs here
          return ret;
                 ^~~
  sound/soc/amd/ps/pci-ps.c:190:9: note: initialize the variable 'ret' to silence this warning
          int ret;
                 ^
                  = 0
  1 error generated.

ret is used uninitialized if 'goto de_init' is taken. As this is not an
error nor should the ACP be deinitialized, just directly return 0 in
this case statement, which resolves the warning.

Fixes: 1d325cdaf7a2 ("ASoC: amd: ps: refactor platform device creation logic")
Link: https://github.com/ClangBuiltLinux/linux/issues/1779
	Suggested-by: Vijendar Mukunda <Vijendar.Mukunda@amd.com>
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
	Reviewed-by: Syed Saba Kareem <syed.sabakareem@amd.com>
Link: https://lore.kernel.org/r/20230105-wsometimes-uninitialized-pci-ps-c-v2-1-c50321676325@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit de1cae22898cf10aacc735a21d799b5bbce4496c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>