selftests: ublk: fix build failure
JIRA: https://issues.redhat.com/browse/RHEL-106845

commit 9d80f48c5e08b2e003e506c6e5326a35a652ea2f
Author: Ming Lei <ming.lei@redhat.com>
Date:   Mon Mar 3 20:43:12 2025 +0800

    selftests: ublk: fix build failure

    Fixes the following build failure:

    ublk//file_backed.c: In function ‘backing_file_tgt_init’:
    ublk//file_backed.c:28:42: error: ‘O_DIRECT’ undeclared (first use in this function); did you mean ‘O_DIRECTORY’?
       28 |                 fd = open(file, O_RDWR | O_DIRECT);
          |                                          ^~~~~~~~
          |                                          O_DIRECTORY

    when trying to reuse this same utility for liburing test.

    Signed-off-by: Ming Lei <ming.lei@redhat.com>
    Reviewed-by: Keith Busch <kbusch@kernel.org>
    Link: https://lore.kernel.org/r/20250303124324.3563605-3-ming.lei@redhat.com
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>