selftests/bpf: Add missing selftests kconfig options
JIRA: https://issues.redhat.com/browse/RHEL-9957

commit 3d272c2fa8045f31879a3beee230c1711367b697
Author: David Vernet <void@manifault.com>
Date:   Fri Jun 2 09:01:08 2023 -0500

    selftests/bpf: Add missing selftests kconfig options
    
    Our selftests of course rely on the kernel being built with
    CONFIG_DEBUG_INFO_BTF=y, though this (nor its dependencies of
    CONFIG_DEBUG_INFO=y and CONFIG_DEBUG_INFO_DWARF4=y) are not specified.
    This causes the wrong kernel to be built, and selftests to similarly
    fail to build.
    
    Additionally, in the BPF selftests kconfig file,
    CONFIG_NF_CONNTRACK_MARK=y is specified, so that the 'u_int32_t mark'
    field will be present in the definition of struct nf_conn.  While a
    dependency of CONFIG_NF_CONNTRACK_MARK=y, CONFIG_NETFILTER_ADVANCED=y,
    should be enabled by default, I've run into instances of
    CONFIG_NF_CONNTRACK_MARK not being set because CONFIG_NETFILTER_ADVANCED
    isn't set, and have to manually enable them with make menuconfig.
    
    Let's add these missing kconfig options to the file so that the
    necessary dependencies are in place to build vmlinux. Otherwise, we'll
    get errors like this when we try to compile selftests and generate
    vmlinux.h:
    
    $ cd /path/to/bpf-next
    $ make mrproper; make defconfig
    $ cat tools/testing/selftests/config >> .config
    $ make -j
    ...
    $ cd tools/testing/selftests/bpf
    $ make clean
    $ make -j
    ...
      LD [M]
      tools/testing/selftests/bpf/bpf_testmod/bpf_testmod.ko
      tools/testing/selftests/bpf/tools/build/bpftool/bootstrap/bpftool
      btf dump file vmlinux format c >
      tools/testing/selftests/bpf/tools/build/bpftool/vmlinux.h
      libbpf: failed to find '.BTF' ELF section in
      vmlinux
      Error: failed to load BTF from bpf-next/vmlinux:
      No data available
      make[1]: *** [Makefile:208:
      tools/testing/selftests/bpf/tools/build/bpftool/vmlinux.h]
      Error 195
      make[1]: *** Deleting file
      'tools/testing/selftests/bpf/tools/build/bpftool/vmlinux.h'
      make: *** [Makefile:261:
      tools/testing/selftests/bpf/tools/sbin/bpftool]
      Error 2
    
    Signed-off-by: David Vernet <void@manifault.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Stanislav Fomichev <sdf@google.com>
    Link: https://lore.kernel.org/bpf/20230602140108.1177900-1-void@manifault.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>