x86/mce: Fix -Wmissing-prototypes warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Borislav Petkov <bp@suse.de>
commit 68b5e4326e4b8ac9080835005d8254fed0fb3c56

Add the proper includes and make smca_get_name() static.

Fix an actual bug too which the warning triggered:

  arch/x86/kernel/cpu/mcheck/therm_throt.c:395:39: error: conflicting \
  types for ‘smp_thermal_interrupt’
   asmlinkage __visible void __irq_entry smp_thermal_interrupt(struct pt_regs *r)
                                         ^~~~~~~~~~~~~~~~~~~~~
  In file included from arch/x86/kernel/cpu/mcheck/therm_throt.c:29:
  ./arch/x86/include/asm/traps.h:107:17: note: previous declaration of \
	  ‘smp_thermal_interrupt’ was here
   asmlinkage void smp_thermal_interrupt(void);

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Yi Wang <wang.yi59@zte.com.cn>
	Cc: Michael Matz <matz@suse.de>
	Cc: x86@kernel.org
Link: https://lkml.kernel.org/r/alpine.DEB.2.21.1811081633160.1549@nanos.tec.linutronix.de
(cherry picked from commit 68b5e4326e4b8ac9080835005d8254fed0fb3c56)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>