ALSA: hda: cs35l41: mark cs35l41_verify_id() static
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit f71e0be5d297b25453fdf4c1757b3e83e94b5f98
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Oct 27 17:25:09 2023 +0200

    ALSA: hda: cs35l41: mark cs35l41_verify_id() static

    The newly introduced function is global but only called in this one
    file and has no extern prototype, so it should probably be static:

    sound/pci/hda/cs35l41_hda.c:733:5: error: no previous prototype for 'cs35l41_verify_id' [-Werror=missing-prototypes]
      733 | int cs35l41_verify_id(struct cs35l41_hda *cs35l41, unsigned int *regid, unsigned int *reg_revid)

    Fixes: 881b7bce0c25 ("ALSA: hda: cs35l41: Run boot process during resume callbacks")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231027152515.482411-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>