seq_buf: Make DECLARE_SEQ_BUF() usable
JIRA: https://issues.redhat.com/browse/RHEL-53569
Upstream Status: v6.8-rc1

commit 7a8e9cdf9405819105ae7405cd91e482bf574b01
Author:     Nathan Lynch <nathanl@linux.ibm.com>
AuthorDate: Tue Jan 16 08:09:25 2024 -0600
Commit:     Steven Rostedt (Google) <rostedt@goodmis.org>
CommitDate: Thu Jan 18 09:22:02 2024 -0500

    Using the address operator on the array doesn't work:

    ./include/linux/seq_buf.h:27:27: error: initialization of ‘char *’
      from incompatible pointer type ‘char (*)[128]’
      [-Werror=incompatible-pointer-types]
       27 |                 .buffer = &__ ## NAME ## _buffer,       \
          |                           ^

    Apart from fixing that, we can improve DECLARE_SEQ_BUF() by using a
    compound literal to define the buffer array without attaching a name
    to it. This makes the macro a single statement, allowing constructs
    such as:

      static DECLARE_SEQ_BUF(my_seq_buf, MYSB_SIZE);

    to work as intended.

    Link: https://lkml.redhat.com/r/20240116-declare-seq-buf-fix-v1-1-915db4692f32@linux.ibm.com

    Cc: stable@vger.redhat.com
    Acked-by: Kees Cook <keescook@chromium.org>
    Fixes: dcc4e5728eea ("seq_buf: Introduce DECLARE_SEQ_BUF and seq_buf_str()")
    Signed-off-by: Nathan Lynch <nathanl@linux.ibm.com>
    Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Robert Foss <rfoss@redhat.com>