dummycon: fix default rows/cols
JIRA: https://issues.redhat.com/browse/RHEL-107476
Upstream Status: v6.15-rc1

commit beefaba1978c04ea2950d34236f58fe6cf6a7f58
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Tue Feb 25 17:44:22 2025 +0100
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Wed Mar 26 22:39:20 2025 +0100

    dummycon fails to build on ARM/footbridge when the VGA console is
    disabled, since I got the dependencies slightly wrong in a previous
    patch:

    drivers/video/console/dummycon.c: In function 'dummycon_init':
    drivers/video/console/dummycon.c:27:25: error: 'CONFIG_DUMMY_CONSOLE_COLUMNS' undeclared (first use in this function); did you mean 'CONFIG_DUMMY_CONSOLE'?
       27 | #define DUMMY_COLUMNS   CONFIG_DUMMY_CONSOLE_COLUMNS
    drivers/video/console/dummycon.c:28:25: error: 'CONFIG_DUMMY_CONSOLE_ROWS' undeclared (first use in this function); did you mean 'CONFIG_DUMMY_CONSOLE'?
       28 | #define DUMMY_ROWS      CONFIG_DUMMY_CONSOLE_ROWS

    This only showed up after many thousand randconfig builds on Arm, and
    doesn't matter in practice, but should still be fixed. Address it by
    using the default row/columns on footbridge after all in that corner
    case.

    Fixes: 4293b0925149 ("dummycon: limit Arm console size hack to footbridge")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202409151512.LML1slol-lkp@intel.com/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Thomas Zimmermann <tzimmermann@suse.de>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>