cdx: Fix cdx_mmap_resource() after constifying attr in ->mmap()
JIRA: https://issues.redhat.com/browse/RHEL-85241
Upstream Status: 5852357d553829e972eeb575b5b3e39fc573addd

commit 5852357d553829e972eeb575b5b3e39fc573addd
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Thu Nov 7 10:07:43 2024 -0700

    cdx: Fix cdx_mmap_resource() after constifying attr in ->mmap()

    Commit 94a20fb9af16 ("sysfs: treewide: constify attribute callback of
    bin_attribute::mmap()") missed updating the attr parameter of
    cdx_mmap_resource(), resulting in a build failure.

      drivers/cdx/cdx.c: In function 'cdx_create_res_attr':
      drivers/cdx/cdx.c:773:24: error: assignment to 'int (*)(struct file *, struct kobject *, const struct bin_attribute *, struct vm_area_struct *)' from incompatible pointer type 'int (*)(struct file *, struct kobject *, struct bin_attribute *, struct vm_area_struct *)' [-Wincompatible-pointer-types]
        773 |         res_attr->mmap = cdx_mmap_resource;
            |                        ^

    Update cdx_mmap_resource() to match, resolving the build failure.

    Fixes: 94a20fb9af16 ("sysfs: treewide: constify attribute callback of bin_attribute::mmap()")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Tested-by: Thorsten Leemhuis <linux@leemhuis.info>
    Reviewed-by: Thomas Weißschuu <linux@weissschuh.net>
    Link: https://lore.kernel.org/r/20241107-sysfs-const-mmap-fix-cdx-v1-1-2ed9b7cd5f8b@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>