x86/speculation: Use DECLARE_PER_CPU for x86_spec_ctrl_current
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2090231
CVE: CVE-2022-23816
CVE: CVE-2022-23825
CVE: CVE-2022-29900
CVE: CVE-2022-29901

commit db886979683a8360ced9b24ab1125ad0c4d2cf76
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed, 13 Jul 2022 08:24:37 -0700

    x86/speculation: Use DECLARE_PER_CPU for x86_spec_ctrl_current

    Clang warns:

      arch/x86/kernel/cpu/bugs.c:58:21: error: section attribute is specified on redeclared variable [-Werror,-Wsection]
      DEFINE_PER_CPU(u64, x86_spec_ctrl_current);
                          ^
      arch/x86/include/asm/nospec-branch.h:283:12: note: previous declaration is here
      extern u64 x86_spec_ctrl_current;
                 ^
      1 error generated.

    The declaration should be using DECLARE_PER_CPU instead so all
    attributes stay in sync.

    Cc: stable@vger.kernel.org
    Fixes: fc02735b14ff ("KVM: VMX: Prevent guest RSB poisoning attacks with eIBRS")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>