net/mlx5: Increase size of irq name buffer
JIRA: https://issues.redhat.com/browse/RHEL-882
Upstream-status: v6.7-rc2

commit 3338bebfc26a1e2cebbba82a1cf12c0159608e73
Author: Rahul Rameshbabu <rrameshbabu@nvidia.com>
Date:   Tue Nov 14 13:58:43 2023 -0800

    net/mlx5: Increase size of irq name buffer

    Without increased buffer size, will trigger -Wformat-truncation with W=1
    for the snprintf operation writing to the buffer.

        drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c: In function 'mlx5_irq_alloc':
        drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:296:7: error: '@pci:' directive output may be truncated writing 5 bytes into a region of size between 1 and 32 [-Werror=format-truncation=]
          296 |    "%s@pci:%s", name, pci_name(dev->pdev));
              |       ^~~~~
        drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:295:2: note: 'snprintf' output 6 or more bytes (assuming 37) into a destination of size 32
          295 |  snprintf(irq->name, MLX5_MAX_IRQ_NAME,
              |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          296 |    "%s@pci:%s", name, pci_name(dev->pdev));
              |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: ada9f5d00797 ("IB/mlx5: Fix eq names to display nicely in /proc/interrupts")
    Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6d4ab2e97dcfbcd748ae71761a9d8e5e41cc732c
    Signed-off-by: Rahul Rameshbabu <rrameshbabu@nvidia.com>
    Reviewed-by: Dragos Tatulea <dtatulea@nvidia.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Link: https://lore.kernel.org/r/20231114215846.5902-13-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>