selftests/bpf: Fix missing ARRAY_SIZE() definition in bench.c
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit d44c93fc2f5a0c47b23fa03d374e45259abd92d2
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:34 2024 -0700

    selftests/bpf: Fix missing ARRAY_SIZE() definition in bench.c

    Add a "bpf_util.h" include to avoid the following error seen compiling for
    mips64el with musl libc:

      bench.c: In function 'find_benchmark':
      bench.c:590:25: error: implicit declaration of function 'ARRAY_SIZE' [-Werror=implicit-function-declaration]
        590 |         for (i = 0; i < ARRAY_SIZE(benchs); i++) {
            |                         ^~~~~~~~~~
      cc1: all warnings being treated as errors

    Fixes: 8e7c2a023ac0 ("selftests/bpf: Add benchmark runner infrastructure")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/bc4dde77dfcd17a825d8f28f72f3292341966810.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>