Revert "net: stmmac: use sysfs_streq() instead of strncmp()"
JIRA: https://issues.redhat.com/browse/RHEL-6297

commit 469d258d9e112fb7ed51a3b35c0c85ee106331e8
Author: Vladimir Oltean <vladimir.oltean@nxp.com>
Date:   Fri Nov 25 12:53:04 2022 +0200

    Revert "net: stmmac: use sysfs_streq() instead of strncmp()"

    This reverts commit f72cd76b05ea1ce9258484e8127932d0ea928f22.
    This patch is so broken, it hurts. Apparently no one reviewed it and it
    passed the build testing (because the code was compiled out), but it was
    obviously never compile-tested, since it produces the following build
    error, due to an incomplete conversion where an extra argument was left,
    although the function being called was left:

    stmmac_main.c: In function ‘stmmac_cmdline_opt’:
    stmmac_main.c:7586:28: error: too many arguments to function ‘sysfs_streq’
     7586 |                 } else if (sysfs_streq(opt, "pause:", 6)) {
          |                            ^~~~~~~~~~~
    In file included from ../include/linux/bitmap.h:11,
                     from ../include/linux/cpumask.h:12,
                     from ../include/linux/smp.h:13,
                     from ../include/linux/lockdep.h:14,
                     from ../include/linux/mutex.h:17,
                     from ../include/linux/notifier.h:14,
                     from ../include/linux/clk.h:14,
                     from ../drivers/net/ethernet/stmicro/stmmac/stmmac_main.c:17:
    ../include/linux/string.h:185:13: note: declared here
      185 | extern bool sysfs_streq(const char *s1, const char *s2);
          |             ^~~~~~~~~~~

    What's even worse is that the patch is flat out wrong. The stmmac_cmdline_opt()
    function does not parse sysfs input, but cmdline input such as
    "stmmaceth=tc:1,pause:1". The pattern of using strsep() followed by
    strncmp() for such strings is not unique to stmmac, it can also be found
    mainly in drivers under drivers/video/fbdev/.

    With strncmp("tc:", 3), the code matches on the "tc:1" token properly.
    With sysfs_streq("tc:"), it doesn't.

    Fixes: f72cd76b05ea ("net: stmmac: use sysfs_streq() instead of strncmp()")
    Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
    Acked-by: Maciej Fijalkowski <maciej.fijalkowski@intel.com>
    Link: https://lore.kernel.org/r/20221125105304.3012153-1-vladimir.oltean@nxp.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>