sunrpc: Fix compilation error (`make W=1`) when dprintk() is no-op
JIRA: https://issues.redhat.com/browse/RHEL-171581

commit 6f57293abb8d087de830dd3f02e66d94b3e59973
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Wed Feb 4 21:21:51 2026 +0100

    sunrpc: Fix compilation error (`make W=1`) when dprintk() is no-op

    Clang compiler is not happy about set but unused variables:

    .../flexfilelayout/flexfilelayoutdev.c:56:9: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
    .../flexfilelayout/flexfilelayout.c:1505:6: error: variable 'err' set but not used [-Werror,-Wunused-but-set-variable]
    .../nfs4proc.c:9244:12: error: variable 'ptr' set but not used [-Werror,-Wunused-but-set-variable]

    Fix these by forwarding parameters of dprintk() to no_printk().
    The positive side-effect is a format-string checker enabled even for the cases
    when dprintk() is no-op.

    Fixes: d67ae825a59d ("pnfs/flexfiles: Add the FlexFile Layout Driver")
    Fixes: fc931582c260 ("nfs41: create_session operation")
    Acked-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Olga Kornievskaia <okorniev@redhat.com>