bpf: Add __bpf_kfunc tag for marking kernel functions as kfuncs
Bugzilla: https://bugzilla.redhat.com/2178930

commit 57e7c169cd6afa093d858b8edfb9bceaf2e1c93b
Author: David Vernet <void@manifault.com>
Date:   Wed Feb 1 11:30:13 2023 -0600

    bpf: Add __bpf_kfunc tag for marking kernel functions as kfuncs
    
    kfuncs are functions defined in the kernel, which may be invoked by BPF
    programs. They may or may not also be used as regular kernel functions,
    implying that they may be static (in which case the compiler could e.g.
    inline it away, or elide one or more arguments), or it could have
    external linkage, but potentially be elided in an LTO build if a
    function is observed to never be used, and is stripped from the final
    kernel binary.
    
    This has already resulted in some issues, such as those discussed in [0]
    wherein changes in DWARF that identify when a parameter has been
    optimized out can break BTF encodings (and in general break the kfunc).
    
    [0]: https://lore.kernel.org/all/1675088985-20300-2-git-send-email-alan.maguire@oracle.com/
    
    We therefore require some convenience macro that kfunc developers can
    use just add to their kfuncs, and which will prevent all of the above
    issues from happening. This is in contrast with what we have today,
    where some kfunc definitions have "noinline", some have "__used", and
    others are static and have neither.
    
    Note that longer term, this mechanism may be replaced by a macro that
    more closely resembles EXPORT_SYMBOL_GPL(), as described in [1]. For
    now, we're going with this shorter-term approach to fix existing issues
    in kfuncs.
    
    [1]: https://lore.kernel.org/lkml/Y9AFT4pTydKh+PD3@maniforge.lan/
    
    Note as well that checkpatch complains about this patch with the
    following:
    
    ERROR: Macros with complex values should be enclosed in parentheses
    +#define __bpf_kfunc __used noinline
    
    There seems to be a precedent for using this pattern in other places
    such as compiler_types.h (see e.g. __randomize_layout and noinstr), so
    it seems appropriate.
    
    Signed-off-by: David Vernet <void@manifault.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Stanislav Fomichev <sdf@google.com>
    Link: https://lore.kernel.org/bpf/20230201173016.342758-2-void@manifault.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>