mlxsw: spectrum_switchdev: Use extack in bridge port flag validation
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2196494

commit 136b8dfbd784e8aa86e1bb9ade7fc41927a3839e
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Tue Nov 8 11:47:16 2022 +0100

    mlxsw: spectrum_switchdev: Use extack in bridge port flag validation

    Propagate extack to mlxsw_sp_port_attr_br_pre_flags_set() in order to
    communicate error messages related to bridge port flag validation.

    Example:

     # bridge link set dev swp1 locked on
     Error: mlxsw_spectrum: Unsupported bridge port flag.

    More error messages will be added in subsequent patches.

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>