net: psample: fix build error when CONFIG_INET is not enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 07a7f30819475a6f058df6bba5150c50e7942cfb
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-310.el8/07a7f308.failed

Fix psample build error when CONFIG_INET is not set/enabled by
bracketing the tunnel code in #ifdef CONFIG_NET / #endif.

../net/psample/psample.c: In function ‘__psample_ip_tun_to_nlattr’:
../net/psample/psample.c:216:25: error: implicit declaration of function ‘ip_tunnel_info_opts’; did you mean ‘ip_tunnel_info_opts_set’? [-Werror=implicit-function-declaration]

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Yotam Gigi <yotam.gi@gmail.com>
	Cc: Cong Wang <xiyou.wangcong@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 07a7f30819475a6f058df6bba5150c50e7942cfb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/psample/psample.c