selftests: KVM: Explicitly use movq to read xmm registers
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Oliver Upton <oupton@google.com>
commit 386ca9d7fd189b641bc5a82871e38dea9f67af85

Compiling the KVM selftests with clang emits the following warning:

>> include/x86_64/processor.h:297:25: error: variable 'xmm0' is uninitialized when used here [-Werror,-Wuninitialized]
>>                return (unsigned long)xmm0;

where xmm0 is accessed via an uninitialized register variable.

Indeed, this is a misuse of register variables, which really should only
be used for specifying register constraints on variables passed to
inline assembly. Rather than attempting to read xmm registers via
register variables, just explicitly perform the movq from the desired
xmm register.

Fixes: 783e9e51266e ("kvm: selftests: add API testing infrastructure")
	Signed-off-by: Oliver Upton <oupton@google.com>
Message-Id: <20210924005147.1122357-1-oupton@google.com>
	Reviewed-by: Ricardo Koller <ricarkol@google.com>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 386ca9d7fd189b641bc5a82871e38dea9f67af85)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>