crypto: ccp - reduce stack usage in ccp_run_aes_gcm_cmd
JIRA: https://issues.redhat.com/browse/RHEL-106910
Upstream Status: merged into the linux.git

commit a71475582ada92ba021852bf3c2b40ab3718549b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 14 16:59:12 2025 +0200

    crypto: ccp - reduce stack usage in ccp_run_aes_gcm_cmd

    A number of functions in this file have large structures on the stack,
    ccp_run_aes_gcm_cmd() being the worst, in particular when KASAN
    is enabled on gcc:

    drivers/crypto/ccp/ccp-ops.c: In function 'ccp_run_sha_cmd':
    drivers/crypto/ccp/ccp-ops.c:1833:1: error: the frame size of 1136 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
    drivers/crypto/ccp/ccp-ops.c: In function 'ccp_run_aes_gcm_cmd':
    drivers/crypto/ccp/ccp-ops.c:914:1: error: the frame size of 1632 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Avoid the issue by using dynamic memory allocation in the worst one
    of these.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Tom Lendacky <thomas.lendacky@amd.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>