wifi: iwlwifi: work around -Wenum-compare-conditional warning
JIRA: https://issues.redhat.com/browse/RHEL-79792

commit cadae7ead4434d6c4ca15fb74cc729fb868fcca3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Oct 18 15:18:34 2024 +0000

    wifi: iwlwifi: work around -Wenum-compare-conditional warning
    
    This is one of only three -Wenum-compare-conditional warnings we get
    in randconfig builds:
    
    drivers/net/wireless/intel/iwlwifi/mvm/sta.c:4331:17: error: conditional expression between different enumeration types ('enum iwl_fw_sta_type' and 'enum iwl_sta_type') [-Werror,-Wenum-compare-conditional]
     4331 |         u32 type = mld ? STATION_TYPE_PEER : IWL_STA_LINK;
          |                        ^ ~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~
    
    This is a false positive since the code works as intended, but the
    warning is otherwise sensible, so slightly rewrite it in order to
    not trigger the warning.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20241018151841.3821671-1-arnd@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>