octeontx2-pf: select CONFIG_NET_DEVLINK
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2040643

commit 9cbc3367968de69017a87a1118b62490ac1bdd0a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Nov 4 14:34:42 2021 +0100

    octeontx2-pf: select CONFIG_NET_DEVLINK

    The octeontx2 pf nic driver failsz to link when the devlink support
    is not reachable:

    aarch64-linux-ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_devlink.o: in function `otx2_dl_mcam_count_get':
    otx2_devlink.c:(.text+0x10): undefined reference to `devlink_priv'
    aarch64-linux-ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_devlink.o: in function `otx2_dl_mcam_count_validate':
    otx2_devlink.c:(.text+0x50): undefined reference to `devlink_priv'
    aarch64-linux-ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_devlink.o: in function `otx2_dl_mcam_count_set':
    otx2_devlink.c:(.text+0xd0): undefined reference to `devlink_priv'
    aarch64-linux-ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_devlink.o: in function `otx2_devlink_info_get':
    otx2_devlink.c:(.text+0x150): undefined reference to `devlink_priv'

    This is already selected by the admin function driver, but not the
    actual nic, which might be built-in when the af driver is not.

    Fixes: 2da489432747 ("octeontx2-pf: devlink params support to set mcam entry count")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>