objtool: Also include tools/include/uapi
JIRA: https://issues.redhat.com/browse/RHEL-114921

commit 32b504854bd96f707a03c6ddecb0af9d7fbc4775
Author: HONG Yifan <elsk@google.com>
Date:   Tue Oct 8 23:47:17 2024 +0000

    objtool: Also include tools/include/uapi

    When building objtool against a sysroot that contains a stripped down
    version of the UAPI headers, the following error happens:

        In file included from arch/x86/decode.c:10:
        In file included from .../tools/arch/x86/include/asm/insn.h:10:
        In file included from <sysroot>/include/asm/byteorder.h:9:
        In file included from <sysroot>/include/linux/byteorder/little_endian.h:15:
        In file included from <sysroot>/include/linux/stddef.h:9:
        In file included from .../tools/include/linux/compiler_types.h:36:
        .../tools/include/linux/compiler-gcc.h:3:2: error: "Please don't include <linux/compiler-gcc.h> directly, include <linux/compiler.h> instead."
            3 | #error "Please don't include <linux/compiler-gcc.h> directly, include <linux/compiler.h> instead."
            |  ^
        1 error generated.

    As hinted by the error, this is because <sysroot>/include/linux/stddef.h
    (a stripped-down version of uapi/include/linux/stddef.h) includes
    linux/compiler_types.h directly. However, this gets resolved to
    tools/include/linux/compiler_types.h, which is not expected to be
    included directly.

    To resolve this, I added tools/include/uapi to the include paths when
    building objtool. With this trick, linux/stddef.h is resolved to
    tools/include/uapi/linux/stddef.h, which doesn't include
    linux/compiler_types.h.

    Signed-off-by: HONG Yifan <elsk@google.com>
    Signed-off-by: Josh Poimboeuf <jpoimboe@kernel.org>

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>