drm: import DMA_BUF module namespace
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
Rebuild_CHGLOG: - Revert "drm: import DMA_BUF module namespace" (Michel Dänzer) [2041811]
Rebuild_FUZZ: 88.89%
commit-author Marcel Ziswiler <marcel.ziswiler@toradex.com>
commit 675053115e4e809643e12ca817dc9147562a70d6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-425.3.1.el8/67505311.failed

Today's -next fails building arm64 defconfig as follows:

ERROR: modpost: module drm_cma_helper uses symbol dma_buf_vunmap from
 namespace DMA_BUF, but does not import it.
ERROR: modpost: module drm_cma_helper uses symbol dma_buf_vmap from
 namespace DMA_BUF, but does not import it.

Fix this by importing DMA_BUF namespace into drm_cma_helper.ko. Also
fix the problem with drm_shmem_helper.ko.

	Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
Fixes: 4b2b5e142ff4 ("drm: Move GEM memory managers into modules")
	Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
	Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
Link: https://patchwork.freedesktop.org/patch/msgid/20211027212506.3418521-1-marcel@ziswiler.com
(cherry picked from commit 675053115e4e809643e12ca817dc9147562a70d6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/gpu/drm/drm_gem_cma_helper.c
#	drivers/gpu/drm/drm_gem_shmem_helper.c