PCI: controller: Use dev_fwnode() instead of of_fwnode_handle()
JIRA: https://issues.redhat.com/browse/RHEL-107898
Upstream Status: a103d2dede5683dabbac2c3374bc24b6a9434478

commit a103d2dede5683dabbac2c3374bc24b6a9434478
Author: Jiri Slaby (SUSE) <jirislaby@kernel.org>
Date:   Wed Jun 11 12:43:44 2025 +0200

    PCI: controller: Use dev_fwnode() instead of of_fwnode_handle()

    All irq_domain functions now accept fwnode instead of of_node. But many
    PCI controllers still extract dev to of_node and then of_node to fwnode.

    Instead, clean this up and simply use the dev_fwnode() helper to extract
    fwnode directly from dev. Internally, it still does dev => of_node =>
    fwnode steps, but it's now hidden from the users.

    In the case of altera, this also removes an unused 'node' variable that is
    only used when CONFIG_OF is enabled:

      drivers/pci/controller/pcie-altera.c: In function 'altera_pcie_init_irq_domain':
      drivers/pci/controller/pcie-altera.c:855:29: error: unused variable 'node' [-Werror=unused-variable]
        855 |         struct device_node *node = dev->of_node;

    Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>    # altera
    [bhelgaas: squash together, rebase to precede msi-parent]
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Link: https://patch.msgid.link/20250521163329.2137973-1-arnd@kernel.org
    Link: https://patch.msgid.link/20250611104348.192092-16-jirislaby@kernel.org
    Link: https://patch.msgid.link/20250723065907.1841758-1-jirislaby@kernel.org

Signed-off-by: Myron Stowe <mstowe@redhat.com>