soc: imx: imx8m-blk-ctrl: Use dev_pm_domain_attach_by_name
Bugzilla: https://bugzilla.redhat.com/2182875

commit 31ef51a4ae5e6e6745aae119a2836d7386652a2b
Author: Jindong Yue <jindong.yue@nxp.com>
Date:   Wed Mar 1 21:05:54 2023 +0800

    soc: imx: imx8m-blk-ctrl: Use dev_pm_domain_attach_by_name

    The genpd_dev_pm_attach_by_name() is not exported, following error
    occurs when building imx8m-blk-ctrl as a module:

    ERROR: modpost: "genpd_dev_pm_attach_by_name" [drivers/soc/imx/imx8m-blk-ctrl.ko] undefined!

    Fix this by using dev_pm_domain_attach_by_name() instead.

    Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    Reviewed-by: Marco Felsch <m.felsch@pengutronix.de>
    Signed-off-by: Shawn Guo <shawnguo@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>