sched/core: Annotate curr pointer in rq with __rcu
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Madhuparna Bhowmik <madhuparnabhowmik10@gmail.com>
commit 4104a562e0ca62e971089db9d3c47794a0d7d4eb

This patch fixes the following sparse warnings in sched/core.c
and sched/membarrier.c:

  kernel/sched/core.c:2372:27: error: incompatible types in comparison expression
  kernel/sched/core.c:4061:17: error: incompatible types in comparison expression
  kernel/sched/core.c:6067:9: error: incompatible types in comparison expression
  kernel/sched/membarrier.c:108:21: error: incompatible types in comparison expression
  kernel/sched/membarrier.c:177:21: error: incompatible types in comparison expression
  kernel/sched/membarrier.c:243:21: error: incompatible types in comparison expression

	Signed-off-by: Madhuparna Bhowmik <madhuparnabhowmik10@gmail.com>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lkml.kernel.org/r/20200201125803.20245-1-madhuparnabhowmik10@gmail.com
(cherry picked from commit 4104a562e0ca62e971089db9d3c47794a0d7d4eb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>