libbpf: Fix build warning on ref_ctr_off for 32-bit architectures
Bugzilla: https://bugzilla.redhat.com/2178930

commit 1520e8466d683b6c5e1aa53aa65165ebd5da46cf
Author: Khem Raj <raj.khem@gmail.com>
Date:   Mon Dec 19 11:15:26 2022 -0800

    libbpf: Fix build warning on ref_ctr_off for 32-bit architectures
    
    Clang warns on 32-bit ARM on this comparision:
    
    libbpf.c:10497:18: error: result of comparison of constant 4294967296 with expression of type 'size_t' (aka 'unsigned int') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
            if (ref_ctr_off >= (1ULL << PERF_UPROBE_REF_CTR_OFFSET_BITS))
                ~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Typecast ref_ctr_off to __u64 in the check conditional, it is false on
    32bit anyways.
    
    Signed-off-by: Khem Raj <raj.khem@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20221219191526.296264-1-raj.khem@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>