tools/testing/nvdimm: Disable "missing prototypes / declarations" warnings
JIRA: https://issues.redhat.com/browse/RHEL-23824

commit c97dac57c804b53eab492ca0230d86356729d633
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Tue Jan 16 13:17:23 2024 -0800

    tools/testing/nvdimm: Disable "missing prototypes / declarations" warnings
    
    Prevent warnings of the form:
    
    tools/testing/nvdimm/config_check.c:4:6: error: no previous prototype
    for ‘check’ [-Werror=missing-prototypes]
    
    ...by locally disabling some warnings.
    
    It turns out that:
    
    Commit 0fcb70851fbf ("Makefile.extrawarn: turn on missing-prototypes globally")
    
    ...in addition to expanding in-tree coverage, also impacts out-of-tree
    module builds like those in tools/testing/nvdimm/.
    
    Filter out the warning options on unit test code that does not effect
    mainline builds.
    
    Reviewed-by: Alison Schofield <alison.schofield@intel.com>
    Link: https://lore.kernel.org/r/170543984331.460832.1780246477583036191.stgit@dwillia2-xfh.jf.intel.com
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>