ASoC: meson: axg-spdifout: select SND_PCM_IEC958
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: meson: axg-spdifout: select SND_PCM_IEC958 (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.12%
commit-author Arnd Bergmann <arnd@arndb.de>
commit a241c3d95b8b985834d218eedde3923ed683e862

When CONFIG_SND_PCM_IEC958 is disabled, we get a link error for the
new driver:

sound/soc/meson/axg-spdifout.o: In function `axg_spdifout_hw_params':
axg-spdifout.c:(.text+0x650): undefined reference to `snd_pcm_create_iec958_consumer_hw_params'

The other users use 'select', so we should do the same here.

Fixes: 53eb4b7aaa04 ("ASoC: meson: add axg spdif output")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Jerome Brunet <jbrunet@baylibre.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit a241c3d95b8b985834d218eedde3923ed683e862)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>