powerpc/crypto: fix missing skcipher dependency for aes-gcm-p10
JIRA: https://issues.redhat.com/browse/RHEL-11208

commit 9d6e1c21e1be4643628ee343e0b8d79828485ba2
Author: Omar Sandoval <osandov@fb.com>
Date:   Mon Jul 10 09:46:46 2023 -0700

    powerpc/crypto: fix missing skcipher dependency for aes-gcm-p10

    My stripped down configuration fails to build with:

      ERROR: modpost: "skcipher_walk_aead_encrypt" [arch/powerpc/crypto/aes-gcm-p10-crypto.ko] undefined!
      ERROR: modpost: "skcipher_walk_done" [arch/powerpc/crypto/aes-gcm-p10-crypto.ko] undefined!
      ERROR: modpost: "skcipher_walk_aead_decrypt" [arch/powerpc/crypto/aes-gcm-p10-crypto.ko] undefined!

    Fix it by selecting CRYPTO_SKCIPHER.

    Signed-off-by: Omar Sandoval <osandov@fb.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/c55ad70799e027a3d2756b85ccadc0af52ae8915.1689007370.git.osandov@osandov.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>