util: constant -1 with expression of type char
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit e9ffa312ff06cde77c4a6395c411c5ebde738f04
Author: Yunseong Kim <yskelg@gmail.com>
Date: Thu Jun 20 05:34:29 2024 +0900

description
===========
This patch resolve following warning.

  tools/perf/util/evsel.c:1620:9: error: result of comparison of constant
   -1 with expression of type 'char' is always false
   -Werror,-Wtautological-constant-out-of-range-compare
   1620 |                 if (c == -1)
        |                     ~ ^  ~~

    Signed-off-by: Yunseong Kim <yskelg@gmail.com>
    Reviewed-by: Ian Rogers <irogers@google.com>
    Cc: Ravi Bangoria <ravi.bangoria@amd.com>
    Cc: Austin Kim <austindh.kim@gmail.com>
    Cc: shjy180909@gmail.com
    Cc: Ze Gao <zegao2021@gmail.com>
    Cc: Leo Yan <leo.yan@linux.dev>
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>
    Link: https://lore.kernel.org/r/20240619203428.6330-2-yskelg@gmail.com

Signed-off-by: Michael Petlan <mpetlan@redhat.com>