dma-mapping: Fix build error unused-value
Bugzilla: https://bugzilla.redhat.com/2112024
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 50d6281ce9b8412f7ef02d1bc9d23aa62ae0cf98
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Thu Jun 30 20:35:28 2022 +0800

    dma-mapping: Fix build error unused-value

    If CONFIG_DMA_DECLARE_COHERENT is not set,
    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu- will be failed, like this:

    drivers/remoteproc/remoteproc_core.c: In function ‘rproc_rvdev_release’:
    ./include/linux/dma-map-ops.h:182:42: error: statement with no effect [-Werror=unused-value]
     #define dma_release_coherent_memory(dev) (0)
					      ^
    drivers/remoteproc/remoteproc_core.c:464:2: note: in expansion of macro ‘dma_release_coherent_memory’
      dma_release_coherent_memory(dev);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    The return type of function dma_release_coherent_memory in CONFIG_DMA_DECLARE_COHERENT area is void, so in !CONFIG_DMA_DECLARE_COHERENT area it should neither return any value nor be defined as zero.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: e61c451476e6 ("dma-mapping: Add dma_release_coherent_memory to DMA API")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Link: https://lore.kernel.org/r/20220630123528.251181-1-renzhijie2@huawei.com
    Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>

(cherry picked from commit 50d6281ce9b8412f7ef02d1bc9d23aa62ae0cf98)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>