cpumask: make cpumask_next_wrap available without smp
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Willem de Bruijn <willemb@google.com>
commit 9af18e56d43ca4864ce65c3542c513827c2697de

The kbuild robot shows build failure on machines without CONFIG_SMP:

  drivers/net/virtio_net.c:1916:10: error:
    implicit declaration of function 'cpumask_next_wrap'

cpumask_next_wrap is exported from lib/cpumask.o, which has

    lib-$(CONFIG_SMP) += cpumask.o

same as other functions, also define it as static inline in the
NR_CPUS==1 branch in include/linux/cpumask.h.

If wrap is true and next == start, return nr_cpumask_bits, or 1.
Else wrap across the range of valid cpus, here [0].

Fixes: 2ca653d607ce ("virtio_net: Stripe queue affinities across cores.")
	Signed-off-by: Willem de Bruijn <willemb@google.com>
	Tested-by: Krzysztof Kozlowski <krzk@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 9af18e56d43ca4864ce65c3542c513827c2697de)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>