ethtool: reduce stack usage with clang
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 3499e87ea0413ee5b2cc028f4c8ed4d424bc7f98

clang inlines the dev_ethtool() more aggressively than gcc does, leading
to a larger amount of used stack space:

net/core/ethtool.c:2536:24: error: stack frame size of 1216 bytes in function 'dev_ethtool' [-Werror,-Wframe-larger-than=]

Marking the sub-functions that require the most stack space as
noinline_for_stack gives us reasonable behavior on all compilers.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Michal Kubecek <mkubecek@suse.cz>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 3499e87ea0413ee5b2cc028f4c8ed4d424bc7f98)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>