vduse: avoid adding implicit padding
JIRA: https://redhat.atlassian.net/browse/RHEL-94833

commit ebcff9dacaf2c1418f8bc927388186d7d3674603
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 2 23:48:07 2026 +0100

    vduse: avoid adding implicit padding

    The vduse_iova_range_v2 and vduse_iotlb_entry_v2 structures are both
    defined in a way that adds implicit padding and is incompatible between
    i386 and x86_64 userspace because of the different structure alignment
    requirements. Building the header with -Wpadded shows these new warnings:

    vduse.h:305:1: error: padding struct size to alignment boundary with 4 bytes [-Werror=padded]
    vduse.h:374:1: error: padding struct size to alignment boundary with 4 bytes [-Werror=padded]

    Change the amount of padding in these two structures to align them to
    64 bit words and avoid those problems. Since the v1 vduse_iotlb_entry
    already has an inconsistent size, do not attempt to reuse the structure
    but rather list the members indiviudally, with a fixed amount of
    padding.

    Fixes: 079212f6877e ("vduse: add vq group asid support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
    Message-Id: <20260202224835.559538-1-arnd@kernel.org>

Signed-off-by: Koushik Dutta <kdutta@redhat.com>