marvell: octeontx2: build error: unknown type name 'u64'
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2040643

commit 6312d52838b21f5c4a5afa1269a00df4364fd354
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Wed Oct 13 15:57:43 2021 +0200

    marvell: octeontx2: build error: unknown type name 'u64'

    Building an allmodconfig kernel arm64 kernel, the following build error
    shows up:

    In file included from drivers/crypto/marvell/octeontx2/cn10k_cpt.c:4:
    include/linux/soc/marvell/octeontx2/asm.h:38:15: error: unknown type name 'u64'
       38 | static inline u64 otx2_atomic64_fetch_add(u64 incr, u64 *ptr)
          |               ^~~

    Include linux/types.h in asm.h so the compiler knows what the type
    'u64' are.

    Fixes: af3826db74d1 ("octeontx2-pf: Use hardware register for CQE count")
    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
    Link: https://lore.kernel.org/r/20211013135743.3826594-1-anders.roxell@linaro.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>