selftests: hsr: Fix "File exists" errors for hsr_ping
JIRA: https://issues.redhat.com/browse/RHEL-127794

commit 21a22ed618d072a47597e63ee591973c18524880
Author: Geliang Tang <geliang@kernel.org>
Date:   Wed May 22 18:45:04 2024 +0800

    selftests: hsr: Fix "File exists" errors for hsr_ping
    
    The hsr_ping test reports the following errors:
    
     INFO: preparing interfaces for HSRv0.
     INFO: Initial validation ping.
     INFO: Longer ping test.
     INFO: Cutting one link.
     INFO: Delay the link and drop a few packages.
     INFO: All good.
     INFO: preparing interfaces for HSRv1.
     RTNETLINK answers: File exists
     RTNETLINK answers: File exists
     RTNETLINK answers: File exists
     RTNETLINK answers: File exists
     RTNETLINK answers: File exists
     RTNETLINK answers: File exists
     Error: ipv4: Address already assigned.
     Error: ipv6: address already assigned.
     Error: ipv4: Address already assigned.
     Error: ipv6: address already assigned.
     Error: ipv4: Address already assigned.
     Error: ipv6: address already assigned.
     INFO: Initial validation ping.
    
    That is because the cleanup code for the 2nd round test before
    "setup_hsr_interfaces 1" is removed incorrectly in commit 680fda4f6714
    ("test: hsr: Remove script code already implemented in lib.sh").
    
    This patch fixes it by re-setup the namespaces using
    
            setup_ns ns1 ns2 ns3
    
    command before "setup_hsr_interfaces 1". It deletes previous namespaces
    and create new ones.
    
    Fixes: 680fda4f6714 ("test: hsr: Remove script code already implemented in lib.sh")
    Reviewed-by: Hangbin Liu <liuhangbin@gmail.com>
    Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
    Link: https://lore.kernel.org/r/6485d3005f467758d49f0f313c8c009759ba6b05.1716374462.git.tanggeliang@kylinos.cn
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Felix Maurer <fmaurer@redhat.com>