powerpc/mm/book3s64: Fix build error with SPARSEMEM disabled
JIRA: https://issues.redhat.com/browse/RHEL-55462

This patch is a backport of the following upstream commit:
commit f1424755db913c5971686537381588261cdfd1ee
Author: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
Date:   Mon Aug 28 13:16:57 2023 +0530

    powerpc/mm/book3s64: Fix build error with SPARSEMEM disabled

    With CONFIG_SPARSEMEM disabled the below kernel build error is observed.

     arch/powerpc/mm/init_64.c:477:38: error: use of undeclared identifier 'SECTION_SIZE_BITS'

    CONFIG_MEMORY_HOTPLUG depends on CONFIG_SPARSEMEM and it is more clear
    to describe the code dependency in terms of MEMORY_HOTPLUG. Outside
    memory hotplug the kernel uses memory_block_size for kernel directmap.
    Instead of depending on SECTION_SIZE_BITS to compute the direct map
    page size, add a new #define which defaults to 16M(same as existing
    SECTION_SIZE)

    Fixes: 4d15721177d5 ("powerpc/mm: Cleanup memory block size probing")
    Signed-off-by: "Aneesh Kumar K.V" <aneesh.kumar@linux.ibm.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202308251532.k9PpWEAD-lkp@intel.com/
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/20230828074658.59553-1-aneesh.kumar@linux.ibm.com

Signed-off-by: Audra Mitchell <audra@redhat.com>