ALSA: hda/ca0132: Remove double parentheses
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit a16fbb85c78a3ce56dc4515ffb8632b82cc969c7

The extra pairs of parantheses are not needed and causes clang to
generate warnings like this:

sound/pci/hda/patch_ca0132.c:1171:14: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((buffer == NULL))
             ~~~~~~~^~~~~~~
sound/pci/hda/patch_ca0132.c:1171:14: note: remove extraneous parentheses around the comparison to silence this warning
        if ((buffer == NULL))
            ~       ^      ~
sound/pci/hda/patch_ca0132.c:1171:14: note: use '=' to turn this equality comparison into an assignment
        if ((buffer == NULL))

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit a16fbb85c78a3ce56dc4515ffb8632b82cc969c7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>