perf probe: Fix to handle optimized not-inlined functions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Fix to handle optimized not-inlined functions (Jiri Olsa) [1222189]
Rebuild_FUZZ: 95.41%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit e1ecbbc3fa834cc6b4b344edb1968e734d57189b

Fix to handle optimized no-inline functions which have only function
definition but no actual instance at that point.

To fix this problem, we need to find actual instance of the function.

Without this patch:
  ----
  # perf probe -a __up
  Failed to get entry address of __up.
    Error: Failed to add events.
  # perf probe -L __up
  Specified source line is not found.
    Error: Failed to show lines.
  ----

With this patch:
  ----
  # perf probe -a __up
  Added new event:
    probe:__up           (on __up)

  You can now use it in all perf tools, such as:

          perf record -e probe:__up -aR sleep 1

  # perf probe -L __up
  <__up@/home/fedora/ksrc/linux-3/kernel/locking/semaphore.c:0>
        0  static noinline void __sched __up(struct semaphore *sem)
           {
                  struct semaphore_waiter *waiter = list_first_entry(&sem->wait_
                                                          struct semaphore_waite
        4         list_del(&waiter->list);
        5         waiter->up = true;
        6         wake_up_process(waiter->task);
        7  }
  ----

	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/20150130093744.30575.43290.stgit@localhost.localdomain
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit e1ecbbc3fa834cc6b4b344edb1968e734d57189b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>