HID: intel-ish-hid: Fix build error for COMPILE_TEST
JIRA: https://issues.redhat.com/browse/RHEL-65221
Upstream status: v6.12-rc7

commit 2360497238261f17d4a3f6cbc02d6dbd8951c23c
Author: Zhang Lixu <lixu.zhang@intel.com>
Date:   Thu May 23 09:14:01 2024 +0800

    HID: intel-ish-hid: Fix build error for COMPILE_TEST

    kernel test robot reported build error due to a pointer type mismatch:

      .../ishtp/loader.c:172:8: error: incompatible pointer types passing
      '__le64 *' (aka 'unsigned long long *') to parameter of type
      'dma_addr_t *' (aka 'unsigned int *')

    The issue arises because the driver, which is primarily intended for
    x86-64, is also built for i386 when COMPILE_TEST is enabled.

    Resolve type mismatch by using a temporary dma_addr_t variable to hold
    the DMA address. Populate this temporary variable in dma_alloc_coherent()
    function, and then convert and store the address in the
    fragment->fragment_tbl[i].ddr_adrs field in the correct format.
    Similarly, convert the ddr_adrs field back to dma_addr_t when freeing
    the DMA buffer with dma_free_coherent().

    Fixes: 579a267e4617 ("HID: intel-ish-hid: Implement loading firmware from host feature")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202405201313.SAStVPrT-lkp@intel.com/
    Signed-off-by: Zhang Lixu <lixu.zhang@intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>