HID: i2c-hid: fix format string mismatch
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit dc5f9f55502e13ba05731d5046a14620aa2ff456

clang doesn't like printing a 32-bit integer using %hX format string:

drivers/hid/i2c-hid/i2c-hid-core.c:994:18: error: format specifies type 'unsigned short' but the argument has type '__u32' (aka 'unsigned int') [-Werror,-Wformat]
                 client->name, hid->vendor, hid->product);
                               ^~~~~~~~~~~
drivers/hid/i2c-hid/i2c-hid-core.c:994:31: error: format specifies type 'unsigned short' but the argument has type '__u32' (aka 'unsigned int') [-Werror,-Wformat]
                 client->name, hid->vendor, hid->product);
                                            ^~~~~~~~~~~~

Use an explicit cast to truncate it to the low 16 bits instead.

Fixes: 9ee3e06610fd ("HID: i2c-hid: override HID descriptors for certain devices")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Nathan Chancellor <nathan@kernel.org>
	Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit dc5f9f55502e13ba05731d5046a14620aa2ff456)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>