perf genelf: Fix compiling with libelf on rv32
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit b828a23a75a012b9242166b78ff1c3ff2189f436
Author: Chen Pei <cp0613@linux.alibaba.com>
Date: Mon Apr 15 17:55:32 2024 +0800

description
===========
When cross-compiling perf with libelf, the following error occurred:

	In file included from tests/genelf.c:14:
	tests/../util/genelf.h:50:2: error: #error "unsupported architecture"
	50 | #error "unsupported architecture"
		|  ^~~~~
	tests/../util/genelf.h:59:5: warning: "GEN_ELF_CLASS" is not defined, evaluates to 0 [-Wundef]
	59 | #if GEN_ELF_CLASS == ELFCLASS64

Fix this by adding GEN-ELF-ARCH and GEN-ELF-CLASS definitions for rv32.

    Reviewed-by: Ian Rogers <irogers@google.com>
    Signed-off-by: Chen Pei <cp0613@linux.alibaba.com>
    Cc: Albert Ou <aou@eecs.berkeley.edu>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Paul Walmsley <paul.walmsley@sifive.com>
    Link: https://lore.kernel.org/r/20240415095532.4930-1-cp0613@linux.alibaba.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>