redhat: fix chronological order in the changelog file
Bugzilla: INTERNAL
Upstream Status: RHEL-only

Right now eg. when creating an src.rpm, rpm throws this:
error: %changelog not in descending chronological order

This is caused by last merge from 9-beta having included
new changelog entries with a date newer than the next
entry.

This is mostly a warning and does not prevent src.rpm creation
or the build. The problem is that tools like centpkg gets
confused treating it as a real error and eg. its build command
fails due it.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>