KVM: selftests: Fix shift of 32 bit unsigned int more than 32 bits
JIRA: https://issues.redhat.com/browse/RHEL-32435

Currrentl a 32 bit 1u value is being shifted more than 32 bits causing
overflow and incorrect checking of bits 32-63. Fix this by using the
BIT_ULL macro for shifting bits.

Detected by cppcheck:
sev_init2_tests.c:108:34: error: Shifting 32-bit value by 63 bits is
undefined behaviour [shiftTooManyBits]

Fixes: dfc083a181ba ("selftests: kvm: add tests for KVM_SEV_INIT2")
Signed-off-by: Colin Ian King <colin.i.king@gmail.com>
Link: https://lore.kernel.org/r/20240523154102.2236133-1-colin.i.king@gmail.com
Signed-off-by: Sean Christopherson <seanjc@google.com>
(cherry picked from commit d21b3c60d6e3917f7388db6bcc455f01c99ee42b)
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>