net/mlx5: avoid build warning for uniprocessor
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [netdrv] mlx5: avoid build warning for uniprocessor (Don Dutile) [1456694 1499362]
Rebuild_FUZZ: 95.45%
commit-author Arnd Bergmann <arnd@arndb.de>
commit f0d7ae95fff4ab444b8433f07afc4b077ef1a285

Building the driver with CONFIG_SMP disabled results in a harmless
warning:

ethernet/mellanox/mlx5/core/main.c: In function 'mlx5_irq_set_affinity_hint':
ethernet/mellanox/mlx5/core/main.c:615:6: error: unused variable 'irq' [-Werror=unused-variable]

It's better to express the conditional compilation using IS_ENABLED()
here, as that lets the compiler see what the intented use for the variable
is, and that it can be silently discarded.

Fixes: b665d98edc9a ("net/mlx5: Tolerate irq_set_affinity_hint() failures")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Saeed Mahameed <saeedm@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit f0d7ae95fff4ab444b8433f07afc4b077ef1a285)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>