wifi: brcmsmac: ampdu: remove unused suc_mpdu variable
Bugzilla: https://bugzilla.redhat.com/2196821

commit 2f73f04b7f93f031c94a5c473dd9b7f1cdf91bc0
Author: Tom Rix <trix@redhat.com>
Date:   Mon Mar 27 11:11:51 2023 -0400

    wifi: brcmsmac: ampdu: remove unused suc_mpdu variable
    
    clang with W=1 reports
    drivers/net/wireless/broadcom/brcm80211/brcmsmac/ampdu.c:848:5: error: variable
      'suc_mpdu' set but not used [-Werror,-Wunused-but-set-variable]
            u8 suc_mpdu = 0, tot_mpdu = 0;
               ^
    This variable is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230327151151.1771350-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>