x86/kvm: fix a missing-prototypes "vmread_error"
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [x86] kvm: fix a missing-prototypes "vmread_error" (Vitaly Kuznetsov) [1813987]
Rebuild_FUZZ: 95.65%
commit-author Qian Cai <cai@lca.pw>
commit 514ccc194971d0649e4e7ec8a9b3a6e33561d7bf
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-240.el8/514ccc19.failed

The commit 842f4be95899 ("KVM: VMX: Add a trampoline to fix VMREAD error
handling") removed the declaration of vmread_error() causes a W=1 build
failure with KVM_WERROR=y. Fix it by adding it back.

arch/x86/kvm/vmx/vmx.c:359:17: error: no previous prototype for 'vmread_error' [-Werror=missing-prototypes]
 asmlinkage void vmread_error(unsigned long field, bool fault)
                 ^~~~~~~~~~~~

	Signed-off-by: Qian Cai <cai@lca.pw>
Message-Id: <20200402153955.1695-1-cai@lca.pw>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 514ccc194971d0649e4e7ec8a9b3a6e33561d7bf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/x86/kvm/vmx/ops.h