KVM: arm64: nv: Select XARRAY_MULTI to fix build error
JIRA: https://issues.redhat.com/browse/RHEL-14347

commit 60046980bf60ed8846113b484d666a5fdf413be4
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Aug 16 14:09:49 2023 -0700

    KVM: arm64: nv: Select XARRAY_MULTI to fix build error

    populate_nv_trap_config() uses xa_store_range(), which is only built
    when XARRAY_MULTI is set, so select that symbol to prevent the build error.

    aarch64-linux-ld: arch/arm64/kvm/emulate-nested.o: in function `populate_nv_trap_config':
    emulate-nested.c:(.init.text+0x17c): undefined reference to `xa_store_range'

    Fixes: e58ec47bf68d ("KVM: arm64: nv: Add trap forwarding infrastructure")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Marc Zyngier <maz@kernel.org>
    Cc: Oliver Upton <oliver.upton@linux.dev>
    Cc: kvmarm@lists.linux.dev
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Will Deacon <will@kernel.org>
    Cc: linux-arm-kernel@lists.infradead.org
    Signed-off-by: Marc Zyngier <maz@kernel.org>
    Link: https://lore.kernel.org/r/20230816210949.17117-1-rdunlap@infradead.org

Signed-off-by: Shaoqin Huang <shahuang@redhat.com>