NTB: ntb_transport: Ensure qp->tx_mw_dma_addr is initaliazed
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Logan Gunthorpe <logang@deltatee.com>
commit 51cb8dbf13246a0b144bff01d7d617efe550a055

Dan Carpenter's static checker reported:

    drivers/ntb/ntb_transport.c:1926 ntb_transport_create_queue()
    error: we previously assumed 'qp->tx_dma_chan' could be null (see line 1872)

This is because the tx_mw_dma_addr is uninitialized in this function and
may be incorrectly released using a NULL DMA channel.

In practice this bug will not likely be seen. I'd guess you could hit
this if you loaded ntb_netdev with use_dma=True, then unloaded it and
loaded it again after setting the module parameter to use_dma=False.

To fix this, we simply ensure that tx_mw_dma_addr is always
initialized to zero. This is the safest in case any other part of the
code operates on it if it is non-zero.

Fixes: c59666bb32b9 ("NTB: ntb_transport: Ensure the destination buffer is mapped for TX DMA")
	Signed-off-by: Logan Gunthorpe <logang@deltatee.com>
	Cc: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Jon Mason <jdmason@kudzu.us>
(cherry picked from commit 51cb8dbf13246a0b144bff01d7d617efe550a055)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>