serial: 8250_tegra: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 933c9f190543007385ccf899e257328c525ce7e5
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:18 2023 -0500

    serial: 8250_tegra: Add explicit include for of.h

    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:

    drivers/tty/serial/8250/8250_tegra.c:68:15: error: implicit declaration of function 'of_alias_get_id' [-Werror=implicit-function-declaration]

    Reviewed-by: Jon Hunter <jonathanh@nvidia.com>
    Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
    Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Acked-by: Thierry Reding <treding@nvidia.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>