net: rfkill-gpio: Add explicit include for of.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Rob Herring <robh@kernel.org>
commit 75c7124ef3bafe0e9d1801d6449196dc3105df24

With linux/acpi.h no longer implicitly including of.h, add an explicit
include of of.h to fix the following error:

net/rfkill/rfkill-gpio.c:181:21: error: implicit declaration of function 'of_match_ptr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

	Acked-by: Johannes Berg <johannes@sipsolutions.net>
	Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
	Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Signed-off-by: Rob Herring <robh@kernel.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 75c7124ef3bafe0e9d1801d6449196dc3105df24)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>