dmaengine: dw-edma: Drop unused dchan2dev() and chan2dev()
JIRA: https://issues.redhat.com/browse/RHEL-117902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 06b80ad4ffa5e614e89f04dffc44b85377c7ee24
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Sun May 25 21:26:01 2025 +0200

    dmaengine: dw-edma: Drop unused dchan2dev() and chan2dev()

    Static functions dchan2dev() and chan2dev() are not used, W=1 build:

      dw-edma-core.c:27:16: error: unused function 'dchan2dev' [-Werror,-Wunused-function]
      dw-edma-core.c:33:16: error: unused function 'chan2dev' [-Werror,-Wunused-function]

    Fixes: e63d79d1ffcd ("dmaengine: Add Synopsys eDMA IP core driver")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20250525-dma-fixes-v1-1-89d06dac9bcb@linaro.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

(cherry picked from commit 06b80ad4ffa5e614e89f04dffc44b85377c7ee24)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>