virtio_test: fixup for vq reset
JIRA: https://issues.redhat.com/browse/RHEL-346

commit dbe449d8f8f2ef91af729f0adcc9bef785873168
Author: Xuan Zhuo <xuanzhuo@linux.alibaba.com>
Date:   Tue Aug 30 19:05:49 2022 +0800

    virtio_test: fixup for vq reset

    Fix virtio test compilation failure caused by vq reset.

    ../../drivers/virtio/virtio_ring.c: In function ‘vring_create_virtqueue_packed’:
    ../../drivers/virtio/virtio_ring.c:1999:8: error: ‘struct virtqueue’ has no member named ‘reset’
     1999 |  vq->vq.reset = false;
          |        ^
    ../../drivers/virtio/virtio_ring.c: In function ‘__vring_new_virtqueue’:
    ../../drivers/virtio/virtio_ring.c:2493:8: error: ‘struct virtqueue’ has no member named ‘reset’
     2493 |  vq->vq.reset = false;
          |        ^
    ../../drivers/virtio/virtio_ring.c: In function ‘virtqueue_resize’:
    ../../drivers/virtio/virtio_ring.c:2587:18: error: ‘struct virtqueue’ has no member named ‘num_max’
     2587 |  if (num > vq->vq.num_max)
          |                  ^
    ../../drivers/virtio/virtio_ring.c:2596:11: error: ‘struct virtio_device’ has no member named ‘config’
     2596 |  if (!vdev->config->disable_vq_and_reset)
          |           ^~
    ../../drivers/virtio/virtio_ring.c:2599:11: error: ‘struct virtio_device’ has no member named ‘config’
     2599 |  if (!vdev->config->enable_vq_after_reset)
          |           ^~
    ../../drivers/virtio/virtio_ring.c:2602:12: error: ‘struct virtio_device’ has no member named ‘config’
     2602 |  err = vdev->config->disable_vq_and_reset(_vq);
          |            ^~
    ../../drivers/virtio/virtio_ring.c:2614:10: error: ‘struct virtio_device’ has no member named ‘config’
     2614 |  if (vdev->config->enable_vq_after_reset(_vq))
          |          ^~
    make: *** [<builtin>: virtio_ring.o] Error 1

    Signed-off-by: Xuan Zhuo <xuanzhuo@linux.alibaba.com>
    Message-Id: <20220830110549.103168-1-xuanzhuo@linux.alibaba.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

Signed-off-by: Laurent Vivier <lvivier@redhat.com>