ALSA: hda: realtek: fix incorrect IS_REACHABLE() usage
JIRA: https://issues.redhat.com/browse/RHEL-80677

commit d0bbe332669c5db32c8c92bc967f8e7f8d460ddf
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Mar 4 15:25:55 2025 +0100

    ALSA: hda: realtek: fix incorrect IS_REACHABLE() usage

    The alternative path leads to a build error after a recent change:

    sound/pci/hda/patch_realtek.c: In function 'alc233_fixup_lenovo_low_en_micmute_led':
    include/linux/stddef.h:9:14: error: called object is not a function or function pointer
        9 | #define NULL ((void *)0)
          |              ^
    sound/pci/hda/patch_realtek.c:5041:49: note: in expansion of macro 'NULL'
     5041 | #define alc233_fixup_lenovo_line2_mic_hotkey    NULL
          |                                                 ^~~~
    sound/pci/hda/patch_realtek.c:5063:9: note: in expansion of macro 'alc233_fixup_lenovo_line2_mic_hotkey'
     5063 |         alc233_fixup_lenovo_line2_mic_hotkey(codec, fix, action);

    Using IS_REACHABLE() is somewhat questionable here anyway since it
    leads to the input code not working when the HDA driver is builtin
    but input is in a loadable module. Replace this with a hard compile-time
    dependency on CONFIG_INPUT. In practice this won't chance much
    other than solve the compiler error because it is rare to require
    sound output but no input support.

    Fixes: f603b159231b ("ALSA: hda/realtek - add supported Mic Mute LED for Lenovo platform")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250304142620.582191-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>