usb: typec: mux: intel: Add dependency on USB_COMMON
JIRA: https://issues.redhat.com/browse/RHEL-15948

commit ef7c4d8a90c64bac294363c6f67eb98246a162a2
Author: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Date: Mon, 31 Jul 2023 16:12:10 +0300

  This fixes an undefined reference to `usb_debug_root' issue
  when USB_COMMON is not enabled.

  Fixes: 0a453dc9f260 ("usb: typec: intel_pmc_mux: Expose IOM port status to debugfs")
  Reported-by: Randy Dunlap <rdunlap@infradead.org>
  Closes: https://lore.kernel.org/lkml/c3bb8781-676d-2448-cfbb-62e29f1f570b@infradead.org/
  Cc: Rajat Khandelwal <rajat.khandelwal@linux.intel.com>
  Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
  Tested-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
  Acked-by: Randy Dunlap <rdunlap@infradead.org>
  Link: https://lore.kernel.org/r/20230731131210.43158-1-heikki.krogerus@linux.intel.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>