perf/x86/intel/uncore: Fix the build on !CONFIG_PHYS_ADDR_T_64BIT
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit 02a08d78f5c429c7dc8e5b9417b4efb518b3d041
Author: Ingo Molnar <mingo@kernel.org>
Date: Thu Mar 3 08:57:08 2022 +0100

description
===========
'val2' is unused if !CONFIG_PHYS_ADDR_T_64BIT:

  arch/x86/events/intel/uncore_discovery.c:213:18: error: unused variable ‘val2’ [-Werror=unused-variable]

Signed-off-by: Michael Petlan <mpetlan@redhat.com>