crypto: qat - reduce stack size with KASAN
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [crypto] qat - reduce stack size with KASAN (Neil Horman) [1546163]
Rebuild_FUZZ: 89.47%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 8c9478a400b7efdeab89797cfb77e4e845fb34fb

Passing the register value by reference here leads a large amount of stack being
used when CONFIG_KASAN is enabled:

drivers/crypto/qat/qat_common/qat_hal.c: In function 'qat_hal_exec_micro_inst.constprop':
drivers/crypto/qat/qat_common/qat_hal.c:963:1: error: the frame size of 1792 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

Changing the register-read function to return the value instead reduces the stack
size to around 800 bytes, most of which is for the 'savuwords' array. The function
now no longer returns an error code, but nothing ever evaluated that anyway.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 8c9478a400b7efdeab89797cfb77e4e845fb34fb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>