arm64: module-plts: inline linux/moduleloader.h
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit 60a0aab7463ee69296692d980b96510ccce3934e
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:37 +0200

    module_frob_arch_sections() is declared in moduleloader.h, but
    that is not included before the definition:

    arch/arm64/kernel/module-plts.c:286:5: error: no previous prototype for 'module_frob_arch_sections' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-11-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>