platform/x86/amd: pmc: add CONFIG_SERIO dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-527.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit abce209d18fd26e865b2406cc68819289db973f9

Using the serio subsystem now requires the code to be reachable:

x86_64-linux-ld: drivers/platform/x86/amd/pmc.o: in function `amd_pmc_suspend_handler':
pmc.c:(.text+0x86c): undefined reference to `serio_bus'

Add the usual dependency: as other users of serio use 'select'
rather than 'depends on', use the same here.

Fixes: 8e60615e8932 ("platform/x86/amd: pmc: Disable IRQ1 wakeup for RN/CZN")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20230127093950.2368575-1-arnd@kernel.org
	Reviewed-by: Hans de Goede <hdegoede@redhat.com>
	Signed-off-by: Hans de Goede <hdegoede@redhat.com>
(cherry picked from commit abce209d18fd26e865b2406cc68819289db973f9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>