ASoC: codecs: wm8904: Fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 5a1803324949f4ebdf6e887b59e0e89afc3ee0bb
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Tue Aug 15 16:32:03 2023 +0200

    ASoC: codecs: wm8904: Fix Wvoid-pointer-to-enum-cast warning

    'devtype' is an enum, thus cast of pointer on 64-bit compile test with
    W=1 causes:

      wm8904.c:2205:21: error: cast to smaller integer type 'enum wm8904_type' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230815143204.379708-2-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>