irqchip/irq-msi-lib: Fix build with PCI disabled
JIRA: https://issues.redhat.com/browse/RHEL-120705
Upstream Status: a8b289f0f2dcbadd8c207ad8f33cf7ba2b4eb088

commit a8b289f0f2dcbadd8c207ad8f33cf7ba2b4eb088
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jul 10 10:00:12 2025 +0200

    irqchip/irq-msi-lib: Fix build with PCI disabled

    The armada-370-xp irqchip fails in some randconfig builds because
    of a missing declaration:

    In file included from drivers/irqchip/irq-armada-370-xp.c:23:
    include/linux/irqchip/irq-msi-lib.h:25:39: error: 'struct msi_domain_info' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

    Add a forward declaration for the msi_domain_info structure.

    [ tglx: Fixed up the subsystem prefix. Is it really that hard to get right? ]

    Fixes: e51b27438a10 ("irqchip: Make irq-msi-lib.h globally available")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Acked-by: Marc Zyngier <maz@kernel.org>
    Link: https://lore.kernel.org/all/20250710080021.2303640-1-arnd@kernel.org

Signed-off-by: Myron Stowe <mstowe@redhat.com>