selftests/bpf: Fix missing space error
Bugzilla: https://bugzilla.redhat.com/2178930

commit 1c48391bc6739f5e3306919d4b887b92c35d5490
Author: Roberto Valenzuela <valenzuelarober@gmail.com>
Date:   Fri Jan 13 13:02:57 2023 -0500

    selftests/bpf: Fix missing space error
    
    Add the missing space after 'dest' variable assignment.
    This change will resolve the following checkpatch.pl
    script error:
    
    ERROR: spaces required around that '+=' (ctx:VxW)
    
    Signed-off-by: Roberto Valenzuela <valenzuelarober@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20230113180257.39769-1-valenzuelarober@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>