mei: me: fix clang -Wformat warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-481.el8
commit-author Justin Stitt <justinstitt@google.com>
commit d618072d86fcc391b77ca0a1909b5f0bb8423f6e

When building with Clang we encounter the following warning:
| drivers/misc/mei/hw-me.c:564:44: error: format specifies type 'unsigned
| short' but the argument has type 'int' [-Werror,-Wformat]
| dev_dbg(dev->dev, "empty slots = %hu.\n", empty_slots);

The format specifier used is `%hu` which specifies an unsigned short,
however, empty_slots is an int -- hence the warning.

Link: https://github.com/ClangBuiltLinux/linux/issues/378
	Tested-by: Nick Desaulniers <ndesaulniers@google.com>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: Justin Stitt <justinstitt@google.com>
Link: https://lore.kernel.org/r/20220708203549.3834790-1-justinstitt@google.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit d618072d86fcc391b77ca0a1909b5f0bb8423f6e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>