ext4: fix potential unnitialized variable
JIRA: https://issues.redhat.com/browse/RHEL-86510

commit 3f4830abd236d0428e50451e1ecb62e14c365e9b
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Wed Apr 17 21:10:40 2024 +0300

    ext4: fix potential unnitialized variable

    Smatch complains "err" can be uninitialized in the caller.

        fs/ext4/indirect.c:349 ext4_alloc_branch()
        error: uninitialized symbol 'err'.

    Set the error to zero on the success path.

    Fixes: 8016e29f4362 ("ext4: fast commit recovery path")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Link: https://lore.kernel.org/r/363a4673-0fb8-4adf-b4fb-90a499077276@moroto.mountain
    Signed-off-by: Theodore Ts'o <tytso@mit.edu>

Signed-off-by: Brian Foster <bfoster@redhat.com>