xfs: fix compile error when libxfs header used in C++ code
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Roger Willcocks <roger@filmlight.ltd.uk>
commit 376c2f3a5f0706868b08ccf043bf3532936a03b1
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/376c2f3a.failed

xfs_ialloc.h:102: error: expected ',' or '...' before 'delete'

Simple parameter rename, no changes to behaviour.

	Signed-off-by: Roger Willcocks <roger@filmlight.ltd.uk>
	Reviewed-by: Dave Chinner <dchinner@redhat.com>
	Signed-off-by: Dave Chinner <david@fromorbit.com>

(cherry picked from commit 376c2f3a5f0706868b08ccf043bf3532936a03b1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	fs/xfs/xfs_ialloc.c