net/mlx5e: xsk: dynamically allocate mlx5e_channel_param
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 658688ce6c936254c34ea1f31549ec62439574aa

The structure is too large to put on the stack, resulting in a
warning on 32-bit ARM:

drivers/net/ethernet/mellanox/mlx5/core/en/xsk/setup.c:59:5: error: stack frame size of 1344 bytes in function
      'mlx5e_open_xsk' [-Werror,-Wframe-larger-than=]

Use kvzalloc() instead.

Fixes: a038e9794541 ("net/mlx5e: Add XSK zero-copy support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Maxim Mikityanskiy <maximmi@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 658688ce6c936254c34ea1f31549ec62439574aa)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>