selftests/bpf: Fix missing BUILD_BUG_ON() declaration
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 6495eb79ca7d15bd87c38d77307e8f9b6b7bf4ef
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:36 2024 -0700

    selftests/bpf: Fix missing BUILD_BUG_ON() declaration

    Explicitly include '<linux/build_bug.h>' to fix errors seen compiling with
    gcc targeting mips64el/musl-libc:

      user_ringbuf.c: In function 'test_user_ringbuf_loop':
      user_ringbuf.c:426:9: error: implicit declaration of function 'BUILD_BUG_ON' [-Werror=implicit-function-declaration]
        426 |         BUILD_BUG_ON(total_samples <= c_max_entries);
            |         ^~~~~~~~~~~~
      cc1: all warnings being treated as errors

    Fixes: e5a9df51c746 ("selftests/bpf: Add selftests validating the user ringbuf")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/b28575f9221ec54871c46a2e87612bb4bbf46ccd.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>