mlx5: fix psample_sample_packet link error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-372.9.1.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7a7dd5114f53885419ef67c530e961d7ceaec15a

When PSAMPLE is a loadable module, built-in drivers cannot use it:

aarch64-linux-ld: drivers/net/ethernet/mellanox/mlx5/core/en/tc/sample.o: in function `mlx5e_tc_sample_skb':
sample.c:(.text+0xd68): undefined reference to `psample_sample_packet'

Add the same dependency here that is used for MLXSW

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
(cherry picked from commit 7a7dd5114f53885419ef67c530e961d7ceaec15a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>