clk: tegra20: fix gcc-7 constant overflow warning
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit b4a2adbf3586efa12fe78b9dec047423e01f3010
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 27 09:59:10 2023 +0100

    clk: tegra20: fix gcc-7 constant overflow warning

    Older gcc versions get confused by comparing a u32 value to a negative
    constant in a switch()/case block:

    drivers/clk/tegra/clk-tegra20.c: In function 'tegra20_clk_measure_input_freq':
    drivers/clk/tegra/clk-tegra20.c:581:2: error: case label does not reduce to an integer constant
      case OSC_CTRL_OSC_FREQ_12MHZ:
      ^~~~
    drivers/clk/tegra/clk-tegra20.c:593:2: error: case label does not reduce to an integer constant
      case OSC_CTRL_OSC_FREQ_26MHZ:

    Make the constants unsigned instead.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230227085914.2560984-1-arnd@kernel.org
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>