drm/amd/display: fix struct init in update_bounding_box
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Raul E Rangel <rrangel@chromium.org>
commit 960b6f4f2d2e96d5f7ffe2854e0040b46cafbd36
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-193.el8/960b6f4f.failed

dcn20_resource.c:2636:9: error: missing braces around initializer [-Werror=missing-braces]
  struct _vcs_dpi_voltage_scaling_st calculated_states[MAX_CLOCK_LIMIT_STATES] = {0};
         ^

Fixes: 7ed4e6352c16f ("drm/amd/display: Add DCN2 HW Sequencer and Resource")

	Signed-off-by: Raul E Rangel <rrangel@chromium.org>
	Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 960b6f4f2d2e96d5f7ffe2854e0040b46cafbd36)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c