drm/xe/vsec: fix CONFIG_INTEL_VSEC dependency
JIRA: https://issues.redhat.com/browse/RHEL-75952

commit e8951661ae9359c3b4a582cbe787f37506ed92cc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 29 10:23:56 2025 -0700

    drm/xe/vsec: fix CONFIG_INTEL_VSEC dependency

    [ Upstream commit 2182f358fb138f81a586ffdddd510f2a4fc61702 ]

    The XE driver can be built with or without VSEC support, but fails to link as
    built-in if vsec is in a loadable module:

    x86_64-linux-ld: vmlinux.o: in function `xe_vsec_init':
    (.text+0x1e83e16): undefined reference to `intel_vsec_register'

    The normal fix for this is to add a 'depends on INTEL_VSEC || !INTEL_VSEC',
    forcing XE to be a loadable module as well, but that causes a circular
    dependency:

            symbol DRM_XE depends on INTEL_VSEC
            symbol INTEL_VSEC depends on X86_PLATFORM_DEVICES
            symbol X86_PLATFORM_DEVICES is selected by DRM_XE

    The problem here is selecting a symbol from another subsystem, so change
    that as well and rephrase the 'select' into the corresponding dependency.
    Since X86_PLATFORM_DEVICES is 'default y', there is no change to
    defconfig builds here.

    Fixes: 0c45e76fcc62 ("drm/xe/vsec: Support BMG devices")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Lucas De Marchi <lucas.demarchi@intel.com>
    Link: https://lore.kernel.org/r/20250529172355.2395634-2-lucas.demarchi@intel.com
    Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>
    (cherry picked from commit e4931f8be347ec5f19df4d6d33aea37145378c42)
    Signed-off-by: Thomas Hellström <thomas.hellstrom@linux.intel.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Robert Foss <rfoss@redhat.com>