selftests/bpf: Build urandom_read with LDFLAGS and LDLIBS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Daniel Díaz <daniel.diaz@linaro.org>
commit 1222653cc0489fa9304a36f7d9593ecaeb51efe1
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-240.el8/1222653c.failed

During cross-compilation, it was discovered that LDFLAGS and
LDLIBS were not being used while building binaries, leading
to defaults which were not necessarily correct.

OpenEmbedded reported this kind of problem:

  ERROR: QA Issue: No GNU_HASH in the ELF binary [...], didn't pass LDFLAGS?

	Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Acked-by: Andrii Nakryiko <andriin@fb.com>
	Acked-by: John Fastabend <john.fastabend@gmail.com>
(cherry picked from commit 1222653cc0489fa9304a36f7d9593ecaeb51efe1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/bpf/Makefile