ASoC: tas2781: fix Kconfig dependencies
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit fcb66ee8d16aa0f88efcc9cb41083c0412e9db8a
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Jun 22 12:11:23 2023 +0200

    ASoC: tas2781: fix Kconfig dependencies

    The new driver has two modules that both get enabled for build testing
    when all codecs are selected. The comlib part has an i2c dependency,
    so this remains disabled on builds without i2c, but then the other
    one fails to link:

    ERROR: modpost: "tasdevice_dev_bulk_write" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!
    ERROR: modpost: "tasdevice_dev_update_bits" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!
    ERROR: modpost: "tasdevice_dev_bulk_read" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!
    ERROR: modpost: "tasdevice_dev_read" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!
    ERROR: modpost: "tasdevice_dev_write" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!

    There are many ways to address this, adding an explicit dependency seems
    to be the clearest method that keeps the structure of the driver otherwise
    unchanged.

    Fixes: ef3bcde75d06d ("ASoC: tas2781: Add tas2781 driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/Message-Id: <20230622101205.3180938-1-arnd@kernel.org>
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>