ath9k_htc: fix potential out of bounds access with invalid rxstatus->rs_keyix
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 2dc509305cf956381532792cb8dceef2b1504765

The "rxstatus->rs_keyix" eventually gets passed to test_bit() so we need to
ensure that it is within the bitmap.

drivers/net/wireless/ath/ath9k/common.c:46 ath9k_cmn_rx_accept()
error: passing untrusted data 'rx_stats->rs_keyix' to 'test_bit()'

Fixes: 4ed1a8d4a257 ("ath9k_htc: use ath9k_cmn_rx_accept")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20220409061225.GA5447@kili
(cherry picked from commit 2dc509305cf956381532792cb8dceef2b1504765)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>