powerpc: Added __cmpdi2 for signed 64bit comparision
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] Added __cmpdi2 for signed 64bit comparision (Don Zickus) [1127366]
Rebuild_FUZZ: 90.53%
commit-author Bharat Bhushan <r65777@freescale.com>
commit 41b93b238ab394c8cf0935ec3ba31c700a2b3b25

This was missing on powerpc and I am getting compilation error
drivers/vfio/pci/vfio_pci_rdwr.c:193: undefined reference to `__cmpdi2'
drivers/vfio/pci/vfio_pci_rdwr.c:193: undefined reference to `__cmpdi2'

	Signed-off-by: Bharat Bhushan <bharat.bhushan@freescale.com>
	Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
(cherry picked from commit 41b93b238ab394c8cf0935ec3ba31c700a2b3b25)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>