usb: gadget: configfs: avoid spaces for indentation
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Parth Y Shah <sparth1292@gmail.com>
commit ad22a6663c6312825876fed25fd6d010d4b46db1

This fixes the following checkpatch error:

ERROR: code indent should use tabs where possible

Here, spaces are replaced by a tab in 2 lines.

	Signed-off-by: Parth Y Shah <sparth1292@gmail.com>
	Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>
(cherry picked from commit ad22a6663c6312825876fed25fd6d010d4b46db1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>