audit: fix type of sessionid in audit_set_loginuid()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
commit-author Eric Paris <eparis@redhat.com>
commit 9175c9d2aed528800175ef81c90569d00d23f9be

sfr pointed out that with CONFIG_UIDGID_STRICT_TYPE_CHECKS set the audit
tree would not build.  This is because the oldsessionid in
audit_set_loginuid() was accidentally being declared as a kuid_t.  This
patch fixes that declaration mistake.

Example of problem:
kernel/auditsc.c: In function 'audit_set_loginuid':
kernel/auditsc.c:2003:15: error: incompatible types when assigning to
type 'kuid_t' from type 'int'
  oldsessionid = audit_get_sessionid(current);

	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Eric Paris <eparis@redhat.com>
(cherry picked from commit 9175c9d2aed528800175ef81c90569d00d23f9be)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>