qed (gcc13): use u16 for fid to be big enough
JIRA: https://issues.redhat.com/browse/RHEL-52263

commit 7d84118229bf7f7290438c85caa8e49de52d50c1
Author: Jiri Slaby (SUSE) <jirislaby@kernel.org>
Date:   Mon Oct 31 12:43:54 2022 +0100

    qed (gcc13): use u16 for fid to be big enough

    gcc 13 correctly reports overflow in qed_grc_dump_addr_range():
    In file included from drivers/net/ethernet/qlogic/qed/qed.h:23,
                     from drivers/net/ethernet/qlogic/qed/qed_debug.c:10:
    drivers/net/ethernet/qlogic/qed/qed_debug.c: In function 'qed_grc_dump_addr_range':
    include/linux/qed/qed_if.h:1217:9: error: overflow in conversion from 'int' to 'u8' {aka 'unsigned char'} changes value from '(int)vf_id << 8 | 128' to '128' [-Werror=overflow]

    We do:
      u8 fid;
      ...
      fid = vf_id << 8 | 128;

    Since fid is 16bit (and the stored value above too), fid should be u16,
    not u8. Fix that.

    Cc: Martin Liska <mliska@suse.cz>
    Cc: Ariel Elior <aelior@marvell.com>
    Cc: Manish Chopra <manishc@marvell.com>
    Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
    Link: https://lore.kernel.org/r/20221031114354.10398-1-jirislaby@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>