selftests: mptcp: join: fix 'delete and re-add' test
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2109139
Upstream Status: net.git commit aaf2123a5cf4

commit aaf2123a5cf46dbd97f84b6eee80269758064d93
Author: Andrea Claudi <aclaudi@redhat.com>
Date:   Thu Aug 3 18:27:27 2023 +0200

    selftests: mptcp: join: fix 'delete and re-add' test

    mptcp_join 'delete and re-add' test fails when using ip mptcp:

      $ ./mptcp_join.sh -iI
      <snip>
      002 delete and re-add                    before delete[ ok ]
                                               mptcp_info subflows=1         [ ok ]
      Error: argument "ADDRESS" is wrong: invalid for non-zero id address
                                               after delete[fail] got 2:2 subflows expected 1

    This happens because endpoint delete includes an ip address while id is
    not 0, contrary to what is indicated in the ip mptcp man page:

    "When used with the delete id operation, an IFADDR is only included when
    the ID is 0."

    This fixes the issue using the $addr variable in pm_nl_del_endpoint()
    only when id is 0.

    Fixes: 34aa6e3bccd8 ("selftests: mptcp: add ip mptcp wrappers")
    Cc: stable@vger.kernel.org
    Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
    Reviewed-by: Matthieu Baerts <matthieu.baerts@tessares.net>
    Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
    Link: https://lore.kernel.org/r/20230803-upstream-net-20230803-misc-fixes-6-5-v1-1-6671b1ab11cc@tessares.net
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrea Claudi <aclaudi@redhat.com>