KVM: selftests: Explicitly disable builtins for mem*() overrides
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2177720

commit 7cf2e7373ab145bf972c3cbcb495fd1a9770c3b0
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Dec 13 00:16:48 2022 +0000

    KVM: selftests: Explicitly disable builtins for mem*() overrides

    Explicitly disable the compiler's builtin memcmp(), memcpy(), and
    memset().  Because only lib/string_override.c is built with -ffreestanding,
    the compiler reserves the right to do what it wants and can try to link the
    non-freestanding code to its own crud.

      /usr/bin/x86_64-linux-gnu-ld: /lib/x86_64-linux-gnu/libc.a(memcmp.o): in function `memcmp_ifunc':
      (.text+0x0): multiple definition of `memcmp'; tools/testing/selftests/kvm/lib/string_override.o:
      tools/testing/selftests/kvm/lib/string_override.c:15: first defined here
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

    Fixes: 6b6f71484bf4 ("KVM: selftests: Implement memcmp(), memcpy(), and memset() for guest use")
    Reported-by: Aaron Lewis <aaronlewis@google.com>
    Reported-by: Raghavendra Rao Ananta <rananta@google.com>
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Message-Id: <20221213001653.3852042-10-seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>