net: intel: igc_ptp: fix build for UML
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 523994ba3ad1b7b55abe4a72e156897b5e2db825
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-365.el8/523994ba.failed

On a UML build, the igc_ptp driver uses CONFIG_X86_TSC for timestamp
conversion. The function that is used is not available on UML builds,
so have the function use the default system_counterval_t timestamp
instead for UML builds.

Prevents this build error on UML:

../drivers/net/ethernet/intel/igc/igc_ptp.c: In function ‘igc_device_tstamp_to_system’:
../drivers/net/ethernet/intel/igc/igc_ptp.c:777:9: error: implicit declaration of function ‘convert_art_ns_to_tsc’ [-Werror=implicit-function-declaration]
  return convert_art_ns_to_tsc(tstamp);
../drivers/net/ethernet/intel/igc/igc_ptp.c:777:9: error: incompatible types when returning type ‘int’ but ‘struct system_counterval_t’ was expected
  return convert_art_ns_to_tsc(tstamp);

Fixes: 68f5d3f3b654 ("um: add PCI over virtio emulation driver")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: linux-um@lists.infradead.org
	Cc: Jeff Dike <jdike@addtoit.com>
	Cc: Richard Weinberger <richard@nod.at>
	Cc: Anton Ivanov <anton.ivanov@cambridgegreys.com>
	Cc: Jesse Brandeburg <jesse.brandeburg@intel.com>
	Cc: Tony Nguyen <anthony.l.nguyen@intel.com>
	Cc: intel-wired-lan@lists.osuosl.org
Link: https://lore.kernel.org/r/20211014050516.6846-1-rdunlap@infradead.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 523994ba3ad1b7b55abe4a72e156897b5e2db825)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/intel/igc/igc_ptp.c