wifi: ipw2x00: remove unused _ipw_read16 function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit c7e39d70613c113b5ac667beeb3cacb242c6a4cb

clang with W=1 reports
drivers/net/wireless/intel/ipw2x00/ipw2200.c:381:19: error:
  unused function '_ipw_read16' [-Werror,-Wunused-function]
static inline u16 _ipw_read16(struct ipw_priv *ipw, unsigned long ofs)
                  ^
This function and its wrapping marco are not used, so remove them.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230319135418.1703380-1-trix@redhat.com
(cherry picked from commit c7e39d70613c113b5ac667beeb3cacb242c6a4cb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>