drivers: thermal: processor_thermal_device: Fix build warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [thermal] thermal: processor_thermal_device: Fix build warning (Alexander Beregalov) [1732604]
Rebuild_FUZZ: 92.04%
commit-author Zhang Rui <rui.zhang@intel.com>
commit 6c395f66e98c895cf3ebf87c0b2fc63b6a57a196

As a system sleep callback, proc_thermal_resume() should be defined only
if CONFIG_PM_SLEEP is defined.

This fixes a build warning when CONFIG_PM_SLEEP is not set,
drivers/thermal/intel/int340x_thermal/processor_thermal_device.c:446:12: error: 'proc_thermal_resume' defined but not used [-Werror=unused-function]
 static int proc_thermal_resume(struct device *dev)

Fixes: aaba9791fbb4 ("drivers: thermal: processor_thermal: Read PPCC on resume")
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Zhang Rui <rui.zhang@intel.com>
(cherry picked from commit 6c395f66e98c895cf3ebf87c0b2fc63b6a57a196)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>