octeontx2-af: Initialize 'cntr_val' to fix uninitialized symbol error
JIRA: https://issues.redhat.com/browse/RHEL-23617

commit 222a6c42e9ef131fd20463bf95d7ce7b39bee2f8
Author: Suman Ghosh <sumang@marvell.com>
Date:   Thu Jul 27 22:01:01 2023 +0530

    octeontx2-af: Initialize 'cntr_val' to fix uninitialized symbol error

    drivers/net/ethernet/marvell/octeontx2/nic/otx2_tc.c:860
    otx2_tc_update_mcam_table_del_req()
    error: uninitialized symbol 'cntr_val'.

    Fixes: ec87f05402f5 ("octeontx2-af: Install TC filter rules in hardware based on priority")
    Signed-off-by: Suman Ghosh <sumang@marvell.com>
    Link: https://lore.kernel.org/r/20230727163101.2793453-1-sumang@marvell.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Sai Krishna <sgajula@redhat.com>