ASoC: codecs: src4xxx-i2c: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2179848

commit 075a430db402eed0907b80493f1432d47a5120a7
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Fri Mar 10 22:43:32 2023 +0100

    ASoC: codecs: src4xxx-i2c: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      sound/soc/codecs/src4xxx-i2c.c:27:34: error: ‘src4xxx_of_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214333.274903-9-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>