perf list: Use relative path for tracepoint scan
Bugzilla: https://bugzilla.redhat.com/2233483

upstream
========
commit 00462d8eaca4eb48e4c07a9a9b49cea2a871fd35
Author: Namhyung Kim <namhyung@kernel.org>
Date: Fri Mar 31 13:29:41 2023 -0700

description
===========
Committer notes:

Added missing #include <unistd.h> for the close() prototype to fix this
on Alma Linux 8:

   1    21.54 almalinux:8                   : FAIL gcc version 8.5.0 20210514 (Red Hat 8.5.0-16) (GCC)
    util/print-events.c: In function 'print_tracepoint_events':
    util/print-events.c:103:4: error: implicit declaration of function 'close'; did you mean 'clone'? [-Werror=implicit-function-declaration]
        close(evt_fd);
        ^~~~~
        clone

Also use the newly added scandirat feature test to check if that
function is available, providing a HAVE_SCANDIRAT_SUPPORT conditional
warning to the user if it isn't available.

    Signed-off-by: Namhyung Kim <namhyung@kernel.org>
    Acked-by: Ian Rogers <irogers@google.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Ingo Molnar <mingo@kernel.org>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Kan Liang <kan.liang@linux.intel.com>
    Cc: Leo Yan <leo.yan@linaro.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Link: https://lore.kernel.org/r/20230331202949.810326-2-namhyung@kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>