bridge: move maybe_deliver_addr() inside #ifdef
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5b9d6b154a622d0481123c1b149afdf377264268

The only caller of this new function is inside of an #ifdef checking
for CONFIG_BRIDGE_IGMP_SNOOPING, so we should move the implementation
there too, in order to avoid this harmless warning:

net/bridge/br_forward.c:177:13: error: 'maybe_deliver_addr' defined but not used [-Werror=unused-function]

Fixes: 6db6f0eae605 ("bridge: multicast to unicast")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Stephen Hemminger <stephen@networkplumber.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5b9d6b154a622d0481123c1b149afdf377264268)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>