mwifiex: avoid null-pointer-subtraction warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 603a1621caa097be23c7784e36cb8edf23cd31db

clang complains about some NULL pointer arithmetic in this driver:

drivers/net/wireless/marvell/mwifiex/sta_tx.c:65:59: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
        pad = ((void *)skb->data - (sizeof(*local_tx_pd) + hroom)-
                                                                 ^
drivers/net/wireless/marvell/mwifiex/uap_txrx.c:478:53: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
        pad = ((void *)skb->data - (sizeof(*txpd) + hroom) - NULL) &

Rework that expression to do the same thing using a uintptr_t.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20210927121656.940304-1-arnd@kernel.org
(cherry picked from commit 603a1621caa097be23c7784e36cb8edf23cd31db)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>