bpf: fix build error with clang
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Stefan Agner <stefan@agner.ch>
commit 3f6e138d41ddff196f452993528cfe75762ede0f
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-147.el8/3f6e138d.failed

Building the newly introduced BPF_PROG_TYPE_SK_REUSEPORT leads to
a compile time error when building with clang:
net/core/filter.o: In function `sk_reuseport_convert_ctx_access':
  ../net/core/filter.c:7284: undefined reference to `__compiletime_assert_7284'

It seems that clang has issues resolving hweight_long at compile
time. Since SK_FL_PROTO_MASK is a constant, we can use the interface
for known constant arguments which works fine with clang.

Fixes: 2dbb9b9e6df6 ("bpf: Introduce BPF_PROG_TYPE_SK_REUSEPORT")
	Signed-off-by: Stefan Agner <stefan@agner.ch>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit 3f6e138d41ddff196f452993528cfe75762ede0f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/core/filter.c