iommu/vt-d: Fix compile error with CONFIG_PCI_ATS not set
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Lu Baolu <baolu.lu@linux.intel.com>
commit 3645a34f5b962aeedeb02f30cdf048eaae9b5f5c

Fix the compile error below (CONFIG_PCI_ATS not set):

drivers/iommu/intel/dmar.c: In function ‘vf_inherit_msi_domain’:
drivers/iommu/intel/dmar.c:338:59: error: ‘struct pci_dev’ has no member named ‘physfn’; did you mean ‘is_physfn’?
  338 |  dev_set_msi_domain(&pdev->dev, dev_get_msi_domain(&pdev->physfn->dev));
      |                                                           ^~~~~~
      |                                                           is_physfn

Fixes: ff828729be44 ("iommu/vt-d: Cure VF irqdomain hickup")
	Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
	Cc: Thomas Gleixner <tglx@linutronix.de>
Link: https://lore.kernel.org/linux-iommu/CAMuHMdXA7wfJovmfSH2nbAhN0cPyCiFHodTvg4a8Hm9rx5Dj-w@mail.gmail.com/
Link: https://lore.kernel.org/r/20201119055119.2862701-1-baolu.lu@linux.intel.com
	Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit 3645a34f5b962aeedeb02f30cdf048eaae9b5f5c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>