coredump: Move dump_emit_page() to kill unused warning
JIRA: https://issues.redhat.com/browse/RHEL-1848

commit 9c7417b5ec440242bb5b64521acd53d4e19130c1
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon Oct 3 11:06:57 2022 +0200

    coredump: Move dump_emit_page() to kill unused warning

    If CONFIG_ELF_CORE is not set:

        fs/coredump.c:835:12: error: ‘dump_emit_page’ defined but not used [-Werror=unused-function]
          835 | static int dump_emit_page(struct coredump_params *cprm, struct page *page)
              |            ^~~~~~~~~~~~~~

    Fix this by moving dump_emit_page() inside the existing section
    protected by #ifdef CONFIG_ELF_CORE.

    Fixes: 06bbaa6dc53cb720 ("[coredump] don't use __kernel_write() on kmap_local_page()")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>