dma-buf: fix use of DMA_BUF_SET_NAME_{A,B} in userspace
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2115876
Upstream Status: v5.18

commit 7c3e9fcad9c7d8bb5d69a576044fb16b1d2e8a01
Author:     Jérôme Pouiller <jerome.pouiller@silabs.com>
AuthorDate: Tue May 17 09:27:08 2022 +0200
Commit:     Christian König <christian.koenig@amd.com>
CommitDate: Tue May 17 13:05:19 2022 +0200

    The typedefs u32 and u64 are not available in userspace. Thus user get
    an error he try to use DMA_BUF_SET_NAME_A or DMA_BUF_SET_NAME_B:

        $ gcc -Wall   -c -MMD -c -o ioctls_list.o ioctls_list.c
        In file included from /usr/include/x86_64-linux-gnu/asm/ioctl.h:1,
                         from /usr/include/linux/ioctl.h:5,
                         from /usr/include/asm-generic/ioctls.h:5,
                         from ioctls_list.c:11:
        ioctls_list.c:463:29: error: ‘u32’ undeclared here (not in a function)
          463 |     { "DMA_BUF_SET_NAME_A", DMA_BUF_SET_NAME_A, -1, -1 }, // linux/dma-buf.h
              |                             ^~~~~~~~~~~~~~~~~~
        ioctls_list.c:464:29: error: ‘u64’ undeclared here (not in a function)
          464 |     { "DMA_BUF_SET_NAME_B", DMA_BUF_SET_NAME_B, -1, -1 }, // linux/dma-buf.h
              |                             ^~~~~~~~~~~~~~~~~~

    The issue was initially reported here[1].

    [1]: https://github.com/jerome-pouiller/ioctl/pull/14

    Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
    Reviewed-by: Christian König <christian.koenig@amd.com>
    Fixes: a5bff92eaac4 ("dma-buf: Fix SET_NAME ioctl uapi")
    CC: stable@vger.kernel.org
    Link: https://patchwork.freedesktop.org/patch/msgid/20220517072708.245265-1-Jerome.Pouiller@silabs.com
    Signed-off-by: Christian König <christian.koenig@amd.com>

Signed-off-by: Karol Herbst <kherbst@redhat.com>