selftests/bpf: Fix casting error when cross-compiling test_verifier for 32-bit platforms
Bugzilla: https://bugzilla.redhat.com/2137876

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 0811664da064c6d7ca64c02f5579f758a007e52d
Author: Pu Lehui <pulehui@huawei.com>
Date:   Tue Nov 8 20:19:45 2022 +0800

    selftests/bpf: Fix casting error when cross-compiling test_verifier for 32-bit platforms

    When cross-compiling test_verifier for 32-bit platforms, the casting error is shown below:

    test_verifier.c:1263:27: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     1263 |  info.xlated_prog_insns = (__u64)*buf;
          |                           ^
    cc1: all warnings being treated as errors

    Fix it by adding zero-extension for it.

    Fixes: 933ff53191eb ("selftests/bpf: specify expected instructions in test_verifier tests")
    Signed-off-by: Pu Lehui <pulehui@huawei.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/r/20221108121945.4104644-1-pulehui@huaweicloud.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Artem Savkov <asavkov@redhat.com>