ath11k: Fix build warning without CONFIG_IPV6
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 67888630addeaa2ae1c04d8d020daccbd26d05d9

drivers/net/wireless/ath/ath11k/mac.c:8175:13: error: ‘ath11k_mac_op_ipv6_changed’ defined but not used [-Werror=unused-function]
 static void ath11k_mac_op_ipv6_changed(struct ieee80211_hw *hw,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~

Wrap it with #ifdef block to fix this.

Fixes: c3c36bfe998b ("ath11k: support ARP and NS offload")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20220411020843.10284-1-yuehaibing@huawei.com
(cherry picked from commit 67888630addeaa2ae1c04d8d020daccbd26d05d9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>