qed: fix old-style function definition
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit d4e991313bd5e10bfa66cd280b8fce6dc3f2d897

The definition of qed_get_rdma_ops() is not a prototype unless
we add 'void' here, as indicated by this W=1 warning:

drivers/net/ethernet/qlogic/qed/qed_roce.c: In function ‘qed_get_rdma_ops’:
drivers/net/ethernet/qlogic/qed/qed_roce.c:2950:28: error: old-style function definition [-Werror=old-style-definition]

Fixes: abd49676c707 ("qed: Add RoCE ll2 & GSI support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Yuval Mintz <Yuval.Mintz@caviumnetworks.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d4e991313bd5e10bfa66cd280b8fce6dc3f2d897)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>