i2c: imx: ensure no clock is generated after last read
JIRA: https://redhat.atlassian.net/browse/RHEL-212089

commit 13101db735bdb29c5f60e95fb578690bd178b30f
Author: Stefan Eichenberger <stefan.eichenberger@toradex.com>
Date:   Wed Feb 18 16:08:50 2026 +0100

    i2c: imx: ensure no clock is generated after last read

    When reading from the I2DR register, right after releasing the bus by
    clearing MSTA and MTX, the I2C controller might still generate an
    additional clock cycle which can cause devices to misbehave. Ensure to
    only read from I2DR after the bus is not busy anymore. Because this
    requires polling, the read of the last byte is moved outside of the
    interrupt handler.

    An example for such a failing transfer is this:
    i2ctransfer -y -a 0 w1@0x00 0x02 r1
    Error: Sending messages failed: Connection timed out
    It does not happen with every device because not all devices react to
    the additional clock cycle.

    Fixes: 5f5c2d4579ca ("i2c: imx: prevent rescheduling in non dma mode")
    Cc: stable@vger.kernel.org # v6.13+
    Signed-off-by: Stefan Eichenberger <stefan.eichenberger@toradex.com>
    Signed-off-by: Andi Shyti <andi.shyti@kernel.org>
    Link: https://lore.kernel.org/r/20260218150940.131354-3-eichest@gmail.com

Signed-off-by: Jared Kangas <jkangas@redhat.com>