cpupower: Fix build error in cpufreq-info
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
commit 38cb76a307821f76c7f9dff7449f73aeb014d5cc

Fix the following build error by including limits.h -

utils/cpufreq-info.c: In function ‘get_latency’:
utils/cpufreq-info.c:437:29: error: ‘UINT_MAX’ undeclared (first use in
this function)
  if (!latency || latency == UINT_MAX) {
                             ^
	Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
Fixes: e98f033f94f3 (cpupower: fix how "cpupower frequency-info" interprets latency)
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 38cb76a307821f76c7f9dff7449f73aeb014d5cc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>