arm64: signal: include asm/exception.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2188323

commit 8ada7aab02ee9b07c8539a5c9cc452520b183a72
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:40 +0200

    The do_notify_resume() is in a header that is not included
    for the definition, which causes a W=1 warning:

    arch/arm64/kernel/signal.c:1280:6: error: no previous prototype for 'do_notify_resume' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-14-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>