net/sched: act_skbedit: Add extack messages for offload failure
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit a9c64939b669b3c83cc54738d1986430e6beaff2
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:28 2022 +0300

    net/sched: act_skbedit: Add extack messages for offload failure

    For better error reporting to user space, add extack messages when
    skbedit action offload fails.

    Example:

     # echo 1 > /sys/kernel/tracing/events/netlink/netlink_extack/enable

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action skbedit queue_mapping 1234
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-185     [002] b..1.    31.802414: netlink_extack: msg=act_skbedit: Offload not supported when "queue_mapping" option is used
           tc-185     [002] .....    31.802418: netlink_extack: msg=cls_matchall: Failed to setup flow action

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action skbedit inheritdsfield
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-187     [002] b..1.    45.985145: netlink_extack: msg=act_skbedit: Offload not supported when "inheritdsfield" option is used
           tc-187     [002] .....    45.985160: netlink_extack: msg=cls_matchall: Failed to setup flow action

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>