tools/bpf: fix perf build error with uClibc (seen on ARC)
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [tools] bpf: fix perf build error with uClibc (seen on ARC) (Yauheni Kaliuta) [1747615]
Rebuild_FUZZ: 94.44%
commit-author Vineet Gupta <Vineet.Gupta1@synopsys.com>
commit ca31ca8247e2d3807ff5fa1d1760616a2292001c

When build perf for ARC recently, there was a build failure due to lack
of __NR_bpf.

| Auto-detecting system features:
|
| ...                     get_cpuid: [ OFF ]
| ...                           bpf: [ on  ]
|
| #  error __NR_bpf not defined. libbpf does not support your arch.
    ^~~~~
| bpf.c: In function 'sys_bpf':
| bpf.c:66:17: error: '__NR_bpf' undeclared (first use in this function)
|  return syscall(__NR_bpf, cmd, attr, size);
|                 ^~~~~~~~
|                 sys_bpf

	Signed-off-by: Vineet Gupta <vgupta@synopsys.com>
	Acked-by: Yonghong Song <yhs@fb.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit ca31ca8247e2d3807ff5fa1d1760616a2292001c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>