iwlwifi: pcie: fix iwl_so_trans_cfg link error when CONFIG_IWLMVM is disabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Kalle Valo <kvalo@codeaurora.org>
commit 62541e266703549550e77fd46138422dbdc881f1

Randy reported an error on his randconfig builds:

ERROR: modpost: "iwl_so_trans_cfg" [drivers/net/wireless/intel/iwlwifi/iwlwifi.ko] undefined!

The problem was that when CONFIG_IWLMVM was disabled we were still accessing
iwl_so_trans_cfg. Fix it by moving IS_ENABLED() check before the access.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
Fixes: 930be4e76f26 ("iwlwifi: add support for SnJ with Jf devices")
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
	Acked-by: Luca Coelho <luciano.coelho@intel.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/1614236661-20274-1-git-send-email-kvalo@codeaurora.org
(cherry picked from commit 62541e266703549550e77fd46138422dbdc881f1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>