perf python: Ignore unused command line arguments when building with clang
Bugzilla: https://bugzilla.redhat.com/2123229

upstream
========
commit 41d0914d861e82b4eeec16dd0f6109c311cf4c7e
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Jul 20 14:59:22 2022 -0300

description
===========
Noticed after switching to python3 by default on some older fedora
releases:

  35    38.20 fedora:27                     : FAIL clang version 5.0.2 (tags/RELEASE_502/final)
    clang-5.0: error: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1' [-Werror,-Wunused-command-line-argument]
    clang-5.0: error: argument unused during compilation: '-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1' [-Werror,-Wunused-command-line-argument]
    error: command 'clang' failed with exit status 1

    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>