libbpf: Avoid designated initializers for unnamed union members
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit 4be6e05c4d4c2ff87750d3242f69999245d119f8

As it fails to build in some systems with:

  libbpf.c: In function 'perf_buffer__new':
  libbpf.c:4515: error: unknown field 'sample_period' specified in initializer
  libbpf.c:4516: error: unknown field 'wakeup_events' specified in initializer

Doing as:

    attr.sample_period = 1;

I.e. not as a designated initializer makes it build everywhere.

	Cc: Andrii Nakryiko <andriin@fb.com>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
Fixes: fb84b8224655 ("libbpf: add perf buffer API")
Link: https://lkml.kernel.org/n/tip-hnlmch8qit1ieksfppmr32si@git.kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Acked-by: Andrii Nakryiko <andriin@fb.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit 4be6e05c4d4c2ff87750d3242f69999245d119f8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>