net/mlx5e: Fix build break on 32bit
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-537.el8
commit-author Saeed Mahameed <saeedm@nvidia.com>
commit 163c2c7059178898ad7512294ca3a768df2c1515

The cited commit caused the following build break in mlx5 due to a change
in size of MAX_SKB_FRAGS.

error: format '%lu' expects argument of type 'long unsigned int',
       but argument 7 has type 'unsigned int' [-Werror=format=]

Fix this by explicit casting.

Fixes: 3948b05950fd ("net: introduce a config option to tweak MAX_SKB_FRAGS")
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
Link: https://lore.kernel.org/r/20230328200723.125122-1-saeed@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 163c2c7059178898ad7512294ca3a768df2c1515)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>