bpftool: Fix generated code in codegen_asserts
Bugzilla: https://bugzilla.redhat.com/2120966

commit ef8a257b4e499a979364b1f9caf25a325f6ee8b8
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Mon Mar 28 10:37:03 2022 +0200

    bpftool: Fix generated code in codegen_asserts

    Arnaldo reported perf compilation fail with:

      $ make -k BUILD_BPF_SKEL=1 CORESIGHT=1 PYTHON=python3
      ...
      In file included from util/bpf_counter.c:28:
      /tmp/build/perf//util/bpf_skel/bperf_leader.skel.h: In function ‘bperf_leader_bpf__assert’:
      /tmp/build/perf//util/bpf_skel/bperf_leader.skel.h:351:51: error: unused parameter ‘s’ [-Werror=unused-parameter]
        351 | bperf_leader_bpf__assert(struct bperf_leader_bpf *s)
            |                          ~~~~~~~~~~~~~~~~~~~~~~~~~^
      cc1: all warnings being treated as errors

    If there's nothing to generate in the new assert function,
    we will get unused 's' warn/error, adding 'unused' attribute to it.

    Fixes: 08d4dba6ae77 ("bpftool: Bpf skeletons assert type sizes")
    Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Jiri Olsa <jolsa@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Link: https://lore.kernel.org/bpf/20220328083703.2880079-1-jolsa@kernel.org

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>