perf tools: Free temporary 'sys' string in read_event_files()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Sanskriti Sharma <sansharm@redhat.com>
commit 1e44224fb0528b4c0cc176bde2bb31e9127eb14b

For each system in a given pevent, read_event_files() reads in a
temporary 'sys' string.  Be sure to free this string before moving onto
to the next system and/or leaving read_event_files().

Fixes the following coverity complaints:

  Error: RESOURCE_LEAK (CWE-772):

  tools/perf/util/trace-event-read.c:343: overwrite_var: Overwriting
  "sys" in "sys = read_string()" leaks the storage that "sys" points to.

  tools/perf/util/trace-event-read.c:353: leaked_storage: Variable "sys"
  going out of scope leaks the storage it points to.

	Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
	Reviewed-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Joe Lawrence <joe.lawrence@redhat.com>
Link: http://lkml.kernel.org/r/1538490554-8161-6-git-send-email-sansharm@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 1e44224fb0528b4c0cc176bde2bb31e9127eb14b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>