cpufreq: amd-pstate: Fix uninitialized variable in amd_pstate_cpu_boost_update()
JIRA: https://issues.redhat.com/browse/RHEL-61470

commit 67d95303c84732c2e1de5730756281f648dbefaf
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Tue Aug 13 15:21:13 2024 +0530

    cpufreq: amd-pstate: Fix uninitialized variable in amd_pstate_cpu_boost_update()

    Smatch complains that "ret" could be uninitialized:

      drivers/cpufreq/amd-pstate.c:734 amd_pstate_cpu_boost_update()
      error: uninitialized symbol 'ret'.

    This seems like it probably is a real issue.  Initialize "ret" to zero to
    be safe.

    Fixes: c8c68c38b56f ("cpufreq: amd-pstate: initialize core precision boost state")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Reviewed-by: Perry Yuan <perry.yuan@amd.com>
    Acked-by: Gautham R. Shenoy <gautham.shenoy@amd.com>
    Link: https://lore.kernel.org/lkml/7ff53543-6c04-48a0-8d99-7dc010b93b3a@stanley.mountain/T/
    Signed-off-by: Gautham R. Shenoy <gautham.shenoy@amd.com>
    Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>

Signed-off-by: David Arcari <darcari@redhat.com>