bpf: Fix compilation warning with -Wparentheses
JIRA: https://issues.redhat.com/browse/RHEL-10691

commit 09fedc731874123e0f6e5e5e3572db0c60378c2a
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Thu Jul 27 22:57:40 2023 -0700

    bpf: Fix compilation warning with -Wparentheses

    The kernel test robot reported compilation warnings when -Wparentheses is
    added to KBUILD_CFLAGS with gcc compiler. The following is the error message:

      .../bpf-next/kernel/bpf/verifier.c: In function ‘coerce_reg_to_size_sx’:
      .../bpf-next/kernel/bpf/verifier.c:5901:14:
        error: suggest parentheses around comparison in operand of ‘==’ [-Werror=parentheses]
        if (s64_max >= 0 == s64_min >= 0) {
            ~~~~~~~~^~~~
      .../bpf-next/kernel/bpf/verifier.c: In function ‘coerce_subreg_to_size_sx’:
      .../bpf-next/kernel/bpf/verifier.c:5965:14:
        error: suggest parentheses around comparison in operand of ‘==’ [-Werror=parentheses]
        if (s32_min >= 0 == s32_max >= 0) {
            ~~~~~~~~^~~~

    To fix the issue, add proper parentheses for the above '>=' condition
    to silence the warning/error.

    I tried a few clang compilers like clang16 and clang18 and they do not emit
    such warnings with -Wparentheses.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202307281133.wi0c4SqG-lkp@intel.com/
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/r/20230728055740.2284534-1-yonghong.song@linux.dev
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>