x86/intel_rdt: Select KERNFS when enabling INTEL_RDT_A
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [x86] intel_rdt: Select KERNFS when enabling INTEL_RDT_A (Jiri Olsa) [1457533]
Rebuild_FUZZ: 96.15%
commit-author Thomas Gleixner <tglx@linutronix.de>
commit 59fe5a77d473f3519dbee8ef5e77c69897a838f9

arch/x86/kernel/cpu/intel_rdt_rdtgroup.c: In function 'rdtgroup_kn_lock_live':
arch/x86/kernel/cpu/intel_rdt_rdtgroup.c:658:2: error: implicit declaration of
function 'kernfs_break_active_protection' [-Werror=implicit-function-declaration]

	Reported-by: Ingo Molnar <mingo@kernel.org>
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
	Cc: Shaohua Li <shli@fb.com>
	Cc: Fenghua Yu <fenghua.yu@intel.com>
	Cc: Tony Luck <tony.luck@intel.com>
(cherry picked from commit 59fe5a77d473f3519dbee8ef5e77c69897a838f9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>