cxgb4: enable ZLIB_DEFLATE when building cxgb4
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
commit a1cf9c9ffe652a4f109eb2cd8e69d8fcdb855d00

Fixes:
drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.c:39:5: error:
redefinition of 'cudbg_compress_buff'
    int cudbg_compress_buff(struct cudbg_init *pdbg_init,
        ^~~~~~~~~~~~~~~~~~~
   In file included from
drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.c:23:0:
   drivers/net/ethernet/chelsio/cxgb4/cudbg_zlib.h:45:19: note: previous
definition of 'cudbg_compress_buff' was here
    static inline int cudbg_compress_buff(struct cudbg_init *pdbg_init,
                      ^~~~~~~~~~~~~~~~~~~

Fixes: 91c1953de387 ("cxgb4: use zlib deflate to compress firmware dump")
	Signed-off-by: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
	Signed-off-by: Ganesh Goudar <ganeshgr@chelsio.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit a1cf9c9ffe652a4f109eb2cd8e69d8fcdb855d00)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>