arm64: vdso: Fix "no previous prototype" warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070169

commit 58cd4a088e8917b4092c7011d499e277e04a6644
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date: Fri, 21 Jan 2022 12:12:34 +0000

    If compiling the arm64 kernel with W=1 the following warning is produced:

    | arch/arm64/kernel/vdso/vgettimeofday.c:9:5: error: no previous prototype for ‘__kernel_clock_gettime’ [-Werror=missing-prototypes]
    |     9 | int __kernel_clock_gettime(clockid_t clock,
    |       |     ^~~~~~~~~~~~~~~~~~~~~~
    | arch/arm64/kernel/vdso/vgettimeofday.c:15:5: error: no previous prototype for ‘__kernel_gettimeofday’ [-Werror=missing-prototypes]
    |    15 | int __kernel_gettimeofday(struct __kernel_old_timeval *tv,
    |       |     ^~~~~~~~~~~~~~~~~~~~~
    | arch/arm64/kernel/vdso/vgettimeofday.c:21:5: error: no previous prototype for ‘__kernel_clock_getres’ [-Werror=missing-prototypes]
    |    21 | int __kernel_clock_getres(clockid_t clock_id,
    |       |     ^~~~~~~~~~~~~~~~~~~~~

    This patch removes "-Wmissing-prototypes" and "-Wmissing-declarations" compilers
    flags from the compilation of vgettimeofday.c to make possible to build the
    kernel with CONFIG_WERROR enabled.

    Cc: Will Deacon <will@kernel.org>
    Reported-by: Marc Kleine-Budde <mkl@pengutronix.de>
    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Tested-by: Marc Kleine-Budde <mkl@pengutronix.de>
    Link: https://lore.kernel.org/r/20220121121234.47273-1-vincenzo.frascino@arm.com
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>