ALSA: usb-audio: mixer: Remove temporary string use in parse_clock_source_unit
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 26f7111abd8e15726c93bafe16a349f1db2f14e0
Author: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Date: Wed Sep 13 12:39:33 2023 +0300

    ALSA: usb-audio: mixer: Remove temporary string use in parse_clock_source_unit

    The kctl->id.name can be directly passed to snd_usb_copy_string_desc() and
    if the string has been fetched the suffix can be appended with the
    append_ctl_name() call.
    The temporary name string becomes redundant and can be removed.

    This change will also fixes the following compiler warning/error (W=1):

    sound/usb/mixer.c: In function ‘parse_audio_unit’:
    sound/usb/mixer.c:1972:29: error: ‘ Validity’ directive output may be truncated writing 9 bytes into a region of size between 1 and 44 [-Werror=format-truncation=]
     1972 |                          "%s Validity", name);
          |                             ^~~~~~~~~
    In function ‘parse_clock_source_unit’,
        inlined from ‘parse_audio_unit’ at sound/usb/mixer.c:2892:10:
    sound/usb/mixer.c:1971:17: note: ‘snprintf’ output between 10 and 53 bytes into a destination of size 44
     1971 |                 snprintf(kctl->id.name, sizeof(kctl->id.name),
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1972 |                          "%s Validity", name);
          |                          ~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    The warnings got brought to light by a recent patch upstream:
    commit 6d4ab2e97dcf ("extrawarn: enable format and stringop overflow warnings in W=1")

    Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Link: https://lore.kernel.org/r/20230913093933.24564-1-peter.ujfalusi@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>