ice: health.c: fix compilation on gcc 7.5
JIRA: https://issues.redhat.com/browse/RHEL-83567

Upstream commit(s):
commit fa8eda19015ca9ae625f46d4ecb13df651bb54cc
Author: Przemek Kitszel <przemyslaw.kitszel@intel.com>
Date:   Thu Feb 6 23:30:23 2025 +0100

    ice: health.c: fix compilation on gcc 7.5

    GCC 7 is not as good as GCC 8+ in telling what is a compile-time
    const, and thus could be used for static storage.
    Fortunately keeping strings as const arrays is enough to make old
    gcc happy.

    Excerpt from the report:
    My GCC is: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0.

      CC [M]  drivers/net/ethernet/stmicro/stmmac/stmmac_mdio.o
    drivers/net/ethernet/intel/ice/devlink/health.c:35:3: error: initializer element is not constant
       ice_common_port_solutions, {ice_port_number_label}},
       ^~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/intel/ice/devlink/health.c:35:3: note: (near initialization for 'ice_health_status_lookup[0].solution')
    drivers/net/ethernet/intel/ice/devlink/health.c:35:31: error: initializer element is not constant
       ice_common_port_solutions, {ice_port_number_label}},
                                   ^~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/intel/ice/devlink/health.c:35:31: note: (near initialization for 'ice_health_status_lookup[0].data_label[0]')
    drivers/net/ethernet/intel/ice/devlink/health.c:37:46: error: initializer element is not constant
       "Change or replace the module or cable.", {ice_port_number_label}},
                                                  ^~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/intel/ice/devlink/health.c:37:46: note: (near initialization for 'ice_health_status_lookup[1].data_label[0]')
    drivers/net/ethernet/intel/ice/devlink/health.c:39:3: error: initializer element is not constant
       ice_common_port_solutions, {ice_port_number_label}},
       ^~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: 85d6164ec56d ("ice: add fw and port health reporters")
    Reported-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
    Closes: https://lore.kernel.org/netdev/CY8PR11MB7134BF7A46D71E50D25FA7A989F72@CY8PR11MB7134.namprd11.prod.outlook.com
    Reviewed-by: Michal Swiatkowski <michal.swiatkowski@linux.intel.com>
    Suggested-by: Simon Horman <horms@kernel.org>
    Signed-off-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Tested-by: Sunitha Mekala <sunithax.d.mekala@intel.com> (A Contingent worker at Intel)
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Petr Oros <poros@redhat.com>