KVM: x86: avoid warning with -Wbitwise-instead-of-logical
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2074832

commit 3d5e7a28b1ea2d603dea478e58e37ce75b9597ab
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Fri Oct 15 04:50:01 2021 -0400

    KVM: x86: avoid warning with -Wbitwise-instead-of-logical

    This is a new warning in clang top-of-tree (will be clang 14):

    In file included from arch/x86/kvm/mmu/mmu.c:27:
    arch/x86/kvm/mmu/spte.h:318:9: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
            return __is_bad_mt_xwr(rsvd_check, spte) |
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     ||
    arch/x86/kvm/mmu/spte.h:318:9: note: cast one or both operands to int to silence this warning

    The code is fine, but change it anyway to shut up this clever clogs
    of a compiler.

    Reported-by: torvic9@mailbox.org
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>