kunit: Allow passing function pointer to kunit_activate_static_stub()
commit fcbac39b7d5e776bed058281af5d3248b94f1282
Author: Richard Fitzgerald <rf@opensource.cirrus.com>
Date:   Thu Dec 21 10:38:56 2023 +0000

    kunit: Allow passing function pointer to kunit_activate_static_stub()

    Swap the arguments to typecheck_fn() in kunit_activate_static_stub()
    so that real_fn_addr can be either the function itself or a pointer
    to that function.

    This is useful to simplify redirecting static functions in a module.
    Having to pass the actual function meant that it must be exported
    from the module. Either making the 'static' and EXPORT_SYMBOL*()
    conditional (which makes the code messy), or change it to always
    exported (which increases the export namespace and prevents the
    compiler inlining a trivial stub function in non-test builds).

    With the original definition of kunit_activate_static_stub() the
    address of real_fn_addr was passed to typecheck_fn() as the type to
    be passed. This meant that if real_fn_addr was a pointer-to-function
    it would resolve to a ** instead of a *, giving an error like this:

       error: initialization of ‘int (**)(int)’ from incompatible pointer
       type ‘int (*)(int)’ [-Werror=incompatible-pointer-types]
       kunit_activate_static_stub(test, add_one_fn_ptr, subtract_one);
          |                             ^~~~~~~~~~~~
       ./include/linux/typecheck.h:21:25: note: in definition of macro
       ‘typecheck_fn’
       21 | ({ typeof(type) __tmp = function; \

    Swapping the arguments to typecheck_fn makes it take the type of a
    pointer to the replacement function. Either a function or a pointer
    to function can be assigned to that. For example:

    static int some_function(int x)
    {
        /* whatever */
    }

    int (* some_function_ptr)(int) = some_function;

    static int replacement(int x)
    {
        /* whatever */
    }

    Then:
      kunit_activate_static_stub(test, some_function, replacement);
    yields:
      typecheck_fn(typeof(&replacement), some_function);

    and:
      kunit_activate_static_stub(test, some_function_ptr, replacement);
    yields:
      typecheck_fn(typeof(&replacement), some_function_ptr);

    The two typecheck_fn() then resolve to:

      int (*__tmp)(int) = some_function;
    and
      int (*__tmp)(int) = some_function_ptr;

    Both of these are valid. In the first case the compiler inserts
    an implicit '&' to take the address of the supplied function, and
    in the second case the RHS is already a pointer to the same type.

    Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Reviewed-by: Rae Moar <rmoar@google.com>
    Reviewed-by: David Gow <davidgow@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

JIRA: https://issues.redhat.com/browse/RHEL-39303
Signed-off-by: Nico Pache <npache@redhat.com>