kunit: tool: Import missing importlib.abc
commit 235528072f28b3b0a1446279b7eaddda36dbf743
Author: Michał Winiarski <michal.winiarski@intel.com>
Date:   Thu Jan 13 00:36:57 2022 +0100

    kunit: tool: Import missing importlib.abc

    Python 3.10.0 contains:
    9e09849d20 ("bpo-41006: importlib.util no longer imports typing (GH-20938)")

    It causes importlib.util to no longer import importlib.abs, which leads
    to the following error when trying to use kunit with qemu:
    AttributeError: module 'importlib' has no attribute 'abc'. Did you mean: '_abc'?

    Add the missing import.

    Signed-off-by: Michał Winiarski <michal.winiarski@intel.com>
    Reviewed-by: Daniel Latypov <dlatypov@google.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>