kernel: trace: preemptirq_delay_test: use offstack cpu mask
JIRA: https://issues.redhat.com/browse/RHEL-115358

commit adc353c0bfb243ebfd29b6222fa3bf149169a6de
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 20 13:12:12 2025 +0200

    kernel: trace: preemptirq_delay_test: use offstack cpu mask

    A CPU mask on the stack is broken for large values of CONFIG_NR_CPUS:

    kernel/trace/preemptirq_delay_test.c: In function ‘preemptirq_delay_run’:
    kernel/trace/preemptirq_delay_test.c:143:1: error: the frame size of 8512 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

    Fall back to dynamic allocation here.

    Cc: Masami Hiramatsu <mhiramat@kernel.org>
    Cc: Song Chen <chensong_2000@189.cn>
    Cc: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
    Link: https://lore.kernel.org/20250620111215.3365305-1-arnd@kernel.org
    Fixes: 4b9091e1c194 ("kernel: trace: preemptirq_delay_test: add cpu affinity")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>