soundwire: intel_ace2x: add SND_HDA_CORE dependency
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit dc3a6a942e9ee3f18560bfcb16c06bb94f37fabf
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Dec 23 22:50:01 2025 +0100

    soundwire: intel_ace2x: add SND_HDA_CORE dependency

    The ace2x driver can optionally use the HDA infrastructure, but can still
    build without that. However, with SND_HDA_CORE=m and SND_HDA_ALIGNED_MMIO=y,
    it fails to link as built-in:

    aarch64-linux-ld: drivers/soundwire/intel_ace2x.o: in function `intel_shim_wake':
    intel_ace2x.c:(.text+0x2518): undefined reference to `snd_hdac_aligned_read'
    aarch64-linux-ld: intel_ace2x.c:(.text+0x25d4): undefined reference to `snd_hdac_aligned_read'
    aarch64-linux-ld: intel_ace2x.c:(.text+0x268c): undefined reference to `snd_hdac_aligned_write'

    Add a Kconfig dependency that forces the soundwire driver to be a loadable
    module if necessary.

    Fixes: 79e7123c078d ("soundwire: intel_ace2x: fix wakeup handling")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20251223215014.534756-1-arnd@kernel.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>