vdpa-sim: depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Michael S. Tsirkin <mst@redhat.com>
commit 355b36e6bfd35bd4f4f28f182bb2f8bc07295c88

set_dma_ops isn't available on all architectures:

        make ARCH=um
...

   drivers/vdpa/vdpa_sim/vdpa_sim.c: In function 'vdpasim_create':
>> drivers/vdpa/vdpa_sim/vdpa_sim.c:324:2: error: implicit declaration of function 'set_dma_ops'; did you mean 'set_groups'?
+[-Werror=implicit-function-declaration]
     set_dma_ops(dev, &vdpasim_dma_ops);
     ^~~~~~~~~~~
     set_groups

Disable vdpa-sim on architectures where it isn't.

	Acked-by: Jason Wang <jasowang@redhat.com>
	Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit 355b36e6bfd35bd4f4f28f182bb2f8bc07295c88)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>