bpf: Fix build error without CONFIG_INET
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 7f94208c8f9a0a6d2ff0e0c0858c00ad8e5c8617

If CONFIG_INET is not set, building fails:

kernel/bpf/verifier.o: In function `check_mem_access':
verifier.c: undefined reference to `bpf_xdp_sock_is_valid_access'
kernel/bpf/verifier.o: In function `convert_ctx_accesses':
verifier.c: undefined reference to `bpf_xdp_sock_convert_ctx_access'

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: fada7fdc83c0 ("bpf: Allow bpf_map_lookup_elem() on an xskmap")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Acked-by: Jonathan Lemon <jonathan.lemon@gmail.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit 7f94208c8f9a0a6d2ff0e0c0858c00ad8e5c8617)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>