x86/pat: Fix W=1 build warning when the within_inclusive() function is unused
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 3fcae7771fb724c276e87e80827b264d2c3ad67e
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Tue Feb 11 16:57:21 2025 +0200

    x86/pat: Fix W=1 build warning when the within_inclusive() function is unused

    The within_inclusive() function, in some cases, when CONFIG_X86_64=n,
    may be not used.

    This, in particular, prevents kernel builds with Clang, `make W=1`
    and CONFIG_WERROR=y:

      arch/x86/mm/pat/set_memory.c:215:1: error: unused function 'within_inclusive' [-Werror,-Wunused-function]

    Fix this by guarding the definitions with the respective ifdeffery.

    See also:

      6863f5643dd7 ("kbuild: allow Clang to find unused static inline functions for W=1 build")

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20250211145721.1620552-1-andriy.shevchenko@linux.intel.com

Signed-off-by: Rafael Aquini <raquini@redhat.com>