cpufreq: intel_pstate: fix intel_pstate_exit_perf_limits() prototype
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [cpufreq] intel_pstate: fix intel_pstate_exit_perf_limits() prototype (Prarit Bhargava) [1465349]
Rebuild_FUZZ: 92.91%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7a3ba767f6bf9d98f1c823417908719af4a22a65
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/7a3ba767.failed

The addition of the generic governor support marked the
intel_pstate_exit_perf_limits as inline(), which fixed a warning,
but it introduced another warning:

drivers/cpufreq/intel_pstate.c: In function ‘intel_pstate_exit_perf_limits’:
drivers/cpufreq/intel_pstate.c:483:1: error: no return statement in function returning non-void [-Werror=return-type]

This changes it back to a 'void' return type, and changes the
corresponding intel_pstate_init_acpi_perf_limits() function to
be inline as well for consistency.

Fixes: 001c76f05b01 (cpufreq: intel_pstate: Generic governors support)
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 7a3ba767f6bf9d98f1c823417908719af4a22a65)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/cpufreq/intel_pstate.c