crypto: qat - use swab32 macro
JIRA: https://redhat.atlassian.net/browse/RHEL-115836
Upstream Status: merged into the upstream linux.git

commit 35ecb77ae0749a2f1b04872c9978d9d7ddbbeb79
Author: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
Date:   Sat Mar 28 22:29:46 2026 +0000

    crypto: qat - use swab32 macro

    Replace __builtin_bswap32() with swab32 in icp_qat_hw_20_comp.h to fix
    the following build errors on architectures without native byte-swap
    support:

       alpha-linux-ld: drivers/crypto/intel/qat/qat_common/adf_gen4_hw_data.o: in function `adf_gen4_build_decomp_block':
       drivers/crypto/intel/qat/qat_common/icp_qat_hw_20_comp.h:141:(.text+0xeec): undefined reference to `__bswapsi2'
       alpha-linux-ld: drivers/crypto/intel/qat/qat_common/icp_qat_hw_20_comp.h:141:(.text+0xef8): undefined reference to `__bswapsi2'
       alpha-linux-ld: drivers/crypto/intel/qat/qat_common/adf_gen4_hw_data.o: in function `adf_gen4_build_comp_block':
       drivers/crypto/intel/qat/qat_common/icp_qat_hw_20_comp.h:57:(.text+0xf64): undefined reference to `__bswapsi2'
       alpha-linux-ld: drivers/crypto/intel/qat/qat_common/icp_qat_hw_20_comp.h:57:(.text+0xf7c): undefined reference to `__bswapsi2'

    Fixes: 5b14b2b307e4 ("crypto: qat - enable deflate for QAT GEN4")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202603290259.Ig9kDOmI-lkp@intel.com/
    Signed-off-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladislav Dronov <vdronov@redhat.com>