soundwire: intel: fix another unused-function warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: soundwire: intel: fix another unused-function warning (Jaroslav Kysela) [1783462]
Rebuild_FUZZ: 94.64%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 17e0da0b8979a53977f684813f5c9db817d170e2

Without CONFIG_PM, there is another warning about an unused function:

drivers/soundwire/intel.c:530:12: error: 'intel_link_power_down' defined but not used [-Werror=unused-function]

After a previous fix, the driver already uses both an #ifdef and
a __maybe_unused annotation but still gets it wrong. Remove the
ifdef and instead use __maybe_unused consistently to avoid the
problem for good.

Fixes: f046b2334083 ("soundwire: intel: fix intel_suspend/resume defined but not used warning")
Fixes: ebf878eddbb4 ("soundwire: intel: add pm_runtime support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20201203230502.1480063-1-arnd@kernel.org
	Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit 17e0da0b8979a53977f684813f5c9db817d170e2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>