KVM: PPC: Move and undef TRACE_INCLUDE_PATH/FILE
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Scott Wood <oss@buserror.net>
commit 28c5bcf74fa07c25d5bd118d1271920f51ce2a98

TRACE_INCLUDE_PATH and TRACE_INCLUDE_FILE are used by
<trace/define_trace.h>, so like that #include, they should
be outside #ifdef protection.

They also need to be #undefed before defining, in case multiple trace
headers are included by the same C file.  This became the case on
book3e after commit cf4a6085151a ("powerpc/mm: Add missing tracepoint for
tlbie"), leading to the following build error:

   CC      arch/powerpc/kvm/powerpc.o
In file included from arch/powerpc/kvm/powerpc.c:51:0:
arch/powerpc/kvm/trace.h:9:0: error: "TRACE_INCLUDE_PATH" redefined
[-Werror]
  #define TRACE_INCLUDE_PATH .
  ^
In file included from arch/powerpc/kvm/../mm/mmu_decl.h:25:0,
                  from arch/powerpc/kvm/powerpc.c:48:
./arch/powerpc/include/asm/trace.h:224:0: note: this is the location of
the previous definition
  #define TRACE_INCLUDE_PATH asm
  ^
cc1: all warnings being treated as errors

	Reported-by: Christian Zigotzky <chzigotzky@xenosoft.de>
	Signed-off-by: Scott Wood <oss@buserror.net>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 28c5bcf74fa07c25d5bd118d1271920f51ce2a98)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>