wifi: ath10k: improve structure padding
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 12ec37be3faf9df7831ce210947f111b3417baf3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 16 11:04:21 2023 +0200

    wifi: ath10k: improve structure padding
    
    Including an aligned structure inside of a packed one is ambiguous
    and can lead to misaligned data, as pointed out by this clang warning:
    
    drivers/net/wireless/ath/ath10k/htt.h:715:34: error: field prefix within 'struct htt_rx_indication' is less aligned than 'struct htt_rx_indication_prefix' and is usually due to 'struct htt_rx_indication' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
            struct htt_rx_indication_prefix prefix;
                                            ^
    drivers/net/wireless/ath/ath10k/htt.h:736:34: error: field prefix within 'struct htt_rx_indication_hl' is less aligned than 'struct htt_rx_indication_prefix' and is usually due to 'struct htt_rx_indication_hl' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
            struct htt_rx_indication_prefix prefix;
                                            ^
    drivers/net/wireless/ath/ath10k/htt.h:1564:2: error: field  within 'struct htt_tx_fetch_ind' is less aligned than 'union htt_tx_fetch_ind::(anonymous at drivers/net/wireless/ath/ath10k/htt.h:1564:2)' and is usually due to 'struct htt_tx_fetch_ind' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
            union {
            ^
    drivers/net/wireless/ath/ath10k/htt.h:1702:2: error: field  within 'struct htt_resp' is less aligned than 'union htt_resp::(anonymous at drivers/net/wireless/ath/ath10k/htt.h:1702:2)' and is usually due to 'struct htt_resp' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
    
    These structures appear to actually need the packing since they
    are embedded at misaligned offsets. Add even more such annotations
    here to enforce bytewise access throughout the driver.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20230616090439.2484857-1-arnd@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>