ASoC: intel: make function stub static
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: make function stub static (Jaroslav Kysela) [1463624]
Rebuild_FUZZ: 92.68%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 2d0b29dca8d6fe49a73cfc16888c1d2e55111d7b

This function stub should have been 'static' in the original patch
so that multiple uses of the header file (in different drivers)
will not cause multiple function definitions.

sound/soc/intel/boards/built-in.o: In function `sst_acpi_find_name_from_hid':
(.text+0x560): multiple definition of `sst_acpi_find_name_from_hid'
sound/soc/intel/atom/built-in.o:(.text+0x10610): first defined here
../scripts/Makefile.build:369: recipe for target 'sound/soc/intel/built-in.o' failed

Fixes: f17131a93f43: add function stub when ACPI is not enabled

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2d0b29dca8d6fe49a73cfc16888c1d2e55111d7b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>