erspan: remove the incorrect mtu limit for erspan
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Haishuang Yan <yanhaishuang@cmss.chinamobile.com>
commit 0e141f757b2c78c983df893e9993313e2dc21e38

erspan driver calls ether_setup(), after commit 61e84623ace3
("net: centralize net_device min/max MTU checking"), the range
of mtu is [min_mtu, max_mtu], which is [68, 1500] by default.

It causes the dev mtu of the erspan device to not be greater
than 1500, this limit value is not correct for ipgre tap device.

Tested:
Before patch:
# ip link set erspan0 mtu 1600
Error: mtu greater than device maximum.
After patch:
# ip link set erspan0 mtu 1600
# ip -d link show erspan0
21: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1600 qdisc noop state DOWN
mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 0

Fixes: 61e84623ace3 ("net: centralize net_device min/max MTU checking")
	Signed-off-by: Haishuang Yan <yanhaishuang@cmss.chinamobile.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 0e141f757b2c78c983df893e9993313e2dc21e38)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>