ALSA:usb:qcom: add AUXILIARY_BUS to Kconfig dependencies
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit b8bee48e38f2ddbdba5e58bc54ef54bb7d8d341b
Author: Frank Zhang <rmxpzlb@gmail.com>
Date: Tue Mar 17 18:25:27 2026 +0800

    ALSA:usb:qcom: add AUXILIARY_BUS to Kconfig dependencies

    The build can fail with:

    ERROR: modpost: "__auxiliary_driver_register"
    [sound/usb/qcom/snd-usb-audio-qmi.ko] undefined!
    ERROR: modpost: "auxiliary_driver_unregister"
    [sound/usb/qcom/snd-usb-audio-qmi.ko] undefined!

    Select AUXILIARY_BUS when SND_USB_AUDIO_QMI is enabled.

    Signed-off-by: Frank Zhang <rmxpzlb@gmail.com>
    Link: https://patch.msgid.link/20260317102527.556248-1-rmxpzlb@gmail.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>