ASoC: hdac_hdmi: don't update the iterator in pcm list remove
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: hdac_hdmi: don't update the iterator in pcm list remove (Jaroslav Kysela) [1463624]
Rebuild_FUZZ: 95.31%
commit-author Jeeja KP <jeeja.kp@intel.com>
commit 2fe42dd0f13812d38daaf05bcb1fd996afd0e87a

Fix not to update the iterator element, instead use list_del to remove
entry from the list.

This fixes the following coccinelle and static checker warning:
sound/soc/codecs/hdac_hdmi.c:1884:2-21:iterator with update on line
1885
sound/soc/codecs/hdac_hdmi.c:2011 hdac_hdmi_dev_remove()
	error: potential NULL dereference 'port'.

Fixes: e0e5d3e5a53b('ASoC: hdac_hdmi: Add support for multiple ports to a PCM')
	Reported-by: Julia Lawall <Julia.Lawall@lip6.fr>
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Jeeja KP <jeeja.kp@intel.com>
	Acked-by: Vinod Koul <vinod.koul@intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2fe42dd0f13812d38daaf05bcb1fd996afd0e87a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>