arch/x86/kvm/mmu.c: work around gcc-4.4.4 bug
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Andrew Morton <akpm@linux-foundation.org>
commit 4141259b56cbd5a8614e487366909a02d702b9dd

arch/x86/kvm/mmu.c: In function 'kvm_mmu_pte_write':
arch/x86/kvm/mmu.c:4256: error: unknown field 'cr0_wp' specified in initializer
arch/x86/kvm/mmu.c:4257: error: unknown field 'cr4_pae' specified in initializer
arch/x86/kvm/mmu.c:4257: warning: excess elements in union initializer
...

gcc-4.4.4 (at least) has issues when using anonymous unions in
initializers.

Fixes: edc90b7dc4ceef6 ("KVM: MMU: fix SMAP virtualization")
	Cc: Xiao Guangrong <guangrong.xiao@linux.intel.com>
	Cc: Paolo Bonzini <pbonzini@redhat.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 4141259b56cbd5a8614e487366909a02d702b9dd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>