perf tools: Cleanup trace-event-info 'tdata' leak
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Sanskriti Sharma <sansharm@redhat.com>
commit faedbf3fd19f2511a39397f76359e4cc6ee93072

Free tracing_data structure in tracing_data_get() error paths.

Fixes the following coverity complaint:

  Error: RESOURCE_LEAK (CWE-772):
  leaked_storage: Variable "tdata" going out of scope leaks the storage

	Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
	Reviewed-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Joe Lawrence <joe.lawrence@redhat.com>
Link: http://lkml.kernel.org/r/1538490554-8161-3-git-send-email-sansharm@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit faedbf3fd19f2511a39397f76359e4cc6ee93072)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>