powerpc/pseries: Fix build break for SPLPAR=n and CPU hotplug
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [powerpc] pseries: Fix build break for SPLPAR=n and CPU hotplug (Gustavo Duarte) [1544437]
Rebuild_FUZZ: 92.98%
commit-author Guenter Roeck <linux@roeck-us.net>
commit 82343484a2d4c97a03bfd81303b5493c65f05c50

Commit e67e02a544e9 ("powerpc/pseries: Fix cpu hotplug crash with
memoryless nodes") adds an unconditional call to
find_and_online_cpu_nid(), which is only declared if CONFIG_PPC_SPLPAR
is enabled. This results in the following build error if this is not
the case.

  arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_online_cpu':
  arch/powerpc/platforms/pseries/hotplug-cpu.c:369:
  			undefined reference to `.find_and_online_cpu_nid'

Follow the guideline provided by similar functions and provide a dummy
function if CONFIG_PPC_SPLPAR is not enabled. This also moves the
external function declaration into an include file where it should be.

Fixes: e67e02a544e9 ("powerpc/pseries: Fix cpu hotplug crash with memoryless nodes")
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
[mpe: Change subject to emphasise the build fix]
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 82343484a2d4c97a03bfd81303b5493c65f05c50)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>