Bluetooth: hci_qca: Fix build error
JIRA: https://issues.redhat.com/browse/RHEL-61734

commit 84f9288208dfcd955446060a53add15b9e01af4e
Author: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Date:   Wed Jul 10 22:30:57 2024 -0400

    Bluetooth: hci_qca: Fix build error

    This fixes the following build error introduced by b80f4e3b8cb8
    ("Bluetooth: hci_qca: schedule a devm action for disabling the clock"):

    drivers/bluetooth/hci_qca.c: In function ‘qca_serdev_remove’:
    drivers/bluetooth/hci_qca.c:2501:2: error: label at end of compound statement
     2501 |  default:
          |  ^~~~~~~

    Fixes: b80f4e3b8cb8 ("Bluetooth: hci_qca: schedule a devm action for disabling the clock")
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>