cpuidle: Update header inclusion
JIRA: https://redhat.atlassian.net/browse/RHEL-176383

commit 6d96ceff9aeb7e7a1713faaccf472f363cc6d48f
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date: Tue, 25 Nov 2025 19:04:29 +0000

While cleaning up some headers, I got a build error on this file:

drivers/cpuidle/poll_state.c:52:2: error: call to undeclared library function 'snprintf' with type 'int (char *restrict, unsigned long, const char *restrict, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

Update header inclusions to follow IWYU (Include What You Use)
principle.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Link: https://patch.msgid.link/20251124205752.1328701-1-andriy.shevchenko@linux.intel.com
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>