ASoC: SOF: ipc3: add checks to prevent static analysis warnings
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit e44222c213678d6ef646d72cbb9a2eda52f6dc22
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Mon Jul 31 16:37:42 2023 -0500

    ASoC: SOF: ipc3: add checks to prevent static analysis warnings

    make KCFLAGS='-fanalyzer' sound/soc/sof/ reports an issue with memcpy:

    sound/soc/sof/ipc3.c: In function ‘ipc3_wait_tx_done’:
    sound/soc/sof/ipc3.c:309:33: error: use of NULL ‘reply_data’ where
    non-null expected [CWE-476] [-Werror=analyzer-null-argument]

      309 |                        memcpy(reply_data, msg->reply_data,
          |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      310 |                               msg->reply_size);

    The finding is legit with this call:
        return sof_ipc3_tx_msg(sdev, &pm_ctx, sizeof(pm_ctx), NULL, 0, false);

    Static analysis has no way of knowing that the reply will be zero-sized.

    Add a check to only do the memcpy if the reply size is not zero and
    the destination pointer is not NULL.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Reviewed-by: Rander Wang <rander.wang@intel.com>
    Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
    Reviewed-by: Yaochun Hung <yc.hung@mediatek.com>
    Link: https://lore.kernel.org/r/20230731213748.440285-3-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>