nfs4: fix missing-braces warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 83aa3e0f791d458a28f91d7a50f92926f971ef7c

A bugfix introduced a harmless warning for update_open_stateid:

fs/nfs/nfs4proc.c:1548:2: error: missing braces around initializer [-Werror=missing-braces]

Removing the zero in the initializer will do the right thing here
and initialize the entire structure to zero.

Fixes: 1393d9612ba0 ("NFSv4: Fix a race when updating an open_stateid")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
(cherry picked from commit 83aa3e0f791d458a28f91d7a50f92926f971ef7c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>