i2c: nvidia-gpu: mark resume function as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 32774a8153b4c62e408297fba352248afb2e0143

When CONFIG_PM is disabled, this is needed to avoid a harmless
unused-function warning:

drivers/i2c/busses/i2c-nvidia-gpu.c:345:12: error: 'gpu_i2c_resume' defined but not used [-Werror=unused-function]

Fixes: c71bcdcb42a7 ("i2c: add i2c bus driver for NVIDIA GPU")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
(cherry picked from commit 32774a8153b4c62e408297fba352248afb2e0143)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>