netfilter: nft_set_hash: fix get operation on big endian
JIRA: https://issues.redhat.com/browse/RHEL-152685
Upstream Status: commit 2f635adbe264

commit 2f635adbe2642d398a0be3ab245accd2987be0c3
Author: Florian Westphal <fw@strlen.de>
Date:   Tue Jan 27 20:13:45 2026 +0100

    netfilter: nft_set_hash: fix get operation on big endian

    tests/shell/testcases/packetpath/set_match_nomatch_hash_fast
    fails on big endian with:

    Error: Could not process rule: No such file or directory
    reset element ip test s { 244.147.90.126 }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Fatal: Cannot fetch element "244.147.90.126"

    ... because the wrong bucket is searched, jhash() and jhash1_word are
    not interchangeable on big endian.

    Fixes: 3b02b0adc242 ("netfilter: nft_set_hash: fix lookups with fixed size hash on big endian")
    Signed-off-by: Florian Westphal <fw@strlen.de>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>