pinctrl: tegra: avoid duplicate field initializers
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2222432
Tested: Pinctrl sanity testing done on Orin AGX

commit d18b2a0f1a78871104695ba9d3b03274bf8e07a1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 16 18:15:55 2023 +0200

    pinctrl: tegra: avoid duplicate field initializers

    The drv_reg field is initialized both in the DRV_PINGROUP_ENTRY_N/DRV_PINGROUP_ENTRY_Y
    macros and in DRV_PINGROUP_Y. Since each pingroup expands both macros, the are
    always duplicate and turning on -Woverride-init (which is disabled by default)
    causes a huge amount of warnings like:

    drivers/pinctrl/tegra/pinctrl-tegra234.c:1384:27: error: initialized field overwritten [-Werror=override-init]
     1384 | #define DRV_PINGROUP_Y(r) ((r))
          |                           ^
    drivers/pinctrl/tegra/pinctrl-tegra234.c:1397:28: note: in expansion of macro 'DRV_PINGROUP_Y'
     1397 |                 .drv_reg = DRV_PINGROUP_Y(r),                   \
          |                            ^~~~~~~~~~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra234.c:1447:49: note: in expansion of macro 'DRV_PINGROUP_ENTRY_Y'
     1447 | #define drive_soc_gpio08_pb0                    DRV_PINGROUP_ENTRY_Y(0x500c,    12,     5,      20,     5,      -1,     -1,     -1,     -1,     0)
          |                                                 ^~~~~~~~~~~~~~~~~~~~
    ...

    Remove the intialization that is never used here.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230616161603.1127687-1-arnd@kernel.org
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
    (cherry picked from commit d18b2a0f1a78871104695ba9d3b03274bf8e07a1)

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>