usb: gadget: fsl_qe_udc: Add missing semicolon in qe_ep_dequeue()
Bugzilla: http://bugzilla.redhat.com/2084667
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46653455
Tested: HP ZBook 15 G5/80D5 Laptop

commit 46d2c20b0b10cf07a2a24b047a09195ba96c84f7
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Sat Mar 19 14:50:31 2022 +0800

    usb: gadget: fsl_qe_udc: Add missing semicolon in qe_ep_dequeue()

    drivers/usb/gadget/udc/fsl_qe_udc.c: In function ‘qe_ep_dequeue’:
    drivers/usb/gadget/udc/fsl_qe_udc.c:1792:3: error: expected ‘;’ before ‘req’
       req = iter;
       ^~~
    Add missing semicolon to fix this.

    Fixes: 838884110f0d ("usb: gadget: fsl: remove usage of list iterator past the loop body")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Link: https://lore.kernel.org/r/20220319065031.36928-1-yuehaibing@huawei.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>