devlink: Fix excessive stack usage in rate TC bandwidth parsing
JIRA: https://issues.redhat.com/browse/RHEL-121724

Upstream commit(s):
commit 1bbdb81a98363fd5cd0c2ac16ad5346bdf814dff
Author: Carolina Jubran <cjubran@nvidia.com>
Date:   Tue Jul 22 12:13:29 2025 +0300

    devlink: Fix excessive stack usage in rate TC bandwidth parsing

    The devlink_nl_rate_tc_bw_parse function uses a large stack array for
    devlink attributes, which triggers a warning about excessive stack
    usage:

    net/devlink/rate.c: In function 'devlink_nl_rate_tc_bw_parse':
    net/devlink/rate.c:382:1: error: the frame size of 1648 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

    Introduce a separate attribute set specifically for rate TC bandwidth
    parsing that only contains the two attributes actually used: index
    and bandwidth. This reduces the stack array from DEVLINK_ATTR_MAX
    entries to just 2 entries, solving the stack usage issue.

    Update devlink selftest to use the new 'index' and 'bw' attribute names
    consistent with the YAML spec.

    Example usage with ynl with the new spec:

        ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/devlink.yaml \
          --do rate-set --json '{
          "bus-name": "pci",
          "dev-name": "0000:08:00.0",
          "port-index": 1,
          "rate-tc-bws": [
            {"index": 0, "bw": 50},
            {"index": 1, "bw": 50},
            {"index": 2, "bw": 0},
            {"index": 3, "bw": 0},
            {"index": 4, "bw": 0},
            {"index": 5, "bw": 0},
            {"index": 6, "bw": 0},
            {"index": 7, "bw": 0}
          ]
        }'

        ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/devlink.yaml \
          --do rate-get --json '{
          "bus-name": "pci",
          "dev-name": "0000:08:00.0",
          "port-index": 1
        }'

        output for rate-get:
        {'bus-name': 'pci',
         'dev-name': '0000:08:00.0',
         'port-index': 1,
         'rate-tc-bws': [{'bw': 50, 'index': 0},
                         {'bw': 50, 'index': 1},
                         {'bw': 0, 'index': 2},
                         {'bw': 0, 'index': 3},
                         {'bw': 0, 'index': 4},
                         {'bw': 0, 'index': 5},
                         {'bw': 0, 'index': 6},
                         {'bw': 0, 'index': 7}],
         'rate-tx-max': 0,
         'rate-tx-priority': 0,
         'rate-tx-share': 0,
         'rate-tx-weight': 0,
         'rate-type': 'leaf'}

    Fixes: 566e8f108fc7 ("devlink: Extend devlink rate API with traffic classes bandwidth management")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Closes: https://lore.kernel.org/netdev/20250708160652.1810573-1-arnd@kernel.org/
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202507171943.W7DJcs6Y-lkp@intel.com/
    Suggested-by: Jakub Kicinski <kuba@kernel.org>
    Signed-off-by: Carolina Jubran <cjubran@nvidia.com>
    Tested-by: Carolina Jubran <cjubran@nvidia.com>
    Signed-off-by: Tariq Toukan <tariqt@nvidia.com>
    Reviewed-by: Jiri Pirko <jiri@nvidia.com>
    Link: https://patch.msgid.link/1753175609-330621-1-git-send-email-tariqt@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>