mm/vmstat: fix a W=1 clang compiler warning
JIRA: https://issues.redhat.com/browse/RHEL-78135

commit 30c2de0a267c04046d89e678cc0067a9cfb455df
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Thu Dec 12 13:31:26 2024 -0800

    mm/vmstat: fix a W=1 clang compiler warning

    Fix the following clang compiler warning that is reported if the kernel is
    built with W=1:

    ./include/linux/vmstat.h:518:36: error: arithmetic between different enumeration types ('enum node_stat_item' and 'enum lru_list') [-Werror,-Wenum-enum-conversion]
      518 |         return node_stat_name(NR_LRU_BASE + lru) + 3; // skip "nr_"
          |                               ~~~~~~~~~~~ ^ ~~~

    Link: https://lkml.kernel.org/r/20241212213126.1269116-1-bvanassche@acm.org
    Fixes: 9d7ea9a297e6 ("mm/vmstat: add helpers to get vmstat item names for each enum type")
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Cc: Konstantin Khlebnikov <koct9i@gmail.com>
    Cc: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Luiz Capitulino <luizcap@redhat.com>