ACPI: sysfs: fix some coding style issues
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Xiaofei Tan <tanxiaofei@huawei.com>
commit d0fb66e999ffafe425833b8bdfcaabb3d7941c93

Fix some coding style issues reported by checkpatch.pl, including
following types:

WARNING: Missing a blank line after declarations
WARNING: Block comments should align the * on each line
ERROR: open brace '{' following function definitions go on the next line

	Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit d0fb66e999ffafe425833b8bdfcaabb3d7941c93)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>