ASoC: cs42l42: Fix missing include of gpio/consumer.h
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit d6cbc6a3a856a7d8047316d81e2e039e44432acb
Author: Richard Fitzgerald <rf@opensource.cirrus.com>
Date: Wed Oct 11 14:48:53 2023 +0100

    ASoC: cs42l42: Fix missing include of gpio/consumer.h

    The call to gpiod_set_value_cansleep() in cs42l42_sdw_update_status()
    needs the header file gpio/consumer.h to be included.

    This was introduced by commit 2d066c6a7865 ("ASoC: cs42l42: Avoid stale
    SoundWire ATTACH after hard reset")

    and caused error:
        sound/soc/codecs/cs42l42-sdw.c:374:4: error: implicit declaration of
        function ‘gpiod_set_value_cansleep’;
        did you mean gpio_set_value_cansleep’?

    Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Fixes: 2d066c6a7865 ("ASoC: cs42l42: Avoid stale SoundWire ATTACH after hard reset")
    Link: https://lore.kernel.org/r/20231011134853.20059-1-rf@opensource.cirrus.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>