perf stat: Fix error return code in bperf__load()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Yu Kuai <yukuai3@huawei.com>
commit d3fddc355a4a4415e8d43d1faae1be713d65cf5e

Fix to return a negative error code from the error handling case instead
of 0, as done elsewhere in this function.

Committer notes:

Added the missing {} for the now multiline 'if' block, fixing this error:

    CC      /tmp/build/perf/util/bpf_counter.o
  util/bpf_counter.c: In function ‘bperf__load’:
  util/bpf_counter.c:523:9: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
    523 |         if (evsel->bperf_leader_link_fd < 0 &&
        |         ^~
  util/bpf_counter.c:526:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    526 |                 goto out;
        |                 ^~~~
  cc1: all warnings being treated as errors

Fixes: 7fac83aaf2eecc9e ("perf stat: Introduce 'bperf' to share hardware PMCs with BPF")
	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Yu Kuai <yukuai3@huawei.com>
	Cc: Alexei Starovoitov <ast@kernel.org>
	Cc: Andrii Nakryiko <andrii@kernel.org>
	Cc: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Song Liu <songliubraving@fb.com>
	Cc: Yu Kuai <yukuai3@huawei.com>
	Cc: Zhang Yi <yi.zhang@huawei.com>
Link: http://lore.kernel.org/lkml/20210517081254.1561564-1-yukuai3@huawei.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit d3fddc355a4a4415e8d43d1faae1be713d65cf5e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>