perf bench breakpoint: Fix build on 32-bit arches
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit df36d2572e0515dc190459489c159b78bb3a21fc
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon May 16 21:18:11 2022 -0300

description
===========
Cast pointers to unsigned long instead of to uint64_t to avoid this
problem on 32-bit arches:

  31     6.89 debian:experimental-x-mips    : FAIL gcc version 11.2.0 (Debian 11.2.0-18)
    bench/breakpoint.c: In function 'breakpoint_setup':
    bench/breakpoint.c:56:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
       56 |         attr.bp_addr = (uint64_t)addr;
          |                        ^
    cc1: all warnings being treated as errors
    make[3]: *** [/git/perf-5.18.0-rc7/tools/build/Makefile.build:139: bench] Error 2

Fixes: 68a6772f11dbb1ed ("perf bench: Add breakpoint benchmarks")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>