perf jevents: fix no member named 'entries' issue
JIRA: https://issues.redhat.com/browse/RHEL-15009

upstream
========
commit e49be27e18c59639be28cd0d766caf594fe2b77f
Author: Xu Yang <xu.yang_2@nxp.com>
Date: Tue Sep 19 16:09:29 2023 +0800

description
===========
The struct "pmu_events_table" has been changed after commit
2e255b4f9f41 (perf jevents: Group events by PMU, 2023-08-23).
So there doesn't exist 'entries' in pmu_events_table anymore.
This will align the members with that commit. Othewise, below
errors will be printed when run jevent.py:

pmu-events/pmu-events.c:5485:26: error: ‘struct pmu_metrics_table’ has no member named ‘entries’
 5485 |                         .entries = pmu_metrics__freescale_imx8dxl_sys,

    Signed-off-by: Xu Yang <xu.yang_2@nxp.com>
    Reviewed-by: Ian Rogers <irogers@google.com>
    Tested-by: Namhyung Kim <namhyung@kernel.org>
    Link: https://lore.kernel.org/r/20230919080929.3807123-1-xu.yang_2@nxp.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>