perf: arm_cspmu: Fix build failure on x86_64
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2128086

commit e72dbf9085b56bbc19ff332f82adec1891077637
Author: Besar Wicaksono <bwicaksono@nvidia.com>
Date: Wed, 16 Nov 2022 13:04:55 -0600

    Building on x86_64 allmodconfig failed:
      | drivers/perf/arm_cspmu/arm_cspmu.c:1114:29: error: implicit
      |    declaration of function 'get_acpi_id_for_cpu'

    get_acpi_id_for_cpu is a helper function from ARM64.
    Fix by adding ARM64 dependency.

    Signed-off-by: Besar Wicaksono <bwicaksono@nvidia.com>
    Reviewed-by: Suzuki K Poulose <suzuki.poulose@arm.com>
    Link: https://lore.kernel.org/r/20221116190455.55651-1-bwicaksono@nvidia.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>