usb: add HAS_IOMEM dependency to USB_OXU210HP_HCD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_OXU210HP_HCD (Torez Smith) [1332712]
Rebuild_FUZZ: 94.62%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit f4a5d7028a20ee87e128a0e5fec5321fc831d1de
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/f4a5d702.failed

drivers/built-in.o: In function `oxu_drv_probe':
/home/vegard/linux/drivers/usb/host/oxu210hp-hcd.c:3821: undefined reference to `devm_ioremap_resource'

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit f4a5d7028a20ee87e128a0e5fec5321fc831d1de)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/usb/host/Kconfig