net/mlx4_core: Avoid impossible mlx4_db_alloc() order value
JIRA: https://issues.redhat.com/browse/RHEL-72015
JIRA: https://issues.redhat.com/browse/RHEL-72020
JIRA: https://issues.redhat.com/browse/RHEL-72224
JIRA: https://issues.redhat.com/browse/RHEL-73519
Upstream-status: v6.15-rc1

commit 4a6f18f28627e121bd1f74b5fcc9f945d6dbeb1e
Author: Kees Cook <kees@kernel.org>
Date:   Mon Feb 10 09:45:05 2025 -0800

    net/mlx4_core: Avoid impossible mlx4_db_alloc() order value

    GCC can see that the value range for "order" is capped, but this leads
    it to consider that it might be negative, leading to a false positive
    warning (with GCC 15 with -Warray-bounds -fdiagnostics-details):

    ../drivers/net/ethernet/mellanox/mlx4/alloc.c:691:47: error: array subscript -1 is below array bounds of 'long unsigned int *[2]' [-Werror=array-bounds=]
      691 |                 i = find_first_bit(pgdir->bits[o], MLX4_DB_PER_PAGE >> o);
          |                                    ~~~~~~~~~~~^~~
      'mlx4_alloc_db_from_pgdir': events 1-2
      691 |                 i = find_first_bit(pgdir->bits[o], MLX4_DB_PER_PAGE >> o);                        |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                     |                         |                                                   |                     |                         (2) out of array bounds here
          |                     (1) when the condition is evaluated to true                             In file included from ../drivers/net/ethernet/mellanox/mlx4/mlx4.h:53,
                     from ../drivers/net/ethernet/mellanox/mlx4/alloc.c:42:
    ../include/linux/mlx4/device.h:664:33: note: while referencing 'bits'
      664 |         unsigned long          *bits[2];
          |                                 ^~~~

    Switch the argument to unsigned int, which removes the compiler needing
    to consider negative values.

    Signed-off-by: Kees Cook <kees@kernel.org>
    Link: https://patch.msgid.link/20250210174504.work.075-kees@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@redhat.com>