selftests: kvm: fix compilation
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2119111

commit baea2ce53f8c7448b4b8dadb563eb0df1bfdfb33
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Wed Aug 10 14:55:27 2022 -0400

    selftests: kvm: fix compilation

    Commit  49de12ba06ef ("selftests: drop KSFT_KHDR_INSTALL make target")
    dropped from tools/testing/selftests/lib.mk the code related to KSFT_KHDR_INSTALL,
    but in doing so it also dropped the definition of the ARCH variable.  The ARCH
    variable is used in several subdirectories, but kvm/ is the only one of these
    that was using KSFT_KHDR_INSTALL.

    As a result, kvm selftests cannot be built anymore:

    In file included from include/x86_64/vmx.h:12,
                     from x86_64/vmx_pmu_caps_test.c:18:
    include/x86_64/processor.h:15:10: fatal error: asm/msr-index.h: No such file or directory
       15 | #include <asm/msr-index.h>
          |          ^~~~~~~~~~~~~~~~~

    In file included from ../../../../tools/include/asm/atomic.h:6,
                     from ../../../../tools/include/linux/atomic.h:5,
                     from rseq_test.c:15:
    ../../../../tools/include/asm/../../arch/x86/include/asm/atomic.h:11:10: fatal error: asm/cmpxchg.h: No such file or directory
       11 | #include <asm/cmpxchg.h>
          |          ^~~~~~~~~~~~~~~

    Fix it by including the definition that was present in lib.mk.

    Fixes: 49de12ba06ef ("selftests: drop KSFT_KHDR_INSTALL make target")
    Cc: Guillaume Tucker <guillaume.tucker@collabora.com>
    Cc: Anders Roxell <anders.roxell@linaro.org>
    Cc: Shuah Khan <skhan@linuxfoundation.org>
    Cc: linux-kselftest@vger.kernel.org
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Conflicts:
	tools/testing/selftests/kvm/Makefile (context, skipping f2745dc0ba3d)

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>