powerpc: Fix STACKTRACE=n build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2069373

commit 48015b632f770c401f3816f144499a39f2884677
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Fri Feb 11 17:32:37 2022 +1100

    powerpc: Fix STACKTRACE=n build

    Our skiroot_defconfig doesn't enable FTRACE, and so doesn't get
    STACKTRACE enabled either. That leads to a build failure since commit
    1614b2b11fab ("arch: Make ARCH_STACKWALK independent of STACKTRACE")
    made stacktrace.c build even when STACKTRACE=n.

      arch/powerpc/kernel/stacktrace.c: In function ‘handle_backtrace_ipi’:
      arch/powerpc/kernel/stacktrace.c:171:2: error: implicit declaration of function ‘nmi_cpu_backtrace’
        171 |  nmi_cpu_backtrace(regs);
            |  ^~~~~~~~~~~~~~~~~
      arch/powerpc/kernel/stacktrace.c: In function ‘arch_trigger_cpumask_backtrace’:
      arch/powerpc/kernel/stacktrace.c:226:2: error: implicit declaration of function ‘nmi_trigger_cpumask_backtrace’
        226 |  nmi_trigger_cpumask_backtrace(mask, exclude_self, raise_backtrace_ipi);
            |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This happens because our headers haven't defined
    arch_trigger_cpumask_backtrace, which causes lib/nmi_backtrace.c not to
    build nmi_cpu_backtrace().

    The code in question doesn't actually depend on STACKTRACE=y, that was
    just added because arch_trigger_cpumask_backtrace() lived in
    stacktrace.c for convenience. So drop the dependency on
    CONFIG_STACKTRACE, that causes lib/nmi_backtrace.c to build
    nmi_cpu_backtrace() etc. and fixes the build.

    Fixes: 1614b2b11fab ("arch: Make ARCH_STACKWALK independent of STACKTRACE")
    [mpe: Cherry pick of 5a72345e6a78 from next into fixes]
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20220212111349.2806972-1-mpe@ellerman.id.au

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>