RDMA/usnic: Avoid overly large buffers on stack
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 2ac5a6d3a917755919d97c89f8aa74e4ed958557

It's never a good idea to put a 1000-byte buffer on the kernel stack. The
compiler warns about this instance when usnic_ib_log_vf() gets inlined
into usnic_ib_pci_probe():

drivers/infiniband/hw/usnic/usnic_ib_main.c:543:12: error: stack frame size of 1044 bytes in function 'usnic_ib_pci_probe' [-Werror,-Wframe-larger-than=]

As this is only called for debugging purposes in the setup path, it's
trivial to convert to a dynamic allocation.

Link: https://lore.kernel.org/r/20190906155730.2750200-1-arnd@arndb.de
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Jason Gunthorpe <jgg@mellanox.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 2ac5a6d3a917755919d97c89f8aa74e4ed958557)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>