cleanup: Adjust scoped_guard() macros to avoid potential warning
JIRA: https://redhat.atlassian.net/browse/RHEL-260239

commit fcc22ac5baf06dd17193de44b60dbceea6461983
Author: Przemek Kitszel <przemyslaw.kitszel@intel.com>
Date:   Fri Oct 18 13:38:14 2024 +0200

    cleanup: Adjust scoped_guard() macros to avoid potential warning

    Change scoped_guard() and scoped_cond_guard() macros to make reasoning
    about them easier for static analysis tools (smatch, compiler
    diagnostics), especially to enable them to tell if the given usage of
    scoped_guard() is with a conditional lock class (interruptible-locks,
    try-locks) or not (like simple mutex_lock()).

    Add compile-time error if scoped_cond_guard() is used for non-conditional
    lock class.

    Beyond easier tooling and a little shrink reported by bloat-o-meter
    this patch enables developer to write code like:

    int foo(struct my_drv *adapter)
    {
    	scoped_guard(spinlock, &adapter->some_spinlock)
    		return adapter->spinlock_protected_var;
    }

    Current scoped_guard() implementation does not support that,
    due to compiler complaining:
    error: control reaches end of non-void function [-Werror=return-type]

    Technical stuff about the change:
    scoped_guard() macro uses common idiom of using "for" statement to declare
    a scoped variable. Unfortunately, current logic is too hard for compiler
    diagnostics to be sure that there is exactly one loop step; fix that.

    To make any loop so trivial that there is no above warning, it must not
    depend on any non-const variable to tell if there are more steps. There is
    no obvious solution for that in C, but one could use the compound
    statement expression with "goto" jumping past the "loop", effectively
    leaving only the subscope part of the loop semantics.

    More impl details:
    one more level of macro indirection is now needed to avoid duplicating
    label names;
    I didn't spot any other place that is using the
    "for (...; goto label) if (0) label: break;" idiom, so it's not packed for
    reuse beyond scoped_guard() family, what makes actual macros code cleaner.

    There was also a need to introduce const true/false variable per lock
    class, it is used to aid compiler diagnostics reasoning about "exactly
    1 step" loops (note that converting that to function would undo the whole
    benefit).

    Big thanks to Andy Shevchenko for help on this patch, both internal and
    public, ranging from whitespace/formatting, through commit message
    clarifications, general improvements, ending with presenting alternative
    approaches - all despite not even liking the idea.

    Big thanks to Dmitry Torokhov for the idea of compile-time check for
    scoped_cond_guard() (to use it only with conditional locsk), and general
    improvements for the patch.

    Big thanks to David Lechner for idea to cover also scoped_cond_guard().

    Signed-off-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Link: https://lkml.kernel.org/r/20241018113823.171256-1-przemyslaw.kitszel@intel.com

(cherry picked from commit fcc22ac5baf06dd17193de44b60dbceea6461983)
Assisted-by: Patchpal
Signed-off-by: Ivan Vecera <ivecera@redhat.com>