tools/lib/subcmd/pager.c: do not alias select() params
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [tools] lib/subcmd/pager.c: do not alias select() params (Yauheni Kaliuta) [1593432]
Rebuild_FUZZ: 94.12%
commit-author Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
commit ad343a98e74e85aa91d844310e797f96fee6983b

Use a separate fd set for select()-s exception fds param to fix the
following gcc warning:

  pager.c:36:12: error: passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
    select(1, &in, NULL, &in, NULL);
              ^~~        ~~~

Link: http://lkml.kernel.org/r/20180101105626.7168-1-sergey.senozhatsky@gmail.com
	Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
	Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit ad343a98e74e85aa91d844310e797f96fee6983b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>