devcoredump: avoid -Wempty-body warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 53f95c55349e75b73f69ce36b0ae2a83b3f28fde

Cleaning out the last -Wempty-body warnings found some interesting
cases with empty macros, along with harmless warnings like this one:

drivers/base/devcoredump.c: In function 'dev_coredumpm':
drivers/base/devcoredump.c:297:56: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  297 |                 /* nothing - symlink will be missing */;
      |                                                        ^
drivers/base/devcoredump.c:301:56: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  301 |                 /* nothing - symlink will be missing */;
      |                                                        ^

Randy tried addressing this one before, and there were multiple
other ideas in that thread.

Add a runtime warning and code comment here.

Link: https://lore.kernel.org/lkml/20200418184111.13401-8-rdunlap@infradead.org/
	Cc: Randy Dunlap <rdunlap@infradead.org>
	Cc: Matthew Wilcox <willy@infradead.org>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20210322114258.3420937-1-arnd@kernel.org
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 53f95c55349e75b73f69ce36b0ae2a83b3f28fde)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>