mlx5: reduce stack usage in mlx5_setup_tc
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-502.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7802886274cc850a205e9e334c5a1b1b743ea71c

Clang warns about excessive stack usage on 32-bit targets:

drivers/net/ethernet/mellanox/mlx5/core/en_main.c:3597:12: error: stack frame size (1184) exceeds limit (1024) in 'mlx5e_setup_tc' [-Werror,-Wframe-larger-than]
static int mlx5e_setup_tc(struct net_device *dev, enum tc_setup_type type,

It turns out that both the mlx5e_setup_tc_mqprio_dcb() function and
the mlx5e_safe_switch_params() function it calls have a copy of
'struct mlx5e_params' on the stack, and this structure is fairly
large.

Use dynamic allocation for the inner one.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
	Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
(cherry picked from commit 7802886274cc850a205e9e334c5a1b1b743ea71c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>