PCI: hv: Remove unused hv_set_msi_entry_from_desc()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 22ef7ee3eeb2a41e07f611754ab9a2663232fedf

Fix the following build error:

  drivers/pci/controller/pci-hyperv.c:769:13: error: ‘hv_set_msi_entry_from_desc’ defined but not used [-Werror=unused-function]
    769 | static void hv_set_msi_entry_from_desc(union hv_msi_entry *msi_entry,

The arm64 implementation of hv_set_msi_entry_from_desc() is not used after
d06957d7a692 ("PCI: hv: Avoid the retarget interrupt hypercall in
irq_unmask() on ARM64"), so remove it.

Fixes: d06957d7a692 ("PCI: hv: Avoid the retarget interrupt hypercall in irq_unmask() on ARM64")
Link: https://lore.kernel.org/r/20220317085130.36388-1-yuehaibing@huawei.com
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
	Reviewed-by: Nathan Chancellor <nathan@kernel.org>
	Acked-by: Boqun Feng <boqun.feng@gmail.com>
(cherry picked from commit 22ef7ee3eeb2a41e07f611754ab9a2663232fedf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>