KVM: selftests: Fix compiling errors when initializing the static structure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Yanan Wang <wangyanan55@huawei.com>
commit 95bf69b400f41fbba7a2dc49b0152dd7bdc9a508

Errors like below were produced from test_util.c when compiling the KVM
selftests on my local platform.

lib/test_util.c: In function 'vm_mem_backing_src_alias':
lib/test_util.c:177:12: error: initializer element is not constant
    .flag = anon_flags,
            ^~~~~~~~~~
lib/test_util.c:177:12: note: (near initialization for 'aliases[0].flag')

The reason is that we are using non-const expressions to initialize the
static structure, which will probably trigger a compiling error/warning
on stricter GCC versions. Fix it by converting the two const variables
"anon_flags" and "anon_huge_flags" into more stable macros.

Fixes: b3784bc28ccc0 ("KVM: selftests: refactor vm_mem_backing_src_type flags")
	Reported-by: Zenghui Yu <yuzenghui@huawei.com>
	Signed-off-by: Yanan Wang <wangyanan55@huawei.com>
Message-Id: <20210610085418.35544-1-wangyanan55@huawei.com>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 95bf69b400f41fbba7a2dc49b0152dd7bdc9a508)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>