objtool: Use O_CREAT with explicit mode mask
JIRA: https://issues.redhat.com/browse/RHEL-85302

commit 73070466ed3b5e4620e03c159ee12a570b171d08
Author: Ingo Molnar <mingo@kernel.org>
Date:   Mon Mar 17 12:21:57 2025 +0100

    objtool: Use O_CREAT with explicit mode mask

    Recent Ubuntu enforces 3-argument open() with O_CREAT:

          CC      /home/mingo/tip/tools/objtool/builtin-check.o
        In file included from /usr/include/fcntl.h:341,
                         from builtin-check.c:9:
        In function ‘open’,
            inlined from ‘copy_file’ at builtin-check.c:201:11:
        /usr/include/x86_64-linux-gnu/bits/fcntl2.h:52:11: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
           52 |           __open_missing_mode ();
              |           ^~~~~~~~~~~~~~~~~~~~~~

    Use 0400 as the most restrictive mode for the new file.

    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Cc: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: linux-kernel@vger.kernel.org

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>