x86/PCI: Add #includes to asm/pci_x86.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2068174
Upstream Status: b9fae6a47b8bcb397e6a482095431f6ba9648211

commit b9fae6a47b8bcb397e6a482095431f6ba9648211
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Feb 26 13:37:03 2022 -0800

    x86/PCI: Add #includes to asm/pci_x86.h

    <asm/pci_x86.h> uses raw_spinlock_t, __init, and EINVAL; #include the
    appropriate files to prevent build errors.

      ../arch/x86/include/asm/pci_x86.h:105:8: error: unknown type name ‘raw_spinlock_t’
      ../arch/x86/include/asm/pci_x86.h:141:20: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘dmi_check_pciprobe’
      ../arch/x86/include/asm/pci_x86.h:150:10: error: ‘EINVAL’ undeclared (first use in this function)

    Link: https://lore.kernel.org/r/20220226213703.24041-1-rdunlap@infradead.org
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Cc: Mark Brown <broonie@kernel.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>