net/mlx5e: Fix compilation error in TLS code
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [netdrv] mlx5e: Fix compilation error in TLS code (Alaa Hleihel) [1724336]
Rebuild_FUZZ: 95.24%
commit-author Tariq Toukan <tariqt@mellanox.com>
commit c93dfec10f1d693a897bfd0d6e3a58a5ea7edc91

In the cited patch below, the Kconfig flags combination of:
CONFIG_MLX5_FPGA is not set
CONFIG_MLX5_TLS=y
CONFIG_MLX5_EN_TLS=y

leads to the compilation error:

./include/linux/mlx5/device.h:61:39: error: invalid application of
sizeof to incomplete type struct mlx5_ifc_tls_flow_bits.

Fix it.

Fixes: 90687e1a9a50 ("net/mlx5: Kconfig, Better organize compilation flags")
	Signed-off-by: Tariq Toukan <tariqt@mellanox.com>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
CC: Mao Wenan <maowenan@huawei.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c93dfec10f1d693a897bfd0d6e3a58a5ea7edc91)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>