usb: Change usb_of_get_companion_dev() place to usb/common
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
commit fa827966090e2a6fc07b437d0d2ffae748ec6e28

Since renesas_usb3 udc driver calls usb_of_get_companion_dev()
which is on usb/core/of.c, build error like below happens if we
disable CONFIG_USB because the usb/core/ needs CONFIG_USB:

ERROR: "usb_of_get_companion_dev" [drivers/usb/gadget/udc/renesas_usb3.ko] undefined!

According to the usb/gadget/Kconfig, "NOTE:  Gadget support
** DOES NOT ** depend on host-side CONFIG_USB !!".
So, to fix the issue, this patch changes the usb_of_get_companion_dev()
place from usb/core/of.c to usb/common/common.c to be called by both
host and gadget.

	Reported-by: John Garry <john.garry@huawei.com>
Fixes: 39facfa01c9f ("usb: gadget: udc: renesas_usb3: Add register of usb role switch")
	Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
	Acked-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit fa827966090e2a6fc07b437d0d2ffae748ec6e28)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>