ASoC: qcom: Fix trivial code style issues
JIRA: https://issues.redhat.com/browse/RHEL-27515

Conflicts: handle platform remove callback return value change

commit bb3392453d3ba44e60b85381e3bfa3c551a44e5d
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Mon Dec 4 11:00:48 2023 +0100

    ASoC: qcom: Fix trivial code style issues

    Fix few trivial code style issues, pointed out by checkpatch, so they do
    not get copied to new code (when old code is used as template):

      WARNING: Prefer "GPL" over "GPL v2" - see commit bf7fbeeae6db ("module: Cure the MODULE_LICENSE "GPL" vs. "GPL v2" bogosity")
      WARNING: function definition argument 'struct platform_device *' should also have an identifier name
      ERROR: code indent should use tabs where possible
      WARNING: please, no spaces at the start of a line
      WARNING: Missing a blank line after declarations
      WARNING: unnecessary whitespace before a quoted newline

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://msgid.link/r/20231204100048.211800-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>