qed: Fix compilation for CONFIG_QED_SRIOV undefined scenario
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-372.32.1.el8_6
commit-author Prabhakar Kushwaha <pkushwaha@marvell.com>
commit e761523d0b407518d4812ada39957bd11227e95b

This patch fixes below compliation error in case CONFIG_QED_SRIOV not
defined.
drivers/net/ethernet/qlogic/qed/qed_dev.c: In function
‘qed_fw_err_handler’:
drivers/net/ethernet/qlogic/qed/qed_dev.c:2390:3: error: implicit
declaration of function ‘qed_sriov_vfpf_malicious’; did you mean
‘qed_iov_vf_task’? [-Werror=implicit-function-declaration]
   qed_sriov_vfpf_malicious(p_hwfn, &data->err_data);
   ^~~~~~~~~~~~~~~~~~~~~~~~
   qed_iov_vf_task
drivers/net/ethernet/qlogic/qed/qed_dev.c: In function
‘qed_common_eqe_event’:
drivers/net/ethernet/qlogic/qed/qed_dev.c:2410:10: error: implicit
declaration of function ‘qed_sriov_eqe_event’; did you mean
‘qed_common_eqe_event’? [-Werror=implicit-function-declaration]
   return qed_sriov_eqe_event(p_hwfn, opcode, echo, data,
          ^~~~~~~~~~~~~~~~~~~
          qed_common_eqe_event

Fixes: fe40a830dcde ("qed: Update qed_hsi.h for fw 8.59.1.0")
	Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
	Cc: Naresh Kamboju <naresh.kamboju@linaro.org>
	Signed-off-by: Ariel Elior <aelior@marvell.com>
	Signed-off-by: Shai Malin <smalin@marvell.com>
	Signed-off-by: Omkar Kulkarni <okulkarni@marvell.com>
	Signed-off-by: Prabhakar Kushwaha <pkushwaha@marvell.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e761523d0b407518d4812ada39957bd11227e95b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>