HID: bpf: fix hid_bpf_input_report() when hid-core is not ready
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.10
Tested: with the hid-tools test suite and some hardware

commit b912cf042072e12e93faa874265b30cc0aa521b9
Author: Benjamin Tissoires <bentiss@kernel.org>
Date:   Thu Apr 11 09:05:56 2024 +0200

    HID: bpf: fix hid_bpf_input_report() when hid-core is not ready

    Reported by linux-next:
    After merging the hid tree, today's linux-next build (x86_64 allmodconfig)
    failed like this:

    x86_64-linux-gnu-ld: vmlinux.o: in function `hid_bpf_input_report':
    (.text+0x1c75181): undefined reference to `hid_input_report'

    Caused by commit 9be50ac30a83 ("HID: bpf: allow to inject HID event
    from BPF")

    I just forgot to put the indirection in place.

    Link: https://lore.kernel.org/linux-kernel/20240411105131.7830f966@canb.auug.org.au/
    Fixes: 9be50ac30a83 ("HID: bpf: allow to inject HID event from BPF")
    Link: https://lore.kernel.org/r/20240411-fix-hid-bpf-v1-1-4ae913031a8c@kernel.org
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>