rxrpc: Fix checker warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2170099
JIRA: https://issues.redhat.com/browse/RHELPLAN-148774

commit 84924aac08a43169811b4814c67994a9154a6a82
Author: David Howells <dhowells@redhat.com>
Date:   Thu Dec 1 12:24:36 2022 +0000

    Fix the following checker warning:

    ../net/rxrpc/key.c:692:9: error: subtraction of different types can't work (different address spaces)

    Checker is wrong in this case, but cast the pointers to unsigned long to
    avoid the warning.

    Whilst we're at it, reduce the assertions to WARN_ON() and return an error.

    Signed-off-by: David Howells <dhowells@redhat.com>
    cc: Marc Dionne <marc.dionne@auristor.com>
    cc: linux-afs@lists.infradead.org

Signed-off-by: Marc Dionne <mdionne@redhat.com>