tools build: Fix removal of feature-sync-compare-and-swap feature detection
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit e8c04ea0fef5731dbcaabac86d65254c227aedf4
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Nov 17 14:29:31 2021 -0300

description
===========
The patch removing the feature-sync-compare-and-swap feature detection
didn't remove the call to main_test_sync_compare_and_swap(), making the
'test-all' case fail an all the feature tests to be performed
individually:

  $ cat /tmp/build/perf/feature/test-all.make.output
  In file included from test-all.c:18:
  test-libpython-version.c:5:10: error: #error
      5 |         #error
        |          ^~~~~
  test-all.c: In function ‘main’:
  test-all.c:203:9: error: implicit declaration of function ‘main_test_sync_compare_and_swap’ [-Werror=implicit-function-declaration]
    203 |         main_test_sync_compare_and_swap(argc, argv);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  $

Fix it, now to figure out what is that test-libpython-version.c
problem...

Fixes: 60fa754b2a5a4e0c ("tools: Remove feature-sync-compare-and-swap feature detection")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>