scsi: mpi3mr: Select CONFIG_SCSI_SAS_ATTRS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Michal Kubecek <mkubecek@suse.cz>
commit 65244389b1b347447a7eed866d9d458963e851e8

Starting with commit 42fc9fee116f ("scsi: mpi3mr: Add helper functions to
manage device's port"), kernel configured with CONFIG_SCSI_MPI3MR=m and
CONFIG_SCSI_SAS_ATTRS=n fails to build because modpost cannot find symbols
used in mpi3mr_transport.c:

  ERROR: modpost: "sas_port_alloc_num" [drivers/scsi/mpi3mr/mpi3mr.ko] undefined!
  ERROR: modpost: "sas_remove_host" [drivers/scsi/mpi3mr/mpi3mr.ko] undefined!
  ERROR: modpost: "sas_phy_alloc" [drivers/scsi/mpi3mr/mpi3mr.ko] undefined!
  ERROR: modpost: "sas_phy_free" [drivers/scsi/mpi3mr/mpi3mr.ko] undefined!
  ...

Select CONFIG_SCSI_SAS_ATTRS when CONFIG_SCSI_MPI3MR is enabled to prevent
inconsistent configs.

Link: https://lore.kernel.org/r/20221017145517.93BCB6043B@lion.mk-sys.cz
Fixes: 42fc9fee116f ("scsi: mpi3mr: Add helper functions to manage device's port")
	Acked-by: Sathya Prakash Veerichetty <sathya.prakash@broadcom.com>
	Signed-off-by: Michal Kubecek <mkubecek@suse.cz>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 65244389b1b347447a7eed866d9d458963e851e8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>