bnxt_en: Fix W=1 warning in bnxt_dcb.c from fortify memcpy()
JIRA: https://issues.redhat.com/browse/RHEL-3505
JIRA: https://issues.redhat.com/browse/RHEL-11007

commit ac1b8c978a7acce25a530b02e7b3f0e74ac931c8
Author: Michael Chan <michael.chan@broadcom.com>
Date:   Mon Aug 7 07:57:19 2023 -0700

    bnxt_en: Fix W=1 warning in bnxt_dcb.c from fortify memcpy()

    Fix the following warning:

    inlined from ‘bnxt_hwrm_queue_cos2bw_qcfg’ at drivers/net/ethernet/broadcom/bnxt/bnxt_dcb.c:165:3,
    ./include/linux/fortify-string.h:592:4: error: call to ‘__read_overflow2_field’ declared with attribute warning: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror]
        __read_overflow2_field(q_size_field, size);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Modify the FW interface defintion of struct hwrm_queue_cos2bw_qcfg_output
    to use an array of sub struct for the queue1 to queue7 fields.  Note that
    the layout of the queue0 fields are different and these are not part of
    the array.  This makes the code much cleaner by removing the pointer
    arithmetic for memcpy().

    Link: https://lore.kernel.org/netdev/20230727190726.1859515-2-kuba@kernel.org/
    Reviewed-by: Andy Gospodarek <andrew.gospodarek@broadcom.com>
    Signed-off-by: Michael Chan <michael.chan@broadcom.com>
    Reviewed-by: Gustavo A. R. Silva <gustavoars@kernel.org>
    Link: https://lore.kernel.org/r/20230807145720.159645-2-michael.chan@broadcom.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ken Cox <jkc@redhat.com>