drivers/perf: arm_pmu: Fix some coding style issues
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Junhao He <hejunhao2@hisilicon.com>
commit f265fd166bce9837ce1ae6c2a4b56f8bd18d1fe4
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-358.el8/f265fd16.failed

Fix some coding style issues reported by checkpatch.pl, including
following types:

ERROR: spaces required around that '=' (ctx:VxW)
WARNING: Possible unnecessary 'out of memory' message

	Signed-off-by: Junhao He <hejunhao2@hisilicon.com>
	Signed-off-by: Jay Fang <f.fangjian@huawei.com>
Link: https://lore.kernel.org/r/1620736054-58412-3-git-send-email-f.fangjian@huawei.com
	Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit f265fd166bce9837ce1ae6c2a4b56f8bd18d1fe4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/perf/arm_pmu.c