ALSA: rme9652: Fix potential Spectre v1 vulnerability
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Gustavo A. R. Silva <gustavo@embeddedor.com>
commit 0b84304ef5da92add8dc75a1b07879c5374cdb05

info->channel is indirectly controlled by user-space, hence leading to
a potential exploitation of the Spectre variant 1 vulnerability.

This issue was detected with the help of Smatch:

sound/pci/rme9652/hdsp.c:4100 snd_hdsp_channel_info() warn: potential spectre issue 'hdsp->channel_map' [r] (local cap)

Fix this by sanitizing info->channel before using it to index hdsp->channel_map

Notice that given that speculation windows are large, the policy is
to kill the speculation on the first load and not worry if it can be
completed with a dependent load/store [1].

Also, notice that I refactored the code a bit in order to get rid of the
following checkpatch warning:

ERROR: do not use assignment in if condition
FILE: sound/pci/rme9652/hdsp.c:4103:
	if ((mapped_channel = hdsp->channel_map[info->channel]) < 0)

[1] https://marc.info/?l=linux-kernel&m=152449131114778&w=2

	Cc: stable@vger.kernel.org
	Signed-off-by: Gustavo A. R. Silva <gustavo@embeddedor.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 0b84304ef5da92add8dc75a1b07879c5374cdb05)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>