usb: misc: onboard_usb_dev: fix build warning for CONFIG_USB_ONBOARD_DEV_USB5744=n
JIRA: https://issues.redhat.com/browse/RHEL-116016

commit 662a9ece32add94469138ae66999ee16cb37a531
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 23 May 2025 14:09:43 +0200

  When the USB5744 option is disabled, the onboard_usb driver warns about
  unused functions:

  drivers/usb/misc/onboard_usb_dev.c:358:12: error: 'onboard_dev_5744_i2c_write_byte' defined but not used [-Werror=unused-function]
    358 | static int onboard_dev_5744_i2c_write_byte(struct i2c_client *client, u16 addr, u8 data)
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  drivers/usb/misc/onboard_usb_dev.c:313:12: error: 'onboard_dev_5744_i2c_read_byte' defined but not used [-Werror=unused-function]
    313 | static int onboard_dev_5744_i2c_read_byte(struct i2c_client *client, u16 addr, u8 *data)
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Extend the #ifdef block a little further to cover all of these functions.
  Ideally we'd use use if(IS_ENABLED()) instead, but that doesn't currently
  work because the i2c_transfer() and i2c_smbus_write_word_data() function
  declarations are hidden  when CONFIG_I2C is disabled.

  Fixes: 1143d41922c0 ("usb: misc: onboard_usb_dev: Fix usb5744 initialization sequence")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Link: https://lore.kernel.org/r/20250523120947.2170302-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>