IB/mlx5: Use div64_u64 for num_var_hw_entries calculation
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Jason Gunthorpe <jgg@ziepe.ca>
commit 685eff513183d6d64a5f413531e683d23b8b198b

On i386:

ERROR: "__udivdi3" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!
ERROR: "__divdi3" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!

Fixes: f164be8c0366 ("IB/mlx5: Extend caps stage to handle VAR capabilities")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Reported-by: Alexander Lobakin <alobakin@dlink.ru>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 685eff513183d6d64a5f413531e683d23b8b198b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>