bpf, devmap: Remove unnecessary if check in for loop
JIRA: https://issues.redhat.com/browse/RHEL-30773

commit 2317dc2c22cc353b699c7d1db47b2fe91f54055c
Author: Thorsten Blum <thorsten.blum@toblux.com>
Date:   Wed May 29 12:19:01 2024 +0200

    bpf, devmap: Remove unnecessary if check in for loop
    
    The iterator variable dst cannot be NULL and the if check can be removed.
    Remove it and fix the following Coccinelle/coccicheck warning reported
    by itnull.cocci:
    
    	ERROR: iterator variable bound on line 762 cannot be NULL
    
    Signed-off-by: Thorsten Blum <thorsten.blum@toblux.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Toke Høiland-Jørgensen <toke@redhat.com>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20240529101900.103913-2-thorsten.blum@toblux.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>