powerpc/livepatch: Fix build error with kprobes disabled.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [powerpc] livepatch: Fix build error with kprobes disabled (Joe Lawrence) [1658435]
Rebuild_FUZZ: 91.43%
commit-author Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
commit 5e3f0d15ae5f95bdde8d092a0884d2defe27d448

arch/powerpc/kernel/stacktrace.c: In function ‘save_stack_trace_tsk_reliable’:
arch/powerpc/kernel/stacktrace.c:176:28: error: ‘kretprobe_trampoline’ undeclared
   if (ip == (unsigned long)kretprobe_trampoline)
                            ^~~~~~~~~~~~~~~~~~~~

Fixes: df78d3f61480 ("powerpc/livepatch: Implement reliable stack tracing for the consistency model")
	Signed-off-by: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 5e3f0d15ae5f95bdde8d092a0884d2defe27d448)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>