libbpf: Fix warning in calloc() usage
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit 0ee30d937c147fc14c4b49535181d437cd2fde7a
Author: Matteo Croce <teknoraver@meta.com>
Date:   Thu Jul 17 22:03:37 2025 +0200

    libbpf: Fix warning in calloc() usage
    
    When compiling libbpf with some compilers, this warning is triggered:
    
    libbpf.c: In function ‘bpf_object__gen_loader’:
    libbpf.c:9209:28: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
     9209 |         gen = calloc(sizeof(*gen), 1);
          |                            ^
    libbpf.c:9209:28: note: earlier argument should specify number of elements, later size of each element
    
    Fix this by inverting the calloc() arguments.
    
    Signed-off-by: Matteo Croce <teknoraver@meta.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/bpf/20250717200337.49168-1-technoboy85@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>