hyperv/vmbus: include linux/bitops.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 8017c99680fa65e1e8d999df1583de476a187830

On arm64 randconfig builds, hyperv sometimes fails with this
error:

In file included from drivers/hv/hv_trace.c:3:
In file included from drivers/hv/hyperv_vmbus.h:16:
In file included from arch/arm64/include/asm/sync_bitops.h:5:
arch/arm64/include/asm/bitops.h:11:2: error: only <linux/bitops.h> can be included directly
In file included from include/asm-generic/bitops/hweight.h:5:
include/asm-generic/bitops/arch_hweight.h:9:9: error: implicit declaration of function '__sw_hweight32' [-Werror,-Wimplicit-function-declaration]
include/asm-generic/bitops/atomic.h:17:7: error: implicit declaration of function 'BIT_WORD' [-Werror,-Wimplicit-function-declaration]

Include the correct header first.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20211018131929.2260087-1-arnd@kernel.org
	Signed-off-by: Wei Liu <wei.liu@kernel.org>
(cherry picked from commit 8017c99680fa65e1e8d999df1583de476a187830)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>