platform/x86/amd/pmf: Add depends on CONFIG_POWER_SUPPLY
JIRA: https://issues.redhat.com/browse/RHEL-2037

commit 3004e8d2a0a98bbf4223ae146464fadbff68bf78
Author: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
Date:   Mon Feb 13 17:44:57 2023 +0530

    platform/x86/amd/pmf: Add depends on CONFIG_POWER_SUPPLY

    It is reported that amd_pmf driver is missing "depends on" for
    CONFIG_POWER_SUPPLY causing the following build error.

    ld: drivers/platform/x86/amd/pmf/core.o: in function `amd_pmf_remove':
    core.c:(.text+0x10): undefined reference to `power_supply_unreg_notifier'
    ld: drivers/platform/x86/amd/pmf/core.o: in function `amd_pmf_probe':
    core.c:(.text+0x38f): undefined reference to `power_supply_reg_notifier'
    make[1]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
    make: *** [Makefile:1248: vmlinux] Error 2

    Add this to the Kconfig file.

    Link: https://bugzilla.kernel.org/show_bug.cgi?id=217028
    Fixes: c5258d39fc4c ("platform/x86/amd/pmf: Add helper routine to update SPS thermals")
    Signed-off-by: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
    Link: https://lore.kernel.org/r/20230213121457.1764463-1-Shyam-sundar.S-k@amd.com
    Cc: stable@vger.kernel.org
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>