powerpc/pseries/eeh: Make pseries_send_allow_unfreeze() static
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Cédric Le Goater <clg@kaod.org>
commit 22f1de2e13b066921dedf6a00d2cc414f3cbab05

Only used locally. It fixes this W=1 compile error :

../arch/powerpc/platforms/pseries/eeh_pseries.c:697:5: error: no previous prototype for ‘pseries_send_allow_unfreeze’ [-Werror=missing-prototypes]
  697 | int pseries_send_allow_unfreeze(struct pci_dn *pdn,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

	Signed-off-by: Cédric Le Goater <clg@kaod.org>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20210104143206.695198-24-clg@kaod.org
(cherry picked from commit 22f1de2e13b066921dedf6a00d2cc414f3cbab05)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>