ASoC: soc-component: fix undefined reference to __ffssi2
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
commit 8ac9e476b86851c94e0f33bea758e0a00e3f875e

microblaze-linux-gcc (GCC) 9.3.0 complains about missing __ffssi2
symbol while using __builtin_ffs at runtime.

This is because arch/h8300 is compiled with -fno-builtin option.

so fallback and use kernel ffs() instead to all the arch builds happy!

Fixes: 1da0b9899abd ("ASoC: soc-component: add snd_soc_component_read/write_field()")
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Link: https://lore.kernel.org/r/20210129100539.23459-1-srinivas.kandagatla@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 8ac9e476b86851c94e0f33bea758e0a00e3f875e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>