iommufd: Fix building without dmabuf
JIRA: https://issues.redhat.com/browse/RHEL-111742

commit 69dc538a4f5a57dcc5ea4893c769d567f539a1b1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 4 11:03:29 2025 +0100

    iommufd: Fix building without dmabuf

    When DMABUF is disabled, trying to use it causes a link failure:

    x86_64-linux-ld: drivers/iommu/iommufd/io_pagetable.o: in function `iopt_map_file_pages':
    io_pagetable.c:(.text+0x1735): undefined reference to `dma_buf_get'
    x86_64-linux-ld: io_pagetable.c:(.text+0x1775): undefined reference to `dma_buf_put'

    Fixes: 44ebaa1744fd ("iommufd: Accept a DMABUF through IOMMU_IOAS_MAP_FILE")
    Link: https://patch.msgid.link/r/20251204100333.1034767-1-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Cédric Le Goater <clg@redhat.com>