Input: i8042 - unbreak Pegatron C15B
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Alexey Dobriyan <adobriyan@gmail.com>
commit a3a9060ecad030e2c7903b2b258383d2c716b56c

g++ reports

	drivers/input/serio/i8042-x86ia64io.h:225:3: error: ‘.matches’ designator used multiple times in the same initializer list

C99 semantics is that last duplicated initialiser wins,
so DMI entry gets overwritten.

Fixes: a48491c65b51 ("Input: i8042 - add ByteSpeed touchpad to noloop table")
	Signed-off-by: Alexey Dobriyan <adobriyan@gmail.com>
	Acked-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
Link: https://lore.kernel.org/r/20201228072335.GA27766@localhost.localdomain
	Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
(cherry picked from commit a3a9060ecad030e2c7903b2b258383d2c716b56c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>