perf tools: Add '\n' at the end of parse-options error messages
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
commit 66f5a0779af2a4f28b1832f6c20bc9d3b1ab1886

Few error messages does not have '\n' at the end and thus next prompt
gets printed in the same line. Ex,

  linux~$ perf buildid-cache -verbose --add ./a.out
   Error: did you mean `--verbose` (with two dashes ?)linux~$

Fix it.

	Signed-off-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
	Reviewed-by: Masami Hiramatsu <mhiramat@kernel.org>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Kate Stewart <kstewart@linuxfoundation.org>
	Cc: Krister Johansen <kjlx@templeofstupid.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Philippe Ombredanne <pombredanne@nexb.com>
	Cc: Sihyeon Jang <uneedsihyeon@gmail.com>
	Cc: Thomas Gleixner <tglx@linutronix.de>
Link: http://lkml.kernel.org/r/20180417041346.5617-2-ravi.bangoria@linux.vnet.ibm.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 66f5a0779af2a4f28b1832f6c20bc9d3b1ab1886)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>