bnx2x: remove unused variable 'cur_data_offset'
JIRA: https://issues.redhat.com/browse/RHEL-23117
JIRA: https://issues.redhat.com/browse/RHEL-25588

commit 919d527956daa3e7ad03a23ba661beb8a46cacf4
Author: Bill Wendling <morbo@google.com>
Date:   Wed Jul 14 02:17:46 2021 -0700

    bnx2x: remove unused variable 'cur_data_offset'

    Fix the clang build warning:

      drivers/net/ethernet/broadcom/bnx2x/bnx2x_sriov.c:1862:13: error: variable 'cur_data_offset' set but not used [-Werror,-Wunused-but-set-variable]
            dma_addr_t cur_data_offset;

    Signed-off-by: Bill Wendling <morbo@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>