thunderbolt: Fix -Wrestrict warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 0a0624a26f9ceb8aae16882d87dc3b12f17f4a49

gcc-11 warns when building with W=1:

drivers/thunderbolt/xdomain.c: In function 'modalias_show':
drivers/thunderbolt/xdomain.c:733:16: error: 'sprintf' argument 3 overlaps destination object 'buf' [-Werror=restrict]
  733 |         return sprintf(buf, "%s\n", buf);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/thunderbolt/xdomain.c:727:36: note: destination object referenced by 'restrict'-qualified argument 1 was declared here
  727 |                              char *buf)
      |                              ~~~~~~^~~

There is no need for the sprintf() here when a strcat() does
the same thing.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
(cherry picked from commit 0a0624a26f9ceb8aae16882d87dc3b12f17f4a49)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>