scsi: ipr: Remove several unused variables
JIRA: https://issues.redhat.com/browse/RHEL-56837

commit 392e4daa8a7e3d9b103c64acef08f62f19d421aa
Author: Tom Rix <trix@redhat.com>
Date:   Thu Apr 20 08:50:35 2023 -0400

    scsi: ipr: Remove several unused variables

    gcc with W=1 reports
    drivers/scsi/ipr.c: In function ‘ipr_init_res_entry’:
    drivers/scsi/ipr.c:1104:22: error: variable ‘proto’
      set but not used [-Werror=unused-but-set-variable]
     1104 |         unsigned int proto;
          |                      ^~~~~
    drivers/scsi/ipr.c: In function ‘ipr_update_res_entry’:
    drivers/scsi/ipr.c:1261:22: error: variable ‘proto’
      set but not used [-Werror=unused-but-set-variable]
     1261 |         unsigned int proto;
          |                      ^~~~~
    drivers/scsi/ipr.c: In function ‘ipr_change_queue_depth’:
    drivers/scsi/ipr.c:4417:36: error: variable ‘res’
      set but not used [-Werror=unused-but-set-variable]
     4417 |         struct ipr_resource_entry *res;
          |                                    ^~~

    These variables are not used, so remove them. The lock around res is not
    needed so remove that. This makes ioa_cfg and lock_flags unneeded so remove
    them as well.

    Fixes: 65a15d6560df ("scsi: ipr: Remove SATA support")
    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230420125035.3888188-1-trix@redhat.com
    Acked-by: Brian King <brking@linux.vnet.ibm.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Ming Lei <ming.lei@redhat.com>