rtla/Makefile: Properly handle dependencies
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2174943

commit fe4d0d5dde457bb5832b866418b5036f4f0c8d13
Author: Daniel Bristot de Oliveira <bristot@kernel.org>
Date:   Fri Apr 29 16:54:58 2022 +0200

	rtla/Makefile: Properly handle dependencies

	Linus had a problem compiling RTLA, saying:

	"[...] I wish the tracing tools would do a bit more package
	checking and helpful error messages too, rather than just
	fail with:

	    fatal error: tracefs.h: No such file or directory"

	Which is indeed not a helpful message. Update the Makefile, adding
	proper checks for the dependencies, with useful information about
	how to resolve possible problems.

	For example, the previous error is now reported as:

	    $ make
	    ********************************************
	    ** NOTICE: libtracefs version 1.3 or higher not found
	    **
	    ** Consider installing the latest libtracefs from your
	    ** distribution, e.g., 'dnf install libtracefs' on Fedora,
	    ** or from source:
	    **
	    **  https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/
	    **
	    ********************************************

	These messages are inspired by the ones used on trace-cmd, as suggested
	by Stevel Rostedt.

	Link: https://lore.kernel.org/r/CAHk-=whxmA86E=csNv76DuxX_wYsg8mW15oUs3XTabu2Yc80yw@mail.gmail.com/

	Changes from V1:
	 - Moved the rst2man check to the install phase (when it is used).
	 - Removed the procps-ng lib check [1] as it is being removed.

	[1] a0f9f8c1030c66305c9b921057c3d483064d5529.1651220820.git.bristot@kernel.org

	Link: https://lkml.kernel.org/r/3f1fac776c37e4b67c876a94e5a0e45ed022ff3d.1651238057.git.bristot@kernel.org

	Cc: Ingo Molnar <mingo@kernel.org>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Reported-by: Linus Torvalds <torvalds@linux-foundation.org>
	Suggested-by: Steven Rostedt <rostedt@goodmis.org>
	Signed-off-by: Daniel Bristot de Oliveira <bristot@kernel.org>
	Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: John Kacur <jkacur@redhat.com>