arm64: sysreg: Generate C compiler warnings on {read,write}_sysreg_s arguments
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit 18b8f57a7f51b4c834e5e974ec38133c02e9eb58
Author: James Clark <james.clark@arm.com>
Date: Tue, 15 Aug 2023 15:06:39 +0100

    Evaluate the register before the asm section so that the C compiler
    generates warnings when there is an issue with the register argument.

    This will prevent possible future issues such as the one seen here [1]
    where a missing bracket caused the shift and addition operators to be
    evaluated in the wrong order, but no warning was emitted. The GNU
    assembler has no warning for when expressions evaluate differently to C
    due to different operator precedence, but the C compiler has some
    warnings that may suggest something is wrong. For example in this case
    the following warning would have been emitted:

      error: operator '>>' has lower precedence than '+'; '+' will be evaluated first [-Werror,-Wshift-op-parentheses]

    There are currently no existing warnings that need to be fixed.

    [1]: https://lore.kernel.org/linux-perf-users/20230728162011.GA22050@willie-the-truck/

    Signed-off-by: James Clark <james.clark@arm.com>
    Link: https://lore.kernel.org/r/20230815140639.614769-1-james.clark@arm.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>