selftests/bpf: Fix bogus uninitialized variable warning
Bugzilla: https://bugzilla.redhat.com/2137876

commit 645d5d3bc001a7d77459cb8360c36a60954d6008
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Tue Jul 5 15:48:16 2022 -0700

    selftests/bpf: Fix bogus uninitialized variable warning
    
    When compiling selftests/bpf in optimized mode (-O2), GCC erroneously
    complains about uninitialized token variable:
    
      In file included from network_helpers.c:22:
      network_helpers.c: In function ‘open_netns’:
      test_progs.h:355:22: error: ‘token’ may be used uninitialized [-Werror=maybe-uninitialized]
        355 |         int ___err = libbpf_get_error(___res);                          \
            |                      ^~~~~~~~~~~~~~~~~~~~~~~~
      network_helpers.c:440:14: note: in expansion of macro ‘ASSERT_OK_PTR’
        440 |         if (!ASSERT_OK_PTR(token, "malloc token"))
            |              ^~~~~~~~~~~~~
      In file included from /data/users/andriin/linux/tools/testing/selftests/bpf/tools/include/bpf/libbpf.h:21,
                       from bpf_util.h:9,
                       from network_helpers.c:20:
      /data/users/andriin/linux/tools/testing/selftests/bpf/tools/include/bpf/libbpf_legacy.h:113:17: note: by argument 1 of type ‘const void *’ to ‘libbpf_get_error’ declared here
        113 | LIBBPF_API long libbpf_get_error(const void *ptr);
            |                 ^~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors
      make: *** [Makefile:522: /data/users/andriin/linux/tools/testing/selftests/bpf/network_helpers.o] Error 1
    
    This is completely bogus becuase libbpf_get_error() doesn't dereference
    pointer, but the only easy way to silence this is to allocate initialized
    memory with calloc().
    
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Yonghong Song <yhs@fb.com>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20220705224818.4026623-2-andrii@kernel.org

Signed-off-by: Artem Savkov <asavkov@redhat.com>