ALSA: hda/realtek: Fix code style error
JIRA: https://issues.redhat.com/browse/RHEL-183295

commit 7b5b7d04498d84bc7abc05b4e09a0d17c820d3b0
Author: songxiebing <songxiebing@kylinos.cn>
Date: Sun Apr 5 09:42:08 2026 +0800

    ALSA: hda/realtek: Fix code style error

    Output of checkpatch shows error:
    ERROR: else should follow close brace '}'
    2168: FILE: sound/hda/codecs/realtek/realtek.c:2168:
    +	}
    +	else

    So fix it.

    Signed-off-by: songxiebing <songxiebing@kylinos.cn>
    Link: https://patch.msgid.link/20260405014208.167364-1-songxiebing@kylinos.cn
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>