serial: cpm_uart: Fix build error without CONFIG_SERIAL_CPM_CONSOLE
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 0258502f11a4f6036b5f8b34b09027c8a92def3a
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed May 18 21:54:52 2022 +0800

    serial: cpm_uart: Fix build error without CONFIG_SERIAL_CPM_CONSOLE

    drivers/tty/serial/cpm_uart/cpm_uart_core.c: In function ‘cpm_uart_init_port’:
    drivers/tty/serial/cpm_uart/cpm_uart_core.c:1251:7: error: ‘udbg_port’ undeclared (first use in this function); did you mean ‘uart_port’?
      if (!udbg_port)
           ^~~~~~~~~
           uart_port

    commit d142585bceb3 leave this corner, wrap it with #ifdef block

    Fixes: d142585bceb3 ("serial: cpm_uart: Protect udbg definitions by CONFIG_SERIAL_CPM_CONSOLE")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Link: https://lore.kernel.org/r/20220518135452.39480-1-yuehaibing@huawei.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>