perf/ui/gtk: Fix gtk2 build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Jiri Olsa <jolsa@kernel.org>
commit 93e843f95f095aeb533ab67ac4718f848d38dfa0

Ravi Bangoria reported an issue when doing the gtk2 feature detection on
Fedora 31, where some types got deprecated:

  /usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: error: ‘GTypeDebugFlags’ is deprecated [-Werror=deprecated-declarations]
    236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);

Fix this for perf by allowing the compile to pass with deprecated
symbols via the -Wno-deprecated-declarations compiler directive.

	Reported-by: Ravi Bangoria <ravi.bangoria@linux.ibm.com>
	Signed-off-by: Jiri Olsa <jolsa@kernel.org>
	Tested-by: Ravi Bangoria <ravi.bangoria@linux.ibm.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jelle van der Waa <jelle@vdwaa.nl>
	Cc: Michael Petlan <mpetlan@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lore.kernel.org/lkml/20200113104358.123511-2-jolsa@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 93e843f95f095aeb533ab67ac4718f848d38dfa0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>