net/mlx5e: Reduce the size of icosq_str
JIRA: https://issues.redhat.com/browse/RHEL-882
Upstream-status: v6.7-rc2

commit dce94142842e119b982c27c1b62bd20890c7fd21
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Tue Nov 14 13:58:44 2023 -0800

    net/mlx5e: Reduce the size of icosq_str

    icosq_str size is unnecessarily too long, and it causes a build warning
    -Wformat-truncation with W=1. Looking closely, It doesn't need to be 255B,
    hence this patch reduces the size to 32B which should be more than enough
    to host the string: "ICOSQ: 0x%x, ".

    While here, add a missing space in the formatted string.

    This fixes the following build warning:

    $ KCFLAGS='-Wall -Werror'
    $ make O=/tmp/kbuild/linux W=1 -s -j12 drivers/net/ethernet/mellanox/mlx5/core/

    drivers/net/ethernet/mellanox/mlx5/core/en/reporter_rx.c: In function 'mlx5e_reporter_rx_timeout':
    drivers/net/ethernet/mellanox/mlx5/core/en/reporter_rx.c:718:56:
    error: ', CQ: 0x' directive output may be truncated writing 8 bytes into a region of size between 0 and 255 [-Werror=format-truncation=]
      718 |                  "RX timeout on channel: %d, %sRQ: 0x%x, CQ: 0x%x",
          |                                                        ^~~~~~~~
    drivers/net/ethernet/mellanox/mlx5/core/en/reporter_rx.c:717:9: note: 'snprintf' output between 43 and 322 bytes into a destination of size 288
      717 |         snprintf(err_str, sizeof(err_str),
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      718 |                  "RX timeout on channel: %d, %sRQ: 0x%x, CQ: 0x%x",
          |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      719 |                  rq->ix, icosq_str, rq->rqn, rq->cq.mcq.cqn);
          |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: 521f31af004a ("net/mlx5e: Allow RQ outside of channel context")
    Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6d4ab2e97dcfbcd748ae71761a9d8e5e41cc732c
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Link: https://lore.kernel.org/r/20231114215846.5902-14-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>