KVM: arm64: selftests: Track width of timer counter as "int", not "uint64_t"
JIRA: https://issues.redhat.com/browse/RHEL-131242

commit cb49b7b8622e914171e9eb7197c006320889e0fc
Author: Sean Christopherson <seanjc@google.com>
Date:   Fri Sep 26 08:58:38 2025 -0700

    KVM: arm64: selftests: Track width of timer counter as "int", not "uint64_t"

    Store the width of arm64's timer counter as an "int", not a "uint64_t".
    ilog2() returns an "int", and more importantly using what is an "unsigned
    long" under the hood makes clang unhappy due to a type mismatch when
    clamping the width to a sane value.

      arm64/arch_timer_edge_cases.c:1032:10: error: comparison of distinct pointer types
         ('typeof (width) *' (aka 'unsigned long *') and 'typeof (56) *' (aka 'int *'))
         [-Werror,-Wcompare-distinct-pointer-types]
       1032 |         width = clamp(width, 56, 64);
            |                 ^~~~~~~~~~~~~~~~~~~~
      tools/include/linux/kernel.h:47:45: note: expanded from macro 'clamp'
         47 | #define clamp(val, lo, hi)      min((typeof(val))max(val, lo), hi)
            |                                                  ^~~~~~~~~~~~
      tools/include/linux/kernel.h:33:17: note: expanded from macro 'max'
         33 |         (void) (&_max1 == &_max2);              \
            |                 ~~~~~~ ^  ~~~~~~
      tools/include/linux/kernel.h:39:9: note: expanded from macro 'min'
         39 |         typeof(x) _min1 = (x);                  \
            |                ^

    Fixes: fad4cf944839 ("KVM: arm64: selftests: Determine effective counter width in arch_timer_edge_cases")
    Cc: Sebastian Ott <sebott@redhat.com>
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Reviewed-by: Oliver Upton <oliver.upton@linux.dev>
    Signed-off-by: Marc Zyngier <maz@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>