wifi: lib80211: remove unused variables iv32 and iv16
JIRA: https://issues.redhat.com/browse/RHEL-19746

commit e04b1973e2ab1e58a79156317b0dc25f848efdc5
Author: Tom Rix <trix@redhat.com>
Date:   Wed May 17 08:33:10 2023 -0400

    wifi: lib80211: remove unused variables iv32 and iv16
    
    clang with W=1 reports
    net/wireless/lib80211_crypt_tkip.c:667:7: error: variable 'iv32'
      set but not used [-Werror,-Wunused-but-set-variable]
                    u32 iv32 = tkey->tx_iv32;
                        ^
    This variable not used so remove it.
    Then remove a similar iv16 variable.
    Change the comment because the unmodified value is returned.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Link: https://lore.kernel.org/r/20230517123310.873023-1-trix@redhat.com
    [change commit log wrt. 'length', add comment in the code]
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>