arm64: mm: Drop 'const' from conditional arm64_dma_phys_limit definition
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2091852
Upstream Status: https://github.com/torvalds/linux.git
Tested: on ampere-mtsnow-altra-11.khw4.lab.eng.bos.redhat.com
Build-info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46106617
Conflicts: none

commit 770093459b9b333380aa71f2c31c60b14895c1df
Author: Will Deacon <will@kernel.org>
Date:   Wed Mar 9 12:21:37 2022 +0000

    arm64: mm: Drop 'const' from conditional arm64_dma_phys_limit definition

    Commit 031495635b46 ("arm64: Do not defer reserve_crashkernel() for
    platforms with no DMA memory zones") introduced different definitions
    for 'arm64_dma_phys_limit' depending on CONFIG_ZONE_DMA{,32} based on
    a late suggestion from Pasha. Sadly, this results in a build error when
    passing W=1:

      | arch/arm64/mm/init.c:90:19: error: conflicting type qualifiers for 'arm64_dma_phys_limit'

    Drop the 'const' for now and use '__ro_after_init' consistently.

    Link: https://lore.kernel.org/r/202203090241.aj7paWeX-lkp@intel.com
    Link: https://lore.kernel.org/r/CA+CK2bDbbx=8R=UthkMesWOST8eJMtOGJdfMRTFSwVmo0Vn0EA@mail.gmail.com
    Fixes: 031495635b46 ("arm64: Do not defer reserve_crashkernel() for platforms with no DMA memory zones")
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Pingfan Liu <piliu@redhat.com>