crypto: qat - add missing function declaration in adf_dbgfs.h
JIRA: https://issues.redhat.com/browse/RHEL-15640
Upstream Status: merged into the linux.git

commit 134e0dc6b73ab7e99464182356a8b3fa4ea3b499
Author: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
Date:   Sat Jun 3 09:28:53 2023 +0100

    crypto: qat - add missing function declaration in adf_dbgfs.h

    The function adf_dbgfs_exit() was improperly named causing the build to
    fail when CONFIG_DEBUG_FS=n.

    Rename adf_dbgfs_cleanup() as adf_dbgfs_exit().

    This fixes the following build error:
          CC [M]  drivers/crypto/intel/qat/qat_c62x/adf_drv.o
        drivers/crypto/intel/qat/qat_c62x/adf_drv.c: In function ‘adf_cleanup_accel’:
        drivers/crypto/intel/qat/qat_c62x/adf_drv.c:69:9: error: implicit declaration of function ‘adf_dbgfs_exit’; did you mean ‘adf_dbgfs_init’? [-Werror=implicit-function-declaration]
           69 |         adf_dbgfs_exit(accel_dev);
              |         ^~~~~~~~~~~~~~
              |         adf_dbgfs_init
        cc1: all warnings being treated as errors
        make[2]: *** [scripts/Makefile.build:252: drivers/crypto/intel/qat/qat_c62x/adf_drv.o] Error 1
        make[1]: *** [scripts/Makefile.build:494: drivers/crypto/intel/qat/qat_c62x] Error 2
        make: *** [Makefile:2026: drivers/crypto/intel/qat] Error 2

    Fixes: 9260db6640a6 ("crypto: qat - move dbgfs init to separate file")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202306030654.5t4qkyN1-lkp@intel.com/
    Signed-off-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>