selftests/bpf: Fix undefined UINT_MAX in veristat.c
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit a8d1c48d0720140b53063ff23507845bb2078e92
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Wed Jan 15 23:50:36 2025 -0800

    selftests/bpf: Fix undefined UINT_MAX in veristat.c

    Include <limits.h> in 'veristat.c' to provide a UINT_MAX definition and
    avoid multiple compile errors against mips64el/musl-libc:

    veristat.c: In function 'max_verifier_log_size':
    veristat.c:1135:36: error: 'UINT_MAX' undeclared (first use in this function)
     1135 |         const int SMALL_LOG_SIZE = UINT_MAX >> 8;
          |                                    ^~~~~~~~
    veristat.c:24:1: note: 'UINT_MAX' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?
       23 | #include <math.h>
      +++ |+#include <limits.h>
       24 |

    Fixes: 1f7c33630724 ("selftests/bpf: Increase verifier log limit in veristat")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20250116075036.3459898-1-tony.ambardar@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>