wifi: rtw89: Fix clang -Wimplicit-fallthrough in rtw89_query_sar()
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 78d84f35d2c3bf4434e9d785e4b4c33fa8e57878
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Aug 22 08:27:16 2023 -0700

    wifi: rtw89: Fix clang -Wimplicit-fallthrough in rtw89_query_sar()
    
    clang warns (or errors with CONFIG_WERROR=y):
    
      drivers/net/wireless/realtek/rtw89/sar.c:216:3: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        216 |                 case RTW89_TAS_STATE_DPR_FORBID:
            |                 ^
      drivers/net/wireless/realtek/rtw89/sar.c:216:3: note: insert 'break;' to avoid fall-through
        216 |                 case RTW89_TAS_STATE_DPR_FORBID:
            |                 ^
            |                 break;
      1 error generated.
    
    Clang is a little more pedantic than GCC, which does not warn when
    falling through to a case that is just break or return. Clang's version
    is more in line with the kernel's own stance in deprecated.rst, which
    states that all switch/case blocks must end in either break,
    fallthrough, continue, goto, or return. Add the missing break to silence
    the warning.
    
    Closes: https://github.com/ClangBuiltLinux/linux/issues/1921
    Fixes: eb2624f55ad1 ("wifi: rtw89: Introduce Time Averaged SAR (TAS) feature")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Acked-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230822-rtw89-tas-clang-implicit-fallthrough-v1-1-5cb73f0fa976@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>