mm: move fold_vm_numa_events() to fix NUMA without SMP
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2064990

This patch is a backport of the following upstream commit:
commit ebeac3ea995b59e823510937ab92825004e3fbaa
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Fri Nov 5 13:40:28 2021 -0700

    mm: move fold_vm_numa_events() to fix NUMA without SMP

    If CONFIG_NUMA=y, but CONFIG_SMP=n (e.g. sh/migor_defconfig):

        sh4-linux-gnu-ld: mm/vmstat.o: in function `vmstat_start': vmstat.c:(.text+0x97c): undefined reference to `fold_vm_numa_events'
        sh4-linux-gnu-ld: drivers/base/node.o: in function `node_read_vmstat': node.c:(.text+0x140): undefined reference to `fold_vm_numa_events'
        sh4-linux-gnu-ld: drivers/base/node.o: in function `node_read_numastat': node.c:(.text+0x1d0): undefined reference to `fold_vm_numa_events'

    Fix this by moving fold_vm_numa_events() outside the SMP-only section.

    Link: https://lkml.kernel.org/r/9d16ccdd9ef32803d7100c84f737de6a749314fb.1631781495.git.geert+renesas@glider.be
    Fixes: f19298b9516c1a03 ("mm/vmstat: convert NUMA statistics to basic NUMA counters")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Acked-by: Mel Gorman <mgorman@suse.de>
    Cc: Gon Solo <gonsolo@gmail.com>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Juri Lelli <juri.lelli@redhat.com>
    Cc: Matt Fleming <matt@codeblueprint.co.uk>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rich Felker <dalias@libc.org>
    Cc: Vincent Guittot <vincent.guittot@linaro.org>
    Cc: Vlastimil Babka <vbabka@suse.cz>
    Cc: Yoshinori Sato <ysato@users.osdn.me>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>