net: bql: fix building with BQL disabled
JIRA: https://issues.redhat.com/browse/RHEL-36218

commit eb2c11b27c58a62b5027b77f702c15cd0ca38f7d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Feb 28 17:06:56 2024 +0100

    net: bql: fix building with BQL disabled

    It is now possible to disable BQL, but that causes the cpsw driver to break:

    drivers/net/ethernet/ti/am65-cpsw-nuss.c:297:28: error: no member named 'dql' in 'struct netdev_queue'
      297 |                    dql_avail(&netif_txq->dql),

    There is already a helper function in net/sch_generic.h that could
    be used to help here. Move its implementation into the common
    linux/netdevice.h along with the other bql interfaces and change
    both users over to the new interface.

    Fixes: ea7f3cfaa588 ("net: bql: allow the config to be disabled")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>