mlxsw: spectrum_buffers: Add extack messages for invalid configurations
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Ido Schimmel <idosch@mellanox.com>
commit 8f6862065d8be320ba45a52c8a361b580722fc18

Add extack messages to better communicate invalid configuration to the
user.

Example:

# devlink sb pool set pci/0000:01:00.0 pool 0 size 104857600 thtype dynamic
Error: mlxsw_spectrum: Exceeded shared buffer size.
devlink answers: Invalid argument

	Signed-off-by: Ido Schimmel <idosch@mellanox.com>
	Acked-by: Jiri Pirko <jiri@mellanox.com>
	Reviewed-by: Petr Machata <petrm@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8f6862065d8be320ba45a52c8a361b580722fc18)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>