media: cx231xx: fix RC_CORE dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 9fab166a3e8f9e071de3418d27ffd03cdba2e9df

With CONFIG_RC_CORE=m and VIDEO_CX231XX=y, we get a link failure:

drivers/media/usb/cx231xx/cx231xx-input.o: In function `cx231xx_ir_init':
cx231xx-input.c:(.text+0xd4): undefined reference to `rc_allocate_device'

This narrows down the dependency so that only valid configurations
are allowed.

Fixes: 84545d2a1436 ("media: cx231xx: Remove RC_CORE dependency")

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
	Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>
(cherry picked from commit 9fab166a3e8f9e071de3418d27ffd03cdba2e9df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>