ASoC: max98373: usleep_range() needs include/delay.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: max98373: usleep_range() needs include/delay.h (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.55%
commit-author Grant Grundler <grundler@chromium.org>
commit 3004136b90bedc9e254ff659adb7a60299e9495e

Commit ca917f9fe1a0fab added use of usleep_range() but not
the corresponding "include <linux/delay.h>". The result is
with Chrome OS won't build because warnings are forced
to be errors:
mnt/host/source/src/third_party/kernel/v4.4/sound/soc/codecs/max98373.c:734:2: error: implicit declaration of function 'usleep_range' [-Werror,-Wimplicit-function-declaration]
        usleep_range(10000, 11000);
        ^

Including delay.h "fixes" this.

	Signed-off-by: Grant Grundler <grundler@chromium.org>
	Reviewed-by: Benson Leung <bleung@chromium.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 3004136b90bedc9e254ff659adb7a60299e9495e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>