pinctrl: imx: prepare for making "group_names" in "function_desc" const
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071845
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set updates pinctrl
 support (NB: some Intel and NVIDIA patches are included as well for similar
 Platforms).  It has been tested via simple boot tests, examining the pinctrl
 definintions in DeviceTree, and by using the kernel GPIO tools to verify
 pins are being still being identified and can be used.

commit 02f117134952c06faef2adb322630c51fcd3c197
Author: Rafał Miłecki <rafal@milecki.pl>
Date:   Thu Dec 16 17:22:03 2021 +0100

    pinctrl: imx: prepare for making "group_names" in "function_desc" const

    The plan for "struct function_desc" is to make its "group_names"
    /double/ const. That will allow drivers to use it with static const
    data.

    This imx change is required to avoid:
    drivers/pinctrl/freescale/pinctrl-imx.c: In function 'imx_pinctrl_parse_functions':
    drivers/pinctrl/freescale/pinctrl-imx.c:672:24: error: assignment of read-only location '*(func->group_names + (sizetype)(i * 4))'
      672 |   func->group_names[i] = child->name;
          |                        ^

    Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
    Link: https://lore.kernel.org/r/20211216162206.8027-1-zajec5@gmail.com
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
    (cherry picked from commit 02f117134952c06faef2adb322630c51fcd3c197)

Signed-off-by: Al Stone <ahs3@redhat.com>