module: include internal.h in module/dups.c
JIRA: https://issues.redhat.com/browse/RHEL-28063

commit 0b891c83d8c54cb70e186456c2191adb5fd98c56
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sat Apr 29 22:36:04 2023 +0200

    module: include internal.h in module/dups.c

    Two newly introduced functions are declared in a header that is not
    included before the definition, causing a warning with sparse or
    'make W=1':

    kernel/module/dups.c:118:6: error: no previous prototype for 'kmod_dup_request_exists_wait' [-Werror=missing-prototypes]
      118 | bool kmod_dup_request_exists_wait(char *module_name, bool wait, int *dup_ret)
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    kernel/module/dups.c:220:6: error: no previous prototype for 'kmod_dup_request_announce' [-Werror=missing-prototypes]
      220 | void kmod_dup_request_announce(char *module_name, int ret)
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~

    Add an explicit include to ensure the prototypes match.

    Fixes: 8660484ed1cf ("module: add debugging auto-load duplicate module support")
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/oe-kbuild-all/202304141440.DYO4NAzp-lkp@intel.com/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>