clk: imx: Make CLK_IMX8ULP select MXC_CLK
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit e8271eff5d8c8499289380edbf3bc47de83ab70b
Author: Fabio Estevam <festevam@gmail.com>
Date:   Wed Oct 6 16:00:08 2021 -0300

    clk: imx: Make CLK_IMX8ULP select MXC_CLK

    Building CLK_IMX8ULP without selecting MXC_CLK causes the following
    build errors:

    ld: drivers/clk/imx/clk-imx8ulp.o: in function `imx8ulp_clk_cgc2_init':
    clk-imx8ulp.c:(.text+0xd0): undefined reference to `imx_ccm_lock'
    ld: clk-imx8ulp.c:(.text+0x14f): undefined reference to `imx_clk_hw_pllv4'
    ld: clk-imx8ulp.c:(.text+0x15a): undefined reference to `imx_ccm_lock'

    Avoid this problem by making CLK_IMX8ULP select MXC_CLK.

    Fixes: c43a801a5789 ("clk: imx: Add clock driver for imx8ulp")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Fabio Estevam <festevam@gmail.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Reviewed-by: Abel Vesa <abel.vesa@nxp.com>
    Link: https://lore.kernel.org/r/20211006190008.1935051-1-festevam@gmail.com
    Signed-off-by: Abel Vesa <abel.vesa@nxp.com>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>