libbpf: Fixed various checkpatch issues in libbpf.c
Bugzilla: https://bugzilla.redhat.com/2177177

commit e3ba8e4e8c19a9b4d1866bc72d81afb10c043560
Author: Kang Minchul <tegongkang@gmail.com>
Date:   Mon Nov 14 04:06:47 2022 +0900

    libbpf: Fixed various checkpatch issues in libbpf.c

    Fixed following checkpatch issues:

    WARNING: Block comments use a trailing */ on a separate line
    +        * other BPF program's BTF object */

    WARNING: Possible repeated word: 'be'
    +        * name. This is important to be be able to find corresponding BTF

    ERROR: switch and case should be at the same indent
    +       switch (ext->kcfg.sz) {
    +               case 1: *(__u8 *)ext_val = value; break;
    +               case 2: *(__u16 *)ext_val = value; break;
    +               case 4: *(__u32 *)ext_val = value; break;
    +               case 8: *(__u64 *)ext_val = value; break;
    +               default:

    ERROR: trailing statements should be on next line
    +               case 1: *(__u8 *)ext_val = value; break;

    ERROR: trailing statements should be on next line
    +               case 2: *(__u16 *)ext_val = value; break;

    ERROR: trailing statements should be on next line
    +               case 4: *(__u32 *)ext_val = value; break;

    ERROR: trailing statements should be on next line
    +               case 8: *(__u64 *)ext_val = value; break;

    ERROR: code indent should use tabs where possible
    +                }$

    WARNING: please, no spaces at the start of a line
    +                }$

    WARNING: Block comments use a trailing */ on a separate line
    +        * for faster search */

    ERROR: code indent should use tabs where possible
    +^I^I^I^I^I^I        &ext->kcfg.is_signed);$

    WARNING: braces {} are not necessary for single statement blocks
    +       if (err) {
    +               return err;
    +       }

    ERROR: code indent should use tabs where possible
    +^I^I^I^I        sizeof(*obj->btf_modules), obj->btf_module_cnt + 1);$

    Signed-off-by: Kang Minchul <tegongkang@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Stanislav Fomichev <sdf@google.com>
    Link: https://lore.kernel.org/bpf/20221113190648.38556-3-tegongkang@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>