dm space map metadata: fix sm_bootstrap_get_nr_blocks()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [md] dm-space-map-metadata: fix sm_bootstrap_get_nr_blocks() (Mike Snitzer) [1205955]
Rebuild_FUZZ: 94.55%
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit c1c6156fe4d4577444b769d7edd5dd503e57bbc9

This function isn't right and it causes a static checker warning:

	drivers/md/dm-thin.c:3016 maybe_resize_data_dev()
	error: potentially using uninitialized 'sb_data_size'.

It should set "*count" and return zero on success the same as the
sm_metadata_get_nr_blocks() function does earlier.

Fixes: 3241b1d3e0aa ('dm: add persistent data library')
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Joe Thornber <ejt@redhat.com>
	Signed-off-by: Mike Snitzer <snitzer@redhat.com>
(cherry picked from commit c1c6156fe4d4577444b769d7edd5dd503e57bbc9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>