ASoC: soc-ops-test: dynamically allocate struct snd_ctl_elem_value
JIRA: https://issues.redhat.com/browse/RHEL-118909

commit dae29b678bb74aa2995c1d2b0fa6b1b91f5d8986
Author: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Date: Fri Jun 13 06:00:20 2025 +0000

    ASoC: soc-ops-test: dynamically allocate struct snd_ctl_elem_value

    This structure is really too larget to be allocated on the stack:

    	linux/sound/soc/soc-ops-test.c:520:1: error: the frame size of\
    	1304 bytes is larger than 1280 bytes
    	[-Werror=frame-larger-than=]

    Change the function to dynamically allocate it instead.

    Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
    Link: https://patch.msgid.link/87sek489l8.wl-kuninori.morimoto.gx@renesas.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>