mmc: sdhci-pci-gli: Fix build error unused-function
JIRA: https://issues.redhat.com/browse/RHEL-41085

commit 1c5fd97373115b932afa72fbc5425560e0d1148f
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Sun Jun 19 18:47:12 2022 +0800

    mmc: sdhci-pci-gli: Fix build error unused-function

    If CONFIG_PM is not set.

    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-, will be failed, like this:

    drivers/mmc/host/sdhci-pci-gli.c:834:13: error: ‘gl9763e_set_low_power_negotiation’ defined but not used [-Werror=unused-function]
     static void gl9763e_set_low_power_negotiation(struct sdhci_pci_slot *slot, bool enable)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    make[3]: *** [drivers/mmc/host/sdhci-pci-gli.o] Error 1

    To fix building warning, wrap all related code with CONFIG_PM.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Acked-by: Adrian Hunter <adrian.hunter@intel.com>
    Link: https://lore.kernel.org/r/20220619104712.125364-1-renzhijie2@huawei.com
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>