block, dax: use correct format string in bdev_dax_supported
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 67fd38973513c341c84654ae2f819089b840a39b

The new message has an incorrect format string, causing a warning in some
configurations:

fs/block_dev.c: In function 'bdev_dax_supported':
fs/block_dev.c:779:5: error: format '%d' expects argument of type 'int', but argument 2 has type 'long int' [-Werror=format=]
     "error: dax access failed (%d)", len);

This changes it to use the correct %ld instead of %d.

Fixes: 2093f2e9dfec ("block, dax: convert bdev_dax_supported() to dax_direct_access()")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Dan Williams <dan.j.williams@intel.com>
(cherry picked from commit 67fd38973513c341c84654ae2f819089b840a39b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>