block: Fix an error path in disk_update_zone_resources()
JIRA: https://issues.redhat.com/browse/RHEL-154215
Conflicts: context difference

commit 07a1bc5c14c9ef6401b21c1873c6c087075ff292
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Wed Jan 14 11:28:02 2026 -0800

    block: Fix an error path in disk_update_zone_resources()

    Any queue_limits_start_update() call must be followed either by a
    queue_limits_commit_update() call or by a queue_limits_cancel_update()
    call. Make sure that the error path near the start of
    disk_update_zone_resources() follows this requirement. Remove the
    "goto unfreeze" statement from that error path to make the code easier
    to verify.

    This was detected by annotating the queue_limits_*() calls with Clang
    thread-safety attributes and by building the kernel with thread-safety
    checking enabled. Without this patch and with thread-safety checking
    enabled, the following error is reported:

    block/blk-zoned.c:2020:1: error: mutex 'disk->queue->limits_lock' is not held on every path through here [-Werror,-Wthread-safety-analysis]
     2020 | }
          | ^
    block/blk-zoned.c:1959:8: note: mutex acquired here
     1959 |         lim = queue_limits_start_update(q);
          |               ^

    Cc: Damien Le Moal <dlemoal@kernel.org>
    Cc: Christoph Hellwig <hch@lst.de>
    Fixes: bba4322e3f30 ("block: freeze queue when updating zone resources")
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Link: https://lore.kernel.org/r/20260114192803.4171847-3-bvanassche@acm.org
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>