drm/vc4: Fix build error when CONFIG_DRM_VC4=y && CONFIG_RASPBERRYPI_FIRMWARE=m
Bugzilla: https://bugzilla.redhat.com/2138240

commit 4dee8eebcfc1a99d7550855ec40720503df4842b
Author: Zheng Bin <zhengbin13@huawei.com>
Date:   Mon Apr 11 10:43:25 2022 +0800

    drm/vc4: Fix build error when CONFIG_DRM_VC4=y && CONFIG_RASPBERRYPI_FIRMWARE=m

    If CONFIG_DRM_VC4=y, CONFIG_RASPBERRYPI_FIRMWARE=m, CONFIG_COMPILE_TEST=n,
    bulding fails:

    drivers/gpu/drm/vc4/vc4_drv.o: In function `vc4_drm_bind':
    vc4_drv.c:(.text+0x320): undefined reference to `rpi_firmware_get'
    vc4_drv.c:(.text+0x320): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `rpi_firmware_get'
    vc4_drv.c:(.text+0x34c): undefined reference to `rpi_firmware_property'
    vc4_drv.c:(.text+0x34c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `rpi_firmware_property'
    vc4_drv.c:(.text+0x354): undefined reference to `rpi_firmware_put'
    vc4_drv.c:(.text+0x354): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `rpi_firmware_put'

    Make DRM_VC4 depends on RASPBERRYPI_FIRMWARE || (COMPILE_TEST && !RASPBERRYPI_FIRMWARE) to fix this.

    Fixes: c406ad5e4a85 ("drm/vc4: Notify the firmware when DRM is in charge")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Zheng Bin <zhengbin13@huawei.com>
    Signed-off-by: Maxime Ripard <maxime@cerno.tech>
    Link: https://patchwork.freedesktop.org/patch/msgid/20220411024325.3968413-1-zhengbin13@huawei.com

Signed-off-by: Adrien Thierry <athierry@redhat.com>