Input: ads7846 - increase xfer array size in 'struct ser_req'
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.13
Tested: with the hid-tools test suite and some hardware

commit 470a271627e8c4e2b5357fd0f5759cf6e33cc145
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Nov 11 08:09:55 2024 -0700

    Input: ads7846 - increase xfer array size in 'struct ser_req'

    Clang warns (or errors with CONFIG_WERROR=y, trimmed for brevity):

      drivers/input/touchscreen/ads7846.c:412:2: error: array index 6 is past the end of the array (that has type 'struct spi_transfer[6]') [-Werror,-Warray-bounds]
        412 |         req->xfer[6].tx_buf = &req->scratch;
            |         ^         ~
      ...
      drivers/input/touchscreen/ads7846.c:416:2: error: array index 7 is past the end of the array (that has type 'struct spi_transfer[6]') [-Werror,-Warray-bounds]
        416 |         req->xfer[7].rx_buf = &req->scratch;
            |         ^         ~
      drivers/input/touchscreen/ads7846.c:334:2: note: array 'xfer' declared here
        334 |         struct spi_transfer     xfer[6];
            |         ^

    Increase the size of xfer in 'struct ser_req' to ensure that there is
    enough space for all necessary members and there are no out of bounds
    accesses, clearing up the warning.

    Fixes: 781a07da9bb9 ("Input: ads7846 - add dummy command register clearing cycle")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Marek Vasut <marex@denx.de>
    Link: https://lore.kernel.org/r/20241111-input-ads7846-increase-xfer-array-size-v1-1-06cd92e9f20f@kernel.org
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>