perf: Fix building warning on ARM 32
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] Fix building warning on ARM 32 (Jiri Olsa) [1209607]
Rebuild_FUZZ: 90.91%
commit-author Wang Nan <wangnan0@huawei.com>
commit ac931f87a647ca156f65a4c00e7297165e4fa2d8

Commit 85c116a6cb91 ("perf callchain: Make get_srcline fall back to sym+offset")
introduces asprintf() call and matches '%ld' to a u64 argument, which is
incorrect on ARM:

   CC       /home/wn/util/srcline.o
 util/srcline.c: In function 'get_srcline':
 util/srcline.c:297:6: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'u64' [-Werror=format]
 cc1: all warnings being treated as errors
 make[1]: *** [/home/wn/util/srcline.o] Error 1

In addition, all users of get_srcline() use u64 addr, and libbfd
also use 64 bit bfd_vma as address. This patch also fix
prototype of get_srcline() and addr2line() to use u64 addr
instead of unsigned long.

	Signed-off-by: Wang Nan <wangnan0@huawei.com>
	Acked-by: Namhyung Kim <namhyung@kernel.org>
	Cc: <lizefan@huawei.com>
	Cc: <a.p.zijlstra@chello.nl>
	Cc: <paulus@samba.org>
	Cc: <acme@kernel.org>
	Cc: <ak@linux.intel.com>
Link: http://lkml.kernel.org/r/1418710746-35943-1-git-send-email-wangnan0@huawei.com
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit ac931f87a647ca156f65a4c00e7297165e4fa2d8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>