tools include uapi asm-generic: Grab a copy of fcntl.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit 84d1d8a12df33a3e707866b9a1f9872058c3d1fb

We'll need defines for beautifying fcntl arguments that are not
available in older distros, these:

  trace/beauty/fcntl.c: In function 'syscall_arg__scnprintf_fcntl_arg':
  trace/beauty/fcntl.c:93: error: 'F_OFD_SETLK' undeclared (first use in this function)
  trace/beauty/fcntl.c:93: error: (Each undeclared identifier is reported only once
  trace/beauty/fcntl.c:93: error: for each function it appears in.)
  trace/beauty/fcntl.c:93: error: 'F_OFD_SETLKW' undeclared (first use in this function)
  trace/beauty/fcntl.c:93: error: 'F_OFD_GETLK' undeclared (first use in this function)
  trace/beauty/fcntl.c:94: error: 'F_GETOWN_EX' undeclared (first use in this function)
  trace/beauty/fcntl.c:94: error: 'F_SETOWN_EX' undeclared (first use in this function)

	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/n/tip-gvlw67a47e9z65jdunj4je5s@git.kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 84d1d8a12df33a3e707866b9a1f9872058c3d1fb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>