io_uring/register: guard compat syscall with CONFIG_COMPAT
JIRA: https://issues.redhat.com/browse/RHEL-27755

commit baf59771343dc0c2ef9ac3189bf9df2d6143654f
Author: Jens Axboe <axboe@kernel.dk>
Date:   Tue Jan 16 17:08:32 2024 -0700

    io_uring/register: guard compat syscall with CONFIG_COMPAT
    
    Add compat.h include to avoid a potential build issue:
    
    io_uring/register.c:281:6: error: call to undeclared function 'in_compat_syscall'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
    
    if (in_compat_syscall()) {
        ^
    1 warning generated.
    io_uring/register.c:282:9: error: call to undeclared function 'compat_get_bitmap'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
    ret = compat_get_bitmap(cpumask_bits(new_mask),
          ^
    
    Fixes: c43203154d8a ("io_uring/register: move io_uring_register(2) related code to register.c")
    Reported-by: Manu Bretelle <chantra@meta.com>
    Reviewed-by: Jeff Moyer <jmoyer@redhat.com>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>