powerpc/powernv: Fix build with IOMMU_API=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit 79cb6879135b7441f0955ca3f86be8c8d21c7199
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-240.el8/79cb6879.failed

The builds breaks when IOMMU_API=n, eg. skiroot_defconfig:

  arch/powerpc/platforms/powernv/npu-dma.c:96:28: error: 'get_gpu_pci_dev_and_pe' defined but not used
  arch/powerpc/platforms/powernv/npu-dma.c:126:13: error: 'pnv_npu_set_window' defined but not used

Fixes: b4d37a7b6934 ("powerpc/powernv: Remove unused pnv_npu_try_dma_set_bypass() function")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 79cb6879135b7441f0955ca3f86be8c8d21c7199)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/platforms/powernv/npu-dma.c