sched/headers: Move 'struct sched_param' out of uapi, to work around glibc/musl breakage
JIRA: https://issues.redhat.com/browse/RHEL-113275

Conflicts: Context diff in include/linux/sched.h due to
    changes introduced with commit 8e7f4729fad2ede3a8f48276c6ff05d51c113a1c
    ("sched/deadline: Introduce deadline servers").

commit d844fe65f0957024c3e1b0bf2a0615246184d9bc
Author: Kir Kolyshkin <kolyshkin@gmail.com>
Date:   Mon Aug 7 20:03:57 2023 -0700

    sched/headers: Move 'struct sched_param' out of uapi, to work around glibc/musl breakage

    Both glibc and musl define 'struct sched_param' in sched.h, while kernel
    has it in uapi/linux/sched/types.h, making it cumbersome to use
    sched_getattr(2) or sched_setattr(2) from userspace.

    For example, something like this:

            #include <sched.h>
            #include <linux/sched/types.h>

            struct sched_attr sa;

    will result in "error: redefinition of ‘struct sched_param’" (note the
    code doesn't need sched_param at all -- it needs struct sched_attr
    plus some stuff from sched.h).

    The situation is, glibc is not going to provide a wrapper for
    sched_{get,set}attr, thus the need to include linux/sched_types.h
    directly, which leads to the above problem.

    Thus, the userspace is left with a few sub-par choices when it wants to
    use e.g. sched_setattr(2), such as maintaining a copy of struct
    sched_attr definition, or using some other ugly tricks.

    OTOH, 'struct sched_param' is well known, defined in POSIX, and it won't
    be ever changed (as that would break backward compatibility).

    So, while 'struct sched_param' is indeed part of the kernel uapi,
    exposing it the way it's done now creates an issue, and hiding it
    (like this patch does) fixes that issue, hopefully without creating
    another one: common userspace software rely on libc headers, and as
    for "special" software (like libc), it looks like glibc and musl
    do not rely on kernel headers for 'struct sched_param' definition
    (but let's Cc their mailing lists in case it's otherwise).

    The alternative to this patch would be to move struct sched_attr to,
    say, linux/sched.h, or linux/sched/attr.h (the new file).

    Oh, and here is the previous attempt to fix the issue:

      https://lore.kernel.org/all/20200528135552.GA87103@google.com/

    While I support Linus arguments, the issue is still here
    and needs to be fixed.

    [ mingo: Linus is right, this shouldn't be needed - but on the other
             hand I agree that this header is not really helpful to
             user-space as-is. So let's pretend that
             <uapi/linux/sched/types.h> is only about sched_attr, and
             call this commit a workaround for user-space breakage
             that it in reality is ... Also, remove the Fixes tag. ]

    Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Link: https://lore.kernel.org/r/20230808030357.1213829-1-kolyshkin@gmail.com

Signed-off-by: Radostin Stoyanov <rstoyano@redhat.com>