net: export netdev_txq_to_tc to allow sch_mqprio to compile as module
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] export netdev_txq_to_tc to allow sch_mqprio to compile as module (Ivan Vecera) [1579358]
Rebuild_FUZZ: 96.24%
commit-author Henrik Austad <henrik@austad.us>
commit 8a5f2166a6288ee4b5a393f1ebc8cfb26b0510f0

In commit 32302902ff09 ("mqprio: Reserve last 32 classid values for HW
traffic classes and misc IDs") sch_mqprio started using netdev_txq_to_tc
to find the correct tc instead of dev->tc_to_txq[]

However, when mqprio is compiled as a module, it cannot resolve the
symbol, leading to this error:

     ERROR: "netdev_txq_to_tc" [net/sched/sch_mqprio.ko] undefined!

This adds an EXPORT_SYMBOL() since the other user in the kernel
(netif_set_xps_queue) is also EXPORT_SYMBOL() (and not _GPL) or in a
sysfs-callback.

	Cc: Alexander Duyck <alexander.h.duyck@intel.com>
	Cc: Jesus Sanchez-Palencia <jesus.sanchez-palencia@intel.com>
	Cc: David S. Miller <davem@davemloft.net>
	Signed-off-by: Henrik Austad <haustad@cisco.com>
	Reviewed-by: Eric Dumazet <edumazet@google.com>
	Acked-by: Alexander Duyck <alexander.h.duyck@intel.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8a5f2166a6288ee4b5a393f1ebc8cfb26b0510f0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>