net: Use __kernel_clockid_t in uapi net_stamp.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
Rebuild_CHGLOG: - [net] Use __kernel_clockid_t in uapi net_stamp.h (Davide Caratti) [1638022]
Rebuild_FUZZ: 94.38%
commit-author Davide Caratti <dcaratti@redhat.com>
commit e2c4cf7f98a519eb4d95532bfa06bcaf3562fed5

Herton reports the following error when building a userspace program that
includes net_stamp.h:

 In file included from foo.c:2:
 /usr/include/linux/net_tstamp.h:158:2: error: unknown type name
 ‘clockid_t’
   clockid_t clockid; /* reference clockid */
   ^~~~~~~~~

Fix it by using __kernel_clockid_t in place of clockid_t.

Fixes: 80b14dee2bea ("net: Add a new socket option for a future transmit time.")
	Cc: Timothy Redaelli <tredaelli@redhat.com>
	Reported-by: Herton R. Krzesinski <herton@redhat.com>
	Signed-off-by: Davide Caratti <dcaratti@redhat.com>
	Tested-by: Paolo Abeni <pabeni@redhat.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e2c4cf7f98a519eb4d95532bfa06bcaf3562fed5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>