perf tools: Initialize perf_data_file fd field
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Jérémie Galarneau <jeremie.galarneau@efficios.com>
commit c04c859f439fb4de9039246370d60a07b9b5bcb5

Building the perf CTF converter fails with gcc 4.8.4 on Ubuntu 14.04
with the following error:

  error: missing initializer for field ‘fd’ of ‘struct perf_data_file’
  [-Werror=missing-field-initializers]

Per 4b838b0db4e9 ("perf tools: Add compression id into 'struct
kmod_path'") and the ensuing discussion on the mailing list, it appears
that this affects other distributions and gcc versions.

	Signed-off-by: Jeremie Galarneau <jeremie.galarneau@efficios.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/20180829201648.19588-1-jeremie.galarneau@efficios.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit c04c859f439fb4de9039246370d60a07b9b5bcb5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>