overflow: add DEFINE_FLEX() for on-stack allocs
JIRA: https://issues.redhat.com/browse/RHEL-40250

Conflicts:
- partial backport that includes only changes to fortify-string.h as
  the other changes were already backported by RHEL commit e027710623a02
- spaces wrongly added by the mentioned RHEL commit to compiler_types.h
  are replaced by tabs according the original upstream commit

commit 26dd68d293fd1c5ac966fb5dd5f6d89de322a541
Author: Przemek Kitszel <przemyslaw.kitszel@intel.com>
Date:   Tue Sep 12 07:59:31 2023 -0400

    overflow: add DEFINE_FLEX() for on-stack allocs

    Add DEFINE_FLEX() macro for on-stack allocations of structs with
    flexible array member.

    Expose __struct_size() macro outside of fortify-string.h, as it could be
    used to read size of structs allocated by DEFINE_FLEX().
    Move __member_size() alongside it.
    -Kees

    Using underlying array for on-stack storage lets us to declare
    known-at-compile-time structures without kzalloc().

    Actual usage for ice driver is in following patches of the series.

    Missing __has_builtin() workaround is moved up to serve also assembly
    compilation with m68k-linux-gcc, see [1].
    Error was (note the .S file extension):
    In file included from ../include/linux/linkage.h:5,
                     from ../arch/m68k/fpsp040/skeleton.S:40:
    ../include/linux/compiler_types.h:331:5: warning: "__has_builtin" is not defined, evaluates to 0 [-Wundef]
      331 | #if __has_builtin(__builtin_dynamic_object_size)
          |     ^~~~~~~~~~~~~
    ../include/linux/compiler_types.h:331:18: error: missing binary operator before token "("
      331 | #if __has_builtin(__builtin_dynamic_object_size)
          |                  ^

    [1] https://lore.kernel.org/netdev/202308112122.OuF0YZqL-lkp@intel.com/
    Co-developed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Link: https://lore.kernel.org/r/20230912115937.1645707-2-przemyslaw.kitszel@intel.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>