smb: client: fix smbdirect_recv_io leak in smbd_negotiate() error path
JIRA: https://issues.redhat.com/browse/RHEL-116054

commit daac51c7032036a0ca5f1aa419ad1b0471d1c6e0
Author: Stefan Metzmacher <metze@samba.org>
Date:   Thu Sep 18 03:06:46 2025 +0200

    smb: client: fix smbdirect_recv_io leak in smbd_negotiate() error path
    
    During tests of another unrelated patch I was able to trigger this
    error: Objects remaining on __kmem_cache_shutdown()
    
    Cc: Steve French <smfrench@gmail.com>
    Cc: Tom Talpey <tom@talpey.com>
    Cc: Long Li <longli@microsoft.com>
    Cc: Namjae Jeon <linkinjeon@kernel.org>
    Cc: linux-cifs@vger.kernel.org
    Cc: samba-technical@lists.samba.org
    Fixes: f198186aa9bb ("CIFS: SMBD: Establish SMB Direct connection")
    Signed-off-by: Stefan Metzmacher <metze@samba.org>
    Signed-off-by: Steve French <stfrench@microsoft.com>

Signed-off-by: Paulo Alcantara <paalcant@redhat.com>