drm/amd/display: Apply e4479aecf658 to dml
JIRA: https://issues.redhat.com/browse/RHEL-142315

commit b023b3f236e84ce57da67ca96d6da44b6db1f7ed
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Sat Dec 13 15:16:43 2025 +0900

    drm/amd/display: Apply e4479aecf658 to dml

    commit 70740454377f1ba3ff32f5df4acd965db99d055b upstream.

    After an innocuous optimization change in clang-22, allmodconfig (which
    enables CONFIG_KASAN and CONFIG_WERROR) breaks with:

      drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn32/display_mode_vba_32.c:1724:6: error: stack frame size (3144) exceeds limit (3072) in 'dml32_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
       1724 | void dml32_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
            |      ^

    With clang-21, this function was already pretty close to the existing
    limit of 3072 bytes.

      drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn32/display_mode_vba_32.c:1724:6: error: stack frame size (2904) exceeds limit (2048) in 'dml32_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
       1724 | void dml32_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
            |      ^

    A similar situation occurred in dml2, which was resolved by
    commit e4479aecf658 ("drm/amd/display: Increase sanitizer frame larger
    than limit when compile testing with clang") by increasing the limit for
    clang when compile testing with certain sanitizer enabled, so that
    allmodconfig (an easy testing target) continues to work.

    Apply that same change to the dml folder to clear up the warning for
    allmodconfig, unbreaking the build.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/2135
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    (cherry picked from commit 25314b453cf812150e9951a32007a32bba85707e)
    Cc: stable@vger.kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Anusha Srivatsa <asrivats@redhat.com>