selftests: nft_nat: switch port shadow test cases to socat
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Florian Westphal <fw@strlen.de>
commit a2acf0c0e2da29950d0361a3b5ea05e8d0351dfe

There are now at least three distinct flavours of netcat/nc tool:
'original' version, one version ported from openbsd and nmap-ncat.

The script only works with original because it sets SOREUSEPORT option.

Other nc versions return 'port already in use' error and port shadow test fails:

PASS: inet IPv6 redirection for ns2-hMHcaRvx
nc: bind failed: Address already in use
ERROR: portshadow test default: got reply from "ROUTER", not CLIENT as intended

Switch to socat instead.

	Reported-by: kernel test robot <oliver.sang@intel.com>
	Signed-off-by: Florian Westphal <fw@strlen.de>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit a2acf0c0e2da29950d0361a3b5ea05e8d0351dfe)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>