net/mlx5_en: Add missing check for memory allocation failure
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [netdrv] mlx5_en: Add missing check for memory allocation failure (Amir Vadai) [1164527 1164530 1164531 1164536 1164537]
Rebuild_FUZZ: 96.55%
commit-author Amir Vadai <amirv@mellanox.com>
commit 5e24851ec502334986c2ac775beb4b7184a0b6c5

The patch afb736e9330a: "net/mlx5: Ethernet resource handling files"
from May 28, 2015, leads to the following static checker warning:

drivers/net/ethernet/mellanox/mlx5/core/en_flow_table.c:726 mlx5e_create_main_flow_table()
error: potential null dereference 'g'.  (kcalloc returns null)

Fixes: afb736e9330a ("net/mlx5: Ethernet resource handling files")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Amir Vadai <amirv@mellanox.com>
	Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5e24851ec502334986c2ac775beb4b7184a0b6c5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>