mm/page_owner.c: add missing __initdata attribute
Bugzilla: https://bugzilla.redhat.com/2160210

commit 3645b5ec0ad644942e363c9a695a6f4c783c0a43
Author: Fanjun Kong <bh1scw@gmail.com>
Date:   Mon May 16 11:00:42 2022 +0800

    mm/page_owner.c: add missing __initdata attribute

    This patch fixes two issues:
    1. Add __initdata attribute according to include/linux/init.h:
            For initialized data:
            You should insert __initdata between the variable name and equal
            sign followed by value

    2. Fix below error reported by checkpatch.pl:
            ERROR: do not initialise statics to false

    Special thanks to Muchun Song :)

    Link: https://lkml.kernel.org/r/20220516030039.1487005-1-bh1scw@gmail.com
    Signed-off-by: Fanjun Kong <bh1scw@gmail.com>
    Suggested-by: Muchun Song <songmuchun@bytedance.com>
    Reviewed-by: Muchun Song <songmuchun@bytedance.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>