ALSA: compress_offload: import DMA_BUF namespace
JIRA: https://issues.redhat.com/browse/RHEL-80681

commit 1ae40d5231732275c620a1c58c83884a979b6eb1
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Dec 16 10:33:40 2024 +0100

    ALSA: compress_offload: import DMA_BUF namespace

    The compression offload code cannot be in a loadable module unless it
    imports that namespace:

    ERROR: modpost: module snd-compress uses symbol dma_buf_get from namespace DMA_BUF, but does not import it.
    ERROR: modpost: module snd-compress uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
    ERROR: modpost: module snd-compress uses symbol dma_buf_fd from namespace DMA_BUF, but does not import it.

    Fixes: 04177158cf98 ("ALSA: compress_offload: introduce accel operation mode")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Shengjiu Wang <shengjiu.wang@gmail.com>
    Acked-by: Vinod Koul <vkoul@kernel.org>
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Link: https://patch.msgid.link/20241216093410.377112-1-arnd@kernel.org

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>