s390/ctcm: add __printf format attribute to ctcm_dbf_longtext
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Heiko Carstens <hca@linux.ibm.com>
commit dddbf91387a04a03a8e071cb4857403df219382e

Allow the compiler to recognize and check format strings and parameters.

As reported with allmodconfig and W=1:

drivers/s390/net/ctcm_dbug.c: In function ‘ctcm_dbf_longtext’:
drivers/s390/net/ctcm_dbug.c:73:9: error: function ‘ctcm_dbf_longtext’ might be a candidate for ‘gnu_printf’ format attribute [-Werror=suggest-attribute=format]
   73 |         vsnprintf(dbf_txt_buf, sizeof(dbf_txt_buf), fmt, args);
      |         ^~~~~~~~~

	Acked-by: Julian Wiedmann <jwi@linux.ibm.com>
	Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
	Signed-off-by: Karsten Graul <kgraul@linux.ibm.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit dddbf91387a04a03a8e071cb4857403df219382e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>