platform/x86/intel/ifs: Add CPU_SUP_INTEL dependency
Bugzilla: https://bugzilla.redhat.com/1971938

commit badb81a58b9e66ca8c15405476f5134e45b57dee
Author: Borislav Petkov <bp@suse.de>
Date:   Thu May 19 16:57:15 2022 +0200

    platform/x86/intel/ifs: Add CPU_SUP_INTEL dependency

    The driver is using functions from a compilation unit which is enabled
    by CONFIG_CPU_SUP_INTEL. Add that dependency to Kconfig explicitly
    otherwise:

      drivers/platform/x86/intel/ifs/load.o: in function `ifs_load_firmware':
      load.c:(.text+0x3b8): undefined reference to `intel_cpu_collect_info'

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lore.kernel.org/r/YoZay8YR0zRGyVu+@zn.tnic
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>