mac80211: minstrel_ht: remove unused n_supported variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit 968a768d28530cadd13aab51531f8fec70bf9eae

clang with W=1 reports
net/mac80211/rc80211_minstrel_ht.c:1711:6: error: variable
  'n_supported' set but not used [-Werror,-Wunused-but-set-variable]
        int n_supported = 0;
            ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Simon Horman <simon.horman@corigine.com>
Link: https://lore.kernel.org/r/20230325132610.1334820-1-trix@redhat.com
	Signed-off-by: Johannes Berg <johannes.berg@intel.com>
(cherry picked from commit 968a768d28530cadd13aab51531f8fec70bf9eae)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>