selftests/powerpc: Add flags.mk to support pmu buildable
JIRA: https://issues.redhat.com/browse/RHEL-74480

Conflicts: There are conflicts
           - The powerpc/pmu/event_code_tests/ folder is not available in RHEL 9.6 because it was introduced in kernel 6.0.
             Since this test folder does not exist, there is no need to make this sub-folder buildable.
             Therefore, the changes to powerpc/pmu/event_code_tests/Makefile have not been backported.

commit 5553a79387e92ffd812a49fdcf679f392281f6a9
Author: Madhavan Srinivasan <maddy@linux.ibm.com>
Date:   Thu Feb 29 15:07:10 2024 +0530

    selftests/powerpc: Add flags.mk to support pmu buildable

    When running `make -C powerpc/pmu run_tests` from top level selftests
    directory, currently this error is being reported:

      make: Entering directory '/home/maddy/linux/tools/testing/selftests/powerpc/pmu'
      Makefile:40: warning: overriding recipe for target 'emit_tests'
      ../../lib.mk:111: warning: ignoring old recipe for target 'emit_tests'
      gcc -m64    count_instructions.c ../harness.c event.c lib.c ../utils.c loop.S  -o /home/maddy/selftest_output//count_instructions
      In file included from count_instructions.c:13:
      event.h:12:10: fatal error: utils.h: No such file or directory
      12 | #include "utils.h"
        |          ^~~~~~~~~
      compilation terminated.

    This is due to missing of include path in CFLAGS. That is, CFLAGS and
    GIT_VERSION macros are defined in the powerpc/ folder Makefile which
    in this case is not involved.

    To address the failure in case of executing specific sub-folder test
    directly, a new rule file has been addded by the patch called "flags.mk"
    under selftest/powerpc/ folder and is linked to all the Makefile of
    powerpc/pmu sub-folders.

    Reported-by: Sachin Sant <sachinp@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Tested-by: Sachin Sant <sachinp@linux.ibm.com>
    [mpe: Fixup ifeq, make GIT_VERSION simply expanded to avoid re-executing git describe]
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/20240229093711.581230-2-maddy@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>