thermal/drivers/qcom/lmh: make QCOM_LMH depends on QCOM_SCM
JIRA: https://issues.redhat.com/browse/RHEL-35736

commit 9e5a4fb8423081d0efbf165c71c7f4abdf5f918c
Author: Jackie Liu <liuyun01@kylinos.cn>
Date:   Sat Oct 9 09:58:53 2021 +0800

    thermal/drivers/qcom/lmh: make QCOM_LMH depends on QCOM_SCM

    Without QCOM_SCM, build failed, avoid like below:

    aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
    aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
    aarch64-linux-gnu-ld: drivers/thermal/qcom/lmh.o: in function `lmh_probe':
    /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:141: undefined reference to `qcom_scm_lmh_dcvsh_available'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:144: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:149: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:154: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:159: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:166: undefined reference to `qcom_scm_lmh_profile_change'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:173: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:180: undefined reference to `qcom_scm_lmh_dcvsh'
    aarch64-linux-gnu-ld: /data/arm/workspace/kernel-build/linux/build/../drivers/thermal/qcom/lmh.c:187: undefined reference to `qcom_scm_lmh_dcvsh'
    make[1]: *** [/data/arm/workspace/kernel-build/linux/Makefile:1183: vmlinux] Error 1
    make[1]: Leaving directory '/data/arm/workspace/kernel-build/linux/build'
    make: *** [Makefile:219: __sub-make] Error 2
    make: Leaving directory '/data/arm/workspace/kernel-build/linux'

    Fixes: 53bca371cdf7 ("thermal/drivers/qcom: Add support for LMh driver")
    Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
    Link: https://lore.kernel.org/r/20211009015853.3509559-1-liu.yun@linux.dev
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>