kselftest/vm: revert "tools/testing/selftests/vm/userfaultfd.c: use swap() to make code cleaner"
commit 07d2505b963b2d30f747dce338211f51068b8765
Author: Shuah Khan <skhan@linuxfoundation.org>
Date:   Thu Feb 3 20:49:45 2022 -0800

    kselftest/vm: revert "tools/testing/selftests/vm/userfaultfd.c: use swap() to make code cleaner"

    With this change, userfaultfd fails to build with undefined reference
    swap() error:

      userfaultfd.c: In function `userfaultfd_stress':
      userfaultfd.c:1530:17: warning: implicit declaration of function `swap'; did you mean `swab'? [-Wimplicit-function-declaration]
       1530 |                 swap(area_src, area_dst);
            |                 ^~~~
            |                 swab
      /usr/bin/ld: /tmp/ccDGOAdV.o: in function `userfaultfd_stress':
      userfaultfd.c:(.text+0x549e): undefined reference to `swap'
      /usr/bin/ld: userfaultfd.c:(.text+0x54bc): undefined reference to `swap'
      collect2: error: ld returned 1 exit status

    Revert the commit to fix the problem.

    Link: https://lkml.kernel.org/r/20220202003340.87195-1-skhan@linuxfoundation.org
    Fixes: 2c769ed7137a ("tools/testing/selftests/vm/userfaultfd.c: use swap() to make code cleaner")
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
    Cc: Shuah Khan <shuah@kernel.org>
    Cc: Minghao Chi <chi.minghao@zte.com.cn>

    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2089501
Signed-off-by: Nico Pache <npache@redhat.com>