netfilter: core: Fix clang warnings about unused static inlines
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit ffdd33dd9c12a8c263f78d778066709ef94671f9
Author: Lukas Wunner <lukas@wunner.de>
Date:   Sat Oct 16 10:13:27 2021 +0200

    netfilter: core: Fix clang warnings about unused static inlines

    Unlike gcc, clang warns about unused static inlines that are not in an
    include file:

      net/netfilter/core.c:344:20: error: unused function 'nf_ingress_hook' [-Werror,-Wunused-function]
      static inline bool nf_ingress_hook(const struct nf_hook_ops *reg, int pf)
                         ^
      net/netfilter/core.c:353:20: error: unused function 'nf_egress_hook' [-Werror,-Wunused-function]
      static inline bool nf_egress_hook(const struct nf_hook_ops *reg, int pf)
                         ^

    According to commit 6863f5643dd7 ("kbuild: allow Clang to find unused
    static inline functions for W=1 build"), the proper resolution is to
    mark the affected functions as __maybe_unused.  An alternative approach
    would be to move them to include/linux/netfilter_netdev.h, but since
    Pablo didn't do that in commit ddcfa710d40b ("netfilter: add
    nf_ingress_hook() helper function"), I'm guessing __maybe_unused is
    preferred.

    This fixes both the warning introduced by Pablo in v5.10 as well as the
    one recently introduced by myself with commit 42df6e1d221d ("netfilter:
    Introduce egress hook").

    Fixes: ddcfa710d40b ("netfilter: add nf_ingress_hook() helper function")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Lukas Wunner <lukas@wunner.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>