ASoC: SOF: Intel: hda-sdw-bpt: fix SND_SOF_SOF_HDA_SDW_BPT dependencies
JIRA: https://issues.redhat.com/browse/RHEL-118909

commit 614d416dd8aee2675fb591c598308a901a660db8
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Aug 5 18:04:25 2025 +0200

    ASoC: SOF: Intel: hda-sdw-bpt: fix SND_SOF_SOF_HDA_SDW_BPT dependencies

    The hda-sdw-bpt code links against the soundwire driver, but that fails when
    trying to link from built-in code into loadable module:

    x86_64-linux-ld: vmlinux.o: in function `intel_ace2x_bpt_close_stream.isra.0':
    intel_ace2x.c:(.text+0x137a531): undefined reference to `hda_sdw_bpt_close'
    x86_64-linux-ld: vmlinux.o: in function `intel_ace2x_bpt_send_async':
    intel_ace2x.c:(.text+0x137aa45): undefined reference to `hda_sdw_bpt_open'
    x86_64-linux-ld: intel_ace2x.c:(.text+0x137ab67): undefined reference to `hda_sdw_bpt_close'
    x86_64-linux-ld: intel_ace2x.c:(.text+0x137ac30): undefined reference to `hda_sdw_bpt_send_async'
    x86_64-linux-ld: vmlinux.o: in function `intel_ace2x_bpt_wait':
    intel_ace2x.c:(.text+0x137aced): undefined reference to `hda_sdw_bpt_wait'

    Ensure that both SOUNDWIRE_INTEL and SND_SOF_SOF_HDA_SDW_BPT are selected
    at the same time by SND_SOC_SOF_INTEL_LNL, and that this happens even if
    SND_SOC_SOF_INTEL_SOUNDWIRE is a loadable module but SND_SOC_SOF_INTEL_LNL
    is built-in.

    This follows the same logic as commit c5a61db9bf89 ("ASoC: SOF: fix
    intel-soundwire link failure").

    Fixes: 5d5cb86fb46e ("ASoC: SOF: Intel: hda-sdw-bpt: add helpers for SoundWire BPT DMA")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Bard Liao <yung-chuan.liao@linux.intel.com>
    Link: https://patch.msgid.link/20250805160451.4004602-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>