nvme-pci: disable secondary temp for Wodposit WPBSNM8
JIRA: https://issues.redhat.com/browse/RHEL-144763

commit 340f4fc5508c2905a1f30de229e2a4b299d55735
Author: Ilikara Zheng <ilikara@aosc.io>
Date:   Mon Dec 8 21:23:40 2025 +0800

    nvme-pci: disable secondary temp for Wodposit WPBSNM8

    Secondary temperature thresholds (temp2_{min,max}) were not reported
    properly on this NVMe SSD. This resulted in an error while attempting to
    read these values with sensors(1):

      ERROR: Can't get value of subfeature temp2_min: I/O error
      ERROR: Can't get value of subfeature temp2_max: I/O error

    Add the device to the nvme_id_table with the
    NVME_QUIRK_NO_SECONDARY_TEMP_THRESH flag to suppress access to all non-
    composite temperature thresholds.

    Cc: stable@vger.kernel.org
    Tested-by: Wu Haotian <rigoligo03@gmail.com>
    Signed-off-by: Ilikara Zheng <ilikara@aosc.io>
    Signed-off-by: Keith Busch <kbusch@kernel.org>

Signed-off-by: Ming Lei <ming.lei@redhat.com>