drm/bridge: ptn3460: Include linux/gpio/consumer.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [drm] bridge: ptn3460: Include linux/gpio/consumer.h (Rob Clark) [1249805]
Rebuild_FUZZ: 95.83%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit dad3c3503462f59c6bec7edfa19dbde1857962c0
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/dad3c350.failed

If GPIOLIB=n and asm-generic/gpio.h is not used:

    drivers/gpu/drm/bridge/ptn3460.c: In function ‘ptn3460_pre_enable’:
    drivers/gpu/drm/bridge/ptn3460.c:135: error: implicit declaration of function ‘gpiod_set_value’
    drivers/gpu/drm/bridge/ptn3460.c: In function ‘ptn3460_probe’:
    drivers/gpu/drm/bridge/ptn3460.c:333: error: implicit declaration of function ‘devm_gpiod_get’
    drivers/gpu/drm/bridge/ptn3460.c:333: warning: assignment makes pointer from integer without a cast
    drivers/gpu/drm/bridge/ptn3460.c:340: error: implicit declaration of function ‘gpiod_direction_output’
    drivers/gpu/drm/bridge/ptn3460.c:346: warning: assignment makes pointer from integer without a cast

Add the missing #include <linux/gpio/consumer.h> to fix this.

Fixes: af478d8823 ("drm/bridge: ptn3460: use gpiod interface")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Cc: David Airlie <airlied@linux.ie>
	Cc: dri-devel@lists.freedesktop.org
	Signed-off-by: Thierry Reding <treding@nvidia.com>
(cherry picked from commit dad3c3503462f59c6bec7edfa19dbde1857962c0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/gpu/drm/bridge/ptn3460.c