Input: synaptics - hide unused smbus_pnp_ids[] array
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.15
Tested: with the hid-tools test suite and some hardware

commit 496b7d2e5b936e3e8eae651b51db8a2f9cf0f8b8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 25 12:25:35 2025 -0800

    Input: synaptics - hide unused smbus_pnp_ids[] array

    When SMBUS is disabled, this is never referenced, causing a W=1 warning:

    drivers/input/mouse/synaptics.c:164:27: error: 'smbus_pnp_ids' defined but not used [-Werror=unused-const-variable=]

    Hide the array behind the same #ifdef as the code referencing it.

    Fixes: e839ffab0289 ("Input: synaptics - add support for Intertouch devices")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250225145451.1141995-1-arnd@kernel.org
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>