nbd: automatically load module on genl access
JIRA: https://issues.redhat.com/browse/RHEL-25988

commit ffe357c868e7796f20bc0eac61f5b952731c0fa8
Author: Thomas Weißschuh <linux@weissschuh.net>
Date:   Thu Jul 13 21:29:35 2023 +0200

    nbd: automatically load module on genl access

    Add a module alias to nbd.ko that allows the generic netlink core to
    automatically load the module when netlink messages for nbd are
    received.

    This frees the user from manually having to load the module before using
    nbd functionality via netlink.
    If the system policy allows it this can even be used to load the nbd
    module from containers which would otherwise not have access to the
    necessary module files to do a normal "modprobe nbd".

    For example this avoids the following error when using nbd-client:

    $ nbd-client localhost 10809 /dev/nbd0
    ...
    Error: Couldn't resolve the nbd netlink family, make sure the nbd module is loaded and your nbd driver supports the netlink interface.

    Signed-off-by: Thomas Weißschuh <linux@weissschuh.net>
    Reviewed-by: Josef Bacik <josef@toxicpadna.com>
    Link: https://lore.kernel.org/r/20230713-b4-nbd-genl-v3-1-226cbddba04b@weissschuh.net
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>