bus: mhi: host: remove unused-but-set parameter
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit b0f9f3607959a24685bb5ebeed57cc2f8a66869d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 11 15:45:41 2023 +0200

    bus: mhi: host: remove unused-but-set parameter
    
    Clang warns about a parameter that is decremented but never evaluated here:
    
    bus/mhi/host/main.c:803:13: error: parameter 'event_quota' set but not used [-Werror,-Wunused-but-set-parameter]
                                 u32 event_quota)
    
    Remove the access to the variable to avoid that warning.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jeffrey Hugo <quic_jhugo@quicinc.com>
    Link: https://lore.kernel.org/r/20230811134547.3231160-1-arnd@kernel.org
    [mani: minor spelling fix to commit message]
    Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>