bitfield: build kunit tests without structleak plugin
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit a8cf90332ae3e2b53813a146a99261b6a5e16a73
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-494.el8/a8cf9033.failed

The structleak plugin causes the stack frame size to grow immensely:

lib/bitfield_kunit.c: In function 'test_bitfields_constants':
lib/bitfield_kunit.c:93:1: error: the frame size of 7440 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Brendan Higgins <brendanhiggins@google.com>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit a8cf90332ae3e2b53813a146a99261b6a5e16a73)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	lib/Makefile