net: rfkill-gpio: Add explicit include for of.h
Bugzilla: https://bugzilla.redhat.com/2196821

commit 75c7124ef3bafe0e9d1801d6449196dc3105df24
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:17 2023 -0500

    net: rfkill-gpio: Add explicit include for of.h
    
    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:
    
    net/rfkill/rfkill-gpio.c:181:21: error: implicit declaration of function 'of_match_ptr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    
    Acked-by: Johannes Berg <johannes@sipsolutions.net>
    Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
    Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>