selftests/bpf: fix a clang compilation error
Bugzilla: https://bugzilla.redhat.com/2120966

commit cdb5ed9796e70ca666863eff65cf4907da5fe13c
Author: Yonghong Song <yhs@fb.com>
Date:   Thu Jan 27 08:37:26 2022 -0800

    selftests/bpf: fix a clang compilation error

    When building selftests/bpf with clang
      make -j LLVM=1
      make -C tools/testing/selftests/bpf -j LLVM=1
    I hit the following compilation error:

      trace_helpers.c:152:9: error: variable 'found' is used uninitialized whenever 'while' loop exits because its condition is false [-Werror,-Wsometimes-uninitialized]
              while (fscanf(f, "%zx-%zx %s %zx %*[^\n]\n", &start, &end, buf, &base) == 4) {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      trace_helpers.c:161:7: note: uninitialized use occurs here
              if (!found)
                   ^~~~~
      trace_helpers.c:152:9: note: remove the condition if it is always true
              while (fscanf(f, "%zx-%zx %s %zx %*[^\n]\n", &start, &end, buf, &base) == 4) {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     1
      trace_helpers.c:145:12: note: initialize the variable 'found' to silence this warning
              bool found;
                        ^
                         = false

    It is possible that for sane /proc/self/maps we may never hit the above issue
    in practice. But let us initialize variable 'found' properly to silence the
    compilation error.

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/r/20220127163726.1442032-1-yhs@fb.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>