dma/contiguous: avoid warning about unused size_bytes
commit d7b98ae5221007d3f202746903d4c21c7caf7ea9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Apr 9 17:15:42 2025 +0200

    dma/contiguous: avoid warning about unused size_bytes

    When building with W=1, this variable is unused for configs with
    CONFIG_CMA_SIZE_SEL_PERCENTAGE=y:

    kernel/dma/contiguous.c:67:26: error: 'size_bytes' defined but not used [-Werror=unused-const-variable=]

    Change this to a macro to avoid the warning.

    Fixes: c64be2bb1c6e ("drivers: add Contiguous Memory Allocator")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Link: https://lore.kernel.org/r/20250409151557.3890443-1-arnd@kernel.org

(cherry picked from commit d7b98ae5221007d3f202746903d4c21c7caf7ea9)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
JIRA: https://issues.redhat.com/browse/RHEL-89891