usb: cdnsp: Fixes error: uninitialized symbol 'len'
JIRA: https://issues.redhat.com/browse/RHEL-54566

commit 1edf48991a783d00a3a18dc0d27c88139e4030a2
Author: Pawel Laszczak <pawell@cadence.com>
Date:   Fri Mar 31 05:06:00 2023 -0400

    usb: cdnsp: Fixes error: uninitialized symbol 'len'

    The patch 5bc38d33a5a1: "usb: cdnsp: Fixes issue with redundant
    Status Stage" leads to the following Smatch static checker warning:

      drivers/usb/cdns3/cdnsp-ep0.c:470 cdnsp_setup_analyze()
      error: uninitialized symbol 'len'.

    cc: <stable@vger.kernel.org>
    Fixes: 5bc38d33a5a1 ("usb: cdnsp: Fixes issue with redundant Status Stage")
    Signed-off-by: Pawel Laszczak <pawell@cadence.com>
    Link: https://lore.kernel.org/r/20230331090600.454674-1-pawell@cadence.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Martin McConnell <mmcconne@redhat.com>