net/mlx5: Fix addr's type in mlx5dr_icm_dm
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [netdrv] mlx5: Fix addr's type in mlx5dr_icm_dm (Alaa Hleihel) [1760284 1724336]
Rebuild_FUZZ: 95.00%
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 334a306f7be8423932da8a0382616fe403d334cf

clang errors when CONFIG_PHYS_ADDR_T_64BIT is not set:

drivers/net/ethernet/mellanox/mlx5/core/steering/dr_icm_pool.c:121:8:
error: incompatible pointer types passing 'u64 *' (aka 'unsigned long
long *') to parameter of type 'phys_addr_t *' (aka 'unsigned int *')
[-Werror,-Wincompatible-pointer-types]
                                   &icm_mr->dm.addr, &icm_mr->dm.obj_id);
                                   ^~~~~~~~~~~~~~~~
include/linux/mlx5/driver.h:1092:39: note: passing argument to parameter
'addr' here
                         u64 length, u16 uid, phys_addr_t *addr, u32 *obj_id);
                                                           ^
1 error generated.

Use phys_addr_t for addr's type in mlx5dr_icm_dm, which won't change
anything with 64-bit builds because phys_addr_t is u64 when
CONFIG_PHYS_ADDR_T_64BIT is set, which is always when CONFIG_64BIT is
set.

Fixes: 29cf8febd185 ("net/mlx5: DR, ICM pool memory allocator")
Link: https://github.com/ClangBuiltLinux/linux/issues/653
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit 334a306f7be8423932da8a0382616fe403d334cf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>