arm64: kexec_file: include linux/vmalloc.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 732291c4fab8b790847aa572703c01ad483b14d0

This is needed for compilation in some configurations that don't
include it implicitly:

arch/arm64/kernel/machine_kexec_file.c: In function 'arch_kimage_file_post_load_cleanup':
arch/arm64/kernel/machine_kexec_file.c:37:2: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]

Fixes: 52b2a8af7436 ("arm64: kexec_file: load initrd and device-tree")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Will Deacon <will.deacon@arm.com>
(cherry picked from commit 732291c4fab8b790847aa572703c01ad483b14d0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>