bpf: Only provide bpf_sock_from_file with CONFIG_NET
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Florent Revest <revest@chromium.org>
commit b60da4955f53d1f50e44351a9c3a37a92503079e
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-326.el8/b60da495.failed

This moves the bpf_sock_from_file definition into net/core/filter.c
which only gets compiled with CONFIG_NET and also moves the helper proto
usage next to other tracing helpers that are conditional on CONFIG_NET.

This avoids
  ld: kernel/trace/bpf_trace.o: in function `bpf_sock_from_file':
  bpf_trace.c:(.text+0xe23): undefined reference to `sock_from_file'
When compiling a kernel with BPF and without NET.

	Reported-by: kernel test robot <lkp@intel.com>
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Florent Revest <revest@chromium.org>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
	Acked-by: Randy Dunlap <rdunlap@infradead.org>
	Acked-by: Martin KaFai Lau <kafai@fb.com>
	Acked-by: KP Singh <kpsingh@kernel.org>
Link: https://lore.kernel.org/bpf/20201208173623.1136863-1-revest@chromium.org
(cherry picked from commit b60da4955f53d1f50e44351a9c3a37a92503079e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/linux/bpf.h