mlx5: prevent 64bit divide
Bugzilla: https://bugzilla.redhat.com/2049449
Upstream-status: v5.16-rc1

commit ac6b7e0d9679db908d92fb96605d1ce01e8173d4
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Mon Oct 18 10:26:08 2021 -0700

    mlx5: prevent 64bit divide

    mlx5_tout_ms() returns a u64, we can't directly divide it.
    This is not a problem here, @timeout which is the value
    that actually matters here is already a ulong, so this
    implies storing return value of mlx5_tout_ms() on a ulong
    should be fine.

    This fixes:

      ERROR: modpost: "__udivdi3" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

    Fixes: 32def4120e48 ("net/mlx5: Read timeout values from DTOR")
    Link: https://lore.kernel.org/r/20211018172608.1069754-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>