rcu/tree: Export rcu_idle_{enter,exit} to modules
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [kernel] rcu/tree: Export rcu_idle_{enter, exit} to modules (Al Stone) [1865698 1851555]
Rebuild_FUZZ: 98.99%
commit-author Borislav Petkov <bp@suse.de>
commit 3ad1c8ef083bef96ec922688966484be1039e6b5

Fix this link error:

  ERROR: modpost: "rcu_idle_enter" [drivers/acpi/processor.ko] undefined!
  ERROR: modpost: "rcu_idle_exit" [drivers/acpi/processor.ko] undefined!

when CONFIG_ACPI_PROCESSOR is built as module. PeterZ says that in light
of ARM needing those soon too, they should simply be exported.

Fixes: 1fecfdbb7acc ("ACPI: processor: Take over RCU-idle for C3-BM idle")
	Reported-by: Sven Joachim <svenjoac@gmx.de>
	Suggested-by: Peter Zijlstra <peterz@infradead.org>
	Signed-off-by: Borislav Petkov <bp@suse.de>
	Reviewed-by: Paul E. McKenney <paulmckrcu@kernel.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 3ad1c8ef083bef96ec922688966484be1039e6b5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>