perf bench: Fix two numa NDEBUG warnings
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit 183d4f2d23acecb29695f4d07427c8594e3a9691
Author: Ian Rogers <irogers@google.com>
Date: Thu Apr 28 13:29:11 2022 -0700

description
===========
BUG_ON is a no-op if NDEBUG is defined, otherwise it is an assert.
Compiling with NDEBUG yields:

  bench/numa.c: In function ‘bind_to_cpu’:
  bench/numa.c:314:1: error: control reaches end of non-void function [-Werror=return-type]
    314 | }
        | ^
  bench/numa.c: In function ‘bind_to_node’:
  bench/numa.c:367:1: error: control reaches end of non-void function [-Werror=return-type]
    367 | }
        | ^

Add return statements to cover this case.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>