vhost: silence an unused-variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit cfdbb4ed31aa777d59b288810f66eb06249ee5b7

On some architectures, the MMU can be disabled, leading to access_ok()
becoming an empty macro that does not evaluate its size argument,
which in turn produces an unused-variable warning:

drivers/vhost/vhost.c:1191:9: error: unused variable 's' [-Werror,-Wunused-variable]
        size_t s = vhost_has_feature(vq, VIRTIO_RING_F_EVENT_IDX) ? 2 : 0;

Mark the variable as __maybe_unused to shut up that warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit cfdbb4ed31aa777d59b288810f66eb06249ee5b7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>