ASoC: qcom: sm8250: Fix possibly undefined reference
JIRA: https://issues.redhat.com/browse/RHEL-112757

commit 999fb9d51f939ee23cbb9313ae558d29d6987804
Author: Luca Weiss <luca.weiss@fairphone.com>
Date: Tue Jun 17 14:20:12 2025 +0200

    ASoC: qcom: sm8250: Fix possibly undefined reference

    With CONFIG_SND_SOC_SM8250=y and CONFIG_SND_SOC_QCOM_OFFLOAD_UTILS=m
    selected in kconfig, the build will fail due to trying to link against a
    symbol only found in the module.

      aarch64-linux-gnu-ld: sound/soc/qcom/sm8250.o: in function `sm8250_snd_exit':
      sound/soc/qcom/sm8250.c:52:(.text+0x210): undefined reference to `qcom_snd_usb_offload_jack_remove'

    Fix this by declaring the dependency that forces CONFIG_SND_SOC_SM8250=m
    when CONFIG_SND_SOC_QCOM_OFFLOAD_UTILS is =m.

    Reported-by: Matthew Croughan <matthew.croughan@nix.how>
    Fixes: 1b8d0d87b934 ("ASoC: qcom: qdsp6: Add headphone jack for offload connection status")
    Signed-off-by: Luca Weiss <luca.weiss@fairphone.com>
    Link: https://patch.msgid.link/20250617-snd-sm8250-dep-fix-v1-1-879af8906ec4@fairphone.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>