ASoC: stac9766: fix build errors with REGMAP_AC97
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-536.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit c70064b96f509daa78f57992aeabcf274fb2fed4

Select REGMAP_AC97 to fix these build errors:

ERROR: modpost: "regmap_ac97_default_volatile" [sound/soc/codecs/snd-soc-stac9766.ko] undefined!
ERROR: modpost: "__regmap_init_ac97" [sound/soc/codecs/snd-soc-stac9766.ko] undefined!

Fixes: 6bbf787bb70c ("ASoC: stac9766: Convert to regmap")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Lars-Peter Clausen <lars@metafoo.de>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: Liam Girdwood <lgirdwood@gmail.com>
	Cc: alsa-devel@alsa-project.org
Link: https://lore.kernel.org/r/20230701044836.18789-1-rdunlap@infradead.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit c70064b96f509daa78f57992aeabcf274fb2fed4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>