powerpc: Fix unused function warning 'lmb_to_memblock'
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [powerpc] Fix unused function warning 'lmb_to_memblock' (Thomas Huth) [1323417]
Rebuild_FUZZ: 90.91%
commit-author Alastair D'Silva <alastair@d-silva.org>
commit 9dc512819e4b723856773f5a018865c20441072f

This patch fixes the following warning:
arch/powerpc/platforms/pseries/hotplug-memory.c:323:29: error: 'lmb_to_memblock' defined but not used [-Werror=unused-function]
static struct memory_block *lmb_to_memblock(struct of_drconf_cell *lmb)
                           ^~~~~~~~~~~~~~~

The only consumer of this function is 'dlpar_remove_lmb', which is
enabled with CONFIG_MEMORY_HOTREMOVE, so move it into the same
ifdef block.

	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 9dc512819e4b723856773f5a018865c20441072f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>