net: sched: select cls when cls_act is enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [net] sched: select cls when cls_act is enabled (Ivan Vecera) [1445420]
Rebuild_FUZZ: 94.25%
commit-author Jiri Pirko <jiri@mellanox.com>
commit 8ec1507dc9d16ecd9ada2f67efa95f8d586335fb

It really makes no sense to have cls_act enabled without cls. In that
case, the cls_act code is dead. So select it.

This also fixes an issue recently reported by kbuild robot:
[linux-next:master 1326/4151] net/sched/act_api.c:37:18: error: implicit declaration of function 'tcf_chain_get'

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
	Signed-off-by: Jiri Pirko <jiri@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8ec1507dc9d16ecd9ada2f67efa95f8d586335fb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>