mt76: mt7915: fix MESH ifdef block
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 0bd157fa2aaa2c77d6254321d7751aa9eec68c7b

Fix a build error when CONFIG_MAC80211_MESH is not enabled:

../drivers/net/wireless/mediatek/mt76/mt7915/init.c:47:2: error: expected expression before '}' token
  }, {
  ^

Fixes: af901eb4ab80 ("mt76: mt7915: get rid of dbdc debugfs knob")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Shayne Chen <shayne.chen@mediatek.com>
	Cc: Ryder Lee <ryder.lee@mediatek.com>
	Cc: Lorenzo Bianconi <lorenzo@kernel.org>
	Cc: Felix Fietkau <nbd@nbd.name>
	Cc: linux-wireless@vger.kernel.org
	Cc: Kalle Valo <kvalo@codeaurora.org>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20201218173202.23159-1-rdunlap@infradead.org
(cherry picked from commit 0bd157fa2aaa2c77d6254321d7751aa9eec68c7b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>