iommu/arm-smmu-v3: Add missing #include of linux/string_choices.h
JIRA: https://issues.redhat.com/browse/RHEL-78705
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 1f3dc29d2445c89c85e451c02e41a8e0cd22423c
Author: Will Deacon <will@kernel.org>
Date:   Fri Jan 10 13:18:55 2025 +0000

    iommu/arm-smmu-v3: Add missing #include of linux/string_choices.h

    Commit f2c77f6e41e6 ("iommu/arm-smmu-v3: Use str_read_write helper w/
    logs") introduced a call to str_read_write() in the SMMUv3 driver but
    without an explicit #include of <linux/string_choices.h>. This breaks
    the build for custom configurations where CONFIG_ACPI=n:

    drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c:1909:4: error: call to
	    undeclared function 'str_read_write'; ISO C99 and later do not
	    support implicit function declarations [-Wimplicit-function-declaration]
     1909 |                         str_read_write(evt->read),
	  |                         ^

    Add the missing #include.

    Link: https://lore.kernel.org/r/d07e82a4-2880-4ae3-961b-471bfa7ac6c4@samsung.com
    Reported-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Fixes: f2c77f6e41e6 ("iommu/arm-smmu-v3: Use str_read_write helper w/ logs")
    Signed-off-by: Will Deacon <will@kernel.org>

(cherry picked from commit 1f3dc29d2445c89c85e451c02e41a8e0cd22423c)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>