soundwire: qcom: Fix build failure when slimbus is module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: soundwire: qcom: Fix build failure when slimbus is module (Jaroslav Kysela) [1783462]
Rebuild_FUZZ: 95.00%
commit-author Vinod Koul <vkoul@kernel.org>
commit 47edc0104c61d609b0898a302267b7269d87a6af

Commit 5bd773242f75 ("soundwire: qcom: avoid dependency on
CONFIG_SLIMBUS") removed hard dependency on Slimbus for qcom driver but
it results in build failure when: CONFIG_SOUNDWIRE_QCOM=y
CONFIG_SLIMBUS=m

drivers/soundwire/qcom.o: In function `qcom_swrm_probe':
qcom.c:(.text+0xf44): undefined reference to `slimbus_bus'

Fix this by using IS_REACHABLE() in driver which is recommended to be
used with imply.

Fixes: 5bd773242f75 ("soundwire: qcom: avoid dependency on CONFIG_SLIMBUS")
	Reported-by: kernel test robot <lkp@intel.com>
	Tested-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
	Reviewed-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
Link: https://lore.kernel.org/r/20201125055155.GD8403@vkoul-mobl
	Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit 47edc0104c61d609b0898a302267b7269d87a6af)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>