netfilter: nf_conncount: increase the connection clean up limit to 64
JIRA: https://redhat.atlassian.net/browse/RHEL-168848
Upstream Status: commit 21d033e47273

commit 21d033e472735ecec677f1ae46d6740b5e47a4f3
Author: Fernando Fernandez Mancera <fmancera@suse.de>
Date:   Wed Dec 17 15:46:41 2025 +0100

    netfilter: nf_conncount: increase the connection clean up limit to 64

    After the optimization to only perform one GC per jiffy, a new problem
    was introduced. If more than 8 new connections are tracked per jiffy the
    list won't be cleaned up fast enough possibly reaching the limit
    wrongly.

    In order to prevent this issue, only skip the GC if it was already
    triggered during the same jiffy and the increment is lower than the
    clean up limit. In addition, increase the clean up limit to 64
    connections to avoid triggering GC too often and do more effective GCs.

    This has been tested using a HTTP server and several
    performance tools while having nft_connlimit/xt_connlimit or OVS limit
    configured.

    Output of slowhttptest + OVS limit at 52000 connections:

     slow HTTP test status on 340th second:
     initializing:        0
     pending:             432
     connected:           51998
     error:               0
     closed:              0
     service available:   YES

    Fixes: d265929930e2 ("netfilter: nf_conncount: reduce unnecessary GC")
    Reported-by: Aleksandra Rukomoinikova <ARukomoinikova@k2.cloud>
    Closes: https://lore.kernel.org/netfilter/b2064e7b-0776-4e14-adb6-c68080987471@k2.cloud/
    Signed-off-by: Fernando Fernandez Mancera <fmancera@suse.de>
    Signed-off-by: Florian Westphal <fw@strlen.de>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>