ASoC: topology: avoid uninitialized kcontrol_type
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: topology: avoid uninitialized kcontrol_type (Jaroslav Kysela) [1399503]
Rebuild_FUZZ: 94.23%
commit-author Arnd Bergmann <arnd@arndb.de>
commit dd5abb742071a962be4403f171063ed1e9d4202d

When num_kcontrols is zero, widget->dobj.widget.kcontrol_type
gets set to an uninitialized local variable:

sound/soc/soc-topology.c: In function 'soc_tplg_dapm_widget_create':
sound/soc/soc-topology.c:1566:36: error: 'kcontrol_type' may be used uninitialized in this function [-Werror=maybe-uninitialized]

I could not figure out which of the valid types would be appropriate
here, so this sets it to '0', which is invalid but at least well-defined
here. There is probably a better way to address the issue.

Fixes: eea3dd4f1247 ("ASoC: topology: Only free TLV for volume mixers of a widget")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Reviewed-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit dd5abb742071a962be4403f171063ed1e9d4202d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>