IB/mlx5: Fix undefined behavior due to shift overflowing the constant
Bugzilla: https://bugzilla.redhat.com/2049451
Upstream-status: v5.19-rc1

commit 0276bd3a94c072de3f69b5afe6224e488cc76635
Author: Borislav Petkov <bp@suse.de>
Date:   Tue Apr 5 17:15:16 2022 +0200

    IB/mlx5: Fix undefined behavior due to shift overflowing the constant

    Fix:

      drivers/infiniband/hw/mlx5/main.c: In function ‘translate_eth_legacy_proto_oper’:
      drivers/infiniband/hw/mlx5/main.c:370:2: error: case label does not reduce to an integer constant
        case MLX5E_PROT_MASK(MLX5E_50GBASE_KR2):
        ^~~~

    See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
    details as to why it triggers with older gccs only.

    Link: https://lore.kernel.org/all/20220405151517.29753-11-bp@alien8.de
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Leon Romanovsky <leon@kernel.org>
    Cc: Saeed Mahameed <saeedm@nvidia.com>
    Cc: linux-rdma@vger.kernel.org
    Cc: netdev@vger.kernel.org
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>