usb: ehci: Simplify platform driver registration
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit aad06846a2304e48e7a223fad8971eed16179606
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Tue Sep 7 05:30:02 2021 -0700

    usb: ehci: Simplify platform driver registration

    Use platform_register_drivers() and platform_unregister_drivers() to
    register and unregister ehci platform drivers. This simplifies the code
    and prevents the following build errors seen with sparc:allmodconfig.

    drivers/usb/host/ehci-hcd.c:1301: error:
            "PLATFORM_DRIVER" redefined
    drivers/usb/host/ehci-sh.c:173:31: error:
            'ehci_hcd_sh_driver' defined but not used

    Acked-by: Alan Stern <stern@rowland.harvard.edu>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Link: https://lore.kernel.org/r/20210907123002.3951446-1-linux@roeck-us.net
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>