zsmalloc: Fix "map_vm_area" undefined reference errors.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [mm] zsmalloc: Fix map_vm_area undefined reference errors (Seth Jennings) [1141434]
Rebuild_FUZZ: 97.20%
commit-author Majunath Goudar <csmanjuvijay@gmail.com>
commit 8addac75a1ab0d8bd5fd25dbbc58e02ddfb089c9

This patch adds a MMU dependency to configure the ZSMALLOC in
drivers/staging/zsmalloc/Kconfig. Without this patch, build
system can lead to build failure. This was observed during
randconfig testing, in which ZSMALLOC was enabled w/o MMU being
enabled. Following was the error:

LD      vmlinux
drivers/built-in.o: In function `__zs_map_object':
drivers/staging/zsmalloc/zsmalloc-main.c:650: undefined reference to `map_vm_area'
make: *** [vmlinux] Error 1

	Signed-off-by: Manjunath Goudar <csmanjuvijay@gmail.com>
	Cc: Nitin Gupta <ngupta@vflare.org>
	Cc: Seth Jennings <sjenning@linux.vnet.ibm.com>
	Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Cc: Minchan Kim <minchan@kernel.org>
	Cc: Joerg Roedel <joro@8bytes.org>
	Cc: devel@driverdev.osuosl.org
	Cc: linux-kernel@vger.kernel.org
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 8addac75a1ab0d8bd5fd25dbbc58e02ddfb089c9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>