net: ethernet: renesas: Fix return type of rswitch_start_xmit()
JIRA: https://issues.redhat.com/browse/RHEL-34587

commit 8e0aa1ff44ca30b0b9df95dfa72003522d9a088d
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Thu Nov 3 15:00:32 2022 -0700

    net: ethernet: renesas: Fix return type of rswitch_start_xmit()

    With clang's kernel control flow integrity (kCFI, CONFIG_CFI_CLANG),
    indirect call targets are validated against the expected function
    pointer prototype to make sure the call target is valid to help mitigate
    ROP attacks. If they are not identical, there is a failure at run time,
    which manifests as either a kernel panic or thread getting killed. A
    proposed warning in clang aims to catch these at compile time, which
    reveals:

      drivers/net/ethernet/renesas/rswitch.c:1533:20: error: incompatible function pointer types initializing 'netdev_tx_t (*)(struct sk_buff *, struct net_device *)' (aka 'enum netdev_tx (*)(struct sk_buff *, struct net_device *)') with an expression of type 'int (struct sk_buff *, struct net_device *)' [-Werror,-Wincompatible-function-pointer-types-strict]
              .ndo_start_xmit = rswitch_start_xmit,
                              ^~~~~~~~~~~~~~~~~~
      1 error generated.

    ->ndo_start_xmit() in 'struct net_device_ops' expects a return type of
    'netdev_tx_t', not 'int'. Adjust the return type of rswitch_start_xmit()
    to match the prototype's to resolve the warning and CFI failure.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1750
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Link: https://lore.kernel.org/r/20221103220032.2142122-1-nathan@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Radu Rendec <rrendec@redhat.com>