drm/i915/selftests: Remove unused dmabuf->kmap routines, fix the build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Chris Wilson <chris@chris-wilson.co.uk>
commit f55786faa156370374c358d186eabf2f6e32e93f

Fix i915's CI build after the removal of the dmabuf->kmap interface that
left the mock routines intact.

In file included from drivers/gpu/drm/i915/i915_gem_dmabuf.c:335:0:
drivers/gpu/drm/i915/selftests/mock_dmabuf.c:104:13: error: ‘mock_dmabuf_kunmap_atomic’ defined but not used [-Werror=unused-function]
 static void mock_dmabuf_kunmap_atomic(struct dma_buf *dma_buf, unsigned long page_num, void *addr)
drivers/gpu/drm/i915/selftests/mock_dmabuf.c:97:14: error: ‘mock_dmabuf_kmap_atomic’ defined but not used [-Werror=unused-function]
 static void *mock_dmabuf_kmap_atomic(struct dma_buf *dma_buf, unsigned long page_num)

Fixes: f664a5269542 ("dma-buf: remove kmap_atomic interface")
	Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
	Cc: Christian König <christian.koenig@amd.com>
	Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
	Cc: Sumit Semwal <sumit.semwal@linaro.org>
Link: https://patchwork.freedesktop.org/patch/msgid/20180620162152.1158-1-chris@chris-wilson.co.uk
	Reviewed-by: Christian König <christian.koenig@amd.com>
(cherry picked from commit f55786faa156370374c358d186eabf2f6e32e93f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>