ath11k: fix a locking bug in ath11k_mac_op_start()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit c202e2ebe1dc454ad54fd0018c023ec553d47284

This error path leads to a Smatch warning:

	drivers/net/wireless/ath/ath11k/mac.c:4269 ath11k_mac_op_start()
	error: double unlocked '&ar->conf_mutex' (orig line 4251)

We're not holding the lock when we do the "goto err;" so it leads to a
double unlock.  The fix is to hold the lock for a little longer.

Fixes: c83c500b55b6 ("ath11k: enable idle power save mode")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
[kvalo@codeaurora.org: move also rcu_assign_pointer() call]
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/YBk4GoeE+yc0wlJH@mwanda
(cherry picked from commit c202e2ebe1dc454ad54fd0018c023ec553d47284)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>