bpf: Initialize ret to 0 inside btf_populate_kfunc_set()
Bugzilla: https://bugzilla.redhat.com/2120966

commit d0b3822902b6af45f2c75706d7eb2a35aacab223
Author: Souptick Joarder (HPE) <jrdr.linux@gmail.com>
Date:   Sat Feb 19 22:09:15 2022 +0530

    bpf: Initialize ret to 0 inside btf_populate_kfunc_set()

    Kernel test robot reported below error ->

    kernel/bpf/btf.c:6718 btf_populate_kfunc_set()
    error: uninitialized symbol 'ret'.

    Initialize ret to 0.

    Fixes: dee872e124e8 ("bpf: Populate kfunc BTF ID sets in struct btf")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Souptick Joarder (HPE) <jrdr.linux@gmail.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>
    Link: https://lore.kernel.org/bpf/20220219163915.125770-1-jrdr.linux@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>