scsi: ufs: Make the TC G210 driver dependent on CONFIG_OF
Bugzilla: https://bugzilla.redhat.com/2185234

commit 473025a6b6f8a4a8de3120c78588d32cf4ba7324
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Thu Feb 9 10:49:03 2023 -0800

    scsi: ufs: Make the TC G210 driver dependent on CONFIG_OF

    The TC G210 driver only supports devices declared in the device tree.
    Hence make this driver dependent on CONFIG_OF. This patch fixes the
    following compiler error:

    drivers/ufs/host/tc-dwc-g210-pltfrm.c:36:34: error: ‘tc_dwc_g210_pltfm_match’ defined but not used [-Werror=unused-const-variable=]
       36 | static const struct of_device_id tc_dwc_g210_pltfm_match[] = {
          |

    Link: https://lore.kernel.org/r/20230209184914.2762172-1-bvanassche@acm.org
    Cc: Joao Pinto <jpinto@synopsys.com>
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Reviewed-by: Bean Huo <beanhuo@micron.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>