libbpf: Disable SEC pragma macro on GCC
Bugzilla: https://bugzilla.redhat.com/2137876

commit 18410251f66aee7e82234073ce6656ca20a732a9
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Wed Jul 6 05:18:38 2022 -0600

    libbpf: Disable SEC pragma macro on GCC
    
    It seems the gcc preprocessor breaks with pragmas when surrounding
    __attribute__.
    
    Disable these pragmas on GCC due to upstream bugs see:
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55578
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90400
    
    Fixes errors like:
    error: expected identifier or '(' before '#pragma'
      106 | SEC("cgroup/bind6")
          | ^~~
    
    error: expected '=', ',', ';', 'asm' or '__attribute__' before '#pragma'
      114 | char _license[] SEC("license") = "GPL";
          | ^~~
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20220706111839.1247911-1-james.hilliard1@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>