cifs: Silence uninitialized variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit ff361fda55fda55031252aca1f8afef735fe057c

This is not really a runtime issue but Smatch complains that:

    fs/cifs/smb2ops.c:1740 smb2_query_symlink()
    error: uninitialized symbol 'resp_buftype'.

The warning is right that it can be uninitialized...  Also "err_buf"
would be NULL at this point and we're not supposed to pass NULLs to
free_rsp_buf() or it might trigger some extra output if we turn on
debugging.

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Reviewed-by: Paulo Alcantara <palcantara@suse.de>
	Signed-off-by: Steve French <stfrench@microsoft.com>
(cherry picked from commit ff361fda55fda55031252aca1f8afef735fe057c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>