net/mlx5: fix possible stack overflows
JIRA: https://issues.redhat.com/browse/RHEL-52869
Upstream-status: v6.9-rc4

commit fe87922cee6161f066f4b9dd542033e048eeedaf
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Apr 8 09:41:10 2024 +0200

    net/mlx5: fix possible stack overflows

    A couple of debug functions use a 512 byte temporary buffer and call another
    function that has another buffer of the same size, which in turn exceeds the
    usual warning limit for excessive stack usage:

    drivers/net/ethernet/mellanox/mlx5/core/steering/dr_dbg.c:1073:1: error: stack frame size (1448) exceeds limit (1024) in 'dr_dump_start' [-Werror,-Wframe-larger-than]
    dr_dump_start(struct seq_file *file, loff_t *pos)
    drivers/net/ethernet/mellanox/mlx5/core/steering/dr_dbg.c:1009:1: error: stack frame size (1120) exceeds limit (1024) in 'dr_dump_domain' [-Werror,-Wframe-larger-than]
    dr_dump_domain(struct seq_file *file, struct mlx5dr_domain *dmn)
    drivers/net/ethernet/mellanox/mlx5/core/steering/dr_dbg.c:705:1: error: stack frame size (1104) exceeds limit (1024) in 'dr_dump_matcher_rx_tx' [-Werror,-Wframe-larger-than]
    dr_dump_matcher_rx_tx(struct seq_file *file, bool is_rx,

    Rework these so that each of the various code paths only ever has one of
    these buffers in it, and exactly the functions that declare one have
    the 'noinline_for_stack' annotation that prevents them from all being
    inlined into the same caller.

    Fixes: 917d1e799ddf ("net/mlx5: DR, Change SWS usage to debug fs seq_file interface")
    Reviewed-by: Simon Horman <horms@kernel.org>
    Reviewed-by: Jiri Pirko <jiri@nvidia.com>
    Link: https://lore.kernel.org/all/20240219100506.648089-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Tariq Toukan <tariqt@nvidia.com>
    Link: https://lore.kernel.org/r/20240408074142.3007036-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@redhat.com>