kernel/trace/bpf_trace.c: work around gcc-4.4.4 anon union initialization bug
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [kernel] trace/bpf_trace.c: work around gcc-4.4.4 anon union initialization bug (Jiri Olsa) [1311586]
Rebuild_FUZZ: 95.24%
commit-author Andrew Morton <akpm@linux-foundation.org>
commit 183fc1537ec39be242dc8b619f71fc11b393d295
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/183fc153.failed

kernel/trace/bpf_trace.c: In function 'bpf_event_output':
kernel/trace/bpf_trace.c:312: error: unknown field 'next' specified in initializer
kernel/trace/bpf_trace.c:312: warning: missing braces around initializer
kernel/trace/bpf_trace.c:312: warning: (near initialization for 'raw.frag.<anonymous>')

Fixes: 555c8a8623a3a87 ("bpf: avoid stack copy and use skb ctx for event output")
	Acked-by: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Alexei Starovoitov <ast@kernel.org>
	Cc: David S. Miller <davem@davemloft.net>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Acked-by: Alexei Starovoitov <ast@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 183fc1537ec39be242dc8b619f71fc11b393d295)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	kernel/trace/bpf_trace.c