scsi: qedi: fix build regression
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [scsi] qedi: fix build regression (Chad Dupuis) [1566549]
Rebuild_FUZZ: 89.66%
commit-author Arnd Bergmann <arnd@arndb.de>
commit edd066a10090773e18a2095455ad793c73d022b4

A bugfix I did caused a build regression in some other randconfig
builds in a rare combination of options:

In file included from drivers/scsi/qedi/qedi_fw.c:16:
drivers/scsi/qedi/qedi_gbl.h:26:38: error: array type has incomplete element type 'struct qedi_debugfs_ops'
 extern const struct qedi_debugfs_ops qedi_debugfs_ops[];
                                      ^~~~~~~~~~~~~~~~

This removes the useless #ifdef around the declarations in qedi_dbg.h
to make it always build.

Fixes: 779936faf4f1 ("scsi: qedi: fix building with LTO")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit edd066a10090773e18a2095455ad793c73d022b4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>