ACPI: dock: fix some coding style issues
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Xiaofei Tan <tanxiaofei@huawei.com>
commit 6ee4bdc27d1aee6fb4dde9b28c95fe87d87c1438

Fix some coding style issues reported by checkpatch.pl, including
following types:

WARNING: Missing a blank line after declarations
ERROR: spaces required around that ':'
WARNING: Statements should start on a tabstop

	Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 6ee4bdc27d1aee6fb4dde9b28c95fe87d87c1438)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>