tools/rtla: fix collision with glibc sched_attr/sched_set_attr
JIRA: https://issues.redhat.com/browse/RHEL-69738

commit 0eecee340672c4b512f6f4a8c6add26df05d130c
Author: Jan Stancek <jstancek@redhat.com>
Date:   Thu Oct 10 17:09:48 2024 +0200

    tools/rtla: fix collision with glibc sched_attr/sched_set_attr

    glibc commit 21571ca0d703 ("Linux: Add the sched_setattr
    and sched_getattr functions") now also provides 'struct sched_attr'
    and sched_setattr() which collide with the ones from rtla.

      In file included from src/trace.c:11:
      src/utils.h:49:8: error: redefinition of ‘struct sched_attr’
         49 | struct sched_attr {
            |        ^~~~~~~~~~
      In file included from /usr/include/bits/sched.h:60,
                       from /usr/include/sched.h:43,
                       from /usr/include/tracefs/tracefs.h:10,
                       from src/trace.c:4:
      /usr/include/linux/sched/types.h:98:8: note: originally defined here
         98 | struct sched_attr {
            |        ^~~~~~~~~~

    Define 'struct sched_attr' conditionally, similar to what strace did:
      https://lore.kernel.org/all/20240930222913.3981407-1-raj.khem@gmail.com/
    and rename rtla's version of sched_setattr() to avoid collision.

    Link: https://lore.kernel.org/8088f66a7a57c1b209cd8ae0ae7c336a7f8c930d.1728572865.git.jstancek@redhat.com
    Signed-off-by: Jan Stancek <jstancek@redhat.com>
    Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Luis Claudio R. Goncalves <lgoncalv@redhat.com>