net: openvswitch: use div_u64() for 64-by-32 divisions
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [net] openvswitch: use div_u64() for 64-by-32 divisions (Eelco Chaudron) [1888576]
Rebuild_FUZZ: 95.15%
commit-author Tonghao Zhang <xiangxia.m.yue@gmail.com>
commit 659d4587fe7233bfdff303744b20d6f41ad04362

Compile the kernel for arm 32 platform, the build warning found.
To fix that, should use div_u64() for divisions.
| net/openvswitch/meter.c:396: undefined reference to `__udivdi3'

[add more commit msg, change reported tag, and use div_u64 instead
of do_div by Tonghao]

Fixes: e57358873bb5d6ca ("net: openvswitch: use u64 for meter bucket")
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
	Tested-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 659d4587fe7233bfdff303744b20d6f41ad04362)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>