ASoC: cs35l41: Use modern pm_ops
JIRA: https://issues.redhat.com/browse/RHEL-27515

Omitted-fix: a9a3f54a23d844971c274f352500dddeadb4412c
             ASoC: cs35l41: Handle mdsync_down reg write errors
Omitted-fix: 4bb5870ab60abca6ad18196090831b5e4cf82d93
             ASoC: cs35l41: Handle mdsync_up reg write errors
Omitted-fix: 5ad668a9ce83d819701fb7abc1c2236049ec15c2
             ASoC: cs35l41: Initialize completion object before requesting IRQ
Omitted-fix: 77bf613f0bf08c021309cdb5f84b5f630b829261
             ASoC: cs35l41: Fix broken shared boost activation
Omitted-fix: 9f8948db9849d202dee3570507d3a0642f92d632
             ASoC: cs35l41: Verify PM runtime resume errors in IRQ handler
Omitted-fix: 2d5661e6008ae1a1cd6df7cc844908fb8b982c58
             ASoC: cs35l41: Undo runtime PM changes at driver exit time
Omitted-fix: 3db52739aca981a436536423a36ab59b9f241096
             ASoC: cs35l41: Make use of dev_err_probe()
Omitted-fix: 486465508f8a5fe441939a7d97607f4460a60891
             ALSA: hda: cs35l41: Fix unbalanced pm_runtime_get()
Omitted-fix: 85a1bf86fac0c195929768b4e92c78cad107523b
             ALSA: hda: cs35l41: Undo runtime PM changes at driver exit time
Omitted-fix: 206b250c3e9be44c096bb9bb1f9d6b7f3440bfbb
             ALSA: hda: cs35l41: Consistently use dev_err_probe()

commit 611b8813a28f49e206e05198dae77c544c72b050
Author: Cristian Ciocaltea <cristian.ciocaltea@collabora.com>
Date: Thu Sep 7 20:10:07 2023 +0300

    ASoC: cs35l41: Use modern pm_ops

    Make use of the recently introduced EXPORT_GPL_DEV_PM_OPS() macro, to
    conditionally export the runtime/system PM functions.

    Replace the old SET_{RUNTIME,SYSTEM_SLEEP,NOIRQ_SYSTEM_SLEEP}_PM_OPS()
    helpers with their modern alternatives and get rid of the now
    unnecessary '__maybe_unused' annotations on all PM functions.

    Additionally, use the pm_ptr() macro to fix the following errors when
    building with CONFIG_PM disabled:

    ERROR: modpost: "cs35l41_pm_ops" [sound/soc/codecs/snd-soc-cs35l41-spi.ko] undefined!
    ERROR: modpost: "cs35l41_pm_ops" [sound/soc/codecs/snd-soc-cs35l41-i2c.ko] undefined!

    Signed-off-by: Cristian Ciocaltea <cristian.ciocaltea@collabora.com>
    Acked-by: Charles Keepax <ckeepax@opensource.cirrus.com>
    Reviewed-by: Takashi Iwai <tiwai@suse.de>
    Link: https://lore.kernel.org/r/20230907171010.1447274-9-cristian.ciocaltea@collabora.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>