selftests: net: bpf_offload: add 'libbpf_global' to ignored maps
jira LE-4076
Rebuild_History Non-Buildable kernel-6.12.0-55.29.1.el10_0
commit-author Jakub Kicinski <kuba@kernel.org>
commit 56a586961bf89f2461ebb1b16541b7a161f63238

After installing pahole on the CI image we have a new map created
by libbpf. Ignore it otherwise we see:

  Exception: Time out waiting for map counts to stabilize want 2, have 3

	Acked-by: Stanislav Fomichev <sdf@fomichev.me>
Link: https://patch.msgid.link/20250304233204.1139251-2-kuba@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 56a586961bf89f2461ebb1b16541b7a161f63238)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>