usb: typec: anx7411: Fix build error without CONFIG_POWER_SUPPLY
Bugzilla: http://bugzilla.redhat.com/2113003
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=48723298
Tested: HP ZBook 15 G5/80D5 Laptop
  ThinkPad P1 Gen5  TB4
  HP zBook Fury

commit 09431acde35f46ac82fb5230c7479f1edc557c75
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Tue Sep 20 16:44:31 2022 +0800

    usb: typec: anx7411: Fix build error without CONFIG_POWER_SUPPLY

    Building without CONFIG_POWER_SUPPLY will fail:

    drivers/usb/typec/anx7411.o: In function `anx7411_detect_power_mode':
    anx7411.c:(.text+0x527): undefined reference to `power_supply_changed'
    drivers/usb/typec/anx7411.o: In function `anx7411_psy_set_prop':
    anx7411.c:(.text+0x90d): undefined reference to `power_supply_get_drvdata'
    anx7411.c:(.text+0x930): undefined reference to `power_supply_changed'
    drivers/usb/typec/anx7411.o: In function `anx7411_psy_get_prop':
    anx7411.c:(.text+0x94d): undefined reference to `power_supply_get_drvdata'
    drivers/usb/typec/anx7411.o: In function `anx7411_i2c_probe':
    anx7411.c:(.text+0x111d): undefined reference to
    `devm_power_supply_register'
    drivers/usb/typec/anx7411.o: In function `anx7411_work_func':
    anx7411.c:(.text+0x167c): undefined reference to `power_supply_changed'
    anx7411.c:(.text+0x1b55): undefined reference to `power_supply_changed'

    Add POWER_SUPPLY dependency to Kconfig.

    Fixes: fe6d8a9c8e64 ("usb: typec: anx7411: Add Analogix PD ANX7411 support")
    Reviewed-by: Xin Ji <xji@analogixsemi.com>
    Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Link: https://lore.kernel.org/r/20220920084431.196258-1-renzhijie2@huawei.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>