Bluetooth: hci_event: Fix coding style
jira LE-1907
cve CVE-2020-26555
Rebuild_History Non-Buildable kernel-4.18.0-553.8.1.el8_10
commit-author Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
commit 35d91d95a0cd61ebb90e0246dc917fd25e519b8c

This fixes the following code style problem:

ERROR: that open brace { should be on the previous line
+	if (!bacmp(&hdev->bdaddr, &ev->bdaddr))
+	{

Fixes: 1ffc6f8cc332 ("Bluetooth: Reject connection with the device which has same BD_ADDR")
	Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
(cherry picked from commit 35d91d95a0cd61ebb90e0246dc917fd25e519b8c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>