libbpf: silence GCC8 warning about string truncation
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Andrii Nakryiko <andriin@fb.com>
commit cb8ffde5694ae5fffb456eae932aac442aa3a207

Despite a proper NULL-termination after strncpy(..., ..., IFNAMSIZ - 1),
GCC8 still complains about *expected* string truncation:

  xsk.c:330:2: error: 'strncpy' output may be truncated copying 15 bytes
  from a string of length 15 [-Werror=stringop-truncation]
    strncpy(ifr.ifr_name, xsk->ifname, IFNAMSIZ - 1);

This patch gets rid of the issue altogether by using memcpy instead.
There is no performance regression, as strncpy will still copy and fill
all of the bytes anyway.

v1->v2:
- rebase against bpf tree.

	Cc: Magnus Karlsson <magnus.karlsson@intel.com>
	Signed-off-by: Andrii Nakryiko <andriin@fb.com>
	Acked-by: Magnus Karlsson <magnus.karlsson@intel.com>
	Acked-by: Song Liu <songliubraving@fb.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit cb8ffde5694ae5fffb456eae932aac442aa3a207)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>