samples: bpf: Fix conflicting types in fds_example
Bugzilla: https://bugzilla.redhat.com/2069046

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 64b5b97b8cfff64409fcc234ae3151bc8de0c4d6
Author: Alexander Lobakin <alexandr.lobakin@intel.com>
Date:   Wed Dec 1 17:49:31 2021 +0100

    samples: bpf: Fix conflicting types in fds_example

    Fix the following samples/bpf build error appeared after the
    introduction of bpf_map_create() in libbpf:

      CC  samples/bpf/fds_example.o
    samples/bpf/fds_example.c:49:12: error: static declaration of 'bpf_map_create' follows non-static declaration
    static int bpf_map_create(void)
               ^
    samples/bpf/libbpf/include/bpf/bpf.h:55:16: note: previous declaration is here
    LIBBPF_API int bpf_map_create(enum bpf_map_type map_type,
                   ^
    samples/bpf/fds_example.c:82:23: error: too few arguments to function call, expected 6, have 0
                    fd = bpf_map_create();
                         ~~~~~~~~~~~~~~ ^
    samples/bpf/libbpf/include/bpf/bpf.h:55:16: note: 'bpf_map_create' declared here
    LIBBPF_API int bpf_map_create(enum bpf_map_type map_type,
                   ^
    2 errors generated.

    fds_example by accident has a static function with the same name.
    It's not worth it to separate a single call into its own function,
    so just embed it.

    Fixes: 992c4225419a ("libbpf: Unify low-level map creation APIs w/ new bpf_map_create()")
    Signed-off-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Reviewed-by: Maciej Fijalkowski <maciej.fijalkowski@intel.com>
    Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
    Link: https://lore.kernel.org/bpf/20211201164931.47357-1-alexandr.lobakin@intel.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>