KVM: x86: allow compiling as non-module with W=1
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Valdis Kletnieks <valdis.kletnieks@vt.edu>
commit 575b255c1663c8fccc41fe965dcac281e3113c65

Compile error with CONFIG_KVM_INTEL=y and W=1:

  CC      arch/x86/kvm/vmx/vmx.o
arch/x86/kvm/vmx/vmx.c:68:32: error: 'vmx_cpu_id' defined but not used [-Werror=unused-const-variable=]
   68 | static const struct x86_cpu_id vmx_cpu_id[] = {
      |                                ^~~~~~~~~~
cc1: all warnings being treated as errors

When building with =y, the MODULE_DEVICE_TABLE macro doesn't generate a
reference to the structure (or any code at all).  This makes W=1 compiles
unhappy.

Wrap both in a #ifdef to avoid the issue.

	Signed-off-by: Valdis Kletnieks <valdis.kletnieks@vt.edu>
[Do the same for CONFIG_KVM_AMD. - Paolo]
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 575b255c1663c8fccc41fe965dcac281e3113c65)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>