rxrpc: rxperf: Fix uninitialised variable
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2170099
JIRA: https://issues.redhat.com/browse/RHELPLAN-148774

commit 11e1706bc84f60040578056f8cef3d0139b92dda
Author: David Howells <dhowells@redhat.com>
Date:   Thu Dec 15 16:20:46 2022 +0000

    Dan Carpenter sayeth[1]:

      The patch 75bfdbf2fca3: "rxrpc: Implement an in-kernel rxperf server
      for testing purposes" from Nov 3, 2022, leads to the following Smatch
      static checker warning:

	    net/rxrpc/rxperf.c:337 rxperf_deliver_to_call()
	    error: uninitialized symbol 'ret'.

    Fix this by initialising ret to 0.  The value is only used for tracing
    purposes in the rxperf server.

	Fixes: 75bfdbf2fca3 ("rxrpc: Implement an in-kernel rxperf server for testing purposes")
    Reported-by: Dan Carpenter <error27@gmail.com>
	Signed-off-by: David Howells <dhowells@redhat.com>
    cc: Marc Dionne <marc.dionne@auristor.com>
    cc: linux-afs@lists.infradead.org
    Link: http://lists.infradead.org/pipermail/linux-afs/2022-December/006124.html [1]
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Marc Dionne <mdionne@redhat.com>