wifi: b43legacy: remove unused freq_r3A_value function
Bugzilla: https://bugzilla.redhat.com/2196821

commit 4c7f8c237d322a98026a57f6ba846fc997f165df
Author: Tom Rix <trix@redhat.com>
Date:   Fri Mar 24 09:50:22 2023 -0400

    wifi: b43legacy: remove unused freq_r3A_value function
    
    clang with W=1 reports
    drivers/net/wireless/broadcom/b43legacy/radio.c:1713:5: error:
      unused function 'freq_r3A_value' [-Werror,-Wunused-function]
    u16 freq_r3A_value(u16 frequency)
        ^
    This function is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Acked-by: Larry Finger <Larry.Finger@lwfinger.net>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230324135022.2649735-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>