scsi: bnx2fc: Fix Kconfig warning & CNIC build errors
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit eefb816acb0162e94a85a857f3a55148f671d5a5

CNIC depends on MMU, but since 'select' does not follow any dependency
chains, SCSI_BNX2X_FCOE also needs to depend on MMU, so that erroneous
configs are not generated, which cause build errors in cnic.

WARNING: unmet direct dependencies detected for CNIC
  Depends on [n]: NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_BROADCOM [=y] && PCI [=y] && (IPV6 [=n] || IPV6 [=n]=n) && MMU [=n]
  Selected by [y]:
  - SCSI_BNX2X_FCOE [=y] && SCSI_LOWLEVEL [=y] && SCSI [=y] && PCI [=y] && (IPV6 [=n] || IPV6 [=n]=n) && LIBFC [=y] && LIBFCOE [=y]

riscv64-linux-ld: drivers/net/ethernet/broadcom/cnic.o: in function `.L154':
cnic.c:(.text+0x1094): undefined reference to `uio_event_notify'
riscv64-linux-ld: cnic.c:(.text+0x10bc): undefined reference to `uio_event_notify'
riscv64-linux-ld: drivers/net/ethernet/broadcom/cnic.o: in function `.L1442':
cnic.c:(.text+0x96a8): undefined reference to `__uio_register_device'
riscv64-linux-ld: drivers/net/ethernet/broadcom/cnic.o: in function `.L0 ':
cnic.c:(.text.unlikely+0x68): undefined reference to `uio_unregister_device'

Link: https://lore.kernel.org/r/20210213192428.22537-1-rdunlap@infradead.org
Fixes: 853e2bd2103a ("[SCSI] bnx2fc: Broadcom FCoE offload driver")
	Cc: Saurav Kashyap <skashyap@marvell.com>
	Cc: Javed Hasan <jhasan@marvell.com>
	Cc: GR-QLogic-Storage-Upstream@marvell.com
	Cc: "James E.J. Bottomley" <jejb@linux.ibm.com>
	Cc: "Martin K. Petersen" <martin.petersen@oracle.com>
	Cc: linux-scsi@vger.kernel.org
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit eefb816acb0162e94a85a857f3a55148f671d5a5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>