wifi: ath: remove unused-but-set parameter
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 3b86f86d0f163454c4043a629f0ba95641d371bc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Aug 14 09:32:23 2023 +0200

    wifi: ath: remove unused-but-set parameter
    
    This has never been used since the driver was merged, but it now causes
    a W=1 warning in recent clang versions
    
    drivers/net/wireless/ath/ath9k/main.c:1566:21: error: parameter 'changed_flags' set but not used [-Werror,-Wunused-but-set-parameter]
    drivers/net/wireless/ath/ath9k/htc_drv_main.c:1258:25: error: parameter 'changed_flags' set but not used [-Werror,-Wunused-but-set-parameter]
    drivers/net/wireless/ath/ath5k/mac80211-ops.c:367:62: error: parameter 'changed_flags' set but not used [-Werror,-Wunused-but-set-parameter]
    
    Remove the bit manipulation on the otherwise unused parameter.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20230814073255.1065242-1-arnd@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>