s390/smsgiucv_app: Make use of iucv_alloc_device()
JIRA: https://issues.redhat.com/browse/RHEL-50786
Upstream status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Tested: by IBM
Build-Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=65307356
Conflicts: None

commit 3bbde49ec560f95b2b09b9cedd0c41ae95ecb92c

    Make use of iucv_alloc_device() to get rid of quite some code. In addition
    this also removes a cast to an incompatible function (clang W=1):

    drivers/s390/net/smsgiucv_app.c:176:26: error: cast from 'void (*)(const void *)' to 'void (*)(struct device *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
    176 |         smsg_app_dev->release = (void (*)(struct device *)) kfree;
    |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Closes: https://lore.kernel.org/r/20240417-s390-drivers-fix-cast-function-type-v1-2-fd048c9903b0@kernel.org
    Acked-by: Alexandra Winter <wintera@linux.ibm.com>
    Link: https://lore.kernel.org/r/20240506194454.1160315-5-hca@linux.ibm.com
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Mete Durlu <mdurlu@redhat.com>