bpf: fix constraint in test_tcpbpf_kern.c
JIRA: https://issues.redhat.com/browse/RHEL-23649

commit 756e34da5380e4c0ed2cfbe5259e1b015567a099
Author: Jose E. Marchesi <jose.marchesi@oracle.com>
Date:   Tue Jan 23 21:56:24 2024 +0100

    bpf: fix constraint in test_tcpbpf_kern.c

    GCC emits a warning:

      progs/test_tcpbpf_kern.c:60:9: error: ‘op’ is used uninitialized [-Werror=uninitialized]

    when an uninialized op is used with a "+r" constraint.  The + modifier
    means a read-write operand, but that operand in the selftest is just
    written to.

    This patch changes the selftest to use a "=r" constraint.  This
    pacifies GCC.

    Tested in bpf-next master.
    No regressions.

    Signed-off-by: Jose E. Marchesi <jose.marchesi@oracle.com>
    Cc: Yonghong Song <yhs@meta.com>
    Cc: Eduard Zingerman <eddyz87@gmail.com>
    Cc: david.faust@oracle.com
    Cc: cupertino.miranda@oracle.com
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20240123205624.14746-1-jose.marchesi@oracle.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>