scsi: qla2xxx: Fix nvme_fc_rcv_ls_req() undefined error
JIRA: https://issues.redhat.com/browse/RHEL-9867

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit 27177862de9676c8c35b86bf89c38864fbe5ed71
Author: Nilesh Javali <njavali@marvell.com>
Date:   Thu Aug 24 20:45:21 2023 +0530

    scsi: qla2xxx: Fix nvme_fc_rcv_ls_req() undefined error

    The kernel robot reported below build error,

    >> ERROR: modpost: "nvme_fc_rcv_ls_req" [drivers/scsi/qla2xxx/qla2xxx.ko] undefined!

    Use CONFIG_NVME_FC enabled check to fix the build error.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202308021445.txlNq7UC-lkp@intel.com/
    Signed-off-by: Nilesh Javali <njavali@marvell.com>
    Link: https://lore.kernel.org/r/20230824151521.35261-1-njavali@marvell.com
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>