kbuild: remove --include-dir MAKEFLAG from top Makefile
JIRA: https://issues.redhat.com/browse/RHEL-25415

Conflicts: Minor drift issues.

commit 67d7c3023a672c2b73d19d6d23684df670fce648
Author: Masahiro Yamada <masahiroy@kernel.org>
Date:   Sat Jan 28 18:24:23 2023 +0900

    kbuild: remove --include-dir MAKEFLAG from top Makefile

    I added $(srctree)/ to some included Makefiles in the following commits:

     - 3204a7fb98a3 ("kbuild: prefix $(srctree)/ to some included Makefiles")
     - d82856395505 ("kbuild: do not require sub-make for separate output tree builds")

    They were a preparation for removing --include-dir flag.

    I have never thought --include-dir useful. Rather, it _is_ harmful.

    For example, run the following commands:

      $ make -s ARCH=x86 mrproper defconfig
      $ make ARCH=arm O=foo dtbs
      make[1]: Entering directory '/tmp/linux/foo'
        HOSTCC  scripts/basic/fixdep
      Error: kernelrelease not valid - run 'make prepare' to update it
        UPD     include/config/kernel.release
      make[1]: Leaving directory '/tmp/linux/foo'

    The first command configures the source tree for x86. The next command
    tries to build ARM device trees in the separate foo/ directory - this
    must stop because the directory foo/ has not been configured yet.

    However, due to --include-dir=$(abs_srctree), the top Makefile includes
    the wrong include/config/auto.conf from the source tree and continues
    building. Kbuild traverses the directory tree, but of course it does
    not work correctly. The Error message is also pointless - 'make prepare'
    does not help at all for fixing the issue.

    This commit fixes more arch Makefile, and finally removes --include-dir
    from the top Makefile.

    There are more breakages under drivers/, but I do not volunteer to fix
    them all. I just moved --include-dir to drivers/Makefile.

    With this commit, the second command will stop with a sensible message.

      $ make -s ARCH=x86 mrproper defconfig
      $ make ARCH=arm O=foo dtbs
      make[1]: Entering directory '/tmp/linux/foo'
        SYNC    include/config/auto.conf.cmd
      ***
      *** The source tree is not clean, please run 'make ARCH=arm mrproper'
      *** in /tmp/linux
      ***
      make[2]: *** [../Makefile:646: outputmakefile] Error 1
      /tmp/linux/Makefile:770: include/config/auto.conf.cmd: No such file or directory
      make[1]: *** [/tmp/linux/Makefile:793: include/config/auto.conf.cmd] Error 2
      make[1]: Leaving directory '/tmp/linux/foo'
      make: *** [Makefile:226: __sub-make] Error 2

    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>