remoteproc: imx_dsp_rproc: mark PM functions as __maybe_unused
Bugzilla: http://bugzilla.redhat.com/2071773

commit 51063f54ffaffa8d24eeb9dda5a30916a38b0fe0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Oct 14 09:52:24 2021 +0200

    remoteproc: imx_dsp_rproc: mark PM functions as __maybe_unused

    When CONFIG_PM_SLEEP is disabled, we get a harmless warning:

    drivers/remoteproc/imx_dsp_rproc.c:1145:12: error: 'imx_dsp_resume' defined but not used [-Werror=unused-function]
     1145 | static int imx_dsp_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~
    drivers/remoteproc/imx_dsp_rproc.c:1110:12: error: 'imx_dsp_suspend' defined but not used [-Werror=unused-function]
     1110 | static int imx_dsp_suspend(struct device *dev)
          |            ^~~~~~~~~~~~~~~

    Mark these as __maybe_unused to get a clean build.

    Fixes: ec0e5549f358 ("remoteproc: imx_dsp_rproc: Add remoteproc driver for DSP on i.MX")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211014075239.3714694-1-arnd@kernel.org
    Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>

Signed-off-by: Steve Best <sbest@redhat.com>