iommu/amd: fix SEV-TIO support reporting
JIRA: https://issues.redhat.com/browse/RHEL-147902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 5e5ea7f61610239fca058011e7d4f342b34d1558
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date: Sat Dec 6 11:13:50 2025 -0800

    iommu/amd: fix SEV-TIO support reporting

    Commit eeb934137deb ("iommu/amd: Report SEV-TIO support") was confused
    about the config options that expose amd_iommu_sev_tio_supported(), and
    made the declaration (and alternative dummy function) conditional on the
    CONFIG_AMD_IOMMU config option.

    But the code is actually dependent on CONFIG_KVM_AMD_SEV, resulting in

       ERROR: modpost: "amd_iommu_sev_tio_supported" [drivers/crypto/ccp/ccp.ko] undefined!
       make[2]: *** [scripts/Makefile.modpost:147: Module.symvers] Error 1

    if you have the AMD iommu enabled, but don't enable KVM_AMD_SEV support.

    Fix it by moving the declaration into the right #ifdef section in the
    header file.

    Fixes: eeb934137deb ("iommu/amd: Report SEV-TIO support")
    Cc: Alexey Kardashevskiy <aik@amd.com>
    Cc: Joerg Roedel <joerg.roedel@amd.com>
    Cc: Vasant Hegde <vasant.hegde@amd.com>
    Cc: Tom Lendacky <thomas.lendacky@amd.com>
    Cc: Dan Williams <dan.j.williams@intel.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

(cherry picked from commit 5e5ea7f61610239fca058011e7d4f342b34d1558)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>