xprtrdma: Squelch kbuild sparse complaint
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Chuck Lever <chuck.lever@oracle.com>
commit eed50879d64ab1b9f76445dbab822e43a098b309

New complaint from kbuild for 4.9.y:

net/sunrpc/xprtrdma/verbs.c:489:19: sparse: incompatible types in
    comparison expression (different type sizes)

verbs.c:
489	max_sge = min(ia->ri_device->attrs.max_sge, RPCRDMA_MAX_SEND_SGES);

I can't reproduce this running sparse here. Likewise, "make W=1
net/sunrpc/xprtrdma/verbs.o" never indicated any issue.

A little poking suggests that because the range of its values is
small, gcc can make the actual width of RPCRDMA_MAX_SEND_SGES
smaller than the width of an unsigned integer.

Fixes: 16f906d66cd7 ("xprtrdma: Reduce required number of send SGEs")
	Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
	Cc: stable@kernel.org
	Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
(cherry picked from commit eed50879d64ab1b9f76445dbab822e43a098b309)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>