KVM: selftests: Define _GNU_SOURCE for all selftests code
JIRA: https://issues.redhat.com/browse/RHEL-113452

commit 730cfa45b5f4f170095707b526dc7af99c9f0959
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Apr 23 12:03:08 2024 -0700

    KVM: selftests: Define _GNU_SOURCE for all selftests code

    Define _GNU_SOURCE is the base CFLAGS instead of relying on selftests to
    manually #define _GNU_SOURCE, which is repetitive and error prone.  E.g.
    kselftest_harness.h requires _GNU_SOURCE for asprintf(), but if a selftest
    includes kvm_test_harness.h after stdio.h, the include guards result in
    the effective version of stdio.h consumed by kvm_test_harness.h not
    defining asprintf():

      In file included from x86_64/fix_hypercall_test.c:12:
      In file included from include/kvm_test_harness.h:11:
     ../kselftest_harness.h:1169:2: error: call to undeclared function
      'asprintf'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
       1169 |         asprintf(&test_name, "%s%s%s.%s", f->name,
            |         ^

    When including the rseq selftest's "library" code, #undef _GNU_SOURCE so
    that rseq.c controls whether or not it wants to build with _GNU_SOURCE.

    Reported-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Acked-by: Claudio Imbrenda <imbrenda@linux.ibm.com>
    Acked-by: Oliver Upton <oliver.upton@linux.dev>
    Acked-by: Anup Patel <anup@brainfault.org>
    Reviewed-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Link: https://lore.kernel.org/r/20240423190308.2883084-1-seanjc@google.com
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Conflicts:
    tools/testing/selftests/kvm/Makefile
    tools/testing/selftests/kvm/aarch64/psci_test.c
    (conflicts due to earlier out-of-order backports)
    tools/testing/selftests/kvm/riscv/arch_timer.c
    (no riscv in RHEL9, thus dropped this hunk)
Signed-off-by: Thomas Huth <thuth@redhat.com>