tools/testing/selftests/vm/hmm-tests.c: fix build
Bugzilla: https://bugzilla.redhat.com/2160210

commit 360614c01f81f48a89d8b13f8fa69c3ae0a1f5c7
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Tue Aug 2 18:03:03 2022 -0700

    tools/testing/selftests/vm/hmm-tests.c: fix build

    hmm-tests.c:1607:42: error: 'HMM_DMIRROR_MIGRATE' undeclared (first use in this function); did you mean 'HMM_DMIRROR_WRITE'?

    Fixes: f6c3e1ae0114cd0 ("mm/hmm: add a test for cross device private faults")
    Reported-by: kernel test robot <lkp@intel.com>
    Reviewed-by: Ralph Campbell <rcampbell@nvidia.com>
    Cc: Alistair Popple <apopple@nvidia.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>