objtool: Detect and warn if libelf is missing and don't break the build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [scripts] revert "objtool: Detect and warn if libelf is missing and don't break the build" (Josh Poimboeuf) [1347232]
Rebuild_FUZZ: 93.42%
commit-author Josh Poimboeuf <jpoimboe@redhat.com>
commit 3b27a0c85d7068130ed8e3977a2e977ade986841
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/3b27a0c8.failed

With CONFIG_STACK_VALIDATION enabled, if the host system doesn't have
a development version of libelf installed, the build fails with errors
like:

  elf.h:22:18: fatal error: gelf.h: No such file or directory compilation terminated.

Instead of failing to build, instead just print a warning and disable
stack validation.

	Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Stephen Rothwell <sfr@canb.auug.org.au>
	Cc: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: linux-next@vger.kernel.org
	Cc: linux@roeck-us.net
	Cc: live-patching@vger.kernel.org
Link: http://lkml.kernel.org/r/8c27fe00face60f42e888ddb3142c97e45223165.1457026550.git.jpoimboe@redhat.com
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 3b27a0c85d7068130ed8e3977a2e977ade986841)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	Makefile
#	scripts/Makefile.build