thunderbolt: xdomain: Avoid potential stack OOB read
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 19813551701d004b517534888aa4e2a62ca4488e
Author: Kees Cook <keescook@chromium.org>
Date:   Mon Dec 6 22:34:13 2021 -0800

    thunderbolt: xdomain: Avoid potential stack OOB read

    tb_xdp_properties_changed_request() was calling tb_xdp_handle_error() with
    a struct tb_xdp_properties_changed_response on the stack, which does not
    have the "error" field present when cast to struct tb_xdp_error_response.
    This was detected when building with -Warray-bounds:

    drivers/thunderbolt/xdomain.c: In function 'tb_xdomain_properties_changed':
    drivers/thunderbolt/xdomain.c:226:22: error: array subscript 'const struct tb_xdp_error_response[0]' is partly outside array bounds of 'struct tb_xdp_properties_changed_response[1]' [-Werror=array-bounds]
      226 |         switch (error->error) {
          |                 ~~~~~^~~~~~~
    drivers/thunderbolt/xdomain.c:448:51: note: while referencing 'res'
      448 |         struct tb_xdp_properties_changed_response res;
          |                                                   ^~~

    Add union containing struct tb_xdp_error_response to structures passed
    to tb_xdp_handle_error(), so that the "error" field will be present.

    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>