tools: Work around BITS_PER_LONG related build failure in objtool
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [tools] Work around BITS_PER_LONG related build failure in objtool (Jiri Olsa) [1387909]
Rebuild_FUZZ: 94.31%
commit-author Ingo Molnar <mingo@kernel.org>
commit 7b39cafb7aa68ef8e32a9f51fbe737d96084ca74

The objtool build fails with the recent changes to the bits-per-long
headers:

  tools/include/linux/bitops.h:12:0: error: "BITS_PER_LONG" redefined [-Werror]

Which got introduced by:

  bb9707077b4e tools: Copy the bitsperlong.h files from the kernel

Work it around for the time being.

	Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Josh Poimboeuf <jpoimboe@redhat.com>
	Cc: linux-kernel@vger.kernel.org
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 7b39cafb7aa68ef8e32a9f51fbe737d96084ca74)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>