perf metric: Add metric group test
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Jiri Olsa <jolsa@kernel.org>
commit dfce77c580e02c19efacfe9110261c935d1ddb60

Adding test for metric group plus compute_metric_group function to get
metrics values within the group.

Committer notes:

Fixed this;

  tests/parse-metric.c:327:7: error: missing field 'val' initializer [-Werror,-Wmissing-field-initializers]
                  { 0 },
                      ^

	Signed-off-by: Jiri Olsa <jolsa@kernel.org>
	Reviewed-by: Kajol Jain <kjain@linux.ibm.com>
	Acked-by: Ian Rogers <irogers@google.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Andi Kleen <ak@linux.intel.com>
	Cc: John Garry <john.garry@huawei.com>
	Cc: Michael Petlan <mpetlan@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Stephane Eranian <eranian@google.com>
Link: http://lore.kernel.org/lkml/20200719181320.785305-18-jolsa@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit dfce77c580e02c19efacfe9110261c935d1ddb60)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>