crypto: qat - fix adf_ctl_drv.c:undefined reference to adf_init_pf_wq
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [crypto] qat - fix adf_ctl_drv.c:undefined reference to adf_init_pf_wq (Neil Horman) [1382849]
Rebuild_FUZZ: 93.85%
commit-author Tadeusz Struk <tadeusz.struk@intel.com>
commit 6dc5df71ee5c8b44607928bfe27be50314dcf848
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-693.el7/6dc5df71.failed

Fix undefined reference issue reported by kbuild test robot.

	Cc: <stable@vger.kernel.org>
	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
	Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 6dc5df71ee5c8b44607928bfe27be50314dcf848)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/crypto/qat/qat_common/adf_common_drv.h