dm table: Fix W=1 build warning when mempool_needs_integrity is unused
JIRA: https://issues.redhat.com/browse/RHEL-83595

commit 7bd47be16108e55e6bc85bdd3cae5c9a2bc98a89
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Apr 7 10:21:26 2025 +0300

    dm table: Fix W=1 build warning when mempool_needs_integrity is unused

    The mempool_needs_integrity is unused. This, in particular, prevents
    kernel builds with Clang, `make W=1` and CONFIG_WERROR=y:

    drivers/md/dm-table.c:1052:7: error: variable 'mempool_needs_integrity' set but not used [-Werror,-Wunused-but-set-variable]
     1052 |         bool mempool_needs_integrity = t->integrity_supported;
          |              ^

    Fix this by removing the leftover.

    Fixes: 105ca2a2c2ff ("block: split struct bio_integrity_payload")
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>

Signed-off-by: Ming Lei <ming.lei@redhat.com>