usb: devio: remove assignment from if condition
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] devio: remove assignment from if condition (Torez Smith) [1303955]
Rebuild_FUZZ: 94.38%
commit-author Kris Borer <kborer@gmail.com>
commit 135551ea1abd5038d14825514df7e259fd500033

Fix five occurrences of the checkpatch.pl error:

ERROR: do not use assignment in if condition

The semantic patch that makes this change is:

// <smpl>
@@
identifier i;
expression E;
statement S1, S2;
@@

+ i = E;
  if (
- (i = E)
+ i
  ) S1 else S2

@@
identifier i;
expression E;
statement S;
constant c;
binary operator b;
@@

+ i = E;
  if (
- (i = E)
+ i
  b
  c ) S
// </smpl>

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 135551ea1abd5038d14825514df7e259fd500033)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>