ASoc: SOF: ipc4-pcm: fix uninit-value in sof_ipc4_pcm_dai_link_fixup_rate
JIRA: https://issues.redhat.com/browse/RHEL-80676

commit 9a59718a5340aa0240a442115eb499de2ed18ee4
Author: Suraj Sonawane <surajsonawane0215@gmail.com>
Date: Thu Nov 7 12:06:09 2024 +0530

    ASoc: SOF: ipc4-pcm: fix uninit-value in sof_ipc4_pcm_dai_link_fixup_rate

    Fix an issue detected by the Smatch tool:

    sound/soc/sof/ipc4-pcm.c: sof_ipc4_pcm_dai_link_fixup_rate()
    error: uninitialized symbol 'be_rate'.

    The warning highlights a case where `be_rate` could remain uninitialized
    if `num_input_formats` is zero, which would cause undefined behavior
    when setting `rate->min` and `rate->max` based on `be_rate`.

    To address this issue, a `WARN_ON_ONCE(!num_input_formats)` check was
    added to ensure `num_input_formats` is greater than zero. If this
    condition fails, the function returns `-EINVAL`, preventing the use of
    an uninitialized `be_rate`.

    This change improves the robustness of the function by catching an
    invalid state early and providing better feedback during development.

    Signed-off-by: Suraj Sonawane <surajsonawane0215@gmail.com>
    Link: https://patch.msgid.link/20241107063609.11627-1-surajsonawane0215@gmail.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>