netdevsim: Fix build error without CONFIG_INET
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit d9bd6d279236a1c90c1e73220c2ae52996c8ff52

If CONFIG_INET is not set, building fails:

drivers/net/netdevsim/dev.o: In function `nsim_dev_trap_report_work':
dev.c:(.text+0x67b): undefined reference to `ip_send_check'

Use ip_fast_csum instead of ip_send_check to avoid
dependencies on CONFIG_INET.

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: da58f90f11f5 ("netdevsim: Add devlink-trap support")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
	Reviewed-by: Ido Schimmel <idosch@mellanox.com>
	Tested-by: Ido Schimmel <idosch@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d9bd6d279236a1c90c1e73220c2ae52996c8ff52)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>