iommu/sva: include mmu_notifier.h header
JIRA: https://issues.redhat.com/browse/RHEL-147902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 4b5c493ff762bb0433529ca6870b284f0a2a5ca8
Author: Carlos Llamas <cmllamas@google.com>
Date: Mon Jan 5 19:07:46 2026 +0000

    iommu/sva: include mmu_notifier.h header

    A call to mmu_notifier_arch_invalidate_secondary_tlbs() was introduced in
    commit e37d5a2d60a3 ("iommu/sva: invalidate stale IOTLB entries for kernel
    address space") but without explicitly adding its corresponding header
    file <linux/mmu_notifier.h>.  This was evidenced while trying to enable
    compile testing support for IOMMU_SVA:

       config IOMMU_SVA
	      select IOMMU_MM_DATA
      -       bool
      +       bool "Shared Virtual Addressing" if COMPILE_TEST

    The thing is for certain architectures this header file is indirectly
    included via <asm/tlbflush.h>.  However, for others such as 32-bit arm the
    header is missing and it results in a build failure:

      $ make ARCH=arm allmodconfig
      [...]
      drivers/iommu/iommu-sva.c:340:3: error: call to undeclared function 'mmu_notifier_arch_invalidate_secondary_tlbs' [...]
	340 |  mmu_notifier_arch_invalidate_secondary_tlbs(iommu_mm->mm, start, end);
	    |  ^

    Fix this by including the appropriate header file.

    Link: https://lkml.kernel.org/r/20260105190747.625082-1-cmllamas@google.com
    Fixes: e37d5a2d60a3 ("iommu/sva: invalidate stale IOTLB entries for kernel address space")
    Signed-off-by: Carlos Llamas <cmllamas@google.com>
    Cc: Baolu Lu <baolu.lu@linux.intel.com>
    Cc: Jason Gunthorpe <jgg@ziepe.ca>
    Cc: Joerg Roedel <joro@8bytes.org>
    Cc: Kevin Tian <kevin.tian@intel.com>
    Cc: Robin Murphy <robin.murphy@arm.com>
    Cc: Vasant Hegde <vasant.hegde@amd.com>
    Cc: Will Deacon <will@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

(cherry picked from commit 4b5c493ff762bb0433529ca6870b284f0a2a5ca8)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>