mlx5: avoid 64-bit division in dr_icm_pool_mr_create()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Michal Kubecek <mkubecek@suse.cz>
commit 8b6b82ad163b54a23f0e89710fb25461d45109c4

Recently added code introduces 64-bit division in dr_icm_pool_mr_create()
so that build on 32-bit architectures fails with

  ERROR: "__umoddi3" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

As the divisor is always a power of 2, we can use bitwise operation
instead.

Fixes: 29cf8febd185 ("net/mlx5: DR, ICM pool memory allocator")
	Reported-by: Borislav Petkov <bp@alien8.de>
	Signed-off-by: Michal Kubecek <mkubecek@suse.cz>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8b6b82ad163b54a23f0e89710fb25461d45109c4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>