iommu/tegra241-cmdqv: import IOMMUFD module namespace
JIRA: https://issues.redhat.com/browse/RHEL-114131
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 601b1d0d9395c711383452bd0d47037afbbb4bcf
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Jul 14 22:57:38 2025 +0200

    iommu/tegra241-cmdqv: import IOMMUFD module namespace

    The tegra variant of smmu-v3 now uses the iommufd mmap interface but
    is missing the corresponding import:

    ERROR: modpost: module arm_smmu_v3 uses symbol _iommufd_object_depend from namespace IOMMUFD, but does not import it.
    ERROR: modpost: module arm_smmu_v3 uses symbol iommufd_viommu_report_event from namespace IOMMUFD, but does not import it.
    ERROR: modpost: module arm_smmu_v3 uses symbol _iommufd_destroy_mmap from namespace IOMMUFD, but does not import it.
    ERROR: modpost: module arm_smmu_v3 uses symbol _iommufd_object_undepend from namespace IOMMUFD, but does not import it.
    ERROR: modpost: module arm_smmu_v3 uses symbol _iommufd_alloc_mmap from namespace IOMMUFD, but does not import it.

    Fixes: b135de24cfc0 ("iommu/tegra241-cmdqv: Add user-space use support")
    Link: https://patch.msgid.link/r/20250714205747.3475772-1-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

(cherry picked from commit 601b1d0d9395c711383452bd0d47037afbbb4bcf)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>