r8169: fix building with CONFIG_LEDS_CLASS=m
JIRA: https://issues.redhat.com/browse/RHEL-36272

commit a2634a5ffcafc31c343c6153ae487eb184c433a6
Author: Heiner Kallweit <hkallweit1@gmail.com>
Date:   Wed Jan 3 16:52:04 2024 +0100

    r8169: fix building with CONFIG_LEDS_CLASS=m

    When r8169 is built-in but LED support is a loadable module, the new
    code to drive the LED causes a link failure:

    ld: drivers/net/ethernet/realtek/r8169_leds.o: in function `rtl8168_init_leds':
    r8169_leds.c:(.text+0x36c): undefined reference to `devm_led_classdev_register_ext'

    LED support is an optional feature, so fix this issue by adding a Kconfig
    symbol R8169_LEDS that is guaranteed to be false if r8169 is built-in
    and LED core support is a module. As a positive side effect of this change
    r8169_leds.o no longer is built under this configuration.

    Fixes: 18764b883e15 ("r8169: add support for LED's on RTL8168/RTL8101")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202312281159.9TPeXbNd-lkp@intel.com/
    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Heiner Kallweit <hkallweit1@gmail.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Tested-by: Simon Horman <horms@kernel.org> # build-tested
    Tested-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/d055aeb5-fe5c-4ccf-987f-5af93a17537b@gmail.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>