owners: fix missing jiraComponent
MR!643 was opened before the mandatory jiraComponent was added. It took
very long to get all approvals. Now, when the MR got merged, we're
failing the tests and `make` returns an error:

error: 'RHEL 9.4 Kernel Maintainer' is missing a jiraComponent entry
error: 'RHEL 8.10 Kernel Maintainer' is missing a jiraComponent entry

Add the missing data.

Signed-off-by: Jiri Benc <jbenc@redhat.com>