spi: spi-fsl-dspi: Stub out DMA functions
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit 4850f158c06eeaf4997fc65c47544f2c82ad5a45
Author: James Clark <james.clark@linaro.org>
Date:   Tue Sep 2 13:44:55 2025 +0100

    spi: spi-fsl-dspi: Stub out DMA functions

    In a later commit we'll use dma_alloc_noncoherent() which isn't
    stubbed out for builds without CONFIG_DMA_ENGINE and results in the
    following build error:

      spi-fsl-dspi.c:(.text+0x644): undefined reference to `dma_free_pages'
      m68k-linux-ld: spi-fsl-dspi.c:(.text+0x67a): undefined reference to `dma_free_pages'

    To continue to support devices that only need XSPI mode and so that
    randconfig builds work, stub out DMA functionality in the DSPI driver.

    Although older parts of the DMA API have their own stubs, it's
    intentional that newer parts don't follow the same pattern. Therefore
    individual drivers should not compile in calls unless CONFIG_DMA_ENGINE
    is set.

    Link: https://lore.kernel.org/oe-kbuild-all/202506160036.t9VDxF6p-lkp@intel.com/
    Signed-off-by: James Clark <james.clark@linaro.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Reviewed-by: Vladimir Oltean <vladimir.oltean@nxp.com>
    Message-ID: <20250902-james-nxp-spi-dma-v6-3-f7aa2c5e56e2@linaro.org>
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>