mdio: fix CONFIG_MDIO_DEVRES selects
JIRA: https://issues.redhat.com/browse/RHEL-121399

commit ccc25158c22bf9aaf1242182b852bb6c73e88ac3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 25 13:27:56 2025 +0200

    mdio: fix CONFIG_MDIO_DEVRES selects

    The newly added rtl9300 driver needs MDIO_DEVRES:

    x86_64-linux-ld: drivers/net/mdio/mdio-realtek-rtl9300.o: in function `rtl9300_mdiobus_probe':
    mdio-realtek-rtl9300.c:(.text+0x941): undefined reference to `devm_mdiobus_alloc_size'
    x86_64-linux-ld: mdio-realtek-rtl9300.c:(.text+0x9e2): undefined reference to `__devm_mdiobus_register'
    Since this is a hidden symbol, it needs to be selected by each user,
    rather than the usual 'depends on'. I see that there are a few other
    drivers that accidentally use 'depends on', so fix these as well for
    consistency and to avoid dependency loops.

    Fixes: 37f9b2a6c086 ("net: ethernet: Add missing depends on MDIO_DEVRES")
    Fixes: 24e31e474769 ("net: mdio: Add RTL9300 MDIO driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Chris Packham <chris.packham@alliedtelesis.co.nz>
    Link: https://patch.msgid.link/20250425112819.1645342-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>