ALSA: usb-audio: Fix multiple definitions in AU0828_DEVICE() macro
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Takashi Iwai <tiwai@suse.de>
commit bd1cd0eb2ce9141100628d476ead4de485501b29

AU0828_DEVICE() macro in quirks-table.h uses USB_DEVICE_VENDOR_SPEC()
for expanding idVendor and idProduct fields.  However, the latter
macro adds also match_flags and bInterfaceClass, which are different
from the values AU0828_DEVICE() macro sets after that.

For fixing them, just expand idVendor and idProduct fields manually in
AU0828_DEVICE().

This fixes sparse warnings like:
  sound/usb/quirks-table.h:2892:1: warning: Initializer entry defined twice

	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit bd1cd0eb2ce9141100628d476ead4de485501b29)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>