selftest: include stdio.h in kselftest.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Tycho Andersen <tycho@tycho.ws>
commit a18261d71bbc625bc32abbcded71acc408cca393

While playing around with a way to skip the seccomp get_metadata test, I
noticed that this header uses printf() without defining it, leading to,

../kselftest.h: In function ‘ksft_print_header’:
../kselftest.h:61:3: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
   printf("TAP version 13\n");
   ^~~~~~
../kselftest.h:61:3: warning: incompatible implicit declaration of built-in function ‘printf’
../kselftest.h:61:3: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’

if user code doesn't also use printf.

	Signed-off-by: Tycho Andersen <tycho@tycho.ws>
	Acked-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Shuah Khan <shuah@kernel.org>
(cherry picked from commit a18261d71bbc625bc32abbcded71acc408cca393)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>