net: ethernet: ti: davinci_mdio: fix build for mdio bitbang uses
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit 35bbe652c421037822aba29423f5f1f7d0d69f3f
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Tue Aug 23 19:42:16 2022 -0700

    net: ethernet: ti: davinci_mdio: fix build for mdio bitbang uses

    davinci_mdio.c uses mdio bitbang APIs, so it should select
    MDIO_BITBANG to prevent build errors.

    arm-linux-gnueabi-ld: drivers/net/ethernet/ti/davinci_mdio.o: in function `davinci_mdio_remove':
    drivers/net/ethernet/ti/davinci_mdio.c:649: undefined reference to `free_mdio_bitbang'
    arm-linux-gnueabi-ld: drivers/net/ethernet/ti/davinci_mdio.o: in function `davinci_mdio_probe':
    drivers/net/ethernet/ti/davinci_mdio.c:545: undefined reference to `alloc_mdio_bitbang'
    arm-linux-gnueabi-ld: drivers/net/ethernet/ti/davinci_mdio.o: in function `davinci_mdiobb_read':
    drivers/net/ethernet/ti/davinci_mdio.c:236: undefined reference to `mdiobb_read'
    arm-linux-gnueabi-ld: drivers/net/ethernet/ti/davinci_mdio.o: in function `davinci_mdiobb_write':
    drivers/net/ethernet/ti/davinci_mdio.c:253: undefined reference to `mdiobb_write'

    Fixes: d04807b80691 ("net: ethernet: ti: davinci_mdio: Add workaround for errata i2329")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Grygorii Strashko <grygorii.strashko@ti.com>
    Cc: Ravi Gunasekaran <r-gunasekaran@ti.com>
    Cc: Eric Dumazet <edumazet@google.com>
    Cc: Paolo Abeni <pabeni@redhat.com>
    Cc: Naresh Kamboju <naresh.kamboju@linaro.org>
    Cc: Sudip Mukherjee (Codethink) <sudipm.mukherjee@gmail.com>
    Link: https://lore.kernel.org/r/20220824024216.4939-1-rdunlap@infradead.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>