openvswitch: Fix build failure.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [net] openvswitch: Fix build failure (Jiri Benc) [1156461 1211348]
Rebuild_FUZZ: 98.36%
commit-author Pravin B Shelar <pshelar@nicira.com>
commit 8cd4313aa775537f724486d5b7503b4d46c9f012
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/8cd4313a.failed

Add dependency on INET to fix following build error. I have also
fixed MPLS dependency.

ERROR: "ip_route_output_flow" [net/openvswitch/openvswitch.ko]
undefined!
make[1]: *** [__modpost] Error 1

	Reported-by: Jim Davis <jim.epost@gmail.com>
	Signed-off-by: Pravin B Shelar <pshelar@nicira.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8cd4313aa775537f724486d5b7503b4d46c9f012)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/openvswitch/Kconfig