selftests/bpf: Fix xdp_synproxy compilation failure in 32-bit arch
Bugzilla: https://bugzilla.redhat.com/2137876

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit e4c9cf0ce8c413c2030e8fb215551d7e0582ee7b
Author: Yang Jihong <yangjihong1@huawei.com>
Date:   Fri Nov 11 11:08:36 2022 +0800

    selftests/bpf: Fix xdp_synproxy compilation failure in 32-bit arch

    xdp_synproxy fails to be compiled in the 32-bit arch, log is as follows:

      xdp_synproxy.c: In function 'parse_options':
      xdp_synproxy.c:175:36: error: left shift count >= width of type [-Werror=shift-count-overflow]
        175 |                 *tcpipopts = (mss6 << 32) | (ttl << 24) | (wscale << 16) | mss4;
            |                                    ^~
      xdp_synproxy.c: In function 'syncookie_open_bpf_maps':
      xdp_synproxy.c:289:28: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
        289 |                 .map_ids = (__u64)map_ids,
            |                            ^

    Fix it.

    Fixes: fb5cd0ce70d4 ("selftests/bpf: Add selftests for raw syncookie helpers")
    Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20221111030836.37632-1-yangjihong1@huawei.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>