rtlwifi: initialize local array and set value.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [wireless] rtlwifi: initialize local array and set value (Prarit Bhargava) [1006333]
Rebuild_FUZZ: 98.90%
commit-author Yunlian Jiang <yunlian@google.com>
commit ec71997eff2231098212a99934c0fb987a9e6b04

GCC 4.8 is spitting out uninitialized-variable warnings against
"drivers/net/wireless/rtlwifi/rtl8192de/dm.c".

drivers/net/wireless/rtlwifi/rtl8192de/dm.c:941:31:
error: 'ofdm_index_old[1]' may be used uninitialized in this
function [-Werror=maybe-uninitialized]
     rtlpriv->dm.ofdm_index[i] = ofdm_index_old[i];

This patch adds initialization to the variable and properly sets its value.

	Signed-off-by: Yunlian Jiang <yunlian@google.com>
	Acked-by: Larry Finger <Larry.Finger@lwfinger.net>
	Signed-off-by: John W. Linville <linville@tuxdriver.com>
(cherry picked from commit ec71997eff2231098212a99934c0fb987a9e6b04)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>