ASoC: sunxi: rename SND_SUNXI_ADDA_PR_REGMAP to SND_SUN8I_ADDA_PR_REGMAP
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: sunxi: rename SND_SUNXI_ADDA_PR_REGMAP to SND_SUN8I_ADDA_PR_REGMAP (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 96.00%
commit-author Vasily Khoruzhick <anarsoul@gmail.com>
commit 2f5d94123ce3c12a1e15802e6d5ee98f304ccb71

SND_SUN50I_CODEC_ANALOG selects SND_SUNXI_ADDA_PR_REGMAP which is leftover
of renaming SND_SUNXI_ADDA_PR_REGMAP to SND_SUN8I_ADDA_PR_REGMAP. Replace
it with SND_SUN8I_ADDA_PR_REGMAP to fix possible link errors for some
configurations:

sound/soc/sunxi/sun50i-codec-analog.o: In function `sun50i_codec_analog_probe':
sun50i-codec-analog.c:(.text+0x62): undefined reference to `sun8i_adda_pr_regmap_init'

Fixes: 42371f327df0 ("ASoC: sunxi: Add new driver for Allwinner A64 codec's analog path controls")
	Signed-off-by: Vasily Khoruzhick <anarsoul@gmail.com>
	Reviewed-by: Andre Przywara <andre.przywara@arm.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2f5d94123ce3c12a1e15802e6d5ee98f304ccb71)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>