samples/bpf: Fix build error due to -isystem removal
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2072020
Upstream Status: v5.16-rc2

commit 6060a6cb05e3223146a3c30a1977f136da6c85e7
Author:     Alexander Lobakin <alexandr.lobakin@intel.com>
AuthorDate: Mon Nov 15 14:07:41 2021 +0100
Commit:     Alexei Starovoitov <ast@kernel.org>
CommitDate: Mon Nov 15 20:37:20 2021 -0800

    Since recent Kbuild updates we no longer include files from compiler
    directories. However, samples/bpf/hbm_kern.h hasn't been tuned for
    this (LLVM 13):

      CLANG-bpf  samples/bpf/hbm_out_kern.o
    In file included from samples/bpf/hbm_out_kern.c:55:
    samples/bpf/hbm_kern.h:12:10: fatal error: 'stddef.h' file not found
             ^~~~~~~~~~
    1 error generated.
      CLANG-bpf  samples/bpf/hbm_edt_kern.o
    In file included from samples/bpf/hbm_edt_kern.c:53:
    samples/bpf/hbm_kern.h:12:10: fatal error: 'stddef.h' file not found
             ^~~~~~~~~~
    1 error generated.

    It is enough to just drop both stdbool.h and stddef.h from includes
    to fix those.

    Fixes: 04e85bbf71c9 ("isystem: delete global -isystem compile option")
    Signed-off-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Michal Swiatkowski <michal.swiatkowski@linux.intel.com>
    Link: https://lore.kernel.org/bpf/20211115130741.3584-1-alexandr.lobakin@intel.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>