ACPI / fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [acpi] fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined (Prarit Bhargava) [1174059]
Rebuild_FUZZ: 95.04%
commit-author Shuah Khan <shuah.kh@samsung.com>
commit b108e0ea94a33f85590959a7a7fbcfd6f8ea8ab6

The ACPI fan driver defines acpi_fan_suspend() and acpi_fan_resume()
when CONFIG_PM_SLEEP is defined. This results in the following compile
errors when CONFIG_PM_SLEEP is undefined:

drivers/acpi/fan.c:60:8: error: ‘acpi_fan_suspend’ undeclared here (not in a function)
drivers/acpi/fan.c:60:8: error: ‘acpi_fan_resume’ undeclared here (not in a function)

	Signed-off-by: Shuah Khan <shuah.kh@samsung.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit b108e0ea94a33f85590959a7a7fbcfd6f8ea8ab6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>