octeontx2-pf: Fix unused variable build error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2040643

commit 54b9a2bb6c013a34cfdb5a6241367b003773662f
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Mon Sep 19 10:58:40 2022 +0800

    octeontx2-pf: Fix unused variable build error

    If CONFIG_DCB is not set,
    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-,
    will be failed, like this:

    drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c: In function ‘otx2_select_queue’:
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c:1886:19: error: unused variable ‘pf’ [-Werror=unused-variable]
      struct otx2_nic *pf = netdev_priv(netdev);
                       ^~
    cc1: all warnings being treated as errors

    To fix this build error, put the definition of *pf under the CONFIG_DCB.

    Fixes: 99c969a83d82 ("octeontx2-pf: Add egress PFC support")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Link: https://lore.kernel.org/r/20220919025840.256411-1-renzhijie2@huawei.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>