ASoC: SOF: build compression interface into snd_sof.ko
With CONFIG_SND_SOC_SOF_COMPRESS=m, the compression code is
not built into a the main SOF driver when that is built-in:

x86_64-linux-ld: sound/soc/sof/ipc.o: in function `ipc_stream_message':
ipc.c:(.text+0x5a2): undefined reference to `snd_sof_compr_fragment_elapsed'
x86_64-linux-ld: sound/soc/sof/topology.o: in function `sof_dai_load':
topology.c:(.text+0x32d1): undefined reference to `snd_sof_compr_init_elapsed_work'
x86_64-linux-ld: topology.c:(.text+0x32e1): undefined reference to `snd_sof_compr_init_elapsed_work'

Make this a 'bool' symbol so it just decides whether the
code gets built at all.

    Fixes: 858f7a5c45ca ("ASoC: SOF: Introduce fragment elapsed notification API")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Tested-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20211108111132.3800548-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Nov 8 12:11:14 2021 +0100

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 1218f06cb3c6e2c51699998bc17c0d9a41ab37a6)
Bugzilla: https://bugzilla.redhat.com/2017320