perf probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [tools] perf/probe: Do not use dwfl_module_addrsym if dwarf_diename finds symbol name (Jiri Olsa) [1169436]
Rebuild_FUZZ: 98.70%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 664fee3dc37939bb8010906913fa9dbc52abb587

Do not use dwfl_module_addrsym if dwarf_diename can find the symbol
name, since dwfl_module_addrsym can be failed on shared libraries.

Without this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Failed to find symbol at 0x11df1
  Failed to find the address of create_arg_op
    Error: Failed to show vars.
  ----
With this patch
  ----
  $ perf probe -x ../lib/traceevent/libtraceevent.so -V create_arg_op
  Available variables at create_arg_op
          @<create_arg_op+0>
                  enum filter_op_type     btype
                  struct filter_arg*      arg
  ----

This bug was reported on linux-perf-users@vger.kernel.org.

	Reported-by: david lerner <dlernerdroid@gmail.com>
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: david lerner <dlernerdroid@gmail.com>
	Cc: linux-perf-user@vger.kernel.org
	Cc: yrl.pp-manager.tt@hitachi.com
Link: http://permalink.gmane.org/gmane.linux.kernel.perf.user/1691
Link: http://lkml.kernel.org/r/20140917084101.3722.25299.stgit@kbuild-f20.novalocal
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 664fee3dc37939bb8010906913fa9dbc52abb587)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>