s390/netiucv: Make use of iucv_alloc_device()
JIRA: https://issues.redhat.com/browse/RHEL-50786
Upstream status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Tested: by IBM
Build-Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=65307356
Conflicts: None

commit 968bfb566dd193f912ccab47aaa50f3112f6f82d

    Make use of iucv_alloc_device() to get rid of quite some code. In addition
    this also removes a cast to an incompatible function (clang W=1):

    drivers/s390/net/netiucv.c:1716:18: error: cast from 'void (*)(const void *)' to 'void (*)(struct device *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
    1716 |                 dev->release = (void (*)(struct device *))kfree;
    |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Closes: https://lore.kernel.org/r/20240417-s390-drivers-fix-cast-function-type-v1-3-fd048c9903b0@kernel.org
    Acked-by: Alexandra Winter <wintera@linux.ibm.com>
    Link: https://lore.kernel.org/r/20240506194454.1160315-4-hca@linux.ibm.com
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Mete Durlu <mdurlu@redhat.com>