netfilter: nft_reject_bridge: Fix powerpc build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Guenter Roeck <linux@roeck-us.net>
commit c1207c049b204b0a96535dc5416aee331b51e0e1
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/c1207c04.failed

Fix:
net/bridge/netfilter/nft_reject_bridge.c:
In function 'nft_reject_br_send_v6_unreach':
net/bridge/netfilter/nft_reject_bridge.c:240:3:
	error: implicit declaration of function 'csum_ipv6_magic'
   csum_ipv6_magic(&nip6h->saddr, &nip6h->daddr,
   ^
make[3]: *** [net/bridge/netfilter/nft_reject_bridge.o] Error 1

Seen with powerpc:allmodconfig.

Fixes: 523b929d5446 ("netfilter: nft_reject_bridge: don't use IP stack to reject traffic")
	Cc: Pablo Neira Ayuso <pablo@netfilter.org>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c1207c049b204b0a96535dc5416aee331b51e0e1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/bridge/netfilter/nft_reject_bridge.c