xfrm: kconfig: make xfrm depend on inet
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Florian Westphal <fw@strlen.de>
commit e54d1527658f2226c1f63d6fb76fa9b97d1c3947

when CONFIG_INET is not enabled:
net/xfrm/xfrm_output.c: In function ‘xfrm4_tunnel_encap_add’:
net/xfrm/xfrm_output.c:234:2: error: implicit declaration of function ‘ip_select_ident’ [-Werror=implicit-function-declaration]
ip_select_ident(dev_net(dst->dev), skb, NULL);

XFRM only supports ipv4 and ipv6 so change dependency to INET and place
user-visible options (pfkey sockets, migrate support and the like)
under 'if INET' guard as well.

Fixes: 1de70830066b7 ("xfrm: remove output2 indirection from xfrm_mode")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Florian Westphal <fw@strlen.de>
	Acked-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>
(cherry picked from commit e54d1527658f2226c1f63d6fb76fa9b97d1c3947)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>