kexec: fix build error when hugetlbfs is disabled
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author David Rientjes <rientjes@google.com>
commit 3a1122d26c62d4e8c61ef9a0eaba6e21c0862c77
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-229.el7/3a1122d2.failed

free_huge_page() is undefined without CONFIG_HUGETLBFS and there's no
need to filter PageHuge() page is such a configuration either, so avoid
exporting the symbol to fix a build error:

   In file included from kernel/kexec.c:14:0:
   kernel/kexec.c: In function 'crash_save_vmcoreinfo_init':
   kernel/kexec.c:1623:20: error: 'free_huge_page' undeclared (first use in this function)
     VMCOREINFO_SYMBOL(free_huge_page);
                       ^

Introduced by commit 8f1d26d0e59b ("kexec: export free_huge_page to
VMCOREINFO")

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Acked-by: Olof Johansson <olof@lixom.net>
	Cc: Atsushi Kumagai <kumagai-atsushi@mxc.nes.nec.co.jp>
	Cc: Baoquan He <bhe@redhat.com>
	Cc: Vivek Goyal <vgoyal@redhat.com>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: David Rientjes <rientjes@google.com>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 3a1122d26c62d4e8c61ef9a0eaba6e21c0862c77)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	kernel/kexec.c