perf tools: Fix documentation of verbose options
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Ian Rogers <irogers@google.com>
commit b55ff1d1456c86209ba28fd06b1b5fb0e05d92c3

Option doesn't take a value, make sure the man pages agree. For example:

  $ perf evlist --verbose=1
   Error: option `verbose' takes no value

	Signed-off-by: Ian Rogers <irogers@google.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Stephane Eranian <eranian@google.com>
Link: http://lore.kernel.org/lkml/20210226183145.1878782-1-irogers@google.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit b55ff1d1456c86209ba28fd06b1b5fb0e05d92c3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>