net: core: Fix build with CONFIG_IPV6=m
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Joe Stringer <joe@wand.net.nz>
commit d71019b54bff4b8f52903e354bf3b8cb2b4dfa75
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-147.el8/d71019b5.failed

Stephen Rothwell reports the following link failure with IPv6 as module:

  x86_64-linux-gnu-ld: net/core/filter.o: in function `sk_lookup':
  (.text+0x19219): undefined reference to `__udp6_lib_lookup'

Fix the build by only enabling the IPv6 socket lookup if IPv6 support is
compiled into the kernel.

	Signed-off-by: Joe Stringer <joe@wand.net.nz>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit d71019b54bff4b8f52903e354bf3b8cb2b4dfa75)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/core/filter.c