arch/arm64/mm/fault: Fix undeclared variable error in do_page_fault()
JIRA: https://issues.redhat.com/browse/RHEL-27742

This patch is a backport of the following upstream commit:
commit 24be4d0b46bb0c3c1dc7bacd30957d6144a70dfc
Author: SeongJae Park <sj@kernel.org>
Date:   Tue Jul 4 01:00:03 2023 +0000

    arch/arm64/mm/fault: Fix undeclared variable error in do_page_fault()

    Commit ae870a68b5d1 ("arm64/mm: Convert to using
    lock_mm_and_find_vma()") made do_page_fault() to use 'vma' even if
    CONFIG_PER_VMA_LOCK is not defined, but the declaration is still in the
    ifdef.

    As a result, building kernel without the config fails with undeclared
    variable error as below:

        arch/arm64/mm/fault.c: In function 'do_page_fault':
        arch/arm64/mm/fault.c:624:2: error: 'vma' undeclared (first use in this function); did you mean 'vmap'?
          624 |  vma = lock_mm_and_find_vma(mm, addr, regs);
              |  ^~~
              |  vmap

    Fix it by moving the declaration out of the ifdef.

    Fixes: ae870a68b5d1 ("arm64/mm: Convert to using lock_mm_and_find_vma()")
    Signed-off-by: SeongJae Park <sj@kernel.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>