drm/amd/pm: avoid large variable on kernel stack
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2115902
Upstream Status: v6.0.16

commit 90dc730178456636dc026423c9938ddfd29812da
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Thu Dec 15 17:36:31 2022 +0100
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Sat Dec 31 13:26:50 2022 +0100

    [ Upstream commit d118b18fb1da02b41df2da78cb2794b3638d89cd ]

    The activity_monitor_external[] array is too big to fit on the
    kernel stack, resulting in this warning with clang:

    drivers/gpu/drm/amd/amdgpu/../pm/swsmu/smu13/smu_v13_0_7_ppt.c:1438:12: error: stack frame size (1040) exceeds limit (1024) in 'smu_v13_0_7_get_power_profile_mode' [-Werror,-Wframe-larger-than]

    Use dynamic allocation instead. It should also be possible to
    have single element here instead of the array, but this seems
    easier.

    v2: fix up argument to sizeof() (Alex)

    Fixes: 334682ae8151 ("drm/amd/pm: enable workload type change on smu_v13_0_7")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>