x86/entry: Add do_SYSENTER_32() prototype
jira LE-2015
Rebuild_History Non-Buildable kernel-5.14.0-427.42.1.el9_4
commit-author Arnd Bergmann <arnd@arndb.de>
commit f34f0d3c10eb4d3160fc6fe7a2482cb78d3b0c12

The 32-bit system call entry points can be called on both 32-bit
and 64-bit kernels, but on the former the declarations are hidden:

arch/x86/entry/common.c:238:24: error: no previous prototype for 'do_SYSENTER_32' [-Werror=missing-prototypes]

Move them all out of the #ifdef block to avoid the warnings.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
	Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
Link: https://lore.kernel.org/all/20230516193549.544673-12-arnd%40kernel.org
(cherry picked from commit f34f0d3c10eb4d3160fc6fe7a2482cb78d3b0c12)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>