ASoC: Intel: sst: Remove unused function sst_restore_shim64()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: sst: Remove unused function sst_restore_shim64() (Jaroslav Kysela) [1463624]
Rebuild_FUZZ: 95.31%
commit-author Matthias Kaehlcke <mka@chromium.org>
commit 9a075265c6dc040e2946d21f4f9d082495bd5460

Looks like the function has never been used since it was added by commit
b0d94acd634a ("ASoC: Intel: mrfld - add shim save restore"). Removing it
fixes the following warning when building with clang:

sound/soc/intel/atom/sst/sst.c:360:20: error: unused function
    'sst_restore_shim64' [-Werror,-Wunused-function]

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9a075265c6dc040e2946d21f4f9d082495bd5460)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>