KVM: PPC: Book3S: Fix compile error in XICS emulation
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [virt] kvm/ppc/Book3S: Fix compile error in XICS emulation (Veaceslav Falico) [1006938]
Rebuild_FUZZ: 94.23%
commit-author Paul Mackerras <paulus@samba.org>
commit 7bfa9ad55d691f2b836b576769b11eca2cf50816

Commit 8e44ddc3f3 ("powerpc/kvm/book3s: Add support for H_IPOLL and
H_XIRR_X in XICS emulation") added a call to get_tb() but didn't
include the header that defines it, and on some configs this means
book3s_xics.c fails to compile:

arch/powerpc/kvm/book3s_xics.c: In function ‘kvmppc_xics_hcall’:
arch/powerpc/kvm/book3s_xics.c:812:3: error: implicit declaration of function ‘get_tb’ [-Werror=implicit-function-declaration]

	Cc: stable@vger.kernel.org [v3.10, v3.11]
	Signed-off-by: Paul Mackerras <paulus@samba.org>
	Signed-off-by: Alexander Graf <agraf@suse.de>
(cherry picked from commit 7bfa9ad55d691f2b836b576769b11eca2cf50816)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>