s390/ptrace: add missing linux/const.h include
JIRA: https://issues.redhat.com/browse/RHEL-54248

commit 388acb471662c273d94163a8502f09668f380686
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Mon Jul 31 20:39:26 2023 +0200

    s390/ptrace: add missing linux/const.h include

    Adrian Reber reported the following CRIU build bug after
    commit b8af5999779d ("s390/ptrace: make all psw related
    defines also available for asm"):

    compel/arch/s390/src/lib/infect.c: In function 'arch_can_dump_task':
    compel/arch/s390/src/lib/infect.c:523:25: error: 'UL' undeclared (first use in this function)
      523 |         if (psw->mask & PSW_MASK_RI) {
          |                         ^~~~~~~~~~~

    Add the missing linux/const.h include to fix this.

    Reported-by: Adrian Reber <areber@redhat.com>
    Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2225745
    Link: https://github.com/checkpoint-restore/criu/pull/2232
    Tested-by: Adrian Reber <areber@redhat.com>
    Fixes: b8af5999779d ("s390/ptrace: make all psw related defines also available for asm")
    Link: https://lore.kernel.org/r/20230731183926.330932-1-hca@linux.ibm.com
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>