perf dso: Fix build when libunwind is enabled
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit 92717bc077892d1ce60fee07aee3a33f33909b85
Author: James Clark <james.clark@linaro.org>
Date: Mon Jul 15 10:47:13 2024 +0100

description
===========
Now that symsrc_filename is always accessed through an accessor, we also
need a free() function for it to avoid the following compilation error:

  util/unwind-libunwind-local.c:416:12: error: lvalue required as unary
    ‘&’ operand
  416 |      zfree(&dso__symsrc_filename(dso));

Fixes: 1553419c3c10 ("perf dso: Fix address sanitizer build")
    Signed-off-by: James Clark <james.clark@linaro.org>
    Reviewed-by: Ian Rogers <irogers@google.com>
    Tested-by: Leo Yan <leo.yan@arm.com>
    Tested-by: Florian Fainelli <florian.fainelli@broadcom.com>
    Cc: Yunseong Kim <yskelg@gmail.com>
    Cc: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
    Link: https://lore.kernel.org/r/20240715094715.3914813-1-james.clark@linaro.org
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>