sched/fair: Hide unused init_cfs_bandwidth() stub
JIRA: https://issues.redhat.com/browse/RHEL-1536
Conflicts: Context difference due to already having 88c56cfeaec4
    ("sched/fair: Block nohz tick_stop when cfs bandwidth in use").

commit c0bdfd72fbfb7319581bd5bb09b4f10979385bac
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon May 22 21:50:19 2023 +0200

    sched/fair: Hide unused init_cfs_bandwidth() stub

    init_cfs_bandwidth() is only used when CONFIG_FAIR_GROUP_SCHED is
    enabled, and without this causes a W=1 warning for the missing prototype:

    kernel/sched/fair.c:6131:6: error: no previous prototype for 'init_cfs_bandwidth'

    The normal implementation is only defined for CONFIG_CFS_BANDWIDTH,
    so the stub exists when CFS_BANDWIDTH is disabled but FAIR_GROUP_SCHED
    is enabled.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Vincent Guittot <vincent.guittot@linaro.org>
    Link: https://lore.kernel.org/r/20230522195021.3456768-4-arnd@kernel.org

Signed-off-by: Phil Auld <pauld@redhat.com>