tools: ynl: Remove absolute paths to yaml files from ethtool testing tool
JIRA: https://issues.redhat.com/browse/RHEL-30656

commit 3ea31e66644b263f43850174847956fbbe2c28cf
Author: Rahul Rameshbabu <rrameshbabu@nvidia.com>
Date:   Wed Apr 12 18:22:51 2023 -0700

    tools: ynl: Remove absolute paths to yaml files from ethtool testing tool

    Absolute paths for the spec and schema files make the ethtool testing tool
    unusable with freshly checked-out source trees. Replace absolute paths with
    relative paths for both files in the Documentation/ directory.

    Issue seen before the change

      Traceback (most recent call last):
        File "/home/binary-eater/Documents/mlx/linux/tools/net/ynl/./ethtool", line 424, in <module>
          main()
        File "/home/binary-eater/Documents/mlx/linux/tools/net/ynl/./ethtool", line 158, in main
          ynl = YnlFamily(spec, schema)
        File "/home/binary-eater/Documents/mlx/linux/tools/net/ynl/lib/ynl.py", line 342, in __init__
          super().__init__(def_path, schema)
        File "/home/binary-eater/Documents/mlx/linux/tools/net/ynl/lib/nlspec.py", line 333, in __init__
          with open(spec_path, "r") as stream:
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/sdf/src/linux/Documentation/netlink/specs/ethtool.yaml'

    Fixes: f3d07b02b2b8 ("tools: ynl: ethtool testing tool")
    Signed-off-by: Rahul Rameshbabu <rrameshbabu@nvidia.com>
    Link: https://lore.kernel.org/r/20230413012252.184434-1-rrameshbabu@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>