tools/power turbostat: Fix file pointer leak
Bugzilla: https://bugzilla.redhat.com/2117770

commit 5e5fd36c58d6c820f7292ee492c3731c9a104a41
Author: Colin Ian King <colin.king@intel.com>
Date:   Tue Apr 26 14:16:07 2022 +0100

    tools/power turbostat: Fix file pointer leak

    Currently if a fscanf fails then an early return leaks an open
    file pointer. Fix this by fclosing the file before the return.
    Detected using static analysis with cppcheck:

    tools/power/x86/turbostat/turbostat.c:2039:3: error: Resource leak: fp [resourceLeak]

    Fixes: eae97e053fe3 ("tools/power turbostat: Support thermal throttle count print")
    Signed-off-by: Colin Ian King <colin.i.king@gmail.com>
    Acked-by: Chen Yu <yu.c.chen@intel.com>
    Reviewed-by: Tom Rix <trix@redhat.com>
    Signed-off-by: Len Brown <len.brown@intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>