HID: amd_sfh: Set the AMD SFH driver to depend on x86
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.9
Tested: with the hid-tools test suite and some hardware

commit 90184f90c9ac559062a04aca72e5d05730164de0
Author: Basavaraj Natikar <Basavaraj.Natikar@amd.com>
Date:   Wed Feb 28 17:09:14 2024 +0530

    HID: amd_sfh: Set the AMD SFH driver to depend on x86

    Considering that amd_sfh exists only on AMD platforms, set the AMD SFH
    driver to depend on x86 to avoid build warnings or errors on other
    architectures, as shown below.

    drivers/hid/amd-sfh-hid/amd_sfh_pcie.c: In function 'amd_mp2_pci_probe':
    drivers/hid/amd-sfh-hid/amd_sfh_pcie.c:413:21: error: 'boot_cpu_data'
    undeclared (first use in this function); did you mean 'boot_cpu_hwid'?
      413 |                 if (boot_cpu_data.x86 >= 0x1A)
          |                     ^~~~~~~~~~~~~
          |                     boot_cpu_hwid

    Fixes: 6296562f30b1 ("HID: amd_sfh: Extend MP2 register access to SFH")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Closes: https://lore.kernel.org/all/20240228145648.41c493ec@canb.auug.org.au/
    Signed-off-by: Basavaraj Natikar <Basavaraj.Natikar@amd.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>