thunderbolt: test: split up test cases in tb_test_credit_alloc_all
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 4b93c544e90e2b28326182d31ee008eb80e02074
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Mon Sep 6 12:27:03 2021 -0700

    thunderbolt: test: split up test cases in tb_test_credit_alloc_all

    The tb_test_credit_alloc_all() function had a huge number of
    KUNIT_ASSERT() statements, all of which (though the magic of many many
    layers of inscrutable macros) ended up allocating and initializing
    various test assertion structures on the stack.

    Don't do that.  The kernel stack isn't infinite, and we have compiler
    warnings (now errors) for the case where a stack frame grows too large.

    Like it did here, by not an inconsiderable margin:

       drivers/thunderbolt/test.c: In function ‘tb_test_credit_alloc_all’:
       drivers/thunderbolt/test.c:2367:1: error: the frame size of 4500 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
        2367 | }
             | ^

    Solve this similarly to the lib/test_scanf case: split out the tests
    into several smaller functions, each just testing one particular tunnel
    credit allocation.

    This makes the i386 allyesconfig build work for me again.

    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>