rdma/siw: Add missing dependencies on LIBCRC32C and DMA_VIRT_OPS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit b45305d777f2f9209dae5a3b8249ca03166a4df3
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-193.el8/b45305d7.failed

If LIBCRC32C and DMA_VIRT_OPS are not enabled:

    drivers/infiniband/sw/siw/siw_main.o: In function `siw_newlink':
    siw_main.c:(.text+0x35c): undefined reference to `dma_virt_ops'
    drivers/infiniband/sw/siw/siw_qp_rx.o: In function `siw_csum_update':
    siw_qp_rx.c:(.text+0x16): undefined reference to `crc32c'

Fix the first issue by adding a select of DMA_VIRT_OPS.  Fix the second
issue by replacing the unneeded dependency on CRYPTO_CRC32 by a dependency
on LIBCRC32C.

	Reported-by: noreply@ellerman.id.au (first issue)
Fixes: c0cf5bdde46c ("rdma/siw: addition to kernel build environment")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Reviewed-by: Jason Gunthorpe <jgg@mellanox.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit b45305d777f2f9209dae5a3b8249ca03166a4df3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/infiniband/sw/siw/Kconfig