drivers/perf: arm-cci: Fix checkpatch spacing error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Junhao He <hejunhao2@hisilicon.com>
commit eb2b22f024c3615d576cead56f2a7d2c90355716

Fix some coding style issues reported by checkpatch.pl, including
following types:

ERROR: need consistent spacing around '-' (ctx:WxV)
ERROR: space required before the open parenthesis '('

	Signed-off-by: Junhao He <hejunhao2@hisilicon.com>
	Signed-off-by: Jay Fang <f.fangjian@huawei.com>
Link: https://lore.kernel.org/r/1620736054-58412-5-git-send-email-f.fangjian@huawei.com
	Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit eb2b22f024c3615d576cead56f2a7d2c90355716)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>