sfc: siena: Fix Kconfig dependencies
Bugzilla: https://bugzilla.redhat.com/2112206

commit f9a210c72d70c9a59cf989fb23fb01ff10d18136
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Fri May 13 09:27:21 2022 +0800

    sfc: siena: Fix Kconfig dependencies
    
    If CONFIG_PTP_1588_CLOCK=m and CONFIG_SFC_SIENA=y, the siena driver will fail to link:
    
    drivers/net/ethernet/sfc/siena/ptp.o: In function `efx_ptp_remove_channel':
    ptp.c:(.text+0xa28): undefined reference to `ptp_clock_unregister'
    drivers/net/ethernet/sfc/siena/ptp.o: In function `efx_ptp_probe_channel':
    ptp.c:(.text+0x13a0): undefined reference to `ptp_clock_register'
    ptp.c:(.text+0x1470): undefined reference to `ptp_clock_unregister'
    drivers/net/ethernet/sfc/siena/ptp.o: In function `efx_ptp_pps_worker':
    ptp.c:(.text+0x1d29): undefined reference to `ptp_clock_event'
    drivers/net/ethernet/sfc/siena/ptp.o: In function `efx_siena_ptp_get_ts_info':
    ptp.c:(.text+0x301b): undefined reference to `ptp_clock_index'
    
    To fix this build error, make SFC_SIENA depends on PTP_1588_CLOCK.
    
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: d48523cb88e0 ("sfc: Copy shared files needed for Siena (part 2)")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Acked-by: Martin Habets <habetsm.xilinx@gmail.com>
    Link: https://lore.kernel.org/r/20220513012721.140871-1-renzhijie2@huawei.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>