tcp: Fix build break when CONFIG_IPV6=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-481.el8
commit-author Saeed Mahameed <saeedm@nvidia.com>
commit c90b6b1005ec7423c7d0063eb27a9728498f6ec8

The cited commit caused the following build break when CONFIG_IPV6 was
disabled

net/ipv4/tcp_input.c: In function ‘tcp_syn_flood_action’:
include/net/sock.h:387:37: error: ‘const struct sock_common’ has no member named ‘skc_v6_rcv_saddr’; did you mean ‘skc_rcv_saddr’?

Fix by using inet6_rcv_saddr() macro which handles this situation
nicely.

Fixes: d9282e48c608 ("tcp: Add listening address to SYN flood message")
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
	Reported-by: Geert Uytterhoeven <geert+renesas@glider.be>
CC: Matthieu Baerts <matthieu.baerts@tessares.net>
CC: Jamie Bainbridge <jamie.bainbridge@gmail.com>
	Reviewed-by: Eric Dumazet <edumazet@google.com>
Link: https://lore.kernel.org/r/20221122184158.170798-1-saeed@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit c90b6b1005ec7423c7d0063eb27a9728498f6ec8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>