mac80211: minstrel_ht: remove unused n_supported variable
Bugzilla: https://bugzilla.redhat.com/2196821

commit 968a768d28530cadd13aab51531f8fec70bf9eae
Author: Tom Rix <trix@redhat.com>
Date:   Sat Mar 25 09:26:10 2023 -0400

    mac80211: minstrel_ht: remove unused n_supported variable
    
    clang with W=1 reports
    net/mac80211/rc80211_minstrel_ht.c:1711:6: error: variable
      'n_supported' set but not used [-Werror,-Wunused-but-set-variable]
            int n_supported = 0;
                ^
    This variable is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Link: https://lore.kernel.org/r/20230325132610.1334820-1-trix@redhat.com
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>