bpf_doc: Fix build error with older python versions
Bugzilla: https://bugzilla.redhat.com/2177177

commit 5fbea42387eba1c7517fcad79099df706def7054
Author: Michal Suchanek <msuchanek@suse.de>
Date:   Mon Jan 9 12:34:42 2023 +0100

    bpf_doc: Fix build error with older python versions

    The ability to subscript match result as an array is only available
    since python 3.6. Existing code in bpf_doc uses the older group()
    interface but commit 8a76145a2ec2 adds code using the new interface.

    Use the old interface consistently to avoid build error on older
    distributions like the below:

    + make -j48 -s -C /dev/shm/kbuild/linux.33946/current ARCH=powerpc HOSTCC=gcc CROSS_COMPILE=powerpc64-suse-linux- clean
    TypeError: '_sre.SRE_Match' object is not subscriptable

    Fixes: 8a76145a2ec2 ("bpf: explicitly define BPF_FUNC_xxx integer values")
    Signed-off-by: Michal Suchanek <msuchanek@suse.de>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Quentin Monnet <quentin@isovalent.com>
    Link: https://lore.kernel.org/bpf/20230109113442.20946-1-msuchanek@suse.de

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>