perf probe: Add warning message if there is unexpected event name
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit 9f5c6d8777a2d962b0eeacb2a16f37da6bea545b

This improve the error message so that user can know event-name error
before writing new events to kprobe-events interface.

E.g.
   ======
   #./perf probe -x /lib64/libc-2.25.so malloc_get_state*
   Internal error: "malloc_get_state@GLIBC_2" is an invalid event name.
     Error: Failed to add events.
   ======

	Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Acked-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
	Reviewed-by: Thomas Richter <tmricht@linux.vnet.ibm.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: bhargavb <bhargavaramudu@gmail.com>
	Cc: linux-rt-users@vger.kernel.org
Link: http://lkml.kernel.org/r/151275040665.24652.5188568529237584489.stgit@devbox
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 9f5c6d8777a2d962b0eeacb2a16f37da6bea545b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>