selftest/tcp-ao: Rectify out-of-tree build
JIRA: https://redhat.atlassian.net/browse/RHEL-142637
Upstream Status: net.git commit 826eb9bcc1844990e3c4a7c84846f1c1eaee0ed0

commit 826eb9bcc1844990e3c4a7c84846f1c1eaee0ed0
Author: Dmitry Safonov <0x7f454c46@gmail.com>
Date:   Tue Dec 19 02:03:05 2023 +0000

    selftest/tcp-ao: Rectify out-of-tree build

    Trivial fix for out-of-tree build that I wasn't testing previously:

    1. Create a directory for library object files, fixes:
    > gcc lib/kconfig.c -Wall -O2 -g -D_GNU_SOURCE -fno-strict-aliasing -I ../../../../../usr/include/ -iquote /tmp/kselftest/kselftest/net/tcp_ao/lib -I ../../../../include/  -o /tmp/kselftest/kselftest/net/tcp_ao/lib/kconfig.o -c
    > Assembler messages:
    > Fatal error: can't create /tmp/kselftest/kselftest/net/tcp_ao/lib/kconfig.o: No such file or directory
    > make[1]: *** [Makefile:46: /tmp/kselftest/kselftest/net/tcp_ao/lib/kconfig.o] Error 1

    2. Include $(KHDR_INCLUDES) that's exported by selftests/Makefile, fixes:
    > In file included from lib/kconfig.c:6:
    > lib/aolib.h:320:45: warning: ‘struct tcp_ao_add’ declared inside parameter list will not be visible outside of this definition or declaration
    >   320 | extern int test_prepare_key_sockaddr(struct tcp_ao_add *ao, const char *alg,
    >       |                                             ^~~~~~~~~~
    ...

    3. While at here, clean-up $(KSFT_KHDR_INSTALL): it's not needed anymore
       since commit f2745dc0ba3d ("selftests: stop using KSFT_KHDR_INSTALL")

    4. Also, while at here, drop .DEFAULT_GOAL definition: that has a
       self-explaining comment, that was valid when I made these selftests
       compile on local v4.19 kernel, but not needed since
       commit 8ce72dc32578 ("selftests: fix headers_install circular dependency")

    Fixes: cfbab37b3da0 ("selftests/net: Add TCP-AO library")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202312190645.q76MmHyq-lkp@intel.com/
    Signed-off-by: Dmitry Safonov <dima@arista.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>