ath11k: Fix build warning without CONFIG_IPV6
Bugzilla: https://bugzilla.redhat.com/2136122

commit 67888630addeaa2ae1c04d8d020daccbd26d05d9
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Mon Apr 11 10:08:43 2022 +0800

    ath11k: Fix build warning without CONFIG_IPV6
    
    drivers/net/wireless/ath/ath11k/mac.c:8175:13: error: ‘ath11k_mac_op_ipv6_changed’ defined but not used [-Werror=unused-function]
     static void ath11k_mac_op_ipv6_changed(struct ieee80211_hw *hw,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Wrap it with #ifdef block to fix this.
    
    Fixes: c3c36bfe998b ("ath11k: support ARP and NS offload")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20220411020843.10284-1-yuehaibing@huawei.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>