ALSA: oss: avoid missing-prototype warnings
Bugzilla: https://bugzilla.redhat.com/2179848

commit 040b5a046a9e18098580d3ccd029e2318fca7859
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue May 16 21:50:42 2023 +0200

    ALSA: oss: avoid missing-prototype warnings

    Two functions are defined and used in pcm_oss.c but also optionally
    used from io.c, with an optional prototype. If CONFIG_SND_PCM_OSS_PLUGINS
    is disabled, this causes a warning as the functions are not static
    and have no prototype:

    sound/core/oss/pcm_oss.c:1235:19: error: no previous prototype for 'snd_pcm_oss_write3' [-Werror=missing-prototypes]
    sound/core/oss/pcm_oss.c:1266:19: error: no previous prototype for 'snd_pcm_oss_read3' [-Werror=missing-prototypes]

    Avoid this by making the prototypes unconditional.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230516195046.550584-2-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>