soc: imx: imx8mp-blk-ctrl: Fix typo of imx8m_blk_ctrl_of_match
Bugzilla: https://bugzilla.redhat.com/2182875

commit d77369ad8cb10bedd244e6dfd8414ebdd8594ba6
Author: Jindong Yue <jindong.yue@nxp.com>
Date:   Wed Mar 1 21:05:52 2023 +0800

    soc: imx: imx8mp-blk-ctrl: Fix typo of imx8m_blk_ctrl_of_match

    Once set CONFIG_SOC_IMX8M as m, following error occurs:

    drivers/soc/imx/imx8mp-blk-ctrl.c:747:25: error: ‘imx8m_blk_ctrl_of_match’
    undeclared here (not in a function); did you mean ‘imx8mp_blk_ctrl_of_match’?
      747 | MODULE_DEVICE_TABLE(of, imx8m_blk_ctrl_of_match);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~

    Fix the typo.

    Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    Reviewed-by: Marco Felsch <m.felsch@pengutronix.de>
    Signed-off-by: Shawn Guo <shawnguo@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>