ALSA: atmel: Fix possible array overflow
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Takashi Iwai <tiwai@suse.de>
commit e4de211cd31665c167351a428e08199ee6355e46

The static checker found a possible array overflow in atmel/abdac.c:
  static checker warning: "sound/atmel/abdac.c:373 set_sample_rates()
        error: buffer overflow 'dac->rates' 6 <= 6"

This patch papers over the buggy point, by ensuring that dac->rates[]
update not overflowing the actual array size.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit e4de211cd31665c167351a428e08199ee6355e46)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>