media: uvcvideo: Invert default value for nodrop module param
JIRA: https://issues.redhat.com/browse/RHEL-78837

commit 52fbe173baa4df9d14bd733f42ee6b9ceab8299b
Author: Ricardo Ribalda <ribalda@chromium.org>
Date: Wed, 18 Dec 2024 21:39:09 +0000

  The module param `nodrop` defines what to do with frames that contain an
  error: drop them or sending them to userspace.

  The default in the rest of the media subsystem is to return buffers with
  an error to userspace with V4L2_BUF_FLAG_ERROR set in v4l2_buffer.flags.
  In UVC we drop buffers with errors by default.

  Change the default behaviour of uvcvideo to match the rest of the
  drivers and maybe get rid of the module parameter in the future.

  Suggested-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
  Reviewed-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Reviewed-by: Hans de Goede <hdegoede@redhat.com>
  Link: https://lore.kernel.org/r/20241218-uvc-deprecate-v2-2-ab814139e983@chromium.org
  Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>