audit: cleanup function braces and assignment-in-if-condition
JIRA: https://issues.redhat.com/browse/RHEL-9127

This patch is a backport of the following upstream commit:
commit 22cde1012f6a6509656f976cbe3aa5f4c5d0f1a3
Author: Atul Kumar Pant <atulpant.linux@gmail.com>
Date:   Wed Aug 16 02:16:44 2023 +0530

    audit: cleanup function braces and assignment-in-if-condition

    The patch fixes following checkpatch.pl issue:
    ERROR: open brace '{' following function definitions go on the next line
    ERROR: do not use assignment in if condition

    Signed-off-by: Atul Kumar Pant <atulpant.linux@gmail.com>
    [PM: subject line tweaks]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ricardo Robaina <rrobaina@redhat.com>