media: platform: amd: add DRM_AMDGPU dependency
JIRA: https://redhat.atlassian.net/browse/RHEL-162129
JIRA: https://redhat.atlassian.net/browse/RHEL-23291

commit e62bb5abdcc0dc57ff09c4db961784582e61cd9b
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 15 May 2026 11:12:06 +0200

  With DRM_AMDGPU=m and DRM_AMD_ISP=y, it is possible to configura
  VIDEO_AMD_ISP4_CAPTURE as built-in, but that fails to link:

  aarch64-linux-ld: drivers/media/platform/amd/isp4/isp4_interface.o: in function `isp4if_gpu_mem_alloc.isra.0':
  isp4_interface.c:(.text+0x1d0): undefined reference to `isp_kernel_buffer_alloc'
  aarch64-linux-ld: drivers/media/platform/amd/isp4/isp4_interface.o: in function `isp4if_dealloc_fw_gpumem':
  isp4_interface.c:(.text+0x26c): undefined reference to `isp_kernel_buffer_free'

  Add a dependency on the tristate DRM_AMDGPU symbol in addition to
  the boolean DRM_AMD_ISP=y, so this can only be built-in if
  the ISP driver is also linked into the kernel itself.

  Fixes: 9a54c285630c ("media: platform: amd: Introduce amd isp4 capture driver")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Bin Du <Bin.Du@amd.com>
  Tested-by: Bin Du <Bin.Du@amd.com>
  Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>

Signed-off-by: Kate Hsuan <hpa@redhat.com>