uas: fix GFP_NOIO under spinlock
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Oliver Neukum <oneukum@suse.de>
commit e7eda9329372f5e436e5a9291eb115eab0feae02

Quote Dan:

The patch e36e64930cff: "uas: Use GFP_NOIO rather then GFP_ATOMIC
where possible" from Nov 7, 2013, leads to the following static
checker warning:

        drivers/usb/storage/uas.c:806 uas_eh_task_mgmt()
        error: scheduling with locks held: 'spin_lock:lock'

Some other allocations under spinlock are not caught.
The fix essentially reverts e36e64930cffd94e1c37fdb82f35989384aa946b

	Signed-off-by: Oliver Neukum <oliver@neukum.org>
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Reviewed-by: Hans de Goede <hdegoede@redhat.com>
	Acked-by: Hans de Goede <hdegoede@redhat.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit e7eda9329372f5e436e5a9291eb115eab0feae02)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>