extcon: axp288: Add a depends on ACPI to the Kconfig entry
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [extcon] axp288: Add a depends on ACPI to the Kconfig entry (Lyude Paul) [1731110]
Rebuild_FUZZ: 92.59%
commit-author YueHaibing <yuehaibing@huawei.com>
commit fa3c098c2d52a268f6372fa053932e11f50cecb1

As Hans de Goede pointed, using this driver without ACPI
makes little sense, so add ACPI dependency to Kconfig entry
to fix a build error while CONFIG_ACPI is not set.

drivers/extcon/extcon-axp288.c: In function 'axp288_extcon_probe':
drivers/extcon/extcon-axp288.c:363:20: error: dereferencing pointer to incomplete type
    put_device(&adev->dev);

Fixes: 0cf064db948a ("extcon: axp288: Convert to use acpi_dev_get_first_match_dev()")
	Reported-by: Hulk Robot <hulkci@huawei.com>
	Suggested-by: Hans de Goede <hdegoede@redhat.com>
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Reviewed-by: Hans de Goede <hdegoede@redhat.com>
	Reviewed-by: Mukesh Ojha <mojha@codeaurora.org>
	Signed-off-by: Chanwoo Choi <cw00.choi@samsung.com>
(cherry picked from commit fa3c098c2d52a268f6372fa053932e11f50cecb1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>