ASoC: ak4375: Fix unused function error
A randconfig caught a compile warning that is now treated as a fatal
error:
  sound/soc/codecs/ak4375.c:415:13: error: ‘ak4375_power_off’ defined but not used [-Werror=unused-function]

where ak4375_power_off() is used only from the PM handler.

As both suspend and resumes are already marked with __maybe_unused,
let's rip off the superfluous ifdef CONFIG_PM, so that the error above
can be avoided.

    Fixes: 53778b8292b5 ("ASoC: Add AK4375 support")
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Link: https://lore.kernel.org/r/20220105162409.20635-1-tiwai@suse.de
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Takashi Iwai <tiwai@suse.de>
Date: Wed Jan 5 17:24:09 2022 +0100

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit e4c35e75209bda13e57c9bc8d280366c2b9275a5)
Bugzilla: https://bugzilla.redhat.com/2065572