misc: rtsx: rename SG_END macro
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit f16ee7c7ec0fa5f0322bd64d5ee183a28ed1ec08

A change to the generic scatterlist code caused a conflict with
the rtsx card reader driver:

In file included from drivers/misc/cardreader/rtsx_pcr.c:32:
include/linux/rtsx_pci.h:40: error: "SG_END" redefined [-Werror]

This changes one instance of the driver to prefix SG_END and
related constants.

Fixes: 723fbf563a6a ("lib/scatterlist: Add SG_CHAIN and SG_END macros for LSB encodings")
	Cc: Anshuman Khandual <khandual@linux.vnet.ibm.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit f16ee7c7ec0fa5f0322bd64d5ee183a28ed1ec08)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>