bpf: Finish constification of 1st parameter of bpf_d_path()
JIRA: https://issues.redhat.com/browse/RHEL-78291

commit de7342228b7343774d6a9981c2ddbfb5e201044b
Author: Rong Tao <rongtao@cestc.cn>
Date:   Sat Oct 4 22:23:29 2025 +0800

    bpf: Finish constification of 1st parameter of bpf_d_path()
    
    The commit 1b8abbb12128 ("bpf...d_path(): constify path argument")
    constified the first parameter of the bpf_d_path(), but failed to
    update it in all places. Finish constification.
    
    Otherwise the selftest fail to build:
    .../selftests/bpf/bpf_experimental.h:222:12: error: conflicting types for 'bpf_path_d_path'
      222 | extern int bpf_path_d_path(const struct path *path, char *buf, size_t buf__sz) __ksym;
          |            ^
    .../selftests/bpf/tools/include/vmlinux.h:153922:12: note: previous declaration is here
     153922 | extern int bpf_path_d_path(struct path *path, char *buf, size_t buf__sz) __weak __ksym;
    
    Fixes: 1b8abbb12128 ("bpf...d_path(): constify path argument")
    Signed-off-by: Rong Tao <rongtao@cestc.cn>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Ines Qian <iqian@redhat.com>