ASoC: cs42l43: Initialize ret in default case in cs42l43_pll_ev()
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit a74048432fbb30e7a574747f6e1f47aef17010b0
Author: Nathan Chancellor <nathan@kernel.org>
Date: Wed Aug 23 09:32:50 2023 -0700

    ASoC: cs42l43: Initialize ret in default case in cs42l43_pll_ev()

    clang warns (or errors with CONFIG_WERROR=y):

      sound/soc/codecs/cs42l43.c:1371:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
       1371 |         default:
            |         ^~~~~~~
      sound/soc/codecs/cs42l43.c:1377:9: note: uninitialized use occurs here
       1377 |         return ret;
            |                ^~~
      sound/soc/codecs/cs42l43.c:1349:9: note: initialize the variable 'ret' to silence this warning
       1349 |         int ret;
            |                ^
            |                 = 0
      1 error generated.

    Initialize ret to 0 in the default case, as there was nothing to do for
    other event types.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/1922
    Fixes: fc918cbe874e ("ASoC: cs42l43: Add support for the cs42l43")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20230823-cs42l43_pll_ev-init-ret-v1-1-5836f1ad5dad@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>