can: softing: softing_startstop(): fix set but not used variable warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071839
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support.  This set updates the CAN driver subsystem.  This set has
 been tested on NXP imx8mm and NV Jetson Xavier NX via simple boot
 tests, using cansend/candump from can-utils to pass messages through
 a virtual CAN interface, and of course the CI loop.

commit 370d988cc529598ebaec6487d4f84c2115dc696b
Author: Marc Kleine-Budde <mkl@pengutronix.de>
Date:   Sat Jan 8 21:57:51 2022 +0100

    can: softing: softing_startstop(): fix set but not used variable warning

    In the function softing_startstop() the variable error_reporting is
    assigned but not used. The code that uses this variable is commented
    out. Its stated that the functionality is not finally verified.

    To fix the warning:

    | drivers/net/can/softing/softing_fw.c:424:9: error: variable 'error_reporting' set but not used [-Werror,-Wunused-but-set-variable]

    remove the comment, activate the code, but add a "0 &&" to the if
    expression and rely on the optimizer rather than the preprocessor to
    remove the code.

    Link: https://lore.kernel.org/all/20220109103126.1872833-1-mkl@pengutronix.de
    Fixes: 03fd3cf5a179 ("can: add driver for Softing card")
    Cc: Kurt Van Dijck <dev.kurt@vandijck-laurijssen.be>
    Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
        (cherry picked from commit 370d988cc529598ebaec6487d4f84c2115dc696b)

Signed-off-by: Al Stone <ahs3@redhat.com>