net: mana: Fix build errors when CONFIG_NET_SHAPER is disabled
JIRA: https://issues.redhat.com/browse/RHEL-131892

commit 11cd0206987205ee05b0abd70a8eafa400ba89e3
Author: Erni Sri Satya Vennela <ernis@linux.microsoft.com>
Date:   Wed Jun 25 04:35:55 2025 -0700

    net: mana: Fix build errors when CONFIG_NET_SHAPER is disabled

    Fix build errors when CONFIG_NET_SHAPER is disabled, including:

    drivers/net/ethernet/microsoft/mana/mana_en.c:804:10: error:
    'const struct net_device_ops' has no member named 'net_shaper_ops'

         804 |         .net_shaper_ops         = &mana_shaper_ops,

    drivers/net/ethernet/microsoft/mana/mana_en.c:804:35: error:
    initialization of 'int (*)(struct net_device *, struct neigh_parms *)'
    from incompatible pointer type 'const struct net_shaper_ops *'
    [-Werror=incompatible-pointer-types]

         804 |         .net_shaper_ops         = &mana_shaper_ops,

    Signed-off-by: Erni Sri Satya Vennela <ernis@linux.microsoft.com>
    Fixes: 75cabb46935b ("net: mana: Add support for net_shaper_ops")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202506230625.bfUlqb8o-lkp@intel.com/
    Reviewed-by: Simon Horman <horms@kernel.org>
    Link: https://patch.msgid.link/1750851355-8067-1-git-send-email-ernis@linux.microsoft.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>