smc_diag.h: fix include from userland
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Nicolas Dichtel <nicolas.dichtel@6wind.com>
commit ea6819e1f2d6c30624ea067f4b3a50a3cca79d8a
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/ea6819e1.failed

This patch prepares the uapi export by fixing the following error:

.../linux/smc_diag.h:6:27: fatal error: rdma/ib_verbs.h: No such file or directory
 #include <rdma/ib_verbs.h>

	Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
	Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
(cherry picked from commit ea6819e1f2d6c30624ea067f4b3a50a3cca79d8a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/rdma/ib_verbs.h
#	include/uapi/linux/smc_diag.h