bpf: Fix pointer cast warning
Bugzilla: http://bugzilla.redhat.com/2041365

commit 16c5900ba776c5acd6568abd60c40f948a96e496
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jul 21 23:19:45 2021 +0200

    bpf: Fix pointer cast warning

    kp->addr is a pointer, so it cannot be cast directly to a 'u64'
    when it gets interpreted as an integer value:

    kernel/trace/bpf_trace.c: In function '____bpf_get_func_ip_kprobe':
    kernel/trace/bpf_trace.c:968:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      968 |         return kp ? (u64) kp->addr : 0;

    Use the uintptr_t type instead.

    Fixes: 9ffd9f3ff719 ("bpf: Add bpf_get_func_ip helper for kprobe programs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20210721212007.3876595-1-arnd@kernel.org

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>