selftests/powerpc: make sub-folders buildable on their own
JIRA: https://issues.redhat.com/browse/RHEL-74480

commit 108e5e683333615023265a9a73a29d4c2fa16c70
Author: Madhavan Srinivasan <maddy@linux.ibm.com>
Date:   Thu Feb 29 15:07:11 2024 +0530

    selftests/powerpc: make sub-folders buildable on their own

    Build breaks when executing make with run_tests for sub-folders
    under powerpc. This is because, CFLAGS and GIT_VERSION macros are
    defined in Makefile of toplevel powerpc folder.

      make: Entering directory '/home/maddy/linux/tools/testing/selftests/powerpc/mm'
      gcc     hugetlb_vs_thp_test.c ../harness.c ../utils.c  -o /home/maddy/selftest_output//hugetlb_vs_thp_test
      hugetlb_vs_thp_test.c:6:10: fatal error: utils.h: No such file or directory
          6 | #include "utils.h"
            |          ^~~~~~~~~
      compilation terminated.

    Fix this by adding the flags.mk in each sub-folder Makefile. Also remove
    the CFLAGS and GIT_VERSION macros from powerpc/ folder Makefile since
    the same is definied in flags.mk

    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/20240229093711.581230-3-maddy@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>