ALSA: hdspm: remove unused copy_u32_le function
Bugzilla: https://bugzilla.redhat.com/2179848

commit 2c7598903f18418aa18d11a9dd081acb22e9e108
Author: Tom Rix <trix@redhat.com>
Date: Thu Mar 23 16:27:13 2023 -0400

    ALSA: hdspm: remove unused copy_u32_le function

    clang with W=1 reports
    sound/pci/rme9652/hdspm.c:6149:19: error: unused function
      'copy_u32_le' [-Werror,-Wunused-function]
    static inline int copy_u32_le(void __user *dest, void __iomem *src)
                      ^
    This function is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230323202713.2637150-1-trix@redhat.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>