libperf: Fix 32-bit build for tests uint64_t printf
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Rob Herring <robh@kernel.org>
commit 096972f5588dbac741f7f0cc057c84d895d4d80f

Commit a7f3713f6bf207e6 ("libperf tests: Add test_stat_multiplexing test")
added printf's of 64-bit ints using %lu which doesn't work on 32-bit
builds:

  tests/test-evlist.c:529:29: error: format ‘%lu’ expects argument of type \
    ‘long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]

Use PRIu64 instead which works on both 32-bit and 64-bit systems.

Fixes: a7f3713f6bf207e6 ("libperf tests: Add test_stat_multiplexing test")
	Signed-off-by: Rob Herring <robh@kernel.org>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Shunsuke Nakamura <nakamura.shun@fujitsu.com>
Link: https://lore.kernel.org/r/20220201213903.699656-1-robh@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 096972f5588dbac741f7f0cc057c84d895d4d80f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>