ASoC: amd: acp: select SND_SOC_AMD_ACP_LEGACY_COMMON for ACP63
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit a65cdffbef7bfdb9f55a3acb07ccf18d4f97b3a5
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Oct 27 17:23:54 2023 +0200

    ASoC: amd: acp: select SND_SOC_AMD_ACP_LEGACY_COMMON for ACP63

    Without this dependency, acp63 fails to link:

    x86_64-linux-ld: sound/soc/amd/acp/acp63.o: in function `acp63_audio_remove':
    acp63.c:(.text+0x22): undefined reference to `acp_disable_interrupts'
    x86_64-linux-ld: sound/soc/amd/acp/acp63.o: in function `acp63_i2s_master_clock_generate.isra.0':
    acp63.c:(.text+0x6f): undefined reference to `smn_read'
    x86_64-linux-ld: acp63.c:(.text+0x81): undefined reference to `smn_write'
    x86_64-linux-ld: acp63.c:(.text+0x8e): undefined reference to `smn_read'
    x86_64-linux-ld: sound/soc/amd/acp/acp63.o: in function `acp63_pcm_resume':
    acp63.c:(.text+0x230): undefined reference to `restore_acp_i2s_params'
    x86_64-linux-ld: acp63.c:(.text+0x23d): undefined reference to `restore_acp_pdm_params'
    x86_64-linux-ld: sound/soc/amd/acp/acp63.o: in function `acp63_audio_probe':
    acp63.c:(.text+0x474): undefined reference to `acp_enable_interrupts'

    Fixes: d4c2d5391d7e ("ASoC: amd: acp: add Kconfig options for acp6.3 based platform driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231027152403.386257-3-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>