dmaengine: make QCOM_HIDMA depend on HAS_IOMEM
JIRA: https://issues.redhat.com/browse/RHEL-10097
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 2437d5ea2191f3059246a1a7ac6fc4c8cc004dec
Author: Baoquan He <bhe@redhat.com>
Date:   Sat May 6 19:16:28 2023 +0800

    dmaengine: make QCOM_HIDMA depend on HAS_IOMEM

    On s390 systems (aka mainframes), it has classic channel devices for
    networking and permanent storage that are currently even more common
    than PCI devices. Hence it could have a fully functional s390 kernel
    with CONFIG_PCI=n, then the relevant iomem mapping functions
    [including ioremap(), devm_ioremap(), etc.] are not available.

    Here let QCOM_HIDMA depend on HAS_IOMEM so that it won't be built to
    cause below compiling error if PCI is unset.

    --------------------------------------------------------
    ld: drivers/dma/qcom/hidma.o: in function `hidma_probe':
    hidma.c:(.text+0x4b46): undefined reference to `devm_ioremap_resource'
    ld: hidma.c:(.text+0x4b9e): undefined reference to `devm_ioremap_resource'
    make[1]: *** [scripts/Makefile.vmlinux:35: vmlinux] Error 1
    make: *** [Makefile:1264: vmlinux] Error 2

    Signed-off-by: Baoquan He <bhe@redhat.com>
    Reviewed-by: Niklas Schnelle <schnelle@linux.ibm.com>
    Cc: Andy Gross <agross@kernel.org>
    Cc: Bjorn Andersson <andersson@kernel.org>
    Cc: Konrad Dybcio <konrad.dybcio@linaro.org>
    Cc: Vinod Koul <vkoul@kernel.org>
    Cc: linux-arm-msm@vger.kernel.org
    Cc: dmaengine@vger.kernel.org
    Reviewed-by: Dmitry Baryshkov <dmitry.baryshkov@gmail.com>
    Link: https://lore.kernel.org/r/20230506111628.712316-3-bhe@redhat.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

(cherry picked from commit 2437d5ea2191f3059246a1a7ac6fc4c8cc004dec)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>