iser-target: Fix non negative ERR_PTR isert_device_get usage
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Nicholas Bellinger <nab@linux-iscsi.org>
commit 373a4cd7378220d3c5a69fd369b1d78fee3207b2

As reported by Dan, isert_create_device_ib_res() failure within
isert_device_get() can potentially return a postive value,
resulting in ERR_PTR() triggering a NULL pointer dereference.

Caught by the static checker:

     drivers/infiniband/ulp/isert/ib_isert.c:423 isert_device_get()
     error: passing non negative 1 to ERR_PTR

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Cc: Sagi Grimberg <sagig@mellanox.com>
	Signed-off-by: Nicholas Bellinger <nab@linux-iscsi.org>
(cherry picked from commit 373a4cd7378220d3c5a69fd369b1d78fee3207b2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>