ASoC: codecs: wcd934x: Fix Kconfig dependency
Bugzilla: https://bugzilla.redhat.com/2179848

commit 4d73b97b8dbaf09af6e5878ce3288ba93956a3fd
Author: Ren Zhijie <renzhijie2@huawei.com>
Date: Mon Sep 26 07:40:42 2022 +0000

    ASoC: codecs: wcd934x: Fix Kconfig dependency

    If CONFIG_REGMAP_SLIMBUS is not set,
    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-,
    will be failed, like this:

    sound/soc/codecs/wcd934x.o: In function `wcd934x_codec_probe':
    wcd934x.c:(.text+0x3310): undefined reference to `__regmap_init_slimbus'
    make: *** [vmlinux] Error 1

    Add select REGMAP_SLIMBUS to config SND_SOC_WCD934X.

    Fixes: a61f3b4f476e ("ASoC: wcd934x: add support to wcd9340/wcd9341 codec")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20220926074042.13297-1-renzhijie2@huawei.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>