ASoC: tegra186_asrc: mark runtime-pm functions as __maybe_unused
sound/soc/tegra/tegra186_asrc.c:90:12: error: ‘tegra186_asrc_runtime_resume’ defined but not used [-Werror=unused-function]
 static int tegra186_asrc_runtime_resume(struct device *dev)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/soc/tegra/tegra186_asrc.c:80:12: error: ‘tegra186_asrc_runtime_suspend’ defined but not used [-Werror=unused-function]
 static int tegra186_asrc_runtime_suspend(struct device *dev)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Mark these functions as __maybe_unused to avoid this kind of warning.

    Fixes: a2df8c2d5b36 ("ASoC: tegra: Add Tegra186 based ASRC driver")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Sameer Pujar <spujar@nvidia.com>
    Link: https://lore.kernel.org/r/20220411020908.580-1-yuehaibing@huawei.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: YueHaibing <yuehaibing@huawei.com>
Date: Mon Apr 11 10:09:08 2022 +0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit dc7680ca7ac6c32b8c18aff36bca728a2f83e2a0)
Bugzilla: https://bugzilla.redhat.com/2125537