PCI: dwc: Expose dw_pcie_ep_exit() to module
JIRA: https://issues.redhat.com/browse/RHEL-26162
Upstream Status: 2066b41a2ef83937f70a84927cbbcc969528b867

commit 2066b41a2ef83937f70a84927cbbcc969528b867
Author: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Date:   Wed Oct 18 17:56:23 2023 +0900

    PCI: dwc: Expose dw_pcie_ep_exit() to module

    Since no PCIe controller drivers call this, this change is not required
    for now. But, Renesas R-Car Gen4 PCIe controller driver will call this
    and if the controller driver is built as a kernel module, the following
    build error happens:

      ERROR: modpost: "dw_pcie_ep_exit" [drivers/pci/controller/dwc/pcie-rcar-gen4-ep-drv.ko] undefined!

    So, expose dw_pcie_ep_exit() for it.

    Link: https://lore.kernel.org/linux-pci/20231018085631.1121289-8-yoshihiro.shimoda.uh@renesas.com
    Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@kernel.org>
    Reviewed-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
    Reviewed-by: Serge Semin <fancer.lancer@gmail.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>