wifi: mac80211: fix maybe-unused warning
Bugzilla: https://bugzilla.redhat.com/2136124

commit 09d838a457a89883a926b8b0104d575158fd4b92
Author: Íñigo Huguet <ihuguet@redhat.com>
Date:   Fri Nov 11 16:36:22 2022 +0100

    wifi: mac80211: fix maybe-unused warning
    
    In ieee80211_lookup_key, the variable named `local` is unused if
    compiled without lockdep, getting this warning:
    
    net/mac80211/cfg.c: In function ‘ieee80211_lookup_key’:
    net/mac80211/cfg.c:542:26: error: unused variable ‘local’ [-Werror=unused-variable]
      struct ieee80211_local *local = sdata->local;
                              ^~~~~
    
    Fix it with __maybe_unused.
    
    Fixes: 8cbf0c2ab6df ("wifi: mac80211: refactor some key code")
    Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>
    Link: https://lore.kernel.org/r/20221111153622.29016-1-ihuguet@redhat.com
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>