fs/posix_acl.c: avoid -Wempty-body warning
JIRA: https://issues.redhat.com/browse/RHEL-33888
Status: Linus

commit d1cef29adc22938d778b4652af34e72facd8184b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 5 13:35:01 2021 -0700

    fs/posix_acl.c: avoid -Wempty-body warning

    The fallthrough comment for an ignored cmpxchg() return value produces a
    harmless warning with 'make W=1':

      fs/posix_acl.c: In function 'get_acl':
      fs/posix_acl.c:127:36: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
        127 |                 /* fall through */ ;
            |                                    ^

    Simplify it as a step towards a clean W=1 build.  As all architectures
    define cmpxchg() as a statement expression these days, it is no longer
    necessary to evaluate its return code, and the if() can just be droped.

    Link: https://lkml.kernel.org/r/20210927102410.1863853-1-arnd@kernel.org
    Link: https://lore.kernel.org/all/20210322132103.qiun2rjilnlgztxe@wittgenstein/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Christian Brauner <christian.brauner@ubuntu.com>
    Cc: Alexander Viro <viro@zeniv.linux.org.uk>
    Cc: James Morris <jamorris@linux.microsoft.com>
    Cc: Serge Hallyn <serge@hallyn.com>
    Cc: Miklos Szeredi <mszeredi@redhat.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Ian Kent <ikent@redhat.com>