usb-misc: sisusbvga: Fix coding style: braces, parenthesis, comment
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Peter Senna Tschudin <peter.senna@gmail.com>
commit f996c49d4fa4e8e33955eb59691e1b116b3d733b

The file drivers/usb/misc/sisusbvga/sisusb.c contained coding style
issues reported by checkpatch. This patch fixes the following
errors:
 - 12 WARNING: braces {} are not necessary for single statement blocks
 - 04 ERROR: return is not a function, parentheses are not required
 - 03 ERROR: do not initialise statics to 0
 - 1 WARNING: else is not generally useful after a break or return
 - 1 WARNING: braces {} are not necessary for any arm of this statement
 - 1 WARNING: Block comments use * on subsequent lines

One case in which braces are not necessary is left unchanged as other
patch of the series will fix it.

	Signed-off-by: Peter Senna Tschudin <peter.senna@collabora.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit f996c49d4fa4e8e33955eb59691e1b116b3d733b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>