net: qed: reduce stack usage for TLV processing
JIRA: https://issues.redhat.com/browse/RHEL-96459

commit 95b6759a81833d0e8c7456430186c2f6d174764e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 20 15:09:53 2025 +0200

    net: qed: reduce stack usage for TLV processing

    clang gets a bit confused by the code in the qed_mfw_process_tlv_req and
    ends up spilling registers to the stack hundreds of times. When sanitizers
    are enabled, this can end up blowing the stack warning limit:

    drivers/net/ethernet/qlogic/qed/qed_mng_tlv.c:1244:5: error: stack frame size (1824) exceeds limit (1280) in 'qed_mfw_process_tlv_req' [-Werror,-Wframe-larger-than]

    Apparently the problem is the complexity of qed_mfw_update_tlvs()
    after inlining, and marking the four main branches of that function
    as noinline_for_stack makes this problem completely go away, the stack
    usage goes down to 100 bytes.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: John Meneghini <jmeneghi@redhat.com>