ASoC: rockchip: Fix Wvoid-pointer-to-enum-cast warning (again)
JIRA: https://issues.redhat.com/browse/RHEL-152846

commit 57d508b5f718730f74b11e0dc9609ac7976802d1
Author: Krzysztof Kozlowski <krzysztof.kozlowski@oss.qualcomm.com>
Date: Wed Dec 3 15:16:45 2025 +0100

    ASoC: rockchip: Fix Wvoid-pointer-to-enum-cast warning (again)

    'version' is an enum, thus cast of pointer on 64-bit compile test with
    clang W=1 causes:

      rockchip_pdm.c:583:17: error: cast to smaller integer type 'enum rk_pdm_version' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    This was already fixed in commit 49a4a8d12612 ("ASoC: rockchip: Fix
    Wvoid-pointer-to-enum-cast warning") but then got bad in
    commit 9958d85968ed ("ASoC: Use device_get_match_data()").

    Discussion on LKML also pointed out that 'uintptr_t' is not the correct
    type and either 'kernel_ulong_t' or 'unsigned long' should be used,
    with several arguments towards the latter [1].

    Link: https://lore.kernel.org/r/CAMuHMdX7t=mabqFE5O-Cii3REMuyaePHmqX+j_mqyrn6XXzsoA@mail.gmail.com/ [1]
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@oss.qualcomm.com>
    Link: https://patch.msgid.link/20251203141644.106459-2-krzysztof.kozlowski@oss.qualcomm.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>