bpf: Fix bpf_prog_pack build for ppc64_defconfig
Bugzilla: https://bugzilla.redhat.com/2120966

commit 4cc0991abd3954609a6929234bbb8c0fe7a0298d
Author: Song Liu <song@kernel.org>
Date:   Thu Feb 10 18:49:39 2022 -0800

    bpf: Fix bpf_prog_pack build for ppc64_defconfig

    bpf_prog_pack causes build error with powerpc ppc64_defconfig:

    kernel/bpf/core.c:830:23: error: variably modified 'bitmap' at file scope
      830 |         unsigned long bitmap[BITS_TO_LONGS(BPF_PROG_CHUNK_COUNT)];
          |                       ^~~~~~

    This is because the marco expands as:

    unsigned long bitmap[((((((1UL) << (16 + __pte_index_size)) / (1 << 6))) \
         + ((sizeof(long) * 8)) - 1) / ((sizeof(long) * 8)))];

    where __pte_index_size is a global variable.

    Fix it by turning bitmap into a 0-length array.

    Fixes: 57631054fae6 ("bpf: Introduce bpf_prog_pack allocator")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Song Liu <song@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20220211024939.2962537-1-song@kernel.org

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>