gpio: merrifield: Fix build err without CONFIG_ACPI
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit fe066621c7966fe47fa17c6be6fd81adb3c0509f

When building CONFIG_ACPI is not set
gcc warn this:

drivers/gpio/gpio-merrifield.c: In function mrfld_gpio_get_pinctrl_dev_name:
drivers/gpio/gpio-merrifield.c:388:19: error: dereferencing pointer to incomplete type struct acpi_device
   put_device(&adev->dev);
                   ^~

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: d00d2109c367 ("gpio: merrifield: Convert to use acpi_dev_get_first_match_dev()")
	Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Acked-by: Linus Walleij <linus.walleij@linaro.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit fe066621c7966fe47fa17c6be6fd81adb3c0509f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>