bits: introduce fixed-type GENMASK_U*()
JIRA: https://issues.redhat.com/browse/RHEL-114532

commit 19408200c094858d952a90bf4977733dc89a4df5
Author: Vincent Mailhol <mailhol.vincent@wanadoo.fr>
Date:   Wed Mar 26 00:59:57 2025 +0900

    bits: introduce fixed-type GENMASK_U*()

    Add GENMASK_TYPE() which generalizes __GENMASK() to support different
    types, and implement fixed-types versions of GENMASK() based on it.
    The fixed-type version allows more strict checks to the min/max values
    accepted, which is useful for defining registers like implemented by
    i915 and xe drivers with their REG_GENMASK*() macros.

    The strict checks rely on shift-count-overflow compiler check to fail
    the build if a number outside of the range allowed is passed.
    Example:

      #define FOO_MASK GENMASK_U32(33, 4)

    will generate a warning like:

      include/linux/bits.h:51:27: error: right shift count >= width of type [-Werror=shift-count-overflow]
         51 |               type_max(t) >> (BITS_PER_TYPE(t) - 1 - (h)))))
            |                           ^~

    The result is casted to the corresponding fixed width type. For
    example, GENMASK_U8() returns an u8. Note that because of the C
    promotion rules, GENMASK_U8() and GENMASK_U16() will immediately be
    promoted to int if used in an expression. Regardless, the main goal is
    not to get the correct type, but rather to enforce more checks at
    compile time.

    While GENMASK_TYPE() is crafted to cover all variants, including the
    already existing GENMASK(), GENMASK_ULL() and GENMASK_U128(), for the
    moment, only use it for the newly introduced GENMASK_U*(). The
    consolidation will be done in a separate change.

    Co-developed-by: Yury Norov <yury.norov@gmail.com>
    Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>
    Acked-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Vincent Mailhol <mailhol.vincent@wanadoo.fr>
    Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Yury Norov <yury.norov@gmail.com>

Signed-off-by: Anusha Srivatsa <asrivats@redhat.com>