x86/usercopy: Include arch_wb_cache_pmem() declaration
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 3b939ba0c21115de99d8e2966eaa2c4e74733d00
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:46 2023 +0200

    x86/usercopy: Include arch_wb_cache_pmem() declaration

    arch_wb_cache_pmem() is declared in a global header but defined by
    the architecture. On x86, the implementation needs to include the header
    to avoid this warning:

    arch/x86/lib/usercopy_64.c:39:6: error: no previous prototype for 'arch_wb_cache_pmem' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-18-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>