RDMA/core: reduce stack using in nldev_stat_get_doit()
JIRA: https://issues.redhat.com/browse/RHEL-109943

commit 43163f4c30f94d2103c948a247cdf2cda5068ca7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 20 13:33:26 2025 +0200

    RDMA/core: reduce stack using in nldev_stat_get_doit()

    In the s390 defconfig, gcc-10 and earlier end up inlining three functions
    into nldev_stat_get_doit(), and each of them uses some 600 bytes of stack.

    The result is a function with an overly large stack frame and a warning:

    drivers/infiniband/core/nldev.c:2466:1: error: the frame size of 1720 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

    Mark the three functions noinline_for_stack to prevent this, ensuring
    that only one copy of the nlattr array is on the stack of each function.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250620113335.3776965-1-arnd@kernel.org
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>