block: iolatency: avoid 64-bit division
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 88b7210c81096c018f5836aff4749743c0d34623

On 32-bit architectures, dividing a 64-bit number needs to use the
do_div() function or something like it to avoid a link failure:

block/blk-iolatency.o: In function `iolatency_prfill_limit':
blk-iolatency.c:(.text+0x8cc): undefined reference to `__aeabi_uldivmod'

Using div_u64() gives us the best output and avoids the need for an
explicit cast.

Fixes: d70675121546 ("block: introduce blk-iolatency io controller")
	Reviewed-by: Josef Bacik <josef@toxicpanda.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit 88b7210c81096c018f5836aff4749743c0d34623)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>