ASoC: Intel: kbl_da7219_max98357a: shrink platform_id below 20 characters
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 94efd726b947f265bd313605c9f73edec5469d65

Sparse throws the following warnings:

sound/soc/intel/boards/kbl_da7219_max98357a.c:647:25: error: too long
initializer-string for array of char(no space for nul char)

Fix by using the 'mx' acronym for Maxim.

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
	Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
	Reviewed-by: Rander Wang <rander.wang@intel.com>
Link: https://lore.kernel.org/r/20210621194057.21711-6-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 94efd726b947f265bd313605c9f73edec5469d65)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>