ALSA: cs46xx: mark snd_cs46xx_download_image as static
Bugzilla: https://bugzilla.redhat.com/2179848

commit ccecefa4f89971e34745abbffdaf4d2c3fb2f457
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue May 16 21:50:41 2023 +0200

    ALSA: cs46xx: mark snd_cs46xx_download_image as static

    snd_cs46xx_download_image() was originally called from dsp_spos.c, but
    is now local to cs46xx_lib.c. Mark it as 'static' to avoid a warning
    about it lacking a declaration, and '__maybe_unused' to avoid a warning
    about it being unused when CONFIG_SND_CS46XX_NEW_DSP is disabled:

    sound/pci/cs46xx/cs46xx_lib.c:534:5: error: no previous prototype for 'snd_cs46xx_download_image'

    Fixes: 89f157d9e6bf ("[ALSA] cs46xx - Fix PM resume")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230516195046.550584-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>