scsi: ufs: qcom: Remove unused variable
JIRA: https://issues.redhat.com/browse/RHEL-10197

commit 65aca38b8ce728bf5a449b74f2a6a344167dfb02
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 24 14:19:58 2023 +0200

    scsi: ufs: qcom: Remove unused variable

    A recent change removed the only user of a local variable that needs to now
    also be removed:

    drivers/ufs/host/ufs-qcom.c: In function 'ufs_qcom_mcq_esi_handler':
    drivers/ufs/host/ufs-qcom.c:1652:31: error: unused variable 'host' [-Werror=unused-variable]

    Fixes: 8f2b78652d05 ("scsi: ufs: qcom: Get queue ID from MSI index in ESI handler")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/llvm/64c00cd4.630a0220.6ad79.0eac@mx.google.com/
    Link: https://lore.kernel.org/r/20230724122029.1430482-1-arnd@kernel.org
    Reviewed-by: Abel Vesa <abel.vesa@linaro.org>
    Reviewed-by: Manivannan Sadhasivam <mani@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Alessandro Carminati <acarmina@redhat.com>