netfilter: combine IPv4 and IPv6 nf_nat_redirect code in one module
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Pablo Neira Ayuso <pablo@netfilter.org>
commit b59eaf9e2871735ea7cc7e3dbf8bf83bddd786b9

This resolves linking problems with CONFIG_IPV6=n:

net/built-in.o: In function `redirect_tg6':
xt_REDIRECT.c:(.text+0x6d021): undefined reference to `nf_nat_redirect_ipv6'

	Reported-by: Andreas Ruprecht <rupran@einserver.de>
	Reported-by: Or Gerlitz <ogerlitz@mellanox.com>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit b59eaf9e2871735ea7cc7e3dbf8bf83bddd786b9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>