tpm: Export tpm2_get_cc_attrs_tbl for ibmvtpm driver as module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Stefan Berger <stefanb@linux.ibm.com>
commit 684c6bd806253bf65dbb64978fc113ff081b4aea

This patch fixes the following problem when the ibmvtpm driver
is built as a module:

ERROR: modpost: "tpm2_get_cc_attrs_tbl" [drivers/char/tpm/tpm_ibmvtpm.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make: *** [Makefile:1298: modules] Error 2

Fixes: 18b3670d79ae ("tpm: ibmvtpm: Add support for TPM2")
	Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
	Reported-by: Sachin Sant <sachinp@linux.vnet.ibm.com>
	Tested-by: Sachin Sant <sachinp@linux.vnet.ibm.com>
	Reviewed-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
	Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
(cherry picked from commit 684c6bd806253bf65dbb64978fc113ff081b4aea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>