power: supply: Fix build error when CONFIG_POWER_SUPPLY is not enabled.
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Ray Chi <raychi@google.com>
commit c21161e40ee94486f7db701f9b4d3f9c25763e8c

The build error happens when CONFIG_POWER_SUPPLY is not enabled.

h8300-linux-ld: drivers/usb/dwc3/gadget.o: in function `.L59':
>> gadget.c:(.text+0x655): undefined reference to `power_supply_set_property'

Fixes: 99288de36020 ("usb: dwc3: add an alternate path in vbus_draw callback")
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Ray Chi <raychi@google.com>
Link: https://lore.kernel.org/r/20210327182809.1814480-3-raychi@google.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit c21161e40ee94486f7db701f9b4d3f9c25763e8c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>