KVM: PPC: Book3S HV: radix: Fix uninitialized var build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit f460772291f8171988b2b60141a45706123d0c69

Old GCCs (4.6.3 at least), aren't able to follow the logic in
__kvmhv_copy_tofrom_guest_radix() and warn that old_pid is used
uninitialized:

  arch/powerpc/kvm/book3s_64_mmu_radix.c:75:3: error: 'old_pid' may be
  used uninitialized in this function

The logic is OK, we only use old_pid if quadrant == 1, and in that
case it has definitely be initialised, eg:

	if (quadrant == 1) {
		old_pid = mfspr(SPRN_PID);
	...
	if (quadrant == 1 && pid != old_pid)
		mtspr(SPRN_PID, old_pid);

Annotate it to fix the error.

	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit f460772291f8171988b2b60141a45706123d0c69)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>