net/mlx5e: Remove unused variable
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [netdrv] mlx5e: Remove unused variable (Don Dutile) [1385330 1417286]
Rebuild_FUZZ: 93.55%
commit-author Arnd Bergmann <arnd@arndb.de>
commit ad05df399f3343b10664827a3860669a8a80782d

A cleanup removed the only user of this variable

mlx5/core/en_ethtool.c: In function 'mlx5e_set_channels':
mlx5/core/en_ethtool.c:546:6: error: unused variable 'ncv' [-Werror=unused-variable]

Let's remove the declaration as well.

Fixes: 639e9e94160e ("net/mlx5e: Remove unnecessary checks when setting num channels")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Reviewed-by: Tariq Toukan <tariqt@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ad05df399f3343b10664827a3860669a8a80782d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>