thunderbolt: test: split up test cases in tb_test_credit_alloc_all
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Linus Torvalds <torvalds@linux-foundation.org>
commit 4b93c544e90e2b28326182d31ee008eb80e02074

The tb_test_credit_alloc_all() function had a huge number of
KUNIT_ASSERT() statements, all of which (though the magic of many many
layers of inscrutable macros) ended up allocating and initializing
various test assertion structures on the stack.

Don't do that.  The kernel stack isn't infinite, and we have compiler
warnings (now errors) for the case where a stack frame grows too large.

Like it did here, by not an inconsiderable margin:

   drivers/thunderbolt/test.c: In function ‘tb_test_credit_alloc_all’:
   drivers/thunderbolt/test.c:2367:1: error: the frame size of 4500 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
    2367 | }
         | ^

Solve this similarly to the lib/test_scanf case: split out the tests
into several smaller functions, each just testing one particular tunnel
credit allocation.

This makes the i386 allyesconfig build work for me again.

	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 4b93c544e90e2b28326182d31ee008eb80e02074)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>