tools, bpftool: Print correct error message when failing to load BTF
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Tobias Klauser <tklauser@distanz.ch>
commit dc3ca5cf3e0be9fb73f4691247367d76a22bf30b

btf__parse_raw and btf__parse_elf return negative error numbers wrapped
in an ERR_PTR, so the extracted value needs to be negated before passing
them to strerror which expects a positive error number.

Before:
  Error: failed to load BTF from .../vmlinux: Unknown error -2

After:
  Error: failed to load BTF from .../vmlinux: No such file or directory

	Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Link: https://lore.kernel.org/bpf/20200525135421.4154-1-tklauser@distanz.ch
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit dc3ca5cf3e0be9fb73f4691247367d76a22bf30b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>