net: mana: select PAGE_POOL
JIRA: https://issues.redhat.com/browse/RHEL-23420

commit 340943fbff3d8faa44d2223ca04917df28786a07
Author: Yury Norov <yury.norov@gmail.com>
Date:   Fri Dec 15 12:33:53 2023 -0800

    net: mana: select PAGE_POOL

    Mana uses PAGE_POOL API. x86_64 defconfig doesn't select it:

    ld: vmlinux.o: in function `mana_create_page_pool.isra.0':
    mana_en.c:(.text+0x9ae36f): undefined reference to `page_pool_create'
    ld: vmlinux.o: in function `mana_get_rxfrag':
    mana_en.c:(.text+0x9afed1): undefined reference to `page_pool_alloc_pages'
    make[3]: *** [/home/yury/work/linux/scripts/Makefile.vmlinux:37: vmlinux] Error 1
    make[2]: *** [/home/yury/work/linux/Makefile:1154: vmlinux] Error 2
    make[1]: *** [/home/yury/work/linux/Makefile:234: __sub-make] Error 2
    make[1]: Leaving directory '/home/yury/work/build-linux-x86_64'
    make: *** [Makefile:234: __sub-make] Error 2

    So we need to select it explicitly.

    Signed-off-by: Yury Norov <yury.norov@gmail.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Tested-by: Simon Horman <horms@kernel.org> # build-tested
    Fixes: ca9c54d2 ("net: mana: Add a driver for Microsoft Azure Network Adapter")
    Link: https://lore.kernel.org/r/20231215203353.635379-1-yury.norov@gmail.com
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>