bpf: Fix bpf-next builds without CONFIG_BPF_EVENTS
Bugzilla: http://bugzilla.redhat.com/2041365

commit eb529c5b10b9401a0f2d1f469e82c6a0ba98082c
Author: Daniel Xu <dxu@dxuuu.xyz>
Date:   Wed Aug 25 18:48:31 2021 -0700

    bpf: Fix bpf-next builds without CONFIG_BPF_EVENTS

    This commit fixes linker errors along the lines of:

        s390-linux-ld: task_iter.c:(.init.text+0xa4): undefined reference to `btf_task_struct_ids'`

    Fix by defining btf_task_struct_ids unconditionally in kernel/bpf/btf.c
    since there exists code that unconditionally uses btf_task_struct_ids.

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Daniel Xu <dxu@dxuuu.xyz>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/05d94748d9f4b3eecedc4fddd6875418a396e23c.1629942444.git.dxu@dxuuu.xyz

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>