cpufreq: amd-pstate: Fix Kconfig dependencies for AMD P-State
Bugzilla: https://bugzilla.redhat.com/1961725

commit a2e6840b37b45d04e095c47f961211b7697cb063
Author: Huang Rui <ray.huang@amd.com>
Date:   Thu Jan 6 15:43:05 2022 +0800

    cpufreq: amd-pstate: Fix Kconfig dependencies for AMD P-State

    The AMD P-State driver is based on ACPI CPPC function, so ACPI should be
    dependence of this driver in the kernel config.

    In file included from ../drivers/cpufreq/amd-pstate.c:40:0:
    ../include/acpi/processor.h:226:2: error: unknown type name ‘phys_cpuid_t’
      phys_cpuid_t phys_id; /* CPU hardware ID such as APIC ID for x86 */
      ^~~~~~~~~~~~
    ../include/acpi/processor.h:355:1: error: unknown type name ‘phys_cpuid_t’; did you mean ‘phys_addr_t’?
     phys_cpuid_t acpi_get_phys_id(acpi_handle, int type, u32 acpi_id);
     ^~~~~~~~~~~~
     phys_addr_t
      CC      drivers/rtc/rtc-rv3029c2.o
    ../include/acpi/processor.h:356:1: error: unknown type name ‘phys_cpuid_t’; did you mean ‘phys_addr_t’?
     phys_cpuid_t acpi_map_madt_entry(u32 acpi_id);
     ^~~~~~~~~~~~
     phys_addr_t
    ../include/acpi/processor.h:357:20: error: unknown type name ‘phys_cpuid_t’; did you mean ‘phys_addr_t’?
     int acpi_map_cpuid(phys_cpuid_t phys_id, u32 acpi_id);
                        ^~~~~~~~~~~~
                        phys_addr_t

    See https://lore.kernel.org/lkml/20e286d4-25d7-fb6e-31a1-4349c805aae3@infradead.org/.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Huang Rui <ray.huang@amd.com>
    [ rjw: Subject edits ]
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>