usb: cdns3: Don't use priv_dev uninitialized in cdns3_gadget_ep_enable()
Bugzilla: http://bugzilla.redhat.com/2113003
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=48723298
Tested: HP ZBook 15 G5/80D5 Laptop
  ThinkPad P1 Gen5  TB4
  HP zBook Fury

commit 78acd4ca433425e6dd4032cfc2156c60e34931f2
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Aug 3 09:24:22 2022 -0700

    usb: cdns3: Don't use priv_dev uninitialized in cdns3_gadget_ep_enable()

    Clang warns:

      drivers/usb/cdns3/cdns3-gadget.c:2290:11: error: variable 'priv_dev' is uninitialized when used here [-Werror,-Wuninitialized]
                      dev_dbg(priv_dev->dev, "usbss: invalid parameters\n");
                              ^~~~~~~~
      include/linux/dev_printk.h:155:18: note: expanded from macro 'dev_dbg'
              dynamic_dev_dbg(dev, dev_fmt(fmt), ##__VA_ARGS__)
                              ^~~
      include/linux/dynamic_debug.h:167:7: note: expanded from macro 'dynamic_dev_dbg'
                              dev, fmt, ##__VA_ARGS__)
                              ^~~
      include/linux/dynamic_debug.h:152:56: note: expanded from macro '_dynamic_func_call'
              __dynamic_func_call(__UNIQUE_ID(ddebug), fmt, func, ##__VA_ARGS__)
                                                                  ^~~~~~~~~~~
      include/linux/dynamic_debug.h:134:15: note: expanded from macro '__dynamic_func_call'
                      func(&id, ##__VA_ARGS__);               \
                                  ^~~~~~~~~~~
      drivers/usb/cdns3/cdns3-gadget.c:2278:31: note: initialize the variable 'priv_dev' to silence this warning
              struct cdns3_device *priv_dev;
                                          ^
                                          = NULL
      1 error generated.

    The priv_dev assignment was moved below the if statement to avoid
    potentially dereferencing ep before it was checked but priv_dev is used
    in the dev_dbg() call.

    To fix this, move the priv_dev and comp_desc assignments back to their
    original spot and hoist the ep check above those assignments with a call
    to pr_debug() instead of dev_dbg().

    Fixes: c3ffc9c4ca44 ("usb: cdns3: change place of 'priv_ep' assignment in cdns3_gadget_ep_dequeue(), cdns3_gadget_ep_enable()")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1680
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>