qed: Fix build error without CONFIG_DEVLINK
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit bd8d7d9088289ba099721e7c696d988842b6cc24

Fix gcc build error while CONFIG_DEVLINK is not set

drivers/net/ethernet/qlogic/qed/qed_main.o: In function `qed_remove':
qed_main.c:(.text+0x1eb4): undefined reference to `devlink_unregister'

Select DEVLINK to fix this.

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 24e04879abdd ("qed: Add qed devlink parameters table")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Acked-by: Michal Kalderon <michal.kalderon@marvell.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit bd8d7d9088289ba099721e7c696d988842b6cc24)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>