ASoC: codecs: tlv320aic32x4: Fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-13724

Omitted-fix: 49a4a8d1261230378a8931d0859329057686b6eb
             ASoC: rockchip: Fix Wvoid-pointer-to-enum-cast warning
             unsupported platform in RHEL

commit 66de320b0214a60095287ba1afa09e870d8cdbe5
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Tue Aug 15 16:32:02 2023 +0200

    ASoC: codecs: tlv320aic32x4: Fix Wvoid-pointer-to-enum-cast warning

    'type' is an enum, thus cast of pointer on 64-bit compile test with W=1
    causes:

      tlv320aic32x4.c:1352:18: error: cast to smaller integer type 'enum aic32x4_type' from 'void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230815143204.379708-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>