KVM: selftests: Fix printf() format goof in SEV smoke test
JIRA: https://issues.redhat.com/browse/RHEL-82917

commit 3b2d3db368013729fd2167a0d91fec821dba807c
Author: Sean Christopherson <seanjc@google.com>
Date:   Fri Feb 28 15:38:52 2025 -0800

    KVM: selftests: Fix printf() format goof in SEV smoke test

    Print out the index of mismatching XSAVE bytes using unsigned decimal
    format.  Some versions of clang complain about trying to print an integer
    as an unsigned char.

      x86/sev_smoke_test.c:55:51: error: format specifies type 'unsigned char'
                                         but the argument has type 'int' [-Werror,-Wformat]

    Fixes: 8c53183dbaa2 ("selftests: kvm: add test for transferring FPU state into VMSA")
    Link: https://lore.kernel.org/r/20250228233852.3855676-1-seanjc@google.com
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>