drm/tests: Split up test cases in igt_check_drm_format_min_pitch
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author Maíra Canal <mairacanal@riseup.net>
commit cf1e6a90315a3f5b8ecbb3cf6a4badf8978e9075

The igt_check_drm_format_min_pitch() function had a lot of
KUNIT_EXPECT_* calls, all of which ended up allocating and initializing
various test assertion structures on the stack.

This behavior was producing -Wframe-larger-than warnings on PowerPC, i386,
and MIPS architectures, such as:

drivers/gpu/drm/tests/drm_format_test.c: In function 'igt_check_drm_format_min_pitch':
drivers/gpu/drm/tests/drm_format_test.c:271:1: error: the frame size of
3712 bytes is larger than 2048 bytes

So, the igt_check_drm_format_min_pitch() test case was split into three
smaller functions: one testing single plane formats, one testing
multi-planar formats, and the other testing tiled formats.

Fixes: 0421bb0baa84 ("drm: selftest: convert drm_format selftest to KUnit")
	Reported-by: kernel test robot <lkp@intel.com>
	Reported-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Maíra Canal <mairacanal@riseup.net>
	Tested-by: Guenter Roeck <linux@roeck-us.net>
	Reviewed-by: André Almeida <andrealmeid@igalia.com>
	Signed-off-by: Melissa Wen <melissa.srw@gmail.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20220729124726.748221-1-mairacanal@riseup.net
(cherry picked from commit cf1e6a90315a3f5b8ecbb3cf6a4badf8978e9075)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>