x86/mm: Include asm/numa.h for set_highmem_pages_init()
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit b963d12aa66ce02b948cd69a20eea5d1d1e0137e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:37 2023 +0200

    x86/mm: Include asm/numa.h for set_highmem_pages_init()

    The set_highmem_pages_init() function is declared in asm/numa.h, which
    must be included in the file that defines it to avoid a W=1 warning:

    arch/x86/mm/highmem_32.c:7:13: error: no previous prototype for 'set_highmem_pages_init' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-9-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>