tools/bpf: add missing strings.h include
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Andrii Nakryiko <andriin@fb.com>
commit 62b8cea62e8bad0511260faab8e8de04c76a69af

Few files in libbpf are using bzero() function (defined in strings.h header), but
don't include corresponding header. When libbpf is added as a dependency to pahole,
this undeterministically causes warnings on some machines:

bpf.c:225:2: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
  bzero(&attr, sizeof(attr));
    ^~~~~

	Signed-off-by: Andrii Nakryiko <andriin@fb.com>
	Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit 62b8cea62e8bad0511260faab8e8de04c76a69af)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>