x86/purgatory: use approprate -m64/-32 build flag for arch/x86/purgatory
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [x86] purgatory: use approprate -m64/-32 build flag for arch/x86/purgatory (Vivek Goyal) [852066]
Rebuild_FUZZ: 97.14%
commit-author Vivek Goyal <vgoyal@redhat.com>
commit 4df4185a596c7301be0d8e1fdf691ec03e57cd23

Thomas reported that build of x86_64 kernel was failing for him.  He is
using 32bit tool chain.

Problem is that while compiling purgatory, I have not specified -m64
flag.  And 32bit tool chain must be assuming -m32 by default.

Following is error message.

(mini) [~/work/linux-2.6] make
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  CC      arch/x86/purgatory/purgatory.o
arch/x86/purgatory/purgatory.c:1:0: error: code model 'large' not supported in
the 32 bit mode

Fix it by explicitly passing appropriate -m64/-m32 build flag for
purgatory.

	Reported-by: Thomas Glanzmann <thomas@glanzmann.de>
	Tested-by: Thomas Glanzmann <thomas@glanzmann.de>
	Suggested-by: H. Peter Anvin <hpa@zytor.com>
	Signed-off-by: Vivek Goyal <vgoyal@redhat.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 4df4185a596c7301be0d8e1fdf691ec03e57cd23)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>