ALSA: rme9652: fix format overflow warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7ad210ace5c1701421a4defa9d9e830a6f2ee56b

gcc-7 warns about a possible sprintf format string overflow with a
temporary buffer that is used to print from another buffer of the same
size:

sound/pci/rme9652/hdspm.c: In function 'snd_hdspm_create_alsa_devices':
sound/pci/rme9652/hdspm.c:2123:17: error: ' MIDIoverMADI' directive writing 13 bytes into a region of size between 1 and 32 [-Werror=format-overflow=]

This extends the temporary buffer to twice the size, and changes
the code to use the safer snprintf() across the entire file.
The longer buffer is still necessary to avoid a format-truncation
warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 7ad210ace5c1701421a4defa9d9e830a6f2ee56b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>