mlx5: fix psample_sample_packet link error
Bugzilla: https://bugzilla.redhat.com/2049450
Upstream-status: v5.17-rc1

commit 7a7dd5114f53885419ef67c530e961d7ceaec15a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 8 12:10:32 2021 +0100

    mlx5: fix psample_sample_packet link error

    When PSAMPLE is a loadable module, built-in drivers cannot use it:

    aarch64-linux-ld: drivers/net/ethernet/mellanox/mlx5/core/en/tc/sample.o: in function `mlx5e_tc_sample_skb':
    sample.c:(.text+0xd68): undefined reference to `psample_sample_packet'

    Add the same dependency here that is used for MLXSW

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>