of: reserved_mem: Fix placement of __free() annotation
JIRA: https://issues.redhat.com/browse/RHEL-214191
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 5dff92a7bde9a8ef3b709f65e347cb1c33260cf4
Author: Gregory CLEMENT <gregory.clement@bootlin.com>
Date: Wed Jan 7 14:04:52 2026 +0100

    of: reserved_mem: Fix placement of __free() annotation

    The __free() annotation was incorrectly placed before the variable
    name instead of after it, which resulted in the following checkpatch
    errors:

    ERROR: need consistent spacing around '*' (ctx:WxV)
    +       struct device_node __free(device_node) *target = of_parse_phandle(np, "memory-region", idx);
						   ^
    WARNING: function definition argument 'idx' should also have an identifier name
    +       struct device_node __free(device_node) *target = of_parse_phandle(np, "memory-region", idx);

    As part of this cleanup, also remove the useless return statement
    flagged by checkpatch.

    Signed-off-by: Gregory CLEMENT <gregory.clement@bootlin.com>
    Link: https://patch.msgid.link/20260107-mtd-memregion-v3-1-f9fc9107b992@bootlin.com
    Signed-off-by: Rob Herring (Arm) <robh@kernel.org>

(cherry picked from commit 5dff92a7bde9a8ef3b709f65e347cb1c33260cf4)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>