dmaengine: dw-edma: increase size of 'name' in debugfs code
JIRA: https://issues.redhat.com/browse/RHEL-65598
Upstream Status: cb95a4fa50bbc1262bfb7fea482388a50b12948f

commit cb95a4fa50bbc1262bfb7fea482388a50b12948f
Author: Vinod Koul <vkoul@kernel.org>
Date:   Fri Jan 19 18:10:44 2024 +0530

    dmaengine: dw-edma: increase size of 'name' in debugfs code

    We seem to have hit warnings of 'output may be truncated' which is fixed
    by increasing the size of 'name'

    drivers/dma/dw-edma/dw-hdma-v0-debugfs.c: In function ‘dw_hdma_v0_debugfs_on’:
    drivers/dma/dw-edma/dw-hdma-v0-debugfs.c:125:50: error: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 8 [-Werror=format-truncation=]
      125 |                 snprintf(name, sizeof(name), "%s:%d", CHANNEL_STR, i);
          |                                                  ^~

    drivers/dma/dw-edma/dw-hdma-v0-debugfs.c: In function ‘dw_hdma_v0_debugfs_on’:
    drivers/dma/dw-edma/dw-hdma-v0-debugfs.c:142:50: error: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 8 [-Werror=format-truncation=]
      142 |                 snprintf(name, sizeof(name), "%s:%d", CHANNEL_STR, i);
          |                                                  ^~
    drivers/dma/dw-edma/dw-edma-v0-debugfs.c: In function ‘dw_edma_debugfs_regs_wr’:
    drivers/dma/dw-edma/dw-edma-v0-debugfs.c:193:50: error: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 8 [-Werror=format-truncation=]
      193 |                 snprintf(name, sizeof(name), "%s:%d", CHANNEL_STR, i);
          |                                                  ^~

    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>