ipmr: fix build with clang and DEBUG_NET disabled.
JIRA: https://issues.redhat.com/browse/RHEL-74037

commit f6d7695b5ae22092fa2cc42529bb7462f7e0c4ad
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Thu Nov 28 17:18:04 2024 +0100

    ipmr: fix build with clang and DEBUG_NET disabled.

    Sasha reported a build issue in ipmr::

    net/ipv4/ipmr.c:320:13: error: function 'ipmr_can_free_table' is not \
            needed and will not be emitted \
            [-Werror,-Wunneeded-internal-declaration]
       320 | static bool ipmr_can_free_table(struct net *net)

    Apparently clang is too smart with BUILD_BUG_ON_INVALID(), let's
    fallback to a plain WARN_ON_ONCE().

    Reported-by: Sasha Levin <sashal@kernel.org>
    Closes: https://qa-reports.linaro.org/lkft/sashal-linus-next/build/v6.11-25635-g6813e2326f1e/testrun/26111580/suite/build/test/clang-nightly-lkftconfig/details/
    Fixes: 11b6e701bce9 ("ipmr: add debug check for mr table cleanup")
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>
    Link: https://patch.msgid.link/ee75faa926b2446b8302ee5fc30e129d2df73b90.1732810228.git.pabeni@redhat.com
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: CKI Backport Bot <cki-ci-bot+cki-gitlab-backport-bot@redhat.com>