fbdev: make offb driver tristate
JIRA: https://issues.redhat.com/browse/RHEL-23295
Upstream Status: v6.2-rc3

Conflicts:
        drivers/video/fbdev/Kconfig
conflict because it misses the Kconfig part of c8a17756c42581ba
	


commit 9d8b5376cc2848ca22314fdec9a7a45b1bf69189
Author:     Randy Dunlap <rdunlap@infradead.org>
AuthorDate: Fri Nov 25 16:04:01 2022 -0800
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Tue Dec 27 22:01:45 2022 +0100

    Make the offb (Open Firmware frame buffer) driver tristate,
    i.e., so that it can be built as a loadable module.

    However, it still depends on the setting of DRM_OFDRM
    so that both of these drivers cannot be builtin at the same time
    nor can one be builtin and the other one a loadable module.

    Build-tested successfully with all combination of DRM_OFDRM and FB_OF.

    This fixes a build issue that Michal reported when FB_OF=y and
    DRM_OFDRM=m:

    powerpc64-linux-ld: drivers/video/fbdev/offb.o:(.data.rel.ro+0x58): undefined reference to `cfb_fillrect'
    powerpc64-linux-ld: drivers/video/fbdev/offb.o:(.data.rel.ro+0x60): undefined reference to `cfb_copyarea'
    powerpc64-linux-ld: drivers/video/fbdev/offb.o:(.data.rel.ro+0x68): undefined reference to `cfb_imageblit'

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Masahiro Yamada <masahiroy@kernel.org>
    Cc: Thomas Zimmermann <tzimmermann@suse.de>
    Cc: Michal Suchánek <msuchanek@suse.de>
    Cc: linuxppc-dev@lists.ozlabs.org
    Cc: Daniel Vetter <daniel@ffwll.ch>
    Cc: Helge Deller <deller@gmx.de>
    Cc: linux-fbdev@vger.kernel.org
    Cc: dri-devel@lists.freedesktop.org
    Acked-by: Thomas Zimmermann <tzimmermann@suse.de>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>