kunit: tool: Assert the version requirement
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author SeongJae Park <sjpark@amazon.de>
commit df4b0807ca1a62822342d404b863eff933d15762

Commit 87c9c1631788 ("kunit: tool: add support for QEMU") on the 'next'
tree adds 'from __future__ import annotations' in 'kunit_kernel.py'.
Because it is supported on only >=3.7 Python, people using older Python
will get below error:

    Traceback (most recent call last):
      File "./tools/testing/kunit/kunit.py", line 20, in <module>
        import kunit_kernel
      File "/home/sjpark/linux/tools/testing/kunit/kunit_kernel.py", line 9
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined

This commit adds a version assertion in 'kunit.py', so that people get
more explicit error message like below:

    Traceback (most recent call last):
      File "./tools/testing/kunit/kunit.py", line 15, in <module>
        assert sys.version_info >= (3, 7), "Python version is too old"
    AssertionError: Python version is too old

	Signed-off-by: SeongJae Park <sjpark@amazon.de>
	Acked-by: Daniel Latypov <dlatypov@google.com>
	Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit df4b0807ca1a62822342d404b863eff933d15762)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>