kgdboc: Fix restrict error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Laura Abbott <labbott@redhat.com>
commit 2dd453168643d9475028cd867c57e65956a0f7f9

There's an error when compiled with restrict:

drivers/tty/serial/kgdboc.c: In function ‘configure_kgdboc’:
drivers/tty/serial/kgdboc.c:137:2: error: ‘strcpy’ source argument is the same
as destination [-Werror=restrict]
  strcpy(config, opt);
  ^~~~~~~~~~~~~~~~~~~

As the error implies, this is from trying to use config as both source and
destination. Drop the call to the function where config is the argument
since nothing else happens in the function.

	Signed-off-by: Laura Abbott <labbott@redhat.com>
	Reviewed-by: Daniel Thompson <daniel.thompson@linaro.org>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 2dd453168643d9475028cd867c57e65956a0f7f9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>