bpf: handle implicit declaration of function gettid in bpf_iter.c
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit 42602e3a06f8e5b9a059344e305c9bee2dcc87c8
Author: Jason Xing <kernelxing@tencent.com>
Date:   Tue Oct 29 15:46:27 2024 +0800

    bpf: handle implicit declaration of function gettid in bpf_iter.c

    As we can see from the title, when I compiled the selftests/bpf, I
    saw the error:
    implicit declaration of function ‘gettid’ ; did you mean ‘getgid’? [-Werror=implicit-function-declaration]
      skel->bss->tid = gettid();
                       ^~~~~~
                       getgid

    Directly call the syscall solves this issue.

    Signed-off-by: Jason Xing <kernelxing@tencent.com>
    Reviewed-by: Alan Maguire <alan.maguire@oracle.com>
    Tested-by: Alan Maguire <alan.maguire@oracle.com>
    Link: https://lore.kernel.org/r/20241029074627.80289-1-kerneljasonxing@gmail.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>