gfs2: Use container_of() for gfs2_glock(aspace)
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2109548

commit 11d8b79e849db099b04584913880a799549aaad5
Author: Kees Cook <keescook@chromium.org>
Date:   Sun May 8 03:06:30 2022 -0700

    gfs2: Use container_of() for gfs2_glock(aspace)

    Clang's structure layout randomization feature gets upset when it sees
    struct address_space (which is randomized) cast to struct gfs2_glock.
    This is due to seeing the mapping pointer as being treated as an array
    of gfs2_glock, rather than "something else, before struct address_space":

    In file included from fs/gfs2/acl.c:23:
    fs/gfs2/meta_io.h:44:12: error: casting from randomized structure pointer type 'struct address_space *' to 'struct gfs2_glock *'
            return (((struct gfs2_glock *)mapping) - 1)->gl_name.ln_sbd;
                    ^

    Replace the instances of open-coded pointer math with container_of()
    usage, and update the allocator to match.

    Some cleanups and conversion of gfs2_glock_get() and
    gfs2_glock_dealloc() by Andreas.

    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/lkml/202205041550.naKxwCBj-lkp@intel.com
    Cc: Bob Peterson <rpeterso@redhat.com>
    Cc: Andreas Gruenbacher <agruenba@redhat.com>
    Cc: Bill Wendling <morbo@google.com>
    Cc: cluster-devel@redhat.com
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Andreas Gruenbacher <agruenba@redhat.com>

Signed-off-by: Andreas Gruenbacher <agruenba@redhat.com>