arm64: kvm: avoid overflow in integer division
JIRA: https://issues.redhat.com/browse/RHEL-1760

commit 14c3555f055dd0819381148bf5b569cc5ba9ddfb
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 22:23:39 2023 +0200

    arm64: kvm: avoid overflow in integer division

    The newly added kvm_mmu_split_nr_page_tables() function uses DIV_ROUND_DOWN_ULL()
    to divide 64-bit addresses, but this requires a 32-bit divisior, and PUD_SIZE
    may exceed that when 64KB pages are used:

    arch/arm64/kvm/mmu.c: In function 'kvm_mmu_split_nr_page_tables':
    include/linux/math.h:42:64: error: conversion from 'long unsigned int' to 'u32' {aka 'unsigned int'} changes value from '68719476736' to '0' [-Werror=overflow]
       42 |         DIV_ROUND_DOWN_ULL((unsigned long long)(ll) + (d) - 1, (d))
          |                                                                ^~~
    include/linux/math.h:39:47: note: in definition of macro 'DIV_ROUND_DOWN_ULL'
       39 | #define DIV_ROUND_DOWN_ULL(ll, d) div_u64(ll, d)
          |                                               ^
    arch/arm64/kvm/mmu.c:95:22: note: in expansion of macro 'DIV_ROUND_UP_ULL'
       95 |                 n += DIV_ROUND_UP_ULL(range, PUD_SIZE);
          |                      ^~~~~~~~~~~~~~~~

    Since this code is only used on 64-bit targets, DIV_ROUND_UP() can deal with this
    more easily, as it already takes 64-bit arguments.

    Fixes: e7bf7a490c68 ("KVM: arm64: Split huge pages when dirty logging is enabled")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230517202352.793673-1-arnd@kernel.org
    Signed-off-by: Oliver Upton <oliver.upton@linux.dev>

Signed-off-by: Shaoqin Huang <shahuang@redhat.com>