net/mlx5e: Fix build break on 32bit
JIRA: https://issues.redhat.com/browse/RHEL-882
Upstream-status: v6.4-rc1

commit 163c2c7059178898ad7512294ca3a768df2c1515
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Tue Mar 28 13:07:23 2023 -0700

    net/mlx5e: Fix build break on 32bit

    The cited commit caused the following build break in mlx5 due to a change
    in size of MAX_SKB_FRAGS.

    error: format '%lu' expects argument of type 'long unsigned int',
           but argument 7 has type 'unsigned int' [-Werror=format=]

    Fix this by explicit casting.

    Fixes: 3948b05950fd ("net: introduce a config option to tweak MAX_SKB_FRAGS")
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Link: https://lore.kernel.org/r/20230328200723.125122-1-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>