clk: qcom: fix build error initializer element is not constant
Bugzilla: https://bugzilla.redhat.com/2158909

commit b5eb8cde863cdf455436c7ba3fb7362c49e1e64e
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Thu Jul 14 20:11:44 2022 +0800

    clk: qcom: fix build error initializer element is not constant

    CONFIG_CC_VERSION_TEXT="x86_64-linux-gnu-gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0"
    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-, will be failed, like this:

    drivers/clk/qcom/gpucc-sm8350.c:111:2: error: initializer element is not constant
      gpu_cc_parent,
      ^~~~~~~~~~~~~
    drivers/clk/qcom/gpucc-sm8350.c:111:2: note: (near initialization for ‘gpu_cc_parent_data_0[0]’)
    drivers/clk/qcom/gpucc-sm8350.c:126:2: error: initializer element is not constant
      gpu_cc_parent,
      ^~~~~~~~~~~~~
    drivers/clk/qcom/gpucc-sm8350.c:126:2: note: (near initialization for ‘gpu_cc_parent_data_1[0]’)
    make[3]: *** [drivers/clk/qcom/gpucc-sm8350.o] Error 1

    It seems that nested constant initializer is not supported in GCC 7.4.0. For portability resons, we should fix it.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: 160758b05ab1 ("clk: qcom: add support for SM8350 GPUCC")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
    Link: https://lore.kernel.org/r/20220714121144.71062-1-renzhijie2@huawei.com

Signed-off-by: Adrien Thierry <athierry@redhat.com>