include/linux/genalloc.h: spinlock_t needs spinlock_types.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [kernel] linux/genalloc.h: spinlock_t needs spinlock_types.h (Jeff Moyer) [1662226]
Rebuild_FUZZ: 92.73%
commit-author Shawn Guo <shawn.guo@linaro.org>
commit b30afea019a4548ee77b73e83f03104e0e3a0556

Compiling a C file which includes genalloc.h but without
spinlock_types.h being included before, we will see the compile error
below.

 include/linux/genalloc.h:54:2: error: unknown type name `spinlock_t'

Include spinlock_types.h from genalloc.h to fix the problem.

	Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit b30afea019a4548ee77b73e83f03104e0e3a0556)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>