arm64: kaslr: add kaslr_early_init() declaration
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit a7f5cb606e9993daf2d129efc5e3b6ca46ad9227
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:39 +0200

    kaslr_early_init() is called from assembler code and does not
    need a declaration to work, but adding one anyway shuts up
    this W=1 warning:

    arch/arm64/kernel/pi/kaslr_early.c:88:16: error: no previous prototype for 'kaslr_early_init' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-13-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>