IB/mlx4: avoid a -Wmaybe-uninitialize warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit a4256bc9ec36159e84d710c7c44aaa244a6380a8

There is an old warning about mlx4_SW2HW_EQ_wrapper on x86:

ethernet/mellanox/mlx4/resource_tracker.c: In function ‘mlx4_SW2HW_EQ_wrapper’:
ethernet/mellanox/mlx4/resource_tracker.c:3071:10: error: ‘eq’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

The problem here is that gcc won't track the state of the variable
across a spin_unlock. Moving the assignment out of the lock is
safe here and avoids the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Yishai Hadas <yishaih@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit a4256bc9ec36159e84d710c7c44aaa244a6380a8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>