perf lock: Subcommands should include common options
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Changbin Du <changbin.du@intel.com>
commit 249eed53152167c64c6dc66fa269a1d8b415a7b4

When I use -i option for report subcommand, it doesn't accept it.  We
need add common options using OPT_PARENT macro.

perf lock report -i lock_perf.data
  Error: unknown switch `i'

  Usage: perf lock report [<options>]

    -f, --force           don't complain, do it
    -k, --key <acquired>  key for sorting ...

	Signed-off-by: Changbin Du <changbin.du@intel.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/20170317055342.8284-1-changbin.du@intel.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 249eed53152167c64c6dc66fa269a1d8b415a7b4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>