soc: ti: pruss: Avoid cast to incompatible function type
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit 413552b360e72604b8c0cf3f60f9e6f01c8ff963
Author: Simon Horman <horms@kernel.org>
Date:   Tue Apr 18 13:41:48 2023 +0200

    soc: ti: pruss: Avoid cast to incompatible function type

    Rather than casting clk_unregister_mux to an incompatible function
    type provide a trivial wrapper with the correct signature for the
    use-case.

    Reported by clang-16 with W=1:

     drivers/soc/ti/pruss.c:158:38: error: cast from 'void (*)(struct clk *)' to 'void (*)(void *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
             ret = devm_add_action_or_reset(dev, (void(*)(void *))clk_unregister_mux,

    No functional change intended.
    Compile tested only.

    Signed-off-by: Simon Horman <horms@kernel.org>
    Reviewed-by: MD Danish Anwar <danishanwar@ti.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20230418-pruss-clk-cb-v1-1-549a7e7febe4@kernel.org
    Signed-off-by: Nishanth Menon <nm@ti.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>