powerpc: Export cpu_to_chip_id() to fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] Export cpu_to_chip_id() to fix build error (Don Zickus) [1127366]
Rebuild_FUZZ: 90.32%
commit-author Guenter Roeck <linux@roeck-us.net>
commit 256588fda10f2a712631f8a4e72641a66adebdb8

powerpc allmodconfig build fails with:

ERROR: ".cpu_to_chip_id" [drivers/block/mtip32xx/mtip32xx.ko] undefined!

The problem was introduced with commit 15863ff3b (powerpc: Make chip-id
information available to userspace).

Export the missing symbol.

	Cc: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
	Cc: Shivaprasad G Bhat <sbhat@linux.vnet.ibm.com>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
(cherry picked from commit 256588fda10f2a712631f8a4e72641a66adebdb8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>