cpufreq: intel_pstate: Fix static checker warning for epp variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
commit 3ff79754d7a2b27f6d2d56b3951fc9aa8080b063

Fix warning for:
drivers/cpufreq/intel_pstate.c:731 store_energy_performance_preference()
error: uninitialized symbol 'epp'.

This warning is for a case, when energy_performance_preference attribute
matches pre defined strings. In this case the value of raw epp will not
be used to set EPP bits in MSR_HWP_REQUEST. So initializing with any
value is fine.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
	Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 3ff79754d7a2b27f6d2d56b3951fc9aa8080b063)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>