rv: Add rtapp_sleep monitor
JIRA: https://issues.redhat.com/browse/RHEL-114755

commit f74f8bb246cf22f27752977da62079cb615f55b2
Author: Nam Cao <namcao@linutronix.de>
Date:   Wed Jul 9 21:21:21 2025 +0200

    rv: Add rtapp_sleep monitor

    Add a monitor for checking that real-time tasks do not go to sleep in a
    manner that may cause undesirable latency.

    Also change
            RV depends on TRACING
    to
            RV select TRACING
    to avoid the following recursive dependency:

     error: recursive dependency detected!
            symbol TRACING is selected by PREEMPTIRQ_TRACEPOINTS
            symbol PREEMPTIRQ_TRACEPOINTS depends on TRACE_IRQFLAGS
            symbol TRACE_IRQFLAGS is selected by RV_MON_SLEEP
            symbol RV_MON_SLEEP depends on RV
            symbol RV depends on TRACING

    Cc: John Ogness <john.ogness@linutronix.de>
    Cc: Masami Hiramatsu <mhiramat@kernel.org>
    Cc: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
    Link: https://lore.kernel.org/75bc5bcc741d153aa279c95faf778dff35c5c8ad.1752088709.git.namcao@linutronix.de
    Reviewed-by: Gabriele Monaco <gmonaco@redhat.com>
    Signed-off-by: Nam Cao <namcao@linutronix.de>
    Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Gabriele Monaco <gmonaco@redhat.com>