powerpc: Fix compile issue with force DAWR
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [powerpc] Fix compile issue with force DAWR (Greg Kurz) [1882796]
Rebuild_FUZZ: 88.00%
commit-author Michael Neuling <mikey@neuling.org>
commit a278e7ea608bea5fe6df9b6ae91fa134655c5d2c
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/a278e7ea.failed

If you compile with KVM but without CONFIG_HAVE_HW_BREAKPOINT you fail
at linking with:
  arch/powerpc/kvm/book3s_hv_rmhandlers.o:(.text+0x708): undefined reference to `dawr_force_enable'

This was caused by commit c1fe190c0672 ("powerpc: Add force enable of
DAWR on P9 option").

This moves a bunch of code around to fix this. It moves a lot of the
DAWR code in a new file and creates a new CONFIG_PPC_DAWR to enable
compiling it.

Fixes: c1fe190c0672 ("powerpc: Add force enable of DAWR on P9 option")
	Signed-off-by: Michael Neuling <mikey@neuling.org>
[mpe: Minor formatting in set_dawr()]
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit a278e7ea608bea5fe6df9b6ae91fa134655c5d2c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/Kconfig
#	arch/powerpc/include/asm/hw_breakpoint.h
#	arch/powerpc/kernel/process.c