ASoC: SDCA: fix HID dependency
JIRA: https://issues.redhat.com/browse/RHEL-118908

commit ad4655653a6c463026ed3c300e5fb34f39abff48
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Jul 9 17:24:17 2025 +0200

    ASoC: SDCA: fix HID dependency

    It is not possible to enable SND_SOC_SDCA_HID when SND_SOC_SDCA is built-in
    but HID is in a loadable module, as that results in a link failure:

    x86_64-linux-ld: sound/soc/sdca/sdca_functions.o: in function `find_sdca_entity_hide':
    sdca_functions.c:(.text+0x25b): undefined reference to `sdca_add_hid_device'

    Change SND_SOC_SDCA_HID into a 'bool' option that can only be enabled
    if this results in a working build, and change the Makefile so this driver
    is a loadable module if possible.

    Fixes: ac558015dfd8 ("ASoC: SDCA: add a HID device for HIDE entity")
    Reviewed-by: Charles Keepax <ckeepax@opensource.cirrus.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250709152430.1498427-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>