arm64/sve: <uapi/asm/ptrace.h> should not depend on <uapi/linux/prctl.h>
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Anisse Astier <aastier@freebox.fr>
commit 35341ca0614ab13e1ef34ad4f29a39e15ef31fa8

Pulling linux/prctl.h into asm/ptrace.h in the arm64 UAPI headers causes
userspace build issues for any program (e.g. strace and qemu) that
includes both <sys/prctl.h> and <linux/ptrace.h> when using musl libc:

  | error: redefinition of 'struct prctl_mm_map'
  |  struct prctl_mm_map {

See https://github.com/foundriesio/meta-lmp/commit/6d4a106e191b5d79c41b9ac78fd321316d3013c0
for a public example of people working around this issue.

Although it's a bit grotty, fix this breakage by duplicating the prctl
constant definitions. Since these are part of the kernel ABI, they
cannot be changed in future and so it's not the end of the world to have
them open-coded.

Fixes: 43d4da2c45b2 ("arm64/sve: ptrace and ELF coredump support")
	Cc: stable@vger.kernel.org
	Acked-by: Dave Martin <Dave.Martin@arm.com>
	Signed-off-by: Anisse Astier <aastier@freebox.fr>
	Signed-off-by: Will Deacon <will.deacon@arm.com>
(cherry picked from commit 35341ca0614ab13e1ef34ad4f29a39e15ef31fa8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>