drm/fourcc: fix integer type usage in uapi header
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Carlos Llamas <cmllamas@google.com>
commit 3d313f09f31490cec9d5251b59adeb6542c944cc

Kernel uapi headers are supposed to use __[us]{8,16,32,64} types defined
by <linux/types.h> as opposed to 'uint32_t' and similar. See [1] for the
relevant discussion about this topic. In this particular case, the usage
of 'uint64_t' escaped headers_check as these macros are not being called
here. However, the following program triggers a compilation error:

  #include <drm/drm_fourcc.h>

  int main()
  {
  	unsigned long x = AMD_FMT_MOD_CLEAR(RB);
  	return 0;
  }

gcc error:
  drm.c:5:27: error: ‘uint64_t’ undeclared (first use in this function)
      5 |         unsigned long x = AMD_FMT_MOD_CLEAR(RB);
        |                           ^~~~~~~~~~~~~~~~~

This patch changes AMD_FMT_MOD_{SET,CLEAR} macros to use the correct
integer types, which fixes the above issue.

  [1] https://lkml.org/lkml/2019/6/5/18

Fixes: 8ba16d599374 ("drm/fourcc: Add AMD DRM modifiers.")
	Signed-off-by: Carlos Llamas <cmllamas@google.com>
	Reviewed-by: Simon Ser <contact@emersion.fr>
	Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 3d313f09f31490cec9d5251b59adeb6542c944cc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>