md: factor out a helper to choose sync action from md_check_recovery()
JIRA: https://issues.redhat.com/browse/RHEL-12455

commit 897c62a1cae6485870a45934b22c180016a0570f
Author: Yu Kuai <yukuai3@huawei.com>
Date:   Fri Aug 25 11:16:17 2023 +0800

    md: factor out a helper to choose sync action from md_check_recovery()

    There are no functional changes, on the one hand make the code cleaner,
    on the other hand prevent following checkpatch error in the next patch to
    delay choosing sync action to md_start_sync().

    ERROR: do not use assignment in if condition
    +       } else if ((spares = remove_and_add_spares(mddev, NULL))) {

    Signed-off-by: Yu Kuai <yukuai3@huawei.com>
    Reviewed-by: Xiao Ni <xni@redhat.com>
    Signed-off-by: Song Liu <song@kernel.org>
    Link: https://lore.kernel.org/r/20230825031622.1530464-3-yukuai1@huaweicloud.com

Signed-off-by: Nigel Croxon <ncroxon@redhat.com>