crypto: bcm - Drop unused setting of local 'ptr' variable
JIRA: https://redhat.atlassian.net/browse/RHEL-186630

commit 1742b0a0e4668763066fab5fa76d071c1ac92648
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Jan 4 21:55:02 2025 +0100

    crypto: bcm - Drop unused setting of local 'ptr' variable

    spum_cipher_req_init() assigns 'spu_hdr' to local 'ptr' variable and
    later increments 'ptr' over specific fields like it was meant to point
    to pieces of message for some purpose.  However the code does not read
    'ptr' at all thus this entire iteration over 'spu_hdr' seams pointless.

    Reported by clang W=1 build:

      drivers/crypto/bcm/spu.c:839:6: error: variable 'ptr' set but not used [-Werror,-Wunused-but-set-variable]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Thomas Huth <thuth@redhat.com>