can: fix CAN BCM build with CONFIG_PROC_FS disabled
jira VULN-36330
cve-prereq CVE-2023-52922
commit-author Oliver Hartkopp <socketcan@hartkopp.net>
commit c2701b370e6b4d0022043691b5ac7adad015e4fc
upstream-diff This commit also has a dependency on 384317ef4187
("can: network namespace support for CAN_BCM protocol") but that does
not affect the CVE-2023-52922 and is therefore not necessary.

The introduced namespace support moved the BCM variables for procfs into a
per-net data structure. This leads to a build failure with disabled procfs:

on x86_64:

when CONFIG_PROC_FS is not enabled:

../net/can/bcm.c:1541:14: error: 'struct netns_can' has no member named 'bcmproc_dir'
../net/can/bcm.c:1601:14: error: 'struct netns_can' has no member named 'bcmproc_dir'
../net/can/bcm.c:1696:11: error: 'struct netns_can' has no member named 'bcmproc_dir'
../net/can/bcm.c:1707:15: error: 'struct netns_can' has no member named 'bcmproc_dir'

http://marc.info/?l=linux-can&m=149321842526524&w=2

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Oliver Hartkopp <socketcan@hartkopp.net>
	Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
(cherry picked from commit c2701b370e6b4d0022043691b5ac7adad015e4fc)
	Signed-off-by: Pratham Patel <ppatel@ciq.com>