x86/calldepth: Fix incorrect init section references
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2190342

commit ade8c20847fcc3f4de08b35f730ec04ef29ddbdc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu, 15 Dec 2022 17:43:23 +0100

    x86/calldepth: Fix incorrect init section references

    The addition of callthunks_translate_call_dest means that
    skip_addr() and patch_dest() can no longer be discarded
    as part of the __init section freeing:

    WARNING: modpost: vmlinux.o: section mismatch in reference: callthunks_translate_call_dest.cold (section: .text.unlikely) -> skip_addr (section: .init.text)
    WARNING: modpost: vmlinux.o: section mismatch in reference: callthunks_translate_call_dest.cold (section: .text.unlikely) -> patch_dest (section: .init.text)
    WARNING: modpost: vmlinux.o: section mismatch in reference: is_callthunk.cold (section: .text.unlikely) -> skip_addr (section: .init.text)
    ERROR: modpost: Section mismatches detected.
    Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.

    Fixes: b2e9dfe54be4 ("x86/bpf: Emit call depth accounting if required")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lkml.kernel.org/r/20221215164334.968863-1-arnd@kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>