bnxt_en: hide CONFIG_DETECT_HUNG_TASK specific code
JIRA: https://issues.redhat.com/browse/RHEL-76565

commit 8ff6175139967cd17b2a62bca4b2de2559942b7e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 23 18:28:21 2025 +0200

    bnxt_en: hide CONFIG_DETECT_HUNG_TASK specific code

    The CONFIG_DEFAULT_HUNG_TASK_TIMEOUT setting is only available when the
    hung task detection is enabled, otherwise the code now produces a build
    failure:

    drivers/net/ethernet/broadcom/bnxt/bnxt.c:10188:21: error: use of undeclared identifier 'CONFIG_DEFAULT_HUNG_TASK_TIMEOUT'
     10188 |             max_tmo_secs > CONFIG_DEFAULT_HUNG_TASK_TIMEOUT) {

    Enclose this warning logic in an #ifdef to ensure this builds.

    Fixes: 0fcad44a86bd ("bnxt_en: Change FW message timeout warning")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Michael Chan <michael.chan@broadcom.com>
    Link: https://patch.msgid.link/20250423162827.2189658-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Shruti Parab <shruti.parab@broadcom.com>