platform/x86: amd-pmc: Fix build error unused-function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-527.el8
commit-author Ren Zhijie <renzhijie2@huawei.com>
commit 17faaacac3c92abde4019600e107c10c367d74f2

If CONFIG_SUSPEND and CONFIG_DEBUG_FS are not set.

compile error:
drivers/platform/x86/amd-pmc.c:323:12: error: ‘get_metrics_table’ defined but not used [-Werror=unused-function]
 static int get_metrics_table(struct amd_pmc_dev *pdev, struct smu_metrics *table)
            ^~~~~~~~~~~~~~~~~
drivers/platform/x86/amd-pmc.c:298:12: error: ‘amd_pmc_idlemask_read’ defined but not used [-Werror=unused-function]
 static int amd_pmc_idlemask_read(struct amd_pmc_dev *pdev, struct device *dev,
            ^~~~~~~~~~~~~~~~~~~~~
drivers/platform/x86/amd-pmc.c:196:12: error: ‘amd_pmc_get_smu_version’ defined but not used [-Werror=unused-function]
 static int amd_pmc_get_smu_version(struct amd_pmc_dev *dev)
            ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

To fix building warning, wrap all related code with CONFIG_SUSPEND or CONFIG_DEBUG_FS.

	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
Link: https://lore.kernel.org/r/20220505121958.138905-1-renzhijie2@huawei.com
	Signed-off-by: Hans de Goede <hdegoede@redhat.com>
(cherry picked from commit 17faaacac3c92abde4019600e107c10c367d74f2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>