ASoC: rockchip: pdm: select CONFIG_RATIONAL
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: rockchip: pdm: select CONFIG_RATIONAL (Jaroslav Kysela) [1738610]
Rebuild_FUZZ: 93.48%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 41d92e0c835bff7dec343bf41e79d24b326d94c1

Without this, we get a link error:

sound/soc/rockchip/rockchip_pdm.o: In function `rockchip_pdm_hw_params':
rockchip_pdm.c:(.text+0x754): undefined reference to `rational_best_approximation'

Fixes: 624e8e00acaf ("ASoC: rockchip: pdm: fixup pdm fractional div")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 41d92e0c835bff7dec343bf41e79d24b326d94c1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>