x86: Avoid missing-prototype warnings for doublefault code
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit c9664839305dfaccd098b1606c197b0eb21056dc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:36 2023 +0200

    x86: Avoid missing-prototype warnings for doublefault code

    Two functions in the 32-bit doublefault code are lacking a prototype:

    arch/x86/kernel/doublefault_32.c:23:36: error: no previous prototype for 'doublefault_shim' [-Werror=missing-prototypes]
       23 | asmlinkage noinstr void __noreturn doublefault_shim(void)
          |                                    ^~~~~~~~~~~~~~~~
    arch/x86/kernel/doublefault_32.c:114:6: error: no previous prototype for 'doublefault_init_cpu_tss' [-Werror=missing-prototypes]
      114 | void doublefault_init_cpu_tss(void)

    The first one is only called from assembler, while the second one is
    declared in doublefault.h, but this file is not included.

    Include the header file and add the other declaration there as well.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-8-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>