net/mlx5: Lag, Make mlx5_lag_is_multipath() be static inline
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Maor Dickman <maord@nvidia.com>
commit 8ca9caee851c444810b70d9c167e7321f3ff68f8

Fix "no previous prototype" W=1 warnings when CONFIG_MLX5_CORE_EN is not set:

  drivers/net/ethernet/mellanox/mlx5/core/lag_mp.h:34:6: error: no previous prototype for ‘mlx5_lag_is_multipath’ [-Werror=missing-prototypes]
     34 | bool mlx5_lag_is_multipath(struct mlx5_core_dev *dev) { return false; }
        |      ^~~~~~~~~~~~~~~~~~~~~

Fixes: 14fe2471c628 ("net/mlx5: Lag, change multipath and bonding to be mutually exclusive")
	Signed-off-by: Maor Dickman <maord@nvidia.com>
(cherry picked from commit 8ca9caee851c444810b70d9c167e7321f3ff68f8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>