perf/marvell: Fix !CONFIG_OF build for CN10K DDR PMU driver
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2042241

commit 6676a42f1e4f1b8ec166b723a3801b7113c25a0e
Author: Will Deacon <will@kernel.org>
Date:   Wed Mar 9 12:31:00 2022 +0000

    perf/marvell: Fix !CONFIG_OF build for CN10K DDR PMU driver

    When compiling the Marvell CN10K DDR PMU driver with CONFIG_OF=n, the
    build fails:

      | drivers/perf/marvell_cn10k_ddr_pmu.c:723:35: error: 'cn10k_ddr_pmu_of_match' undeclared here (not in a function); did you mean 'cn10k_ddr_pmu_driver'?

    Use `of_match_ptr()` to avoid referencing the non-existent match table
    in this configuration.

    Link: https://lore.kernel.org/r/202203091424.Vfe8J4W9-lkp@intel.com
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Bharat Bhushan <bbhushan@redhat.com>