Bluetooth: hci_ll: drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit cd97d47f3069ef578f3b3ddb8c7ae3d6ce38b61a
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 12:13:51 2023 +0100

    Bluetooth: hci_ll: drop of_match_ptr for ID table

    The driver can match only via the DT table so the table should be always
    used and the of_match_ptr does not have any sense (this also allows ACPI
    matching via PRP0001, even though it might not be relevant here).

      drivers/bluetooth/hci_ll.c:769:34: error: ‘hci_ti_of_match’ defined
      but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>