Bluetooth: btusb: Fix application of sizeof to pointer
Bugzilla: http://bugzilla.redhat.com/2066188

commit dc1650fc94a8566fb89f3fd14a26d1cec7865f16
Author: David Yang <davidcomponentone@gmail.com>
Date:   Wed Oct 13 08:56:33 2021 +0800

    Bluetooth: btusb: Fix application of sizeof to pointer

    The coccinelle check report:
    "./drivers/bluetooth/btusb.c:2239:36-42:
    ERROR: application of sizeof to pointer".
    Using the real size to fix it.

    Fixes: 5a87679ffd443 ("Bluetooth: btusb: Support public address configuration for MediaTek Chip.")
    Reported-by: Zeal Robot <zealci@zte.com.cn>
    Signed-off-by: David Yang <davidcomponentone@gmail.com>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>