usbip: Fix unsafe unaligned pointer usage
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Shuah Khan <skhan@linuxfoundation.org>
commit 585c91f40d201bc564d4e76b83c05b3b5363fe7e

Fix unsafe unaligned pointer usage in usbip network interfaces. usbip tool
build fails with new gcc -Werror=address-of-packed-member checks.

usbip_network.c: In function ‘usbip_net_pack_usb_device’:
usbip_network.c:79:32: error: taking address of packed member of ‘struct usbip_usb_device’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
   79 |  usbip_net_pack_uint32_t(pack, &udev->busnum);

Fix with minor changes to pass by value instead of by address.

	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
Link: https://lore.kernel.org/r/20200109012416.2875-1-skhan@linuxfoundation.org
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 585c91f40d201bc564d4e76b83c05b3b5363fe7e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>