cgroup: Fix 64-bit division in cgroup.stat.local
JIRA: https://issues.redhat.com/browse/RHEL-113305

commit 8d2a75589599fd8cd5c542c8052642445652ca5e
Author: Tiffany Yang <ynaffit@google.com>
Date:   Fri, 22 Aug 2025 19:21:28 -0700

    cgroup: Fix 64-bit division in cgroup.stat.local

    Fix the following build error for 32-bit systems:
       arm-linux-gnueabi-ld: kernel/cgroup/cgroup.o: in function `cgroup_core_local_stat_show':
    >> kernel/cgroup/cgroup.c:3781:(.text+0x28f4): undefined reference to `__aeabi_uldivmod'
       arm-linux-gnueabi-ld: (__aeabi_uldivmod): Unknown destination type (ARM/Thumb) in kernel/cgroup/cgroup.o
    >> kernel/cgroup/cgroup.c:3781:(.text+0x28f4): dangerous relocation: unsupported relocation

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202508230604.KyvqOy81-lkp@intel.com/
    Signed-off-by: Tiffany Yang <ynaffit@google.com>
    Cc: Tejun Heo <tj@kernel.org>
    Signed-off-by: Tejun Heo <tj@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>