CIFS: Fix build failure with smb2
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Tobias Regnery <tobias.regnery@gmail.com>
commit 4fa8e504e5c0d7db9280ac96a4ac92192f1041f5
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/4fa8e504.failed

I saw the following build error during a randconfig build:

fs/cifs/smb2ops.c: In function 'smb2_new_lease_key':
fs/cifs/smb2ops.c:1104:2: error: implicit declaration of function 'generate_random_uuid' [-Werror=implicit-function-declaration]

Explicit include the right header to fix this issue.

	Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>
	Reviewed-by: Aurelien Aptel <aaptel@suse.com>
	Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit 4fa8e504e5c0d7db9280ac96a4ac92192f1041f5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	fs/cifs/smb2ops.c