drivers/infiniband/core/verbs.c: fix build with gcc-4.4.4
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [infiniband] infiniband/core/verbs.c: fix build with gcc-4.4.4 (Kamal Heib) [1641363]
Rebuild_FUZZ: 92.45%
commit-author Andrew Morton <akpm@linux-foundation.org>
commit 6ee687735e745eafae9e6b93d1ea70bc52e7ad07

gcc-4.4.4 has issues with initialization of anonymous unions.

drivers/infiniband/core/verbs.c: In function '__ib_drain_sq':
drivers/infiniband/core/verbs.c:2204: error: unknown field 'wr_cqe' specified in initializer
drivers/infiniband/core/verbs.c:2204: warning: initialization makes integer from pointer without a cast

Work around this.

Fixes: a1ae7d0345edd5 ("RDMA/core: Avoid that ib_drain_qp() triggers an out-of-bounds stack access")
	Cc: Bart Van Assche <bart.vanassche@wdc.com>
	Cc: Steve Wise <swise@opengridcomputing.com>
	Cc: Sagi Grimberg <sagi@grimberg.me>
	Cc: Jason Gunthorpe <jgg@mellanox.com>
	Cc: <stable@vger.kernel.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 6ee687735e745eafae9e6b93d1ea70bc52e7ad07)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>