ACPI / button: fix button driver compile error when CONFIG_PM_SLEEP is undefined
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [acpi] button: fix button driver compile error when CONFIG_PM_SLEEP is undefined (Lenny Szubowicz) [1246944]
Rebuild_FUZZ: 95.42%
commit-author Shuah Khan <shuah.kh@samsung.com>
commit 2de9fd17c0359fea0c2ab5ae393c40d6d299bcaf

The ACPI button driver defines acpi_button_resume() when
CONFIG_PM_SLEEP is defined. This results in the following
compile error when CONFIG_PM_SLEEP is undefined:

drivers/acpi/button.c:85:8: error: ‘acpi_button_resume’ undeclared here (not in a function)

	Signed-off-by: Shuah Khan <shuah.kh@samsung.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 2de9fd17c0359fea0c2ab5ae393c40d6d299bcaf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>