ALSA: scarlett2: Zero initialize ret in scarlett2_ag_target_ctl_get()
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit 3a56855bb549211031184e45fe1a9d24874d7227
Author: Nathan Chancellor <nathan@kernel.org>
Date: Fri Apr 19 17:25:59 2024 -0700

    ALSA: scarlett2: Zero initialize ret in scarlett2_ag_target_ctl_get()

    Clang warns (or errors with CONFIG_WERROR):

      sound/usb/mixer_scarlett2.c:3697:6: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
       3697 |         if (private->autogain_updated) {
            |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      sound/usb/mixer_scarlett2.c:3707:9: note: uninitialized use occurs here
       3707 |         return err;
            |                ^~~
      sound/usb/mixer_scarlett2.c:3697:2: note: remove the 'if' if its condition is always true
       3697 |         if (private->autogain_updated) {
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      sound/usb/mixer_scarlett2.c:3688:9: note: initialize the variable 'err' to silence this warning
       3688 |         int err;
            |                ^
            |                 = 0
      1 error generated.

    Initialize ret to zero to ensure ret is initialized in all paths within
    scarlett2_ag_target_ctl_get(), which matches the style of other
    functions in this driver.

    Fixes: e30ea5340c25 ("ALSA: scarlett2: Add autogain target controls")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Message-ID: <20240419-alsa-scarlett2-fix-wsometimes-uninitialized-v1-1-e2ace8642e08@kernel.org>
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>