HID: debug: Remove duplicate entry (BTN_WHEEL)
JIRA: https://issues.redhat.com/browse/RHEL-124788
Upstream Status: since v6.16

commit 04515e08bca9b5a1f9729b8d99d8b322e56d7454
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Thu Jul 10 12:41:20 2025 +0300

    HID: debug: Remove duplicate entry (BTN_WHEEL)

    BTN_WHEEL is duplicated (by value) and compiler is not happy about that:

    drivers/hid/hid-debug.c:3302:16: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
     3302 |         [BTN_WHEEL] = "BtnWheel",               [KEY_OK] = "Ok",
          |                       ^~~~~~~~~~
    drivers/hid/hid-debug.c:3301:20: note: previous initialization is here
     3301 |         [BTN_GEAR_DOWN] = "BtnGearDown",        [BTN_GEAR_UP] = "BtnGearUp",
          |                           ^~~~~~~~~~~~~

    Remove it again, as the commit 7b2daa648eb7 ("HID: debug: Remove duplicates
    from 'keys'") already did this once in the past.

    Fixes: 194808a1ea39 ("HID: Fix debug name for BTN_GEAR_DOWN, BTN_GEAR_UP, BTN_WHEEL")
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Link: https://patch.msgid.link/20250710094120.753358-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>