ASoC: wcd934x: Add missing COMMON_CLK dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: wcd934x: Add missing COMMON_CLK dependency (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.12%
commit-author Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
commit 42b716359beca10684195fd6e93a74ecd8ca8003

Looks like some platforms are not yet using COMMON CLK.

PowerPC allyesconfig failed with below error in next

ld: sound/soc/codecs/wcd934x.o:(.toc+0x0):
	 undefined reference to `of_clk_src_simple_get'
ld: sound/soc/codecs/wcd934x.o: in function `.wcd934x_codec_probe':
wcd934x.c:(.text.wcd934x_codec_probe+0x3d4):
	 undefined reference to `.__clk_get_name'
ld: wcd934x.c:(.text.wcd934x_codec_probe+0x438):
	 undefined reference to `.clk_hw_register'
ld: wcd934x.c:(.text.wcd934x_codec_probe+0x474):
	 undefined reference to `.of_clk_add_provider'

Add the missing COMMON_CLK dependency to fix this errors.

	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Link: https://lore.kernel.org/r/20200204111241.6927-1-srinivas.kandagatla@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 42b716359beca10684195fd6e93a74ecd8ca8003)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>