wifi: iwlwifi: fix #ifdef CONFIG_ACPI check
JIRA: https://issues.redhat.com/browse/RHEL-34696

commit bad9d21110037fa346426566d34dcffffc166fc6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 12 12:23:36 2024 +0100

    wifi: iwlwifi: fix #ifdef CONFIG_ACPI check
    
    The #ifdef check around the function definition for two functions was
    changed without also changing the one on the declaration:
    
    drivers/net/wireless/intel/iwlwifi/fw/uefi.c:359:6: error: redefinition of 'iwl_uefi_get_sgom_table'
      359 | void iwl_uefi_get_sgom_table(struct iwl_trans *trans,
          |      ^~~~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/net/wireless/intel/iwlwifi/fw/uefi.c:11:
    drivers/net/wireless/intel/iwlwifi/fw/uefi.h:294:6: note: previous definition of 'iwl_uefi_get_sgom_table' with type 'void(struct iwl_trans *, struct iwl_fw_runtime *)'
      294 | void iwl_uefi_get_sgom_table(struct iwl_trans *trans, struct iwl_fw_runtime *fwrt)
          |      ^~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/intel/iwlwifi/fw/uefi.c:392:5: error: redefinition of 'iwl_uefi_get_uats_table'
      392 | int iwl_uefi_get_uats_table(struct iwl_trans *trans,
          |     ^~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/intel/iwlwifi/fw/uefi.h:299:5: note: previous definition of 'iwl_uefi_get_uats_table' with type 'int(struct iwl_trans *, struct iwl_fw_runtime *)'
      299 | int iwl_uefi_get_uats_table(struct iwl_trans *trans,
          |     ^~~~~~~~~~~~~~~~~~~~~~~
    
    Adapt it by merging the declarations into the existing #ifdef block.
    
    Fixes: 74f4cd710705 ("wifi: iwlwifi: take SGOM and UATS code out of ACPI ifdef")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://msgid.link/20240212112343.1148931-1-arnd@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>