net: phy: export fixed_phy_register()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [netdrv] phy: export fixed_phy_register() (Ivan Vecera) [1382040]
Rebuild_FUZZ: 92.75%
commit-author Mark Salter <msalter@redhat.com>
commit 37e9a6904520b525b542ecd67201164d06fdb95a

When building the bcmgenet driver as module, I get:

ERROR: "fixed_phy_register" [drivers/net/ethernet/broadcom/genet/genet.ko] undefined!

commit b0ba512e225d72 ("net: bcmgenet: enable driver to work without device
tree") which added a call to fixed_phy_register. But fixed_phy_register
needs to be exported if used from a module.

	Signed-off-by: Mark Salter <msalter@redhat.com>
	Acked-by: Florian Fainelli <f.fainelli@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 37e9a6904520b525b542ecd67201164d06fdb95a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>