powerpc/pseries: Define __u{8,32} types in papr_hvpipe_hdr struct
JIRA: https://issues.redhat.com/browse/RHEL-101849

commit ef104054a312608deab266f95945057fa73eeaad
Author: Haren Myneni <haren@linux.ibm.com>
Date:   Mon Sep 22 02:11:08 2025 -0700

    powerpc/pseries: Define __u{8,32} types in papr_hvpipe_hdr struct

    Fix the the following build errors with CONFIG_UAPI_HEADER_TEST:

    ./usr/include/asm/papr-hvpipe.h:16:9: error: unknown type name 'u8'
       16 |         u8 version;
    ./usr/include/asm/papr-hvpipe.h:17:9: error: unknown type name 'u8'
       17 |         u8 reserved[3];
    ./usr/include/asm/papr-hvpipe.h:18:9: error: unknown type name 'u32'
       18 |         u32 flags;
    ./usr/include/asm/papr-hvpipe.h:19:9: error: unknown type name 'u8'
       19 |         u8 reserved2[40];

    Fixes: 043439ad1a23c ("powerpc/pseries: Define papr-hvpipe ioctl")
    Reported-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Signed-off-by: Haren Myneni <haren@linux.ibm.com>
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://patch.msgid.link/20250922091108.1483970-1-haren@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>