powerpc/maple: Fix declaration made after definition
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit af6cf95c4d003fccd6c2ecc99a598fb854b537e7

When building ppc64 defconfig, Clang errors (trimmed for brevity):

  arch/powerpc/platforms/maple/setup.c:365:1: error: attribute declaration
  must precede definition [-Werror,-Wignored-attributes]
  machine_device_initcall(maple, maple_cpc925_edac_setup);
  ^

machine_device_initcall expands to __define_machine_initcall, which in
turn has the macro machine_is used in it, which declares mach_##name
with an __attribute__((weak)). define_machine actually defines
mach_##name, which in this file happens before the declaration, hence
the warning.

To fix this, move define_machine after machine_device_initcall so that
the declaration occurs before the definition, which matches how
machine_device_initcall and define_machine work throughout
arch/powerpc.

While we're here, remove some spaces before tabs.

Fixes: 8f101a051ef0 ("edac: cpc925 MC platform device setup")
	Reported-by: Nick Desaulniers <ndesaulniers@google.com>
	Suggested-by: Ilie Halip <ilie.halip@gmail.com>
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20200323222729.15365-1-natechancellor@gmail.com
(cherry picked from commit af6cf95c4d003fccd6c2ecc99a598fb854b537e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>