usb: xhci: tegra: mark PM functions as __maybe_unused
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 3ea75b3f57e5b2837b980a2cbcf014773d00ae51
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 5 13:20:28 2021 +0200

    usb: xhci: tegra: mark PM functions as __maybe_unused

    The added #ifdefs in the PM rework were almost correct, but still
    cause warnings in some randconfig builds:

    drivers/usb/host/xhci-tegra.c:2147:12: error: 'tegra_xusb_resume' defined but not used [-Werror=unused-function]
     2147 | static int tegra_xusb_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~
    drivers/usb/host/xhci-tegra.c:2105:12: error: 'tegra_xusb_suspend' defined but not used [-Werror=unused-function]
     2105 | static int tegra_xusb_suspend(struct device *dev)

    Replace the #ifdef checks with simpler __maybe_unused annotations to
    reliably shut up these warnings.

    Link: https://lore.kernel.org/all/20210421135613.3560777-2-arnd@kernel.org/
    Fixes: 971ee247060d ("usb: xhci: tegra: Enable ELPG for runtime/system PM")
    Reviewed-by: JC Kuo <jckuo@nvidia.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211005112057.2700888-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>