bridge: remove unnecessary check for vtbegin in br_fill_vlan_tinfo_range
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Roopa Prabhu <roopa@cumulusnetworks.com>
commit a8cab863a75f2d353588d4c3c37dc37c77b96c83

vtbegin should not be NULL in this function, Its already checked by the
caller.

this should silence the below smatch complaint:
  net/bridge/br_netlink_tunnel.c:144 br_fill_vlan_tinfo_range()
    error: we previously assumed 'vtbegin' could be null (see line 130)

net/bridge/br_netlink_tunnel.c
   129
   130      if (vtbegin && vtend && (vtend->vid - vtbegin->vid) > 0) {
                    ^^^^^^^
Check for NULL.

Fixes: efa5356b0d97 ("bridge: per vlan dst_metadata netlink support")
Reported-By: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Roopa Prabhu <roopa@cumulusnetworks.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit a8cab863a75f2d353588d4c3c37dc37c77b96c83)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>