tools/testing/selftests/vm/split_huge_page_test.c: fix application of sizeof to pointer
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2028891

This patch is a backport of the following upstream commit:
commit 9c7516d669e68e94e17203469a873ff5d1d3a41a
Author: David Yang <davidcomponentone@gmail.com>
Date:   Thu Oct 28 14:36:36 2021 -0700

    tools/testing/selftests/vm/split_huge_page_test.c: fix application of sizeof to pointer

    The coccinelle check report:

      ./tools/testing/selftests/vm/split_huge_page_test.c:344:36-42:
      ERROR: application of sizeof to pointer

    Use "strlen" to fix it.

    Link: https://lkml.kernel.org/r/20211012030116.184027-1-davidcomponentone@gmail.com
    Signed-off-by: David Yang <davidcomponentone@gmail.com>
    Reported-by: Zeal Robot <zealci@zte.com.cn>
    Cc: Zi Yan <ziy@nvidia.com>
    Cc: Shuah Khan <shuah@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>