IB/core, cma: Make __attribute_const__ declarations sparse-friendly
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Bart Van Assche <bart.vanassche@sandisk.com>
commit db7489e07669073970358b6cacf6a9dd8dc9275e

Move the __attribute_const__ declarations such that sparse understands
that these apply to the function itself and not to the return type.
This avoids that sparse reports error messages like the following:

drivers/infiniband/core/verbs.c:73:12: error: symbol 'ib_event_msg' redeclared with different type (originally declared at include/rdma/ib_verbs.h:470) - different modifiers

Fixes: 2b1b5b601230 ("IB/core, cma: Nice log-friendly string helpers")
	Signed-off-by: Bart Van Assche <bart.vanassche@sandisk.com>
	Cc: Sagi Grimberg <sagig@mellanox.com>
	Reviewed-by: Sagi Grimberg <sagig@mellanox.com>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit db7489e07669073970358b6cacf6a9dd8dc9275e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>