firmware: arm_scmi: Convert to SYSTEM_SLEEP_PM_OPS
JIRA: https://issues.redhat.com/browse/RHEL-120360

commit 62d6b81e8bd207ad44eff39d1a0fe17f0df510a5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jul 9 09:01:01 2025 +0200

    firmware: arm_scmi: Convert to SYSTEM_SLEEP_PM_OPS

    The old SET_SYSTEM_SLEEP_PM_OPS() macro leads to a warning about an
    unused function:

      |  drivers/firmware/arm_scmi/scmi_power_control.c:363:12: error:
      |     'scmi_system_power_resume' defined but not used [-Werror=unused-function]
      |         static int scmi_system_power_resume(struct device *dev)

    The proper way to do this these days is to use SYSTEM_SLEEP_PM_OPS()
    and pm_sleep_ptr().

    Fixes: 9a0658d3991e ("firmware: arm_scmi: power_control: Ensure SCMI_SYSPOWER_IDLE is set early during resume")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Peng Fan <peng.fan@nxp.com>
    Message-Id: <20250709070107.1388512-1-arnd@kernel.org>
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>

(cherry picked from commit 62d6b81e8bd207ad44eff39d1a0fe17f0df510a5)
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>