net: stmmac: dwmac-meson8b: Avoid cast to incompatible function type
JIRA: https://issues.redhat.com/browse/RHEL-6297

commit 43bb6100d8d5871d211196034042308c1b1d69c3
Author: Simon Horman <horms@kernel.org>
Date:   Tue Apr 18 13:07:33 2023 +0200

    net: stmmac: dwmac-meson8b: Avoid cast to incompatible function type

    Rather than casting clk_disable_unprepare to an incompatible function
    type provide a trivial wrapper with the correct signature for the
    use-case.

    Reported by clang-16 with W=1:

     drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c:276:6: error: cast from 'void (*)(struct clk *)' to 'void (*)(void *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
                                            (void(*)(void *))clk_disable_unprepare,
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    No functional change intended.
    Compile tested only.

    Signed-off-by: Simon Horman <horms@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Link: https://lore.kernel.org/r/20230418-dwmac-meson8b-clk-cb-cast-v1-1-e892b670cbbb@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>