qed: select ZLIB_INFLATE
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 4bdb96cb69d9e4c6038a976fa9def9f8ae024ff8

The newly added qlogic qed driver uses the zlib library, but
misses the dependency:

drivers/built-in.o: In function `qed_alloc_stream_mem':
drivers/net/ethernet/qlogic/qed/qed_main.c:707: undefined reference to `zlib_inflate_workspacesize'
drivers/built-in.o: In function `qed_unzip_data':
drivers/net/ethernet/qlogic/qed/qed_main.c:675: undefined reference to `zlib_inflateInit2'

This changes Kconfig to always select zlib when needed.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: fe56b9e6a8d9 ("qed: Add module with basic common support")
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 4bdb96cb69d9e4c6038a976fa9def9f8ae024ff8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>