perf/amlogic: Fix build error for x86_64 allmodconfig
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2217547

commit 7299fdc1cfff0e45e4ca4efd77f250965598b41c
Author: Jiucheng Xu <jiucheng.xu@amlogic.com>
Date: Tue, 22 Nov 2022 16:40:28 +0800

    The driver misses including <linux/io.h>, which causes a compilation
    error with x86_64 'allmodconfig':

    drivers/perf/amlogic/meson_g12_ddr_pmu.c: In function 'dmc_g12_get_freq_quick':
    drivers/perf/amlogic/meson_g12_ddr_pmu.c:135:15: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]
      135 |         val = readl(info->pll_reg);
          |               ^~~~~
    drivers/perf/amlogic/meson_g12_ddr_pmu.c: In function 'dmc_g12_counter_enable':
    drivers/perf/amlogic/meson_g12_ddr_pmu.c:204:9: error: implicit declaration of function 'writel' [-Werror=implicit-function-declaration]
      204 |         writel(clock_count, info->ddr_reg[0] + DMC_MON_G12_TIMER);
          |         ^~~~~~

    Add the missing header to fix the build.

    Fixes: 2016e2113d35 ("perf/amlogic: Add support for Amlogic meson G12 SoC DDR PMU driver")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Jiucheng Xu <jiucheng.xu@amlogic.com>
    Reviewed-by: Neil Armstrong <neil.armstrong@linaro.org>
    Link: https://lore.kernel.org/r/20221122084028.572494-1-jiucheng.xu@amlogic.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>