net: phy: marvell: Fix build.
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [netdrv] phy: marvell: Fix build (Petr Oros) [1772010]
Rebuild_FUZZ: 88.46%
commit-author David S. Miller <davem@davemloft.net>
commit 4b1bd69769454175268908f50b32f1cbfee5bb83

Local variable 'autoneg' doesn't even exist:

drivers/net/phy/marvell.c: In function 'm88e1121_config_aneg':
drivers/net/phy/marvell.c:468:25: error: 'autoneg' undeclared (first use in this function); did you mean 'put_net'?
  if (phydev->autoneg != autoneg || changed) {
                         ^~~~~~~

Fixes: d6ab93364734 ("net: phy: marvell: Avoid unnecessary soft reset")
	Reported-by:Vakul Garg <vakul.garg@nxp.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 4b1bd69769454175268908f50b32f1cbfee5bb83)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>