ASoC: codecs: tas2764: Fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-112755

commit c23c7c60711e34963c78f18fc3b9aaa313b6c8ce
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Sun Apr 27 12:51:07 2025 +0200

    ASoC: codecs: tas2764: Fix Wvoid-pointer-to-enum-cast warning

    'devid' is an enum, thus cast of pointer on 64-bit compile test with
    clang and W=1 causes:

      tas2764.c:879:19: error: cast to smaller integer type 'enum tas2764_devid' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    One of the discussions in 2023 on LKML suggested warning is not suitable
    for kernel.  Nothing changed in this regard for more than a year, so
    assume the warning will stay and we want to have warnings-free builds.

    Link: https://lore.kernel.org/all/20230814160457.GA2836@dev-arch.thelio-3990X/
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://patch.msgid.link/20250427105105.18164-4-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>