mm/page_alloc: mark pagesets as __maybe_unused
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2064990

This patch is a backport of the following upstream commit:
commit a4812d47deff0642b3315f0528d579f0a99c45c2
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Mar 22 14:43:23 2022 -0700

    mm/page_alloc: mark pagesets as __maybe_unused

    Commit 9983a9d577db ("locking/local_lock: Make the empty local_lock_*()
    function a macro.") in the -tip tree converted the local_lock_*()
    functions into macros, which causes a warning with clang with
    CONFIG_PREEMPT_RT=n + CONFIG_DEBUG_LOCK_ALLOC=n:

      mm/page_alloc.c:131:40: error: variable 'pagesets' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
      static DEFINE_PER_CPU(struct pagesets, pagesets) = {
                                             ^
      1 error generated.

    Prior to that change, clang was not able to tell that pagesets was
    unused in this configuration because it does not perform cross function
    analysis in the frontend.  After that change, it sees that the macros
    just do a typecheck on the lock member of pagesets, which is evaluated
    at compile time (so the variable is technically "used"), meaning the
    variable is not needed in the final assembly, as the warning states.

    Mark the variable as __maybe_unused to make it clear to clang that this
    is expected in this configuration so there is no more warning.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1593
    Link: https://lkml.kernel.org/r/20220215184322.440969-1-nathan@kernel.org
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Suggested-by: Nick Desaulniers <ndesaulniers@google.com>
    Reported-by: "kernelci.org bot" <bot@kernelci.org>
    Cc: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>