perf strbuf: Match va_{add,copy} with va_end
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [tools] perf strbuf: Match va_{add, copy} with va_end (Jiri Olsa) [1680074]
Rebuild_FUZZ: 98.88%
commit-author Sanskriti Sharma <sansharm@redhat.com>
commit ce49d8436cffa9b7a6a5f110879d53e89dbc6746

Ensure that all code paths in strbuf_addv() call va_end() on the
ap_saved copy that was made.

Fixes the following coverity complaint:

  Error: VARARGS (CWE-237): [#def683]
  tools/perf/util/strbuf.c:106: missing_va_end: va_end was not called
  for "ap_saved".

	Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
	Reviewed-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Joe Lawrence <joe.lawrence@redhat.com>
Link: http://lkml.kernel.org/r/1538490554-8161-2-git-send-email-sansharm@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit ce49d8436cffa9b7a6a5f110879d53e89dbc6746)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>