scripts/gdb: fix usage of MOD_TEXT not defined when CONFIG_MODULES=n
JIRA: https://issues.redhat.com/browse/RHEL-28063

commit 16501630bdeb107141a0139ddc33f92ab5582c6f
Author: Clément Léger <cleger@rivosinc.com>
Date:   Tue Oct 31 13:49:04 2023 +0000

    scripts/gdb: fix usage of MOD_TEXT not defined when CONFIG_MODULES=n

    MOD_TEXT is only defined if CONFIG_MODULES=y which lead to loading failure
    of the gdb scripts when kernel is built without CONFIG_MODULES=y:

    Reading symbols from vmlinux...
    Traceback (most recent call last):
      File "/foo/vmlinux-gdb.py", line 25, in <module>
        import linux.constants
      File "/foo/scripts/gdb/linux/constants.py", line 14, in <module>
        LX_MOD_TEXT = gdb.parse_and_eval("MOD_TEXT")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    gdb.error: No symbol "MOD_TEXT" in current context.

    Add a conditional check on CONFIG_MODULES to fix this error.

    Link: https://lkml.kernel.org/r/20231031134848.119391-1-da.gomez@samsung.com
    Fixes: b4aff7513df3 ("scripts/gdb: use mem instead of core_layout to get the module address")
    Signed-off-by: Clément Léger <cleger@rivosinc.com>
    Tested-by: Daniel Gomez <da.gomez@samsung.com>
    Signed-off-by: Daniel Gomez <da.gomez@samsung.com>
    Cc: Jan Kiszka <jan.kiszka@siemens.com>
    Cc: Kieran Bingham <kbingham@kernel.org>
    Cc: Luis Chamberlain <mcgrof@kernel.org>
    Cc: Pankaj Raghav <p.raghav@samsung.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>