fpga: zynqmp-fpga: Correctly handle error pointer
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Moritz Fischer <mdf@kernel.org>
commit 498ddaa3b4e72152ae42dab2d4ebe93092885422

Fixes the following static checker errors:

drivers/fpga/zynqmp-fpga.c:50 zynqmp_fpga_ops_write()
error: 'eemi_ops' dereferencing possible ERR_PTR()

drivers/fpga/zynqmp-fpga.c:84 zynqmp_fpga_ops_state()
error: 'eemi_ops' dereferencing possible ERR_PTR()

Note: This does not handle the EPROBE_DEFER value in a
      special manner.

Fixes commit c09f7471127e ("fpga manager: Adding FPGA Manager support for
Xilinx zynqmp")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Moritz Fischer <mdf@kernel.org>
	Acked-by: Alan Tull <atull@kernel.org>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 498ddaa3b4e72152ae42dab2d4ebe93092885422)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>