locking/lockdep: Avoid bogus Clang warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 3771b0fe9dfc3801eac0142d1af6ba94dee83c6c

When lockdep is enabled, and -Wuninitialized warnings are enabled,
Clang produces a silly warning for every file we compile:

 In file included from  kernel/sched/fair.c:23:
  kernel/sched/sched.h:1094:15: error: variable 'cookie' is uninitialized when used here [-Werror,-Wuninitialized]
         rf->cookie = lockdep_pin_lock(&rq->lock);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  include/linux/lockdep.h:474:60: note: expanded from macro 'lockdep_pin_lock'
  #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                                             ^~~~~~
  kernel/sched/sched.h:1094:15: note: variable 'cookie' is declared here
  include/linux/lockdep.h:474:34: note: expanded from macro 'lockdep_pin_lock'
  #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                    ^

As the 'struct pin_cookie' structure is empty in this configuration,
there is no need to initialize it for correctness, but it also
does not hurt to set it to an empty structure, so do that to
avoid the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Will Deacon <will.deacon@arm.com>
	Cc: Bart Van Assche <bvanassche@acm.org>
	Cc: Joel Fernandes (Google) <joel@joelfernandes.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Nathan Chancellor <natechancellor@gmail.com>
	Cc: Nick Desaulniers <ndesaulniers@google.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Steven Rostedt (VMware) <rostedt@goodmis.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: Waiman Long <longman@redhat.com>
	Cc: clang-built-linux@googlegroups.com
Link: http://lkml.kernel.org/r/20190325125807.1437049-1-arnd@arndb.de
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 3771b0fe9dfc3801eac0142d1af6ba94dee83c6c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>