arm64: efi: add efi_handle_corrupted_x18 prototype
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit fbc0cd6f60443264af0b7aed050cae2ef38036f9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:35 +0200

    This functions is only called from assembler and lacks a prototype,
    which is seen from this W=1 warning:

    arch/arm64/kernel/efi.c:155:25: error: no previous prototype for 'efi_handle_corrupted_x18' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-9-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>