[CIFS] Fix build warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [fs] cifs: Fix build warning (Sachin Prabhu) [988398]
Rebuild_FUZZ: 93.62%
commit-author Steve French <smfrench@gmail.com>
commit e65a5cb41718e0eb17a470bc3acf2c3b2f00f1d0

Fix build warning in Shirish's recent SMB3 signing patch
which occurs when SMB2 support is disabled in Kconfig.

fs/built-in.o: In function `cifs_setup_session':
>> (.text+0xa1767): undefined reference to `generate_smb3signingkey'

Pointed out by: automated 0-DAY kernel build testing backend
Intel Open Source Technology Center

CC: Shirish Pargaonkar <shirishpargaonkar@gmail.com>
	Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit e65a5cb41718e0eb17a470bc3acf2c3b2f00f1d0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>