ASoC: ak4458: Add ak4458_reset in device probe and remove
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Shengjiu Wang <shengjiu.wang@nxp.com>
commit da995e22fa7193b067f2545e63d726ffe36ba174

This patch fixup this warning when CONFIG_PM not defined

linux/sound/soc/codecs/ak4458.c:631:13: error: 'ak4458_reset' defined but\
        not used [-Werror=unused-function]
  631 | static void ak4458_reset(struct ak4458_priv *ak4458, bool active)
      |             ^~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: e9e7df88996d64 ("ASoC: ak4458: Remove component probe() and remove()")
	Reported-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
	Signed-off-by: Shengjiu Wang <shengjiu.wang@nxp.com>
Link: https://lore.kernel.org/r/1663057594-29141-1-git-send-email-shengjiu.wang@nxp.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit da995e22fa7193b067f2545e63d726ffe36ba174)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>