arm64: alternatives: Use vdso/bits.h instead of linux/bits.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2167398

commit d2995249a2f72333a4ab4922ff3c42a76c023791
Author: Nathan Chancellor <nathan@kernel.org>
Date: Mon, 3 Oct 2022 12:37:59 -0700

    When building with CONFIG_LTO after commit ba00c2a04fa5 ("arm64: fix the
    build with binutils 2.27"), the following build error occurs:

      In file included from arch/arm64/kernel/module-plts.c:6:
      In file included from include/linux/elf.h:6:
      In file included from arch/arm64/include/asm/elf.h:8:
      In file included from arch/arm64/include/asm/hwcap.h:9:
      In file included from arch/arm64/include/asm/cpufeature.h:9:
      In file included from arch/arm64/include/asm/alternative-macros.h:5:
      In file included from include/linux/bits.h:22:
      In file included from include/linux/build_bug.h:5:
      In file included from include/linux/compiler.h:248:
      In file included from arch/arm64/include/asm/rwonce.h:71:
      include/asm-generic/rwonce.h:67:9: error: expected string literal in 'asm'
              return __READ_ONCE(*(unsigned long *)addr);
                    ^
      arch/arm64/include/asm/rwonce.h:43:16: note: expanded from macro '__READ_ONCE'
                      asm volatile(__LOAD_RCPC(b, %w0, %1)                    \
                                  ^
      arch/arm64/include/asm/rwonce.h:17:2: note: expanded from macro '__LOAD_RCPC'
              ALTERNATIVE(                                                    \
              ^

    Similar to the issue resolved by commit 0072dc1b53c3 ("arm64: avoid
    BUILD_BUG_ON() in alternative-macros"), there is a circular include
    dependency through <linux/bits.h> when CONFIG_LTO is enabled due to
    <asm/rwonce.h> appearing in the include chain before the contents of
    <asm/alternative-macros.h>, which results in ALTERNATIVE() not getting
    expanded properly because it has not been defined yet.

    Avoid this issue by including <vdso/bits.h>, which includes the
    definition of the BIT() macro, instead of <linux/bits.h>, as BIT() is the
    only macro from bits.h that is relevant to this header.

    Fixes: ba00c2a04fa5 ("arm64: fix the build with binutils 2.27")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1728
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Tested-by: Will Deacon <will@kernel.org>
    Link: https://lore.kernel.org/r/20221003193759.1141709-1-nathan@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>