drm/amd/ras: Fix type size of remainder argument
JIRA: https://redhat.atlassian.net/browse/RHEL-180328

commit d8f3d78ca63cacfe3d8c117023dff3c8f0e9a846
Author: Kees Cook <kees@kernel.org>
Date:   Wed Feb 25 09:47:03 2026 -0800

    drm/amd/ras: Fix type size of remainder argument

    [ Upstream commit 9f3d543a9f7371622aff389e69010ac6bac69ef8 ]

    Forcing an int to be dereferenced at uint64_t for div64_u64_rem() runs
    the risk of endian confusion and stack overflowing writes. Seen while
    preparing to enable -Warray-bounds globally:

    In file included from ../arch/x86/include/asm/processor.h:35,
                     from ../include/linux/sched.h:13,
                     from ../include/linux/ratelimit.h:6,
                     from ../include/linux/dev_printk.h:16,
                     from ../drivers/gpu/drm/amd/amdgpu/../ras/ras_mgr/ras_sys.h:29,
                     from ../drivers/gpu/drm/amd/amdgpu/../ras/rascore/ras.h:27,
                     from ../drivers/gpu/drm/amd/amdgpu/../ras/rascore/ras_core.c:24:
    In function 'div64_u64_rem',
        inlined from 'ras_core_convert_timestamp_to_time' at ../drivers/gpu/drm/amd/amdgpu/../ras/rascore/ras_core.c:72:9:
    ../include/linux/math64.h:56:20: error: array subscript 'u64 {aka long long unsigned int}[0]' is partly outside array bounds of 'int[1]' [-Werror=array-bounds=]
       56 |         *remainder = dividend % divisor;
          |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    ../drivers/gpu/drm/amd/amdgpu/../ras/rascore/ras_core.c: In function 'ras_core_convert_timestamp_to_time':
    ../drivers/gpu/drm/amd/amdgpu/../ras/rascore/ras_core.c:70:19: note: object 'remaining_seconds' of size 4
       70 |         int days, remaining_seconds;
          |                   ^~~~~~~~~~~~~~~~~

    Use a 64-bit type for the remainder calculation, but leave
    remaining_seconds as 32-bit to avoid 64-bit division later. The value of
    remainder will always be less than seconds_per_day, so there's no
    truncation risk.

    Fixes: ace232eff50e ("drm/amdgpu: Add ras module files into amdgpu")
    Signed-off-by: Kees Cook <kees@kernel.org>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>