ntb: idt: fix clang -Wformat warnings
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2179137
Upstream Status: a44252d5c3bbd76efa7b65819712f0e2b1de54c0

commit a44252d5c3bbd76efa7b65819712f0e2b1de54c0
Author: Justin Stitt <justinstitt@google.com>
Date:   Mon Jul 11 16:01:48 2022 -0700

    ntb: idt: fix clang -Wformat warnings

    When building with Clang we encounter these warnings:
    | drivers/ntb/hw/idt/ntb_hw_idt.c:2409:28: error: format specifies type
    | 'unsigned char' but the argument has type 'int' [-Werror,-Wformat]
    | "\t%hhu-%hhu.\t", idx + cnt - 1);
    -
    | drivers/ntb/hw/idt/ntb_hw_idt.c:2438:29: error: format specifies type
    | 'unsigned char' but the argument has type 'int' [-Werror,-Wformat]
    | "\t%hhu-%hhu.\t", idx + cnt - 1);
    -
    | drivers/ntb/hw/idt/ntb_hw_idt.c:2484:15: error: format specifies type
    | 'unsigned char' but the argument has type 'int' [-Werror,-Wformat], src);

    For the first two warnings the format specifier used is `%hhu` which
    describes a u8. Both `idx` and `cnt` are u8 as well. However, the
    expression as a whole is promoted to an int as you cannot get
    smaller-than-int from addition. Therefore, to fix the warning, use the
    promoted-to-type's format specifier -- in this case `%d`.

    example:
    ``
    uint8_t a = 4, b = 7;
    int size = sizeof(a + b - 1);
    printf("%d\n", size);
    // output: 4
    ```

    For the last warning, src is of type `int` while the format specifier
    describes a u8. The fix here is just to use the proper specifier `%d`.

    See more:
    (https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules)
    "Integer types smaller than int are promoted when an operation is
    performed on them. If all values of the original type can be represented
    as an int, the value of the smaller type is converted to an int;
    otherwise, it is converted to an unsigned int."

    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Acked-by: Serge Semin <fancer.lancer@gmail.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

Signed-off-by: Myron Stowe <mstowe@redhat.com>