sched: Add schedule_user() declaration
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-521.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 378be384e01f13fc44d0adc70873de525586ad74

The schedule_user() function is used on powerpc and sparc architectures, but
only ever called from assembler, so it has no prototype, causing a harmless W=1
warning:

kernel/sched/core.c:6730:35: error: no previous prototype for 'schedule_user' [-Werror=missing-prototypes]

Add a prototype in sched/sched.h to shut up the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Reviewed-by: Vincent Guittot <vincent.guittot@linaro.org>
Link: https://lore.kernel.org/r/20230522195021.3456768-3-arnd@kernel.org
(cherry picked from commit 378be384e01f13fc44d0adc70873de525586ad74)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>