ASoC: davinci-mcasp: Fix clang warning without CONFIG_PM
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: davinci-mcasp: Fix clang warning without CONFIG_PM (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.92%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 8ca5104715cfd14254ea5aecc390ae583b707607

Building with clang shows a variable that is only used by the
suspend/resume functions but defined outside of their #ifdef block:

sound/soc/ti/davinci-mcasp.c:48:12: error: variable 'context_regs' is not needed and will not be emitted

We commonly fix these by marking the PM functions as __maybe_unused,
but here that would grow the davinci_mcasp structure, so instead
add another #ifdef here.

Fixes: 1cc0c054f380 ("ASoC: davinci-mcasp: Convert the context save/restore to use array")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 8ca5104715cfd14254ea5aecc390ae583b707607)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>