Revert "drm/sysfb: Find screen_info format with helpers"
JIRA: https://issues.redhat.com/browse/RHEL-125801
Upstream Status: RHEL only

This reverts commit 31eea29d727ce35b747e68c6be350ca07b7ecd9b.

This commit was backported automatically as part of the DRM backport.

The reverted commit uses 2 video helpers not present in this tree:
screen_info_pixel_format() and pixel_format_equal().

While backporting the helpers can be easily done by picking upstream
commits 5f24434fe3bd3 ("video: pixel_format: Add compare helpers") and
898e91ebdedd0 ("video: screen_info: Add pixel-format helper for linear
framebuffers"), the latter forward declares the struct "pixel_format"
in a header, causing this compile error:

	In file included from drivers/gpu/drm/amd/amdgpu/../display/dc/dc_types.h:38,
		         from drivers/gpu/drm/amd/amdgpu/../display/dc/dm_services_types.h:30,
		         from drivers/gpu/drm/amd/amdgpu/../include/dm_pp_interface.h:26,
		         from drivers/gpu/drm/amd/amdgpu/amdgpu.h:62,
		         from drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c:43:
	drivers/gpu/drm/amd/amdgpu/../display/dc/dc_hw_types.h:221:6:
	error: ‘pixel_format’ defined as wrong kind of tag
	  221 | enum pixel_format {
	      |      ^~~~~~~~~~~~

Fixing it would require backporting b36f1c85e0a19 ("x86: Do not include
<asm/bootparam.h> in several files") and a bunch of follow up fixes.

To avoid pulling a big number of changes, revert this patch.

NOTE: This commit does not compile due to missing RHEL-specific fix-ups,
which are split out into separate Git commits following this one.

If git bisect selected this commit, run "git bisect skip" and try again.
Repeat this until it selects a commit which compiles.

Signed-off-by: José Expósito <jexposit@redhat.com>