ath11k: fix compiler warnings without CONFIG_THERMAL
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit c9be1a642a7b9ec021e3f32e084dc781b3e5216d

drivers/net/wireless/ath/ath11k/thermal.h:45:1:
 warning: no return statement in function returning non-void [-Wreturn-type]
drivers/net/wireless/ath/ath11k/core.c:416:28: error:
 passing argument 1 of 'ath11k_thermal_unregister' from incompatible pointer type [-Werror=incompatible-pointer-types]

Add missing return 0 in ath11k_thermal_set_throttling,
and fix ath11k_thermal_unregister param type.

Fixes: 2a63bbca06b2 ("ath11k: add thermal cooling device support")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20200403083414.31392-1-yuehaibing@huawei.com
(cherry picked from commit c9be1a642a7b9ec021e3f32e084dc781b3e5216d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>