perf tools: Fix compiler error in util/tool_pmu.c
JIRA: https://issues.redhat.com/browse/RHEL-77935

upstream
========
commit 1a3d6a9723d4dbdad41dad67b66a64d4a84c5f5c
Author: Namhyung Kim <namhyung@kernel.org>
Date: Mon Oct 14 10:34:17 2024 -0700

description
===========
  util/tool_pmu.c: In function 'evsel__tool_pmu_read':
  util/tool_pmu.c:419:55: error: passing argument 2 of 'tool_pmu__read_event' from incompatible pointer type [-Werror=incompatible-pointer-types]
    419 |                         if (!tool_pmu__read_event(ev, &val)) {
        |                                                       ^~~~
        |                                                       |
        |                                                       long unsigned int *
  util/tool_pmu.c:335:56: note: expected 'u64 *' {aka 'long long unsigned int *'} but argument is of type 'long unsigned int *'
    335 | bool tool_pmu__read_event(enum tool_pmu_event ev, u64 *result)
        |                                                   ~~~~~^~~~~~

    Link: https://lore.kernel.org/r/Zw1XIGML32VaxE0t@google.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>