perf tests: Fix compile failure on do_sort_something
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [tools] perf/tests: Fix compile failure on do_sort_something (Jiri Olsa) [1036665]
Rebuild_FUZZ: 98.08%
commit-author David Ahern <dsahern@gmail.com>
commit 309b5185047c5309bbc576025f6c5e257edd9f69

Commit b55ae0a9 added code-reading.c which fails to compile on Fedora 16
with compiler version:
$ gcc --version
gcc (GCC) 4.6.3 20120306 (Red Hat 4.6.3-2)

Failure message is:

tests/code-reading.c: In function ‘do_sort_something’:
tests/code-reading.c:305:13: error: stack protector not protecting local variables: variable length buffer [-Werror=stack-protector]
cc1: all warnings being treated as errors
make: *** [/tmp/junk/tests/code-reading.o] Error 1
make: *** Waiting for unfinished jobs....

v2: as Adrian noticed changed sizeof to ARRAY_SIZE

	Signed-off-by: David Ahern <dsahern@gmail.com>
	Acked-by: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
Link: http://lkml.kernel.org/r/1376454732-83728-1-git-send-email-dsahern@gmail.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 309b5185047c5309bbc576025f6c5e257edd9f69)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>