signal.h: add linux/signal.h and asm/signal.h to UAPI compile-test coverage
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 72113d0a7d90d950c7c9a87ab905bffb6bc5752d
Author: Masahiro Yamada <masahiroy@kernel.org>
Date:   Thu Feb 10 11:11:24 2022 +0900

    signal.h: add linux/signal.h and asm/signal.h to UAPI compile-test coverage

    linux/signal.h and asm/signal.h are currently excluded from the UAPI
    compile-test because of the errors like follows:

        HDRTEST usr/include/asm/signal.h
      In file included from <command-line>:
      ./usr/include/asm/signal.h:103:9: error: unknown type name ‘size_t’
        103 |         size_t ss_size;
            |         ^~~~~~

    The errors can be fixed by replacing size_t with __kernel_size_t.

    Then, remove the no-header-test entries from user/include/Makefile.

    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Omitted-fix: be92e1ded1d1 sparc64: fix building assembly files
	sparc64 is not supported in RHEL0

Signed-off-by: Prarit Bhargava <prarit@redhat.com>