ASoC: amd: acp: Add new cpu dai's in machine driver
Bugzilla: https://bugzilla.redhat.com/2179848

commit 099b923fc15d8faa91c5fc1b46cbc483d034f5dc
Author: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Date: Mon Jan 9 18:51:00 2023 +0530

    ASoC: amd: acp: Add new cpu dai's in machine driver

    when using same cpu dai for 2 different dai links
    below error is reported.
    error: can't find BE for DAI ACPHS_VIRTUAL1.OUT

    To avoid this error add new cpu dai.

    Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
    Link: https://lore.kernel.org/r/20230109132104.1259479-2-venkataprasad.potturu@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>