soundwire: qcom: use __maybe_unused for swrm_runtime_resume()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
commit 266fa94673d325f489f74d0a9a12024a7f1ee49c

swrm_runtime_resume() would not be defined when CONFIG_PM=n

This causes below build failure
drivers/soundwire/qcom.c:1460:12: error: 'swrm_runtime_resume' defined
but not used [-Werror=unused-function]

Mark the resume swrm_runtime_resume() with  __maybe_unused attribute.

	Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Link: https://lore.kernel.org/r/20220303110321.23666-1-srinivas.kandagatla@linaro.org
[redo commit title and log]
	Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit 266fa94673d325f489f74d0a9a12024a7f1ee49c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>