IB/mlx5: Fix undefined behavior due to shift overflowing the constant
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Borislav Petkov <bp@suse.de>
commit 0276bd3a94c072de3f69b5afe6224e488cc76635

Fix:

  drivers/infiniband/hw/mlx5/main.c: In function ‘translate_eth_legacy_proto_oper’:
  drivers/infiniband/hw/mlx5/main.c:370:2: error: case label does not reduce to an integer constant
    case MLX5E_PROT_MASK(MLX5E_50GBASE_KR2):
    ^~~~

See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
details as to why it triggers with older gccs only.

Link: https://lore.kernel.org/all/20220405151517.29753-11-bp@alien8.de
	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Leon Romanovsky <leon@kernel.org>
	Cc: Saeed Mahameed <saeedm@nvidia.com>
	Cc: linux-rdma@vger.kernel.org
	Cc: netdev@vger.kernel.org
	Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
(cherry picked from commit 0276bd3a94c072de3f69b5afe6224e488cc76635)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>