x86/fbdev: Include asm/fb.h as needed
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 29bf464cb8ee1b119d23aec88cbf17f9941610ad
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:43 2023 +0200

    x86/fbdev: Include asm/fb.h as needed

    fb_is_primary_device() is defined as a global function on x86, unlike
    the others that have an inline version. The file that defines is
    however needs to include the declaration to avoid a warning:

    arch/x86/video/fbdev.c:14:5: error: no previous prototype for 'fb_is_primary_device' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-15-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>