ASoC: Fix SND_SOC_ALL_CODECS imply ac97 fallout
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: Fix SND_SOC_ALL_CODECS imply ac97 fallout (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.00%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 5a309875787db47d69610e45f00a727ef9e62aa0

On i386 randconfig:

    sound/soc/codecs/wm9705.o: In function `wm9705_soc_resume':
    wm9705.c:(.text+0x128): undefined reference to `snd_ac97_reset'
    sound/soc/codecs/wm9712.o: In function `wm9712_soc_resume':
    wm9712.c:(.text+0x2d1): undefined reference to `snd_ac97_reset'
    sound/soc/codecs/wm9713.o: In function `wm9713_soc_resume':
    wm9713.c:(.text+0x820): undefined reference to `snd_ac97_reset'

Fix this by adding the missing dependencies on SND_SOC_AC97_BUS.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/r/20200224112537.14483-1-geert@linux-m68k.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 5a309875787db47d69610e45f00a727ef9e62aa0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>