PCI/MSI: Provide missing stub for pci_msix_can_alloc_dyn()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2188822
Upstream Status: 195d8e5da3acb17c5357526494f818a21e97cd10

commit 195d8e5da3acb17c5357526494f818a21e97cd10
Author: Reinette Chatre <reinette.chatre@intel.com>
Date:   Wed Mar 29 13:13:11 2023 -0700

    PCI/MSI: Provide missing stub for pci_msix_can_alloc_dyn()

    pci_msix_can_alloc_dyn() is not declared when CONFIG_PCI_MSI is disabled.

    There is no existing user of pci_msix_can_alloc_dyn() but work is in
    progress to change this. This work encounters the following error when
    CONFIG_PCI_MSI is disabled:

      drivers/vfio/pci/vfio_pci_intrs.c:427:21: error: implicit declaration of function 'pci_msix_can_alloc_dyn' [-Werror=implicit-function-declaration]

    Provide definition for pci_msix_can_alloc_dyn() in preparation for users
    that need to compile when CONFIG_PCI_MSI is disabled.

    [bhelgaas: Also reported by Arnd Bergmann <arnd@kernel.org> in
    drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c; added his Fixes: line]

    Fixes: fb0a6a268dcd ("net/mlx5: Provide external API for allocating vectors")
    Fixes: 34026364df8e ("PCI/MSI: Provide post-enable dynamic allocation interfaces for MSI-X")
    Link: https://lore.kernel.org/oe-kbuild-all/202303291000.PWFqGCxH-lkp@intel.com/
    Link: https://lore.kernel.org/r/310ecc4815dae4174031062f525245f0755c70e2.1680119924.git.reinette.chatre@intel.com
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Reinette Chatre <reinette.chatre@intel.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Reviewed-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>
    Cc: stable@vger.kernel.org      # v6.2+

Signed-off-by: Myron Stowe <mstowe@redhat.com>