power: reset: pwr-mlxbf: add missing include
jira LE-1907
Rebuild_History Non-Buildable kernel-5.14.0-427.16.1.el9_4
commit-author Asmaa Mnebhi <asmaa@nvidia.com>
commit a5a3d94fc4edecb894bc79810aea511ff9261c09

Add missing include for devm_work_autocancel to fix build error:

drivers/power/reset/pwr-mlxbf.c: In function 'pwr_mlxbf_probe':
drivers/power/reset/pwr-mlxbf.c:67:15: error: implicit declaration of function 'devm_work_autocancel' [-Werror=implicit-function-declaration]
   67 |         err = devm_work_autocancel(dev, &priv->send_work, pwr_mlxbf_send_work);
      |               ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: a4c0094fcf76 ("power: reset: pwr-mlxbf: add BlueField SoC power control driver")
	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Asmaa Mnebhi <asmaa@nvidia.com>
	Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>
(cherry picked from commit a5a3d94fc4edecb894bc79810aea511ff9261c09)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>