tools: ynl: throw a more meaningful exception if family not supported
JIRA: https://issues.redhat.com/browse/RHEL-30656

commit ebe3bdc4359e07b4e347af8d5324fb436302bbe1
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Fri Apr 7 07:56:09 2023 -0700

    tools: ynl: throw a more meaningful exception if family not supported

    cli.py currently throws a pure KeyError if kernel doesn't support
    a netlink family. Users who did not write ynl (hah) may waste
    their time investigating what's wrong with the Python code.
    Improve the error message:

    Traceback (most recent call last):
      File "/home/kicinski/devel/linux/tools/net/ynl/lib/ynl.py", line 362, in __init__
        self.family = GenlFamily(self.yaml['name'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kicinski/devel/linux/tools/net/ynl/lib/ynl.py", line 331, in __init__
        self.genl_family = genl_family_name_to_id[family_name]
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    KeyError: 'netdev'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/kicinski/devel/linux/./tools/net/ynl/cli.py", line 52, in <module>
        main()
      File "/home/kicinski/devel/linux/./tools/net/ynl/cli.py", line 31, in main
        ynl = YnlFamily(args.spec, args.schema)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kicinski/devel/linux/tools/net/ynl/lib/ynl.py", line 364, in __init__
        raise Exception(f"Family '{self.yaml['name']}' not supported by the kernel")
    Exception: Family 'netdev' not supported by the kernel

    Signed-off-by: Jakub Kicinski <kuba@kernel.org>
    Link: https://lore.kernel.org/r/20230407145609.297525-1-kuba@kernel.org
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>