ALSA: hda: tas2781: mark const variables as __maybe_unused
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit a2d6d8aee4a4f694920bfaf6f6be3690e0f8d302
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Jul 19 11:56:34 2024 +0200

    ALSA: hda: tas2781: mark const variables as __maybe_unused

    An earlier patch changed the DECLARE_TLV_DB_SCALE declaration, but
    now there are additional static const variables that cause
    the same build warnings:

    In file included from sound/pci/hda/tas2781_hda_i2c.c:23:
    include/sound/tas2781-tlv.h:23:28: error: 'tas2563_dvc_table' defined but not used [-Werror=unused-const-variable=]
       23 | static const unsigned char tas2563_dvc_table[][4] = {
          |                            ^~~~~~~~~~~~~~~~~
    In file included from include/sound/tlv.h:10,
                     from sound/pci/hda/tas2781_hda_i2c.c:22:
    include/sound/tas2781-tlv.h:20:35: error: 'tas2563_dvc_tlv' defined but not used [-Werror=unused-const-variable=]
       20 | static const DECLARE_TLV_DB_SCALE(tas2563_dvc_tlv, -12150, 50, 1);
          |                                   ^~~~~~~~~~~~~~~

    Mark them all as unused as well.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20240719095640.3741247-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>