net: ethernet: dpaa: remove unused variables
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [netdrv] ethernet: dpaa: remove unused variables (Petr Oros) [1691720]
Rebuild_FUZZ: 93.98%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5e8cc3947d8f7b62ff964e58789677a81b20dfca

The patch that removed the only users of the oldadv/newadv variables
accidentally left the now-unused declarations behind:

drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c: In function 'dpaa_set_pauseparam':
drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c:185:14: error: unused variable 'oldadv' [-Werror=unused-variable]
drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c:185:6: error: unused variable 'newadv' [-Werror=unused-variable]

Fixes: 70814e819c11 ("net: ethernet: Add helper for set_pauseparam for Asym Pause")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5e8cc3947d8f7b62ff964e58789677a81b20dfca)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>