samples/bpf: Remove unnecessary -I flags from libbpf EXTRA_CFLAGS
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit 5a6ea7022ff4d2a65ae328619c586d6a8909b48b
Author: Eduard Zingerman <eddyz87@gmail.com>
Date:   Tue Dec 3 10:22:22 2024 -0800

    samples/bpf: Remove unnecessary -I flags from libbpf EXTRA_CFLAGS

    Commit [0] breaks samples/bpf build:

        $ make M=samples/bpf
        ...
        make -C /path/to/kernel/samples/bpf/../../tools/lib/bpf \
         ...
         EXTRA_CFLAGS=" \
         ...
         -fsanitize=bounds \
         -I/path/to/kernel/usr/include \
         ...
        	/path/to/kernel/samples/bpf/libbpf/libbpf.a install_headers
          CC      /path/to/kernel/samples/bpf/libbpf/staticobjs/libbpf.o
        In file included from libbpf.c:29:
        /path/to/kernel/tools/include/linux/err.h:35:8: error: 'inline' can only appear on functions
           35 | static inline void * __must_check ERR_PTR(long error_)
              |        ^

    The error is caused by `objtree` variable changing definition from `.`
    (dot) to an absolute path:
    - The variable TPROGS_CFLAGS is constructed as follows:
      ...
      TPROGS_CFLAGS += -I$(objtree)/usr/include
    - It is passed as EXTRA_CFLAGS for libbpf compilation:
      $(LIBBPF): ...
        ...
    	$(MAKE) -C $(LIBBPF_SRC) RM='rm -rf' EXTRA_CFLAGS="$(TPROGS_CFLAGS)"
    - Before commit [0], the line passed to libbpf makefile was
      '-I./usr/include', where '.' referred to LIBBPF_SRC due to -C flag.
      The directory $(LIBBPF_SRC)/usr/include does not exist and thus
      was never resolved by C compiler.
    - After commit [0], the line passed to libbpf makefile became:
      '<output-dir>/usr/include', this directory exists and is resolved by
      C compiler.
    - Both 'tools/include' and 'usr/include' define files err.h and types.h.
    - libbpf expects headers like 'linux/err.h' and 'linux/types.h'
      defined in 'tools/include', not 'usr/include', hence the compilation
      error.

    This commit removes unnecessary -I flags from libbpf compilation.
    (libbpf sets up the necessary includes at lib/bpf/Makefile:63).

    Changes v1 [1] -> v2:
    - dropped unnecessary replacement of KBUILD_OUTPUT with $(objtree)
      (Andrii)
    Changes v2 [2] -> v3:
    - make sure --sysroot option is set for libbpf's EXTRA_CFLAGS,
      if $(SYSROOT) is set (Stanislav)

    [0] commit 13b25489b6f8 ("kbuild: change working directory to external module directory with M=")
    [1] https://lore.kernel.org/bpf/20241202212154.3174402-1-eddyz87@gmail.com/
    [2] https://lore.kernel.org/bpf/20241202234741.3492084-1-eddyz87@gmail.com/

    Fixes: 13b25489b6f8 ("kbuild: change working directory to external module directory with M=")
    Signed-off-by: Eduard Zingerman <eddyz87@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Stanislav Fomichev <sdf@fomichev.me>
    Link: https://lore.kernel.org/bpf/20241203182222.3915763-1-eddyz87@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>