ALSA: mixart: Reduce size of mixart_timer_notify
The mixart_timer_notify structure was larger than could be represented
by the mixart_msg_data array storage. Adjust the size to as large as
possible to fix the warning seen with -Warray-bounds builds:

sound/pci/mixart/mixart_core.c: In function 'snd_mixart_threaded_irq':
sound/pci/mixart/mixart_core.c:447:50: error: array subscript 'struct mixart_timer_notify[0]' is partly outside array bounds of 'u32[128]' {aka 'unsigned int[128]'} [-Werror=array-bounds]
  447 |                                 for(i=0; i<notify->stream_count; i++) {
      |                                                  ^~
sound/pci/mixart/mixart_core.c:328:12: note: while referencing 'mixart_msg_data'
  328 | static u32 mixart_msg_data[MSG_DEFAULT_SIZE / 4];
      |            ^~~~~~~~~~~~~~~

    Signed-off-by: Kees Cook <keescook@chromium.org>
    Link: https://lore.kernel.org/r/20211207062941.2413679-1-keescook@chromium.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Kees Cook <keescook@chromium.org>
Date: Mon Dec 6 22:29:41 2021 -0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit c7d58971dbea0888b6328ed0ea61089a6d62253a)
Bugzilla: https://bugzilla.redhat.com/2065572