regulator: tps65219: use IS_ERR() to detect an error pointer
Bugzilla: https://bugzilla.redhat.com/2213574

commit 2bbba115c3c9a647bcb3201b014fcc3728fe75c8
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Jan 14 10:57:36 2023 -0800

    regulator: tps65219: use IS_ERR() to detect an error pointer

    Fix pointer comparison to integer warning from gcc & sparse:

    GCC:
    ../drivers/regulator/tps65219-regulator.c:370:26: warning: ordered comparison of pointer with integer zero [-Wextra]
      370 |                 if (rdev < 0) {
          |                          ^

    sparse warning:
    drivers/regulator/tps65219-regulator.c:370:26: sparse: error: incompatible types for operation (<):
    drivers/regulator/tps65219-regulator.c:370:26: sparse:    struct regulator_dev *[assigned] rdev
    drivers/regulator/tps65219-regulator.c:370:26: sparse:    int

    Fixes: c12ac5fc3e0a ("regulator: drivers: Add TI TPS65219 PMIC regulators support")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Jerome Neanne <jneanne@baylibre.com>
    Cc: Tony Lindgren <tony@atomide.com>
    Cc: linux-omap@vger.kernel.org
    Cc: Liam Girdwood <lgirdwood@gmail.com>
    Cc: Mark Brown <broonie@kernel.org>
    Link: https://lore.kernel.org/r/20230114185736.2076-1-rdunlap@infradead.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Adrien Thierry <athierry@redhat.com>