usb: dwc3: xilinx: include linux/gpio/consumer.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2190250
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e498a04443240c15c3c857165f7b652b87f4fd96

commit e498a04443240c15c3c857165f7b652b87f4fd96
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 3 Jan 2023 13:17:46 +0100

  The newly added gpio consumer calls cause a build failure in configurations
  that fail to include the right header implicitly:

  drivers/usb/dwc3/dwc3-xilinx.c: In function 'dwc3_xlnx_init_zynqmp':
  drivers/usb/dwc3/dwc3-xilinx.c:207:22: error: implicit declaration of function 'devm_gpiod_get_optional'; did you mean 'devm_clk_get_optional'? [-Werror=implicit-function-declaration]
    207 |         reset_gpio = devm_gpiod_get_optional(dev, "reset", GPIOD_OUT_LOW);
        |                      ^~~~~~~~~~~~~~~~~~~~~~~
        |                      devm_clk_get_optional

  Fixes: ca05b38252d7 ("usb: dwc3: xilinx: Add gpio-reset support")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Link: https://lore.kernel.org/r/20230103121755.956027-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>