x86/microcode/AMD: Avoid -Wformat warning with clang-15
JIRA: https://issues.redhat.com/browse/RHEL-64439

commit 9e11fc78e2df7a2649764413029441a0c897fb11
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 5 22:49:07 2024 +0200

    x86/microcode/AMD: Avoid -Wformat warning with clang-15

    Older versions of clang show a warning for amd.c after a fix for a gcc
    warning:

      arch/x86/kernel/cpu/microcode/amd.c:478:47: error: format specifies type \
        'unsigned char' but the argument has type 'u16' (aka 'unsigned short') [-Werror,-Wformat]
                               "amd-ucode/microcode_amd_fam%02hhxh.bin", family);
                                                           ~~~~~~        ^~~~~~
                                                           %02hx

    In clang-16 and higher, this warning is disabled by default, but clang-15 is
    still supported, and it's trivial to avoid by adapting the types according
    to the range of the passed data and the format string.

      [ bp: Massage commit message. ]

    Fixes: 2e9064faccd1 ("x86/microcode/amd: Fix snprintf() format string warning in W=1 build")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20240405204919.1003409-1-arnd@kernel.org

Signed-off-by: David Arcari <darcari@redhat.com>