x86/efi: parse_efi_setup() build fix
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [x86] efi: parse_efi_setup() build fix (Dave Young) [1080109]
Rebuild_FUZZ: 94.12%
commit-author Dave Young <dyoung@redhat.com>
commit 5c12af0c41e3417e1939095325920463b5f8e726
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-229.el7/5c12af0c.failed

In case without CONFIG_EFI, there will be below build error:

   arch/x86/built-in.o: In function `setup_arch':
  (.init.text+0x9dc): undefined reference to `parse_efi_setup'

Thus fix it by adding blank inline function in asm/efi.h
Also remove an unused declaration for variable efi_data_len.

	Signed-off-by: Dave Young <dyoung@redhat.com>
	Signed-off-by: Matt Fleming <matt.fleming@intel.com>
(cherry picked from commit 5c12af0c41e3417e1939095325920463b5f8e726)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/x86/include/asm/efi.h