tools/testing/nvdimm: Fix security_init() symbol collision
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Dan Williams <dan.j.williams@intel.com>
commit e8cf229ebe5eb31eecee86268223530a872872c2

Starting with the new perf-event support in the nvdimm core, the
nfit_test mock module stops compiling. Rename its security_init() to
nfit_security_init().

tools/testing/nvdimm/test/nfit.c:1845:13: error: conflicting types for ‘security_init’; have ‘void(struct nfit_test *)’
 1845 | static void security_init(struct nfit_test *t)
      |             ^~~~~~~~~~~~~
In file included from ./include/linux/perf_event.h:61,
                 from ./include/linux/nd.h:11,
                 from ./drivers/nvdimm/nd-core.h:11,
                 from tools/testing/nvdimm/test/nfit.c:19:

Fixes: 9a61d0838cd0 ("drivers/nvdimm: Add nvdimm pmu structure")
	Cc: Kajol Jain <kjain@linux.ibm.com>
	Reviewed-by: Kajol Jain <kjain@linux.ibm.com>
	Reviewed-by: Vishal Verma <vishal.l.verma@intel.com>
Link: https://lore.kernel.org/r/164904238610.1330275.1889212115373993727.stgit@dwillia2-desk3.amr.corp.intel.com
	Signed-off-by: Dan Williams <dan.j.williams@intel.com>
(cherry picked from commit e8cf229ebe5eb31eecee86268223530a872872c2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>