perf parse-events: Avoid enum forward declaration.
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit 8228e9361e2a7447eaed87499123e85871c8bc18
Author: Ian Rogers <irogers@google.com>
Date: Wed Sep 15 14:14:28 2021 -0700

description
===========
Enum forward declarations aren't allowed as the size can't be implied.
Switch to just using an int. This fixes a clang warning:

  In file included from tools/perf/bench/evlist-open-close.c:13:
  tools/perf/bench/../util/parse-events.h:185:6: error: redeclaration of already-defined enum 'perf_tool_event' is a GNU extension [-Werror,-Wgnu-redeclared-enum]
  enum perf_tool_event;
       ^
  tools/perf/bench/../util/evsel.h:28:6: note: previous definition is here
  enum perf_tool_event {
       ^

Signed-off-by: Michael Petlan <mpetlan@redhat.com>