mm: move anon_vma declarations to linux/mm_inline.h
Bugzilla: https://bugzilla.redhat.com/2120352

commit 17fca131cee21724ee953a17c185c14e9533af5b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jan 14 14:06:07 2022 -0800

    mm: move anon_vma declarations to linux/mm_inline.h

    The patch to add anonymous vma names causes a build failure in some
    configurations:

      include/linux/mm_types.h: In function 'is_same_vma_anon_name':
      include/linux/mm_types.h:924:37: error: implicit declaration of function 'strcmp' [-Werror=implicit-function-declaration]
        924 |         return name && vma_name && !strcmp(name, vma_name);
            |                                     ^~~~~~
      include/linux/mm_types.h:22:1: note: 'strcmp' is defined in header '<string.h>'; did you forget to '#include <string.h>'?

    This should not really be part of linux/mm_types.h in the first place,
    as that header is meant to only contain structure defintions and need a
    minimum set of indirect includes itself.

    While the header clearly includes more than it should at this point,
    let's not make it worse by including string.h as well, which would pull
    in the expensive (compile-speed wise) fortify-string logic.

    Move the new functions into a separate header that only needs to be
    included in a couple of locations.

    Link: https://lkml.kernel.org/r/20211207125710.2503446-1-arnd@kernel.org
    Fixes: "mm: add a field to store names for private anonymous memory"
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Al Viro <viro@zeniv.linux.org.uk>
    Cc: Colin Cross <ccross@google.com>
    Cc: Eric Biederman <ebiederm@xmission.com>
    Cc: Kees Cook <keescook@chromium.org>
    Cc: Matthew Wilcox (Oracle) <willy@infradead.org>
    Cc: Peter Xu <peterx@redhat.com>
    Cc: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Suren Baghdasaryan <surenb@google.com>
    Cc: Vlastimil Babka <vbabka@suse.cz>
    Cc: Yu Zhao <yuzhao@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>