mm: move node_reclaim_distance to fix NUMA without SMP
Bugzilla: http://bugzilla.redhat.com/2020279

commit 61bb6cd2f765b90cfc5f0f91696889c366a6a13d
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Fri Nov 5 13:40:24 2021 -0700

    mm: move node_reclaim_distance to fix NUMA without SMP

    Patch series "Fix NUMA without SMP".

    SuperH is the only architecture which still supports NUMA without SMP,
    for good reasons (various memories scattered around the address space,
    each with varying latencies).

    This series fixes two build errors due to variables and functions used
    by the NUMA code being provided by SMP-only source files or sections.

    This patch (of 2):

    If CONFIG_NUMA=y, but CONFIG_SMP=n (e.g. sh/migor_defconfig):

        sh4-linux-gnu-ld: mm/page_alloc.o: in function `get_page_from_freelist':
        page_alloc.c:(.text+0x2c24): undefined reference to `node_reclaim_distance'

    Fix this by moving the declaration of node_reclaim_distance from an
    SMP-only to a generic file.

    Link: https://lkml.kernel.org/r/cover.1631781495.git.geert+renesas@glider.be
    Link: https://lkml.kernel.org/r/6432666a648dde85635341e6c918cee97c97d264.1631781495.git.geert+renesas@glider.be
    Fixes: a55c7454a8c887b2 ("sched/topology: Improve load balancing on AMD EPYC systems")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Suggested-by: Matt Fleming <matt@codeblueprint.co.uk>
    Acked-by: Mel Gorman <mgorman@suse.de>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Juri Lelli <juri.lelli@redhat.com>
    Cc: Vincent Guittot <vincent.guittot@linaro.org>
    Cc: Vlastimil Babka <vbabka@suse.cz>
    Cc: Yoshinori Sato <ysato@users.osdn.me>
    Cc: Rich Felker <dalias@libc.org>
    Cc: Gon Solo <gonsolo@gmail.com>
    Cc: Geert Uytterhoeven <geert+renesas@glider.be>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Phil Auld <pauld@redhat.com>