kmsan: export kmsan_handle_urb
JIRA: https://issues.redhat.com/browse/RHEL-1848

commit 7ba594d700998bafa96a75360d2e060aa39156d2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:26:57 2022 +0100

    kmsan: export kmsan_handle_urb

    USB support can be in a loadable module, and this causes a link failure
    with KMSAN:

    ERROR: modpost: "kmsan_handle_urb" [drivers/usb/core/usbcore.ko] undefined!

    Export the symbol so it can be used by this module.

    Link: https://lkml.kernel.org/r/20221215162710.3802378-1-arnd@kernel.org
    Fixes: 553a80188a5d ("kmsan: handle memory sent to/from USB")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Alexander Potapenko <glider@google.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: Marco Elver <elver@google.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>