RDMA/rxe: Fix compile warnings on 32-bit
Bugzilla: https://bugzilla.redhat.com/2022578

commit 5fc24e6022d47c19d92fb8b84c1616754ef6fdb2
Author: Jason Gunthorpe <jgg@ziepe.ca>
Date:   Thu Dec 15 11:29:25 2022 -0400

    RDMA/rxe: Fix compile warnings on 32-bit

    Move the conditional code into a function, with two varients so it is
    harder to make these kinds of mistakes.

     drivers/infiniband/sw/rxe/rxe_resp.c: In function 'atomic_write_reply':
     drivers/infiniband/sw/rxe/rxe_resp.c:794:13: error: unused variable 'payload' [-Werror=unused-variable]
       794 |         int payload = payload_size(pkt);
           |             ^~~~~~~
     drivers/infiniband/sw/rxe/rxe_resp.c:793:24: error: unused variable 'mr' [-Werror=unused-variable]
       793 |         struct rxe_mr *mr = qp->resp.mr;
           |                        ^~
     drivers/infiniband/sw/rxe/rxe_resp.c:791:19: error: unused variable 'dst' [-Werror=unused-variable]
       791 |         u64 src, *dst;
           |                   ^~~
     drivers/infiniband/sw/rxe/rxe_resp.c:791:13: error: unused variable 'src' [-Werror=unused-variable]
       791 |         u64 src, *dst;

    Fixes: 034e285f8b99 ("RDMA/rxe: Make responder support atomic write on RC service")
    Link: https://lore.kernel.org/linux-rdma/Y5s+EVE7eLWQqOwv@nvidia.com/
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>