net: phy: make mdio_bus_phy_suspend/resume as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-383.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7f654157f0aefba04cd7f6297351c87b76b47b89

When CONFIG_PM_SLEEP is disabled, the compiler warns about unused
functions:

drivers/net/phy/phy_device.c:273:12: error: unused function 'mdio_bus_phy_suspend' [-Werror,-Wunused-function]
static int mdio_bus_phy_suspend(struct device *dev)
drivers/net/phy/phy_device.c:293:12: error: unused function 'mdio_bus_phy_resume' [-Werror,-Wunused-function]
static int mdio_bus_phy_resume(struct device *dev)

The logic is intentional, so just mark these two as __maybe_unused
and remove the incorrect #ifdef.

Fixes: 4c0d2e96ba05 ("net: phy: consider that suspend2ram may cut off PHY power")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Andrew Lunn <andrew@lunn.ch>
Link: https://lore.kernel.org/r/20210225145748.404410-1-arnd@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 7f654157f0aefba04cd7f6297351c87b76b47b89)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>