wifi: mwifiex: remove unused evt_buf variable
Bugzilla: https://bugzilla.redhat.com/2196821

commit 074d0a1ae1fefce3dfe73bdda855e62eb8eb2a78
Author: Tom Rix <trix@redhat.com>
Date:   Wed Mar 29 09:14:44 2023 -0400

    wifi: mwifiex: remove unused evt_buf variable
    
    clang with W=1 reports
    drivers/net/wireless/marvell/mwifiex/11h.c:198:6: error: variable
      'evt_buf' set but not used [-Werror,-Wunused-but-set-variable]
            u8 *evt_buf;
                ^
    This variable is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230329131444.1809018-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>