tools: ynl: fix build on systems with old kernel headers
JIRA: https://redhat.atlassian.net/browse/RHEL-156508
Upstream Status: net.git commit db6b35cffe59

commit db6b35cffe59c619ea3772b21d7c7c8a7b885dc1
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Sat Dec 6 17:38:48 2025 -0800

    tools: ynl: fix build on systems with old kernel headers

    The wireguard YNL conversion was missing the customary .deps entry.
    NIPA doesn't catch this but my CentOS 9 system complains:

     wireguard-user.c:72:10: error: ‘WGALLOWEDIP_A_FLAGS’ undeclared here
     wireguard-user.c:58:67: error: parameter 1 (‘value’) has incomplete type
     58 | const char *wireguard_wgallowedip_flags_str(enum wgallowedip_flag value)
        |                                             ~~~~~~~~~~~~~~~~~~~~~~^~~~~

    And similarly does Ubuntu 22.04.

    One extra complication here is that we renamed the header guard,
    so we need to compat with both old and new guard define.

    Reviewed-by: Asbjørn Sloth Tønnesen <ast@fiberby.net>
    Link: https://patch.msgid.link/20251207013848.1692990-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>