x86/boot: Fix randconfig build error due to MEMORY_HOTREMOVE
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Borislav Petkov <bp@suse.de>
commit 82df8261c6a9523511d83ac367c7d64375ebabf4

When building randconfigs, one of the failures is:

  ld: arch/x86/boot/compressed/kaslr.o: in function `choose_random_location':
  kaslr.c:(.text+0xbf7): undefined reference to `count_immovable_mem_regions'
  ld: kaslr.c:(.text+0xcbe): undefined reference to `immovable_mem'
  make[2]: *** [arch/x86/boot/compressed/vmlinux] Error 1

because CONFIG_ACPI is not enabled in this particular .config but
CONFIG_MEMORY_HOTREMOVE is and count_immovable_mem_regions() is
unresolvable because it is defined in compressed/acpi.c which is the
compilation unit that depends on CONFIG_ACPI.

Add CONFIG_ACPI to the explicit dependencies for MEMORY_HOTREMOVE.

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Chao Fan <fanc.fnst@cn.fujitsu.com>
	Cc: x86@kernel.org
Link: https://lkml.kernel.org/r/20190205131033.9564-1-bp@alien8.de
(cherry picked from commit 82df8261c6a9523511d83ac367c7d64375ebabf4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>