md/raid5: remove unused working_disks variable
Bugzilla: https://bugzilla.redhat.com/2162219

clang with W=1 reports
drivers/md/raid5.c:7719:6: error: variable 'working_disks'
  set but not used [-Werror,-Wunused-but-set-variable]
        int working_disks = 0;
            ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>
Signed-off-by: Song Liu <song@kernel.org>
Link: https://lore.kernel.org/r/20230327132324.1769595-1-trix@redhat.com
(cherry picked from commit 7bc436121e557b1f5bebf5ad67e7ed3614d6df92)
Signed-off-by: Nigel Croxon <ncroxon@redhat.com>