drm: i915: Change fault type to unsigned long
JIRA: https://issues.redhat.com/browse/RHEL-78135

commit 8fd236b00fc1bc40e2f9205d0121a2de5ea506d0
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date:   Mon Oct 14 16:13:38 2024 +0100

    drm: i915: Change fault type to unsigned long

    Fault is currently of type u32 and with the introduction of the
    generalized vdso/page.h we trigger the error below:

    drivers/gpu/drm/i915/gt/intel_gt_print.h:29:36: error: format ‘%lx’ expects
    argument of type ‘long unsigned int’, but argument 6 has type ‘u32’ {aka
    ‘unsigned int’} [-Werror=format=]
       29 |         drm_dbg(&(_gt)->i915->drm, "GT%u: " _fmt, (_gt)->info.id,
          |                                    ^~~~~~~~
    include/drm/drm_print.h:424:39: note: in definition of macro ‘drm_dev_dbg’
      424 |         __drm_dev_dbg(NULL, dev, cat, fmt, ##__VA_ARGS__)
          |                                       ^~~
    include/drm/drm_print.h:524:33: note: in expansion of macro ‘drm_dbg_driver’
      524 | #define drm_dbg(drm, fmt, ...)  drm_dbg_driver(drm, fmt, ##__VA_ARGS__)
          |                                 ^~~~~~~~~~~~~~
    linux/drivers/gpu/drm/i915/gt/intel_gt_print.h:29:9: note: in expansion of macro
    ‘drm_dbg’
       29 |         drm_dbg(&(_gt)->i915->drm, "GT%u: " _fmt, (_gt)->info.id,
          |         ^~~~~~~
    drivers/gpu/drm/i915/gt/intel_gt.c:310:25: note: in expansion of macro ‘gt_dbg’
      310 |                         gt_dbg(gt, "Unexpected fault\n"
          |                         ^~~~~~

    This happens because the type of PAGE_MASK depends on the architecture.

    Prevent the compilation error changing the 'fault' type to unsigned
    long.

    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/all/20241014151340.1639555-2-vincenzo.frascino@arm.com

Signed-off-by: Luiz Capitulino <luizcap@redhat.com>