perf tools: Fix build error on generated/fs_at_flags_array.c
JIRA: https://issues.redhat.com/browse/RHEL-127734

upstream
========
commit 968121f0a649ee2ff5ac7b29aa4d4f6b0798ea9e
Author: Namhyung Kim <namhyung@kernel.org>
Date: Mon Dec 2 19:53:49 2024 -0800

description
===========
It should only have generic flags in the array but the recent header
sync brought a new flags to fcntl.h and caused a build error.  Let's
update the shell script to exclude flags specific to name_to_handle_at().

    CC      trace/beauty/fs_at_flags.o
  In file included from trace/beauty/fs_at_flags.c:21:
  tools/perf/trace/beauty/generated/fs_at_flags_array.c:13:30: error: initialized field overwritten [-Werror=override-init]
     13 |         [ilog2(0x002) + 1] = "HANDLE_CONNECTABLE",
        |                              ^~~~~~~~~~~~~~~~~~~~
  tools/perf/trace/beauty/generated/fs_at_flags_array.c:13:30: note: (near initialization for ‘fs_at_flags[2]’)

    Reviewed-by: James Clark <james.clark@linaro.org>
    Link: https://lore.kernel.org/r/20241203035349.1901262-12-namhyung@kernel.org
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Anubhav Shelat <ashelat@redhat.com>