sfc: Fix build with CONFIG_RFS_ACCEL disabled.
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [netdrv] sfc: Fix build with CONFIG_RFS_ACCEL disabled (Jarod Wilson) [1856681]
Rebuild_FUZZ: 98.90%
commit-author David S. Miller <davem@davemloft.net>
commit da7955405fb25c11a541234b32d06d9c09f81be6

   drivers/net/ethernet/sfc/ef100_nic.c:835:3: error: 'const struct efx_nic_type' has no member named 'filter_rfs_expire_one'
     835 |  .filter_rfs_expire_one = efx_mcdi_filter_rfs_expire_one,
         |   ^~~~~~~~~~~~~~~~~~~~~
>> drivers/net/ethernet/sfc/ef100_nic.c:835:27: error: initialization of 'void (*)(struct efx_nic *, u32)' {aka 'void (*)(struct efx_nic *, unsigned int)'} from incompatible pointer type 'bool (*)(struct efx_nic *, u32,  unsigned int)' {aka '_Bool (*)(struct efx_nic *, unsigned int,  unsigned int)'} [-Werror=incompatible-pointer-types]
     835 |  .filter_rfs_expire_one = efx_mcdi_filter_rfs_expire_one,
         |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit da7955405fb25c11a541234b32d06d9c09f81be6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>