wifi: brcmsmac: Remove const from tbl_ptr parameter in wlc_lcnphy_common_read_table()
JIRA: https://issues.redhat.com/browse/RHEL-114891

commit 81284e86bf8849f8e98e8ead3ff5811926b2107f
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Jul 15 19:45:23 2025 -0700

    wifi: brcmsmac: Remove const from tbl_ptr parameter in wlc_lcnphy_common_read_table()
    
    A new warning in clang [1] complains that diq_start in
    wlc_lcnphy_tx_iqlo_cal() is passed uninitialized as a const pointer to
    wlc_lcnphy_common_read_table():
    
      drivers/net/wireless/broadcom/brcm80211/brcmsmac/phy/phy_lcn.c:2728:13: error: variable 'diq_start' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
       2728 |                                                      &diq_start, 1, 16, 69);
            |                                                       ^~~~~~~~~
    
    The table pointer passed to wlc_lcnphy_common_read_table() should not be
    considered constant, as wlc_phy_read_table() is ultimately going to
    update it. Remove the const qualifier from the tbl_ptr to clear up the
    warning.
    
    Cc: stable@vger.kernel.org
    Closes: https://github.com/ClangBuiltLinux/linux/issues/2108
    Fixes: 5b435de0d786 ("net: wireless: add brcm80211 drivers")
    Link: https://github.com/llvm/llvm-project/commit/00dacf8c22f065cb52efb14cd091d441f19b319e [1]
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Arend van Spriel <arend.vanspriel@broadcom.com>>
    Link: https://patch.msgid.link/20250715-brcmsmac-fix-uninit-const-pointer-v1-1-16e6a51a8ef4@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>