perf test all metrics: Fully ignore Default metric failures
JIRA: https://redhat.atlassian.net/browse/RHEL-140195

upstream
========
commit 41b67ab3d2f5be9d0b6e5ba9cbec97c820fc50e8
Author: Ian Rogers <irogers@google.com>
Date: Wed Nov 19 11:30:47 2025 -0800

description
===========
Determine if a metric is default from `perf list --raw-dump $m` eg:
```
$ perf list --raw-dump l1_prefetch_miss_rate
Default4 l1_prefetch_miss_rate
```
If a metric has "not supported" or "no supported events" then ignore
these failures for default metrics. Tidy up the skip/fail messages in
the output to make them easier to spot/read.

```
$ perf list -vv "all metrics"
...
Testing llc_miss_rate
[Ignored llc_miss_rate] failed but as a Default metric this can be expected
Error: No supported events found. The LLC-loads event is not supported.
...
```

    Reported-by: Thomas Richter <tmricht@linux.ibm.com>
Closes: https://lore.kernel.org/linux-perf-users/20251119104751.51960-1-tmricht@linux.ibm.com/
    Reported-by: Namhyung Kim <namhyung@kernel.org>
    Reported-by: James Clark <james.clark@linaro.org>
Closes: https://lore.kernel.org/lkml/aRi9xnwdLh3Dir9f@google.com/
    Signed-off-by: Ian Rogers <irogers@google.com>
    Reviewed-by: James Clark <james.clark@linaro.org>
    Tested-by: Thomas Richter <tmricht@linux.ibm.com>
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Trevor Allison <tallison@redhat.com>