wifi: iwlwifi: cfg: Limit cb_size to valid range
JIRA: https://issues.redhat.com/browse/RHEL-122256

commit d5352b491a3a2628f1a798952a4ae76bde5d42e4
Author: Pei Xiao <xiaopei01@kylinos.cn>
Date:   Tue May 27 16:03:55 2025 +0800

    wifi: iwlwifi: cfg: Limit cb_size to valid range
    
    on arm64 defconfig build failed with gcc-8:
    
    drivers/net/wireless/intel/iwlwifi/pcie/ctxt-info.c:208:3:
    include/linux/bitfield.h:195:3: error: call to '__field_overflow'
    declared with attribute error: value doesn't fit into mask
       __field_overflow();     \
       ^~~~~~~~~~~~~~~~~~
    include/linux/bitfield.h:215:2: note: in expansion of macro '____MAKE_OP'
      ____MAKE_OP(u##size,u##size,,)
      ^~~~~~~~~~~
    include/linux/bitfield.h:218:1: note: in expansion of macro '__MAKE_OP'
     __MAKE_OP(32)
    
    Limit cb_size to valid range to fix it.
    
    Signed-off-by: Pei Xiao <xiaopei01@kylinos.cn>
    Link: https://patch.msgid.link/7b373a4426070d50b5afb3269fd116c18ce3aea8.1748332709.git.xiaopei01@kylinos.cn
    Signed-off-by: Miri Korenblit <miriam.rachel.korenblit@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>