ipv4: Return error for RTA_VIA attribute
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author David Ahern <dsahern@gmail.com>
commit b6e9e5df4ecf100f6a10ab2ade8e46d47a4b9779

IPv4 currently does not support nexthops outside of the AF_INET family.
Specifically, it does not handle RTA_VIA attribute. If it is passed
in a route add request, the actual route added only uses the device
which is clearly not what the user intended:

  $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
  $ ip ro ls
  ...
  172.16.1.0/24 dev eth0

Catch this and fail the route add:
  $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
  Error: IPv4 does not support RTA_VIA attribute.

Fixes: 03c0566542f4c ("mpls: Netlink commands to add, remove, and dump routes")
	Signed-off-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b6e9e5df4ecf100f6a10ab2ade8e46d47a4b9779)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>