perf build: Remove -Wno-unused-but-set-variable from the flex flags when building with clang < 13.0.0
JIRA: https://issues.redhat.com/browse/RHEL-15009

upstream
========
commit 878460e8d0ff84a0edbaff9d06f9d9dbe8353800
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Aug 10 11:46:20 2023 -0300

description
===========
clang < 13.0.0 doesn't grok -Wno-unused-but-set-variable, so just remove
it to avoid:

  error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
  make[4]: *** [/git/perf-6.5.0-rc4/tools/build/Makefile.build:128: /tmp/build/perf/util/pmu-flex.o] Error 1
  make[4]: *** Waiting for unfinished jobs....

Fixes: ddc8e4c966923ad1 ("perf build: Disable fewer bison warnings")
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Ian Rogers <irogers@google.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Link: https://lore.kernel.org/lkml/ZNUSWr52jUnVaaa%2F@kernel.org/
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>