HID: intel-ish-hid: fix endian-conversion
JIRA: https://issues.redhat.com/browse/RHEL-65221
Upstream status: v6.12-rc7

commit 9e438fe31e96b75c2ec599f6a9239950e6712358
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 3 09:41:03 2024 +0200

    HID: intel-ish-hid: fix endian-conversion

    The newly added file causes a ton of sparse warnings about the
    incorrect use of __le32 and similar types:

    drivers/hid/intel-ish-hid/ishtp/loader.h:41:23: error: invalid bitfield specifier for type restricted __le32.
    drivers/hid/intel-ish-hid/ishtp/loader.h:42:27: error: invalid bitfield specifier for type restricted __le32.
    drivers/hid/intel-ish-hid/ishtp/loader.h:43:24: error: invalid bitfield specifier for type restricted __le32.
    drivers/hid/intel-ish-hid/ishtp/loader.h:44:24: error: invalid bitfield specifier for type restricted __le32.
    drivers/hid/intel-ish-hid/ishtp/loader.h:45:22: error: invalid bitfield specifier for type restricted __le32.
    drivers/hid/intel-ish-hid/ishtp/loader.c:172:33: warning: restricted __le32 degrades to integer
    drivers/hid/intel-ish-hid/ishtp/loader.c:178:50: warning: incorrect type in assignment (different base types)
    drivers/hid/intel-ish-hid/ishtp/loader.c:178:50:    expected restricted __le32 [usertype] length
    drivers/hid/intel-ish-hid/ishtp/loader.c:178:50:    got unsigned long
    drivers/hid/intel-ish-hid/ishtp/loader.c:179:50: warning: incorrect type in assignment (different base types)
    drivers/hid/intel-ish-hid/ishtp/loader.c:179:50:    expected restricted __le32 [usertype] fw_off
    drivers/hid/intel-ish-hid/ishtp/loader.c:179:50:    got unsigned int [usertype] offset
    drivers/hid/intel-ish-hid/ishtp/loader.c:180:17: warning: cast from restricted __le32
    drivers/hid/intel-ish-hid/ishtp/loader.c:183:24: warning: invalid assignment: +=
    drivers/hid/intel-ish-hid/ishtp/loader.c:183:24:    left side has type unsigned int
    drivers/hid/intel-ish-hid/ishtp/loader.c:183:24:    right side has type restricted __le32

    Add the necessary conversions and use temporary variables where appropriate
    to avoid converting back.

    Fixes: 579a267e4617 ("HID: intel-ish-hid: Implement loading firmware from host feature")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Zhang Lixu <lixu.zhang@intel.com>
    Tested-by: Zhang Lixu <lixu.zhang@intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>