net/mlx5e: Ensure macsec_rule is always initiailized in macsec_fs_{r,t}x_add_rule()
Bugzilla: https://bugzilla.redhat.com/2165355
Upstream-status: v6.1-rc1

commit 2e50e9bf328fb781c9fcd5dc6531458dd02d1626
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Sun Sep 11 01:57:50 2022 -0700

    net/mlx5e: Ensure macsec_rule is always initiailized in macsec_fs_{r,t}x_add_rule()

    Clang warns:

      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:539:6: error: variable 'macsec_rule' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
              if (err)
                  ^~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:598:9: note: uninitialized use occurs here
              return macsec_rule;
                    ^~~~~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:539:2: note: remove the 'if' if its condition is always false
              if (err)
              ^~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:523:38: note: initialize the variable 'macsec_rule' to silence this warning
              union mlx5e_macsec_rule *macsec_rule;
                                                  ^
                                                  = NULL
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:1131:6: error: variable 'macsec_rule' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
              if (err)
                  ^~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:1215:9: note: uninitialized use occurs here
              return macsec_rule;
                    ^~~~~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:1131:2: note: remove the 'if' if its condition is always false
              if (err)
              ^~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_accel/macsec_fs.c:1118:38: note: initialize the variable 'macsec_rule' to silence this warning
              union mlx5e_macsec_rule *macsec_rule;
                                                  ^
                                                  = NULL
      2 errors generated.

    If macsec_fs_{r,t}x_ft_get() fail, macsec_rule will be uninitialized.
    Initialize it to NULL at the top of each function so that it cannot be
    used uninitialized.

    Fixes: e467b283ffd5 ("net/mlx5e: Add MACsec TX steering rules")
    Fixes: 3b20949cb21b ("net/mlx5e: Add MACsec RX steering rules")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1706
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Raed Salem <raeds@nvidia.com>
    Link: https://lore.kernel.org/r/20220911085748.461033-1-nathan@kernel.org
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>