percpu: km: ensure it is used with NOMMU (either UP or SMP)
Bugzilla: https://bugzilla.redhat.com/2120352

commit 3583521aabac76e58675297cead02f9ecac518b6
Author: Vladimir Murzin <vladimir.murzin@arm.com>
Date:   Tue Nov 30 17:29:54 2021 +0000

    percpu: km: ensure it is used with NOMMU (either UP or SMP)

    Currently, NOMMU pull km allocator via !SMP dependency because most of
    them are UP, yet for SMP+NOMMU vm allocator gets pulled which:

    * may lead to broken build [1]
    * ...or not working runtime due to [2]

    It looks like SMP+NOMMU case was overlooked in bbddff054587 ("percpu:
    use percpu allocator on UP too") so restore that.

    [1]
    For ARM SMP+NOMMU (R-class cores)

    arm-none-linux-gnueabihf-ld: mm/percpu.o: in function `pcpu_post_unmap_tlb_flush':
    mm/percpu-vm.c:188: undefined reference to `flush_tlb_kernel_range'

    [2]
    static inline
    int vmap_pages_range_noflush(unsigned long addr, unsigned long end,
                    pgprot_t prot, struct page **pages, unsigned int page_shift)
    {
           return -EINVAL;
    }

    Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>
    Tested-by: Rob Landley <rob@landley.net>
    Tested-by: Rich Felker <dalias@libc.org>
    [Dennis: use depends instead of default for condition]
    Signed-off-by: Dennis Zhou <dennis@kernel.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>