selftests: net: bpf_offload: add 'libbpf_global' to ignored maps
JIRA: https://issues.redhat.com/browse/RHEL-84558
Upstream Status: net.git commit 56a586961bf8

commit 56a586961bf89f2461ebb1b16541b7a161f63238
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Tue Mar 4 15:32:04 2025 -0800

    selftests: net: bpf_offload: add 'libbpf_global' to ignored maps

    After installing pahole on the CI image we have a new map created
    by libbpf. Ignore it otherwise we see:

      Exception: Time out waiting for map counts to stabilize want 2, have 3

    Acked-by: Stanislav Fomichev <sdf@fomichev.me>
    Link: https://patch.msgid.link/20250304233204.1139251-2-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>