selftests/bpf: Add selftests for load-acquire and store-release instructions
JIRA: https://issues.redhat.com/browse/RHEL-78202

commit ff3afe5da9985b465427a4a7ab14d27598de0d44
Author: Peilin Ye <yepeilin@google.com>
Date:   Tue Mar 4 01:06:46 2025 +0000

    selftests/bpf: Add selftests for load-acquire and store-release instructions
    
    Add several ./test_progs tests:
    
      - arena_atomics/load_acquire
      - arena_atomics/store_release
      - verifier_load_acquire/*
      - verifier_store_release/*
      - verifier_precision/bpf_load_acquire
      - verifier_precision/bpf_store_release
    
    The last two tests are added to check if backtrack_insn() handles the
    new instructions correctly.
    
    Additionally, the last test also makes sure that the verifier
    "remembers" the value (in src_reg) we store-release into e.g. a stack
    slot.  For example, if we take a look at the test program:
    
        #0:  r1 = 8;
          /* store_release((u64 *)(r10 - 8), r1); */
        #1:  .8byte %[store_release];
        #2:  r1 = *(u64 *)(r10 - 8);
        #3:  r2 = r10;
        #4:  r2 += r1;
        #5:  r0 = 0;
        #6:  exit;
    
    At #1, if the verifier doesn't remember that we wrote 8 to the stack,
    then later at #4 we would be adding an unbounded scalar value to the
    stack pointer, which would cause the program to be rejected:
    
      VERIFIER LOG:
      =============
    ...
      math between fp pointer and register with unbounded min value is not allowed
    
    For easier CI integration, instead of using built-ins like
    __atomic_{load,store}_n() which depend on the new
    __BPF_FEATURE_LOAD_ACQ_STORE_REL pre-defined macro, manually craft
    load-acquire/store-release instructions using __imm_insn(), as suggested
    by Eduard.
    
    All new tests depend on:
    
      (1) Clang major version >= 18, and
      (2) ENABLE_ATOMICS_TESTS is defined (currently implies -mcpu=v3 or
          v4), and
      (3) JIT supports load-acquire/store-release (currently arm64 and
          x86-64)
    
    In .../progs/arena_atomics.c:
    
      /* 8-byte-aligned */
      __u8 __arena_global load_acquire8_value = 0x12;
      /* 1-byte hole */
      __u16 __arena_global load_acquire16_value = 0x1234;
    
    That 1-byte hole in the .addr_space.1 ELF section caused clang-17 to
    crash:
    
      fatal error: error in backend: unable to write nop sequence of 1 bytes
    
    To work around such llvm-17 CI job failures, conditionally define
    __arena_global variables as 64-bit if __clang_major__ < 18, to make sure
    .addr_space.1 has no holes.  Ideally we should avoid compiling this file
    using clang-17 at all (arena tests depend on
    __BPF_FEATURE_ADDR_SPACE_CAST, and are skipped for llvm-17 anyway), but
    that is a separate topic.
    
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Signed-off-by: Peilin Ye <yepeilin@google.com>
    Link: https://lore.kernel.org/r/1b46c6feaf0f1b6984d9ec80e500cc7383e9da1a.1741049567.git.yepeilin@google.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Gregory Bell <grbell@redhat.com>