selftests: bpf: add config fragment LWTUNNEL
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Anders Roxell <anders.roxell@linaro.org>
commit d3c72d7a20d8ebb0618d06fc49e83a4d74d96205
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-147.el8/d3c72d7a.failed

When test_lwt_seg6local.sh was added commit c99a84eac026
("selftests/bpf: test for seg6local End.BPF action") config fragment
wasn't added, and without CONFIG_LWTUNNEL enabled we see this:
Error: CONFIG_LWTUNNEL is not enabled in this kernel.
selftests: test_lwt_seg6local [FAILED]

	Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
	Acked-by: Song Liu <songliubraving@fb.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit d3c72d7a20d8ebb0618d06fc49e83a4d74d96205)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/bpf/config