perf tests: Fix 'perf probe' error log check in skip_if_no_debuginfo
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-481.el8
commit-author Athira Rajeev <atrajeev@linux.vnet.ibm.com>
commit 4627a000dced43ae9e81a9c174e75773794ce905

The perf probe related tests like probe_vfs_getname.sh which
is in "tools/perf/tests/shell" directory have dependency on
debuginfo information in the kernel. Currently debuginfo
check is handled by skip_if_no_debuginfo function in the
file "lib/probe_vfs_getname.sh". skip_if_no_debuginfo function
looks for this specific error log from perf probe to skip
the testcase:

<<>>
Failed to find the path for the kernel|Debuginfo-analysis is
not supported
<>>

But in some case, like this one in powerpc, while running this
test, observed error logs is:

<<>>
The /lib/modules/<version>/build/vmlinux file has no debug information.
Rebuild with CONFIG_DEBUG_INFO=y, or install an appropriate debuginfo
package.
  Error: Failed to add events.
<<>>

Update the skip_if_no_debuginfo function to include the above
error, to skip the test in these scenarios too.

	Reported-by: Disha Goel <disgoel@linux.vnet.ibm.com>
	Signed-off-by: Athira Jajeev <atrajeev@linux.vnet.ibm.com>
	Tested-by: Disha Goel <disgoel@linux.vnet.ibm.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Madhavan Srinivasan <maddy@linux.vnet.ibm.com>
	Cc: Michael Ellerman <mpe@ellerman.id.au>
	Cc: Nageswara R Sastry <rnsastry@linux.ibm.com>
	Cc: linuxppc-dev@lists.ozlabs.org
Link: https://lore.kernel.org/r/20220916104904.99798-1-atrajeev@linux.vnet.ibm.com
Reviewed-By: Kajol Jain <kjain@linux.ibm.com>
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 4627a000dced43ae9e81a9c174e75773794ce905)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>