uapi: fix rdma/mlx5-abi.h userspace compilation errors
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Dmitry V. Levin <ldv@altlinux.org>
commit 812755d69efcf7c12fded57983d456647a0bbadd
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/812755d6.failed

Consistently use types from linux/types.h to fix the following
rdma/mlx5-abi.h userspace compilation errors:

/usr/include/rdma/mlx5-abi.h:69:25: error: 'u64' undeclared here (not in a function)
  MLX5_LIB_CAP_4K_UAR = (u64)1 << 0,
/usr/include/rdma/mlx5-abi.h:69:29: error: expected ',' or '}' before numeric constant
  MLX5_LIB_CAP_4K_UAR = (u64)1 << 0,

Include <linux/if_ether.h> to fix the following rdma/mlx5-abi.h
userspace compilation error:

/usr/include/rdma/mlx5-abi.h:286:12: error: 'ETH_ALEN' undeclared here (not in a function)
  __u8 dmac[ETH_ALEN];

	Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 812755d69efcf7c12fded57983d456647a0bbadd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/uapi/rdma/mlx5-abi.h