scsi: ufs: ufs-mediatek: Guard power management functions with CONFIG_PM
Bugzilla: https://bugzilla.redhat.com/2185234

commit 19873b03f1daeffd9d5e089b855dd926975ab5b7
Author: Yangtao Li <frank.li@vivo.com>
Date:   Mon Feb 20 22:24:31 2023 +0800

    scsi: ufs: ufs-mediatek: Guard power management functions with CONFIG_PM

    Fix the following compilation error when CONFIG_PM is set to 'n':

    drivers/ufs/host/ufs-mediatek.c: In function `ufs_mtk_runtime_suspend`:
    drivers/ufs/host/ufs-mediatek.c:1623:8: error: implicit declaration of
            function `ufshcd_runtime_suspend`; did you mean `ufs_mtk_runtime_suspend`?
            [-Werror=implicit-function-declaration]
     1623 |  ret = ufshcd_runtime_suspend(dev);
          |        ^~~~~~~~~~~~~~~~~~~~~~
          |        ufs_mtk_runtime_suspend
    drivers/ufs/host/ufs-mediatek.c: In function `ufs_mtk_runtime_resume`:
    drivers/ufs/host/ufs-mediatek.c:1638:9: error: implicit declaration of function
            `ufshcd_runtime_resume`; did you mean `ufs_mtk_runtime_resume`?
            [-Werror=implicit-function-declaration]
     1638 |  return ufshcd_runtime_resume(dev);
          |         ^~~~~~~~~~~~~~~~~~~~~
          |         ufs_mtk_runtime_resume
    At top level:
    drivers/ufs/host/ufs-mediatek.c:1632:12: error: `ufs_mtk_runtime_resume`
            defined but not used [-Werror=unused-function]
     1632 | static int ufs_mtk_runtime_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~
    drivers/ufs/host/ufs-mediatek.c:1618:12: error: `ufs_mtk_runtime_suspend`
            defined but not used [-Werror=unused-function]
     1618 | static int ufs_mtk_runtime_suspend(struct device *dev)

    Link: https://lore.kernel.org/r/20230220142431.54589-1-frank.li@vivo.com
    Reported-by: k2ci <kernel-bot@kylinos.cn>
    Reported-by: Shida Zhang <zhangshida@kylinos.cn>
    Signed-off-by: Yangtao Li <frank.li@vivo.com>
    Reviewed-by: Stanley Chu <stanley.chu@mediatek.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>