kexec.h: add linux/kexec.h to UAPI compile-test coverage
JIRA: https://issues.redhat.com/browse/RHEL-32199

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

Conflict: There's conflict in usr/include/Makefile hunk.

commit 8b4bca21c2c0cb3b5adb80985830a81d4e5d7081
Author: Masahiro Yamada <masahiroy@kernel.org>
Date:   Thu Feb 10 11:11:28 2022 +0900

    kexec.h: add linux/kexec.h to UAPI compile-test coverage

    linux/kexec.h is currently excluded from the UAPI compile-test because
    of the errors like follows:

        HDRTEST usr/include/linux/kexec.h
      In file included from <command-line>:
      ./usr/include/linux/kexec.h:56:9: error: unknown type name ‘size_t’
         56 |         size_t bufsz;
            |         ^~~~~~
      ./usr/include/linux/kexec.h:58:9: error: unknown type name ‘size_t’
         58 |         size_t memsz;
            |         ^~~~~~

    The errors can be fixed by replacing size_t with __kernel_size_t.

    Then, remove the no-header-test entry from user/include/Makefile.

    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Baoquan He <bhe@redhat.com>