crypto: octeontx2 - select CONFIG_NET_DEVLINK
JIRA: https://issues.redhat.com/browse/RHEL-74335
Upstream Status: merged into the linux.git

commit 85872d1a6f38d133133784c8027d25d1c5328f4f
Author: Shijith Thotton <sthotton@marvell.com>
Date:   Fri Jan 21 16:42:32 2022 +0530

    crypto: octeontx2 - select CONFIG_NET_DEVLINK

    OcteonTX2 CPT driver will fail to link without devlink support.

    aarch64-linux-gnu-ld: otx2_cpt_devlink.o: in function `otx2_cpt_dl_egrp_delete':
    otx2_cpt_devlink.c:18: undefined reference to `devlink_priv'
    aarch64-linux-gnu-ld: otx2_cpt_devlink.o: in function `otx2_cpt_dl_egrp_create':
    otx2_cpt_devlink.c:9: undefined reference to `devlink_priv'
    aarch64-linux-gnu-ld: otx2_cpt_devlink.o: in function `otx2_cpt_dl_uc_info':
    otx2_cpt_devlink.c:27: undefined reference to `devlink_priv'

    Fixes: fed8f4d5f946 ("crypto: octeontx2 - parameters for custom engine groups")

    Signed-off-by: Shijith Thotton <sthotton@marvell.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>