ASoC: apple: mca: Unselect COMMON_CLK in Kconfig
Bugzilla: https://bugzilla.redhat.com/2179848

commit 7d2497b7fd3bf45706360bfe289f19d61d37f536
Author: Martin Povišer <povik+lin@cutebit.org>
Date: Thu Sep 1 13:34:14 2022 +0200

    ASoC: apple: mca: Unselect COMMON_CLK in Kconfig

    The MCA driver selects COMMON_CLK, which leads to misconfiguration
    on platforms with HAVE_LEGACY_CLK (under compile test). Kconfig catches
    the conflict with the following warning:

      WARNING: unmet direct dependencies detected for COMMON_CLK
      Depends on [n]: !HAVE_LEGACY_CLK [=y]
      Selected by [m]:
      - SND_SOC_APPLE_MCA [=m] && SOUND [=m] && !UML && SND [=m] &&
        SND_SOC [=m] && (ARCH_APPLE || COMPILE_TEST [=y])

    Eventually the build fails with errors like:

    >> drivers/clk/clk.c:867:6: error: redefinition of 'clk_unprepare'
         867 | void clk_unprepare(struct clk *clk)
             |      ^~~~~~~~~~~~~
       In file included from drivers/clk/clk.c:9:
       include/linux/clk.h:303:20: note: previous definition of 'clk_unprepare' with type 'void(struct clk *)'
         303 | static inline void clk_unprepare(struct clk *clk)
             |                    ^~~~~~~~~~~~~

    which appears to be because COMMON_CLK is selected but HAVE_CLK_PREPARE
    is not. In the end it seems we had no business selecting COMMON_CLK from
    an unrelated driver like that, so remove the selection. The linux/clk.h
    API is there anyway.

    Fixes: 3df5d0d97289 ("ASoC: apple: mca: Start new platform driver")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Martin Povišer <povik+lin@cutebit.org>
    Link: https://lore.kernel.org/r/20220901113415.27449-1-povik+lin@cutebit.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>