ASoC: msm8916-wcd-digital: Select REGMAP_MMIO to fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: msm8916-wcd-digital: Select REGMAP_MMIO to fix build error (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 95.52%
commit-author Axel Lin <axel.lin@ingics.com>
commit 5b86fa6d2903c41c3c3dbff4def76a5b8bbe0660

Fix below build error:
ERROR: "__devm_regmap_init_mmio_clk" [sound/soc/codecs/snd-soc-msm8916-digital.ko] undefined!

	Signed-off-by: Axel Lin <axel.lin@ingics.com>
	Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 5b86fa6d2903c41c3c3dbff4def76a5b8bbe0660)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>