ALSA: hdspm: remove unused copy_u32_le function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Tom Rix <trix@redhat.com>
commit 2c7598903f18418aa18d11a9dd081acb22e9e108

clang with W=1 reports
sound/pci/rme9652/hdspm.c:6149:19: error: unused function
  'copy_u32_le' [-Werror,-Wunused-function]
static inline int copy_u32_le(void __user *dest, void __iomem *src)
                  ^
This function is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230323202713.2637150-1-trix@redhat.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 2c7598903f18418aa18d11a9dd081acb22e9e108)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>