ASoC: codecs: rt1320-sdw: Refactor to reduce stack frames
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit 233ccfe911aa62c0f9211f2e3297d6a7f870b295
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date: Sat Jan 24 11:17:03 2026 +0100

    ASoC: codecs: rt1320-sdw: Refactor to reduce stack frames

    Compiler is not happy about used stack frames in a couple of functions:

    sound/soc/codecs/rt1320-sdw.c: In function 'rt1320_rae_load':
    sound/soc/codecs/rt1320-sdw.c:1570:1: error: the frame size of 1336 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]
    sound/soc/codecs/rt1320-sdw.c: In function 'rt1320_dspfw_load_code':
    sound/soc/codecs/rt1320-sdw.c:1786:1: error: the frame size of 1520 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

    Refactor the code to fix these.

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Link: https://patch.msgid.link/20260124101824.3424793-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>