ALSA: pcxhr: fix string overflow warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5051735221ba50cb5794b9194a8ad10a13368f2f

With gcc-7, we get a warning about a possible string overflow:

sound/pci/pcxhr/pcxhr.c: In function 'pcxhr_probe':
sound/pci/pcxhr/pcxhr.c:1647:28: error: ' [PCM #' directive writing 7 bytes into a region of size between 1 and 32 [-Werror=format-overflow=]

The shortname can simply be removed, and the longname can
be changed into a shorter "name" string that is used in three
places. Making it a little shorter (40 bytes) avoids the risk of
overflowing completely, but I also use snprintf() here for
extra clarity.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 5051735221ba50cb5794b9194a8ad10a13368f2f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>