turbostat: Use GCC's CPUID functions to support PIC
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Josh Triplett <josh@joshtriplett.org>
commit 2b92865e648ce04a39fda4f903784a5d01ecb0dc

turbostat uses inline assembly to call cpuid.  On 32-bit x86, on systems
that have certain security features enabled by default that make -fPIC
the default, this causes a build error:

turbostat.c: In function ‘check_cpuid’:
turbostat.c:1906:2: error: PIC register clobbered by ‘ebx’ in ‘asm’
  asm("cpuid" : "=a" (fms), "=c" (ecx), "=d" (edx) : "a" (1) : "ebx");
  ^

GCC provides a header cpuid.h, containing a __get_cpuid function that
works with both PIC and non-PIC.  (On PIC, it saves and restores ebx
around the cpuid instruction.)  Use that instead.

	Signed-off-by: Josh Triplett <josh@joshtriplett.org>
	Cc: stable@vger.kernel.org
	Signed-off-by: Len Brown <len.brown@intel.com>
(cherry picked from commit 2b92865e648ce04a39fda4f903784a5d01ecb0dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>