brcmfmac: Fix use after free in brcmf_sdio_readframes()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 216b44000ada87a63891a8214c347e05a4aea8fe

The brcmu_pkt_buf_free_skb() function frees "pkt" so it leads to a
static checker warning:

    drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:1974 brcmf_sdio_readframes()
    error: dereferencing freed memory 'pkt'

It looks like there was supposed to be a continue after we free "pkt".

Fixes: 4754fceeb9a6 ("brcmfmac: streamline SDIO read frame routine")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Franky Lin <franky.lin@broadcom.com>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
(cherry picked from commit 216b44000ada87a63891a8214c347e05a4aea8fe)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>