ip_tunnel: Move ip_tunnel_get_stats64 into ip_tunnel_core.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author David S. Miller <davem@davemloft.net>
commit ebe44f350e15d6142d4d74cbaec0dad976c36753
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/ebe44f35.failed

net/built-in.o:(.rodata+0x1707c): undefined reference to `ip_tunnel_get_stats64'

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ebe44f350e15d6142d4d74cbaec0dad976c36753)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/ipv4/ip_tunnel.c