ath11k: Fix uninitialized symbol 'rx_buf_sz'
Bugzilla: https://bugzilla.redhat.com/2059999

commit dca857f07dc14c923a3c47965e771f435807b39c
Author: Anilkumar Kolli <quic_akolli@quicinc.com>
Date:   Wed Jan 19 20:53:13 2022 +0530

    ath11k: Fix uninitialized symbol 'rx_buf_sz'
    
    Add missing else statement in ath11k_dp_rx_process_mon_status()
    to fix below smatch warnings,
        drivers/net/wireless/ath/ath11k/dp_rx.c:3105
        ath11k_dp_rx_process_mon_status()
        error: uninitialized symbol 'rx_buf_sz'.
    
    Fixes: ab18e3bc1c13 ("ath11k: Fix pktlog lite rx events")
    
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Anilkumar Kolli <quic_akolli@quicinc.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/1642605793-13518-1-git-send-email-quic_akolli@quicinc.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>