net: rxrpc: fix clang -Wformat warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2170099
JIRA: https://issues.redhat.com/browse/RHELPLAN-148774

commit 5b47d2364652979dc43df14f7af19346a001b770
Author: Justin Stitt <justinstitt@google.com>
Date:   Thu Jul 7 11:20:52 2022 -0700

    When building with Clang we encounter this warning:
    | net/rxrpc/rxkad.c:434:33: error: format specifies type 'unsigned short'
    | but the argument has type 'u32' (aka 'unsigned int') [-Werror,-Wformat]
    | _leave(" = %d [set %hx]", ret, y);

    y is a u32 but the format specifier is `%hx`. Going from unsigned int to
    short int results in a loss of data. This is surely not intended
    behavior. If it is intended, the warning should be suppressed through
    other means.

    This patch should get us closer to the goal of enabling the -Wformat
    flag for Clang builds.

    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: David Howells <dhowells@redhat.com>
    Link: https://lore.kernel.org/r/20220707182052.769989-1-justinstitt@google.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Marc Dionne <mdionne@redhat.com>