x86: kvm: avoid unused variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7288bde1f9df6c1475675419bdd7725ce84dec56

Removing one of the two accesses of the maxphyaddr variable led to
a harmless warning:

arch/x86/kvm/x86.c: In function 'kvm_set_mmio_spte_mask':
arch/x86/kvm/x86.c:6563:6: error: unused variable 'maxphyaddr' [-Werror=unused-variable]

Removing the #ifdef seems to be the nicest workaround, as it
makes the code look cleaner than adding another #ifdef.

Fixes: 28a1f3ac1d0c ("kvm: x86: Set highest physical address bits in non-present/reserved SPTEs")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Cc: stable@vger.kernel.org # L1TF
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 7288bde1f9df6c1475675419bdd7725ce84dec56)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>