platform/x86/intel-uncore-freq: avoid non-literal format string
JIRA: https://issues.redhat.com/browse/RHEL-119043

commit 0c44b46f51a17baa7ab67de1464427116e9c4eaa
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jun 10 11:34:55 2025 +0200

    platform/x86/intel-uncore-freq: avoid non-literal format string

    Using a string variable in place of a format string causes a W=1 build warning:

    drivers/platform/x86/intel/uncore-frequency/uncore-frequency-common.c:61:40: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
       61 |                 length += sysfs_emit_at(buf, length, agent_name[agent]);
          |                                                      ^~~~~~~~~~~~~~~~~

    Use the safer "%s" format string to print it instead.

    Fixes: b98fa870fce2 ("platform/x86/intel-uncore-freq: Add attributes to show agent types")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Tested-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Link: https://lore.kernel.org/r/20250610093459.2646337-1-arnd@kernel.org
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>

Signed-off-by: Steve Best <sbest@redhat.com>