md/raid5: use do_div() for 64 bit divisions in raid5_sync_request
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Yufen Yu <yuyufen@huawei.com>
commit 83c3e5e17b5e3057ac304383a46e3c485d00ffed

We get compilation error on 32-bit architectures (e.g. m68k), as:

  ERROR: modpost: "__udivdi3" [drivers/md/raid456.ko] undefined!

Since 'sync_blocks' is defined as u64, use do_div() to fix this error.

Fixes: c911c46c017c ("md/raid456: convert macro STRIPE_* to RAID5_STRIPE_*")
	Signed-off-by: Yufen Yu <yuyufen@huawei.com>
	Signed-off-by: Song Liu <songliubraving@fb.com>
(cherry picked from commit 83c3e5e17b5e3057ac304383a46e3c485d00ffed)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>