[s390] s390/ctcm: add __printf format attribute to ctcm_dbf_longtext
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2044295
Upstream Status: https://github.com/torvalds/linux.git
Tested: by IBM
Build-info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45699913
Conflicts: None

commit dddbf91387a04a03a8e071cb4857403df219382e
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Thu Nov 18 17:06:06 2021 +0100

    s390/ctcm: add __printf format attribute to ctcm_dbf_longtext

    Allow the compiler to recognize and check format strings and parameters.

    As reported with allmodconfig and W=1:

    drivers/s390/net/ctcm_dbug.c: In function ‘ctcm_dbf_longtext’:
    drivers/s390/net/ctcm_dbug.c:73:9: error: function ‘ctcm_dbf_longtext’ might be a candidate for ‘gnu_printf’ format attribute [-Werror=suggest-attribute=format]
       73 |         vsnprintf(dbf_txt_buf, sizeof(dbf_txt_buf), fmt, args);
          |         ^~~~~~~~~

    Acked-by: Julian Wiedmann <jwi@linux.ibm.com>
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Karsten Graul <kgraul@linux.ibm.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Mete Durlu <mdurlu@redhat.com>