Revert "usb: mtu3: fix up undefined reference to usb_debug_root"
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Chunfeng Yun <chunfeng.yun@mediatek.com>
commit e137d34f94ebcb6508d7c8614ac045583fffbe2a

It's not needed after [1] is applied, because usb_debug_root is created
by usb common core but not usbcore now.

[1] 812086d362a1 ("USB: move usb debugfs directory creation to the usb common core")

	Signed-off-by: Chunfeng Yun <chunfeng.yun@mediatek.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit e137d34f94ebcb6508d7c8614ac045583fffbe2a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>