fwctl/cxl: Fix uuid_t usage in uapi
JIRA: https://issues.redhat.com/browse/RHEL-107284

commit 7bdd8f75d16557ee4111c7b2678463cabf0f04c3
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Thu Apr 10 11:27:40 2025 -0700

    fwctl/cxl: Fix uuid_t usage in uapi

    The uuid_t type is kernel internal, and Paul reports the following build
    error when it is used in a uapi header:

        usr/include/cxl/features.h:59:9: error: unknown type name ‘uuid_t’

    Create a uuid type (__uapi_uuid_t) compatible with the longstanding
    definition uuid/uuid.h for userspace builds, and use uuid_t directly for
    kernel builds.

    Fixes: 9b8e73cdb141 ("cxl: Move cxl feature command structs to user header")
    Link: https://patch.msgid.link/r/174430961702.617339.13963021112051029933.stgit@dwillia2-xfh.jf.intel.com
    Suggested-by: Jason Gunthorpe <jgg@nvidia.com>
    Reported-by: Paul E. McKenney <paulmck@kernel.org>
    Closes: http://lore.kernel.org/f6489337-67c7-48c8-b48a-58603ec15328@paulmck-laptop
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202504050434.Eb4vugh5-lkp@intel.com/
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
    Reviewed-by: Dave Jiang <dave.jiang@intel.com>
    Tested-by: Paul E. McKenney <paulmck@kernel.org>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: John W. Linville <linville@redhat.com>