tools/virtio: fix missing kmemleak_ignore symbol
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Joel Stanley <joel@jms.id.au>
commit 6abb2dd92868927c1d680546b9d13f208373d517

In commit bb478d8b167 virtio_ring: plug kmemleak false positive,
kmemleak_ignore was introduced. This broke compilation of virtio_test:

  cc -g -O2 -Wall -I. -I ../../usr/include/ -Wno-pointer-sign
    -fno-strict-overflow -fno-strict-aliasing -fno-common -MMD
    -U_FORTIFY_SOURCE   -c -o virtio_ring.o ../../drivers/virtio/virtio_ring.c
  ../../drivers/virtio/virtio_ring.c: In function ‘vring_add_indirect’:
  ../../drivers/virtio/virtio_ring.c:177:2: warning: implicit declaration
  of function ‘kmemleak_ignore’ [-Wimplicit-function-declaration]
    kmemleak_ignore(desc);
    ^
  cc   virtio_test.o virtio_ring.o   -o virtio_test
  virtio_ring.o: In function `vring_add_indirect':
  tools/virtio/../../drivers/virtio/virtio_ring.c:177:
  undefined reference to `kmemleak_ignore'

Add a dummy header for tools/virtio, and add #incldue <linux/kmemleak.h>
to drivers/virtio/virtio_ring.c so it is picked up by the userspace
tools.

	Signed-off-by: Joel Stanley <joel@jms.id.au>
	Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
(cherry picked from commit 6abb2dd92868927c1d680546b9d13f208373d517)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>