mfd: cs42l43: Fix MFD_CS42L43 dependency on REGMAP_IRQ
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 9ef4dc24eb85f9e95ef183d09ae622b8efc34783
Author: Woody Zhang <woodylab@foxmail.com>
Date: Tue Sep 5 19:41:00 2023 +0800

    mfd: cs42l43: Fix MFD_CS42L43 dependency on REGMAP_IRQ

    MFD_CS42L43 depends on REGMAP_IRQ as it uses devm_regmap_add_irq_chip.
    Otherwise the build may fail with following log.

      AR      drivers/built-in.a
      AR      built-in.a
      AR      vmlinux.a
      LD      vmlinux.o
      OBJCOPY modules.builtin.modinfo
      GEN     modules.builtin
      MODPOST Module.symvers
    ERROR: modpost: "devm_regmap_add_irq_chip" [drivers/mfd/cs42l43.ko] undefined!

    Fixes: ace6d1448138 ("mfd: cs42l43: Add support for cs42l43 core driver")
    Signed-off-by: Woody Zhang <woodylab@foxmail.com>
    Acked-by: Charles Keepax <ckeepax@opensource.cirrus.com>
    Link: https://lore.kernel.org/r/tencent_E54C7156F583E15FFE320E576E3389C39A08@qq.com
    Signed-off-by: Lee Jones <lee@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>