init: consolidate prototypes in linux/init.h
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit ad1a48301f659a02df5bff0a121d4a5c0411d36b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 15:10:59 2023 +0200

    init: consolidate prototypes in linux/init.h

    The init/main.c file contains some extern declarations for functions
    defined in architecture code, and it defines some other functions that are
    called from architecture code with a custom prototype.  Both of those
    result in warnings with 'make W=1':

    init/calibrate.c:261:37: error: no previous prototype for 'calibrate_delay_is_known' [-Werror=missing-prototypes]
    init/main.c:790:20: error: no previous prototype for 'mem_encrypt_init' [-Werror=missing-prototypes]
    init/main.c:792:20: error: no previous prototype for 'poking_init' [-Werror=missing-prototypes]
    arch/arm64/kernel/irq.c:122:13: error: no previous prototype for 'init_IRQ' [-Werror=missing-prototypes]
    arch/arm64/kernel/time.c:55:13: error: no previous prototype for 'time_init' [-Werror=missing-prototypes]
    arch/x86/kernel/process.c:935:13: error: no previous prototype for 'arch_post_acpi_subsys_init' [-Werror=missing-prototypes]
    init/calibrate.c:261:37: error: no previous prototype for 'calibrate_delay_is_known' [-Werror=missing-prototypes]
    kernel/fork.c:991:20: error: no previous prototype for 'arch_task_cache_init' [-Werror=missing-prototypes]

    Add prototypes for all of these in include/linux/init.h or another
    appropriate header, and remove the duplicate declarations from
    architecture specific code.

    [sfr@canb.auug.org.au: declare time_init_early()]
      Link: https://lkml.kernel.org/r/20230519124311.5167221c@canb.auug.org.au
    Link: https://lkml.kernel.org/r/20230517131102.934196-12-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Boqun Feng <boqun.feng@gmail.com>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Christoph Lameter <cl@linux.com>
    Cc: Dennis Zhou <dennis@kernel.org>
    Cc: Eric Paris <eparis@redhat.com>
    Cc: Heiko Carstens <hca@linux.ibm.com>
    Cc: Helge Deller <deller@gmx.de>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Cc: Michal Simek <monstr@monstr.eu>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Paul Moore <paul@paul-moore.com>
    Cc: Pavel Machek <pavel@ucw.cz>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rafael J. Wysocki <rafael@kernel.org>
    Cc: Russell King <linux@armlinux.org.uk>
    Cc: Tejun Heo <tj@kernel.org>
    Cc: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Waiman Long <longman@redhat.com>
    Cc: Will Deacon <will@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Conflicts:
	arch/powerpc/include/asm/irq.h
	arch/riscv/include/asm/irq.h
	(unsupported in RHEL)

RHEL-only: add #include <linux/maple_tree.h> to main.c as RHEL lacks
d4af56c5c7c67 backport.

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>