x86/mm: Add early_memremap_pgprot_adjust() prototype
JIRA: https://issues.redhat.com/browse/RHEL-27742

This patch is a backport of the following upstream commit:
commit 4d312ac057da57b4a844ec8af14236e74b652efe
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:47 2023 +0200

    x86/mm: Add early_memremap_pgprot_adjust() prototype

    early_memremap_pgprot_adjust() is a __weak function with a local
    prototype, but x86 has a custom implementation that does not
    see the prototype, causing a W=1 warning:

    arch/x86/mm/ioremap.c:785:17: error: no previous prototype for 'early_memremap_pgprot_adjust' [-Werror=missing-prototypes]

    Move the declaration into the global linux/io.h header to avoid this.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-19-arnd%40kernel.org

Signed-off-by: Rafael Aquini <raquini@redhat.com>