ASoC: codecs: aw88261: avoid uninitialized variable warning
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 87b56172431bc2e8c497d2f10ee8245313167bd9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Aug 8 14:56:54 2023 +0200

    ASoC: codecs: aw88261: avoid uninitialized variable warning

    aw88261_reg_update() returns an unintialized error code in the
    success path:

    sound/soc/codecs/aw88261.c:651:7: error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
                    if (aw_dev->prof_cur != aw_dev->prof_index) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    sound/soc/codecs/aw88261.c:660:9: note: uninitialized use occurs here
            return ret;
                   ^~~
    sound/soc/codecs/aw88261.c:651:3: note: remove the 'if' if its condition is always true
                    if (aw_dev->prof_cur != aw_dev->prof_index) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Return zero instead here.

    Fixes: 028a2ae256916 ("ASoC: codecs: Add aw88261 amplifier driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230808125703.1611325-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>