x86: Export 'boot_cpu_physical_apicid' to modules
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author David Rientjes <rientjes@google.com>
commit cc08e04c3fdcaab767b8db27527002b2b4d758cb

Commit 9ebddac7ea2a "ACPI, x86: Fix extended error log driver to depend on
CONFIG_X86_LOCAL_APIC" fixed a build error when CONFIG_X86_LOCAL_APIC was not
selected and !CONFIG_SMP.

However, since CONFIG_ACPI_EXTLOG is tristate, there is a second build error:

  ERROR: "boot_cpu_physical_apicid" [drivers/acpi/acpi_extlog.ko] undefined!

The symbol needs to be exported for it to be available.

	Signed-off-by: David Rientjes <rientjes@google.com>
	Acked-by: Tony Luck <tony.luck@intel.com>
	Cc: Chen Gong <gong.chen@linux.intel.com>
	Cc: Rafael J. Wysocki <rjw@rjwysocki.net>
Link: http://lkml.kernel.org/r/alpine.DEB.2.02.1311141504080.30112@chino.kir.corp.google.com
[ Changed it to a _GPL() export. ]
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit cc08e04c3fdcaab767b8db27527002b2b4d758cb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>