powerpc/64s: Include <asm/nmi.h> header file to fix a warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Mathieu Malaterre <malat@debian.org>
commit de3c83c2fd2b87cf68214eda76dfa66989d78cb6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-310.el8/de3c83c2.failed

Make sure to include <asm/nmi.h> to provide the following prototype:
hv_nmi_check_nonrecoverable.

Remove the following warning treated as error (W=1):

  arch/powerpc/kernel/traps.c:393:6: error: no previous prototype for 'hv_nmi_check_nonrecoverable'

Fixes: ccd477028a20 ("powerpc/64s: Fix HV NMI vs HV interrupt recoverability test")
	Signed-off-by: Mathieu Malaterre <malat@debian.org>
	Reviewed-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit de3c83c2fd2b87cf68214eda76dfa66989d78cb6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/kernel/traps.c