tools/net/ynl: ethtool: fix crash when Hardware Clock info is missing
JIRA: https://issues.redhat.com/browse/RHEL-89014

commit 45375814eb3f4245956c0c85092a4eee4441d167
Author: Hangbin Liu <liuhangbin@gmail.com>
Date:   Thu May 8 03:54:14 2025 +0000

    tools/net/ynl: ethtool: fix crash when Hardware Clock info is missing

    Fix a crash in the ethtool YNL implementation when Hardware Clock information
    is not present in the response. This ensures graceful handling of devices or
    drivers that do not provide this optional field. e.g.

      Traceback (most recent call last):
        File "/net/tools/net/ynl/pyynl/./ethtool.py", line 438, in <module>
          main()
          ~~~~^^
        File "/net/tools/net/ynl/pyynl/./ethtool.py", line 341, in main
          print(f'PTP Hardware Clock: {tsinfo["phc-index"]}')
                                       ~~~~~~^^^^^^^^^^^^^
      KeyError: 'phc-index'

    Fixes: f3d07b02b2b8 ("tools: ynl: ethtool testing tool")
    Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
    Acked-by: Stanislav Fomichev <sdf@fomichev.me>
    Link: https://patch.msgid.link/20250508035414.82974-1-liuhangbin@gmail.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Heib <mheib@redhat.com>