selinux: use kernel linux/socket.h for genheaders and mdp
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Paulo Alcantara <paulo@paulo.ac>
commit ff1bf4c0714e7936330bb316090a75eaa35061e7
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/ff1bf4c0.failed

When compiling genheaders and mdp from a newer host kernel, the
following error happens:

    In file included from scripts/selinux/genheaders/genheaders.c:18:
    ./security/selinux/include/classmap.h:238:2: error: #error New
    address family defined, please update secclass_map.  #error New
    address family defined, please update secclass_map.  ^~~~~
    make[3]: *** [scripts/Makefile.host:107:
    scripts/selinux/genheaders/genheaders] Error 1 make[2]: ***
    [scripts/Makefile.build:599: scripts/selinux/genheaders] Error 2
    make[1]: *** [scripts/Makefile.build:599: scripts/selinux] Error 2
    make[1]: *** Waiting for unfinished jobs....

Instead of relying on the host definition, include linux/socket.h in
classmap.h to have PF_MAX.

	Signed-off-by: Paulo Alcantara <paulo@paulo.ac>
	Acked-by: Stephen Smalley <sds@tycho.nsa.gov>
[PM: manually merge in mdp.c, subject line tweaks]
	Signed-off-by: Paul Moore <paul@paul-moore.com>
(cherry picked from commit ff1bf4c0714e7936330bb316090a75eaa35061e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	scripts/selinux/mdp/mdp.c