fbdev: uvesafb: don't build on UML
JIRA: https://issues.redhat.com/browse/RHEL-23295
Upstream Status: v6.2-rc1

commit 35b4f4d4a725cf8f8c10649163cd12aed509b953
Author:     Randy Dunlap <rdunlap@infradead.org>
AuthorDate: Wed Nov 30 13:55:59 2022 -0800
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Wed Dec 14 20:01:51 2022 +0100

    The uvesafb fbdev driver uses memory management information that is not
    available on ARCH=um, so don't allow this driver to be built on UML.

    Prevents these build errors:

    ../drivers/video/fbdev/uvesafb.c: In function ‘uvesafb_vbe_init’:
    ../drivers/video/fbdev/uvesafb.c:807:21: error: ‘__supported_pte_mask’ undeclared (first use in this function)
      807 |                 if (__supported_pte_mask & _PAGE_NX) {
    ../drivers/video/fbdev/uvesafb.c:807:44: error: ‘_PAGE_NX’ undeclared (first use in this function)
      807 |                 if (__supported_pte_mask & _PAGE_NX) {

    Fixes: 68f5d3f3b654 ("um: add PCI over virtio emulation driver")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Johannes Berg <johannes@sipsolutions.net>
    Cc: Richard Weinberger <richard@nod.at>
    Cc: linux-um@lists.infradead.org
    Cc: Daniel Vetter <daniel@ffwll.ch>
    Cc: Helge Deller <deller@gmx.de>
    Cc: linux-fbdev@vger.kernel.org
    Cc: dri-devel@lists.freedesktop.org
    Cc: Michal Januszewski <spock@gentoo.org>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>