ipmi: ssif_bmc: Fix KUnit test link failure when KUNIT=m
JIRA: https://redhat.atlassian.net/browse/RHEL-169911
Upstream status: v7.0+

commit 93b5d21e8b5cbdc3e439b94feee9b013e8170905
Author: Jian Zhang <zhangjian.3032@bytedance.com>
Date:   Tue Apr 7 17:46:47 2026 +0800

    ipmi: ssif_bmc: Fix KUnit test link failure when KUNIT=m

    Building with CONFIG_KUNIT=m and CONFIG_SSIF_IPMI_BMC_KUNIT_TEST=y
    results in link errors such as:

      undefined reference to `kunit_binary_assert_format'
      undefined reference to `__kunit_do_failed_assertion'

    This happens because the test code is built-in while the KUnit core
    is built as a module, so the required KUnit symbols are not available
    at link time.

    Fix this by requiring KUNIT to be built-in when enabling
    SSIF_IPMI_BMC_KUNIT_TEST.

    Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202604071448.zUBjPYPu-lkp@intel.com/
    Message-ID: <20260407094647.356661-1-zhangjian.3032@bytedance.com>
    Signed-off-by: Corey Minyard <corey@minyard.net>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>