drm/amdgpu: Fix type of second parameter in odn_edit_dpm_table() callback
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2115902
Upstream Status: v6.0.16

commit 24cba9d865157c9e23128fbcf8b86f5da9570edd
Author:     Nathan Chancellor <nathan@kernel.org>
AuthorDate: Wed Nov  2 08:25:40 2022 -0700
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Sat Dec 31 13:26:43 2022 +0100

    [ Upstream commit e4d0ef752081e7aa6ffb7ccac11c499c732a2e05 ]

    With clang's kernel control flow integrity (kCFI, CONFIG_CFI_CLANG),
    indirect call targets are validated against the expected function
    pointer prototype to make sure the call target is valid to help mitigate
    ROP attacks. If they are not identical, there is a failure at run time,
    which manifests as either a kernel panic or thread getting killed. A
    proposed warning in clang aims to catch these at compile time, which
    reveals:

      drivers/gpu/drm/amd/amdgpu/../pm/swsmu/amdgpu_smu.c:3008:29: error: incompatible function pointer types initializing 'int (*)(void *, uint32_t, long *, uint32_t)' (aka 'int (*)(void *, unsigned int, long *, unsigned int)') with an expression of type 'int (void *, enum PP_OD_DPM_TABLE_COMMAND, long *, uint32_t)' (aka 'int (void *, enum PP_OD_DPM_TABLE_COMMAND, long *, unsigned int)') [-Werror,-Wincompatible-function-pointer-types-strict]
              .odn_edit_dpm_table      = smu_od_edit_dpm_table,
                                         ^~~~~~~~~~~~~~~~~~~~~
      1 error generated.

    There are only two implementations of ->odn_edit_dpm_table() in 'struct
    amd_pm_funcs': smu_od_edit_dpm_table() and pp_odn_edit_dpm_table(). One
    has a second parameter type of 'enum PP_OD_DPM_TABLE_COMMAND' and the
    other uses 'u32'. Ultimately, smu_od_edit_dpm_table() calls
    ->od_edit_dpm_table() from 'struct pptable_funcs' and
    pp_odn_edit_dpm_table() calls ->odn_edit_dpm_table() from 'struct
    pp_hwmgr_func', which both have a second parameter type of 'enum
    PP_OD_DPM_TABLE_COMMAND'.

    Update the type parameter in both the prototype in 'struct amd_pm_funcs'
    and pp_odn_edit_dpm_table() to 'enum PP_OD_DPM_TABLE_COMMAND', which
    cleans up the warning.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1750
    Reported-by: Sami Tolvanen <samitolvanen@google.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>