perf tools: Work around lack of sched_getcpu in glibc < 2.6.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] tools: Work around lack of sched_getcpu in glibc < 2.6 (Jiri Olsa) [1222189]
Rebuild_FUZZ: 94.74%
commit-author Vinson Lee <vlee@twitter.com>
commit e1e455f4f4d35850c30235747620d0d078fe9f64

This patch fixes this build error with glibc < 2.6.

  CC       util/cloexec.o
cc1: warnings being treated as errors
util/cloexec.c: In function ‘perf_flag_probe’:
util/cloexec.c:24: error: implicit declaration of function
‘sched_getcpu’
util/cloexec.c:24: error: nested extern declaration of ‘sched_getcpu’
make: *** [util/cloexec.o] Error 1

	Signed-off-by: Vinson Lee <vlee@twitter.com>
	Acked-by: Jiri Olsa <jolsa@kernel.org>
	Acked-by: Namhyung Kim <namhyung@kernel.org>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Yann Droneaud <ydroneaud@opteya.com>
	Cc: stable@vger.kernel.org # 3.18+
Link: http://lkml.kernel.org/r/1427137761-16119-1-git-send-email-vlee@twopensource.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit e1e455f4f4d35850c30235747620d0d078fe9f64)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>