net: i40e: shut up uninitialized variable warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [netdrv] i40e: shut up uninitialized variable warnings (Stefan Assmann) [1269238 1272322 1274176 1281279 1293277 1310436]
Rebuild_FUZZ: 94.74%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 79febbc19b81b5242339bffb90e4dbea15015dde

intel/i40e/i40e_txrx.c: In function 'i40e_xmit_frame_ring':
intel/i40e/i40e_txrx.c:2367:20: error: 'oiph' may be used uninitialized in this function [-Werror=maybe-uninitialized]
intel/i40e/i40e_txrx.c:2317:16: note: 'oiph' was declared here
intel/i40e/i40e_txrx.c:2367:17: error: 'oudph' may be used uninitialized in this function [-Werror=maybe-uninitialized]
intel/i40e/i40e_txrx.c:2316:17: note: 'oudph' was declared here

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
	Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
(cherry picked from commit 79febbc19b81b5242339bffb90e4dbea15015dde)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>