dmaengine: tegra: Fix build error without IOMMU_API
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2135064

commit 2cdd3ca67aeabf4d6274af2d1c7e22f17a33dd64
Author: YueHaibing <yuehaibing@huawei.com>
Date: Thu, 5 May 2022 17:32:36 +0800

    drivers/dma/tegra186-gpc-dma.c: In function ‘tegra_dma_probe’:
    drivers/dma/tegra186-gpc-dma.c:1364:24: error: ‘struct iommu_fwspec’ has no member named ‘ids’
      stream_id = iommu_spec->ids[0] & 0xffff;
                            ^~

    Make TEGRA186_GPC_DMA depends on IOMMU_API to fix this.

    Fixes: ee17028009d4 ("dmaengine: tegra: Add tegra gpcdma driver")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Link: https://lore.kernel.org/r/20220505093236.15076-1-yuehaibing@huawei.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>