selftests: mlxsw: resource_scale: Fix return value
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2140704

commit 196f9bc050cbc5085b4cbb61cce2efe380bc66d0
Author: Amit Cohen <amcohen@nvidia.com>
Date:   Wed Mar 2 18:14:47 2022 +0200

    selftests: mlxsw: resource_scale: Fix return value

    The test runs several test cases and is supposed to return an error in
    case at least one of them failed.

    Currently, the check of the return value of each test case is in the
    wrong place, which can result in the wrong return value. For example:

     # TESTS='tc_police' ./resource_scale.sh
     TEST: 'tc_police' [default] 968                                     [FAIL]
             tc police offload count failed
     Error: mlxsw_spectrum: Failed to allocate policer index.
     We have an error talking to the kernel
     Command failed /tmp/tmp.i7Oc5HwmXY:969
     TEST: 'tc_police' [default] overflow 969                            [ OK ]
     ...
     TEST: 'tc_police' [ipv4_max] overflow 969                           [ OK ]

     $ echo $?
     0

    Fix this by moving the check to be done after each test case.

    Fixes: 059b18e21c63 ("selftests: mlxsw: Return correct error code in resource scale test")
    Signed-off-by: Amit Cohen <amcohen@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>