ixgbe/ixgbevf: fix XFRM_ALGO dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Jeff Kirsher <jeffrey.t.kirsher@intel.com>
commit 48e01e001da31d5a40e31ed5f8cea83a18823cc1

Based on the original work from Arnd Bergmann.

When XFRM_ALGO is not enabled, the new ixgbe IPsec code produces a
link error:

drivers/net/ethernet/intel/ixgbe/ixgbe_ipsec.o: In function `ixgbe_ipsec_vf_add_sa':
ixgbe_ipsec.c:(.text+0x1266): undefined reference to `xfrm_aead_get_byname'

Simply selecting XFRM_ALGO from here causes circular dependencies, so
to fix it, we probably want this slightly more complex solution that is
similar to what other drivers with XFRM offload do:

A separate Kconfig symbol now controls whether we include the IPsec
offload code. To keep the old behavior, this is left as 'default y'. The
dependency in XFRM_OFFLOAD still causes a circular dependency but is
not actually needed because this symbol is not user visible, so removing
that dependency on top makes it all work.

CC: Arnd Bergmann <arnd@arndb.de>
CC: Shannon Nelson <shannon.nelson@oracle.com>
Fixes: eda0333ac293 ("ixgbe: add VF IPsec management")
	Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
	Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
(cherry picked from commit 48e01e001da31d5a40e31ed5f8cea83a18823cc1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>