scsi: qla2xxx: Fix compilation issue in PPC systems
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Arun Easi <aeasi@marvell.com>
commit aceba54ba0f998ed6bec88faaf94e7458f753399

Fix compile time errors reported on PPC systems,

qla_gbl.h:991:20: error: inlining failed in call to always_inline
     ‘qla_nvme_abort_set_option’: function body not available

Link: https://lore.kernel.org/r/20201202132312.19966-7-njavali@marvell.com
	Signed-off-by: Arun Easi <aeasi@marvell.com>
	Signed-off-by: Nilesh Javali <njavali@marvell.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit aceba54ba0f998ed6bec88faaf94e7458f753399)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>