bpf: Fix a compilation failure with clang lto build
Bugzilla: https://bugzilla.redhat.com/2177177

commit 3144bfa5078e0df7507a4de72061501e6a0e56be
Author: Yonghong Song <yhs@fb.com>
Date:   Tue Nov 29 21:21:47 2022 -0800

    bpf: Fix a compilation failure with clang lto build

    When building the kernel with clang lto (CONFIG_LTO_CLANG_FULL=y), the
    following compilation error will appear:

      $ make LLVM=1 LLVM_IAS=1 -j
      ...
      ld.lld: error: ld-temp.o <inline asm>:26889:1: symbol 'cgroup_storage_map_btf_ids' is already defined
      cgroup_storage_map_btf_ids:;
      ^
      make[1]: *** [/.../bpf-next/scripts/Makefile.vmlinux_o:61: vmlinux.o] Error 1

    In local_storage.c, we have
      BTF_ID_LIST_SINGLE(cgroup_storage_map_btf_ids, struct, bpf_local_storage_map)
    Commit c4bcfb38a95e ("bpf: Implement cgroup storage available to
    non-cgroup-attached bpf progs") added the above identical BTF_ID_LIST_SINGLE
    definition in bpf_cgrp_storage.c. With duplicated definitions, llvm linker
    complains with lto build.

    Also, extracting btf_id of 'struct bpf_local_storage_map' is defined four times
    for sk, inode, task and cgrp local storages. Let us define a single global one
    with a different name than cgroup_storage_map_btf_ids, which also fixed
    the lto compilation error.

    Fixes: c4bcfb38a95e ("bpf: Implement cgroup storage available to non-cgroup-attached bpf progs")
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20221130052147.1591625-1-yhs@fb.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>