PCI: Move pci_set_flags() from asm-generic/pci-bridge.h to linux/pci.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [pci] Move pci_set_flags() from asm-generic/pci-bridge.h to linux/pci.h (Myron Stowe) [1392577]
Rebuild_FUZZ: 96.30%
commit-author Bjorn Helgaas <bhelgaas@google.com>
commit 5bbe029ff7bc8ff82ef31d3480d68c95642a3c7a

The PCI flag management constants and functions were previously declared in
include/asm-generic/pci-bridge.h.  But they are not specific to bridges,
and arches did not include pci-bridge.h consistently.

Move the following interfaces and related constants to include/linux/pci.h
and remove pci-bridge.h:

  pci_set_flags()
  pci_add_flags()
  pci_clear_flags()
  pci_has_flag()

This fixes these warnings when building for some arches:

  drivers/pci/host/pcie-designware.c:562:20: error: 'PCI_PROBE_ONLY' undeclared (first use in this function)
  drivers/pci/host/pcie-designware.c:562:7: error: implicit declaration of function 'pci_has_flag' [-Werror=implicit-function-declaration]

	Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
(cherry picked from commit 5bbe029ff7bc8ff82ef31d3480d68c95642a3c7a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>