x86/init: fix build with CONFIG_SWAP=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Vlastimil Babka <vbabka@suse.cz>
commit 792adb90fa724ce07c0171cbc96b9215af4b1045

The introduction of generic_max_swapfile_size and arch-specific versions has
broken linking on x86 with CONFIG_SWAP=n due to undefined reference to
'generic_max_swapfile_size'. Fix it by compiling the x86-specific
max_swapfile_size() only with CONFIG_SWAP=y.

	Reported-by: Tomas Pruzina <pruzinat@gmail.com>
Fixes: 377eeaa8e11f ("x86/speculation/l1tf: Limit swap file size to MAX_PA/2")
	Signed-off-by: Vlastimil Babka <vbabka@suse.cz>
	Cc: stable@vger.kernel.org
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 792adb90fa724ce07c0171cbc96b9215af4b1045)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>