mailbox: qcom-ipcc: Fix -Wunused-function with CONFIG_PM_SLEEP=n
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2124638
Upstream Status: 79f9fbe303520d2c32b70f04f2bb02cc2baaa4c3

commit 79f9fbe303520d2c32b70f04f2bb02cc2baaa4c3
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon May 23 15:47:02 2022 -0700

    mailbox: qcom-ipcc: Fix -Wunused-function with CONFIG_PM_SLEEP=n

    When CONFIG_PM_SLEEP is not set, there is a warning that
    qcom_ipcc_pm_resume() is unused:

      drivers/mailbox/qcom-ipcc.c:258:12: error: 'qcom_ipcc_pm_resume' defined but not used [-Werror=unused-function]
        258 | static int qcom_ipcc_pm_resume(struct device *dev)
            |            ^~~~~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors

    Commit 1a3c7bb08826 ("PM: core: Add new *_PM_OPS macros, deprecate old
    ones") reworked the PM_OPS macros to avoid this problem. Use
    NOIRQ_SYSTEM_SLEEP_PM_OPS directly so that qcom_ipcc_pm_resume() always
    appears to be used to the compiler, even though it will be dead code
    eliminated in the !CONFIG_PM_SLEEP case.

    Fixes: c25f77899753 ("mailbox: qcom-ipcc: Log the pending interrupt during resume")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Sibi Sankar <quic_sibis@quicinc.com>
    Signed-off-by: Jassi Brar <jaswinder.singh@linaro.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>