dmaengine: idxd: fix PCI_MSI build errors
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit d6a7bb869dd8a516901591136a9a895fd829d6c6

Fix build errors when CONFIG_PCI_MSI is not enabled by making the
driver depend on PCI_MSI:

ld: drivers/dma/idxd/device.o: in function `idxd_mask_msix_vector':
device.c:(.text+0x26f): undefined reference to `pci_msi_mask_irq'
ld: drivers/dma/idxd/device.o: in function `idxd_unmask_msix_vector':
device.c:(.text+0x2af): undefined reference to `pci_msi_unmask_irq'

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Dave Jiang <dave.jiang@intel.com>
	Cc: dmaengine@vger.kernel.org
	Cc: Vinod Koul <vkoul@kernel.org>
Link: https://lore.kernel.org/r/9dee3f46-70d9-ea75-10cb-5527ab297d1d@infradead.org
	Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit d6a7bb869dd8a516901591136a9a895fd829d6c6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>