media: gspca/gl860-mi1320/ov9655: avoid -Wstring-concatenation warning
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 3ae5c3bc07f602c7abbfad1c75f3d288851a9611
Author: Hans Verkuil <hverkuil-cisco@xs4all.nl>
Date:   Mon Oct 4 15:09:33 2021 +0100

    media: gspca/gl860-mi1320/ov9655: avoid -Wstring-concatenation warning

    Newer clang versions are suspicious of definitions that mix concatenated
    strings with comma-separated arrays of strings, this has found real bugs
    elsewhere, but this seems to be a false positive:

    drivers/media/usb/gspca/gl860/gl860-mi1320.c:62:37: error: suspicious concatenation of string literals in an array initialization; did you
    mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
            "\xd3\x02\xd4\x28\xd5\x01\xd0\x02" "\xd1\x18\xd2\xc1"
                                               ^
                                              ,
    drivers/media/usb/gspca/gl860/gl860-mi1320.c:62:2: note: place parentheses around the string literal to silence warning
            "\xd3\x02\xd4\x28\xd5\x01\xd0\x02" "\xd1\x18\xd2\xc1"

    Replace the string literals by compound initializers, using normal hex numbers.

    Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Torez Smith <torez@redhat.com>