runqslower: Fix Makefile
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Yulia Kartseva <hex@fb.com>
commit 2577e373bbc07f18680287b3958d3b2fdebe4b20

Fix undefined reference linker errors when building runqslower with
gcc 7.4.0 on Ubuntu 18.04.
The issue is with misplaced -lelf, -lz options in Makefile:
$(Q)$(CC) $(CFLAGS) -lelf -lz $^ -o $@

-lelf, -lz options should follow the list of target dependencies:
$(Q)$(CC) $(CFLAGS) $^ -lelf -lz -o $@
or after substitution
cc -g -Wall runqslower.o libbpf.a -lelf -lz -o runqslower

The current order of gcc params causes failure in libelf symbols resolution,
e.g. undefined reference to `elf_memory'

Fixes: 9c01546d26d2 ("tools/bpf: Add runqslower tool to tools/bpf")
	Signed-off-by: Julia Kartseva <hex@fb.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
	Acked-by: Andrii Nakryiko <andriin@fb.com>
Link: https://lore.kernel.org/bpf/908498f794661c44dca54da9e09dc0c382df6fcb.1580425879.git.hex@fb.com
(cherry picked from commit 2577e373bbc07f18680287b3958d3b2fdebe4b20)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>