wifi: iwlwifi: Avoid disabling GCC specific flag with clang
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit 499183cc3b52613f06cf4ce70809546971c96ed8

Clang errors:

  drivers/net/wireless/intel/iwlwifi/iwl-devtrace.c:15:32: error: unknown warning group '-Wsuggest-attribute=format', ignored [-Werror,-Wunknown-warning-option]
  #pragma GCC diagnostic ignored "-Wsuggest-attribute=format"
                                 ^
  1 error generated.

The warning being disabled by this pragma is GCC specific. Guard its use
with CONFIG_CC_IS_GCC so that it is not used with clang to clear up the
error.

Fixes: 4eca8cbf7ba8 ("wifi: iwlwifi: suppress printf warnings in tracing")
Link: https://github.com/ClangBuiltLinux/linux/issues/1818
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Link: https://lore.kernel.org/r/20230315-iwlwifi-fix-pragma-v1-1-ad23f92c4739@kernel.org
	Signed-off-by: Johannes Berg <johannes.berg@intel.com>
(cherry picked from commit 499183cc3b52613f06cf4ce70809546971c96ed8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>