vfio/pci: set TRACE_INCLUDE_PATH to fix the build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Masahiro Yamada <yamada.masahiro@socionext.com>
commit d1fc1176c055c9ec9c6ec4d113a284e0bad9d09a
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-147.el8/d1fc1176.failed

drivers/vfio/pci/vfio_pci_nvlink2.c cannot be compiled for in-tree
building.

    CC      drivers/vfio/pci/vfio_pci_nvlink2.o
  In file included from drivers/vfio/pci/trace.h:102,
                   from drivers/vfio/pci/vfio_pci_nvlink2.c:29:
  ./include/trace/define_trace.h:89:42: fatal error: ./trace.h: No such file or directory
   #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
                                          ^
  compilation terminated.
  make[1]: *** [scripts/Makefile.build;277: drivers/vfio/pci/vfio_pci_nvlink2.o] Error 1

To fix the build error, let's tell include/trace/define_trace.h the
location of drivers/vfio/pci/trace.h

Fixes: 7f92891778df ("vfio_pci: Add NVIDIA GV100GL [Tesla V100 SXM2] subdriver")
	Reported-by: Laura Abbott <labbott@redhat.com>
	Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
	Reviewed-by: Cornelia Huck <cohuck@redhat.com>
	Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
(cherry picked from commit d1fc1176c055c9ec9c6ec4d113a284e0bad9d09a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/vfio/pci/trace.h