ASoC: ops: dynamically allocate struct snd_ctl_elem_value
JIRA: https://issues.redhat.com/browse/RHEL-101627

commit 7e10d7242ea8a5947878880b912ffa5806520705
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Jun 10 11:30:53 2025 +0200

    ASoC: ops: dynamically allocate struct snd_ctl_elem_value

    This structure is really too larget to be allocated on the stack:

    sound/soc/soc-ops.c:435:5: error: stack frame size (1296) exceeds limit (1280) in 'snd_soc_limit_volume' [-Werror,-Wframe-larger-than]

    Change the function to dynamically allocate it instead.

    There is probably a better way to do it since only two integer fields
    inside of that structure are actually used, but this is the simplest
    rework for the moment.

    Fixes: 783db6851c18 ("ASoC: ops: Enforce platform maximum on initial value")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250610093057.2643233-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>