fpga: zynqmp: fix modular build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 6a47d6efc6931b02d10163de2fb85ec9953c4f5e

Two symbols need to be exported to allow the zynqmp-fpga module
to get loaded dynamically:

ERROR: modpost: "zynqmp_pm_fpga_load" [drivers/fpga/zynqmp-fpga.ko] undefined!
ERROR: modpost: "zynqmp_pm_fpga_get_status" [drivers/fpga/zynqmp-fpga.ko] undefined!

To ensure this is done correctly, also fix the Kconfig dependency
to only allow building the fpga driver when the firmware driver is
either disabled, or when it is reachable. With that, the dependency
on the SoC itself can be removed, and there are no surprises when
the fpga driver is built-in but the firmware a module.

Fixes: 4db8180ffe7c ("firmware: xilinx: Remove eemi ops for fpga related APIs")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Moritz Fischer <mdf@kernel.org>
(cherry picked from commit 6a47d6efc6931b02d10163de2fb85ec9953c4f5e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>