selftests/bpf: Fix errors compiling lwt_redirect.c with musl libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 27c4797ce51c8dd51e35e68e9024a892f62d78b2
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:43 2024 -0700

    selftests/bpf: Fix errors compiling lwt_redirect.c with musl libc

    Remove a redundant include of '<linux/icmp.h>' which is already provided in
    'lwt_helpers.h'. This avoids errors seen compiling for mips64el/musl-libc:

      In file included from .../arpa/inet.h:9,
                       from lwt_redirect.c:51:
      .../netinet/in.h:23:8: error: redefinition of 'struct in6_addr'
         23 | struct in6_addr {
            |        ^~~~~~~~
      In file included from .../linux/icmp.h:24,
                       from lwt_redirect.c:50:
      .../linux/in6.h:33:8: note: originally defined here
         33 | struct in6_addr {
            |        ^~~~~~~~
      .../netinet/in.h:34:8: error: redefinition of 'struct sockaddr_in6'
         34 | struct sockaddr_in6 {
            |        ^~~~~~~~~~~~
      .../linux/in6.h:50:8: note: originally defined here
         50 | struct sockaddr_in6 {
            |        ^~~~~~~~~~~~
      .../netinet/in.h:42:8: error: redefinition of 'struct ipv6_mreq'
         42 | struct ipv6_mreq {
            |        ^~~~~~~~~
      .../linux/in6.h:60:8: note: originally defined here
         60 | struct ipv6_mreq {
            |        ^~~~~~~~~

    Fixes: 43a7c3ef8a15 ("selftests/bpf: Add lwt_xmit tests for BPF_REDIRECT")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/3869dda876d5206d2f8d4dd67331c739ceb0c7f8.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>