drm/xe: fix drm_gpusvm_init() arguments
JIRA: https://issues.redhat.com/browse/RHEL-135337

commit 754b10c067f0faf0302ef30b176bcb4b479dd361
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 4 10:46:58 2025 +0100

    drm/xe: fix drm_gpusvm_init() arguments

    [ Upstream commit 9acc3295813b9b846791fd3eab0a78a3144af560 ]

    The Xe driver fails to build when CONFIG_DRM_XE_GPUSVM is disabled
    but CONFIG_DRM_GPUSVM is turned on, due to the clash of two commits:

    In file included from drivers/gpu/drm/xe/xe_vm_madvise.c:8:
    drivers/gpu/drm/xe/xe_svm.h: In function 'xe_svm_init':
    include/linux/stddef.h:8:14: error: passing argument 5 of 'drm_gpusvm_init' makes integer from pointer without a cast [-Wint-conversion]
    drivers/gpu/drm/xe/xe_svm.h:217:38: note: in expansion of macro 'NULL'
      217 |                                NULL, NULL, 0, 0, 0, NULL, NULL, 0);
          |                                      ^~~~
    In file included from drivers/gpu/drm/xe/xe_bo_types.h:11,
                     from drivers/gpu/drm/xe/xe_bo.h:11,
                     from drivers/gpu/drm/xe/xe_vm_madvise.c:11:
    include/drm/drm_gpusvm.h:254:35: note: expected 'long unsigned int' but argument is of type 'void *'
      254 |                     unsigned long mm_start, unsigned long mm_range,
          |                     ~~~~~~~~~~~~~~^~~~~~~~
    In file included from drivers/gpu/drm/xe/xe_vm_madvise.c:14:
    drivers/gpu/drm/xe/xe_svm.h:216:16: error: too many arguments to function 'drm_gpusvm_init'; expected 10, have 11
      216 |         return drm_gpusvm_init(&vm->svm.gpusvm, "Xe SVM (simple)", &vm->xe->drm,
          |                ^~~~~~~~~~~~~~~
      217 |                                NULL, NULL, 0, 0, 0, NULL, NULL, 0);
          |                                                                 ~
    include/drm/drm_gpusvm.h:251:5: note: declared here

    Adapt the caller to the new argument list by removing the extraneous
    NULL argument.

    Fixes: 9e9787414882 ("drm/xe/userptr: replace xe_hmm with gpusvm")
    Fixes: 10aa5c806030 ("drm/gpusvm, drm/xe: Fix userptr to not allow device private pages")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Thomas Hellström <thomas.hellstrom@linux.intel.com>
    Signed-off-by: Thomas Hellström <thomas.hellstrom@linux.intel.com>
    Link: https://patch.msgid.link/20251204094704.1030933-1-arnd@kernel.org
    (cherry picked from commit 29bce9c8b41d5c378263a927acb9a9074d0e7a0e)
    Signed-off-by: Thomas Hellström <thomas.hellstrom@linux.intel.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: José Expósito <jexposit@redhat.com>