net: sched: cls_u32: use hash_ptr() for tc_u_hash
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] sched: cls_u32: use hash_ptr() for tc_u_hash (Ivan Vecera) [1572720]
Rebuild_FUZZ: 94.62%
commit-author Arnd Bergmann <arnd@arndb.de>
commit d18b4b35e310c5e30a3726309a93db8893cd3251

After the change to the tp hash, we now get a build warning
on 32-bit architectures:

net/sched/cls_u32.c: In function 'tc_u_hash':
net/sched/cls_u32.c:338:17: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  return hash_64((u64) tp->chain->block, U32_HASH_SHIFT);

Using hash_ptr() instead of hash_64() lets us drop the cast
and fixes the warning while still resulting in the same hash
value.

Fixes: 7fa9d974f3c2 ("net: sched: cls_u32: use block instead of q in tc_u_common")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Jiri Pirko <jiri@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d18b4b35e310c5e30a3726309a93db8893cd3251)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>