xfrm: checkpatch errors with foo * bar
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Weilong Chen <chenweilong@huawei.com>
commit 3e94c2dcfd7ca297bd7e0a8d96be1e76dec711a3

This patch clean up some checkpatch errors like this:
ERROR: "foo * bar" should be "foo *bar"
ERROR: "(foo*)" should be "(foo *)"

	Signed-off-by: Weilong Chen <chenweilong@huawei.com>
	Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>
(cherry picked from commit 3e94c2dcfd7ca297bd7e0a8d96be1e76dec711a3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>