audit: move trailing statements to next line
JIRA: https://issues.redhat.com/browse/RHEL-9127

This patch is a backport of the following upstream commit:
commit b1a0f64cc65ea2ebfaae9e0ce623e993a7d24257
Author: Atul Kumar Pant <atulpant.linux@gmail.com>
Date:   Wed Aug 16 02:17:51 2023 +0530

    audit: move trailing statements to next line

    Fixes following checkpatch.pl issue:
    ERROR: trailing statements should be on next line

    Signed-off-by: Atul Kumar Pant <atulpant.linux@gmail.com>
    [PM: subject line tweak]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ricardo Robaina <rrobaina@redhat.com>