scsi: tracing: Fix compile error in trace_array calls when TRACING is disabled
Bugzilla: https://bugzilla.redhat.com/2109835

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit 1a77dd1c2bb5d4a58c16d198cf593720787c02e4
Author: Arun Easi <aeasi@marvell.com>
Date:   Wed Sep 7 16:33:08 2022 -0700

    scsi: tracing: Fix compile error in trace_array calls when TRACING is disabled

    Fix this compilation error seen when CONFIG_TRACING is not enabled:

    drivers/scsi/qla2xxx/qla_os.c: In function 'qla_trace_init':
    drivers/scsi/qla2xxx/qla_os.c:2854:25: error: implicit declaration of function
    'trace_array_get_by_name'; did you mean 'trace_array_set_clr_event'?
    [-Werror=implicit-function-declaration]
     2854 |         qla_trc_array = trace_array_get_by_name("qla2xxx");
          |                         ^~~~~~~~~~~~~~~~~~~~~~~
          |                         trace_array_set_clr_event

    drivers/scsi/qla2xxx/qla_os.c: In function 'qla_trace_uninit':
    drivers/scsi/qla2xxx/qla_os.c:2869:9: error: implicit declaration of function
    'trace_array_put' [-Werror=implicit-function-declaration]
     2869 |         trace_array_put(qla_trc_array);
          |         ^~~~~~~~~~~~~~~

    Link: https://lore.kernel.org/r/20220907233308.4153-2-aeasi@marvell.com
    Reported-by: kernel test robot <lkp@intel.com>
    Reviewed-by: Steven Rostedt (Google) <rostedt@goodmis.org>
    Signed-off-by: Arun Easi <aeasi@marvell.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>