md: dm-zoned-target: Initialize return variable r to avoid uninitialized use
JIRA: https://issues.redhat.com/browse/RHEL-119008
Upstream Status: kernel/git/torvalds/linux.git

commit 487767bff572d46f7c37ad846c4078f6d6c9cc55
Author: Purva Yeshi <purvayeshi550@gmail.com>
Date:   Thu Jul 10 13:11:57 2025 +0530

    md: dm-zoned-target: Initialize return variable r to avoid uninitialized use

    Fix Smatch-detected error:
    drivers/md/dm-zoned-target.c:1073 dmz_iterate_devices()
    error: uninitialized symbol 'r'.

    Smatch detects a possible use of the uninitialized variable 'r' in
    dmz_iterate_devices() because if dmz->nr_ddevs is zero, the loop is
    skipped and 'r' is returned without being set, leading to undefined
    behavior.

    Initialize 'r' to 0 before the loop. This ensures that if there are no
    devices to iterate over, the function still returns a defined value.

    Signed-off-by: Purva Yeshi <purvayeshi550@gmail.com>
    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>

Signed-off-by: Benjamin Marzinski <bmarzins@redhat.com>