ipmi_si: fix -Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-12707
Upstream status: v6.5+

commit d40f09c1a23024f0e550d9423f4d389672e1dfaf
Author: Justin Stitt <justinstitt@google.com>
Date:   Wed Aug 9 21:05:17 2023 +0000

    ipmi_si: fix -Wvoid-pointer-to-enum-cast warning

    With W=1 we see the following warning:

    |  drivers/char/ipmi/ipmi_si_platform.c:272:15: error: \
    |       cast to smaller integer type 'enum si_type' from \
    |       'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]
    |    272 |         io.si_type      = (enum si_type) match->data;
    |        |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~

    This is due to the fact that the `si_type` enum members are int-width
    and a cast from pointer-width down to int will cause truncation and
    possible data loss. Although in this case `si_type` has only a few
    enumerated fields and thus there is likely no data loss occurring.
    Nonetheless, this patch is necessary to the goal of promoting this
    warning out of W=1.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1902
    Link: https://lore.kernel.org/llvm/202308081000.tTL1ElTr-lkp@intel.com/
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Message-Id: <20230809-cbl-1902-v1-1-92def12d1dea@google.com>
    Signed-off-by: Corey Minyard <minyard@acm.org>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>