x86/alternative: Add a __alt_reloc_selftest() prototype
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 1a3e4b4da39bbf540a379e21869faa74bb19d16f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 3 10:26:17 2023 +0200

    x86/alternative: Add a __alt_reloc_selftest() prototype

    The newly introduced selftest function causes a warning when -Wmissing-prototypes
    is enabled:

      arch/x86/kernel/alternative.c:1461:32: error: no previous prototype for '__alt_reloc_selftest' [-Werror=missing-prototypes]

    Since it's only used locally, add the prototype directly in front of it.

    Fixes: 270a69c4485d ("x86/alternative: Support relocations in alternatives")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230803082619.1369127-6-arnd@kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>