iommu/amd: Fix compile warning in init code
Bugzilla: https://bugzilla.redhat.com/2117776
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit be280ea763f7db492e0e30ba22873433aea0f468
Author: Joerg Roedel <jroedel@suse.de>
Date:   Fri Jul 29 12:04:32 2022 +0200

    iommu/amd: Fix compile warning in init code

    A recent commit introduced these compile warnings:

      CC      drivers/iommu/amd/init.o
    drivers/iommu/amd/init.c:938:12: error: ‘iommu_init_ga_log’ defined but not used [-Werror=unused-function]
      938 | static int iommu_init_ga_log(struct amd_iommu *iommu)
	  |            ^~~~~~~~~~~~~~~~~
    drivers/iommu/amd/init.c:902:12: error: ‘iommu_ga_log_enable’ defined but not used [-Werror=unused-function]
      902 | static int iommu_ga_log_enable(struct amd_iommu *iommu)
	  |            ^~~~~~~~~~~~~~~~~~~

    The warnings appear because both functions are defined when IRQ
    remapping is not enabled, but only used when IRQ remapping is enabled.

    Fix it by only defining the functions when IRQ remapping is enabled.

    Fixes: c5e1a1eb9279 ("iommu/amd: Simplify and Consolidate Virtual APIC (AVIC) Enablement")
    Signed-off-by: Joerg Roedel <jroedel@suse.de>
    Link: https://lore.kernel.org/r/20220729100432.22474-1-joro@8bytes.org

(cherry picked from commit be280ea763f7db492e0e30ba22873433aea0f468)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>