perf kwork: Fix a build error on 32-bit
JIRA: https://issues.redhat.com/browse/RHEL-25824

upstream
========
commit a6dda77a752d918b35ef4a3f94e6b8c7d7ba4a73
Author: Yang Jihong <yangjihong1@huawei.com>
Date: Sat Nov 18 02:48:56 2023 +0000

description
===========
lkft reported a build error for 32-bit system:

    builtin-kwork.c: In function 'top_print_work':
    builtin-kwork.c:1646:28: error: format '%ld' expects argument of
  type 'long int', but argument 3 has type 'u64' {aka 'long long
  unsigned int'} [-Werror=format=]
     1646 |         ret += printf(" %*ld ", PRINT_PID_WIDTH, work->id);
          |                         ~~~^                     ~~~~~~~~
          |                            |                         |
          |                            long int                  u64
  {aka long long unsigned int}
          |                         %*lld
    cc1: all warnings being treated as errors
    make[3]: *** [/builds/linux/tools/build/Makefile.build:106:
  /home/tuxbuild/.cache/tuxmake/builds/1/build/builtin-kwork.o] Error 1

Fix it.

Fixes: 55c40e505234 ("perf kwork top: Introduce new top utility")
    Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
    Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
    Acked-by: Namhyung Kim <namhyung@kernel.org>
    Cc: avagin@google.com
    Cc: daniel.diaz@linaro.org
    Link: https://lore.kernel.org/r/20231118024858.1567039-2-yangjihong1@huawei.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>