i2c-designware: use div_u64 to fix link
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Vincent Stehlé <vincent.stehle@freescale.com>
commit 97191d734f6ac028e5e6dcd574378c1544a16c0b
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/97191d73.failed

This fixes the following link error:

  drivers/built-in.o: In function `dw_i2c_probe':
  of_iommu.c:(.text+0x18c8f0): undefined reference to `__aeabi_uldivmod'
  make: *** [vmlinux] Error 1

	Signed-off-by: Vincent Stehlé <vincent.stehle@freescale.com>
	Tested-by: Kevin Hilman <khilman@linaro.org>
	Reviewed-by: Christian Ruppert <christian.ruppert@abilis.com>
	Acked-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
(cherry picked from commit 97191d734f6ac028e5e6dcd574378c1544a16c0b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/i2c/busses/i2c-designware-platdrv.c