kvm: arm64: use BUG() instead of BUG_ON(1)
JIRA: https://issues.redhat.com/browse/RHEL-115972

commit 700d6868fee2d384cbd821d31db3a245d218223c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 7 09:21:28 2025 +0200

    kvm: arm64: use BUG() instead of BUG_ON(1)

    The BUG_ON() macro adds a little bit of complexity over BUG(), and in
    some cases this ends up confusing the compiler's control flow analysis
    in a way that results in a warning. This one now shows up with clang-21:

    arch/arm64/kvm/vgic/vgic-mmio.c:1094:3: error: variable 'len' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
     1094 |                 BUG_ON(1);

    Change both instances of BUG_ON(1) to a plain BUG() in the arm64 kvm
    code, to avoid the false-positive warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20250807072132.4170088-1-arnd@kernel.org
    Signed-off-by: Oliver Upton <oliver.upton@linux.dev>

Signed-off-by: Donald Dutile <ddutile@redhat.com>