selinux: declare path parameters of _genfs_sid const
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2083580

commit 08df49054f311ca04954cf24d1216d3b5ddfd0a6
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Tue Jan 25 15:14:12 2022 +0100

    selinux: declare path parameters of _genfs_sid const

    The path parameter is only read from in security_genfs_sid(),
    selinux_policy_genfs_sid() and __security_genfs_sid(). Since a string
    literal is passed as argument, declare the parameter const.
    Also align the parameter names in the declaration and definition.

    Reported by clang [-Wwrite-strings]:

        security/selinux/hooks.c:553:60: error: passing 'const char [2]'
          to parameter of type 'char *' discards qualifiers
          [-Wincompatible-pointer-types-discards-qualifiers]
                rc = security_genfs_sid(&selinux_state, ... , /,
                                                              ^~~
        ./security/selinux/include/security.h:389:36: note: passing
          argument to parameter 'name' here
                               const char *fstype, char *name, u16 sclass,
                                                         ^

    Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
    [PM: wrapped description]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>