regulator: rohm-generic: iniline stub function
Bugzilla: http://bugzilla.redhat.com/2071777

commit cff6f593251cdf5398dc3c57f7032b8e9dcb633e
Author: Matti Vaittinen <matti.vaittinen@fi.rohmeurope.com>
Date:   Tue Nov 23 12:36:47 2021 +0200

    regulator: rohm-generic: iniline stub function

    The function rohm_regulator_set_voltage_sel_restricted() has a stub
    implementation. Linux-next testing spot following:

    include/linux/mfd/rohm-generic.h:93:12: error:
    'rohm_regulator_set_voltage_sel_restricted' defined but not used

    Fix this by inlining the stub.

    Fixes: 8b6e88555971 ("regulator: rohm-regulator: add helper for restricted voltage setting")
    Signed-off-by: Matti Vaittinen <matti.vaittinen@fi.rohmeurope.com>
    Link: https://lore.kernel.org/r/YZzEP3S7U15bTDAI@fedora
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>