ASoC: SOF: core: fix undefined nocodec reference
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: SOF: core: fix undefined nocodec reference (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.12%
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit ce38a75089f70f6380fc63a5478a7659b4eb3f47

The existing code mistakenly uses IS_ENABLED in C code instead of as
in conditional compilation, leading to the following error:

ld: sound/soc/sof/core.o: in function `sof_machine_check':
sound/soc/sof/core.c:279: undefined reference to `sof_nocodec_setup'

Fix by using #if !IS_ENABLED()

	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ce38a75089f70f6380fc63a5478a7659b4eb3f47)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>