perf probe: Check the orphaned -x option
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Check the orphaned -x option (Jiri Olsa) [1222189]
Rebuild_FUZZ: 93.33%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 8cb0aa4c2db395b143cd5165586dc17677960002

To avoid probing in unintended binary, the orphaned -x option must be
checked and warned.

Without this patch, following command sets up the probe in the kernel.

  -----
  # perf probe -a strcpy -x ./perf
  Added new event:
    probe:strcpy         (on strcpy)

  You can now use it in all perf tools, such as:

          perf record -e probe:strcpy -aR sleep 1
  -----

But in this case, it seems that the user may want to probe in the perf
binary. With this patch, perf-probe correctly handles the orphaned -x.

  -----
  # perf probe -a strcpy -x ./perf
    Error: -x/-m must follow the probe definitions.
  ...
  -----

	Reported-by: Jiri Olsa <jolsa@redhat.com>
	Acked-by: Jiri Olsa <jolsa@redhat.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/20150401102541.17137.75477.stgit@localhost.localdomain
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 8cb0aa4c2db395b143cd5165586dc17677960002)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>