percpu: adjust the value of PERCPU_DYNAMIC_EARLY_SIZE
JIRA: https://issues.redhat.com/browse/RHEL-27743
Conflicts:
  * context difference due to out-of-order backport of upstream commit
    d667c94962c1 ("mm/percpu: remove unused PERCPU_DYNAMIC_EARLY_SLOTS")

This patch is a backport of the following upstream commit:
commit e8753e416c7ec39812cf92608aa95640caca70fa
Author: Baoquan He <bhe@redhat.com>
Date:   Sun Nov 13 18:08:27 2022 +0800

    percpu: adjust the value of PERCPU_DYNAMIC_EARLY_SIZE

    LKP reported a build failure as below on the following patch "mm/slub,
    percpu: correct the calculation of early percpu allocation size"

    ~~~~~~
    In file included from <command-line>:
    In function 'alloc_kmem_cache_cpus',
       inlined from 'kmem_cache_open' at mm/slub.c:4340:6:
    >> >> include/linux/compiler_types.h:357:45: error: call to '__compiletime_assert_474' declared with attribute error:
    BUILD_BUG_ON failed: PERCPU_DYNAMIC_EARLY_SIZE < NR_KMALLOC_TYPES * KMALLOC_SHIFT_HIGH * sizeof(struct kmem_cache_cpu)
         357 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
    ~~~~~~

    From the kernel config file provided by LKP, the building was made on
    arm64 with below Kconfig item enabled:

      CONFIG_ZONE_DMA=y
      CONFIG_SLUB_CPU_PARTIAL=y
      CONFIG_DEBUG_LOCK_ALLOC=y
      CONFIG_SLUB_STATS=y
      CONFIG_ARM64_PAGE_SHIFT=16
      CONFIG_ARM64_64K_PAGES=y

    Then we will have:
      NR_KMALLOC_TYPES:4
      KMALLOC_SHIFT_HIGH:17
      sizeof(struct kmem_cache_cpu):184

    The product of them is 12512, which is bigger than PERCPU_DYNAMIC_EARLY_SIZE,
    12K. Hence, the BUILD_BUG_ON in alloc_kmem_cache_cpus() is triggered.

    Earlier, in commit 099a19d91ca4 ("percpu: allow limited allocation
    before slab is online"), PERCPU_DYNAMIC_EARLY_SIZE was introduced and
    set to 12K which is equal to the then PERPCU_DYNAMIC_RESERVE.
    Later, in commit 1a4d76076cda ("percpu: implement asynchronous chunk
    population"), PERPCU_DYNAMIC_RESERVE was increased by 8K, while
    PERCPU_DYNAMIC_EARLY_SIZE was kept unchanged.

    So, here increase PERCPU_DYNAMIC_EARLY_SIZE by 8K too to accommodate to
    the slub's requirement.

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Baoquan He <bhe@redhat.com>
    Acked-by: Dennis Zhou <dennis@kernel.org>
    Signed-off-by: Vlastimil Babka <vbabka@suse.cz>

Signed-off-by: Rafael Aquini <raquini@redhat.com>