ata: ahci_brcm: Fix compilation warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2162218

When compiling with clang and W=1, the following warning is generated:

drivers/ata/ahci_brcm.c:451:18: error: cast to smaller integer type
'enum brcm_ahci_version' from 'const void *'
[-Werror,-Wvoid-pointer-to-enum-cast]
        priv->version = (enum brcm_ahci_version)of_id->data;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by using a cast to unsigned long to match the "void *" type
size of of_id->data.

Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Acked-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Florian Fainelli <f.fainelli@gmail.com>
(cherry picked from commit 7d7b0c85127cbac45e6c4e0ae0647ace17cadfaf)
Signed-off-by: Tomas Henzl <thenzl@redhat.com>