ASoC: codecs: SND_SOC_WCD934X should select REGMAP_IRQ
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit e231cd833f6463e9a1d54acae9614b513c74d45e
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date: Thu Jul 6 13:42:04 2023 +0200

    ASoC: codecs: SND_SOC_WCD934X should select REGMAP_IRQ

    If CONFIG_SND_SOC_WCD934X=y, CONFIG_COMPILE_TEST=y,
    CONFIG_MFD_WCD934X=n, CONFIG_REGMAP_IRQ=n:

        aarch64-linux-gnu-ld: sound/soc/codecs/wcd934x.o: in function `wcd934x_codec_probe':
        wcd934x.c:(.text+0x33cc): undefined reference to `regmap_irq_get_virq'
        aarch64-linux-gnu-ld: sound/soc/codecs/wcd934x.o: in function `wcd934x_comp_probe':
        wcd934x.c:(.text+0x4cb0): undefined reference to `regmap_irq_get_virq'
        aarch64-linux-gnu-ld: wcd934x.c:(.text+0x4cc0): undefined reference to `regmap_irq_get_virq'
        aarch64-linux-gnu-ld: wcd934x.c:(.text+0x4cd0): undefined reference to `regmap_irq_get_virq'
        aarch64-linux-gnu-ld: wcd934x.c:(.text+0x4ce0): undefined reference to `regmap_irq_get_virq'
        aarch64-linux-gnu-ld: sound/soc/codecs/wcd934x.o:wcd934x.c:(.text+0x4cf0): more undefined references to `regmap_irq_get_virq' follow

    Fix this by making SND_SOC_WCD934X select REGMAP_IRQ.

    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Link: https://lore.kernel.org/r/cafd878747e7951914a7d9fea33788a4a230d1f0.1688643442.git.geert@linux-m68k.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>