selftests/bpf: Fix broken build where char is unsigned
JIRA: https://issues.redhat.com/browse/RHEL-31944

Upstream commit(s):
commit d84b139f53e8fa8048f16814c6b2a53d7bc15c3d
Author: Björn Töpel <bjorn@rivosinc.com>
Date:   Thu Nov 2 11:35:37 2023 +0100

    selftests/bpf: Fix broken build where char is unsigned

    There are architectures where char is not signed. If so, the following
    error is triggered:

      | xdp_hw_metadata.c:435:42: error: result of comparison of constant -1 \
      |   with expression of type 'char' is always true \
      |   [-Werror,-Wtautological-constant-out-of-range-compare]
      |   435 |         while ((opt = getopt(argc, argv, "mh")) != -1) {
      |       |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
      | 1 error generated.

    Correct by changing the char to int.

    Fixes: bb6a88885fde ("selftests/bpf: Add options and frags to xdp_hw_metadata")
    Signed-off-by: Björn Töpel <bjorn@rivosinc.com>
    Acked-by: Larysa Zaremba <larysa.zaremba@intel.com>
    Tested-by: Anders Roxell <anders.roxell@linaro.org>
    Link: https://lore.kernel.org/r/20231102103537.247336-1-bjorn@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>