perf callchains: Fix unw_word_t pointer casts
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Rabin Vincent <rabin.vincent@axis.com>
commit 186c6cfb32beae66140bc3c3fe4a519ee0234e33

unw_word_t is uint64_t even on 32-bit MIPS.  Cast it to uintptr_t before
the cast to void *p to get rid of the following errors:

  util/unwind-libunwind.c: In function 'access_mem':
  util/unwind-libunwind.c:464:4: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  util/unwind-libunwind.c:475:2: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  cc1: all warnings being treated as errors
  make[3]: *** [util/unwind-libunwind.o] Error 1

	Signed-off-by: Rabin Vincent <rabin.vincent@axis.com>
	Acked-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Rabin Vincent <rabinv@axis.com>
Link: http://lkml.kernel.org/r/1443379079-29133-1-git-send-email-rabin.vincent@axis.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 186c6cfb32beae66140bc3c3fe4a519ee0234e33)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>