ALSA: hda/cs35l41_hda: select FW_CS_DSP
JIRA: https://issues.redhat.com/browse/RHEL-112757

commit 9110fadda376ee1377a478dbae5e168243b081f3
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue May 20 18:20:48 2025 +0200

    ALSA: hda/cs35l41_hda: select FW_CS_DSP

    When compile-testing this driver, the missing FW_CS_DSP module
    causes a link failure:

    aarch64-linux-ld: sound/pci/hda/cs35l41_hda.o: in function `cs35l41_shutdown_dsp':
    cs35l41_hda.c:(.text+0x7e4): undefined reference to `cs_dsp_stop'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x7ec): undefined reference to `cs_dsp_power_down'
    aarch64-linux-ld: sound/pci/hda/cs35l41_hda.o: in function `cs35l41_hda_remove':
    cs35l41_hda.c:(.text+0x14b4): undefined reference to `cs_dsp_remove'
    aarch64-linux-ld: sound/pci/hda/cs35l41_hda.o: in function `cs35l41_smart_amp.isra.0':
    cs35l41_hda.c:(.text+0x189c): undefined reference to `cs_dsp_halo_init'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1bd4): undefined reference to `cs_dsp_power_up'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1c38): undefined reference to `cs_dsp_run'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1c80): undefined reference to `cs_dsp_get_ctl'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1c90): undefined reference to `cs_dsp_coeff_read_ctrl'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1cd4): undefined reference to `cs_dsp_get_ctl'
    aarch64-linux-ld: cs35l41_hda.c:(.text+0x1ce4): undefined reference to `cs_dsp_coeff_read_ctrl'

    Fixes: bdd9ea9187c4 ("ALSA: hda/hda_cs_dsp_ctl: Delete hda_cs_dsp_ctl module")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Link: https://patch.msgid.link/20250520162101.3929551-1-arnd@kernel.org

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>