net/sched: cls_api: Add extack message for unsupported action offload
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit c440615ffbcb9c06975103e5abbcb094589329d1
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:31 2022 +0300

    net/sched: cls_api: Add extack message for unsupported action offload

    For better error reporting to user space, add an extack message when the
    requested action does not support offload.

    Example:

     # echo 1 > /sys/kernel/tracing/events/netlink/netlink_extack/enable

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action nat ingress 192.0.2.1 198.51.100.1
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-181     [000] b..1.    88.406093: netlink_extack: msg=Action does not support offload
           tc-181     [000] .....    88.406108: netlink_extack: msg=cls_matchall: Failed to setup flow action

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>