powerpc/pseries: Fix build break when MEMORY_HOTREMOVE=n
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [powerpc] pseries: Fix build break when MEMORY_HOTREMOVE=n (Thomas Huth) [1323417]
Rebuild_FUZZ: 92.31%
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit f84775c2d5d92581f2df60d53b574b0405c85be3

We broke the build when CONFIG_MEMORY_HOTREMOVE=n:

  arch/powerpc/platforms/pseries/hotplug-memory.c:821:8: error: implicit
  declaration of function 'dlpar_memory_readd_by_index'

Add a dummy to fix it.

Fixes: e70d59700fc3 ("powerpc/pseries: Introduce memory hotplug READD operation")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit f84775c2d5d92581f2df60d53b574b0405c85be3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>