PCI: dwc: Expose dw_pcie_write_dbi2() to module
JIRA: https://issues.redhat.com/browse/RHEL-26162
Upstream Status: 303e845351f5d2b4ff349bb3e59aba2b554d8229

commit 303e845351f5d2b4ff349bb3e59aba2b554d8229
Author: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Date:   Tue Sep 26 21:24:22 2023 +0900

    PCI: dwc: Expose dw_pcie_write_dbi2() to module

    Since no PCIe controller drivers call this, this change is not required
    for now. But, Renesas R-Car Gen4 PCIe controller driver will call this
    and if the controller driver is built as a kernel module, the following
    build error happens:

      ERROR: modpost: "dw_pcie_write_dbi2" [drivers/pci/controller/dwc/pcie-rcar-gen4-host-drv.ko] undefined!

    So, expose dw_pcie_write_dbi2() for it.

    Link: https://lore.kernel.org/linux-pci/20230926122431.3974714-8-yoshihiro.shimoda.uh@renesas.com
    Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@kernel.org>
    Reviewed-by: Serge Semin <fancer.lancer@gmail.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>