scsi: lpfc: Fix compiler warning on frame size
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author James Smart <jsmart2021@gmail.com>
commit a99c80742af4b58bfd2d16cada8ee73cb9618649

The following error is see from the compiler:

  drivers/scsi/lpfc/lpfc_init.c: In function
    ‘lpfc_cpuhp_get_eq’: drivers/scsi/lpfc/lpfc_init.c:12660:1:
      error: the frame size of 1032 bytes is larger than 1024 bytes
         [-Werror=frame-larger-than=]

The issue is due to allocating a cpumask on the stack.

Fix by converting to a dynamical allocation of the cpu mask.

Link: https://lore.kernel.org/r/20200128002312.16346-7-jsmart2021@gmail.com
	Signed-off-by: Dick Kennedy <dick.kennedy@broadcom.com>
	Signed-off-by: James Smart <jsmart2021@gmail.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit a99c80742af4b58bfd2d16cada8ee73cb9618649)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>