tools: ynl: fix build of the page-pool sample
JIRA: https://issues.redhat.com/browse/RHEL-31941

Upstream commit(s):
commit ee1eb9de81dbdbf078df659062e4df256a009627
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Wed Nov 29 11:36:19 2023 -0800

    tools: ynl: fix build of the page-pool sample

    The name of the "destroyed" field in the reply was not changed
    in the sample after we started calling it "detach_time".

    page-pool.c: In function ‘main’:
    page-pool.c:84:33: error: ‘struct <anonymous>’ has no member named ‘destroyed’
       84 |                 if (pp->_present.destroyed)
          |                                 ^

    Fixes: 637567e4a3ef ("tools: ynl: add sample for getting page-pool information")
    Link: https://lore.kernel.org/r/20231129193622.2912353-2-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>