ASoC: amd: vangogh: select CONFIG_SND_AMD_ACP_CONFIG
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-536.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 812a05256d673b2b9c5db906775d1e6625ba4787

The vangogh driver just gained a link time dependency that now causes
randconfig builds to fail:

x86_64-linux-ld: sound/soc/amd/vangogh/pci-acp5x.o: in function `snd_acp5x_probe':
pci-acp5x.c:(.text+0xbb): undefined reference to `snd_amd_acp_find_config'

Fixes: e89f45edb747e ("ASoC: amd: vangogh: Add check for acp config flags in vangogh platform")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20230602124447.863476-1-arnd@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 812a05256d673b2b9c5db906775d1e6625ba4787)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>