x86: Move gds_ucode_mitigated() declaration to header
jira LE-1907
cve CVE-2023-20569
Rebuild_History Non-Buildable kernel-4.18.0-521.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit eb3515dc99c7c85f4170b50838136b2a193f8012

The declaration got placed in the .c file of the caller, but that
causes a warning for the definition:

arch/x86/kernel/cpu/bugs.c:682:6: error: no previous prototype for 'gds_ucode_mitigated' [-Werror=missing-prototypes]

Move it to a header where both sides can observe it instead.

Fixes: 81ac7e5d74174 ("KVM: Add GDS_NO support to KVM")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
	Tested-by: Daniel Sneddon <daniel.sneddon@linux.intel.com>
	Cc: stable@kernel.org
Link: https://lore.kernel.org/all/20230809130530.1913368-2-arnd%40kernel.org
(cherry picked from commit eb3515dc99c7c85f4170b50838136b2a193f8012)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>