arm64: add alt_cb_patch_nops prototype
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit c152aed4dcc21e6d496e700148fdd85c2b0ff09c
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:42 +0200

    alt_cb_patch_nops() is called through an inline asm macro, so
    it does not need a prototype for the caller, but adding it
    avoids this W=1 build warning:

    arch/arm64/kernel/alternative.c:295:14: error: no previous prototype for 'alt_cb_patch_nops' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-16-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>