usb: misc: onboard_usb_dev: introduce new config symbol for usb5744 SMBus support
JIRA: https://issues.redhat.com/browse/RHEL-59052

commit 6c4e1ef46c9d565c71e9ff1a70ddbe24790694d5
Author: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
Date: Sat, 28 Sep 2024 18:56:32 +0530

  Introduce new kernel config symbol for Microchip usb5744 SMBus programming
  support. Since usb5744 i2c initialization routine uses i2c SMBus APIs these
  APIs should only be invoked when kernel has I2C support. This new kernel
  config describes the dependency on I2C kernel support and fix the below
  build issues when USB_ONBOARD_DEV=y and CONFIG_I2C=m.

  riscv64-linux-ld: drivers/usb/misc/onboard_usb_dev.o:
  undefined reference to `i2c_find_device_by_fwnode'
  drivers/usb/misc/onboard_usb_dev.c:408:(.text+0xb24): undefined
  reference to `i2c_smbus_write_block_data'
  <snip>

  Parsing of the i2c-bus bus handle is not put under usb5744 kernel config
  check as the intention is to report an error when DT is configured for
  usb5744 SMBus support and kernel has USB_ONBOARD_DEV_USB5744 disabled.

  Fixes: 6782311d04df ("usb: misc: onboard_usb_dev: add Microchip usb5744 SMBus programming support")
  Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
  Suggested-by: Matthias Kaehlcke <matthias@kaehlcke.net>
  Reported-by: kernel test robot <lkp@intel.com>
  Closes: https://lore.kernel.org/oe-kbuild-all/202409140539.3Axwv38m-lkp@intel.com/
  Acked-by: Matthias Kaehlcke <matthias@kaehlcke.net>
  Link: https://lore.kernel.org/r/1727529992-476088-1-git-send-email-radhey.shyam.pandey@amd.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>