dmaengine: tegra: explicitly select DMA_VIRTUAL_CHANNELS
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181001

commit 7511f28792c6c724cc584a42f3eeb2fa5af689c4
Author: Mark Salter <msalter@redhat.com>
Date: Wed, 29 Mar 2023 13:21:29 -0400

    Enabling TEGRA186_GPC_DMA will cause this build failure unless some other
    DMA driver which uses DMA_VIRTUAL_CHANNELS is enabled:

      ERROR: modpost: "vchan_dma_desc_free_list" [drivers/dma/tegra186-gpc-dma.ko] undefined!
      ERROR: modpost: "vchan_init" [drivers/dma/tegra186-gpc-dma.ko] undefined!
      ERROR: modpost: "vchan_tx_submit" [drivers/dma/tegra186-gpc-dma.ko] undefined!
      ERROR: modpost: "vchan_tx_desc_free" [drivers/dma/tegra186-gpc-dma.ko] undefined!
      ERROR: modpost: "vchan_find_desc" [drivers/dma/tegra186-gpc-dma.ko] undefined!
      make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1

    Add an explicit select of DMA_VIRTUAL_CHANNELS to avoid this.

    Signed-off-by: Mark Salter <msalter@redhat.com>
    Link: https://lore.kernel.org/r/20230329172129.88403-1-msalter@redhat.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>