nfsd: define exports_proc_ops with CONFIG_PROC_FS
JIRA: https://issues.redhat.com/browse/RHEL-7936

commit 340086da9a87820b40601141a0e9e87c954ac006
Author: Tom Rix <trix@redhat.com>
Date:   Tue May 2 13:11:21 2023 -0400

    nfsd: define exports_proc_ops with CONFIG_PROC_FS

    gcc with W=1 and ! CONFIG_PROC_FS
    fs/nfsd/nfsctl.c:161:30: error: ‘exports_proc_ops’
      defined but not used [-Werror=unused-const-variable=]
      161 | static const struct proc_ops exports_proc_ops = {
          |                              ^~~~~~~~~~~~~~~~

    The only use of exports_proc_ops is when CONFIG_PROC_FS
    is defined, so its definition should be likewise conditional.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Jeffrey Layton <jlayton@redhat.com>