x86: Move gds_ucode_mitigated() declaration to header
JIRA: https://issues.redhat.com/browse/RHEL-8594
CVE: CVE-2023-20569

commit eb3515dc99c7c85f4170b50838136b2a193f8012
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed, 9 Aug 2023 15:05:00 +0200

    x86: Move gds_ucode_mitigated() declaration to header

    The declaration got placed in the .c file of the caller, but that
    causes a warning for the definition:

    arch/x86/kernel/cpu/bugs.c:682:6: error: no previous prototype for 'gds_ucode_mitigated' [-Werror=missing-prototypes]

    Move it to a header where both sides can observe it instead.

    Fixes: 81ac7e5d74174 ("KVM: Add GDS_NO support to KVM")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Tested-by: Daniel Sneddon <daniel.sneddon@linux.intel.com>
    Cc: stable@kernel.org
    Link: https://lore.kernel.org/all/20230809130530.1913368-2-arnd%40kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>