bpftool: Fix regression of "bpftool cgroup tree" EINVAL on older kernels
JIRA: https://issues.redhat.com/browse/RHEL-110274

commit 43745d11bfd9683abdf08ad7a5cc403d6a9ffd15
Author: YiFei Zhu <zhuyifei@google.com>
Date:   Mon Apr 28 21:15:36 2025 +0000

    bpftool: Fix regression of "bpftool cgroup tree" EINVAL on older kernels
    
    If cgroup_has_attached_progs queries an attach type not supported
    by the running kernel, due to the kernel being older than the bpftool
    build, it would encounter an -EINVAL from BPF_PROG_QUERY syscall.
    
    Prior to commit 98b303c9bf05 ("bpftool: Query only cgroup-related
    attach types"), this EINVAL would be ignored by the function, allowing
    the function to only consider supported attach types. The commit
    changed so that, instead of querying all attach types, only attach
    types from the array `cgroup_attach_types` is queried. The assumption
    is that because these are only cgroup attach types, they should all
    be supported. Unfortunately this assumption may be false when the
    kernel is older than the bpftool build, where the attach types queried
    by bpftool is not yet implemented in the kernel. This would result in
    errors such as:
    
      $ bpftool cgroup tree
      CgroupPath
      ID       AttachType      AttachFlags     Name
      Error: can't query bpf programs attached to /sys/fs/cgroup: Invalid argument
    
    This patch restores the logic of ignoring EINVAL from prior to that patch.
    
    Fixes: 98b303c9bf05 ("bpftool: Query only cgroup-related attach types")
    Reported-by: Sagarika Sharma <sharmasagarika@google.com>
    Reported-by: Minh-Anh Nguyen <minhanhdn@google.com>
    Signed-off-by: YiFei Zhu <zhuyifei@google.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Quentin Monnet <qmo@kernel.org>
    Link: https://lore.kernel.org/bpf/20250428211536.1651456-1-zhuyifei@google.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>