include/linux/pgtable.h: convert arch_enter_lazy_mmu_mode() and friends to static inlines
JIRA: https://redhat.atlassian.net/browse/RHEL-145696

commit 7e89979f6695fb56e8739b7d19614256e637131d
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Sat Sep 13 17:03:39 2025 -0700

    include/linux/pgtable.h: convert arch_enter_lazy_mmu_mode() and friends to static inlines

    commit c519c3c0a113 ("mm/kasan: avoid lazy MMU mode hazards") introduced
    the use of arch_enter_lazy_mmu_mode(), which results in the compiler
    complaining about "statement has no effect", when
    __HAVE_ARCH_LAZY_MMU_MODE is not defined in include/linux/pgtable.h

    The exact warning/error is:

    In file included from ./include/linux/kasan.h:37,
                     from mm/kasan/shadow.c:14:
    mm/kasan/shadow.c: In function kasan_populate_vmalloc_pte:
    ./include/linux/pgtable.h:247:41: error: statement with no effect [-Werror=unused-value]
      247 | #define arch_enter_lazy_mmu_mode()      (LAZY_MMU_DEFAULT)
          |                                         ^
    mm/kasan/shadow.c:322:9: note: in expansion of macro arch_enter_lazy_mmu_mode>   322 |         arch_enter_lazy_mmu_mode();
         |         ^~~~~~~~~~~~~~~~~~~~~~~~

    switching these "functions" to static inlines fixes this up.

    Fixes: c519c3c0a113 ("mm/kasan: avoid lazy MMU mode hazards")
    Reported-by: Balbir Singh <balbirs@nvidia.com>
    Closes: https://lkml.kernel.org/r/20250912235515.367061-1-balbirs@nvidia.com
    Cc: Alexander Gordeev <agordeev@linux.ibm.com>
    Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>