s390/mm: Fix ERROR: "__node_distance" undefined!
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Justin M. Forbes <jforbes@fedoraproject.org>
commit a541f0ebcc08ed8bc0cc492eec9a86cb280a9f24

Fixes:
ERROR: "__node_distance" [drivers/nvme/host/nvme-core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1
make: *** [Makefile:1275: modules] Error 2
+ exit 1

	Signed-off-by: Justin M. Forbes <jforbes@fedoraproject.org>
	Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
	Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
(cherry picked from commit a541f0ebcc08ed8bc0cc492eec9a86cb280a9f24)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>