qede: Fix net-next "make ARCH=x86_64"
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Manish Chopra <manish.chopra@qlogic.com>
commit 88f09bd5b9875a0fbf2075221590d9c4418cdbbc

'commit 55482edc25f0606851de42e73618f813f310d009
("qede: Add slowpath/fastpath support and enable hardware GRO")'
introduces below error when compiling net-next with "make ARCH=x86_64"

drivers/built-in.o: In function `qede_rx_int':
qede_main.c:(.text+0x6101a0): undefined reference to `tcp_gro_complete'

	Signed-off-by: Manish Chopra <manish.chopra@qlogic.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 88f09bd5b9875a0fbf2075221590d9c4418cdbbc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>