cpufreq: amd-pstate: remove global header file
JIRA: https://issues.redhat.com/browse/RHEL-34751

commit 779b8a14afde110dd3502566be907289eba72447
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 28 14:09:23 2024 +0200

    cpufreq: amd-pstate: remove global header file

    When extra warnings are enabled, gcc points out a global variable
    definition in a header:

    In file included from drivers/cpufreq/amd-pstate-ut.c:29:
    include/linux/amd-pstate.h:123:27: error: 'amd_pstate_mode_string' defined but not used [-Werror=unused-const-variable=]
      123 | static const char * const amd_pstate_mode_string[] = {
          |                           ^~~~~~~~~~~~~~~~~~~~~~

    This header is only included from two files in the same directory,
    and one of them uses only a single definition from it, so clean it
    up by moving most of the contents into the driver that uses them,
    and making shared bits a local header file.

    Fixes: 36c5014e5460 ("cpufreq: amd-pstate: optimize driver working mode selection in amd_pstate_param()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Mario Limonciello <mario.limonciello@amd.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>