spi: amd: Fix -Wuninitialized in amd_spi_exec_mem_op()
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit e896c04890aeff2292364c19632fc15d890d436c
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Sat Jan 11 12:08:38 2025 -0700

    spi: amd: Fix -Wuninitialized in amd_spi_exec_mem_op()

    After commit e6204f39fe3a ("spi: amd: Drop redundant check"), clang warns (or
    errors with CONFIG_WERROR=y):

      drivers/spi/spi-amd.c:695:9: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
        695 |         return ret;
            |                ^~~
      drivers/spi/spi-amd.c:673:9: note: initialize the variable 'ret' to silence this warning
        673 |         int ret;
            |                ^
            |                 = 0
      1 error generated.

    ret is no longer set on anything other than the default switch path.
    Replace ret with a direct return of 0 at the end of the function and
    -EOPNOTSUPP in the default case to resolve the warning.

    Fixes: e6204f39fe3a ("spi: amd: Drop redundant check")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202501112315.ugYQ7Ce7-lkp@intel.com/
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Miguel Ojeda <ojeda@kernel.org>
    Reviewed-by: Miquel Raynal <miquel.raynal@bootlin.com>
    Link: https://patch.msgid.link/20250111-spi-amd-fix-uninitialized-ret-v1-1-c66ab9f6a23d@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>