scsi: ufs: ufs-mediatek: Fix build warnings
Bugzilla: https://bugzilla.redhat.com/2185234

commit e7bf1d50063ce0dcae84ddbd27531a3ecec59e28
Author: Stanley Chu <stanley.chu@mediatek.com>
Date:   Thu Jun 23 11:50:45 2022 +0800

    scsi: ufs: ufs-mediatek: Fix build warnings

    Fix build warnings:

    1.
    ../drivers/ufs/host/ufs-mediatek.c:1375:5: error: no previous prototype for function 'ufs_mtk_system_suspend' [-Werror,-Wmissing-prototypes]
    int ufs_mtk_system_suspend(struct device *dev)
        ^
    ../drivers/ufs/host/ufs-mediatek.c:1375:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
    int ufs_mtk_system_suspend(struct device *dev)
    ^
    static

    2.
    ../drivers/ufs/host/ufs-mediatek.c:702:50: error: format specifies type 'unsigned long' but the argument has type 'int' [-Werror,-Wformat]
                    snprintf(vcc_name, MAX_VCC_NAME, "vcc-ufs%lu", ver);
                                                             ~~~   ^~~
                                                             %d

    Link: https://lore.kernel.org/r/20220623035052.18802-2-stanley.chu@mediatek.com
    Reviewed-by: Bart Van Assche <bvanassche@acm.org>
    Signed-off-by: Stanley Chu <stanley.chu@mediatek.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>