net: ethernet: ti: am65-cpsw: fix CONFIG_PM #ifdef
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit 078838f5b9c9203e94d7724f997392ea8012ea6a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:39:05 2022 +0100

    net: ethernet: ti: am65-cpsw: fix CONFIG_PM #ifdef

    The #ifdef check is incorrect and leads to a warning:

    drivers/net/ethernet/ti/am65-cpsw-nuss.c:1679:13: error: 'am65_cpsw_nuss_remove_rx_chns' defined but not used [-Werror=unused-function]
     1679 | static void am65_cpsw_nuss_remove_rx_chns(void *data)

    It's better to remove the #ifdef here and use the modern
    SYSTEM_SLEEP_PM_OPS() macro instead.

    Fixes: 24bc19b05f1f ("net: ethernet: ti: am65-cpsw: Add suspend/resume support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Alexander Duyck <alexanderduyck@fb.com>
    Link: https://lore.kernel.org/r/20221215163918.611609-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>