ASoC: max98388: fix unused function warnings
JIRA: https://issues.redhat.com/browse/RHEL-13724

Omitted-fix: 041c5a1d065e5882299475326655f573e2a2a580
             ASoC: loongson: fix unused PM function warning
             loongson platform is not supported in RHEL
Omitted-fix: 08432e59c7d9a958e69cf6b7a03777ba4f26f10b
             ASoC: loongson: add PCI dependency
             loongson platform is not supported in RHEL
Omitted-fix: 928314eb06709e3861ce3e2c7e9ef3f83ba8691b
             ASoC: loongson: fix compile testing on 32-bit
             loongson platform is not supported in RHEL

commit 0c340ba05fda0fbf5a54207452728911c6388330
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Jun 16 11:00:37 2023 +0200

    ASoC: max98388: fix unused function warnings

    The PM functions are never referenced when CONFIG_PM_SLEEP is
    disabled:

    sound/soc/codecs/max98388.c:854:12: error: unused function 'max98388_suspend' [-Werror,-Wunused-function]
    static int max98388_suspend(struct device *dev)
               ^
    sound/soc/codecs/max98388.c:864:12: error: unused function 'max98388_resume' [-Werror,-Wunused-function]
    static int max98388_resume(struct device *dev)

    Fix this by using the modern SYSTEM_SLEEP_PM_OPS() macro in place of
    the deprecated SET_SYSTEM_SLEEP_PM_OPS() version, and use pm_sleep_ptr()
    to hide the entire structure as well.

    On a related note, the of_match_ptr() and ACPI_PTR() macros have the same
    problem and would cause the device id table to be unused when the driver
    is built-in and the respective subsystems are disabled. This does not
    cause warnings unless -Wunused-const-variable is passed to the compiler,
    but it's better to just not use the macros at all here.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230616090156.2347850-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>