mm/damon: move the implementation of damon_insert_region to damon.h
Bugzilla: https://bugzilla.redhat.com/2004230

commit 2cd4b8e10cc31eadb5b10b1d73b3f28156f3776c
Author: Guoqing Jiang <guoqing.jiang@linux.dev>
Date:   Fri Jan 14 14:10:38 2022 -0800

    mm/damon: move the implementation of damon_insert_region to damon.h

    Usually, inline function is declared static since it should sit between
    storage and type.  And implement it in a header file if used by multiple
    files.

    And this change also fixes compile issue when backport damon to 5.10.

      mm/damon/vaddr.c: In function `damon_va_evenly_split_region':
      ./include/linux/damon.h:425:13: error: inlining failed in call to `always_inline' `damon_insert_region': function body not available
      425 | inline void damon_insert_region(struct damon_region *r,
          | ^~~~~~~~~~~~~~~~~~~
      mm/damon/vaddr.c:86:3: note: called from here
      86 | damon_insert_region(n, r, next, t);
         | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Link: https://lkml.kernel.org/r/20211223085703.6142-1-guoqing.jiang@linux.dev
    Signed-off-by: Guoqing Jiang <guoqing.jiang@linux.dev>
    Reviewed-by: SeongJae Park <sj@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>