wifi: ath11k: ath11k_debugfs_register(): fix format-truncation warning
JIRA: https://issues.redhat.com/browse/RHEL-19746

commit a47111663491ff2829df0626493ce81b48dd880a
Author: Kalle Valo <quic_kvalo@quicinc.com>
Date:   Tue Oct 10 09:22:50 2023 +0300

    wifi: ath11k: ath11k_debugfs_register(): fix format-truncation warning
    
    In v6.6-rc4 with GCC 13.2 I see a new warning:
    
    drivers/net/wireless/ath/ath11k/debugfs.c: In function 'ath11k_debugfs_register':
    drivers/net/wireless/ath/ath11k/debugfs.c:1597:51: error: '%d' directive output may be truncated writing between 1 and 3 bytes into a region of size 2 [-Werror=format-truncation=]
    drivers/net/wireless/ath/ath11k/debugfs.c:1597:48: note: directive argument in the range [0, 255]
    drivers/net/wireless/ath/ath11k/debugfs.c:1597:9: note: 'snprintf' output between 5 and 7 bytes into a destination of size 5
    
    Increase the size of pdev_name to 10 bytes to make sure there's enough room for
    the string. Also change the format to '%u' as ar->pdev_idx is u8.
    
    Compile tested only.
    
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20231010062250.2580951-1-kvalo@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>