firmware: arm_scmi: Disable ftrace for Clang Thumb2 builds
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071830
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2071840
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  At this stage, this
 has been tested by ensuring we can survive the CI/CD loop -- i.e.,
 that we have not broken anything else, and a simple boot test.  When
 sufficient drivers have been brought in for i.MX8M, we will be able
 to run further tests.

commit cdf157faaafe36c0823148587a78147200898e87
Author: Ard Biesheuvel <ardb@kernel.org>
Date:   Thu Feb 3 09:22:01 2022 +0100

    firmware: arm_scmi: Disable ftrace for Clang Thumb2 builds

    The SMC calling convention designates R0-R7 as input registers in
    AArch32 mode, and this conflicts with the compiler's use of R7 as a
    frame pointer when building in Thumb2 mode. Generally, we don't enable
    the frame pointer, and GCC happily enables the -pg profiling hooks
    without them. However, Clang refuses, and errors out with the message
    below:

    drivers/firmware/arm_scmi/smc.c:152:2: error: write to reserved register 'R7'
            arm_smccc_1_1_invoke(scmi_info->func_id, 0, 0, 0, 0, 0, 0, 0, &res);
            ^
    include/linux/arm-smccc.h:550:4: note: expanded from macro 'arm_smccc_1_1_invoke'
                            arm_smccc_1_1_smc(__VA_ARGS__);                 \
                            ^
    Let's just disable ftrace for the compilation unit when building this
    configuration.

    Link: https://lore.kernel.org/r/20220203082204.1176734-11-ardb@kernel.org
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
    (cherry picked from commit cdf157faaafe36c0823148587a78147200898e87)

Signed-off-by: Al Stone <ahs3@redhat.com>