drm/vmwgfx: remove unused vmw_overlay function
jira LE-1907
cve CVE-2023-5633
Rebuild_History Non-Buildable kernel-4.18.0-529.el8
commit-author Tom Rix <trix@redhat.com>
commit fd35174e13f98f9232c4aa66689816731d34ca28

clang with W=1 reports
drivers/gpu/drm/vmwgfx/vmwgfx_overlay.c:56:35: error:
  unused function 'vmw_overlay' [-Werror,-Wunused-function]
static inline struct vmw_overlay *vmw_overlay(struct drm_device *dev)
                                  ^
This function is not used, so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: Zack Rusin <zackr@vmware.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20230321182414.1826372-1-trix@redhat.com
(cherry picked from commit fd35174e13f98f9232c4aa66689816731d34ca28)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>