tracing: Annotate ftrace_graph_notrace_hash pointer with __rcu
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Amol Grover <frextrite@gmail.com>
commit fd0e6852c407dd9aefc594f54ddcc21d84803d3b

Fix following instances of sparse error
kernel/trace/ftrace.c:5667:29: error: incompatible types in comparison
kernel/trace/ftrace.c:5813:21: error: incompatible types in comparison
kernel/trace/ftrace.c:5868:36: error: incompatible types in comparison
kernel/trace/ftrace.c:5870:25: error: incompatible types in comparison

Use rcu_dereference_protected to dereference the newly annotated pointer.

Link: http://lkml.kernel.org/r/20200205055701.30195-1-frextrite@gmail.com

	Signed-off-by: Amol Grover <frextrite@gmail.com>
	Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
(cherry picked from commit fd0e6852c407dd9aefc594f54ddcc21d84803d3b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>