ASoC: intel: initialize return value properly
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: initialize return value properly (Jaroslav Kysela) [1535427]
Rebuild_FUZZ: 93.75%
commit-author Arnd Bergmann <arnd@arndb.de>
commit cc20c4df1627dd515ea90dd20e2684a8a1c76693

When CONFIG_SND_SOC_HDAC_HDMI is disabled, we can run into an
uninitialized variable:

sound/soc/intel/skylake/skl.c: In function 'skl_resume':
sound/soc/intel/skylake/skl.c:326:6: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

I have run into this on today's linux-next kernel, but it appears
that this is an older problem that was just hard to trigger
with randconfig builds as CONFIG_SND_SOC_HDAC_HDMI would in
effect be impossible to disable when having SND_SOC_INTEL_SKYLAKE
enabled.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-By: Vinod Koul <vinod.koul@intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit cc20c4df1627dd515ea90dd20e2684a8a1c76693)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>