selftests: timestamping: Fix SIOCGSTAMP undeclared build failure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Shuah Khan <skhan@linuxfoundation.org>
commit 877d53c295498c16a1977e591b7fc2838f8d8daf

Add missing linux/sockios.h include to fix the following SIOCGSTAMP
undeclared build error. In addition, remove the local defines for
SIOCGSTAMPNS and SIOCSHWTSTAMP and pick them up from linux/sockios.h.

timestamping.c:249:19: error: SIOCGSTAMP undeclared
   if (ioctl(sock, SIOCGSTAMP, &tv))

	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit 877d53c295498c16a1977e591b7fc2838f8d8daf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>