scsi: cxgb4i: silence overflow warning in t4_uld_rx_handler()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [scsi] cxgb4i: silence overflow warning in t4_uld_rx_handler() (Arjun Vynipadath) [1523190]
Rebuild_FUZZ: 94.83%
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit ccc495efb326d17be3e7790b5aa49b25e239ead7

Smatch marks skb->data as untrusted so it complains that there is a
potential overflow here:

	drivers/scsi/cxgbi/cxgb4i/cxgb4i.c:2111 t4_uld_rx_handler()
	error: buffer overflow 'cxgb4i_cplhandlers' 239 <= 255.

In this case, skb->data comes from the hardware or firmware so it's not
going to overflow unless there is a firmware bug.

[mkp: fixed braces]

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit ccc495efb326d17be3e7790b5aa49b25e239ead7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>