ASoC: Intel: sof-nau8825: fix module alias overflow
Bugzilla: https://bugzilla.redhat.com/2179848

commit 3e78986a840d59dd27e636eae3f52dc11125c835
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Dec 21 14:24:56 2022 +0100

    ASoC: Intel: sof-nau8825: fix module alias overflow

    The maximum name length for a platform_device_id entry is 20 characters
    including the trailing NUL byte. The sof_nau8825.c file exceeds that,
    which causes an obscure error message:

    sound/soc/intel/boards/snd-soc-sof_nau8825.mod.c:35:45: error: illegal character encoding in string literal [-Werror,-Winvalid-source-encoding]
    MODULE_ALIAS("platform:adl_max98373_nau8825<U+0018><AA>");
                                                       ^~~~
    include/linux/module.h:168:49: note: expanded from macro 'MODULE_ALIAS'
                                                    ^~~~~~
    include/linux/module.h:165:56: note: expanded from macro 'MODULE_INFO'
                                                           ^~~~
    include/linux/moduleparam.h:26:47: note: expanded from macro '__MODULE_INFO'
                    = __MODULE_INFO_PREFIX __stringify(tag) "=" info

    I could not figure out how to make the module handling robust enough
    to handle this better, but as a quick fix, using slightly shorter
    names that are still unique avoids the build issue.

    Fixes: 8d0872f6239f ("ASoC: Intel: add sof-nau8825 machine driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20221221132515.2363276-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>