USB: serial: quatech2: remove unused qt2_setdevice function
JIRA: https://issues.redhat.com/browse/RHEL-13058

commit 8c1b63b3c2358024181674e0ada901d50b919d3e
Author: Tom Rix <trix@redhat.com>
Date: Tue, 21 Mar 2023 14:12:55 -0400

  clang with W=1 reports
  drivers/usb/serial/quatech2.c:179:19: error: unused function
    'qt2_setdevice' [-Werror,-Wunused-function]
  static inline int qt2_setdevice(struct usb_device *dev, u8 *data)
                    ^
  This function is not used, so remove it.

  Signed-off-by: Tom Rix <trix@redhat.com>
  Link: https://lore.kernel.org/r/20230321181255.1825963-1-trix@redhat.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>