ASoC: codecs: zl38060: Mark OF related data as maybe unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
commit da1f22825b4fec7e25431fa5238252452f3dce46

The driver can be compile tested with !CONFIG_OF making certain data
unused:

  sound/soc/codecs/zl38060.c:611:34: error: ‘zl38_dt_ids’ defined but not used [-Werror=unused-const-variable=]

	Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230310214333.274903-10-krzysztof.kozlowski@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit da1f22825b4fec7e25431fa5238252452f3dce46)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>