bpf: fix implicit declaration of bpf_prog_add
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Brenden Blanco <bblanco@plumgrid.com>
commit cc2e0b3fbcdd9667d7b7ecdf36d7b4d3647681d6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/cc2e0b3f.failed

For the ifndef case of CONFIG_BPF_SYSCALL, an inline version of
bpf_prog_add needs to exist otherwise the build breaks on some configs.

 drivers/net/ethernet/mellanox/mlx4/en_netdev.c:2544:10: error: implicit declaration of function 'bpf_prog_add'
       prog = bpf_prog_add(prog, priv->rx_ring_num - 1);

The function is introduced in
59d3656d5bf50 ("bpf: add bpf_prog_add api for bulk prog refcnt")
and first used in
47f1afdba2b87 ("net/mlx4_en: add support for fast rx drop bpf program").

Fixes: 47f1afdba2b87 ("net/mlx4_en: add support for fast rx drop bpf program")
	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Reported-by: Tariq Toukan <ttoukan.linux@gmail.com>
	Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
	Acked-by: Alexei Starovoitov <ast@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit cc2e0b3fbcdd9667d7b7ecdf36d7b4d3647681d6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/linux/bpf.h