firmware: arm_scmi: Fix i.MX build dependency
JIRA: https://issues.redhat.com/browse/RHEL-73890

commit 514b2262ade48a0503ac6aa03c3bfb8c5be69b21
Author: Arnd Bergmann <arnd@arndb.de>
Date: Sat Nov 16 00:05:18 2024 +0100

    firmware: arm_scmi: Fix i.MX build dependency

    The newly added SCMI vendor driver references functions in the
    protocol driver but needs a Kconfig dependency to ensure it can link,
    essentially the Kconfig dependency needs to be reversed to match the
    link time dependency:

      |  arm-linux-gnueabi-ld: sound/soc/fsl/fsl_mqs.o: in function `fsl_mqs_sm_write':
      |  	fsl_mqs.c:(.text+0x1aa): undefined reference to `scmi_imx_misc_ctrl_set'
      |  arm-linux-gnueabi-ld: sound/soc/fsl/fsl_mqs.o: in function `fsl_mqs_sm_read':
      |  	fsl_mqs.c:(.text+0x1ee): undefined reference to `scmi_imx_misc_ctrl_get'

    This however only works after changing the dependency in the SND_SOC_FSL_MQS
    driver as well, which uses 'select IMX_SCMI_MISC_DRV' to turn on a
    driver it depends on. This is generally a bad idea, so the best solution
    is to change that into a dependency.

    To allow the ASoC driver to keep building with the SCMI support, this
    needs to be an optional dependency that enforces the link-time
    dependency if IMX_SCMI_MISC_DRV is a loadable module but not
    depend on it if that is disabled.

    Fixes: 61c9f03e22fc ("firmware: arm_scmi: Add initial support for i.MX MISC protocol")
    Fixes: 101c9023594a ("ASoC: fsl_mqs: Support accessing registers by scmi interface")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Mark Brown <broonie@kernel.org>
    Acked-by: Shengjiu Wang <shengjiu.wang@gmail.com>
    Message-Id: <20241115230555.2435004-1-arnd@kernel.org>
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>