ath11k: Fix uninitialized symbol 'rx_buf_sz'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Anilkumar Kolli <quic_akolli@quicinc.com>
commit dca857f07dc14c923a3c47965e771f435807b39c

Add missing else statement in ath11k_dp_rx_process_mon_status()
to fix below smatch warnings,
    drivers/net/wireless/ath/ath11k/dp_rx.c:3105
    ath11k_dp_rx_process_mon_status()
    error: uninitialized symbol 'rx_buf_sz'.

Fixes: ab18e3bc1c13 ("ath11k: Fix pktlog lite rx events")

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Anilkumar Kolli <quic_akolli@quicinc.com>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/1642605793-13518-1-git-send-email-quic_akolli@quicinc.com
(cherry picked from commit dca857f07dc14c923a3c47965e771f435807b39c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>