nvdimm/pfn_dev: Prevent the creation of zero-sized namespaces
JIRA: https://issues.redhat.com/browse/RHEL-23824

commit e96d9a938e8946e87daf456e0311020ca6747d99
Author: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
Date:   Wed Aug 9 11:05:11 2023 +0530

    nvdimm/pfn_dev: Prevent the creation of zero-sized namespaces
    
    On architectures that have different page size values used for kernel
    direct mapping and userspace mappings, the user can end up creating zero-sized
    namespaces as shown below
    
    :/sys/bus/nd/devices/region1# cat align
    0x1000000
    /sys/bus/nd/devices/region1# echo 0x200000 > align
    /sys/bus/nd/devices/region1/dax1.0# cat supported_alignments
    65536 16777216
     $ ndctl create-namespace -r region1 -m devdax -s 18M --align 64K
    {
      "dev":"namespace1.0",
      "mode":"devdax",
      "map":"dev",
      "size":0,
      "uuid":"3094329a-0c66-4905-847e-357223e56ab0",
      "daxregion":{
        "id":1,
        "size":0,
        "align":65536
      },
      "align":65536
    }
    similarily for fsdax
    
     $ ndctl create-namespace -r region1 -m fsdax  -s 18M --align 64K
    {
      "dev":"namespace1.0",
      "mode":"fsdax",
      "map":"dev",
      "size":0,
      "uuid":"45538a6f-dec7-405d-b1da-2a4075e06232",
      "sector_size":512,
      "align":65536,
      "blockdev":"pmem1"
    }
    
    In commit 9ffc1d19fc4a ("mm/memremap_pages: Introduce memremap_compat_align()")
    memremap_compat_align was added to make sure the kernel always creates
    namespaces with 16MB alignment. But the user can still override the
    region alignment and no input validation is done in the region alignment
    values to retain the flexibility user had before. However, the kernel
    ensures that only part of the namespace that can be mapped via kernel
    direct mapping page size is enabled. This is achieved by tracking the
    unmapped part of the namespace in pfn_sb->end_trunc. The kernel also
    ensures that the start address of the namespace is also aligned to the
    kernel direct mapping page size.
    
    Depending on the user request, the kernel implements userspace mapping
    alignment by updating pfn device alignment attribute and this value is
    used to adjust the start address for userspace mappings. This is tracked
    in pfn_sb->dataoff. Hence the available size for userspace mapping is:
    
    usermapping_size = size of the namespace - pfn_sb->end_trun - pfn_sb->dataoff
    
    If the kernel finds the user mapping size zero then don't allow the
    creation of namespace.
    
    After fix:
    $ ndctl create-namespace -f  -r region1 -m devdax  -s 18M --align 64K
    libndctl: ndctl_dax_enable: dax1.1: failed to enable
      Error: namespace1.2: failed to enable
    
    failed to create namespace: No such device or address
    
    And existing zero sized namespace will be marked disabled.
    root@ltczz75-lp2:/home/kvaneesh# ndctl  list -N -r region1 -i
    [
      {
        "dev":"namespace1.0",
        "mode":"raw",
        "size":18874368,
        "uuid":"94a90fb0-8e78-4fb6-a759-ffc62f9fa181",
        "sector_size":512,
        "state":"disabled"
      },
    
    Signed-off-by: Aneesh Kumar K.V <aneesh.kumar@linux.ibm.com>
    Reviewed-by: Jeff Moyer <jmoyer@redhat.com>
    Link: https://lore.kernel.org/r/20230809053512.350660-1-aneesh.kumar@linux.ibm.com
    Signed-off-by: Dave Jiang <dave.jiang@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>