ASoC: sdca: Fix missing regmap dependencies in Kconfig
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit bbb758a6943e19c483ab752cf8220140b46cf22c
Author: Boris Faure <boris@fau.re>
Date: Thu Jan 29 14:14:54 2026 +0000

    ASoC: sdca: Fix missing regmap dependencies in Kconfig

    The SDCA modules failed to build with modpost errors:

      ERROR: modpost: "__devm_regmap_init_sdw" [sound/soc/sdca/snd-soc-sdca-class.ko] undefined!
      ERROR: modpost: "__devm_regmap_init_sdw_mbq" [sound/soc/sdca/snd-soc-sdca-class-function.ko] undefined!

    The issue occurs because:
    - sdca_class.c calls devm_regmap_init_sdw() which requires REGMAP_SOUNDWIRE
    - sdca_class_function.c calls devm_regmap_init_sdw_mbq_cfg() which requires REGMAP_SOUNDWIRE_MBQ

    However, the Kconfig didn't select these dependencies, causing the symbols
    to be unavailable when the SDCA modules are built.

    Fix this by adding:
    - select REGMAP_SOUNDWIRE to SND_SOC_SDCA_CLASS
    - select REGMAP_SOUNDWIRE_MBQ to SND_SOC_SDCA_CLASS_FUNCTION

    This ensures the required regmap drivers are enabled when building SDCA support.

    Configuration after fix:
      CONFIG_SND_SOC_SDCA_CLASS=m
      CONFIG_SND_SOC_SDCA_CLASS_FUNCTION=m
      CONFIG_REGMAP_SOUNDWIRE=m
      CONFIG_REGMAP_SOUNDWIRE_MBQ=m

    Signed-off-by: Boris Faure <boris@fau.re>
    Link: https://patch.msgid.link/20260129141419.13843-1-boris@fau.re
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>