lib/genalloc.c: include vmalloc.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [lib] genalloc.c: include vmalloc.h (Don Dutile) [1754732]
Rebuild_FUZZ: 93.55%
commit-author Olof Johansson <olof@lixom.net>
commit 35004f2e55807a1a1491db24ab512dd2f770a130

Fixes build break on most ARM/ARM64 defconfigs:

  lib/genalloc.c: In function 'gen_pool_add_virt':
  lib/genalloc.c:190:10: error: implicit declaration of function 'vzalloc_node'; did you mean 'kzalloc_node'?
  lib/genalloc.c:190:8: warning: assignment to 'struct gen_pool_chunk *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  lib/genalloc.c: In function 'gen_pool_destroy':
  lib/genalloc.c:254:3: error: implicit declaration of function 'vfree'; did you mean 'kfree'?

Fixes: 6862d2fc8185 ('lib/genalloc.c: use vzalloc_node() to allocate the bitmap')
	Cc: Huang Shijie <sjhuang@iluvatar.ai>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Cc: Alexey Skidanov <alexey.skidanov@intel.com>
	Signed-off-by: Olof Johansson <olof@lixom.net>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 35004f2e55807a1a1491db24ab512dd2f770a130)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>