mt76: mt7615: fix potential overflow on large shift
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Ryder Lee <ryder.lee@mediatek.com>
commit 3253f8fddd954aba9ac88ce3c34551dcca505b21

Fix the following static checker warning:
error: undefined (user controlled) shift '(((1))) << (c->omac_idx)'

Fixes: 402a695b1ae6 ("mt76: mt7615: fix CSA notification for DBDC")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
	Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit 3253f8fddd954aba9ac88ce3c34551dcca505b21)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>