imx: soc: Select REGMAP_MMIO
Bugzilla: https://bugzilla.redhat.com/2182875

commit f617a8717657e9142de02e54c8e6c885c569692d
Author: Ezequiel Garcia <ezequiel@vanguardiasur.com.ar>
Date:   Fri Sep 24 11:01:46 2021 -0300

    imx: soc: Select REGMAP_MMIO

    The imx-gpcv2 driver needs Regmap MMIO. Select it, and fix:

    drivers/soc/imx/gpcv2.c:420:34: error: array type has incomplete element type ‘struct regmap_range’
      420 | static const struct regmap_range imx7_yes_ranges[] = {
          |                                  ^~~~~~~~~~~~~~~
    drivers/soc/imx/gpcv2.c:421:17: error: implicit declaration of function ‘regmap_reg_range’; did you mean ‘remap_pfn_range’? [-Werror=implicit-function-declaration]
      421 |                 regmap_reg_range(GPC_LPCR_A_CORE_BSC,
          |                 ^~~~~~~~~~~~~~~~
          |                 remap_pfn_range

    Signed-off-by: Ezequiel Garcia <ezequiel@vanguardiasur.com.ar>
    Signed-off-by: Shawn Guo <shawnguo@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>