perf tools: Fix arm64 build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [tools] perf: Fix arm64 build error (Jiri Olsa) [1169436]
Rebuild_FUZZ: 90.00%
commit-author Mark Salter <msalter@redhat.com>
commit 7d885749b6de2c9a1168d566e2380207b9177108

I'm seeing the following build error on arm64:

  In file included from util/event.c:3:0:
  util/event.h:95:17: error: 'PERF_REGS_MAX' undeclared here (not in a function)
    u64 cache_regs[PERF_REGS_MAX];
                 ^

This patch adds a PERF_REGS_MAX definition for arm64.

	Signed-off-by: Mark Salter <msalter@redhat.com>
	Acked-by: Jean Pihet <jean.pihet@linaro.org>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Jean Pihet <jean.pihet@linaro.org>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: http://lkml.kernel.org/r/1406325766-8085-1-git-send-email-msalter@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 7d885749b6de2c9a1168d566e2380207b9177108)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>