sfc (gcc13): synchronize ef100_enqueue_skb()'s return type
Bugzilla: https://bugzilla.redhat.com/2159241

commit 3319dbb3e755398f254c3daa04b9030197137efe
Author: Jiri Slaby (SUSE) <jirislaby@kernel.org>
Date:   Mon Oct 31 12:44:40 2022 +0100

    sfc (gcc13): synchronize ef100_enqueue_skb()'s return type
    
    ef100_enqueue_skb() generates a valid warning with gcc-13:
      drivers/net/ethernet/sfc/ef100_tx.c:370:5: error: conflicting types for 'ef100_enqueue_skb' due to enum/integer mismatch; have 'int(struct efx_tx_queue *, struct sk_buff *)'
      drivers/net/ethernet/sfc/ef100_tx.h:25:13: note: previous declaration of 'ef100_enqueue_skb' with type 'netdev_tx_t(struct efx_tx_queue *, struct sk_buff *)'
    
    I.e. the type of the ef100_enqueue_skb()'s return value in the declaration is
    int, while the definition spells enum netdev_tx_t. Synchronize them to the
    latter.
    
    Cc: Martin Liska <mliska@suse.cz>
    Cc: Edward Cree <ecree.xilinx@gmail.com>
    Cc: Martin Habets <habetsm.xilinx@gmail.com>
    Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
    Link: https://lore.kernel.org/r/20221031114440.10461-1-jirislaby@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>