RDMA/bnxt_re: remove unused num_srqne_processed and num_cqne_processed variables
JIRA: https://issues.redhat.com/browse/RHEL-3526
JIRA: https://issues.redhat.com/browse/RHEL-11009

commit 1b69f1e3d7449d0c66f7bc0f429ed94fc03dfeb3
Author: Tom Rix <trix@redhat.com>
Date: Sat, 25 Mar 2023 10:05:59 -0400

    RDMA/bnxt_re: remove unused num_srqne_processed and num_cqne_processed variables

    clang with W=1 reports
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:303:6: error: variable
      'num_srqne_processed' set but not used [-Werror,-Wunused-but-set-variable]
            int num_srqne_processed = 0;
            ^
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:304:6: error: variable
      'num_cqne_processed' set but not used [-Werror,-Wunused-but-set-variable]
            int num_cqne_processed = 0;
                ^
    These variables are not used so remove them.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230325140559.1336056-1-trix@redhat.com
    Acked-by: Selvin Xavier <selvin.xavier@broadcom.com>
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Sreekanth Reddy <sreeredd@redhat.com>