x86: ksysfs.c build fix
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [x86] ksysfs.c build fix (Dave Young) [1080109]
Rebuild_FUZZ: 87.80%
commit-author Dave Young <dyoung@redhat.com>
commit 41a34cec2e0df7798ea322ed1480bc3d3facdc8e

kbuild test robot report below error for randconfig:

  arch/x86/kernel/ksysfs.c: In function 'get_setup_data_paddr':
  arch/x86/kernel/ksysfs.c:81:3: error: implicit declaration of function 'ioremap_cache' [-Werror=implicit-function-declaration]
  arch/x86/kernel/ksysfs.c:86:3: error: implicit declaration of function 'iounmap' [-Werror=implicit-function-declaration]

Fix it by including <asm/io.h> in ksysfs.c

	Signed-off-by: Dave Young <dyoung@redhat.com>
	Signed-off-by: Matt Fleming <matt.fleming@intel.com>
(cherry picked from commit 41a34cec2e0df7798ea322ed1480bc3d3facdc8e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>