ACPI: tools: pfrut: fix memory leak and resource leak in pfrut.c
JIRA: https://issues.redhat.com/browse/RHEL-156420

commit 8974573ba45493af6120093cdf88ce5511aff935
Author: Malaya Kumar Rout <mrout@redhat.com>
Date: Mon, 24 Nov 2025 20:50:15 +0000

Static analysis found an issue in pfrut.c

cppcheck output before this patch:
tools/power/acpi/tools/pfrut/pfrut.c:225:3: error: Resource leak: fd_update [resourceLeak]
tools/power/acpi/tools/pfrut/pfrut.c:269:3: error: Resource leak: fd_update [resourceLeak]
tools/power/acpi/tools/pfrut/pfrut.c:269:3: error: Resource leak: fd_update_log [resourceLeak]
tools/power/acpi/tools/pfrut/pfrut.c:365:4: error: Memory leak: addr_map_capsule [memleak]
tools/power/acpi/tools/pfrut/pfrut.c:424:4: error: Memory leak: log_buf [memleak]

cppcheck output after this patch:
No resource leaks found

Fix by closing file descriptors and freeing allocated memory.

Signed-off-by: Malaya Kumar Rout <mrout@redhat.com>
Link: https://patch.msgid.link/20251120170001.251968-1-mrout@redhat.com
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>