netfilter: nft_set_pipapo: don't return bogus extension pointer
JIRA: https://redhat.atlassian.net/browse/RHEL-186601
Upstream Status: commit c8a7c2c60818

commit c8a7c2c608180f3b4e51dc958b3861242dcdd76d
Author: Florian Westphal <fw@strlen.de>
Date:   Mon Aug 4 12:10:41 2025 +0200

    netfilter: nft_set_pipapo: don't return bogus extension pointer

    Dan Carpenter says:
    Commit 17a20e09f086 ("netfilter: nft_set: remove one argument from
    lookup and update functions") [..] leads to the following Smatch
    static checker warning:

     net/netfilter/nft_set_pipapo_avx2.c:1269 nft_pipapo_avx2_lookup()
     error: uninitialized symbol 'ext'.

    Fix this by initing ext to NULL and set it only once we've found
    a match.

    Fixes: 17a20e09f086 ("netfilter: nft_set: remove one argument from lookup and update functions")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/netfilter-devel/aJBzc3V5wk-yPOnH@stanley.mountain/
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>