drm/i915/tc: Fix -Wformat-truncation in intel_tc_port_init
JIRA: https://issues.redhat.com/browse/RHEL-1351
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.6.3)

commit 8ebe2d452fd0c7e6ac2583e3f41022f60e0f1fd1
Author:     Nirmoy Das <nirmoy.das@intel.com>
AuthorDate: Thu Oct 26 14:56:36 2023 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Tue Nov 28 17:19:49 2023 +0000

    [ Upstream commit 9506fba463fcbdf8c8b7af3ec9ee34360df843fe ]

    Fix below compiler warning:

    intel_tc.c:1879:11: error: ‘%d’ directive output may be truncated
    writing between 1 and 11 bytes into a region of size 3
    [-Werror=format-truncation=]
    "%c/TC#%d", port_name(port), tc_port + 1);
               ^~
    intel_tc.c:1878:2: note: ‘snprintf’ output between 7 and 17 bytes
    into a destination of size 8
      snprintf(tc->port_name, sizeof(tc->port_name),
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        "%c/TC#%d", port_name(port), tc_port + 1);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    v2: use kasprintf(Imre)
    v3: use const for port_name, and fix tc mem leak(Imre)

    Fixes: 3eafcddf766b ("drm/i915/tc: Move TC port fields to a new intel_tc_port struct")
    Cc: Mika Kahola <mika.kahola@intel.com>
    Cc: Imre Deak <imre.deak@intel.com>
    Cc: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Nirmoy Das <nirmoy.das@intel.com>
    Reviewed-by: Andrzej Hajda <andrzej.hajda@intel.com>
    Reviewed-by: Imre Deak <imre.deak@intel.com>
    Reviewed-by: Mika Kahola <mika.kahola@intel.com>
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20231026125636.5080-1-nirmoy.das@intel.com
    (cherry picked from commit 70a3cbbe620ee66afb0c066624196077767e61b2)
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>