lockdep: Address clang -Wformat warning printing for %hd
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
Rebuild_CHGLOG: - lockdep: Address clang -Wformat warning printing for hd (Waiman Long) [1954361]
Rebuild_FUZZ: 99.10%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 6d48b7912cc72275dc7c59ff961c8bac7ef66a92

Clang doesn't like format strings that truncate a 32-bit
value to something shorter:

  kernel/locking/lockdep.c:709:4: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]

In this case, the warning is a slightly questionable, as it could realize
that both class->wait_type_outer and class->wait_type_inner are in fact
8-bit struct members, even though the result of the ?: operator becomes an
'int'.

However, there is really no point in printing the number as a 16-bit
'short' rather than either an 8-bit or 32-bit number, so just change
it to a normal %d.

Fixes: de8f5e4f2dc1 ("lockdep: Introduce wait-type checks")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lore.kernel.org/r/20210322115531.3987555-1-arnd@kernel.org
(cherry picked from commit 6d48b7912cc72275dc7c59ff961c8bac7ef66a92)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>