mm/kmemleak.c: fix unused-function warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit dce5b0bdeec61bdbee56121ceb1d014151d5cab1

The only references outside of the #ifdef have been removed, so now we
get a warning in non-SMP configurations:

  mm/kmemleak.c:1404:13: error: unused function 'scan_large_block' [-Werror,-Wunused-function]

Add a new #ifdef around it.

Link: http://lkml.kernel.org/r/20190416123148.3502045-1-arnd@arndb.de
Fixes: 298a32b13208 ("kmemleak: powerpc: skip scanning holes in the .bss section")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Catalin Marinas <catalin.marinas@arm.com>
	Cc: Vincent Whitchurch <vincent.whitchurch@axis.com>
	Cc: Michael Ellerman <mpe@ellerman.id.au>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit dce5b0bdeec61bdbee56121ceb1d014151d5cab1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>