rtw88: wow: build wow function only if CONFIG_PM is on
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Ping-Ke Shih <pkshih@realtek.com>
commit 05e45887382c4c0f9522515759b34991aa17e69d

The kernel test robot reports undefined reference after we report wakeup
reason to mac80211. This is because CONFIG_PM is not defined in the testing
configuration file. In fact, functions within wow.c are used if CONFIG_PM
is defined, so use CONFIG_PM to decide whether we build this file or not.

The reported messages are:
   hppa-linux-ld: drivers/net/wireless/realtek/rtw88/wow.o: in function `rtw_wow_show_wakeup_reason':
>> (.text+0x6c4): undefined reference to `ieee80211_report_wowlan_wakeup'
>> hppa-linux-ld: (.text+0x6e0): undefined reference to `ieee80211_report_wowlan_wakeup'

	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20210728014335.8785-4-pkshih@realtek.com
(cherry picked from commit 05e45887382c4c0f9522515759b34991aa17e69d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>