Bluetooth: NXP: select CONFIG_CRC8
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit 11e29b4a3fda975f4427800285b7e4544f4e9152
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Mar 22 12:16:27 2023 +0100

    Bluetooth: NXP: select CONFIG_CRC8

    The driver needs both CRC32 and CRC8 to link correctly:

    ld: drivers/bluetooth/btnxpuart.o: in function `nxp_serdev_probe':
    drivers/bluetooth/btnxpuart.c:1214: undefined reference to
    `crc8_populate_msb'
    ld: drivers/bluetooth/btnxpuart.o: in function `nxp_send_ack':
    drivers/bluetooth/btnxpuart.c:559: undefined reference to `crc8'
    ld: drivers/bluetooth/btnxpuart.c:559: undefined reference to `crc8'

    Fixes: 3e662aa4453a ("Bluetooth: NXP: Add protocol support for NXP Bluetooth chipsets")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>