media: v4l2-ioctl: S_CTRL output the right value
JIRA: https://issues.redhat.com/browse/RHEL-67885

commit c87ed93574e3cd8346c05bd934c617596c12541b
Author: Ricardo Ribalda <ribalda@chromium.org>
Date: Fri, 18 Jun 2021 14:29:06 +0200

  If the driver does not implement s_ctrl, but it does implement
  s_ext_ctrls, we convert the call.

  When that happens we have also to convert back the response from
  s_ext_ctrls.

  Fixes v4l2_compliance:
  Control ioctls (Input 0):
  		fail: v4l2-test-controls.cpp(411): returned control value out of range
  		fail: v4l2-test-controls.cpp(507): invalid control 00980900
  	test VIDIOC_G/S_CTRL: FAIL

  Fixes: 35ea11ff8471 ("V4L/DVB (8430): videodev: move some functions from v4l2-dev.h to v4l2-common.h or v4l2-ioctl.h")
  Reviewed-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
  Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
  Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Kate Hsuan <hpa@redhat.com>