hrtimers: Mark is_migration_base() with __always_inline
JIRA: https://issues.redhat.com/browse/RHEL-114122

commit 27af31e44949fa85550176520ef7086a0d00fd7b
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Thu, 16 Jan 2025 18:07:45 +0200

    hrtimers: Mark is_migration_base() with __always_inline

    When is_migration_base() is unused, it prevents kernel builds
    with clang, `make W=1` and CONFIG_WERROR=y:

    kernel/time/hrtimer.c:156:20: error: unused function 'is_migration_base' [-Werror,-Wunused-function]
      156 | static inline bool is_migration_base(struct hrtimer_clock_base *base)
          |                    ^~~~~~~~~~~~~~~~~

    Fix this by marking it with __always_inline.

    [ tglx: Use __always_inline instead of __maybe_unused and move it into the
            usage sites conditional ]

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Link: https://lore.kernel.org/all/20250116160745.243358-1-andriy.shevchenko@linux.intel.com

Signed-off-by: Waiman Long <longman@redhat.com>