net: bnxt_ptp: fix compilation error
Bugzilla: http://bugzilla.redhat.com/2043783
Bugzilla: http://bugzilla.redhat.com/2042819

commit dcf500065fabe27676dfe7b4ba521a4f1e0fc8ac
Author: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Date:   Mon Mar 28 15:27:08 2022 +0900

    net: bnxt_ptp: fix compilation error

    The Broadcom bnxt_ptp driver does not compile with GCC 11.2.2 when
    CONFIG_WERROR is enabled. The following error is generated:

    drivers/net/ethernet/broadcom/bnxt/bnxt_ptp.c: In function ‘bnxt_ptp_enable’:
    drivers/net/ethernet/broadcom/bnxt/bnxt_ptp.c:400:43: error: array
    subscript 255 is above array bounds of ‘struct pps_pin[4]’
    [-Werror=array-bounds]
      400 |  ptp->pps_info.pins[pin_id].event = BNXT_PPS_EVENT_EXTERNAL;
          |  ~~~~~~~~~~~~~~~~~~^~~~~~~~
    In file included from drivers/net/ethernet/broadcom/bnxt/bnxt_ptp.c:20:
    drivers/net/ethernet/broadcom/bnxt/bnxt_ptp.h:75:24: note: while
    referencing ‘pins’
       75 |         struct pps_pin pins[BNXT_MAX_TSIO_PINS];
          |                        ^~~~
    cc1: all warnings being treated as errors

    This is due to the function ptp_find_pin() returning a pin ID of -1 when
    a valid pin is not found and this error never being checked.
    Change the TSIO_PIN_VALID() function to also check that a pin ID is not
    negative and use this macro in bnxt_ptp_enable() to check the result of
    the calls to ptp_find_pin() to return an error early for invalid pins.
    This fixes the compilation error.

    Cc: <stable@vger.kernel.org>
    Fixes: 9e518f25802c ("bnxt_en: 1PPS functions to configure TSIO pins")
    Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
    Reviewed-by: Michael Chan <michael.chan@broadcom.com>
    Link: https://lore.kernel.org/r/20220328062708.207079-1-damien.lemoal@opensource.wdc.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ken Cox <jkc@redhat.com>