net: sched: gred: dynamically allocate tc_gred_qopt_offload
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2090410

commit f25c0515c521375154c62c72447869f40218c861
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 26 12:07:11 2021 +0200

    net: sched: gred: dynamically allocate tc_gred_qopt_offload

    The tc_gred_qopt_offload structure has grown too big to be on the
    stack for 32-bit architectures after recent changes.

    net/sched/sch_gred.c:903:13: error: stack frame size (1180) exceeds limit (1024) in 'gred_destroy' [-Werror,-Wframe-larger-than]
    net/sched/sch_gred.c:310:13: error: stack frame size (1212) exceeds limit (1024) in 'gred_offload' [-Werror,-Wframe-larger-than]

    Use dynamic allocation per qdisc to avoid this.

    Fixes: 50dc9a8572aa ("net: sched: Merge Qdisc::bstats and Qdisc::cpu_bstats data types")
    Fixes: 67c9e6270f30 ("net: sched: Protect Qdisc::bstats with u64_stats")
    Suggested-by: Jakub Kicinski <kuba@kernel.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
    Link: https://lore.kernel.org/r/20211026100711.nalhttf6mbe6sudx@linutronix.de
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>