platform/x86/intel/pmt/discovery: fix format string warning
JIRA: https://issues.redhat.com/browse/RHEL-119042

commit 6382c27389c266e90b31151a79d81fa6e122d2d6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 11 09:27:09 2025 +0200

    platform/x86/intel/pmt/discovery: fix format string warning

    When -Wformat-security is enabled, this new code triggers it:

    drivers/platform/x86/intel/pmt/discovery.c: In function 'pmt_features_discovery':
    drivers/platform/x86/intel/pmt/discovery.c:505:36: error: format not a string literal and no format arguments [-Werror=format-security]
      505 |                                    pmt_feature_names[feature->id]);

    Fixes: d9a078809356 ("platform/x86/intel/pmt: Add PMT Discovery driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250711072718.2748415-1-arnd@kernel.org
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>

Signed-off-by: Steve Best <sbest@redhat.com>