fm10k: Add CONFIG_FM10K_VXLAN configuration option
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Andy Zhou <azhou@nicira.com>
commit f6b03c10a1b3f2c98ed23813997cdebef8aabeba

Compiling with CONFIG_FM10K=y and VXLAN=m resulting in linking error:

   drivers/built-in.o: In function `fm10k_open':
   (.text+0x1f9d7a): undefined reference to `vxlan_get_rx_port'
   make: *** [vmlinux] Error 1

The fix follows the same strategy as I40E.

	Signed-off-by: Andy Zhou <azhou@nicira.com>
	Acked-by: Alexander Duyck <alexander.h.duyck@intel.com>
	Tested-by: Aaron Brown <aaron.f.brown@intel.com>
	Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
(cherry picked from commit f6b03c10a1b3f2c98ed23813997cdebef8aabeba)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>