net/sched: act_police: Add extack messages for offload failure
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

Conflicts:
- modified due to existing backport of 052f744f4446 ("net/sched:
  act_police: allow 'continue' action offload")

commit b50e462bc22df4488ec04d85606646e3db5952b8
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:27 2022 +0300

    net/sched: act_police: Add extack messages for offload failure

    For better error reporting to user space, add extack messages when
    police action offload fails.

    Example:

     # echo 1 > /sys/kernel/tracing/events/netlink/netlink_extack/enable

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action police rate 100Mbit burst 10000
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-182     [000] b..1.    21.592969: netlink_extack: msg=act_police: Offload not supported when conform/exceed action is "reclassify"
           tc-182     [000] .....    21.592982: netlink_extack: msg=cls_matchall: Failed to setup flow action

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action police rate 100Mbit burst 10000 conform-exceed drop/continue
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-184     [000] b..1.    38.882579: netlink_extack: msg=act_police: Offload not supported when conform/exceed action is "continue"
           tc-184     [000] .....    38.882593: netlink_extack: msg=cls_matchall: Failed to setup flow action

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>