ASoC: imx-rpmsg: SND_SOC_IMX_RPMSG should depend on OF and I2C
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit f83d38def6b1b00c9bb17173837045b41df7e7d7
Author: Chancel Liu <chancel.liu@nxp.com>
Date: Sat Nov 25 14:53:00 2023 +0800

    ASoC: imx-rpmsg: SND_SOC_IMX_RPMSG should depend on OF and I2C

    SND_SOC_IMX_RPMSG should depend on OF and I2C. It fixes the following
    error reported by kernel test robot:

    ld: sound/soc/fsl/imx-rpmsg.o: in function `imx_rpmsg_late_probe':
    imx-rpmsg.c:(.text+0x4f): undefined reference to `i2c_find_device_by_fwnode'

    Fixes: 5d9f746ca64c ("ASoC: imx-rpmsg: Force codec power on in low power audio mode")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202311230506.DPF9vvYY-lkp@intel.com/
    Signed-off-by: Chancel Liu <chancel.liu@nxp.com>
    Link: https://lore.kernel.org/r/20231125065300.6385-1-chancel.liu@nxp.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>