accel/amdxdna: include linux/slab.h
JIRA: https://redhat.atlassian.net/browse/RHEL-222546
Upstream Status: v6.14-rc1

commit 221e29e197981e8e5882cdcf230d063598298e2f
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Wed Dec 18 09:58:57 2024 +0100
Commit:     Mario Limonciello <mario.limonciello@amd.com>
CommitDate: Wed Dec 18 08:14:12 2024 -0600
    
    This driver fails to build in random configurations:
    
    drivers/accel/amdxdna/aie2_solver.c: In function 'remove_partition_node':
    drivers/accel/amdxdna/aie2_solver.c:121:9: error: implicit declaration of function 'kfree' [-Wimplicit-function-declaration]
      121 |         kfree(pt_node);
          |         ^~~~~
    drivers/accel/amdxdna/aie2_solver.c: In function 'get_free_partition':
    drivers/accel/amdxdna/aie2_solver.c:153:19: error: implicit declaration of function 'kzalloc' [-Wimplicit-function-declaration]
      153 |         pt_node = kzalloc(sizeof(*pt_node), GFP_KERNEL);
    
    Add the missing include.
    
    Fixes: c88d3325ae69 ("accel/amdxdna: Add hardware resource solver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Mario Limonciello <mario.limonciello@amd.com>
    Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241218085902.2684002-1-arnd@kernel.org

Signed-off-by: Peter Colberg <pcolberg@redhat.com>