extcon: max14526: depends on I2C to prevent build warning/errors
JIRA: https://issues.redhat.com/browse/RHEL-147786

commit 531f47fd35f4ead8c76d584ef8c546b4cd9cb3b7
Author: Randy Dunlap <rdunlap@infradead.org>
Date: Thu, 15 May 2025 16:48:03 -0700

  Make EXTCON_MAX14526 depend on I2C to address a kconfig warning and
  subsequent build errors:

  WARNING: unmet direct dependencies detected for REGMAP_I2C
    Depends on [m]: I2C [=m]
    Selected by [y]:
    - EXTCON_MAX14526 [=y] && EXTCON [=y]

  ld: vmlinux.o: in function `max14526_driver_init':
  extcon-max14526.c:(.init.text+0x77b0e): undefined reference to `i2c_register_driver'
  ld: vmlinux.o: in function `max14526_driver_exit':
  extcon-max14526.c:(.exit.text+0x467c): undefined reference to `i2c_del_driver'

  Fixes: 145af3ddd1cd ("extcon: Add basic support for Maxim MAX14526 MUIC")
  Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
  Signed-off-by: Chanwoo Choi <cw00.choi@samsung.com>
  Link: https://lore.kernel.org/lkml/20250515234803.1385375-1-rdunlap@infradead.org/

Signed-off-by: Desnes Nunes <desnesn@redhat.com>