sched: fair: move unused stub functions to header
JIRA: https://issues.redhat.com/browse/RHEL-25535

commit b1c3efe07987592c16d5f59ce235e6ddbea65a73
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Nov 23 12:05:03 2023 +0100

    sched: fair: move unused stub functions to header

    These four functions have a normal definition for CONFIG_FAIR_GROUP_SCHED,
    and empty one that is only referenced when FAIR_GROUP_SCHED is disabled
    but CGROUP_SCHED is still enabled.  If both are turned off, the functions
    are still defined but the misisng prototype causes a W=1 warning:

    kernel/sched/fair.c:12544:6: error: no previous prototype for 'free_fair_sched_group'
    kernel/sched/fair.c:12546:5: error: no previous prototype for 'alloc_fair_sched_group'
    kernel/sched/fair.c:12553:6: error: no previous prototype for 'online_fair_sched_group'
    kernel/sched/fair.c:12555:6: error: no previous prototype for 'unregister_fair_sched_group'

    Move the alternatives into the header as static inline functions with the
    correct combination of #ifdef checks to avoid the warning without adding
    even more complexity.

    [A different patch with the same description got applied by accident
     and was later reverted, but the original patch is still missing]

    Link: https://lkml.kernel.org/r/20231123110506.707903-4-arnd@kernel.org
    Fixes: 7aa55f2a5902 ("sched/fair: Move unused stub functions to header")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: David Woodhouse <dwmw2@infradead.org>
    Cc: Dinh Nguyen <dinguyen@kernel.org>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Ivan Kokshaysky <ink@jurassic.park.msu.ru>
    Cc: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
    Cc: Kees Cook <keescook@chromium.org>
    Cc: Masahiro Yamada <masahiroy@kernel.org>
    Cc: Matt Turner <mattst88@gmail.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Cc: Nathan Chancellor <nathan@kernel.org>
    Cc: Nicolas Schier <nicolas@fjasle.eu>
    Cc: Palmer Dabbelt <palmer@rivosinc.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Richard Henderson <richard.henderson@linaro.org>
    Cc: Richard Weinberger <richard@nod.at>
    Cc: Rich Felker <dalias@libc.org>
    Cc: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
    Cc: Tudor Ambarus <tudor.ambarus@linaro.org>
    Cc: Yoshinori Sato <ysato@users.sourceforge.jp>
    Cc: Zhihao Cheng <chengzhihao1@huawei.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Phil Auld <pauld@redhat.com>