x86, sched: Fix undefined reference to init_freq_invariance_cppc() build error
Bugzilla: https://bugzilla.redhat.com/2164042

commit 6c4ab1b86dac3954d15c00c1a6396d60a1023fab
Author: Huang Rui <ray.huang@amd.com>
Date:   Thu Jan 6 15:43:06 2022 +0800

    x86, sched: Fix undefined reference to init_freq_invariance_cppc() build error

    The init_freq_invariance_cppc function is implemented in smpboot and depends on
    CONFIG_SMP.

      MODPOST vmlinux.symvers
      MODINFO modules.builtin.modinfo
      GEN     modules.builtin
      LD      .tmp_vmlinux.kallsyms1
    ld: drivers/acpi/cppc_acpi.o: in function `acpi_cppc_processor_probe':
    /home/ray/brahma3/linux/drivers/acpi/cppc_acpi.c:819: undefined reference to `init_freq_invariance_cppc'
    make: *** [Makefile:1161: vmlinux] Error 1

    See https://lore.kernel.org/lkml/484af487-7511-647e-5c5b-33d4429acdec@infradead.org/.

    Fixes: 41ea667227ba ("x86, sched: Calculate frequency invariance for AMD systems")
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Huang Rui <ray.huang@amd.com>
    [ rjw: Subject edits ]
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>