ALSA: jack: fix a randconfig build issue
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [alsa] jack: fix a randconfig build issue (Jaroslav Kysela) [1197064]
Rebuild_FUZZ: 91.89%
commit-author Jie Yang <yang.jie@intel.com>
commit 973109cafc9d11e41be4d64667ff2165bf79d948
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/973109ca.failed

Building errors reported such as below when 'CONFIG_INPUT=m':
    ...undefined reference to `input_xxx'...

Here change to enable SND_JACK selectively to fix the issue.

Also remove the config 'SND_HDA_INPUT_JACK' which won't be
used anymore.

	Signed-off-by: Jie Yang <yang.jie@intel.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 973109cafc9d11e41be4d64667ff2165bf79d948)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	sound/pci/hda/Kconfig