net/mlx5: FWTrace, Reduce stack usage
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [netdrv] mlx5: FWTrace, Reduce stack usage (Alaa Hleihel) [1724336]
Rebuild_FUZZ: 94.29%
commit-author Saeed Mahameed <saeedm@mellanox.com>
commit fa355bb1b0373e7fe087cfc830b1b0b9b6130388
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-193.el8/fa355bb1.failed

Mark mlx5_tracer_print_trace as noinline as the function only uses 512
bytes on the stack to avoid the following build warning:

drivers/net/ethernet/mellanox/mlx5/core/diag/fw_tracer.c:660:13: error: stack frame size of 1032 bytes in function 'mlx5_fw_tracer_handle_traces' [-Werror,-Wframe-larger-than=]

Fixes: 70dd6fdb8987 ("net/mlx5: FW tracer, parse traces and kernel tracing support")
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit fa355bb1b0373e7fe087cfc830b1b0b9b6130388)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/mellanox/mlx5/core/diag/fw_tracer.c