phy: qcom: uniphy-28lp: add COMMON_CLK dependency
JIRA: https://issues.redhat.com/browse/RHEL-122019

commit be8f23cebdb9546beb30ad15ff59130b66c8f2ac
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 14 Mar 2025 16:49:10 +0100

  In configurations without CONFIG_COMMON_CLK, the driver fails to build:

  aarch64-linux-ld: drivers/phy/qualcomm/phy-qcom-uniphy-pcie-28lp.o: in function `qcom_uniphy_pcie_probe':
  phy-qcom-uniphy-pcie-28lp.c:(.text+0x200): undefined reference to `__clk_hw_register_fixed_rate'
  aarch64-linux-ld: phy-qcom-uniphy-pcie-28lp.c:(.text+0x238): undefined reference to `of_clk_hw_simple_get'
  phy-qcom-uniphy-pcie-28lp.c:(.text+0x238): dangerous relocation: unsupported relocation
  aarch64-linux-ld: phy-qcom-uniphy-pcie-28lp.c:(.text+0x240): undefined reference to `of_clk_hw_simple_get'
  aarch64-linux-ld: phy-qcom-uniphy-pcie-28lp.c:(.text+0x248): undefined reference to `devm_of_clk_add_hw_provider'

  Add that as a Kconfig dependencies.

  Fixes: 74badb8b0b14 ("phy: qcom: Introduce PCIe UNIPHY 28LP driver")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>
  Link: https://lore.kernel.org/r/20250314154915.4074980-1-arnd@kernel.org
  Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>