net: octeontx2-pf: mcs: consider MACSEC setting
JIRA: https://issues.redhat.com/browse/RHEL-23617

commit 4581dd480c9e42a1ad21dd8b9c110abe41878ce5
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Mon Oct 31 22:08:13 2022 -0700

    net: octeontx2-pf: mcs: consider MACSEC setting

    Fix build errors when MACSEC=m and OCTEONTX2_PF=y by having
    OCTEONTX2_PF depend on MACSEC if it is enabled. By adding
    "|| !MACSEC", this means that MACSEC is not required -- it can
    be disabled for this driver.

    drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_remove':
    ../drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c:(.text+0x2fd0): undefined reference to `cn10k_mcs_free'
    mips64-linux-ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_mbox_up_handler_mcs_intr_notify':
    ../drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c:(.text+0x4610): undefined reference to `cn10k_handle_mcs_event'

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: c54ffc73601c ("octeontx2-pf: mcs: Introduce MACSEC hardware offloading")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Subbaraya Sundeep <sbhatta@marvell.com>
    Cc: Sunil Goutham <sgoutham@marvell.com>
    Cc: Geetha sowjanya <gakula@marvell.com>
    Cc: hariprasad <hkelam@marvell.com>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: Eric Dumazet <edumazet@google.com>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: Paolo Abeni <pabeni@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Sai Krishna <sgajula@redhat.com>