kasan: fix a missing header include of static_keys.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070169

commit d8fd5a1e78db375f2246d43df7833fec07a221cd
Author: Joey Gouly <joey.gouly@arm.com>
Date: Tue, 1 Mar 2022 15:45:18 +0000

    The kasan-enabled.h header relies on static keys, so make sure
    to include the header to avoid compilation errors (with JUMP_LABEL=n).

    It fixes the following:
    ./include/linux/kasan-enabled.h:9:1: warning: data definition has no type or storage class
        9 | DECLARE_STATIC_KEY_FALSE(kasan_flag_enabled);
          | ^~~~~~~~~~~~~~~~~~~~~~~~
    error: type defaults to 'int' in declaration of 'DECLARE_STATIC_KEY_FALSE' [-Werror=implicit-int]

    Fixes: f9b5e46f4097eb29 ("kasan: split kasan_*enabled() functions into a separate header")
    Cc: Peter Collingbourne <pcc@google.com>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Will Deacon <will@kernel.org>
    Acked-by: Andrey Konovalov <andreyknvl@gmail.com>
    Signed-off-by: Joey Gouly <joey.gouly@arm.com>
    Link: https://lore.kernel.org/r/20220301154518.19456-1-joey.gouly@arm.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>