KVM: s390: remove unused gisa_clear_ipm_gisc() function
Bugzilla: http://bugzilla.redhat.com/2169293

commit 99b63f55dc514a357c2ecf25e9aab149879329f0
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Fri Nov 18 16:11:33 2022 +0100

    KVM: s390: remove unused gisa_clear_ipm_gisc() function

    clang warns about an unused function:
    arch/s390/kvm/interrupt.c:317:20:
      error: unused function 'gisa_clear_ipm_gisc' [-Werror,-Wunused-function]
    static inline void gisa_clear_ipm_gisc(struct kvm_s390_gisa *gisa, u32 gisc)

    Remove gisa_clear_ipm_gisc(), since it is unused and get rid of this
    warning.

    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Reviewed-by: Thomas Huth <thuth@redhat.com>
    Link: https://lore.kernel.org/r/20221118151133.2974602-1-hca@linux.ibm.com
    Signed-off-by: Christian Borntraeger <borntraeger@linux.ibm.com>
    Signed-off-by: Janosch Frank <frankja@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>