fbdev: au1100fb: Mark several local functions as static
JIRA: https://redhat.atlassian.net/browse/RHEL-135265

commit 2bb53005f4670b8c17c181b9559319b27a6ab74e
Author: Uwe Kleine-König <u.kleine-koenig@baylibre.com>
Date:   Mon Feb 16 00:33:18 2026 +0100

    fbdev: au1100fb: Mark several local functions as static

    This fixes several (fatal) compiler warnings à la

            drivers/video/fbdev/au1100fb.c:530:6: error: no previous prototype for ‘au1100fb_drv_remove’ [-Werror=missing-prototypes]
              523 | void au1100fb_drv_remove(struct platform_device *dev)
                  |      ^~~~~~~~~~~~~~~~~~~

    Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>