net: wwan: t7xx: do not compile with -Werror
Bugzilla: https://bugzilla.redhat.com/2123542

commit 362f0b6678ad1377c322a7dd237ea6785efc7342
Author: Jiri Slaby (SUSE) <jirislaby@kernel.org>
Date:   Fri Mar 31 08:35:15 2023 +0200

    net: wwan: t7xx: do not compile with -Werror
    
    When playing with various compilers or their versions, some choke on
    the t7xx code. For example (with gcc 13):
     In file included from ./arch/s390/include/generated/asm/rwonce.h:1,
                      from ../include/linux/compiler.h:247,
                      from ../include/linux/build_bug.h:5,
                      from ../include/linux/bits.h:22,
                      from ../drivers/net/wwan/t7xx/t7xx_state_monitor.c:17:
     In function 'preempt_count',
         inlined from 't7xx_fsm_append_event' at ../drivers/net/wwan/t7xx/t7xx_state_monitor.c:439:43:
     ../include/asm-generic/rwonce.h:44:26: error: array subscript 0 is outside array bounds of 'const volatile int[0]' [-Werror=array-bounds=]
    
    There is no reason for any code in the kernel to be built with -Werror
    by default. Note that we have generic CONFIG_WERROR. So if anyone wants
    -Werror, they can enable that.
    
    Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
    Link: https://lore.kernel.org/all/20230330232717.1f8bf5ea@kernel.org/
    Cc: Chandrashekar Devegowda <chandrashekar.devegowda@intel.com>
    Cc: Intel Corporation <linuxwwan@intel.com>
    Cc: Chiranjeevi Rapolu <chiranjeevi.rapolu@linux.intel.com>
    Cc: Liu Haijun <haijun.liu@mediatek.com>
    Cc: M Chetan Kumar <m.chetan.kumar@linux.intel.com>
    Cc: Ricardo Martinez <ricardo.martinez@linux.intel.com>
    Cc: Loic Poulain <loic.poulain@linaro.org>
    Cc: Sergey Ryazanov <ryazanov.s.a@gmail.com>
    Cc: Johannes Berg <johannes@sipsolutions.net>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: Eric Dumazet <edumazet@google.com>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: Paolo Abeni <pabeni@redhat.com>
    Cc: netdev@vger.kernel.org
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>