Bluetooth: MGMT: Use correct address for memcpy()
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit d1f0a9816f5fbc1316355ec1aa4ddfb9b624cca5
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Jul 17 12:32:14 2023 +0300

    Bluetooth: MGMT: Use correct address for memcpy()

    In function ‘fortify_memcpy_chk’,
        inlined from ‘get_conn_info_complete’ at net/bluetooth/mgmt.c:7281:2:
    include/linux/fortify-string.h:592:25: error: call to
    ‘__read_overflow2_field’ declared with attribute warning: detected read
    beyond size of field (2nd parameter); maybe use struct_group()?
    [-Werror=attribute-warning]
      592 |                         __read_overflow2_field(q_size_field, size);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    This is due to the wrong member is used for memcpy(). Use correct one.

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>