tools/testing/selftests/vm: fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Xingxing Su <suxingxing@loongson.cn>
commit d8cbe8bfa7df3c680ddfd5e1eee3a5c86d8dc764
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-408.el8/d8cbe8bf.failed

Only x86 and PowerPC implement the pkey-xxx.h, and an error was reported
when compiling protection_keys.c.

Add a Arch judgment to compile "protection_keys" in the Makefile.

If other arch implement this, add the arch name to the Makefile.
eg:
    ifneq (,$(findstring $(ARCH),powerpc mips ... ))

Following build errors:

    pkey-helpers.h:93:2: error: #error Architecture not supported
     #error Architecture not supported
    pkey-helpers.h:96:20: error: `PKEY_DISABLE_ACCESS' undeclared
     #define PKEY_MASK (PKEY_DISABLE_ACCESS | PKEY_DISABLE_WRITE)
                        ^
    protection_keys.c:218:45: error: `PKEY_DISABLE_WRITE' undeclared
     pkey_assert(flags & (PKEY_DISABLE_ACCESS | PKEY_DISABLE_WRITE));
                                                ^

	Signed-off-by: Xingxing Su <suxingxing@loongson.cn>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Cc: Shuah Khan <shuah@kernel.org>
	Cc: Sandipan Das <sandipan@linux.ibm.com>
	Cc: John Hubbard <jhubbard@nvidia.com>
	Cc: Dave Hansen <dave.hansen@intel.com>
	Cc: "Kirill A. Shutemov" <kirill.shutemov@linux.intel.com>
	Cc: Brian Geffon <bgeffon@google.com>
	Cc: Mina Almasry <almasrymina@google.com>
Link: https://lkml.kernel.org/r/1606826876-30656-1-git-send-email-suxingxing@loongson.cn
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit d8cbe8bfa7df3c680ddfd5e1eee3a5c86d8dc764)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/vm/Makefile