vdpa: mlx5: fix vdpa/vhost dependencies
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 98701a2a861fa87a5055cf2809758e8725e8b146

drivers/vdpa/mlx5/ uses vhost_iotlb*() interfaces, so select
VHOST_IOTLB to make them be built.

However, if VHOST_IOTLB is the only VHOST symbol that is
set/enabled, the object file still won't be built because
drivers/Makefile won't descend into drivers/vhost/ to build it,
so make drivers/Makefile build the needed binary whenever
VHOST_IOTLB is set, like it does for VHOST_RING.

Fixes these build errors:
ERROR: modpost: "vhost_iotlb_itree_next" [drivers/vdpa/mlx5/mlx5_vdpa.ko] undefined!
ERROR: modpost: "vhost_iotlb_itree_first" [drivers/vdpa/mlx5/mlx5_vdpa.ko] undefined!

Fixes: 29064bfdabd5 ("vdpa/mlx5: Add support library for mlx5 VDPA implementation")
Fixes: aff90770e54c ("vdpa/mlx5: Fix dependency on MLX5_CORE")
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Eli Cohen <eli@mellanox.com>
	Cc: Parav Pandit <parav@mellanox.com>
	Cc: "Michael S. Tsirkin" <mst@redhat.com>
	Cc: Jason Wang <jasowang@redhat.com>
	Cc: virtualization@lists.linux-foundation.org
	Cc: Saeed Mahameed <saeedm@nvidia.com>
	Cc: Leon Romanovsky <leonro@nvidia.com>
	Cc: netdev@vger.kernel.org
Link: https://lore.kernel.org/r/20201128213905.27409-1-rdunlap@infradead.org
	Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
	Acked-by: Jason Wang <jasowang@redhat.com>
(cherry picked from commit 98701a2a861fa87a5055cf2809758e8725e8b146)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>