raw: Fix mixed declarations error in raw_icmp_error().
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2138802
Upstream Status: linux.git

commit 5da39e31b1b0eb62b8ed369ad9615da850239e9e
Author: Kuniyuki Iwashima <kuniyu@amazon.com>
Date:   Sun Jun 19 16:29:26 2022 -0700

    raw: Fix mixed declarations error in raw_icmp_error().

    The trailing semicolon causes a compiler error, so let's remove it.

    net/ipv4/raw.c: In function ‘raw_icmp_error’:
    net/ipv4/raw.c:266:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
      266 |  struct hlist_nulls_head *hlist;
          |  ^~~~~~

    Fixes: ba44f8182ec2 ("raw: use more conventional iterators")
    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Guillaume Nault <gnault@redhat.com>