tpm: atmel: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 8edd49ce8da7b5c24e751c41e6bb882424b47fc5
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:22 2023 -0500

    tpm: atmel: Add explicit include for of.h

    With linux/acpi.h (in linux/tpm.h) no longer implicitly including of.h,
    add an explicit include of of.h to fix the following errors:

    drivers/char/tpm/tpm_atmel.h:50:14: error: implicit declaration of function 'of_find_node_by_name'; did you mean 'bus_find_device_by_name'? [-Werror=implicit-function-declaration]
    drivers/char/tpm/tpm_atmel.h:50:12: error: assignment to 'struct device_node *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
    drivers/char/tpm/tpm_atmel.h:55:14: error: implicit declaration of function 'of_device_is_compatible'; did you mean 'fwnode_device_is_compatible'? [-Werror=implicit-function-declaration]
    ...

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>