wifi: wilc1000: avoid buffer overflow in WID string configuration
JIRA: https://issues.redhat.com/browse/RHEL-114891
CVE: CVE-2025-39952

commit fe9e4d0c39311d0f97b024147a0d155333f388b5
Author: Ajay.Kathat@microchip.com <Ajay.Kathat@microchip.com>
Date:   Fri Aug 29 22:58:43 2025 +0000

    wifi: wilc1000: avoid buffer overflow in WID string configuration
    
    Fix the following copy overflow warning identified by Smatch checker.
    
     drivers/net/wireless/microchip/wilc1000/wlan_cfg.c:184 wilc_wlan_parse_response_frame()
            error: '__memcpy()' 'cfg->s[i]->str' copy overflow (512 vs 65537)
    
    This patch introduces size check before accessing the memory buffer.
    The checks are base on the WID type of received data from the firmware.
    For WID string configuration, the size limit is determined by individual
    element size in 'struct wilc_cfg_str_vals' that is maintained in 'len' field
    of 'struct wilc_cfg_str'.
    
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/linux-wireless/aLFbr9Yu9j_TQTey@stanley.mountain
    Suggested-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Ajay Singh <ajay.kathat@microchip.com>
    Link: https://patch.msgid.link/20250829225829.5423-1-ajay.kathat@microchip.com
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>