tools/testing/cxl: Use DEFINE_STATIC_SRCU()
JIRA: https://issues.redhat.com/browse/RHEL-5228

commit 270205be711056534d1f86d275d4ec922fb62102
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Fri, 12 May 2023 14:31:35 -0700

    tools/testing/cxl: Use DEFINE_STATIC_SRCU()

    Starting with commit:

    95433f726301 ("srcu: Begin offloading srcu_struct fields to srcu_update")

    ...it is no longer possible to do:

    static DEFINE_SRCU(x)

    Switch to DEFINE_STATIC_SRCU(x) to fix:

    tools/testing/cxl/test/mock.c:22:1: error: duplicate ‘static’
       22 | static DEFINE_SRCU(cxl_mock_srcu);
          | ^~~~~~

    Reviewed-by: Dave Jiang <dave.jiang@intel.com>
    Link: https://lore.kernel.org/r/168392709546.1135523.10424917245934547117.stgit@dwillia2-xfh.jf.intel.com
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Waiman Long <longman@redhat.com>