Bluetooth: btmtk: hide unused btmtk_mt6639_devs[] array
JIRA: https://issues.redhat.com/browse/RHEL-184635

commit 81f971c6abec59240e2bcfc38756bda8172fa788
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Apr 2 16:11:15 2026 +0200

    Bluetooth: btmtk: hide unused btmtk_mt6639_devs[] array

    When USB support is disabled, the array is not referenced anywhere,
    causing a warning:

    drivers/bluetooth/btmtk.c:35:3: error: 'btmtk_mt6639_devs' defined but not used [-Werror=unused-const-variable=]
       35 | } btmtk_mt6639_devs[] = {
          |   ^~~~~~~~~~~~~~~~~

    Move it into the #ifdef block.

    Fixes: 28b7c5a6db74 ("Bluetooth: btmtk: Add MT6639 (MT7927) Bluetooth support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Paul Menzel <pmenzel@molgen.mpg.de>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: David Marlin <dmarlin@redhat.com>