dmaengine: ti: edma: remove unused edma_and function
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit 3366c6fe2769fe653107626b3273e03156d9cac8
Author: Tom Rix <trix@redhat.com>
Date:   Mon Mar 20 19:12:09 2023 -0400

    dmaengine: ti: edma: remove unused edma_and function

    clang with W=1 reports
    drivers/dma/ti/edma.c:321:20: error: unused function
      'edma_and' [-Werror,-Wunused-function]
    static inline void edma_and(struct edma_cc *ecc, int offset, unsigned and)
                       ^
    This function is not used, so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230320231209.1728940-1-trix@redhat.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>