ice: dpll: Fix compilation warning
JIRA: https://redhat.atlassian.net/browse/RHEL-187013

commit 586483cb41f40eab03ca65ceedeae623b379783a
Author: Przemyslaw Korba <przemyslaw.korba@intel.com>
Date:   Thu Apr 30 23:37:24 2026 -0700

    ice: dpll: Fix compilation warning

    Introduced by commit ad1df4f2d591 ("ice: dpll: Support E825-C SyncE and
    dynamic pin discovery"):

    ice_dpll.c: In function ‘ice_dpll_init’:
    ice_dpll.c:3588:59: error: ‘%u’ directive output may be truncated
    writing between 1 and 10 bytes into a region of size 4
    [-Werror=format-truncation=] snprintf(pin_name, sizeof(pin_name),
    "rclk%u", i);

    Reviewed-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Signed-off-by: Przemyslaw Korba <przemyslaw.korba@intel.com>
    Reviewed-by: Aleksandr Loktionov <aleksandr.loktionov@intel.com>
    Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
    Link: https://patch.msgid.link/20260430-jk-iwl-net-next-2026-04-30-v1-13-6f27ae1cd073@intel.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>