crash_dump, nvme: select CONFIGFS_FS as built-in
JIRA: https://issues.redhat.com/browse/RHEL-104939

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 4496e1c1354bd4837bcc1414f6e1a4d042857903
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 21 18:03:19 2025 +0200

    crash_dump, nvme: select CONFIGFS_FS as built-in

    Configfs can be configured as a loadable module, which causes a link-time
    failure for dm-crypt crash dump support:

    crash_dump_dm_crypt.c:(.text+0x3a4): undefined reference to `config_item_init_type_name'
    aarch64-linux-ld: kernel/crash_dump_dm_crypt.o: in function `configfs_dmcrypt_keys_init':
    crash_dump_dm_crypt.c:(.init.text+0x90): undefined reference to `config_group_init'
    aarch64-linux-ld: crash_dump_dm_crypt.c:(.init.text+0xb4): undefined reference to `configfs_register_subsystem'
    aarch64-linux-ld: crash_dump_dm_crypt.c:(.init.text+0xd8): undefined reference to `configfs_unregister_subsystem'

    This could be avoided with a dependency on CONFIGFS_FS=y, but the
    dependency has an additional problem of causing Kconfig dependency loops
    since most other uses select the symbol.

    Using a simple 'select CONFIGFS_FS' here in turn fails with
    CONFIG_DM_CRYPT=m, because that still only causes configfs to be a
    loadable module.

    The only version I found that fixes this reliably uses an additional
    Kconfig symbol to ensure the 'select' actually turns on configfs as
    builtin, with two additional changes to avoid dependency loops with nvme
    and sysfs.

    There is no compile-time dependency between configfs and sysfs, so
    selecting configfs from a driver with sysfs disabled does not cause link
    failures, only the default /sys/kernel/config mount point will not be
    created.

    Link: https://lkml.kernel.org/r/20250521160359.2132363-1-arnd@kernel.org
    Fixes: 6b23858fd63b ("crash_dump: make dm crypt keys persist for the kdump kernel")
    Fixes: 1fb470408497 ("nvme-loop: add configfs dependency")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Andreas Hindborg <a.hindborg@kernel.org>
    Cc: Breno Leitao <leitao@debian.org>
    Cc: Chaitanya Kulkarni <kch@nvidia.com>
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Coiby Xu <coxu@redhat.com>
    Cc: Jens Axboe <axboe@kernel.dk>
    Cc: Sagi Grimberg <sagi@grimberg.me>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Coiby Xu <coxu@redhat.com>