dm raid: remove unused d variable
Bugzilla: https://bugzilla.redhat.com/2189971
Upstream Status: kernel/git/torvalds/linux.git

commit 306fbc2e041c227be7c934efe8a49ddb87bd31f1
Author: Tom Rix <trix@redhat.com>
Date:   Thu Mar 30 17:27:53 2023 -0400

    dm raid: remove unused d variable

    clang with W=1 reports
    drivers/md/dm-raid.c:2212:15: error: variable
      'd' set but not used [-Werror,-Wunused-but-set-variable]
            unsigned int d;
                         ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Signed-off-by: Mike Snitzer <snitzer@kernel.org>

Signed-off-by: Benjamin Marzinski <bmarzins@redhat.com>