s390/test_unwind: use raw opcode instead of invalid instruction
Bugzilla: https://bugzilla.redhat.com/2120352

commit 53ae7230918154d1f4281d7aa3aae9650436eadf
Author: Ilie Halip <ilie.halip@gmail.com>
Date:   Wed Nov 17 19:48:21 2021 +0200

    s390/test_unwind: use raw opcode instead of invalid instruction

    Building with clang & LLVM_IAS=1 leads to an error:
        arch/s390/lib/test_unwind.c:179:4: error: invalid register pair
                            "       mvcl    %%r1,%%r1\n"
                            ^

    The test creates an invalid instruction that would trap at runtime, but the
    LLVM inline assembler tries to validate it at compile time too.

    Use the raw instruction opcode instead.

    Reported-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Ilie Halip <ilie.halip@gmail.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Suggested-by: Ulrich Weigand <Ulrich.Weigand@de.ibm.com>
    Link: https://github.com/ClangBuiltLinux/linux/issues/1421
    Link: https://lore.kernel.org/r/20211117174822.3632412-1-ilie.halip@gmail.com
    Reviewed-by: Christian Borntraeger <borntraeger@de.ibm.com>
    Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>
    [hca@linux.ibm.com: use illegal opcode, and update comment]
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>