bpf: Fix bpftool without skeleton code enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author John Fastabend <john.fastabend@gmail.com>
commit 8ae4121bd89e3dce27b519ed469efbc15423af18

Fix segfault from bpftool by adding emit_obj_refs_plain when skeleton
code is disabled.

Tested by deleting BUILD_BPF_SKELS in Makefile. We found this doing
backports for Cilium when a testing image pulled in latest bpf-next
bpftool, but kept using an older clang-7.

  # ./bpftool prog show
  Error: bpftool built without PID iterator support
  3: cgroup_skb  tag 7be49e3934a125ba  gpl
          loaded_at 2020-07-01T08:01:29-0700  uid 0
  Segmentation fault

Fixes: d53dee3fe013 ("tools/bpftool: Show info for processes holding BPF map/prog/link/btf FDs")
	Reported-by: Joe Stringer <joe@wand.net.nz>
	Signed-off-by: John Fastabend <john.fastabend@gmail.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Acked-by: Yonghong Song <yhs@fb.com>
Link: https://lore.kernel.org/bpf/159375071997.14984.17404504293832961401.stgit@john-XPS-13-9370
(cherry picked from commit 8ae4121bd89e3dce27b519ed469efbc15423af18)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>