sched/headers: ARM needs asm/paravirt_api_clock.h too
Bugzilla: http://bugzilla.redhat.com/2069275

commit ffea9fb319360b9ead8befac6bb2db2b54fd53e6
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Mar 16 13:41:46 2022 -0700

    sched/headers: ARM needs asm/paravirt_api_clock.h too

    Add <asm/paravirt_api_clock.h> for arch/arm/, mapped to <asm/paravirt.h>,
    to simplify #ifdeffery in generic code.

    Fixes this build error introduced by the scheduler tree:

      In file included from ../kernel/sched/core.c:81:
      ../kernel/sched/sched.h:87:11: fatal error: asm/paravirt_api_clock.h: No such file or directory
         87 | # include <asm/paravirt_api_clock.h>

    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Fixes: 4ff8f2ca6ccd ("sched/headers: Reorganize, clean up and optimize kernel/sched/sched.h dependencies")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20220316204146.14000-1-rdunlap@infradead.org

Signed-off-by: Phil Auld <pauld@redhat.com>