mlx5: avoid truncating error message
JIRA: https://issues.redhat.com/browse/RHEL-45365
Upstream-status: v6.10-rc1

commit b324a960354b872431d25959ad384ab66a7116ec
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 26 23:38:03 2024 +0100

    mlx5: avoid truncating error message

    clang warns that one error message is too long for its destination buffer:

    drivers/net/ethernet/mellanox/mlx5/core/esw/bridge.c:1876:4: error: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 94 [-Werror,-Wformat-truncation-non-kprintf]

    Reword it to be a bit shorter so it always fits.

    Fixes: 70f0302b3f20 ("net/mlx5: Bridge, implement mdb offload")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Subbaraya Sundeep <sbhatta@marvell.com>
    Link: https://lore.kernel.org/r/20240326223825.4084412-5-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@redhat.com>