selftests/bpf: Fix build error with llvm 19
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit 608e99f7869e3a6e028c7cba14a896c7797e8746
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Sat Nov 16 10:56:17 2024 -0800

    selftests/bpf: Fix build error with llvm 19

    llvm 19 fails to compile arena self test:
    CLNG-BPF [test_progs] verifier_arena_large.bpf.o
    progs/verifier_arena_large.c:90:24: error: unsupported signed division, please convert to unsigned div/mod.
       90 |                 pg_idx = (pg - base) / PAGE_SIZE;

    Though llvm <= 18 and llvm >= 20 don't have this issue,
    fix the test to avoid the build error.

    Reported-by: Jiri Olsa <olsajiri@gmail.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>