ASoC: SOF: Intel: hda-sdw-bpt: select SND_SOF_SOF_HDA_SDW_BPT properly
JIRA: https://issues.redhat.com/browse/RHEL-193254

commit 999ec4c29d73ac85b639a31bbc85ad2ec00eb9d7
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Jun 11 15:23:06 2026 +0200

    ASoC: SOF: Intel: hda-sdw-bpt: select SND_SOF_SOF_HDA_SDW_BPT properly

    When SND_SOC_SOF_INTEL_LNL is set, SND_SOF_SOF_HDA_SDW_BPT must also
    be enabled, in order to let the soundwire support call into it.

    However, there are configurations with SND_SOF_SOF_HDA_SDW_BPT=m
    and SND_SOF_SOF_HDA_SDW_BPT=m but SOUNDWIRE_INTEL=y, which still
    lead to a link failure:

    aarch64-linux-ld: drivers/soundwire/intel_ace2x.o: in function `intel_ace2x_bpt_wait':
    intel_ace2x.c:(.text+0xfc8): undefined reference to `hda_sdw_bpt_wait'
    aarch64-linux-ld: drivers/soundwire/intel_ace2x.o: in function `intel_ace2x_bpt_send_async':
    intel_ace2x.c:(.text+0x1ff8): undefined reference to `hda_sdw_bpt_get_buf_size_alignment'

    Address this by moving the 'select SND_SOF_SOF_HDA_SDW_BPT' into
    SND_SOC_SOF_HDA_GENERIC.

    Fixes: 614d416dd8ae ("ASoC: SOF: Intel: hda-sdw-bpt: fix SND_SOF_SOF_HDA_SDW_BPT dependencies")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260611132310.137688-2-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>