IB/rdmavt: Validate remote_addr during loopback atomic tests
Bugzilla: http://bugzilla.redhat.com/2032114
Upstream status: rdma/for-rc

commit 4028bccb003cf67e46632dee7f97ddc5d7b6e685
Author: Mike Marciniszyn <mike.marciniszyn@cornelisnetworks.com>
Date:   Wed Jan 19 04:28:09 2022 -0500

    IB/rdmavt: Validate remote_addr during loopback atomic tests

    The rdma-core test suite sends an unaligned remote address and expects a
    failure.

    ERROR: test_atomic_non_aligned_addr (tests.test_atomic.AtomicTest)

    The qib/hfi1 rc handling validates properly, but the test has the client
    and server on the same system.

    The loopback of these operations is a distinct code path.

    Fix by syntaxing the proposed remote address in the loopback code path.

    Fixes: 15703461533a ("IB/{hfi1, qib, rdmavt}: Move ruc_loopback to rdmavt")
    Link: https://lore.kernel.org/r/1642584489-141005-1-git-send-email-mike.marciniszyn@cornelisnetworks.com
    Reviewed-by: Dennis Dalessandro <dennis.dalessandro@cornelisnetworks.com>
    Signed-off-by: Mike Marciniszyn <mike.marciniszyn@cornelisnetworks.com>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>