IB/mlx4: Potential buffer overflow in _mlx4_set_path()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 54a6d63f14bdb4e899bbb4128d32717074d13862

Smatch complains about this code:

    drivers/infiniband/hw/mlx4/qp.c:1827 _mlx4_set_path()
    error: buffer overflow 'dev->dev->caps.gid_table_len' 3 <= 255

The mlx4_ib_gid_index_to_real_index() does check that "port" is within
bounds, but we don't check the return value for errors.  It seems simple
enough to add a check for that.

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 54a6d63f14bdb4e899bbb4128d32717074d13862)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>