scsi: target: core: Remove unused 'prod_len' variable
JIRA: https://issues.redhat.com/browse/RHEL-5751

clang with W=1 reports:

drivers/target/target_core_spc.c:229:6: error: variable
  'prod_len' set but not used [-Werror,-Wunused-but-set-variable]
        u32 prod_len;
            ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230329132421.1809362-1-trix@redhat.com
Reviewed-by: Chaitanya Kulkarni <kch@nvidia.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit aa4d7812cf2cb0847e027d0e2a124926eea9d4fb)
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>