qed: remove unused 'resp_size' calculation
JIRA: https://issues.redhat.com/browse/RHEL-52263

commit 7a456b894ea57cceee6951ce421205152f23a051
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Aug 14 09:45:03 2023 +0200

    qed: remove unused 'resp_size' calculation

    Newer versions of clang warn about this variable being assigned but
    never used:

    drivers/net/ethernet/qlogic/qed/qed_vf.c:63:67: error: parameter 'resp_size' set but not used [-Werror,-Wunused-but-set-parameter]

    There is no indication in the git history on how this was ever
    meant to be used, so just remove the entire calculation and argument
    passing for it to avoid the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Leon Romanovsky <leonro@nvidia.com>
    Link: https://lore.kernel.org/r/20230814074512.1067715-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>