perf probe: Support escaped character in parser
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit c588d158124d5b60184fc612e551a19720720d68
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1062.el7/c588d158.failed

Support the special characters escaped by '\' in parser.  This allows
user to specify versions directly like below.

  =====
  # ./perf probe -x /lib64/libc-2.25.so malloc_get_state\\@GLIBC_2.2.5
  Added new event:
    probe_libc:malloc_get_state (on malloc_get_state@GLIBC_2.2.5 in /usr/lib64/libc-2.25.so)

  You can now use it in all perf tools, such as:

	  perf record -e probe_libc:malloc_get_state -aR sleep 1

  =====

Or, you can use separators in source filename, e.g.

  =====
  # ./perf probe -x /opt/test/a.out foo+bar.c:3
  Semantic error :There is non-digit character in offset.
    Error: Command Parse Error.
  =====

Usually "+" in source file cause parser error, but

  =====
  # ./perf probe -x /opt/test/a.out foo\\+bar.c:4
  Added new event:
    probe_a:main         (on @foo+bar.c:4 in /opt/test/a.out)

  You can now use it in all perf tools, such as:

	  perf record -e probe_a:main -aR sleep 1
  =====

escaped "\+" allows you to specify that.

	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Reviewed-by: Thomas Richter <tmricht@linux.vnet.ibm.com>
	Acked-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: bhargavb <bhargavaramudu@gmail.com>
	Cc: linux-rt-users@vger.kernel.org
Link: http://lkml.kernel.org/r/151309111236.18107.5634753157435343410.stgit@devbox
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit c588d158124d5b60184fc612e551a19720720d68)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/perf/Documentation/perf-probe.txt