mmc: sdhci-omap: Remove forward declaration of sdhci_omap_context_save()
JIRA: https://issues.redhat.com/browse/RHEL-41085

commit b3e202fa0f9a20995eb8e1efbc0bf4a67616965e
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Oct 20 10:39:02 2021 +0200

    mmc: sdhci-omap: Remove forward declaration of sdhci_omap_context_save()

    If CONFIG_PM_SLEEP=n:

        drivers/mmc/host/sdhci-omap.c:1213:13: error: ‘sdhci_omap_context_save’ declared ‘static’ but never defined [-Werror=unused-function]
         1213 | static void sdhci_omap_context_save(struct sdhci_omap_host *omap_host);
              |             ^~~~~~~~~~~~~~~~~~~~~~~

    The referenced commit added an unrelated forward declaration of
    sdhci_omap_context_save(), which is unneeded in general, and unused when
    CONFIG_PM_SLEEP=n.

    Fixes: f433e8aac6b94218 ("mmc: sdhci-omap: Implement PM runtime functions")
    Reported-by: noreply@ellerman.id.au
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Link: https://lore.kernel.org/r/20211020083902.3669769-1-geert@linux-m68k.org
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>