mdio_bus: fix devm_mdiobus_alloc_size export
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 93dccc59165ad1b4db94528dfdf88bff92c09cef
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-693.el7/93dccc59.failed

commit 6d48f44b7b2 "mdio_bus: implement devm_mdiobus_alloc/devm_mdiobus_free"
introduced a new function devm_mdiobus_alloc_size() but added an export
for a different function devm_mdiobus_alloc(), which was obviously
a simple mistake that leads to  build error whenever this function is
used from a loadable module:

ERROR: "devm_mdiobus_alloc_size" [drivers/net/ethernet/ti/davinci_mdio.ko] undefined!

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Cc: Grygorii Strashko <grygorii.strashko@ti.com>
	Cc: Florian Fainelli <f.fainelli@gmail.com>
	Cc: Sergei Shtylyov <sergei.shtylyov@cogentembedded.com>
	Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
	Cc: David S. Miller <davem@davemloft.net>
	Cc: netdev@vger.kernel.org
	Acked-by: Lad, Prabhakar <prabhakar.csengg@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 93dccc59165ad1b4db94528dfdf88bff92c09cef)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/phy/mdio_bus.c