ASoC: SOF: amd: Fixed Build error
Add linux/module.h in acp-pci.c to solve the below dependency

All error/warnings (new ones prefixed by >>):

>> sound/soc/amd/acp/acp-pci.c:148:1: warning: data definition has no type or storage class
148 | MODULE_DEVICE_TABLE(pci, acp_pci_ids);
| ^~~~~~~~~~~~~~~~~~~
>> sound/soc/amd/acp/acp-pci.c:148:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
...

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Syed Saba Kareem<ssabakar@amd.com>
    Link: https://lore.kernel.org/r/20220523112956.3087604-1-ssabakar@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Syed Saba kareem <ssabakar@amd.com>
Date: Mon May 23 16:59:53 2022 +0530

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 803a1f7272797faa15a7879cdc70f9adaf3fdcba)
Bugzilla: https://bugzilla.redhat.com/2065578