net: wwan: iosm: select CONFIG_RELAY
Bugzilla: https://bugzilla.redhat.com/2123542

commit 5382911f5d67a5a13815fb6958265b4a11ff7cfd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sat Dec 4 18:40:25 2021 +0100

    net: wwan: iosm: select CONFIG_RELAY
    
    The iosm driver started using relayfs, but is missing the Kconfig
    logic to ensure it's built into the kernel:
    
    x86_64-linux-ld: drivers/net/wwan/iosm/iosm_ipc_trace.o: in function `ipc_trace_create_buf_file_handler':
    iosm_ipc_trace.c:(.text+0x16): undefined reference to `relay_file_operations'
    x86_64-linux-ld: drivers/net/wwan/iosm/iosm_ipc_trace.o: in function `ipc_trace_subbuf_start_handler':
    iosm_ipc_trace.c:(.text+0x31): undefined reference to `relay_buf_full'
    x86_64-linux-ld: drivers/net/wwan/iosm/iosm_ipc_trace.o: in function `ipc_trace_ctrl_file_write':
    iosm_ipc_trace.c:(.text+0xd5): undefined reference to `relay_flush'
    x86_64-linux-ld: drivers/net/wwan/iosm/iosm_ipc_trace.o: in function `ipc_trace_port_rx':
    
    Fixes: 00ef32565b9b ("net: wwan: iosm: device trace collection using relayfs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Sergey Ryazanov <ryazanov.s.a@gmail.com>
    Reviewed-by: M Chetan Kumar <m.chetan.kumar@linux.intel.com>
    Link: https://lore.kernel.org/r/20211204174033.950528-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>