power: supply: core: Move psy_has_property() to fix build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071846
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set updates the
 power subsystem.  This set has been tested via simple boot tests and
 the CI loop.

commit 5ce39985c60418579fab1d4ee81427d12bf9e64f
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Tue Sep 28 14:00:19 2021 +0200

    power: supply: core: Move psy_has_property() to fix build

    If CONFIG_THERMAL=n:

        drivers/power/supply/power_supply_core.c: In function ‘__power_supply_register’:
        drivers/power/supply/power_supply_core.c:1137:6: error: implicit declaration of function ‘psy_has_property’ [-Werror=implicit-function-declaration]
         1137 |  if (psy_has_property(desc, POWER_SUPPLY_PROP_USB_TYPE) &&
              |      ^~~~~~~~~~~~~~~~

    Fix this by moving psy_has_property() outside the section protected by
    CONFIG_THERMAL.

    Fixes: 9ba533eb99bb2acf ("power: supply: core: Add psy_has_property()")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Reviewed-by: Matthias Kaehlcke <mka@chromium.org>
    Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>
    (cherry picked from commit 5ce39985c60418579fab1d4ee81427d12bf9e64f)

Signed-off-by: Al Stone <ahs3@redhat.com>