usb: typec: rt1719: Fix build error without CONFIG_POWER_SUPPLY
Bugzilla: http://bugzilla.redhat.com/2084667
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46653455
Tested: HP ZBook 15 G5/80D5 Laptop

commit 9e3d68f872e4f5ce40dcc5baba7e37ab7961ed74
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Mon Apr 18 16:24:25 2022 +0800

    usb: typec: rt1719: Fix build error without CONFIG_POWER_SUPPLY

    Building without CONFIG_POWER_SUPPLY will fail:

    drivers/usb/typec/rt1719.o: In function `rt1719_psy_set_property':
    rt1719.c:(.text+0x10a): undefined reference to `power_supply_get_drvdata'
    drivers/usb/typec/rt1719.o: In function `rt1719_psy_get_property':
    rt1719.c:(.text+0x2c8): undefined reference to `power_supply_get_drvdata'
    drivers/usb/typec/rt1719.o: In function `devm_rt1719_psy_register':
    rt1719.c:(.text+0x3e9): undefined reference to `devm_power_supply_register'
    drivers/usb/typec/rt1719.o: In function `rt1719_irq_handler':
    rt1719.c:(.text+0xf9f): undefined reference to `power_supply_changed'
    drivers/usb/typec/rt1719.o: In function `rt1719_update_pwr_opmode.part.9':
    rt1719.c:(.text+0x657): undefined reference to `power_supply_changed'
    drivers/usb/typec/rt1719.o: In function `rt1719_attach':
    rt1719.c:(.text+0x83e): undefined reference to `power_supply_changed'

    Add POWER_SUPPLY dependency to Kconfig.

    Fixes: 25d29b980912 ("usb: typec: rt1719: Add support for Richtek RT1719")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Reviewed-by: ChiYuan Huang <cy_huang@richtek.com>
    Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Link: https://lore.kernel.org/r/20220418082425.41566-1-renzhijie2@huawei.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>