powerpc/papr_scm: Fix build failure when
Bugzilla: http://bugzilla.redhat.com/1873830

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45652052

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/

Tested by Kajol Jain <kjain101@in.ibm.com>

commit d0007eb15c2a8113e847143c783ea83d93963741
Author: Kajol Jain <kjain@linux.ibm.com>
Date:   Wed Mar 23 22:15:50 2022 +0530

    powerpc/papr_scm: Fix build failure when

    The following build failure occurs when CONFIG_PERF_EVENTS is not set
    as generic pmu functions are not visible in that scenario.

    arch/powerpc/platforms/pseries/papr_scm.c:372:35: error: ‘struct perf_event’ has no member named ‘attr’
             p->nvdimm_events_map[event->attr.config],
                                       ^~
    In file included from ./include/linux/list.h:5,
                     from ./include/linux/kobject.h:19,
                     from ./include/linux/of.h:17,
                     from arch/powerpc/platforms/pseries/papr_scm.c:5:
    arch/powerpc/platforms/pseries/papr_scm.c: In function ‘papr_scm_pmu_event_init’:
    arch/powerpc/platforms/pseries/papr_scm.c:389:49: error: ‘struct perf_event’ has no member named ‘pmu’
      struct nvdimm_pmu *nd_pmu = to_nvdimm_pmu(event->pmu);
                                                     ^~
    ./include/linux/container_of.h:18:26: note: in definition of macro ‘container_of’
      void *__mptr = (void *)(ptr);     \
                              ^~~
    arch/powerpc/platforms/pseries/papr_scm.c:389:30: note: in expansion of macro ‘to_nvdimm_pmu’
      struct nvdimm_pmu *nd_pmu = to_nvdimm_pmu(event->pmu);
                                  ^~~~~~~~~~~~~
    In file included from ./include/linux/bits.h:22,
                     from ./include/linux/bitops.h:6,
                     from ./include/linux/of.h:15,
                     from arch/powerpc/platforms/pseries/papr_scm.c:5:

    Fix the build issue by adding check for CONFIG_PERF_EVENTS config option
    and also add stub function for papr_scm_pmu_register to handle
    the CONFIG_PERF_EVENTS=n case. Also move the position of macro
    "to_nvdimm_pmu" inorder to merge it in CONFIG_PERF_EVENTS=y block.

    based on libnvdimm-for-next tree)

    Fixes: 4c08d4bbc089 ("powerpc/papr_scm: Add perf interface support") (Commit id
    Signed-off-by: Kajol Jain <kjain@linux.ibm.com>
    Link: https://lore.kernel.org/r/20220323164550.109768-2-kjain@linux.ibm.com
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
    Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>

Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>