perf lock contention: Fix a build error on 32-bit
JIRA: https://issues.redhat.com/browse/RHEL-25824

upstream
========
commit 29b8e94dcf2575c17541f843741ee96691ff1ded
Author: Yang Jihong <yangjihong1@huawei.com>
Date: Sat Nov 18 02:48:57 2023 +0000

description
===========
Fix a build error on 32-bit system:

  util/bpf_lock_contention.c: In function 'lock_contention_get_name':
  util/bpf_lock_contention.c:253:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'u64 {aka long long unsigned int}' [-Werror=format=]
     snprintf(name_buf, sizeof(name_buf), "cgroup:%lu", cgrp_id);
                                                  ~~^
                                                  %llu
  cc1: all warnings being treated as errors

Fixes: d0c502e46e97 ("perf lock contention: Prepare to handle cgroups")
    Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
    Acked-by: Namhyung Kim <namhyung@kernel.org>
    Cc: avagin@google.com
    Cc: daniel.diaz@linaro.org
    Link: https://lore.kernel.org/r/20231118024858.1567039-3-yangjihong1@huawei.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>