drm/panel: novatek-nt35560: avoid on-stack device structure
JIRA: https://issues.redhat.com/browse/RHEL-142315

commit 0accacccba1943a32986b95225607f1994b0d26d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 4 10:45:45 2025 +0100

    drm/panel: novatek-nt35560: avoid on-stack device structure

    [ Upstream commit 1a7a7b80a22448dff55e1ad69a4681fd8b760b85 ]

    A cleanup patch apparently by accident used a local device structure
    instead of a pointer to one in the nt35560_read_id() function, causing
    a warning about stack usage:

    drivers/gpu/drm/panel/panel-novatek-nt35560.c: In function 'nt35560_read_id':
    drivers/gpu/drm/panel/panel-novatek-nt35560.c:249:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

    Change this to a pointer as was liley intended here.

    Fixes: 5fbc0dbb92d6 ("drm/panel: novatek-nt35560: Clean up driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Douglas Anderson <dianders@chromium.org>
    Signed-off-by: Douglas Anderson <dianders@chromium.org>
    Link: https://patch.msgid.link/20251204094550.1030506-1-arnd@kernel.org
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Anusha Srivatsa <asrivats@redhat.com>