netfilter: nf_tables: Only use nf_skip_indirect_calls() when MITIGATION_RETPOLINE
JIRA: https://redhat.atlassian.net/browse/RHEL-168848
Upstream Status: commit e3a4182edd1a

commit e3a4182edd1ae60e7e3539ff3b3784af9830d223
Author: WangYuli <wangyuli@uniontech.com>
Date:   Wed Mar 19 22:01:47 2025 +0800

    netfilter: nf_tables: Only use nf_skip_indirect_calls() when MITIGATION_RETPOLINE

    1. MITIGATION_RETPOLINE is x86-only (defined in arch/x86/Kconfig),
    so no need to AND with CONFIG_X86 when checking if enabled.

    2. Remove unused declaration of nf_skip_indirect_calls() when
    MITIGATION_RETPOLINE is disabled to avoid warnings.

    3. Declare nf_skip_indirect_calls() and nf_skip_indirect_calls_enable()
    as inline when MITIGATION_RETPOLINE is enabled, as they are called
    only once and have simple logic.

    Fix follow error with clang-21 when W=1e:
      net/netfilter/nf_tables_core.c:39:20: error: unused function 'nf_skip_indirect_calls' [-Werror,-Wunused-function]
         39 | static inline bool nf_skip_indirect_calls(void) { return false; }
            |                    ^~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      make[4]: *** [scripts/Makefile.build:207: net/netfilter/nf_tables_core.o] Error 1
      make[3]: *** [scripts/Makefile.build:465: net/netfilter] Error 2
      make[3]: *** Waiting for unfinished jobs....

    Fixes: d8d760627855 ("netfilter: nf_tables: add static key to skip retpoline workarounds")
    Co-developed-by: Wentao Guan <guanwentao@uniontech.com>
    Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
    Signed-off-by: WangYuli <wangyuli@uniontech.com>
    Acked-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>