KEYS: Create static version of public_key_verify_signature
Bugzilla: https://bugzilla.redhat.com/2055205

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-tpmdd.git

commit 7f8da9915fcc6386edf86471bf31e162845930a4
Author: Eric Snowberg <eric.snowberg@oracle.com>
Date:   Thu Mar 2 11:46:47 2023 -0500

    KEYS: Create static version of public_key_verify_signature

    The kernel test robot reports undefined reference to
    public_key_verify_signature when CONFIG_ASYMMETRIC_PUBLIC_KEY_SUBTYPE is
    not defined. Create a static version in this case and return -EINVAL.

    Fixes: db6c43bd2132 ("crypto: KEYS: convert public key and digsig asym to the akcipher api")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Eric Snowberg <eric.snowberg@oracle.com>
    Reviewed-by: Mimi Zohar <zohar@linux.ibm.com>
    Reviewed-by: Petr Vorel <pvorel@suse.cz>
    Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
    Tested-by: Mimi Zohar <zohar@linux.ibm.com>
    Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>

Signed-off-by: Coiby Xu <coxu@redhat.com>