sparc: Unbreak the build
Bugzilla: https://bugzilla.redhat.com/2159468

commit 17006e86a7641fa3c50324cfb602f0e74dac8527
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Tue Aug 30 13:58:42 2022 -0700

    sparc: Unbreak the build

    Fix the following build errors:

    arch/sparc/mm/srmmu.c: In function ‘smp_flush_page_for_dma’:
    arch/sparc/mm/srmmu.c:1639:13: error: cast between incompatible function types from ‘void (*)(long unsigned int)’ to ‘void (*)(long unsigned int,  long unsigned int,  long unsigned int,  long unsigned int,  long unsigned int)’ [-Werror=cast-function-type]
     1639 |         xc1((smpfunc_t) local_ops->page_for_dma, page);
          |             ^
    arch/sparc/mm/srmmu.c: In function ‘smp_flush_cache_mm’:
    arch/sparc/mm/srmmu.c:1662:29: error: cast between incompatible function types from ‘void (*)(struct mm_struct *)’ to ‘void (*)(long unsigned int,  long unsigned int,  long unsigned int,  long unsigned int,  long unsigned int)’ [-Werror=cast-function-type]
     1662 |                         xc1((smpfunc_t) local_ops->cache_mm, (unsigned long) mm);
          |
    [ ... ]

    Compile-tested only.

    Fixes: 552a23a0e5d0 ("Makefile: Enable -Wcast-function-type")
    Cc: stable@vger.kernel.org
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Tested-by: Andreas Larsson <andreas@gaisler.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Link: https://lore.kernel.org/r/20220830205854.1918026-1-bvanassche@acm.org

Signed-off-by: Eric Chanudet <echanude@redhat.com>