media: uvcvideo: Fix power line control for a Chicony camera
JIRA: https://issues.redhat.com/browse/RHEL-34114

commit dba3e701917a4cce92920f8ccb9fa4d4ee5ac07e
Author: Ricardo Ribalda <ribalda@chromium.org>
Date: Tue, 5 Sep 2023 17:29:52 +0200

  The device does not implement the control properly.

  Fixes v4l2-compliance error:

  info: checking control 'Power Line Frequency' (0x00980918)
  fail: v4l2-test-controls.cpp(552): could not set valid menu item 3

  Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
  Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>