selftests: mptcp: join: fix 'implicit EP' test
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2109139
Upstream Status: net.git commit c8c101ae390a

commit c8c101ae390a3e817369e94a6f12a1ddea420702
Author: Andrea Claudi <aclaudi@redhat.com>
Date:   Thu Aug 3 18:27:28 2023 +0200

    selftests: mptcp: join: fix 'implicit EP' test

    mptcp_join 'implicit EP' test currently fails when using ip mptcp:

      $ ./mptcp_join.sh -iI
      <snip>
      001 implicit EP    creation[fail] expected '10.0.2.2 10.0.2.2 id 1 implicit' found '10.0.2.2 id 1 rawflags 10 '
      Error: too many addresses or duplicate one: -22.
                         ID change is prevented[fail] expected '10.0.2.2 10.0.2.2 id 1 implicit' found '10.0.2.2 id 1 rawflags 10 '
                         modif is allowed[fail] expected '10.0.2.2 10.0.2.2 id 1 signal' found '10.0.2.2 id 1 signal '

    This happens because of two reasons:
    - iproute v6.3.0 does not support the implicit flag, fixed with
      iproute2-next commit 3a2535a41854 ("mptcp: add support for implicit
      flag")
    - pm_nl_check_endpoint wrongly expects the ip address to be repeated two
      times in iproute output, and does not account for a final whitespace
      in it.

    This fixes the issue trimming the whitespace in the output string and
    removing the double address in the expected string.

    Fixes: 69c6ce7b6eca ("selftests: mptcp: add implicit endpoint test case")
    Cc: stable@vger.kernel.org
    Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
    Reviewed-by: Matthieu Baerts <matthieu.baerts@tessares.net>
    Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
    Link: https://lore.kernel.org/r/20230803-upstream-net-20230803-misc-fixes-6-5-v1-2-6671b1ab11cc@tessares.net
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrea Claudi <aclaudi@redhat.com>