Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm regression
jira LE-1907
cve CVE-2022-3640
Rebuild_History Non-Buildable kernel-4.18.0-506.el8
commit-author Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
commit 332f1795ca202489c665a75e62e18ff6284de077

The patch d0be8347c623: "Bluetooth: L2CAP: Fix use-after-free caused
by l2cap_chan_put" from Jul 21, 2022, leads to the following Smatch
static checker warning:

        net/bluetooth/l2cap_core.c:1977 l2cap_global_chan_by_psm()
        error: we previously assumed 'c' could be null (see line 1996)

Fixes: d0be8347c623 ("Bluetooth: L2CAP: Fix use-after-free caused by l2cap_chan_put")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
(cherry picked from commit 332f1795ca202489c665a75e62e18ff6284de077)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>