PCI: mt7621: Add missing MODULE_LICENSE()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2052155
Upstream Status: e4b1cd02dc8d7967a79edccd510724831e5cdee8

commit e4b1cd02dc8d7967a79edccd510724831e5cdee8
Author: Sergio Paracuellos <sergio.paracuellos@gmail.com>
Date:   Tue Dec 7 11:49:23 2021 +0100

    PCI: mt7621: Add missing MODULE_LICENSE()

    The MT7621 PCIe host controller driver can be built as a module, but it
    lacks a MODULE_LICENSE(), which causes a build error:

      ERROR: modpost: missing MODULE_LICENSE() in drivers/pci/controller/pcie-mt7621.o

    Add MODULE_LICENSE() to the driver.

    Fixes: 2bdd5238e756 ("PCI: mt7621: Add MediaTek MT7621 PCIe host controller driver")
    Link: https://lore.kernel.org/r/20211207104924.21327-5-sergio.paracuellos@gmail.com
    Signed-off-by: Yanteng Si <siyanteng@loongson.cn>
    Signed-off-by: Sergio Paracuellos <sergio.paracuellos@gmail.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Reviewed-by: Krzysztof Wilczyński <kw@linux.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>