sfc: siena: Have a unique wrapper ifndef for efx channels header
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Saeed Mahameed <saeedm@nvidia.com>
commit 309ec443079b0c6fcfb93a62c2554a164ade3f3e

Both sfc/efx_channels.h and sfc/siena/efx_channels.h used the same
wrapper #ifndef EFX_CHANNELS_H, this patch changes the siena define to be
EFX_SIENA_CHANNELS_H to avoid build system confusion.

This fixes the following build break:
drivers/net/ethernet/sfc/ptp.c:2191:28:
error: ‘efx_copy_channel’ undeclared here (not in a function); did you mean ‘efx_ptp_channel’?
  2191 |  .copy                   = efx_copy_channel,

Fixes: 6e173d3b4af9 ("sfc: Copy shared files needed for Siena (part 1)")
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
	Cc: Edward Cree <ecree.xilinx@gmail.com>
	Acked-by: Martin Habets <habetsm.xilinx@gmail.com>
Link: https://lore.kernel.org/r/20220518065820.131611-1-saeed@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 309ec443079b0c6fcfb93a62c2554a164ade3f3e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>