ACPI: arm64: export acpi_arch_thermal_cpufreq_pctg()
JIRA: https://issues.redhat.com/browse/RHEL-1697

commit ccb45b34d44016b91fa75646741d317d6d6fdeea
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 12 Dec 2023 22:48:38 +0100

    The cpufreq code can be in a loadable module, so the architecture support
    for it has to be exported:

    ERROR: modpost: "acpi_arch_thermal_cpufreq_pctg" [drivers/acpi/processor.ko] undefined!

    Fixes: 310293a2b941 ("ACPI: processor: reduce CPUFREQ thermal reduction pctg for Tegra241")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Charles Mirabile <cmirabil@redhat.com>