binfmt: a.out: Fix bogus semicolon
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2028891

This patch is a backport of the following upstream commit:
commit 0319b848b155185815724e1b46103c550627a845
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Sun Sep 5 11:30:34 2021 +0200

    binfmt: a.out: Fix bogus semicolon

        fs/binfmt_aout.c: In function ‘load_aout_library’:
        fs/binfmt_aout.c:311:27: error: expected ‘)’ before ‘;’ token
          311 |    MAP_FIXED | MAP_PRIVATE;
              |                           ^
        fs/binfmt_aout.c:309:10: error: too few arguments to function ‘vm_mmap’
          309 |  error = vm_mmap(file, start_addr, ex.a_text + ex.a_data,
              |          ^~~~~~~
        In file included from fs/binfmt_aout.c:12:
        include/linux/mm.h:2626:35: note: declared here
         2626 | extern unsigned long __must_check vm_mmap(struct file *, unsigned long,
              |                                   ^~~~~~~

    Fix this by reverting the accidental replacement of a comma by a
    semicolon.

    Fixes: 42be8b42535183f8 ("binfmt: don't use MAP_DENYWRITE when loading shared libraries via uselib()")
    Reported-by: noreply@ellerman.id.au
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>