ALSA: hda: cirrus_scodec: Select GPIOLIB for KUnit test
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit f9262fb1da6cc5499fff7e169e3aca8f8b59adde
Author: Richard Fitzgerald <rf@opensource.cirrus.com>
Date: Wed Sep 20 10:03:38 2023 +0100

    ALSA: hda: cirrus_scodec: Select GPIOLIB for KUnit test

    The KUnit test for cirrus_scodec uses GPIO library functions so select
    GPIOLIB in Kconfig.

    This fixes the ld failures on builds that didn't already select GPIOLIB.
     ld: vmlinux.o: in function `cirrus_scodec_test_gpio_get':
     sound/pci/hda/cirrus_scodec_test.c:40: undefined reference to
    	`gpiochip_get_data'
     ld: vmlinux.o: in function `cirrus_scodec_test_gpio_probe':
     sound/pci/hda/cirrus_scodec_test.c:94: undefined reference to
    	`gpiochip_generic_request'
     ld: sound/pci/hda/cirrus_scodec_test.c:94: undefined reference to
    	`gpiochip_generic_free'
     ld: sound/pci/hda/cirrus_scodec_test.c:95: undefined reference to
    	`devm_gpiochip_add_data_with_key'

    Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202309201646.NnjfKPWk-lkp@intel.com/
    Fixes: 2144833e7b41 ("ALSA: hda: cirrus_scodec: Add KUnit test")
    Link: https://lore.kernel.org/r/20230920090338.29345-1-rf@opensource.cirrus.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>