bnx2x: Fix build with SRIOV disabled.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [ethernet] bnx2x: Fix build with SRIOV disabled (Michal Schmidt) [1038666]
Rebuild_FUZZ: 98.63%
commit-author David S. Miller <davem@davemloft.net>
commit fcf93a0a2f9d317c0bffc430ddf8950041d13265

drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c: In function 'bnx2x_drv_info_ether_stat':
drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c:3302:46: error: dereferencing pointer to incomplete type
make[6]: *** [drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.o] Error 1

	Reported-by: Eric Dumazet <eric.dumazet@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit fcf93a0a2f9d317c0bffc430ddf8950041d13265)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>