bpf_helpers.h: Add note for building with vmlinux.h or linux/types.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Yoshiki Komachi <komachi.yoshiki@gmail.com>
commit ae460c022453337850bdc36a36bf7596a6cfcf99

The following error was shown when a bpf program was compiled without
vmlinux.h auto-generated from BTF:

 # clang -I./linux/tools/lib/ -I/lib/modules/$(uname -r)/build/include/ \
   -O2 -Wall -target bpf -emit-llvm -c bpf_prog.c -o bpf_prog.bc
 ...
 In file included from linux/tools/lib/bpf/bpf_helpers.h:5:
 linux/tools/lib/bpf/bpf_helper_defs.h:56:82: error: unknown type name '__u64'
 ...

It seems that bpf programs are intended for being built together with
the vmlinux.h (which will have all the __u64 and other typedefs). But
users may mistakenly think "include <linux/types.h>" is missing
because the vmlinux.h is not common for non-bpf developers. IMO, an
explicit comment therefore should be added to bpf_helpers.h as this
patch shows.

	Signed-off-by: Yoshiki Komachi <komachi.yoshiki@gmail.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
	Acked-by: Andrii Nakryiko <andriin@fb.com>
Link: https://lore.kernel.org/bpf/1587427527-29399-1-git-send-email-komachi.yoshiki@gmail.com
(cherry picked from commit ae460c022453337850bdc36a36bf7596a6cfcf99)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>