KVM: PPC: Fix compilation when KVM is not enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Paul Mackerras <paulus@ozlabs.org>
commit e74d53e30e2927fa5b223296ac7922baf15ea89a

Compiling with CONFIG_PPC_POWERNV=y and KVM disabled currently gives
an error like this:

  CC      arch/powerpc/kernel/dbell.o
In file included from arch/powerpc/kernel/dbell.c:20:0:
arch/powerpc/include/asm/kvm_ppc.h: In function ‘xics_on_xive’:
arch/powerpc/include/asm/kvm_ppc.h:625:9: error: implicit declaration of function ‘xive_enabled’ [-Werror=implicit-function-declaration]
  return xive_enabled() && cpu_has_feature(CPU_FTR_HVMODE);
         ^
cc1: all warnings being treated as errors
scripts/Makefile.build:276: recipe for target 'arch/powerpc/kernel/dbell.o' failed
make[3]: *** [arch/powerpc/kernel/dbell.o] Error 1

Fix this by making the xics_on_xive() definition conditional on the
same symbol (CONFIG_KVM_BOOK3S_64_HANDLER) that determines whether we
include <asm/xive.h> or not, since that's the header that defines
xive_enabled().

Fixes: 03f953329bd8 ("KVM: PPC: Book3S: Allow XICS emulation to work in nested hosts using XIVE")
	Signed-off-by: Paul Mackerras <paulus@ozlabs.org>
(cherry picked from commit e74d53e30e2927fa5b223296ac7922baf15ea89a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>