regmap: maple: Fix uninitialized symbol 'ret' warnings
JIRA: https://issues.redhat.com/browse/RHEL-27515

Omitted-fix: 8a8317f92770ab70ff39b15de74bdb3a07fdb6cb
	     regmap: kunit: Add some test cases and a few small

commit eaa03486d932572dfd1c5f64f9dfebe572ad88c0
Author: Richard Fitzgerald <rf@opensource.cirrus.com>
Date: Fri Mar 29 14:46:30 2024 +0000

    regmap: maple: Fix uninitialized symbol 'ret' warnings

    Fix warnings reported by smatch by initializing local 'ret' variable
    to 0.

    drivers/base/regmap/regcache-maple.c:186 regcache_maple_drop()
    error: uninitialized symbol 'ret'.
    drivers/base/regmap/regcache-maple.c:290 regcache_maple_sync()
    error: uninitialized symbol 'ret'.

    Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Fixes: f033c26de5a5 ("regmap: Add maple tree based register cache")
    Link: https://lore.kernel.org/r/20240329144630.1965159-1-rf@opensource.cirrus.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>