drivers/block/sunvdc.c: update the correct AIP call
JIRA: https://issues.redhat.com/browse/RHEL-79456

commit 64b48ec36dbed561ab1cd99708c33d96f4b7b729
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Feb 3 12:47:17 2025 +1100

    drivers/block/sunvdc.c: update the correct AIP call

    My sparc64 defconfig build failed like this:

    drivers/block/sunvdc.c: In function 'vdc_queue_drain':
    drivers/block/sunvdc.c:1130:9: error: too many arguments to function 'blk_mq_unquiesce_queue'
     1130 |         blk_mq_unquiesce_queue(q, memflags);
          |         ^~~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/block/sunvdc.c:10:
    include/linux/blk-mq.h:895:6: note: declared here
      895 | void blk_mq_unquiesce_queue(struct request_queue *q);
          |      ^~~~~~~~~~~~~~~~~~~~~~
    drivers/block/sunvdc.c:1131:9: error: too few arguments to function 'blk_mq_unfreeze_queue'
     1131 |         blk_mq_unfreeze_queue(q);
          |         ^~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/block/sunvdc.c:10:
    include/linux/blk-mq.h:914:1: note: declared here
      914 | blk_mq_unfreeze_queue(struct request_queue *q, unsigned int memflags)
          | ^~~~~~~~~~~~~~~~~~~~~

    Fixes: 1e1a9cecfab3 ("block: force noio scope in blk_mq_freeze_queue")
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Jens Axboe <axboe@kernel.dk>
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>