LSM: Avoid warnings about potentially unused hook variables
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2083580

commit 86dd9fd52e1449084c58c1ebb1f099a2ccc85091
Author: Kees Cook <keescook@chromium.org>
Date:   Wed Oct 13 10:28:48 2021 -0700

    LSM: Avoid warnings about potentially unused hook variables

    Building with W=1 shows many unused const variable warnings. These can
    be silenced, as we're well aware of their being potentially unused:

    ./include/linux/lsm_hook_defs.h:36:18: error: 'ptrace_access_check_default' defined but not used [-Werror=unused-const-variable=]
       36 | LSM_HOOK(int, 0, ptrace_access_check, struct task_struct *child,
          |                  ^~~~~~~~~~~~~~~~~~~
    security/security.c:706:32: note: in definition of macro 'LSM_RET_DEFAULT'
      706 | #define LSM_RET_DEFAULT(NAME) (NAME##_default)
          |                                ^~~~
    security/security.c:711:9: note: in expansion of macro 'DECLARE_LSM_RET_DEFAULT_int'
      711 |         DECLARE_LSM_RET_DEFAULT_##RET(DEFAULT, NAME)
          |         ^~~~~~~~~~~~~~~~~~~~~~~~
    ./include/linux/lsm_hook_defs.h:36:1: note: in expansion of macro 'LSM_HOOK'
       36 | LSM_HOOK(int, 0, ptrace_access_check, struct task_struct *child,
          | ^~~~~~~~

    Cc: James Morris <jmorris@namei.org>
    Cc: "Serge E. Hallyn" <serge@hallyn.com>
    Cc: Paul Moore <paul@paul-moore.com>
    Cc: Casey Schaufler <casey@schaufler-ca.com>
    Cc: KP Singh <kpsingh@chromium.org>
    Cc: linux-security-module@vger.kernel.org
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/linux-mm/202110131608.zms53FPR-lkp@intel.com/
    Fixes: 98e828a0650f ("security: Refactor declaration of LSM hooks")
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Acked-by: James Morris <jamorris@linux.microsoft.com>
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>