tools: PCI: Fix compiler warning in pcitest
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Alan Mikhak <alan.mikhak@sifive.com>
commit 81cb4203a5fec7d3f8cf4f145e8e7077b2dcbc78

Fix the following compiler warning in pcitest:

pcitest.c: In function main:
pcitest.c:214:4: warning: too many arguments for
format [-Wformat-extra-args]
    "usage: %s [options]\n"

Fixes: fbca0b284bd0 ("tools: PCI: Add 'h' in optstring of getopt()")
	Signed-off-by: Alan Mikhak <alan.mikhak@sifive.com>
	Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
	Reviewed-by: Paul Walmsley <paul.walmsley@sifive.com>
(cherry picked from commit 81cb4203a5fec7d3f8cf4f145e8e7077b2dcbc78)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>