x86/idle: Use MONITOR and MWAIT mnemonics in <asm/mwait.h>
JIRA: https://issues.redhat.com/browse/RHEL-83893
Conflicts:
  Context diff's due to missing upstream commit 1ae899e41310 ("x86/idle:
  Standardize argument types for MONITOR{,X} and MWAIT{,X} instruction
  wrappers on 'u32'").

commit fc1cd60042b3df1d162278461c7a87f0362502b8
Author: Uros Bizjak <ubizjak@gmail.com>
Date:   Thu, 3 Apr 2025 14:50:45 +0200

    x86/idle: Use MONITOR and MWAIT mnemonics in <asm/mwait.h>

    Current minimum required version of binutils is 2.25,
    which supports MONITOR and MWAIT instruction mnemonics.

    Replace the byte-wise specification of MONITOR and
    MWAIT with these proper mnemonics.

    No functional change intended.

    Note: LLVM assembler is not able to assemble correct forms of MONITOR
    and MWAIT instructions with explicit operands and reports:

      error: invalid operand for instruction
              monitor %rax,%ecx,%edx
                           ^~~~
      # https://lore.kernel.org/oe-kbuild-all/202504030802.2lEVBSpN-lkp@intel.com/

    Use instruction mnemonics with implicit operands to
    work around this issue.

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Acked-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20250403125111.429805-1-ubizjak@gmail.com

Signed-off-by: Waiman Long <longman@redhat.com>