powerpc/64s: Remove 'dummy_copy_buffer'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Mathieu Malaterre <malat@debian.org>
commit a5ae043de7678f189303559782f6057078459a41

In commit 2bf1071a8d50 ("powerpc/64s: Remove POWER9 DD1 support") the
function __switch_to remove usage for 'dummy_copy_buffer'. Since it is
not used anywhere else, remove it completely.

This remove the following warning:
  arch/powerpc/kernel/process.c:1156:17: error: 'dummy_copy_buffer' defined but not used

	Suggested-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Signed-off-by: Mathieu Malaterre <malat@debian.org>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit a5ae043de7678f189303559782f6057078459a41)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>