HID: Kconfig: Add LEDS_CLASS_MULTICOLOR dependency to HID_LOGITECH
JIRA: https://issues.redhat.com/browse/RHEL-170872
Upstream Status: since v6.15

commit 4465f4fa21e0e54c10896db3ed49dbd5a9aad3fd
Author: Kate Hsuan <hpa@redhat.com>
Date:   Tue Feb 11 13:02:40 2025 +0800

    HID: Kconfig: Add LEDS_CLASS_MULTICOLOR dependency to HID_LOGITECH

    The test bot found an issue with building hid-lg-g15.

    All errors (new ones prefixed by >>):

       powerpc-linux-ld: drivers/hid/hid-lg-g15.o: in function `lg_g510_kbd_led_write':
    >> drivers/hid/hid-lg-g15.c:241:(.text+0x768): undefined reference to `led_mc_calc_color_components'
       powerpc-linux-ld: drivers/hid/hid-lg-g15.o: in function `lg_g15_register_led':
    >> drivers/hid/hid-lg-g15.c:686:(.text+0xa9c): undefined reference to `devm_led_classdev_multicolor_register_ext'

    Since multicolor LED APIs manage the keyboard backlight settings of
    hid-lg-g15, the LEDS_CLASS_MULTICOLOR dependency was added to
    HID_LOGITECH.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202502110032.VZ0J024X-lkp@intel.com/
    Fixes: a3a064146c50 ("HID: hid-lg-g15: Use standard multicolor LED API")
    Signed-off-by: Kate Hsuan <hpa@redhat.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>