dmaengine: qcom: gpi: Drop unused gpi_write_reg_field()
JIRA: https://issues.redhat.com/browse/RHEL-114133
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 24c13df655ca1fad5fc6fa4fbacb828f4a6d4f2b
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Sun May 25 21:26:03 2025 +0200

    dmaengine: qcom: gpi: Drop unused gpi_write_reg_field()

    Static function gpi_write_reg_field() is not used, W=1 build:

      gpi.c:573:20: error: unused function 'gpi_write_reg_field' [-Werror,-Wunused-function]

    Fixes: 5d0c3533a19f ("dmaengine: qcom: Add GPI dma driver")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20250525-dma-fixes-v1-3-89d06dac9bcb@linaro.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

(cherry picked from commit 24c13df655ca1fad5fc6fa4fbacb828f4a6d4f2b)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>