ASoC: amd: acp: Fix pointer assignments for snd_soc_acpi_mach structures
JIRA: https://issues.redhat.com/browse/RHEL-101627

commit 0779c0ad2a7cc0ae1865860c9bc8732613cc56b1
Author: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Date: Mon Jun 9 17:42:32 2025 +0530

    ASoC: amd: acp: Fix pointer assignments for snd_soc_acpi_mach structures

    This patch modifies the assignment of machine structure pointers in the
    acp_pci_probe function. Previously, the machine pointers were assigned
    using the address-of operator (&), which caused incompatibility issues
    in type assignments.

    Additionally, the declarations of the machine arrays in amd.h have been
    updated to reflect that they are indeed arrays (`[]`). The code is
    further cleaned up by declaring the codec structures in
    amd-acpi-mach.c as static, reflecting their intended usage.

    error: symbol 'amp_rt1019' was not declared. Should it be static?
    error: symbol 'amp_max' was not declared. Should it be static?
    error: symbol 'snd_soc_acpi_amd_acp_machines' was not declared. Should it be static?
    error: symbol 'snd_soc_acpi_amd_rmb_acp_machines' was not declared. Should it be static?
    error: symbol 'snd_soc_acpi_amd_acp63_acp_machines' was not declared. Should it be static?
    error: symbol 'snd_soc_acpi_amd_acp70_acp_machines' was not declared. Should it be static?

    Fixes: 9c2c0ef64009 ("ASoC: amd: acp: Fix snd_soc_acpi_mach id's duplicate symbol error")

    Link: https://github.com/thesofproject/linux/issues/5438
    Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
    Link: https://patch.msgid.link/20250609121251.639080-1-venkataprasad.potturu@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>