wifi: brcmsmac: remove unused has_5g variable
Bugzilla: https://bugzilla.redhat.com/2196821

commit 5aeb763a27c2b444928639d35cbe94520c405969
Author: Tom Rix <trix@redhat.com>
Date:   Sat Mar 25 09:03:43 2023 -0400

    wifi: brcmsmac: remove unused has_5g variable
    
    clang with W=1 reports
    drivers/net/wireless/broadcom/brcm80211/brcmsmac/mac80211_if.c:1051:6: error:
      variable 'has_5g' set but not used [-Werror,-Wunused-but-set-variable]
            int has_5g = 0;
                ^
    This variable is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230325130343.1334209-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>