acpi/nfit: Fix COMPLETION_INITIALIZER_ONSTACK() abuse
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [acpi] nfit: Fix COMPLETION_INITIALIZER_ONSTACK() abuse (Jeff Moyer) [1455958]
Rebuild_FUZZ: 95.05%
commit-author Boqun Feng <boqun.feng@gmail.com>
commit 1c322ac06d9af7ea259098ae5dc977855207d335

COMPLETION_INITIALIZER_ONSTACK() is supposed to be used as an initializer,
in other words, it should only be used in assignment expressions or
compound literals. So the usage in drivers/acpi/nfit/core.c:

	COMPLETION_INITIALIZER_ONSTACK(flush.cmp);

... is inappropriate.

Besides, this usage could also break the build for another fix that
reduces stack sizes caused by COMPLETION_INITIALIZER_ONSTACK(), because
that fix changes COMPLETION_INITIALIZER_ONSTACK() from rvalue to lvalue,
and usage as above will report the following error:

	drivers/acpi/nfit/core.c: In function 'acpi_nfit_flush_probe':
	include/linux/completion.h:77:3: error: value computed is not used [-Werror=unused-value]
	  (*({ init_completion(&work); &work; }))

This patch fixes this by replacing COMPLETION_INITIALIZER_ONSTACK()
with init_completion() in acpi_nfit_flush_probe(), which does the
same initialization without any other problems.

	Signed-off-by: Boqun Feng <boqun.feng@gmail.com>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Acked-by: Dan Williams <dan.j.williams@intel.com>
	Acked-by: Arnd Bergmann <arnd@arndb.de>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Cc: Byungchul Park <byungchul.park@lge.com>
	Cc: Len Brown <lenb@kernel.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Nicholas Piggin <npiggin@gmail.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Rafael J. Wysocki <rjw@rjwysocki.net>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: walken@google.com
	Cc: willy@infradead.org
Link: http://lkml.kernel.org/r/20170824142239.15178-1-boqun.feng@gmail.com
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 1c322ac06d9af7ea259098ae5dc977855207d335)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>