scsi: qla2xxx: Fix printk() format string
Bugzilla: https://bugzilla.redhat.com/2164960

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit d794a23113b1a198e3d05f144aeba5b6ac87fe99
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 17 18:00:15 2023 +0100

    scsi: qla2xxx: Fix printk() format string

    Printing a size_t value that is the result of the sizeof() operator
    requires using the %z format string modifier to avoid a warning on 32-bit
    architectures:

    drivers/scsi/qla2xxx/qla_mid.c: In function 'qla_create_buf_pool':
    drivers/scsi/qla2xxx/qla_mid.c:1094:51: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'unsigned int' [-Werror=format=]
     1094 |                     "Failed to allocate buf_map(%ld).\n", sz * sizeof(unsigned long));
          |                                                 ~~^       ~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                                                   |          |
          |                                                   long int   unsigned int
          |                                                 %d

    Fixes: 82d8dfd2a238 ("scsi: qla2xxx: edif: Fix performance dip due to lock contention")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Bart Van Assche <bvanassche@acm.org>
    Reviewed-by: Himanshu Madhani <himansnhu.madhani@oracle.com <mailto:himansnhu.madhani@oracle.com>>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Link: https://lore.kernel.org/r/20230117170029.2387516-1-arnd@kernel.org
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>