ALSA: asihpi: avoid write overflow check warning
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit 591721223be9e28f83489a59289579493b8e3d83
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Mar 18 13:40:07 2026 +0100

    ALSA: asihpi: avoid write overflow check warning

    clang-22 rightfully warns that the memcpy() in adapter_prepare() copies
    between different structures, crossing the boundary of nested
    structures inside it:

    In file included from sound/pci/asihpi/hpimsgx.c:13:
    In file included from include/linux/string.h:386:
    include/linux/fortify-string.h:569:4: error: call to '__write_overflow_field' declared with 'warning' attribute: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
      569 |                         __write_overflow_field(p_size_field, size);

    The two structures seem to refer to the same layout, despite the
    separate definitions, so the code is in fact correct.

    Avoid the warning by copying the two inner structures separately.
    I see the same pattern happens in other functions in the same file,
    so there is a chance that this may come back in the future, but
    this instance is the only one that I saw in practice, hitting it
    multiple times per day in randconfig build.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260318124016.3488566-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>