mmc: dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] dw_mmc: add missing MFD_SYSCON dependency for SOCFPGA (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 95.50%
commit-author Jingoo Han <jg1.han@samsung.com>
commit e33c2025c0c2f8a20054c3e031877ff595d1c31f

Added missing MFD_SYSCON dependency for SOCFPGA in order to fix
the following link error.

drivers/mmc/host/dw_mmc-socfpga.c:49: undefined reference to `syscon_regmap_lookup_by_compatible'

	Signed-off-by: Jingoo Han <jg1.han@samsung.com>
	Acked-by: Jaehoon Chung <jh80.chung@samsung.com>
	Acked-by: Seungwon Jeon <tgih.jun@samsung.com>
	Signed-off-by: Chris Ball <cjb@laptop.org>
(cherry picked from commit e33c2025c0c2f8a20054c3e031877ff595d1c31f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>