net: stmmac: mark PM functions as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-331.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 81a8b0799632627b587af31ecd06112397e4ec36

The newly added suspend/resume functions cause a build warning
when CONFIG_PM is disabled:

drivers/net/ethernet/stmicro/stmmac/stmmac_pci.c:324:12: error: 'stmmac_pci_resume' defined but not used [-Werror=unused-function]
drivers/net/ethernet/stmicro/stmmac/stmmac_pci.c:306:12: error: 'stmmac_pci_suspend' defined but not used [-Werror=unused-function]

Mark them as __maybe_unused so gcc can drop them silently.

Fixes: b7d0f08e9129 ("net: stmmac: Fix WoL for PCI-based setups")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 81a8b0799632627b587af31ecd06112397e4ec36)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>