x86/speculation: Add cpu_show_gds() prototype
JIRA: https://issues.redhat.com/browse/RHEL-8594
CVE: CVE-2023-20569

commit a57c27c7ad85c420b7de44c6ee56692d51709dda
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed, 9 Aug 2023 15:04:59 +0200

    x86/speculation: Add cpu_show_gds() prototype

    The newly added function has two definitions but no prototypes:

    drivers/base/cpu.c:605:16: error: no previous prototype for 'cpu_show_gds' [-Werror=missing-prototypes]

    Add a declaration next to the other ones for this file to avoid the
    warning.

    Fixes: 8974eb588283b ("x86/speculation: Add Gather Data Sampling mitigation")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Tested-by: Daniel Sneddon <daniel.sneddon@linux.intel.com>
    Cc: stable@kernel.org
    Link: https://lore.kernel.org/all/20230809130530.1913368-1-arnd%40kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>