ALSA: pci: lx6464es: remove useless self-comparison
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-372.9.1.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit b5c2e2c79034eaa4c786e304d094618156eea69b

Sparse throws the following warning:

sound/pci/lx6464es/lx_core.c:677:34: error: self-comparison always
evaluates to false

This comparison and error message make no sense, let's remove them.

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20210526192957.449515-2-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit b5c2e2c79034eaa4c786e304d094618156eea69b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>