HID: u2fzero: fix compiling error in u2fzero_probe()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [hid] u2fzero: fix compiling error in u2fzero_probe() (Benjamin Tissoires) [1740778]
Rebuild_FUZZ: 94.95%
commit-author Mao Wenan <maowenan@huawei.com>
commit e252e0e0028167ea3d1eafa99c2ff9f62c444b0a

There is one compiling error in u2fzero_probe()->u2fzero_init_hwrng(),
this is because HW_RANDOM is not set.

drivers/hid/hid-u2fzero.o: In function `u2fzero_probe':
hid-u2fzero.c:(.text+0xc70): undefined reference to `devm_hwrng_register'

Fixes: 42337b9d4d958("HID: add driver for U2F Zero built-in LED and RNG")
	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Mao Wenan <maowenan@huawei.com>
	Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit e252e0e0028167ea3d1eafa99c2ff9f62c444b0a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>