sound/oss/dmasound: fix 'dmasound_setup' defined but not used
We observed: 'dmasound_setup' defined but not used error with
COMPILER=gcc ARCH=m68k DEFCONFIG=allmodconfig build.

Fix it by adding __maybe_unused to dmasound_setup.

Error(s):
sound/oss/dmasound/dmasound_core.c:1431:12: error: 'dmasound_setup' defined but not used [-Werror=unused-function]

    Fixes: 9dd7c46346ca ("sound/oss/dmasound: fix build when drivers are mixed =y/=m")
    Signed-off-by: Miles Chen <miles.chen@mediatek.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Link: https://lore.kernel.org/r/20220414091940.2216-1-miles.chen@mediatek.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Miles Chen <miles.chen@mediatek.com>
Date: Thu Apr 14 17:19:38 2022 +0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 357ad4d898286b94aaae0cb7e3f573459e5b98b9)
Bugzilla: https://bugzilla.redhat.com/2065572