arm64: mm: make CONFIG_ZONE_DMA32 configurable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Miles Chen <miles.chen@mediatek.com>
commit 0c1f14ed12262f45a3af1d588e4d7bd12438b8f5

This change makes CONFIG_ZONE_DMA32 defuly y and allows users
to overwrite it only when CONFIG_EXPERT=y.

For the SoCs that do not need CONFIG_ZONE_DMA32, this is the
first step to manage all available memory by a single
zone(normal zone) to reduce the overhead of multiple zones.

The change also fixes a build error when CONFIG_NUMA=y and
CONFIG_ZONE_DMA32=n.

arch/arm64/mm/init.c:195:17: error: use of undeclared identifier 'ZONE_DMA32'
                max_zone_pfns[ZONE_DMA32] = PFN_DOWN(max_zone_dma_phys());

Change since v1:
1. only expose CONFIG_ZONE_DMA32 when CONFIG_EXPERT=y
2. remove redundant IS_ENABLED(CONFIG_ZONE_DMA32)

	Cc: Robin Murphy <robin.murphy@arm.com>
	Signed-off-by: Miles Chen <miles.chen@mediatek.com>
	Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
(cherry picked from commit 0c1f14ed12262f45a3af1d588e4d7bd12438b8f5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>