drm/tegra: Mark nvdec_writel() as inline
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2154295
Upstream Status: v5.17-rc1

commit 2245c2a2722be04ed15012d169a7ceb7df7550a7
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Wed Oct 13 16:40:58 2021 +0200
Commit:     Thierry Reding <treding@nvidia.com>
CommitDate: Thu Dec 16 14:07:07 2021 +0100

    Without CONFIG_IOMMU_API, the nvdec_writel() function is unused, causing
    a warning:

    drivers/gpu/drm/tegra/nvdec.c:48:13: error: 'nvdec_writel' defined but not used [-Werror=unused-function]
       48 | static void nvdec_writel(struct nvdec *nvdec, u32 value, unsigned int offset)
          |             ^~~~~~~~~~~~

    As this is a trivial wrapper around an inline function, mark it as
    inline itself, which avoids the warning as well.

    Fixes: e76599df354d ("drm/tegra: Add NVDEC driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thierry Reding <treding@nvidia.com>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>