bpftool: Query only cgroup-related attach types
JIRA: https://issues.redhat.com/browse/RHEL-30774

commit 98b303c9bf05dae932efbd71e18d81f6c64f20d8
Author: Kenta Tada <tadakentaso@gmail.com>
Date:   Fri Jun 7 20:17:04 2024 +0900

    bpftool: Query only cgroup-related attach types
    
    When CONFIG_NETKIT=y,
    bpftool-cgroup shows error even if the cgroup's path is correct:
    
    $ bpftool cgroup tree /sys/fs/cgroup
    CgroupPath
    ID       AttachType      AttachFlags     Name
    Error: can't query bpf programs attached to /sys/fs/cgroup: No such device or address
    
    >From strace and kernel tracing, I found netkit returned ENXIO and this command failed.
    I think this AttachType(BPF_NETKIT_PRIMARY) is not relevant to cgroup.
    
    bpftool-cgroup should query just only cgroup-related attach types.
    
    v2->v3:
      - removed an unnecessary check
    
    v1->v2:
      - used an array of cgroup attach types
    
    Signed-off-by: Kenta Tada <tadakentaso@gmail.com>
    Reviewed-by: Quentin Monnet <qmo@kernel.org>
    Link: https://lore.kernel.org/r/20240607111704.6716-1-tadakentaso@gmail.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>