KEYS: Fix an error code in request_master_key()
jira LE-1907
cve CVE-2017-7472
cve CVE-2015-8539
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 57cb17e764ba0aaa169d07796acce54ccfbc6cae

This function has two callers and neither are able to handle a NULL
return.  Really, -EINVAL is the correct thing return here anyway.  This
fixes some static checker warnings like:

	security/keys/encrypted-keys/encrypted.c:709 encrypted_key_decrypt()
	error: uninitialized symbol 'master_key'.

Fixes: 7e70cb497850 ("keys: add new key-type encrypted")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Mimi Zohar <zohar@linux.vnet.ibm.com>
	Signed-off-by: James Morris <james.l.morris@oracle.com>
(cherry picked from commit 57cb17e764ba0aaa169d07796acce54ccfbc6cae)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>