tools: Suppress request for warning options not existent in clang
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [tools] Suppress request for warning options not existent in clang (Jiri Olsa) [1478485]
Rebuild_FUZZ: 94.31%
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit 093b75ef5995ea35d7f6bdb6c7b32a42a1999813

To allow building with clang, avoiding:

  error: unknown warning option '-Wstrict-aliasing=3'; did you mean '-Wstring-plus-int'? [-Werror,-Wunknown-warning-option]

	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/n/tip-xvthlvmhzfnt7jx73jgmaea1@git.kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 093b75ef5995ea35d7f6bdb6c7b32a42a1999813)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>