ASoC: mediatek: mt8188: avoid uninitialized variable use
JIRA: https://issues.redhat.com/browse/RHEL-80658

commit 79ed408b2402e8113aa5a298f3bb9088ede58f6c
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Feb 27 14:19:01 2025 +0100

    ASoC: mediatek: mt8188: avoid uninitialized variable use

    The 'msk' variable has no initialization:

    sound/soc/mediatek/mt8188/mt8188-dai-dmic.c:311:4: error: variable 'msk' is uninitialized when used here [-Werror,-Wuninitialized]
      311 |                         msk |= PWR2_TOP_CON1_DMIC_FIFO_SOFT_RST_EN(i);
          |                         ^~~

    Set it to zero before the loop.

    Fixes: c1e42ec04197 ("ASoC: mediatek: mt8188: Add support for DMIC")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nícolas F. R. A. Prado <nfraprado@collabora.com>
    Link: https://patch.msgid.link/20250227131939.1040168-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>