ALSA: sparc/dbri: add missing fallthrough
JIRA: https://issues.redhat.com/browse/RHEL-183295

commit 2bcbb163162789d3488562073dbb99d9bd71a762
Author: Rosen Penev <rosenp@gmail.com>
Date: Tue May 5 20:18:54 2026 -0700

    ALSA: sparc/dbri: add missing fallthrough

    Fixes compiler error with probably newer compilers:

    sound/sparc/dbri.c:595:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
      595 |         case 1:
          |         ^
    sound/sparc/dbri.c:595:2: note: insert 'break;' to avoid fall-through
      595 |         case 1:
          |         ^
          |         break;

    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    Link: https://patch.msgid.link/20260506031854.780411-1-rosenp@gmail.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>