dmaengine: dw-edma: remove unused readq_ch and writeq_ch functions
JIRA: https://issues.redhat.com/browse/RHEL-65598
Upstream Status: d77c4502d6238bbfed7cb9422748477839d506f2

commit d77c4502d6238bbfed7cb9422748477839d506f2
Author: Tom Rix <trix@redhat.com>
Date:   Mon Mar 20 19:49:06 2023 -0400

    dmaengine: dw-edma: remove unused readq_ch and writeq_ch functions

    clang with W=1 reports
    drivers/dma/dw-edma/dw-edma-v0-core.c:162:20: error:
      unused function 'writeq_ch' [-Werror,-Wunused-function]
    static inline void writeq_ch(struct dw_edma *dw, enum dw_edma_dir dir, u16 ch,
                       ^
    drivers/dma/dw-edma/dw-edma-v0-core.c:185:19: error:
      unused function 'readq_ch' [-Werror,-Wunused-function]
    static inline u64 readq_ch(struct dw_edma *dw, enum dw_edma_dir dir, u16 ch,
                      ^
    These functions and their wrapping macros are not used, so remove them.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230320234906.1730308-1-trix@redhat.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>