net/mlx5e: allocate 'indirection_rqt' buffer dynamically
jira LE-1907
Rebuild_History Non-Buildable kernel-rt-4.18.0-372.9.1.rt7.166.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 2119bda642c49c732409574ce699e4845e95df48

Increasing the size of the indirection_rqt array from 128 to 256 bytes
pushed the stack usage of the mlx5e_hairpin_fill_rqt_rqns() function
over the warning limit when building with clang and CONFIG_KASAN:

drivers/net/ethernet/mellanox/mlx5/core/en_tc.c:970:1: error: stack frame size of 1180 bytes in function 'mlx5e_tc_add_nic_flow' [-Werror,-Wframe-larger-than=]

Using dynamic allocation here is safe because the caller does the
same, and it reduces the stack usage of the function to just a few
bytes.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
(cherry picked from commit 2119bda642c49c732409574ce699e4845e95df48)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>