wifi: rtw88: add RTW88_LEDS depends on LEDS_CLASS to Kconfig
JIRA: https://issues.redhat.com/browse/RHEL-79792

commit b4bfbc50b1b92a0815800eb1231f73bfc917af03
Author: Ping-Ke Shih <pkshih@realtek.com>
Date:   Thu Jan 16 20:04:24 2025 +0800

    wifi: rtw88: add RTW88_LEDS depends on LEDS_CLASS to Kconfig
    
    When using allmodconfig, .config has CONFIG_LEDS_CLASS=m but
    autoconf.h has CONFIG_LEDS_CLASS_MODULE (additional suffix _MODULE)
    instead of CONFIG_LEDS_CLASS, which condition CONFIG_LEDS_CLASS in
    rtw88/led.h can't work properly.
    
    Add RTW88_LEDS to Kconfig, and use it as condition to fix this problem.
    
    drivers/net/wireless/realtek/rtw88/led.c:19:6: error: redefinition of 'rtw_led_init'
       19 | void rtw_led_init(struct rtw_dev *rtwdev)
          |      ^~~~~~~~~~~~
    In file included from drivers/net/wireless/realtek/rtw88/led.c:7:
    drivers/net/wireless/realtek/rtw88/led.h:15:20: note: previous definition of 'rtw_led_init' with type 'void(struct rtw_dev *)'
       15 | static inline void rtw_led_init(struct rtw_dev *rtwdev)
          |                    ^~~~~~~~~~~~
    drivers/net/wireless/realtek/rtw88/led.c:64:6: error: redefinition of 'rtw_led_deinit'
       64 | void rtw_led_deinit(struct rtw_dev *rtwdev)
          |      ^~~~~~~~~~~~~~
    drivers/net/wireless/realtek/rtw88/led.h:19:20: note: previous definition of 'rtw_led_deinit' with type 'void(struct rtw_dev *)'
       19 | static inline void rtw_led_deinit(struct rtw_dev *rtwdev)
          |                    ^~~~~~~~~~~~~~
    
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Closes: https://lore.kernel.org/linux-wireless/e19a87ad9cd54bfa9907f3a043b25d30@realtek.com/T/#me407832de1040ce22e53517bcb18e322ad0e2260
    Fixes: 4b6652bc6d8d ("wifi: rtw88: Add support for LED blinking")
    Cc: Bitterblue Smith <rtl8821cerfe2@gmail.com>
    Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://patch.msgid.link/20250116120424.13174-1-pkshih@realtek.com

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>