net: usb: catc: constify usb_device_id and fix space before '[' error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [usb] usb: catc: constify usb_device_id and fix space before '[' error (Torez Smith) [1540721]
Rebuild_FUZZ: 96.24%
commit-author Arvind Yadav <arvind.yadav.cs@gmail.com>
commit 2f622c4951aade21d9d8c66dc9d6276012a1d8b5

usb_device_id are not supposed to change at runtime. All functions
working with usb_device_id provided by <linux/usb.h> work with
const usb_device_id. So mark the non-const structs as const.

Fix checkpatch.pl error:
ERROR: space prohibited before open square bracket '['.

	Signed-off-by: Arvind Yadav <arvind.yadav.cs@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 2f622c4951aade21d9d8c66dc9d6276012a1d8b5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>