perf metric: Add DCache_L2 to metric parse test
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Jiri Olsa <jolsa@kernel.org>
commit 5a606f3b9c85ea024a8071765a523c85df93c454

Adding test that compute DCache_L2 metrics with other related metrics in it.

Committer notes:

Fixed up this:

  tests/parse-metric.c:285:7: error: missing field 'val' initializer [-Werror,-Wmissing-field-initializers]
                  { 0 },
                      ^

	Signed-off-by: Jiri Olsa <jolsa@kernel.org>
	Reviewed-by: Kajol Jain <kjain@linux.ibm.com>
	Acked-by: Ian Rogers <irogers@google.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Andi Kleen <ak@linux.intel.com>
	Cc: John Garry <john.garry@huawei.com>
	Cc: Michael Petlan <mpetlan@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Stephane Eranian <eranian@google.com>
Link: http://lore.kernel.org/lkml/20200719181320.785305-15-jolsa@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 5a606f3b9c85ea024a8071765a523c85df93c454)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>