tty: hvc-iucv: fix function pointer casts
JIRA: https://issues.redhat.com/browse/RHEL-86670

commit 42af6bcbc351d544889fcbcfc9c3d4bd39191b7d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 13 11:17:49 2024 +0100

    tty: hvc-iucv: fix function pointer casts

    clang warns about explicitly casting between incompatible function
    pointers:

    drivers/tty/hvc/hvc_iucv.c:1100:23: error: cast from 'void (*)(const void *)' to 'void (*)(struct device *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
     1100 |         priv->dev->release = (void (*)(struct device *)) kfree;
          |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Add a separate function to handle this correctly.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jiri Slaby <jirislaby@kernel.org>
    Link: https://lore.kernel.org/r/20240213101756.461701-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Thomas Huth <thuth@redhat.com>