PCI/AER: include header file
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [pci] aer: include header file (David Milburn) [1288601]
Rebuild_FUZZ: 92.31%
commit-author Sudip Mukherjee <sudipm.mukherjee@gmail.com>
commit c89e5b80245899fc51fb1d83880e2f5762fcf350

We are having build failure with sparc allmodconfig with the error:

drivers/nvme/host/pci.c:15:0:
include/linux/aer.h: In function 'pci_enable_pcie_error_reporting':
include/linux/aer.h:49:10: error: 'EINVAL' undeclared (first use in this function)

The file aer.h is using the error values but they are defined in
errno.h. Include errno.h so that we have the definitions of the error
codes.

Fixes: a0a3408ee614 ("NVMe: Add pci error handlers")
	Cc: Keith Busch <keith.busch@intel.com>
	Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>
	Signed-off-by: Jens Axboe <axboe@fb.com>
(cherry picked from commit c89e5b80245899fc51fb1d83880e2f5762fcf350)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>