ASoC: intel: add function stub when ACPI is not enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: add function stub when ACPI is not enabled (Jaroslav Kysela) [1399503]
Rebuild_FUZZ: 94.83%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit f17131a93f43665a76ae1f6aebdbb3e41674137c

Add function stub for "sst_acpi_find_name_from_hid()"
when CONFIG_ACPI is not enabled so that the driver will build
successfully. This fixes the following build errors:

(loadable module)
ERROR: "sst_acpi_find_name_from_hid" [sound/soc/intel/boards/snd-soc-sst-bytcr-rt5640.ko] undefined!
(or built-in)
bytcr_rt5640.c:(.text+0x26fc52): undefined reference to `sst_acpi_find_name_from_hid'

	Reported-by: Borislav Petkov <bp@alien8.de>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit f17131a93f43665a76ae1f6aebdbb3e41674137c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>