RDMA/core: Reduce poll batch for direct cq polling
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Max Gurtovoy <maxg@mellanox.com>
commit d3b9e8ad425cfd5b9116732e057f1b48e4d3bcb8

Fix warning limit for kernel stack consumption:

drivers/infiniband/core/cq.c: In function 'ib_process_cq_direct':
drivers/infiniband/core/cq.c:78:1: error: the frame size of 1032 bytes
is larger than 1024 bytes [-Werror=frame-larger-than=]

Using smaller ib_wc array on the stack brings us comfortably below that
limit again.

Fixes: 246d8b184c10 ("IB/cq: Don't force IB_POLL_DIRECT poll context for ib_process_cq_direct")
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Sergey Gorenko <sergeygo@mellanox.com>
	Signed-off-by: Max Gurtovoy <maxg@mellanox.com>
	Signed-off-by: Leon Romanovsky <leonro@mellanox.com>
	Reviewed-by: Bart Van Assche <bart.vanassche@wdc.com>
	Acked-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit d3b9e8ad425cfd5b9116732e057f1b48e4d3bcb8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>