wifi: mt76: mt7915: fix an uninitialized variable bug
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-481.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit b5ee771c84082b4e54cc39d9d9a2dd239e4f6b86

Smatch complains that:

    drivers/net/wireless/mediatek/mt76/mt7915/mac.c:428 mt7915_mac_fill_rx()
    error: uninitialized symbol 'msta'.

It looks like this was supposed to be initialized to NULL.

Fixes: 0880d40871d1 ("mt76: connac: move mt76_connac2_reverse_frag0_hdr_trans in mt76-connac module")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit b5ee771c84082b4e54cc39d9d9a2dd239e4f6b86)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>