usb: typec: fusb302: Fix an undefined reference to 'extcon_get_state'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author zhong jiang <zhongjiang@huawei.com>
commit 547fc228755d79af648898187e7831a825d4f42c

Fixes the following compile error:

drivers/usb/typec/tcpm/fusb302.o: In function `tcpm_get_current_limit':
fusb302.c:(.text+0x3ee): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x422): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x450): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x48c): undefined reference to `extcon_get_state'
drivers/usb/typec/tcpm/fusb302.o: In function `fusb302_probe':
fusb302.c:(.text+0x980): undefined reference to `extcon_get_extcon_dev'
make: *** [vmlinux] Error 1

It is because EXTCON is build as a module, but FUSB302 is not.

	Suggested-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
	Signed-off-by: zhong jiang <zhongjiang@huawei.com>
	Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
	Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/1576239378-50795-1-git-send-email-zhongjiang@huawei.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 547fc228755d79af648898187e7831a825d4f42c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>