HID: intel-ish-hid: fix module device-id handling
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070873
Upstream Status: since v5.16
Tested: with the hid-tools test suite and some hardware

partial backport as it was already backported as commit
2dbebbcd24c6.

commit bf9167a8b40c9cf463521da05342db81808c1b6e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Nov 11 09:56:33 2021 +0100

    HID: intel-ish-hid: fix module device-id handling

    A late addititon to the intel-ish-hid framework caused a build failure
    with clang, and introduced an ABI to the module loader that stops working
    if any driver ever needs to bind to more than one UUID:

    drivers/hid/intel-ish-hid/ishtp-fw-loader.c:1067:4: error: initializer element is not a compile-time constant

    Change the ishtp_device_id to have correct documentation and a driver_data
    field like all the other ones, and change the drivers to use the ID table
    as the primary identification in a way that works with all compilers
    and avoids duplciating the identifiers.

    Fixes: f155dfeaa4ee ("platform/x86: isthp_eclite: only load for matching devices")
    Fixes: facfe0a4fdce ("platform/chrome: chros_ec_ishtp: only load for matching devices")
    Fixes: 0d0cccc0fd83 ("HID: intel-ish-hid: hid-client: only load for matching devices")
    Fixes: 44e2a58cb880 ("HID: intel-ish-hid: fw-loader: only load for matching devices")
    Fixes: cb1a2c6847f7 ("HID: intel-ish-hid: use constants for modaliases")
    Fixes: fa443bc3c1e4 ("HID: intel-ish-hid: add support for MODULE_DEVICE_TABLE()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    [jkosina@suse.cz: fix ecl_ishtp_cl_driver.id initialization]
    [jkosina@suse.cz: fix conflict with already fixed kerneldoc]
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>