tee: optee: fix build error caused by recent optee tracepoints feature
jira LE-1907
cve CVE-2021-44733
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Jisheng Zhang <Jisheng.Zhang@synaptics.com>
commit 7ccdcaace80810175bd20b2ece856b42edd43991

If build kernel without "O=dir", below error will be seen:

In file included from drivers/tee/optee/optee_trace.h:67,
                 from drivers/tee/optee/call.c:18:
./include/trace/define_trace.h:95:42: fatal error: ./optee_trace.h: No such file or directory
   95 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
      |                                          ^
compilation terminated.

Fix it by adding below line to Makefile:
CFLAGS_call.o := -I$(src)

Tested with and without "O=dir", both can build successfully.

Fixes: 0101947dbcc3 ("tee: optee: add invoke_fn tracepoints")
	Tested-by: Heiko Thiery <heiko.thiery@gmail.com>
	Tested-by: Guenter Roeck <linux@roeck-us.net>
	Reported-by: Guenter Roeck <linux@roeck-us.net>
	Suggested-by: Steven Rostedt <rostedt@goodmis.org>
	Signed-off-by: Jisheng Zhang <Jisheng.Zhang@synaptics.com>
	Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
(cherry picked from commit 7ccdcaace80810175bd20b2ece856b42edd43991)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>