mmu_gather: fix the CONFIG_MMU_GATHER_NO_RANGE case
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2130164
CVE: CVE-2022-39188

commit 7fb5e508319068de1d69e6d7230416c390cb3cbb
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Fri, 22 Jul 2022 09:28:34 -0700

    mmu_gather: fix the CONFIG_MMU_GATHER_NO_RANGE case

    Sudip reports that alpha doesn't build properly, with errors like

      include/asm-generic/tlb.h:401:1: error: redefinition of 'tlb_update_vma_flags'
        401 | tlb_update_vma_flags(struct mmu_gather *tlb, struct vm_area_struct *vma)
            | ^~~~~~~~~~~~~~~~~~~~
      include/asm-generic/tlb.h:372:1: note: previous definition of 'tlb_update_vma_flags' with type 'void(struct mmu_gather *, struct vm_area_struct *)'
        372 | tlb_update_vma_flags(struct mmu_gather *tlb, struct vm_area_struct *vma) { }

    the cause being that We have this odd situation where some architectures
    were never converted to the newer TLB flushing interfaces that have a
    range for the flush.  Instead people left them alone, and we have them
    select the MMU_GATHER_NO_RANGE config option to make the tlb header
    files account for this.

    Peter Zijlstra cleaned some of these nasty header file games up in
    commits

      1e9fdf21a433 ("mmu_gather: Remove per arch tlb_{start,end}_vma()")
      18ba064e42df ("mmu_gather: Let there be one tlb_{start,end}_vma() implementation")

    but tlb_update_vma_flags() was left alone, and then commit b67fbebd4cf9
    ("mmu_gather: Force tlb-flush VM_PFNMAP vmas") ended up removing only
    _one_ of the two stale duplicate dummy inline functions.

    This removes the other stale one.

    Somebody braver than me should try to remove MMU_GATHER_NO_RANGE
    entirely, but it requires fixing up the oddball architectures that use
    it: alpha, m68k, microblaze, nios2 and openrisc.

    The fixups should be fairly straightforward ("fix the build errors it
    exposes by adding the appropriate range arguments"), but the reason this
    wasn't done in the first place is that so few people end up working on
    those architectures.  But it could be done one architecture at a time,
    hint, hint.

    Reported-by: Sudip Mukherjee (Codethink) <sudipm.mukherjee@gmail.com>
    Fixes: b67fbebd4cf9 ("mmu_gather: Force tlb-flush VM_PFNMAP vmas")
    Link: https://lore.kernel.org/all/YtpXh0QHWwaEWVAY@debian/
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Will Deacon <will@kernel.org>
    Cc: "Aneesh Kumar K.V" <aneesh.kumar@linux.ibm.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Nick Piggin <npiggin@gmail.com>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>