bonding: netlink error message support for options
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Jonathan Toppins <jtoppins@redhat.com>
commit 2bff369b23542ea22d0111aaa8e0b8208bf0dc96
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-448.el8/2bff369b.failed

Add support for reporting errors via extack in both bond_newlink
and bond_changelink.

Instead of having to look in the kernel log for why an option was not
correct just report the error to the user via the extack variable.

What is currently reported today:
  ip link add bond0 type bond
  ip link set bond0 up
  ip link set bond0 type bond mode 4
 RTNETLINK answers: Device or resource busy

After this change:
  ip link add bond0 type bond
  ip link set bond0 up
  ip link set bond0 type bond mode 4
 Error: unable to set option because the bond is up.

	Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
	Acked-by: Jay Vosburgh <jay.vosburgh@canonical.com>
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 2bff369b23542ea22d0111aaa8e0b8208bf0dc96)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/bonding/bond_netlink.c