PCI: endpoint: pci-epf-test: Select configfs
JIRA: https://issues.redhat.com/browse/RHEL-151449
Upstream Status: 5ddb66967924e38c680e6a304585c0f553681a3a

commit 5ddb66967924e38c680e6a304585c0f553681a3a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Feb 11 08:07:40 2026 +0100

    PCI: endpoint: pci-epf-test: Select configfs

    Like some of the other endpoint modules, pci-epf-test now also uses
    configfs, but is missing an indication in Kconfig:

      arm-linux-gnueabi-ld: drivers/pci/endpoint/functions/pci-epf-test.o: in function `pci_epf_test_add_cfs':
      pci-epf-test.c:(.text.pci_epf_test_add_cfs+0x2c): undefined reference to `config_group_init_type_name'

    Select the symbol as needed.

    Fixes: ffcc4850a161 ("PCI: endpoint: pci-epf-test: Allow overriding default BAR sizes")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202602180706.VtXkmtqL-lkp@intel.com/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Reviewed-by: Niklas Cassel <cassel@kernel.org>
    Reviewed-by: Damien Le Moal <dlemoal@kernel.org>
    Link: https://patch.msgid.link/20260211070812.4087119-1-arnd@kernel.org

Signed-off-by: Myron Stowe <mstowe@redhat.com>