Bluetooth: hci_event: Fix coding style
JIRA: https://issues.redhat.com/browse/RHEL-18222
CVE: CVE-2020-26555

commit 35d91d95a0cd61ebb90e0246dc917fd25e519b8c
Author: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Date:   Thu Oct 5 14:12:19 2023 -0700

    Bluetooth: hci_event: Fix coding style

    This fixes the following code style problem:

    ERROR: that open brace { should be on the previous line
    +       if (!bacmp(&hdev->bdaddr, &ev->bdaddr))
    +       {

    Fixes: 1ffc6f8cc332 ("Bluetooth: Reject connection with the device which has same BD_ADDR")
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: David Marlin <dmarlin@redhat.com>