bonding: bond_sysfs.c checkpatch cleanup
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author dingtianhong <dingtianhong@huawei.com>
commit 38c4916a7874aff9dc07a68bf8e7e4136b00f8dd

net/bonding/bond_sysfs.c:1302: ERROR: else should follow close brace '}'
net/bonding/bond_sysfs.c:1314: ERROR: else should follow close brace '}'

	Signed-off-by: Ding Tianhong <dingtianhong@huawei.com>
	Cc: Jay Vosburgh <fubar@us.ibm.com>
	Cc: Andy Gospodarek <andy@greyhouse.net>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 38c4916a7874aff9dc07a68bf8e7e4136b00f8dd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>