nfsd: Clean up errors in nfs3proc.c
JIRA: https://issues.redhat.com/browse/RHEL-34875

commit afb8aae519bcdbcc9d9d8d07e249fe4131381e8c
Author: KaiLong Wang <wangkailong@jari.cn>
Date:   Thu Sep 28 10:51:55 2023 +0800

    nfsd: Clean up errors in nfs3proc.c

    Fix the following errors reported by checkpatch:

    ERROR: need consistent spacing around '+' (ctx:WxV)
    ERROR: spaces required around that '?' (ctx:VxW)

    Signed-off-by: KaiLong Wang <wangkailong@jari.cn>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Benjamin Coddington <bcodding@redhat.com>