mlxsw: spectrum_router: Prevent ipv6 gateway with v4 route via replace and append
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author David Ahern <dsahern@gmail.com>
commit 7973d9e76727aa42f0824f5569e96248a572d50b

mlxsw currently does not support v6 gateways with v4 routes. Commit
19a9d136f198 ("ipv4: Flag fib_info with a fib_nh using IPv6 gateway")
prevents a route from being added, but nothing stops the replace or
append. Add a catch for them too.
    $ ip  ro add 172.16.2.0/24 via 10.99.1.2
    $ ip  ro replace 172.16.2.0/24 via inet6 fe80::202:ff:fe00:b dev swp1s0
    Error: mlxsw_spectrum: IPv6 gateway with IPv4 route is not supported.
    $ ip  ro append 172.16.2.0/24 via inet6 fe80::202:ff:fe00:b dev swp1s0
    Error: mlxsw_spectrum: IPv6 gateway with IPv4 route is not supported.

	Signed-off-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 7973d9e76727aa42f0824f5569e96248a572d50b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>