gpio: xlp: Fix build errors from Netlogic XLP removal
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071835
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set updates GPIO
 support.  It has been tested via simple boot tests and by using the
 kernel GPIO tools to verify pins are being identified and can be used.

commit e320d9c2e900d988c82021c80a3cbff488977946
Author: Rob Herring <robh@kernel.org>
Date:   Wed Dec 1 15:43:05 2021 -0600

    gpio: xlp: Fix build errors from Netlogic XLP removal

    Commit ea708ac5bf41 ("gpio: xlp: Remove Netlogic XLP variants") has
    build errors with CONFIG_ACPI:

    drivers/gpio/gpio-xlp.c:300:23: error: 'GPIO_VARIANT_VULCAN' undeclared here (not in a function)

    and !CONFIG_OF:

    drivers/gpio/gpio-xlp.c:267:11: error: 'struct gpio_chip' has no member named 'of_node'

    Fix these errors.

    Fixes: ea708ac5bf41 ("gpio: xlp: Remove Netlogic XLP variants")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Linus Walleij <linus.walleij@linaro.org>
    Cc: Bartosz Golaszewski <brgl@bgdev.pl>
    Cc: linux-gpio@vger.kernel.org
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Bartosz Golaszewski <brgl@bgdev.pl>
    (cherry picked from commit e320d9c2e900d988c82021c80a3cbff488977946)

Signed-off-by: Al Stone <ahs3@redhat.com>