xhci: split out rcar/rz support from xhci-plat.c
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2212495
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ec5499d338ece9db9b7590649d3cfcc4d7f9603d
Conflicts:
* Even though rcar/rz are not supported here, xhci-plat is. Hence, let's
  untangle the xhci-plat from the rcar code without having to merge all
  rz code, which is completely avoided here. Among other patches, this
  avoids commit <b9f20cff54f7> ("usb: gadget: udc: renesas_usb3: Add
  support for RZ/V2M") and commit <9cad72dfc556> ("usb: gadget: Add
  support for RZ/V2M USB3DRD driver")

commit ec5499d338ece9db9b7590649d3cfcc4d7f9603d
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 31 Jan 2023 16:04:31 +0100

  The USB_XHCI_RZV2M and USB_RENESAS_USB3 select other drivers
  based on the enabled SoC types, which leads to build failures
  when the dependencies are not met:

  WARNING: unmet direct dependencies detected for USB_RZV2M_USB3DRD
    Depends on [n]: USB_SUPPORT [=y] && USB_GADGET [=n] && (ARCH_R9A09G011 [=n] || COMPILE_TEST [=y])
    Selected by [m]:
    - USB_XHCI_RZV2M [=m] && USB_SUPPORT [=y] && USB [=y] && USB_XHCI_HCD [=m] && USB_XHCI_PLATFORM [=m] && (ARCH_R9A09G011 [=n] || COMPILE_TEST [=y])
  ERROR: modpost: "rzv2m_usb3drd_reset" [drivers/usb/host/xhci-plat-hcd.ko] undefined!

  The xhci-rcar driver has a reverse dependency with the xhci core, and it
  depends on the UDC driver in turn. To untangle this, make the xhci-rcar.ko
  driver a standalone module that just calls into the xhci-plat.ko module
  like other drivers do.

  This allows handling the dependency on the USB_RZV2M_USB3DRD driver to
  only affect the xhci-rcar module and simplify the xhci-plat module.

  It also allows leaving out the hacks for broken dma mask and nested
  devices from the rcar side and keep that only in the generic xhci driver.

  As a future cleanup, the marvell and dwc3 specific bits of xhci-plat.c
  could be moved out as well, but that is not required for this bugfix.

  Fixes: c52c9acc415e ("xhci: host: Add Renesas RZ/V2M SoC support")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Tested-by: Biju Das <biju.das.jz@bp.renesas.com>
  Link: https://lore.kernel.org/r/20230131150531.12347-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>