efi: sysfb_efi: remove unnecessary <asm/efi.h> include
JIRA: https://redhat.atlassian.net/browse/RHEL-168822

commit 34705a57e7df97d161324263c103c4d4d120dfe7
Author: Javier Martinez Canillas <javierm@redhat.com>
Date:   Fri Jun 10 11:00:05 2022 +0200

    efi: sysfb_efi: remove unnecessary <asm/efi.h> include

    Nothing defined in the header is used by drivers/firmware/efi/sysfb_efi.c
    but also, including it can lead to build errors when built on arches that
    don't have an asm/efi.h header file.

    This can happen for example if a driver that is built when COMPILE_TEST is
    enabled selects the SYSFB symbol, e.g. on powerpc with allyesconfig:

    drivers/firmware/efi/sysfb_efi.c:29:10: fatal error: asm/efi.h: No such file or directory
       29 | #include <asm/efi.h>
          |          ^~~~~~~~~~~

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

Signed-off-by: Thomas Huth <thuth@redhat.com>