tee: fix compiler warning in tee_shm_register()
JIRA: https://issues.redhat.com/browse/RHEL-16037

commit eccd7439709810127563e7e3e49b8b44c7b2791d
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date: Mon, 22 Aug 2022 07:43:35 +0200

    Include <linux/uaccess.h> to avoid the warning:
       drivers/tee/tee_shm.c: In function 'tee_shm_register':
    >> drivers/tee/tee_shm.c:242:14: error: implicit declaration of function 'access_ok' [-Werror=implicit-function-declaration]
         242 |         if (!access_ok((void __user *)addr, length))
             |              ^~~~~~~~~
       cc1: some warnings being treated as errors

    Fixes: 573ae4f13f63 ("tee: add overflow check in register_shm_helper()")
    Reviewed-by: Sumit Garg <sumit.garg@linaro.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Signed-off-by: Mark Salter <msalter@redhat.com>