i2c: core: Export bus recovery functions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [i2c] core: Export bus recovery functions (Gopal Tiwari) [1456705]
Rebuild_FUZZ: 93.33%
commit-author Mark Brown <broonie@kernel.org>
commit c1c21f4e60ed4523292f1a89ff45a208bddd3849

Current -next fails to link an ARM allmodconfig because drivers that use
the core recovery functions can be built as modules but those functions
are not exported:

ERROR: "i2c_generic_gpio_recovery" [drivers/i2c/busses/i2c-davinci.ko] undefined!
ERROR: "i2c_generic_scl_recovery" [drivers/i2c/busses/i2c-davinci.ko] undefined!
ERROR: "i2c_recover_bus" [drivers/i2c/busses/i2c-davinci.ko] undefined!

Add exports to fix this.

Fixes: 5f9296ba21b3c (i2c: Add bus recovery infrastructure)
	Signed-off-by: Mark Brown <broonie@kernel.org>
	Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
(cherry picked from commit c1c21f4e60ed4523292f1a89ff45a208bddd3849)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>