mlxsw: spectrum_qdisc: Fix 64-bit division error in mlxsw_sp_qdisc_tbf_rate_kbps
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 91a7d4bf3ee3794d4090cedd17b8e865645f5f79

When building arm32 allmodconfig:

ERROR: "__aeabi_uldivmod"
[drivers/net/ethernet/mellanox/mlxsw/mlxsw_spectrum.ko] undefined!

rate_bytes_ps has type u64, we need to use a 64-bit division helper to
avoid a build error.

Fixes: a44f58c41bfb ("mlxsw: spectrum_qdisc: Support offloading of TBF Qdisc")
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Reviewed-by: Ido Schimmel <idosch@mellanox.com>
	Tested-by: Ido Schimmel <idosch@mellanox.com>
	Acked-by: Jiri Pirko <jiri@mellanox.com>
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 91a7d4bf3ee3794d4090cedd17b8e865645f5f79)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>