clk: imx: fix compile testing imxrt1050
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit 64ea30d1a192e2866397169ebfe3d0109878d040
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:58:18 2022 +0100

    clk: imx: fix compile testing imxrt1050

    Randconfig testing revealed multiple issues with this driver:

    ERROR: modpost: missing MODULE_LICENSE() in drivers/clk/imx/clk-imxrt1050.o
    ERROR: modpost: "imx_clk_hw_pllv3" [drivers/clk/imx/clk-imxrt1050.ko] undefined!
    ERROR: modpost: "imx_clk_hw_pfd" [drivers/clk/imx/clk-imxrt1050.ko] undefined!

    Export the necessary symbols from the core clk driver and add the
    license and author tags. To find this type of problem more easily
    in the future, also enable building on other platforms, as we do for
    the other i.MX clk drivers.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20221215165836.2136448-1-arnd@kernel.org
    Acked-by: Jesse Taube <Mr.Bossman075@gmail.com>
    Reviewed-by: Abel Vesa <abel.vesa@linaro.org>
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>