bpf: fix link failure with NETFILTER=y INET=n
Bugzilla: https://bugzilla.redhat.com/2221599

commit 6d26d985eeda89faedabbcf6607c37454b9691b0
Author: Florian Westphal <fw@strlen.de>
Date:   Sat Apr 22 09:35:44 2023 +0200

    bpf: fix link failure with NETFILTER=y INET=n
    
    Explicitly check if NETFILTER_BPF_LINK is enabled, else configs
    that have NETFILTER=y but CONFIG_INET=n fail to link:
    
    > kernel/bpf/syscall.o: undefined reference to `netfilter_prog_ops'
    > kernel/bpf/verifier.o: undefined reference to `netfilter_verifier_ops'
    
    Fixes: fd9c663b9ad6 ("bpf: minimal support for programs hooked into netfilter framework")
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/oe-kbuild-all/202304220903.fRZTJtxe-lkp@intel.com/
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Link: https://lore.kernel.org/r/20230422073544.17634-1-fw@strlen.de
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Artem Savkov <asavkov@redhat.com>