selftests/bpf: Properly initialize linfo in sockmap_basic
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Stanislav Fomichev <sdf@google.com>
commit 48ca6243c6adf1a3d7e7a0fd519ba918eb7b00ca

When using -Werror=missing-braces, compiler complains about missing braces.
Let's use use ={} initialization which should do the job:

tools/testing/selftests/bpf/prog_tests/sockmap_basic.c: In function 'test_sockmap_iter':
tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:181:8: error: missing braces around initializer [-Werror=missing-braces]
  union bpf_iter_link_info linfo = {0};
        ^
tools/testing/selftests/bpf/prog_tests/sockmap_basic.c:181:8: error: (near initialization for 'linfo.map') [-Werror=missing-braces]
tools/testing/selftests/bpf/prog_tests/sockmap_basic.c: At top level:

	Signed-off-by: Stanislav Fomichev <sdf@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Link: https://lore.kernel.org/bpf/20201002000451.1794044-1-sdf@google.com
(cherry picked from commit 48ca6243c6adf1a3d7e7a0fd519ba918eb7b00ca)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>