perf probe: Ignore vmlinux buildid if offline kernel is given
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit 428aff82e92a29da0e4276623180f9a98f2d5b16

Ignore the buildid of running kernel when both of --definition and
--vmlinux is given because that kernel should be off-line.

This also skips post-processing of kprobe event for relocating symbol
and checking blacklist, because it can not be done on off-line kernel.

E.g. without this fix perf shows an error as below
  ----
  $ perf probe --vmlinux=./vmlinux-arm --definition do_sys_open
  ./vmlinux-arm with build id 7a1f76dd56e9c4da707cd3d6333f50748141434b not found, continuing without symbols
  Failed to find symbol do_sys_open in kernel
    Error: Failed to add events.
  ----
with this fix, we can get the definition
  ----
  $ perf probe --vmlinux=./vmlinux-arm --definition do_sys_open
  p:probe/do_sys_open do_sys_open+0
  ----

	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/147214228193.23638.12581984840822162131.stgit@devbox
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 428aff82e92a29da0e4276623180f9a98f2d5b16)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>