powerpc/64s: Fix build failure when CONFIG_PPC_64S_HASH_MMU is not set
Bugzilla: https://bugzilla.redhat.com/2120352

commit 58dbe9b373df2828d873b1c0e5afc77485b2f376
Author: Murilo Opsfelder Araujo <muriloo@linux.ibm.com>
Date:   Tue Mar 1 17:47:43 2022 -0300

    powerpc/64s: Fix build failure when CONFIG_PPC_64S_HASH_MMU is not set

    The following build failure occurs when CONFIG_PPC_64S_HASH_MMU is not
    set:

        arch/powerpc/kernel/setup_64.c: In function ‘setup_per_cpu_areas’:
        arch/powerpc/kernel/setup_64.c:811:21: error: ‘mmu_linear_psize’ undeclared (first use in this function); did you mean ‘mmu_virtual_psize’?
          811 |                 if (mmu_linear_psize == MMU_PAGE_4K)
              |                     ^~~~~~~~~~~~~~~~
              |                     mmu_virtual_psize
        arch/powerpc/kernel/setup_64.c:811:21: note: each undeclared identifier is reported only once for each function it appears in

    Move the declaration of mmu_linear_psize outside of
    CONFIG_PPC_64S_HASH_MMU ifdef.

    After the above is fixed, it fails later with the following error:

        ld: arch/powerpc/kexec/file_load_64.o: in function `.arch_kexec_kernel_image_probe':
        file_load_64.c:(.text+0x1c1c): undefined reference to `.add_htab_mem_range'

    Fix that, too, by conditioning add_htab_mem_range() symbol to
    CONFIG_PPC_64S_HASH_MMU.

    Fixes: 387e220a2e5e ("powerpc/64s: Move hash MMU support code under CONFIG_PPC_64S_HASH_MMU")
    Reported-by: Erhard F. <erhard_f@mailbox.org>
    Signed-off-by: Murilo Opsfelder Araujo <muriloo@linux.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    BugLink: https://bugzilla.kernel.org/show_bug.cgi?id=215567
    Link: https://lore.kernel.org/r/20220301204743.45133-1-muriloo@linux.ibm.com

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>