media: pvrusb2: fix pvr2_stream_callback casts
JIRA: https://issues.redhat.com/browse/RHEL-37673

commit 30baa4a96b23add91a87305baaeba82c4e109e1f
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 13 Feb 2024 11:04:27 +0100

  clang-16 complains about a control flow integrity (KCFI) issue in pvrusb2,
  which casts three different prototypes into pvr2_stream_callback:

  drivers/media/usb/pvrusb2/pvrusb2-v4l2.c:1070:30: error: cast from 'void (*)(struct pvr2_v4l2_fh *)' to 'pvr2_stream_callback' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
   1070 |         pvr2_stream_set_callback(sp,(pvr2_stream_callback)pvr2_v4l2_notify,fh);
        |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  drivers/media/usb/pvrusb2/pvrusb2-context.c:110:6: error: cast from 'void (*)(struct pvr2_context *)' to 'void (*)(void *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
    110 |                                         (void (*)(void *))pvr2_context_notify,
        |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  drivers/media/usb/pvrusb2/pvrusb2-dvb.c:152:6: error: cast from 'void (*)(struct pvr2_dvb_adapter *)' to 'pvr2_stream_callback' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
    152 |                                  (pvr2_stream_callback) pvr2_dvb_notify, adap);
        |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Change the functions to actually take a void* argument so the cast is no longer
  needed.

  Fixes: bb8ce9d9143c ("V4L/DVB (7682): pvrusb2-dvb: finish up stream & buffer handling")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>