libbpf: Fix missing #pragma in libbpf_utils.c
JIRA: https://issues.redhat.com/browse/RHEL-78291

commit 63d2247e2e37d9c589a0a26aa4e684f736a45e29
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Thu Oct 2 13:31:50 2025 -0700

    libbpf: Fix missing #pragma in libbpf_utils.c
    
    The recent sha256 patch uses a GCC pragma to suppress compile errors for
    a packed struct, but omits a needed pragma (see related link) and thus
    still raises errors: (e.g. on GCC 12.3 armhf)
    
    libbpf_utils.c:153:29: error: packed attribute causes inefficient alignment for ‘__val’ [-Werror=attributes]
      153 | struct __packed_u32 { __u32 __val; } __attribute__((packed));
          |                             ^~~~~
    
    Resolve by adding the GCC diagnostic pragma to ignore "-Wattributes".
    
    Link: https://lore.kernel.org/bpf/CAP-5=fXURWoZu2j6Y8xQy23i7=DfgThq3WC1RkGFBx-4moQKYQ@mail.gmail.com/
    
    Fixes: 4a1c9e544b8d ("libbpf: remove linux/unaligned.h dependency for libbpf_sha256()")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Acked-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Ines Qian <iqian@redhat.com>