HID: hid-lenovo-go: fix LEDS dependencies
JIRA: https://issues.redhat.com/browse/RHEL-170872
Upstream Status: since v7.1

commit 19acad732afbfb23bd0d4d5830d7553889e739f8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 24 20:20:28 2026 +0100

    HID: hid-lenovo-go: fix LEDS dependencies

    The newly added hid-lenovo-go and hid-lenovo-go-s drivers attempt to
    'select LEDS_CLASS', which has a dependency on NEW_LEDS, causing a build
    failure when NEW_LEDS itself it disabled:

    WARNING: unmet direct dependencies detected for LEDS_CLASS
      Depends on [n]: NEW_LEDS [=n]
      Selected by [m]:
      - HID_LENOVO_GO [=m] && HID_SUPPORT [=y] && HID [=m] && USB_HID [=m]
      - HID_LENOVO_GO_S [=m] && HID_SUPPORT [=y] && HID [=m] && USB_HID [=m]

    WARNING: unmet direct dependencies detected for LEDS_CLASS_MULTICOLOR
      Depends on [n]: NEW_LEDS [=n] && LEDS_CLASS [=m]
      Selected by [m]:
      - HID_LENOVO_GO [=m] && HID_SUPPORT [=y] && HID [=m] && USB_HID [=m]
      - HID_LENOVO_GO_S [=m] && HID_SUPPORT [=y] && HID [=m] && USB_HID [=m]
    ERROR: modpost: "led_set_brightness_nopm" [drivers/leds/led-class.ko] undefined!
    ERROR: modpost: "led_set_brightness" [drivers/leds/led-class.ko] undefined!
    ERROR: modpost: "led_get_color_name" [drivers/leds/led-class-multicolor.ko] undefined!
    ERROR: modpost: "led_set_brightness" [drivers/leds/led-class-multicolor.ko] undefined!

    Device drivers generally should not select other subsystems like this, as
    that tends to cause dependency problems including loops in the dependency
    graph.

    Change these two and the older hid-lenovo driver to behave the same way as all
    other HID drivers and use 'depends on LEDS_CLASS' or 'depends on LEDS_CLASS_MULTICOLOR'
    instead, which itself has NEW_LEDS and LEDS_CLASS as dependencies.

    Fixes: a23f3497bf20 ("HID: hid-lenovo-go-s: Add Lenovo Legion Go S Series HID Driver")
    Fixes: d69ccfcbc955 ("HID: hid-lenovo-go: Add Lenovo Legion Go Series HID Driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Mark Pearson <mpearson-lenovo@squebb.ca>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>