HID: wacom: Have wacom_tpc_irq guard against possible NULL dereference
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [hid] wacom: Have wacom_tpc_irq guard against possible NULL dereference (Aristeu Rozanski) [1475409 1462363]
Rebuild_FUZZ: 96.30%
commit-author Jason Gerecke <killertofu@gmail.com>
commit 2ac97f0f6654da14312d125005c77a6010e0ea38

The following Smatch complaint was generated in response to commit
2a6cdbd ("HID: wacom: Introduce new 'touch_input' device"):

    drivers/hid/wacom_wac.c:1586 wacom_tpc_irq()
             error: we previously assumed 'wacom->touch_input' could be null (see line 1577)

The 'touch_input' and 'pen_input' variables point to the 'struct input_dev'
used for relaying touch and pen events to userspace, respectively. If a
device does not have a touch interface or pen interface, the associated
input variable is NULL. The 'wacom_tpc_irq()' function is responsible for
forwarding input reports to a more-specific IRQ handler function. An
unknown report could theoretically be mistaken as e.g. a touch report
on a device which does not have a touch interface. This can be prevented
by only calling the pen/touch functions are called when the pen/touch
pointers are valid.

Fixes: 2a6cdbd ("HID: wacom: Introduce new 'touch_input' device")
	Signed-off-by: Jason Gerecke <jason.gerecke@wacom.com>
	Reviewed-by: Ping Cheng <ping.cheng@wacom.com>
	Cc: stable@vger.kernel.org
	Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit 2ac97f0f6654da14312d125005c77a6010e0ea38)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>