selftests/bpf: Initialize tc in xdp_synproxy
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2178930

commit 354bb4a0e0b6be8f55bacbe7f08c94b4741f5658
Author: Ilya Leoshkevich <iii@linux.ibm.com>
Date:   Fri Feb 3 00:53:35 2023 +0100

    selftests/bpf: Initialize tc in xdp_synproxy

    xdp_synproxy/xdp fails in CI with:

        Error: bpf_tc_hook_create: File exists

    The XDP version of the test should not be calling bpf_tc_hook_create();
    the reason it's happening anyway is that if we don't specify --tc on the
    command line, tc variable remains uninitialized.

    Fixes: 784d5dc0efc2 ("selftests/bpf: Add selftests for raw syncookie helpers in TC mode")
    Reported-by: Alexei Starovoitov <ast@kernel.org>
    Reported-by: Joanne Koong <joannelkoong@gmail.com>
    Signed-off-by: Ilya Leoshkevich <iii@linux.ibm.com>
    Link: https://lore.kernel.org/r/20230202235335.3403781-1-iii@linux.ibm.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Felix Maurer <fmaurer@redhat.com>