wifi: ath11k: mac: fix reading 16 bytes from a region of size 0 warning
Bugzilla: https://bugzilla.redhat.com/2136124

commit abf93f369419249ca482a8911039fe1c75a94227
Author: Kalle Valo <quic_kvalo@quicinc.com>
Date:   Mon Oct 10 19:06:38 2022 +0300

    wifi: ath11k: mac: fix reading 16 bytes from a region of size 0 warning
    
    Linaro reported stringop-overread warnings in ath11k (this is one of many):
    
    drivers/net/wireless/ath/ath11k/mac.c:2238:29: error: 'ath11k_peer_assoc_h_he_limit' reading 16 bytes from a region of size 0 [-Werror=stringop-overread]
    
    My further investigation showed that these warnings happen on GCC 11.3 but not
    with GCC 12.2, and with only the kernel config Linaro provided:
    
    https://builds.tuxbuild.com/2F4W7nZHNx3T88RB0gaCZ9hBX6c/config
    
    I saw the same warnings both with arm64 and x86_64 builds and KASAN seems to be
    the reason triggering these warnings with GCC 11.  Nobody else has reported
    this so this seems to be quite rare corner case. I don't know what specific
    commit started emitting this warning so I can't provide a Fixes tag. The
    function hasn't been touched for a year.
    
    I decided to workaround this by converting the pointer to a new array in stack,
    and then copying the data to the new array. It's only 16 bytes anyway and this
    is executed during association, so not in a hotpath.
    
    Tested-on: WCN6855 hw2.0 PCI WLAN.HSP.1.1-03125-QCAHSPSWPL_V1_V2_SILICONZ_LITE-3.6510.9
    
    Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
    Link: https://lore.kernel.org/all/CA+G9fYsZ_qypa=jHY_dJ=tqX4515+qrV9n2SWXVDHve826nF7Q@mail.gmail.com/
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20221010160638.20152-1-kvalo@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>