arm64: Fix bit-shifting UB in the MIDR_CPU_MODEL() macro
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2122232

commit 8ec8490a1950efeccb00967698cf7cb2fcd25ca7
Author: D Scott Phillips <scott@os.amperecomputing.com>
Date: Wed, 2 Nov 2022 09:01:06 -0700

    CONFIG_UBSAN_SHIFT with gcc-5 complains that the shifting of
    ARM_CPU_IMP_AMPERE (0xC0) into bits [31:24] by MIDR_CPU_MODEL() is
    undefined behavior. Well, sort of, it actually spells the error as:

     arch/arm64/kernel/proton-pack.c: In function 'spectre_bhb_loop_affected':
     arch/arm64/include/asm/cputype.h:44:2: error: initializer element is not constant
       (((imp)   << MIDR_IMPLEMENTOR_SHIFT) | \
       ^

    This isn't an issue for other Implementor codes, as all the other codes
    have zero in the top bit and so are representable as a signed int.

    Cast the implementor code to unsigned in MIDR_CPU_MODEL to remove the
    undefined behavior.

    Fixes: 0e5d5ae837c8 ("arm64: Add AMPERE1 to the Spectre-BHB affected list")
    Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: D Scott Phillips <scott@os.amperecomputing.com>
    Link: https://lore.kernel.org/r/20221102160106.1096948-1-scott@os.amperecomputing.com
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>