usb: dwc3: fix extcon dependency
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2190250
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7d80dbd708c18c683dd34f79b600a05307707ce8

commit 7d80dbd708c18c683dd34f79b600a05307707ce8
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 18 Jan 2023 10:01:41 +0100

  The dwc3 core support now links against the extcon subsystem,
  so it cannot be built-in when extcon is a loadable module:

  arm-linux-gnueabi-ld: drivers/usb/dwc3/core.o: in function `dwc3_get_extcon':
  core.c:(.text+0x572): undefined reference to `extcon_get_edev_by_phandle'
  arm-linux-gnueabi-ld: core.c:(.text+0x596): undefined reference to `extcon_get_extcon_dev'
  arm-linux-gnueabi-ld: core.c:(.text+0x5ea): undefined reference to `extcon_find_edev_by_node'

  There was already a Kconfig dependency in the dual-role support,
  but this is now needed for the entire dwc3 driver.

  It is still possible to build dwc3 without extcon, but this
  prevents it from being set to built-in when extcon is a loadable
  module.

  Fixes: d182c2e1bc92 ("usb: dwc3: Don't switch OTG -> peripheral if extcon is present")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
  Acked-by: Thinh Nguyen <Thinh.Nguyen@synopsys.com>
  Link: https://lore.kernel.org/r/20230118090147.2126563-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>