ASoC: amd: acp: Fix possible deadlock
JIRA: https://issues.redhat.com/browse/RHEL-80682

commit 3ff53862c322aa7bb115d84348d5a641dc905d87
Author: Daniel Baluta <daniel.baluta@nxp.com>
Date: Mon Jan 27 10:34:22 2025 +0200

    ASoC: amd: acp: Fix possible deadlock

    On error path, function acp_i2s_set_tdm_slot returns without releasing
    the lock and this could result in potential deadlocks in the future.

    Error reported by sparse:
    sound/soc/amd/acp/acp-i2s.c:95:12: error: context imbalance in
    'acp_i2s_set_tdm_slot' - different lock contexts for basic block

    Fixes: cd60dec8994c ("ASoC: amd: acp: Refactor TDM slots selction based on acp revision id")
    Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
    Reviewed-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
    Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.dev>
    Reviewed-by: Bard Liao <yung-chuan.liao@linux.intel.com>
    Link: https://patch.msgid.link/20250127083422.20406-1-daniel.baluta@nxp.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>