bpf: Reduce stack frame size by using env->insn_buf for bpf insns
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit 45e9cd38aa8df9f4673d73bb86f7c9626d513a76
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Thu Jul 3 07:11:11 2025 -0700

    bpf: Reduce stack frame size by using env->insn_buf for bpf insns
    
    Arnd Bergmann reported an issue ([1]) where clang compiler (less than
    llvm18) may trigger an error where the stack frame size exceeds the limit.
    I can reproduce the error like below:
      kernel/bpf/verifier.c:24491:5: error: stack frame size (2552) exceeds limit (1280) in 'bpf_check'
          [-Werror,-Wframe-larger-than]
      kernel/bpf/verifier.c:19921:12: error: stack frame size (1368) exceeds limit (1280) in 'do_check'
          [-Werror,-Wframe-larger-than]
    
    Use env->insn_buf for bpf insns instead of putting these insns on the
    stack. This can resolve the above 'bpf_check' error. The 'do_check' error
    will be resolved in the next patch.
    
      [1] https://lore.kernel.org/bpf/20250620113846.3950478-1-arnd@kernel.org/
    
    Reported-by: Arnd Bergmann <arnd@kernel.org>
    Tested-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20250703141111.1484521-1-yonghong.song@linux.dev
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>