ALSA: drivers: opl3: fix useless self-comparison
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 93a5b85c3c53ec99782b5973f6f6559c8f0af12c

Sparse throws the following warning:

sound/drivers/opl3/opl3_midi.c:183:60: error: self-comparison always
evaluates to false

This is likely a 16+ year old confusion between vp2 and vp.

	Suggested-by: Takashi Iwai <tiwai@suse.de>
	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20210526192957.449515-1-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 93a5b85c3c53ec99782b5973f6f6559c8f0af12c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>