bpftool: Show also the name of type BPF_OBJ_LINK
Bugzilla: https://bugzilla.redhat.com/2137876

commit 7a255ae77216237a4ce83ddea595aa4e0a812f46
Author: Yafang Shao <laoar.shao@gmail.com>
Date:   Wed Jun 29 15:48:32 2022 +0000

    bpftool: Show also the name of type BPF_OBJ_LINK
    
    For example, /sys/fs/bpf/maps.debug is a BPF link. When you run `bpftool map show`
    to show it:
    
    Before:
    
      $ bpftool map show pinned /sys/fs/bpf/maps.debug
      Error: incorrect object type: unknown
    
    After:
    
      $ bpftool map show pinned /sys/fs/bpf/maps.debug
      Error: incorrect object type: link
    
    Signed-off-by: Yafang Shao <laoar.shao@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Quentin Monnet <quentin@isovalent.com>
    Link: https://lore.kernel.org/bpf/20220629154832.56986-5-laoar.shao@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>