bpf: fix bpf_probe_read_kernel prototype mismatch
JIRA: https://issues.redhat.com/browse/RHEL-10691

commit 6a5a148aaf14747570cc634f9cdfcb0393f5617f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Aug 1 13:13:58 2023 +0200

    bpf: fix bpf_probe_read_kernel prototype mismatch

    bpf_probe_read_kernel() has a __weak definition in core.c and another
    definition with an incompatible prototype in kernel/trace/bpf_trace.c,
    when CONFIG_BPF_EVENTS is enabled.

    Since the two are incompatible, there cannot be a shared declaration in
    a header file, but the lack of a prototype causes a W=1 warning:

    kernel/bpf/core.c:1638:12: error: no previous prototype for 'bpf_probe_read_kernel' [-Werror=missing-prototypes]

    On 32-bit architectures, the local prototype

    u64 __weak bpf_probe_read_kernel(void *dst, u32 size, const void *unsafe_ptr)

    passes arguments in other registers as the one in bpf_trace.c

    BPF_CALL_3(bpf_probe_read_kernel, void *, dst, u32, size,
                const void *, unsafe_ptr)

    which uses 64-bit arguments in pairs of registers.

    As both versions of the function are fairly simple and only really
    differ in one line, just move them into a header file as an inline
    function that does not add any overhead for the bpf_trace.c callers
    and actually avoids a function call for the other one.

    Cc: stable@vger.kernel.org
    Link: https://lore.kernel.org/all/ac25cb0f-b804-1649-3afb-1dc6138c2716@iogearbox.net/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20230801111449.185301-1-arnd@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>