ASoC: nau8825: mark pm functions __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: nau8825: mark pm functions __maybe_unused (Jaroslav Kysela) [1399503]
Rebuild_FUZZ: 94.00%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 4983d32526ab6db2f8bd2288def8abf2da5f37b2

The newly added nau8825_dai_is_active() function is only called from
the PM logic that is build-time conditional in this driver, so we get
a warning when CONFIG_PM is disabled:

sound/soc/codecs/nau8825.c:229:13: error: 'nau8825_dai_is_active' defined but not used [-Werror=unused-function]
 static bool nau8825_dai_is_active(struct nau8825 *nau8825)

By replacing the #ifdef around the functions with a __maybe_unused
annotation, the code becomes more robust to this kind of problem
and we no longer get the warning while also slightly improving
readability.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: b50455fab459 ("ASoC: nau8825: cross talk suppression measurement function")
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 4983d32526ab6db2f8bd2288def8abf2da5f37b2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>