ACPI: processor: fix some coding style issues
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Xiaofei Tan <tanxiaofei@huawei.com>
commit c8deb1c2576237d27aadce0e769be4b18518fab1

Fix some coding style issues reported by checkpatch.pl, including the
following types:

ERROR: code indent should use tabs where possible
WARNING: Block comments use a trailing */ on a separate line
WARNING: Missing a blank line after declarations
WARNING: labels should not be indented

	Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit c8deb1c2576237d27aadce0e769be4b18518fab1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>