kernfs: add stub helper for kernfs_generic_poll()
JIRA: https://issues.redhat.com/browse/RHEL-34600

commit 79038a99445f69c5d28494dd4f8c6f0509f65b2e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon, 24 Jul 2023 14:18:16 +0200

    kernfs: add stub helper for kernfs_generic_poll()

    In some randconfig builds, kernfs ends up being disabled, so there is no prototype
    for kernfs_generic_poll()

    In file included from kernel/sched/build_utility.c:97:
    kernel/sched/psi.c:1479:3: error: implicit declaration of function 'kernfs_generic_poll' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    kernfs_generic_poll(t->of, wait);
                    ^

    Add a stub helper for it, as we have it for other kernfs functions.

    Fixes: aff037078ecae ("sched/psi: use kernfs polling functions for PSI trigger polling")
    Fixes: 147e1a97c4a0b ("fs: kernfs: add poll file operation")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Chengming Zhou <zhouchengming@bytedance.com>
    Link: https://lore.kernel.org/r/20230724121823.1357562-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>