RDMA: Don't reference kernel private header from UAPI header
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Leon Romanovsky <leon@kernel.org>
commit 646ebd4166ca00bdf682a36bd2e1c9a74d848ac6

Remove references to private kernel header and defines from exported
ib_user_verb.h file.

The code snippet below is used to reproduce the issue:

 #include <stdio.h>
 #include <rdma/ib_user_verb.h>

 int main(void)
 {
	printf("IB_USER_VERBS_ABI_VERSION = %d\n", IB_USER_VERBS_ABI_VERSION);
	return 0;
 }

It fails during compilation phase with an error:
➜  /tmp gcc main.c
main.c:2:31: fatal error: rdma/ib_user_verb.h: No such file or directory
 #include <rdma/ib_user_verb.h>
                               ^
compilation terminated.

Fixes: 189aba99e700 ("IB/uverbs: Extend modify_qp and support packet pacing")
CC: Bodong Wang <bodong@mellanox.com>
CC: Matan Barak <matanb@mellanox.com>
CC: Christoph Hellwig <hch@infradead.org>
	Tested-by: Slava Shwartsman <slavash@mellanox.com>
	Signed-off-by: Leon Romanovsky <leon@kernel.org>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 646ebd4166ca00bdf682a36bd2e1c9a74d848ac6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>