misc: kgdbts: Fix restrict error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Laura Abbott <labbott@redhat.com>
commit fa0218ef733e6f247a1a3986e3eb12460064ac77

kgdbts current fails when compiled with restrict:

drivers/misc/kgdbts.c: In function ‘configure_kgdbts’:
drivers/misc/kgdbts.c:1070:2: error: ‘strcpy’ source argument is the same as destination [-Werror=restrict]
  strcpy(config, opt);
  ^~~~~~~~~~~~~~~~~~~

As the error says, config is being used in both the source and destination.
Refactor the code to avoid the extra copy and put the parsing closer to
the actual location.

	Signed-off-by: Laura Abbott <labbott@redhat.com>
	Acked-by: Daniel Thompson <daniel.thompson@linaro.org>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit fa0218ef733e6f247a1a3986e3eb12460064ac77)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>