tools/power turbostat: Fix build with musl
JIRA: https://issues.redhat.com/browse/RHEL-110366

commit 6ea0ec1b958a84aff9f03fb0ae4613a4d5bed3ea
Author: Calvin Owens <calvin@wbinvd.org>
Date:   Fri Jun 13 09:54:23 2025 -0700

    tools/power turbostat: Fix build with musl

    turbostat.c: In function 'parse_int_file':
        turbostat.c:5567:19: error: 'PATH_MAX' undeclared (first use in this function)
         5567 |         char path[PATH_MAX];
              |                   ^~~~~~~~

        turbostat.c: In function 'probe_graphics':
        turbostat.c:6787:19: error: 'PATH_MAX' undeclared (first use in this function)
         6787 |         char path[PATH_MAX];
              |                   ^~~~~~~~

    Signed-off-by: Calvin Owens <calvin@wbinvd.org>
    Reviewed-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
    Signed-off-by: Len Brown <len.brown@intel.com>

Signed-off-by: Steve Best <sbest@redhat.com>