scsi: qedf: Remove unused 'num_handled' variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-527.el8
commit-author Tom Rix <trix@redhat.com>
commit 7866e03b9825e1e08fc5136d3ab9a35ebabdc7f5

clang with W=1 reports:

drivers/scsi/qedf/qedf_main.c:2227:6: error: variable
  'num_handled' set but not used [-Werror,-Wunused-but-set-variable]
        int num_handled = 0;
            ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230330203444.1842425-1-trix@redhat.com
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 7866e03b9825e1e08fc5136d3ab9a35ebabdc7f5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>