iio: frequency: adrf6780: Fix adrf6780_spi_{read,write}()
Bugzilla: http://bugzilla.redhat.com/2071780

commit 7b473ae754fec86cfa44f05f0882d1329d244e6c
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Fri Oct 22 12:56:56 2021 -0700

    iio: frequency: adrf6780: Fix adrf6780_spi_{read,write}()

    Clang warns:

    drivers/iio/frequency/adrf6780.c:117:1: error: all paths through this
    function will call itself [-Werror,-Winfinite-recursion]
    {
    ^
    drivers/iio/frequency/adrf6780.c:138:1: error: all paths through this
    function will call itself [-Werror,-Winfinite-recursion]
    {
    ^
    2 errors generated.

    The underscore variants should be used here.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1490
    Fixes: 63aaf6d06d87 ("iio: frequency: adrf6780: add support for ADRF6780")
    Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20211022195656.1513147-1-nathan@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Steve Best <sbest@redhat.com>