selftests: bridge_vlan_mcast: Delete qdiscs during cleanup
Bugzilla: https://bugzilla.redhat.com/2184372

commit 6fb1faa1b92b19e3b1fad70a800c87bee934d67b
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Tue Oct 18 09:39:58 2022 +0300

    selftests: bridge_vlan_mcast: Delete qdiscs during cleanup
    
    The qdiscs are added during setup, but not deleted during cleanup,
    resulting in the following error messages:
    
     # ./bridge_vlan_mcast.sh
     [...]
     # ./bridge_vlan_mcast.sh
     Error: Exclusivity flag on, cannot modify.
     Error: Exclusivity flag on, cannot modify.
    
    Solve by deleting the qdiscs during cleanup.
    
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Acked-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>