bpftool: Use __typeof__() instead of typeof() in BPF skeleton
JIRA: https://issues.redhat.com/browse/RHEL-30773

commit 2a24e2485722b0e12e17a2bd473bd15c9e420bdb
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Mon Apr 1 10:07:13 2024 -0700

    bpftool: Use __typeof__() instead of typeof() in BPF skeleton
    
    When generated BPF skeleton header is included in C++ code base, some
    compiler setups will emit warning about using language extensions due to
    typeof() usage, resulting in something like:
    
      error: extension used [-Werror,-Wlanguage-extension-token]
      obj->struct_ops.empty_tcp_ca = (typeof(obj->struct_ops.empty_tcp_ca))
                                      ^
    
    It looks like __typeof__() is a preferred way to do typeof() with better
    C++ compatibility behavior, so switch to that. With __typeof__() we get
    no such warning.
    
    Fixes: c2a0257c1edf ("bpftool: Cast pointers for shadow types explicitly.")
    Fixes: 00389c58ffe9 ("bpftool: Add support for subskeletons")
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Kui-Feng Lee <thinker.li@gmail.com>
    Acked-by: Quentin Monnet <qmo@kernel.org>
    Acked-by: John Fastabend <john.fastabend@gmail.com>
    Link: https://lore.kernel.org/bpf/20240401170713.2081368-1-andrii@kernel.org

Signed-off-by: Viktor Malik <vmalik@redhat.com>