ALSA: compress_offload: avoid 64-bit get_user()
JIRA: https://issues.redhat.com/browse/RHEL-80676

commit 6018f2fe1089b46c6c9eb136338eca7b16a92331
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Dec 16 10:33:41 2024 +0100

    ALSA: compress_offload: avoid 64-bit get_user()

    On some architectures, get_user() cannot read a 64-bit user variable:

    arm-linux-gnueabi-ld: sound/core/compress_offload.o: in function `snd_compr_ioctl':
    compress_offload.c:(.text.snd_compr_ioctl+0x538): undefined reference to `__get_user_bad'

    Use an equivalent copy_from_user() instead.

    Fixes: 04177158cf98 ("ALSA: compress_offload: introduce accel operation mode")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Shengjiu Wang <shengjiu.wang@gmail.com>
    Acked-by: Vinod Koul <vkoul@kernel.org>
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Link: https://patch.msgid.link/20241216093410.377112-2-arnd@kernel.org

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>