ASoC: soc-utils: Rename dummy_dma_ops to snd_dummy_dma_ops
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: soc-utils: Rename dummy_dma_ops to snd_dummy_dma_ops (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 95.08%
commit-author Matthias Kaehlcke <mka@chromium.org>
commit 42cfb412e24ffbb46d6de9590293bc44f921a0fb

The symbols 'dummy_dma_ops' is declared with different data types by
sound/soc/soc-utils.c and arch/arm64/include/asm/dma-mapping.h. This
leads to conflicts when soc-utils.c (indirectly) includes dma-mapping.h:

sound/soc/soc-utils.c:282:33: error: conflicting types for 'dummy_dma_ops'
  static const struct snd_pcm_ops dummy_dma_ops = {
                                  ^
...
arch/arm64/include/asm/dma-mapping.h:27:33: note: previous declaration of 'dummy_dma_ops' was here
  extern const struct dma_map_ops dummy_dma_ops;
                                  ^

Rename the symbol in soc-utils.c to 'snd_dummy_dma_ops' to avoid the
conflict.

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 42cfb412e24ffbb46d6de9590293bc44f921a0fb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>