mfd: arizona: Fix undefined behavior
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-372.9.1.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5da6cbcd2f395981aa9bfc571ace99f1c786c985

When the driver is used with a subdevice that is disabled in the
kernel configuration, clang gets a little confused about the
control flow and fails to notice that n_subdevs is only
uninitialized when subdevs is NULL, and we check for that,
leading to a false-positive warning:

drivers/mfd/arizona-core.c:1423:19: error: variable 'n_subdevs' is uninitialized when used here
      [-Werror,-Wuninitialized]
                              subdevs, n_subdevs, NULL, 0, NULL);
                                       ^~~~~~~~~
drivers/mfd/arizona-core.c:999:15: note: initialize the variable 'n_subdevs' to silence this warning
        int n_subdevs, ret, i;
                     ^
                      = 0

Ideally, we would rearrange the code to avoid all those early
initializations and have an explicit exit in each disabled case,
but it's much easier to chicken out and add one more initialization
here to shut up the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Charles Keepax <ckeepax@opensource.cirrus.com>
	Signed-off-by: Lee Jones <lee.jones@linaro.org>
(cherry picked from commit 5da6cbcd2f395981aa9bfc571ace99f1c786c985)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>