ALSA: aw2: avoid casting function pointers
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 022a13a1db302d55aad3c7c4c40d2c9392f3842b
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Feb 13 11:13:19 2024 +0100

    ALSA: aw2: avoid casting function pointers

    clang-16 started warning about incompatible function pointers here:

    sound/pci/aw2/aw2-alsa.c:363:11: error: cast from 'void (*)(struct snd_pcm_substream *)' to 'snd_aw2_saa7146_it_cb' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
      363 |                                                     (snd_aw2_saa7146_it_cb)
          |                                                     ^~~~~~~~~~~~~~~~~~~~~~~
      364 |                                                     snd_pcm_period_elapsed,
          |                                                     ~~~~~~~~~~~~~~~~~~~~~~
    sound/pci/aw2/aw2-alsa.c:392:10: error: cast from 'void (*)(struct snd_pcm_substream *)' to 'snd_aw2_saa7146_it_cb' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
      392 |                                                    (snd_aw2_saa7146_it_cb)
          |                                                    ^~~~~~~~~~~~~~~~~~~~~~~
      393 |                                                    snd_pcm_period_elapsed,
          |                                                    ~~~~~~~~~~~~~~~~~~~~~~

    Add a forward declaration for struct snd_pcm_substrea to allow it to just
    use the correct prototype.

    Fixes: 98f2a97f207a ("[ALSA] Emagic Audiowerk 2 ALSA driver.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240213101327.460191-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>