PCI/MSI: Handle lack of irqdomain gracefully
JIRA: https://issues.redhat.com/browse/RHEL-107953

commit a60b990798eb17433d0283788280422b1bd94b18
Author: Thomas Gleixner <tglx@linutronix.de>
Date:   Sat Dec 14 12:50:18 2024 +0100

    Alexandre observed a warning emitted from pci_msi_setup_msi_irqs() on a
    RISCV platform which does not provide PCI/MSI support:

     WARNING: CPU: 1 PID: 1 at drivers/pci/msi/msi.h:121 pci_msi_setup_msi_irqs+0x2c/0x32
     __pci_enable_msix_range+0x30c/0x596
     pci_msi_setup_msi_irqs+0x2c/0x32
     pci_alloc_irq_vectors_affinity+0xb8/0xe2

    RISCV uses hierarchical interrupt domains and correctly does not implement
    the legacy fallback. The warning triggers from the legacy fallback stub.

    That warning is bogus as the PCI/MSI layer knows whether a PCI/MSI parent
    domain is associated with the device or not. There is a check for MSI-X,
    which has a legacy assumption. But that legacy fallback assumption is only
    valid when legacy support is enabled, but otherwise the check should simply
    return -ENOTSUPP.

    Loongarch tripped over the same problem and blindly enabled legacy support
    without implementing the legacy fallbacks. There are weak implementations
    which return an error, so the problem was papered over.

    Correct pci_msi_domain_supports() to evaluate the legacy mode and add
    the missing supported check into the MSI enable path to complete it.

    Fixes: d2a463b29741 ("PCI/MSI: Reject multi-MSI early")
    Reported-by: Alexandre Ghiti <alexghiti@rivosinc.com>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Tested-by: Alexandre Ghiti <alexghiti@rivosinc.com>
    Cc: stable@vger.kernel.org
    Link: https://lore.kernel.org/all/87ed2a8ow5.ffs@tglx

Signed-off-by: Frank Liang <xiliang@redhat.com>