Bluetooth: hci_intel: Fix multiple issues reported by checkpatch.pl
JIRA: https://issues.redhat.com/browse/RHEL-61734

commit 62f7de372c9452e200fde215628903758c3df6c4
Author: Uri Arev <me@wantyapps.xyz>
Date:   Tue Apr 2 21:37:45 2024 +0300

    Bluetooth: hci_intel: Fix multiple issues reported by checkpatch.pl

    This fixes the following CHECKs, WARNINGs, and ERRORs reported in
    hci_intel.c

    Reported by checkpatch.pl:
    -----------
    hci_intel.c
    -----------
    WARNING: Prefer using '"%s...", __func__' to using 'intel_setup', this
            function's name, in a string
    +       bt_dev_dbg(hdev, "start intel_setup");

    ERROR: code indent should use tabs where possible
    +        /* Check for supported iBT hardware variants of this firmware$

    ERROR: code indent should use tabs where possible
    +         * loading method.$

    ERROR: code indent should use tabs where possible
    +         *$

    ERROR: code indent should use tabs where possible
    +         * This check has been put in place to ensure correct forward$

    ERROR: code indent should use tabs where possible
    +         * compatibility options when newer hardware variants come along.$

    ERROR: code indent should use tabs where possible
    +         */$

    CHECK: No space is necessary after a cast
    +       duration = (unsigned long long) ktime_to_ns(delta) >> 10;

    CHECK: No space is necessary after a cast
    +       duration = (unsigned long long) ktime_to_ns(delta) >> 10;

    WARNING: Missing a blank line after declarations
    +               int err = PTR_ERR(intel->rx_skb);
    +               bt_dev_err(hu->hdev, "Frame reassembly failed (%d)", err);

    Signed-off-by: Uri Arev <me@wantyapps.xyz>
    Suggested-by: Luiz Augusto von Dentz <luiz.dentz@gmail.com>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>