entry: Fix compile error in dynamic_irqentry_exit_cond_resched()
Bugzilla: http://bugzilla.redhat.com/2065226
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git sched/urgent

commit 0a70045ed8516dfcff4b5728557e1ef3fd017c53
Author: Sven Schnelle <svens@linux.ibm.com>
Date:   Wed Mar 30 10:43:28 2022 +0200

    entry: Fix compile error in dynamic_irqentry_exit_cond_resched()

    kernel/entry/common.c: In function ‘dynamic_irqentry_exit_cond_resched’:
    kernel/entry/common.c:409:14: error: implicit declaration of function ‘static_key_unlikely’; did you mean ‘static_key_enable’? [-Werror=implicit-function-declaration]
      409 |         if (!static_key_unlikely(&sk_dynamic_irqentry_exit_cond_resched))
          |              ^~~~~~~~~~~~~~~~~~~
          |              static_key_enable

    static_key_unlikely() should be static_branch_unlikely().

    Fixes: 99cf983cc8bca ("sched/preempt: Add PREEMPT_DYNAMIC using static keys")
    Signed-off-by: Sven Schnelle <svens@linux.ibm.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Mark Rutland <mark.rutland@arm.com>
    Link: https://lore.kernel.org/r/20220330084328.1805665-1-svens@linux.ibm.com

Signed-off-by: Phil Auld <pauld@redhat.com>