Bluetooth: fix set_ecdh_privkey() prototype
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 8ff0278d106753a553d6cb2cf49a8888425b8187

gcc-11 points out that the declaration does not match the definition:

net/bluetooth/ecdh_helper.c:122:55: error: argument 2 of type ‘const u8[32]’ {aka ‘const unsigned char[32]’} with mismatched bound [-Werror=array-parameter=]
  122 | int set_ecdh_privkey(struct crypto_kpp *tfm, const u8 private_key[32])
      |                                              ~~~~~~~~~^~~~~~~~~~~~~~~
In file included from net/bluetooth/ecdh_helper.c:23:
net/bluetooth/ecdh_helper.h:28:56: note: previously declared as ‘const u8 *’ {aka ‘const unsigned char *’}
   28 | int set_ecdh_privkey(struct crypto_kpp *tfm, const u8 *private_key);
      |                                              ~~~~~~~~~~^~~~~~~~~~~

Change the declaration to contain the size of the array, rather than
just a pointer.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
(cherry picked from commit 8ff0278d106753a553d6cb2cf49a8888425b8187)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>