tools: bpftool: fix infinite loop in map create
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Alban Crequy <alban@kinvolk.io>
commit 8694d8c1f82cccec9380e0d3720b84eee315dfb7

"bpftool map create" has an infinite loop on "while (argc)". The error
case is missing.

Symptoms: when forgetting to type the keyword 'type' in front of 'hash':
$ sudo bpftool map create /sys/fs/bpf/dir/foobar hash key 8 value 8 entries 128
(infinite loop, taking all the CPU)
^C

After the patch:
$ sudo bpftool map create /sys/fs/bpf/dir/foobar hash key 8 value 8 entries 128
Error: unknown arg hash

Fixes: 0b592b5a01be ("tools: bpftool: add map create command")
	Signed-off-by: Alban Crequy <alban@kinvolk.io>
	Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
	Acked-by: Song Liu <songliubraving@fb.com>
	Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit 8694d8c1f82cccec9380e0d3720b84eee315dfb7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>