bitfield: build kunit tests without structleak plugin
commit a8cf90332ae3e2b53813a146a99261b6a5e16a73
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 29 14:27:13 2021 -0700

    bitfield: build kunit tests without structleak plugin

    The structleak plugin causes the stack frame size to grow immensely:

    lib/bitfield_kunit.c: In function 'test_bitfields_constants':
    lib/bitfield_kunit.c:93:1: error: the frame size of 7440 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

    Turn it off in this file.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Brendan Higgins <brendanhiggins@google.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>