iio: test: fix missing MODULE_LICENSE for IIO_RESCALE=m
commit 7a2f6f61e8ee016b75e1b1dd62fbd03e6d6db37d
Author: Liam Beguin <liambeguin@gmail.com>
Date:   Wed Jun 1 10:21:38 2022 -0400

    iio: test: fix missing MODULE_LICENSE for IIO_RESCALE=m

    When IIO_RESCALE_KUNIT_TEST=y and IIO_RESCALE=m,
    drivers/iio/afe/iio-rescale.o is built twice causing the
    MODULE_LICENSE() to be lost, as shown by:

      ERROR: modpost: missing MODULE_LICENSE() in drivers/iio/afe/iio-rescale.o

    Rework the build configuration to have the dependency specified in the
    Kconfig.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: 8e74a48d17d5 ("iio: test: add basic tests for the iio-rescale driver")
    Signed-off-by: Liam Beguin <liambeguin@gmail.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Reviewed-by: Masahiro Yamada <masahiroy@kernel.org>
    Link: https://lore.kernel.org/r/20220601142138.3331278-1-liambeguin@gmail.com
    Cc: <Stable@vger.kernel.org>
    Signed-off-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>