hwmon: (ibmpowernv) Fix build error seen for some configurations
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [hwmon] ibmpowernv: Fix build error seen for some configurations (Gustavo Duarte) [1224367]
Rebuild_FUZZ: 91.67%
commit-author Guenter Roeck <linux@roeck-us.net>
commit 8416915c16d4335980c5d5d6d39957adbfe40b55
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/8416915c.failed

Fix
drivers/hwmon/ibmpowernv.c: In function 'get_logical_cpu':
drivers/hwmon/ibmpowernv.c:121:3:
	error: implicit declaration of function 'get_hard_smp_processor_id'

seen for some configurations, possibly if SMP is not configured.

Fixes: 3df2f59f0aae ("hwmon: (ibmpowernv) pretty print labels")
	Cc: Cédric Le Goater <clg@fr.ibm.com>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
(cherry picked from commit 8416915c16d4335980c5d5d6d39957adbfe40b55)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/hwmon/ibmpowernv.c