usb: ohci-omap: avoid unused-variable warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2212495
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=903b39e119245b52b9e929984189d7c96aa44d55

commit 903b39e119245b52b9e929984189d7c96aa44d55
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 18 Jan 2023 09:27:34 +0100

  The dead code removal has led to 'need_transceiver' not being
  used at all when OTG support is disabled:

  drivers/usb/host/ohci-omap.c: In function 'ohci_omap_reset':
  drivers/usb/host/ohci-omap.c:99:33: error: unused variable 'need_transceiver' [-Werror=unused-variable]
     99 |         int                     need_transceiver = (config->otg != 0);

  Change the #ifdef check into an IS_ENABLED() check to make the
  code more readable and let the compiler see where it is used.

  Fixes: 8825acd7cc8a ("ARM: omap1: remove dead code")
  Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
  Acked-by: Alan Stern <stern@rowland.harvard.edu>
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>