ath11k: fix link error when CONFIG_REMOTEPROC is disabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Kalle Valo <kvalo@codeaurora.org>
commit 5c0ec012ca7f7771f4a2dc9e41333411dd2693bc

If CONFIG_REMOTEPROC was disabled the linking failed with:

ERROR: modpost: "rproc_get_by_phandle" [drivers/net/wireless/ath/ath11k/ath11k.ko] undefined!

Compile tested only.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
Fixes: 1ff8ed786d5d ("ath11k: use remoteproc only with AHB devices")
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/0101017476e38f40-c4168ac4-c00a-4220-a032-fe17e4a157cb-000000@us-west-2.amazonses.com
(cherry picked from commit 5c0ec012ca7f7771f4a2dc9e41333411dd2693bc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>