radix-tree: add missing cleanup.h
JIRA: https://issues.redhat.com/browse/RHEL-78197

upstream
========
commit be8254f694469e60252e35c467ac9a878d7797bf
Author: Daniel Gomez <da.gomez@samsung.com>
Date: Fri Mar 21 20:24:33 2025 +0000

description
===========
Add shared cleanup.h header for radix-tree testing tools.

Fixes build error found with kdevops [1]:

cc -I../shared -I. -I../../include -I../../../lib -g -Og -Wall
-D_LGPL_SOURCE -fsanitize=address -fsanitize=undefined   -c -o
radix-tree.o radix-tree.c
In file included from ../shared/linux/idr.h:1,
                 from radix-tree.c:18:
../shared/linux/../../../../include/linux/idr.h:18:10: fatal error:
linux/cleanup.h: No such file or directory
   18 | #include <linux/cleanup.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: radix-tree.o] Error 1

[1] https://github.com/linux-kdevops/kdevops
https://github.com/linux-kdevops/linux-mm-kpd/
actions/runs/13971648496/job/39114756401

[akpm@linux-foundation.org: remove unneeded header guards, per Sidhartha]
    Link: https://lkml.kernel.org/r/20250321-fix-radix-tree-build-v1-1-838a1e6540e2@samsung.com
Fixes: 6c8b0b835f00 ("perf/core: Simplify perf_pmu_register()")
    Signed-off-by: Daniel Gomez <da.gomez@samsung.com>
    Cc: Daniel Gomez <da.gomez@samsung.com>
    Cc: Ingo Molnar <mingo@kernel.org>
    Cc: Liam Howlett <liam.howlett@oracle.com>
    Cc: Luis Chamberalin <mcgrof@kernel.org>
    Cc: Matthew Wilcox (Oracle) <willy@infradead.org>
    Cc: Ravi Bangoria <ravi.bangoria@amd.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Sidhartha Kumar <sidhartha.kumar@oracle.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>