perf tests wp: Remove unused functions on s390
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit ccb05590c4325ce50b1c0deedd54d5f24f4f1652
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Nov 16 13:02:52 2021 -0300

description
===========
Fixing these build problems:

  tests/wp.c:24:12: error: 'wp_read' defined but not used [-Werror=unused-function]
   static int wp_read(int fd, long long *count, int size)
              ^
  tests/wp.c:35:13: error: 'get__perf_event_attr' defined but not used [-Werror=unused-function]
   static void get__perf_event_attr(struct perf_event_attr *attr, int wp_type,
               ^
    CC      /tmp/build/perf/util/print_binary.o

Fixes: e47c6ecaae1df54a ("perf test: Convert watch point tests to test cases.")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>