perf annotate: Use capstone_init and remove open_capstone_handle from disasm.c
JIRA: https://issues.redhat.com/browse/RHEL-29796

upstream
========
commit f1e9347c855de73d8df1b0fa763184a46548d62f
Author: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
Date: Thu Jul 18 14:13:56 2024 +0530

description
===========
capstone_init is made availbale for all archs to use and updated to
enable support for CS_ARCH_PPC as well. Patch removes
open_capstone_handle and uses capstone_init in all the places.

Committer notes:

Avoid including capstone/capstone.h from print_insn.h to not break the
build in builtin-script.c due to the namespace clash with libbpf:

  /usr/include/capstone/bpf.h:94:14: error: 'bpf_insn' defined as wrong kind of tag

    Reviewed-by: Kajol Jain <kjain@linux.ibm.com>
    Reviewed-by: Namhyung Kim <namhyung@kernel.org>
    Signed-off-by: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
    Tested-by: Kajol Jain <kjain@linux.ibm.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Akanksha J N <akanksha@linux.ibm.com>
    Cc: Christophe Leroy <christophe.leroy@csgroup.eu>
    Cc: Disha Goel <disgoel@linux.vnet.ibm.com>
    Cc: Hari Bathini <hbathini@linux.ibm.com>
    Cc: Ian Rogers <irogers@google.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Madhavan Srinivasan <maddy@linux.ibm.com>
    Cc: Segher Boessenkool <segher@kernel.crashing.org>
    Link: https://lore.kernel.org/lkml/20240718084358.72242-14-atrajeev@linux.vnet.ibm.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>