ASoC: pxa: add GPIOLIB_LEGACY dependency
JIRA: https://issues.redhat.com/browse/RHEL-118910

commit 2d86d2585ab929a143d1e6f8963da1499e33bf13
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Aug 8 17:18:05 2025 +0200

    ASoC: pxa: add GPIOLIB_LEGACY dependency

    The pxa27x platform uses the legacy gpiolib interfaces, including
    in its sound drivers:

    sound/arm/pxa2xx-ac97-lib.c: In function 'pxa2xx_ac97_hw_probe':
    sound/arm/pxa2xx-ac97-lib.c:374:23: error: implicit declaration of function 'gpio_request_one' [-Wimplicit-function-declaration]
      374 |                 ret = gpio_request_one(reset_gpio, GPIOF_OUT_INIT_HIGH,

    Make sure we don't select those drivers for compile-testing unless
    we are building for a pxa27x system, or CONFIG_GPIOLIB_LEGACY is
    already enabled.

    The SND_PXA_SOC_SSP driver accidentally used a dependency on PLAT_PXA,
    which includes both ARCH_PXA and ARCH_MMP, but it is only used on
    the former.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250808151822.536879-21-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>