x86: xen: add missing prototypes
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit fb9b7b4b2b82d72031bff6d615215c1c74064bb3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jun 14 09:35:01 2023 +0200

    x86: xen: add missing prototypes

    These function are all called from assembler files, or from inline
    assembler, so there is no immediate need for a prototype in a header,
    but if -Wmissing-prototypes is enabled, the compiler warns about them:

    arch/x86/xen/efi.c:130:13: error: no previous prototype for 'xen_efi_init' [-Werror=missing-prototypes]
    arch/x86/platform/pvh/enlighten.c:120:13: error: no previous prototype for 'xen_prepare_pvh' [-Werror=missing-prototypes]
    arch/x86/xen/enlighten_pv.c:1233:34: error: no previous prototype for 'xen_start_kernel' [-Werror=missing-prototypes]
    arch/x86/xen/irq.c:22:14: error: no previous prototype for 'xen_force_evtchn_callback' [-Werror=missing-prototypes]
    arch/x86/entry/common.c:302:24: error: no previous prototype for 'xen_pv_evtchn_do_upcall' [-Werror=missing-prototypes]

    Declare all of them in an appropriate header file to avoid the warnings.
    For consistency, also move the asm_cpu_bringup_and_idle() declaration
    out of smp_pv.c.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Juergen Gross <jgross@suse.com>
    Reviewed-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
    Link: https://lore.kernel.org/r/20230614073501.10101-3-jgross@suse.com
    Signed-off-by: Juergen Gross <jgross@suse.com>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>