ethernet: fix PTP_1588_CLOCK dependencies
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2066451
Upstream Status: net.git commit e5f31552674e

Conflicts: context conflicts due to apply commit
55c8fca1dae1 ("ptp_pch: Restore dependency on PCI") first.

commit e5f31552674e88bff3a4e3ca3e5357668b5f2973
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 12 20:33:58 2021 +0200

    ethernet: fix PTP_1588_CLOCK dependencies

    The 'imply' keyword does not do what most people think it does, it only
    politely asks Kconfig to turn on another symbol, but does not prevent
    it from being disabled manually or built as a loadable module when the
    user is built-in. In the ICE driver, the latter now causes a link failure:

    aarch64-linux-ld: drivers/net/ethernet/intel/ice/ice_main.o: in function `ice_eth_ioctl':
    ice_main.c:(.text+0x13b0): undefined reference to `ice_ptp_get_ts_config'
    ice_main.c:(.text+0x13b0): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `ice_ptp_get_ts_config'
    aarch64-linux-ld: ice_main.c:(.text+0x13bc): undefined reference to `ice_ptp_set_ts_config'
    ice_main.c:(.text+0x13bc): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `ice_ptp_set_ts_config'
    aarch64-linux-ld: drivers/net/ethernet/intel/ice/ice_main.o: in function `ice_prepare_for_reset':
    ice_main.c:(.text+0x31fc): undefined reference to `ice_ptp_release'
    ice_main.c:(.text+0x31fc): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `ice_ptp_release'
    aarch64-linux-ld: drivers/net/ethernet/intel/ice/ice_main.o: in function `ice_rebuild':

    This is a recurring problem in many drivers, and we have discussed
    it several times befores, without reaching a consensus. I'm providing
    a link to the previous email thread for reference, which discusses
    some related problems.

    To solve the dependency issue better than the 'imply' keyword, introduce a
    separate Kconfig symbol "CONFIG_PTP_1588_CLOCK_OPTIONAL" that any driver
    can depend on if it is able to use PTP support when available, but works
    fine without it. Whenever CONFIG_PTP_1588_CLOCK=m, those drivers are
    then prevented from being built-in, the same way as with a 'depends on
    PTP_1588_CLOCK || !PTP_1588_CLOCK' dependency that does the same trick,
    but that can be rather confusing when you first see it.

    Since this should cover the dependencies correctly, the IS_REACHABLE()
    hack in the header is no longer needed now, and can be turned back
    into a normal IS_ENABLED() check. Any driver that gets the dependency
    wrong will now cause a link time failure rather than being unable to use
    PTP support when that is in a loadable module.

    However, the two recently added ptp_get_vclocks_index() and
    ptp_convert_timestamp() interfaces are only called from builtin code with
    ethtool and socket timestamps, so keep the current behavior by stubbing
    those out completely when PTP is in a loadable module. This should be
    addressed properly in a follow-up.

    As Richard suggested, we may want to actually turn PTP support into a
    'bool' option later on, preventing it from being a loadable module
    altogether, which would be one way to solve the problem with the ethtool
    interface.

    Fixes: 06c16d89d2cb ("ice: register 1588 PTP clock device object for E810 devices")
    Link: https://lore.kernel.org/netdev/20210804121318.337276-1-arnd@kernel.org/
    Link: https://lore.kernel.org/netdev/CAK8P3a06enZOf=XyZ+zcAwBczv41UuCTz+=0FMf2gBz1_cOnZQ@mail.gmail.com/
    Link: https://lore.kernel.org/netdev/CAK8P3a3=eOxE-K25754+fB_-i_0BZzf9a9RfPTX3ppSwu9WZXw@mail.gmail.com/
    Link: https://lore.kernel.org/netdev/20210726084540.3282344-1-arnd@kernel.org/
    Acked-by: Shannon Nelson <snelson@pensando.io>
    Acked-by: Jacob Keller <jacob.e.keller@intel.com>
    Acked-by: Richard Cochran <richardcochran@gmail.com>
    Reviewed-by: Vladimir Oltean <vladimir.oltean@nxp.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20210812183509.1362782-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>