net/sched: mqprio: add an extack message to mqprio_parse_opt()
JIRA: https://issues.redhat.com/browse/RHEL-1773

commit ab277d2084ba59956b177a7d417791a27361e283
Author: Vladimir Oltean <vladimir.oltean@nxp.com>
Date:   Tue Apr 11 21:01:52 2023 +0300

    net/sched: mqprio: add an extack message to mqprio_parse_opt()

    Ferenc reports that a combination of poor iproute2 defaults and obscure
    cases where the kernel returns -EINVAL make it difficult to understand
    what is wrong with this command:

    $ ip link add veth0 numtxqueues 8 numrxqueues 8 type veth peer name veth1
    $ tc qdisc add dev veth0 root mqprio num_tc 8 map 0 1 2 3 4 5 6 7 \
            queues 1@0 1@1 1@2 1@3 1@4 1@5 1@6 1@7
    RTNETLINK answers: Invalid argument

    Hopefully with this patch, the cause is clearer:

    Error: Device does not support hardware offload.

    The kernel was (and still is) rejecting this because iproute2 defaults
    to "hw 1" if this command line option is not specified.

    Link: https://lore.kernel.org/netdev/ede5e9a2f27bf83bfb86d3e8c4ca7b34093b99e2.camel@inf.elte.hu/
    Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
    Reviewed-by: Ferenc Fejes <fejes@inf.elte.hu>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Acked-by: Jamal Hadi Salim <jhs@mojatatu.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>