drm/amd/pm: avoid large variable on kernel stack
jira LE-1907
Rebuild_History Non-Buildable kernel-rt-4.18.0-477.10.1.rt7.274.el8_8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 76a95b833ac75dfc62e8ca0d8acd337a683061f4

The activity_monitor_external[] array is too big to fit on the
kernel stack, resulting in this warning with clang:

drivers/gpu/drm/amd/amdgpu/../pm/swsmu/smu13/smu_v13_0_7_ppt.c:1438:12: error: stack frame size (1040) exceeds limit (1024) in 'smu_v13_0_7_get_power_profile_mode' [-Werror,-Wframe-larger-than]

Use dynamic allocation instead. It should also be possible to
have single element here instead of the array, but this seems
easier.

v2: fix up argument to sizeof() (Alex)

Fixes: 334682ae8151 ("drm/amd/pm: enable workload type change on smu_v13_0_7")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 76a95b833ac75dfc62e8ca0d8acd337a683061f4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>