ASoC: Intel: sof_rt5682: shrink platform_id names below 20 characters
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 590cfb082837cc6c0c595adf1711330197c86a58

Some Chromebooks machine driver aliases exceed 20 characters, which
leads to sparse warnings:

sound/soc/intel/boards/sof_rt5682.c:959:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:989:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:1039:25: error: too long
initializer-string for array of char(no space for nul char)

Fix by using the 'mx' shortcut for Maxim platforms (already used in
platform firmware)

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
	Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
	Reviewed-by: Rander Wang <rander.wang@intel.com>
Link: https://lore.kernel.org/r/20210621194057.21711-4-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 590cfb082837cc6c0c595adf1711330197c86a58)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>