ASoC: sophgo: fix 64-bit division build failure
JIRA: https://issues.redhat.com/browse/RHEL-168082

commit cad9720dd7e4dcdaec8e854fb2c1d1d45fd6dbad
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Feb 2 10:53:14 2026 +0100

    ASoC: sophgo: fix 64-bit division build failure

    cv1800b_adc_setbclk_div() does four 64-bit divisions in a row, which
    is rather inefficient on 32-bit systems, and using the plain division
    causes a build failure as a result:

    ERROR: modpost: "__aeabi_uldivmod" [sound/soc/sophgo/cv1800b-sound-adc.ko] undefined!

    Consolidate those into a single division using the div_u64() macro.

    Fixes: 4cf8752a03e6 ("ASoC: sophgo: add CV1800B internal ADC codec driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260202095323.1233553-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>