netfilter: nf_tables: bogus ENOENT when destroying element which does not exist
JIRA: https://issues.redhat.com/browse/RHEL-21443
Upstream Status: commit a7d5a955bfa8

commit a7d5a955bfa854ac6b0c53aaf933394b4e6139e4
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Mon Nov 13 20:34:56 2023 +0100

    netfilter: nf_tables: bogus ENOENT when destroying element which does not exist

    destroy element command bogusly reports ENOENT in case a set element
    does not exist. ENOENT errors are skipped, however, err is still set
    and propagated to userspace.

     # nft destroy element ip raw BLACKLIST { 1.2.3.4 }
     Error: Could not process rule: No such file or directory
     destroy element ip raw BLACKLIST { 1.2.3.4 }
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Fixes: f80a612dd77c ("netfilter: nf_tables: add support to destroy operation")
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>