RDMA/iw_cxgb4: Use kfree_skb instead of kfree
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Hariprasad S <hariprasad@chelsio.com>
commit 56b2eca3fea8ea4fb6ec732b98470a09385cb1eb

The commit 0f8ab0b6e91b4d53 ("RDMA/iw_cxgb4: Low resource fixes for Memory
registration") from Jun 10, 2016, leads to the following static checker
warning:

        drivers/infiniband/hw/cxgb4/mem.c:612 c4iw_alloc_mw()
        error: use kfree_skb() here instead of kfree(mhp->dereg_skb)

Also fixes skb leak in c4iw_dealloc_mw

Fixes: 0f8ab0b6e91b4d53 ("RDMA/iw_cxgb4: Low resource fixes for Memory registration")

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Steve Wise <swise@opengridcomputing.com>
	Signed-off-by: Hariprasad Shenai <hariprasad@chelsio.com>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 56b2eca3fea8ea4fb6ec732b98470a09385cb1eb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>