ALSA: hda/ca0132 - make pci_iounmap() call conditional
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 1e73359a24fad529b0794515b46cbfff99e5fbe6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1062.el7/1e73359a.failed

When building without CONFIG_PCI, we can (depending on the architecture)
get a link failure:

ERROR: "pci_iounmap" [sound/pci/hda/snd-hda-codec-ca0132.ko] undefined!

Adding a compile-time check for PCI gets it to work correctly on
32-bit ARM.

Fixes: d99501b8575d ("ALSA: hda/ca0132 - Call pci_iounmap() instead of iounmap()")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 1e73359a24fad529b0794515b46cbfff99e5fbe6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	sound/pci/hda/patch_ca0132.c