blk-iocost: Fix error on iocost_ioc_vrate_adj
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Waiman Long <longman@redhat.com>
commit d6c8e949a35d6906d6c03a50e9a9cdf4e494528a

Systemtap 4.2 is unable to correctly interpret the "u32 (*missed_ppm)[2]"
argument of the iocost_ioc_vrate_adj trace entry defined in
include/trace/events/iocost.h leading to the following error:

  /tmp/stapAcz0G0/stap_c89c58b83cea1724e26395efa9ed4939_6321_aux_6.c:78:8:
  error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
   , u32[]* __tracepoint_arg_missed_ppm

That argument type is indeed rather complex and hard to read. Looking
at block/blk-iocost.c. It is just a 2-entry u32 array. By simplifying
the argument to a simple "u32 *missed_ppm" and adjusting the trace
entry accordingly, the compilation error was gone.

Fixes: 7caa47151ab2 ("blkcg: implement blk-iocost")
	Acked-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
	Acked-by: Tejun Heo <tj@kernel.org>
	Signed-off-by: Waiman Long <longman@redhat.com>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit d6c8e949a35d6906d6c03a50e9a9cdf4e494528a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>