net/sched: act_gact: Add extack messages for offload failure
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit 69642c2ab2f553fd8c4c121fcdf3b3054c727e86
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:23 2022 +0300

    net/sched: act_gact: Add extack messages for offload failure

    For better error reporting to user space, add extack messages when gact
    action offload fails.

    Example:

     # echo 1 > /sys/kernel/tracing/events/netlink/netlink_extack/enable

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action continue
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-181     [002] b..1.   105.493450: netlink_extack: msg=act_gact: Offload of "continue" action is not supported
           tc-181     [002] .....   105.493466: netlink_extack: msg=cls_matchall: Failed to setup flow action

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action reclassify
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-183     [002] b..1.   124.126477: netlink_extack: msg=act_gact: Offload of "reclassify" action is not supported
           tc-183     [002] .....   124.126489: netlink_extack: msg=cls_matchall: Failed to setup flow action

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action pipe action drop
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-185     [002] b..1.   137.097791: netlink_extack: msg=act_gact: Offload of "pipe" action is not supported
           tc-185     [002] .....   137.097804: netlink_extack: msg=cls_matchall: Failed to setup flow action

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>