selftests/bpf: Fix errors compiling cg_storage_multi.h with musl libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 730561d3c08d4a327cceaabf11365958a1c00cec
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:46 2024 -0700

    selftests/bpf: Fix errors compiling cg_storage_multi.h with musl libc

    Remove a redundant include of '<asm/types.h>', whose needed definitions are
    already included (via '<linux/types.h>') in cg_storage_multi_egress_only.c,
    cg_storage_multi_isolated.c, and cg_storage_multi_shared.c. This avoids
    redefinition errors seen compiling for mips64el/musl-libc like:

      In file included from progs/cg_storage_multi_egress_only.c:13:
      In file included from progs/cg_storage_multi.h:6:
      In file included from /usr/mips64el-linux-gnuabi64/include/asm/types.h:23:
      /usr/include/asm-generic/int-l64.h:29:25: error: typedef redefinition with different types ('long' vs 'long long')
         29 | typedef __signed__ long __s64;
            |                         ^
      /usr/include/asm-generic/int-ll64.h:30:44: note: previous definition is here
         30 | __extension__ typedef __signed__ long long __s64;
            |                                            ^

    Fixes: 9e5bd1f7633b ("selftests/bpf: Test CGROUP_STORAGE map can't be used by multiple progs")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/4f4702e9f6115b7f84fea01b2326ca24c6df7ba8.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>