scsi: lpfc: Use %zd format string for size_t
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [scsi] lpfc: Use zd format string for size_t (Rob Evers) [1382101]
Rebuild_FUZZ: 91.36%
commit-author Arnd Bergmann <arnd@arndb.de>
commit efe583c6d3cdafbeb0c039cd5d0f88fd26637065

A recent bugfix introduced a harmless warning in the lpfc driver:

drivers/scsi/lpfc/lpfc_init.c: In function 'lpfc_write_firmware':
drivers/scsi/lpfc/lpfc_logmsg.h:56:45: error: format '%ld' expects argument of type 'long int', but argument 9 has type 'size_t {aka const unsigned int}' [-Werror=format=]

'size_t' is always the same width as 'long' in the kernel, but the
compiler doesn't know that. The %z modifier is what the standard expects
to be used here, and this shuts up the warning.

Fixes: 679053c651fb ("scsi: lpfc: Fix fw download on SLI-4 FC adapters")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
	Acked-by: James Smart <james.smart@broadcom.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit efe583c6d3cdafbeb0c039cd5d0f88fd26637065)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>