firmware: tegra: bpmp: Fix build failure for tegra264-only config
JIRA: https://issues.redhat.com/browse/RHEL-109772

commit 83f96a7eaaf0e3ac1b1447f74a8d3b2213187b6e
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 11 Jul 2025 10:24:03 +0200

    The definition of tegra186_bpmp_ops was not updated in sync with the use
    in bpmp.c:

    drivers/firmware/tegra/bpmp.c:856:17: error: 'tegra186_bpmp_ops' undeclared here (not in a function); did you mean 'tegra_bpmp_ops'?
      856 |         .ops = &tegra186_bpmp_ops,
    aarch64-linux-ld: drivers/firmware/tegra/bpmp.o:(.rodata+0x2f0): undefined reference to `tegra186_bpmp_ops'

    Update the Makefile as needed.

    There is really no need to hide the declaration based on the configuration,
    so just expose it unconditionally so it never has to be updated again
    for the next SoC.

    Fixes: 94bce2cf7cf6 ("firmware: tegra: bpmp: Add support on Tegra264")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250711082409.1398497-1-arnd@kernel.org
    Signed-off-by: Thierry Reding <treding@nvidia.com>

Signed-off-by: Marcin Juszkiewicz <mjuszkiewicz@redhat.com>