RDMA/mlx5: fix build error with INFINIBAND_USER_ACCESS=n
Bugzilla: https://bugzilla.redhat.com/2049449
Upstream-status: v5.16-rc1

commit 97ad8c8c719d0f7fbf3e828be7e99121b4b05b1f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 19 08:15:45 2021 +0200

    RDMA/mlx5: fix build error with INFINIBAND_USER_ACCESS=n

    The mlx5_ib_fs_add_op_fc/mlx5_ib_fs_remove_op_fc functions are only
    available when user access is enabled, without that we run into a link
    error:

    ERROR: modpost: "mlx5_ib_fs_add_op_fc" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!
    ERROR: modpost: "mlx5_ib_fs_remove_op_fc" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!

    Conditionally compiling the newly added code section makes it build,
    though this is probably not a correct fix.

    Fixes: a29b934ceb4c ("RDMA/mlx5: Add modify_op_stat() support")
    Link: https://lore.kernel.org/r/20211019061602.3062196-1-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Leon Romanovsky <leonro@nvidia.com>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>