mptcp: Fix undefined mptcp_handle_ipv6_mapped for modular IPV6
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 31484d56ca9511e62c08626db338d2aaafb3aa3f

If CONFIG_MPTCP=y, CONFIG_MPTCP_IPV6=n, and CONFIG_IPV6=m:

    ERROR: "mptcp_handle_ipv6_mapped" [net/ipv6/ipv6.ko] undefined!

This does not happen if CONFIG_MPTCP_IPV6=y, as CONFIG_MPTCP_IPV6
selects CONFIG_IPV6, and thus forces CONFIG_IPV6 builtin.

As exporting a symbol for an empty function would be a bit wasteful, fix
this by providing a dummy version of mptcp_handle_ipv6_mapped() for the
CONFIG_MPTCP_IPV6=n case.

Rename mptcp_handle_ipv6_mapped() to mptcpv6_handle_mapped(), to make it
clear this is a pure-IPV6 function, just like mptcpv6_init().

Fixes: cec37a6e41aae7bf ("mptcp: Handle MP_CAPABLE options for outgoing connections")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 31484d56ca9511e62c08626db338d2aaafb3aa3f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>