h8300: pci: Remove local declaration of pcibios_penalize_isa_irq
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Guenter Roeck <linux@roeck-us.net>
commit 21c7acc439b55d0569d7c2fc2eea5194b3910406

h8300 builds fail with:

In file included from drivers/of/address.c:11:
include/linux/pci.h:1966:20: error: redefinition of 'pcibios_penalize_isa_irq'

This is because CONFIG_PCI is not enabled, and pcibios_penalize_isa_irq()
is now declared as inline static function in generic code if this is the
case. Since h8300 does not support PCI to start with, fix the problem by
removing the architecture specific pci.h.

Fixes: 5d32a66541c46 ("PCI/ACPI: Allow ACPI to be built without CONFIG_PCI set")
	Cc: Sinan Kaya <okaya@kernel.org>
	Cc: Bjorn Helgaas <bhelgaas@google.com>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Yoshinori Sato <ysato@users.sourceforge.jp>
(cherry picked from commit 21c7acc439b55d0569d7c2fc2eea5194b3910406)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>