drivers/perf: arm-cmn: Add space after ','
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Junhao He <hejunhao2@hisilicon.com>
commit a9f00c9760febb84215bcb489855b5b23e3ab4dc

Fix a warning from checkpatch.pl.

ERROR: space required after that ',' (ctx:VxV)

	Signed-off-by: Junhao He <hejunhao2@hisilicon.com>
	Signed-off-by: Jay Fang <f.fangjian@huawei.com>
Link: https://lore.kernel.org/r/1620736054-58412-4-git-send-email-f.fangjian@huawei.com
	Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit a9f00c9760febb84215bcb489855b5b23e3ab4dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>