cxgb4: fix 64-bit division on i386
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
commit 97c20ea8a115b405288404d8c84a90f43425630d

Fix following compile error on i386 architecture.

ERROR: "__udivdi3" [drivers/net/ethernet/chelsio/cxgb4/cxgb4.ko] undefined!

Fixes: 0e395b3cb1fb ("cxgb4: add FLOWC based QoS offload")
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 97c20ea8a115b405288404d8c84a90f43425630d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>