i2c: mlxbf: avoid 64-bit division
JIRA: https://issues.redhat.com/browse/RHEL-103884

commit 2b2805404c926b8dcd5c5c13d240722da714906e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 20 17:25:45 2025 +0200

    i2c: mlxbf: avoid 64-bit division

    The 64-bit division in mlxbf_i2c_get_ticks() causes link failures
    when compile-testing on 32-bit machines:

    ERROR: modpost: "__udivdi3" [drivers/i2c/busses/i2c-mlxbf.ko] undefined!

    Change this to a div_u64(), which should replace the constant division
    with a a multiply/shift combination in the mlxbf_i2c_get_ticks().

    The frequency calculation functions require a slow library call but
    should be used much rarer.

    Fixes: 053859002c20 ("i2c: mlxbf: Allow build with COMPILE_TEST")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250520152600.1975628-1-arnd@kernel.org
    Signed-off-by: Andi Shyti <andi@smida.it>

(cherry picked from commit 2b2805404c926b8dcd5c5c13d240722da714906e)
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>