powerpc/64e: Tie PPC_BOOK3E_64 to PPC_FSL_BOOK3E
JIRA: https://issues.redhat.com/browse/RHEL-23910

commit 1a76e520ee1831a81dabf8a9a58c6453f700026e
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Fri Mar 4 17:12:22 2022 +1100

    powerpc/64e: Tie PPC_BOOK3E_64 to PPC_FSL_BOOK3E

    Since the IBM A2 CPU support was removed, see commit
    fb5a515704d7 ("powerpc: Remove platforms/wsp and associated pieces"),
    the only 64-bit Book3E CPUs we support are Freescale (NXP) ones.

    However our Kconfig still allows configurating a kernel that has 64-bit
    Book3E support, but no Freescale CPU support enabled. Such a kernel
    would never boot, it doesn't know about any CPUs.

    It also causes build errors, as reported by lkp, because
    PPC_BARRIER_NOSPEC is not enabled in such a configuration:

      powerpc64-linux-ld: arch/powerpc/net/bpf_jit_comp64.o:(.toc+0x0):
      undefined reference to `powerpc_security_features'

    To fix this, force PPC_FSL_BOOK3E to be selected whenever we are
    building a 64-bit Book3E kernel.

    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
    Suggested-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20220304061222.2478720-1-mpe@ellerman.id.au

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>