wifi: mt76: mt7915: workaround too long expansion sparse warnings
JIRA: https://issues.redhat.com/browse/RHEL-50013

commit 2d5cde1143eca31c72547dfd589702c6b4a7e684
Author: Lorenzo Bianconi <lorenzo@kernel.org>
Date:   Tue Mar 19 16:12:47 2024 +0100

    wifi: mt76: mt7915: workaround too long expansion sparse warnings
    
    Fix the following sparse warnings:
    
    drivers/net/wireless/mediatek/mt76/mt7915/debugfs.c:1133:29: error: too long token expansion
    drivers/net/wireless/mediatek/mt76/mt7915/debugfs.c:1133:29: error: too long token expansion
    drivers/net/wireless/mediatek/mt76/mt7915/debugfs.c:1133:29: error: too long token expansion
    drivers/net/wireless/mediatek/mt76/mt7915/debugfs.c:1133:29: error: too long token expansion
    
    No functional changes, compile tested only.
    
    Fixes: e3296759f347 ("wifi: mt76: mt7915: enable per bandwidth power limit support")
    Signed-off-by: Lorenzo Bianconi <lorenzo@kernel.org>
    Acked-by: Felix Fietkau <nbd@nbd.name>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://msgid.link/5457b92e41909dd75ab3db7a0e9ec372b917a386.1710858172.git.lorenzo@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>