perf list: Fix --raw-dump option
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] list: Fix --raw-dump option (Jiri Olsa) [1209607]
Rebuild_FUZZ: 91.53%
commit-author Taesoo Kim <tsgatesv@gmail.com>
commit b3505208804f3b59150cd77719f01c8b0023a865

Currently, 'perf list --raw-dump' requires extra arguments
(e.g., hw) to invoke, which breaks bash/zsh completion
(perf-completion.sh).

  $ perf list --raw-dump
    Error: unknown option `raw-dump'

     usage: perf list [hw|sw|cache|tracepoint|pmu|event_glob]

After,

  $ perf list --raw-dump
  cpu-cycles instructions cache-references cache-misses ...

	Signed-off-by: Taesoo Kim <tsgatesv@gmail.com>
	Acked-by: Namhyung Kim <namhyung@kernel.org>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Taesoo kim <taesoo@gatech.edu>
Link: http://lkml.kernel.org/r/1419997015-11071-1-git-send-email-tsgatesv@gmail.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit b3505208804f3b59150cd77719f01c8b0023a865)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>