lib: fix build failure in CONFIG_DEBUG_VIRTUAL test
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Christophe Leroy <christophe.leroy@c-s.fr>
commit 10fdf838e5f540beca466e9d1325999c072e5d3f

On several arches, virt_to_phys() is in io.h

Build fails without it:

  CC      lib/test_debug_virtual.o
lib/test_debug_virtual.c: In function 'test_debug_virtual_init':
lib/test_debug_virtual.c:26:7: error: implicit declaration of function 'virt_to_phys' [-Werror=implicit-function-declaration]
  pa = virt_to_phys(va);
       ^

Fixes: e4dace361552 ("lib: add test module for CONFIG_DEBUG_VIRTUAL")
CC: stable@vger.kernel.org
	Signed-off-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 10fdf838e5f540beca466e9d1325999c072e5d3f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>