selftests: netfilter: fix a build error on openSUSE
JIRA: https://issues.redhat.com/browse/RHEL-21061
Upstream Status: commit a50a88f026fb

commit a50a88f026fb28ece512c50e8ef7cd4ef6d0a291
Author: Geliang Tang <geliang.tang@suse.com>
Date:   Wed Mar 2 13:29:13 2022 +0800

    selftests: netfilter: fix a build error on openSUSE

    This patch fixed the following build error on openSUSE Leap 15.3:

    =======================================================================
     gcc     nf-queue.c -lmnl -o tools/testing/selftests/netfilter/nf-queue
     nf-queue.c:13:10: fatal error: libmnl/libmnl.h: No such file or directory
      #include <libmnl/libmnl.h>
               ^~~~~~~~~~~~~~~~~
     compilation terminated.
    =======================================================================

    It is because libmnl.h is put in the directory of
    "/usr/include/libmnl/libmnl/" on openSUSE, not "/usr/include/libmnl/":

     > rpm -ql libmnl-devel
     /usr/include/libmnl
     /usr/include/libmnl/libmnl
     /usr/include/libmnl/libmnl/libmnl.h
     /usr/lib64/libmnl.so
     /usr/lib64/pkgconfig/libmnl.pc

    Suggested-by: Kai Liu <kai.liu@suse.com>
    Signed-off-by: Geliang Tang <geliang.tang@suse.com>
    Reviewed-by: Shuah Khan <skhan@linuxfoundation.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>