ASoC: dapm: add initialization for w_param_text pointer
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: dapm: add initialization for w_param_text pointer (Jaroslav Kysela) [1535427]
Rebuild_FUZZ: 94.83%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 667ebc97c99a2ea9279bf3fdd791d97adfafbbc2

We now allocate the array conditionally, but we always pass
the pointer to the new snd_soc_dapm_free_kcontrol() function,
which introduces a warning for the case that it is not
initialized:

sound/soc/soc-dapm.c: In function 'snd_soc_dapm_new_pcm':
sound/soc/soc-dapm.c:3940:2: error: 'w_param_text' may be used uninitialized in this function [-Werror=maybe-uninitialized]

As snd_soc_dapm_free_kcontrol() is global, it doesn't get inlined
and gcc fails to notice that we don't actually access the array
in that case, so the code is actually safe. Adding an initialization
for the array pointer shuts up the warning.

Fixes: 19ad683abc85 ("ASoC: dapm: Avoid creating kcontrol for params")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 667ebc97c99a2ea9279bf3fdd791d97adfafbbc2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>