x86/tracing: Add config option checking to the definitions of mce handlers
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [x86] trace: Add config option checking to the definitions of mce handlers (Seiji Aguchi) [741673]
Rebuild_FUZZ: 94.37%
commit-author Seiji Aguchi <seiji.aguchi@hds.com>
commit 33e5ff634f07dec26b7ed1fd7f9e32978fe1f2b2

In case CONFIG_X86_MCE_THRESHOLD and CONFIG_X86_THERMAL_VECTOR
are disabled, kernel build fails as follows.

   arch/x86/built-in.o: In function `trace_threshold_interrupt':
   (.entry.text+0x122b): undefined reference to `smp_trace_threshold_interrupt'
   arch/x86/built-in.o: In function `trace_thermal_interrupt':
   (.entry.text+0x132b): undefined reference to `smp_trace_thermal_interrupt'

In this case, trace_threshold_interrupt/trace_thermal_interrupt
are not needed to define.

So, add config option checking to their definitions in entry_64.S.

	Signed-off-by: Seiji Aguchi <seiji.aguchi@hds.com>
	Cc: rostedt@goodmis.org
Link: http://lkml.kernel.org/r/51C58B8A.2080808@hds.com
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 33e5ff634f07dec26b7ed1fd7f9e32978fe1f2b2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>