ASoC: cs42l84: remove incorrect of_match_ptr()
JIRA: https://issues.redhat.com/browse/RHEL-80676

commit 0d4f74febc9d92d88099aff01f121b7f5f942c8f
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Oct 29 09:23:55 2024 +0000

    ASoC: cs42l84: remove incorrect of_match_ptr()

    The use of of_match_ptr() is incorrect here and just causes
    a warning:

    sound/soc/codecs/cs42l84.c:1084:34: error: unused variable 'cs42l84_of_match' [-Werror,-Wunused-const-variable]

    Fixes: 250304a0fb34 ("ASoC: cs42l84: Add new codec driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20241029092404.3874040-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>