EDAC, skx: Fix randconfig builds
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1127.el7
commit-author Borislav Petkov <bp@suse.de>
commit a324e9396ca3d00e1101476ba067b412e0aba232
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1127.el7/a324e939.failed

The driver depends on the ADXL component glue and selects it. However,
ADXL itself implicitly depends on ACPI and in nonsensical randconfig
builds like this:

  # CONFIG_ACPI is not set
  CONFIG_ACPI_ADXL=y

where ACPI is not enabled, the build fails with:

  drivers/edac/skx_edac.o: In function `skx_mce_check_error':
  skx_edac.c:(.text+0xab): undefined reference to `adxl_decode'
  drivers/edac/skx_edac.o: In function `skx_init':
  skx_edac.c:(.init.text+0x8bf): undefined reference to `adxl_get_component_names'
  make: *** [vmlinux] Error 1

Add stubs for that case so that the build succeeds. CONFIG_ACPI=n
doesn't make any sense for real configurations but this fix will at
least silence randconfig builds.

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Acked-by: Tony Luck <tony.luck@intel.com>
	Cc: "Rafael J. Wysocki" <rafael@kernel.org>
(cherry picked from commit a324e9396ca3d00e1101476ba067b412e0aba232)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/edac/Kconfig
#	include/linux/adxl.h