tipc: not enable tipc when ipv6 works as a module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Xin Long <lucien.xin@gmail.com>
commit c530189905efe91b6a464db4ec1b56b4c069609f
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/c5301899.failed

When using ipv6_dev_find() in one module, it requires ipv6 not to
work as a module. Otherwise, this error occurs in build:

  undefined reference to `ipv6_dev_find'.

So fix it by adding "depends on IPV6 || IPV6=n" to tipc/Kconfig,
as it does in sctp/Kconfig.

Fixes: 5a6f6f579178 ("tipc: set ub->ifindex for local ipv6 address")
	Reported-by: kernel test robot <lkp@intel.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Xin Long <lucien.xin@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c530189905efe91b6a464db4ec1b56b4c069609f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/tipc/Kconfig