x86/debug: Include percpu.h in debugreg.h to get DECLARE_PER_CPU() et al
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 2d08a893b87cf9b2f9dbb3afaff60ca4530d55a2
Author: Sean Christopherson <seanjc@google.com>
Date:   Thu Nov 10 20:17:07 2022 +0000

    x86/debug: Include percpu.h in debugreg.h to get DECLARE_PER_CPU() et al

    Include percpu.h to pick up the definition of DECLARE_PER_CPU() and
    friends instead of relying on the parent to provide the #include.  E.g.
    swapping the order of includes in arch/x86/kvm/vmx/nested.c (simulating
    KVM code movement being done for other purposes) results in build errors:

      In file included from arch/x86/kvm/vmx/nested.c:3:
      arch/x86/include/asm/debugreg.h:9:32: error: unknown type name âcpu_dr7â=99
          9 | DECLARE_PER_CPU(unsigned long, cpu_dr7);
            |                                ^~~~~~~

    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lkml.kernel.org/r/20221110201707.1976032-1-seanjc@google.com

Signed-off-by: Prarit Bhargava <prarit@redhat.com>