x86/orc: Make the is_callthunk() definition depend on CONFIG_BPF_JIT=y
JIRA: https://issues.redhat.com/browse/RHEL-25415

Conflicts: Minor drift issues.

commit 301cf77e21317b3465c5e2bb0188df24bbf1c2e2
Author: Ingo Molnar <mingo@kernel.org>
Date:   Fri Jun 9 11:04:53 2023 +0200

    x86/orc: Make the is_callthunk() definition depend on CONFIG_BPF_JIT=y

    Recent commit:

      020126239b8f Revert "x86/orc: Make it callthunk aware"

    Made the only user of is_callthunk() depend on CONFIG_BPF_JIT=y, while
    the definition of the helper function is unconditional.

    Move is_callthunk() inside the #ifdef block.

    Addresses this build failure:

       arch/x86/kernel/callthunks.c:296:13: error: ‘is_callthunk’ defined but not used [-Werror=unused-function]

    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Cc: Josh Poimboeuf <jpoimboe@kernel.org>
    Cc: linux-kernel@vger.kernel.org
    Cc: Peter Zijlstra <peterz@infradead.org>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>