net/mlx4: Avoid 'may be used uninitialized' warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [netdrv] mlx4: Avoid 'may be used uninitialized' warnings (Amir Vadai) [1164527 1164530 1164531 1164536 1164537]
Rebuild_FUZZ: 96.00%
commit-author Bjorn Helgaas <bhelgaas@google.com>
commit c1c52db16e26a26b545821abae303310a074350f

With a cross-compiler based on gcc-4.9, I see warnings like the following:

  drivers/net/ethernet/mellanox/mlx4/resource_tracker.c: In function 'mlx4_SW2HW_CQ_wrapper':
  drivers/net/ethernet/mellanox/mlx4/resource_tracker.c:3048:10: error: 'cq' may be used uninitialized in this function [-Werror=maybe-uninitialized]
    cq->mtt = mtt;

I think the warning is spurious because we only use cq when
cq_res_start_move_to() returns zero, and it always initializes *cq in that
case.  The srq case is similar.  But maybe gcc isn't smart enough to figure
that out.

Initialize cq and srq explicitly to avoid the warnings.

	Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c1c52db16e26a26b545821abae303310a074350f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>