mei: fix compilation error with missing WATCHDOG_CORE
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Tomas Winkler <tomas.winkler@intel.com>
commit 208008c322fd1ffdd07e7fc95910154174ce0ff3

Kconfig is not transitive so INTEL_ME_TXE has to depend
on WATCHDOG_CORE as well

ERROR: "watchdog_unregister_device" [drivers/misc/mei/mei.ko] undefined!
ERROR: "watchdog_register_device" [drivers/misc/mei/mei.ko] undefined!

	Reported-by: Fengguang Wu <fengguang.wu@intel.com>
	Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 208008c322fd1ffdd07e7fc95910154174ce0ff3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>