shmbuf.h: add asm/shmbuf.h to UAPI compile-test coverage
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 4a3233c1a69885aa7e71c48ff39ae11c212ac90a
Author: Masahiro Yamada <masahiroy@kernel.org>
Date:   Thu Feb 10 11:11:25 2022 +0900

    shmbuf.h: add asm/shmbuf.h to UAPI compile-test coverage

    asm/shmbuf.h is currently excluded from the UAPI compile-test because of
    the errors like follows:

        HDRTEST usr/include/asm/shmbuf.h
      In file included from ./usr/include/asm/shmbuf.h:6,
                       from <command-line>:
      ./usr/include/asm-generic/shmbuf.h:26:33: error: field ‘shm_perm’ has incomplete type
         26 |         struct ipc64_perm       shm_perm;       /* operation perms */
            |                                 ^~~~~~~~
      ./usr/include/asm-generic/shmbuf.h:27:9: error: unknown type name ‘size_t’
         27 |         size_t                  shm_segsz;      /* size of segment (bytes) */
            |         ^~~~~~
      ./usr/include/asm-generic/shmbuf.h:40:9: error: unknown type name ‘__kernel_pid_t’
         40 |         __kernel_pid_t          shm_cpid;       /* pid of creator */
            |         ^~~~~~~~~~~~~~
      ./usr/include/asm-generic/shmbuf.h:41:9: error: unknown type name ‘__kernel_pid_t’
         41 |         __kernel_pid_t          shm_lpid;       /* pid of last operator */
            |         ^~~~~~~~~~~~~~

    The errors can be fixed by replacing size_t with __kernel_size_t and by
    including proper headers.

    Then, remove the no-header-test entry from user/include/Makefile.

    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
    Reviewed-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Omitted-fix: 169adc2b6b3c android/binder.h: add linux/android/binder(fs).h to UAPI co…
	not strictly necessary for arch/x86 update
Omitted-fix: cbf282034129 fsmap.h: add linux/fsmap.h to UAPI compile-test coverage
	not strictly necessary for arch/x86 update
Omitted-fix: 8b4bca21c2c0 kexec.h: add linux/kexec.h to UAPI compile-test coverage
	not strictly necessary for arch/x86 update
Omitted-fix: 2a5c0fdc70cd reiserfs_xattr.h: add linux/reiserfs_xattr.h to UAPI compi
	not strictly necessary for arch/x86 update

Signed-off-by: Prarit Bhargava <prarit@redhat.com>