fou: remove sparse errors
JIRA: https://issues.redhat.com/browse/RHEL-138741
Tested: compile only

Conflicts:
- fou.c has been renamed to fou_core.c due to commit 08d323234d10
  already backported.

commit 8d65cd8d25fa23951171094553901d69a88ccdff
Author: Eric Dumazet <edumazet@google.com>
Date:   Mon Aug 30 20:26:08 2021 -0700

    fou: remove sparse errors

    We need to add __rcu qualifier to avoid these errors:

    net/ipv4/fou.c:250:18: warning: incorrect type in assignment (different address spaces)
    net/ipv4/fou.c:250:18:    expected struct net_offload const **offloads
    net/ipv4/fou.c:250:18:    got struct net_offload const [noderef] __rcu **
    net/ipv4/fou.c:251:15: error: incompatible types in comparison expression (different address spaces):
    net/ipv4/fou.c:251:15:    struct net_offload const [noderef] __rcu *
    net/ipv4/fou.c:251:15:    struct net_offload const *
    net/ipv4/fou.c:272:18: warning: incorrect type in assignment (different address spaces)
    net/ipv4/fou.c:272:18:    expected struct net_offload const **offloads
    net/ipv4/fou.c:272:18:    got struct net_offload const [noderef] __rcu **
    net/ipv4/fou.c:273:15: error: incompatible types in comparison expression (different address spaces):
    net/ipv4/fou.c:273:15:    struct net_offload const [noderef] __rcu *
    net/ipv4/fou.c:273:15:    struct net_offload const *
    net/ipv4/fou.c:442:18: warning: incorrect type in assignment (different address spaces)
    net/ipv4/fou.c:442:18:    expected struct net_offload const **offloads
    net/ipv4/fou.c:442:18:    got struct net_offload const [noderef] __rcu **
    net/ipv4/fou.c:443:15: error: incompatible types in comparison expression (different address spaces):
    net/ipv4/fou.c:443:15:    struct net_offload const [noderef] __rcu *
    net/ipv4/fou.c:443:15:    struct net_offload const *
    net/ipv4/fou.c:489:18: warning: incorrect type in assignment (different address spaces)
    net/ipv4/fou.c:489:18:    expected struct net_offload const **offloads
    net/ipv4/fou.c:489:18:    got struct net_offload const [noderef] __rcu **
    net/ipv4/fou.c:490:15: error: incompatible types in comparison expression (different address spaces):
    net/ipv4/fou.c:490:15:    struct net_offload const [noderef] __rcu *
    net/ipv4/fou.c:490:15:    struct net_offload const *
    net/ipv4/udp_offload.c:170:26: warning: incorrect type in assignment (different address spaces)
    net/ipv4/udp_offload.c:170:26:    expected struct net_offload const **offloads
    net/ipv4/udp_offload.c:170:26:    got struct net_offload const [noderef] __rcu **
    net/ipv4/udp_offload.c:171:23: error: incompatible types in comparison expression (different address spaces):
    net/ipv4/udp_offload.c:171:23:    struct net_offload const [noderef] __rcu *
    net/ipv4/udp_offload.c:171:23:    struct net_offload const *

    Fixes: efc98d08e1ec ("fou: eliminate IPv4,v6 specific GRO functions")
    Fixes: 8bce6d7d0d1e ("udp: Generalize skb_udp_segment")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Xin Long <lxin@redhat.com>