net/mlx5e: Do not use err uninitialized in mlx5e_rep_add_meta_tunnel_rule()
Bugzilla: https://bugzilla.redhat.com/2165355
Upstream-status: v6.1-rc1

commit 92f97c00f0ca538fe820c0b18b6f957a69410689
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Thu Aug 25 11:06:07 2022 -0700

    net/mlx5e: Do not use err uninitialized in mlx5e_rep_add_meta_tunnel_rule()

    Clang warns:

      drivers/net/ethernet/mellanox/mlx5/core/en_rep.c:481:6: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
              if (IS_ERR(flow_rule)) {
                  ^~~~~~~~~~~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_rep.c:489:9: note: uninitialized use occurs here
              return err;
                    ^~~
      drivers/net/ethernet/mellanox/mlx5/core/en_rep.c:481:2: note: remove the 'if' if its condition is always true
              if (IS_ERR(flow_rule)) {
              ^~~~~~~~~~~~~~~~~~~~~~~
      drivers/net/ethernet/mellanox/mlx5/core/en_rep.c:474:9: note: initialize the variable 'err' to silence this warning
              int err;
                    ^
                      = 0
      1 error generated.

    There is little reason to have the 'goto + error variable' construct in
    this function. Get rid of it and just return the PTR_ERR value in the if
    statement and 0 at the end.

    Fixes: 430e2d5e2a98 ("net/mlx5: E-Switch, Move send to vport meta rule creation")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1695
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Reviewed-by: Leon Romanovsky <leonro@nvidia.com>
    Link: https://lore.kernel.org/r/20220825180607.2707947-1-nathan@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>