mt76: fix enum type mismatch
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit abf3d98dee7c4038152ce88833ddc2189f68cbd4

There is no 'NONE' version of 'enum mcu_cipher_type', and returning
'MT_CIPHER_NONE' causes a warning:

drivers/net/wireless/mediatek/mt76/mt7921/mcu.c: In function 'mt7921_mcu_get_cipher':
drivers/net/wireless/mediatek/mt76/mt7921/mcu.c:114:24: error: implicit conversion from 'enum mt76_cipher_type' to 'enum mcu_cipher_type' [-Werror=enum-conversion]
  114 |                 return MT_CIPHER_NONE;
      |                        ^~~~~~~~~~~~~~

Add the missing MCU_CIPHER_NONE defintion that fits in here with
the same value.

Fixes: c368362c36d3 ("mt76: fix iv and CCMP header insertion")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20210721150745.1914829-1-arnd@kernel.org
(cherry picked from commit abf3d98dee7c4038152ce88833ddc2189f68cbd4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>