selftests/mm: kvm, mdwe fixes to avoid requiring "make headers"
JIRA: https://issues.redhat.com/browse/RHEL-101190

commit c142850fbc956058ff2f2987d3d11eb2c628f710
Author: John Hubbard <jhubbard@nvidia.com>
Date:   Mon, 17 Jun 2024 19:24:21 -0700

    selftests/mm: kvm, mdwe fixes to avoid requiring "make headers"

    On Ubuntu 23.04, the kvm and mdwe selftests/mm build fails due to
    missing a few items that are found in prctl.h. Here is an excerpt of the
    build failures:

    ksm_tests.c:252:13: error: use of undeclared identifier 'PR_SET_MEMORY_MERGE'
    ...
    mdwe_test.c:26:18: error: use of undeclared identifier 'PR_SET_MDWE'
    mdwe_test.c:38:18: error: use of undeclared identifier 'PR_GET_MDWE'

    Fix these errors by adding a new tools/include/uapi/linux/prctl.h . This
    file was created by running "make headers", and then copying a snapshot
    over from ./usr/include/linux/prctl.h, as per the approach we settled on
    in [1].

    [1] commit e076eaca5906 ("selftests: break the dependency upon local
    header files")

    Link: https://lkml.kernel.org/r/20240618022422.804305-6-jhubbard@nvidia.com
    Signed-off-by: John Hubbard <jhubbard@nvidia.com>
    Acked-by: David Hildenbrand <david@redhat.com>
    Cc: Andrei Vagin <avagin@google.com>
    Cc: Axel Rasmussen <axelrasmussen@google.com>
    Cc: Christian Brauner <brauner@kernel.org>
    Cc: Jeff Xu <jeffxu@chromium.org>
    Cc: Kees Cook <kees@kernel.org>
    Cc: Kent Overstreet <kent.overstreet@linux.dev>
    Cc: Liam R. Howlett <Liam.Howlett@oracle.com>
    Cc: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Cc: Peter Xu <peterx@redhat.com>
    Cc: Rich Felker <dalias@libc.org>
    Cc: Shuah Khan <shuah@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>