scsi: scsi_transport_fc: Remove unused 'desc_cnt' variable
JIRA: https://issues.redhat.com/browse/RHEL-14312
Upstream Status: From upstream linux mainline

clang with W=1 reports:

drivers/scsi/scsi_transport_fc.c:908:6: error: variable
  'desc_cnt' set but not used [-Werror,-Wunused-but-set-variable]
        u32 desc_cnt = 0, bytes_remain;
            ^
This variable is not used so remove it.

Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230326003222.1343671-1-trix@redhat.com
Reviewed-by: Himanshu Madhani <himanshu.madhani@oracle.com>
Reviewed-by: Benjamin Block <bblock@linux.ibm.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit e324dd00fd17906ad9f0386f5e15d78da2e2b9fe)
Signed-off-by: Ewan D. Milne <emilne@redhat.com>