Reapply "perf util: Make util its own library"
JIRA: https://issues.redhat.com/browse/RHEL-79032
Upstream Status: RHEL-only

This reverts commit d1630cc5a21845f43e1ee6e11c9e2372b92ad013.

Testing has found out that d1630cc5a21845f43e1ee6e11c9e2372b92ad013
(which is a revert of b04cbd70545bb8c27d5a120a43c461c3952963be) has
broken the perf python module shipped in python3-perf package:

    [root@machine ~]# echo "import sys ; sys.path.insert(0, 'python'); import perf" | '/usr/bin/python3'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ImportError: /usr/lib64/python3.9/site-packages/perf.cpython-39-x86_64-linux-gnu.so: undefined symbol: verbose

Revert that revert.

The original problem needs to be solved by moving python3-perf to
AppStream, so that it does not break the dependency rule that no
BaseOS packages may depend on AppStream packages.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>