crypto: qat - avoid memcpy() overflow warning
JIRA: https://issues.redhat.com/browse/RHEL-17715
Upstream Status: merged into the linux.git

commit 23a22e831ed4e6aa0831312e8cc8b7c60a657f60
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 3 17:26:02 2024 +0100

    crypto: qat - avoid memcpy() overflow warning

    The use of array_size() leads gcc to assume the memcpy() can have a larger
    limit than actually possible, which triggers a string fortification warning:

    In file included from include/linux/string.h:296,
                     from include/linux/bitmap.h:12,
                     from include/linux/cpumask.h:12,
                     from include/linux/sched.h:16,
                     from include/linux/delay.h:23,
                     from include/linux/iopoll.h:12,
                     from drivers/crypto/intel/qat/qat_common/adf_gen4_hw_data.c:3:
    In function 'fortify_memcpy_chk',
        inlined from 'adf_gen4_init_thd2arb_map' at drivers/crypto/intel/qat/qat_common/adf_gen4_hw_data.c:401:3:
    include/linux/fortify-string.h:579:4: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
      579 |    __write_overflow_field(p_size_field, size);
          |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    include/linux/fortify-string.h:588:4: error: call to '__read_overflow2_field' declared with attribute warning: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror=attribute-warning]
      588 |    __read_overflow2_field(q_size_field, size);
          |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Add an explicit range check to avoid this.

    Fixes: 5da6a2d5353e ("crypto: qat - generate dynamically arbiter mappings")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>