fbdev/hyperv_fb: Include <linux/screen_info.h>
JIRA: https://issues.redhat.com/browse/RHEL-24125

commit f1b215fdcd01ff3cc74f1e4194c866573af8034b
Author: Thomas Zimmermann <tzimmermann@suse.de>
Date:   Mon, 10 Jul 2023 09:58:38 +0200

    fbdev/hyperv_fb: Include <linux/screen_info.h>

    Include <linux/screen_info.h> to get the global screen_info state.
    Fixes the following errors:

    >> drivers/video/fbdev/hyperv_fb.c:1033:10: error: use of undeclared identifier 'screen_info'
        1033 |                 base = screen_info.lfb_base;
             |                        ^
       drivers/video/fbdev/hyperv_fb.c:1034:10: error: use of undeclared identifier 'screen_info'
        1034 |                 size = screen_info.lfb_size;
             |                        ^
    >> drivers/video/fbdev/hyperv_fb.c:1080:3: error: must use 'struct' tag to refer to type 'screen_info'
        1080 |                 screen_info.lfb_size = 0;
             |                 ^
             |                 struct
    >> drivers/video/fbdev/hyperv_fb.c:1080:14: error: expected identifier or '('
        1080 |                 screen_info.lfb_size = 0;
             |                            ^
       drivers/video/fbdev/hyperv_fb.c:1081:3: error: must use 'struct' tag to refer to type 'screen_info'
        1081 |                 screen_info.lfb_base = 0;
             |                 ^
             |                 struct
       drivers/video/fbdev/hyperv_fb.c:1081:14: error: expected identifier or '('
        1081 |                 screen_info.lfb_base = 0;
             |                            ^
       drivers/video/fbdev/hyperv_fb.c:1082:3: error: must use 'struct' tag to refer to type 'screen_info'
        1082 |                 screen_info.orig_video_isVGA = 0;
             |                 ^
             |                 struct
        drivers/video/fbdev/hyperv_fb.c:1082:14: error: expected identifier or '('
        1082 |                 screen_info.orig_video_isVGA = 0;
             |                            ^
        8 errors generated.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202307101042.rqehuauj-lkp@intel.com/
    Fixes: 8b0d13545b09 ("efi: Do not include <linux/screen_info.h> from EFI header")
    Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
    Cc: "K. Y. Srinivasan" <kys@microsoft.com> (supporter:Hyper-V/Azure CORE AND DRIVERS)
    Cc: Haiyang Zhang <haiyangz@microsoft.com> (supporter:Hyper-V/Azure CORE AND DRIVERS)
    Cc: Wei Liu <wei.liu@kernel.org> (supporter:Hyper-V/Azure CORE AND DRIVERS)
    Cc: Dexuan Cui <decui@microsoft.com> (supporter:Hyper-V/Azure CORE AND DRIVERS)
    Cc: Helge Deller <deller@gmx.de> (maintainer:FRAMEBUFFER LAYER)
    Cc: Javier Martinez Canillas <javierm@redhat.com>
    Cc: Sui Jingfeng <suijingfeng@loongson.cn>
    Cc: Ard Biesheuvel <ardb@kernel.org>
    Cc: Russell King <linux@armlinux.org.uk>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Will Deacon <will@kernel.org>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Cc: linux-efi@vger.kernel.org
    Cc: linux-hyperv@vger.kernel.org (open list:Hyper-V/Azure CORE AND DRIVERS)
    Cc: linux-fbdev@vger.kernel.org (open list:FRAMEBUFFER LAYER)
    Cc: dri-devel@lists.freedesktop.org (open list:FRAMEBUFFER LAYER)
    Reviewed-by: Javier Martinez Canillas <javierm@redhat.com>
    Reviewed-by: Sui Jingfeng <suijingfeng@loongson.cn>
    Link: https://patchwork.freedesktop.org/patch/msgid/20230710075848.23087-1-tzimmermann@suse.de

Signed-off-by: Waiman Long <longman@redhat.com>