ext4: avoid -Wformat-security warning
JIRA: https://issues.redhat.com/browse/RHEL-121233

commit d612a07931e261c537978aad096e7340b687cd0c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 23 18:43:49 2025 +0200

    ext4: avoid -Wformat-security warning

    check_igot_inode() prints a variable string, which causes a harmless
    warning with 'make W=1':

    fs/ext4/inode.c:4763:45: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
     4763 |         ext4_error_inode(inode, function, line, 0, err_str);

    Use a trivial "%s" format string instead.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jan Kara <jack@suse.cz>
    Link: https://patch.msgid.link/20250423164354.2780635-1-arnd@kernel.org
    Signed-off-by: Theodore Ts'o <tytso@mit.edu>

Signed-off-by: Brian Foster <bfoster@redhat.com>