perf cs-etm: Mute enumeration value warning
JIRA: https://redhat.atlassian.net/browse/RHEL-140195

upstream
========
commit 3e98f0203e10bc9d379852faf424f769ef5049a6
Author: Leo Yan <leo.yan@arm.com>
Date: Wed Oct 22 15:28:49 2025 +0100

description
===========
When the OpenCSD library introduces a new enumeration value (for example,
in the v1.7.1 release), the perf build fails with an error:

  util/cs-etm-decoder/cs-etm-decoder.c:600:10: error: enumeration value 'OCSD_GEN_TRC_ELEM_ITMTRACE' not explicitly handled in switch [-Werror, -Wswitch-enum]
    600 |         switch (elem->elem_type) {
	|                 ^~~~~~~~~~~~~~~
  1 error generated.

Convert to if-else sentences to mute the enumeration value warning,
which can avoid build failures whenever the lib is updated.

No functional change.

    Suggested-by: Suzuki K Poulose <suzuki.poulose@arm.com>
    Signed-off-by: Leo Yan <leo.yan@arm.com>
    Reviewed-by: James Clark <james.clark@linaro.org>
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Trevor Allison <tallison@redhat.com>