ASoC: fsl_asrc_m2m: select CONFIG_DMA_SHARED_BUFFER
JIRA: https://issues.redhat.com/browse/RHEL-80677

commit a2cd92185db0586f2136feae84d98cc54580f381
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Jan 22 07:53:17 2025 +0100

    ASoC: fsl_asrc_m2m: select CONFIG_DMA_SHARED_BUFFER

    Randconfig builds without dmabuf result in this link error from
    the fasl-asrc driver:

    ERROR: modpost: "dma_buf_put" [sound/core/snd-compress.ko] undefined!
    ERROR: modpost: "dma_buf_export" [sound/soc/fsl/snd-soc-fsl-asrc.ko] undefined!

    Add the missing 'select' statement.

    Fixes: 24a01710f627 ("ASoC: fsl_asrc_m2m: Add memory to memory function")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
    Link: https://patch.msgid.link/20250122065330.1423248-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>