ASoC: SOF: imx: remove error checks on NULL ipc
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit e302f8d9f799af57a61a7456451c28f2647e9751
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Mon Jul 31 16:37:44 2023 -0500

    ASoC: SOF: imx: remove error checks on NULL ipc

    imx_dsp_get_data() can return NULL, but the value is not checked
    before being usd, leading to static analysis warnings.

    sound/soc/sof/imx/imx8.c:85:32: error: dereference of NULL ‘0’
    [CWE-476] [-Werror=analyzer-null-dereference]

       85 |         spin_lock_irqsave(&priv->sdev->ipc_lock, flags);
          |                            ~~~~^~~~~~

    It appears this is not really a possible problem, so remove those checks.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Reviewed-by: Rander Wang <rander.wang@intel.com>
    Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
    Reviewed-by: Yaochun Hung <yc.hung@mediatek.com>
    Link: https://lore.kernel.org/r/20230731213748.440285-5-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>