HID: debug: Remove duplicates from 'keys'
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.13
Tested: with the hid-tools test suite and some hardware

commit 7b2daa648eb75ec75a6ebf5fce5629b758ea06df
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Wed Oct 16 16:32:40 2024 +0300

    HID: debug: Remove duplicates from 'keys'

    Duplicates in 'keys prevents kernel builds with clang, `make W=1` and
    CONFIG_WERROR=y, for example:

    drivers/hid/hid-debug.c:3443:18: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
     3443 |         [KEY_HANGEUL] = "HanGeul",              [KEY_HANGUP_PHONE] = "HangUpPhone",
          |                         ^~~~~~~~~
    drivers/hid/hid-debug.c:3217:18: note: previous initialization is here
     3217 |         [KEY_HANGUEL] = "Hangeul",              [KEY_HANJA] = "Hanja",
          |                         ^~~~~~~~~

    Fix this by removing them.

    The logic of removal is that, remove...
    1) if there is a constant that uses another defined constant, OR
    2) the one that appears later in the list.

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>