wifi: ath10k: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit de43b07db2a1af0d11ed167bb028f1038ae04086
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Thu Aug 10 11:12:24 2023 +0200

    wifi: ath10k: fix Wvoid-pointer-to-enum-cast warning
    
    'hw_rev' is an enum, thus cast of pointer on 64-bit compile test with W=1
    causes:
    
      ath10k/ahb.c:736:11: error: cast to smaller integer type 'enum ath10k_hw_rev' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]
    
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Acked-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20230810091224.70088-2-krzysztof.kozlowski@linaro.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>