x86: Add dummy prototype for mk_early_pgtbl_32()
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 2eb5d1df2aa657ccc65cfab67e65eb9f97cef4d6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:34 2023 +0200

    x86: Add dummy prototype for mk_early_pgtbl_32()

    'make W=1' warns about a function without a prototype in the x86-32 head code:

    arch/x86/kernel/head32.c:72:13: error: no previous prototype for 'mk_early_pgtbl_32' [-Werror=missing-prototypes]

    This is called from assembler code, so it does not actually need a prototype.
    I could not find an appropriate header for it, so just declare it in front
    of the definition to shut up the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-6-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>