mm/vmalloc: extend find_vmap_lowest_match_check with extra arguments
Bugzilla: https://bugzilla.redhat.com/2160210

commit bd1264c37c15a75a3164852740ad0c9529907d83
Author: Song Liu <song@kernel.org>
Date:   Tue Aug 30 22:27:34 2022 -0700

    mm/vmalloc: extend find_vmap_lowest_match_check with extra arguments

    find_vmap_lowest_match() is now able to handle different roots.  With
    DEBUG_AUGMENT_LOWEST_MATCH_CHECK enabled as:

    : --- a/mm/vmalloc.c
    : +++ b/mm/vmalloc.c
    : @@ -713,7 +713,7 @@ EXPORT_SYMBOL(vmalloc_to_pfn);
    : /*** Global kva allocator ***/
    :
    : -#define DEBUG_AUGMENT_LOWEST_MATCH_CHECK 0
    : +#define DEBUG_AUGMENT_LOWEST_MATCH_CHECK 1

    compilation failed as:

    mm/vmalloc.c: In function 'find_vmap_lowest_match_check':
    mm/vmalloc.c:1328:32: warning: passing argument 1 of 'find_vmap_lowest_match' makes pointer from integer without a cast [-Wint-conversion]
    1328 |  va_1 = find_vmap_lowest_match(size, align, vstart, false);
         |                                ^~~~
         |                                |
         |                                long unsigned int
    mm/vmalloc.c:1236:40: note: expected 'struct rb_root *' but argument is of type 'long unsigned int'
    1236 | find_vmap_lowest_match(struct rb_root *root, unsigned long size,
         |                        ~~~~~~~~~~~~~~~~^~~~
    mm/vmalloc.c:1328:9: error: too few arguments to function 'find_vmap_lowest_match'
    1328 |  va_1 = find_vmap_lowest_match(size, align, vstart, false);
         |         ^~~~~~~~~~~~~~~~~~~~~~
    mm/vmalloc.c:1236:1: note: declared here
    1236 | find_vmap_lowest_match(struct rb_root *root, unsigned long size,
         | ^~~~~~~~~~~~~~~~~~~~~~

    Extend find_vmap_lowest_match_check() and find_vmap_lowest_linear_match()
    with extra arguments to fix this.

    Link: https://lkml.kernel.org/r/20220906060548.1127396-1-song@kernel.org
    Link: https://lkml.kernel.org/r/20220831052734.3423079-1-song@kernel.org
    Fixes: f9863be49312 ("mm/vmalloc: extend __alloc_vmap_area() with extra arguments")
    Signed-off-by: Song Liu <song@kernel.org>
    Reviewed-by: Baoquan He <bhe@redhat.com>
    Reviewed-by: Uladzislau Rezki (Sony) <urezki@gmail.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>