selftests/bpf: Use syscall(SYS_gettid) instead of gettid() wrapper in bench
JIRA: https://issues.redhat.com/browse/RHEL-30773

commit 1684d6eb99e480ff653af60e20ff5e7e55e69ccd
Author: Alan Maguire <alan.maguire@oracle.com>
Date:   Fri Mar 22 09:57:28 2024 +0000

    selftests/bpf: Use syscall(SYS_gettid) instead of gettid() wrapper in bench
    
    With glibc 2.28, selftests compilation fails for benchs/bench_trigger.c:
    
    benchs/bench_trigger.c: In function ‘inc_counter’:
    benchs/bench_trigger.c:25:23: error: implicit declaration of function ‘gettid’; did you mean ‘getgid’? [-Werror=implicit-function-declaration]
       25 |                 tid = gettid();
          |                       ^~~~~~
          |                       getgid
    cc1: all warnings being treated as errors
    
    It appears support for the gettid() wrapper is variable across glibc
    versions, so may be safer to use syscall(SYS_gettid) instead.
    
    Fixes: 520fad2e3206 ("selftests/bpf: scale benchmark counting by using per-CPU counters")
    Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20240322095728.95671-1-alan.maguire@oracle.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>