s390/ctcm: Fix return type of ctc{mp,}m_tx()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit aa5bf80c3c067b82b4362cd6e8e2194623bcaca6

With clang's kernel control flow integrity (kCFI, CONFIG_CFI_CLANG),
indirect call targets are validated against the expected function
pointer prototype to make sure the call target is valid to help mitigate
ROP attacks. If they are not identical, there is a failure at run time,
which manifests as either a kernel panic or thread getting killed. A
proposed warning in clang aims to catch these at compile time, which
reveals:

  drivers/s390/net/ctcm_main.c:1064:21: error: incompatible function pointer types initializing 'netdev_tx_t (*)(struct sk_buff *, struct net_device *)' (aka 'enum netdev_tx (*)(struct sk_buff *, struct net_device *)') with an expression of type 'int (struct sk_buff *, struct net_device *)' [-Werror,-Wincompatible-function-pointer-types-strict]
          .ndo_start_xmit         = ctcm_tx,
                                    ^~~~~~~
  drivers/s390/net/ctcm_main.c:1072:21: error: incompatible function pointer types initializing 'netdev_tx_t (*)(struct sk_buff *, struct net_device *)' (aka 'enum netdev_tx (*)(struct sk_buff *, struct net_device *)') with an expression of type 'int (struct sk_buff *, struct net_device *)' [-Werror,-Wincompatible-function-pointer-types-strict]
          .ndo_start_xmit         = ctcmpc_tx,
                                    ^~~~~~~~~

->ndo_start_xmit() in 'struct net_device_ops' expects a return type of
'netdev_tx_t', not 'int'. Adjust the return type of ctc{mp,}m_tx() to
match the prototype's to resolve the warning and potential CFI failure,
should s390 select ARCH_SUPPORTS_CFI_CLANG in the future.

Additionally, while in the area, remove a comment block that is no
longer relevant.

Link: https://github.com/ClangBuiltLinux/linux/issues/1750
	Reviewed-by: Alexandra Winter <wintera@linux.ibm.com>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit aa5bf80c3c067b82b4362cd6e8e2194623bcaca6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>