libbpf: Show error info about missing ".BTF" section
Bugzilla: https://bugzilla.redhat.com/2178930

commit e6b4e1d759d3bfb7cb84c87cc8f1858da7db8dea
Author: Changbin Du <changbin.du@gmail.com>
Date:   Sun Dec 18 06:35:08 2022 +0800

    libbpf: Show error info about missing ".BTF" section
    
    Show the real problem instead of just saying "No such file or directory".
    
    Now will print below info:
    libbpf: failed to find '.BTF' ELF section in /home/changbin/work/linux/vmlinux
    Error: failed to load BTF from /home/changbin/work/linux/vmlinux: No such file or directory
    
    Signed-off-by: Changbin Du <changbin.du@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20221217223509.88254-2-changbin.du@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>