firmware_loader: Add sysfs nodes to monitor fw_upload
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-477.10.1.el8_8
commit-author Russ Weight <russell.h.weight@intel.com>
commit 536fd8184b7dfa30e28e5b459e7c5c91c3a8063f
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-477.10.1.el8_8/536fd818.failed

Add additional sysfs nodes to monitor the transfer of firmware upload data
to the target device:

cancel: Write 1 to cancel the data transfer
error: Display error status for a failed firmware upload
remaining_size: Display the remaining amount of data to be transferred
status: Display the progress of the firmware upload

	Reviewed-by: Luis Chamberlain <mcgrof@kernel.org>
	Reviewed-by: Tianfei zhang <tianfei.zhang@intel.com>
	Tested-by: Matthew Gerlach <matthew.gerlach@linux.intel.com>
	Signed-off-by: Russ Weight <russell.h.weight@intel.com>
Link: https://lore.kernel.org/r/20220421212204.36052-6-russell.h.weight@intel.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 536fd8184b7dfa30e28e5b459e7c5c91c3a8063f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	Documentation/ABI/testing/sysfs-class-firmware
#	Documentation/driver-api/firmware/fw_upload.rst
#	drivers/base/firmware_loader/sysfs.c
#	drivers/base/firmware_loader/sysfs_upload.c
#	drivers/base/firmware_loader/sysfs_upload.h