NFSD: Clean up errors in stats.c
JIRA: https://issues.redhat.com/browse/RHEL-34875

commit 0e5559ebe7f48d7957587e441abdaa331133d503
Author: KaiLong Wang <wangkailong@jari.cn>
Date:   Thu Sep 28 10:35:16 2023 +0800

    NFSD: Clean up errors in stats.c

    Fix the following errors reported by checkpatch:

    ERROR: space required after that ',' (ctx:VxV)

    Signed-off-by: KaiLong Wang <wangkailong@jari.cn>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Benjamin Coddington <bcodding@redhat.com>