io_uring: warning about unused-but-set parameter
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2107743

commit 00169246e6981752e53266c62d0ab0c827493634
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 19 17:34:53 2021 +0200

    io_uring: warning about unused-but-set parameter
    
    When enabling -Wunused warnings by building with W=1, I get an
    instance of the -Wunused-but-set-parameter warning in the io_uring code:
    
    fs/io_uring.c: In function 'io_queue_async_work':
    fs/io_uring.c:1445:61: error: parameter 'locked' set but not used [-Werror=unused-but-set-parameter]
     1445 | static void io_queue_async_work(struct io_kiocb *req, bool *locked)
          |                                                       ~~~~~~^~~~~~
    
    There are very few warnings of this type, so it would be nice to enable
    this by default and fix all the existing instances. As the assignment
    serves no purpose by itself other than to prevent developers from using
    the variable, an easy workaround is to remove the assignment and just
    rename the argument to "dont_use".
    
    Fixes: f237c30a5610 ("io_uring: batch task work locking")
    Link: https://lore.kernel.org/lkml/20210920121352.93063-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211019153507.348480-1-arnd@kernel.org
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>