kunit: Export kunit_running()
commit db105c37a4d69d684c1edf2915557463d0ba172c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 17 17:50:26 2023 +0100

    kunit: Export kunit_running()

    Using kunit_fail_current_test() in a loadable module causes a link
    error like:

    ERROR: modpost: "kunit_running" [drivers/gpu/drm/vc4/vc4.ko] undefined!

    Export the symbol to allow using it from modules.

    Fixes: da43ff045c3f ("drm/vc4: tests: Fail the current test if we access a register")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: David Gow <davidgow@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

JIRA: https://issues.redhat.com/browse/RHEL-5618
Signed-off-by: Nico Pache <npache@redhat.com>