arm64: Fix __cpu_logical_map undefined issue
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Kefeng Wang <wangkefeng.wang@huawei.com>
commit eaecca9e7710281be7c31d892c9f447eafd7ddd9

The __cpu_logical_map undefined issue occued when the new
tegra194-cpufreq drvier building as a module.

ERROR: modpost: "__cpu_logical_map" [drivers/cpufreq/tegra194-cpufreq.ko] undefined!

The driver using cpu_logical_map() macro which will expand to
__cpu_logical_map, we can't access it in a drvier. Let's turn
cpu_logical_map() into a C wrapper and export it to fix the
build issue.

Also create a function set_cpu_logical_map(cpu, hwid) when assign
a value to cpu_logical_map(cpu).

	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
	Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
(cherry picked from commit eaecca9e7710281be7c31d892c9f447eafd7ddd9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>