ata: ahci_qoriq: Fix compilation warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2162218

When compiling with clang and W=1, the following warning is generated:

drivers/ata/ahci_qoriq.c:283:22: error: cast to smaller integer type
'enum ahci_qoriq_type' from 'const void *'
[-Werror,-Wvoid-pointer-to-enum-cast]
                qoriq_priv->type = (enum ahci_qoriq_type)of_id->data;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by using a cast to unsigned long to match the "void *" type
size of of_id->data.

Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Acked-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit 2ce3a0bf2010b16c78b78cc35a97fa913f1be0ca)
Signed-off-by: Tomas Henzl <thenzl@redhat.com>