powerpc/powernv: Include asm/smp.h to fix UP build failure
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] powernv: Include asm/smp.h to fix UP build failure (Don Zickus) [1127366]
Rebuild_FUZZ: 92.59%
commit-author Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
commit b2a80878693256ab97e1e3667e24b3ecdc951de1

Build throws following errors when CONFIG_SMP=n
arch/powerpc/platforms/powernv/setup.c: In function ‘pnv_kexec_wait_secondaries_down’:
arch/powerpc/platforms/powernv/setup.c:179:4: error: implicit declaration of function ‘get_hard_smp_processor_id’
    rc = opal_query_cpu_status(get_hard_smp_processor_id(i),

The usage of get_hard_smp_processor_id() needs the declaration from
<asm/smp.h>. The file setup.c includes <linux/sched.h>, which in-turn
includes <linux/smp.h>. However, <linux/smp.h> includes <asm/smp.h>
only on SMP configs and hence UP builds fail.

Fix this by directly including <asm/smp.h> in setup.c unconditionally.

	Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Reviewed-by: Srivatsa S. Bhat <srivatsa.bhat@linux.vnet.ibm.com>
	Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
	Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
(cherry picked from commit b2a80878693256ab97e1e3667e24b3ecdc951de1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>