selftests/bpf: fix type conflict in test_tc_dtime
Bugzilla: https://bugzilla.redhat.com/2166911

commit ab9ac19c4d0615fee40ec7d49fa16c9fd33f61f8
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Thu Aug 25 23:06:59 2022 -0600

    selftests/bpf: fix type conflict in test_tc_dtime
    
    The sys/socket.h header isn't required to build test_tc_dtime and may
    cause a type conflict.
    
    Fixes the following error:
    In file included from /usr/include/x86_64-linux-gnu/sys/types.h:155,
                     from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                     from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                     from progs/test_tc_dtime.c:18:
    /usr/include/x86_64-linux-gnu/bits/stdint-intn.h:24:18: error: conflicting types for 'int8_t'; have '__int8_t' {aka 'signed char'}
       24 | typedef __int8_t int8_t;
          |                  ^~~~~~
    In file included from progs/test_tc_dtime.c:5:
    /home/buildroot/opt/cross/lib/gcc/bpf/13.0.0/include/stdint.h:34:23: note: previous declaration of 'int8_t' with type 'int8_t' {aka 'char'}
       34 | typedef __INT8_TYPE__ int8_t;
          |                       ^~~~~~
    /usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: error: conflicting types for 'int64_t'; have '__int64_t' {aka 'long long int'}
       27 | typedef __int64_t int64_t;
          |                   ^~~~~~~
    /home/buildroot/opt/cross/lib/gcc/bpf/13.0.0/include/stdint.h:43:24: note: previous declaration of 'int64_t' with type 'int64_t' {aka 'long int'}
       43 | typedef __INT64_TYPE__ int64_t;
          |                        ^~~~~~~
    make: *** [Makefile:537: /home/buildroot/bpf-next/tools/testing/selftests/bpf/bpf_gcc/test_tc_dtime.o] Error 1
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Link: https://lore.kernel.org/r/20220826050703.869571-1-james.hilliard1@gmail.com
    Signed-off-by: Martin KaFai Lau <kafai@fb.com>

Signed-off-by: Artem Savkov <asavkov@redhat.com>