perf: Always feature test reallocarray
JIRA: https://issues.redhat.com/browse/RHEL-78197

upstream
========
commit 4c4c0724d6521a8092b7c16f8f210c5869d95b17
Author: James Clark <james.clark@linaro.org>
Date: Wed Jan 29 15:44:05 2025 +0000

description
===========
This is also used in util/comm.c now, so instead of selectively doing
the feature test, always do it. If it's ever used anywhere else it's
less likely to cause another build failure.

This doesn't remove the need to manually include libc_compat.h, and
missing that will still cause an error for glibc < 2.26. There isn't a
way to fix that without poisoning reallocarray like libbpf did, but that
has other downsides like making memory debugging tools less useful. So
for Perf keep it like this and we'll have to fix up any missed includes.

Fixes the following build error:

  util/comm.c:152:31: error: implicit declaration of function
                      'reallocarray' [-Wimplicit-function-declaration]
  152 |                         tmp = reallocarray(comm_strs->strs,
      |                               ^~~~~~~~~~~~

Fixes: 13ca628716c6 ("perf comm: Add reference count checking to 'struct comm_str'")
    Reported-by: Ali Utku Selen <ali.utku.selen@arm.com>
    Signed-off-by: James Clark <james.clark@linaro.org>
    Reviewed-by: Ian Rogers <irogers@google.com>
    Link: https://lore.kernel.org/r/20250129154405.777533-1-james.clark@linaro.org
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>