perf probe: Fix to show correct error message for $vars and $params
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit f6eb0518f325ef0d6557fbef5c7ebe48a81e74db

Fix to show correct error messages for $vars and $params because
those special variables requires debug information to find the
real variables or function parameters.

E.g. without this fix;
  ----
  # perf probe -x /lib64/libc-2.23.so getaddrinfo \$params
  Failed to write event: Invalid argument
  Please upgrade your kernel to at least 3.14 to have access to feature $params
    Error: Failed to add events.
  ----

Perf ends up with an error, but the message is not correct.  With this
fix, perf shows correct error message as below.

  ----
  # perf probe -x /lib64/libc-2.23.so getaddrinfo \$params
  The /usr/lib64/libc-2.23.so file has no debug information.
  Rebuild with -g, or install an appropriate debuginfo package.
    Error: Failed to add events.
  ----

Reported-and-Tested-by: Arnaldo Carvalho de Melo <acme@kernel.org>
	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Cc: Ananth N Mavinakayanahalli <ananth@linux.vnet.ibm.com>
	Cc: Brendan Gregg <brendan.d.gregg@gmail.com>
	Cc: Hemant Kumar <hemant@linux.vnet.ibm.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/146831787438.17065.6152436996780110699.stgit@devbox
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit f6eb0518f325ef0d6557fbef5c7ebe48a81e74db)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>