net/sched/sch_prio.c: work around gcc-4.4.4 union initializer issues
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] sched: prio: work around gcc-4.4.4 union initializer issues (Ivan Vecera) [1584297]
Rebuild_FUZZ: 89.76%
commit-author Andrew Morton <akpm@linux-foundation.org>
commit ef58ca38dbda0642e293bcaa2e05edc79677c617
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/ef58ca38.failed

gcc-4.4.4 has problems witn anon union initializers.  Work around this.

net/sched/sch_prio.c: In function 'prio_dump_offload':
net/sched/sch_prio.c:260: error: unknown field 'stats' specified in initializer
net/sched/sch_prio.c:260: warning: initialization makes integer from pointer without a cast
net/sched/sch_prio.c:261: error: unknown field 'stats' specified in initializer
net/sched/sch_prio.c:261: warning: initialization makes integer from pointer without a cast

Fixes: 7fdb61b44c0c95 ("net: sch: prio: Add offload ability to PRIO qdisc")
	Cc: Nogah Frankel <nogahf@mellanox.com>
	Cc: Yuval Mintz <yuvalm@mellanox.com>
	Cc: Jiri Pirko <jiri@mellanox.com>
	Cc: David S. Miller <davem@davemloft.net>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ef58ca38dbda0642e293bcaa2e05edc79677c617)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/sched/sch_prio.c