firmware: arm_scmi: Avoid non-constant printk format strings
JIRA: https://issues.redhat.com/browse/RHEL-65607

commit 495667d49c5067ef4f732dcc44c9a7b0d7e98d39
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 3 13:10:24 2024 +0200

    firmware: arm_scmi: Avoid non-constant printk format strings

    A recent rework changed the constant format strings to a local variable,
    which causes warnings from clang when -Wformat-security is enabled:

    drivers/firmware/arm_scmi/driver.c: In function 'scmi_probe':
    drivers/firmware/arm_scmi/driver.c:2936:25: error: format not a string literal and no format arguments [-Werror=format-security]
     2936 |                         dev_err(dev, err_str);
          |                         ^~~~~~~
    drivers/firmware/arm_scmi/driver.c:2993:9: error: format not a string literal and no format arguments [-Werror=format-security]
     2993 |         return dev_err_probe(dev, ret, err_str);

    Print these using an explicit "%s" string instead.

    Fixes: 3a7d93d1f71b ("firmware: arm_scmi: Use dev_err_probe to bail out")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240403111040.3924658-1-arnd@kernel.org
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>

(cherry picked from commit 495667d49c5067ef4f732dcc44c9a7b0d7e98d39)
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>