scsi: qedf: Remove unused 'num_handled' variable
JIRA: https://issues.redhat.com/browse/RHEL-9887

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit 7866e03b9825e1e08fc5136d3ab9a35ebabdc7f5
Author: Tom Rix <trix@redhat.com>
Date:   Thu Mar 30 16:34:44 2023 -0400

    scsi: qedf: Remove unused 'num_handled' variable

    clang with W=1 reports:

    drivers/scsi/qedf/qedf_main.c:2227:6: error: variable
      'num_handled' set but not used [-Werror,-Wunused-but-set-variable]
            int num_handled = 0;
                ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230330203444.1842425-1-trix@redhat.com
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>