powerpc/pseries: Fix CONFIG_NUMA=n build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [powerpc] pseries: Fix CONFIG_NUMA=n build (Gustavo Duarte) [1544437]
Rebuild_FUZZ: 88.89%
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit 6c0a8f6b5a45ac892a763b6299bd3c5324fc5e02

The build is failing with CONFIG_NUMA=n and some compiler versions:

  arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_online_cpu':
  hotplug-cpu.c:(.text+0x12c): undefined reference to `timed_topology_update'
  arch/powerpc/platforms/pseries/hotplug-cpu.o: In function `dlpar_cpu_remove':
  hotplug-cpu.c:(.text+0x400): undefined reference to `timed_topology_update'

Fix it by moving the empty version of timed_topology_update() into the
existing #ifdef block, which has the right guard of SPLPAR && NUMA.

Fixes: cee5405da402 ("powerpc/hotplug: Improve responsiveness of hotplug change")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 6c0a8f6b5a45ac892a763b6299bd3c5324fc5e02)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>