fbdev: nvidiafb: add depends on HAS_IOPORT
JIRA: https://issues.redhat.com/browse/RHEL-107473

commit ecdd7df997fd992f0ec70b788e3b12258008a2bf
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sun Jun 15 11:36:51 2025 -0700

    fbdev: nvidiafb: add depends on HAS_IOPORT

    The nvidiafb driver uses inb()/outb() without depending on HAS_IOPORT,
    which leads to build errors since kernel v6.13-rc1:
    commit 6f043e757445 ("asm-generic/io.h: Remove I/O port accessors
    for HAS_IOPORT=n")

    Add the HAS_IOPORT dependency to prevent the build errors.

    (Found in ARCH=um allmodconfig builds)

    drivers/video/fbdev/nvidia/nv_accel.c: In function ‘NVDmaWait’:
    include/asm-generic/io.h:596:15: error: call to ‘_outb’ declared with attribute error: outb() requires CONFIG_HAS_IOPORT
      596 | #define _outb _outb

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Arnd Bergmann <arnd@kernel.org>
    Cc: Niklas Schnelle <schnelle@linux.ibm.com>
    Cc: Antonino Daplas <adaplas@gmail.com>
    Cc: Helge Deller <deller@gmx.de>
    Cc: linux-fbdev@vger.kernel.org
    Cc: dri-devel@lists.freedesktop.org
    Cc: stable@vger.kernel.org # v6.13+
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: José Expósito <jexposit@redhat.com>