perf/arm-cmn: Fix resource_size_t printk specifier in arm_cmn_init_dtc()
JIRA: https://issues.redhat.com/browse/RHEL-234652

commit 47f06ebbe8dad695002e5d9a2ab436411f88e985
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Mar 25 19:19:26 2026 -0700

    perf/arm-cmn: Fix resource_size_t printk specifier in arm_cmn_init_dtc()

    When building for 32-bit ARM, there is a warning when using the %llx
    specifier to print a resource_size_t variable:

      drivers/perf/arm-cmn.c: In function 'arm_cmn_init_dtc':
      drivers/perf/arm-cmn.c:2149:73: error: format '%llx' expects argument of type 'long long unsigned int', but argument 4 has type 'resource_size_t' {aka 'unsigned int'} [-Werror=format=]
       2149 |                                      "Failed to request DTC region 0x%llx\n", base);
            |                                                                      ~~~^     ~~~~
            |                                                                         |     |
            |                                                                         |     resource_size_t {aka unsigned int}
            |                                                                         long long unsigned int
            |                                                                      %x

    Use the %pa specifier to handle the possible sizes of phys_addr_t
    properly. This requires passing the variable by reference.

    Fixes: 5394396ff548 ("perf/arm-cmn: Stop claiming entire iomem region")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Robin murphy <robin.murphy@arm.com>
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Jeremy Linton <jlinton@redhat.com>