iommu/vt-d: Don't dereference iommu_device if IOMMU_API is not built
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [iommu] vt-d: Don't dereference iommu_device if IOMMU_API is not built (Vitaly Kuznetsov) [1887216]
Rebuild_FUZZ: 95.38%
commit-author Bartosz Golaszewski <bgolaszewski@baylibre.com>
commit 9def3b1a07c41e21c68a0eb353e3e569fdd1d2b1

Since commit c40aaaac1018 ("iommu/vt-d: Gracefully handle DMAR units
with no supported address widths") dmar.c needs struct iommu_device to
be selected. We can drop this dependency by not dereferencing struct
iommu_device if IOMMU_API is not selected and by reusing the information
stored in iommu->drhd->ignored instead.

This fixes the following build error when IOMMU_API is not selected:

drivers/iommu/intel/dmar.c: In function ‘free_iommu’:
drivers/iommu/intel/dmar.c:1139:41: error: ‘struct iommu_device’ has no member named ‘ops’
 1139 |  if (intel_iommu_enabled && iommu->iommu.ops) {
                                                ^

Fixes: c40aaaac1018 ("iommu/vt-d: Gracefully handle DMAR units with no supported address widths")
	Signed-off-by: Bartosz Golaszewski <bgolaszewski@baylibre.com>
	Acked-by: Lu Baolu <baolu.lu@linux.intel.com>
	Acked-by: David Woodhouse <dwmw@amazon.co.uk>
Link: https://lore.kernel.org/r/20201013073055.11262-1-brgl@bgdev.pl
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 9def3b1a07c41e21c68a0eb353e3e569fdd1d2b1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>