mtd: rawnand: qcom: Fix build issue on x86 architecture
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit b9371866799d67a80be0ea9e01bd41987db22f26
Author: Md Sadre Alam <quic_mdalam@quicinc.com>
Date:   Mon Jan 6 18:45:58 2025 +0530

    mtd: rawnand: qcom: Fix build issue on x86 architecture

    Fix a buffer overflow issue in qcom_clear_bam_transaction by using
    struct_group to group related fields and avoid FORTIFY_SOURCE warnings.

    On x86 architecture, the following error occurs due to warnings being
    treated as errors:

    In function ‘fortify_memset_chk’,
        inlined from ‘qcom_clear_bam_transaction’ at
    drivers/mtd/nand/qpic_common.c:88:2:
    ./include/linux/fortify-string.h:480:25: error: call to ‘__write_overflow_field’
    declared with attribute warning: detected write beyond size of field
    (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
      480 |                         __write_overflow_field(p_size_field, size);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      LD [M]  drivers/mtd/nand/nandcore.o
      CC [M]  drivers/w1/masters/mxc_w1.o
    cc1: all warnings being treated as errors

    This patch addresses the issue by grouping the related fields in
    struct bam_transaction using struct_group and updating the memset call
    accordingly.

    Fixes: 8c52932da5e6 ("mtd: rawnand: qcom: cleanup qcom_nandc driver")
    Signed-off-by: Md Sadre Alam <quic_mdalam@quicinc.com>
    Signed-off-by: Miquel Raynal <miquel.raynal@bootlin.com>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>