ASoC: codecs: aw88395: initialize cur_scene_id to 0
Bugzilla: https://bugzilla.redhat.com/2179848

commit 983272a2a223de59dbb4cb189aa4d02d7156d209
Author: Tom Rix <trix@redhat.com>
Date: Sat Feb 4 17:57:33 2023 -0800

    ASoC: codecs: aw88395: initialize cur_scene_id to 0

    cppcheck reports
    sound/soc/codecs/aw88395/aw88395_lib.c:789:6: error: Uninitialized variable: cur_scene_id [uninitvar]
     if (cur_scene_id == 0) {
         ^

    Passing a garbage value to aw_dev_parse_data_by_sec_type_v1() will cause a crash
    when the value is used as an array index.  This check assumes cur_scene_id is
    initialized to 0, so initialize it to 0.

    Fixes: 4345865b003b ("ASoC: codecs: ACF bin parsing and check library file for aw88395")
    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230205015733.1721009-1-trix@redhat.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>