md/raid1: fix error: ISO C90 forbids mixed declarations
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-516.el8
commit-author Nigel Croxon <ncroxon@redhat.com>
commit df203da47f4428bc286fc99318936416253a321c

There is a compile error when this commit is added:
md: raid1: fix potential OOB in raid1_remove_disk()

drivers/md/raid1.c: In function 'raid1_remove_disk':
drivers/md/raid1.c:1844:9: error: ISO C90 forbids mixed declarations
and code [-Werror=declaration-after-statement]
1844 |         struct raid1_info *p = conf->mirrors + number;
     |         ^~~~~~

That's because the new code was inserted before the struct.
The change is move the struct command above this commit.

Fixes: 8b0472b50bcf ("md: raid1: fix potential OOB in raid1_remove_disk()")
	Signed-off-by: Nigel Croxon <ncroxon@redhat.com>
	Signed-off-by: Song Liu <song@kernel.org>
Link: https://lore.kernel.org/r/46d929d0-2aab-4cf2-b2bf-338963e8ba5a@redhat.com
(cherry picked from commit df203da47f4428bc286fc99318936416253a321c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>