powerpc/mm: Move tlbcam_sz() and make it static
Bugzilla: https://bugzilla.redhat.com/2160210

commit ff47a95d1a67477e9bc2049a840d93b68508e079
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Wed Nov 24 20:32:52 2021 +1100

    powerpc/mm: Move tlbcam_sz() and make it static

    Building with W=1 we see a warning:
      linux/arch/powerpc/mm/nohash/fsl_book3e.c:63:15: error: no previous protot
ype for ‘tlbcam_sz’

    tlbcam_sz() is not used outside this file, so we can make it static.
    However it's only used inside #ifdef CONFIG_PPC32, so move it within
    that ifdef, otherwise we would get a defined but not used error.

    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20211124093254.1054750-4-mpe@ellerman.id.au

Signed-off-by: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>