sched/psi: Select KERNFS as needed
JIRA: https://issues.redhat.com/browse/RHEL-34600

commit 98dfdd9ee93995a408192dbbf3dd219ba23e3738
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sun, 30 Jul 2023 20:07:40 -0700

    sched/psi: Select KERNFS as needed

    Users of KERNFS should select it to enforce its being built, so
    do this to prevent a build error.

    In file included from ../kernel/sched/build_utility.c:97:
    ../kernel/sched/psi.c: In function 'psi_trigger_poll':
    ../kernel/sched/psi.c:1479:17: error: implicit declaration of function 'kernfs_generic_poll' [-Werror=implicit-function-declaration]
     1479 |                 kernfs_generic_poll(t->of, wait);

    Fixes: aff037078eca ("sched/psi: use kernfs polling functions for PSI trigger polling")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Suren Baghdasaryan <surenb@google.com>
    Link: lore.kernel.org/r/202307310732.r65EQFY0-lkp@intel.com

Signed-off-by: Waiman Long <longman@redhat.com>