dm vdo indexer: prevent unterminated string warning
JIRA: https://issues.redhat.com/browse/RHEL-119008
Upstream Status: kernel/git/torvalds/linux.git

commit f4e99b846c90163d350c69d6581ac38dd5818eb8
Author: Chung Chung <cchung@redhat.com>
Date:   Wed Jan 29 18:27:12 2025 -0500

    dm vdo indexer: prevent unterminated string warning

    Fix array initialization that triggers a warning:

    error: initializer-string for array of ‘unsigned char’ is too long
     [-Werror=unterminated-string-initialization]

    Signed-off-by: Chung Chung <cchung@redhat.com>
    Signed-off-by: Matthew Sakai <msakai@redhat.com>
    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>

Signed-off-by: Benjamin Marzinski <bmarzins@redhat.com>