usb: hcd: Bump local buffer size in rh_string()
JIRA: https://issues.redhat.com/browse/RHEL-78931

commit 70cd0576aa39c55aabd227851cba0c601e811fb6
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date: Thu, 16 Jan 2025 18:05:43 +0200

  GCC is not happy about the buffer size:

  drivers/usb/core/hcd.c:441:48: error: ‘%s’ directive output may be truncated writing up to 64 bytes into a region of size between 35 and 99 [-Werror=format-truncation=]
    441 |                 snprintf (buf, sizeof buf, "%s %s %s", init_utsname()->sysname,
        |                                                ^~
    442 |                         init_utsname()->release, hcd->driver->description);
        |                         ~~~~~~~~~~~~~~~~~~~~~~~

  Bump the size to get it enough for the possible strings.

  Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
  Link: https://lore.kernel.org/r/20250116160543.216913-1-andriy.shevchenko@linux.intel.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>