ASoC: wm_adsp: select CONFIG_SND_SOC_WM_ADSP from all users
JIRA: https://issues.redhat.com/browse/RHEL-183295

commit e3f1ce073a0dd2b319bd1541c461f153306ca163
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Mar 20 16:17:31 2026 +0100

    ASoC: wm_adsp: select CONFIG_SND_SOC_WM_ADSP from all users

    The addition of the kunit test made it possible to enable the WM_ADSP
    driver even when there are no users. However, an unintended side-effect
    was that it is also possible to turn it off when it is actually required,
    leading to build failures:

    ERROR: modpost: "wm_halo_init" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
    ERROR: modpost: "wm_adsp2_remove" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
    ERROR: modpost: "wm_adsp_hibernate" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
    ERROR: modpost: "wm_adsp2_component_probe" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!

    Reverse the logic to replace the ununual list of 'default y if ....' with
    the regular 'select' that do the same thing but prevent it from being
    disabled if that would break the build.

    Fixes: bf2d44d07de7 ("ASoC: wm_adsp: Add kunit test for firmware file search")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Link: https://patch.msgid.link/20260320151752.3439218-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>