ACPI: Fix build failure when CONFIG_NLS is set to 'n'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Sinan Kaya <okaya@kernel.org>
commit 2e61069b056f7ac3cde5f84a4be8aa703b57089d

Observing link failure as follows when CONFIG_ACPI is set but
both CONFIG_NLS and CONFIG_PCI are no set:

drivers/acpi/device_sysfs.o: In function `description_show':
device_sysfs.c:(.text+0x48a): undefined reference to `utf16s_to_utf8s'

This issue was previously addressed implicitly by commit 8a226e00eeed
(PCI: pci-label: Fix build failure when CONFIG_NLS is set to 'm' by
allmodconfig) causing PCI_LABEL to be selected when ACPI was set
which caused NLS to be selected too in that case.

However, after commit 5d32a66541c46 (PCI/ACPI: Allow ACPI to be built
without CONFIG_PCI set) it is possible to build ACPI support without
PCI, so make ACPI select NLS directly to cover that case.

Fixes: 5d32a66541c46 (PCI/ACPI: Allow ACPI to be built without CONFIG_PCI set)
	Signed-off-by: Sinan Kaya <okaya@kernel.org>
[ rjw: Changelog ]
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 2e61069b056f7ac3cde5f84a4be8aa703b57089d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>