Revert "firmware: qcom: scm: Add support for MC boot address API"
Bugzilla: https://bugzilla.redhat.com/2213601

commit 7db2bc925e4642df6255612e5521af0423ada18a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Oct 27 16:25:07 2021 +0200

    Revert "firmware: qcom: scm: Add support for MC boot address API"

    This reverts commits 55845f46df03 and c50031f03dfe, since this still
    causes a build failure when QCOM_SCM is a loadable module, or when
    CONFIG_SMP is disabled:

    ERROR: modpost: "cpu_logical_map" [drivers/firmware/qcom-scm.ko] undefined!

    This be done better for 5.17, but it's too late now to rework
    properly.

    Fixes: c50031f03dfe ("firmware: qcom: scm: Don't break compile test on non-ARM platforms")
    Fixes: 55845f46df03 ("firmware: qcom: scm: Add support for MC boot address API")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>