eth: bnxt: fix string truncation warning in FW version
JIRA: https://issues.redhat.com/browse/RHEL-107291

commit 17656eb5cfe5b7287dc7f1b21ad02acc25ecdb15
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Fri Jan 17 10:37:26 2025 -0800

    eth: bnxt: fix string truncation warning in FW version

    W=1 builds with gcc 14.2.1 report:

    drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:4193:32: error: ‘%s’ directive output may be truncated writing up to 31 bytes into a region of size 27 [-Werror=format-truncation=]
     4193 |                          "/pkg %s", buf);

    It's upset that we let buf be full length but then we use 5
    characters for "/pkg ".

    The builds is also clear with clang version 19.1.5 now.

    Reviewed-by: Michael Chan <michael.chan@broadcom.com>
    Link: https://patch.msgid.link/20250117183726.1481524-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>