mmc: rtsx_usb_sdmmc: Fix clang -Wimplicit-fallthrough in sd_set_power_mode()
JIRA: https://issues.redhat.com/browse/RHEL-122019

commit 3ab659eb696f0aa0373469c1abb9e242a74d3796
Author: Nathan Chancellor <nathan@kernel.org>
Date: Fri, 20 Jun 2025 11:25:22 -0700

  Clang warns (or errors with CONFIG_WERROR=y):

    drivers/mmc/host/rtsx_usb_sdmmc.c:1042:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
     1042 |         case MMC_POWER_UNDEFINED:
          |         ^
    drivers/mmc/host/rtsx_usb_sdmmc.c:1042:2: note: insert 'break;' to avoid fall-through
     1042 |         case MMC_POWER_UNDEFINED:
          |         ^
          |         break;

  Clang is a little more pedantic than GCC, which does not warn when
  falling through to a case that is just break or return. Clang's version
  is more in line with the kernel's own stance in deprecated.rst, which
  states that all switch/case blocks must end in either break,
  fallthrough, continue, goto, or return. Add the missing break to silence
  the warning.

  Fixes: 2c3809bd6f65 ("mmc: rtsx_usb_sdmmc: Add 74 clocks in poweron flow")
  Signed-off-by: Nathan Chancellor <nathan@kernel.org>
  Link: https://lore.kernel.org/r/20250620-mmc-rtsx-usb-sdmmc-fix-clang-implicit-fallthrough-v1-1-4031d11159c0@kernel.org
  Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>