sched: Hide unused sched_update_scaling()
JIRA: https://issues.redhat.com/browse/RHEL-1536

commit d55ebae3f3122b07689cc4c34043114e09ce904c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon May 22 21:50:17 2023 +0200

    sched: Hide unused sched_update_scaling()

    This function is only used when CONFIG_SMP is enabled, without that there
    is no caller and no prototype:

    kernel/sched/fair.c:688:5: error: no previous prototype for 'sched_update_scaling' [-Werror=missing-prototypes

    Hide the definition in the same #ifdef check as the declaration.

    Fixes: 8a99b6833c88 ("sched: Move SCHED_DEBUG sysctl to debugfs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Vincent Guittot <vincent.guittot@linaro.org>
    Link: https://lore.kernel.org/r/20230522195021.3456768-2-arnd@kernel.org

Signed-off-by: Phil Auld <pauld@redhat.com>