pktgen: add needed include file
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Stephen Rothwell <sfr@canb.auug.org.au>
commit 73d94e9481a20817abe2f1b41ee441bb4f6461f7
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-693.el7/73d94e94.failed

Fixes this on PowerPC (at least):

net/core/pktgen.c: In function 'fill_packet_ipv6':
net/core/pktgen.c:2906:3: error: implicit declaration of function 'csum_ipv6_magic' [-Werror=implicit-function-declaration]
   udph->check = ~csum_ipv6_magic(&iph->saddr, &iph->daddr, udplen, IPPROTO_UDP, 0);
   ^

	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 73d94e9481a20817abe2f1b41ee441bb4f6461f7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/core/pktgen.c