perf tools: Fix statfs.f_type data type mismatch build error with uclibc
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] tools: Fix statfs.f_type data type mismatch build error with uclibc (Jiri Olsa) [1209607]
Rebuild_FUZZ: 96.40%
commit-author Alexey Brodkin <abrodkin@synopsys.com>
commit db1806edcfef007d9594435a331dcf7e7f1b8fac

ARC Linux uses the no legacy syscalls abi and corresponding uClibc headers
statfs defines f_type to be U32 which causes perf build breakage

http://git.uclibc.org/uClibc/tree/libc/sysdeps/linux/common-generic/bits/statfs.h

  ----------->8---------------
    CC       fs/fs.o
  fs/fs.c: In function 'fs__valid_mount':
  fs/fs.c:82:24: error: comparison between signed and unsigned integer
  expressions [-Werror=sign-compare]
    else if (st_fs.f_type != magic)
                          ^
  cc1: all warnings being treated as errors
  ----------->8---------------

	Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
	Acked-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Borislav Petkov <bp@suse.de>
	Cc: Cody P Schafer <dev@codyps.com>
	Cc: Ingo Molnar <mingo@kernel.org>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Vineet Gupta <Vineet.Gupta1@synopsys.com>
Link: http://lkml.kernel.org/r/1420888254-17504-2-git-send-email-vgupta@synopsys.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit db1806edcfef007d9594435a331dcf7e7f1b8fac)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>