vfio-mdev: fix non-standard ioctl return val causing i386 build fail
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Paul Gortmaker <paul.gortmaker@windriver.com>
commit c6ef7fd40eddad38a8825cbd6bb2ce8bdbba88f5
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-693.el7/c6ef7fd4.failed

What appears to be a copy and paste error from the line above gets
the ioctl a ssize_t return value instead of the traditional "int".

The associated sample code used "long" which meant it would compile
for x86-64 but not i386, with the latter failing as follows:

  CC [M]  samples/vfio-mdev/mtty.o
samples/vfio-mdev/mtty.c:1418:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ioctl          = mtty_ioctl,
                    ^
samples/vfio-mdev/mtty.c:1418:20: note: (near initialization for ‘mdev_fops.ioctl’)
cc1: some warnings being treated as errors

Since in this case, vfio is working with struct file_operations; as such:

    long (*unlocked_ioctl) (struct file *, unsigned int, unsigned long);
    long (*compat_ioctl) (struct file *, unsigned int, unsigned long);

...and so here we just standardize on long vs. the normal int that user
space typically sees and documents as per "man ioctl" and similar.

Fixes: 9d1a546c53b4 ("docs: Sample driver to demonstrate how to use Mediated device framework.")
	Cc: Kirti Wankhede <kwankhede@nvidia.com>
	Cc: Neo Jia <cjia@nvidia.com>
	Cc: kvm@vger.kernel.org
	Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
	Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
(cherry picked from commit c6ef7fd40eddad38a8825cbd6bb2ce8bdbba88f5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/linux/mdev.h