arm64: cpufeature: Export this_cpu_has_cap helper
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2076088

commit 20b02fe36530a1e48dde73c80b882ae276346ea3
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 3 Nov 2021 22:12:56 +0000

    Export the this_cpu_has_cap() for use by modules. This is
    used by TRBE driver. Without this patch, TRBE will fail
    to build as a module :

    ERROR: modpost: "this_cpu_has_cap" [drivers/hwtracing/coresight/coresight-trbe.ko] undefined!

    Fixes: 8a1065127d95 ("coresight: trbe: Add infrastructure for Errata handling")
    Cc: Will Deacon <will@kernel.org>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Mathieu Poirier <mathieu.poirier@linaro.org>
    Cc: Anshuman Khandual <anshuman.khandual@arm.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    [ change to EXPORT_SYMBOL_GPL ]
    Acked-by: Catalin Marinas <catalin.marinas@arm.com>
    Signed-off-by: Suzuki K Poulose <suzuki.poulose@arm.com>
    [ Added Will AB tag]
    Acked-by: Will Deacon <will@kernel.org>
    Link: https://lore.kernel.org/r/20211103221256.725080-1-suzuki.poulose@arm.com
    Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>

Signed-off-by: Mark Salter <msalter@redhat.com>