ASoC: Intel: sof_da7219_mx98360a: Access num_codecs through dai_link
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit 0402cca4828dd9556d36ddef67710993b7063f7c

After commit 3989ade2d1e7 ("ASoC: soc.h: remove num_cpus/codecs"), the
following build error occurs:

  sound/soc/intel/boards/sof_da7219_max98373.c:198:27: error: no member named 'num_codecs' in 'struct snd_soc_pcm_runtime'
          for (j = 0; j < runtime->num_codecs; j++) {
                          ~~~~~~~  ^
  1 error generated.

This conversion was missed by the aforementioned change. Do it now to
fix the build error.

Fixes: 3989ade2d1e7 ("ASoC: soc.h: remove num_cpus/codecs")
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20220922153752.336193-1-nathan@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0402cca4828dd9556d36ddef67710993b7063f7c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>