net/mlx5e: Fix build error in fec_set_block_stats()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Jakub Kicinski <kuba@kernel.org>
commit 342402c426902c59491b43d3056a1039e5ca02db

Build bot reports:

drivers/net/ethernet/mellanox/mlx5/core/en_stats.c: In function 'fec_set_block_stats':
drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:1235:48: error: 'outl' undeclared (first use in this function); did you mean 'out'?
    1235 |         if (mlx5_core_access_reg(mdev, in, sz, outl, sz, MLX5_REG_PPCNT, 0, 0))
         |                                                ^~~~
         |                                                out

	Reported-by: kernel test robot <lkp@intel.com>
	Suggested-by: Leon Romanovsky <leon@kernel.org>
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Link: https://lore.kernel.org/r/20220109213321.2292830-1-kuba@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 342402c426902c59491b43d3056a1039e5ca02db)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>