net: sched: cls_u32: disallow linking to root hnode
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [net] sched: cls_u32: disallow linking to root hnode (Ivan Vecera) [1688236 1687456]
Rebuild_FUZZ: 94.85%
commit-author Al Viro <viro@zeniv.linux.org.uk>
commit 27594ec4b6a7035450ba43624d1648cbd2c0aaea

Operation makes no sense.  Nothing will actually break if we do so
(depth limit in u32_classify() will prevent infinite loops), but
according to maintainers it's best prohibited outright.

NOTE: doing so guarantees that u32_destroy() will trigger the call
of u32_destroy_hnode(); we might want to make that unconditional.

Test:
tc qdisc add dev eth0 ingress
tc filter add dev eth0 parent ffff: protocol ip prio 100 u32 \
link 800: offset at 0 mask 0f00 shift 6 plus 0 eat match ip protocol 6 ff
should fail with
Error: cls_u32: Not linking to root node

	Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
	Signed-off-by: Jamal Hadi Salim <jhs@mojatatu.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 27594ec4b6a7035450ba43624d1648cbd2c0aaea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>