soundwire: intel: Fix uninitialized adev deref
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [drivers] ALSA: soundwire: intel: Fix uninitialized adev deref (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 93.88%
commit-author Vinod Koul <vkoul@kernel.org>
commit e1c815f4b24a305e5bc9eceb541674bf4d02b709

In case of error, we can dereference uninitialized 'adev'

drivers/soundwire/intel_init.c:154 sdw_intel_acpi_cb()
error: uninitialized symbol 'adev'.

Fix that by not using adev for warn print and make it pr_err.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Signed-off-by: Vinod Koul <vkoul@kernel.org>
(cherry picked from commit e1c815f4b24a305e5bc9eceb541674bf4d02b709)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>