ath11k: fix m68k and xtensa build failure in ath11k_peer_assoc_h_smps()
Bugzilla: http://bugzilla.redhat.com/2043454

commit 16bdce2ada5a4c3c91b7c4e81780d2de50bd6ab5
Author: Kalle Valo <kvalo@codeaurora.org>
Date:   Fri Oct 8 17:39:32 2021 +0300

    ath11k: fix m68k and xtensa build failure in ath11k_peer_assoc_h_smps()
    
    Stephen reported that ath11k was failing to build on m68k and xtensa:
    
    In file included from <command-line>:0:0:
    In function 'ath11k_peer_assoc_h_smps',
        inlined from 'ath11k_peer_assoc_prepare' at drivers/net/wireless/ath/ath11k/mac.c:2362:2:
    include/linux/compiler_types.h:317:38: error: call to '__compiletime_assert_650' declared with attribute error: FIELD_GET: type of reg too small for mask
      _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
                                          ^
    include/linux/compiler_types.h:298:4: note: in definition of macro '__compiletime_assert'
        prefix ## suffix();    \
        ^
    include/linux/compiler_types.h:317:2: note: in expansion of macro '_compiletime_assert'
      _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      ^
    include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
     #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                         ^
    include/linux/bitfield.h:52:3: note: in expansion of macro 'BUILD_BUG_ON_MSG'
       BUILD_BUG_ON_MSG((_mask) > (typeof(_reg))~0ull,  \
       ^
    include/linux/bitfield.h:108:3: note: in expansion of macro '__BF_FIELD_CHECK'
       __BF_FIELD_CHECK(_mask, _reg, 0U, "FIELD_GET: "); \
       ^
    drivers/net/wireless/ath/ath11k/mac.c:2079:10: note: in expansion of macro 'FIELD_GET'
       smps = FIELD_GET(IEEE80211_HE_6GHZ_CAP_SM_PS,
    
    Fix the issue by using le16_get_bits() to specify the size explicitly.
    
    Fixes: 6f4d70308e5e ("ath11k: support SMPS configuration for 6 GHz")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Tested-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>