futex: Relax the rcu_assign_pointer() assignment of mm->futex_phash in futex_mm_init()
JIRA: https://issues.redhat.com/browse/RHEL-101509

commit 094ac8cff7858bee5fa4554f6ea66c964f8e160e
Author: Ingo Molnar <mingo@kernel.org>
Date:   Sat, 10 May 2025 10:45:28 +0200

    futex: Relax the rcu_assign_pointer() assignment of mm->futex_phash in futex_mm_init()

    The following commit added an rcu_assign_pointer() assignment to
    futex_mm_init() in <linux/futex.h>:

      bd54df5ea7ca ("futex: Allow to resize the private local hash")

    Which breaks the build on older compilers (gcc-9, x86-64 defconfig):

       CC      io_uring/futex.o
       In file included from ./arch/x86/include/generated/asm/rwonce.h:1,
                        from ./include/linux/compiler.h:390,
                        from ./include/linux/array_size.h:5,
                        from ./include/linux/kernel.h:16,
                        from io_uring/futex.c:2:
       ./include/linux/futex.h: In function 'futex_mm_init':
       ./include/linux/rcupdate.h:555:36: error: dereferencing pointer to incomplete type 'struct futex_private_hash'

    The problem is that this variant of rcu_assign_pointer() wants to
    know the full type of 'struct futex_private_hash', which type
    is local to futex.c:

       kernel/futex/core.c:struct futex_private_hash {

    There are a couple of mechanical solutions for this bug:

      - we can uninline futex_mm_init() and move it into futex/core.c

      - or we can share the structure definition with kernel/fork.c.

    But both of these solutions have disadvantages: the first one adds
    runtime overhead, while the second one dis-encapsulates private
    futex types.

    A third solution, implemented by this patch, is to just initialize
    mm->futex_phash with NULL like the patch below, it's not like this
    new MM's ->futex_phash can be observed externally until the task
    is inserted into the task list, which guarantees full store ordering.

    The relaxation of this initialization might also give a tiny speedup
    on certain platforms.

    Fixes: bd54df5ea7ca ("futex: Allow to resize the private local hash")
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Cc: André Almeida <andrealmeid@igalia.com>
    Cc: Darren Hart <dvhart@infradead.org>
    Cc: Davidlohr Bueso <dave@stgolabs.net>
    Cc: Juri Lelli <juri.lelli@redhat.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
    Cc: Valentin Schneider <vschneid@redhat.com>
    Cc: Waiman Long <longman@redhat.com>
    Link: https://lore.kernel.org/r/aB8SI00EHBri23lB@gmail.com

Signed-off-by: Waiman Long <longman@redhat.com>