Documentation: Fix description format for powerpc RTAS ioctls
JIRA: https://issues.redhat.com/browse/RHEL-101838

commit 03c9d1a5a30d93bff31b4eb0a52f030b4c7f73ea
Author: Haren Myneni <haren@linux.ibm.com>
Date:   Tue Apr 29 19:28:47 2025 -0700

    Documentation: Fix description format for powerpc RTAS ioctls

    Fix the description format for the following build warnings:

    "Documentation/userspace-api/ioctl/ioctl-number.rst:369:
    ERROR: Malformed table. Text in column margin in table line 301.

    0xB2  03-05 arch/powerpc/include/uapi/asm/papr-indices.h
    powerpc/pseries indices API
                                <mailto:linuxppc-dev>
    0xB2  06-07 arch/powerpc/include/uapi/asm/papr-platform-dump.h
    powerpc/pseries Platform Dump API
                                <mailto:linuxppc-dev>
    0xB2  08  arch/powerpc/include/uapi/asm/papr-physical-attestation.h
    powerpc/pseries Physical Attestation API
                                <mailto:linuxppc-dev>"

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Haren Myneni <haren@linux.ibm.com>
    Fixes: 43d869ac25f1 ("powerpc/pseries: Define papr_indices_io_block for papr-indices ioctls")
    Fixes: 8aa9efc0be66 ("powerpc/pseries: Add papr-platform-dump character driver for dump retrieval")
    Fixes: 86900ab620a4 ("powerpc/pseries: Add a char driver for physical-attestation RTAS")
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Reviewed-by: Bagas Sanjaya <bagasdotme@gmail.com>
    Closes: https://lore.kernel.org/linux-next/20250429181707.7848912b@canb.auug.org.au/
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://patch.msgid.link/20250430022847.1118093-1-haren@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>