RDMA/bnxt_re: Initialize opcode while sending message
JIRA: https://issues.redhat.com/browse/RHEL-3526
JIRA: https://issues.redhat.com/browse/RHEL-11009

commit 147394dbe1237ef1f2da528c238633215f7193e1
Author: Leon Romanovsky <leonro@nvidia.com>
Date: Tue, 13 Jun 2023 11:15:57 +0300

    RDMA/bnxt_re: Initialize opcode while sending message

    Fix compilation warning:

    drivers/infiniband/hw/bnxt_re/qplib_rcfw.c:325:18:
      error: variable 'opcode' is uninitialized when used here [-Werror,-Wuninitialized]
            crsqe->opcode = opcode;
                            ^~~~~~
    drivers/infiniband/hw/bnxt_re/qplib_rcfw.c:291:11:
      note: initialize the variable 'opcode' to silence this warning
            u8 opcode;
                     ^
                      = '\0'

    Fixes: bcfee4ce3e01 ("RDMA/bnxt_re: remove redundant cmdq_bitmap")
    Link: https://lore.kernel.org/r/6ad1e44be2b560986da6fdc6b68da606413e9026.1686644105.git.leonro@nvidia.com
    Acked-by: Selvin Xavier <selvin.xavier@broadcom.com>
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Sreekanth Reddy <sreeredd@redhat.com>