ALSA: pcm: Protect call to dma_mmap_coherent() by check for HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit abe594c2cf55b46d4feb61c01fe9063afff2e50c

If NO_DMA=y:

    sound/core/pcm_native.o: In function `snd_pcm_lib_default_mmap':
    pcm_native.c:(.text+0x144c): undefined reference to `bad_dma_ops'
    pcm_native.c:(.text+0x1474): undefined reference to `dma_common_mmap'

Add a check for HAS_DMA to fix this.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit abe594c2cf55b46d4feb61c01fe9063afff2e50c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>