mpt2sas: fix undefined reference to `__udivdi3' compilation errors
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Sreekanth Reddy <sreekanth.reddy@avagotech.com>
commit f78f694c34ae6fdc29f5e80abb2dbb894f961772

This patch will fix the below compilation errors on i386 ARCH

drivers/built-in.o: In function `_scsih_qcmd':
mpt2sas_scsih.c:(.text+0x1e7b56): undefined reference to `__udivdi3'
mpt2sas_scsih.c:(.text+0x1e7b8a): undefined reference to `__umoddi3'

Used sector_div() API to fix above compilation errors.

	Signed-off-by: Sreekanth Reddy <Sreekanth.Reddy@avagotech.com>
	Reviewed-by: Martin K. Petersen <martin.petersen@oracle.com>
	Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit f78f694c34ae6fdc29f5e80abb2dbb894f961772)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>