s390/hypfs: remove unused info_blk_hdr__pcpus() function
Bugzilla: https://bugzilla.redhat.com/2160210

commit 12a6c2c182c1160c46500d80c2f8922cd2747f41
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Fri Nov 18 15:21:49 2022 +0100

    s390/hypfs: remove unused info_blk_hdr__pcpus() function

    Remove unused info_blk_hdr__pcpus() function:

    arch/s390/hypfs/hypfs_diag.c:71:21:
      error: unused function 'info_blk_hdr__pcpus' [-Werror,-Wunused-function]

    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>