dm vdo: use a short static string for thread name prefix
JIRA: https://issues.redhat.com/browse/RHEL-119008
Upstream Status: kernel/git/torvalds/linux.git

commit 3280c9313c9adce01550cc9f00edfb1dc7c744da
Author: Matthew Sakai <msakai@redhat.com>
Date:   Wed Jan 29 18:26:05 2025 -0500

    dm vdo: use a short static string for thread name prefix

    Also remove MODULE_NAME and a BUG_ON check, both unneeded.

    This fixes a warning about string truncation in snprintf that
    will never happen in practice:

    drivers/md/dm-vdo/vdo.c: In function ‘vdo_make’:
    drivers/md/dm-vdo/vdo.c:564:5: error: ‘%s’ directive output may be truncated writing up to 55 bytes into a region of size 16 [-Werror=format-truncation=]
        "%s%u", MODULE_NAME, instance);
         ^~
    drivers/md/dm-vdo/vdo.c:563:2: note: ‘snprintf’ output between 2 and 66 bytes into a destination of size 16
      snprintf(vdo->thread_name_prefix, sizeof(vdo->thread_name_prefix),
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        "%s%u", MODULE_NAME, instance);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Reported-by: John Garry <john.g.garry@oracle.com>
    Reviewed-by: John Garry <john.g.garry@oracle.com>
    Signed-off-by: Matthew Sakai <msakai@redhat.com>
    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>

Signed-off-by: Benjamin Marzinski <bmarzins@redhat.com>