ASoC: atmel: fix atmel_ssc_set_audio link failure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: atmel: fix atmel_ssc_set_audio link failure (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.23%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 9437bfda00f3b26eb5f475737ddaaf4dc07fee4f

The ssc audio driver can call into both pdc and dma backends.  With the
latest rework, the logic to do this in a safe way avoiding link errors
was removed, bringing back link errors that were fixed long ago in commit
061981ff8cc8 ("ASoC: atmel: properly select dma driver state") such as

sound/soc/atmel/atmel_ssc_dai.o: In function `atmel_ssc_set_audio':
atmel_ssc_dai.c:(.text+0xac): undefined reference to `atmel_pcm_pdc_platform_register'

Fix it this time using Makefile hacks and a comment to prevent this
from accidentally getting removed again rather than Kconfig hacks.

Fixes: 18291410557f ("ASoC: atmel: enable SOC_SSC_PDC and SOC_SSC_DMA in Kconfig")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>
Link: https://lore.kernel.org/r/20200130130545.31148-1-codrin.ciubotariu@microchip.com
	Reviewed-by: Michał Mirosław <mirq-linux@rere.qmqm.pl>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9437bfda00f3b26eb5f475737ddaaf4dc07fee4f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>