crypto: qat - fix linking errors when PCI_IOV is disabled
JIRA: https://issues.redhat.com/browse/RHEL-52749
Upstream Status: merged into the linux.git

commit a5d8922ab2aec39336ebc78d7cefe3b84647b058
Author: Xin Zeng <xin.zeng@intel.com>
Date:   Mon Jun 10 22:37:56 2024 +0800

    crypto: qat - fix linking errors when PCI_IOV is disabled

    When CONFIG_PCI_IOV=n, the build of the QAT vfio pci variant driver
    fails reporting the following linking errors:

        ERROR: modpost: "qat_vfmig_open" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_resume" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_save_state" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_suspend" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_load_state" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_reset" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_save_setup" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_destroy" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_close" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        ERROR: modpost: "qat_vfmig_cleanup" [drivers/vfio/pci/qat/qat_vfio_pci.ko] undefined!
        WARNING: modpost: suppressed 1 unresolved symbol warnings because there were too many)

    Make live migration helpers provided by QAT PF driver always available
    even if CONFIG_PCI_IOV is not selected. This does not cause any side
    effect.

    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Closes: https://lore.kernel.org/lkml/20240607153406.60355e6c.alex.williamson@redhat.com/T/
    Fixes: bb208810b1ab ("vfio/qat: Add vfio_pci driver for Intel QAT SR-IOV VF devices")
    Signed-off-by: Xin Zeng <xin.zeng@intel.com>
    Reviewed-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Reviewed-by: Kevin Tian <kevin.tian@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>