mlx4_core: Make buffer larger to avoid overflow warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [infiniband] mlx4: Make buffer larger to avoid overflow warning (Amir Vadai) [1107617 1107618 1107619 1107620]
Rebuild_FUZZ: 95.24%
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 4661bd798f1b58ee2755bfa04003638345802680

My static checker complains that the sprintf() here can overflow.

	drivers/infiniband/hw/mlx4/main.c:1836 mlx4_ib_alloc_eqs()
	error: format string overflow. buf_size: 32 length: 69

This seems like a valid complaint.  The "dev->pdev->bus->name" string
can be 48 characters long.  I just made the buffer 80 characters instead
of 69 and I changed the sprintf() to snprintf().

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit 4661bd798f1b58ee2755bfa04003638345802680)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>