RDMA/ucaps: Avoid format-security warning
JIRA: https://issues.redhat.com/browse/RHEL-75593

commit 62dd71e691109bb44ba8ad7f58b3a2ac6b69d496
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Mar 14 16:57:15 2025 +0100

    RDMA/ucaps: Avoid format-security warning

    Passing a non-literal format string to dev_set_name causes a warning:

    drivers/infiniband/core/ucaps.c:173:33: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
      173 |         ret = dev_set_name(&ucap->dev, ucap_names[type]);
          |                                        ^~~~~~~~~~~~~~~~
    drivers/infiniband/core/ucaps.c:173:33: note: treat the string as an argument to avoid this
      173 |         ret = dev_set_name(&ucap->dev, ucap_names[type]);
          |                                        ^
          |                                        "%s",

    Turn the name into the %s argument as suggested by gcc.

    Fixes: 61e51682816d ("RDMA/uverbs: Introduce UCAP (User CAPabilities) API")
    Link: https://patch.msgid.link/r/20250314155721.264083-1-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Zhu Yanjun <yanjun.zhu@linux.dev>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>