mlxsw: add psample dependency for spectrum
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 8d1fb01df8f64af14c833805dcbd05bf4582e028

When PSAMPLE is a loadable module, spectrum must not be built-in:

drivers/net/built-in.o: In function `mlxsw_sp_rx_listener_sample_func':
spectrum.c:(.text+0xe357e): undefined reference to `psample_sample_packet'

This adds a Kconfig dependency to enforce usable configurations.

Fixes: 98d0f7b9acda ("mlxsw: spectrum: Add packet sample offloading support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Yotam Gigi <yotamg@mellanox.com>
	Acked-by: Jiri Pirko <jiri@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8d1fb01df8f64af14c833805dcbd05bf4582e028)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>