ALSA: emux: Adjust one function call together with a variable assignment
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Markus Elfring <elfring@users.sourceforge.net>
commit c997aabbd3503c61901059caf457115098f344a4

The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code place.

	Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit c997aabbd3503c61901059caf457115098f344a4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>