ASoC: zl38060 add gpiolib dependency
Bugzilla: https://bugzilla.redhat.com/2179848

commit 0de2cc3707b6b6e2ad40bd24ce09a5c1f65d01e1
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Feb 27 09:58:26 2023 +0100

    ASoC: zl38060 add gpiolib dependency

    Without gpiolib, this driver fails to link:

    arm-linux-gnueabi-ld: sound/soc/codecs/zl38060.o: in function `chip_gpio_get':
    zl38060.c:(.text+0x30): undefined reference to `gpiochip_get_data'
    arm-linux-gnueabi-ld: sound/soc/codecs/zl38060.o: in function `zl38_spi_probe':
    zl38060.c:(.text+0xa18): undefined reference to `devm_gpiochip_add_data_with_key'

    This appears to have been in the driver since the start, but is hard to
    hit in randconfig testing since gpiolib is almost always selected by something
    else.

    Fixes: 52e8a94baf90 ("ASoC: Add initial ZL38060 driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230227085850.2503725-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>