HID: Kconfig: Fix build error from CONFIG_HID_HAPTIC
JIRA: https://issues.redhat.com/browse/RHEL-170872
Upstream Status: since v6.18

commit 083a4f3f3cc7d107728c8f297e4f6276f0876b2d
Author: Jonathan Denose <jdenose@google.com>
Date:   Mon Oct 13 20:54:57 2025 +0000

    HID: Kconfig: Fix build error from CONFIG_HID_HAPTIC

    Temporarily change CONFIG_HID_HAPTIC to be bool instead of tristate, until
    we implement a permanent solution.

    Recently the CONFIG_HID_HAPTIC Kconfig option was reported as causing
    the following build errors:

      MODPOST Module.symvers
    ERROR: modpost: "hid_haptic_init" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_pressure_increase" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_check_pressure_unit" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_input_configured" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_input_mapping" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_feature_mapping" [drivers/hid/hid-multitouch.ko] undefined!
    ERROR: modpost: "hid_haptic_pressure_reset" [drivers/hid/hid-multitouch.ko] undefined!
    make[3]: *** [/home/thl/var/linux.dev/scripts/Makefile.modpost:147: Module.symvers] Error 1

    when the kernel is compiled with the following configuration:

    CONFIG_HID=y
    CONFIG_HID_MULTITOUCH=m
    CONFIG_HID_HAPTIC=m

    To resolve this, temporarily change the CONFIG_HID_HAPTIC option to be
    bool, until we arrive at a permanent solution to enable CONFIG_HID_HAPTIC
    to be tristate.

    For a more detailed discussion, see [1].

    [1]: https://lore.kernel.org/linux-input/auypydfkhx2eg7vp764way4batdilzc35inqda3exwzs3tk3ff@oagat6g46zto/

    Signed-off-by: Jonathan Denose <jdenose@google.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>