selftests: ublk: add io_uring uapi header
JIRA: https://issues.redhat.com/browse/RHEL-106845

commit 9cad26d66b7a6306fa1e3cf64e30941afdadf6c8
Author: Ming Lei <ming.lei@redhat.com>
Date:   Sat Apr 12 10:30:18 2025 +0800

    selftests: ublk: add io_uring uapi header

    Add io_uring UAPI header so that ublk can work with latest uapi
    definition.

    Fix the following build failure:

    stripe.c: In function ‘stripe_to_uring_op’:
    stripe.c:120:29: error: ‘IORING_OP_READV_FIXED’ undeclared (first use in this function); did you mean ‘IORING_OP_READ_FIXED’?
      120 |                 return zc ? IORING_OP_READV_FIXED : IORING_OP_READV;
          |                             ^~~~~~~~~~~~~~~~~~~~~
          |                             IORING_OP_READ_FIXED

    Reviewed-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
    Fixes: 57ed58c13256 ("selftests: ublk: enable zero copy for stripe target")
    Signed-off-by: Ming Lei <ming.lei@redhat.com>
    Link: https://lore.kernel.org/r/20250412023035.2649275-3-ming.lei@redhat.com
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>