add a build check to avoid duplicated subsystem entries
This patch adds simple machinery to the Makefile so
we avoid committing duplicated subsystem entries to
owners.yaml file. In case of tripping the exception
the check will cause the build (make) process to
bail out with an error message similar to:

   $ make
   ERROR: info/owners.yaml: 2 entries found for  FUTEX SUBSYSTEM
   make: *** [Makefile:5: all] Error 1

Signed-off-by: Rafael Aquini <aquini@redhat.com>