KVM: x86: Fix clang -Wimplicit-fallthrough in do_host_cpuid()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit 07ea4ab1f9b83953ff5c3f6ccfb84d581bfe0046

Clang warns:

  arch/x86/kvm/cpuid.c:739:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
          default:
          ^
  arch/x86/kvm/cpuid.c:739:2: note: insert 'break;' to avoid fall-through
          default:
          ^
          break;
  1 error generated.

Clang is a little more pedantic than GCC, which does not warn when
falling through to a case that is just break or return. Clang's version
is more in line with the kernel's own stance in deprecated.rst, which
states that all switch/case blocks must end in either break,
fallthrough, continue, goto, or return. Add the missing break to silence
the warning.

Fixes: f144c49e8c39 ("KVM: x86: synthesize CPUID leaf 0x80000021h if useful")
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Message-Id: <20220322152906.112164-1-nathan@kernel.org>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 07ea4ab1f9b83953ff5c3f6ccfb84d581bfe0046)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>