ASoC: da7219: Fix build error without CONFIG_I2C
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: da7219: Fix build error without CONFIG_I2C (Jaroslav Kysela) [1738610]
Rebuild_FUZZ: 94.12%
commit-author YueHaibing <yuehaibing@huawei.com>
commit cbc0fa7b6e8c6180c18fd951d28197281a526330

Fix gcc build error while CONFIG_I2C is not set

sound/soc/codecs/da7219.c:2640:1: warning: data definition has no type or storage class
 module_i2c_driver(da7219_i2c_driver);
 ^~~~~~~~~~~~~~~~~
sound/soc/codecs/da7219.c:2640:1: error: type defaults to int in declaration of module_i2c_driver [-Werror=implicit-int]
sound/soc/codecs/da7219.c:2640:1: warning: parameter names (without types) in function declaration
sound/soc/codecs/da7219.c:2629:26: warning: da7219_i2c_driver defined but not used [-Wunused-variable]

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 6d817c0e9fd7 ("ASoC: codecs: Add da7219 codec driver")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit cbc0fa7b6e8c6180c18fd951d28197281a526330)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>