cpuidle: mvebu: Fix duplicate flags assignment
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181277

commit 3b8645e9ec7eb42e7df7a367d6787a3af53f37a9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 18 Jan 2023 12:03:54 +0000

The added '.flags' value is sometimes ignored here because
it gets overwritten by another initialization:

  drivers/cpuidle/cpuidle-mvebu-v7.c:24:33: error: initialized field overwritten [-Werror=override-init]
     24 | #define MVEBU_V7_FLAG_DEEP_IDLE 0x10000
        |                                 ^~~~~~~
  drivers/cpuidle/cpuidle-mvebu-v7.c:69:43: note: in expansion of macro 'MVEBU_V7_FLAG_DEEP_IDLE'
  ...

Merge the two fields into one.

Fixes: 4ce40e9dbe83 ("cpuidle, armada: Push RCU-idle into driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Acked-by: Peter Zijlstra <peterz@infradead.org>
Link: https://lore.kernel.org/r/20230117164642.1672784-1-arnd@kernel.org
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>