Revert "i2c: Make remove callback return void" for ti-tfp410.c
JIRA: https://issues.redhat.com/browse/RHEL-35606
Upstream Status: RHEL-only

This is a partial revert of DRM's
4cb818386e62 ("Merge DRM changes from upstream v6.0.8..v6.1").
This specifically is partially reverting
ed5c2f5fd10d ("i2c: Make remove callback return void") applied in
4cb818386e62.

The tree isn't setup yet for that commit, without this we see the
following compiler error if enabled:

    drivers/gpu/drm/bridge/ti-tfp410.c:455:13: error: incompatible function pointer types initializing 'int (*)(struct i2c_client *)' with an expression of type 'void (struct i2c_client *)' [-Wincompatible-function-pointer-types]
      455 |         .remove         = tfp410_i2c_remove,
          |                           ^~~~~~~~~~~~~~~~~

It seems a similar approach was taken in DRM's
00ef8586437a ("Partial revert of "i2c: Make remove callback return void"")
for enabled drivers. Let's do the same thing here for this one.

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>