timekeeping/vsyscall: Use __iter_div_u64_rem()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 0df1c9868c3a1916198ee09c323ca5932a0b8a11

On 32-bit x86 when building with clang-9, the 'division' loop gets turned
back into an inefficient division that causes a link error:

kernel/time/vsyscall.o: In function `update_vsyscall':
vsyscall.c:(.text+0xe3): undefined reference to `__udivdi3'

Use the existing __iter_div_u64_rem() function which is used to address the
same issue in other places.

Fixes: 44f57d788e7d ("timekeeping: Provide a generic update_vsyscall() implementation")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Tested-by: Nathan Chancellor <natechancellor@gmail.com>
Link: https://lkml.kernel.org/r/20190710130206.1670830-1-arnd@arndb.de
(cherry picked from commit 0df1c9868c3a1916198ee09c323ca5932a0b8a11)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>