brcmfmac: sdio: Fix undefined behavior due to shift overflowing the constant
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Borislav Petkov <bp@alien8.de>
commit 6fb3a5868b2117611f41e421e10e6a8c2a13039a

Fix:

  drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c: In function ‘brcmf_sdio_drivestrengthinit’:
  drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:3798:2: error: case label does not reduce to an integer constant
    case SDIOD_DRVSTR_KEY(BRCM_CC_43143_CHIP_ID, 17):
    ^~~~
  drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:3809:2: error: case label does not reduce to an integer constant
    case SDIOD_DRVSTR_KEY(BRCM_CC_43362_CHIP_ID, 13):
    ^~~~

See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
details as to why it triggers with older gccs only.

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Arend van Spriel <aspriel@gmail.com>
	Cc: Franky Lin <franky.lin@broadcom.com>
	Cc: Hante Meuleman <hante.meuleman@broadcom.com>
	Cc: Kalle Valo <kvalo@kernel.org>
	Cc: "David S. Miller" <davem@davemloft.net>
	Cc: Jakub Kicinski <kuba@kernel.org>
	Cc: brcm80211-dev-list.pdl@broadcom.com
	Cc: netdev@vger.kernel.org
	Acked-by: Arend van Spriel <arend.vanspriel@broadcom.com>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/Ykx0iRlvtBnKqtbG@zn.tnic
(cherry picked from commit 6fb3a5868b2117611f41e421e10e6a8c2a13039a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>