mdio_bus: unhide mdio_bus_init prototype
JIRA: https://issues.redhat.com/browse/RHEL-33716

commit 2e9f8ab68f42b059e80db71266c1675c07c664bd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:45:36 2023 +0200

    mdio_bus: unhide mdio_bus_init prototype

    mdio_bus_init() is either used as a local module_init() entry,
    or it gets called in phy_device.c. In the former case, there
    is no declaration, which causes a warning:

    drivers/net/phy/mdio_bus.c:1371:12: error: no previous prototype for 'mdio_bus_init' [-Werror=missing-prototypes]

    Remove the #ifdef around the declaration to avoid the warning..

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230516194625.549249-4-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>