usb: core: Allow compilation on platforms where NO_DMA=y
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] core: Allow compilation on platforms where NO_DMA=y (Torez Smith) [1332712]
Rebuild_FUZZ: 95.33%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 58f2266f4019b9d023979de31950d34cce23b43c

Some platforms don't have DMA, but we should still be able to build USB
drivers for these platforms. They could still be used through vhci_hcd,
usbip_host, or maybe something like USB passthrough in UML from a
capable host.

If NO_DMA=y:

    ERROR: "dma_pool_destroy" [drivers/usb/core/usbcore.ko] undefined!
    ERROR: "bad_dma_ops" [drivers/usb/core/usbcore.ko] undefined!
    ERROR: "dma_pool_free" [drivers/usb/core/usbcore.ko] undefined!
    ERROR: "dma_pool_alloc" [drivers/usb/core/usbcore.ko] undefined!
    ERROR: "dma_pool_create" [drivers/usb/core/usbcore.ko] undefined!

Add a few checks for CONFIG_HAS_DMA to fix this.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Acked-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 58f2266f4019b9d023979de31950d34cce23b43c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>