perf unwind: Fix a compile error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Hou Pengyang <houpengyang@huawei.com>
commit f005813afb89bae92faf254130c544dc68984c6b

When libunwind is on, there is a compile error as :

  util/unwind-libunwind.c:363:21: error: 'dso' undeclared (first use in this function)
      dso__data_put_fd(dso);

This patch fixes it.

	Signed-off-by: Hou Pengyang <houpengyang@huawei.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Fixes: 4bb11d012ab248d0 ("perf tools: Add dso__data_get/put_fd()")
Link: http://lkml.kernel.org/r/1434453395-10560-1-git-send-email-houpengyang@huawei.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit f005813afb89bae92faf254130c544dc68984c6b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>