HID: bpf: fix gcc warning and unify __u64 into u64
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.12
Tested: with the hid-tools test suite and some hardware

commit 762ced1630a97a457ad2fd5f5a36849009808431
Author: Benjamin Tissoires <bentiss@kernel.org>
Date:   Mon Jul 1 14:39:50 2024 +0200

    HID: bpf: fix gcc warning and unify __u64 into u64

    I've got multiple reports of:
    error: cast from pointer to integer of different size
    [-Werror=pointer-to-int-cast].

    Let's use the same trick than kernel/bpf/helpers.c to shut up that warning.

    Even if we were on an architecture with addresses on more than 64 bits,
    this isn't much of an issue as the address is not used as a pointer,
    but as an hash and the caller is not supposed to go back to the kernel
    address ever.

    And while we change those, make sure we use u64 instead of __u64 for
    consistency

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202406280633.OPB5uIFj-lkp@intel.com/
    Closes: https://lore.kernel.org/oe-kbuild-all/202406282304.UydSVncq-lkp@intel.com/
    Closes: https://lore.kernel.org/oe-kbuild-all/202406282242.Fk738zzy-lkp@intel.com/
    Reported-by: Mirsad Todorovac <mtodorovac69@gmail.com>
    Fixes: 67eccf151d76 ("HID: add source argument to HID low level functions")
    Link: https://patch.msgid.link/20240701-fix-cki-v2-2-20564e2e1393@kernel.org
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>