drm/i915: fix build error some more
JIRA: https://issues.redhat.com/browse/RHEL-75958

commit 0bb347826176401058a912f1bb64f41d5ad52626
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 20 13:18:18 2025 +0200

    drm/i915: fix build error some more

    [ Upstream commit d02b2103a08b6d6908f1d3d8e8783d3f342555ac ]

    An earlier patch fixed a build failure with clang, but I still see the
    same problem with some configurations using gcc:

    drivers/gpu/drm/i915/i915_pmu.c: In function 'config_mask':
    include/linux/compiler_types.h:568:38: error: call to '__compiletime_assert_462' declared with attribute error: BUILD_BUG_ON failed: bit > BITS_PER_TYPE(typeof_member(struct i915_pmu, enable)) - 1
    drivers/gpu/drm/i915/i915_pmu.c:116:3: note: in expansion of macro 'BUILD_BUG_ON'
      116 |   BUILD_BUG_ON(bit >

    As I understand it, the problem is that the function is not always fully
    inlined, but the __builtin_constant_p() can still evaluate the argument
    as being constant.

    Marking it as __always_inline so far works for me in all configurations.

    Fixes: a7137b1825b5 ("drm/i915/pmu: Fix build error with GCOV and AutoFDO enabled")
    Fixes: a644fde77ff7 ("drm/i915/pmu: Change bitmask of enabled events to u32")
    Reviewed-by: Rodrigo Vivi <rodrigo.vivi@intel.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250620111824.3395007-1-arnd@kernel.org
    Signed-off-by: Rodrigo Vivi <rodrigo.vivi@intel.com>
    (cherry picked from commit ef69f9dd1cd7301cdf04ba326ed28152a3affcf6)
    Signed-off-by: Joonas Lahtinen <joonas.lahtinen@linux.intel.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: José Expósito <jexposit@redhat.com>