ASoC: gtm601: fix build warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: gtm601: fix build warning (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 91.18%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 599b10193c77e4b8a68192b3b277a01e8b467043

The driver produces warnings without CONFIG_OF, and makes
no sense without it either:

sound/soc/codecs/gtm601.c:50:34: error: 'bm818_dai' defined but not used [-Werror=unused-variable]
 static struct snd_soc_dai_driver bm818_dai = {
                                  ^~~~~~~~~
sound/soc/codecs/gtm601.c:32:34: error: 'gtm601_dai' defined but not used [-Werror=unused-variable]
 static struct snd_soc_dai_driver gtm601_dai = {
                                  ^~~~~~~~~~

Remove the #ifdef check to avoid the warning.

Fixes: 057a317a8d94 ("ASoC: gtm601: add Broadmobi bm818 sound profile")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20200107214846.1284981-1-arnd@arndb.de
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 599b10193c77e4b8a68192b3b277a01e8b467043)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>