selftests: netfilter: check stateless nat udp checksum fixup
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2077385
Upstream Status: net.git commit aad51ca71ad8

commit aad51ca71ad83273e8826d6cfdcf53c98748d1fa
Author: Florian Westphal <fw@strlen.de>
Date:   Mon Jan 24 22:09:15 2022 +0100

    selftests: netfilter: check stateless nat udp checksum fixup

    Add a test that sends large udp packet (which is fragmented)
    via a stateless nft nat rule, i.e. 'ip saddr set 10.2.3.4'
    and check that the datagram is received by peer.

    On kernels without
    commit 4e1860a38637 ("netfilter: nft_payload: do not update layer 4 checksum when mangling fragments")',
    this will fail with:

    cmp: EOF on /tmp/tmp.V1q0iXJyQF which is empty
    -rw------- 1 root root 4096 Jan 24 22:03 /tmp/tmp.Aaqnq4rBKS
    -rw------- 1 root root    0 Jan 24 22:03 /tmp/tmp.V1q0iXJyQF
    ERROR: in and output file mismatch when checking udp with stateless nat
    FAIL: nftables v1.0.0 (Fearless Fosdick #2)

    On patched kernels, this will show:
    PASS: IP statless for ns2-PFp89amx

    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>