nfsd: Clean up errors in nfs4state.c
JIRA: https://issues.redhat.com/browse/RHEL-34875

commit 03a0497f83c25292e11c934ee1a2f769f14b4f3c
Author: KaiLong Wang <wangkailong@jari.cn>
Date:   Thu Sep 28 10:43:04 2023 +0800

    nfsd: Clean up errors in nfs4state.c

    Fix the following errors reported by checkpatch:

    ERROR: spaces required around that '=' (ctx:VxW)

    ERROR: space required after that ',' (ctx:VxO)
    ERROR: space required before that '~' (ctx:OxV)
    Signed-off-by: KaiLong Wang <wangkailong@jari.cn>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Benjamin Coddington <bcodding@redhat.com>