tpm: tpm_tis_spi: Mark ACPI and OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2227058

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 3fb29a23fcdadc9d7b60d323bbc1d9896249f6ac
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 18:35:41 2023 +0100

    tpm: tpm_tis_spi: Mark ACPI and OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF or !CONFIG_ACPI making
    unused:

      drivers/char/tpm/tpm_tis_spi_main.c:234:34: error: ‘of_tis_spi_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>

Signed-off-by: Štěpán Horáček <shoracek@redhat.com>