iwlwifi: mld: fix building with CONFIG_PM_SLEEP disabled
JIRA: https://issues.redhat.com/browse/RHEL-89168

commit 44605365f93518eacfc500665d965e88db4791c2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Mar 25 09:43:30 2025 +0100

    iwlwifi: mld: fix building with CONFIG_PM_SLEEP disabled
    
    The newly added driver causes multiple build problems when CONFIG_PM_SLEEP is
    disabled:
    
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c:1982:12: error: 'iwl_mld_resume' defined but not used [-Werror=unused-function]
     1982 | static int iwl_mld_resume(struct ieee80211_hw *hw)
          |            ^~~~~~~~~~~~~~
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c:1960:1: error: 'iwl_mld_suspend' defined but not used [-Werror=unused-function]
     1960 | iwl_mld_suspend(struct ieee80211_hw *hw, struct cfg80211_wowlan *wowlan)
          | ^~~~~~~~~~~~~~~
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c:1946:13: error: 'iwl_mld_set_wakeup' defined but not used [-Werror=unused-function]
     1946 | static void iwl_mld_set_wakeup(struct ieee80211_hw *hw, bool enabled)
          |             ^~~~~~~~~~~~~~~~~~
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c: In function 'iwl_mld_mac80211_start':
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c:504:20: error: 'ret' is used uninitialized [-Werror=uninitialized]
      504 |         if (!in_d3 || ret) {
          |                    ^~
    drivers/net/wireless/intel/iwlwifi/mld/mac80211.c:478:13: note: 'ret' was declared here
      478 |         int ret;
          |             ^~~
    
    Hide the unused functions and make sure the 'ret' variable is not used
    before the initialization.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250325084340.378724-1-arnd@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>