fbdev: simplefb: fix Kconfig dependencies
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071840
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  At this stage, this
 has been tested by ensuring we can survive the CI/CD loop -- i.e.,
 that we have not broken anything else, and a simple boot test.  When
 sufficient drivers have been brought in for i.MX8M, we will be able
 to run further tests.

commit ec7cc3f74b4236860ce612656aa5be7936d1c594
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 28 16:52:10 2021 +0200

    fbdev: simplefb: fix Kconfig dependencies

    Configurations with both CONFIG_FB_SIMPLE=y and CONFIG_DRM_SIMPLEDRM=m
    are allowed by Kconfig because the 'depends on !DRM_SIMPLEDRM' dependency
    does not disallow FB_SIMPLE as long as SIMPLEDRM is not built-in. This
    can however result in a build failure when cfb_fillrect() etc are then
    also in loadable modules:

    x86_64-linux-ld: drivers/video/fbdev/simplefb.o:(.rodata+0x1f8): undefined reference to `cfb_fillrect'
    x86_64-linux-ld: drivers/video/fbdev/simplefb.o:(.rodata+0x200): undefined reference to `cfb_copyarea'
    x86_64-linux-ld: drivers/video/fbdev/simplefb.o:(.rodata+0x208): undefined reference to `cfb_imageblit'

    To work around this, change FB_SIMPLE to be a 'tristate' symbol,
    which still allows both to be =m together, but not one of them to
    be =y if the other one is =m. If a distro kernel picks this
    configuration, it can be determined by local policy which of
    the two modules gets loaded. The 'of_chosen' export is needed
    as this is the first loadable module referencing it.

    Alternatively, the Kconfig dependency could be changed to
    'depends on DRM_SIMPLEDRM=n', which would forbid the configuration
    with both drivers.

    Fixes: 11e8f5fd223b ("drm: Add simpledrm driver")
    Acked-by: Rob Herring <robh@kernel.org> # for drivers/of/
    Link: https://lore.kernel.org/all/20210721151839.2484245-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Thomas Zimmermann <tzimmermann@suse.de>
    Cc: Daniel Vetter <daniel.vetter@ffwll.ch> # fbdev support
    Cc: Maxime Ripard <maxime@cerno.tech>
    Cc: Liam Girdwood <lgirdwood@gmail.com>
    Cc: Mark Brown <broonie@kernel.org>
    Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
    Cc: Borislav Petkov <bp@suse.de>
    Cc: Javier Martinez Canillas <javierm@redhat.com>
    Cc: Randy Dunlap <rdunlap@infradead.org>
    Cc: Geert Uytterhoeven <geert+renesas@glider.be>
    Cc: Peter Collingbourne <pcc@google.com>
    Cc: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Cc: dri-devel@lists.freedesktop.org
    Cc: linux-kernel@vger.kernel.org
    Cc: <stable@vger.kernel.org> # v5.14+
    Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
    Link: https://patchwork.freedesktop.org/patch/msgid/20210928145243.1098064-1-arnd@kernel.org
    Signed-off-by: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
    (cherry picked from commit ec7cc3f74b4236860ce612656aa5be7936d1c594)

Signed-off-by: Al Stone <ahs3@redhat.com>