platform/x86/amd: pmc: Fix build without debugfs
Bugzilla: https://bugzilla.redhat.com/2104173

commit 9af48b262675561eefd6edc11b4b02854e6a18ae
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Thu Sep 22 08:31:00 2022 -0700

    platform/x86/amd: pmc: Fix build without debugfs

    Without CONFIG_DEBUG_FS, the following build error occurs:

      drivers/platform/x86/amd/pmc.c:984:17: error: use of undeclared identifier 'pmc_groups'; did you mean 'set_groups'?
                      .dev_groups = pmc_groups,
                                    ^~~~~~~~~~
                                    set_groups
      ./include/linux/cred.h:65:13: note: 'set_groups' declared here
      extern void set_groups(struct cred *, struct group_info *);
                  ^
      drivers/platform/x86/amd/pmc.c:984:17: error: incompatible pointer types initializing 'const struct attribute_group **' with an expression of type 'void (struct cred *, struct group_info *)' [-Werror,-Wincompatible-pointer-types]
                      .dev_groups = pmc_groups,
                                    ^~~~~~~~~~
      2 errors generated.

    pmc_groups was only defined inside a CONFIG_DEBUG_FS block but
    commit 7f1ea75d499a ("platform/x86/amd: pmc: Add sysfs files for SMU")
    intended for these sysfs files to be available outside of debugfs.
    Shuffle the necessary functions out of the CONFIG_DEBUG_FS block so that
    the file always builds.

    Fixes: 7f1ea75d499a ("platform/x86/amd: pmc: Add sysfs files for SMU")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Mario Limonciello <mario.limonciello@amd.com>
    Link: https://lore.kernel.org/r/20220922153100.324922-1-nathan@kernel.org
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>