[s390] s390/lcs: add braces around empty function body
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2044295
Upstream Status: https://github.com/torvalds/linux.git
Tested: by IBM
Build-info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45699913
Conflicts: None

commit 09ae598271f8cfe46148cece8e03509b9da16334
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Thu Nov 18 17:06:07 2021 +0100

    s390/lcs: add braces around empty function body

    Fix allmodconfig + W=1 compile breakage:

    drivers/s390/net/lcs.c: In function ‘lcs_get_frames_cb’:
    drivers/s390/net/lcs.c:1823:25: error: suggest braces around empty body in an ‘else’ statement [-Werror=empty-body]
     1823 |                         ; // FIXME: error message ?
          |                         ^

    Acked-by: Julian Wiedmann <jwi@linux.ibm.com>
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Karsten Graul <kgraul@linux.ibm.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Mete Durlu <mdurlu@redhat.com>