iommu: ipmmu-vmsa: avoid Wformat-security warning
commit 33647d0be323f9e2f27cd1e86de5cfd965cec654
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Apr 23 18:40:02 2025 +0200

    iommu: ipmmu-vmsa: avoid Wformat-security warning

    iommu_device_sysfs_add() requires a constant format string, otherwise
    a W=1 build produces a warning:

    drivers/iommu/ipmmu-vmsa.c:1093:62: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
     1093 |         ret = iommu_device_sysfs_add(&mmu->iommu, &pdev->dev, NULL, dev_name(&pdev->dev));
	  |                                                                     ^~~~~~~~~~~~~~~~~~~~
    drivers/iommu/ipmmu-vmsa.c:1093:62: note: treat the string as an argument to avoid this
     1093 |         ret = iommu_device_sysfs_add(&mmu->iommu, &pdev->dev, NULL, dev_name(&pdev->dev));
	  |                                                                     ^
	  |                                                                     "%s",

    This was an old bug but I saw it now because the code was changed as part
    of commit d9d3cede4167 ("iommu/ipmmu-vmsa: Register in a sensible order").

    Fixes: 7af9a5fdb9e0 ("iommu/ipmmu-vmsa: Use iommu_device_sysfs_add()/remove()")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Link: https://lore.kernel.org/r/20250423164006.2661372-1-arnd@kernel.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 33647d0be323f9e2f27cd1e86de5cfd965cec654)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
JIRA: https://issues.redhat.com/browse/RHEL-89891
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git