net: mii: report 0 for unknown lp_advertising
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] mii: report 0 for unknown lp_advertising (Ivan Vecera) [1554965]
Rebuild_FUZZ: 94.12%
commit-author Arnd Bergmann <arnd@arndb.de>
commit dc0b2c9cb47a2176e1f341bfdc770745d24e072c

The newly introduced mii_ethtool_get_link_ksettings function sets
lp_advertising to an uninitialized value when BMCR_ANENABLE is not
set:

drivers/net/mii.c: In function 'mii_ethtool_get_link_ksettings':
drivers/net/mii.c:224:2: error: 'lp_advertising' may be used uninitialized in this function [-Werror=maybe-uninitialized]

As documented in include/uapi/linux/ethtool.h, the value is
expected to be zero when we don't know it, so let's initialize
it to that.

Fixes: bc8ee596afe8 ("net: mii: add generic function to support ksetting support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit dc0b2c9cb47a2176e1f341bfdc770745d24e072c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>