perf script: Fix build by removing unused evsel_script()
JIRA: https://redhat.atlassian.net/browse/RHEL-140195

upstream
========
commit 86ce2a29dd9a3564fd7be584c8bb7ced28f7ca02
Author: James Clark <james.clark@linaro.org>
Date: Fri Nov 14 14:06:18 2025 +0000

description
===========
The evsel_script() function is unused since the linked commit. Fix the
build by removing it.

Fixes the following compilation error:

  static inline struct evsel_script *evsel_script(struct evsel *evsel)
                                     ^

builtin-script.c:347:36: error: unused function 'evsel_script' [-Werror,-Wunused-function]
Fixes: 3622990efaab ("perf script: Change metric format to use json metrics")
    Signed-off-by: James Clark <james.clark@linaro.org>
    Reviewed-by: Ian Rogers <irogers@google.com>
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Trevor Allison <tallison@redhat.com>