tools/resolve_btfids: Fix setting HOSTCFLAGS
Bugzilla: https://bugzilla.redhat.com/2178930
Upstream status: https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git

commit edd75c802855271c8610f58a2fc9e54aefc49ce5
Author: Viktor Malik <vmalik@redhat.com>
Date:   Tue May 30 14:33:52 2023 +0200

    tools/resolve_btfids: Fix setting HOSTCFLAGS

    Building BPF selftests with custom HOSTCFLAGS yields an error:

        # make HOSTCFLAGS="-O2"
        [...]
          HOSTCC  ./tools/testing/selftests/bpf/tools/build/resolve_btfids/main.o
        main.c:73:10: fatal error: linux/rbtree.h: No such file or directory
           73 | #include <linux/rbtree.h>
              |          ^~~~~~~~~~~~~~~~

    The reason is that tools/bpf/resolve_btfids/Makefile passes header
    include paths by extending HOSTCFLAGS which is overridden by setting
    HOSTCFLAGS in the make command (because of Makefile rules [1]).

    This patch fixes the above problem by passing the include paths via
    `HOSTCFLAGS_resolve_btfids` which is used by tools/build/Build.include
    and can be combined with overridding HOSTCFLAGS.

    [1] https://www.gnu.org/software/make/manual/html_node/Overriding.html

    Fixes: 56a2df7615fa ("tools/resolve_btfids: Compile resolve_btfids as host program")
    Signed-off-by: Viktor Malik <vmalik@redhat.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20230530123352.1308488-1-vmalik@redhat.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>