drm/nouveau: dispnv50: fix missing-prototypes warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-511.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 504e72ed3a1b1c0d4450712a42ae6070d3a05a8e

nv50_display_create() is declared in another header, along with
a couple of declarations that are now outdated:

drivers/gpu/drm/nouveau/dispnv50/disp.c:2517:1: error: no previous prototype for 'nv50_display_create'

Fixes: ba801ef068c1 ("drm/nouveau/kms: display destroy/init/fini hooks can be static")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Karol Herbst <kherbst@redhat.com>
	Signed-off-by: Karol Herbst <kherbst@redhat.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20230417210329.2469722-1-arnd@kernel.org
(cherry picked from commit 504e72ed3a1b1c0d4450712a42ae6070d3a05a8e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>