tools build: Fix objtool build with ARCH=x86_64
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Josh Poimboeuf <jpoimboe@redhat.com>
commit 60cbdf5d051d4f4db23d267d511ca241d4be7c0d

The objtool build fails in a cross-compiled environment on a non-x86
host with "ARCH=x86_64":

  tools/objtool/objtool-in.o: In function `decode_instructions':
  tools/objtool/builtin-check.c:276: undefined reference to `arch_decode_instruction'

We could override the ARCH environment variable and change it back to
x86, similar to what the objtool Makefile was doing before; but it's
tricky to override environment variables consistently.

Instead, take a similar approach used by the Linux top-level Makefile
and introduce a SRCARCH Makefile variable which evaluates to "x86" when
ARCH is either "x86_64" or "x86".

	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
	Cc: Andy Lutomirski <luto@amacapital.net>
	Cc: H. Peter Anvin <hpa@zytor.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
Link: http://lkml.kernel.org/r/20160722191920.ej62fnspnqurbaa7@treble
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 60cbdf5d051d4f4db23d267d511ca241d4be7c0d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>