drm/fbdev-dma: Select FB_DEFERRED_IO
JIRA: https://issues.redhat.com/browse/RHEL-53571
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.12.4)

commit 22fd2377b9ceeda391f7e23a4925e9da2266688d
Author:     Thomas Zimmermann <tzimmermann@suse.de>
AuthorDate: Mon Oct 14 10:55:17 2024 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Mon Dec  9 10:41:12 2024 +0100

    commit 67c40c9b2ec5f375bf78274d4e9ef0e3b8315bea upstream.

    Commit 808a40b69468 ("drm/fbdev-dma: Implement damage handling and
    deferred I/O") added deferred I/O for fbdev-dma. Also select the
    Kconfig symbol FB_DEFERRED_IO (via FB_DMAMEM_HELPERS_DEFERRED). Fixes
    build errors about missing fbdefio, such as

    drivers/gpu/drm/drm_fbdev_dma.c:218:26: error: 'struct drm_fb_helper' has no member named 'fbdefio'
      218 |                 fb_helper->fbdefio.delay = HZ / 20;
          |                          ^~
    drivers/gpu/drm/drm_fbdev_dma.c:219:26: error: 'struct drm_fb_helper' has no member named 'fbdefio'
      219 |                 fb_helper->fbdefio.deferred_io = drm_fb_helper_deferred_io;
          |                          ^~
    drivers/gpu/drm/drm_fbdev_dma.c:221:21: error: 'struct fb_info' has no member named 'fbdefio'
      221 |                 info->fbdefio = &fb_helper->fbdefio;
          |                     ^~
    drivers/gpu/drm/drm_fbdev_dma.c:221:43: error: 'struct drm_fb_helper' has no member named 'fbdefio'
      221 |                 info->fbdefio = &fb_helper->fbdefio;
          |                                           ^~

    Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202410050241.Mox9QRjP-lkp@intel.com/
    Fixes: 808a40b69468 ("drm/fbdev-dma: Implement damage handling and deferred I/O")
    Cc: Thomas Zimmermann <tzimmermann@suse.de>
    Cc: Javier Martinez Canillas <javierm@redhat.com>
    Cc: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
    Cc: Maxime Ripard <mripard@kernel.org>
    Cc: <stable@vger.kernel.org> # v6.11+
    Reviewed-by: Jonathan Cavitt <jonathan.cavitt@intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241014085740.582287-4-tzimmermann@suse.de
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>