thermal: int340x: Limit Kconfig to 64-bit
Bugzilla: https://bugzilla.redhat.com/2039995

commit 994a04a20b03128838ec0250a0e266aab24d23f1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 8 12:13:41 2021 +0100

    thermal: int340x: Limit Kconfig to 64-bit

    32-bit processors cannot generally access 64-bit MMIO registers
    atomically, and it is unknown in which order the two halves of
    this registers would need to be read:

    drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c: In function 'send_mbox_cmd':
    drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c:79:37: error: implicit declaration of function 'readq'; did you mean 'readl'? [-Werror=implicit-function-declaration]
       79 |                         *cmd_resp = readq((void __iomem *) (proc_priv->mmio_base + MBOX_OFFSET_DATA));
          |                                     ^~~~~
          |                                     readl

    The driver already does not build for anything other than x86,
    so limit it further to x86-64.

    Fixes: aeb58c860dc5 ("thermal/drivers/int340x: processor_thermal: Suppot 64 bit RFIM responses")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Reviewed-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>