KVM: x86: add back X86_LOCAL_APIC dependency
JIRA: https://issues.redhat.com/browse/RHEL-82917

commit 1331343af6f502aecd274d522dd34bf7c965f484
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 18 09:20:01 2024 -0800

    KVM: x86: add back X86_LOCAL_APIC dependency

    Enabling KVM now causes a build failure on x86-32 if X86_LOCAL_APIC
    is disabled:

    arch/x86/kvm/svm/svm.c: In function 'svm_emergency_disable_virtualization_cpu':
    arch/x86/kvm/svm/svm.c:597:9: error: 'kvm_rebooting' undeclared (first use in this function); did you mean 'kvm_irq_routing'?
      597 |         kvm_rebooting = true;
          |         ^~~~~~~~~~~~~
          |         kvm_irq_routing
    arch/x86/kvm/svm/svm.c:597:9: note: each undeclared identifier is reported only once for each function it appears in
    make[6]: *** [scripts/Makefile.build:221: arch/x86/kvm/svm/svm.o] Error 1
    In file included from include/linux/rculist.h:11,
                     from include/linux/hashtable.h:14,
                     from arch/x86/kvm/svm/avic.c:18:
    arch/x86/kvm/svm/avic.c: In function 'avic_pi_update_irte':
    arch/x86/kvm/svm/avic.c:909:38: error: 'struct kvm' has no member named 'irq_routing'
      909 |         irq_rt = srcu_dereference(kvm->irq_routing, &kvm->irq_srcu);
          |                                      ^~
    include/linux/rcupdate.h:538:17: note: in definition of macro '__rcu_dereference_check'
      538 |         typeof(*p) *local = (typeof(*p) *__force)READ_ONCE(p); \

    Move the dependency to the same place as before.

    Fixes: ea4290d77bda ("KVM: x86: leave kvm.ko out of the build if no vendor module is requested")
    Cc: stable@vger.kernel.org
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202410060426.e9Xsnkvi-lkp@intel.com/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Sean Christopherson <seanjc@google.com>
    [sean: add Cc to stable, tweak shortlog scope]
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Message-ID: <20241118172002.1633824-2-seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>