vfio iommu: Use shift operation for 64-bit integer division
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Kirti Wankhede <kwankhede@nvidia.com>
commit cd0bb41ea86027d3a5c3555772692323cbc05bc1

Fixes compilation error with ARCH=i386.

Error fixed by this commit:
ld: drivers/vfio/vfio_iommu_type1.o: in function `vfio_dma_populate_bitmap':
>> vfio_iommu_type1.c:(.text+0x666): undefined reference to `__udivdi3'

Fixes: d6a4c185660c ("vfio iommu: Implementation of ioctl for dirty pages tracking")
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Kirti Wankhede <kwankhede@nvidia.com>
	Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
(cherry picked from commit cd0bb41ea86027d3a5c3555772692323cbc05bc1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>