netfilter: nf_tables: nft_set_rbtree: fix spurious insertion failure
JIRA: https://issues.redhat.com/browse/RHEL-1720
JIRA: https://issues.redhat.com/browse/RHEL-1721
Upstream Status: commit 087388278e0f

commit 087388278e0f301f4c61ddffb1911d3a180f84b8
Author: Florian Westphal <fw@strlen.de>
Date:   Thu Sep 28 15:12:44 2023 +0200

    netfilter: nf_tables: nft_set_rbtree: fix spurious insertion failure

    nft_rbtree_gc_elem() walks back and removes the end interval element that
    comes before the expired element.

    There is a small chance that we've cached this element as 'rbe_ge'.
    If this happens, we hold and test a pointer that has been queued for
    freeing.

    It also causes spurious insertion failures:

    $ cat test-testcases-sets-0044interval_overlap_0.1/testout.log
    Error: Could not process rule: File exists
    add element t s {  0 -  2 }
                       ^^^^^^
    Failed to insert  0 -  2 given:
    table ip t {
            set s {
                    type inet_service
                    flags interval,timeout
                    timeout 2s
                    gc-interval 2s
            }
    }

    The set (rbtree) is empty. The 'failure' doesn't happen on next attempt.

    Reason is that when we try to insert, the tree may hold an expired
    element that collides with the range we're adding.
    While we do evict/erase this element, we can trip over this check:

    if (rbe_ge && nft_rbtree_interval_end(rbe_ge) && nft_rbtree_interval_end(new))
          return -ENOTEMPTY;

    rbe_ge was erased by the synchronous gc, we should not have done this
    check.  Next attempt won't find it, so retry results in successful
    insertion.

    Restart in-kernel to avoid such spurious errors.

    Such restart are rare, unless userspace intentionally adds very large
    numbers of elements with very short timeouts while setting a huge
    gc interval.

    Even in this case, this cannot loop forever, on each retry an existing
    element has been removed.

    As the caller is holding the transaction mutex, its impossible
    for a second entity to add more expiring elements to the tree.

    After this it also becomes feasible to remove the async gc worker
    and perform all garbage collection from the commit path.

    Fixes: c9e6978e2725 ("netfilter: nft_set_rbtree: Switch to node list walk for overlap detection")
    Signed-off-by: Florian Westphal <fw@strlen.de>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>