bpf: BPF_PRELOAD depends on BPF_SYSCALL
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 7c0afcad7507636529e6a5a2a5eef5482619a449
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-315.el8/7c0afcad.failed

Fix build error when BPF_SYSCALL is not set/enabled but BPF_PRELOAD is
by making BPF_PRELOAD depend on BPF_SYSCALL.

ERROR: modpost: "bpf_preload_ops" [kernel/bpf/preload/bpf_preload.ko] undefined!

	Reported-by: kernel test robot <lkp@intel.com>
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Link: https://lore.kernel.org/bpf/20201105195109.26232-1-rdunlap@infradead.org
(cherry picked from commit 7c0afcad7507636529e6a5a2a5eef5482619a449)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	kernel/bpf/preload/Kconfig