ALSA: usb-audio: qcom: fix USB_XHCI dependency
JIRA: https://issues.redhat.com/browse/RHEL-112757

commit 882826f58b2c48cafc7084a799207e76f2c74fe0
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed May 21 15:55:43 2025 +0200

    ALSA: usb-audio: qcom: fix USB_XHCI dependency

    SND_USB_AUDIO_QMI depends on USB_XHCI_SIDEBAND, but that is a bool symbol
    and allows it to be built-in even when XHCI itself is in a loadable module.
    That configuration causes a link failure:

    arm-linux-gnueabi-ld: sound/usb/qcom/qc_audio_offload.o: in function `uaudio_event_ring_cleanup_free':
    qc_audio_offload.c:(.text+0x7dc): undefined reference to `xhci_sideband_remove_interrupter'
    arm-linux-gnueabi-ld: sound/usb/qcom/qc_audio_offload.o: in function `uaudio_endpoint_setup':
    qc_audio_offload.c:(.text+0xe88): undefined reference to `xhci_sideband_add_endpoint'

    Add the extra dependency on USB_XHCI itself.

    Fixes: 326bbc348298 ("ALSA: usb-audio: qcom: Introduce QC USB SND offloading support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250521135551.2111109-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>