PCI: Test for bit underflow in pcie_set_readrq()
JIRA: https://issues.redhat.com/browse/RHEL-151449
Upstream Status: 00e58ff924b3a684b076f9512fe2753be87b50e1

commit 00e58ff924b3a684b076f9512fe2753be87b50e1
Author: Kees Cook <kees@kernel.org>
Date:   Thu Sep 4 22:28:41 2025 -0700

    PCI: Test for bit underflow in pcie_set_readrq()

    In preparation for the future commit ("bitops: Add __attribute_const__ to generic
    ffs()-family implementations"), which allows GCC's value range tracker
    to see past ffs(), GCC 8 on ARM thinks that it might be possible that
    "ffs(rq) - 8" used here:

            v = FIELD_PREP(PCI_EXP_DEVCTL_READRQ, ffs(rq) - 8);

    could wrap below 0, leading to a very large value, which would be out of
    range for the FIELD_PREP() usage:

    drivers/pci/pci.c: In function 'pcie_set_readrq':
    include/linux/compiler_types.h:572:38: error: call to '__compiletime_assert_471' declared with attribute error: FIELD_PREP: value too large for the field
    ...
    drivers/pci/pci.c:5896:6: note: in expansion of macro 'FIELD_PREP'
      v = FIELD_PREP(PCI_EXP_DEVCTL_READRQ, ffs(rq) - 8);
          ^~~~~~~~~~

    If the result of the ffs() is bounds checked before being used in
    FIELD_PREP(), the value tracker seems happy again. :)

    Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
    Closes: https://lore.kernel.org/linux-pci/CA+G9fYuysVr6qT8bjF6f08WLyCJRG7aXAeSd2F7=zTaHHd7L+Q@mail.gmail.com/
    Acked-by: Bjorn Helgaas <bhelgaas@google.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250905052836.work.425-kees@kernel.org
    Signed-off-by: Kees Cook <kees@kernel.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>