ASoC: codecs: zl38060: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2179848

commit da1f22825b4fec7e25431fa5238252452f3dce46
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Fri Mar 10 22:43:33 2023 +0100

    ASoC: codecs: zl38060: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      sound/soc/codecs/zl38060.c:611:34: error: ‘zl38_dt_ids’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214333.274903-10-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>