tools/io_uring: fix Makefile for pthread library link
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Jens Axboe <axboe@kernel.dk>
commit 486f069253c3c738dec62daeb16f7232b2cca065

Currently fails with:

io_uring-bench.o: In function `main':
/home/axboe/git/linux-block/tools/io_uring/io_uring-bench.c:560: undefined reference to `pthread_create'
/home/axboe/git/linux-block/tools/io_uring/io_uring-bench.c:588: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'io_uring-bench' failed
make: *** [io_uring-bench] Error 1

Move -lpthread to the end.

	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit 486f069253c3c738dec62daeb16f7232b2cca065)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>