net: tso: Export symbols for modular build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [net] tso: Export symbols for modular build (Ivan Vecera) [1268334]
Rebuild_FUZZ: 93.67%
commit-author Sachin Kamat <sachin.kamat@linaro.org>
commit 484611e53047b55163822bfe60424a55a31775b3

Export the symbols to fix the below errors when built as modules:
ERROR: "tso_build_data" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
ERROR: "tso_build_hdr" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
ERROR: "tso_start" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
ERROR: "tso_count_descs" [drivers/net/ethernet/marvell/mvneta.ko] undefined!
ERROR: "tso_build_data" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
ERROR: "tso_build_hdr" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
ERROR: "tso_start" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!
ERROR: "tso_count_descs" [drivers/net/ethernet/marvell/mv643xx_eth.ko] undefined!

	Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
	Acked-by: Ezequiel Garcia <ezequiel.garcia@free-electrons.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 484611e53047b55163822bfe60424a55a31775b3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>