usb: dwc3: select CONFIG_REGMAP_MMIO
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit a51bab592fbbef10f0e42a8aed86adfbf6a68fa7

After many randconfig builds, one configuration caused a link
error with dwc3-meson-g12a lacking the regmap-mmio code:

drivers/usb/dwc3/dwc3-meson-g12a.o: In function `dwc3_meson_g12a_probe':
dwc3-meson-g12a.c:(.text+0x9f): undefined reference to `__devm_regmap_init_mmio_clk'

Add the select statement that we have for all other users
of that dependency.

Fixes: c99993376f72 ("usb: dwc3: Add Amlogic G12A DWC3 glue")
	Acked-by: Neil Armstrong <narmstrong@baylibre.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>
(cherry picked from commit a51bab592fbbef10f0e42a8aed86adfbf6a68fa7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>