KVM: selftests: Define literal to asm constraint in aarch64 as unsigned long
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2177720

commit e779fd53b4aa0aa8704ae62eb56065b9877a540b
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Dec 13 00:16:40 2022 +0000

    KVM: selftests: Define literal to asm constraint in aarch64 as unsigned long

    Define a literal '0' asm input constraint to aarch64/page_fault_test's
    guest_cas() as an unsigned long to make clang happy.

      tools/testing/selftests/kvm/aarch64/page_fault_test.c:120:16: error:
        value size does not match register size specified by the constraint
        and modifier [-Werror,-Wasm-operand-widths]
                           :: "r" (0), "r" (TEST_DATA), "r" (guest_test_memory));
                                   ^
      tools/testing/selftests/kvm/aarch64/page_fault_test.c:119:15: note:
        use constraint modifier "w"
                           "casal %0, %1, [%2]\n"
                                  ^~
                                  %w0

    Fixes: 35c581015712 ("KVM: selftests: aarch64: Add aarch64/page_fault_test")
    Cc: Ricardo Koller <ricarkol@google.com>
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
    Message-Id: <20221213001653.3852042-2-seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>