x86/insn: Use get_unaligned() instead of memcpy()
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit f96b4675839b66168f5a07bf964dde6c2f1c4885
Author: Borislav Petkov <bp@suse.de>
Date: Wed Sep 29 16:37:53 2021 +0200

description
===========
Use get_unaligned() instead of memcpy() to access potentially unaligned
memory, which, when accessed through a pointer, leads to undefined
behavior. get_unaligned() describes much better what is happening there
anyway even if memcpy() does the job.

In addition, since perf tool builds with -Werror, it would fire with:

  util/intel-pt-decoder/../../../arch/x86/lib/insn.c: In function '__insn_get_emulate_prefix':
  tools/include/../include/asm-generic/unaligned.h:10:15: error: packed attribute is unnecessary [-Werror=packed]
     10 |  const struct { type x; } __packed *__pptr = (typeof(__pptr))(ptr); \

because -Werror=packed would complain if the packed attribute would have
no effect on the layout of the structure.

In this case, that is intentional so disable the warning only for that
compilation unit.

No functional changes.

Fixes: 5ba1071f7554 ("x86/insn, tools/x86: Fix undefined behavior due to potential unaligned accesses")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>