netfilter: nf_tables: allow iter callbacks to sleep
JIRA: https://issues.redhat.com/browse/RHEL-130086
Upstream Status: commit a60a5abe19d6

commit a60a5abe19d6acd9d9ea4c1883745399fb5dc023
Author: Florian Westphal <fw@strlen.de>
Date:   Fri Aug 22 10:15:37 2025 +0200

    netfilter: nf_tables: allow iter callbacks to sleep

    Quoting Sven Auhagen:
      we do see on occasions that we get the following error message, more so on
      x86 systems than on arm64:

      Error: Could not process rule: Cannot allocate memory delete table inet filter

      It is not a consistent error and does not happen all the time.
      We are on Kernel 6.6.80, seems to me like we have something along the lines
      of the nf_tables: allow clone callbacks to sleep problem using GFP_ATOMIC.

    As hinted at by Sven, this is because of GFP_ATOMIC allocations during
    set flush.

    When set is flushed, all elements are deactivated. This triggers a set
    walk and each element gets added to the transaction list.

    The rbtree and rhashtable sets don't allow the iter callback to sleep:
    rbtree walk acquires read side of an rwlock with bh disabled, rhashtable
    walk happens with rcu read lock held.

    Rbtree is simple enough to resolve:
    When the walk context is ITER_READ, no change is needed (the iter
    callback must not deactivate elements; we're not in a transaction).

    When the iter type is ITER_UPDATE, the rwlock isn't needed because the
    caller holds the transaction mutex, this prevents any and all changes to
    the ruleset, including add/remove of set elements.

    Rhashtable is slightly more complex.
    When the iter type is ITER_READ, no change is needed, like rbtree.

    For ITER_UPDATE, we hold transaction mutex which prevents elements from
    getting free'd, even outside of rcu read lock section.

    So build a temporary list of all elements while doing the rcu iteration
    and then call the iterator in a second pass.

    The disadvantage is the need to iterate twice, but this cost comes with
    the benefit to allow the iter callback to use GFP_KERNEL allocations in
    a followup patch.

    The new list based logic makes it necessary to catch recursive calls to
    the same set earlier.

    Such walk -> iter -> walk recursion for the same set can happen during
    ruleset validation in case userspace gave us a bogus (cyclic) ruleset
    where verdict map m jumps to chain that sooner or later also calls
    "vmap @m".

    Before the new ->in_update_walk test, the ruleset is rejected because the
    infinite recursion causes ctx->level to exceed the allowed maximum.

    But with the new logic added here, elements would get skipped:

    nft_rhash_walk_update would see elements that are on the walk_list of
    an older stack frame.

    As all recursive calls into same map results in -EMLINK, we can avoid this
    problem by using the new in_update_walk flag and reject immediately.

    Next patch converts the problematic GFP_ATOMIC allocations.

    Reported-by: Sven Auhagen <Sven.Auhagen@belden.com>
    Closes: https://lore.kernel.org/netfilter-devel/BY1PR18MB5874110CAFF1ED098D0BC4E7E07BA@BY1PR18MB5874.namprd18.prod.outlook.com/
    Signed-off-by: Florian Westphal <fw@strlen.de>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>