backlight: lp855x: Mark OF related data as maybe unused
JIRA: https://issues.redhat.com/browse/RHEL-23295
Upstream Status: v6.4-rc1

commit c857b87202bf5266b45c5b4dc0308aa603aeb262
Author:     Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
AuthorDate: Sat Mar 11 18:35:55 2023 +0100
Commit:     Lee Jones <lee@kernel.org>
CommitDate: Thu Mar 16 16:11:14 2023 +0000

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/video/backlight/lp855x_bl.c:551:34: error: ‘lp855x_dt_ids’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Daniel Thompson <daniel.thompson@linaro.org>
    Signed-off-by: Lee Jones <lee@kernel.org>
    Link: https://lore.kernel.org/r/20230311173556.263086-1-krzysztof.kozlowski@linaro.org

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>