selftests/bpf: fix compilation error for flow_dissector.c
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Alan Maguire <alan.maguire@oracle.com>
commit fe937ea12ec83da6c6bbbdb54a03062155318d0e

When building the tools/testing/selftest/bpf subdirectory,
(running both a local directory "make" and a
"make -C tools/testing/selftests/bpf") I keep hitting the
following compilation error:

prog_tests/flow_dissector.c: In function ‘create_tap’:
prog_tests/flow_dissector.c:150:38: error: ‘IFF_NAPI’ undeclared (first
use in this function)
   .ifr_flags = IFF_TAP | IFF_NO_PI | IFF_NAPI | IFF_NAPI_FRAGS,
                                      ^
prog_tests/flow_dissector.c:150:38: note: each undeclared identifier is
reported only once for each function it appears in
prog_tests/flow_dissector.c:150:49: error: ‘IFF_NAPI_FRAGS’ undeclared

Adding include/uapi/linux/if_tun.h to tools/include/uapi/linux
resolves the problem and ensures the compilation of the file
does not depend on having up-to-date kernel headers locally.

	Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit fe937ea12ec83da6c6bbbdb54a03062155318d0e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>