KVM: selftests: Actually print out magic token in NX hugepages skip message
JIRA: https://issues.redhat.com/browse/RHEL-32430

commit 4a073e813477be4ae95dfd23cb08baf36e93a29f
Author: angquan yu <angquan21@gmail.com>
Date:   Tue Nov 28 16:11:05 2023 -0600

    KVM: selftests: Actually print out magic token in NX hugepages skip message

    Pass MAGIC_TOKEN to __TEST_REQUIRE() when printing the help message about
    needing to pass a magic value to manually run the NX hugepages test,
    otherwise the help message will contain garbage.

      In file included from x86_64/nx_huge_pages_test.c:15:
      x86_64/nx_huge_pages_test.c: In function ‘main’:
      include/test_util.h:40:32: error: format ‘%d’ expects a matching ‘int’ argument [-Werror=format=]
         40 |                 ksft_exit_skip("- " fmt "\n", ##__VA_ARGS__);   \
            |                                ^~~~
      x86_64/nx_huge_pages_test.c:259:9: note: in expansion of macro ‘__TEST_REQUIRE’
        259 |         __TEST_REQUIRE(token == MAGIC_TOKEN,
            |         ^~~~~~~~~~~~~~

    Signed-off-by: angquan yu <angquan21@gmail.com>
    Link: https://lore.kernel.org/r/20231128221105.63093-1-angquan21@gmail.com
    [sean: rewrite shortlog+changelog]
    Signed-off-by: Sean Christopherson <seanjc@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>