net: qlcnic: don't set unused function argument
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [netdrv] qlcnic: don't set unused function argument (Harish Patil) [1367116]
Rebuild_FUZZ: 94.38%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 287debd6aac5b9f60113d45931a53da0cd4adc94

We get a warning for qlcnic_83xx_get_mac_address when building with
"make W=1":

drivers/net/ethernet/qlogic/qlcnic/qlcnic_83xx_hw.c: In function 'qlcnic_83xx_get_mac_address':
drivers/net/ethernet/qlogic/qlcnic/qlcnic_83xx_hw.c:2156:8: error: parameter 'function' set but not used [-Werror=unused-but-set-parameter]

Clearly this is harmless, but there is also no point for setting
the variable, so we can simply remove the assignment.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Rajesh Borundia <rajesh.borundia@qlogic.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 287debd6aac5b9f60113d45931a53da0cd4adc94)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>