usb: add HAS_IOMEM dependency to USB_EHCI_HCD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_EHCI_HCD (Torez Smith) [1332712]
Rebuild_FUZZ: 94.12%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit aaa98db7181f99784c900618f9c1c8b0bcab43a0

drivers/built-in.o: In function `ehci_platform_probe':
/home/vegard/linux/drivers/usb/host/ehci-platform.c:282: undefined reference to `devm_ioremap_resource'
drivers/built-in.o: In function `oxu_drv_probe':
/home/vegard/linux/drivers/usb/host/oxu210hp-hcd.c:3821: undefined reference to `devm_ioremap_resource'
drivers/built-in.o: In function `isp1362_probe':
/home/vegard/linux/drivers/usb/host/isp1362-hcd.c:2668: undefined reference to `devm_ioremap_resource'

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit aaa98db7181f99784c900618f9c1c8b0bcab43a0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>