cleanup: Remove address space of returned pointer
JIRA: https://redhat.atlassian.net/browse/RHEL-260239

commit f730fd535fc51573f982fad629f2fc6b4a0cde2f
Author: Uros Bizjak <ubizjak@gmail.com>
Date:   Mon Aug 19 09:41:15 2024 +0200

    cleanup: Remove address space of returned pointer

    Guard functions in local_lock.h are defined using DEFINE_GUARD() and
    DEFINE_LOCK_GUARD_1() macros having lock type defined as pointer in
    the percpu address space. The functions, defined by these macros
    return value in generic address space, causing:

    cleanup.h:157:18: error: return from pointer to non-enclosed address space

    and

    cleanup.h:214:18: error: return from pointer to non-enclosed address space

    when strict percpu checks are enabled.

    Add explicit casts to remove address space of the returned pointer.

    Found by GCC's named address space checks.

    Fixes: e4ab322fbaaa ("cleanup: Add conditional guard support")
    Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lkml.kernel.org/r/20240819074124.143565-1-ubizjak@gmail.com

(cherry picked from commit f730fd535fc51573f982fad629f2fc6b4a0cde2f)
Assisted-by: Patchpal
Signed-off-by: Ivan Vecera <ivecera@redhat.com>