arm64: move early_brk64 prototype to header
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit e13d32e99264e0b63b01417e2f2db627f4507b97
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:41 +0200

    The prototype used for calling early_brk64() is in the file that calls
    it, which is the wrong place, as it is not included for the definition:

    arch/arm64/kernel/traps.c:1100:12: error: no previous prototype for 'early_brk64' [-Werror=missing-prototypes]

    Move it to an appropriate header instead.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-15-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>