selftests/bpf: Fix bind{4,6} tcp/socket header type conflict
Bugzilla: https://bugzilla.redhat.com/2166911

commit 3721359d3907c313833a2fd6e40c36a30179ea89
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Thu Aug 25 23:29:22 2022 -0600

    selftests/bpf: Fix bind{4,6} tcp/socket header type conflict
    
    There is a potential for us to hit a type conflict when including
    netinet/tcp.h with sys/socket.h, we can remove these as they are not
    actually needed.
    
    Fixes errors like the below when compiling with gcc BPF backend:
    
      In file included from /usr/include/netinet/tcp.h:91,
                       from progs/bind4_prog.c:10:
      /home/buildroot/opt/cross/lib/gcc/bpf/13.0.0/include/stdint.h:34:23: error: conflicting types for 'int8_t'; have 'char'
         34 | typedef __INT8_TYPE__ int8_t;
            |                       ^~~~~~
      In file included from /usr/include/x86_64-linux-gnu/sys/types.h:155,
                       from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                       from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                       from progs/bind4_prog.c:9:
      /usr/include/x86_64-linux-gnu/bits/stdint-intn.h:24:18: note: previous declaration of 'int8_t' with type 'int8_t' {aka 'signed char'}
         24 | typedef __int8_t int8_t;
            |                  ^~~~~~
      /home/buildroot/opt/cross/lib/gcc/bpf/13.0.0/include/stdint.h:43:24: error: conflicting types for 'int64_t'; have 'long int'
         43 | typedef __INT64_TYPE__ int64_t;
            |                        ^~~~~~~
      /usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: note: previous declaration of 'int64_t' with type 'int64_t' {aka 'long long int'}
         27 | typedef __int64_t int64_t;
            |                   ^~~~~~~
      make: *** [Makefile:537: /home/buildroot/bpf-next/tools/testing/selftests/bpf/bpf_gcc/bind4_prog.o] Error 1
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20220826052925.980431-1-james.hilliard1@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>