cifs: hide unused functions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 84908426f2097d5c6e254c73ffcb6923a355dbda

Some functions are only referenced under an #ifdef, causing a harmless
warning:

fs/cifs/smb2ops.c:1374:1: error: 'get_smb2_acl' defined but not used [-Werror=unused-function]

We could mark them __maybe_unused or add another #ifdef, I picked
the second approach here.

Fixes: b3fdda4d1e1b ("cifs: Use smb 2 - 3 and cifsacl mount options getacl functions")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Steve French <smfrench@gmail.com>
(cherry picked from commit 84908426f2097d5c6e254c73ffcb6923a355dbda)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>