selftests/bpf: Fix procmap_query()'s params mismatch and compilation warning
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 02baa0a2a677cf543899bc3eb43ed92caf4aba7a
Author: Yuan Chen <chenyuan@kylinos.cn>
Date:   Tue Sep 3 09:28:39 2024 +0800

    selftests/bpf: Fix procmap_query()'s params mismatch and compilation warning

    When the PROCMAP_QUERY is not defined, a compilation error occurs due to the
    mismatch of the procmap_query()'s params, procmap_query() only be called in
    the file where the function is defined, modify the params so they can match.

    We get a warning when build samples/bpf:
        trace_helpers.c:252:5: warning: no previous prototype for ‘procmap_query’ [-Wmissing-prototypes]
          252 | int procmap_query(int fd, const void *addr, __u32 query_flags, size_t *start, size_t *offset, int *flags)
              |     ^~~~~~~~~~~~~
    As this function is only used in the file, mark it as 'static'.

    Fixes: 4e9e07603ecd ("selftests/bpf: make use of PROCMAP_QUERY ioctl if available")
    Signed-off-by: Yuan Chen <chenyuan@kylinos.cn>
    Link: https://lore.kernel.org/r/20240903012839.3178-1-chenyuan_fl@163.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>