selftests/ptrace: add test cases for dead-locks
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Bernd Edlinger <bernd.edlinger@hotmail.de>
commit 2de4e82318c7f9d34f4b08599a612cd4cd10bf0b
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-358.el8/2de4e823.failed

This adds test cases for ptrace deadlocks.

Additionally fixes a compile problem in get_syscall_info.c,
observed with gcc-4.8.4:

get_syscall_info.c: In function 'get_syscall_info':
get_syscall_info.c:93:3: error: 'for' loop initial declarations are only
                                 allowed in C99 mode
   for (unsigned int i = 0; i < ARRAY_SIZE(args); ++i) {
   ^
get_syscall_info.c:93:3: note: use option -std=c99 or -std=gnu99 to compile
                               your code

	Signed-off-by: Bernd Edlinger <bernd.edlinger@hotmail.de>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Eric W. Biederman <ebiederm@xmission.com>
(cherry picked from commit 2de4e82318c7f9d34f4b08599a612cd4cd10bf0b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/ptrace/Makefile