clk: tegra: fix old-style declaration
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181001

commit 27115441b938b0287471ac351041dbac81095178
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon, 22 Mar 2021 22:50:41 +0100

    With extra warnings enabled, gcc complains about a slightly odd
    prototype:

    drivers/clk/tegra/clk-dfll.c:1380:1: error: 'inline' is not at beginning of declaration [-Werror=old-style-declaration]
     1380 | static void inline dfll_debug_init(struct tegra_dfll *td) { }

    Move the 'inline' keyword to the start of the line.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20210322215047.1062540-1-arnd@kernel.org
    Acked-by: Thierry Reding <treding@nvidia.com>
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>