ASoC: simple-card-utils: fix build warning without CONFIG_OF
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: simple-card-utils: fix build warning without CONFIG_OF (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 95.24%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 2b320e046495e6cf02d1f0b1abf07042ac5635ea

When CONFIG_OF is disabled, of_graph_parse_endpoint() does not
initialize 'info', and gcc can see that:

sound/soc/generic/simple-card-utils.c: In function 'asoc_simple_card_parse_graph_dai':
sound/soc/generic/simple-card-utils.c:284:13: error: 'info.port' may be used uninitialized in this function [-Werror=maybe-uninitialized]

It's probably best to check the return code anyway, and that also
takes care of the warning.

Fixes: b6f3fc005a2c ("ASoC: simple-card-utils: fixup asoc_simple_card_get_dai_id() counting")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2b320e046495e6cf02d1f0b1abf07042ac5635ea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>