ASoC: wcd9335: Fix missing regmap requirement
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: wcd9335: Fix missing regmap requirement (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 93.75%
commit-author Marc Gonzalez <marc.w.gonzalez@free.fr>
commit ac71317e6be01812cc0c54d8be6d3c1139c8380b
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-147.el8/ac71317e.failed

wcd9335.c: undefined reference to 'devm_regmap_add_irq_chip'

	Signed-off-by: Marc Gonzalez <marc.w.gonzalez@free.fr>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ac71317e6be01812cc0c54d8be6d3c1139c8380b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	sound/soc/codecs/Kconfig