phy: mscc: fix printf format
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 31bae7dad359e7fee7e2857206107b744dfb2a4e

gcc points out that the length of the temporary buffer may not be sufficient for
large numbers of leds:

drivers/net/phy/mscc.c: In function 'vsc85xx_probe':
drivers/net/phy/mscc.c:460:45: error: '-mode' directive writing 5 bytes into a region of size between 0 and 9 [-Werror=format-overflow=]
   ret = sprintf(led_dt_prop, "vsc8531,led-%d-mode", i);
                                             ^~~~~
drivers/net/phy/mscc.c:460:9: note: 'sprintf' output between 19 and 28 bytes into a destination of size 22
   ret = sprintf(led_dt_prop, "vsc8531,led-%d-mode", i);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

While we can make a reasonable assumption that the number of LEDs is small,
the cost of making the buffer a little bigger is insignificant as well.

Fixes: 11bfdabb7ff5 ("net: phy: mscc: factorize code for LEDs mode")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 31bae7dad359e7fee7e2857206107b744dfb2a4e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>