slub: Fix a documentation build error for krealloc()
JIRA: https://redhat.atlassian.net/browse/RHEL-145695

commit e8a45f198e3ae2434108f815bc28f37f6fe6742b
Author: Jonathan Corbet <corbet@lwn.net>
Date:   Wed Jun 11 16:59:08 2025 +0100

    slub: Fix a documentation build error for krealloc()

    The kerneldoc comment for krealloc() contains an unmarked literal block,
    leading to these warnings in the docs build:

      ./mm/slub.c:4936: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]
      ./mm/slub.c:4936: ERROR: Undefined substitution referenced: "--------". [docutils]

    Mark up and indent the block properly to bring a bit of peace to our build
    logs.

    Fixes: 489a744e5fb1 (mm: krealloc: clarify valid usage of __GFP_ZERO)
    Signed-off-by: Jonathan Corbet <corbet@lwn.net>
    Signed-off-by: Matthew Wilcox (Oracle) <willy@infradead.org>
    Link: https://patch.msgid.link/20250611155916.2579160-6-willy@infradead.org
    Signed-off-by: Vlastimil Babka <vbabka@suse.cz>

Signed-off-by: Rafael Aquini <raquini@redhat.com>