asm-generic: Add missing brackets for io_stop_wc macro
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070169

commit 440323b6cf5b9896013a78c4f578823e8243a7fd
Author: Xiongfeng Wang <wangxiongfeng2@huawei.com>
Date: Fri, 14 Jan 2022 18:58:57 +0800

    After using io_stop_wc(), drivers reports following compile error when
    compiled on X86.

      drivers/net/ethernet/hisilicon/hns3/hns3_enet.c: In function ‘hns3_tx_push_bd’:
      drivers/net/ethernet/hisilicon/hns3/hns3_enet.c:2058:12: error: expected ‘;’ before ‘(’ token
        io_stop_wc();
                  ^
    It is because I missed to add the brackets after io_stop_wc macro. So
    let's add the missing brackets.

    Fixes: d5624bb29f49 ("asm-generic: introduce io_stop_wc() and add implementation for ARM64")
    Reported-by: Guangbin Huang <huangguangbin2@huawei.com>
    Signed-off-by: Xiongfeng Wang <wangxiongfeng2@huawei.com>
    Link: https://lore.kernel.org/r/20220114105857.126300-1-wangxiongfeng2@huawei.com
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>