selftests/bpf: Fix a selftest compilation error with CONFIG_SMP=n
Bugzilla: https://bugzilla.redhat.com/2177177

commit ec9230b18b45853287298d70be23f8ec6bd44ff0
Author: Yonghong Song <yhs@fb.com>
Date:   Mon Dec 12 17:22:24 2022 -0800

    selftests/bpf: Fix a selftest compilation error with CONFIG_SMP=n
    
    Kernel test robot reported bpf selftest build failure when CONFIG_SMP
    is not set. The error message looks below:
    
      >> progs/rcu_read_lock.c:256:34: error: no member named 'last_wakee' in 'struct task_struct'
                 last_wakee = task->real_parent->last_wakee;
                              ~~~~~~~~~~~~~~~~~  ^
         1 error generated.
    
    When CONFIG_SMP is not set, the field 'last_wakee' is not available in struct
    'task_struct'. Hence the above compilation failure. To fix the issue, let us
    choose another field 'group_leader' which is available regardless of
    CONFIG_SMP set or not.
    
    Fixes: fe147956fca4 ("bpf/selftests: Add selftests for new task kfuncs")
    Fixes: 48671232fcb8 ("selftests/bpf: Add tests for bpf_rcu_read_lock()")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: David Vernet <void@manifault.com>
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: David Vernet <void@manifault.com>
    Link: https://lore.kernel.org/bpf/20221213012224.379581-1-yhs@fb.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>