usb/misc: fix chaoskey build, needs HW_RANDOM
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Randy Dunlap <rdunlap@infradead.org>
commit d9aab404e60d122ded979fa0b81db42fb680d867

Fix build errors when HW_RANDOM is not enabled:

drivers/built-in.o: In function `chaoskey_disconnect':
chaoskey.c:(.text+0x5f3f00): undefined reference to `hwrng_unregister'
drivers/built-in.o: In function `chaoskey_probe':
chaoskey.c:(.text+0x5f42a6): undefined reference to `hwrng_register'

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit d9aab404e60d122ded979fa0b81db42fb680d867)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>