mt76: fix LED link time failure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit d68f4e43a46ff1f772ff73085f96d44eb4163e9d

The mt76_led_cleanup() function is called unconditionally, which
leads to a link error when CONFIG_LEDS is a loadable module or
disabled but mt76 is built-in:

drivers/net/wireless/mediatek/mt76/mac80211.o: In function `mt76_unregister_device':
mac80211.c:(.text+0x2ac): undefined reference to `led_classdev_unregister'

Use the same trick that is guarding the registration, using an
IS_ENABLED() check for the CONFIG_MT76_LEDS symbol that indicates
whether LEDs can be used or not.

Fixes: 36f7e2b2bb1d ("mt76: do not use devm API for led classdev")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Felix Fietkau <nbd@nbd.name>
	Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
(cherry picked from commit d68f4e43a46ff1f772ff73085f96d44eb4163e9d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>