chelsio/chtls: Re-add dependencies on CHELSIO_T4 to fix modular CHELSIO_T4
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-338.el8
commit-author Geert Uytterhoeven <geert+renesas@glider.be>
commit e859536dac30aa891a01462eef6e12168c6e8f29
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-338.el8/e859536d.failed

As CHELSIO_INLINE_CRYPTO is bool, and CHELSIO_T4 is tristate, the
dependency of CHELSIO_INLINE_CRYPTO on CHELSIO_T4 is not sufficient to
protect CRYPTO_DEV_CHELSIO_TLS and CHELSIO_IPSEC_INLINE.  The latter two
are also tristate, hence if CHELSIO_T4=n, they cannot be builtin, as
that would lead to link failures like:

    drivers/net/ethernet/chelsio/inline_crypto/chtls/chtls_main.c:259: undefined reference to `cxgb4_port_viid'

and

    drivers/net/ethernet/chelsio/inline_crypto/ch_ipsec/chcr_ipsec.c:752: undefined reference to `cxgb4_reclaim_completed_tx'

Fix this by re-adding dependencies on CHELSIO_T4 to tristate symbols.
The dependency of CHELSIO_INLINE_CRYPTO on CHELSIO_T4 is kept to avoid
asking the user.

Fixes: 6bd860ac1c2a0ec2 ("chelsio/chtls: CHELSIO_INLINE_CRYPTO should depend on CHELSIO_T4")
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e859536dac30aa891a01462eef6e12168c6e8f29)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/chelsio/inline_crypto/Kconfig