arm64: cpuidle: fix #ifdef for acpi functions
JIRA: https://issues.redhat.com/browse/RHEL-9668

commit 68a879b55346588de936c99a04e665d9cdc326e6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 18:06:34 2023 +0200

    arm64: cpuidle: fix #ifdef for acpi functions

    The acpi_processor_ffh_lpi_* functions are defined whenever CONFIG_ACPI
    is enabled, but only called and declared when CONFIG_ACPI_PROCESSOR_IDLE
    is also enabled. Without that, a W=1 build triggers missing-prototope
    warnings, so the #ifdef needs to be adapted:

    arch/arm64/kernel/cpuidle.c:60:5: error: no previous prototype for 'acpi_processor_ffh_lpi_probe' [-Werror=missing-prototypes]
    arch/arm64/kernel/cpuidle.c:65:15: error: no previous prototype for 'acpi_processor_ffh_lpi_enter' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-8-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

(cherry picked from commit 68a879b55346588de936c99a04e665d9cdc326e6)
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>