bpftool: make key and value optional in update command
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [tools] tool: make key and value optional in update command (Yauheni Kaliuta) [1747341]
Rebuild_FUZZ: 97.14%
commit-author Stanislav Fomichev <sdf@google.com>
commit 7d7209cb9afdfc3dfcdc1b45013e62afb1ad71b6

Bpftool expects both key and value for 'update' operations. For some
map types, key should not be specified. Support updating those map types.

Before:
bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
Error: did not find key

After:
bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3

	Signed-off-by: Stanislav Fomichev <sdf@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit 7d7209cb9afdfc3dfcdc1b45013e62afb1ad71b6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>