igb: Define igb_pm_ops conditionally on CONFIG_PM
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-504.el8
commit-author Tom Rix <trix@redhat.com>
commit 7271522b729b80d9581f4b3debef0e942d3a1049

For s390, gcc with W=1 reports
drivers/net/ethernet/intel/igb/igb_main.c:186:32: error:
  'igb_pm_ops' defined but not used [-Werror=unused-const-variable=]
  186 | static const struct dev_pm_ops igb_pm_ops = {
      |                                ^~~~~~~~~~

The only use of igb_pm_ops is conditional on CONFIG_PM.
The definition of igb_pm_ops should also be conditional on CONFIG_PM

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Simon Horman <simon.horman@corigine.com>
	Tested-by: Pucha Himasekhar Reddy <himasekharx.reddy.pucha@intel.com> (A Contingent worker at Intel)
	Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
(cherry picked from commit 7271522b729b80d9581f4b3debef0e942d3a1049)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>