powerpc/47x: Remove early_init_mmu_47x() to fix no previous prototype
JIRA: https://issues.redhat.com/browse/RHEL-55462

This patch is a backport of the following upstream commit:
commit ed05c71a574235aec3418d2b5c94f24ae84cc2db
Author: Christophe Leroy <christophe.leroy@csgroup.eu>
Date:   Thu Aug 17 16:26:44 2023 +0200

    powerpc/47x: Remove early_init_mmu_47x() to fix no previous prototype

    4xx/iss476-smp_defconfig leads to:

      CC      arch/powerpc/mm/nohash/tlb.o
    arch/powerpc/mm/nohash/tlb.c:322:13: error: no previous prototype for 'early_init_mmu_47x' [-Werror=missing-prototypes]
      322 | void __init early_init_mmu_47x(void)
          |             ^~~~~~~~~~~~~~~~~~

    early_init_mmu_47x() is used only at one place and only locally.

    Fold it into its only caller and remove it.

    Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/0a667b7c2e05d3cf41ecd38f33cc334083a61c8d.1692282396.git.christophe.leroy@csgroup.eu

Signed-off-by: Audra Mitchell <audra@redhat.com>