spi: amd: add CONFIG_PCI dependency
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit 7a978d8fcf57b283cb8c88dd4c9431502bd36ea8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Apr 10 16:07:49 2025 +0200

    spi: amd: add CONFIG_PCI dependency

    Without CONFIG_PCI, the module_pci_driver() macro is not defined:

    drivers/spi/spi-amd-pci.c:67:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
       67 | module_pci_driver(amd_spi_pci_driver);

    Fixes: b644c2776652 ("spi: spi_amd: Add PCI-based driver for AMD HID2 SPI controller")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250410140809.812863-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>