usb: fix build error without CONFIG_USB_PHY
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Peter Chen <peter.chen@freescale.com>
commit 848d5b9121e52f63847bf9e156f836db001f51c7

on i386:

drivers/built-in.o: In function `ci_hdrc_probe':
core.c:(.text+0x20446b): undefined reference to `of_usb_get_phy_mode'

	Signed-off-by: Peter Chen <peter.chen@freescale.com>
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Acked-by: Randy Dunlap <rdunlap@infradead.org>
	Acked-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Acked-by: Felipe Balbi <balbi@ti.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 848d5b9121e52f63847bf9e156f836db001f51c7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>