powerpc/mem: Fix arch/powerpc/mm/mem.c:53:12: error: no previous prototype for 'create_section_mapping'
Bugzilla: https://bugzilla.redhat.com/2120352

commit 7eff9bc00ddf1e2281dff575884b7f676c85b006
Author: Christophe Leroy <christophe.leroy@csgroup.eu>
Date:   Mon Sep 13 17:17:26 2021 +0200

    powerpc/mem: Fix arch/powerpc/mm/mem.c:53:12: error: no previous prototype for 'create_section_mapping'

    Commit 8e11d62e2e87 ("powerpc/mem: Add back missing header to fix 'no
    previous prototype' error") was supposed to fix the problem, but in
    the meantime commit a927bd6ba952 ("mm: fix phys_to_target_node() and*
    memory_add_physaddr_to_nid() exports") moved create_section_mapping()
    prototype from asm/sparsemem.h to asm/mmzone.h

    Fixes: 8e11d62e2e87 ("powerpc/mem: Add back missing header to fix 'no previous prototype' error")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/025754fde3d027904ae9d0191f395890bec93369.1631541649.git.christophe.leroy@csgroup.eu

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>