tty: serial: qcom_geni: avoid duplicate struct member init
Bugzilla: https://bugzilla.redhat.com/2162957

commit 5342ab0af45064cbdc773645b93ab70c24ee161f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:54:24 2022 +0100

    tty: serial: qcom_geni: avoid duplicate struct member init

    When -Woverride-init is enabled in a build, gcc points out that
    qcom_geni_serial_pm_ops contains conflicting initializers:

    drivers/tty/serial/qcom_geni_serial.c:1586:20: error: initialized field overwritten [-Werror=override-init]
     1586 |         .restore = qcom_geni_serial_sys_hib_resume,
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/tty/serial/qcom_geni_serial.c:1586:20: note: (near initialization for 'qcom_geni_serial_pm_ops.restore')
    drivers/tty/serial/qcom_geni_serial.c:1587:17: error: initialized field overwritten [-Werror=override-init]
     1587 |         .thaw = qcom_geni_serial_sys_hib_resume,
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Open-code the initializers with the version that was already used,
    and use the pm_sleep_ptr() method to deal with unused ones,
    in place of the __maybe_unused annotation.

    Fixes: 35781d8356a2 ("tty: serial: qcom-geni-serial: Add support for Hibernation feature")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Douglas Anderson <dianders@chromium.org>
    Link: https://lore.kernel.org/r/20221215165453.1864836-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Alessandro Carminati <acarmina@redhat.com>