perf cpumap: Introduce cpu_map__snprint_mask()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Namhyung Kim <namhyung@kernel.org>
commit 4400ac8a9a900318f8516dc0fb94075cb3fdb50d

The cpu_map__snprint_mask() generates a string representation of a
cpumask bitmap.  For cpu 0 to 11, it'll return "fff".

Committer notes:

Fix compiler warning on some toolchains:

    19 fedora:24-x-ARC-uClibc: FAIL

    CC       /tmp/build/perf/util/cpumap.o
  util/cpumap.c: In function 'hex_char':
  util/cpumap.c:679:2: error: comparison is always true due to limited range of data type [-Werror=type-limits]
    if (0 <= val && val <= 9)
    ^
  cc1: all warnings being treated as errors

Applying patch from Namhyung that makes function receive an 'unsigned
char', that is what the callers are passing to this function.

	Signed-off-by: Namhyung Kim <namhyung@kernel.org>
	Cc: Frederic Weisbecker <fweisbec@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Steven Rostedt <rostedt@goodmis.org>
	Cc: kernel-team@lge.com
Link: http://lkml.kernel.org/r/20170224011251.14946-2-namhyung@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 4400ac8a9a900318f8516dc0fb94075cb3fdb50d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>