cleanup: Fix documentation build error for ACQUIRE updates
JIRA: https://issues.redhat.com/browse/RHEL-147186

commit b2df55a98672f4be076ff69d0f0d0b1fc81f2044
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Thu Jul 17 09:30:36 2025 -0700

    cleanup: Fix documentation build error for ACQUIRE updates

    Stephen reports:

    Documentation/core-api/cleanup:7: include/linux/cleanup.h:73: ERROR: Unexpected indentation. [docutils]
    Documentation/core-api/cleanup:7: include/linux/cleanup.h:74: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]

    Which points out that the ACQUIRE() example in cleanup.h missed the "::"
    suffix to mark the following text as a code-block.

    Fixes: 857d18f23ab1 ("cleanup: Introduce ACQUIRE() and ACQUIRE_ERR() for conditional locks")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Closes: http://lore.kernel.org/20250717173354.34375751@canb.auug.org.au
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Link: https://patch.msgid.link/20250717163036.1275791-1-dan.j.williams@intel.com
    Signed-off-by: Dave Jiang <dave.jiang@intel.com>

Signed-off-by: Phil Auld <pauld@redhat.com>