sfc: falcon: use padding to fix alignment in loopback test
JIRA: https://issues.redhat.com/browse/RHEL-11017

commit 1186c6b31ee14fa1e83f5a94be0daa9bc99f9b30
Author: Edward Cree <ecree.xilinx@gmail.com>
Date:   Fri Jun 23 19:38:06 2023 +0100

    sfc: falcon: use padding to fix alignment in loopback test

    Add two bytes of padding to the start of struct ef4_loopback_payload,
     which are not sent on the wire.  This ensures the 'ip' member is
     4-byte aligned, preventing the following W=1 warning:
    net/ethernet/sfc/falcon/selftest.c:43:15: error: field ip within 'struct ef4_loopback_payload' is less aligned than 'struct iphdr' and is usually due to 'struct ef4_loopback_payload' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
            struct iphdr ip;

    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Edward Cree <ecree.xilinx@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>