ALSA: hda: tas2781-spi: Fix -Wsometimes-uninitialized in tasdevice_spi_switch_book()
JIRA: https://issues.redhat.com/browse/RHEL-76110

commit 1256961d865cb6e8ab131351283036117f895283
Author: Nathan Chancellor <nathan@kernel.org>
Date: Mon Jan 20 06:32:48 2025 -0700

    ALSA: hda: tas2781-spi: Fix -Wsometimes-uninitialized in tasdevice_spi_switch_book()

    Clang warns (or errors with CONFIG_WERROR=y):

      sound/pci/hda/tas2781_hda_spi.c:110:6: error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        110 |         if (tas_priv->cur_book != TASDEVICE_BOOK_ID(reg)) {
            |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      sound/pci/hda/tas2781_hda_spi.c:119:9: note: uninitialized use occurs here
        119 |         return ret;
            |                ^~~
      sound/pci/hda/tas2781_hda_spi.c:110:2: note: remove the 'if' if its condition is always true
        110 |         if (tas_priv->cur_book != TASDEVICE_BOOK_ID(reg)) {
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      sound/pci/hda/tas2781_hda_spi.c:108:9: note: initialize the variable 'ret' to silence this warning
        108 |         int ret;
            |                ^
            |                 = 0

    Sink the declaration of ret into the if block and just return 0 at the
    end of the function, as there is nothing to do if cur_book has already
    been changed.

    Fixes: bb5f86ea50ff ("ALSA: hda/tas2781: Add tas2781 hda SPI driver")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202501192006.Hm9GmKiV-lkp@intel.com/
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://patch.msgid.link/20250120-tas2781_hda_spi-fix-wsometimes-uninitialized-v1-1-d7fd104aa63e@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>