ACPI: APEI: EINJ: mark remove callback as non-__exit
JIRA: https://issues.redhat.com/browse/RHEL-54149

commit a24118a8a6870fe06dbbd59f915b9ca3662b2ddb
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 26 Mar 2024 12:16:06 +0000

The remove callback of a device is called whenever it is unbound,
which may happen during runtime e.g. through sysfs, so this is not
allowed to be dropped from the binary:

WARNING: modpost: vmlinux: section mismatch in reference: einj_driver+0x8 (section: .data) -> einj_remove (section: .exit.text)
ERROR: modpost: Section mismatches detected.

Remove that annotation.

Fixes: 12fb28ea6b1c ("EINJ: Add CXL error type support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>