ASoC: component: suppress uninitialized-variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: component: suppress uninitialized-variable warning (Jaroslav Kysela) [1869536]
Rebuild_FUZZ: 94.92%
commit-author Arnd Bergmann <arnd@arndb.de>
commit be16a0f0dc8fab8e25d9cdbeb4f8f28afc9186d2

Old versions of gcc (tested on gcc-4.8) produce a warning for
correct code:

sound/soc/soc-compress.c: In function 'soc_compr_open':
sound/soc/soc-compress.c:75:28: error: 'component' is used uninitialized in this function [-Werror=uninitialized]
  struct snd_soc_component *component, *save = NULL;

Change the for_each_rtd_components() macro to ensure 'component'
gets initialized to a value the compiler does not complain about.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20200428214754.3925368-1-arnd@arndb.de
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit be16a0f0dc8fab8e25d9cdbeb4f8f28afc9186d2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>