usb: renesas_usbhs: mark PM functions as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit eaf3074e0a8c2a39c4c14aa8ef1c2ec09ace9c79

Without CONFIG_PM, we get a new build warning here:

drivers/usb/renesas_usbhs/common.c:860:12: error: 'usbhsc_resume' defined but not used [-Werror=unused-function]
 static int usbhsc_resume(struct device *dev)
            ^~~~~~~~~~~~~
drivers/usb/renesas_usbhs/common.c:844:12: error: 'usbhsc_suspend' defined but not used [-Werror=unused-function]
 static int usbhsc_suspend(struct device *dev)
            ^~~~~~~~~~~~~~

Fixes: d54d334e75b9 ("usb: renesas_usbhs: Use SIMPLE_DEV_PM_OPS macro")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit eaf3074e0a8c2a39c4c14aa8ef1c2ec09ace9c79)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>