dmaengine: avoid non-constant format string
JIRA: https://issues.redhat.com/browse/RHEL-63088
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit ae04342b5264fcf90a288a984a69ffb9e93904a7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 19 12:23:12 2024 +0200

    dmaengine: avoid non-constant format string

    Using an arbitrary string as a printf-style format can be a security
    problem if that string contains % characters, as the optionalal
    -Wformat-security flag points out:

    drivers/dma/dmaengine.c: In function '__dma_async_device_channel_register':
    drivers/dma/dmaengine.c:1073:17: error: format not a string literal and no format arguments [-Werror=format-security]
     1073 |                 dev_set_name(&chan->dev->device, name);
	  |                 ^~~~~~~~~~~~

    Change this newly added instance to use "%s" as the format instead to
    pass the actual name.

    Fixes: 10b8e0fd3f72 ("dmaengine: add channel device name to channel registration")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Dave Jiang <dave.jiang@intel.com>
    Link: https://lore.kernel.org/r/20240719102319.546622-1-arnd@kernel.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

(cherry picked from commit ae04342b5264fcf90a288a984a69ffb9e93904a7)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>