powerpc/powernv : Disable subcore for UP configs
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] powernv: Disable subcore for UP configs (Don Zickus) [1127366]
Rebuild_FUZZ: 89.66%
commit-author Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
commit ad417330628c60e83692211e7161eb49e1843318

Build throws following errors when CONFIG_SMP=n
arch/powerpc/platforms/powernv/subcore.c: In function ‘cpu_update_split_mode’:
arch/powerpc/platforms/powernv/subcore.c:274:15: error: ‘setup_max_cpus’ undeclared (first use in this function)
arch/powerpc/platforms/powernv/subcore.c:285:5: error: lvalue required as left operand of assignment

'setup_max_cpus' variable is relevant only on SMP, so there is no point
working around it for UP. Furthermore, subcore itself is relevant only
on SMP and hence the better solution is to exclude subcore.o and
subcore-asm.o for UP builds.

	Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
	Reviewed-by: Srivatsa S. Bhat <srivatsa.bhat@linux.vnet.ibm.com>
	Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
(cherry picked from commit ad417330628c60e83692211e7161eb49e1843318)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>