net/mlx5: Fix format-security build warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Saeed Mahameed <saeedm@nvidia.com>
commit aef0f8c67d752ed68cc18582711ac6accf0ad9b6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-373.el8/aef0f8c6.failed

Treat the string as an argument to avoid this.

drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:482:5:
error: format string is not a string literal (potentially insecure)
                         name);
                         ^~~~
drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:2079:4:
error: format string is not a string literal (potentially insecure)
                        ptp_ch_stats_desc[i].format);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
	Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
	Reviewed-by: Shay Drory <shayd@nvidia.com>
	Reviewed-by: Moshe Shemesh <moshe@nvidia.com>
(cherry picked from commit aef0f8c67d752ed68cc18582711ac6accf0ad9b6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c