usb: add HAS_IOMEM dependency to USB_ISP116X_HCD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_ISP116X_HCD (Torez Smith) [1332712]
Rebuild_FUZZ: 94.51%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit ca23d3b747f8ed294fe9e809dca0ed518fffc8cc

drivers/usb/host/isp116x-hcd.c: In function ‘isp116x_remove’:
drivers/usb/host/isp116x-hcd.c:1552:2: error: implicit declaration of function ‘iounmap’ [-Werror=implicit-function-declaration]
  iounmap(isp116x->data_reg);
  ^
drivers/usb/host/isp116x-hcd.c: In function ‘isp116x_probe’:
drivers/usb/host/isp116x-hcd.c:1604:2: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]
  addr_reg = ioremap(addr->start, resource_size(addr));
  ^
drivers/usb/host/isp116x-hcd.c:1604:11: warning: assignment makes pointer from integer without a cast [enabled by default]
  addr_reg = ioremap(addr->start, resource_size(addr));
           ^
drivers/usb/host/isp116x-hcd.c:1613:11: warning: assignment makes pointer from integer without a cast [enabled by default]
  data_reg = ioremap(data->start, resource_size(data));
           ^

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit ca23d3b747f8ed294fe9e809dca0ed518fffc8cc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>