ALSA: ymfpci: Use common error handling code in snd_card_ymfpci_probe()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Markus Elfring <elfring@users.sourceforge.net>
commit 1f5ca8ec58eaa9d42a2474ecae335ead3f845ba1

* Add a jump target so that a bit of exception handling can be better
  reused at the end of this function.

  This issue was detected by using the Coccinelle software.

* The script "checkpatch.pl" pointed information out like the following.

  ERROR: do not use assignment in if condition

  Thus fix a few source code places.

[ This also fixed a potential use-after-free at error path of
  snd_opl3_hwdep_new(), too -- tiwai ]

	Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 1f5ca8ec58eaa9d42a2474ecae335ead3f845ba1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>