virtio_net: Fix code indent error
JIRA: https://issues.redhat.com/browse/RHEL-346

commit 4f50ef152ec652cf1f1d3031019828b170406ebf
Author: Michael Catanzaro <mcatanzaro.kernel@gmail.com>
Date:   Sun Feb 13 02:01:41 2022 -0600

    virtio_net: Fix code indent error

    This patch fixes the checkpatch.pl warning:

    ERROR: code indent should use tabs where possible #3453: FILE: drivers/net/virtio_net.c:3453: ret = register_virtio_driver(&virtio_net_driver);$

    Uneccessary newline was also removed making line 3453 now 3452.

    Signed-off-by: Michael Catanzaro <mcatanzaro.kernel@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Laurent Vivier <lvivier@redhat.com>