x86/apic: Hide unused safe_smp_processor_id() on 32-bit UP
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit ac1c6283c45a77431af33fbae435f1a29f23a9f4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jul 25 15:48:33 2023 +0200

    x86/apic: Hide unused safe_smp_processor_id() on 32-bit UP

    When CONFIG_SMP is disabled in a 32-bit config, the prototype for
    safe_smp_processor_id() is hidden, which causes a W=1 warning:

      arch/x86/kernel/apic/ipi.c:316:5: error: no previous prototype for 'safe_smp_processor_id' [-Werror=missing-prototypes]

    Since there are no callers in this configuration, just hide the definition
    as well.

      [ bp: Clarify it is a 32-bit config. ]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230725134837.1534228-2-arnd@kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>