cpufreq: ACPI: Remove unused variables 'acpi_cpufreq_online' and 'ret'
jira LE-1907
Rebuild_History Non-Buildable kernel-rt-4.18.0-477.10.1.rt7.274.el8_8
commit-author Nathan Chancellor <nathan@kernel.org>
commit cab75e1c8e42ebb4bb386247a928af6ab412e82b

Clang warns:

  drivers/cpufreq/acpi-cpufreq.c:970:24: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
          acpi_cpufreq_online = ret;
                                ^~~
  drivers/cpufreq/acpi-cpufreq.c:960:9: note: initialize the variable 'ret' to silence this warning
          int ret;
                ^
                  = 0
  1 error generated.

Both ret and acpi_cpufreq_online are now unused so they can be safely
removed, clearing up the warning.

Fixes: 13fdbc8b8da6 ("cpufreq: ACPI: Defer setting boost MSRs")
Link: https://github.com/ClangBuiltLinux/linux/issues/1757
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit cab75e1c8e42ebb4bb386247a928af6ab412e82b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>