ath9k: htc: clean up statistics macros
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2084600
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/wireless/wireless-next.git, branch: main
Tested: Compile only
CVE: CVE-2022-1679

commit d7fc76039b74ad37b7056d5607b05d7cb31a5404
Author: Pavel Skripkin <paskripkin@gmail.com>
Date:   Mon Jun 13 21:44:07 2022 +0300

    ath9k: htc: clean up statistics macros

    I've changed *STAT_* macros a bit in previous patch and I seems like
    they become really unreadable. Align these macros definitions to make
    code cleaner and fix folllowing checkpatch warning

    ERROR: Macros with complex values should be enclosed in parentheses

    Also, statistics macros now accept an hif_dev as argument, since
    macros that depend on having a local variable with a magic name
    don't abide by the coding style.

    No functional change

    Suggested-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>
    Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/ebb2306d06a496cd1b032155ae52fdc5fa8cc2c5.1655145743.git.paskripkin@gmail.com

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>