[s390] s390/qeth: add __printf format attribute to qeth_dbf_longtext
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2044295
Upstream Status: https://github.com/torvalds/linux.git
Tested: by IBM
Build-info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45699913
Conflicts: None

commit 79140e22d245aa3d06e2991f397c187b3ab07df3
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Mon Oct 25 11:56:56 2021 +0200

    s390/qeth: add __printf format attribute to qeth_dbf_longtext

    Allow the compiler to recognize and check format strings and parameters.

    As reported with allmodconfig and W=1:

    drivers/s390/net/qeth_core_main.c: In function ‘qeth_dbf_longtext’:
    drivers/s390/net/qeth_core_main.c:6190:9: error: function ‘qeth_dbf_longtext’ might be a candidate for ‘gnu_printf’ format attribute [-Werror=suggest-attribute=format]
     6190 |         vsnprintf(dbf_txt_buf, sizeof(dbf_txt_buf), fmt, args);
          |         ^~~~~~~~~

    Acked-by: Julian Wiedmann <jwi@linux.ibm.com>
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Mete Durlu <mdurlu@redhat.com>