r8152: Remove unused function usb_ocp_read()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit db646cc0aefbc5da0b9699ed40d4402e01245f57

The function is not used, removing it fixes the following warning when
building with clang:

drivers/net/usb/r8152.c:825:5: error: unused function 'usb_ocp_read'
    [-Werror,-Wunused-function]

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit db646cc0aefbc5da0b9699ed40d4402e01245f57)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>