crypto: qcom-rng - Add missing dependency on hw_random
JIRA: https://issues.redhat.com/browse/RHEL-36682

commit a2786e8bdd0242d7f00abf452a572de7464d177b
Author: André Apitzsch <git@apitzsch.eu>
Date:   Mon Oct 16 19:45:53 2023 +0200

    crypto: qcom-rng - Add missing dependency on hw_random

    This should fix the undefined reference:

    > /usr/bin/aarch64-alpine-linux-musl-ld: Unexpected GOT/PLT entries detected!
    > /usr/bin/aarch64-alpine-linux-musl-ld: Unexpected run-time procedure linkages detected!
    > /usr/bin/aarch64-alpine-linux-musl-ld: drivers/crypto/qcom-rng.o: in function `qcom_rng_probe':
    > qcom-rng.c:(.text+0x130): undefined reference to `devm_hwrng_register'

    Fixes: f29cd5bb64c2 ("crypto: qcom-rng - Add hw_random interface support")
    Signed-off-by: André Apitzsch <git@apitzsch.eu>
    Reviewed-by: Neil Armstrong <neil.armstrong@linaro.org>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>