sprintf.h requires stdarg.h
JIRA: https://issues.redhat.com/browse/RHEL-94928
Upstream Status: merged into the linux.git

commit 0dec7201788b9152f06321d0dab46eed93834cda
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Jul 21 16:15:57 2025 +1000

    sprintf.h requires stdarg.h

    In file included from drivers/crypto/intel/qat/qat_common/adf_pm_dbgfs_utils.c:4:
    include/linux/sprintf.h:11:54: error: unknown type name 'va_list'
       11 | __printf(2, 0) int vsprintf(char *buf, const char *, va_list);
          |                                                      ^~~~~~~
    include/linux/sprintf.h:1:1: note: 'va_list' is defined in header '<stdarg.h>'; this is probably fixable by adding '#include <stdarg.h>'

    Link: https://lkml.kernel.org/r/20250721173754.42865913@canb.auug.org.au
    Fixes: 39ced19b9e60 ("lib/vsprintf: split out sprintf() and friends")
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Andriy Shevchenko <andriy.shevchenko@linux.intel.com>
    Cc: Herbert Xu <herbert@gondor.apana.org.au>
    Cc: Petr Mladek <pmladek@suse.com>
    Cc: Steven Rostedt <rostedt@goodmis.org>
    Cc: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Cc: Sergey Senozhatsky <senozhatsky@chromium.org>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Vladislav Dronov <vdronov@redhat.com>