wifi: rtl8xxxu: add LEDS_CLASS dependency
Bugzilla: https://bugzilla.redhat.com/2178526

commit 38ae3192296924181537544e7cfc43ca78eadcda
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 17 10:59:04 2023 +0100

    wifi: rtl8xxxu: add LEDS_CLASS dependency
    
    rtl8xxxu now unconditionally uses LEDS_CLASS, so a Kconfig dependency
    is required to avoid link errors:
    
    aarch64-linux-ld: drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_core.o: in function `rtl8xxxu_disconnect':
    rtl8xxxu_core.c:(.text+0x730): undefined reference to `led_classdev_unregister'
    
    ERROR: modpost: "led_classdev_unregister" [drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.ko] undefined!
    ERROR: modpost: "led_classdev_register_ext" [drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.ko] undefined!
    
    Fixes: 3be01622995b ("wifi: rtl8xxxu: Register the LED and make it blink")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230217095910.2480356-1-arnd@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>