ASoC: SOF: imx: imx8ulp: declare ops structure as static
Bugzilla: https://bugzilla.redhat.com/2179848

commit 1332d2078a839b371b3d541c3653a800d12a763d
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Tue Aug 23 17:40:27 2022 +0200

    ASoC: SOF: imx: imx8ulp: declare ops structure as static

    Sparse warning:

    sound/soc/sof/imx/imx8ulp.c:416:24: error: symbol 'sof_imx8ulp_ops'
    was not declared. Should it be static?

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20220823154027.762889-1-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>