cgroup: fix build when CGROUP_SCHED is not enabled
JIRA: https://issues.redhat.com/browse/RHEL-34600

commit 76be05d4fd6c91a3885298f1dc3efeef32846399
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat, 2 Sep 2023 08:27:17 -0700

    cgroup: fix build when CGROUP_SCHED is not enabled

    Sudip Mukherjee reports that the mips sb1250_swarm_defconfig build fails
    with the current kernel.  It isn't actually MIPS-specific, it's just
    that that defconfig does not have CGROUP_SCHED enabled like most configs
    do, and as such shows this error:

      kernel/cgroup/cgroup.c: In function 'cgroup_local_stat_show':
      kernel/cgroup/cgroup.c:3699:15: error: implicit declaration of function 'cgroup_tryget_css'; did you mean 'cgroup_tryget'? [-Werror=implicit-function-declaration]
       3699 |         css = cgroup_tryget_css(cgrp, ss);
            |               ^~~~~~~~~~~~~~~~~
            |               cgroup_tryget
      kernel/cgroup/cgroup.c:3699:13: warning: assignment to 'struct cgroup_subsys_state *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
       3699 |         css = cgroup_tryget_css(cgrp, ss);
            |             ^

    because cgroup_tryget_css() only exists when CGROUP_SCHED is enabled,
    and the cgroup_local_stat_show() function should similarly be guarded by
    that config option.

    Move things around a bit to fix this all.

    Fixes: d1d4ff5d11a5 ("cgroup: put cgroup_tryget_css() inside CONFIG_CGROUP_SCHED")
    Reported-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
    Cc: Miaohe Lin <linmiaohe@huawei.com>
    Cc: Tejun Heo <tj@kernel.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>