perf probe: Find compilation directory path for lazy matching
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Find compilation directory path for lazy matching (Jiri Olsa) [1222189]
Rebuild_FUZZ: 95.73%
commit-author Naohiro Aota <naota@elisp.net>
commit 09ed8975c4b13be4469899b210f0e0936021ee8f

If we use lazy matching, it failed to open a souce file if perf command
is invoked outside of compilation directory:

$ perf probe -a '__schedule;clear_*'
Failed to open kernel/sched/core.c: No such file or directory
  Error: Failed to add events. (-2)

OTOH, other commands like "probe -L" can solve the souce directory by
themselves. Let's make it possible for lazy matching too!

	Signed-off-by: Naohiro Aota <naota@elisp.net>
	Acked-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: He Kuang <hekuang@huawei.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: http://lkml.kernel.org/r/1426223923-1493-1-git-send-email-naota@elisp.net
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 09ed8975c4b13be4469899b210f0e0936021ee8f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>