rtnetlink: Add more extack messages to rtnl_newlink
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author David Ahern <dsahern@gmail.com>
commit 68d57f3b1d1a87b4022a0a7463126d7ea172bda1

Add extack arg to the nla_parse_nested calls in rtnl_newlink, and
add messages for unknown device type and link network namespace id.
In particular, it improves the failure message when the wrong link
type is used. From
    $ ip li add bond1 type bonding
    RTNETLINK answers: Operation not supported
to
    $ ip li add bond1 type bonding
    Error: Unknown device type.

(The module name is bonding but the link type is bond.)

	Signed-off-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 68d57f3b1d1a87b4022a0a7463126d7ea172bda1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>