tools: ynl-gen: refactor local vars for .attr_put() callers
JIRA: https://issues.redhat.com/browse/RHEL-123090
Upstream Status: net.git commit db4ea3baa484

commit db4ea3baa4842d01de201662da628655cd366c38
Author: Asbjørn Sloth Tønnesen <ast@fiberby.net>
Date:   Mon Sep 15 14:42:49 2025 +0000

    tools: ynl-gen: refactor local vars for .attr_put() callers

    Refactor the generation of local variables needed when building
    requests, by moving the logic from put_req_nested() into a new
    helper put_local_vars(), and use the helper before .attr_put() is
    called, thus generating the local variables assumed by .attr_put().

    Previously only put_req_nested() generated the variables assumed
    by .attr_put(),  print_req() only generated the count iterator `i`,
    and print_dump() neither generated `i` nor `array`.

    This patch fixes the build errors below:
    $ make -C tools/net/ynl/generated/
    [...]
    -e      GEN wireguard-user.c
    -e      GEN wireguard-user.h
    -e      CC wireguard-user.o
    wireguard-user.c: In function ‘wireguard_get_device_dump’:
    wireguard-user.c:480:9: error: ‘array’ undeclared (first use in func)
      480 |         array = ynl_attr_nest_start(nlh, WGDEVICE_A_PEERS);
          |         ^~~~~
    wireguard-user.c:480:9: note: each undeclared identifier is reported
                            only once for each function it appears in
    wireguard-user.c:481:14: error: ‘i’ undeclared (first use in func)
      481 |         for (i = 0; i < req->_count.peers; i++)
          |              ^
    wireguard-user.c: In function ‘wireguard_set_device’:
    wireguard-user.c:533:9: error: ‘array’ undeclared (first use in func)
      533 |         array = ynl_attr_nest_start(nlh, WGDEVICE_A_PEERS);
          |         ^~~~~
    make: *** [Makefile:52: wireguard-user.o] Error 1
    make: Leaving directory '/usr/src/linux/tools/net/ynl/generated'

    Signed-off-by: Asbjørn Sloth Tønnesen <ast@fiberby.net>
    Reviewed-by: Jakub Kicinski <kuba@kernel.org>
    Link: https://patch.msgid.link/20250915144301.725949-5-ast@fiberby.net
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>