usb: devio: fix spacing
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] devio: fix spacing (Torez Smith) [1303955]
Rebuild_FUZZ: 87.80%
commit-author Kris Borer <kborer@gmail.com>
commit f355e830a54ebe1601613d78a8d5b85eeafde358

Fix two occurrences of the checkpatch.pl error:

ERROR: space prohibited before that ',' (ctx:WxW)

Fix one occurrence of the checkpatch error:

ERROR: space required before the open parenthesis '('

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit f355e830a54ebe1601613d78a8d5b85eeafde358)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>