selftests/sgx: Specify freestanding environment for enclave compilation
JIRA: https://issues.redhat.com/browse/RHEL-22826
Upstream Status: merged into the linux.git

commit 304b259e63b94c4f825e0648b33b15f8962955c7
Author: Jo Van Bulck <jo.vanbulck@cs.kuleuven.be>
Date:   Thu Oct 5 17:38:46 2023 +0200

    selftests/sgx: Specify freestanding environment for enclave compilation

    Use -ffreestanding to assert the enclave compilation targets a
    freestanding environment (i.e., without "main" or standard libraries).
    This fixes clang reporting "undefined reference to `memset'" after
    erroneously optimizing away the provided memset/memcpy implementations.

    Still need to instruct the linker from using standard system startup
    functions, but drop -nostartfiles as it is implied by -nostdlib.

    Signed-off-by: Jo Van Bulck <jo.vanbulck@cs.kuleuven.be>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
    Acked-by: Kai Huang <kai.huang@intel.com>
    Link: https://lore.kernel.org/all/20231005153854.25566-6-jo.vanbulck%40cs.kuleuven.be

Signed-off-by: Vladis Dronov <vdronov@redhat.com>