net: report invalid mtu value via netlink extack
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [net] report invalid mtu value via netlink extack (Ivan Vecera) [1751279]
Rebuild_FUZZ: 94.51%
commit-author Stephen Hemminger <stephen@networkplumber.org>
commit 7a4c53bee3324ac00bf964aa2f82d15d279e86e4

If an invalid MTU value is set through rtnetlink return extra error
information instead of putting message in kernel log. For other cases
where there is no visible API, keep the error report in the log.

Example:
	# ip li set dev enp12s0 mtu 10000
	Error: mtu greater than device maximum.

	# ifconfig enp12s0 mtu 10000
	SIOCSIFMTU: Invalid argument
	# dmesg | tail -1
	[ 2047.795467] enp12s0: mtu greater than device maximum

	Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 7a4c53bee3324ac00bf964aa2f82d15d279e86e4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>