scsi: lpfc: Fix compilation errors on kernels with no CONFIG_DEBUG_FS
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1879528
commit 37e384095f20cca728500fe5344cd308aa6fd7ff
Author: James Smart <jsmart2021@gmail.com>
Date:   Tue Sep 7 22:09:27 2021 -0700

    scsi: lpfc: Fix compilation errors on kernels with no CONFIG_DEBUG_FS

    The Kernel test robot flagged the following warning:

      ".../lpfc_init.c:7788:35: error: 'struct lpfc_sli4_hba' has no member
       named 'c_stat'"

    Reviewing this issue highlighted that one of the recent patches caused the
    driver to no longer compile cleanly if CONFIG_DEBUG_FS is not set.

    Correct the different areas that are failing to compile.

    Link: https://lore.kernel.org/r/20210908050927.37275-1-jsmart2021@gmail.com
    Fixes: 02243836ad6f ("scsi: lpfc: Add support for the CM framework")
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Build-tested-by: Nathan Chancellor <nathan@kernel.org>
    Co-developed-by: Justin Tee <justin.tee@broadcom.com>
    Signed-off-by: Justin Tee <justin.tee@broadcom.com>
    Signed-off-by: James Smart <jsmart2021@gmail.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Dick Kennedy <dkennedy@redhat.com>