can: gs_usb: fix use of uninitialized variable, detach device on reception of invalid USB data
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071839
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support.  This set updates the CAN driver subsystem.  This set has
 been tested on NXP imx8mm and NV Jetson Xavier NX via simple boot
 tests, using cansend/candump from can-utils to pass messages through
 a virtual CAN interface, and of course the CI loop.

commit 4a8737ff068724f509d583fef404d349adba80d6
Author: Marc Kleine-Budde <mkl@pengutronix.de>
Date:   Fri Dec 10 10:03:09 2021 +0100

    can: gs_usb: fix use of uninitialized variable, detach device on reception of invalid USB data

    The received data contains the channel the received data is associated
    with. If the channel number is bigger than the actual number of
    channels assume broken or malicious USB device and shut it down.

    This fixes the error found by clang:

    | drivers/net/can/usb/gs_usb.c:386:6: error: variable 'dev' is used
    |                                     uninitialized whenever 'if' condition is true
    |         if (hf->channel >= GS_MAX_INTF)
    |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    | drivers/net/can/usb/gs_usb.c:474:10: note: uninitialized use occurs here
    |                           hf, dev->gs_hf_size, gs_usb_receive_bulk_callback,
    |                               ^~~

    Link: https://lore.kernel.org/all/20211210091158.408326-1-mkl@pengutronix.de
    Fixes: d08e973a77d1 ("can: gs_usb: Added support for the GS_USB CAN devices")
    Cc: stable@vger.kernel.org
    Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
        (cherry picked from commit 4a8737ff068724f509d583fef404d349adba80d6)

Signed-off-by: Al Stone <ahs3@redhat.com>