selftests/tcp_ao: Fix fscanf() call for format-security
JIRA: https://redhat.atlassian.net/browse/RHEL-142637
Upstream Status: net.git commit beb78cd1329d039d73487ca05633d1b92e1ab2ea

commit beb78cd1329d039d73487ca05633d1b92e1ab2ea
Author: Dmitry Safonov <0x7f454c46@gmail.com>
Date:   Sat Apr 13 02:42:54 2024 +0100

    selftests/tcp_ao: Fix fscanf() call for format-security

    On my new laptop with packages from nixos-unstable, gcc 12.3.0 produces:
    > lib/proc.c: In function ‘netstat_read_type’:
    > lib/proc.c:89:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    89 |         if (fscanf(fnetstat, type->header_name) == EOF)
    >       |         ^~
    > cc1: some warnings being treated as errors

    Here the selftests lib parses header name, while expectes non-space word
    ending with a column.

    Fixes: cfbab37b3da0 ("selftests/net: Add TCP-AO library")
    Signed-off-by: Dmitry Safonov <0x7f454c46@gmail.com>
    Reported-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>