OPP: fix error code in dev_pm_opp_set_config()
JIRA: https://issues.redhat.com/browse/RHEL-81536

commit eb8333673e1ebc2418980b664a84c91b4e98afc4
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Mon Sep 16 17:07:26 2024 +0300

This is an error path so set the error code.  Smatch complains about the
current code:

    drivers/opp/core.c:2660 dev_pm_opp_set_config()
    error: uninitialized symbol 'ret'.

Fixes: e37440e7e2c2 ("OPP: Call dev_pm_opp_set_opp() for required OPPs")
Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
Cc: stable@vger.kernel.org
Link: https://lore.kernel.org/r/3f3660af-4ea0-4a89-b3b7-58de7b16d7a5@stanley.mountain
Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>