selftests/powerpc: Fix compile error on tlbie_test due to newer gcc
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Desnes A. Nunes do Rosario <desnesn@linux.ibm.com>
commit 5b216ea1c40cf06eead15054c70e238c9bd4729e
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-193.el8/5b216ea1.failed

Newer versions of GCC (>= 9) demand that the size of the string to be
copied must be explicitly smaller than the size of the destination.
Thus, the NULL char has to be taken into account on strncpy.

This will avoid the following compiling error:

  tlbie_test.c: In function 'main':
  tlbie_test.c:639:4: error: 'strncpy' specified bound 100 equals destination size
      strncpy(logdir, optarg, LOGDIR_NAME_SIZE);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

	Signed-off-by: Desnes A. Nunes do Rosario <desnesn@linux.ibm.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20191003211010.9711-1-desnesn@linux.ibm.com
(cherry picked from commit 5b216ea1c40cf06eead15054c70e238c9bd4729e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/powerpc/mm/tlbie_test.c