ASoC: amd: ps: use static function
Bugzilla: https://bugzilla.redhat.com/2179848

commit b118458936785bd104e95f09abd52525c0a84616
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Wed Jan 4 08:57:08 2023 -0600

    ASoC: amd: ps: use static function

    Sparse warning:

    error: symbol 'acp63_fill_platform_dev_info' was not declared. Should
    it be static?

    Also reduce line lines below 100 characters.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20230104145708.25051-1-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>