mm/damon/tests/vaddr-kunit.h: reduce stack consumption
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 79dc2bff4d8d36f04d7683916eb6d4eb9ea04da4
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Mon Dec 9 18:20:01 2024 -0800

    mm/damon/tests/vaddr-kunit.h: reduce stack consumption

    After "mm: move per-vma lock into vm_area_struct" we're hitting

    mm/damon/tests/vaddr-kunit.h: In function 'damon_test_three_regions_in_vmas':
    mm/damon/tests/vaddr-kunit.h:92:1: error: the frame size of 3280 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

    Fix by moving all those vmas off the stack.

    [akpm@linux-foundation.org: fix build]
    Closes: https://lkml.kernel.org/r/20241209170829.11311e70@canb.auug.org.au
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reviewed-by: SeongJae Park <sj@kernel.org>
    Cc: Suren Baghdasaryan <surenb@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>