scsi: core: Fix kernel doc for scsi_track_queue_full()
JIRA: https://issues.redhat.com/browse/RHEL-116076
Upstream Status: From upstream linux mainline

Sphinx reports indentation warning on scsi_track_queue_full() return
values:

Documentation/driver-api/scsi:101: ./drivers/scsi/scsi.c:247: ERROR: Unexpected indentation. [docutils]

Fix the warning by making the return values listing a bullet list.

Fixes: eb44820c28bc ("[SCSI] Add Documentation and integrate into docbook build")
Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>
Link: https://lore.kernel.org/r/20250702035822.18072-2-bagasdotme@gmail.com
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 6070bd558aee1eb5114e1676165bf0ccaa08240a)
Signed-off-by: Ewan D. Milne <emilne@redhat.com>