ARM: omap1: move omap15xx local bus handling to usb.c
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 94ad8aacbc2d4908b052c8bdb5ae13bc702f77ea
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 16:40:50 2021 +0200

    ARM: omap1: move omap15xx local bus handling to usb.c

    Commit 38225f2ef2f4 ("ARM/omap1: switch to use dma_direct_set_offset for
    lbus DMA offsets") removed a lot of mach/memory.h, but left the USB
    offset handling split into arch/arm/mach-omap1/usb.c and
    drivers/usb/host/ohci-omap.c.

    This can cause a randconfig build warning that now fails the build
    with -Werror:

    arch/arm/mach-omap1/usb.c:561:30: error: 'omap_1510_usb_ohci_nb' defined but not used [-Werror=unused-variable]
      561 | static struct notifier_block omap_1510_usb_ohci_nb = {
          |                              ^~~~~~~~~~~~~~~~~~~~~

    Move it all into the platform file to get rid of the final
    location that relies on mach/memory.h.

    Acked-by: Felipe Balbi <felipe.balbi@linux.intel.com>
    Acked-by: Alan Stern <stern@rowland.harvard.edu>
    Acked-by: Tony Lindgren <tony@atomide.com>
    Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Link: https://lore.kernel.org/r/20210927144118.2464881-1-arnd@kernel.org'
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Torez Smith <torez@redhat.com>