ASoC: SOF: ipc3-topology: Fix clang -Wformat warning
When building with Clang we encounter these warnings:
| sound/soc/sof/ipc3-topology.c:2343:4: error: format specifies type
| 'unsigned char' but the argument has type 'int' [-Werror,-Wformat]
|                  SOF_ABI_MAJOR, SOF_ABI_MINOR, SOF_ABI_PATCH);
|                  ^~~~~~~~~~~~~~~^~~~~~~~~~~~~~~^~~~~~~~~~~~~

Use correct format specifier `%d` since args are of type int.

    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Suggested-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20220803204442.2996580-1-justinstitt@google.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Justin Stitt <justinstitt@google.com>
Date: Wed Aug 3 13:44:42 2022 -0700

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit b7bf23c0865faac61564425ddc96a4a79ebf19b0)
Bugzilla: https://bugzilla.redhat.com/2125537