fbdev: shmobile: fix snprintf truncation
JIRA: https://issues.redhat.com/browse/RHEL-53899
Upstream Status: v6.10-rc1

commit 26c8cfb9d1e4b252336d23dd5127a8cbed414a32
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Tue Mar 26 23:38:00 2024 +0100
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Wed Mar 27 09:12:57 2024 +0100

    The name of the overlay does not fit into the fixed-length field:

    drivers/video/fbdev/sh_mobile_lcdcfb.c:1577:2: error: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 25

    Make it short enough by changing the string.

    Fixes: c5deac3c9b22 ("fbdev: sh_mobile_lcdc: Implement overlays support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Laurent Pinchart <laurent.pinchart+renesas@ideasonboard.com>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>