mlxsw: core_thermal: Fix -Wformat-truncation warning
JIRA: https://issues.redhat.com/browse/RHEL-67125

commit b0d21321140ce9a3cbdf877a4902cce2b596f282
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Tue Jul 30 15:58:21 2024 +0200

    mlxsw: core_thermal: Fix -Wformat-truncation warning

    The name of a thermal zone device cannot be longer than 19 characters
    ('THERMAL_NAME_LENGTH - 1'). The format string 'mlxsw-lc%d-module%d' can
    exceed this limitation if the maximum number of line cards cannot be
    represented using a single digit and the maximum number of transceiver
    modules cannot be represented using two digits.

    This is not the case with current systems nor future ones. Therefore,
    increase the size of the result buffer beyond 'THERMAL_NAME_LENGTH' and
    suppress the following build warning [1].

    If this limitation is ever exceeded, we will know about it since the
    thermal core validates the thermal device's name during registration.

    [1]
    drivers/net/ethernet/mellanox/mlxsw/core_thermal.c: In function ‘mlxsw_thermal_modules_init.part.0’:
    drivers/net/ethernet/mellanox/mlxsw/core_thermal.c:418:70: error: ‘%d’ directive output may be truncated writing between 1 and 3 bytes into a region of size between 2 and 4 [-Werror=format-truncation=]
      418 |                 snprintf(tz_name, sizeof(tz_name), "mlxsw-lc%d-module%d",
          |                                                                      ^~
    In function ‘mlxsw_thermal_module_tz_init’,
        inlined from ‘mlxsw_thermal_module_init’ at drivers/net/ethernet/mellanox/mlxsw/core_thermal.c:465:9,
        inlined from ‘mlxsw_thermal_modules_init.part.0’ at drivers/net/ethernet/mellanox/mlxsw/core_thermal.c:500:9:
    drivers/net/ethernet/mellanox/mlxsw/core_thermal.c:418:52: note: directive argument in the range [1, 256]
      418 |                 snprintf(tz_name, sizeof(tz_name), "mlxsw-lc%d-module%d",
          |                                                    ^~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/mellanox/mlxsw/core_thermal.c:418:17: note: ‘snprintf’ output between 18 and 22 bytes into a destination of size 20
      418 |                 snprintf(tz_name, sizeof(tz_name), "mlxsw-lc%d-module%d",
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      419 |                          module_tz->slot_index, module_tz->module + 1);
          |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Vadim Pasternak <vadimp@nvidia.com>
    Signed-off-by: Petr Machata <petrm@nvidia.com>
    Reviewed-by: Wojciech Drewek <wojciech.drewek@intel.com>
    Link: https://patch.msgid.link/583a70c6dbe75e6bf0c2c58abbb3470a860d2dc3.1722345311.git.petrm@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>