x86/its: Fix build errors when CONFIG_MODULES=n
JIRA: https://issues.redhat.com/browse/RHEL-91960
Conflicts: A context diff in the its_init_thunk() hunk due to missing
	   upstream commit e52c1dc7455d ("x86/its: FineIBT-paranoid
	   vs ITS").

commit 9f35e33144ae5377d6a8de86dd3bd4d995c6ac65
Author: Eric Biggers <ebiggers@google.com>
Date:   Mon, 12 May 2025 19:58:39 -0700

    x86/its: Fix build errors when CONFIG_MODULES=n

    Fix several build errors when CONFIG_MODULES=n, including the following:

    ../arch/x86/kernel/alternative.c:195:25: error: incomplete definition of type 'struct module'
      195 |         for (int i = 0; i < mod->its_num_pages; i++) {

    Fixes: 872df34d7c51 ("x86/its: Use dynamic thunks for indirect branches")
    Cc: stable@vger.kernel.org
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Acked-by: Dave Hansen <dave.hansen@intel.com>
    Tested-by: Steven Rostedt (Google) <rostedt@goodmis.org>
    Reviewed-by: Alexandre Chartre <alexandre.chartre@oracle.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>