phy: tegra: xusb: mark PM functions as __maybe_unused
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071844
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2121508
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set cleans up
 PHY handling for imx8m (and Tegra) in drivers/phy.  This set has been
 tested via simple boot tests, and of course the CI loop.  If the PHYs
 are not working, their devices aren't; everything appears to be
 working just fine.

commit c1302e8ce517ed9c417aa4eb19776df4efbbebf4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jul 21 17:25:42 2021 +0200

    phy: tegra: xusb: mark PM functions as __maybe_unused

    When these are not referenced, gcc prints a harmless warning:

    drivers/phy/tegra/xusb.c:1286:12: error: 'tegra_xusb_padctl_resume_noirq' defined but not used [-Werror=unused-function]
     1286 | static int tegra_xusb_padctl_resume_noirq(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/phy/tegra/xusb.c:1276:12: error: 'tegra_xusb_padctl_suspend_noirq' defined but not used [-Werror=unused-function]
     1276 | static int tegra_xusb_padctl_suspend_noirq(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: c545a9056712 ("phy: tegra: xusb: Add sleepwalk and suspend/resume")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20210721152550.2976003-1-arnd@kernel.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>
    (cherry picked from commit c1302e8ce517ed9c417aa4eb19776df4efbbebf4)

Signed-off-by: Al Stone <ahs3@redhat.com>