mt76: mt7915: fix unbounded shift in mt7915_mcu_beacon_mbss
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Lorenzo Bianconi <lorenzo@kernel.org>
commit aa796f12091aa4758366f5171fd9cba2ff574ba3

Fix the following smatch static checker warning:
	drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:1872 mt7915_mcu_beacon_mbss()
	error: undefined (user controlled) shift '(((1))) << (data[2])'

Rely on mac80211 definitions for ieee80211_bssid_index subelement.

Fixes: 6b7f9aff7c67 ("mt76: mt7915: introduce 802.11ax multi-bss support")
	Signed-off-by: Lorenzo Bianconi <lorenzo@kernel.org>
	Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit aa796f12091aa4758366f5171fd9cba2ff574ba3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>