drm/fourcc: fix integer type usage in uapi header
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2088409
Upstream Status: v5.18.10

commit 45611d5ad8a8044f6a1d2c19fc767c1eaecf724a
Author:     Carlos Llamas <cmllamas@google.com>
AuthorDate: Tue Jun 21 20:39:21 2022 +0000
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Thu Jul  7 17:55:00 2022 +0200

    [ Upstream commit 20b8264394b33adb1640a485a62a84bc1388b6a3 ]

    Kernel uapi headers are supposed to use __[us]{8,16,32,64} types defined
    by <linux/types.h> as opposed to 'uint32_t' and similar. See [1] for the
    relevant discussion about this topic. In this particular case, the usage
    of 'uint64_t' escaped headers_check as these macros are not being called
    here. However, the following program triggers a compilation error:

      #include <drm/drm_fourcc.h>

      int main()
      {
      	unsigned long x = AMD_FMT_MOD_CLEAR(RB);
      	return 0;
      }

    gcc error:
      drm.c:5:27: error: ‘uint64_t’ undeclared (first use in this function)
          5 |         unsigned long x = AMD_FMT_MOD_CLEAR(RB);
            |                           ^~~~~~~~~~~~~~~~~

    This patch changes AMD_FMT_MOD_{SET,CLEAR} macros to use the correct
    integer types, which fixes the above issue.

      [1] https://lkml.org/lkml/2019/6/5/18

    Fixes: 8ba16d599374 ("drm/fourcc: Add AMD DRM modifiers.")
    Signed-off-by: Carlos Llamas <cmllamas@google.com>
    Reviewed-by: Simon Ser <contact@emersion.fr>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>