drivers/base: build kunit tests without structleak plugin
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 38009c766725a9877ea8866fc813a5460011817f

The structleak plugin causes the stack frame size to grow immensely:

drivers/base/test/property-entry-test.c: In function 'pe_test_reference':
drivers/base/test/property-entry-test.c:481:1: error: the frame size of 2640 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
  481 | }
      | ^
drivers/base/test/property-entry-test.c: In function 'pe_test_uints':
drivers/base/test/property-entry-test.c:99:1: error: the frame size of 2592 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20210125124533.101339-3-arnd@kernel.org
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 38009c766725a9877ea8866fc813a5460011817f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>