include/uapi/linux/if_tunnel.h: include linux/if.h, linux/ip.h and linux/in6.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [netdrv] uapi/linux/if_tunnel.h: include linux/if.h, linux/ip.h and linux/in6.h (Ivan Vecera) [1486860]
Rebuild_FUZZ: 94.59%
commit-author Mikko Rapeli <mikko.rapeli@iki.fi>
commit 1fe8e0f074c77aa41aaa579345a9e675acbebfa9

Fixes userspace compilation errors like:

error: field ‘iph’ has incomplete type
error: field ‘prefix’ has incomplete type

	Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 1fe8e0f074c77aa41aaa579345a9e675acbebfa9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>