optee: smc_abi.c: add missing #include <linux/mm.h>
Bugzilla: https://bugzilla.redhat.com/2166659

commit 34f3c67b817852625ba839ed4bc28381773d0f58
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Thu Oct 21 14:55:39 2021 +0200

    optee: smc_abi.c: add missing #include <linux/mm.h>

    Adds missing #include <linux/mm.h> drivers/tee/optee/smc_abi.c to fix
    compile errors like:
    drivers/tee/optee/smc_abi.c:405:15: error: implicit
    declaration of function 'page_to_section'
    [-Werror,-Wimplicit-function-declaration]
            optee_page = page_to_phys(*pages) +
                         ^
    arch/arm/include/asm/memory.h:148:43: note: expanded from
    macro 'page_to_phys'
                                                   ^
    include/asm-generic/memory_model.h:52:21: note: expanded
    from macro 'page_to_pfn'
                        ^
    include/asm-generic/memory_model.h:35:14: note: expanded
    from macro '__page_to_pfn'
            int __sec = page_to_section(__pg);                      \
                        ^
    drivers/tee/optee/smc_abi.c:405:15: note: did you mean
    '__nr_to_section'?
    arch/arm/include/asm/memory.h:148:43: note: expanded from
    macro 'page_to_phys'
                                                   ^
    include/asm-generic/memory_model.h:52:21: note: expanded
    from macro 'page_to_pfn'
                        ^
    include/asm-generic/memory_model.h:35:14: note: expanded
    from macro '__page_to_pfn'
            int __sec = page_to_section(__pg);                      \
                        ^
    include/linux/mmzone.h:1365:35: note: '__nr_to_section'
    declared here
    static inline struct mem_section *__nr_to_section(unsigned long nr)

    Fixes: c51a564a5b48 ("optee: isolate smc abi")
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
    Link: https://lore.kernel.org/r/20211021125539.3858495-1-jens.wiklander@linaro.org'
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>