net: sfc: avoid -Wtype-limits warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [netdrv] sfc: avoid -Wtype-limits warning (Jarod Wilson) [1368201]
Rebuild_FUZZ: 92.75%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 17471c7ba5115ed724d624577b21c166d2194272

When building with -Wextra, we get a harmless warning from the
EFX_EXTRACT_OWORD32 macro:

ethernet/sfc/farch.c: In function 'efx_farch_test_registers':
ethernet/sfc/farch.c:119:30: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
ethernet/sfc/farch.c:124:144: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
ethernet/sfc/farch.c:124:392: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
ethernet/sfc/farch.c:124:731: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]

The macro and the caller are both correct, but we can avoid the
warning by changing the index variable to a signed type.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Bert Kenward <bkenward@solarflare.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 17471c7ba5115ed724d624577b21c166d2194272)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>