net: qlcnic: include irq.h for irq definitions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [ethernet] qlcnic: include irq.h for irq definitions (Chad Dupuis) [1089352]
Rebuild_FUZZ: 94.25%
commit-author Josh Boyer <jwboyer@fedoraproject.org>
commit acdd32be6d3ec5f872d9fd930cac54d18d6c74ac

The qlcnic driver fails to build on ARM with errors like:

In file included from drivers/net/ethernet/qlogic/qlcnic/qlcnic.h:36:0,
                 from drivers/net/ethernet/qlogic/qlcnic/qlcnic_hw.c:8:
drivers/net/ethernet/qlogic/qlcnic/qlcnic_83xx_hw.h:585:1: error: unknown type name 'irqreturn_t'
 irqreturn_t qlcnic_83xx_clear_legacy_intr(struct qlcnic_adapter *);
 ^

Nothing in the driver is explicitly including the irq definitions, so we
add an include of linux/irq.h to pick them up.

	Signed-off-by: Josh Boyer <jwboyer@fedoraproject.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit acdd32be6d3ec5f872d9fd930cac54d18d6c74ac)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>