s390/mm/hugetlbfs: Add missing includes
JIRA: https://issues.redhat.com/browse/RHEL-78135

commit adb44a4bfc8a3312d2a13cc09d2b89d5828e7702
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Thu Nov 28 09:43:29 2024 +0100

    s390/mm/hugetlbfs: Add missing includes

    Add missing includes to fix this randconfig compile error:

    All errors (new ones prefixed by >>):

       In file included from mm/pagewalk.c:5:
       In file included from include/linux/hugetlb.h:798:
    >> arch/s390/include/asm/hugetlb.h:94:31: error: call to undeclared function 'is_pte_marker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          94 |         return huge_pte_none(pte) || is_pte_marker(pte);
             |                                      ^

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202411281002.IPkRpIcR-lkp@intel.com/
    Fixes: 487ef5d4d912 ("s390/mm: Add PTE_MARKER support for hugetlbfs mappings")
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Luiz Capitulino <luizcap@redhat.com>