scsi: lpfc: Avoid unused function warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 336df6eb628298e27e40e23d1eb00a0fb7083269

When building powerpc pseries_defconfig or powernv_defconfig:

drivers/scsi/lpfc/lpfc_nvmet.c:224:1: error: unused function
'lpfc_nvmet_get_ctx_for_xri' [-Werror,-Wunused-function]
drivers/scsi/lpfc/lpfc_nvmet.c:246:1: error: unused function
'lpfc_nvmet_get_ctx_for_oxid' [-Werror,-Wunused-function]

These functions are only compiled when CONFIG_NVME_TARGET_FC is enabled.
Use that same condition so there is no more warning. While the fixes commit
did not introduce these functions, it caused these warnings.

Fixes: 4064b27417a7 ("scsi: lpfc: Make some symbols static")
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Acked-by: James Smart <james.smart@broadcom.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 336df6eb628298e27e40e23d1eb00a0fb7083269)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>