fs/Kconfig: Fix compile error for romfs
JIRA: https://issues.redhat.com/browse/RHEL-29564

commit a24c8b5111a139b54fd02fec23bc21789135cd2e
Author: Li Zetao <lizetao1@huawei.com>
Date:   Thu Aug 3 21:07:38 2023 +0800

    fs/Kconfig: Fix compile error for romfs

    There are some compile errors reported by kernel test robot:

    arm-linux-gnueabi-ld: fs/romfs/storage.o: in function `romfs_dev_read':
    storage.c:(.text+0x64): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x9c): undefined reference to `__bread_gfp'
    arm-linux-gnueabi-ld: fs/romfs/storage.o: in function `romfs_dev_strnlen':
    storage.c:(.text+0x128): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x16c): undefined reference to `__bread_gfp'
    arm-linux-gnueabi-ld: fs/romfs/storage.o: in function `romfs_dev_strcmp':
    storage.c:(.text+0x22c): undefined reference to `__bread_gfp'
    arm-linux-gnueabi-ld: storage.c:(.text+0x27c): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x2a8): undefined reference to `__bread_gfp'
    arm-linux-gnueabi-ld: storage.c:(.text+0x2bc): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x2d4): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x2f4): undefined reference to `__brelse'
    arm-linux-gnueabi-ld: storage.c:(.text+0x304): undefined reference to `__brelse'

    The reason for the problem is that the commit
    "925c86a19bac" ("fs: add CONFIG_BUFFER_HEAD") has added a new config
    "CONFIG_BUFFER_HEAD" that controls building the buffer_head code, and
    romfs needs to use the buffer_head API, but no corresponding config has
    beed added. Select the config "CONFIG_BUFFER_HEAD" in romfs Kconfig to
    resolve the problem.

    Fixes: 925c86a19bac ("fs: add CONFIG_BUFFER_HEAD")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202308031810.pQzGmR1v-lkp@intel.com/
    Reviewed-by: Luis Chamberlain <mcgrof@kernel.org>
    Tested-by: Li Zetao <lizetao1@huawei.com>
    Signed-off-by: Li Zetao <lizetao1@huawei.com>
    [axboe: fold in Christoph's incremental]
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>