perf build: Add missing cflags when building with custom libtraceevent
JIRA: https://issues.redhat.com/browse/RHEL-77935

upstream
========
commit d5a0a4ab4af4c27de097b78d6f1b7e7f7e31908f
Author: Yicong Yang <yangyicong@hisilicon.com>
Date: Thu Oct 24 21:32:36 2024 +0800

description
===========
When building with custom libtraceevent, below errors occur:

  $ make -C tools/perf NO_LIBPYTHON=1 PKG_CONFIG_PATH=<custom libtraceevent>
  In file included from util/session.h:5,
                   from builtin-buildid-list.c:17:
  util/trace-event.h:153:10: fatal error: traceevent/event-parse.h: No such file or directory
    153 | #include <traceevent/event-parse.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  <snip similar errors of missing headers>

This is because the include path is missed in the cflags. Add it.

Fixes: 0f0e1f445690 ("perf build: Use pkg-config for feature check for libtrace{event,fs}")
    Signed-off-by: Yicong Yang <yangyicong@hisilicon.com>
    Reviewed-by: Leo Yan <leo.yan@arm.com>
    Reviewed-by: Guilherme Amadio <amadio@gentoo.org>
    Cc: linuxarm@huawei.com
    Link: https://lore.kernel.org/r/20241024133236.31016-1-yangyicong@huawei.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>