x86/platform: Avoid missing-prototype warnings for OLPC
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 454a348714954f7b626c027a90c3967278e3f93b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:49 2023 +0200

    x86/platform: Avoid missing-prototype warnings for OLPC

    There are two functions in the olpc platform that have no prototype:

    arch/x86/platform/olpc/olpc_dt.c:237:13: error: no previous prototype for 'olpc_dt_fixup' [-Werror=missing-prototypes]
    arch/x86/platform/olpc/olpc-xo1-pm.c:73:26: error: no previous prototype for 'xo1_do_sleep' [-Werror=missing-prototypes]

    The first one should just be marked 'static' as there are no other
    callers, while the second one is called from assembler and is
    just a false-positive warning that can be silenced by adding a
    prototype.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-21-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>