pinctrl: tegra: tegra194: drop unused pin groups
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071845
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set updates pinctrl
 support (NB: some Intel and NVIDIA patches are included as well for similar
 Platforms).  It has been tested via simple boot tests, examining the pinctrl
 definintions in DeviceTree, and by using the kernel GPIO tools to verify
 pins are being still being identified and can be used.

commit a9387099d8a14cc9eaf6db15db1aa37bcfc3ac2d
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Apr 29 08:13:32 2022 +0200

    pinctrl: tegra: tegra194: drop unused pin groups

    The sdmmc1_hv_trim_pins, sdmmc3_hv_trim_pins and sys_reset_n_pins are
    not defined as pin groups:

      drivers/pinctrl/tegra/pinctrl-tegra194.c:1119:27: error: ‘sdmmc3_hv_trim_pins’ defined but not used [-Werror=unused-const-variable=]
       1119 | static const unsigned int sdmmc3_hv_trim_pins[] = {

    Proper fix would be to define them, but this requires knowledge from
    datasheet.  Removal should not cause any harm and at least it silences
    the warnings.

    Fixes: 613c0826081b ("pinctrl: tegra: Add pinmux support for Tegra194")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20220429061332.25135-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
    (cherry picked from commit a9387099d8a14cc9eaf6db15db1aa37bcfc3ac2d)

Signed-off-by: Al Stone <ahs3@redhat.com>