tools build: Fixup sched_getcpu feature test
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit 1e6e7eae8a3a66f5fee4f44ef165ffcf31f0c40e
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/1e6e7eae.failed

We have tools/build/feature/test-all.c to speed up feature testing,
doing all tests at once, but then all tests in this file should normally
pass.

That is not the case with the sched-getcpu one, that wasn't passing when
included from test-all.c because it needs to have _GNU_SOURCE defined
before including sched.h, but _GNU_SOURCE is defined by a header
included from another feature test included earlier in test-all.d,
test-libpython.c, resulting in:

  $ cat /tmp/build/perf/feature/test-all.make.output
  In file included from test-all.c:121:0:
  test-sched_getcpu.c:1:0: error: "_GNU_SOURCE" redefined [-Werror]
   #define _GNU_SOURCE

  In file included from /usr/include/python2.7/pyconfig.h:6:0,
                   from /usr/include/python2.7/Python.h:8,
                   from test-libpython.c:1,
                   from test-all.c:13:
  /usr/include/python2.7/pyconfig-64.h:1177:0: note: this is the location of the previous definition
   #define _GNU_SOURCE 1

  cc1: all warnings being treated as errors

Which would trigger testing the tests individually, when that
_GNU_SOURCE redefinition would not take place, and the whole process
would continue, just slower... Fix it.

	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Fixes: 120010cb1eea ("tools build: Add test for sched_getcpu()")
Link: http://lkml.kernel.org/n/tip-3qp1it69xsc4w8gnuu1e9ayh@git.kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 1e6e7eae8a3a66f5fee4f44ef165ffcf31f0c40e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/build/feature/test-sched_getcpu.c