ASoC: SOF: amd: Fixed Build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Syed Saba kareem <ssabakar@amd.com>
commit 803a1f7272797faa15a7879cdc70f9adaf3fdcba

Add linux/module.h in acp-pci.c to solve the below dependency

All error/warnings (new ones prefixed by >>):

>> sound/soc/amd/acp/acp-pci.c:148:1: warning: data definition has no type or storage class
148 | MODULE_DEVICE_TABLE(pci, acp_pci_ids);
| ^~~~~~~~~~~~~~~~~~~
>> sound/soc/amd/acp/acp-pci.c:148:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
...

	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Syed Saba Kareem<ssabakar@amd.com>
Link: https://lore.kernel.org/r/20220523112956.3087604-1-ssabakar@amd.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 803a1f7272797faa15a7879cdc70f9adaf3fdcba)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>