IB/mlx5: Fix use of null pointer PD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Majd Dibbiny <majd@mellanox.com>
commit 09f16cf59fbf825130c216c3af189253505dc9d9
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/09f16cf5.failed

When a Raw Ethernet QP is created, a NULL pointer PD could be used.
Fixing that by only using the PD after validating it's valid.
smatch also reported this error:
drivers/infiniband/hw/mlx5/qp.c:1629 mlx5_ib_create_qp()
	 error: we previously assumed 'pd' could be null (see line 1616)

Fixes: 0fb2ed66a14c ('IB/mlx5: Add create and destroy functionality for Raw Packet QP')
	Signed-off-by: Majd Dibbiny <majd@mellanox.com>
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 09f16cf59fbf825130c216c3af189253505dc9d9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/infiniband/hw/mlx5/qp.c