ASoC: wm9712: fix unused variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: wm9712: fix unused variable warning (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 93.18%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 18380dcc52cc8965e5144ce33fdfad7e168679a5

The 'ret' variable is now only used in an #ifdef, and causes a
warning if it is declared outside of that block:

sound/soc/codecs/wm9712.c: In function 'wm9712_soc_probe':
sound/soc/codecs/wm9712.c:641:6: error: unused variable 'ret' [-Werror=unused-variable]

Fixes: 2ed1a8e0ce8d ("ASoC: wm9712: add ac97 new bus support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Charles Keepax <ckeepax@opensource.cirrus.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 18380dcc52cc8965e5144ce33fdfad7e168679a5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>