wifi: rtw89: fix rtw89_read_chip_ver() for RTL8852B and RTL8851B
Bugzilla: https://bugzilla.redhat.com/2196821

commit 9d4f491b860ea6d04471c3342093b86a46eee63e
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Fri Apr 21 13:44:04 2023 +0300

    wifi: rtw89: fix rtw89_read_chip_ver() for RTL8852B and RTL8851B
    
    The if statement is reversed so it will not record the chip version.
    This was detected using Smatch:
    
        drivers/net/wireless/realtek/rtw89/core.c:3593 rtw89_read_chip_ver()
        error: uninitialized symbol 'val'.
    
    Fixes: a6fb2bb84654 ("wifi: rtw89: read version of analog hardware")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Acked-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/e4d912a2-37f8-4068-8861-7b9494ae731b@kili.mountain

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>