selftests: bonding: Check initial state
JIRA: https://issues.redhat.com/browse/RHEL-31077
Upstream Status: net.git commit 8cc063ae1b3d

commit 8cc063ae1b3dbe416ce62a15d49af4c2314b45fe
Author: Benjamin Poirier <bpoirier@nvidia.com>
Date:   Wed Jan 31 09:08:45 2024 -0500

    selftests: bonding: Check initial state

    The purpose of the test_LAG_cleanup() function is to check that some
    hardware addresses are removed from underlying devices after they have been
    unenslaved. The test function simply checks that those addresses are not
    present at the end. However, if the addresses were never added to begin
    with due to some error in device setup, the test function currently passes.
    This is a false positive since in that situation the test did not actually
    exercise the intended functionality.

    Add a check that the expected addresses are indeed present after device
    setup. This makes the test function more robust.

    I noticed this problem when running the team/dev_addr_lists.sh test on a
    system without support for dummy and ipv6:

    tools/testing/selftests/drivers/net/team# ./dev_addr_lists.sh
    Error: Unknown device type.
    Error: Unknown device type.
    This program is not intended to be run as root.
    RTNETLINK answers: Operation not supported
    TEST: team cleanup mode lacp                                        [ OK ]

    Fixes: bbb774d921e2 ("net: Add tests for bonding and team address list management")
    Signed-off-by: Benjamin Poirier <bpoirier@nvidia.com>
    Link: https://lore.kernel.org/r/20240131140848.360618-3-bpoirier@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>