ext4: fix compile error when using BUFFER_TRACE
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author zhangyi (F) <yi.zhang@huawei.com>
commit ddccb6dbe780d68133191477571cb7c69e17bb8c

Fix compile error below when using BUFFER_TRACE.

fs/ext4/inode.c: In function ‘ext4_expand_extra_isize’:
fs/ext4/inode.c:5979:19: error: request for member ‘bh’ in something not a structure or union
  BUFFER_TRACE(iloc.bh, "get_write_access");

Fixes: c03b45b853f58 ("ext4, project: expand inode extra size if possible")
	Signed-off-by: zhangyi (F) <yi.zhang@huawei.com>
	Signed-off-by: Theodore Ts'o <tytso@mit.edu>
	Reviewed-by: Jan Kara <jack@suse.cz>
(cherry picked from commit ddccb6dbe780d68133191477571cb7c69e17bb8c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>