perf tools riscv: Fix build error on riscv due to missing header for 'struct perf_sample'
Bugzilla: https://bugzilla.redhat.com/2177180

upstream
========
commit a8f54d940196c8bd9aced9c82557fdc63baefb02
Author: Eric Lin <eric.lin@sifive.com>
Date: Sat Dec 31 05:27:31 2022 +0000

description
===========
Since the definition of 'struct perf_sample' has been moved to sample.h,
we need to include this header file to fix the build error as follows:

  arch/riscv/util/unwind-libdw.c: In function 'libdw__arch_set_initial_registers':
  arch/riscv/util/unwind-libdw.c:12:50: error: invalid use of undefined type 'struct perf_sample'
     12 |         struct regs_dump *user_regs = &ui->sample->user_regs;
        |                                                  ^~

Fixes: 9823147da6c893d9 ("perf tools: Move 'struct perf_sample' to a separate header file to disentangle headers")
    Signed-off-by: Eric Lin <eric.lin@sifive.com>
    Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Cc: greentime.hu@sifive.com
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: linux-riscv@lists.infradead.org
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Paul Walmsley <paul.walmsley@sifive.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Vincent Chen <vincent.chen@sifive.com>
    Link: https://lore.kernel.org/r/20221231052731.24908-1-eric.lin@sifive.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>