sched: Remove never used code in mm_cid_get()
JIRA: https://issues.redhat.com/browse/RHEL-147186

commit 53abe3e1c154628cc74e33a1bfcd865656e433a5
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Wed Oct 15 11:19:34 2025 +0200

    sched: Remove never used code in mm_cid_get()

    Clang is not happy with set but unused variable (this is visible
    with `make W=1` build:

      kernel/sched/sched.h:3744:18: error: variable 'cpumask' set but not used [-Werror,-Wunused-but-set-variable]

    It seems like the variable was never used along with the assignment
    that does not have side effects as far as I can see.  Remove those
    altogether.

    Fixes: 223baf9d17f2 ("sched: Fix performance regression introduced by mm_cid")
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Tested-by: Eric Biggers <ebiggers@kernel.org>
    Reviewed-by: Breno Leitao <leitao@debian.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Phil Auld <pauld@redhat.com>