drm/amd/display: avoid stringop-overflow warnings for dp_decide_lane_settings()
JIRA: https://issues.redhat.com/browse/RHEL-1351
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.6.14)

commit ecfaeb66b1f08c72fe8e8d1df955cf2879d7333b
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Wed Nov 22 23:13:36 2023 +0100
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Thu Jan 25 15:35:40 2024 -0800

    [ Upstream commit c966dc0e9d96dc44423c404a2628236f1200c24e ]

    gcc prints a warning about a possible array overflow for a couple of
    callers of dp_decide_lane_settings() after commit 1b56c90018f0 ("Makefile:
    Enable -Wstringop-overflow globally"):

    drivers/gpu/drm/amd/amdgpu/../display/dc/link/protocols/link_dp_training_fixed_vs_pe_retimer.c: In function 'dp_perform_fixed_vs_pe_training_sequence_legacy':
    drivers/gpu/drm/amd/amdgpu/../display/dc/link/protocols/link_dp_training_fixed_vs_pe_retimer.c:426:25: error: 'dp_decide_lane_settings' accessing 4 bytes in a region of size 1 [-Werror=stringop-overflow=]
      426 |                         dp_decide_lane_settings(lt_settings, dpcd_lane_adjust,
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      427 |                                         lt_settings->hw_lane_settings, lt_settings->dpcd_lane_settings);
          |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/amd/amdgpu/../display/dc/link/protocols/link_dp_training_fixed_vs_pe_retimer.c:426:25: note: referencing argument 4 of type 'union dpcd_training_lane[4]'

    I'm not entirely sure what caused this, but changing the prototype to expect
    a pointer instead of an array avoids the warnings.

    Fixes: 7727e7b60f82 ("drm/amd/display: Improve robustness of FIXED_VS link training at DP1 rates")
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>