selftests: cachestat: properly link in librt
JIRA: https://issues.redhat.com/browse/RHEL-50302

commit 7fb10233e0617603402abffc0d8d2cbf5ef55560
Author: Andre Przywara <andre.przywara@arm.com>
Date:   Tue Aug 15 16:56:10 2023 +0100

    selftests: cachestat: properly link in librt

    Libraries should be listed last on the compiler's command line, so that
    the linker can look for and find still unresolved symbols. The librt
    library, required for the shm_* functions, was announced using CFLAGS,
    which puts the library *before* the source files, and fails compilation
    on my system:
    ======================
    gcc -isystem /src/linux-selftests/usr/include -Wall -lrt test_cachestat.c
      -o /src/linux-selftests/kselftest/cachestat/test_cachestat
    /usr/bin/ld: /tmp/cceQWO3u.o: in function `test_cachestat_shmem':
    test_cachestat.c:(.text+0x890): undefined reference to `shm_open'
    /usr/bin/ld: test_cachestat.c:(.text+0x99c): undefined reference to `shm_unlink'
    collect2: error: ld returned 1 exit status
    make[4]: *** [../lib.mk:181: /src/linux-selftests/kselftest/cachestat/test_cachestat] Error 1
    ======================

    Announce the library using the LDLIBS variable, which ensures the proper
    ordering on the command line.

    Signed-off-by: Andre Przywara <andre.przywara@arm.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Eric Chanudet <echanude@redhat.com>