regulator: lp872x: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2213574

commit 70b26bb55f719e2900404459128d41c8425c8dde
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Mar 10 22:45:45 2023 +0100

    regulator: lp872x: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/regulator/lp872x.c:931:34: error: ‘lp872x_dt_ids’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214553.275450-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Adrien Thierry <athierry@redhat.com>