bpf: Fix net/core/filter build errors when INET is not enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 6b207d66aa9fad0deed13d5f824e1ea193b0a777
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/6b207d66.failed

Fix build errors when CONFIG_INET is not set/enabled.

(.text+0x2b1b): undefined reference to `tcp_prot'
(.text+0x2b3b): undefined reference to `tcp_prot'

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
	Acked-by: Yonghong Song <yhs@fb.com>
Link: https://lore.kernel.org/bpf/b1a858ec-7e04-56bc-248a-62cb9bbee726@infradead.org
(cherry picked from commit 6b207d66aa9fad0deed13d5f824e1ea193b0a777)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/core/filter.c