crypto: ccp - Fix dereferencing uninitialized error pointer
JIRA: https://issues.redhat.com/browse/RHEL-106910
Upstream Status: merged into the linux.git
CVE: CVE-2025-39729

commit 0fa766726c091ff0ec7d26874f6e4724d23ecb0e
Author: Ashish Kalra <ashish.kalra@amd.com>
Date:   Wed May 28 20:20:18 2025 +0000

    crypto: ccp - Fix dereferencing uninitialized error pointer

    Fix below smatch warnings:
    drivers/crypto/ccp/sev-dev.c:1312 __sev_platform_init_locked()
    error: we previously assumed 'error' could be null

    Fixes: 9770b428b1a2 ("crypto: ccp - Move dev_info/err messages for SEV/SNP init and shutdown")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/r/202505071746.eWOx5QgC-lkp@intel.com/
    Signed-off-by: Ashish Kalra <ashish.kalra@amd.com>
    Reviewed-by: Tom Lendacky <thomas.lendacky@amd.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>