md: raid10: remove VLAIS
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [md] raid10: remove VLAIS (Nigel Croxon) [1494474]
Rebuild_FUZZ: 90.91%
commit-author Matthias Kaehlcke <mka@chromium.org>
commit 584ed9fa9532f8b9d5955628ff87ee3b2ab9f5a9
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/584ed9fa.failed

The raid10 driver can't be built with clang since it uses a variable
length array in a structure (VLAIS):

drivers/md/raid10.c:4583:17: error: fields must have a constant size:
  'variable length array in structure' extension will never be supported

Allocate the r10bio struct with kmalloc instead of using the VLAIS
construct.

Shaohua: set the MD_RECOVERY_INTR bit
Neil Brown: use GFP_NOIO

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Reviewed-by: Guenter Roeck <groeck@chromium.org>
	Signed-off-by: Shaohua Li <shli@fb.com>
(cherry picked from commit 584ed9fa9532f8b9d5955628ff87ee3b2ab9f5a9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/md/raid10.c