thermal/core: Fix thermal_cooling_device_register() prototype
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071849
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2126952
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for Arm SystemReady IR compliant platforms.
 This set cleans up thermal handling for imx8m and Tegra234 in
 drivers/thermal.  This set has been tested via simple boot tests,
 and of course the CI loop.

commit fb83610762dd5927212aa62a468dd3b756b57a88
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jul 22 11:06:44 2021 +0200

    thermal/core: Fix thermal_cooling_device_register() prototype

    There are two pairs of declarations for thermal_cooling_device_register()
    and thermal_of_cooling_device_register(), and only one set was changed
    in a recent patch, so the other one now causes a compile-time warning:

    drivers/net/wireless/mediatek/mt76/mt7915/init.c: In function 'mt7915_thermal_init':
    drivers/net/wireless/mediatek/mt76/mt7915/init.c:134:48: error: passing argument 1 of 'thermal_cooling_device_register' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
      134 |         cdev = thermal_cooling_device_register(wiphy_name(wiphy), phy,
          |                                                ^~~~~~~~~~~~~~~~~
    In file included from drivers/net/wireless/mediatek/mt76/mt7915/init.c:7:
    include/linux/thermal.h:407:39: note: expected 'char *' but argument is of type 'const char *'
      407 | thermal_cooling_device_register(char *type, void *devdata,
          |                                 ~~~~~~^~~~

    Change the dummy helper functions to have the same arguments as the
    normal version.

    Fixes: f991de53a8ab ("thermal: make device_register's type argument const")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jean-Francois Dagenais <jeff.dagenais@gmail.com>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>
    Link: https://lore.kernel.org/r/20210722090717.1116748-1-arnd@kernel.org
    (cherry picked from commit fb83610762dd5927212aa62a468dd3b756b57a88)

Signed-off-by: Al Stone <ahs3@redhat.com>