perf top: Remove needless malloc(0) call that triggers -Walloc-size
JIRA: https://issues.redhat.com/browse/RHEL-25824

upstream
========
commit 79baac8acfc60a7a5114f6d60731e28c242ef8ce
Author: Sun Haiyong <sunhaiyong@loongson.cn>
Date: Mon Dec 4 16:20:55 2023 +0800

description
===========
GCC 14 introduces a new -Walloc-size included in -Wextra which errors out
like:

  builtin-top.c: In function ‘prompt_integer’:
  builtin-top.c:360:21: error: allocation of insufficient size ‘0’ for
  type ‘char’ with size ‘1’ [-Werror=alloc-size]
    360 |         char *buf = malloc(0), *p;
        |                     ^~~~~~

Just set it to NULL, getline() will do the allocation.

    Signed-off-by: Sun Haiyong <sunhaiyong@loongson.cn>
    Signed-off-by: Yanteng Si <siyanteng@loongson.cn>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Link: https://lore.kernel.org/r/20231204082055.91877-1-siyanteng@loongson.cn
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>