ASoC: codecs: rt1019: Mark OF related data as maybe unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
commit 0e8599a35823f05e90513918ff1201f8d210e315

The driver can be compile tested with !CONFIG_OF making certain data
unused:

  sound/soc/codecs/rt1019.c:549:34: error: ‘rt1019_of_match’ defined but not used [-Werror=unused-const-variable=]

	Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230310214333.274903-8-krzysztof.kozlowski@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0e8599a35823f05e90513918ff1201f8d210e315)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>