ASoC: Intel: catpt: avoid type mismatch in dev_dbg() format
JIRA: https://issues.redhat.com/browse/RHEL-80658

commit 95b2536137eeb66f20947e0fb0d0c100c8d6a140
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Apr 29 09:35:19 2025 +0200

    ASoC: Intel: catpt: avoid type mismatch in dev_dbg() format

    Depending on the architecture __ffs() returns either an 'unsigned long'
    or 'unsigned int' result. Compile-testing this driver on targets that
    use the latter produces a warning:

    sound/soc/intel/catpt/dsp.c: In function 'catpt_dsp_set_srampge':
    sound/soc/intel/catpt/dsp.c:181:44: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'u32' {aka 'unsigned int'} [-Werror=format=]
      181 |                         dev_dbg(cdev->dev, "sanitize block %ld: off 0x%08x\n",
          |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Change the type of the local variable to match the format string and
    avoid the warning on any architecture.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Cezary Rojewski <cezary.rojewski@intel.com>
    Link: https://patch.msgid.link/20250429073545.3558494-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>