ASoC: amd: acp: fix SND_SOC_AMD_ACP_PCI depdenencies
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 4edc07fc7fe1a9eec1a4ebc518d2dec222382f43
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Jul 19 15:08:37 2023 +0200

    ASoC: amd: acp: fix SND_SOC_AMD_ACP_PCI depdenencies

    The new PM functions require code that is part of the snd-acp-legacy-common
    module:

    x86_64-linux-ld: sound/soc/amd/acp/acp-pci.o: in function `snd_acp_resume':
    acp-pci.c:(.text+0x23): undefined reference to `acp_init'
    x86_64-linux-ld: acp-pci.c:(.text+0x58): undefined reference to `acp_enable_interrupts'
    x86_64-linux-ld: sound/soc/amd/acp/acp-pci.o: in function `snd_acp_suspend':
    acp-pci.c:(.text+0x89): undefined reference to `acp_deinit'
    x86_64-linux-ld: sound/soc/amd/acp/acp-pci.o: in function `acp_pci_remove':
    acp-pci.c:(.text+0xec): undefined reference to `acp_deinit'
    x86_64-linux-ld: sound/soc/amd/acp/acp-pci.o: in function `acp_pci_probe':
    acp-pci.c:(.text+0x26b): undefined reference to `acp_init'

    Select that Kconfig symbol as is done for the other frontends.

    Fixes: 088a40980efbc ("ASoC: amd: acp: add pm ops support for acp pci driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230719130846.633701-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>