net: hns: make hns_dsaf_roce_reset non static
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit ff7b91262b3ad31dfe1461dace0314a773b0fa55

hns_dsaf_roce_reset is exported and used in hns_roce_hw_v1.c
In commit 336a443bd9dd ("net: hns: Make many functions static") I make
it static wrongly.

drivers/infiniband/hw/hns/hns_roce_hw_v1.o: In function `hns_roce_v1_reset':
hns_roce_hw_v1.c:(.text+0x37ac): undefined reference to `hns_dsaf_roce_reset'
hns_roce_hw_v1.c:(.text+0x37cc): undefined reference to `hns_dsaf_roce_reset'

Fixes: 336a443bd9dd ("net: hns: Make many functions static")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ff7b91262b3ad31dfe1461dace0314a773b0fa55)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>