mptcp: Fix code formatting
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Mat Martineau <mathew.j.martineau@linux.intel.com>
commit edc7e4898d5fdb164de1ab9d3a0c30ef9888e4f1

checkpatch.pl had a few complaints in the last set of MPTCP patches:

ERROR: code indent should use tabs where possible
+^I         subflow, sk->sk_family, icsk->icsk_af_ops, target, mapped);$

CHECK: Comparison to NULL could be written "!new_ctx"
+	if (new_ctx == NULL) {

ERROR: "foo * bar" should be "foo *bar"
+static const struct proto_ops * tcp_proto_ops(struct sock *sk)

	Signed-off-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit edc7e4898d5fdb164de1ab9d3a0c30ef9888e4f1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>