powerpc/mm: fix ".__node_distance" undefined
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] mm: fix ".__node_distance" undefined (David Milburn) [1081734]
Rebuild_FUZZ: 90.00%
commit-author Mike Qiu <qiudayu@linux.vnet.ibm.com>
commit 12c743eb2289bcaace32859d4919417ff5707768

  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  ...
  Building modules, stage 2.
WARNING: 1 bad relocations
c0000000013d6a30 R_PPC64_ADDR64    uprobes_fetch_type_table
  WRAP    arch/powerpc/boot/zImage.pseries
  WRAP    arch/powerpc/boot/zImage.epapr
  MODPOST 1849 modules
ERROR: ".__node_distance" [drivers/block/nvme.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
make: *** Waiting for unfinished jobs....

The reason is symbol "__node_distance" not been exported in powerpc.

	Signed-off-by: Mike Qiu <qiudayu@linux.vnet.ibm.com>
	Acked-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Nathan Fontenot <nfont@linux.vnet.ibm.com>
	Cc: Stephen Rothwell <sfr@canb.auug.org.au>
	Cc: Srivatsa S. Bhat <srivatsa.bhat@linux.vnet.ibm.com>
	Cc: Jesse Larrew <jlarrew@linux.vnet.ibm.com>
	Cc: Robert Jennings <rcj@linux.vnet.ibm.com>
	Cc: Alistair Popple <alistair@popple.id.au>
	Cc: Mike Qiu <qiudayu@linux.vnet.ibm.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 12c743eb2289bcaace32859d4919417ff5707768)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>