selftests/bpf: Rename fallback in bpf_dctcp to avoid naming conflict
JIRA: https://issues.redhat.com/browse/RHEL-63880

Conflicts: Context change due to missing commit 0ce089cbdc6a ("bpf:
selftests: Namespace struct_opt callbacks in bpf_dctcp")

commit a48a43884cdd46dba8cc4a15160c116ffd965800
Author: Pu Lehui <pulehui@huawei.com>
Date:   Thu Sep 5 08:13:53 2024 +0000

    selftests/bpf: Rename fallback in bpf_dctcp to avoid naming conflict

    Recently, when compiling bpf selftests on RV64, the following
    compilation failure occurred:

    progs/bpf_dctcp.c:29:21: error: redefinition of 'fallback' as different kind of symbol
       29 | volatile const char fallback[TCP_CA_NAME_MAX];
          |                     ^
    /workspace/tools/testing/selftests/bpf/tools/include/vmlinux.h:86812:15: note: previous definition is here
     86812 | typedef u32 (*fallback)(u32, const unsigned char *, size_t);

    The reason is that the `fallback` symbol has been defined in
    arch/riscv/lib/crc32.c, which will cause symbol conflicts when vmlinux.h
    is included in bpf_dctcp. Let we rename `fallback` string to
    `fallback_cc` in bpf_dctcp to fix this compilation failure.

    Signed-off-by: Pu Lehui <pulehui@huawei.com>
    Link: https://lore.kernel.org/r/20240905081401.1894789-3-pulehui@huaweicloud.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>