wifi: mwifiex: mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2178526

commit 139f6973bf140c65d4d1d4bde5485badb4454d7a
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sun Mar 12 14:25:23 2023 +0100

    wifi: mwifiex: mark OF related data as maybe unused
    
    The driver can be compile tested with !CONFIG_OF making certain data
    unused:
    
      drivers/net/wireless/marvell/mwifiex/sdio.c:498:34: error: ‘mwifiex_sdio_of_match_table’ defined but not used [-Werror=unused-const-variable=]
      drivers/net/wireless/marvell/mwifiex/pcie.c:175:34: error: ‘mwifiex_pcie_of_match_table’ defined but not used [-Werror=unused-const-variable=]
    
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230312132523.352182-1-krzysztof.kozlowski@linaro.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>