libceph: fix old style declaration warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit e67ae2b7b23b283e657865b498b151e6a17b919d

The new macros don't follow the usual style for declarations,
which we get a warning for with 'make W=1':

In file included from fs/ceph/mds_client.c:16:0:
include/linux/ceph/ceph_features.h:74:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

This moves the 'static' keyword to the front of the
declaration.

Fixes: f179d3ba8cb9 ("libceph: new features macros")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit e67ae2b7b23b283e657865b498b151e6a17b919d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>