ipv4/route: avoid unused-but-set-variable warning
jira KERNEL-474
Rebuild_History Non-Buildable kernel-5.14.0-611.24.1.el9_7
commit-author Arnd Bergmann <arnd@arndb.de>
commit cf1b7201df59fb936f40f4a807433fe3f2ce310a

The log_martians variable is only used in an #ifdef, causing a 'make W=1'
warning with gcc:

net/ipv4/route.c: In function 'ip_rt_send_redirect':
net/ipv4/route.c:880:13: error: variable 'log_martians' set but not used [-Werror=unused-but-set-variable]

Change the #ifdef to an equivalent IS_ENABLED() to let the compiler
see where the variable is used.

Fixes: 30038fc61adf ("net: ip_rt_send_redirect() optimization")
	Reviewed-by: David Ahern <dsahern@kernel.org>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Eric Dumazet <edumazet@google.com>
Link: https://lore.kernel.org/r/20240408074219.3030256-2-arnd@kernel.org
	Signed-off-by: Paolo Abeni <pabeni@redhat.com>
(cherry picked from commit cf1b7201df59fb936f40f4a807433fe3f2ce310a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>