perf tools: Fix compile of util/tsc.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [tools] perf: Fix compile of util/tsc.c (Jiri Olsa) [1036665]
Rebuild_FUZZ: 91.18%
commit-author David Ahern <dsahern@gmail.com>
commit 602bab1b883090ffd125ed1253fe8ec127c048b1

On Fedora 18, with gcc 4.6.4 compile fails with:

arch/x86/util/tsc.c: In function ‘perf_time_to_tsc’:
arch/x86/util/tsc.c:13:6: error: declaration of ‘time’ shadows a global declaration [-Werror=shadow]
cc1: all warnings being treated as errors
make: *** [/tmp/junk/arch/x86/util/tsc.o] Error 1
make: *** Waiting for unfinished jobs....

Fix by renaming the local variable.

	Signed-off-by: David Ahern <dsahern@gmail.com>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
Link: http://lkml.kernel.org/r/1374848843-43127-1-git-send-email-dsahern@gmail.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 602bab1b883090ffd125ed1253fe8ec127c048b1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>