Bluetooth: btnxpuart: Fix missing devm_request_irq() return value check
JIRA: https://issues.redhat.com/browse/RHEL-107922

commit edc14f2adc6401d67bf73828d9135c80d32615a2
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sun May 25 21:00:21 2025 +0200

    Bluetooth: btnxpuart: Fix missing devm_request_irq() return value check

    Return value of devm_request_irq() must be checked (function is even
    annotated) and without it clang W=1 complains:

      btnxpuart.c:494:6: error: unused variable 'ret' [-Werror,-Wunused-variable]

    Setting up wakeup IRQ handler is not really critical, because the
    handler is empty, so just log the informational message so user could
    submit proper bug report and silences the clang warning.

    Fixes: c50b56664e48 ("Bluetooth: btnxpuart: Implement host-wakeup feature")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Neeraj Sanjay Kale <neeraj.sanjaykale@nxp.com>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: David Marlin <dmarlin@redhat.com>