net: ipv4: avoid unused variable warning for sysctl
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] ipv4: avoid unused variable warning for sysctl (Sabrina Dubroca) [1541250]
Rebuild_FUZZ: 94.85%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 773daa3caf5d3f87fdb1ab43e9c1b367a38fa394

The newly introudced ip_min_valid_pmtu variable is only used when
CONFIG_SYSCTL is set:

net/ipv4/route.c:135:12: error: 'ip_min_valid_pmtu' defined but not used [-Werror=unused-variable]

This moves it to the other variables like it, to avoid the harmless
warning.

Fixes: c7272c2f1229 ("net: ipv4: don't allow setting net.ipv4.route.min_pmtu below 68")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Sabrina Dubroca <sd@queasysnail.net>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 773daa3caf5d3f87fdb1ab43e9c1b367a38fa394)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>