selftests: bpf: xskxceiver: ksft_print_msg: fix format type error
Conflicts:
       tools/testing/selftests/bpf/xskxceiver.c: missing upstream
        commit 8367eb954e24 ("selftests/xsk: Move pkt_stream to the
        xsk_socket_info")

commit fe69a1b1b6ed9ffc2c578c63f526026a8ab74f0c
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Thu Nov 9 18:43:28 2023 +0100

    selftests: bpf: xskxceiver: ksft_print_msg: fix format type error

    Crossbuilding selftests/bpf for architecture arm64, format specifies
    type error show up like.

    xskxceiver.c:912:34: error: format specifies type 'int' but the argument
    has type '__u64' (aka 'unsigned long long') [-Werror,-Wformat]
     ksft_print_msg("[%s] expected meta_count [%d], got meta_count [%d]\n",
                                                                    ~~
                                                                    %llu
                    __func__, pkt->pkt_nb, meta->count);
                                           ^~~~~~~~~~~
    xskxceiver.c:929:55: error: format specifies type 'unsigned long long' but
     the argument has type 'u64' (aka 'unsigned long') [-Werror,-Wformat]
     ksft_print_msg("Frag invalid addr: %llx len: %u\n", addr, len);
                                        ~~~~             ^~~~

    Fixing the issues by casting to (unsigned long long) and changing the
    specifiers to be %llu from %d and %u, since with u64s it might be %llx
    or %lx, depending on architecture.

    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
    Link: https://lore.kernel.org/r/20231109174328.1774571-1-anders.roxell@linaro.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

JIRA: https://issues.redhat.com/browse/RHEL-39306
Signed-off-by: Nico Pache <npache@redhat.com>