tools: ynl: introduce option to process unknown attributes or types
JIRA: https://issues.redhat.com/browse/RHEL-30145

Upstream commit(s):
commit d96e48a3d55db7ee62e607ad2d89eee1a8585028
Author: Jiri Pirko <jiri@nvidia.com>
Date:   Fri Oct 27 11:25:25 2023 +0200

    tools: ynl: introduce option to process unknown attributes or types

    In case the kernel sends message back containing attribute not defined
    in family spec, following exception is raised to the user:

    $ sudo ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/devlink.yaml --do trap-get --json '{"bus-name": "netdevsim", "dev-name": "netdevsim1", "trap-name": "source_mac_is_multicast"}'
    Traceback (most recent call last):
      File "/home/jiri/work/linux/tools/net/ynl/lib/ynl.py", line 521, in _decode
        attr_spec = attr_space.attrs_by_val[attr.type]
                    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 132

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/jiri/work/linux/./tools/net/ynl/cli.py", line 61, in <module>
        main()
      File "/home/jiri/work/linux/./tools/net/ynl/cli.py", line 49, in main
        reply = ynl.do(args.do, attrs, args.flags)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jiri/work/linux/tools/net/ynl/lib/ynl.py", line 731, in do
        return self._op(method, vals, flags)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jiri/work/linux/tools/net/ynl/lib/ynl.py", line 719, in _op
        rsp_msg = self._decode(decoded.raw_attrs, op.attr_set.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jiri/work/linux/tools/net/ynl/lib/ynl.py", line 525, in _decode
        raise Exception(f"Space '{space}' has no attribute with value '{attr.type}'")
    Exception: Space 'devlink' has no attribute with value '132'

    Introduce a command line option "process-unknown" and pass it down to
    YnlFamily class constructor to allow user to process unknown
    attributes and types and print them as binaries.

    $ sudo ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/devlink.yaml --do trap-get --json '{"bus-name": "netdevsim", "dev-name": "netdevsim1", "trap-name": "source_mac_is_multicast"}' --process-unknown
    {'UnknownAttr(129)': {'UnknownAttr(0)': b'\x00\x00\x00\x00\x00\x00\x00\x00',
                          'UnknownAttr(1)': b'\x00\x00\x00\x00\x00\x00\x00\x00',
                          'UnknownAttr(2)': b'\x0e\x00\x00\x00\x00\x00\x00\x00'},
     'UnknownAttr(132)': b'\x00',
     'UnknownAttr(133)': b'',
     'UnknownAttr(134)': {'UnknownAttr(0)': b''},
     'bus-name': 'netdevsim',
     'dev-name': 'netdevsim1',
     'trap-action': 'drop',
     'trap-group-name': 'l2_drops',
     'trap-name': 'source_mac_is_multicast'}

    Signed-off-by: Jiri Pirko <jiri@nvidia.com>
    Link: https://lore.kernel.org/r/20231027092525.956172-1-jiri@resnulli.us
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>