selftests: harness: Rename is_signed_type() to avoid collision with overflow.h
JIRA: https://issues.redhat.com/browse/RHEL-120168

commit dce1b33ed7430c7189b8cc1567498f9e6bf12731
Author: Sean Christopherson <seanjc@google.com>
Date:   Tue Jun 24 16:19:30 2025 -0700

    selftests: harness: Rename is_signed_type() to avoid collision with overflow.h

    Rename is_signed_type() to is_signed_var() to avoid colliding with a macro
    of the same name defined by tools' linux/overflow.h.  This fixes warnings
    (and presumably potential test failures) in tests that utilize the
    selftests harness and happen to (indirectly) include overflow.h.

      In file included from tools/include/linux/bits.h:34,
                       from tools/include/linux/bitops.h:14,
                       from tools/include/linux/hashtable.h:13,
                       from include/kvm_util.h:11,
                       from x86/userspace_msr_exit_test.c:11:
      tools/include/linux/overflow.h:31:9: error: "is_signed_type" redefined [-Werror]
         31 | #define is_signed_type(type)       (((type)(-1)) < (type)1)
            |         ^~~~~~~~~~~~~~
      In file included from include/kvm_test_harness.h:11,
                       from x86/userspace_msr_exit_test.c:9:
      ../kselftest_harness.h:754:9: note: this is the location of the previous definition
        754 | #define is_signed_type(var)       (!!(((__typeof__(var))(-1)) < (__typeof__(var))1))
            |         ^~~~~~~~~~~~~~

    Use a separate definition, at least for now, as many selftests build
    without tools/include in their include path.

    Fixes: fc92099902fb ("tools headers: Synchronize linux/bits.h with the kernel sources")
    Cc: Vincent Mailhol <mailhol.vincent@wanadoo.fr>
    Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
    Cc: Mark Brown <broonie@kernel.org>
    Link: https://lore.kernel.org/r/20250624231930.583689-1-seanjc@google.com
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>