wifi: b43: fix incorrect __packed annotation
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 212457ccbd60dba34f965e4ffbe62f0e4f970538

clang warns about an unpacked structure inside of a packed one:

drivers/net/wireless/broadcom/b43/b43.h:654:4: error: field data within 'struct b43_iv' is less aligned than 'union (unnamed union at /home/arnd/arm-soc/drivers/net/wireless/broadcom/b43/b43.h:651:2)' and is usually due to 'struct b43_iv' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]

The problem here is that the anonymous union has the default alignment
from its members, apparently because the original author mixed up the
placement of the __packed attribute by placing it next to the struct
member rather than the union definition. As the struct itself is
also marked as __packed, there is no need to mark its members, so just
move the annotation to the inner type instead.

As Michael noted, the same problem is present in b43legacy, so
change both at the same time.

	Acked-by: Michael Büsch <m@bues.ch>
	Reported-by: kernel test robot <lkp@intel.com>
	Reviewed-by: Simon Horman <simon.horman@corigine.com>
	Tested-by: Larry Finger <Larry.Finger@lwfinger.net>
Link: https://lore.kernel.org/oe-kbuild-all/202305160749.ay1HAoyP-lkp@intel.com/
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230516183442.536589-1-arnd@kernel.org
(cherry picked from commit 212457ccbd60dba34f965e4ffbe62f0e4f970538)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>