bpftool: Skeleton should depend on libbpf
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Song Liu <songliubraving@fb.com>
commit 39be909c38a42543239de97087d3c93ea9272864

Add the dependency to libbpf, to fix build errors like:

  In file included from skeleton/profiler.bpf.c:5:
  .../bpf_helpers.h:5:10: fatal error: 'bpf_helper_defs.h' file not found
  #include "bpf_helper_defs.h"
           ^~~~~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [skeleton/profiler.bpf.o] Error 1
  make: *** Waiting for unfinished jobs....

Fixes: 47c09d6a9f67 ("bpftool: Introduce "prog profile" command")
	Suggested-by: Quentin Monnet <quentin@isovalent.com>
	Signed-off-by: Song Liu <songliubraving@fb.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Reviewed-by: Quentin Monnet <quentin@isovalent.com>
	Acked-by: John Fastabend <john.fastabend@gmail.com>
Link: https://lore.kernel.org/bpf/20200312182332.3953408-3-songliubraving@fb.com
(cherry picked from commit 39be909c38a42543239de97087d3c93ea9272864)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>