Documentation: KUnit: Fix example with compilation error
commit 4c392516accfe51a1aaf80ed163517646f8f0476
Author: Maíra Canal <mairacanal@riseup.net>
Date:   Wed Jul 20 15:57:19 2022 -0300

    Documentation: KUnit: Fix example with compilation error

    The Parameterized Testing example contains a compilation error, as the
    signature for the description helper function is void(*)(const struct
    sha1_test_case *, char *), and the struct is non-const. This is
    warned by Clang:

    error: initialization of ‘void (*)(struct sha1_test_case *, char *)’
    from incompatible pointer type ‘void (*)(const struct sha1_test_case *,
    char *)’ [-Werror=incompatible-pointer-types]
    33 | KUNIT_ARRAY_PARAM(sha1, cases, case_to_desc);
       |                                ^~~~~~~~~~~~
    ../include/kunit/test.h:1339:70: note: in definition of macro
    ‘KUNIT_ARRAY_PARAM’
    1339 |                         void
       (*__get_desc)(typeof(__next), char *) = get_desc; \

    Signed-off-by: Maíra Canal <mairacanal@riseup.net>
    Reviewed-by: Daniel Latypov <dlatypov@google.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>