perf probe: Find versioned symbols from map
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit 4b3a2716dd785fabb9f6ac80c1d53cb29a88169d

Commit d80406453ad4 ("perf symbols: Allow user probes on versioned
symbols") allows user to find default versioned symbols (with "@@") in
map. However, it did not enable normal versioned symbol (with "@") for
perf-probe.  E.g.

  =====
  # ./perf probe -x /lib64/libc-2.25.so malloc_get_state
  Failed to find symbol malloc_get_state in /usr/lib64/libc-2.25.so
    Error: Failed to add events.
  =====

This solves above issue by improving perf-probe symbol search function,
as below.

  =====
  # ./perf probe -x /lib64/libc-2.25.so malloc_get_state
  Added new event:
    probe_libc:malloc_get_state (on malloc_get_state in /usr/lib64/libc-2.25.so)

  You can now use it in all perf tools, such as:

	  perf record -e probe_libc:malloc_get_state -aR sleep 1

  # ./perf probe -l
    probe_libc:malloc_get_state (on malloc_get_state@GLIBC_2.2.5 in /usr/lib64/libc-2.25.so)
  =====

	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Reviewed-by: Thomas Richter <tmricht@linux.vnet.ibm.com>
	Acked-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: bhargavb <bhargavaramudu@gmail.com>
	Cc: linux-rt-users@vger.kernel.org
Link: http://lkml.kernel.org/r/151275049269.24652.1639103455496216255.stgit@devbox
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 4b3a2716dd785fabb9f6ac80c1d53cb29a88169d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>