mlxsw: spectrum_flower: Make vlan_id limitation more specific
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2140704

commit 70ec72d5b6c25822184f7adf9ec3ba207138e7ff
Author: Amit Cohen <amcohen@nvidia.com>
Date:   Tue Dec 21 16:49:42 2021 +0200

    mlxsw: spectrum_flower: Make vlan_id limitation more specific

    Spectrum ASICs do not support matching of VLAN ID at egress.
    Currently, mlxsw driver forbids matching of all VLAN related fields at
    egress, which is too strict check.

    For example, the following filter is not supported by the driver:
    $ tc filter add dev swpX egress protocol 802.1q pref 1 handle 101 flower
    vlan_ethtype ipv4 src_ip .. dst_ip .. skip_sw action pass
    Error: mlxsw_spectrum: vlan_id key is not supported on egress.
    We have an error talking to the kernel

    The filter above does not match on VLAN ID, but is bounced anyway.

    Make the check more specific, forbid only matching of 'vlan_id' at egress.

    Signed-off-by: Amit Cohen <amcohen@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>