netfilter: nft_set_pipapo: fix range overlap detection
JIRA: https://redhat.atlassian.net/browse/RHEL-168848
Upstream Status: commit 7711f4bb4b36

commit 7711f4bb4b360d9c0ff84db1c0ec91e385625047
Author: Florian Westphal <fw@strlen.de>
Date:   Thu Dec 4 12:20:35 2025 +0100

    netfilter: nft_set_pipapo: fix range overlap detection

    set->klen has to be used, not sizeof().  The latter only compares a
    single register but a full check of the entire key is needed.

    Example:
    table ip t {
            map s {
                    typeof iifname . ip saddr : verdict
                    flags interval
            }
    }

    nft add element t s '{ "lo" . 10.0.0.0/24 : drop }' # no error, expected
    nft add element t s '{ "lo" . 10.0.0.0/24 : drop }' # no error, expected
    nft add element t s '{ "lo" . 10.0.0.0/8 : drop }' # bug: no error

    The 3rd 'add element' should be rejected via -ENOTEMPTY, not -EEXIST,
    so userspace / nft can report an error to the user.

    The latter is only correct for the 2nd case (re-add of existing element).

    As-is, userspace is told that the command was successful, but no elements were
    added.

    After this patch, 3rd command gives:
    Error: Could not process rule: File exists
    add element t s { "lo" . 127.0.0.0/8 . "lo"  : drop }
                      ^^^^^^^^^^^^^^^^^^^^^^^^^

    Fixes: 0eb4b5ee33f2 ("netfilter: nft_set_pipapo: Separate partial and complete overlap cases on insertion")
    Signed-off-by: Florian Westphal <fw@strlen.de>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>