ALSA: hda/tas2781: select CONFIG_CRC8 for SND_HDA_SCODEC_TAS2781_I2C
JIRA: https://issues.redhat.com/browse/RHEL-112757

commit f0ccc717c6c64b0762f34cd1a2072bff44859423
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon May 5 07:21:21 2025 +0200

    ALSA: hda/tas2781: select CONFIG_CRC8 for SND_HDA_SCODEC_TAS2781_I2C

    The crc8 function is used by the common fmwlib module, so this has
    to be selected directly to avoid a link failure:

    ERROR: modpost: "crc8" [sound/soc/codecs/snd-soc-tas2781-fmwlib.ko] undefined!

    Fixes: 9fa6a693ad8d ("ALSA: hda/tas2781: Remove tas2781_spi_fwlib.c and leverage SND_SOC_TAS2781_FMWLIB")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20250505052303.1812002-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>