perf: arm_pmuv3: Include asm/arm_pmuv3.h from linux/perf/arm_pmuv3.h
JIRA: https://issues.redhat.com/browse/RHEL-5704

commit d688ffa269421cec73c7e13fd0cb03879b07db89
Author: "Rob Herring (Arm)" <robh@kernel.org>
Date: Wed, 26 Jun 2024 16:32:29 -0600

    The arm64 asm/arm_pmuv3.h depends on defines from
    linux/perf/arm_pmuv3.h. Rather than depend on include order, follow the
    usual pattern of "linux" headers including "asm" headers of the same
    name.

    With this change, the include of linux/kvm_host.h is problematic due to
    circular includes:

    In file included from ../arch/arm64/include/asm/arm_pmuv3.h:9,
                     from ../include/linux/perf/arm_pmuv3.h:312,
                     from ../include/kvm/arm_pmu.h:11,
                     from ../arch/arm64/include/asm/kvm_host.h:38,
                     from ../arch/arm64/mm/init.c:41:
    ../include/linux/kvm_host.h:383:30: error: field 'arch' has incomplete type

    Switching to asm/kvm_host.h solves the issue.

    Signed-off-by: Rob Herring (Arm) <robh@kernel.org>
    Link: https://lore.kernel.org/r/20240626-arm-pmu-3-9-icntr-v2-5-c9784b4f4065@kernel.org
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>