perf build: Don't use -ffat-lto-objects in the python feature test when building with clang-13
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit 3a8a0475861a443f02e3a9b57d044fe2a0a99291
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Apr 7 11:04:20 2022 -0300

description
===========
Using -ffat-lto-objects in the python feature test when building with
clang-13 results in:

  clang-13: error: optimization flag '-ffat-lto-objects' is not supported [-Werror,-Wignored-optimization-argument]
  error: command '/usr/sbin/clang' failed with exit code 1
  cp: cannot stat '/tmp/build/perf/python_ext_build/lib/perf*.so': No such file or directory
  make[2]: *** [Makefile.perf:639: /tmp/build/perf/python/perf.so] Error 1

Noticed when building on a docker.io/library/archlinux:base container.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>