bridge: mcast: fix br_multicast_dev_del warn when igmp snooping is not defined
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Nikolay Aleksandrov <razor@blackwall.org>
commit a7ce45a74bedd0ed80b956b3e14f8bc6dec85327

Fix:
net/bridge/br_if.c: In function 'br_dev_delete':
>> net/bridge/br_if.c:284:2: error: implicit declaration of function
>> 'br_multicast_dev_del' [-Werror=implicit-function-declaration]
     br_multicast_dev_del(br);
     ^
   cc1: some warnings being treated as errors

when igmp snooping is not defined.

	Signed-off-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit a7ce45a74bedd0ed80b956b3e14f8bc6dec85327)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>