nfsd: avoid uninitialized variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 0ab88ca4bcf18ba21058d8f19220f60afe0d34d8

clang warns that 'contextlen' may be accessed without an initialization:

fs/nfsd/nfs4xdr.c:2911:9: error: variable 'contextlen' is uninitialized when used here [-Werror,-Wuninitialized]
                                                                contextlen);
                                                                ^~~~~~~~~~
fs/nfsd/nfs4xdr.c:2424:16: note: initialize the variable 'contextlen' to silence this warning
        int contextlen;
                      ^
                       = 0

Presumably this cannot happen, as FATTR4_WORD2_SECURITY_LABEL is
set if CONFIG_NFSD_V4_SECURITY_LABEL is enabled.
Adding another #ifdef like the other two in this function
avoids the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: J. Bruce Fields <bfields@redhat.com>
(cherry picked from commit 0ab88ca4bcf18ba21058d8f19220f60afe0d34d8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>