ata: Kconfig: fix sata gemini compile test condition
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2042790

When compile testing the sata gemini driver, CONFIG_OF is required to
avoid the warning:

drivers/ata/sata_gemini.c:421:34: error: ‘gemini_sata_of_match’ defined
but not used [-Werror=unused-const-variable=]

Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
(cherry picked from commit f7220eac752f2c96a1b6e0830cbf427ca908e511)
Signed-off-by: Tomas Henzl <thenzl@redhat.com>