i3c: simplify combined i3c/i2c dependencies
JIRA: https://issues.redhat.com/browse/RHEL-168906

Conflicts:
 * drivers/hwmon/Kconfig
 * drivers/iio/magnetometer/Kconfig
 * drivers/misc/amd-sbi/Kconfig

The upstream patch both introduces config I3C_OR_I2C and updates
Kconfig to make four drivers use it: SENSORS_LM75, SENSORS_TMP108,
MMC5633, and AMD_SBRMI_I2C.

MMC5633 and AMD_SBRMI_I2C don't exist in c10s while SENSORS_LM75 and
SENSORS_TMP108 don't have I3C support backported in c10s. This backport
simply introduces the new I3C_OR_I2C config without changing the
dependencies of any existing driver.

commit 663eb8763c251dbcd0536b14ec134e63e4173348
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed, 4 Feb 2026 17:41:58 +0100

    i3c: simplify combined i3c/i2c dependencies

    All combined i2c/i3c drivers appear to suffer from the same link
    time problem when CONFIG_I3C is set to 'm':

    arm-linux-gnueabi-ld: drivers/iio/magnetometer/mmc5633.o: in function `mmc5633_i3c_driver_init':
    mmc5633.c:(.init.text+0x30): undefined reference to `i3c_driver_register_with_owner'

    This was previously fixed every time by marking individual
    drivers as 'depends on I2C; depends on I3C || !I3C', but this gets
    tedious and is somewhat confusing.

    Add a Kconfig symbol 'I3C_OR_I2C' to help replace those dependencies,
    and use this in all the existing drivers that had already fixed it
    as well as the new mmc5633 driver.

    Reviewed-by: Jonathan Cameron <jonathan.cameron@huawei.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Guenter Roeck <linux@roeck-us.net>
    Acked-by: Jonathan Cameron <jonathan.cameron@huawei.com>
    Link: https://patch.msgid.link/20260204164216.544409-1-arnd@kernel.org
    Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>

Signed-off-by: Jennifer Berringer <jberring@redhat.com>