ASoC: cs35l45: Select REGMAP_IRQ
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit d9ba2975e98a4bec0a9f8d4be4c1de8883fccb71
Author: Nathan Chancellor <nathan@kernel.org>
Date: Mon Jul 3 14:43:15 2023 -0700

    ASoC: cs35l45: Select REGMAP_IRQ

    After commit 6085f9e6dc19 ("ASoC: cs35l45: IRQ support"), without any
    other configuration that selects CONFIG_REGMAP_IRQ, modpost errors out
    with:

      ERROR: modpost: "regmap_irq_get_virq" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
      ERROR: modpost: "devm_regmap_add_irq_chip" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!

    Add the Kconfig selection to ensure these functions get built and
    included, which resolves the build failure.

    Cc: stable@vger.kernel.org
    Fixes: 6085f9e6dc19 ("ASoC: cs35l45: IRQ support")
    Reported-by: Marcus Seyfarth <m.seyfarth@gmail.com>
    Closes: https://github.com/ClangBuiltLinux/linux/issues/1882
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20230703-cs35l45-select-regmap_irq-v1-1-37d7e838b614@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>