ASoC: qcom: Select missing common Soundwire module code on SDM845
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit b930d8647869802a0d430aae6b1b05c3acb24a41
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Sat Oct 12 12:09:57 2024 +0200

    ASoC: qcom: Select missing common Soundwire module code on SDM845

    SDM845 sound card driver uses qcom_snd_sdw_startup() from the common
    Soundwire module, so select it to fix build failures:

      ERROR: modpost: "qcom_snd_sdw_startup" [sound/soc/qcom/snd-soc-sdm845.ko] undefined!

    Fixes: d0e806b0cc62 ("ASoC: qcom: sdm845: add missing soundwire runtime stream alloc")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://patch.msgid.link/20241012100957.129103-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>