usb: typec: ucsi: yoga-c630: add DRM dependency
JIRA: https://issues.redhat.com/browse/RHEL-122021

commit a33665facf792de619e451bdbf66e86b9c6763bc
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu, 17 Jul 2025 15:30:41 +0200

  Selecting DRM_AUX_HPD_BRIDGE is not possible from a built-in driver when
  CONFIG_DRM=m:

  WARNING: unmet direct dependencies detected for DRM_AUX_HPD_BRIDGE
    Depends on [m]: HAS_IOMEM [=y] && DRM [=m] && DRM_BRIDGE [=y] && OF [=y]
    Selected by [y]:
    - UCSI_LENOVO_YOGA_C630 [=y] && USB_SUPPORT [=y] && TYPEC [=y] && TYPEC_UCSI [=y] && EC_LENOVO_YOGA_C630 [=y] && DRM_BRIDGE [=y] && OF [=y]
  arm-linux-gnueabi-ld: drivers/gpu/drm/bridge/aux-hpd-bridge.o: in function `drm_aux_hpd_bridge_notify':
  aux-hpd-bridge.c:(.text.drm_aux_hpd_bridge_notify+0x28): undefined reference to `drm_bridge_hpd_notify'
  arm-linux-gnueabi-ld: drivers/gpu/drm/bridge/aux-hpd-bridge.o: in function `drm_aux_hpd_bridge_probe':
  aux-hpd-bridge.c:(.text.drm_aux_hpd_bridge_probe+0x20): undefined reference to `__devm_drm_bridge_alloc'

  Add a dependency to force UCSI_LENOVO_YOGA_C630 to be a loadable module as
  well in this configuration.

  Fixes: eb90d36bfa06 ("usb: typec: ucsi: yoga-c630: register DRM HPD bridge")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
  Link: https://lore.kernel.org/r/20250717133045.991254-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>