ASoC: rt5677: Fix build error without CONFIG_SPI
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: rt5677: Fix build error without CONFIG_SPI (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.12%
commit-author YueHaibing <yuehaibing@huawei.com>
commit fb3194413d1ef79732931a40f54da21a16505a76

If CONFIG_SPI is n, SND_SOC_RT5677_SPI also is n, building fails:

sound/soc/codecs/rt5677.o: In function `rt5677_irq':
rt5677.c:(.text+0x2dbf): undefined reference to `rt5677_spi_hotword_detected'
sound/soc/codecs/rt5677.o: In function `rt5677_dsp_work':
rt5677.c:(.text+0x3709): undefined reference to `rt5677_spi_write'

This adds stub helpers to fix this.

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 461c623270e4 ("ASoC: rt5677: Load firmware via SPI using delayed work")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Link: https://lore.kernel.org/r/20191127082145.6100-1-yuehaibing@huawei.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit fb3194413d1ef79732931a40f54da21a16505a76)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>