io_uring: fix two assignments in if conditions
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2068237

commit df730ec21f7ba395b1b22e7f93a3a85b1d1b7882
Author: Xinghui Li <korantli@tencent.com>
Date:   Wed Nov 2 16:25:03 2022 +0800

    io_uring: fix two assignments in if conditions
    
    Fixes two errors:
    
    "ERROR: do not use assignment in if condition
    130: FILE: io_uring/net.c:130:
    +       if (!(issue_flags & IO_URING_F_UNLOCKED) &&
    
    ERROR: do not use assignment in if condition
    599: FILE: io_uring/poll.c:599:
    +       } else if (!(issue_flags & IO_URING_F_UNLOCKED) &&"
    reported by checkpatch.pl in net.c and poll.c .
    
    Signed-off-by: Xinghui Li <korantli@tencent.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/r/20221102082503.32236-1-korantwork@gmail.com
    [axboe: style tweaks]
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>