crypto: tegra - Fix format specifier in tegra_sha_prep_cmd()
JIRA: https://issues.redhat.com/browse/RHEL-89531
Upstream Status: linux.git

commit 795e5bdb0ada2c77ea28611d88f1d5d7ca9b2f4d
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Thu Mar 13 16:29:31 2025 +0100

    crypto: tegra - Fix format specifier in tegra_sha_prep_cmd()

    When building for 32-bit targets, for which ssize_t is 'int' instead of
    'long', there is a warning due to an incorrect format specifier:

      In file included from include/linux/printk.h:610,
                       from include/linux/kernel.h:31,
                       from include/linux/clk.h:13,
                       from drivers/crypto/tegra/tegra-se-hash.c:7:
      drivers/crypto/tegra/tegra-se-hash.c: In function 'tegra_sha_prep_cmd':
      drivers/crypto/tegra/tegra-se-hash.c:343:26: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'ssize_t' {aka 'int'} [-Werror=format=]
        343 |         dev_dbg(se->dev, "msg len %llu msg left %llu sz %lu cfg %#x",
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ...
      drivers/crypto/tegra/tegra-se-hash.c:343:59: note: format string is defined here
        343 |         dev_dbg(se->dev, "msg len %llu msg left %llu sz %lu cfg %#x",
            |                                                         ~~^
            |                                                           |
            |                                                           long unsigned int
            |                                                         %u
      cc1: all warnings being treated as errors

    Use '%zd', the proper specifier for ssize_t, to resolve the warning.

    Fixes: ff4b7df0b511 ("crypto: tegra - Fix HASH intermediate result handling")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Herbert Xu <herbert.xu@redhat.com>