usb: hide unused usbfs_notify_suspend/resume functions
JIRA: https://issues.redhat.com/browse/RHEL-15948

commit 8e6bd945e6dde64fbc60ec3fe252164493a8d3a2
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 22:17:42 +0200

  The declaration is in an #ifdef, which causes warnings when building
  with 'make W=1' and without CONFIG_PM:

  drivers/usb/core/devio.c:742:6: error: no previous prototype for 'usbfs_notify_suspend'
  drivers/usb/core/devio.c:747:6: error: no previous prototype for 'usbfs_notify_resume'

  Use the same #ifdef check around the function definitions to avoid
  the warnings and slightly shrink the USB core.

  Fixes: 7794f486ed0b ("usbfs: Add ioctls for runtime power management")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Sebastian Reichel <sebastian.reichel@collabora.com>
  Acked-by: Alan Stern <stern@rowland.harvard.edu>
  Link: https://lore.kernel.org/r/20230516202103.558301-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>