usb: host: ehci.h: move pointer operator to name side
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] host: ehci.h: move pointer operator to name side (Torez Smith) [1332712]
Rebuild_FUZZ: 95.05%
commit-author Geyslan G. Bem <geyslan@gmail.com>
commit c021170f1da3448d398614b6bc546f3dee256979

The pointer operator must be sticked to name.

Caught by checkpatch:
ERROR: "foo * bar" should be "foo *bar"

	Signed-off-by: Geyslan G. Bem <geyslan@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit c021170f1da3448d398614b6bc546f3dee256979)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>