lib: Fix ia64 bootloader linkage
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Alexander Shishkin <alexander.shishkin@linux.intel.com>
commit 93048c0944150b316a15f92c41a4d626c8df37fd
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-358.el8/93048c09.failed

kbuild robot reports that since commit ce76d938dd98 ("lib: Add memcat_p():
paste 2 pointer arrays together") the ia64/hp/sim/boot fails to link:

> LD      arch/ia64/hp/sim/boot/bootloader
> lib/string.o: In function `__memcat_p':
> string.c:(.text+0x1f22): undefined reference to `__kmalloc'
> string.c:(.text+0x1ff2): undefined reference to `__kmalloc'
> make[1]: *** [arch/ia64/hp/sim/boot/Makefile:37: arch/ia64/hp/sim/boot/bootloader] Error 1

The reason is, the above commit, via __memcat_p(), adds a call to
__kmalloc to string.o, which happens to be used in the bootloader, but
there's no kmalloc or slab or anything.

Since the linker would only pull in objects that contain referenced
symbols, moving __memcat_p() to a different compilation unit solves the
problem.

Fixes: ce76d938dd98 ("lib: Add memcat_p(): paste 2 pointer arrays together")
	Signed-off-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Reported-by: kbuild test robot <lkp@intel.com>
	Cc: Fenghua Yu <fenghua.yu@intel.com>
	Cc: Tony Luck <tony.luck@intel.com>
	Cc: Joe Perches <joe@perches.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 93048c0944150b316a15f92c41a4d626c8df37fd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	lib/Makefile