PCI: Drop of_match_ptr() to avoid unused variables
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2124638
Upstream Status: 1dff012f636d4440f2f99256c09c5b6bfacf7552

commit 1dff012f636d4440f2f99256c09c5b6bfacf7552
Author: Bjorn Helgaas <bhelgaas@google.com>
Date:   Wed Jul 6 14:27:21 2022 -0500

    PCI: Drop of_match_ptr() to avoid unused variables

    We have stubs for most OF interfaces even when CONFIG_OF is not set, so we
    allow building of most controller drivers in that case for compile testing.

    When CONFIG_OF is not set, "of_match_ptr(<match_table>)" compiles to NULL,
    which leaves <match_table> unused, resulting in errors like this:

      $ make W=1
      drivers/pci/controller/pci-xgene.c:636:34: error: ‘xgene_pcie_match_table’ defined but not used [-Werror=unused-const-variable=]

    Drop of_match_ptr() to avoid the unused variable warning.

    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>