ptp: fix code indentation issues
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2066451
Upstream Status: net.git commit 11195bf5a355

commit 11195bf5a355a5ef048e690f12b90b70b2c42a86
Author: Carlos Llamas <cmllamas@google.com>
Date:   Wed Oct 27 23:18:02 2021 +0000

    ptp: fix code indentation issues

    This fixes the following checkpatch.pl errors:

    ERROR: code indent should use tabs where possible
    +^I        if (ptp->pps_source)$

    ERROR: code indent should use tabs where possible
    +^I                pps_unregister_source(ptp->pps_source);$

    ERROR: code indent should use tabs where possible
    +^I                kthread_destroy_worker(ptp->kworker);$

    Fixes: 4225fea1cb28 ("ptp: Fix possible memory leak in ptp_clock_register()")
    Signed-off-by: Carlos Llamas <cmllamas@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Hangbin Liu <haliu@redhat.com>