powerpc/kdump: Fix powernv build break when KEXEC_CORE=n
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [powerpc] kdump: Fix powernv build break when KEXEC_CORE=n (Desnes Augusto Nunes do Rosario) [1559434]
Rebuild_FUZZ: 92.31%
commit-author Guenter Roeck <linux@roeck-us.net>
commit 910961754572a2f4c83ad7e610d180e3e6c29bda
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/91096175.failed

If KEXEC_CORE is not enabled, powernv builds fail as follows.

  arch/powerpc/platforms/powernv/smp.c: In function 'pnv_smp_cpu_kill_self':
  arch/powerpc/platforms/powernv/smp.c:236:4: error:
  	implicit declaration of function 'crash_ipi_callback'

Add dummy function calls, similar to kdump_in_progress(), to solve the
problem.

Fixes: 4145f358644b ("powernv/kdump: Fix cases where the kdump kernel can get HMI's")
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Acked-by: Balbir Singh <bsingharora@gmail.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 910961754572a2f4c83ad7e610d180e3e6c29bda)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/include/asm/kexec.h