usb: typec: tcpm: Fix undefined behavior due to shift overflowing the constant
Bugzilla: http://bugzilla.redhat.com/2084667
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46653455
Tested: HP ZBook 15 G5/80D5 Laptop

commit 8d084b2eae7fc5fcfc9f143cd7321a88e1cd76aa
Author: Borislav Petkov <bp@suse.de>
Date:   Tue Apr 5 17:15:13 2022 +0200

    usb: typec: tcpm: Fix undefined behavior due to shift overflowing the constant

    Fix:

      drivers/usb/typec/tcpm/tcpm.c: In function ‘run_state_machine’:
      drivers/usb/typec/tcpm/tcpm.c:4724:3: error: case label does not reduce to an integer constant
         case BDO_MODE_TESTDATA:
         ^~~~

    See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
    details as to why it triggers with older gccs only.

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: linux-usb@vger.kernel.org
    Link: https://lore.kernel.org/r/20220405151517.29753-8-bp@alien8.de
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>