perf probe: Cut off the version suffix from event name
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit a3110cd9d0f77a796da545e112f9305094257798

Cut off the version suffix (e.g. @GLIBC_2.2.5 etc.) from automatic
generated event name. This fixes wildcard event adding like below case;

  =====
  # perf probe -x /lib64/libc-2.25.so malloc*
  Internal error: "malloc_get_state@GLIBC_2" is wrong event name.
    Error: Failed to add events.
  =====

This failure was caused by a versioned suffix symbol.

With this fix, perf probe automatically cuts the suffix after @ as
below.

  =====
  # ./perf probe -x /lib64/libc-2.25.so malloc*
  Added new events:
    probe_libc:malloc_printerr (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_consolidate (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_check (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_hook_ini (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc    (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_trim (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_usable_size (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_stats (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_info (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:mallochook (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_get_state (on malloc* in /usr/lib64/libc-2.25.so)
    probe_libc:malloc_set_state (on malloc* in /usr/lib64/libc-2.25.so)

  You can now use it in all perf tools, such as:

	  perf record -e probe_libc:malloc_set_state -aR sleep 1

  =====

	Reported-by: Arnaldo Carvalho de Melo <acme@kernel.org>
	Reported-by: bhargavb <bhargavaramudu@gmail.com>
	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Acked-by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
	Reviewed-by: Thomas Richter <tmricht@linux.vnet.ibm.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Paul Clarke <pc@us.ibm.com>
	Cc: linux-rt-users@vger.kernel.org
Link: http://lkml.kernel.org/r/None
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit a3110cd9d0f77a796da545e112f9305094257798)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>