ublk: prevent invalid access with DEBUG
JIRA: https://issues.redhat.com/browse/RHEL-144763

commit c6a45ee7607de3a350008630f4369b1b5ac80884
Author: Kevin Brodsky <kevin.brodsky@arm.com>
Date:   Wed Nov 26 12:48:35 2025 +0000

    ublk: prevent invalid access with DEBUG

    ublk_ch_uring_cmd_local() may jump to the out label before
    initialising the io pointer. This will cause trouble if DEBUG is
    defined, because the pr_devel() call dereferences io. Clang reports:

    drivers/block/ublk_drv.c:2403:6: error: variable 'io' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
     2403 |         if (tag >= ub->dev_info.queue_depth)
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/block/ublk_drv.c:2492:32: note: uninitialized use occurs here
     2492 |                         __func__, cmd_op, tag, ret, io->flags);
          |

    Fix this by initialising io to NULL and checking it before
    dereferencing it.

    Signed-off-by: Kevin Brodsky <kevin.brodsky@arm.com>
    Fixes: 71f28f3136af ("ublk_drv: add io_uring based userspace block driver")
    Reviewed-by: Caleb Sander Mateos <csander@purestorage.com>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>