mptcp: Fix incorrect IPV6 dependency check
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 8e1974a2a02bf5b77831c686f01761163ea0cd3e

If CONFIG_MPTCP=y, CONFIG_MPTCP_IPV6=n, and CONFIG_IPV6=m:

    net/mptcp/protocol.o: In function `__mptcp_tcp_fallback':
    protocol.c:(.text+0x786): undefined reference to `inet6_stream_ops'

Fix this by checking for CONFIG_MPTCP_IPV6 instead of CONFIG_IPV6, like
is done in all other places in the mptcp code.

Fixes: 8ab183deb26a3b79 ("mptcp: cope with later TCP fallback")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Reviewed-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8e1974a2a02bf5b77831c686f01761163ea0cd3e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>