kexec: fix KEXEC_FILE dependencies
JIRA: https://issues.redhat.com/browse/RHEL-58641

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

Conflicts: There's conflict in power because of fuzz, and discard the
           risc-v part of change.

commit c1ad12ee0efc07244be37f69311e6f7c4ac98e62
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 23 13:01:54 2023 +0200

    kexec: fix KEXEC_FILE dependencies

    The cleanup for the CONFIG_KEXEC Kconfig logic accidentally changed the
    'depends on CRYPTO=y' dependency to a plain 'depends on CRYPTO', which
    causes a link failure when all the crypto support is in a loadable module
    and kexec_file support is built-in:

    x86_64-linux-ld: vmlinux.o: in function `__x64_sys_kexec_file_load':
    (.text+0x32e30a): undefined reference to `crypto_alloc_shash'
    x86_64-linux-ld: (.text+0x32e58e): undefined reference to `crypto_shash_update'
    x86_64-linux-ld: (.text+0x32e6ee): undefined reference to `crypto_shash_final'

    Both s390 and x86 have this problem, while ppc64 and riscv have the
    correct dependency already.  On riscv, the dependency is only used for the
    purgatory, not for the kexec_file code itself, which may be a bit
    surprising as it means that with CONFIG_CRYPTO=m, it is possible to enable
    KEXEC_FILE but then the purgatory code is silently left out.

    Move this into the common Kconfig.kexec file in a way that is correct
    everywhere, using the dependency on CRYPTO_SHA256=y only when the
    purgatory code is available.  This requires reversing the dependency
    between ARCH_SUPPORTS_KEXEC_PURGATORY and KEXEC_FILE, but the effect
    remains the same, other than making riscv behave like the other ones.

    On s390, there is an additional dependency on CRYPTO_SHA256_S390, which
    should technically not be required but gives better performance.  Remove
    this dependency here, noting that it was not present in the initial
    Kconfig code but was brought in without an explanation in commit
    71406883fd357 ("s390/kexec_file: Add kexec_file_load system call").

    [arnd@arndb.de: fix riscv build]
      Link: https://lkml.kernel.org/r/67ddd260-d424-4229-a815-e3fcfb864a77@app.fastmail.com
    Link: https://lkml.kernel.org/r/20231023110308.1202042-1-arnd@kernel.org
    Fixes: 6af5138083005 ("x86/kexec: refactor for kernel/Kconfig.kexec")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Eric DeVolder <eric_devolder@yahoo.com>
    Tested-by: Eric DeVolder <eric_devolder@yahoo.com>
    Cc: Albert Ou <aou@eecs.berkeley.edu>
    Cc: Alexander Gordeev <agordeev@linux.ibm.com>
    Cc: Ard Biesheuvel <ardb@kernel.org>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Christian Borntraeger <borntraeger@linux.ibm.com>
    Cc: Christophe Leroy <christophe.leroy@csgroup.eu>
    Cc: Conor Dooley <conor@kernel.org>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>
    Cc: David S. Miller <davem@davemloft.net>
    Cc: Heiko Carstens <hca@linux.ibm.com>
    Cc: Herbert Xu <herbert@gondor.apana.org.au>
    Cc: "H. Peter Anvin" <hpa@zytor.com>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Nicholas Piggin <npiggin@gmail.com>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Paul Walmsley <paul.walmsley@sifive.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Sven Schnelle <svens@linux.ibm.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Vasily Gorbik <gor@linux.ibm.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Baoquan He <bhe@redhat.com>