drm/amd/display: fix i386 frame size warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2184097
Conflicts: This commit conflicts with upstream v6.0 commit 41012d715d5d
	   ("drm/amd/display: Mark dml30's UseMinimumDCFCLK() as noinline
	   for stack usage"). The v6.1 branch does not have commit
	   41012d715d5d but a similar commit b0f4b23fc3db on top of this.
	   I have to revert commit 41012d715d5d and then apply this commit
	   followed by commit b0f4b23fc3db.

commit a0f7e7f759cf299ee6f6d8723c596af9a1a86b10
Author: Hamza Mahfooz <hamza.mahfooz@amd.com>
Date:   Wed, 17 Aug 2022 12:03:51 -0400

    drm/amd/display: fix i386 frame size warning

    Addresses the following warning:
    drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn30/display_mode_vba_30.c:3596:6: error: stack frame size (2092) exceeds limit (2048) in 'dml30_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
    void dml30_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
         ^

    UseMinimumDCFCLK() is eating away at
    dml30_ModeSupportAndSystemConfigurationFull()'s stack space, so use a
    pointer to struct vba_vars_st instead of passing lots of large arrays
    as parameters by value.

    Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

Signed-off-by: Waiman Long <longman@redhat.com>