ahci, msix: Fix build error for !PCI_MSI
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Robert Richter <robert.richter@caviumnetworks.com>
commit 34c56932ce5278b8bbae13936f9df05cd59e3193

It turned out the irq vector of the msix can be obtained from struct
msix_entry. This makes the lookup function for msi_desc obsolete.

This fixes a build error if PCI_MSI is unset:

 drivers/ata/ahci.c: In function ‘msix_get_desc’:
 drivers/ata/ahci.c:1210:2: error: ‘struct pci_dev’ has no member named ‘msi_list’

Catched by Fengguang's build bot.

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Robert Richter <rrichter@cavium.com>
	Signed-off-by: Tejun Heo <tj@kernel.org>
(cherry picked from commit 34c56932ce5278b8bbae13936f9df05cd59e3193)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>