Revert "KEYS: verify a certificate is signed by a 'trusted' key"
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [crypto] Revert: keys: verify a certificate is signed by a 'trusted' key (Vivek Goyal) [1129779]
Rebuild_FUZZ: 96.12%
commit-author Linus Torvalds <torvalds@linux-foundation.org>
commit 4c1cc40a2d49500d84038ff751bc6cd183e729b5

This reverts commit 09fbc47373826d67531380662b516de2da120545, which
caused the following build errors:

  crypto/asymmetric_keys/x509_public_key.c: In function ‘x509_key_preparse’:
  crypto/asymmetric_keys/x509_public_key.c:237:35: error: ‘system_trusted_keyring’ undeclared (first use in this function)
   ret = x509_validate_trust(cert, system_trusted_keyring);
                                   ^
  crypto/asymmetric_keys/x509_public_key.c:237:35: note: each undeclared identifier is reported only once for each function it appears in

reported by Jim Davis. Mimi says:

 "I made the classic mistake of requesting this patch to be upstreamed
  at the last second, rather than waiting until the next open window.

  At this point, the best course would probably be to revert the two
  commits and fix them for the next open window"

	Reported-by: Jim Davis <jim.epost@gmail.com>
	Acked-by: Mimi Zohar <zohar@linux.vnet.ibm.com>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 4c1cc40a2d49500d84038ff751bc6cd183e729b5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>