RDMA/cxgb4: Add a sanity check in process_work()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit ccc04cdd55d8cfa7376ba96a037ba0f1b3df33c7

The story is that Smatch marks skb->data as untrusted so it generates
a warning message here:

    drivers/infiniband/hw/cxgb4/cm.c:4100 process_work()
    error: buffer overflow 'work_handlers' 241 <= 255

In other places which handle this such as t4_uld_rx_handler() there is
some checking to make sure that the function pointer is not NULL.  I
have added bounds checking and a check for NULL here as well.

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Acked-by: Steve Wise <swise@opengridcomputing.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit ccc04cdd55d8cfa7376ba96a037ba0f1b3df33c7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>