ASoC: amd: Add ACPI dependency to fix build error
JIRA: https://issues.redhat.com/browse/RHEL-80677

commit 7e24ec93aecd12e33d31e38e5af4625553bbc727
Author: Yu-Chun Lin <eleanor15x@gmail.com>
Date: Fri Jan 10 01:15:47 2025 +0800

    ASoC: amd: Add ACPI dependency to fix build error

    As reported by the kernel test robot, the following error occurs:

       sound/soc/amd/yc/acp6x-mach.c: In function 'acp6x_probe':
    >> sound/soc/amd/yc/acp6x-mach.c:573:15: error: implicit declaration of function 'acpi_evaluate_integer'; did you mean 'acpi_evaluate_object'? [-Werror=implicit-function-declaration]
         573 |         ret = acpi_evaluate_integer(handle, "_WOV", NULL, &dmic_status);
             |               ^~~~~~~~~~~~~~~~~~~~~
             |               acpi_evaluate_object
       cc1: some warnings being treated as errors

    The function 'acpi_evaluate_integer' and its prototype in 'acpi_bus.h'
    are only available when 'CONFIG_ACPI' is enabled. Add a 'depends on ACPI'
    directive in Kconfig to ensure proper compilation.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202501090345.pBIDRTym-lkp@intel.com/
    Signed-off-by: Yu-Chun Lin <eleanor15x@gmail.com>
    Link: https://patch.msgid.link/20250109171547.362412-1-eleanor15x@gmail.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>