serial: sprd: Drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit 5406dc04884b96b8438b664d1a9b73e30e2a5517
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Mar 10 23:29:57 2023 +0100

    serial: sprd: Drop of_match_ptr for ID table

    The driver can match only via the DT table so the table should be always
    used and the of_match_ptr does not have any sense (this also allows ACPI
    matching via PRP0001, even though it is not relevant here).

      drivers/tty/serial/sprd_serial.c:1242:34: error: ‘serial_ids’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Baolin Wang <baolin.wang@linux.alibaba.com>
    Link: https://lore.kernel.org/r/20230310222957.315848-2-krzysztof.kozlowski@linaro.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>