block: rsxx: select CONFIG_CRC32
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 36a106a4c1c100d55ba3d32a21ef748cfcd4fa99

Without crc32, the driver fails to link:

arm-linux-gnueabi-ld: drivers/block/rsxx/config.o: in function `rsxx_load_config':
config.c:(.text+0x124): undefined reference to `crc32_le'

Fixes: 8722ff8cdbfa ("block: IBM RamSan 70/80 device driver")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit 36a106a4c1c100d55ba3d32a21ef748cfcd4fa99)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>