ia64: make IA64_MCA_RECOVERY bool instead of tristate
Bugzilla: https://bugzilla.redhat.com/2120352

commit dbecf9b8b8ce580f4e11afed9d61e8aa294cddd2
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Jan 29 13:40:58 2022 -0800

    ia64: make IA64_MCA_RECOVERY bool instead of tristate

    In linux-next, IA64_MCA_RECOVERY uses the (new) function
    make_task_dead(), which is not exported for use by modules.  Instead of
    exporting it for one user, convert IA64_MCA_RECOVERY to be a bool
    Kconfig symbol.

    In a config file from "kernel test robot <lkp@intel.com>" for a
    different problem, this linker error was exposed when
    CONFIG_IA64_MCA_RECOVERY=m.

    Fixes this build error:

      ERROR: modpost: "make_task_dead" [arch/ia64/kernel/mca_recovery.ko] undefined!

    Link: https://lkml.kernel.org/r/20220124213129.29306-1-rdunlap@infradead.org
    Fixes: 0e25498f8cd4 ("exit: Add and use make_task_dead.")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Suggested-by: Christoph Hellwig <hch@infradead.org>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: "Eric W. Biederman" <ebiederm@xmission.com>
    Cc: Tony Luck <tony.luck@intel.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>