ASoC: rt5682: Fix build error without CONFIG_I2C
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: rt5682: Fix build error without CONFIG_I2C (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.12%
commit-author YueHaibing <yuehaibing@huawei.com>
commit 59564e117356d5bb6df6876c03d7d650361781c9

If I2C is n but SoundWire is m, building fails:

sound/soc/codecs/rt5682.c:3716:1: warning: data definition has no type or storage class
 module_i2c_driver(rt5682_i2c_driver);
 ^~~~~~~~~~~~~~~~~
sound/soc/codecs/rt5682.c:3716:1: error: type defaults to 'int' in declaration of 'module_i2c_driver' [-Werror=implicit-int]
sound/soc/codecs/rt5682.c:3716:1: warning: parameter names (without types) in function declaration

Guard this use #ifdef CONFIG_I2C.

Fixes: 5549ea647997 ("ASoC: rt5682: fix unmet dependencies")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Link: https://lore.kernel.org/r/20200401091055.34112-1-yuehaibing@huawei.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 59564e117356d5bb6df6876c03d7d650361781c9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>