ASoC: max98988: add I2C dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: max98988: add I2C dependency (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 91.89%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 9641faa2db7e856f50a6d1169e1b9f01e7fcb2b0

max98988 only builds with I2C support enabled, otherwise we get a build error:

sound/soc/codecs/max98088.c:1789:1: error: data definition has no type or storage class [-Werror]
 module_i2c_driver(max98088_i2c_driver);
 ^~~~~~~~~~~~~~~~~
sound/soc/codecs/max98088.c:1789:1: error: type defaults to 'int' in declaration of 'module_i2c_driver' [-Werror=implicit-int]
sound/soc/codecs/max98088.c:1789:1: error: parameter names (without types) in function declaration [-Werror]
sound/soc/codecs/max98088.c:1780:26: error: 'max98088_i2c_driver' defined but not used [-Werror=unused-variable]

Fixes: 24ae67c58250 ("ASoC: max98988: make it selectable")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Marco Felsch <m.felsch@pengutronix.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9641faa2db7e856f50a6d1169e1b9f01e7fcb2b0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>