netfilter: nf_reject: Fix build warning when CONFIG_BRIDGE_NETFILTER=n
JIRA: https://issues.redhat.com/browse/RHEL-66865
CVE: CVE-2024-50256

commit fc56878ca1c288e49b5cbb43860a5938e3463654
Author: Simon Horman <horms@kernel.org>
Date:   Mon Sep 16 10:50:34 2024 +0100

    netfilter: nf_reject: Fix build warning when CONFIG_BRIDGE_NETFILTER=n

    If CONFIG_BRIDGE_NETFILTER is not enabled, which is the case for x86_64
    defconfig, then building nf_reject_ipv4.c and nf_reject_ipv6.c with W=1
    using gcc-14 results in the following warnings, which are treated as
    errors:

    net/ipv4/netfilter/nf_reject_ipv4.c: In function 'nf_send_reset':
    net/ipv4/netfilter/nf_reject_ipv4.c:243:23: error: variable 'niph' set but not used [-Werror=unused-but-set-variable]
      243 |         struct iphdr *niph;
          |                       ^~~~
    cc1: all warnings being treated as errors
    net/ipv6/netfilter/nf_reject_ipv6.c: In function 'nf_send_reset6':
    net/ipv6/netfilter/nf_reject_ipv6.c:286:25: error: variable 'ip6h' set but not used [-Werror=unused-but-set-variable]
      286 |         struct ipv6hdr *ip6h;
          |                         ^~~~
    cc1: all warnings being treated as errors

    Address this by reducing the scope of these local variables to where
    they are used, which is code only compiled when CONFIG_BRIDGE_NETFILTER
    enabled.

    Compile tested and run through netfilter selftests.

    Reported-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Closes: https://lore.kernel.org/netfilter-devel/20240906145513.567781-1-andriy.shevchenko@linux.intel.com/
    Signed-off-by: Simon Horman <horms@kernel.org>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: CKI Backport Bot <cki-ci-bot+cki-gitlab-backport-bot@redhat.com>