net: ethernet: renesas: rswitch: Fix build error about ptp
JIRA: https://issues.redhat.com/browse/RHEL-34587

commit 76ad97e150f1079163c8503c7b8e249db994b244
Author: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Date:   Thu Nov 10 10:27:20 2022 +0900

    net: ethernet: renesas: rswitch: Fix build error about ptp

    If CONFIG_PTP_1588_CLOCK_OPTIONAL=m and CONFIG_RENESAS_ETHER_SWITCH=y,
    the following build error happened:

        aarch64-linux-ld: DWARF error: could not find abbrev number 60
        drivers/net/ethernet/renesas/rswitch.o: in function `rswitch_get_ts_info':
        rswitch.c:(.text+0x408): undefined reference to `ptp_clock_index'
        aarch64-linux-ld: DWARF error: could not find abbrev number 1190123
        drivers/net/ethernet/renesas/rcar_gen4_ptp.o: in function `rcar_gen4_ptp_register':
        rcar_gen4_ptp.c:(.text+0x4dc): undefined reference to `ptp_clock_register'
        aarch64-linux-ld: drivers/net/ethernet/renesas/rcar_gen4_ptp.o: in function `rcar_gen4_ptp_unregister':
        rcar_gen4_ptp.c:(.text+0x584): undefined reference to `ptp_clock_unregister'

    To fix the issue, add "depends on PTP_1588_CLOCK_OPTIONAL" into the
    Kconfig.

    Reported-by: kernel test robot <lkp@intel.com>
    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 6c6fa1a00ad3 ("net: ethernet: renesas: rswitch: Add R-Car Gen4 gPTP support")
    Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Link: https://lore.kernel.org/r/20221110012720.3552060-1-yoshihiro.shimoda.uh@renesas.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Radu Rendec <rrendec@redhat.com>