ath11k: Fix 'unused-but-set-parameter' error
Bugzilla: http://bugzilla.redhat.com/2043454

commit 624e0a3170309eeb5b729f7a43c1ba3234325f02
Author: Seevalamuthu Mariappan <quic_seevalam@quicinc.com>
Date:   Thu Nov 11 11:22:47 2021 +0530

    ath11k: Fix 'unused-but-set-parameter' error
    
    Below compilation error is reported when built with W=1,
    
    drivers/net/wireless/ath/ath11k/mac.c:5408:22: error: parameter 'changed_flags' set but not used [-Werror,-Wunused-but-set-parameter]
    
    changed_flags is set, but left unused. So, remove unnecessary set.
    Compile tested only.
    
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Seevalamuthu Mariappan <quic_seevalam@quicinc.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/1636609967-5114-1-git-send-email-quic_seevalam@quicinc.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>