RDMA/uverbs: Add empty rdma_uattrs_has_raw_cap() declaration
JIRA: https://issues.redhat.com/browse/RHEL-109942

commit 98269398c02ab20eb9ed6d77416023a2627049d8
Author: Leon Romanovsky <leon@kernel.org>
Date:   Tue Jul 8 12:31:39 2025 +0300

    RDMA/uverbs: Add empty rdma_uattrs_has_raw_cap() declaration

    The call to rdma_uattrs_has_raw_cap() is placed in mlx5 fs.c file,
    which is compiled without relation to CONFIG_INFINIBAND_USER_ACCESS.

    Despite the check is used only in flows with CONFIG_INFINIBAND_USER_ACCESS=y|m,
    the compilers generate the following error for CONFIG_INFINIBAND_USER_ACCESS=n
    builds.

    >> ERROR: modpost: "rdma_uattrs_has_raw_cap" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!

    Fixes: f458ccd2aa2c ("RDMA/uverbs: Check CAP_NET_RAW in user namespace for flow create")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202507080725.bh7xrhpg-lkp@intel.com/
    Link: https://patch.msgid.link/72dee6b379bd709255a5d8e8010b576d50e47170.1751967071.git.leon@kernel.org
    Reviewed-by: Zhu Yanjun <yanjun.zhu@linux.dev>
    Reviewed-by: Parav Pandit <parav@nvidia.com>
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>