wifi: b43legacy: remove unused freq_r3A_value function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit 4c7f8c237d322a98026a57f6ba846fc997f165df

clang with W=1 reports
drivers/net/wireless/broadcom/b43legacy/radio.c:1713:5: error:
  unused function 'freq_r3A_value' [-Werror,-Wunused-function]
u16 freq_r3A_value(u16 frequency)
    ^
This function is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Acked-by: Larry Finger <Larry.Finger@lwfinger.net>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230324135022.2649735-1-trix@redhat.com
(cherry picked from commit 4c7f8c237d322a98026a57f6ba846fc997f165df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>