perf record: Fix documentation for a inexistent option '-l'
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Taeung Song <treeze.taeung@gmail.com>
commit 3f50f614d61f91ad30b1947c429d1f235493a7f9

'perf record' had a '-l' option that meant "scale counter values" a very
long time ago, but it currently belongs to 'perf stat' as '-c'.  So
remove it. I found this problem in the below case.

    $ perf record -e cycles -l sleep 3
      Error: unknown switch `l

	Signed-off-by: Taeung Song <treeze.taeung@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
Link: http://lkml.kernel.org/r/1507907412-19813-1-git-send-email-treeze.taeung@gmail.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 3f50f614d61f91ad30b1947c429d1f235493a7f9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>