drm/mediatek: Fix return type of mtk_hdmi_bridge_mode_valid()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2115902
Upstream Status: v6.0.16

commit cb5b1d1c979d502e454f40dee10e90242edc0300
Author:     Nathan Chancellor <nathan@kernel.org>
AuthorDate: Wed Nov  2 08:47:12 2022 -0700
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Sat Dec 31 13:26:44 2022 +0100

    [ Upstream commit 890d637523eec9d730e3885532fa1228ba678880 ]

    With clang's kernel control flow integrity (kCFI, CONFIG_CFI_CLANG),
    indirect call targets are validated against the expected function
    pointer prototype to make sure the call target is valid to help mitigate
    ROP attacks. If they are not identical, there is a failure at run time,
    which manifests as either a kernel panic or thread getting killed. A
    proposed warning in clang aims to catch these at compile time, which
    reveals:

      drivers/gpu/drm/mediatek/mtk_hdmi.c:1407:16: error: incompatible function pointer types initializing 'enum drm_mode_status (*)(struct drm_bridge *, const struct drm_display_info *, const struct drm_display_mode *)' with an expression of type 'int (struct drm_bridge *, const struct drm_display_info *, const struct drm_display_mode *)' [-Werror,-Wincompatible-function-pointer-types-strict]
              .mode_valid = mtk_hdmi_bridge_mode_valid,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.

    ->mode_valid() in 'struct drm_bridge_funcs' expects a return type of
    'enum drm_mode_status', not 'int'. Adjust the return type of
    mtk_hdmi_bridge_mode_valid() to match the prototype's to resolve the
    warning and CFI failure.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1750
    Reported-by: Sami Tolvanen <samitolvanen@google.com>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
    Signed-off-by: Chun-Kuang Hu <chunkuang.hu@kernel.org>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>