powerpc/kvm: Fix ppc64_defconfig + PPC_POWERNV=n build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [powerpc] kvm: Fix ppc64_defconfig + PPC_POWERNV=n build error (Thomas Huth) [1287973]
Rebuild_FUZZ: 92.86%
commit-author Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
commit a7e73e711e48e138a25265c156cca9a1ed109b50

kvm_no_guest() calls power7_wakeup_loss() to put the thread into the
deepest supported idle state. power7_wakeup_loss() is defined in
arch/powerpc/kernel/idle_power7.S, which is compiled only when
PPC_P7_NAP=y.

And PPC_P7_NAP is selected when PPC_POWERNV=y.

Hence in cases where PPC_POWERNV=n and KVM_BOOK3S_64_HV=y we see the
following error:

  arch/powerpc/kvm/built-in.o: In function `kvm_no_guest':
  arch/powerpc/kvm/book3s_hv_rmhandlers.o:(.text+0x42c): undefined reference to `power7_wakeup_loss'

Fix this by adding PPC_POWERNV as a dependency for KVM_BOOK3S_64_HV.

	Signed-off-by: Shreyas B. Prabhu <shreyas@linux.vnet.ibm.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit a7e73e711e48e138a25265c156cca9a1ed109b50)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>