ACPI: arm64: export acpi_arch_thermal_cpufreq_pctg()
jira LE-1907
Rebuild_History Non-Buildable kernel-5.14.0-427.35.1.el9_4
commit-author Arnd Bergmann <arnd@arndb.de>
commit ccb45b34d44016b91fa75646741d317d6d6fdeea
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-5.14.0-427.35.1.el9_4/ccb45b34.failed

The cpufreq code can be in a loadable module, so the architecture support
for it has to be exported:

ERROR: modpost: "acpi_arch_thermal_cpufreq_pctg" [drivers/acpi/processor.ko] undefined!

Fixes: 310293a2b941 ("ACPI: processor: reduce CPUFREQ thermal reduction pctg for Tegra241")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit ccb45b34d44016b91fa75646741d317d6d6fdeea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/acpi/arm64/thermal_cpufreq.c