iio: imx8qxp-adc: mark PM functions as __maybe_unused
Bugzilla: http://bugzilla.redhat.com/2071780

commit 0336d605daeea142c3ec9b143d0131a137f45108
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Oct 13 16:43:26 2021 +0200

    iio: imx8qxp-adc: mark PM functions as __maybe_unused

    Without CONFIG_PM_SLEEP, the runtime suspend/resume functions
    are unused, producing a warning:

    drivers/iio/adc/imx8qxp-adc.c:433:12: error: 'imx8qxp_adc_runtime_resume' defined but not used [-Werror=unused-function]
      433 | static int imx8qxp_adc_runtime_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/iio/adc/imx8qxp-adc.c:419:12: error: 'imx8qxp_adc_runtime_suspend' defined but not used [-Werror=unused-function]
      419 | static int imx8qxp_adc_runtime_suspend(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~

    Mark them as __maybe_unused to shut up the compiler.

    Fixes: 1e23dcaa1a9f ("iio: imx8qxp-adc: Add driver support for NXP IMX8QXP ADC")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Cai Huoqing <caihuoqing@baidu.com>
    Link: https://lore.kernel.org/r/20211013144338.2261316-1-arnd@kernel.org
    Signed-off-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>

Signed-off-by: Steve Best <sbest@redhat.com>