serial: ce4100: fix build after serial_in/out() changes
JIRA: https://issues.redhat.com/browse/RHEL-111649

commit f5655940771fbc75efadfe91ca081525732bed3f
Author: "Jiri Slaby (SUSE)" <jirislaby@kernel.org>
Date: Mon, 23 Jun 2025 12:12:45 +0200

    This x86_32 driver remain unnoticed, so after the commit below, the
    compilation now fails with:
      arch/x86/platform/ce4100/ce4100.c:107:16: error: incompatible function pointer types assigning to '...' from '...'

    To fix the error, convert also ce4100 to the new
    uart_port::serial_{in,out}() types.

    Signed-off-by: "Jiri Slaby (SUSE)" <jirislaby@kernel.org>
    Fixes: fc9ceb501e38 ("serial: 8250: sanitize uart_port::serial_{in,out}() types")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202506190552.TqNasrC3-lkp@intel.com/
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>
    Cc: x86@kernel.org
    Cc: "H. Peter Anvin" <hpa@zytor.com>
    Link: https://lore.kernel.org/r/20250623101246.486866-1-jirislaby@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Mark Salter <msalter@redhat.com>