futex: Fix sparc32/m68k/nds32 build regression
commit 4e0d84634445ed550498d613a49ea8f6cfa5e66c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 26 10:58:40 2021 +0100

    futex: Fix sparc32/m68k/nds32 build regression

    The recent futex cleanup series, botched up a rename of some function
    names, breaking sparc32, m68k and nds32:

    include/asm-generic/futex.h:17:2: error: implicit declaration of function 'futex_atomic_cmpxchg_inatomic_local_generic'; did you mean 'futex_atomic_cmpxchg_inatomic_local'? [-Werror=implicit-function-declaration]

    Fix the macros to point to the correct functions.

    Fixes: 3f2bedabb62c ("futex: Ensure futex_atomic_cmpxchg_inatomic() is present")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Link: https://lore.kernel.org/r/20211126095852.455492-1-arnd@kernel.org

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2176147
Signed-off-by: Joel Savitz <jsavitz@redhat.com>