HID: intel-ish-hid: Fix -Wcast-function-type-strict in devm_ishtp_alloc_workqueue()
JIRA: https://issues.redhat.com/browse/RHEL-136560
Upstream status: v6.18+

commit 3644f4411713f52bf231574aa8759e3d8e20b341
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Oct 22 00:49:08 2025 +0200

    HID: intel-ish-hid: Fix -Wcast-function-type-strict in devm_ishtp_alloc_workqueue()

    Clang warns (or errors with CONFIG_WERROR=y / W=e):

      drivers/hid/intel-ish-hid/ipc/ipc.c:935:36: error: cast from 'void (*)(struct workqueue_struct *)' to 'void (*)(void *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
        935 |         if (devm_add_action_or_reset(dev, (void (*)(void *))destroy_workqueue,
            |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      include/linux/device/devres.h:168:34: note: expanded from macro 'devm_add_action_or_reset'
        168 |         __devm_add_action_or_ireset(dev, action, data, #action)
            |                                         ^~~~~~

    This warning is pointing out a kernel control flow integrity (kCFI /
    CONFIG_CFI=y) violation will occur due to this function cast when the
    destroy_workqueue() is indirectly called via devm_action_release()
    because the prototype of destroy_workqueue() does not match the
    prototype of (*action)().

    Use a local function with the correct prototype to wrap
    destroy_workqueue() to resolve the warning and CFI violation.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202510190103.qTZvfdjj-lkp@intel.com/
    Closes: https://github.com/ClangBuiltLinux/linux/issues/2139
    Fixes: 0d30dae38fe0 ("HID: intel-ish-hid: Use dedicated unbound workqueues to prevent resume blocking")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Reviewed-by: Zhang Lixu <lixu.zhang@intel.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>