phy: broadcom: sr-usb: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-28810

commit 2bc00b9b9001329792b14ce20141f334b6debcbc
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Thu, 10 Aug 2023 13:19:57 +0200

  'version' is an enum, thus cast of pointer on 64-bit compile test with
  W=1 causes:

    phy-bcm-sr-usb.c:314:13: error: cast to smaller integer type 'enum bcm_usb_phy_version' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

  Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
  Link: https://lore.kernel.org/r/20230810111958.205705-3-krzysztof.kozlowski@linaro.org
  Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>