scsi: lpfc: Add dependency on CPU_FREQ
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Guenter Roeck <linux@roeck-us.net>
commit e3d2bf6505ddd4d11226dc2ad2071981564a35db

Since commit 317aeb83c92b ("scsi: lpfc: Add blk_io_poll support for latency
improvment"), the lpfc driver depends on CPUFREQ. Without it, builds fail
with

drivers/scsi/lpfc/lpfc_sli.c: In function 'lpfc_init_idle_stat_hb':
drivers/scsi/lpfc/lpfc_sli.c:7329:26: error:
	implicit declaration of function 'get_cpu_idle_time'

Add the missing dependency.

Link: https://lore.kernel.org/r/20200722023027.36866-1-linux@roeck-us.net
Fixes: 317aeb83c92b ("scsi: lpfc: Add blk_io_poll support for latency improvment")
	Cc: Dick Kennedy <dick.kennedy@broadcom.com>
	Cc: James Smart <jsmart2021@gmail.com>
	Reviewed-by: James Smart <james.smart@broadcom.com>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit e3d2bf6505ddd4d11226dc2ad2071981564a35db)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>