clk: Avoid invalid function names in CLK_OF_DECLARE()
JIRA: https://issues.redhat.com/browse/RHEL-5705

commit 5cf9d015be160e2d90d29ae74ef1364390e8fce8
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Mar 8 13:47:11 2023 -0700

    clk: Avoid invalid function names in CLK_OF_DECLARE()

    After commit c28cd1f3433c ("clk: Mark a fwnode as initialized when using
    CLK_OF_DECLARE() macro"), drivers/clk/mvebu/kirkwood.c fails to build:

     drivers/clk/mvebu/kirkwood.c:358:1: error: expected identifier or '('
     CLK_OF_DECLARE(98dx1135_clk, "marvell,mv98dx1135-core-clock",
     ^
     include/linux/clk-provider.h:1367:21: note: expanded from macro 'CLK_OF_DECLARE'
             static void __init name##_of_clk_init_declare(struct device_node *np) \
                                ^
     <scratch space>:124:1: note: expanded from here
     98dx1135_clk_of_clk_init_declare
     ^
     drivers/clk/mvebu/kirkwood.c:358:1: error: invalid digit 'd' in decimal constant
     include/linux/clk-provider.h:1372:34: note: expanded from macro 'CLK_OF_DECLARE'
             OF_DECLARE_1(clk, name, compat, name##_of_clk_init_declare)
                                             ^
     <scratch space>:125:3: note: expanded from here
     98dx1135_clk_of_clk_init_declare
       ^
     drivers/clk/mvebu/kirkwood.c:358:1: error: invalid digit 'd' in decimal constant
     include/linux/clk-provider.h:1372:34: note: expanded from macro 'CLK_OF_DECLARE'
             OF_DECLARE_1(clk, name, compat, name##_of_clk_init_declare)
                                             ^
     <scratch space>:125:3: note: expanded from here
     98dx1135_clk_of_clk_init_declare
       ^
     drivers/clk/mvebu/kirkwood.c:358:1: error: invalid digit 'd' in decimal constant
     include/linux/clk-provider.h:1372:34: note: expanded from macro 'CLK_OF_DECLARE'
             OF_DECLARE_1(clk, name, compat, name##_of_clk_init_declare)
                                             ^
     <scratch space>:125:3: note: expanded from here
     98dx1135_clk_of_clk_init_declare
       ^

    C function names must start with either an alphabetic letter or an
    underscore. To avoid generating invalid function names from clock names,
    add two underscores to the beginning of the identifier.

    Fixes: c28cd1f3433c ("clk: Mark a fwnode as initialized when using CLK_OF_DECLARE() macro")
    Suggested-by: Saravana Kannan <saravanak@google.com>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20230308-clk_of_declare-fix-v1-1-317b741e2532@kernel.org
    Reviewed-by: Saravana Kannan <saravanak@google.com>
    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Signed-off-by: Stephen Boyd <sboyd@kernel.org>

Signed-off-by: Joel Slebodnick <jslebodn@redhat.com>