bpf: avoid unused variable warning in tcp_bpf_rtt()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit bef8e2639242e7f7214f1ab3b37ace1415a4f750

When CONFIG_BPF is disabled, we get a warning for an unused
variable:

In file included from drivers/target/target_core_device.c:26:
include/net/tcp.h:2226:19: error: unused variable 'tp' [-Werror,-Wunused-variable]
        struct tcp_sock *tp = tcp_sk(sk);

The variable is only used in one place, so it can be
replaced with its value there to avoid the warning.

Fixes: 23729ff23186 ("bpf: add BPF_CGROUP_SOCK_OPS callback that is executed on every RTT")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Soheil Hassas Yeganeh <soheil@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit bef8e2639242e7f7214f1ab3b37ace1415a4f750)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>