net1080: Remove unused function nc_dump_ttl()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit ce064e68a7e1ae525cd525fac3a6901591ddae3c

The function is not used, removing it fixes the following warning when
building with clang:

drivers/net/usb/net1080.c:271:20: error: unused function
    'nc_dump_ttl' [-Werror,-Wunused-function]

Also remove the definition of TTL_THIS, which is only used in
nc_dump_ttl()

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ce064e68a7e1ae525cd525fac3a6901591ddae3c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>