bpf: Fix uninitialized values in BPF_{CORE,PROBE}_READ
JIRA: https://issues.redhat.com/browse/RHEL-78203

commit 41d4ce6df3f4945341ec509a840cc002a413b6cc
Author: Anton Protopopov <a.s.protopopov@gmail.com>
Date:   Fri May 2 19:30:31 2025 +0000

    bpf: Fix uninitialized values in BPF_{CORE,PROBE}_READ
    
    With the latest LLVM bpf selftests build will fail with
    the following error message:
    
        progs/profiler.inc.h:710:31: error: default initialization of an object of type 'typeof ((parent_task)->real_cred->uid.val)' (aka 'const unsigned int') leaves the object uninitialized and is incompatible with C++ [-Werror,-Wdefault-const-init-unsafe]
          710 |         proc_exec_data->parent_uid = BPF_CORE_READ(parent_task, real_cred, uid.val);
              |                                      ^
        tools/testing/selftests/bpf/tools/include/bpf/bpf_core_read.h:520:35: note: expanded from macro 'BPF_CORE_READ'
          520 |         ___type((src), a, ##__VA_ARGS__) __r;                               \
              |                                          ^
    
    This happens because BPF_CORE_READ (and other macro) declare the
    variable __r using the ___type macro which can inherit const modifier
    from intermediate types.
    
    Fix this by using __typeof_unqual__, when supported. (And when it
    is not supported, the problem shouldn't appear, as older compilers
    haven't complained.)
    
    Fixes: 792001f4f7aa ("libbpf: Add user-space variants of BPF_CORE_READ() family of macros")
    Fixes: a4b09a9ef945 ("libbpf: Add non-CO-RE variants of BPF_CORE_READ() macro family")
    Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20250502193031.3522715-1-a.s.protopopov@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>