ASoC: Mediatek: MT8183: Fix build error in mt8183_da7219_max98357_dev_probe
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: Mediatek: MT8183: Fix build error in mt8183_da7219_max98357_dev_probe (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 96.15%
commit-author YueHaibing <yuehaibing@huawei.com>
commit 52a30f3bb1b15c7d27233e9947370c1c14b5cbae

When building CONFIG_SND_SOC_MT8183_DA7219_MAX98357A=m
gcc warn this:

sound/soc/mediatek/mt8183/mt8183-da7219-max98357.c: In function mt8183_da7219_max98357_dev_probe:
sound/soc/mediatek/mt8183/mt8183-da7219-max98357.c:413:13: error: struct snd_soc_dai_link has no member named platform; did you mean platforms?
   dai_link->platform = NULL;
             ^~~~~~~~
             platforms

use 'dai_link->platforms' instead of 'dai_link->platform'.

Fixes: 11c0269017b2 ("ASoC: Mediatek: MT8183: Add machine driver with TS3A227")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 52a30f3bb1b15c7d27233e9947370c1c14b5cbae)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>