tools/power/x86/intel-speed-select: fix build failure when using -Wl,--as-needed
Bugzilla: https://bugzilla.redhat.com/2040063
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86.git

commit b2dd71f9f728da695a86b8308feb4f39defe9019
Author: Herton R. Krzesinski <herton@redhat.com>
Date:   Mon Apr 4 18:05:25 2022 -0300

    tools/power/x86/intel-speed-select: fix build failure when using -Wl,--as-needed

    Build of intel-speed-select will fail if you run:

    $ LDFLAGS="-Wl,--as-needed" /usr/bin/make V=1
    ...
    gcc -O2 -Wall -g -D_GNU_SOURCE -Iinclude -I/usr/include/libnl3 -Wl,--as-needed -lnl-genl-3 -lnl-3 intel-speed-select-in.o -o intel-speed-select
    /usr/bin/ld: intel-speed-select-in.o: in function `handle_event':
    (...)/linux/tools/power/x86/intel-speed-select/hfi-events.c:189: undefined reference to `nlmsg_hdr'
    ...

    In this case the problem is that order when linking matters when using
    the flag -Wl,--as-needed, symbols not used at that point are discarded.
    So since intel-speed-select-in.o comes after, at that point the
    libraries/symbols are already discarded and then missing/undefined
    references are reported.

    To fix this, make sure we specify LDFLAGS after the object file.

    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Signed-off-by: Herton R. Krzesinski <herton@redhat.com>
    Link: https://lore.kernel.org/r/20220404210525.725611-1-herton@redhat.com
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>