powerpc: Move `path` variable inside DEBUG_PROM
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Mathieu Malaterre <malat@debian.org>
commit eab00a208eb63d863b6cc0a03f68b4424ef5add8

Add gcc attribute unused for two variables. Fix warnings treated as errors
with W=1:

  arch/powerpc/kernel/prom_init.c:1388:8: error: variable ‘path’ set but not used [-Werror=unused-but-set-variable]

	Suggested-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Signed-off-by: Mathieu Malaterre <malat@debian.org>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit eab00a208eb63d863b6cc0a03f68b4424ef5add8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>