i40iw: Fixes for static checker warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Shiraz Saleem <shiraz.saleem@intel.com>
commit 83fb1c89e7ee5bb16397b294ccfbd65a9a22e402

Remove NULL check for cm_node->listener in i40iw_accept
as listener is always present at this point.

Remove the check for cm_node->accept_pend and related code
in i40iw_cm_event_connected as the cm_node in this context
is only pertinent to active node and cm_node->accept_pend
is always 0.

This fixes the following smatch warnings,

drivers/infiniband/hw/i40iw/i40iw_cm.c:3691 i40iw_accept()
error: we previously assumed 'cm_node->listener' could be null

drivers/infiniband/hw/i40iw/i40iw_cm.c:4061 i40iw_cm_event_connected()
error: we previously assumed 'cm_node->listener' could be null

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 83fb1c89e7ee5bb16397b294ccfbd65a9a22e402)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>