perf test: Fix a compile error on pe-file-parsing.c
Bugzilla: https://bugzilla.redhat.com/2233483

upstream
========
commit ad5f604e186ac08d12c401e34ea96c09c38ddbc5
Author: Namhyung Kim <namhyung@kernel.org>
Date:   Mon Jun 26 23:32:57 2023 -0700

description
===========
The dso__find_symbol_by_name() should be have idx pointer argument.
Found during the build-test.

  $ make build-test
  ...
    CC      /tmp/tmp.6JwPK1xbWG/tests/pe-file-parsing.o
  tests/pe-file-parsing.c: In function ‘run_dir’:
  tests/pe-file-parsing.c:64:15: error: too few arguments to function ‘dso__find_symbol_by_name’
     64 |         sym = dso__find_symbol_by_name(dso, "main");
        |               ^~~~~~~~~~~~~~~~~~~~~~~~
  In file included from tests/pe-file-parsing.c:16:
  /usr/local/google/home/namhyung/project/linux/tools/perf/util/symbol.h:135:16: note: declared here
    135 | struct symbol *dso__find_symbol_by_name(struct dso *dso, const char *name, size_t *idx);
        |                ^~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 259dce914e93 ("perf symbol: Remove symbol_name_rb_node")
    Acked-by: Ian Rogers <irogers@google.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Arnaldo Carvalho de Melo <acme@kernel.org>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20230627063257.549005-1-namhyung@kernel.org
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Conflicts:
==========
We haven't removed the flags before (commit dd6775f98614 ("perf build: Remove
FEATURE_CHECK_LDFLAGS-disassembler-{four-args,init-styled} setting")), so not
all were re-added now.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>