gpiolib: provide a declaration of seq_file in gpio/driver.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Stephen Rothwell <sfr@canb.auug.org.au>
commit f3ed0b66482fa2a0403280174a998487e9054867

Fixes this build error:

In file included from include/asm-generic/gpio.h:13:0,
                 from include/linux/gpio.h:51,
                 from include/linux/of_gpio.h:20,
                 from arch/powerpc/sysdev/ppc4xx_gpio.c:29:
include/linux/gpio/driver.h:85:14: error: 'struct seq_file' declared inside=
 parameter list [-Werror]
include/linux/gpio/driver.h:85:14: error: its scope is only this definition=
 or declaration, which is probably not what you want [-Werror]

	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit f3ed0b66482fa2a0403280174a998487e9054867)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>