md/md-llbitmap: Use DIV_ROUND_UP_SECTOR_T
JIRA: https://issues.redhat.com/browse/RHEL-129337

commit 7935b843ce2184164f41c3b5c64e9f52994306f4
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Sep 10 13:47:26 2025 -0700

    md/md-llbitmap: Use DIV_ROUND_UP_SECTOR_T

    When building for 32-bit platforms, there are several link (if builtin)
    or modpost (if a module) errors due to dividends of type 'sector_t' in
    DIV_ROUND_UP:

      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.o: in function `llbitmap_resize':
      drivers/md/md-llbitmap.c:1017:(.text+0xae8): undefined reference to `__aeabi_uldivmod'
      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.c:1020:(.text+0xb10): undefined reference to `__aeabi_uldivmod'
      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.o: in function `llbitmap_end_discard':
      drivers/md/md-llbitmap.c:1114:(.text+0xf14): undefined reference to `__aeabi_uldivmod'
      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.o: in function `llbitmap_start_discard':
      drivers/md/md-llbitmap.c:1097:(.text+0x1808): undefined reference to `__aeabi_uldivmod'
      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.o: in function `llbitmap_read_sb':
      drivers/md/md-llbitmap.c:867:(.text+0x2080): undefined reference to `__aeabi_uldivmod'
      arm-linux-gnueabi-ld: drivers/md/md-llbitmap.o:drivers/md/md-llbitmap.c:895: more undefined references to `__aeabi_uldivmod' follow

    Use DIV_ROUND_UP_SECTOR_T instead of DIV_ROUND_UP, which exists to
    handle this exact situation.

    Fixes: 5ab829f1971d ("md/md-llbitmap: introduce new lockless bitmap")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Nigel Croxon <ncroxon@redhat.com>