usb: typec: include linux/device.h in ucsi.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [usb] typec: include linux/device.h in ucsi.h (Torez Smith) [1456565]
Rebuild_FUZZ: 93.98%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 86be7f7b2d940ddc18143061e77989b017d93bf8
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/86be7f7b.failed

The new driver causes a build failure in some configurations:

In file included from /git/arm-soc/drivers/usb/typec/ucsi/trace.h:9:0,
                 from /git/arm-soc/drivers/usb/typec/ucsi/trace.c:2:
drivers/usb/typec/ucsi/ucsi.h:331:39: error: 'struct device' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

This includes the required header file.

Fixes: c1b0bc2dabfa ("usb: typec: Add support for UCSI interface")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
	Reviewed-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 86be7f7b2d940ddc18143061e77989b017d93bf8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/usb/misc/ucsi.h