bpf: syscall_nrs: Disable no previous prototype warnning
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit c50fc1cbfd71dcb1d70fd593b2af7c92af465921
Author: Jason Xing <kernelxing@tencent.com>
Date:   Wed Oct 2 07:32:42 2024 +0800

    bpf: syscall_nrs: Disable no previous prototype warnning

    In some environments (gcc treated as error in W=1, which is default), if we
    make -C samples/bpf/, it will be stopped because of
    "no previous prototype" error like this:

      ../samples/bpf/syscall_nrs.c:7:6:
      error: no previous prototype for ‘syscall_defines’ [-Werror=missing-prototypes]
       void syscall_defines(void)
            ^~~~~~~~~~~~~~~

    Actually, this file meets our expectatations because it will be converted to
    a .h file. In this way, it's correct. Considering the warnning stopping us
    compiling, we can remove the warnning directly.

    Signed-off-by: Jason Xing <kernelxing@tencent.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/all/20241001012540.39007-1-kerneljasonxing@gmail.com/
    Link: https://lore.kernel.org/all/CAEf4BzaVdr_0kQo=+jPLN++PvcU6pwTjaPVEA880kgDN94TZYw@mail.gmail.com/
    Link: https://lore.kernel.org/bpf/20241001233242.98679-1-kerneljasonxing@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>