ASoC: SOF: fix intel-soundwire link failure
Bugzilla: https://bugzilla.redhat.com/2179848

commit c5a61db9bf897494fb0657eeb24dfdcb1aab1fc4
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Feb 2 11:22:30 2023 +0100

    ASoC: SOF: fix intel-soundwire link failure

    My randconfig build setup ran into a rare build failure with

    CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE=y
    CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE=m
    CONFIG_SOUNDWIRE=y
    CONFIG_SOUNDWIRE_INTEL=m
    CONFIG_SND_SOC_SOF_HDA=y
    CONFIG_SND_SOC_SOF_INTEL_TGL=y

    x86_64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_init_caps':
    hda.c:(.text+0x691): undefined reference to `sdw_intel_cnl_hw_ops'
    x86_64-linux-ld: hda.c:(.text+0x6f2): undefined reference to `sdw_intel_probe'
    x86_64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_sdw_startup':
    hda.c:(.text+0x1c40): undefined reference to `sdw_intel_startup'
    x86_64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_sdw_process_wakeen':
    hda.c:(.text+0x1cb6): undefined reference to `sdw_intel_process_wakeen_event'
    x86_64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_dsp_interrupt_thread':
    hda.c:(.text+0x1d67): undefined reference to `sdw_intel_thread'
    x86_64-linux-ld: sound/soc/sof/intel/hda.o: in function `hda_dsp_remove':
    hda.c:(.text+0x2655): undefined reference to `sdw_intel_exit'

    My best understanding is that the definition of
    SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE was intended to avoid this
    problem, but got it wrong for the SND_SOC_SOF_INTEL_SOUNDWIRE=m case,
    where the 'select' is meant to set SOUNDWIRE_INTEL to the value of
    SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE rather than the intersection of
    SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE and SND_SOC_SOF_INTEL_SOUNDWIRE.

    Change the condition to check for SND_SOC_SOF_INTEL_SOUNDWIRE to be a
    boolean rather than a tristate expression in order to propagate this
    as intended.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230202102247.806749-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>