selftests/mm: fix build break when compiling pkey_util.c
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 22adb528621ddc92f887882a658507fbf88a5214
Author: Madhavan Srinivasan <maddy@linux.ibm.com>
Date:   Mon Apr 28 18:49:34 2025 +0530

    selftests/mm: fix build break when compiling pkey_util.c

    Commit 50910acd6f615 ("selftests/mm: use sys_pkey helpers consistently")
    added a pkey_util.c to refactor some of the protection_keys functions
    accessible by other tests.  But this broken the build in powerpc in two
    ways,

    pkey-powerpc.h: In function `arch_is_powervm':
    pkey-powerpc.h:73:21: error: storage size of `buf' isn't known
       73 |         struct stat buf;
          |                     ^~~
    pkey-powerpc.h:75:14: error: implicit declaration of function `stat'; did you mean `strcat'? [-Wimplicit-function-declaration]
       75 |         if ((stat("/sys/firmware/devicetree/base/ibm,partition-name", &buf) == 0) &&
          |              ^~~~
          |              strcat

    Since pkey_util.c includes pkeys-helper.h, which in turn includes pkeys-powerpc.h,
    stat.h including is missing for "struct stat". This is fixed by adding "sys/stat.h"
    in pkeys-powerpc.h

    Secondly,

    pkey-powerpc.h:55:18: warning: format `%llx' expects argument of type `long long unsigned int', but argument 3 has type `u64' {aka `long unsigned int'} [-Wformat=]
       55 |         dprintf4("%s() changing %016llx to %016llx\n",
          |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       56 |                          __func__, __read_pkey_reg(), pkey_reg);
          |                                    ~~~~~~~~~~~~~~~~~
          |                                    |
          |                                    u64 {aka long unsigned int}
    pkey-helpers.h:63:32: note: in definition of macro `dprintf_level'
       63 |                 sigsafe_printf(args);           \
          |                                ^~~~

    These format specifier related warning are removed by adding
    "__SANE_USERSPACE_TYPES__" to pkeys_utils.c.

    Link: https://lkml.kernel.org/r/20250428131937.641989-1-nysal@linux.ibm.com
    Fixes: 50910acd6f61 ("selftests/mm: use sys_pkey helpers consistently")
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Signed-off-by: Nysal Jan K.A. <nysal@linux.ibm.com>
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>