net: of: fix stub of_net helpers for CONFIG_NET=n
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071840
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  At this stage, this
 has been tested by ensuring we can survive the CI/CD loop -- i.e.,
 that we have not broken anything else, and a simple boot test.  When
 sufficient drivers have been brought in for i.MX8M, we will be able
 to run further tests.

commit 8b017fbe0bbb98dd71fb4850f6b9cc0e136a26b8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Oct 14 11:00:37 2021 +0200

    net: of: fix stub of_net helpers for CONFIG_NET=n

    Moving the of_net code from drivers/of/ to net/core means we
    no longer stub out the helpers when networking is disabled,
    which leads to a randconfig build failure with at least one
    ARM platform that calls this from non-networking code:

    arm-linux-gnueabi-ld: arch/arm/mach-mvebu/kirkwood.o: in function `kirkwood_dt_eth_fixup':
    kirkwood.c:(.init.text+0x54): undefined reference to `of_get_mac_address'

    Restore the way this worked before by changing that #ifdef
    check back to testing for both CONFIG_OF and CONFIG_NET.

    Fixes: e330fb14590c ("of: net: move of_net under net/")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211014090055.2058949-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>
    (cherry picked from commit 8b017fbe0bbb98dd71fb4850f6b9cc0e136a26b8)

Signed-off-by: Al Stone <ahs3@redhat.com>