perf python: Fix binding linkage due to rename and move of evsel__increase_rlimit()
JIRA: https://issues.redhat.com/browse/RHEL-25824

upstream
========
commit 93c65d61433bcec4070fc61b7c737c79fc25f09a
Author: Arnaldo Carvalho de Melo <acme@kernel.org>
Date: Fri Oct 27 10:33:30 2023 -0300

description
===========
The changes in ("perf evsel: Rename evsel__increase_rlimit to
rlimit__increase_nofile") ended up breaking the python binding that now
references the rlimit__increase_nofile function, add the util/rlimit.o
to the tools/perf/util/python-ext-sources to cure that.

This was detected by the 'perf test python' regression test:

  $ perf test python
   14: 'import perf' in python        : FAILED!

  $ perf test -v python
  Couldn't bump rlimit(MEMLOCK), failures may take place when creating BPF maps, etc
   14: 'import perf' in python                                         :
  --- start ---
  test child forked, pid 2912462
  python usage test: "echo "import sys ; sys.path.insert(0, '/tmp/build/perf-tools-next/python'); import perf" | '/usr/bin/python3' "
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: /tmp/build/perf-tools-next/python/perf.cpython-311-x86_64-linux-gnu.so: undefined symbol: rlimit__increase_nofile
  test child finished with -1
  ---- end ----
  'import perf' in python: FAILED!
  $

Fixes: e093a222d7cba1eb ("perf evsel: Rename evsel__increase_rlimit to rlimit__increase_nofile")
    Acked-by: Namhyung Kim <namhyung@kernel.org>
    Acked-by: Yang Jihong <yangjihong1@huawei.com>
    Link: https://lore.kernel.org/lkml/ZTrCS5Z3PZAmfPdV@kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>