samples/bpf: Fix sockex3 error: Missing BPF prog type
Bugzilla: https://bugzilla.redhat.com/2137876

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit e5659e4e19e49f1eac58bb07ce8bc2d78a89fe65
Author: Rong Tao <rongtao@cestc.cn>
Date:   Sat Nov 5 14:48:00 2022 +0800

    samples/bpf: Fix sockex3 error: Missing BPF prog type

    since commit 450b167fb9be("libbpf: clean up SEC() handling"),
    sec_def_matches() does not recognize "socket/xxx" as "socket", therefore,
    the BPF program type is not recognized.

    Instead of sockex3_user.c parsing section names to get the BPF program fd.
    We use the program array map to assign a static index to each BPF program
    (get inspired by selftests/bpf progs/test_prog_array_init.c).
    Therefore, use SEC("socket") as section name instead of SEC("socket/xxx"),
    so that the BPF program is parsed to SOCKET_FILTER type. The "missing BPF
    prog type" problem is solved.

    How to reproduce this error:
    $ cd samples/bpf
    $ sudo ./sockex3
    libbpf: prog 'bpf_func_PARSE_IP': missing BPF prog type, check ELF section name 'socket/3'
    libbpf: prog 'bpf_func_PARSE_IP': failed to load: -22
    libbpf: failed to load object './sockex3_kern.o'
    ERROR: loading BPF object file failed

    Signed-off-by: Rong Tao <rongtao@cestc.cn>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/tencent_EBA3C18864069E42175946973C2ACBAF5408@qq.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>