drm/tests: Split up test cases in igt_check_drm_format_min_pitch
commit cf1e6a90315a3f5b8ecbb3cf6a4badf8978e9075
Author: Maíra Canal <mairacanal@riseup.net>
Date:   Fri Jul 29 09:47:26 2022 -0300

    drm/tests: Split up test cases in igt_check_drm_format_min_pitch

    The igt_check_drm_format_min_pitch() function had a lot of
    KUNIT_EXPECT_* calls, all of which ended up allocating and initializing
    various test assertion structures on the stack.

    This behavior was producing -Wframe-larger-than warnings on PowerPC, i386,
    and MIPS architectures, such as:

    drivers/gpu/drm/tests/drm_format_test.c: In function 'igt_check_drm_format_min_pitch':
    drivers/gpu/drm/tests/drm_format_test.c:271:1: error: the frame size of
    3712 bytes is larger than 2048 bytes

    So, the igt_check_drm_format_min_pitch() test case was split into three
    smaller functions: one testing single plane formats, one testing
    multi-planar formats, and the other testing tiled formats.

    Fixes: 0421bb0baa84 ("drm: selftest: convert drm_format selftest to KUnit")
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Maíra Canal <mairacanal@riseup.net>
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Reviewed-by: André Almeida <andrealmeid@igalia.com>
    Signed-off-by: Melissa Wen <melissa.srw@gmail.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20220729124726.748221-1-mairacanal@riseup.net

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>