memstick r592: make memstick_debug_get_tpc_name() static
JIRA: https://issues.redhat.com/browse/RHEL-34114

commit 434587df9f7fd68575f99a889cc5f2efc2eaee5e
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 22:27:04 +0200

  There are no other files referencing this function, apparently
  it was left global to avoid an 'unused function' warning when
  the only caller is left out. With a 'W=1' build, it causes
  a 'missing prototype' warning though:

  drivers/memstick/host/r592.c:47:13: error: no previous prototype for 'memstick_debug_get_tpc_name' [-Werror=missing-prototypes]

  Annotate the function as 'static __maybe_unused' to avoid both
  problems.

  Fixes: 926341250102 ("memstick: add driver for Ricoh R5C592 card reader")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Link: https://lore.kernel.org/r/20230516202714.560929-1-arnd@kernel.org
  Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>