ASoC: amd: acp: Fix initialization of ext_intr_stat1 in i2s_irq_handler()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Nathan Chancellor <nathan@kernel.org>
commit d81677410f172c2b946393c09b46ff9e8dc1b6ec

Clang warns:

  ../sound/soc/amd/acp/acp-platform.c:117:19: error: variable 'ext_intr_stat1' is uninitialized when used here [-Werror,-Wuninitialized]
                          if (stream && (ext_intr_stat1 & stream->irq_bit)) {
                                         ^~~~~~~~~~~~~~
  ../sound/soc/amd/acp/acp-platform.c:97:35: note: initialize the variable 'ext_intr_stat1' to silence this warning
          u32 ext_intr_stat, ext_intr_stat1, i;
                                           ^
                                            = 0
  1 error generated.

The variable was not properly renamed, correct it to resolve the
warning.

Fixes: 93f53881473c ("ASoC: amd: acp: Modify local variables name to generic")
Link: https://github.com/ClangBuiltLinux/linux/issues/1675
	Signed-off-by: Nathan Chancellor <nathan@kernel.org>
	Reviewed-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20220725180539.1315066-1-nathan@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit d81677410f172c2b946393c09b46ff9e8dc1b6ec)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>