mm: fix mismerge of folio page flag manipulators
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2019485
Tested: ran Rafael's set of sanity tests, other than known issues, seems ok

commit e66435936756d9bce96433be183358a8994a0f0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Mon Nov 1 14:56:37 2021 -0700

    mm: fix mismerge of folio page flag manipulators

    I had missed a semantic conflict between commit d389a4a81155 ("mm: Add
    folio flag manipulation functions") from the folio tree, and commit
    eac96c3efdb5 ("mm: filemap: check if THP has hwpoisoned subpage for PMD
    page fault") that added a new set of page flags.

    My build tests had too many options enabled, which hid this issue.  But
    if you didn't have MEMORY_FAILURE or TRANSPARENT_HUGEPAGE enabled, you'd
    end up with build errors like this:

      include/linux/page-flags.h:806:29: error: macro "PAGEFLAG_FALSE" requires 2 arguments, but only 1 given
        806 | PAGEFLAG_FALSE(HasHWPoisoned)
            |                             ^

    due to the missing lowercase name used for folio function naming.

    Fixes: 49f8275c7d92 ("Merge tag 'folio-5.16' of git://git.infradead.org/users/willy/pagecache")
    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Reported-by: Yang Shi <shy828301@gmail.com>
    Cc: Matthew Wilcox <willy@infradead.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>