Bluetooth: hci: fix build when POWER_SEQUENCING=m
JIRA: https://issues.redhat.com/browse/RHEL-61734

commit b96bac9607b285d4316e74fbf469df084c4f8adb
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sun Jun 23 19:13:52 2024 +0200

    Bluetooth: hci: fix build when POWER_SEQUENCING=m

    BT_HCIUART_QCA, which is a bool and an HCI UART component, uses now
    power sequencing, so we need to be sure BT_HCIUART_QCA=y and
    POWER_SEQUENCING=m cannot happen:

      /usr/bin/aarch64-linux-gnu-ld: drivers/bluetooth/hci_qca.o: in function `qca_serdev_probe':
      drivers/bluetooth/hci_qca.c:2401:(.text+0xc48): undefined reference to `devm_pwrseq_get'
      /usr/bin/aarch64-linux-gnu-ld: drivers/bluetooth/hci_qca.o: in function `qca_power_shutdown':
      drivers/bluetooth/hci_qca.c:2192:(.text+0x29e8): undefined reference to `pwrseq_power_off'
      /usr/bin/aarch64-linux-gnu-ld: drivers/bluetooth/hci_qca.o: in function `qca_power_on':
      drivers/bluetooth/hci_qca.c:1808:(.text+0x3390): undefined reference to `pwrseq_power_on'

    Fixes: 9a15ce685706 ("Bluetooth: qca: use the power sequencer for QCA6390")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>