wifi: rtl8xxxu: add LEDS_CLASS dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-496.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 38ae3192296924181537544e7cfc43ca78eadcda

rtl8xxxu now unconditionally uses LEDS_CLASS, so a Kconfig dependency
is required to avoid link errors:

aarch64-linux-ld: drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_core.o: in function `rtl8xxxu_disconnect':
rtl8xxxu_core.c:(.text+0x730): undefined reference to `led_classdev_unregister'

ERROR: modpost: "led_classdev_unregister" [drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.ko] undefined!
ERROR: modpost: "led_classdev_register_ext" [drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.ko] undefined!

Fixes: 3be01622995b ("wifi: rtl8xxxu: Register the LED and make it blink")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230217095910.2480356-1-arnd@kernel.org
(cherry picked from commit 38ae3192296924181537544e7cfc43ca78eadcda)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>