ASoC: fsl_utils: Drop usage of __clk_get_name()
Avoid build errors when CONFIG_COMMON_CLK is not set/enabled.

ERROR: modpost: "__clk_get_name" [sound/soc/fsl/snd-soc-fsl-utils.ko] undefined!

    Fixes: 7bad8125549c ("ASoC: fsl_utils: Add function to handle PLL clock source")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Shengjiu Wang <shengjiu.wang@nxp.com>
    Link: https://lore.kernel.org/r/1657507190-14546-1-git-send-email-shengjiu.wang@nxp.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Shengjiu Wang <shengjiu.wang@nxp.com>
Date: Mon Jul 11 10:39:50 2022 +0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit eaa27e7fe43f16fe587c3e93fd5c25ce86be3c43)
Bugzilla: https://bugzilla.redhat.com/2125537