audit: avoid missing-prototype warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-504.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit e455ca40dbcf2cd50d1e59bf4b2752b300bcdad4

Building with 'make W=1' reveals two function definitions without
a previous prototype in the audit code:

lib/compat_audit.c:32:5: error: no previous prototype for 'audit_classify_compat_syscall' [-Werror=missing-prototypes]
kernel/audit.c:1813:14: error: no previous prototype for 'audit_serial' [-Werror=missing-prototypes]

The first one needs a declaration from linux/audit.h but cannot
include that header without causing conflicting (compat) syscall number
definitions, so move the it into linux/audit_arch.h.

The second one is declared conditionally based on CONFIG_AUDITSYSCALL
but needed as a local function even when that option is disabled, so
move the declaration out of the #ifdef block.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Paul Moore <paul@paul-moore.com>
(cherry picked from commit e455ca40dbcf2cd50d1e59bf4b2752b300bcdad4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>