arm64: armv8_deprecated: fix unused-function error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2167398

commit 223d3a0d30b6e9f979f5642e430e1753d3e29f89
Author: Ren Zhijie <renzhijie2@huawei.com>
Date: Thu, 24 Nov 2022 02:24:29 +0000

    If CONFIG_SWP_EMULATION is not set and
    CONFIG_CP15_BARRIER_EMULATION is not set,
    aarch64-linux-gnu complained about unused-function :

    arch/arm64/kernel/armv8_deprecated.c:67:21: error: ‘aarch32_check_condition’ defined but not used [-Werror=unused-function]
     static unsigned int aarch32_check_condition(u32 opcode, u32 psr)
                         ^~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    To fix this warning, modify aarch32_check_condition() with __maybe_unused.

    Fixes: 0c5f416219da ("arm64: armv8_deprecated: move aarch32 helper earlier")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Acked-by: Mark Rutland <mark.rutland@arm.com>
    Link: https://lore.kernel.org/r/20221124022429.19024-1-renzhijie2@huawei.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>