Fix dist-get-buildreqs breakage around perl(ExtUtils::Embed)
CKI fails with

$ export missing=$(make dist-get-buildreqs | grep "Missing dependencies:" | cut -d":" -f2)
$ if [ "$missing" == "" ]; then echo "Missing dependencies should not be null but are empty. Review test log." && exit 1; fi;
$ dnf -y install $missing
Last metadata expiration check: 0:00:29 ago on Sat Feb  3 23:44:30 2024.
No match for argument: perl(ExtUtils
Error: Unable to find a match: perl(ExtUtils

This is because it was trying to "cut -d':' -f2" this line:
Missing dependencies:  perl(ExtUtils::Embed)

And it grabbed the content between the ':', leaving out ::Embed.  Easy
fix, convert cut's parameter '-f2' to '-f2-' to included everything
after the first ':'.

Running the command locally resolves the issue.

Signed-off-by: Don Zickus <dzickus@redhat.com>