usb: uhci-grlib: Explicitly include linux/platform_device.h
JIRA: https://issues.redhat.com/browse/RHEL-34114

commit d70c7a6614ac2e1340a9fed044aec04d695c6645
Author: Andreas Larsson <andreas@gaisler.com>
Date: Mon, 29 Jan 2024 08:50:56 +0100

  This fixes relying upon linux/of_platform.h to include
  linux/platform_device.h, which it no longer does, thereby fixing
  compilation problems like:

  In file included from drivers/usb/host/uhci-hcd.c:850:
  drivers/usb/host/uhci-grlib.c: In function 'uhci_hcd_grlib_probe':
  drivers/usb/host/uhci-grlib.c:92:29: error: invalid use of undefined type 'struct platform_device'
     92 |  struct device_node *dn = op->dev.of_node;
        |                             ^~

  Fixes: ef175b29a242 ("of: Stop circularly including of_device.h and of_platform.h")
  Signed-off-by: Andreas Larsson <andreas@gaisler.com>
  Link: https://lore.kernel.org/r/20240129075056.1511630-1-andreas@gaisler.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>