mmc: MMC_GOLDFISH should depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] MMC_GOLDFISH should depend on HAS_DMA (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 93.67%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 3d35877294005911da54c36e2ab4d7b72d5e9331

If NO_DMA=y:

    ERROR: dma_unmap_sg [drivers/mmc/host/android-goldfish.ko] undefined!
    ERROR: dma_alloc_coherent [drivers/mmc/host/android-goldfish.ko] undefined!
    ERROR: dma_map_sg [drivers/mmc/host/android-goldfish.ko] undefined!
    ERROR: dma_free_coherent [drivers/mmc/host/android-goldfish.ko] undefined!

Add a dependency on HAS_DMA to fix this.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
(cherry picked from commit 3d35877294005911da54c36e2ab4d7b72d5e9331)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>