ALSA: usb-audio: Fix whitespace & blank line issues in mixer_quirks
JIRA: https://issues.redhat.com/browse/RHEL-118908

commit df6b4dcf2e2c3b4e34c3213a575c92d0c9415d0d
Author: Cristian Ciocaltea <cristian.ciocaltea@collabora.com>
Date: Mon May 26 17:07:41 2025 +0300

    ALSA: usb-audio: Fix whitespace & blank line issues in mixer_quirks

    Address all whitespace & blank line(s) related issues reported by
    checkpatch.pl:

      ERROR: trailing whitespace
      ERROR: space required after that ',' (ctx:VxV)
      WARNING: Missing a blank line after declarations
      CHECK: Please use a blank line after function/struct/union/enum declarations
      CHECK: Please don't use multiple blank lines

    Signed-off-by: Cristian Ciocaltea <cristian.ciocaltea@collabora.com>
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Link: https://patch.msgid.link/20250526-dualsense-alsa-jack-v1-2-1a821463b632@collabora.com

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>