arm64: move cpu_suspend_set_dbg_restorer() prototype to header
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit ec3a3db7100ddebb32ed5b1052c1cd1136057230
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:31 +0200

    The cpu_suspend_set_dbg_restorer() function is called by the hw_breakpoint
    code but defined in another file. Since the declaration is in the
    same file as the caller, the compiler warns about the definition
    without a prior prototype:

    arch/arm64/kernel/suspend.c:35:13: error: no previous prototype for 'cpu_suspend_set_dbg_restorer' [-Werror=missing-prototypes]

    Move it into the corresponding header instead to avoid the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-5-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>