mlxsw: spectrum: Add extack messages for enslave failures
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author David Ahern <dsahern@gmail.com>
commit e58376e1df2aaffbf12753959142a50f824c46ea

mlxsw fails device enslavement for a number of reasons. Use the extack
facility to return an error message to the user stating why the enslave
is failing.

Messages are prefixed with "spectrum" so users know it is a constraint
imposed by the hardware driver. For example:
    $ ip li add br0.11 link br0 type vlan id 11
    $ ip li set swp11 master br0
    Error: spectrum: Enslaving a port to a device that already has an upper device is not supported.

	Signed-off-by: David Ahern <dsahern@gmail.com>
	Reviewed-by: Ido Schimmel <idosch@mellanox.com>
	Tested-by: Ido Schimmel <idosch@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e58376e1df2aaffbf12753959142a50f824c46ea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>