arm64: xor-neon: mark xor_arm64_neon_*() static
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit 320a93d4df48a378ebf923639fa62770676b80db
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:28 +0200

    The only references to these functions are in the same file, and
    there is no prototype, which causes a harmless warning:

    arch/arm64/lib/xor-neon.c:13:6: error: no previous prototype for 'xor_arm64_neon_2' [-Werror=missing-prototypes]
    arch/arm64/lib/xor-neon.c:40:6: error: no previous prototype for 'xor_arm64_neon_3' [-Werror=missing-prototypes]
    arch/arm64/lib/xor-neon.c:76:6: error: no previous prototype for 'xor_arm64_neon_4' [-Werror=missing-prototypes]
    arch/arm64/lib/xor-neon.c:121:6: error: no previous prototype for 'xor_arm64_neon_5' [-Werror=missing-prototypes]

    Fixes: cc9f8349cb33 ("arm64: crypto: add NEON accelerated XOR implementation")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-2-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>