s390/mm: remove unused get_page_state() function
Bugzilla: https://bugzilla.redhat.com/2160210

commit 17ca7df6fcc44470199b66752b8d8459e17aa077
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Fri Nov 18 15:22:14 2022 +0100

    s390/mm: remove unused get_page_state() function

    Remove unused get_page_state() function:

    arch/s390/mm/page-states.c:61:29:
      error: unused function 'get_page_state' [-Werror,-Wunused-function]

    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>