io_uring: Add missing inline to io_uring_cmd_import_fixed() dummy
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2068237

commit 0e0abad2a71bcd7ba0f30e7975f5b4199ade4e60
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Tue Oct 4 14:39:10 2022 +0200

    io_uring: Add missing inline to io_uring_cmd_import_fixed() dummy
    
    If CONFIG_IO_URING is not set:
    
        include/linux/io_uring.h:65:12: error: ‘io_uring_cmd_import_fixed’ defined but not used [-Werror=unused-function]
           65 | static int io_uring_cmd_import_fixed(u64 ubuf, unsigned long len, int rw,
              |            ^~~~~~~~~~~~~~~~~~~~~~~~~
    
    Fix this by adding the missing "inline" keyword.
    
    Fixes: a9216fac3ed8819c ("io_uring: add io_uring_cmd_import_fixed")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Link: https://lore.kernel.org/r/7404b4a696f64e33e5ef3c5bd3754d4f26d13e50.1664887093.git.geert+renesas@glider.be
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>