RDMA/bnxt_re: Fix clang -Wimplicit-fallthrough in bnxt_re_handle_cq_async_error()
JIRA: https://issues.redhat.com/browse/RHEL-3526
JIRA: https://issues.redhat.com/browse/RHEL-11009

commit 9040c0d96fd66e84bb9b017b821e31f2876e949c
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Fri Oct 20 15:17:02 2023 -0700

    RDMA/bnxt_re: Fix clang -Wimplicit-fallthrough in bnxt_re_handle_cq_async_error()

    Clang warns (or errors with CONFIG_WERROR=y):

      drivers/infiniband/hw/bnxt_re/main.c:1114:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
       1114 |         default:
            |         ^
      drivers/infiniband/hw/bnxt_re/main.c:1114:2: note: insert 'break;' to avoid fall-through
       1114 |         default:
            |         ^
            |         break;
      1 error generated.

    Clang is a little more pedantic than GCC, which does not warn when
    falling through to a case that is just break or return. Clang's version
    is more in line with the kernel's own stance in deprecated.rst, which
    states that all switch/case blocks must end in either break,
    fallthrough, continue, goto, or return. Add the missing break to silence
    the warning.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/1950
    Fixes: b02fd3f79ec3 ("RDMA/bnxt_re: Report async events and errors")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20231020-bnxt_re-implicit-fallthrough-v1-1-b5c19534a6c9@kernel.org
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Sreekanth Reddy <sreeredd@redhat.com>