nfs/blocklayout: Fix compilation error (`make W=1`) in bl_write_pagelist()
JIRA: https://issues.redhat.com/browse/RHEL-171546

commit f83c8dda456ce4863f346aa26d88efa276eda35d
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Wed Feb 4 21:21:49 2026 +0100

    nfs/blocklayout: Fix compilation error (`make W=1`) in bl_write_pagelist()

    Clang compiler is not happy about set but unused variable
    (when dprintk() is no-op):

    .../blocklayout/blocklayout.c:384:9: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]

    Remove a leftover from the previous cleanup.

    Fixes: 3a6fd1f004fc ("pnfs/blocklayout: remove read-modify-write handling in bl_write_pagelist")
    Acked-by: Anna Schumaker <anna.schumkaer@oracle.com>
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Olga Kornievskaia <okorniev@redhat.com>