netfilter: nft_bitwise: Adjust parentheses to fix memcmp size argument
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 83c156d3ecc0121d27dc2b7f34e829b265c70c4f

clang warns:

net/netfilter/nft_bitwise.c:138:50: error: size argument in 'memcmp'
call is a comparison [-Werror,-Wmemsize-comparison]
        if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
                                      ~~~~~~~~~~~~~~~~~~^~
net/netfilter/nft_bitwise.c:138:6: note: did you mean to compare the
result of 'memcmp' instead?
        if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
            ^
                                                       )
net/netfilter/nft_bitwise.c:138:32: note: explicitly cast the argument
to size_t to silence this warning
        if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
                                      ^
                                      (size_t)(
1 error generated.

Adjust the parentheses so that the result of the sizeof is used for the
size argument in memcmp, rather than the result of the comparison (which
would always be true because sizeof is a non-zero number).

Fixes: bd8699e9e292 ("netfilter: nft_bitwise: add offload support")
Link: https://github.com/ClangBuiltLinux/linux/issues/638
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit 83c156d3ecc0121d27dc2b7f34e829b265c70c4f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>