ionic: convert Rx queue buffers to use page_pool
JIRA: https://issues.redhat.com/browse/RHEL-64963

Conflicts:
 Missing patch 1a251f52cfdc (minmax: make generic MIN() and MAX()
 macros available everywhere) which adds new MIN/MAX macros that used
 by ionic driver in this patch and that cause compilation error,
 fix that by using the exist min/max operations for linux/minmax.h.

commit ac8813c0ab7d2816946379bff2677a5f725e37bf
Author: Shannon Nelson <shannon.nelson@amd.com>
Date:   Fri Sep 6 16:26:22 2024 -0700

    ionic: convert Rx queue buffers to use page_pool

    Our home-grown buffer management needs to go away and we need
    to be playing nicely with the page_pool infrastructure.  This
    converts the Rx traffic queues to use page_pool.

    Also, since ionic_rx_buf_size() was removed, redefine
    IONIC_PAGE_SIZE to account for IONIC_MAX_BUF_LEN being the
    largest allowed buffer to prevent overflowing u16 variables,
    which could happen when PAGE_SIZE is defined as >= 64KB.

    include/linux/minmax.h:93:37: warning: conversion from 'long unsigned int' to 'u16' {aka 'short unsigned int'} changes value from '65536' to '0' [-Woverflow]

    Signed-off-by: Shannon Nelson <shannon.nelson@amd.com>
    Signed-off-by: Brett Creeley <brett.creeley@amd.com>
    Link: https://patch.msgid.link/20240906232623.39651-7-brett.creeley@amd.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Heib <mheib@redhat.com>