usb: endpoint: convert spaces to tabs
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] endpoint: convert spaces to tabs (Torez Smith) [1303955]
Rebuild_FUZZ: 92.75%
commit-author Kris Borer <kborer@gmail.com>
commit 3290b1b818934a517a593159f39a3651dcf34518

Fix one occurrence of the checkpatch error:

ERROR: code indent should use tabs where possible

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 3290b1b818934a517a593159f39a3651dcf34518)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>