fork: Stop protecting back_fork_cleanup_cgroup_lock with CONFIG_NUMA
Bugzilla: https://bugzilla.redhat.com/2120352

commit 6692c98c7df53502adb8b8b73ab9bcbd399f7a06
Author: Eric W. Biederman <ebiederm@xmission.com>
Date:   Mon Dec 20 10:20:14 2021 -0600

    fork: Stop protecting back_fork_cleanup_cgroup_lock with CONFIG_NUMA

    Mark Brown <broonie@kernel.org> reported:

    > This is also causing further build errors including but not limited to:
    >
    > /tmp/next/build/kernel/fork.c: In function 'copy_process':
    > /tmp/next/build/kernel/fork.c:2106:4: error: label 'bad_fork_cleanup_threadgroup_lock' used but not defined
    >  2106 |    goto bad_fork_cleanup_threadgroup_lock;
    >       |    ^~~~

    It turns out that I messed up and was depending upon a label protected
    by an ifdef.  Move the label out of the ifdef as the ifdef around the label
    no longer makes sense (if it ever did).

    Link: https://lkml.kernel.org/r/YbugCP144uxXvRsk@sirena.org.uk
    Fixes: 40966e316f86 ("kthread: Ensure struct kthread is present for all kthreads")
    Signed-off-by: "Eric W. Biederman" <ebiederm@xmission.com>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>