ASoC: mediatek: mt8186: fix Kconfig dependency
If CONFIG_SND_SOC_MT8186=y and CONFIG_SND_SOC_MT6358 is not set,
make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-, will be failed, like this:

sound/soc/mediatek/mt8186/mt8186-mt6366-common.o: In function `mt8186_mt6366_init':
mt8186-mt6366-common.c:(.text+0x4d): undefined reference to `mt6358_set_mtkaif_protocol'
make: *** [vmlinux] Error 1

To fix this build error, add select SND_SOC_MT6358 to config SND_SOC_MT8186 dependency.

    Fixes: 097e874ad3fc ("ASoC: mediatek: mt8186: add platform driver")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Link: https://lore.kernel.org/r/20220724110619.212774-1-renzhijie2@huawei.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Ren Zhijie <renzhijie2@huawei.com>
Date: Sun Jul 24 19:06:19 2022 +0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit f20d5116b7f3d8d40e1248a59be89e667eaabd62)
Bugzilla: https://bugzilla.redhat.com/2125537