sched/fair: Hide unused init_cfs_bandwidth() stub
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-517.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit c0bdfd72fbfb7319581bd5bb09b4f10979385bac

init_cfs_bandwidth() is only used when CONFIG_FAIR_GROUP_SCHED is
enabled, and without this causes a W=1 warning for the missing prototype:

kernel/sched/fair.c:6131:6: error: no previous prototype for 'init_cfs_bandwidth'

The normal implementation is only defined for CONFIG_CFS_BANDWIDTH,
so the stub exists when CFS_BANDWIDTH is disabled but FAIR_GROUP_SCHED
is enabled.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Reviewed-by: Vincent Guittot <vincent.guittot@linaro.org>
Link: https://lore.kernel.org/r/20230522195021.3456768-4-arnd@kernel.org
(cherry picked from commit c0bdfd72fbfb7319581bd5bb09b4f10979385bac)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>