perf probe: Show better error message when failed to find variable
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author He Kuang <hekuang@huawei.com>
commit 7d5eaba9b33682b734e3a79c21c4a9a5f91624b1

Indicate to check variable location range in error message when we got
failed to find the variable.

Before this patch:

  $ perf probe --add 'generic_perform_write+118 bytes'
  Failed to find the location of bytes at this address.
   Perhaps, it has been optimized out.
    Error: Failed to add events.

After this patch:

  $ perf probe --add 'generic_perform_write+118 bytes'
  Failed to find the location of the 'bytes' variable at this address.
   Perhaps it has been optimized out.
   Use -V with the --range option to show 'bytes' location range.
    Error: Failed to add events.

	Signed-off-by: He Kuang <hekuang@huawei.com>
	Acked-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/r/1431336304-16863-3-git-send-email-hekuang@huawei.com
[ Improve the error message based on lkml thread ]
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 7d5eaba9b33682b734e3a79c21c4a9a5f91624b1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>