Bluetooth: btusb: Remove return statement in btintel_reset_to_bootloader
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit fae7548f25a41443f1f074fcc6d3fed220a42a34

When building with Clang and CONFIG_BT_INTEL unset, the following error
occurs:

In file included from drivers/bluetooth/hci_ldisc.c:34:
drivers/bluetooth/btintel.h:188:2: error: void function
'btintel_reset_to_bootloader' should not return a value [-Wreturn-type]
        return -EOPNOTSUPP;
        ^      ~~~~~~~~~~~
1 error generated.

Remove the unneeded return statement to fix this.

Fixes: b9a2562f4918 ("Bluetooth: btusb: Trigger Intel FW download error recovery")
Link: https://github.com/ClangBuiltLinux/linux/issues/743
	Reported-by: <ci_notify@linaro.org>
	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
(cherry picked from commit fae7548f25a41443f1f074fcc6d3fed220a42a34)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>