soundwire: qcom: use __maybe_unused for swrm_runtime_resume()
swrm_runtime_resume() would not be defined when CONFIG_PM=n

This causes below build failure
drivers/soundwire/qcom.c:1460:12: error: 'swrm_runtime_resume' defined
but not used [-Werror=unused-function]

Mark the resume swrm_runtime_resume() with  __maybe_unused attribute.

    Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
    Link: https://lore.kernel.org/r/20220303110321.23666-1-srinivas.kandagatla@linaro.org
[redo commit title and log]
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Author: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Date: Thu Mar 3 11:03:21 2022 +0000

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 266fa94673d325f489f74d0a9a12024a7f1ee49c)
Bugzilla: https://bugzilla.redhat.com/2065572