Revert "drm/client: Support emergency restore via sysrq for all clients"
JIRA: https://redhat.atlassian.net/browse/RHEL-151751

Upstream Status: RHEL only

This reverts upstream commit 6915190a50e8 which moved the SysRq+v
emergency console restore from drm_fb_helper.c to a new
drm_client_sysrq.c file, making it available to all DRM clients.

The new code uses a u8 argument for the sysrq handler callback, matching
upstream's sysrq.h signature (changed by commit bcb48185eddf "tty:
sysrq: switch sysrq handlers from int to u8"). However, this tree's
include/linux/sysrq.h still uses the original int signature, causing:

  error: initialization of 'void (*)(int)' from incompatible pointer
  type 'void (*)(u8)'

Restore the original sysrq handling in drm_fb_helper.c with the int
handler signature matching this tree's sysrq.h. SysRq+v functionality
is preserved for fbdev clients.

Signed-off-by: Anusha Srivatsa <asrivats@redhat.com>