sched/rt: fix build error when CONFIG_SYSCTL is disable
Bugzilla: https://bugzilla.redhat.com/2115520

commit 28f152cd0926596e69d412467b11b6fe6fe4e864
Author: Baisong Zhong <zhongbaisong@huawei.com>
Date:   Fri Mar 18 10:54:17 2022 +0800

    sched/rt: fix build error when CONFIG_SYSCTL is disable

    Avoid random build errors which do not select
    CONFIG_SYSCTL by depending on it in Kconfig.

    This fixes the following warning:

    In file included from kernel/sched/build_policy.c:43:
    At top level:
    kernel/sched/rt.c:3017:12: error: ‘sched_rr_handler’ defined but not used [-Werror=unused-function]
     3017 | static int sched_rr_handler(struct ctl_table *table, int write, void *buffer,
          |            ^~~~~~~~~~~~~~~~
    kernel/sched/rt.c:2978:12: error: ‘sched_rt_handler’ defined but not used [-Werror=unused-function]
     2978 | static int sched_rt_handler(struct ctl_table *table, int write, void *buffer,
          |            ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [scripts/Makefile.build:310: kernel/sched/build_policy.o] Error 1
    make[1]: *** [scripts/Makefile.build:638: kernel/sched] Error 2
    make[1]: *** Waiting for unfinished jobs....

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Baisong Zhong <zhongbaisong@huawei.com>
    [mcgrof: small build fix, we need sched_rt_can_attach() even
     when CONFIG_SYSCTL is disabled]
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Phil Auld <pauld@redhat.com>