bpf: Have bpf_rdonly_cast() take a const pointer
JIRA: https://issues.redhat.com/browse/RHEL-23649

commit 5b268d1ebcdceacf992dfda8f9031d56005a274e
Author: Daniel Xu <dxu@dxuuu.xyz>
Date:   Sun Feb 4 14:06:34 2024 -0700

    bpf: Have bpf_rdonly_cast() take a const pointer

    Since 20d59ee55172 ("libbpf: add bpf_core_cast() macro"), libbpf is now
    exporting a const arg version of bpf_rdonly_cast(). This causes the
    following conflicting type error when generating kfunc prototypes from
    BTF:

    In file included from skeleton/pid_iter.bpf.c:5:
    /home/dxu/dev/linux/tools/bpf/bpftool/bootstrap/libbpf/include/bpf/bpf_core_read.h:297:14: error: conflicting types for 'bpf_rdonly_cast'
    extern void *bpf_rdonly_cast(const void *obj__ign, __u32 btf_id__k) __ksym __weak;
                 ^
    ./vmlinux.h:135625:14: note: previous declaration is here
    extern void *bpf_rdonly_cast(void *obj__ign, u32 btf_id__k) __weak __ksym;

    This is b/c the kernel defines bpf_rdonly_cast() with non-const arg.
    Since const arg is more permissive and thus backwards compatible, we
    change the kernel definition as well to avoid conflicting type errors.

    Signed-off-by: Daniel Xu <dxu@dxuuu.xyz>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/bpf/dfd3823f11ffd2d4c838e961d61ec9ae8a646773.1707080349.git.dxu@dxuuu.xyz

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>