libbpf: fix ptr to u64 conversion warning on 32-bit platforms
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Andrii Nakryiko <andriin@fb.com>
commit 36db2a94f19ae1fcf1e6d8253df0c32f90f92860

On 32-bit platforms compiler complains about conversion:

libbpf.c: In function ‘perf_event_open_probe’:
libbpf.c:4112:17: error: cast from pointer to integer of different
size [-Werror=pointer-to-int-cast]
  attr.config1 = (uint64_t)(void *)name; /* kprobe_func or uprobe_path */
                 ^

	Reported-by: Matt Hart <matthew.hart@linaro.org>
Fixes: b26500274767 ("libbpf: add kprobe/uprobe attach API")
	Tested-by: Matt Hart <matthew.hart@linaro.org>
	Signed-off-by: Andrii Nakryiko <andriin@fb.com>
	Acked-by: Yonghong Song <yhs@fb.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit 36db2a94f19ae1fcf1e6d8253df0c32f90f92860)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>