selftests/bpf: trace_helpers.c: do not use poisoned type
JIRA: https://issues.redhat.com/browse/RHEL-23649

Conflicts: Commit 21d6169b9606 ("selftests/bpf: fix uprobe offset
calculation in selftests") had changed the u32 to uint32_t because of
a build failure on ppc64.

commit a68b50f47bec8bd6a33b07b7e1562db2553981a7
Author: Shung-Hsi Yu <shung-hsi.yu@suse.com>
Date:   Fri Feb 2 17:55:58 2024 +0800

    selftests/bpf: trace_helpers.c: do not use poisoned type

    After commit c698eaebdf47 ("selftests/bpf: trace_helpers.c: Optimize
    kallsyms cache") trace_helpers.c now includes libbpf_internal.h, and
    thus can no longer use the u32 type (among others) since they are poison
    in libbpf_internal.h. Replace u32 with __u32 to fix the following error
    when building trace_helpers.c on powerpc:

      error: attempt to use poisoned "u32"

    Fixes: c698eaebdf47 ("selftests/bpf: trace_helpers.c: Optimize kallsyms cache")
    Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/r/20240202095559.12900-1-shung-hsi.yu@suse.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>