scsi: lpfc: Resolve inconsistent check of hdwq in lpfc_scsi_cmd_iocb_cmpl
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author James Smart <jsmart2021@gmail.com>
commit ff6bf89717b0dc7b8dd0934d1c065f29069831e7

A prior patch which added support for non-uniform allocation of MSIX
vectors now causes a smatch complaint:

 drivers/scsi/lpfc/lpfc_scsi.c:3674 lpfc_scsi_cmd_iocb_cmpl()
   error: we previously assumed 'phba->sli4_hba.hdwq' could be
          null (see line 3667)

Resolve by removing the unnecessary check for a NULL hdwq table.

Fixes 6a828b0f6192: ("scsi: lpfc: Support non-uniform allocation of MSIX vectors to hardware queues")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Dick Kennedy <dick.kennedy@broadcom.com>
	Signed-off-by: James Smart <jsmart2021@gmail.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit ff6bf89717b0dc7b8dd0934d1c065f29069831e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>