usb: gadget: at91_udc: fix incorrect print type
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 26d81b29249273d39e753cc0c7b0ca62c6a6283f
Author: Miles Chen <miles.chen@mediatek.com>
Date:   Wed Jan 19 10:08:49 2022 +0800

    usb: gadget: at91_udc: fix incorrect print type

    Fix a build error observed with ARCH=arm DEFCONFIG=allmodconfig build.

    drivers/usb/gadget/udc/at91_udc.h:174:42: error: format '%d' expects argument of type 'int', but argument 3 has type 'struct gpio_desc *' [-Werror=format=]

    Fixes: 4a555f2b8d31 ("usb: gadget: at91_udc: Convert to GPIO descriptors")
    Reviewed-by: Macpaul Lin <macpaul.lin@mediatek.com>
    Signed-off-by: Miles Chen <miles.chen@mediatek.com>
    Link: https://lore.kernel.org/r/20220119020849.25732-1-miles.chen@mediatek.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>