mmc: MMC_OMAP_HS should depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] MMC_OMAP_HS should depend on HAS_DMA (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 93.51%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit c00c594d8882c64258150dbbf5ff1c328400c65a

If NO_DMA=y:

    drivers/built-in.o: In function `omap_hsmmc_pre_dma_transfer':
    omap_hsmmc.c:(.text+0x5a0928): undefined reference to `dma_map_sg'
    drivers/built-in.o: In function `omap_hsmmc_dma_cleanup':
    omap_hsmmc.c:(.text+0x5a0e8e): undefined reference to `dma_unmap_sg'
    drivers/built-in.o: In function `omap_hsmmc_dma_callback':
    omap_hsmmc.c:(.text+0x5a1f58): undefined reference to `dma_unmap_sg'
    drivers/built-in.o: In function `omap_hsmmc_post_req':
    omap_hsmmc.c:(.text+0x5a2082): undefined reference to `dma_unmap_sg'

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
(cherry picked from commit c00c594d8882c64258150dbbf5ff1c328400c65a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>