pkt_sched: fq: prefetch() fix
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Eric Dumazet <edumazet@google.com>
commit 08f89b981b0e6b46058dae2957241d4099129521

kbuild bot reported following m68k build error :

  net/sched/sch_fq.c: In function 'fq_dequeue':
>> net/sched/sch_fq.c:491:2: error: implicit declaration of function
'prefetch' [-Werror=implicit-function-declaration]
   cc1: some warnings being treated as errors

While we are fixing this, move this prefetch() call a bit earlier.

	Reported-by: Wu Fengguang <fengguang.wu@intel.com>
	Signed-off-by: Eric Dumazet <edumazet@google.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 08f89b981b0e6b46058dae2957241d4099129521)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>