usb: typec: fusb302: mark OF related data as maybe unused
JIRA: https://issues.redhat.com/browse/RHEL-13058

commit b16de6a5c70b53bee495a42ebe74ccca076a3e26
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Fri, 10 Mar 2023 23:29:37 +0100

  The driver can be compile tested with !CONFIG_OF making certain data
  unused:

    drivers/usb/typec/tcpm/fusb302.c:1816:34: error: ‘fusb302_dt_match’ defined but not used [-Werror=unused-const-variable=]

  Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
  Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
  Reviewed-by: Guenter Roeck <linux@roeck-us.net>
  Link: https://lore.kernel.org/r/20230310222937.315773-2-krzysztof.kozlowski@linaro.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>