selftests/bpf: Fix arena_spin_lock compilation on PowerPC
JIRA: https://issues.redhat.com/browse/RHEL-78202

commit 1f375aef6cc0ae03ea714bff58ba7be1ca95997c
Author: Kumar Kartikeya Dwivedi <memxor@gmail.com>
Date:   Tue Mar 11 08:42:44 2025 -0700

    selftests/bpf: Fix arena_spin_lock compilation on PowerPC
    
    Venkat reported a compilation error for BPF selftests on PowerPC [0].
    The crux of the error is the following message:
      In file included from progs/arena_spin_lock.c:7:
      /root/bpf-next/tools/testing/selftests/bpf/bpf_arena_spin_lock.h:122:8:
      error: member reference base type '__attribute__((address_space(1)))
      u32' (aka '__attribute__((address_space(1))) unsigned int') is not a
      structure or union
         122 |         old = atomic_read(&lock->val);
    
    This is because PowerPC overrides the qspinlock type changing the
    lock->val member's type from atomic_t to u32.
    
    To remedy this, import the asm-generic version in the arena spin lock
    header, name it __qspinlock (since it's aliased to arena_spinlock_t, the
    actual name hardly matters), and adjust the selftest to not depend on
    the type in vmlinux.h.
    
      [0]: https://lore.kernel.org/bpf/7bc80a3b-d708-4735-aa3b-6a8c21720f9d@linux.ibm.com
    
    Fixes: 88d706ba7cc5 ("selftests/bpf: Introduce arena spin lock")
    Reported-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Link: https://lore.kernel.org/bpf/20250311154244.3775505-1-memxor@gmail.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Gregory Bell <grbell@redhat.com>