perf cs-etm: Add missing case value
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Solomon Tan <solomonbobstoner@gmail.com>
commit c8fa7a807f3c5f946bd92076fbaf7826edb650dc

The following error was thrown when compiling `tools/perf` using OpenCSD
v0.11.1. This patch fixes said error.

    CC       util/intel-pt-decoder/intel-pt-log.o
    CC       util/cs-etm-decoder/cs-etm-decoder.o
  util/cs-etm-decoder/cs-etm-decoder.c: In function
  ‘cs_etm_decoder__buffer_range’:
  util/cs-etm-decoder/cs-etm-decoder.c:370:2: error: enumeration value
  ‘OCSD_INSTR_WFI_WFE’ not handled in switch [-Werror=switch-enum]
    switch (elem->last_i_type) {
    ^~~~~~
    CC       util/intel-pt-decoder/intel-pt-decoder.o
  cc1: all warnings being treated as errors

Because `OCSD_INSTR_WFI_WFE` case was added only in v0.11.0, the minimum
required OpenCSD library version for this patch is no longer v0.10.0.

	Signed-off-by: Solomon Tan <solomonbobstoner@gmail.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Mathieu Poirier <mathieu.poirier@linaro.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Robert Walker <robert.walker@arm.com>
	Cc: Suzuki K Poulouse <suzuki.poulose@arm.com>
	Cc: linux-arm-kernel@lists.infradead.org
Link: http://lkml.kernel.org/r/20190322052255.GA4809@w-OptiPlex-7050
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit c8fa7a807f3c5f946bd92076fbaf7826edb650dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>