PCI: rcar-gen4: Fix -Wvoid-pointer-to-enum-cast error
JIRA: https://issues.redhat.com/browse/RHEL-28627
Upstream Status: 7682f19c3c8c709ff4ef0e1d475f00907ade868f

commit 7682f19c3c8c709ff4ef0e1d475f00907ade868f
Author: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Date:   Wed Dec 20 14:38:29 2023 +0900

    PCI: rcar-gen4: Fix -Wvoid-pointer-to-enum-cast error

    When building with clang 18 with the -Werror compiler option enabled,
    the following error will be reported:

      drivers/pci/controller/dwc/pcie-rcar-gen4.c:439:15: error: cast to smaller integer type 'enum dw_pcie_device_mode' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]
        439 |         rcar->mode = (enum dw_pcie_device_mode)of_device_get_match_data(&rcar->pdev->dev);

    To fix this issue, cast the data the of_device_get_match_data() helper
    returns to uintptr_t rather than the dw_pcie_device_mode enum.

    [kwilczynski: commit log]
    Link: https://lore.kernel.org/linux-pci/20231220053829.1921187-7-yoshihiro.shimoda.uh@renesas.com
    Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@kernel.org>
    Reviewed-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Reviewed-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>