pinctrl: intel: mark intel_pin_to_gpio __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 55dac43747be98516a337285428806d177afaa3a

The intel_pin_to_gpio() function is only called by the
PM support functions and causes a warning when those are disabled:

drivers/pinctrl/intel/pinctrl-intel.c:841:12: error: unused function 'intel_pin_to_gpio' [-Werror,-Wunused-function]

Mark it __maybe_unused to suppress the warning.

	Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Chris Chiu <chiu@endlessm.com>
	Acked-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
(cherry picked from commit 55dac43747be98516a337285428806d177afaa3a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>