iov_iter: Fix build error without CONFIG_CRYPTO
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 27fad74a5a77fe2e1f876db7bf27efcf2ec304b2

If CONFIG_CRYPTO is not set or set to m,
gcc building warn this:

lib/iov_iter.o: In function `hash_and_copy_to_iter':
iov_iter.c:(.text+0x9129): undefined reference to `crypto_stats_get'
iov_iter.c:(.text+0x9152): undefined reference to `crypto_stats_ahash_update'

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: d05f443554b3 ("iov_iter: introduce hash_and_copy_to_iter helper")
	Suggested-by: Al Viro <viro@zeniv.linux.org.uk>
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
(cherry picked from commit 27fad74a5a77fe2e1f876db7bf27efcf2ec304b2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>