ath9k: htc: clean up statistics macros
jira LE-1907
cve CVE-2022-1679
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Pavel Skripkin <paskripkin@gmail.com>
commit d7fc76039b74ad37b7056d5607b05d7cb31a5404

I've changed *STAT_* macros a bit in previous patch and I seems like
they become really unreadable. Align these macros definitions to make
code cleaner and fix folllowing checkpatch warning

ERROR: Macros with complex values should be enclosed in parentheses

Also, statistics macros now accept an hif_dev as argument, since
macros that depend on having a local variable with a magic name
don't abide by the coding style.

No functional change

	Suggested-by: Jeff Johnson <quic_jjohnson@quicinc.com>
	Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>
	Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/ebb2306d06a496cd1b032155ae52fdc5fa8cc2c5.1655145743.git.paskripkin@gmail.com
(cherry picked from commit d7fc76039b74ad37b7056d5607b05d7cb31a5404)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>