remoteproc: imx_dsp_rproc: use modern pm_ops
Bugzilla: https://bugzilla.redhat.com/2230679

commit 47f64e7ef95a58e5c56f2ec62cbadbe868661149
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Apr 20 23:36:04 2023 +0200

    remoteproc: imx_dsp_rproc: use modern pm_ops

    Without CONFIG_PM, the driver warns about unused functions:

    drivers/remoteproc/imx_dsp_rproc.c:1210:12: error: 'imx_dsp_runtime_suspend' defined but not used [-Werror=unused-function]
     1210 | static int imx_dsp_runtime_suspend(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~~
    drivers/remoteproc/imx_dsp_rproc.c:1178:12: error: 'imx_dsp_runtime_resume' defined but not used [-Werror=unused-function]
     1178 | static int imx_dsp_runtime_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~~

    Change the old SET_SYSTEM_SLEEP_PM_OPS()/SET_RUNTIME_PM_OPS()
    helpers to their modern replacements that avoid the warning,
    and remove the now unnecessary __maybe_unused annotations
    on the other PM helper functions.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Mukesh Ojha <quic_mojha@quicinc.com>
    Reviewed-by: Iuliana Prodan <iuliana.prodan@nxp.com>
    Link: https://lore.kernel.org/r/20230420213610.2219080-1-arnd@kernel.org
    Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>

Signed-off-by: Steve Best <sbest@redhat.com>