mips: boot/compressed: use __NO_FORTIFY
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139493

commit 62776e4378ae9086115ffd6f8bd9b9c0fe6e6809
Author: John Thomson <git@johnthomson.fastmail.com.au>
Date:   Tue Nov 1 03:07:49 2022 +1000

    mips: boot/compressed: use __NO_FORTIFY

    In the mips CONFIG_SYS_SUPPORTS_ZBOOT kernel, fix the compile error
    when using CONFIG_FORTIFY_SOURCE=y

    LD      vmlinuz
    mipsel-openwrt-linux-musl-ld: arch/mips/boot/compressed/decompress.o: in
    function `decompress_kernel':
    ./include/linux/decompress/mm.h:(.text.decompress_kernel+0x177c):
    undefined reference to `warn_slowpath_fmt'

    kernel test robot helped identify this as related to fortify. The error
    appeared with commit 54d9469bc515 ("fortify: Add run-time WARN for
    cross-field memcpy()")
    Link: https://lore.kernel.org/r/202209161144.x9xSqNQZ-lkp@intel.com/

    Resolve this in the same style as commit cfecea6ead5f ("lib/string:
    Move helper functions out of string.c")

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: 54d9469bc515 ("fortify: Add run-time WARN for cross-field memcpy()")
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: John Thomson <git@johnthomson.fastmail.com.au>
    Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>

Signed-off-by: Josef Oskera <joskera@redhat.com>