iommufd/selftest: Prevent module/builtin conflicts in kconfig
JIRA: https://issues.redhat.com/browse/RHEL-147902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Conflicts: Context diff due to out of order backports.

commit 7adfd682745a41fdf0279e4457d11fffab145a8f
Author: Jason Gunthorpe <jgg@nvidia.com>
Date: Tue Jan 6 15:22:12 2026 -0400

    iommufd/selftest: Prevent module/builtin conflicts in kconfig

    The selftest now depends on the AMDv1 page table, however the selftest
    kconfig itself is just an sub-option of the main IOMMUFD module kconfig.

    This means it cannot be modular and so kconfig allowed a modular
    IOMMU_PT_AMDV1 with a built in IOMMUFD. This causes link failures:

       ld: vmlinux.o: in function `mock_domain_alloc_pgtable.isra.0':
       selftest.c:(.text+0x12e8ad3): undefined reference to `pt_iommu_amdv1_init'
       ld: vmlinux.o: in function `BSWAP_SHUFB_CTL':
       sha1-avx2-asm.o:(.rodata+0xaa36a8): undefined reference to `pt_iommu_amdv1_read_and_clear_dirty'
       ld: sha1-avx2-asm.o:(.rodata+0xaa36f0): undefined reference to `pt_iommu_amdv1_map_pages'
       ld: sha1-avx2-asm.o:(.rodata+0xaa36f8): undefined reference to `pt_iommu_amdv1_unmap_pages'
       ld: sha1-avx2-asm.o:(.rodata+0xaa3720): undefined reference to `pt_iommu_amdv1_iova_to_phys'

    Adjust the kconfig to disable IOMMUFD_TEST if IOMMU_PT_AMDV1 is incompatible.

    Fixes: e93d5945ed5b ("iommufd: Change the selftest to use iommupt instead of xarray")
    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202512210135.freQWpxa-lkp@intel.com/
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
    Signed-off-by: Joerg Roedel <joerg.roedel@amd.com>

(cherry picked from commit 7adfd682745a41fdf0279e4457d11fffab145a8f)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>