ALSA: hda - Fix build error in hda_tegra.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [alsa] hda: Fix build error in hda_tegra.c (Jaroslav Kysela) [1112200]
Rebuild_FUZZ: 88.31%
commit-author Takashi Iwai <tiwai@suse.de>
commit 178942b69f4eb695bfb92742b6082052d6730ca0
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-229.el7/178942b6.failed

The "list" field has been omitted from struct azx, but its
initialization remained mistakenly in hda_tegra.c, which leads to a
compile error:
   sound/pci/hda/hda_tegra.c: In function 'hda_tegra_create':
   sound/pci/hda/hda_tegra.c:481:22: error: 'struct azx' has no member
named 'list'

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
Fixes: 9a34af4a3327 ('ALSA: hda - Move more PCI-controller-specific stuff from generic code')
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 178942b69f4eb695bfb92742b6082052d6730ca0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	sound/pci/hda/hda_tegra.c