audit: mark audit_log_vformat() with __printf() attribute
JIRA: https://issues.redhat.com/browse/RHEL-145403

commit baaba7b4483731592334611f4170160ae8a4d5f7
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Thu Mar 13 10:52:39 2025 +0200

    audit: mark audit_log_vformat() with __printf() attribute

    audit_log_vformat() is using printf() type of format, and GCC compiler
    (Debian 14.2.0-17) is not happy about this:

    kernel/audit.c:1978:9: error: function ‘audit_log_vformat’
      might be a candidate for ‘gnu_printf’ format attribute
    kernel/audit.c:1987:17: error: function ‘audit_log_vformat’
      might be a candidate for ‘gnu_printf’ format attribute

    Fix the compilation errors (`make W=1` when CONFIG_WERROR=y, which is
    default) by adding __printf() attribute.

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    [PM: commit description line wrap fixes]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ricardo Robaina <rrobaina@redhat.com>