i40e: mark PM functions as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 254d152a216750f508442cc3e502130e5f539ab4

A cleanup of the PM code left an incorrect #ifdef in place, leading
to a harmless build warning:

drivers/net/ethernet/intel/i40e/i40e_main.c:12223:12: error: 'i40e_resume' defined but not used [-Werror=unused-function]
drivers/net/ethernet/intel/i40e/i40e_main.c:12185:12: error: 'i40e_suspend' defined but not used [-Werror=unused-function]

It's easier to use __maybe_unused attributes here, since you
can't pick the wrong one.

Fixes: 0e5d3da40055 ("i40e: use newer generic PM support instead of legacy PM callbacks")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
	Acked-by: Jacob Keller <jacob.e.keller@intel.com>
	Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
(cherry picked from commit 254d152a216750f508442cc3e502130e5f539ab4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>