net: ti: icssg-prueth: add dependency for PTP
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit e083dd032eeba9e28e4703cd5aaf4a409ebc3837
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Feb 10 22:11:52 2024 -0800

    net: ti: icssg-prueth: add dependency for PTP

    When CONFIG_PTP_1588_CLOCK=m and CONFIG_TI_ICSSG_PRUETH=y, there are
    kconfig dependency warnings and build errors referencing PTP functions.

    Fix these by making TI_ICSSG_PRUETH depend on PTP_1588_CLOCK_OPTIONAL.

    Fixes these build errors and warnings:

    WARNING: unmet direct dependencies detected for TI_ICSS_IEP
      Depends on [m]: NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_TI [=y] && PTP_1588_CLOCK_OPTIONAL [=m] && TI_PRUSS [=y]
      Selected by [y]:
      - TI_ICSSG_PRUETH [=y] && NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_TI [=y] && PRU_REMOTEPROC [=y] && ARCH_K3 [=y] && OF [=y] && TI_K3_UDMA_GLUE_LAYER [=y]

    aarch64-linux-ld: drivers/net/ethernet/ti/icssg/icss_iep.o: in function `icss_iep_get_ptp_clock_idx':
    icss_iep.c:(.text+0x1d4): undefined reference to `ptp_clock_index'
    aarch64-linux-ld: drivers/net/ethernet/ti/icssg/icss_iep.o: in function `icss_iep_exit':
    icss_iep.c:(.text+0xde8): undefined reference to `ptp_clock_unregister'
    aarch64-linux-ld: drivers/net/ethernet/ti/icssg/icss_iep.o: in function `icss_iep_init':
    icss_iep.c:(.text+0x176c): undefined reference to `ptp_clock_register'

    Fixes: 186734c15886 ("net: ti: icssg-prueth: add packet timestamping and ptp support")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Roger Quadros <rogerq@ti.com>
    Cc: Md Danish Anwar <danishanwar@ti.com>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: Eric Dumazet <edumazet@google.com>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: Paolo Abeni <pabeni@redhat.com>
    Cc: netdev@vger.kernel.org
    Reviewed-by: MD Danish Anwar <danishanwar@ti.com>
    Link: https://lore.kernel.org/r/20240211061152.14696-1-rdunlap@infradead.org
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>