perf tools: Fix is_compat_mode build break in ppc64
JIRA: https://issues.redhat.com/browse/RHEL-77936

upstream
========
commit 7e442be7015af524d2b5fb84f0ff04a44501542b
Author: Likhitha Korrapati <likhitha@linux.ibm.com>
Date: Fri Mar 21 15:37:26 2025 +0530

description
===========
Commit 54f9aa1092457 ("tools/perf/powerpc/util: Add support to
handle compatible mode PVR for perf json events") introduced
to select proper JSON events in case of compat mode using
auxiliary vector. But this caused a compilation error in ppc64
Big Endian.

arch/powerpc/util/header.c: In function 'is_compat_mode':
arch/powerpc/util/header.c:20:21: error: cast to pointer from
integer of different size [-Werror=int-to-pointer-cast]
   20 |         if (!strcmp((char *)platform, (char *)base_platform))
      |                     ^
arch/powerpc/util/header.c:20:39: error: cast to pointer from
integer of different size [-Werror=int-to-pointer-cast]
   20 |         if (!strcmp((char *)platform, (char *)base_platform))
      |

Commit saved the getauxval(AT_BASE_PLATFORM) and getauxval(AT_PLATFORM)
return values in u64 which causes the compilation error.

Patch fixes this issue by changing u64 to "unsigned long".

Fixes: 54f9aa1092457 ("tools/perf/powerpc/util: Add support to handle compatible mode PVR for perf json events")
    Signed-off-by: Likhitha Korrapati <likhitha@linux.ibm.com>
    Reviewed-by: Athira Rajeev <atrajeev@linux.ibm.com>
    Link: https://lore.kernel.org/r/20250321100726.699956-1-likhitha@linux.ibm.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>