bpf: Add explicit cast to 'void *' for __BPF_DISPATCHER_UPDATE()
Bugzilla: https://bugzilla.redhat.com/2166911

commit a679120edfcf3d63f066f53afd425d51b480e533
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Nov 7 10:07:11 2022 -0700

    bpf: Add explicit cast to 'void *' for __BPF_DISPATCHER_UPDATE()
    
    When building with clang:
    
      kernel/bpf/dispatcher.c:126:33: error: pointer type mismatch ('void *' and 'unsigned int (*)(const void *, const struct bpf_insn *, bpf_func_t)' (aka 'unsigned int (*)(const void *, const struct bpf_insn *, unsigned int (*)(const void *, const struct bpf_insn *))')) [-Werror,-Wpointer-type-mismatch]
              __BPF_DISPATCHER_UPDATE(d, new ?: &bpf_dispatcher_nop_func);
                                         ~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~
      ./include/linux/bpf.h:1045:54: note: expanded from macro '__BPF_DISPATCHER_UPDATE'
              __static_call_update((_d)->sc_key, (_d)->sc_tramp, (_new))
                                                                  ^~~~
      1 error generated.
    
    The warning is pointing out that the type of new ('void *') and
    &bpf_dispatcher_nop_func are not compatible, which could have side
    effects coming out of a conditional operator due to promotion rules.
    
    Add the explicit cast to 'void *' to make it clear that this is
    expected, as __BPF_DISPATCHER_UPDATE() expands to a call to
    __static_call_update(), which expects a 'void *' as its final argument.
    
    Fixes: c86df29d11df ("bpf: Convert BPF_DISPATCHER to use static_call() (not ftrace)")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1755
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: "kernelci.org bot" <bot@kernelci.org>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Björn Töpel <bjorn@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/r/20221107170711.42409-1-nathan@kernel.org
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Artem Savkov <asavkov@redhat.com>