openvswitch: Fix dependency on IPv6 defrag.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [net] openvswitch: Fix dependency on IPv6 defrag (Thadeu Lima de Souza Cascardo) [1274845]
Rebuild_FUZZ: 98.82%
commit-author Joe Stringer <joestringer@nicira.com>
commit 38c089d1d8d058f5dff018a811568aa8e8bc47fc
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/38c089d1.failed

When NF_CONNTRACK is built-in, NF_DEFRAG_IPV6 is a module, and
OPENVSWITCH is built-in, the following build error would occur:

net/built-in.o: In function `ovs_ct_execute':
(.text+0x10f587): undefined reference to `nf_ct_frag6_gather'

Fixes: 7f8a436eaa2c ("openvswitch: Add conntrack action")
	Reported-by: Jim Davis <jim.epost@gmail.com>
	Signed-off-by: Joe Stringer <joestringer@nicira.com>
	Acked-by: Pravin B Shelar <pshelar@nicira.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 38c089d1d8d058f5dff018a811568aa8e8bc47fc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/openvswitch/Kconfig