selftests: nft_nat: switch port shadow test cases to socat
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2006169
Upstream Status: commit a2acf0c0e2da2

commit a2acf0c0e2da29950d0361a3b5ea05e8d0351dfe
Author: Florian Westphal <fw@strlen.de>
Date:   Thu Nov 11 18:23:30 2021 +0100

    selftests: nft_nat: switch port shadow test cases to socat

    There are now at least three distinct flavours of netcat/nc tool:
    'original' version, one version ported from openbsd and nmap-ncat.

    The script only works with original because it sets SOREUSEPORT option.

    Other nc versions return 'port already in use' error and port shadow test fails:

    PASS: inet IPv6 redirection for ns2-hMHcaRvx
    nc: bind failed: Address already in use
    ERROR: portshadow test default: got reply from "ROUTER", not CLIENT as intended

    Switch to socat instead.

    Reported-by: kernel test robot <oliver.sang@intel.com>
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>