ASoC: atmel: fix build error with CONFIG_SND_ATMEL_SOC_DMA=m
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: atmel: fix build error with CONFIG_SND_ATMEL_SOC_DMA=m (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 95.24%
commit-author Chen Zhou <chenzhou10@huawei.com>
commit 8fea78029f5e6ed734ae1957bef23cfda1af4354

If CONFIG_SND_ATMEL_SOC_DMA=m, build error:

sound/soc/atmel/atmel_ssc_dai.o: In function `atmel_ssc_set_audio':
(.text+0x7cd): undefined reference to `atmel_pcm_dma_platform_register'

Function atmel_pcm_dma_platform_register is defined under
CONFIG SND_ATMEL_SOC_DMA, so select SND_ATMEL_SOC_DMA in
CONFIG SND_ATMEL_SOC_SSC, same to CONFIG_SND_ATMEL_SOC_PDC.

	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Chen Zhou <chenzhou10@huawei.com>
Link: https://lore.kernel.org/r/20200113133242.144550-1-chenzhou10@huawei.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 8fea78029f5e6ed734ae1957bef23cfda1af4354)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>