swim3: mark swim3_init() static
JIRA: https://issues.redhat.com/browse/RHEL-25988

commit d21fed50c523d87af6456697ad09378060c4f09a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 10 16:19:23 2023 +0200

    swim3: mark swim3_init() static

    This is the module init function, which by definition is used only
    locally, so mark it static to avoid a warning:

    drivers/block/swim3.c:1280:5: error: no previous prototype for 'swim3_init' [-Werror=missing-prototypes]

    Reviewed-by: Jack Wang <jinpu.wang@ionos.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>