iw_cxgb4: add INFINIBAND_ADDR_TRANS dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit e4b1672ac0a54c7740cbc4ff39dfdc56182236cb

The newly added fill_res_ep_entry function fails to link if
CONFIG_INFINIBAND_ADDR_TRANS is not set:

drivers/infiniband/hw/cxgb4/restrack.o: In function `fill_res_ep_entry':
restrack.c:(.text+0x3cc): undefined reference to `rdma_res_to_id'
restrack.c:(.text+0x3d0): undefined reference to `rdma_iw_cm_id'

This adds a Kconfig dependency for the driver.

Fixes: 116aeb887371 ("iw_cxgb4: provide detailed provider-specific CM_ID information")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Greg Thelen <gthelen@google.com>
	Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit e4b1672ac0a54c7740cbc4ff39dfdc56182236cb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>