net/mlxfw: Properly handle dependancy with non-loadable mlx5
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [netdrv] mlxfw: Properly handle dependancy with non-loadable mlx5 (Don Dutile) [1499363 1466367]
Rebuild_FUZZ: 96.55%
commit-author Or Gerlitz <ogerlitz@mellanox.com>
commit c1c1d86bdea45880c1843087d40498127d4293c9
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/c1c1d86b.failed

If mlx5 is set to be built-in and mlxfw as a module, we
get a link error:

drivers/built-in.o: In function `mlx5_firmware_flash':
(.text+0x5aed72): undefined reference to `mlxfw_firmware_flash'

Since we don't want to mandate selecting mlxfw for mlx5 users, we
use the IS_REACHABLE macro to make sure that a stub is exposed
to the caller.

	Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
	Reported-by: Jakub Kicinski <kubakici@wp.pl>
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c1c1d86bdea45880c1843087d40498127d4293c9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/mellanox/mlxfw/mlxfw.h