net/mlx5e: Make mlx5e_dcbnl_ops static
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Saeed Mahameed <saeedm@mellanox.com>
commit eb24387183d37f2f4f456654ef92679b1556f8df

Fix sparse warning:
drivers/net/ethernet/mellanox/mlx5/core/en_dcbnl.c:988:29:
error: symbol 'mlx5e_dcbnl_ops' was not declared. Should it be static?

	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit eb24387183d37f2f4f456654ef92679b1556f8df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>