ALSA: usb-line6: use the same declaration as definition in header for MIDI manufacturer ID
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Takashi Sakamoto <o-takashi@sakamocchi.jp>
commit 8da08ca03b73593d5299893bf29fc08569c3fb5f

Currently, usb-line6 module exports an array of MIDI manufacturer ID and
usb-pod module uses it. However, the declaration is not the definition in
common header. The difference is explicit length of array. Although
compiler calculates it and everything goes well, it's better to use the
same representation between definition and declaration.

This commit fills the length of array for usb-line6 module. As a small
good sub-effect, this commit suppress below warnings from static analysis
by sparse v0.5.0.

sound/usb/line6/driver.c:274:43: error: cannot size expression
sound/usb/line6/driver.c:275:16: error: cannot size expression
sound/usb/line6/driver.c:276:16: error: cannot size expression
sound/usb/line6/driver.c:277:16: error: cannot size expression

Fixes: 705ececd1c60 ("Staging: add line6 usb driver")
	Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 8da08ca03b73593d5299893bf29fc08569c3fb5f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>