PCI: endpoint: remove bogus return in pci_epf_device_remove()
Upstream Status: RHEL Only
JIRA: https://issues.redhat.com/browse/RHEL-47218

When upstream commit fc7a6209d571 ("bus: Make remove callback return
void") was backported into CS9 via commit a5384e8ee517 ("bus: Make
remove callback return void"), the 'return 0' was not included for
this driver. This is causing the following compiler error now that
this driver is enabled:

    drivers/pci/endpoint/pci-epf-core.c: In function ‘pci_epf_device_remove’:
    drivers/pci/endpoint/pci-epf-core.c:509:16: error: ‘return’ with a value, in function returning void [-Werror=return-type]
      509 |         return 0;
          |                ^
    drivers/pci/endpoint/pci-epf-core.c:500:13: note: declared here
      500 | static void pci_epf_device_remove(struct device *dev)
          |             ^~~~~~~~~~~~~~~~~~~~~

Let's fix this by adding the 'return 0' that was missing from that
backport.

Fixes: a5384e8ee517 ("bus: Make remove callback return void")
Signed-off-by: Brian Masney <bmasney@redhat.com>
(cherry picked from commit 349ae41a2a41b4c197fabd447adffdca8f2df0fd)
Signed-off-by: Radu Rendec <rrendec@redhat.com>