md/raid1-10: fix casting from randomized structure in raid1_submit_write()
JIRA: https://issues.redhat.com/browse/RHEL-3359

commit b5a99602b74bbfa655be509c615181dd95b0719e
Author: Yu Kuai <yukuai3@huawei.com>
Date:   Fri Jun 16 09:21:36 2023 +0800

    md/raid1-10: fix casting from randomized structure in raid1_submit_write()

    Following build error triggered while build with clang version 17.0.0
    with W=1(this can't be reporduced with gcc 13.1.0):

    drivers/md/raid1-10.c:117:25: error: casting from randomized structure
    pointer type 'struct block_device *' to 'struct md_rdev *'
         117 |         struct md_rdev *rdev = (struct md_rdev *)bio->bi_bdev;
             |                                ^

    Fix this by casting 'bio->bi_bdev' to 'void *', as it used to be.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202306142042.fmjfmTF8-lkp@intel.com/
    Fixes: 8295efbe68c0 ("md/raid1-10: factor out a helper to submit normal write")
    Signed-off-by: Yu Kuai <yukuai3@huawei.com>
    Signed-off-by: Song Liu <song@kernel.org>
    Link: https://lore.kernel.org/r/20230616012136.3047071-1-yukuai1@huaweicloud.com

Signed-off-by: Nigel Croxon <ncroxon@redhat.com>