ASoC: max98927: add missing header file
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit bb45f689fa62110c263c86070bfcb9ecbb6e1e23

Add a header file that provides the missing function prototypes
and macro to fix these build errors (seen on arch/alpha/):

../sound/soc/codecs/max98927.c: In function 'max98927_i2c_probe':
../sound/soc/codecs/max98927.c:902:19: error: implicit declaration of function 'devm_gpiod_get_optional'; did you mean 'devm_regulator_get_optional'? [-Werror=implicit-function-declaration]
  902 |                 = devm_gpiod_get_optional(&i2c->dev, "reset", GPIOD_OUT_HIGH);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
../sound/soc/codecs/max98927.c:902:63: error: 'GPIOD_OUT_HIGH' undeclared (first use in this function); did you mean 'GPIOF_INIT_HIGH'?
  902 |                 = devm_gpiod_get_optional(&i2c->dev, "reset", GPIOD_OUT_HIGH);
      |                                                               ^~~~~~~~~~~~~~
../sound/soc/codecs/max98927.c:909:17: error: implicit declaration of function 'gpiod_set_value_cansleep'; did you mean 'gpio_set_value_cansleep'? [-Werror=implicit-function-declaration]
  909 |                 gpiod_set_value_cansleep(max98927->reset_gpio, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 4d67dc1998f1 ("ASoC: max98927: Handle reset gpio when probing i2c")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Reported-by: kernel test robot <lkp@intel.com>
	Cc: Alejandro Tafalla <atafalla@dnyon.com>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: Liam Girdwood <lgirdwood@gmail.com>
	Cc: Takashi Iwai <tiwai@suse.com>
	Cc: alsa-devel@alsa-project.org
Link: https://lore.kernel.org/r/20220129080259.19964-1-rdunlap@infradead.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit bb45f689fa62110c263c86070bfcb9ecbb6e1e23)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>