s390/debug: remove function type cast
JIRA: https://issues.redhat.com/browse/RHEL-54248

commit a78c2e31f6c769d7746989273cf9348944cf504d
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Fri Nov 18 15:21:02 2022 +0100

    s390/debug: remove function type cast

    clang warns about an incompatible function type cast:

      CC      arch/s390/kernel/debug.o
    arch/s390/kernel/debug.c:142:2: error: cast from 'int (*)(debug_info_t *, struct debug_view *, char *, debug_sprintf_entry_t *)' (aka 'int (*)(struct debug_info *, struct debug_view *, char *, debug_sprintf_entry_t *)') to 'debug_format_proc_t *' (aka 'int (*)(struct debug_info *, struct debug_view *, char *, const char *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
            (debug_format_proc_t *)&debug_sprintf_format_fn,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Get rid of this warning by changing debug_sprintf_format_fn() so it matches
    the debug_format_proc_t function type, and do the cast of the last
    parameter within the function itself.
    This is the standard way of handling such cases anyway.

    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
    Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>