powerpc/kexec_file: fix implicit decl error
Bugzilla: https://bugzilla.redhat.com/2167267

commit 97e45d469eb180a7bd2809e4e079331552c73e42
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sat Feb 4 09:22:06 2023 -0800

    powerpc/kexec_file: fix implicit decl error

    kexec (PPC64) code calls memory_hotplug_max(). Add the header
    declaration for it from <asm/mmzone.h>. Using <linux/mmzone.h> does not
    work since the #include for <asm/mmzone.h> depends on CONFIG_NUMA=y,
    which is not always set.

    Fixes this build error/warning:

      arch/powerpc/kexec/file_load_64.c: In function 'kexec_extra_fdt_size_ppc64':
      arch/powerpc/kexec/file_load_64.c:993:33: error: implicit declaration of function 'memory_hotplug_max'
      993 |                 usm_entries = ((memory_hotplug_max() / drmem_lmb_size()) +
          |                                 ^~~~~~~~~~~~~~~~~~

    Fixes: fc546faa5595 ("powerpc/kexec_file: Count hot-pluggable memory in FDT estimate")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20230204172206.7662-1-rdunlap@infradead.org

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>