crypto: qat - add missing header inclusion
JIRA: https://issues.redhat.com/browse/RHEL-94928
Upstream Status: merged into the linux.git

commit 61fc01f8f7f8e299b9fed5a5e5e068ef0e40593d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 22 11:21:41 2025 +0100

    crypto: qat - add missing header inclusion

    Without this header, the build of the new qat_6xxx driver fails when
    CONFIG_PCI_IOV is not set:

        In file included from drivers/crypto/intel/qat/qat_common/adf_gen6_shared.c:7:
        drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h: In function 'adf_gen4_init_pf_pfvf_ops':
        drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h:13:34: error: 'adf_pfvf_comms_disabled' undeclared (first use in this function)
           13 |         pfvf_ops->enable_comms = adf_pfvf_comms_disabled;
              |                                  ^~~~~~~~~~~~~~~~~~~~~~~

    Fixes: 17fd7514ae68 ("crypto: qat - add qat_6xxx driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladislav Dronov <vdronov@redhat.com>