iommu/arm-smmu-v3: Fix compilation when CONFIG_CMA=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [iommu] arm-smmu-v3: Fix compilation when CONFIG_CMA=n (Jerry Snitselaar) [1722978]
Rebuild_FUZZ: 93.88%
commit-author Will Deacon <will@kernel.org>
commit 900a85ca43f4ae88c325a468cb8827e4852b9141

When compiling a kernel without support for CMA, CONFIG_CMA_ALIGNMENT
is not defined which results in the following build failure:

In file included from ./include/linux/list.h:9:0
                 from ./include/linux/kobject.h:19,
                 from ./include/linux/of.h:17
                 from ./include/linux/irqdomain.h:35,
                 from ./include/linux/acpi.h:13,
                 from drivers/iommu/arm-smmu-v3.c:12:
drivers/iommu/arm-smmu-v3.c: In function ‘arm_smmu_device_hw_probe’:
drivers/iommu/arm-smmu-v3.c:194:40: error: ‘CONFIG_CMA_ALIGNMENT’ undeclared (first use in this function)
 #define Q_MAX_SZ_SHIFT   (PAGE_SHIFT + CONFIG_CMA_ALIGNMENT)

Fix the breakage by capping the maximum queue size based on MAX_ORDER
when CMA is not enabled.

	Reported-by: Zhangshaokun <zhangshaokun@hisilicon.com>
	Signed-off-by: Will Deacon <will@kernel.org>
	Tested-by: Shaokun Zhang <zhangshaokun@hisilicon.com>
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 900a85ca43f4ae88c325a468cb8827e4852b9141)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>