rtc: pcf8523: Fix GCC 12 warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071847
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for compliant platforms.  This set updates the
 RTC drivers as needed in drivers/rtc.  This set has been tested via
 simple boot tests, and of course the CI loop.

commit 85bcb01f145dc32e7f88e6eebb3b5f96d3b56eb6
Author: Victor Erminpour <victor.erminpour@oracle.com>
Date:   Wed Feb 9 16:30:27 2022 -0800

    rtc: pcf8523: Fix GCC 12 warning

    When building with automatic stack variable initialization, GCC 12
    complains about variables defined outside of switch case statements.
    Move variables outside the switch, which silences warnings:

    ./drivers/rtc/rtc-pcf8523.c:284:20: error: statement will never be executed [-Werror=switch-unreachable]
      284 |                 u8 mode;
          |

    ./drivers/rtc/rtc-pcf8523.c:245:21: error: statement will never be executed [-Werror=switch-unreachable]
      245 |                 u32 value;
          |                     ^~~~~

    Signed-off-by: Victor Erminpour <victor.erminpour@oracle.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
    Link: https://lore.kernel.org/r/1644453027-886-1-git-send-email-victor.erminpour@oracle.com
    (cherry picked from commit 85bcb01f145dc32e7f88e6eebb3b5f96d3b56eb6)

Signed-off-by: Al Stone <ahs3@redhat.com>