tools: ynl: handle broken pipe gracefully in CLI
JIRA: https://issues.redhat.com/browse/RHEL-123090
Upstream Status: net.git commit 0df6932485a0

commit 0df6932485a07f0fc44a3379038d5853cbbb505c
Author: Donald Hunter <donald.hunter@gmail.com>
Date:   Thu May 8 12:21:02 2025 +0100

    tools: ynl: handle broken pipe gracefully in CLI

    When sending YNL CLI output into a pipe, closing the pipe causes a
    BrokenPipeError. E.g. running the following and quitting less:

    ./tools/net/ynl/pyynl/cli.py --family rt-link --dump getlink | less
    Traceback (most recent call last):
      File "/home/donaldh/net-next/./tools/net/ynl/pyynl/cli.py", line 160, in <module>
        main()
        ~~~~^^
      File "/home/donaldh/net-next/./tools/net/ynl/pyynl/cli.py", line 142, in main
        output(reply)
        ~~~~~~^^^^^^^
      File "/home/donaldh/net-next/./tools/net/ynl/pyynl/cli.py", line 97, in output
        pprint.PrettyPrinter().pprint(msg)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
    [...]
    BrokenPipeError: [Errno 32] Broken pipe

    Consolidate the try block for ops and notifications, and gracefully
    handle the BrokenPipeError by adding an exception handler to the
    consolidated try block.

    Signed-off-by: Donald Hunter <donald.hunter@gmail.com>
    Link: https://patch.msgid.link/20250508112102.63539-1-donald.hunter@gmail.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>