ASoC: SOF: Intel: select CONFIG_SND_HDA_EXT_CORE from SND_SOC_SOF_HDA_COMMON
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit 3a7dbc729e42b95f1a82806a11128c1926ab26d8
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Feb 9 08:08:38 2026 +0100

    ASoC: SOF: Intel: select CONFIG_SND_HDA_EXT_CORE from SND_SOC_SOF_HDA_COMMON

    The _hda_dsp_stream_put() function now depends on the
    snd_hdac_ext_stream_release() interface from SND_HDA_EXT_CORE:

    x86_64-linux-ld: vmlinux.o: in function `_hda_dsp_stream_put':
    hda-stream.c:(.text+0xfac605): undefined reference to `snd_hdac_ext_stream_release'

    Select this symbol the same way the other users do.

    Fixes: 89e1d632bb29 ("ASoC: SOF: Intel: add hda_dsp_stream_pair_get/put helpers")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260209070901.857700-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>