drm/bridge: it6505: Fix build error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2088409
Upstream Status: v5.18.3

commit 1fcf40a5889aca1b824528784fc2f07bcb14f4dc
Author:     YueHaibing <yuehaibing@huawei.com>
AuthorDate: Thu Mar 17 17:47:24 2022 +0800
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Thu Jun  9 10:29:54 2022 +0200

    [ Upstream commit 3dd4834a6efe4eb3c086526e1870bb768776d86a ]

    If DRM_ITE_IT6505 is y but DRM_DP_HELPER is m, building failed:

    drivers/gpu/drm/bridge/ite-it6505.o: In function `it6505_i2c_remove':
    ite-it6505.c:(.text+0x35c): undefined reference to `drm_dp_aux_unregister'
    drivers/gpu/drm/bridge/ite-it6505.o: In function `it6505_dpcd_read':
    ite-it6505.c:(.text+0x420): undefined reference to `drm_dp_dpcd_read'
    drivers/gpu/drm/bridge/ite-it6505.o: In function `it6505_get_dpcd':
    ite-it6505.c:(.text+0x4a4): undefined reference to `drm_dp_dpcd_read'
    drivers/gpu/drm/bridge/ite-it6505.o: In function `it6505_dpcd_write':
    ite-it6505.c:(.text+0x52c): undefined reference to `drm_dp_dpcd_write'

    Select DRM_DP_HELPER for DRM_ITE_IT6505 to fix this.

    Fixes: b5c84a9edcd4 ("drm/bridge: add it6505 driver")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Robert Foss <robert.foss@linaro.org>
    Signed-off-by: Robert Foss <robert.foss@linaro.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20220317094724.25972-1-yuehaibing@huawei.com
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>