genpd: move owl-sps-helper.c from drivers/soc
JIRA: https://issues.redhat.com/browse/RHEL-25420

commit 7ed363cd8d0a3e4fbe3c37b7458420f82ef9a106
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jul 26 13:49:36 2023 +0200

    genpd: move owl-sps-helper.c from drivers/soc

    Moving only one of the two files in drivers/soc/actions to drivers/genpd
    caused a link failure in allmodconfig, as drivers/genpd is entered
    for compile testing, but drivers/soc/actions accidentally got skipped:

    x86_64-linux-gnu-ld: vmlinux.o: in function `owl_sps_set_power':
    owl-sps.c:(.text+0x16e259d): undefined reference to `owl_sps_set_pg'

    Move the other one as well to allow build testing to work correctly.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Radu Rendec <rrendec@redhat.com>