tools/perf/build: Pass through all targets to Makefile.perf
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [tools] perf/build: Pass through all targets to Makefile.perf (Jiri Olsa) [1131394]
Rebuild_FUZZ: 94.64%
commit-author Ingo Molnar <mingo@kernel.org>
commit b016a0dd08999218a05a4b176bc08a9ff68ccc5e

Jiri reported that 'make .o' stopped working:

  > [jolsa@krava perf]$ make -f Makefile perf.o
  > cc    -c -o perf.o perf.c
  > In file included from builtin.h:4:0,
  >                  from perf.c:9:
  > util/util.h:74:24: fatal error: lk/debugfs.h: No such file or directory
  > compilation terminated.
  > make: *** [perf.o] Error 1

This is due to GNU make having built-in rules for popular targets such
as *.o. Clear them out so that all targets as passed through to Makefile.perf.

	Reported-by: Jiri Olsa <jolsa@redhat.com>
	Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: David Ahern <dsahern@gmail.com>
Link: http://lkml.kernel.org/n/tip-5wkuvmlaaxtfgepKcvRij8sh@git.kernel.org
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit b016a0dd08999218a05a4b176bc08a9ff68ccc5e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>