iwlwifi: mei: fix linking when tracing is not enabled
Bugzilla: https://bugzilla.redhat.com/2059999

commit fe6db7eda9306d665f7b8fc3decdb556ec10fb85
Author: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
Date:   Wed Dec 1 13:34:10 2021 +0200

    iwlwifi: mei: fix linking when tracing is not enabled
    
    I forgot to add stubs in case tracing is disabled which caused linking errors:
    
    ERROR: modpost: "__SCT__tp_func_iwlmei_sap_data" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__SCT__tp_func_iwlmei_me_msg" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__tracepoint_iwlmei_sap_cmd" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__tracepoint_iwlmei_me_msg" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__SCK__tp_func_iwlmei_me_msg" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__SCK__tp_func_iwlmei_sap_data" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__tracepoint_iwlmei_sap_data" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__SCT__tp_func_iwlmei_sap_cmd" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    ERROR: modpost: "__SCK__tp_func_iwlmei_sap_cmd" [drivers/net/wireless/intel/iwlwifi/mei/iwlmei.ko] undefined!
    
    Fixes: 2da4366f9e2c ("iwlwifi: mei: add the driver to allow cooperation with CSME")
    Reported-by: Jiri Slaby <jirislaby@kernel.org>
    Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
    Acked-by: Luca Coelho <luciano.coelho@intel.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20211201113411.130409-1-emmanuel.grumbach@intel.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>