scsi: ufs: ufs-mediatek: Fix build error and type mismatch
Bugzilla: https://bugzilla.redhat.com/2185234

commit f54912b228a8df6c0133e31bc75628677bb8c6e5
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Sun Jun 19 19:54:32 2022 +0800

    scsi: ufs: ufs-mediatek: Fix build error and type mismatch

    If CONFIG_PM_SLEEP is not set.

    make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-, will fail:

    drivers/ufs/host/ufs-mediatek.c: In function ‘ufs_mtk_vreg_fix_vcc’:
    drivers/ufs/host/ufs-mediatek.c:688:46: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
        snprintf(vcc_name, MAX_VCC_NAME, "vcc-opt%u", res.a1);
                                                 ~^   ~~~~~~
                                                 %lu
    drivers/ufs/host/ufs-mediatek.c: In function ‘ufs_mtk_system_suspend’:
    drivers/ufs/host/ufs-mediatek.c:1371:8: error: implicit declaration of function ‘ufshcd_system_suspend’; did you mean ‘ufs_mtk_system_suspend’? [-Werror=implicit-function-declaration]
      ret = ufshcd_system_suspend(dev);
            ^~~~~~~~~~~~~~~~~~~~~
            ufs_mtk_system_suspend
    drivers/ufs/host/ufs-mediatek.c: In function ‘ufs_mtk_system_resume’:
    drivers/ufs/host/ufs-mediatek.c:1386:9: error: implicit declaration of function ‘ufshcd_system_resume’; did you mean ‘ufs_mtk_system_resume’? [-Werror=implicit-function-declaration]
      return ufshcd_system_resume(dev);
             ^~~~~~~~~~~~~~~~~~~~
             ufs_mtk_system_resume
    cc1: some warnings being treated as errors

    The declaration of func "ufshcd_system_suspend()" depends on
    CONFIG_PM_SLEEP, so the function wrapper ufs_mtk_system_suspend() should
    wrapped by CONFIG_PM_SLEEP too.

    Link: https://lore.kernel.org/r/20220619115432.205504-1-renzhijie2@huawei.com
    Fixes: 3fd23b8dfb54 ("scsi: ufs: ufs-mediatek: Fix the timing of configuring device regulators")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Reviewed-by: Stanley Chu <stanley.chu@mediatek.com>
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>