thunderbolt: Fix -Wrestrict warning
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 0a0624a26f9ceb8aae16882d87dc3b12f17f4a49
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 15:16:11 2021 +0200

    thunderbolt: Fix -Wrestrict warning

    gcc-11 warns when building with W=1:

    drivers/thunderbolt/xdomain.c: In function 'modalias_show':
    drivers/thunderbolt/xdomain.c:733:16: error: 'sprintf' argument 3 overlaps destination object 'buf' [-Werror=restrict]
      733 |         return sprintf(buf, "%s\n", buf);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/thunderbolt/xdomain.c:727:36: note: destination object referenced by 'restrict'-qualified argument 1 was declared here
      727 |                              char *buf)
          |                              ~~~~~~^~~

    There is no need for the sprintf() here when a strcat() does
    the same thing.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>