perf tools: Fix arm64 libjvmti build by generating unistd_64.h
JIRA: https://issues.redhat.com/browse/RHEL-78292

upstream
========
commit f3b601f900902ab80902c44f820a8985384ac021
Author: Vincent Minet <v.minet@criteo.com>
Date: Mon Sep 22 07:37:02 2025 +0200

description
===========
Since commit 22f72088ffe6 ("tools headers: Update the syscall table with
the kernel sources") the arm64 syscall header is generated at build
time. Later, commit bfb713ea53c7 ("perf tools: Fix arm64 build by
generating unistd_64.h") added a dependency to libperf to guarantee that
this header was created before building libperf or perf itself.

However, libjvmti also requires this header but does not depend on
libperf, leading to build failures such as:

  In file included from /usr/include/sys/syscall.h:24,
                   from /usr/include/syscall.h:1,
                   from jvmti/jvmti_agent.c:36:
  tools/arch/arm64/include/uapi/asm/unistd.h:2:10: fatal error: asm/unistd_64.h: No such file or directory
      2 | #include <asm/unistd_64.h>

Fix this by ensuring that libperf is built before libjvmti, so that
unistd_64.h is always available.

Fixes: 22f72088ffe69a37 ("tools headers: Update the syscall table with the kernel sources")
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Vincent Minet <v.minet@criteo.com>
    Link: https://lore.kernel.org/r/20250922053702.2688374-1-v.minet@criteo.com
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>