pinctrl: pinconf: fix comparison of different types
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [pinctrl] pinconf: fix comparison of different types (David Arcari) [1383814]
Rebuild_FUZZ: 90.32%
commit-author Jingoo Han <jg1.han@samsung.com>
commit 9b6803542e1bd544289d605c84233a0e0a46ac7d

Fix the following sparse warning:

drivers/pinctrl/pinconf.c:521:20: error: incompatible types in comparison expression (different type sizes)

	Signed-off-by: Jingoo Han <jg1.han@samsung.com>
	Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit 9b6803542e1bd544289d605c84233a0e0a46ac7d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>