tools lib api fs: Fix gcc9 stringop-truncation compilation error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Andrey Zhizhikin <andrey.z@gmail.com>
commit 6794200fa3c9c3e6759dae099145f23e4310f4f7

GCC9 introduced string hardening mechanisms, which exhibits the error
during fs api compilation:

error: '__builtin_strncpy' specified bound 4096 equals destination size
[-Werror=stringop-truncation]

This comes when the length of copy passed to strncpy is is equal to
destination size, which could potentially lead to buffer overflow.

There is a need to mitigate this potential issue by limiting the size of
destination by 1 and explicitly terminate the destination with NULL.

	Signed-off-by: Andrey Zhizhikin <andrey.zhizhikin@leica-geosystems.com>
	Reviewed-by: Petr Mladek <pmladek@suse.com>
	Acked-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Alexei Starovoitov <ast@kernel.org>
	Cc: Andrii Nakryiko <andriin@fb.com>
	Cc: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Kefeng Wang <wangkefeng.wang@huawei.com>
	Cc: Martin KaFai Lau <kafai@fb.com>
	Cc: Petr Mladek <pmladek@suse.com>
	Cc: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
	Cc: Song Liu <songliubraving@fb.com>
	Cc: Yonghong Song <yhs@fb.com>
	Cc: bpf@vger.kernel.org
	Cc: netdev@vger.kernel.org
Link: http://lore.kernel.org/lkml/20191211080109.18765-1-andrey.zhizhikin@leica-geosystems.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 6794200fa3c9c3e6759dae099145f23e4310f4f7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>