ASoC: SOF: Intel: Fix build error without SND_SOC_SOF_PCI_DEV
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Zheng Bin <zhengbin13@huawei.com>
commit 664d66dc0a64b32e60a5ad59a9aebb08676a612b

If SND_SOC_SOF_PCI_DEV is n, bulding fails:

sound/soc/sof/intel/pci-tng.o:(.data+0x1c0): undefined reference to `sof_pci_probe'
sound/soc/sof/intel/pci-tng.o:(.data+0x1c8): undefined reference to `sof_pci_remove'
sound/soc/sof/intel/pci-tng.o:(.data+0x1e0): undefined reference to `sof_pci_shutdown'
sound/soc/sof/intel/pci-tng.o:(.data+0x290): undefined reference to `sof_pci_pm'

Make SND_SOC_SOF_MERRIFIELD select SND_SOC_SOF_PCI_DEV to fix this.

Fixes: 8d4ba1be3d22 ("ASoC: SOF: pci: split PCI into different drivers")
	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Zheng Bin <zhengbin13@huawei.com>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20220323092501.145879-1-zhengbin13@huawei.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 664d66dc0a64b32e60a5ad59a9aebb08676a612b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>