tools headers UAPI: Sync linux/kvm.h with the kernel sources
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2177720

commit b235e5b51f7d557cf10cbb1245b6cdeb341e1e2b
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Sun May 9 09:39:02 2021 -0300

    tools headers UAPI: Sync linux/kvm.h with the kernel sources

    To pick the changes in:

      86bdf3ebcfe1ded0 ("KVM: Support dirty ring in conjunction with bitmap")

    That just rebuilds perf, as these patches don't add any new KVM ioctl to
    be harvested for the the 'perf trace' ioctl syscall argument
    beautifiers.

    This is also by now used by tools/testing/selftests/kvm/, a simple test
    build didn't succeed, but for another reason:

      lib/kvm_util.c: In function ‘vm_enable_dirty_ring’:
      lib/kvm_util.c:125:30: error: ‘KVM_CAP_DIRTY_LOG_RING_ACQ_REL’ undeclared (first use in this function); did you mean ‘KVM_CAP_DIRTY_LOG_RING’?
        125 |         if (vm_check_cap(vm, KVM_CAP_DIRTY_LOG_RING_ACQ_REL))
            |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                              KVM_CAP_DIRTY_LOG_RING

    I'll send a separate patch for that.

    This silences this perf build warning:

      Warning: Kernel ABI header at 'tools/include/uapi/linux/kvm.h' differs from latest version at 'include/uapi/linux/kvm.h'
      diff -u tools/include/uapi/linux/kvm.h include/uapi/linux/kvm.h

    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Gavin Shan <gshan@redhat.com>
    Cc: Ian Rogers <irogers@google.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Marc Zyngier <maz@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Link: http://lore.kernel.org/lkml/Y6H3b1Q4Msjy5Yz3@kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>