selftests/cgroup: Fix compile error in test_cpu.c
JIRA: https://issues.redhat.com/browse/RHEL-80382

commit 11312c86f9d7d1bffe0587185934a7070ce9ec33
Author: Xiu Jianfeng <xiujianfeng@huawei.com>
Date:   Fri Oct 11 06:11:53 2024 +0000

    selftests/cgroup: Fix compile error in test_cpu.c

    When compiling the cgroup selftests with the following command:

    make -C tools/testing/selftests/cgroup/

    the compiler complains as below:

    test_cpu.c: In function ‘test_cpucg_nice’:
    test_cpu.c:284:39: error: incompatible type for argument 2 of ‘hog_cpus_timed’
      284 |                 hog_cpus_timed(cpucg, param);
          |                                       ^~~~~
          |                                       |
          |                                       struct cpu_hog_func_param
    test_cpu.c:132:53: note: expected ‘void *’ but argument is of type ‘struct cpu_hog_func_param’
      132 | static int hog_cpus_timed(const char *cgroup, void *arg)
          |                                               ~~~~~~^~~

    Fix it by passing the address of param to hog_cpus_timed().

    Fixes: 2e82c0d4562a ("cgroup/rstat: Selftests for niced CPU statistics")
    Signed-off-by: Xiu Jianfeng <xiujianfeng@huawei.com>
    Signed-off-by: Tejun Heo <tj@kernel.org>

Signed-off-by: Radostin Stoyanov <rstoyano@redhat.com>