platform/x86/amd/hsmp: mark hsmp_msg_desc_table[] as maybe_unused
JIRA: https://issues.redhat.com/browse/RHEL-102859

commit 0d5e2d9b8fcb58116df2a201c54af60c1ac50bf2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 28 16:35:46 2024 +0000

    platform/x86/amd/hsmp: mark hsmp_msg_desc_table[] as maybe_unused

    After the file got split, there are now W=1 warnings for users that
    include it without referencing hsmp_msg_desc_table:

    In file included from arch/x86/include/asm/amd_hsmp.h:6,
                     from drivers/platform/x86/amd/hsmp/plat.c:12:
    arch/x86/include/uapi/asm/amd_hsmp.h:91:35: error: 'hsmp_msg_desc_table' defined but not used [-Werror=unused-const-variable=]
       91 | static const struct hsmp_msg_desc hsmp_msg_desc_table[] = {
          |                                   ^~~~~~~~~~~~~~~~~~~

    Mark it as __attribute__((maybe_unused)) to shut up the warning but
    keep it in the file in case it is used from userland. The __maybe_unused
    shorthand unfortunately isn't available in userspace, so this has to
    be the long form.

    While it is not envisioned a normal userspace program could benefit
    from having this table as part of UAPI, it seems there is non-zero
    chance this array is used by some userspace tests so it is retained for
    now (see the Link below).

    Fixes: e47c018a0ee6 ("platform/x86/amd/hsmp: Move platform device specific code to plat.c")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/platform-driver-x86/CAPhsuW7mDRswhVjYf+4iinO+sph_rQ1JykEof+apoiSOVwOXXQ@mail.gmail.com/
    Link: https://lore.kernel.org/r/20241028163553.2452486-1-arnd@kernel.org
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>