unix: fix up for "apparmor: add fine grained af_unix mediation"
jira KERNEL-1600
Rebuild_History Non-Buildable kernel-6.12.0-211.55.1.el10_2
commit-author Stephen Rothwell <sfr@canb.auug.org.au>
commit 705094f6556d88540e1076e432cbca6b596421dd

After merging the apparmor tree, today's linux-next build (x86_64
allmodconfig) failed like this:

security/apparmor/af_unix.c: In function 'unix_state_double_lock':
security/apparmor/af_unix.c:627:17: error: implicit declaration of function 'unix_state_lock'; did you mean 'unix_state_double_lock'? [-Wimplicit-function-declaration]
  627 |                 unix_state_lock(sk1);
      |                 ^~~~~~~~~~~~~~~
      |                 unix_state_double_lock
security/apparmor/af_unix.c: In function 'unix_state_double_unlock':
security/apparmor/af_unix.c:642:17: error: implicit declaration of function 'unix_state_unlock'; did you mean 'unix_state_double_lock'? [-Wimplicit-function-declaration]
  642 |                 unix_state_unlock(sk1);
      |                 ^~~~~~~~~~~~~~~~~
      |                 unix_state_double_lock

Caused by commit

  c05e705812d1 ("apparmor: add fine grained af_unix mediation")

interacting with commit

  84960bf24031 ("af_unix: Move internal definitions to net/unix/.")

from the net-next tree.

	Reviewed-by: Kuniyuki Iwashima <kuniyu@amazon.com>
	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Link: https://patch.msgid.link/20250326150148.72d9138d@canb.auug.org.au
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 705094f6556d88540e1076e432cbca6b596421dd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>