fbdev: fbmem: mark get_fb_unmapped_area() static
JIRA: https://issues.redhat.com/browse/RHEL-23295
Upstream Status: v6.4-rc3

commit 19abb4583d5eba06459930932e72c862a83cd9c2
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Tue May 16 22:22:48 2023 +0200
Commit:     Helge Deller <deller@gmx.de>
CommitDate: Sat May 20 07:02:12 2023 +0200

    There is a global function with this name on sparc, but no
    global declaration:

    drivers/video/fbdev/core/fbmem.c:1469:15: error: no previous prototype for 'get_fb_unmapped_area'

    Make the generic definition static to avoid this warning. On
    sparc, this is never seen.

    Edit by Helge:
    Update Kconfig text as suggested by Geert Uytterhoeven.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Helge Deller <deller@gmx.de>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>