arm64: fix build warning for ARM64_MEMSTART_SHIFT
JIRA: https://issues.redhat.com/browse/RHEL-40604

commit 4e0bacd65e72f7f9b1b60e48e85e6d4187474644
Author: Zhang Jianhua <chris.zjh@huawei.com>
Date: Fri, 4 Aug 2023 15:56:15 +0800

    When building with W=1, the following warning occurs.

    arch/arm64/include/asm/kernel-pgtable.h:129:41: error: "PUD_SHIFT" is not defined, evaluates to 0 [-Werror=undef]
      129 | #define ARM64_MEMSTART_SHIFT            PUD_SHIFT
          |                                         ^~~~~~~~~
    arch/arm64/include/asm/kernel-pgtable.h:142:5: note: in expansion of macro ‘ARM64_MEMSTART_SHIFT’
      142 | #if ARM64_MEMSTART_SHIFT < SECTION_SIZE_BITS
          |     ^~~~~~~~~~~~~~~~~~~~

    The generic PUD_SHIFT was defined in include/asm-generic/pgtable-nopud.h,
    however the #ifndef __ASSEMBLY__ guard in this header file makes it unavailable
    for assembly files. While someone .S file include the <asm/kernel-pgtable.h>,
    the build warning would occur. Now move the macro ARM64_MEMSTART_SHIFT and
    ARM64_MEMSTART_ALIGN to arch/arm64/mm/init.c where it is used only, to avoid
    this issue.

    Signed-off-by: Zhang Jianhua <chris.zjh@huawei.com>
    Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
    Link: https://lore.kernel.org/r/20230804075615.3334756-1-chris.zjh@huawei.com
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>