iommu/amd: Fix compile error for unused function
JIRA: https://issues.redhat.com/browse/RHEL-10026
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 1ce018df87640adb139c8418785ad3b6e4376bd3
Author: Joerg Roedel <jroedel@suse.de>
Date:   Fri Jun 9 15:15:08 2023 +0200

    iommu/amd: Fix compile error for unused function

    Recent changes introduced a compile error:

    drivers/iommu/amd/iommu.c:1285:13: error: ‘iommu_flush_irt_and_complete’ defined but not used [-Werror=unused-function]
     1285 | static void iommu_flush_irt_and_complete(struct amd_iommu *iommu, u16 devid)
	  |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This happens with defconfig-x86_64 because AMD IOMMU is enabled but
    CONFIG_IRQ_REMAP is disabled. Move the function under #ifdef
    CONFIG_IRQ_REMAP to fix the error.

    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 1ce018df87640adb139c8418785ad3b6e4376bd3)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>