locking/ww-mutex: Fix uninitialized use of ret in test_aa()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2072020
Upstream Status: v5.16-rc1

commit 1415b49bcd321bca7347f43f8b269c91ec46d1dc
Author:     Nathan Chancellor <nathan@kernel.org>
AuthorDate: Wed Sep 22 07:58:22 2021 -0700
Commit:     Peter Zijlstra <peterz@infradead.org>
CommitDate: Fri Oct  1 13:57:49 2021 +0200

    Clang warns:

    kernel/locking/test-ww_mutex.c:138:7: error: variable 'ret' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
                    if (!ww_mutex_trylock(&mutex, &ctx)) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    kernel/locking/test-ww_mutex.c:172:9: note: uninitialized use occurs here
            return ret;
                   ^~~
    kernel/locking/test-ww_mutex.c:138:3: note: remove the 'if' if its condition is always false
                    if (!ww_mutex_trylock(&mutex, &ctx)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    kernel/locking/test-ww_mutex.c:125:9: note: initialize the variable 'ret' to silence this warning
            int ret;
                   ^
                    = 0
    1 error generated.

    Assign !ww_mutex_trylock(...) to ret so that it is always initialized.

    Fixes: 12235da8c80a ("kernel/locking: Add context to ww_mutex_trylock()")
    Reported-by: "kernelci.org bot" <bot@kernelci.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Waiman Long <longman@redhat.com>
    Link: https://lore.kernel.org/r/20210922145822.3935141-1-nathan@kernel.org

Signed-off-by: Karol Herbst <kherbst@redhat.com>