selftests/bpf: Fix test_progs compilation failure in 32-bit arch
Bugzilla: https://bugzilla.redhat.com/2166911

commit 5704bc7e8991164b14efb748b5afa0715c25fac3
Author: Yang Jihong <yangjihong1@huawei.com>
Date:   Tue Nov 8 09:58:57 2022 +0800

    selftests/bpf: Fix test_progs compilation failure in 32-bit arch
    
    test_progs fails to be compiled in the 32-bit arch, log is as follows:
    
      test_progs.c:1013:52: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
       1013 |                 sprintf(buf, "MSG_TEST_LOG (cnt: %ld, last: %d)",
            |                                                  ~~^
            |                                                    |
            |                                                    long int
            |                                                  %d
       1014 |                         strlen(msg->test_log.log_buf),
            |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                         |
            |                         size_t {aka unsigned int}
    
    Fix it.
    
    Fixes: 91b2c0afd00c ("selftests/bpf: Add parallelism to test_progs")
    Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/r/20221108015857.132457-1-yangjihong1@huawei.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Artem Savkov <asavkov@redhat.com>