efi: libstub: Use '-std=gnu11' to fix build with GCC 15
JIRA: https://issues.redhat.com/browse/RHEL-129401

commit 8ba14d9f490aef9fd535c04e9e62e1169eb7a055
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Jan 21 18:11:34 2025 -0700

    efi: libstub: Use '-std=gnu11' to fix build with GCC 15

    GCC 15 changed the default C standard version to C23, which should not
    have impacted the kernel because it requests the gnu11 standard via
    '-std=' in the main Makefile. However, the EFI libstub Makefile uses its
    own set of KBUILD_CFLAGS for x86 without a '-std=' value (i.e., using
    the default), resulting in errors from the kernel's definitions of bool,
    true, and false in stddef.h, which are reserved keywords under C23.

      ./include/linux/stddef.h:11:9: error: expected identifier before ‘false’
         11 |         false   = 0,
      ./include/linux/types.h:35:33: error: two or more data types in declaration specifiers
         35 | typedef _Bool                   bool;

    Set '-std=gnu11' in the x86 cflags to resolve the error and consistently
    use the same C standard version for the entire kernel. All other
    architectures reuse KBUILD_CFLAGS from the rest of the kernel, so this
    issue is not visible for them.

    Cc: stable@vger.kernel.org
    Reported-by: Kostadin Shishmanov <kostadinshishmanov@protonmail.com>
    Closes: https://lore.kernel.org/4OAhbllK7x4QJGpZjkYjtBYNLd_2whHx9oFiuZcGwtVR4hIzvduultkgfAIRZI3vQpZylu7Gl929HaYFRGeMEalWCpeMzCIIhLxxRhq4U-Y=@protonmail.com/
    Reported-by: Jakub Jelinek <jakub@redhat.com>
    Closes: https://lore.kernel.org/Z4467umXR2PZ0M1H@tucnak/
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

(cherry picked from commit 8ba14d9f490aef9fd535c04e9e62e1169eb7a055)
Assisted-by: Patchpal
Signed-off-by: Lenny Szubowicz <lszubowi@redhat.com>