perf tools: Fix syscalltbl build failure
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Akemi Yagi <amyagi@gmail.com>
commit 090657c9fb7094e4c1b05c1713d6c2a12ef43dea

The build of kernel v4.14-rc1 for i686 fails on RHEL 6 with the error
in tools/perf:

  util/syscalltbl.c:157: error: expected ';', ',' or ')' before '__maybe_unused'
  mv: cannot stat `util/.syscalltbl.o.tmp': No such file or directory

Fix it by placing/moving:

  #include <linux/compiler.h>

  outside of #ifdef HAVE_SYSCALL_TABLE block.

	Signed-off-by: Akemi Yagi <toracat@elrepo.org>
	Cc: Alan Bartlett <ajb@elrepo.org>
Link: http://lkml.kernel.org/r/oq41r8$1v9$1@blaine.gmane.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 090657c9fb7094e4c1b05c1713d6c2a12ef43dea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>