platform/x86: amd-pmc: Fix build error unused-function
Bugzilla: https://bugzilla.redhat.com/2104173

commit 17faaacac3c92abde4019600e107c10c367d74f2
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Thu May 5 20:19:58 2022 +0800

    platform/x86: amd-pmc: Fix build error unused-function

    If CONFIG_SUSPEND and CONFIG_DEBUG_FS are not set.

    compile error:
    drivers/platform/x86/amd-pmc.c:323:12: error: ‘get_metrics_table’ defined but not used [-Werror=unused-function]
     static int get_metrics_table(struct amd_pmc_dev *pdev, struct smu_metrics *table)
                ^~~~~~~~~~~~~~~~~
    drivers/platform/x86/amd-pmc.c:298:12: error: ‘amd_pmc_idlemask_read’ defined but not used [-Werror=unused-function]
     static int amd_pmc_idlemask_read(struct amd_pmc_dev *pdev, struct device *dev,
                ^~~~~~~~~~~~~~~~~~~~~
    drivers/platform/x86/amd-pmc.c:196:12: error: ‘amd_pmc_get_smu_version’ defined but not used [-Werror=unused-function]
     static int amd_pmc_get_smu_version(struct amd_pmc_dev *dev)
                ^~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    To fix building warning, wrap all related code with CONFIG_SUSPEND or CONFIG_DEBUG_FS.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Link: https://lore.kernel.org/r/20220505121958.138905-1-renzhijie2@huawei.com
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>