arm64/mm: Define dummy pud_user_exec() when using 2-level page-table
JIRA: https://issues.redhat.com/browse/RHEL-40604

commit 4e4ff23a35ee3a145fbc8378ecfeaab2d235cddd
Author: Will Deacon <will@kernel.org>
Date: Mon, 9 Jan 2023 15:47:25 +0000

    With only two levels of page-table, the generic 'pud_*' macros are
    implemented using dummy operations in pgtable-nopmd.h. Since commit
    730a11f982e6 ("arm64/mm: add pud_user_exec() check in
    pud_user_accessible_page()"), pud_user_accessible_page() unconditionally
    calls pud_user_exec(), which is an arm64-specific helper and therefore
    isn't defined by pgtable-nopmd.h. This results in a build failure for
    configurations with only two levels of page table:

       arch/arm64/include/asm/pgtable.h: In function 'pud_user_accessible_page':
    >> arch/arm64/include/asm/pgtable.h:870:51: error: implicit declaration of function 'pud_user_exec'; did you mean 'pmd_user_exec'? [-Werror=implicit-function-declaration]
         870 |         return pud_leaf(pud) && (pud_user(pud) || pud_user_exec(pud));
             |                                                   ^~~~~~~~~~~~~
             |                                                   pmd_user_exec

    Fix the problem by defining pud_user_exec() as pud_user() in this case.

    Link: https://lore.kernel.org/r/202301080515.z6zEksU4-lkp@intel.com
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>