mlxsw: spectrum_router: avoid uninitialized variable access
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit be9c64b19b8131459dd7107dc0ae209eeeaa9ce8

When CONFIG_BRIDGE_VLAN_FILTERING is disabled, gcc correctly points out
that the 'vid' variable is uninitialized whenever br_vlan_get_pvid
returns an error:

drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c: In function 'mlxsw_sp_rif_vlan_fid_get':
drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:6881:6: error: 'vid' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This changes the condition check to always return -EINVAL here,
which I guess is what the author intended here.

Fixes: e6f1960ae6c7 ("mlxsw: spectrum_router: Allocate FID according to PVID")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Ido Schimmel <idosch@mellanox.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit be9c64b19b8131459dd7107dc0ae209eeeaa9ce8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>