x86/mce/therm_throt: Mark throttle_active_work() as __maybe_unused
jira LE-3201
Rebuild_History Non-Buildable kernel-rt-4.18.0-553.22.1.rt7.363.el8_10
commit-author Arnd Bergmann <arnd@arndb.de>
commit db1ae0314f47e88ae06679270adf17ffa245afd4
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-rt-4.18.0-553.22.1.rt7.363.el8_10/db1ae031.failed

throttle_active_work() is only called if CONFIG_SYSFS is set, otherwise
we get a harmless warning:

  arch/x86/kernel/cpu/mce/therm_throt.c:238:13: error: 'throttle_active_work' \
	  defined but not used [-Werror=unused-function]

Mark the function as __maybe_unused to avoid the warning.

Fixes: f6656208f04e ("x86/mce/therm_throt: Optimize notifications of thermal throttle")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Borislav Petkov <bp@suse.de>
	Reviewed-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
	Cc: bberg@redhat.com
	Cc: ckellner@redhat.com
	Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Cc: hdegoede@redhat.com
	Cc: "H. Peter Anvin" <hpa@zytor.com>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: linux-edac <linux-edac@vger.kernel.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Cc: Tony Luck <tony.luck@intel.com>
	Cc: x86-ml <x86@kernel.org>
Link: https://lkml.kernel.org/r/20191210203925.3119091-1-arnd@arndb.de
(cherry picked from commit db1ae0314f47e88ae06679270adf17ffa245afd4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/thermal/intel/therm_throt.c