pinctrl: tegra194: remove duplicate initializer again
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071845
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set updates pinctrl
 support (NB: some Intel and NVIDIA patches are included as well for similar
 Platforms).  It has been tested via simple boot tests, examining the pinctrl
 definintions in DeviceTree, and by using the kernel GPIO tools to verify
 pins are being still being identified and can be used.

commit 293083f877a7d9dba8165cc3bd159cbfcea28fe7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Nov 4 14:36:39 2021 +0100

    pinctrl: tegra194: remove duplicate initializer again

    An earlier bugfix removed a duplicate field initializer in
    a macro, but it seems that this came back with the following
    update:

    drivers/pinctrl/tegra/pinctrl-tegra194.c:1341:28: error: initialized field overwritten [-Werror=override-init]
     1341 |                 .drv_reg = ((r)),                               \
          |                            ^
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1392:41: note: in expansion of macro 'DRV_PINGROUP_ENTRY_Y'
     1392 | #define drive_touch_clk_pcc4            DRV_PINGROUP_ENTRY_Y(0x2004,    12,     5,      20,     5,      -1,     -1,     -1,     -1,     1)
          |                                         ^~~~~~~~~~~~~~~~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1631:17: note: in expansion of macro 'drive_touch_clk_pcc4'
     1631 |                 drive_##pg_name,                                \
          |                 ^~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1636:9: note: in expansion of macro 'PINGROUP'
     1636 |         PINGROUP(touch_clk_pcc4,        GP,             TOUCH,          RSVD2,          RSVD3,          0x2000,         1,      Y,      -1,     -1,     6,      8,      -1,     10,     11,     12,     N,      -1,     -1,     N,      "vddio_ao"),
          |         ^~~~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1341:28: note: (near initialization for 'tegra194_groups[0].drv_reg')
     1341 |                 .drv_reg = ((r)),                               \
          |                            ^
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1392:41: note: in expansion of macro 'DRV_PINGROUP_ENTRY_Y'
     1392 | #define drive_touch_clk_pcc4            DRV_PINGROUP_ENTRY_Y(0x2004,    12,     5,      20,     5,      -1,     -1,     -1,     -1,     1)
          |                                         ^~~~~~~~~~~~~~~~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1631:17: note: in expansion of macro 'drive_touch_clk_pcc4'
     1631 |                 drive_##pg_name,                                \
          |                 ^~~~~~
    drivers/pinctrl/tegra/pinctrl-tegra194.c:1636:9: note: in expansion of macro 'PINGROUP'
     1636 |         PINGROUP(touch_clk_pcc4,        GP,             TOUCH,          RSVD2,          RSVD3,          0x2000,         1,      Y,      -1,     -1,     6,      8,      -1,     10,     11,     12,     N,      -1,     -1,     N,      "vddio_ao"),
          |         ^~~~~~~~

    Remove it again.

    Fixes: 613c0826081b ("pinctrl: tegra: Add pinmux support for Tegra194")
    Fixes: 92cadf68e50a ("pinctrl: tegra: pinctrl-tegra194: Do not initialise field twice")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211104133645.1186968-1-arnd@kernel.org
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
    (cherry picked from commit 293083f877a7d9dba8165cc3bd159cbfcea28fe7)

Signed-off-by: Al Stone <ahs3@redhat.com>