bridge: mcast: Allow user space to specify MDB entry routing protocol
Bugzilla: https://bugzilla.redhat.com/2184372

commit 1d7b66a7d9754c229d12c53ad6a1effe88c16ca4
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Sat Dec 10 16:56:30 2022 +0200

    bridge: mcast: Allow user space to specify MDB entry routing protocol
    
    Add the 'MDBE_ATTR_RTPORT' attribute to allow user space to specify the
    routing protocol of the MDB port group entry. Enforce a minimum value of
    'RTPROT_STATIC' to prevent user space from using protocol values that
    should only be set by the kernel (e.g., 'RTPROT_KERNEL'). Maintain
    backward compatibility by defaulting to 'RTPROT_STATIC'.
    
    The protocol is already visible to user space in RTM_NEWMDB responses
    and notifications via the 'MDBA_MDB_EATTR_RTPROT' attribute.
    
    The routing protocol allows a routing daemon to distinguish between
    entries configured by it and those configured by the administrator. Once
    MDB flush is supported, the protocol can be used as a criterion
    according to which the flush is performed.
    
    Examples:
    
     # bridge mdb add dev br0 port dummy10 grp 239.1.1.1 permanent proto kernel
     Error: integer out of range.
    
     # bridge mdb add dev br0 port dummy10 grp 239.1.1.1 permanent proto static
    
     # bridge mdb add dev br0 port dummy10 grp 239.1.1.1 src 192.0.2.1 permanent proto zebra
    
     # bridge mdb add dev br0 port dummy10 grp 239.1.1.2 permanent source_list 198.51.100.1,198.51.100.2 filter_mode include proto 250
    
     # bridge -d mdb show
     dev br0 port dummy10 grp 239.1.1.2 src 198.51.100.2 permanent filter_mode include proto 250
     dev br0 port dummy10 grp 239.1.1.2 src 198.51.100.1 permanent filter_mode include proto 250
     dev br0 port dummy10 grp 239.1.1.2 permanent filter_mode include source_list 198.51.100.2/0.00,198.51.100.1/0.00 proto 250
     dev br0 port dummy10 grp 239.1.1.1 src 192.0.2.1 permanent filter_mode include proto zebra
     dev br0 port dummy10 grp 239.1.1.1 permanent filter_mode exclude proto static
    
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Acked-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>