media: v4l2-ioctl: Fix check_ext_ctrls
JIRA: https://issues.redhat.com/browse/RHEL-67885

commit 861f92cb9160b14beef0ada047384c2340701ee2
Author: Ricardo Ribalda <ribalda@chromium.org>
Date: Fri, 18 Jun 2021 14:29:03 +0200

  Drivers that do not use the ctrl-framework use this function instead.

  Fix the following issues:

  - Do not check for multiple classes when getting the DEF_VAL.
  - Return -EINVAL for request_api calls
  - Default value cannot be changed, return EINVAL as soon as possible.
  - Return the right error_idx
  [If an error is found when validating the list of controls passed with
  VIDIOC_G_EXT_CTRLS, then error_idx shall be set to ctrls->count to
  indicate to userspace that no actual hardware was touched.
  It would have been much nicer of course if error_idx could point to the
  control index that failed the validation, but sadly that's not how the
  API was designed.]

  Fixes v4l2-compliance:
  Control ioctls (Input 0):
          warn: v4l2-test-controls.cpp(834): error_idx should be equal to count
          warn: v4l2-test-controls.cpp(855): error_idx should be equal to count
  		fail: v4l2-test-controls.cpp(813): doioctl(node, VIDIOC_G_EXT_CTRLS, &ctrls)
  	test VIDIOC_G/S/TRY_EXT_CTRLS: FAIL
  Buffer ioctls (Input 0):
  		fail: v4l2-test-buffers.cpp(1994): ret != EINVAL && ret != EBADR && ret != ENOTTY
  	test Requests: FAIL

  Cc: stable@vger.kernel.org
  Fixes: 6fa6f831f095 ("media: v4l2-ctrls: add core request support")
  Suggested-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
  Reviewed-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
  Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
  Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
  Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

Signed-off-by: Kate Hsuan <hpa@redhat.com>