linux/container_of.h: switch to static_assert
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2072020
Upstream Status: v5.16-rc1

commit e1edc277e6f6dfb372216522dfc57f9381c39e35
Author:     Rasmus Villemoes <linux@rasmusvillemoes.dk>
AuthorDate: Mon Nov  8 18:32:46 2021 -0800
Commit:     Linus Torvalds <torvalds@linux-foundation.org>
CommitDate: Tue Nov  9 10:02:49 2021 -0800

    _Static_assert() is evaluated already in the compiler's frontend, and
    gives a somehat more to-the-point error, compared to the BUILD_BUG_ON
    macro, which only fires after the optimizer has had a chance to
    eliminate calls to functions marked with __attribute__((error)).  In
    theory, this might make builds a tiny bit faster.

    There's also a little less gunk in the error message emitted:

      lib/sort.c: In function `foo':
      include/linux/build_bug.h:78:41: error: static assertion failed: "pointer type mismatch in container_of()"
         78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)

    compared to

      lib/sort.c: In function `foo':
      include/linux/compiler_types.h:322:38: error: call to `__compiletime_assert_2' declared with attribute error: pointer type mismatch in container_of()
        322 |  _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)

    While at it, fix the copy-pasto in container_of_safe().

    Link: https://lkml.kernel.org/r/20211015090530.2774079-1-linux@rasmusvillemoes.dk
    Link: https://lore.kernel.org/lkml/20211014132331.GA4811@kernel.org/T/
    Signed-off-by: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Reviewed-by: Miguel Ojeda <ojeda@kernel.org>
    Acked-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>