ethtool.h: define INT_MAX for userland
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [net] ethtool: define INT_MAX for userland (Ivan Vecera) [1268334]
Rebuild_FUZZ: 97.30%
commit-author Nicolas Dichtel <nicolas.dichtel@6wind.com>
commit 14e2037902d65213842b4e40305ff54a64abbcb6

INT_MAX needs limits.h in userland.
When ethtool.h is included by a userland app, we got the following error:

.../usr/include/linux/ethtool.h: In function 'ethtool_validate_speed':
.../usr/include/linux/ethtool.h:1471:18: error: 'INT_MAX' undeclared (first use in this function)
  return speed <= INT_MAX || speed == SPEED_UNKNOWN
                  ^

Fixes: e02564ee334a ("ethtool: make validate_speed accept all speeds between 0 and INT_MAX")
CC: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
	Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
	Acked-by: Nikolay Aleksandrov <nikolay@cumulusnetworks.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 14e2037902d65213842b4e40305ff54a64abbcb6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>