rtc: fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [scsi] fcoe: fix build error (Neil Horman) [1087099]
Rebuild_FUZZ: 87.80%
commit-author Raghavendra Ganiga <ravi23ganiga@gmail.com>
commit 0dd449b1626c3db6b40fc2c7685bf9b0ac79ce00
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-229.el7/0dd449b1.failed

Fix the following build errors reported by kbuild test robot by selecting
REGMAP_SPI in Kconfig file

drivers/built-in.o: In function `ds1343_probe':
rtc-ds1343.c:(.text+0x1baf8f): undefined reference to `devm_regmap_init_spi'

	Signed-off-by: Raghavendra Chandra Ganiga <ravi23ganiga@gmail.com>
	Acked-by: Alessandro Zummo <a.zummo@towertech.it>
	Cc: <stable@vger.kernel.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 0dd449b1626c3db6b40fc2c7685bf9b0ac79ce00)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/rtc/Kconfig