net/sched: avoid unused-label warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [net] sched: avoid unused-label warning (Ivan Vecera) [1688236 1687456]
Rebuild_FUZZ: 94.29%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 096461de96a94c856190ba892ebf62dfba5a38f1

The label is only used from inside the #ifdef and should be
hidden the same way, to avoid this warning:

net/sched/act_tunnel_key.c: In function 'tunnel_key_init':
net/sched/act_tunnel_key.c:389:1: error: label 'release_tun_meta' defined but not used [-Werror=unused-label]
 release_tun_meta:

Fixes: 41411e2fd6b8 ("net/sched: act_tunnel_key: Add dst_cache support")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 096461de96a94c856190ba892ebf62dfba5a38f1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>