flow_offload: Reject matching on layer 2 miss
JIRA: https://issues.redhat.com/browse/RHEL-1773

commit f4356947f0297b0962fdd197672db7edf9f58be6
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Mon May 29 14:48:31 2023 +0300

    flow_offload: Reject matching on layer 2 miss

    Adjust drivers that support the 'FLOW_DISSECTOR_KEY_META' key to reject
    filters that try to match on the newly added layer 2 miss field. Add an
    extack message to clearly communicate the failure reason to user space.

    The following users were not patched:

    1. mtk_flow_offload_replace(): Only checks that the key is present, but
       does not do anything with it.
    2. mlx5_tc_ct_set_tuple_match(): Used as part of netfilter offload,
       which does not make use of the new field, unlike tc.
    3. get_netdev_from_rule() in nfp: Likewise.

    Example:

     # tc filter add dev swp1 egress pref 1 proto all flower skip_sw l2_miss true action drop
     Error: mlxsw_spectrum: Can't match on "l2_miss".
     We have an error talking to the kernel

    Acked-by: Elad Nachman <enachman@marvell.com>
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>