selftests/bpf: Fix errors compiling decap_sanity.c with musl libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 1b00f355130a5dfc38a01ad02458ae2cb2ebe609
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:44 2024 -0700

    selftests/bpf: Fix errors compiling decap_sanity.c with musl libc

    Remove a redundant include of '<linux/in6.h>', whose needed definitions are
    already provided by 'test_progs.h'. This avoids errors seen compiling for
    mips64el/musl-libc:

      In file included from .../arpa/inet.h:9,
                       from ./test_progs.h:17,
                       from prog_tests/decap_sanity.c:9:
      .../netinet/in.h:23:8: error: redefinition of 'struct in6_addr'
         23 | struct in6_addr {
            |        ^~~~~~~~
      In file included from decap_sanity.c:7:
      .../linux/in6.h:33:8: note: originally defined here
         33 | struct in6_addr {
            |        ^~~~~~~~
      .../netinet/in.h:34:8: error: redefinition of 'struct sockaddr_in6'
         34 | struct sockaddr_in6 {
            |        ^~~~~~~~~~~~
      .../linux/in6.h:50:8: note: originally defined here
         50 | struct sockaddr_in6 {
            |        ^~~~~~~~~~~~
      .../netinet/in.h:42:8: error: redefinition of 'struct ipv6_mreq'
         42 | struct ipv6_mreq {
            |        ^~~~~~~~~
      .../linux/in6.h:60:8: note: originally defined here
         60 | struct ipv6_mreq {
            |        ^~~~~~~~~

    Fixes: 70a00e2f1dba ("selftests/bpf: Test bpf_skb_adjust_room on CHECKSUM_PARTIAL")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/e986ba2d7edccd254b54f7cd049b98f10bafa8c3.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>