perf tools: Fix build errors with O and DESTDIR make vars set
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [tools] perf: Fix build errors with O and DESTDIR make vars set (Jiri Olsa) [984998]
Rebuild_FUZZ: 94.83%
commit-author Robert Richter <robert.richter@linaro.org>
commit 107de3724eff5a6fa6474a4d2aa5460b63749ebf

Fixing build errors with O and DESTDIR make vars set:

 $ make prefix=/usr/local O=$builddir DESTDIR=$destdir -C tools/ perf
 ...
 make[1]: Entering directory `.../.source/perf/tools/perf'
     CC .../.build/perf/perf/util/parse-events.o
 util/parse-events.c:14:32: fatal error: parse-events-bison.h: No such file or directory
 compilation terminated.
 make[1]: *** [.../.build/perf/perf/util/parse-events.o] Error 1
 ...

and:

     LINK /.../.build/perf/perf/perf
 gcc: error: /.../.build/perf/perf//.../.source/perf/tools/lib/lk/liblk.a: No such file or directory

	Signed-off-by: Robert Richter <robert.richter@linaro.org>
	Signed-off-by: Robert Richter <rric@kernel.org>
	Cc: Ingo Molnar <mingo@kernel.org>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Robert Richter <rric@kernel.org>
Link: http://lkml.kernel.org/r/1370964158-4135-1-git-send-email-rric@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 107de3724eff5a6fa6474a4d2aa5460b63749ebf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>