mt76: fix build error implicit enumeration conversion
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Sean Wang <sean.wang@mediatek.com>
commit adedbc643f02f5a3193b8dcc5cfca97b4c988667

drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:114:10: error: implicit
conversion from enumeration type 'enum mt76_cipher_type' to different
enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                return MT_CIPHER_NONE;
                ~~~~~~ ^~~~~~~~~~~~~~

drivers/net/wireless/mediatek/mt76/mt7921/mcu.c:114:10: error: implicit
conversion from enumeration type 'enum mt76_cipher_type' to different
enumeration type 'enum mcu_cipher_type' [-Werror,-Wenum-conversion]
                return MT_CIPHER_NONE;
                ~~~~~~ ^~~~~~~~~~~~~~

Fixes: c368362c36d3 ("mt76: fix iv and CCMP header insertion")
	Signed-off-by: Sean Wang <sean.wang@mediatek.com>
	Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit adedbc643f02f5a3193b8dcc5cfca97b4c988667)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>