media: v4l2-common.h: kerneldoc: correctly format return values
JIRA: https://issues.redhat.com/browse/RHEL-67885

commit 83d48b5d39261be16902872367e89a0d1a874b0d
Author: Hans Verkuil <hverkuil-cisco@xs4all.nl>
Date: Fri, 2 Feb 2024 09:25:44 +0100

  Building the kerneldoc resulted in two errors:

  Documentation/media/driver-api/v4l2-common:6: ./include/media/v4l2-common.h:566: ERROR: Unexpected indentation.
  Documentation/media/driver-api/v4l2-common:6: ./include/media/v4l2-common.h:567: WARNING: Block quote ends without a blank line; unexpected unindent.

  Format v4l2_link_freq_to_bitmap according to the kerneldoc standard.
  The v4l2_fill_pixfmt_mp function also had incorrect return value
  formatting, although that didn't report an error/warning, but it looked
  ugly in the generated documentation. So fix that one as well.

  Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
  Fixes: a68e88e2cf9e ("media: v4l: Add a helper for setting up link-frequencies control")
  Acked-by: Sakari Ailus <sakari.ailus@linux.intel.com>

Signed-off-by: Kate Hsuan <hpa@redhat.com>