wifi: ath12k: fix memcpy array overflow in ath12k_peer_assoc_h_he()
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 603cf6c2fcdcbc38f1daa316794e7268852677a7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 3 14:37:29 2023 +0200

    wifi: ath12k: fix memcpy array overflow in ath12k_peer_assoc_h_he()
    
    Two memory copies in this function copy from a short array into a longer one,
    using the wrong size, which leads to an out-of-bounds access:
    
    include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                            __read_overflow2_field(q_size_field, size);
                            ^
    include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
    2 errors generated.
    
    Fixes: d889913205cf7 ("wifi: ath12k: driver for Qualcomm Wi-Fi 7 devices")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20230703123737.3420464-1-arnd@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>