cifs: Avoid error pointer dereference
jira LE-1907
Rebuild_History Non-Buildable kernel-rt-4.18.0-553.16.1.rt7.357.el8_10
commit-author Samuel Cabrero <scabrero@suse.de>
commit 0bf1bafb17df03fbd0e8b9a086c39e6f24af7193

The patch 7d6535b72042: "cifs: Simplify reconnect code when dfs
upcall is enabled" leads to the following static checker warning:

	fs/cifs/connect.c:160 reconn_set_next_dfs_target()
	error: 'server->hostname' dereferencing possible ERR_PTR()

Avoid dereferencing the error pointer by early returning on error
condition.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Samuel Cabrero <scabrero@suse.de>
	Signed-off-by: Steve French <stfrench@microsoft.com>
(cherry picked from commit 0bf1bafb17df03fbd0e8b9a086c39e6f24af7193)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>