iommu/vt-d: Fix constant-out-of-range warning
JIRA: https://issues.redhat.com/browse/RHEL-28780
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 4578f989ed6b77c14af86bb882cc5ff0a46a69eb
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 19 19:16:01 2024 +0800

    iommu/vt-d: Fix constant-out-of-range warning

    On 32-bit builds, the vt-d driver causes a warning with clang:

    drivers/iommu/intel/nested.c:112:13: error: result of comparison of constant 18446744073709551615 with expression of type 'unsigned long' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
      112 |         if (npages == U64_MAX)
	  |             ~~~~~~ ^  ~~~~~~~

    Make the variable a 64-bit type, which matches both the caller and the
    use anyway.

    Fixes: f6f3721244a8 ("iommu/vt-d: Add iotlb flush for nested domain")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240213095832.455245-1-arnd@kernel.org
    Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 4578f989ed6b77c14af86bb882cc5ff0a46a69eb)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>