selftests: cgroup: fix cleanup path in test_memcg_subtree_control()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Roman Gushchin <guro@fb.com>
commit e14d314c7a489f060d6d691866fef5f131281718

Dan reported, that cleanup path in test_memcg_subtree_control()
triggers a static checker warning:
  ./tools/testing/selftests/cgroup/test_memcontrol.c:76 \
  test_memcg_subtree_control()
  error: uninitialized symbol 'child2'.

Fix this by initializing child2 and parent2 variables and
split the cleanup path into few stages.

	Signed-off-by: Roman Gushchin <guro@fb.com>
Fixes: 84092dbcf901 ("selftests: cgroup: add memory controller self-tests")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Cc: Dan Carpenter <dan.carpenter@oracle.com>
	Cc: Shuah Khan (Samsung OSG) <shuah@kernel.org>
	Cc: Mike Rapoport <rppt@linux.vnet.ibm.com>
	Signed-off-by: Shuah Khan <shuah@kernel.org>
(cherry picked from commit e14d314c7a489f060d6d691866fef5f131281718)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>