Bluetooth: btmtk: remove #ifdef around declarations
JIRA: https://issues.redhat.com/browse/RHEL-61734

commit 7a8c6fb21a7c913ddb99785b14914dab2f934fbd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 22 11:27:06 2024 +0200

    Bluetooth: btmtk: remove #ifdef around declarations

    The caller of these functions in btusb.c is guarded with an
    if(IS_ENABLED()) style check, so dead code is left out, but the
    declarations are still needed at compile time:

    drivers/bluetooth/btusb.c: In function 'btusb_mtk_reset':
    drivers/bluetooth/btusb.c:2705:15: error: implicit declaration of function 'btmtk_usb_subsys_reset' [-Wimplicit-function-declaration]
     2705 |         err = btmtk_usb_subsys_reset(hdev, btmtk_data->dev_id);
          |               ^~~~~~~~~~~~~~~~~~~~~~
    drivers/bluetooth/btusb.c: In function 'btusb_send_frame_mtk':
    drivers/bluetooth/btusb.c:2720:23: error: implicit declaration of function 'alloc_mtk_intr_urb' [-Wimplicit-function-declaration]
     2720 |                 urb = alloc_mtk_intr_urb(hdev, skb, btusb_tx_complete);
          |                       ^~~~~~~~~~~~~~~~~~
    drivers/bluetooth/btusb.c:2720:21: error: assignment to 'struct urb *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     2720 |                 urb = alloc_mtk_intr_urb(hdev, skb, btusb_tx_complete);
          |                     ^

    Fixes: f0c83a23fcbb ("Bluetooth: btmtk: Fix btmtk.c undefined reference build error")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>