ovl: select EXPORTFS
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 72d42504bd7faa6de1c1644b5e46652933e040a6

We get a link error when EXPORTFS is not enabled:

ERROR: "exportfs_encode_fh" [fs/overlayfs/overlay.ko] undefined!
ERROR: "exportfs_decode_fh" [fs/overlayfs/overlay.ko] undefined!

This adds a Kconfig 'select' statement for overlayfs, the same way that
it is done for the other users of exportfs.

Fixes: 3a1e819b4e80 ("ovl: store file handle of lower inode on copy up")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
(cherry picked from commit 72d42504bd7faa6de1c1644b5e46652933e040a6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>