ASoC: tegra: select CONFIG_SND_SIMPLE_CARD_UTILS
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit 83340b855d222f257354afd272dc8d315fecc3ee
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Jul 19 09:48:03 2024 +0200

    ASoC: tegra: select CONFIG_SND_SIMPLE_CARD_UTILS

    This I2S client driver now uses functions exported from a helper module
    but fails to link when the helper is disabled:

    ERROR: modpost: "simple_util_parse_convert" [sound/soc/tegra/snd-soc-tegra210-i2s.ko] undefined!
    ERROR: modpost: "simple_util_get_sample_fmt" [sound/soc/tegra/snd-soc-tegra210-i2s.ko] undefined!

    Add a Kconfig select line to ensure it's always turned on here.

    Fixes: 2502f8dd8c30 ("ASoC: tegra: I2S client convert formats handling")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Sameer Pujar <spujar@nvidia.com>
    Link: https://patch.msgid.link/20240719074831.3253995-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>