usb: add HAS_IOMEM dependency to USB_FOTG210_HCD
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_FOTG210_HCD (Torez Smith) [1332712]
Rebuild_FUZZ: 94.51%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit eaa86229ff32a9aea80d7aa24289754e2eed8a76
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/eaa86229.failed

drivers/built-in.o: In function `fotg210_hcd_probe':
/home/vegard/linux/drivers/usb/host/fotg210-hcd.c:5637: undefined reference to `devm_ioremap_resource'

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit eaa86229ff32a9aea80d7aa24289754e2eed8a76)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/usb/host/Kconfig