Input: serio-raw - fix potential serio port name truncation
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.13
Tested: with the hid-tools test suite and some hardware

commit d49e7d08f08eb2c553a83b408894aad3cb8ccf5e
Author: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Date:   Wed Sep 4 21:17:26 2024 -0700

    Input: serio-raw - fix potential serio port name truncation

    When compiling with W=1 the following warnings are triggered:

    drivers/input/serio/serio_raw.c: In function ‘serio_raw_connect’:
    drivers/input/serio/serio_raw.c:303:28: error: ‘%ld’ directive output may be truncated writing between 1 and 11 bytes into a region of size 7 [-Werror=format-truncation=]
      303 |                  "serio_raw%ld", (long)atomic_inc_return(&serio_raw_no));

    atomic_inc_return() returns an int, so there is no reason to cast it
    to long and print as such. Fix the issue by removing the cast,
    printing it as unsigned decimal, and expanding the name from 16 to 20
    bytes to accommodate the largest possible port number.

    Link: https://lore.kernel.org/r/20240905041732.2034348-22-dmitry.torokhov@gmail.com
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>