perf/core: Fix reversed NULL check in perf_event_groups_less()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit a6763625ae6f8aa5ee82fcd8fa4e5e38db20dbc6

This NULL check is reversed so it leads to a Smatch warning and
presumably a NULL dereference.

    kernel/events/core.c:1598 perf_event_groups_less()
    error: we previously assumed 'right->cgrp->css.cgroup' could be null
	(see line 1590)

Fixes: 95ed6c707f26 ("perf/cgroup: Order events in RB tree by cgroup id")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
Link: https://lkml.kernel.org/r/20200312105637.GA8960@mwanda
(cherry picked from commit a6763625ae6f8aa5ee82fcd8fa4e5e38db20dbc6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>