selftests/bpf: Fix redefinition of 'off' as different kind of symbol
JIRA: https://issues.redhat.com/browse/RHEL-78291

commit a1e83d4c0361f4b0e3b7ef8b603bf5e5ef60af86
Author: Brahmajit Das <listout@listout.xyz>
Date:   Fri Oct 17 22:45:51 2025 +0530

    selftests/bpf: Fix redefinition of 'off' as different kind of symbol
    
    This fixes the following build error
    
       CLNG-BPF [test_progs] verifier_global_ptr_args.bpf.o
    progs/verifier_global_ptr_args.c:228:5: error: redefinition of 'off' as
    different kind of symbol
       228 | u32 off;
           |     ^
    
    The symbol 'off' was previously defined in
    tools/testing/selftests/bpf/tools/include/vmlinux.h, which includes an
    enum i40e_ptp_gpio_pin_state from
    drivers/net/ethernet/intel/i40e/i40e_ptp.c:
    
    	enum i40e_ptp_gpio_pin_state {
    		end = -2,
    		invalid = -1,
    		off = 0,
    		in_A = 1,
    		in_B = 2,
    		out_A = 3,
    		out_B = 4,
    	};
    
    This enum is included when CONFIG_I40E is enabled. As of commit
    032676ff8217 ("LoongArch: Update Loongson-3 default config file"),
    CONFIG_I40E is set in the defconfig, which leads to the conflict.
    
    Renaming the local variable avoids the redefinition and allows the
    build to succeed.
    
    Suggested-by: Yonghong Song <yonghong.song@linux.dev>
    Signed-off-by: Brahmajit Das <listout@listout.xyz>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20251017171551.53142-1-listout@listout.xyz
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    

Signed-off-by: Ines Qian <iqian@redhat.com>