Kbuild: use -std=gnu11 for KBUILD_USERCFLAGS
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2074118

commit 1e24078113ae69c741cb1b03375a9f1490db7308
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue, 8 Mar 2022 22:56:15 +0100

    Kbuild: use -std=gnu11 for KBUILD_USERCFLAGS

    As we change the C language standard for the kernel from gnu89 to
    gnu11, it makes sense to also update the version for user space
    compilation.

    Some users have older native compilers than what they use for
    kernel builds, so I considered using gnu99 as the default version
    for wider compatibility with gcc-4.6 and earlier.

    However, testing with older compilers showed that we already require
    HOSTCC version 5.1 as well because a lot of host tools include
    linux/compiler.h that uses __has_attribute():

      CC      tools/objtool/exec-cmd.o
    In file included from tools/include/linux/compiler_types.h:36:0,
                     from tools/include/linux/compiler.h:5,
                     from exec-cmd.c:2:
    tools/include/linux/compiler-gcc.h:19:5: error: "__has_attribute" is not defined [-Werror=undef]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Tested-by: Sedat Dilek <sedat.dilek@gmail.com>
    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>