Bluetooth: btmtkuart: mark OF related data as maybe unused
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit a88ea43b73f109e446f6027df237c8f868127a78
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 12:13:54 2023 +0100

    Bluetooth: btmtkuart: mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/bluetooth/btmtkuart.c:971:36: error: ‘mt7668_data’ defined
      but not used [-Werror=unused-const-variable=]
      drivers/bluetooth/btmtkuart.c:966:36: error: ‘mt7663_data’ defined
      but not used [-Werror=unused-const-variable=]
      drivers/bluetooth/btmtkuart.c:962:36: error: ‘mt7622_data’ defined
      but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>