ASoC: tegra: Fix -Wuninitialized in tegra210_amx_platform_probe()
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 41cb1126bed152f7679417834ad7ea39f2252dfb
Author: Nathan Chancellor <nathan@kernel.org>
Date: Wed Oct 11 13:21:51 2023 -0700

    ASoC: tegra: Fix -Wuninitialized in tegra210_amx_platform_probe()

    Clang warns (or errors with CONFIG_WERROR=y):

      sound/soc/tegra/tegra210_amx.c:553:10: error: variable 'soc_data' is uninitialized when used here [-Werror,-Wuninitialized]
        553 |                                             soc_data->regmap_conf);
            |                                             ^~~~~~~~

    A refactoring removed the initialization of this variable but its use
    was not updated. Use the soc_data value in the amx variable to resolve
    the warning and remove the soc_data variable, as it is now entirely
    unused.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/1943
    Fixes: 9958d85968ed ("ASoC: Use device_get_match_data()")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://lore.kernel.org/r/20231011-asoc-tegra-fix-uninit-soc_data-v1-1-0ef0ab44cf48@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>