bpf_trace: Make dependent on PERF_EVENTS
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Steven Rostedt <rostedt@goodmis.org>
commit a31d82d85afdcbdb8c4128dfd6146992dc6b3576
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/a31d82d8.failed

Arnd Bergmann reported:

  In my ARM randconfig tests, I'm getting a build error for
  newly added code in bpf_perf_event_read and bpf_perf_event_output
  whenever CONFIG_PERF_EVENTS is disabled:

  kernel/trace/bpf_trace.c: In function 'bpf_perf_event_read':
  kernel/trace/bpf_trace.c:203:11: error: 'struct perf_event' has no member named 'oncpu'
  if (event->oncpu != smp_processor_id() ||
           ^
  kernel/trace/bpf_trace.c:204:11: error: 'struct perf_event' has no member named 'pmu'
        event->pmu->count)

  This can happen when UPROBE_EVENT is enabled but KPROBE_EVENT
  is disabled. I'm not sure if that is a configuration we care
  about, otherwise we could prevent this case from occuring by
  adding Kconfig dependencies.

Looking at this further, it's really that UPROBE_EVENT enables PERF_EVENTS.
By just having BPF_EVENTS depend on PERF_EVENTS, then all is fine.

Link: http://lkml.kernel.org/r/4525348.Aq9YoXkChv@wuerfel
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Steven Rostedt <rostedt@goodmis.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit a31d82d85afdcbdb8c4128dfd6146992dc6b3576)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	kernel/trace/Kconfig