PCI: vmd: Fix indentation issue in vmd_shutdown()
JIRA: https://issues.redhat.com/browse/RHEL-67693
Upstream Status: 4654cf52cbd07cb2d6ab6f55bcc5eb2dae8b736a

commit 4654cf52cbd07cb2d6ab6f55bcc5eb2dae8b736a
Author: Riyan Dhiman <riyandhiman14@gmail.com>
Date:   Sun Sep 1 14:56:02 2024 +0530

    PCI: vmd: Fix indentation issue in vmd_shutdown()

    The code in vmd_shutdown() had an indentation issue where spaces were
    used instead of tabs. This commit corrects the indentation to use tabs,
    adhering to the Linux kernel coding style guidelines.

    Issue reported by the checkpatch.pl script:

      ERROR: code indent should use tabs where possible
      #1056: FILE: drivers/pci/controller/vmd.c:1056:
      +        struct vmd_dev *vmd = pci_get_drvdata(dev);$

      WARNING: please, no spaces at the start of a line
      #1056: FILE: drivers/pci/controller/vmd.c:1056:
      +        struct vmd_dev *vmd = pci_get_drvdata(dev);$

      ERROR: code indent should use tabs where possible
      #1058: FILE: drivers/pci/controller/vmd.c:1058:
      +        vmd_remove_irq_domain(vmd);$

      WARNING: please, no spaces at the start of a line
      #1058: FILE: drivers/pci/controller/vmd.c:1058:
      +        vmd_remove_irq_domain(vmd);$

    No functional changes are intended.

    Link: https://lore.kernel.org/linux-pci/20240901092602.17414-1-riyandhiman14@gmail.com
    Signed-off-by: Riyan Dhiman <riyandhiman14@gmail.com>
    [kwilczynski: commit log]
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@kernel.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>