net/mlx5e: use %pad format string for dma_addr_t
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [netdrv] mlx5e: use pad format string for dma_addr_t (Don Dutile) [1385330 1417286]
Rebuild_FUZZ: 94.51%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 9afd895271d91cd6ed743d22fce043f8c28b30ce

On 32-bit ARM with 64-bit dma_addr_t I get this warning about an
incorrect format string:

In file included from /git/arm-soc/drivers/net/ethernet/mellanox/mlx5/core/alloc.c:42:0:
drivers/net/ethernet/mellanox/mlx5/core/alloc.c: In function ‘mlx5_frag_buf_alloc_node’:
drivers/net/ethernet/mellanox/mlx5/core/alloc.c:134:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]

We have the special %pad format for printing dma_addr_t, so use that
to print the correct address and avoid the warning.

Fixes: 1c1b522808a1 ("net/mlx5e: Implement Fragmented Work Queue (WQ)")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 9afd895271d91cd6ed743d22fce043f8c28b30ce)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>