dt-bindings: net: mvusb: Fix example errors
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Rob Herring <robh@kernel.org>
commit d61f4d61ff7f73bed1f4c613de59b4534c08a088

The example for Marvell USB to MDIO Controller doesn't build:

Error: Documentation/devicetree/bindings/net/marvell,mvusb.example.dts:18.9-14 syntax error
FATAL ERROR: Unable to parse input tree

This is due to label refs being used which can't be resolved.

Fixes: 61e0150cb44b ("dt-bindings: net: add marvell usb to mdio bindings")
	Cc: Tobias Waldekranz <tobias@waldekranz.com>
	Cc: "David S. Miller" <davem@davemloft.net>
	Cc: netdev@vger.kernel.org
	Signed-off-by: Rob Herring <robh@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d61f4d61ff7f73bed1f4c613de59b4534c08a088)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>