drivers/vfio_pci_core: Change PXD_ORDER check from switch case to if/else block
JIRA: https://issues.redhat.com/browse/RHEL-149504

commit 948b71aa81cd89b222942db6055e8d9c51c54e78
Author: Ritesh Harjani (IBM) <ritesh.list@gmail.com>
Date:   Mon Mar 9 18:08:37 2026 +0530

    drivers/vfio_pci_core: Change PXD_ORDER check from switch case to if/else block

    Architectures like PowerPC uses runtime defined values for
    PMD_ORDER/PUD_ORDER. This is because it can use either RADIX or HASH MMU
    at runtime using kernel cmdline. So the pXd_index_size is not known at
    compile time. Without this fix, when we add huge pfn support on powerpc
    in the next patch, vfio_pci_core driver compilation can fail with the
    following errors.

      CC [M]  drivers/vfio/vfio_main.o
      CC [M]  drivers/vfio/group.o
      CC [M]  drivers/vfio/container.o
      CC [M]  drivers/vfio/virqfd.o
      CC [M]  drivers/vfio/vfio_iommu_spapr_tce.o
      CC [M]  drivers/vfio/pci/vfio_pci_core.o
      CC [M]  drivers/vfio/pci/vfio_pci_intrs.o
      CC [M]  drivers/vfio/pci/vfio_pci_rdwr.o
      CC [M]  drivers/vfio/pci/vfio_pci_config.o
      CC [M]  drivers/vfio/pci/vfio_pci.o
      AR      kernel/built-in.a
    ../drivers/vfio/pci/vfio_pci_core.c: In function ‘vfio_pci_vmf_insert_pfn’:
    ../drivers/vfio/pci/vfio_pci_core.c:1678:9: error: case label does not reduce to an integer constant
     1678 |         case PMD_ORDER:
          |         ^~~~
    ../drivers/vfio/pci/vfio_pci_core.c:1682:9: error: case label does not reduce to an integer constant
     1682 |         case PUD_ORDER:
          |         ^~~~
    make[6]: *** [../scripts/Makefile.build:289: drivers/vfio/pci/vfio_pci_core.o] Error 1
    make[6]: *** Waiting for unfinished jobs....
    make[5]: *** [../scripts/Makefile.build:546: drivers/vfio/pci] Error 2
    make[5]: *** Waiting for unfinished jobs....
    make[4]: *** [../scripts/Makefile.build:546: drivers/vfio] Error 2
    make[3]: *** [../scripts/Makefile.build:546: drivers] Error 2

    Fixes: f9e54c3a2f5b7 ("vfio/pci: implement huge_fault support")
    Signed-off-by: Ritesh Harjani (IBM) <ritesh.list@gmail.com>
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Reviewed-by: Alex Williamson <alex@shazbot.org>
    Reviewed-by: Christophe Leroy (CS GROUP) <chleroy@kernel.org>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://patch.msgid.link/b155e19993ee1f5584c72050192eb468b31c5029.1773058761.git.ritesh.list@gmail.com

Conflicts:

    - drivers/vfio/pci/vfio_pci_core.c: Context change due to missing
      commits 79065255abc4 ("mm: remove remaining uses of PFN_DEV")
      and 21aa65bf82a7 ("mm: remove callers of pfn_t functionality").
      Kept previous interface using the pfn_t type.

Signed-off-by: Cédric Le Goater <clg@redhat.com>