net: sched: Remove TCA_OPTIONS from policy
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
Rebuild_CHGLOG: - [net] sched: Remove TCA_OPTIONS from policy (Davide Caratti) [1658516]
Rebuild_FUZZ: 93.67%
commit-author David Ahern <dsahern@gmail.com>
commit e72bde6b66299602087c8c2350d36a525e75d06e

Marco reported an error with hfsc:
root@Calimero:~# tc qdisc add dev eth0 root handle 1:0 hfsc default 1
Error: Attribute failed policy validation.

Apparently a few implementations pass TCA_OPTIONS as a binary instead
of nested attribute, so drop TCA_OPTIONS from the policy.

Fixes: 8b4c3cdd9dd8 ("net: sched: Add policy validation for tc attributes")
	Reported-by: Marco Berizzi <pupilla@libero.it>
	Signed-off-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit e72bde6b66299602087c8c2350d36a525e75d06e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>