sfc: use padding to fix alignment in loopback test
JIRA: https://issues.redhat.com/browse/RHEL-11017

commit cf60ed469629927fe43c2f4b4ef28a563d991935
Author: Edward Cree <ecree.xilinx@gmail.com>
Date:   Fri Jun 23 19:38:04 2023 +0100

    sfc: use padding to fix alignment in loopback test

    Add two bytes of padding to the start of struct efx_loopback_payload,
     which are not sent on the wire.  This ensures the 'ip' member is
     4-byte aligned, preventing the following W=1 warning:
    net/ethernet/sfc/selftest.c:46:15: error: field ip within 'struct efx_loopback_payload' is less aligned than 'struct iphdr' and is usually due to 'struct efx_loopback_payload' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
            struct iphdr ip;

    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Edward Cree <ecree.xilinx@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>