ASoC: txx9: Remove unused rtd variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: txx9: Remove unused rtd variable (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 92.68%
commit-author Paul Burton <paulburton@kernel.org>
commit ec0f6a4c4a987aa20b2e77e0db2ae555276e45e6

Commit a857e073ffc6 ("ASoC: txx9: txx9aclc: remove snd_pcm_ops") removed
the last use of the rtd variable but didn't remove its definition,
leading to the following warning/error for MIPS rbtx49xx_defconfig
builds:

sound/soc/txx9/txx9aclc.c: In function 'txx9aclc_pcm_hw_params':
sound/soc/txx9/txx9aclc.c:54:30: error: unused variable 'rtd'
    [-Werror=unused-variable]
  struct snd_soc_pcm_runtime *rtd = snd_pcm_substream_chip(substream);
                              ^~~

Resolve this by removing the unused variable.

	Signed-off-by: Paul Burton <paulburton@kernel.org>
Fixes: a857e073ffc6 ("ASoC: txx9: txx9aclc: remove snd_pcm_ops")
	Cc: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: Liam Girdwood <lgirdwood@gmail.com>
	Cc: Jaroslav Kysela <perex@perex.cz>
	Cc: Takashi Iwai <tiwai@suse.com>
	Cc: alsa-devel@alsa-project.org
Link: https://lore.kernel.org/r/20200109191422.334516-1-paulburton@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ec0f6a4c4a987aa20b2e77e0db2ae555276e45e6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>