x86/qspinlock-paravirt: Fix missing-prototype warning
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 8874a414f8f706daf1de467cbf2550988ebec09d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 3 10:26:19 2023 +0200

    x86/qspinlock-paravirt: Fix missing-prototype warning

    __pv_queued_spin_unlock_slowpath() is defined in a header file as
    a global function, and designed to be called from inline asm, but
    there is no prototype visible in the definition:

      kernel/locking/qspinlock_paravirt.h:493:1: error: no previous \
        prototype for '__pv_queued_spin_unlock_slowpath' [-Werror=missing-prototypes]

    Add this to the x86 header that contains the inline asm calling it,
    and ensure this gets included before the definition, rather than
    after it.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230803082619.1369127-8-arnd@kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>