net/mlx5: Eliminate query xsrq dead code
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [netdrv] mlx5: Eliminate query xsrq dead code (Alaa Hleihel) [1642498]
Rebuild_FUZZ: 94.74%
commit-author Saeed Mahameed <saeedm@mellanox.com>
commit b2d3907c234618c20239127f2c234b4e92adf5ef

1. This function is not used anywhere in mlx5 driver
2. It has a memcpy statement that makes no sense and produces build
warning with gcc8

drivers/net/ethernet/mellanox/mlx5/core/transobj.c: In function 'mlx5_core_query_xsrq':
drivers/net/ethernet/mellanox/mlx5/core/transobj.c:347:3: error: 'memcpy' source argument is the same as destination [-Werror=restrict]

Fixes: 01949d0109ee ("net/mlx5_core: Enable XRCs and SRQs when using ISSI > 0")
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit b2d3907c234618c20239127f2c234b4e92adf5ef)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>