openvswitch: Export lockdep_ovsl_is_held to modules.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [net] openvswitch: Export lockdep_ovsl_is_held to modules (Jiri Benc) [1156461 1211348]
Rebuild_FUZZ: 99.03%
commit-author David S. Miller <davem@davemloft.net>
commit 2c6c49ded7a7209fe8618423c457b8000ee528a4

ERROR: "lockdep_ovsl_is_held" [net/openvswitch/vport-gre.ko] undefined!

	Reported-by: Alexei Starovoitov <alexei.starovoitov@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 2c6c49ded7a7209fe8618423c457b8000ee528a4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>