arm64: smp: Fix compilation error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Shaokun Zhang <zhangshaokun@hisilicon.com>
commit 1236cd2bad8bc9038af90830cf017c770fdba03c

For arm64: updates for 4.21, there is a compilation error:
arch/arm64/kernel/head.S: Assembler messages:
arch/arm64/kernel/head.S:824: Error: missing ')'
arch/arm64/kernel/head.S:824: Error: missing ')'
arch/arm64/kernel/head.S:824: Error: missing ')'
arch/arm64/kernel/head.S:824: Error: unexpected characters following instruction at operand 2 -- `mov x2,#(2)|(2U<<(8))'
scripts/Makefile.build:391: recipe for target 'arch/arm64/kernel/head.o' failed
make[1]: *** [arch/arm64/kernel/head.o] Error 1
GCC version is gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

Let's fix it using the UL() macro.

Fixes: 66f16a24512f ("arm64: smp: Rework early feature mismatched detection")
	Cc: Catalin Marinas <catalin.marinas@arm.com>
	Cc: Will Deacon <will.deacon@arm.com>
	Tested-by: John Stultz <john.stultz@linaro.org>
	Signed-off-by: Shaokun Zhang <zhangshaokun@hisilicon.com>
[will: consistent use of UL() for all shifts in asm constants]
	Signed-off-by: Will Deacon <will.deacon@arm.com>
(cherry picked from commit 1236cd2bad8bc9038af90830cf017c770fdba03c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>