bpf: Fix uninitialized symbol in bpf_perf_link_fill_kprobe()
JIRA: https://issues.redhat.com/browse/RHEL-10691

commit 0aa35162d2a1ed7ae5303b8d91f7290d3b8b9219
Author: Yafang Shao <laoar.shao@gmail.com>
Date:   Sun Aug 13 14:18:59 2023 +0000

    bpf: Fix uninitialized symbol in bpf_perf_link_fill_kprobe()

    The commit 1b715e1b0ec5 ("bpf: Support ->fill_link_info for perf_event") leads
    to the following Smatch static checker warning:

        kernel/bpf/syscall.c:3416 bpf_perf_link_fill_kprobe()
        error: uninitialized symbol 'type'.

    That can happens when uname is NULL. So fix it by verifying the uname when we
    really need to fill it.

    Fixes: 1b715e1b0ec5 ("bpf: Support ->fill_link_info for perf_event")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Yafang Shao <laoar.shao@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Closes: https://lore.kernel.org/bpf/85697a7e-f897-4f74-8b43-82721bebc462@kili.mountain
    Link: https://lore.kernel.org/bpf/20230813141900.1268-2-laoar.shao@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>