ksmbd: fix non-IPv6 build
JIRA: https://issues.redhat.com/browse/RHEL-190706

commit 8f7df60fe063b6b8f039af1042a4b99214347dd1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 10 23:30:00 2026 +0900

    ksmbd: fix non-IPv6 build
    
    The newly added procfs code fails to build when CONFIG_IPv6 is disabled:
    
    fs/smb/server/connection.c: In function 'proc_show_clients':
    fs/smb/server/connection.c:47:58: error: 'struct ksmbd_conn' has no member named 'inet6_addr'; did you mean 'inet_addr'?
       47 |                         seq_printf(m, "%-20pI6c", &conn->inet6_addr);
          |                                                          ^~~~~~~~~~
          |                                                          inet_addr
    make[7]: *** [scripts/Makefile.build:279: fs/smb/server/connection.o] Error 1
    fs/smb/server/mgmt/user_session.c: In function 'show_proc_sessions':
    fs/smb/server/mgmt/user_session.c:215:65: error: 'struct ksmbd_conn' has no member named 'inet6_addr'; did you mean 'inet_addr'?
      215 |                         seq_printf(m, " %-40pI6c", &chan->conn->inet6_addr);
          |                                                                 ^~~~~~~~~~
          |                                                                 inet_addr
    
    Rearrange the condition to allow adding a simple preprocessor conditional.
    
    Fixes: b38f99c1217a ("ksmbd: add procfs interface for runtime monitoring and statistics")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Namjae Jeon <linkinjeon@kernel.org>
    Signed-off-by: Steve French <stfrench@microsoft.com>

Signed-off-by: Paulo Alcantara <paalcant@redhat.com>