ASoC: Intel: fix sof-nau8825 link failure
Bugzilla: https://bugzilla.redhat.com/2179848

commit 63f3d99b7efe4c5404a9388c05780917099cecf4
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Dec 21 14:25:48 2022 +0100

    ASoC: Intel: fix sof-nau8825 link failure

    The snd-soc-sof_nau8825.ko module fails to link unless the
    sof_realtek_common support is also enabled:

    ERROR: modpost: "sof_rt1015p_codec_conf" [sound/soc/intel/boards/snd-soc-sof_nau8825.ko] undefined!
    ERROR: modpost: "sof_rt1015p_dai_link" [sound/soc/intel/boards/snd-soc-sof_nau8825.ko] undefined!

    Fixes: 8d0872f6239f ("ASoC: Intel: add sof-nau8825 machine driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20221221132559.2402341-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>