mei: fix vsc dependency
JIRA: https://issues.redhat.com/browse/RHEL-77170

commit 95171e45663307fc33a939f0220b39afadfe7cb9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 14 18:39:31 2023 +0000

    mei: fix vsc dependency

    CONFIG_INTEL_MEI_VSC_HW can be set to built-in even with CONFIG_MEI=m,
    but then the driver is not built because Kbuild never enters the
    drivers/misc/mei directory for built-in files, leading to a link
    failure:

    ERROR: modpost: "vsc_tp_reset" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_init" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_xfer" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_need_read" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_intr_enable" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_intr_synchronize" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_intr_disable" [drivers/misc/mei/mei-vsc.ko] undefined!
    ERROR: modpost: "vsc_tp_register_event_cb" [drivers/misc/mei/mei-vsc.ko] undefined!

    Add an explicit dependency on CONFIG_MEI that was apparently missing,
    to ensure the VSC_HW driver cannot be built-in with MEI itself being
    a loadable module.

    Fixes: 566f5ca97680 ("mei: Add transport driver for IVSC device")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Sakari Ailus <sakari.ailus@linux.intel.com>
    Reviewed-by: Wentong Wu <wentong.wu@intel.com>
    Link: https://lore.kernel.org/r/20231214183946.109124-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: David Arcari <darcari@redhat.com>