ASoC: Intel: sof_sdw_amp: mark coeff tables with __maybe_unused
Bugzilla: https://bugzilla.redhat.com/2179848

commit 041fe8858475a0337b28404ec5136f4fc583b3aa
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Fri Nov 18 09:51:06 2022 +0800

    ASoC: Intel: sof_sdw_amp: mark coeff tables with __maybe_unused

    The same file provides two tables used in separate drivers, make them
    as __maybe_unused to avoid errors:

    sound/soc/intel/boards/sof_sdw_amp_coeff_tables.h:163:17: error:
    ‘dell_0b00_bq_params’ defined but not used
    [-Werror=unused-const-variable=]
      163 | static const u8 dell_0b00_bq_params[] = {

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>
    Link: https://lore.kernel.org/r/20221118015106.532302-1-yung-chuan.liao@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>