objtool: Build with disassembly can fail when including bdf.h
JIRA: https://redhat.atlassian.net/browse/RHEL-152189

commit 59bfa6408214b6533d8691715cf5459e89b45b89
Author: Alexandre Chartre <alexandre.chartre@oracle.com>
Date:   Wed Nov 26 14:45:19 2025 +0100

    objtool: Build with disassembly can fail when including bdf.h

    Building objtool with disassembly support can fail when including
    the bdf.h file:

      In file included from tools/objtool/include/objtool/arch.h:108,
                       from check.c:14:
      /usr/include/bfd.h:35:2: error: #error config.h must be included before this header
         35 | #error config.h must be included before this header
            |  ^~~~~

    This check is present in the bfd.h file generated from the binutils
    source code, but it is not necessarily present in the bfd.h file
    provided in a binutil package (for example, it is not present in
    the binutil RPM).

    The solution to this issue is to define the PACKAGE macro before
    including bfd.h. This is the solution suggested by the binutil
    developer in bug 14243, and it is used by other kernel tools
    which also use bfd.h (perf and bpf).

    Fixes: 59953303827ec ("objtool: Disassemble code with libopcodes instead of running objdump")
    Closes: https://lore.kernel.org/all/3fa261fd-3b46-4cbe-b48d-7503aabc96cb@oracle.com/
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Suggested-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Alexandre Chartre <alexandre.chartre@oracle.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://sourceware.org/bugzilla/show_bug.cgi?id=14243
    Link: https://patch.msgid.link/20251126134519.1760889-1-alexandre.chartre@oracle.com

Signed-off-by: Yannick Cote <ycote@redhat.com>