nfs: do not initialise statics to 0
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Wei Tang <tangwei@cmss.chinamobile.com>
commit ed476752493bc997f1690516fdc0609ddcbaca82

This patch fixes the checkpatch.pl error to nfs4sysctl.c:

ERROR: do not initialise statics to 0

	Signed-off-by: Wei Tang <tangwei@cmss.chinamobile.com>
	Signed-off-by: Trond Myklebust <trond.myklebust@primarydata.com>
(cherry picked from commit ed476752493bc997f1690516fdc0609ddcbaca82)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>