iommufd/selftest: Add missing kconfig for DMA_SHARED_BUFFER
JIRA: https://issues.redhat.com/browse/RHEL-111742

commit faa37ff3bf18d5242fe3d54f5462b1c3254c2567
Author: Jason Gunthorpe <jgg@ziepe.ca>
Date:   Tue Jan 6 15:22:11 2026 -0400

    iommufd/selftest: Add missing kconfig for DMA_SHARED_BUFFER

    The test doesn't build without it, dma-buf.h does not provide stub
    functions if it is not enabled. Compilation can fail with:

     ERROR:root:ld: vmlinux.o: in function `iommufd_test':
     (.text+0x3b1cdd): undefined reference to `dma_buf_get'
     ld: (.text+0x3b1d08): undefined reference to `dma_buf_put'
     ld: (.text+0x3b2105): undefined reference to `dma_buf_export'
     ld: (.text+0x3b211f): undefined reference to `dma_buf_fd'
     ld: (.text+0x3b2e47): undefined reference to `dma_buf_move_notify'

    Add the missing select.

    Fixes: d2041f1f11dd ("iommufd/selftest: Add some tests for the dmabuf flow")
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
    Signed-off-by: Joerg Roedel <joerg.roedel@amd.com>

Conflicts:

    - drivers/iommu/iommufd/io_pagetable.c: Context change due missing
      commit e93d5945ed5b ("iommufd: Change the selftest to use
      iommupt instead of xarray")

Signed-off-by: Cédric Le Goater <clg@redhat.com>