selftests/mm/mkdirty: fix memory leak in test_uffdio_copy()
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 7882d8fc8fe0c2b2a01f09e56edf82df6b3013fd
Author: liuye <liuye@kylinos.cn>
Date:   Tue Jan 14 10:38:38 2025 +0800

    selftests/mm/mkdirty: fix memory leak in test_uffdio_copy()

    Release memory before exception branch returns to prevent memory leaks

    Checking tools/testing/selftests/mm/mkdirty.c ...
    tools/testing/selftests/mm/mkdirty.c:283:3: error: Memory leak: src [memleak]
      return;
      ^

    Link: https://lkml.kernel.org/r/20250114023838.48589-1-liuye@kylinos.cn
    Signed-off-by: liuye <liuye@kylinos.cn>
    Reviewed-by: David Hildenbrand <david@redhat.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>