perf tools: Fix calloc() arguments to address error introduced in gcc-14
JIRA: https://issues.redhat.com/browse/RHEL-25824

upstream
========
commit 7bbe8f0071dfa23fcc3b2864ec9f3b1aeb7ab2df
Author: Sun Haiyong <sunhaiyong@loongson.cn>
Date: Sat Jan 6 17:41:29 2024 +0800

description
===========
the definition of calloc is as follows:

    void *calloc(size_t nmemb, size_t size);

number of members is in the first parameter and the size is in the
second parameter.

Fix error messages on gcc 14 20240102:

  error: 'calloc' sizes specified with 'sizeof' in the earlier argument and
  not in the later argument [-Werror=calloc-transposed-args]

Committer notes:

I noticed this on fedora 40 and rawhide.

    Signed-off-by: Sun Haiyong <sunhaiyong@loongson.cn>
    Acked-by: Namhyung Kim <namhyung@kernel.org>
    Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Cc: Ian Rogers <irogers@google.com>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Link: https://lore.kernel.org/r/20240106094129.3337057-1-siyanteng@loongson.cn
    Signed-off-by: Yanteng Si <siyanteng@loongson.cn>
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>