Bluetooth: btmrvl_sdio: mark OF related data as maybe unused
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit 04909d7bf847bc0b939a5571a1a1fcbe5f2e2ead
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 12:13:52 2023 +0100

    Bluetooth: btmrvl_sdio: mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      drivers/bluetooth/btmrvl_sdio.c:43:34: error:
      ‘btmrvl_sdio_of_match_table’ defined but not used
      [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>