enic: Make dummy rfs functions inline to fix !CONFIG_RFS_ACCEL build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 644a918d20336a7deaa81f675c3c2f25bf3dafbb

If CONFIG_RFS_ACCEL=n:

drivers/net/ethernet/cisco/enic/enic_main.c: In function 'enic_open':
drivers/net/ethernet/cisco/enic/enic_main.c:1603:2: error: implicit declaration of function 'enic_rfs_flw_tbl_init' [-Werror=implicit-function-declaration]
drivers/net/ethernet/cisco/enic/enic_main.c: In function 'enic_stop':
drivers/net/ethernet/cisco/enic/enic_main.c:1630:2: error: implicit declaration of function 'enic_rfs_flw_tbl_free' [-Werror=implicit-function-declaration]

Introduced in commit a145df23ef32c7b933875f334ba28791ee75766e ("enic: Add
Accelerated RFS support").

Dummy functions are provided, but their prototypes are missing, causing the
build failure.  Provide dummy static inline functions instead to fix this.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 644a918d20336a7deaa81f675c3c2f25bf3dafbb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>