ASoC: rt5514: mark PM functions as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: rt5514: mark PM functions as __maybe_unused (Jaroslav Kysela) [1535427]
Rebuild_FUZZ: 94.23%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7e6358ec3b6f69815a42af6203219584a80d4e22

The new functions are only used when CONFIG_PM is enabled,
leading to a harmless warning:

sound/soc/codecs/rt5514-spi.c:474:12: error: 'rt5514_resume' defined but not used [-Werror=unused-function]
sound/soc/codecs/rt5514-spi.c:464:12: error: 'rt5514_suspend' defined but not used [-Werror=unused-function]

This marks them as __maybe_unused to make the build silent
again.

Fixes: 58f1c07d23cd ("ASoC: rt5514: Voice wakeup support.")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 7e6358ec3b6f69815a42af6203219584a80d4e22)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>