ASoC: rt5575: fix SPI dependency
JIRA: https://issues.redhat.com/browse/RHEL-168082

commit 1db63f6af17945aed7497ce34a5648add0c1b6d9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Feb 2 10:54:12 2026 +0100

    ASoC: rt5575: fix SPI dependency

    The rt5575 driver fails to link when SPI support is in a loadable
    module but the codec is built-in:

    x86_64-linux-ld: vmlinux.o: in function `rt5575_i2c_probe':
    rt5575.c:(.text+0x9792ce): undefined reference to `rt5575_spi_get_device'
    rt5575.c:(.text+0x979332): undefined reference to `rt5575_spi_fw_load'

    Change the symbol in to a 'bool' and add a dependency that rules
    out the broken configuration.

    Fixes: 420739112e95 ("ASoC: rt5575: Add the codec driver for the ALC5575")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260202095432.1234133-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>