ASoC: amd: acp: Fix snd_soc_acpi_mach id's duplicate symbol error
JIRA: https://issues.redhat.com/browse/RHEL-80658

Conflicts: Kconfig - AMD_NODE not available

commit 9c2c0ef6400980f09b377be250f5dff14dbbf3b6
Author: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Date: Mon Mar 17 12:54:07 2025 +0530

    ASoC: amd: acp: Fix snd_soc_acpi_mach id's duplicate symbol error

    Move snd_soc_acpi_mach id's of all acp platforms form header file to
    amd-acpi-mach.c file to avoid below errors.

    ld.lld: error: duplicate symbol: amp_rt1019
    ld.lld: error: duplicate symbol: amp_max
    ld.lld: error: duplicate symbol: snd_soc_acpi_amd_acp63_acp_machines
    ld.lld: error: duplicate symbol: snd_soc_acpi_amd_acp70_acp_machines
    ld.lld: error: duplicate symbol: snd_soc_acpi_amd_rmb_acp_machines
    ld.lld: error: duplicate symbol: snd_soc_acpi_amd_acp_machines

    Fixes: 6e60db74b69c ("ASoC: amd: acp: Refactor acp machine select")

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202503160801.yExt0K2E-lkp@intel.com/
    Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
    Link: https://patch.msgid.link/20250317072413.88971-1-venkataprasad.potturu@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>