btrfs: Fix compile error when CONFIG_SECURITY is not set.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [fs] btrfs: Fix compile error when CONFIG_SECURITY is not set (Eric Sandeen) [1205873]
Rebuild_FUZZ: 99.12%
commit-author Qu Wenruo <quwenruo@cn.fujitsu.com>
commit a43bb39b5c710e79e921fb76341bacc418cfde78

Fix the following compile error when CONFIG_SECURITY is not set:

error: 'struct security_mnt_opts' has no member named 'num_mnt_opts'

	Signed-off-by: Qu Wenruo <quwenruo@cn.fujitsu.com>
	Signed-off-by: Chris Mason <clm@fb.com>
(cherry picked from commit a43bb39b5c710e79e921fb76341bacc418cfde78)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>