x86/microcode/amd: Fix snprintf() format string warning in W=1 build
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 2e9064faccd1a5b9de8c6f4b23d9f4948901cbe9
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Mon Oct 16 18:48:58 2023 -0400

    x86/microcode/amd: Fix snprintf() format string warning in W=1 build

    Building with GCC 11.x results in the following warning:

      arch/x86/kernel/cpu/microcode/amd.c: In function ‘find_blobs_in_containers’:
      arch/x86/kernel/cpu/microcode/amd.c:504:58: error: ‘h.bin’ directive output may be truncated writing 5 bytes into a region of size between 1 and 7 [-Werror=format-truncation=]
      arch/x86/kernel/cpu/microcode/amd.c:503:17: note: ‘snprintf’ output between 35 and 41 bytes into a destination of size 36

    The issue is that GCC does not know that the family can only be a byte
    (it ultimately comes from CPUID).  Suggest the right size to the compiler
    by marking the argument as char-size ("hh").  While at it, instead of
    using the slightly more obscure precision specifier use the width with
    zero padding (over 23000 occurrences in kernel sources, vs 500 for
    the idiom using the precision).

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Closes: https://lore.kernel.org/oe-kbuild-all/202308252255.2HPJ6x5Q-lkp@intel.com/
    Link: https://lore.kernel.org/r/20231016224858.2829248-1-pbonzini@redhat.com

Signed-off-by: Prarit Bhargava <prarit@redhat.com>