net: phy: aquantia: switch to crc_itu_t()
JIRA: https://issues.redhat.com/browse/RHEL-33716

commit 6c8e2407100e4ff1db86e4af65b74be7895031a2
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Thu Dec 21 13:09:46 2023 +1100

    net: phy: aquantia: switch to crc_itu_t()

    After merging the net-next tree, today's linux-next build (x86_64
    allmodconfig) failed like this:

    drivers/net/phy/aquantia/aquantia_firmware.c: In function 'aqr_fw_load_memory':
    drivers/net/phy/aquantia/aquantia_firmware.c:135:23: error: implicit declaration of function 'crc_ccitt_false'; did you mean 'crc_ccitt_byte'? [-Werror=implicit-function-declaration]
      135 |                 crc = crc_ccitt_false(crc, crc_data, sizeof(crc_data));
          |                       ^~~~~~~~~~~~~~~
          |                       crc_ccitt_byte

    Caused by commit e93984ebc1c8 ("net: phy: aquantia: add firmware load support")
    interacting with commit ("lib: crc_ccitt_false() is identical to crc_itu_t()")
    from the mm tree.

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Link: https://lore.kernel.org/r/20231221130946.7ed9a805@canb.auug.org.au
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>