smb: server: Fix building with GCC 15
JIRA: https://issues.redhat.com/browse/RHEL-116054

commit e18655cf35a5958fbf4ae9ca3ebf28871a3a1801
Author: Brahmajit Das <brahmajit.xyz@gmail.com>
Date:   Tue Nov 26 11:41:35 2024 +0530

    smb: server: Fix building with GCC 15
    
    GCC 15 introduces -Werror=unterminated-string-initialization by default,
    this results in the following build error
    
    fs/smb/server/smb_common.c:21:35: error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-ini
    tialization]
       21 | static const char basechars[43] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-!@#$%";
          |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    
    To this we are replacing char basechars[43] with a character pointer
    and then using strlen to get the length.
    
    Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>
    Acked-by: Namjae Jeon <linkinjeon@kernel.org>
    Signed-off-by: Steve French <stfrench@microsoft.com>

Signed-off-by: Paulo Alcantara <paalcant@redhat.com>