ALSA: fix kernel-doc build warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 3f1185d6c9d3fe91aa85ec8d3f4d71207452c458

Fix kernel-doc build error. A symbol that ends with an underscore
character ('_') has special meaning in reST (reStructuredText), so add
a '*' to prevent this error and to indicate that there are several of
these values to choose from.

../sound/core/jack.c:312: ERROR: Unknown target name: "snd_jack_btn".

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 3f1185d6c9d3fe91aa85ec8d3f4d71207452c458)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>