net: atlantic: Define aq_pm_ops conditionally on CONFIG_PM
JIRA: https://issues.redhat.com/browse/RHEL-36002

commit 4f163bf82b0244bf4d1e9a6b0f4cf4e90b42496e
Author: Tom Rix <trix@redhat.com>
Date:   Fri Apr 28 17:43:21 2023 -0400

    net: atlantic: Define aq_pm_ops conditionally on CONFIG_PM

    For s390, gcc with W=1 reports
    drivers/net/ethernet/aquantia/atlantic/aq_pci_func.c:458:32: error:
      'aq_pm_ops' defined but not used [-Werror=unused-const-variable=]
      458 | static const struct dev_pm_ops aq_pm_ops = {
          |                                ^~~~~~~~~

    The only use of aq_pm_ops is conditional on CONFIG_PM.
    The definition of aq_pm_ops and its functions should also
    be conditional on CONFIG_PM.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>