KVM: Fix ERROR: do not initialise statics to 0 or NULL in kvm_main.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Xiubo Li <lixiubo@cmss.chinamobile.com>
commit f4fee93270abbf862aab268111ac1e12934130c4

ERROR: do not initialise statics to 0 or NULL
+static int kvm_usage_count = 0;

The kvm_usage_count will be placed to .bss segment when linking, so
not need to set it to 0 here obviously.

This patch fixes this ERROR to reduce noise when checking new patches
in kvm_main.c.

	Signed-off-by: Xiubo Li <lixiubo@cmss.chinamobile.com>
	Signed-off-by: Marcelo Tosatti <mtosatti@redhat.com>
(cherry picked from commit f4fee93270abbf862aab268111ac1e12934130c4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>