libbpf: Initialize err in probe_map_create
Bugzilla: https://bugzilla.redhat.com/2069046

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 3045f42a64324d339125a8a1a1763bb9e1e08300
Author: Florian Fainelli <f.fainelli@gmail.com>
Date:   Sun Jul 31 19:51:09 2022 -0700

    libbpf: Initialize err in probe_map_create

    GCC-11 warns about the possibly unitialized err variable in
    probe_map_create:

    libbpf_probes.c: In function 'probe_map_create':
    libbpf_probes.c:361:38: error: 'err' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      361 |                 return fd < 0 && err == exp_err ? 1 : 0;
          |                                  ~~~~^~~~~~~~~~

    Fixes: 878d8def0603 ("libbpf: Rework feature-probing APIs")
    Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20220801025109.1206633-1-f.fainelli@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>