wifi: mwifiex: Fix uninitialized variable in mwifiex_cfg80211_authenticate()
JIRA: https://issues.redhat.com/browse/RHEL-67113

commit c9f4c1ec69728310a31080c266b8529381c1a7fa
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Thu Aug 15 14:29:27 2024 +0300

    wifi: mwifiex: Fix uninitialized variable in mwifiex_cfg80211_authenticate()
    
    Smatch complains that:
    
        drivers/net/wireless/marvell/mwifiex/cfg80211.c:4408 mwifiex_cfg80211_authenticate()
        error: uninitialized symbol 'varptr'.
    
    It's a check for NULL, but "varptr" is either non-NULL or uninitialized.
    Initialize it to NULL.
    
    Fixes: 36995892c271 ("wifi: mwifiex: add host mlme for client mode")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Acked-by: Brian Norris <briannorris@chromium.org>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://patch.msgid.link/d7d043b2-95d5-4e1d-b340-5d7330053ac6@stanley.mountain

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>