ALSA: hda/realtek: fix code style (ERROR: else should follow close brace '}')
JIRA: https://issues.redhat.com/browse/RHEL-183296

commit d1888bf848ade6a9e71c7ba516fd215aa1bd8d65
Author: Lei Huang <huanglei@kylinos.cn>
Date: Tue Mar 31 15:54:05 2026 +0800

    ALSA: hda/realtek: fix code style (ERROR: else should follow close brace '}')

    Fix checkpatch code style errors:

      ERROR: else should follow close brace '}'
      #2300: FILE: sound/hda/codecs/realtek/alc269.c:2300:
      +       }
      +       else

    Fixes: 31278997add6 ("ALSA: hda/realtek - Add headset quirk for Dell DT")
    Signed-off-by: Lei Huang <huanglei@kylinos.cn>
    Link: https://patch.msgid.link/20260331075405.78148-1-huanglei814@163.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>