netdevsim: Fix hwstats debugfs file permissions
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2140149

commit 34513ada53eb3e3f711250d8dbc2de4de493d510
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Fri Sep 9 18:38:30 2022 +0300

    netdevsim: Fix hwstats debugfs file permissions

    The hwstats debugfs files are only writeable, but they are created with
    read and write permissions, causing certain selftests to fail [1].

    Fix by creating the files with write permission only.

    [1]
     # ./test_offload.py
     Test destruction of generic XDP...
     Traceback (most recent call last):
       File "/home/idosch/code/linux/tools/testing/selftests/bpf/./test_offload.py", line 810, in <module>
         simdev = NetdevSimDev()
     [...]
     Exception: Command failed: cat /sys/kernel/debug/netdevsim/netdevsim0//ports/0/dev/hwstats/l3/disable_ifindex

     cat: /sys/kernel/debug/netdevsim/netdevsim0//ports/0/dev/hwstats/l3/disable_ifindex: Invalid argument

    Fixes: 1a6d7ae7d63c ("netdevsim: Introduce support for L3 offload xstats")
    Reported-by: Jie2x Zhou <jie2x.zhou@intel.com>
    Tested-by: Jie2x Zhou <jie2x.zhou@intel.com>
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Link: https://lore.kernel.org/r/20220909153830.3732504-1-idosch@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>