net: make snmp_mib_free static inline
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [net] ipv4: make snmp_mib_free static inline (Amerigo Wang) [970585]
Rebuild_FUZZ: 90.67%
commit-author Cong Wang <amwang@redhat.com>
commit 5a17a390de7bdbcfff9b8f344273a886ca4cf8bf

Fengguang reported:

   net/built-in.o: In function `in6_dev_finish_destroy':
   (.text+0x4ca7d): undefined reference to `snmp_mib_free'

this is due to snmp_mib_free() is defined when CONFIG_INET is enabled,
but in6_dev_finish_destroy() is now moved to core kernel.

I think snmp_mib_free() is small enough to be inlined, so just make it
static inline.

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Cong Wang <amwang@redhat.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5a17a390de7bdbcfff9b8f344273a886ca4cf8bf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>