x86/alternatives: Do not use integer constant suffixes in inline asm
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit c22ef5684b64a3a1ac08db06a6f327f2695fd377
Author: Willy Tarreau <w@1wt.eu>
Date:   Tue Apr 18 08:42:28 2023 +0200

    x86/alternatives: Do not use integer constant suffixes in inline asm

    The usage of the BIT() macro in inline asm code was introduced in 6.3 by
    the commit in the Fixes tag. However, this macro uses "1UL" for integer
    constant suffixes in its shift operation, while gas before 2.28 does not
    support the "L" suffix after a number, and gas before 2.27 does not
    support the "U" suffix, resulting in build errors such as the following
    with such versions:

      ./arch/x86/include/asm/uaccess_64.h:124: Error: found 'L', expected: ')'
      ./arch/x86/include/asm/uaccess_64.h:124: Error: junk at end of line,
      first unrecognized character is `L'

    However, the currently minimal binutils version the kernel supports is
    2.25.

    There's a single use of this macro here, revert to (1 << 0) that works
    with such older binutils.

    As an additional info, the binutils PRs which add support for those
    suffixes are:

      https://sourceware.org/bugzilla/show_bug.cgi?id=19910
      https://sourceware.org/bugzilla/show_bug.cgi?id=20732

      [ bp: Massage and extend commit message. ]

    Fixes: 5d1dd961e743 ("x86/alternatives: Add alt_instr.flags")
    Signed-off-by: Willy Tarreau <w@1wt.eu>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Tested-by: Jingbo Xu <jefflexu@linux.alibaba.com>
    Link: https://lore.kernel.org/lkml/a9aae568-3046-306c-bd71-92c1fc8eeddc@linux.alibaba.com/

Signed-off-by: Prarit Bhargava <prarit@redhat.com>