mm: hugetlb_vmemmap: include missing linux/moduleparam.h
Bugzilla: https://bugzilla.redhat.com/2160210

commit db5e8d84319bcdb51e1d3cfa42b410291d6d1cfa
Author: Vasily Gorbik <gor@linux.ibm.com>
Date:   Wed Nov 2 19:09:17 2022 +0100

    mm: hugetlb_vmemmap: include missing linux/moduleparam.h

    The kernel test robot reported build failures with a 'randconfig' on s390:
    >> mm/hugetlb_vmemmap.c:421:11: error: a function declaration without a
    prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
       core_param(hugetlb_free_vmemmap, vmemmap_optimize_enabled, bool, 0);
                 ^

    Link: https://lore.kernel.org/linux-mm/202210300751.rG3UDsuc-lkp@intel.com/
    Link: https://lkml.kernel.org/r/patch.git-296b83ca939b.your-ad-here.call-01667411912-ext-5073@work.hours
    Fixes: 30152245c63b ("mm: hugetlb_vmemmap: replace early_param() with core_param()")
    Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Reviewed-by: Muchun Song <songmuchun@bytedance.com>
    Cc: Gerald Schaefer <gerald.schaefer@linux.ibm.com>
    Cc: Mike Kravetz <mike.kravetz@oracle.com>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>