ASoC: q6dsp: fix event handler prototype
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 5b5089e2a1e753ffe9ee2bf101a9e06784ec5e1a
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Feb 13 11:10:46 2024 +0100

    ASoC: q6dsp: fix event handler prototype

    clang-16 points out a mismatch in function types that was hidden
    by a typecast:

    sound/soc/qcom/qdsp6/q6apm-dai.c:355:38: error: cast from 'void (*)(uint32_t, uint32_t, uint32_t *, void *)' (aka 'void (*)(unsigned int, unsigned int, unsigned int *, void *)') to 'q6apm_cb' (aka 'void (*)(unsigned int, unsigned int, void *, void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
      355 |         prtd->graph = q6apm_graph_open(dev, (q6apm_cb)event_handler, prtd, graph_id);
    sound/soc/qcom/qdsp6/q6apm-dai.c:499:38: error: cast from 'void (*)(uint32_t, uint32_t, uint32_t *, void *)' (aka 'void (*)(unsigned int, unsigned int, unsigned int *, void *)') to 'q6apm_cb' (aka 'void (*)(unsigned int, unsigned int, void *, void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
      499 |         prtd->graph = q6apm_graph_open(dev, (q6apm_cb)event_handler_compr, prtd, graph_id);

    The only difference here is the 'payload' argument, which is not even
    used in this function, so just fix its type and remove the cast.

    Fixes: 88b60bf047fd ("ASoC: q6dsp: q6apm-dai: Add open/free compress DAI callbacks")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://msgid.link/r/20240213101105.459402-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>