selftests/bpf: Set CONFIG_PACKET=y for selftests
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit 0f626c98fd10330da0420029a1c4fa35e39fb873
Author: Saket Kumar Bhaskar <skb99@linux.ibm.com>
Date:   Mon Jul 7 12:47:35 2025 +0530

    selftests/bpf: Set CONFIG_PACKET=y for selftests
    
    BPF selftest fails to build with below error:
    
      CLNG-BPF [test_progs] lsm_cgroup.bpf.o
    progs/lsm_cgroup.c:105:21: error: variable has incomplete type 'struct sockaddr_ll'
      105 |         struct sockaddr_ll sa = {};
          |                            ^
    progs/lsm_cgroup.c:105:9: note: forward declaration of 'struct sockaddr_ll'
      105 |         struct sockaddr_ll sa = {};
          |                ^
    1 error generated.
    
    lsm_cgroup selftest requires sockaddr_ll structure which is not there
    in vmlinux.h when the kernel is built with CONFIG_PACKET=m.
    
    Enabling CONFIG_PACKET=y ensures that sockaddr_ll is available in vmlinux,
    allowing it to be captured in the generated vmlinux.h for bpf selftests.
    
    Reported-by: Sachin P Bappalige <sachinpb@linux.ibm.com>
    Signed-off-by: Saket Kumar Bhaskar <skb99@linux.ibm.com>
    Acked-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/r/20250707071735.705137-1-skb99@linux.ibm.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>