ASoC: fix build warning in soc-core.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: fix build warning in soc-core.c (Jaroslav Kysela) [1535427]
Rebuild_FUZZ: 92.50%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit bb19ba2a345439b4de3f6d59819da9853500ac4d

Fix kernel-doc build error. A symbol that ends with an underscore
character ('_') has special meaning in reST (reStructuredText), so add
a '*' to prevent this error and to indicate that there are several of
these values to choose from.

../sound/soc/soc-core.c:2799: ERROR: Unknown target name: "snd_soc_daifmt".

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit bb19ba2a345439b4de3f6d59819da9853500ac4d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>