net: phy: Kconfig: micrel_phy: fix dependency issue
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2066451
Upstream Status: net.git commit 231fdac3e58f

commit 231fdac3e58f4e52e387930c73bf535439607563
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Mon Mar 14 12:02:54 2022 +0100

    net: phy: Kconfig: micrel_phy: fix dependency issue

    When building driver CONFIG_MICREL_PHY the follow error shows up:

    aarch64-linux-gnu-ld: drivers/net/phy/micrel.o: in function `lan8814_ts_info':
    micrel.c:(.text+0x1764): undefined reference to `ptp_clock_index'
    micrel.c:(.text+0x1764): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `ptp_clock_index'
    aarch64-linux-gnu-ld: drivers/net/phy/micrel.o: in function `lan8814_probe':
    micrel.c:(.text+0x4720): undefined reference to `ptp_clock_register'
    micrel.c:(.text+0x4720): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `ptp_clock_register'

    Rework Kconfig for MICREL_PHY to depend on 'PTP_1588_CLOCK_OPTIONAL'.
    Arnd describes in a good way why its needed to add this depends in patch
    e5f31552674e ("ethernet: fix PTP_1588_CLOCK dependencies").

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: ece19502834d ("net: phy: micrel: 1588 support for LAN8814 phy")
    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
    Reviewed-by: Andrew Lunn <andrew@lunn.ch>
    Link: https://lore.kernel.org/r/20220314110254.12498-1-anders.roxell@linaro.org
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Hangbin Liu <haliu@redhat.com>