nfs: fix anonymous member initializer build failure with older compilers
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Linus Torvalds <torvalds@linux-foundation.org>
commit e0714ec4f9efe7b86828b0dcc077fd8f5d8e5e91

Older versions of gcc don't understand named initializers inside a
anonymous structure or union member.  It can be worked around by adding
the bracin gin the initializer for the anonymous member.

Without this, gcc 4.4.4 will fail the build with

    CC      fs/nfs/nfs4state.o
  fs/nfs/nfs4state.c:69: error: unknown field ‘data’ specified in initializer
  fs/nfs/nfs4state.c:69: warning: missing braces around initializer
  fs/nfs/nfs4state.c:69: warning: (near initialization for ‘zero_stateid.<anonymous>.data’)
  make[2]: *** [fs/nfs/nfs4state.o] Error 1

introduced in commit 93b717fd81bf ("NFSv4: Label stateids with the type")

Reported-and-tested-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
	Cc: Anna Schumaker <Anna.Schumaker@netapp.com>
	Cc: Trond Myklebust <trond.myklebust@primarydata.com>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit e0714ec4f9efe7b86828b0dcc077fd8f5d8e5e91)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>