arm64: hide unused is_valid_bugaddr()
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit b925b4314c9155b32d17e9dfda37d64c229063b7
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:36 +0200

    When generic BUG() support is disabled, this function has no declaration
    and no callers but causes a W=1 warning:

    arch/arm64/kernel/traps.c:950:5: error: no previous prototype for 'is_valid_bugaddr' [-Werror=missing-prototypes]

    Add an #ifdef that matches the one around the declaration.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-10-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>