cn10k-ipsec: Fix compilation error when CONFIG_XFRM_OFFLOAD disabled
JIRA: https://issues.redhat.com/browse/RHEL-23617

commit b82ca90d5512b07be2b9ee28d0e9a775bc23e3e9
Author: Bharat Bhushan <bbhushan2@marvell.com>
Date:   Wed Dec 11 11:54:19 2024 +0530

    cn10k-ipsec: Fix compilation error when CONFIG_XFRM_OFFLOAD disabled

    Define static branch variable "cn10k_ipsec_sa_enabled"
    in "otx2_txrx.c". This fixes below compilation error
    when CONFIG_XFRM_OFFLOAD is disabled.

     drivers/net/ethernet/marvell/octeontx2/nic/otx2_txrx.o:(__jump_table+0x8): undefined reference to `cn10k_ipsec_sa_enabled'
     drivers/net/ethernet/marvell/octeontx2/nic/otx2_txrx.o:(__jump_table+0x18): undefined reference to `cn10k_ipsec_sa_enabled'
     drivers/net/ethernet/marvell/octeontx2/nic/otx2_txrx.o:(__jump_table+0x28): undefined reference to `cn10k_ipsec_sa_enabled'

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202412110505.ZKDzGRMv-lkp@intel.com/
    Fixes: 6a77a158848a ("cn10k-ipsec: Process outbound ipsec crypto offload")
    Signed-off-by: Bharat Bhushan <bbhushan2@marvell.com>
    Link: https://patch.msgid.link/20241211062419.2587111-1-bbhushan2@marvell.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Sai Krishna <sgajula@redhat.com>