powerpc/fsl_booke: Fix setting of exec flag when setting TLBCAMs
Bugzilla: https://bugzilla.redhat.com/2120352

commit 44c14509b0dabb909ad1ec28800893ea71762732
Author: Christophe Leroy <christophe.leroy@csgroup.eu>
Date:   Tue Oct 26 07:39:26 2021 +0200

    powerpc/fsl_booke: Fix setting of exec flag when setting TLBCAMs

    Building tqm8541_defconfig results in:

            arch/powerpc/mm/nohash/fsl_book3e.c: In function 'settlbcam':
            arch/powerpc/mm/nohash/fsl_book3e.c:126:40: error: '_PAGE_BAP_SX' undeclared (first use in this function)
              126 |         TLBCAM[index].MAS3 |= (flags & _PAGE_BAP_SX) ? MAS3_SX : 0;
                  |                                        ^~~~~~~~~~~~
            arch/powerpc/mm/nohash/fsl_book3e.c:126:40: note: each undeclared identifier is reported only once for each function it appears in
            make[3]: *** [scripts/Makefile.build:277: arch/powerpc/mm/nohash/fsl_book3e.o] Error 1
            make[2]: *** [scripts/Makefile.build:540: arch/powerpc/mm/nohash] Error 2
            make[1]: *** [scripts/Makefile.build:540: arch/powerpc/mm] Error 2
            make: *** [Makefile:1868: arch/powerpc] Error 2

    This is because _PAGE_BAP_SX is not defined when using 32 bits PTE.

    Now that _PAGE_EXEC contains both _PAGE_BAP_SX and _PAGE_BAP_UX, it can be used instead.

    Fixes: 01116e6e98b0 ("powerpc/fsl_booke: Take exec flag into account when setting TLBCAMs")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/91a0235e7f2a85308b84aa5b9efd8d022e2b899a.1635226743.git.christophe.leroy@csgroup.eu

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>