selftests/bpf: Fix uprobe_multi compilation error
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit c27d8235ba97139d7a085367ff57773902eb3fc5
Author: Alan Maguire <alan.maguire@oracle.com>
Date:   Thu Sep 26 15:49:48 2024 +0100

    selftests/bpf: Fix uprobe_multi compilation error

    When building selftests, the following was seen:

    uprobe_multi.c: In function ‘trigger_uprobe’:
    uprobe_multi.c:108:40: error: ‘MADV_PAGEOUT’ undeclared (first use in this function)
      108 |                 madvise(addr, page_sz, MADV_PAGEOUT);
          |                                        ^~~~~~~~~~~~
    uprobe_multi.c:108:40: note: each undeclared identifier is reported only once for each function it appears in
    make: *** [Makefile:850: bpf-next/tools/testing/selftests/bpf/uprobe_multi] Error 1

    ...even with updated UAPI headers. It seems the above value is
    defined in UAPI <linux/mman.h> but including that file triggers
    other redefinition errors.  Simplest solution is to add a
    guarded definition, as was done for MADV_POPULATE_READ.

    Fixes: 3c217a182018 ("selftests/bpf: add build ID tests")
    Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Link: https://lore.kernel.org/bpf/20240926144948.172090-1-alan.maguire@oracle.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>