cxl: Fix -Werror=return-type in cxl_decoder_detach()
JIRA: https://issues.redhat.com/browse/RHEL-119007

commit 3796f2985c267b90052613cf0b379e51c61e9367
Author: Li Zhijian <lizhijian@fujitsu.com>
Date:   Thu Jul 17 11:12:51 2025 +0800

    cxl: Fix -Werror=return-type in cxl_decoder_detach()

    Fix following compiling errors:
    In file included from ../drivers/cxl/core/pmu.c:10:
    ../drivers/cxl/core/core.h: In function ‘cxl_decoder_detach’:
    ../drivers/cxl/core/core.h:65:1: error: no return statement in function returning non-void [-Werror=return-type]
     }
     ^
    cc1: some warnings being treated as errors
      CC [M]  drivers/nvdimm/claim.o
    make[6]: *** [../scripts/Makefile.build:287: drivers/cxl/core/pmu.o] Error 1
    make[6]: *** Waiting for unfinished jobs....
      CC [M]  drivers/infiniband/core/verbs.o

    Fixes: b3a88225519c ("cxl/region: Consolidate cxl_decoder_kill_region() and cxl_region_detach()")
    Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>
    Link: https://patch.msgid.link/20250717031251.1043825-1-lizhijian@fujitsu.com
    Signed-off-by: Dave Jiang <dave.jiang@intel.com>

Signed-off-by: John W. Linville <linville@redhat.com>