net/mlx5: Kconfig: Fix MLX5_CORE dependency with PCI_HYPERV_INTERFACE
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Mao Wenan <maowenan@huawei.com>
commit 4057a7652b74af25ba1197689fc144cdb766f423

When MLX5_CORE=y and PCI_HYPERV_INTERFACE=m, below errors are found:
drivers/net/ethernet/mellanox/mlx5/core/en_main.o: In function `mlx5e_nic_enable':
en_main.c:(.text+0xb649): undefined reference to `mlx5e_hv_vhca_stats_create'
drivers/net/ethernet/mellanox/mlx5/core/en_main.o: In function `mlx5e_nic_disable':
en_main.c:(.text+0xb8c4): undefined reference to `mlx5e_hv_vhca_stats_destroy'

Fix this by making MLX5_CORE imply PCI_HYPERV_INTERFACE.

Fixes: cef35af34d6d ("net/mlx5e: Add mlx5e HV VHCA stats agent")
	Signed-off-by: Mao Wenan <maowenan@huawei.com>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit 4057a7652b74af25ba1197689fc144cdb766f423)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>