net: enic: include irq.h for irqreturn_t definitions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [ethernet] enic: include irq.h for irqreturn_t definitions (Stefan Assmann) [1107934]
Rebuild_FUZZ: 94.95%
commit-author Josh Boyer <jwboyer@gmail.com>
commit fef1f07cbf3d9b6f79beac8575554476c02c7f54

The enic driver fails to build on ARM with:

In file included from drivers/net/ethernet/cisco/enic/enic_res.c:40:0:
drivers/net/ethernet/cisco/enic/enic.h:48:2: error: expected specifier-qualifier-list before 'irqreturn_t'
  irqreturn_t (*isr)(int, void *);
  ^

Nothing in the driver is explicitly including the irq definitions, so we add
an include of linux/irq.h to pick them up.

	Signed-off-by: Josh Boyer <jwboyer@fedoraproject.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit fef1f07cbf3d9b6f79beac8575554476c02c7f54)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>