netfilter: nft_set_hash: fix get operation on big endian
jira KERNEL-1478
Rebuild_History Non-Buildable kernel-6.12.0-211.47.1.el10_2
commit-author Florian Westphal <fw@strlen.de>
commit 2f635adbe2642d398a0be3ab245accd2987be0c3

tests/shell/testcases/packetpath/set_match_nomatch_hash_fast
fails on big endian with:

Error: Could not process rule: No such file or directory
reset element ip test s { 244.147.90.126 }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fatal: Cannot fetch element "244.147.90.126"

... because the wrong bucket is searched, jhash() and jhash1_word are
not interchangeable on big endian.

Fixes: 3b02b0adc242 ("netfilter: nft_set_hash: fix lookups with fixed size hash on big endian")
	Signed-off-by: Florian Westphal <fw@strlen.de>
(cherry picked from commit 2f635adbe2642d398a0be3ab245accd2987be0c3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>