selftests/bpf: Fix missing UINT_MAX definitions in benchmarks
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit a2c155131b710959beb508ca6a54769b6b1bd488
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:35 2024 -0700

    selftests/bpf: Fix missing UINT_MAX definitions in benchmarks

    Include <limits.h> in 'bench.h' to provide a UINT_MAX definition and avoid
    multiple compile errors against mips64el/musl-libc like:

      benchs/bench_local_storage.c: In function 'parse_arg':
      benchs/bench_local_storage.c:40:38: error: 'UINT_MAX' undeclared (first use in this function)
         40 |                 if (ret < 1 || ret > UINT_MAX) {
            |                                      ^~~~~~~~
      benchs/bench_local_storage.c:11:1: note: 'UINT_MAX' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?
         10 | #include <test_btf.h>
        +++ |+#include <limits.h>
         11 |

    seen with bench_local_storage.c, bench_local_storage_rcu_tasks_trace.c, and
    bench_bpf_hashmap_lookup.c.

    Fixes: 73087489250d ("selftests/bpf: Add benchmark for local_storage get")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/8f64a9d9fcff40a7fca090a65a68a9b62a468e16.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>