ASoC: ak4458: Add ak4458_reset in device probe and remove
Bugzilla: https://bugzilla.redhat.com/2179848

commit da995e22fa7193b067f2545e63d726ffe36ba174
Author: Shengjiu Wang <shengjiu.wang@nxp.com>
Date: Tue Sep 13 16:26:34 2022 +0800

    ASoC: ak4458: Add ak4458_reset in device probe and remove

    This patch fixup this warning when CONFIG_PM not defined

    linux/sound/soc/codecs/ak4458.c:631:13: error: 'ak4458_reset' defined but\
            not used [-Werror=unused-function]
      631 | static void ak4458_reset(struct ak4458_priv *ak4458, bool active)
          |             ^~~~~~~~~~~~
    cc1: all warnings being treated as errors

    Fixes: e9e7df88996d64 ("ASoC: ak4458: Remove component probe() and remove()")
    Reported-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
    Signed-off-by: Shengjiu Wang <shengjiu.wang@nxp.com>
    Link: https://lore.kernel.org/r/1663057594-29141-1-git-send-email-shengjiu.wang@nxp.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>