scsi: ibmvscsis: Fix a stringop-overflow warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Laura Abbott <labbott@redhat.com>
commit d792d4c4fc866ae224b0b0ca2aabd87d23b4d6cc

There's currently a warning about string overflow with strncat:

drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c: In function 'ibmvscsis_probe':
drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c:3479:2: error: 'strncat' specified
bound 64 equals destination size [-Werror=stringop-overflow=]
  strncat(vscsi->eye, vdev->name, MAX_EYE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Switch to a single snprintf instead of a strcpy + strcat to handle this
cleanly.

	Signed-off-by: Laura Abbott <labbott@redhat.com>
	Suggested-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit d792d4c4fc866ae224b0b0ca2aabd87d23b4d6cc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>