memstick: core: Zero initialize id_reg in h_memstick_read_dev_id()
JIRA: https://issues.redhat.com/browse/RHEL-116016

commit 21b34a3a204ed616373a12ec17dc127ebe51eab3
Author: Nathan Chancellor <nathan@kernel.org>
Date: Tue, 15 Jul 2025 15:56:05 -0700

  A new warning in clang [1] points out that id_reg is uninitialized then
  passed to memstick_init_req() as a const pointer:

    drivers/memstick/core/memstick.c:330:59: error: variable 'id_reg' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
      330 |                 memstick_init_req(&card->current_mrq, MS_TPC_READ_REG, &id_reg,
          |                                                                         ^~~~~~

  Commit de182cc8e882 ("drivers/memstick/core/memstick.c: avoid -Wnonnull
  warning") intentionally passed this variable uninitialized to avoid an
  -Wnonnull warning from a NULL value that was previously there because
  id_reg is never read from the call to memstick_init_req() in
  h_memstick_read_dev_id(). Just zero initialize id_reg to avoid the
  warning, which is likely happening in the majority of builds using
  modern compilers that support '-ftrivial-auto-var-init=zero'.

  Cc: stable@vger.kernel.org
  Fixes: de182cc8e882 ("drivers/memstick/core/memstick.c: avoid -Wnonnull warning")
  Link: https://github.com/llvm/llvm-project/commit/00dacf8c22f065cb52efb14cd091d441f19b319e [1]
  Closes: https://github.com/ClangBuiltLinux/linux/issues/2105
  Signed-off-by: Nathan Chancellor <nathan@kernel.org>
  Link: https://lore.kernel.org/r/20250715-memstick-fix-uninit-const-pointer-v1-1-f6753829c27a@kernel.org
  Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>