cxl: Include range.h in cxl.h
JIRA: https://issues.redhat.com/browse/RHEL-119007

commit 9f97e61bde6a91a429f48da1a461488a15b01813
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Jul 1 07:33:31 2025 -0700

    cxl: Include range.h in cxl.h

    After commit aefeb286b960 ("libnvdimm: Don't use "proxy" headers"),
    range.h may not be implicitly included, resulting in a build error:

      In file included from drivers/cxl/core/features.c:8:
      drivers/cxl/cxl.h:365:22: error: field 'hpa_range' has incomplete type
        365 |         struct range hpa_range;
            |                      ^~~~~~~~~
      drivers/cxl/cxl.h:562:22: error: field 'hpa_range' has incomplete type
        562 |         struct range hpa_range;
            |                      ^~~~~~~~~
      drivers/cxl/cxl.h:570:22: error: field 'hpa_range' has incomplete type
        570 |         struct range hpa_range;
            |                      ^~~~~~~~~
      drivers/cxl/cxl.h:803:22: error: array type has incomplete element type 'struct range'
        803 |         struct range dvsec_range[2];
            |                      ^~~~~~~~~~~

    Include range.h in cxl.h explicitly to clear up the errors.

    Fixes: aefeb286b960 ("libnvdimm: Don't use "proxy" headers")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Dave Jiang <dave.jiang@intel.com>
    Reviewed-by: Jonathan Cameron <jonathan.cameron@huawei.com>
    Link: https://patch.msgid.link/20250701-cxl-fix-struct-range-error-v1-1-1f199bddc7c9@kernel.org
    Signed-off-by: Ira Weiny <ira.weiny@intel.com>

Signed-off-by: John W. Linville <linville@redhat.com>