ASoC: Intel: mrfld: fix uninitialized variable access
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: Intel: mrfld: fix uninitialized variable access (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.64%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 1539c7f23f256120f89f8b9ec53160790bce9ed2

Randconfig testing revealed a very old bug, with gcc-8:

sound/soc/intel/atom/sst/sst_loader.c: In function 'sst_load_fw':
sound/soc/intel/atom/sst/sst_loader.c:357:5: error: 'fw' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (fw == NULL) {
     ^
sound/soc/intel/atom/sst/sst_loader.c:354:25: note: 'fw' was declared here
  const struct firmware *fw;

We must check the return code of request_firmware() before we look at the
pointer result that may be uninitialized when the function fails.

Fixes: 9012c9544eea ("ASoC: Intel: mrfld - Add DSP load and management")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 1539c7f23f256120f89f8b9ec53160790bce9ed2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>