PCI/PM: Define pci_restore_standard_config() only for CONFIG_PM_SLEEP
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2118429
Upstream Status: 18a94192e20de31e7e495d7c805c8930c42e99ef

commit 18a94192e20de31e7e495d7c805c8930c42e99ef
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Wed Apr 20 16:11:35 2022 +0200

    PCI/PM: Define pci_restore_standard_config() only for CONFIG_PM_SLEEP

    pci_restore_standard_config() was defined under CONFIG_PM but called only
    by pci_pm_resume() (defined under CONFIG_SUSPEND) and pci_pm_restore()
    (defined under CONFIG_HIBERNATE_CALLBACKS).  A configuration with only
    CONFIG_PM leads to a warning:

      drivers/pci/pci-driver.c:533:12: error: ‘pci_restore_standard_config’ defined but not used [-Werror=unused-function]

    CONFIG_PM_SLEEP depends on CONFIG_SUSPEND and CONFIG_HIBERNATE_CALLBACKS,
    so define pci_restore_standard_config() under that instead.

    Link: https://lore.kernel.org/r/20220420141135.444820-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>