ALSA: caiaq: Fix unused variable warning
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit af1d53b6e0ebef5ea57887e23619b2bb33a6f4de
Author: Takashi Iwai <tiwai@suse.de>
Date: Fri Aug 9 09:42:51 2024 +0200

    ALSA: caiaq: Fix unused variable warning

    The recent cleanup of caiaq driver forgot to remove the unused loop
    variable:
    sound/usb/caiaq/audio.c: In function 'snd_usb_caiaq_pcm_prepare':
    sound/usb/caiaq/audio.c:179:41: error: unused variable 'i' [-Werror=unused-variable]

    Fixes: e95b9f7f2ee0 ("ALSA: snd-usb-caiaq: use snd_pcm_rate_to_rate_bit")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Closes: https://lore.kernel.org/20240809112252.5af8025f@canb.auug.org.au
    Link: https://patch.msgid.link/20240809074254.5290-1-tiwai@suse.de
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>