selftests: netfilter: fix nft_meta.sh error reporting
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Fabian Frederick <fabf@skynet.be>
commit 5b1a995bfa93667762badbe1d8f0f7ad680bdf29
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-326.el8/5b1a995b.failed

When some test directly done with check_one_counter() fails,
counter variable is undefined. This patch calls ip with cname
which avoids errors like:
FAIL: oskuidcounter, want "packets 2", got
Error: syntax error, unexpected newline, expecting string
list counter inet filter
                        ^
Error is now correctly rendered:
FAIL: oskuidcounter, want "packets 2", got
table inet filter {
	counter oskuidcounter {
		packets 1 bytes 84
	}
}

	Signed-off-by: Fabian Frederick <fabf@skynet.be>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit 5b1a995bfa93667762badbe1d8f0f7ad680bdf29)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/testing/selftests/netfilter/nft_meta.sh