net: cdc_ncm: Fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 5fd99b5d9950d6300467ded18ff4e44af0b4ae55

If USB_NET_CDC_NCM is y and USB_NET_CDCETHER is m, build fails:

drivers/net/usb/cdc_ncm.o:(.rodata+0x1d8): undefined reference to `usbnet_cdc_update_filter'

Select USB_NET_CDCETHER for USB_NET_CDC_NCM to fix this.

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: e10dcb1b6ba7 ("net: cdc_ncm: hook into set_rx_mode to admit multicast traffic")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 5fd99b5d9950d6300467ded18ff4e44af0b4ae55)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>