drm/panic: remove spurious empty line to clean warning
JIRA: https://issues.redhat.com/browse/RHEL-53571
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.12.6)

commit 8f2cf4d32b1578d0193605c9c4a644f79b8fc497
Author:     Miguel Ojeda <ojeda@kernel.org>
AuthorDate: Tue Nov 26 00:33:32 2024 +0100
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Thu Dec 19 18:13:02 2024 +0100

    commit 4011b351b1b5a953aaa7c6b3915f908b3cc1be96 upstream.

    Clippy in the upcoming Rust 1.83.0 spots a spurious empty line since the
    `clippy::empty_line_after_doc_comments` warning is now enabled by default
    given it is part of the `suspicious` group [1]:

        error: empty line after doc comment
           --> drivers/gpu/drm/drm_panic_qr.rs:931:1
            |
        931 | / /// They must remain valid for the duration of the function call.
        932 | |
            | |_
        933 |   #[no_mangle]
        934 | / pub unsafe extern "C" fn drm_panic_qr_generate(
        935 | |     url: *const i8,
        936 | |     data: *mut u8,
        937 | |     data_len: usize,
        ...   |
        940 | |     tmp_size: usize,
        941 | | ) -> u8 {
            | |_______- the comment documents this function
            |
            = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_doc_comments
            = note: `-D clippy::empty-line-after-doc-comments` implied by `-D warnings`
            = help: to override `-D warnings` add `#[allow(clippy::empty_line_after_doc_comments)]`
            = help: if the empty line is unintentional remove it

    Thus remove the empty line.

    Cc: stable@vger.kernel.org
    Fixes: cb5164ac43d0 ("drm/panic: Add a QR code panic screen")
    Link: https://github.com/rust-lang/rust-clippy/pull/13091 [1]
    Reviewed-by: Jocelyn Falempe <jfalempe@redhat.com>
    Link: https://lore.kernel.org/r/20241125233332.697497-1-ojeda@kernel.org
    Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>