mlxsw: spectrum_flower: Do not allow mixing sample and mirror actions
JIRA: https://issues.redhat.com/browse/RHEL-94569

commit 175dd9079ecbd86d0e10927c442d64519baf5809
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Tue Dec 10 10:45:37 2024 +0100

    mlxsw: spectrum_flower: Do not allow mixing sample and mirror actions

    The device does not support multiple mirror actions per rule and the
    driver rejects such configuration:

     # tc filter add dev swp1 ingress pref 1 proto ip flower skip_sw action mirred egress mirror dev swp2 action mirred egress mirror dev swp3
     Error: mlxsw_spectrum: Multiple mirror actions per rule are not supported.
     We have an error talking to the kernel

    Internally, the sample action is implemented by the device by mirroring
    to the CPU port. Therefore, mixing sample and mirror actions in a single
    rule does not work correctly and results in the last action effect.

    Solve by rejecting such misconfiguration:

     # tc filter add dev swp1 ingress pref 1 proto ip flower skip_sw action mirred egress mirror dev swp2 action sample rate 100 group 1
     Error: mlxsw_spectrum: Sample action after mirror action is not supported.
     We have an error talking to the kernel

     # tc filter add dev swp1 ingress pref 1 proto ip flower skip_sw action sample rate 100 group 1 action mirred egress mirror dev swp2
     Error: mlxsw_spectrum: Mirror action after sample action is not supported.
     We have an error talking to the kernel

    Reported-by: Vladyslav Mykhaliuk <vmykhaliuk@nvidia.com>
    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Amit Cohen <amcohen@nvidia.com>
    Reviewed-by: Jiri Pirko <jiri@nvidia.com>
    Signed-off-by: Petr Machata <petrm@nvidia.com>
    Reviewed-by: Michal Swiatkowski <michal.swiatkowski@linux.intel.com>
    Reviewed-by: Kalesh AP <kalesh-anakkur.purayil@broadcom.com>
    Link: https://patch.msgid.link/d6c979914e8706dbe1dedbaf29ffffb0b8d71166.1733822570.git.petrm@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>