s390/boot: get rid of arithmetics on function pointers
Bugzilla: https://bugzilla.redhat.com/2120352

commit 6ab023641a34b18751310bbbeedb0e60aca2e4b2
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Sun Jul 25 15:07:25 2021 +0200

    s390/boot: get rid of arithmetics on function pointers

    sparse warning:
      CHECK   arch/s390/boot/startup.c
    arch/s390/boot/startup.c:283:39: error: arithmetics on pointers to functions

    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>