wifi: mt76: mt7996: select CONFIG_RELAY
Bugzilla: https://bugzilla.redhat.com/2178526

commit 37fc9ad1617a303bbfd28870eb25aaa4766e79ab
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:31:10 2022 +0100

    wifi: mt76: mt7996: select CONFIG_RELAY
    
    Without CONFIG_RELAY, the driver fails to link:
    
    ERROR: modpost: "relay_flush" [drivers/net/wireless/mediatek/mt76/mt7996/mt7996e.ko] undefined!
    ERROR: modpost: "relay_switch_subbuf" [drivers/net/wireless/mediatek/mt76/mt7996/mt7996e.ko] undefined!
    ERROR: modpost: "relay_open" [drivers/net/wireless/mediatek/mt76/mt7996/mt7996e.ko] undefined!
    ERROR: modpost: "relay_reset" [drivers/net/wireless/mediatek/mt76/mt7996/mt7996e.ko] undefined!
    ERROR: modpost: "relay_file_operations" [drivers/net/wireless/mediatek/mt76/mt7996/mt7996e.ko] undefined!
    
    The same change was done in mt7915 for the corresponding copy of the code.
    
    Fixes: 98686cd21624 ("wifi: mt76: mt7996: add driver for MediaTek Wi-Fi 7 (802.11be) devices")
    See-also: 988845c9361a ("mt76: mt7915: add support for passing chip/firmware debug data to user space")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20221215163133.4152299-1-arnd@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>