media: media-entity.h: add include for min()
JIRA: https://issues.redhat.com/browse/RHEL-67885

commit c7097c80ca684f6476a55b2e202b975cf3e36b46
Author: Tomi Valkeinen <tomi.valkeinen@ideasonboard.com>
Date: Wed, 31 Aug 2022 16:13:25 +0200

  ./include/media/media-entity.h:595:34: error: implicit declaration of function ‘min’

  Include minmax.h to get the definition for min().

  Signed-off-by: Tomi Valkeinen <tomi.valkeinen@ideasonboard.com>
  Reviewed-by: Laurent Pinchart <laurent.pinchart+renesas@ideasonboard.com>
  Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>
  Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>

Signed-off-by: Kate Hsuan <hpa@redhat.com>