HID: lenovo: Fix undefined platform_profile_cycle in ThinkPad X12 keyboard patch
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.14
Tested: with the hid-tools test suite and some hardware

commit 52e7d1f7c2fdd1592ab2cc48edd7ca583cabe93e
Author: Vishnu Sankar <vishnuocv@gmail.com>
Date:   Fri Jan 10 23:14:09 2025 +0900

    HID: lenovo: Fix undefined platform_profile_cycle in ThinkPad X12 keyboard patch

    The commit "HID: lenovo: Support for ThinkPad-X12-TAB-1/2 Kbd Fn keys"
    introduced an issue where the CI failed with the following error:
    ERROR: modpost: "platform_profile_cycle" [drivers/hid/hid-lenovo.ko] undefined!

    This issue occurs because platform_profile_cycle is used without ensuring
    the kernel is configured with CONFIG_ACPI_PLATFORM_PROFILE.
    To address this, this patch adds conditional support for platform profile
    management to the Fn+F8 key handling.
    The functionality for platform_profile_cycle is now included only when
    CONFIG_ACPI_PLATFORM_PROFILE is enabled in the kernel configuration.

    This ensures compatibility with kernels that do not include the ACPI
    platform profile feature, resolving the CI build issue.

    Signed-off-by: Vishnu Sankar <vishnuocv@gmail.com>
    Signed-off-by: Vishnu Sankar <vsankar@lenovo.com>
    Suggested-by: Benjamin Tissoires <bentiss@kernel.org>
    Suggested-by: Jiri Kosina <jikos@kernel.org>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>