ndtest: Cleanup all of blk namespace specific code
Bugzilla: https://bugzilla.redhat.com/2162211

commit 69053101e096c01a4c8e3d2497e3cd5716e43cec
Author: Shivaprasad G Bhat <sbhat@linux.ibm.com>
Date:   Tue Jul 12 10:23:44 2022 -0500

    ndtest: Cleanup all of blk namespace specific code
    
    With the nd_namespace_blk and nd_blk_region infrastructures being removed,
    the ndtest still has some references to the old code. So the
    compilation fails as below,
    
    ../tools/testing/nvdimm/test/ndtest.c:204:25: error: ‘ND_DEVICE_NAMESPACE_BLK’ undeclared here (not in a function); did you mean ‘ND_DEVICE_NAMESPACE_IO’?
      204 |                 .type = ND_DEVICE_NAMESPACE_BLK,
          |                         ^~~~~~~~~~~~~~~~~~~~~~~
          |                         ND_DEVICE_NAMESPACE_IO
    ../tools/testing/nvdimm/test/ndtest.c: In function ‘ndtest_create_region’:
    ../tools/testing/nvdimm/test/ndtest.c:630:17: error: ‘ndbr_desc’ undeclared (first use in this function); did you mean ‘ndr_desc’?
      630 |                 ndbr_desc.enable = ndtest_blk_region_enable;
          |                 ^~~~~~~~~
          |                 ndr_desc
    ../tools/testing/nvdimm/test/ndtest.c:630:17: note: each undeclared identifier is reported only once for each function it appears in
    ../tools/testing/nvdimm/test/ndtest.c:630:36: error: ‘ndtest_blk_region_enable’ undeclared (first use in this function)
      630 |                 ndbr_desc.enable = ndtest_blk_region_enable;
          |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
    ../tools/testing/nvdimm/test/ndtest.c:631:35: error: ‘ndtest_blk_do_io’ undeclared (first use in this function); did you mean ‘ndtest_blk_mmio’?
      631 |                 ndbr_desc.do_io = ndtest_blk_do_io;
          |                                   ^~~~~~~~~~~~~~~~
          |                                   ndtest_blk_mmio
    
    The current patch removes the specific code to cleanup all obsolete
    references.
    
    Signed-off-by: Shivaprasad G Bhat <sbhat@linux.ibm.com>
    Link: https://lore.kernel.org/r/165763940218.3501174.7103619358744815702.stgit@ltc-boston123.aus.stglabs.ibm.com
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>