perf/x86/intel: Fix and clean up intel_pmu_drain_arch_pebs() type use
JIRA: https://redhat.atlassian.net/browse/RHEL-140195

upstream
========
commit 9929dffce5ed7e2988e0274f4db98035508b16d9
Author: Ingo Molnar <mingo@kernel.org>
Date: Wed Nov 12 10:40:26 2025 +0100

description
===========
The following commit introduced a build failure on x86-32:

  21954c8a0ff ("perf/x86/intel: Process arch-PEBS records or record fragments")

  ...

  arch/x86/events/intel/ds.c:2983:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]

The forced type conversion to 'u64' and 'void *' are not 32-bit clean,
but they are also entirely unnecessary: ->pebs_vaddr is 'void *' already,
and integer-compatible pointer arithmetics will work just fine on it.

Fix & simplify the code.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Fixes: d21954c8a0ff ("perf/x86/intel: Process arch-PEBS records or record fragments")
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Acked-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Dapeng Mi <dapeng1.mi@linux.intel.com>
    Cc: Kan Liang <kan.liang@linux.intel.com>
    Link: https://patch.msgid.link/20251029102136.61364-10-dapeng1.mi@linux.intel.com

Signed-off-by: Trevor Allison <tallison@redhat.com>