HID: lenovo: select CONFIG_ACPI_PLATFORM_PROFILE
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.14
Tested: with the hid-tools test suite and some hardware

commit 52572cde8b4a44676557ccb67b035291833112c5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 22 07:50:57 2025 +0100

    HID: lenovo: select CONFIG_ACPI_PLATFORM_PROFILE

    A previous patch tried to fix this link failure:

    x86_64-linux-ld: drivers/hid/hid-lenovo.o: in function `lenovo_raw_event':
    hid-lenovo.c:(.text+0x22c): undefined reference to `platform_profile_cycle'

    but got it wrong in three ways:

     - the link failure still exists with CONFIG_ACPI_PLATFORM_PROFILE=m
       when hid-lenovo is built-in

     - There is no way to manually enable CONFIG_ACPI_PLATFORM_PROFILE, as
       it is intended to be selected by its users.

    Remove the broken #if check again and instead select the symbol like
    the other users do. This requires adding a dependency on CONFIG_ACPI.

    Fixes: 52e7d1f7c2fd ("HID: lenovo: Fix undefined platform_profile_cycle in ThinkPad X12 keyboard patch")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jiri Kosina <jkosina@suse.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>