rtla: Define __NR_sched_setattr for LoongArch
JIRA: https://issues.redhat.com/browse/RHEL-117873

commit 6a38c51a2557d4d50748818a858d507c250f3bee
Author: Tiezhu Yang <yangtiezhu@loongson.cn>
Date:   Tue Apr 22 15:49:17 2025 +0800

    rtla: Define __NR_sched_setattr for LoongArch

    When executing "make -C tools/tracing/rtla" on LoongArch, there exists
    the following error:

      src/utils.c:237:24: error: '__NR_sched_setattr' undeclared

    Just define __NR_sched_setattr for LoongArch if not exist.

    Link: https://lore.kernel.org/20250422074917.25771-1-yangtiezhu@loongson.cn
    Reported-by: Haiyong Sun <sunhaiyong@loongson.cn>
    Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>
    Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Tomas Glozar <tglozar@redhat.com>