selftests/bpf: Fix clang compilation errors
Bugzilla: https://bugzilla.redhat.com/2120966

commit ccaff3d56acc47c257a99b2807b7c78a9467cf09
Author: Yonghong Song <yhs@fb.com>
Date:   Fri Mar 25 13:03:04 2022 -0700

    selftests/bpf: Fix clang compilation errors

    llvm upstream patch ([1]) added to issue warning for code like
      void test() {
        int j = 0;
        for (int i = 0; i < 1000; i++)
                j++;
        return;
      }

    This triggered several errors in selftests/bpf build since
    compilation flag -Werror is used.
      ...
      test_lpm_map.c:212:15: error: variable 'n_matches' set but not used [-Werror,-Wunused-but-set-variable]
            size_t i, j, n_matches, n_matches_after_delete, n_nodes, n_lookups;
                         ^
      test_lpm_map.c:212:26: error: variable 'n_matches_after_delete' set but not used [-Werror,-Wunused-but-set-variable]
            size_t i, j, n_matches, n_matches_after_delete, n_nodes, n_lookups;
                                    ^
      ...
      prog_tests/get_stack_raw_tp.c:32:15: error: variable 'cnt' set but not used [-Werror,-Wunused-but-set-variable]
            static __u64 cnt;
                         ^
      ...

      For test_lpm_map.c, 'n_matches'/'n_matches_after_delete' are changed to be volatile
      in order to silent the warning. I didn't remove these two declarations since
      they are referenced in a commented code which might be used by people in certain
      cases. For get_stack_raw_tp.c, the variable 'cnt' is removed.

      [1] https://reviews.llvm.org/D122271

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20220325200304.2915588-1-yhs@fb.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>