ALSA: hda: intel-sdw-acpi: Use u8 type for link index
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 485ddd519fbd89a9d9ac4b02be489e03cbbeebba
Author: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Date: Tue Sep 12 19:26:17 2023 +0300

    ALSA: hda: intel-sdw-acpi: Use u8 type for link index

    Use consistently u8 for sdw link index. The id is limited to 4, u8 is
    adequate in size to store it.

    This change will also fixes the following compiler warning/error (W=1):

    sound/hda/intel-sdw-acpi.c: In function ‘sdw_intel_acpi_scan’:
    sound/hda/intel-sdw-acpi.c:34:35: error: ‘-subproperties’ directive output may be truncated writing 14 bytes into a region of size between 7 and 17 [-Werror=format-truncation=]
       34 |                  "mipi-sdw-link-%d-subproperties", i);
          |                                   ^~~~~~~~~~~~~~
    In function ‘is_link_enabled’,
        inlined from ‘sdw_intel_scan_controller’ at sound/hda/intel-sdw-acpi.c:106:8,
        inlined from ‘sdw_intel_acpi_scan’ at sound/hda/intel-sdw-acpi.c:180:9:
    sound/hda/intel-sdw-acpi.c:33:9: note: ‘snprintf’ output between 30 and 40 bytes into a destination of size 32
       33 |         snprintf(name, sizeof(name),
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
       34 |                  "mipi-sdw-link-%d-subproperties", i);
          |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    The warnings got brought to light by a recent patch upstream:
    commit 6d4ab2e97dcf ("extrawarn: enable format and stringop overflow warnings in W=1")

    Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20230912162617.29178-1-peter.ujfalusi@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>