ASN.1: Clean up include statements in public headers
JIRA: https://redhat.atlassian.net/browse/RHEL-186630

commit 4df86c6ea5c37fe0452638f39a1e4b189da75c54
Author: Lukas Wunner <lukas@wunner.de>
Date:   Tue Sep 10 16:30:23 2024 +0200

    ASN.1: Clean up include statements in public headers

    If <linux/asn1_decoder.h> is the first header included from a .c file
    (due to headers being sorted alphabetically), the compiler complains:

      include/linux/asn1_decoder.h:18:29: error: unknown type name 'size_t'

    Avoid by including <linux/types.h>.

    Jonathan notes that the counterpart <linux/asn1_encoder.h> already
    includes <linux/types.h>, but additionally includes the unnecessary
    <linux/bug.h>.  Drop it.

    Signed-off-by: Lukas Wunner <lukas@wunner.de>
    Reviewed-by: Stefan Berger <stefanb@linux.ibm.com>
    Reviewed-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Thomas Huth <thuth@redhat.com>