bpftool: Always disable stack protection for BPF objects
Bugzilla: https://bugzilla.redhat.com/2178930

commit 878625e1c7a10dfbb1fdaaaae2c4d2a58fbce627
Author: Holger Hoffstätte <holger@applied-asynchrony.com>
Date:   Fri Jan 13 16:40:23 2023 +0100

    bpftool: Always disable stack protection for BPF objects
    
    When the clang toolchain has stack protection enabled in order to be
    consistent with gcc - which just happens to be the case on Gentoo -
    the bpftool build fails:
    
      [...]
      clang \
    	-I. \
    	-I/tmp/portage/dev-util/bpftool-6.0.12/work/linux-6.0/tools/include/uapi/ \
    	-I/tmp/portage/dev-util/bpftool-6.0.12/work/linux-6.0/tools/bpf/bpftool/bootstrap/libbpf/include \
    	-g -O2 -Wall -target bpf -c skeleton/pid_iter.bpf.c -o pid_iter.bpf.o
      clang \
    	-I. \
    	-I/tmp/portage/dev-util/bpftool-6.0.12/work/linux-6.0/tools/include/uapi/ \
    	-I/tmp/portage/dev-util/bpftool-6.0.12/work/linux-6.0/tools/bpf/bpftool/bootstrap/libbpf/include \
    	-g -O2 -Wall -target bpf -c skeleton/profiler.bpf.c -o profiler.bpf.o
      skeleton/profiler.bpf.c:40:14: error: A call to built-in function '__stack_chk_fail' is not supported.
      int BPF_PROG(fentry_XXX)
                    ^
      skeleton/profiler.bpf.c:94:14: error: A call to built-in function '__stack_chk_fail' is not supported.
      int BPF_PROG(fexit_XXX)
                    ^
      2 errors generated.
      [...]
    
    Since stack-protector makes no sense for the BPF bits just unconditionally
    disable it.
    
    Bug: https://bugs.gentoo.org/890638
    Signed-off-by: Holger Hoffstätte <holger@applied-asynchrony.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Quentin Monnet <quentin@isovalent.com>
    Link: https://lore.kernel.org/bpf/74cd9d2e-6052-312a-241e-2b514a75c92c@applied-asynchrony.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>