selftests/bpf: Fix compile if backtrace support missing in libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit c9a83e76b5a96801a2c7ea0a79ca77c356d8b38d
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 29 02:24:22 2024 -0700

    selftests/bpf: Fix compile if backtrace support missing in libc

    Include GNU <execinfo.h> header only with glibc and provide weak, stubbed
    backtrace functions as a fallback in test_progs.c. This allows for non-GNU
    replacements while avoiding compile errors (e.g. with musl libc) like:

      test_progs.c:13:10: fatal error: execinfo.h: No such file or directory
         13 | #include <execinfo.h> /* backtrace */
            |          ^~~~~~~~~~~~
      test_progs.c: In function 'crash_handler':
      test_progs.c:1034:14: error: implicit declaration of function 'backtrace' [-Werror=implicit-function-declaration]
       1034 |         sz = backtrace(bt, ARRAY_SIZE(bt));
            |              ^~~~~~~~~
      test_progs.c:1045:9: error: implicit declaration of function 'backtrace_symbols_fd' [-Werror=implicit-function-declaration]
       1045 |         backtrace_symbols_fd(bt, sz, STDERR_FILENO);
            |         ^~~~~~~~~~~~~~~~~~~~

    Fixes: 9fb156bb82a3 ("selftests/bpf: Print backtrace on SIGSEGV in test_progs")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/aa6dc8e23710cb457b278039d0081de7e7b4847d.1722244708.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>