serial: 8250: omap: Move uart_write() inside PM section
JIRA: https://issues.redhat.com/browse/RHEL-24205

commit c53aab20762255ee03e65dd66b3cba3887ad39d1
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon May 15 08:57:06 2023 +0200

    serial: 8250: omap: Move uart_write() inside PM section

    If CONFIG_PM is not set (e.g. m68k/allmodconfig):

        drivers/tty/serial/8250/8250_omap.c:169:13: error: ‘uart_write’ defined but not used [-Werror=unused-function]
          169 | static void uart_write(struct omap8250_priv *priv, u32 reg, u32 val)
              |             ^~~~~~~~~~

    Fix tis by moving uart_write() inside the existing section protected
    by #ifdef CONFIG_PM.

    Reported-by: noreply@ellerman.id.au
    Link: http://kisskb.ellerman.id.au/kisskb/buildresult/14925095/
    Fixes: 398cecc24846e867 ("serial: 8250: omap: Fix imprecise external abort for omap_8250_pm()")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reviewed-by: Tony Lindgren <tony@atomide.com>
    Link: https://lore.kernel.org/r/20230515065706.1723477-1-geert@linux-m68k.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>