scsi: qedi: fix build, depends on UIO
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [scsi] qedi: fix build, depends on UIO (Chad Dupuis) [1384083]
Rebuild_FUZZ: 91.18%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 7961d53d22375bb9e8ae8063533b9059102ed39d

Fix build of SCSI qedi driver. It uses uio interfaces so it should
depend on UIO.

ERROR: "uio_unregister_device" [drivers/scsi/qedi/qedi.ko] undefined!
ERROR: "uio_event_notify" [drivers/scsi/qedi/qedi.ko] undefined!
ERROR: "__uio_register_device" [drivers/scsi/qedi/qedi.ko] undefined!

	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: QLogic-Storage-Upstream@cavium.com
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 7961d53d22375bb9e8ae8063533b9059102ed39d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>