bpf: fix perf_snapshot_branch_stack link failure
JIRA: https://issues.redhat.com/browse/RHEL-30773

commit 58babe27180c8d4cb54d831589cf801bd9268876
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 5 16:26:25 2024 +0200

    bpf: fix perf_snapshot_branch_stack link failure
    
    The newly added code to handle bpf_get_branch_snapshot fails to link when
    CONFIG_PERF_EVENTS is disabled:
    
    aarch64-linux-ld: kernel/bpf/verifier.o: in function `do_misc_fixups':
    verifier.c:(.text+0x1090c): undefined reference to `__SCK__perf_snapshot_branch_stack'
    
    Add a build-time check for that Kconfig symbol around the code to
    remove the link time dependency.
    
    Fixes: 314a53623cd4 ("bpf: inline bpf_get_branch_snapshot() helper")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240405142637.577046-1-arnd@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Viktor Malik <vmalik@redhat.com>