kvm/emulate: fix a -Werror=cast-function-type
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Qian Cai <cai@lca.pw>
commit b78a8552d77f8efb7c4fbd92a91b890c32b89528

arch/x86/kvm/emulate.c: In function 'x86_emulate_insn':
arch/x86/kvm/emulate.c:5686:22: error: cast between incompatible
function types from 'int (*)(struct x86_emulate_ctxt *)' to 'void
(*)(struct fastop *)' [-Werror=cast-function-type]
    rc = fastop(ctxt, (fastop_t)ctxt->execute);

Fix it by using an unnamed union of a (*execute) function pointer and a
(*fastop) function pointer.

Fixes: 3009afc6e39e ("KVM: x86: Use a typedef for fastop functions")
	Suggested-by: Paolo Bonzini <pbonzini@redhat.com>
	Signed-off-by: Qian Cai <cai@lca.pw>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit b78a8552d77f8efb7c4fbd92a91b890c32b89528)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>