wifi: ath11k: workaround too long expansion sparse warnings
JIRA: https://issues.redhat.com/browse/RHEL-28754

commit fd6ed1772b2c639370b7b41602d4c925dbd003d4
Author: Kalle Valo <quic_kvalo@quicinc.com>
Date:   Thu Dec 14 18:17:40 2023 +0200

    wifi: ath11k: workaround too long expansion sparse warnings
    
    In v6.7-rc1 sparse warns:
    
    drivers/net/wireless/ath/ath11k/mac.c:4702:15: error: too long token expansion
    drivers/net/wireless/ath/ath11k/mac.c:4702:15: error: too long token expansion
    drivers/net/wireless/ath/ath11k/mac.c:8393:23: error: too long token expansion
    drivers/net/wireless/ath/ath11k/mac.c:8393:23: error: too long token expansion
    
    Workaround the warnings by refactoring the code to a new function, which also
    reduces code duplication. And in the new function use max3() to make the code
    more readable.
    
    No functional changes, compile tested only.
    
    Acked-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://msgid.link/20231214161740.1582340-1-kvalo@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>