mm: percpu: unhide pcpu_embed_first_chunk prototype
JIRA: https://issues.redhat.com/browse/RHEL-27742

This patch is a backport of the following upstream commit:
commit 6ca0f81c0b96a5e29de48cb02062b5130d27dbe3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 15:10:49 2023 +0200

    mm: percpu: unhide pcpu_embed_first_chunk prototype

    Patch series "mm/init/kernel: missing-prototypes warnings".

    These are patches addressing -Wmissing-prototypes warnings in common
    kernel code and memory management code files that usually get merged
    through the -mm tree.

    This patch (of 12):

    This function is called whenever CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK or
    CONFIG_HAVE_SETUP_PER_CPU_AREA, but only declared when the former is set:

    mm/percpu.c:3055:12: error: no previous prototype for 'pcpu_embed_first_chunk' [-Werror=missing-prototypes]

    There is no real point in hiding declarations, so just remove
    the #ifdef here.

    Link: https://lkml.kernel.org/r/20230517131102.934196-1-arnd@kernel.org
    Link: https://lkml.kernel.org/r/20230517131102.934196-2-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Boqun Feng <boqun.feng@gmail.com>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Christoph Lameter <cl@linux.com>
    Cc: Dennis Zhou <dennis@kernel.org>
    Cc: Eric Paris <eparis@redhat.com>
    Cc: Heiko Carstens <hca@linux.ibm.com>
    Cc: Helge Deller <deller@gmx.de>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Cc: Michal Simek <monstr@monstr.eu>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Paul Moore <paul@paul-moore.com>
    Cc: Pavel Machek <pavel@ucw.cz>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rafael J. Wysocki <rafael@kernel.org>
    Cc: Russell King <linux@armlinux.org.uk>
    Cc: Tejun Heo <tj@kernel.org>
    Cc: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Waiman Long <longman@redhat.com>
    Cc: Will Deacon <will@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>