ALSA: ymfpci: Use common error handling code in snd_ymfpci_create()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Markus Elfring <elfring@users.sourceforge.net>
commit ba2186e40c9565b0a3ecd9e51ac1195cc501c182

* Add a jump target so that a bit of exception handling can be better
  reused at the end of this function.

  This issue was detected by using the Coccinelle software.

* The script "checkpatch.pl" pointed information out like the following.

  ERROR: do not use assignment in if condition

  Thus fix a few source code places.

	Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit ba2186e40c9565b0a3ecd9e51ac1195cc501c182)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>