iommu: Make IPMMU_VMSA dependencies more strict
JIRA: https://issues.redhat.com/browse/RHEL-10094
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit e332003bb216a9f91e08004b9e2de0745f321290
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Thu Mar 30 09:58:17 2023 -0700

    iommu: Make IPMMU_VMSA dependencies more strict

    On riscv64, linux-next-20233030 (and for several days earlier),
    there is a kconfig warning:

    WARNING: unmet direct dependencies detected for IOMMU_IO_PGTABLE_LPAE
      Depends on [n]: IOMMU_SUPPORT [=y] && (ARM || ARM64 || COMPILE_TEST [=n]) && !GENERIC_ATOMIC64 [=n]
      Selected by [y]:
      - IPMMU_VMSA [=y] && IOMMU_SUPPORT [=y] && (ARCH_RENESAS [=y] || COMPILE_TEST [=n]) && !GENERIC_ATOMIC64 [=n]

    and build errors:

    riscv64-linux-ld: drivers/iommu/io-pgtable-arm.o: in function `.L140':
    io-pgtable-arm.c:(.init.text+0x1e8): undefined reference to `alloc_io_pgtable_ops'
    riscv64-linux-ld: drivers/iommu/io-pgtable-arm.o: in function `.L168':
    io-pgtable-arm.c:(.init.text+0xab0): undefined reference to `free_io_pgtable_ops'
    riscv64-linux-ld: drivers/iommu/ipmmu-vmsa.o: in function `.L140':
    ipmmu-vmsa.c:(.text+0xbc4): undefined reference to `free_io_pgtable_ops'
    riscv64-linux-ld: drivers/iommu/ipmmu-vmsa.o: in function `.L0 ':
    ipmmu-vmsa.c:(.text+0x145e): undefined reference to `alloc_io_pgtable_ops'

    Add ARM || ARM64 || COMPILE_TEST dependencies to IPMMU_VMSA to prevent
    these issues, i.e., so that ARCH_RENESAS on RISC-V is not allowed.

    This makes the ARCH dependencies become:
	    depends on (ARCH_RENESAS && (ARM || ARM64)) || COMPILE_TEST
    but that can be a bit hard to read.

    Fixes: 8292493c22c8 ("riscv: Kconfig.socs: Add ARCH_RENESAS kconfig option")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Suggested-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Cc: Joerg Roedel <joro@8bytes.org>
    Cc: Will Deacon <will@kernel.org>
    Cc: Robin Murphy <robin.murphy@arm.com>
    Cc: iommu@lists.linux.dev
    Cc: Conor Dooley <conor@kernel.org>
    Cc: Lad Prabhakar <prabhakar.mahadev-lad.rj@bp.renesas.com>
    Reviewed-by: Robin Murphy <robin.murphy@arm.com>
    Link: https://lore.kernel.org/r/20230330165817.21920-1-rdunlap@infradead.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit e332003bb216a9f91e08004b9e2de0745f321290)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>