selftests/bpf: Initialize duration in xdp_noinline.c
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-315.el8
commit-author Stanislav Fomichev <sdf@google.com>
commit cffcdbff70a3cf3cc4f42fa2e57012411b1c78a6

Fixes clang error:
tools/testing/selftests/bpf/prog_tests/xdp_noinline.c:35:6: error: variable 'duration' is uninitialized when used here [-Werror,-Wuninitialized]
        if (CHECK(!skel, "skel_open_and_load", "failed\n"))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	Signed-off-by: Stanislav Fomichev <sdf@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Acked-by: Martin KaFai Lau <kafai@fb.com>
Link: https://lore.kernel.org/bpf/20201001225440.1373233-1-sdf@google.com
(cherry picked from commit cffcdbff70a3cf3cc4f42fa2e57012411b1c78a6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>