compiler.h: Introduce absolute_pointer macro
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Guenter Roeck <linux@roeck-us.net>
commit f6b5f1a56987de837f8e25cd560847106b8632a8

absolute_pointer() disassociates a pointer from its originating symbol
type and context. Use it to prevent compiler warnings/errors such as

  drivers/net/ethernet/i825xx/82596.c: In function 'i82596_probe':
  arch/m68k/include/asm/string.h:72:25: error:
	'__builtin_memcpy' reading 6 bytes from a region of size 0 [-Werror=stringop-overread]

Such warnings may be reported by gcc 11.x for string and memory
operations on fixed addresses.

	Suggested-by: Linus Torvalds <torvalds@linux-foundation.org>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Reviewed-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit f6b5f1a56987de837f8e25cd560847106b8632a8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>