bitops: Fix signedness of compile-time hweight implementations
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Paul Walmsley <pwalmsley@nvidia.com>
commit c32fa99f0b4252633aa464e28d1cb925bd2a79df

Enabling '-Wsign-compare' compiler warnings on code that includes
include/linux/bitops.h can generate the following warning:

  In file included from include/linux/kernel.h:10:0,
                    from <random filename>:48:
  include/linux/bitops.h: In function 'hweight_long':
  include/linux/bitops.h:77:26: error: signed and unsigned type in conditional expression [-Werror=sign-compare]

(converted to an error with -Werror)

This is due to the use of the logical negation operator '!' in the
__const_hweight8 macro in include/asm-generic/bitops/const_hweight.h.
The use of that operator here results in a signed value.

Fix by explicitly casting the __const_hweight8 macro expansion to
'unsigned int'.  While here, clean up several checkpatch.pl warnings.

	Signed-off-by: Paul Walmsley <pwalmsley@nvidia.com>
	Cc: Arnd Bergmann <arnd@arndb.de>
	Cc: H. Peter Anvin <hpa@zytor.com>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/alpine.DEB.2.02.1312180459580.30198@tamien
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit c32fa99f0b4252633aa464e28d1cb925bd2a79df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>