Input: stmpe-ts - use module alias instead of device table
JIRA: https://issues.redhat.com/browse/RHEL-101770
Upstream Status: since v6.15
Tested: with the hid-tools test suite and some hardware

commit 9a046c1d21f0ae14c73b5e106e5a501dd902b6a9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 9 14:22:55 2025 +0200

    Input: stmpe-ts - use module alias instead of device table

    When compile tested with W=1 on x86_64 with driver as built-in:

      stmpe-ts.c:371:34: error: unused variable 'stmpe_ts_ids' [-Werror,-Wunused-const-variable]

    Ideally this would be referenced from the platform_driver, but since
    the compatible string is already matched by the mfd driver for its
    parent device, that would break probing.

    In this case, the of_device_id table just serves as a module alias
    for loading the driver, while the device itself is probed using
    the platform device name.

    Remove the table and instead use a module alias that reflects how
    the driver is actually probed.

    Link: https://lore.kernel.org/lkml/20240403080702.3509288-8-arnd@kernel.org/
    Link: https://lore.kernel.org/lkml/181dbdb8-c050-4966-8cb4-2f39495ff3f9@app.fastmail.com/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20250409122314.2848028-3-arnd@kernel.org
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>