drm/i915: Fix format string truncation warning
JIRA: https://issues.redhat.com/browse/RHEL-135337

commit 5457bdfab729c8523220d302565e10adb57cc1a1
Author: Ard Biesheuvel <ardb@kernel.org>
Date:   Fri Dec 5 12:35:01 2025 +0100

    drm/i915: Fix format string truncation warning

    commit 1c7f9e528f8f488b060b786bfb90b40540854db3 upstream.

    GCC notices that the 16-byte uabi_name field could theoretically be too
    small for the formatted string if the instance number exceeds 100.

    So grow the field to 20 bytes.

    drivers/gpu/drm/i915/intel_memory_region.c: In function ‘intel_memory_region_create’:
    drivers/gpu/drm/i915/intel_memory_region.c:273:61: error: ‘%u’ directive output may be truncated writing between 1 and 5 bytes into a region of size between 3 and 11 [-Werror=format-truncation=]
      273 |         snprintf(mem->uabi_name, sizeof(mem->uabi_name), "%s%u",
          |                                                             ^~
    drivers/gpu/drm/i915/intel_memory_region.c:273:58: note: directive argument in the range [0, 65535]
      273 |         snprintf(mem->uabi_name, sizeof(mem->uabi_name), "%s%u",
          |                                                          ^~~~~~
    drivers/gpu/drm/i915/intel_memory_region.c:273:9: note: ‘snprintf’ output between 7 and 19 bytes into a destination of size 16
      273 |         snprintf(mem->uabi_name, sizeof(mem->uabi_name), "%s%u",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      274 |                  intel_memory_type_str(type), instance);
          |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: 3b38d3515753 ("drm/i915: Add stable memory region names")
    Cc: <stable@vger.kernel.org> # v6.8+
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
    Signed-off-by: Tvrtko Ursulin <tursulin@ursulin.net>
    Link: https://lore.kernel.org/r/20251205113500.684286-2-ardb@kernel.org
    (cherry picked from commit 18476087f1a18dc279d200d934ad94fba1fb51d5)
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: José Expósito <jexposit@redhat.com>