iommu/arm-smmu-qcom: Don't build debug features as a kernel module
JIRA: https://issues.redhat.com/browse/RHEL-55448
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 0928fc15f31553c7acb8117b0609799fc0f22fa5
Author: Will Deacon <will@kernel.org>
Date:   Wed May 1 15:27:29 2024 +0100

    iommu/arm-smmu-qcom: Don't build debug features as a kernel module

    The Qualcomm TBU debug support introduced by 414ecb030870
    ("iommu/arm-smmu-qcom-debug: Add support for TBUs") provides its own
    driver initialisation function, which breaks the link when the core SMMU
    driver is built as a module:

      ld.lld: error: duplicate symbol: init_module
      >>> defined at arm-smmu.c
      >>>            drivers/iommu/arm/arm-smmu/arm-smmu.o:(init_module)
      >>> defined at arm-smmu-qcom-debug.c
      >>>            drivers/iommu/arm/arm-smmu/arm-smmu-qcom-debug.o:(.init.text+0x4)

    Since we're late in the cycle, just make the debug features depend on a
    non-modular SMMU driver for now while the initialisation is reworked to
    hang off qcom_smmu_impl_init().

    Signed-off-by: Will Deacon <will@kernel.org>

(cherry picked from commit 0928fc15f31553c7acb8117b0609799fc0f22fa5)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>