mtd: nand: Drop explicit test for built-in CONFIG_SPI_QPIC_SNAND
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit 36c6468724aa98d33fea9a1d7e07ddda6302f5d4
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Fri Mar 28 09:24:01 2025 +0100

    mtd: nand: Drop explicit test for built-in CONFIG_SPI_QPIC_SNAND

    If CONFIG_SPI_QPIC_SNAND=m, but CONFIG_MTD_NAND_QCOM=n:

        ERROR: modpost: "qcom_nandc_unalloc" [drivers/spi/spi-qpic-snand.ko] undefined!
        ...

    Fix this by dropping the explicit test for a built-in
    CONFIG_SPI_QPIC_SNAND completely.  Kbuild handles multiple and mixed
    obj-y/obj-m rules for the same object file fine.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202503280759.XhwLcV7m-lkp@intel.com/
    Fixes: 7304d1909080ef0c ("spi: spi-qpic: add driver for QCOM SPI NAND flash Interface")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Signed-off-by: Miquel Raynal <miquel.raynal@bootlin.com>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>