ASoC: amd: fix Jadeite kconfig warning and build errors
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 1795c16a436057f95fef5b622d808885dd772d0e

Since SND_SOC_ES8316 has a hard dependency on I2C and since 'select'
does not follow any dependency chains, SND_SOC_AMD_ST_ES8336_MACH
also needs to have a hard dependency on I2C.

Fixes a kconfig warning and subsequent build errors:

WARNING: unmet direct dependencies detected for SND_SOC_ES8316
  Depends on [n]: SOUND [=y] && !UML && SND [=y] && SND_SOC [=y] && I2C [=n]
  Selected by [y]:
  - SND_SOC_AMD_ST_ES8336_MACH [=y] && SOUND [=y] && !UML && SND [=y] && SND_SOC [=y] && SND_SOC_AMD_ACP [=y] && ACPI [=y] && (I2C [=n] || COMPILE_TEST [=y])

sound/soc/codecs/es8316.c:866:1: warning: data definition has no type or storage class
  866 | module_i2c_driver(es8316_i2c_driver);
sound/soc/codecs/es8316.c:866:1: error: type defaults to ‘int’ in declaration of ‘module_i2c_driver’ [-Werror=implicit-int]
sound/soc/codecs/es8316.c:866:1: warning: parameter names (without types) in function declaration
sound/soc/codecs/es8316.c:857:26: warning: ‘es8316_i2c_driver’ defined but not used [-Wunused-variable]
  857 | static struct i2c_driver es8316_i2c_driver = {

Fixes: f94fa8405801 ("ASoC: amd: enable machine driver build for Jadeite platform")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Vijendar Mukunda <Vijendar.Mukunda@amd.com>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: alsa-devel@alsa-project.org
	Cc: Jaroslav Kysela <perex@perex.cz>
	Cc: Takashi Iwai <tiwai@suse.com>
Link: https://lore.kernel.org/r/20220712183348.31046-1-rdunlap@infradead.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 1795c16a436057f95fef5b622d808885dd772d0e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>