ASoC: rt5682: fix I2C/Soundwire dependencies
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: rt5682: fix I2C/Soundwire dependencies (Jaroslav Kysela) [1869536]
Rebuild_FUZZ: 93.62%
commit-author Arnd Bergmann <arnd@arndb.de>
commit fd443a20c2f0950f3c31765a08f7dd49b3bc69cb

If one of the two is a loadable module, the combined driver must
not be built-in:

aarch64-linux-ld: sound/soc/codecs/rt5682.o: in function `rt5682_sdw_hw_free':
rt5682.c:(.text+0xb34): undefined reference to `sdw_stream_remove_slave'
aarch64-linux-ld: sound/soc/codecs/rt5682.o: in function `rt5682_sdw_hw_params':
rt5682.c:(.text+0xe78): undefined reference to `sdw_stream_add_slave'

In particular, the soundwire driver must not be built-in if
CONFIG_I2C=m.

Fixes: 5549ea647997 ("ASoC: rt5682: fix unmet dependencies")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20200428214642.3925004-1-arnd@arndb.de
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit fd443a20c2f0950f3c31765a08f7dd49b3bc69cb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>