i2c: imx: fix i2c issue when reading multiple messages
jira KERNEL-1600
Rebuild_History Non-Buildable kernel-6.12.0-211.55.1.el10_2
commit-author Stefan Eichenberger <stefan.eichenberger@toradex.com>
commit f88e2e748a1fc3cb4b8d163a9be790812f578850

When reading multiple messages, meaning a repeated start is required,
polling the bus busy bit must be avoided. This must only be done for
the last message. Otherwise, the driver will timeout.

Here an example of such a sequence that fails with an error:
i2ctransfer -y -a 0 w1@0x00 0x02 r1 w1@0x00 0x02 r1
Error: Sending messages failed: Connection timed out

Fixes: 5f5c2d4579ca ("i2c: imx: prevent rescheduling in non dma mode")
	Cc: stable@vger.kernel.org # v6.13+
	Signed-off-by: Stefan Eichenberger <stefan.eichenberger@toradex.com>
	Reviewed-by: Frank Li <Frank.Li@nxp.com>
	Signed-off-by: Andi Shyti <andi.shyti@kernel.org>
Link: https://lore.kernel.org/r/20260218150940.131354-2-eichest@gmail.com
(cherry picked from commit f88e2e748a1fc3cb4b8d163a9be790812f578850)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>