arm64: arch_timer: avoid unused function warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 040f340134751d73bd03ee92fabb992946c55b3d

arm64_1188873_read_cntvct_el0() is protected by the correct
CONFIG_ARM64_ERRATUM_1188873 #ifdef, but the only reference to it is
also inside of an CONFIG_ARM_ARCH_TIMER_OOL_WORKAROUND section,
and causes a warning if that is disabled:

drivers/clocksource/arm_arch_timer.c:323:20: error: 'arm64_1188873_read_cntvct_el0' defined but not used [-Werror=unused-function]

Since the erratum requires that we always apply the workaround
in the timer driver, select that symbol as we do for SoC
specific errata.

Fixes: 95b861a4a6d9 ("arm64: arch_timer: Add workaround for ARM erratum 1188873")
	Acked-by: Marc Zyngier <marc.zyngier@arm.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
(cherry picked from commit 040f340134751d73bd03ee92fabb992946c55b3d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>