Input: i8042 - fix Pegatron C15B ID entry
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit daa58c8eec0a65ac8e2e77ff3ea8a233d8eec954

The Zenbook Flip entry that was added overwrites a previous one
because of a typo:

In file included from drivers/input/serio/i8042.h:23,
                 from drivers/input/serio/i8042.c:131:
drivers/input/serio/i8042-x86ia64io.h:591:28: error: initialized field overwritten [-Werror=override-init]
  591 |                 .matches = {
      |                            ^
drivers/input/serio/i8042-x86ia64io.h:591:28: note: (near initialization for 'i8042_dmi_noselftest_table[0].matches')

Add the missing separator between the two.

Fixes: b5d6e7ab7fe7 ("Input: i8042 - add ASUS Zenbook Flip to noselftest list")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Hans de Goede <hdegoede@redhat.com>
	Reviewed-by: Marcos Paulo de Souza <mpdesouza@suse.com>
Link: https://lore.kernel.org/r/20210323130623.2302402-1-arnd@kernel.org
	Cc: stable@vger.kernel.org
	Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
(cherry picked from commit daa58c8eec0a65ac8e2e77ff3ea8a233d8eec954)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>