bpf: Avoid putting struct bpf_scc_callchain variables on the stack
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit 82bc4abf28d8147dd5da9ba52f0aa1bac23c125e
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Thu Jul 3 07:11:17 2025 -0700

    bpf: Avoid putting struct bpf_scc_callchain variables on the stack
    
    Add a 'struct bpf_scc_callchain callchain_buf' field in bpf_verifier_env.
    This way, the previous bpf_scc_callchain local variables can be
    replaced by taking address of env->callchain_buf. This can reduce stack
    usage and fix the following error:
        kernel/bpf/verifier.c:19921:12: error: stack frame size (1368) exceeds limit (1280) in 'do_check'
            [-Werror,-Wframe-larger-than]
    
    Reported-by: Arnd Bergmann <arnd@kernel.org>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20250703141117.1485108-1-yonghong.song@linux.dev
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>