powerpc/spinlocks: Include correct header for static key
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Jason A. Donenfeld <Jason@zx2c4.com>
commit 6da3eced8c5f3b03340b0c395bacd552c4d52411

Recently, the spinlock implementation grew a static key optimization,
but the jump_label.h header include was left out, leading to build
errors:

  linux/arch/powerpc/include/asm/spinlock.h:44:7: error: implicit declaration of function ‘static_branch_unlikely’
   44 |  if (!static_branch_unlikely(&shared_processor))

This commit adds the missing header.

mpe: The build break is only seen with CONFIG_JUMP_LABEL=n.

Fixes: 656c21d6af5d ("powerpc/shared: Use static key to detect shared processor")
	Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
	Reviewed-by: Srikar Dronamraju <srikar@linux.ibm.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20191223133147.129983-1-Jason@zx2c4.com
(cherry picked from commit 6da3eced8c5f3b03340b0c395bacd552c4d52411)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>