autofs: move inclusion of linux/limits.h to uapi
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Tomohiro Kusumi <kusumi.tomohiro@gmail.com>
commit f58b3c91f6786c66483fc18fd8b82a74cbf96d19

linux/limits.h should be included by uapi instead of linux/auto_fs.h
so as not to cause compile error in userspace.

 # cat << EOF > ./test1.c
 > #include <stdio.h>
 > #include <linux/auto_fs.h>
 > int main(void) {
 >     return 0;
 > }
 > EOF
 # gcc -Wall -g ./test1.c
 In file included from ./test1.c:2:0:
 /usr/include/linux/auto_fs.h:54:12: error: 'NAME_MAX' undeclared here (not in a function)
   char name[NAME_MAX+1];
             ^

Link: http://lkml.kernel.org/r/20160812024856.12352.24092.stgit@pluto.themaw.net
	Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>
	Signed-off-by: Ian Kent <ikent@redhat.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit f58b3c91f6786c66483fc18fd8b82a74cbf96d19)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>