libbpf: Use __u32 instead of u32 in bpf_program__load
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Andrey Ignatov <rdna@fb.com>
commit e5b0863c2064f2d40de9de4862317f9db4ccffff

Make bpf_program__load consistent with other interfaces: use __u32
instead of u32. That in turn fixes build of samples:

In file included from ./samples/bpf/trace_output_user.c:21:0:
./tools/lib/bpf/libbpf.h:132:9: error: unknown type name ‘u32’
         u32 kern_version);
         ^

Fixes: commit 29cd77f41620d ("libbpf: Support loading individual progs")
	Signed-off-by: Andrey Ignatov <rdna@fb.com>
	Acked-by: Alexei Starovoitov <ast@kernel.org>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit e5b0863c2064f2d40de9de4862317f9db4ccffff)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>