ALSA: trident: Fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit fd498bba7c5194cdfc3f0d726f99f0fa3b7e51de

sound/pci/trident/trident_memory.c: In function ‘set_tlb_bus’:
sound/pci/trident/trident_memory.c:85:35: error: ‘pagetr’ undeclared (first use in this function); did you mean ‘page’?
  for (i = 0; i < UNIT_PAGES; i++, pagetr++) {
                                   ^~~~~~
                                   page

Fixes: 74fb98311c4e ("ALSA: trident: Drop shadow TLB pointer table")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Link: https://lore.kernel.org/r/20210612033458.42928-1-yuehaibing@huawei.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit fd498bba7c5194cdfc3f0d726f99f0fa3b7e51de)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>