perf bench futex: Fix prctl include in musl libc
JIRA: https://issues.redhat.com/browse/RHEL-101509

commit 1c85c94b3767895d70b7a5a49b111f974f5660ec
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Mon, 16 Jun 2025 14:33:17 -0300

    perf bench futex: Fix prctl include in musl libc

    Namhyung Kim reported:

      I've updated the perf-tools-next to v6.16-rc1 and found a build error
      like below on alpine linux 3.18.

        In file included from bench/futex.c:6:
        /usr/include/sys/prctl.h:88:8: error: redefinition of 'struct prctl_mm_map'
           88 | struct prctl_mm_map {
              |        ^~~~~~~~~~~~
        In file included from bench/futex.c:5:
        /linux/tools/include/uapi/linux/prctl.h:134:8: note: originally defined here
          134 | struct prctl_mm_map {
              |        ^~~~~~~~~~~~
        make[4]: *** [/linux/tools/build/Makefile.build:86: /build/bench/futex.o] Error 1

      git bisect says it's the first commit introduced the failure.

    So both /usr/include/sys/prctl.h and /linux/tools/include/uapi/linux/prctl.h
    provide struct prctl_mm_map but their include guard must be different.

    /usr/include/sys/prctl.h provided by glibc contains the
    prctl() declaration. It includes also linux/prctl.h.

    The /usr/include/sys/prctl.h on alpine linux is different. This is
    probably coming from musl. It contains the PR_* definition and the
    prctl() declaration.  So it clashes here because now the one struct is
    available twice.

    The man page for prctl(2) says:

    |       #include <linux/prctl.h>  /* Definition of PR_* constants */
    |       #include <sys/prctl.h>

    so musl doesn't follow this.

    So don't include linux/prctl.h explicitely and add some new defines
    needed if they aren't available.

    Acked-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
    Reported-by: Namhyung Kim <namhyung@kernel.org>
    Closes: https://lore.kernel.org/r/20250611092542.F4ooE2FL@linutronix.de
    Link: https://www.openwall.com/lists/musl/2025/06/12/11
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Waiman Long <longman@redhat.com>