selftests/bpf: Fix build error due to certain uninitialized variables
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit e860a98c8aebd8de82c0ee901acf5a759acd4570
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Tue Jul 15 11:59:10 2025 -0700

    selftests/bpf: Fix build error due to certain uninitialized variables
    
    With the latest llvm21 compiler, I hit several errors when building bpf
    selftests. Some of errors look like below:
    
      test_maps.c:565:40: error: variable 'val' is uninitialized when passed as a
          const pointer argument here [-Werror,-Wuninitialized-const-pointer]
        565 |         assert(bpf_map_update_elem(fd, NULL, &val, 0) < 0 &&
            |                                               ^~~
    
      prog_tests/bpf_iter.c:400:25: error: variable 'c' is uninitialized when passed
          as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
      400 |         write(finish_pipe[1], &c, 1);
          |                                ^
    
    Some other errors have similar the pattern as the above.
    
    These errors are fixed by initializing those variables properly.
    
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20250715185910.3659447-1-yonghong.song@linux.dev

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>