HID: ft260: support i2c writes larger than HID report size
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2166610
Upstream Status: since v6.2
Tested: with the hid-tools test suite and some hardware

commit 1edfae51d5763439b2c89c9419c377f9c0da354d
Author: Michael Zaidman <michael.zaidman@gmail.com>
Date:   Sat Nov 5 23:11:41 2022 +0200

    HID: ft260: support i2c writes larger than HID report size

    To support longer than one HID report size write, the driver splits a
    single i2c message data payload into multiple i2c messages of HID report
    size. However, it does not replicate the offset bytes within the EEPROM
    chip in every consequent HID report because it is not and should not be
    aware of the EEPROM type. It breaks the i2c write message integrity and
    causes the EEPROM device not to acknowledge the second HID report keeping
    the i2c bus busy until the ft260 controller reports failure.

    This patch preserves the i2c write message integrity by manipulating the
    i2c flag bits across multiple HID reports to be seen by the EEPROM device
    as a single i2c write transfer.

    Before:

    $ sudo ./i2cperf -f 2 -o 2 -s 64 -r 0-0xff 13 0x51 -S
    Error: Sending messages failed: Input/output error

    [  +3.667741] ft260_i2c_write: rep 0xde addr 0x51 off 0 len 60 d[0] 0x0
    [  +0.007330] ft260_hid_output_report_check_status: wait 6400 usec, len 64
    [  +0.000203] ft260_xfer_status: bus_status 0x40, clock 100
    [  +0.000001] ft260_i2c_write: rep 0xd1 addr 0x51 off 60 len 6 d[0] 0x0
    [  +0.002337] ft260_hid_output_report_check_status: wait 1000 usec, len 10
    [  +0.000157] ft260_xfer_status: bus_status 0x2e, clock 100
    [  +0.000241] ft260_i2c_reset: done
    [  +0.000003] ft260_i2c_write: failed to start transfer, ret -5

    After:

    $ sudo ./i2cperf -f 2 -o 2 -s 128 -r 0-0xff 13 0x51 -S

      Fill block with increment via i2ctransfer by chunks
      -------------------------------------------------------------------
      data rate(bps)  efficiency(%)  data size(B)  total IOs   IO size(B)
      -------------------------------------------------------------------
      71260           86             256           2           128

    Signed-off-by: Michael Zaidman <michael.zaidman@gmail.com>
    Tested-by: Guillaume Champagne <champagne.guillaume.c@gmail.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>