redhat/kernel.spec.template: fix standalone tools build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2081992
Upstream Status: RHEL-only
                 (kernel-ark)

commit c83dc39ec2c9e7c284f5ba392176ae901b07f147
Author: Jan Stancek <jstancek@redhat.com>
Date:   Tue May 10 09:00:27 2022 +0200

    redhat/kernel.spec.template: fix standalone tools build

    Building only tools:
      rpmbuild --rebuild --without doc --without cross_headers \
               --without kabidw_base --without debuginfo --without debug \
               --without up --without zfcpdump --without trace \
               --without bpftool --without selftests --without pae kernel.src.rpm

    at the moment fails with:
      find: '/root/rpmbuild/BUILDROOT/kernel-5.18.0-0.rc6.47.test.el9.x86_64/lib/modules/': No such file or directory
      xz: Compressed data cannot be written to a terminal
      xz: Try `xz --help' for more information.
      error: Bad exit status from /var/tmp/rpm-tmp.EaolzQ (%install)

    Add "-r" to xargs to skip compression if no modules are built.

    Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
    Signed-off-by: Jan Stancek <jstancek@redhat.com>

Signed-off-by: Jan Stancek <jstancek@redhat.com>