ipv4: Fix compilation errors in fib_rebalance
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Peter Nørlund <pch@ordbogen.com>
commit 0a837fe4724713ef701e47d6bfab98a5efaff3eb
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/0a837fe4.failed

This fixes

net/built-in.o: In function `fib_rebalance':
fib_semantics.c:(.text+0x9df14): undefined reference to `__divdi3'

and

net/built-in.o: In function `fib_rebalance':
net/ipv4/fib_semantics.c:572: undefined reference to `__aeabi_ldivmod'

Fixes: 0e884c78ee19 ("ipv4: L3 hash-based multipath")

	Signed-off-by: Peter Nørlund <pch@ordbogen.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 0a837fe4724713ef701e47d6bfab98a5efaff3eb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/ipv4/fib_semantics.c