selftests/bpf: Fix compiling parse_tcp_hdr_opt.c with musl-libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 4c329b99ef9c118343379bde9f97e8ce5cac9fc9
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:38 2024 -0700

    selftests/bpf: Fix compiling parse_tcp_hdr_opt.c with musl-libc

    The GNU version of 'struct tcphdr', with members 'doff' and 'urg_ptr', is
    not exposed by musl headers unless _GNU_SOURCE is defined.

    Add this definition to fix errors seen compiling for mips64el/musl-libc:

      parse_tcp_hdr_opt.c:18:21: error: 'struct tcphdr' has no member named 'urg_ptr'
         18 |         .pk6_v6.tcp.urg_ptr = 123,
            |                     ^~~~~~~
      parse_tcp_hdr_opt.c:19:21: error: 'struct tcphdr' has no member named 'doff'
         19 |         .pk6_v6.tcp.doff = 9, /* 16 bytes of options */
            |                     ^~~~

    Fixes: cfa7b011894d ("selftests/bpf: tests for using dynptrs to parse skb and xdp buffers")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/ac5440213c242c62cb4e0d9e0a9cd5058b6a31f6.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>