HID: bpf: doc fixes for hid_hw_request() hooks
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.12
Tested: with the hid-tools test suite and some hardware

commit 260ffc9676b635c2ededc39285bfa41f83536ee1
Author: Benjamin Tissoires <bentiss@kernel.org>
Date:   Mon Jul 1 14:39:51 2024 +0200

    HID: bpf: doc fixes for hid_hw_request() hooks

    We had the following errors while doing make htmldocs:
    Documentation/hid/hid-bpf:185: include/linux/hid_bpf.h:144:
            ERROR: Unexpected indentation.
    Documentation/hid/hid-bpf:185: include/linux/hid_bpf.h:145:
            WARNING: Block quote ends without a blank line;
            unexpected unindent.
    Documentation/hid/hid-bpf:185: include/linux/hid_bpf.h:147:
            ERROR: Unexpected indentation.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Fixes: 8bd0488b5ea5 ("HID: bpf: add HID-BPF hooks for hid_hw_raw_requests")
    Link: https://patch.msgid.link/20240701-fix-cki-v2-3-20564e2e1393@kernel.org
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>