ASoC: amd: AMD RV RT5682 should depends on CROS_EC
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Enric Balletbo i Serra <enric.balletbo@collabora.com>
commit e7e2afeacaa6e6b3d428ca8dd0507f1098bafe5d

If SND_SOC_AMD_RV_RT5682_MACH=y, below kconfig and build errors can be seen:

 WARNING: unmet direct dependencies detected for SND_SOC_CROS_EC_CODEC
 WARNING: unmet direct dependencies detected for I2C_CROS_EC_TUNNEL

 ld: drivers/i2c/busses/i2c-cros-ec-tunnel.o: in function `ec_i2c_xfer':
 i2c-cros-ec-tunnel.c:(.text+0x2fc): undefined reference to `cros_ec_cmd_xfer_status'
 ld: sound/soc/codecs/cros_ec_codec.o: in function `wov_host_event':
 cros_ec_codec.c:(.text+0x4fb): undefined reference to `cros_ec_get_host_event'
 ld: sound/soc/codecs/cros_ec_codec.o: in function `send_ec_host_command':
 cros_ec_codec.c:(.text+0x831): undefined reference to `cros_ec_cmd_xfer_status'

This is because it will select SND_SOC_CROS_EC_CODEC and I2c_CROS_EC_TUNNEL but
both depends on CROS_EC.

Fixes: 6b8e4e7db3cd ("ASoC: amd: Add machine driver for Raven based platform")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Enric Balletbo i Serra <enric.balletbo@collabora.com>
Link: https://lore.kernel.org/r/20200303110514.3267126-1-enric.balletbo@collabora.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit e7e2afeacaa6e6b3d428ca8dd0507f1098bafe5d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>