selftests:resctrl: Fix build failure on archs without __cpuid_count()
JIRA: https://issues.redhat.com/browse/RHEL-20790

commit 7beaf1da074f7ea25454d6c11da142c3892d3c4e
Author: Shuah Khan <skhan@linuxfoundation.org>
Date:   Thu Sep 5 12:02:31 2024 -0600

    selftests:resctrl: Fix build failure on archs without __cpuid_count()

    When resctrl is built on architectures without __cpuid_count()
    support, build fails. resctrl uses __cpuid_count() defined in
    kselftest.h.

    Even though the problem is seen while building resctrl on aarch64,
    this error can be seen on any platform that doesn't support CPUID.

    CPUID is a x86/x86-64 feature and code paths with CPUID asm commands
    will fail to build on all other architectures.

    All others tests call __cpuid_count() do so from x86/x86_64 code paths
    when _i386__ or __x86_64__ are defined. resctrl is an exception.

    Fix the problem by defining __cpuid_count() only when __i386__ or
    __x86_64__ are defined in kselftest.h and changing resctrl to call
    __cpuid_count() only when __i386__ or __x86_64__ are defined.

    In file included from resctrl.h:24,
                     from cat_test.c:11:
    In function ‘arch_supports_noncont_cat’,
        inlined from ‘noncont_cat_run_test’ at cat_test.c:326:6:
    ../kselftest.h:74:9: error: impossible constraint in ‘asm’
       74 |         __asm__ __volatile__ ("cpuid\n\t"                               \
          |         ^~~~~~~
    cat_test.c:304:17: note: in expansion of macro ‘__cpuid_count’
      304 |                 __cpuid_count(0x10, 1, eax, ebx, ecx, edx);
          |                 ^~~~~~~~~~~~~
    ../kselftest.h:74:9: error: impossible constraint in ‘asm’
       74 |         __asm__ __volatile__ ("cpuid\n\t"                               \
          |         ^~~~~~~
    cat_test.c:306:17: note: in expansion of macro ‘__cpuid_count’
      306 |                 __cpuid_count(0x10, 2, eax, ebx, ecx, edx);

    Fixes: ae638551ab64 ("selftests/resctrl: Add non-contiguous CBMs CAT test")
    Reported-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Closes: https://lore.kernel.org/lkml/20240809071059.265914-1-usama.anjum@collabora.com/
    Reported-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
    Acked-by: Reinette Chatre <reinette.chatre@intel.com>
    Reviewed-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: David Arcari <darcari@redhat.com>