refperf: Work around 64-bit division
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7c944d7c67daee84e3c756bb74ad2f32b28c41cf

A 64-bit division was introduced in refperf, breaking compilation
on all 32-bit architectures:

kernel/rcu/refperf.o: in function `main_func':
refperf.c:(.text+0x57c): undefined reference to `__aeabi_uldivmod'

Fix this by using div_u64 to mark the expensive operation.

[ paulmck: Update primitive and format per Nathan Chancellor. ]
Fixes: bd5b16d6c88d ("refperf: Allow decimal nanoseconds")
	Reported-by: kbuild test robot <lkp@intel.com>
	Reported-by: Valdis Klētnieks <valdis.kletnieks@vt.edu>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Paul E. McKenney <paulmck@kernel.org>
(cherry picked from commit 7c944d7c67daee84e3c756bb74ad2f32b28c41cf)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>