x86/paravirt: Silence unused native_pv_lock_init() function warning
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit ce0a1b608bfc709cf366f020b520310a3b3272c3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 3 10:26:18 2023 +0200

    x86/paravirt: Silence unused native_pv_lock_init() function warning

    The native_pv_lock_init() function is only used in SMP configurations
    and declared in asm/qspinlock.h which is not used in UP kernels, but
    the function is still defined for both, which causes a warning:

      arch/x86/kernel/paravirt.c:76:13: error: no previous prototype for 'native_pv_lock_init' [-Werror=missing-prototypes]

    Move the declaration to asm/paravirt.h so it is visible even
    with CONFIG_SMP but short-circuit the definition to turn it
    into an empty function.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230803082619.1369127-7-arnd@kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>