ftrace: Fix BPF fexit with livepatch
JIRA: https://issues.redhat.com/browse/RHEL-14156

commit 56b3c85e153b84f27e6cff39623ba40a1ad299d3
Author: Song Liu <song@kernel.org>
Date:   Mon Oct 27 10:50:21 2025 -0700

    ftrace: Fix BPF fexit with livepatch

    When livepatch is attached to the same function as bpf trampoline with
    a fexit program, bpf trampoline code calls register_ftrace_direct()
    twice. The first time will fail with -EAGAIN, and the second time it
    will succeed. This requires register_ftrace_direct() to unregister
    the address on the first attempt. Otherwise, the bpf trampoline cannot
    attach. Here is an easy way to reproduce this issue:

      insmod samples/livepatch/livepatch-sample.ko
      bpftrace -e 'fexit:cmdline_proc_show {}'
      ERROR: Unable to attach probe: fexit:vmlinux:cmdline_proc_show...

    Fix this by cleaning up the hash when register_ftrace_function_nolock hits
    errors.

    Also, move the code that resets ops->func and ops->trampoline to the error
    path of register_ftrace_direct(); and add a helper function reset_direct()
    in register_ftrace_direct() and unregister_ftrace_direct().

    Fixes: d05cb470663a ("ftrace: Fix modification of direct_function hash while in use")
    Cc: stable@vger.kernel.org # v6.6+
    Reported-by: Andrey Grodzovsky <andrey.grodzovsky@crowdstrike.com>
    Closes: https://lore.kernel.org/live-patching/c5058315a39d4615b333e485893345be@crowdstrike.com/
    Cc: Steven Rostedt (Google) <rostedt@goodmis.org>
    Cc: Masami Hiramatsu (Google) <mhiramat@kernel.org>
    Acked-and-tested-by: Andrey Grodzovsky <andrey.grodzovsky@crowdstrike.com>
    Signed-off-by: Song Liu <song@kernel.org>
    Reviewed-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/r/20251027175023.1521602-2-song@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Steven Rostedt (Google) <rostedt@goodmis.org>

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>