USB: serial: quatech2: remove unused qt2_setdevice function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-526.el8
commit-author Tom Rix <trix@redhat.com>
commit 8c1b63b3c2358024181674e0ada901d50b919d3e

clang with W=1 reports
drivers/usb/serial/quatech2.c:179:19: error: unused function
  'qt2_setdevice' [-Werror,-Wunused-function]
static inline int qt2_setdevice(struct usb_device *dev, u8 *data)
                  ^
This function is not used, so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230321181255.1825963-1-trix@redhat.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 8c1b63b3c2358024181674e0ada901d50b919d3e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>