drm/bridge: ps8640: Fix size mismatch warning w/ len
JIRA: https://issues.redhat.com/browse/RHEL-1351
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.6.11)

commit 8b410abf172994205a0a4341a8cc0a1bc14c5a3d
Author:     Douglas Anderson <dianders@chromium.org>
AuthorDate: Mon Dec 18 09:04:54 2023 -0800
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Wed Jan 10 17:16:47 2024 +0100

    [ Upstream commit 35ba6bd582cf926a082296b7e9a876ec81136cb1 ]

    After commit 26195af57798 ("drm/bridge: ps8640: Drop the ability of
    ps8640 to fetch the EDID"), I got an error compiling:

      error: comparison of distinct pointer types
      ('typeof (len) *' (aka 'unsigned int *') and
       'typeof (msg->size) *' (aka 'unsigned long *'))
      [-Werror,-Wcompare-distinct-pointer-types]

    Fix it by declaring the `len` as size_t.

    The above error only shows up on downstream kernels without commit
    d03eba99f5bf ("minmax: allow min()/max()/clamp() if the arguments have
    the same signedness."), but since commit 26195af57798 ("drm/bridge:
    ps8640: Drop the ability of ps8640 to fetch the EDID") is a "Fix" that
    will likely be backported it seems nice to make it easy. ...plus it's
    more correct to declare `len` as size_t anyway.

    Fixes: 26195af57798 ("drm/bridge: ps8640: Drop the ability of ps8640 to fetch the EDID")
    Reviewed-by: Stephen Boyd <swboyd@chromium.org>
    Signed-off-by: Douglas Anderson <dianders@chromium.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20231218090454.1.I5c6eb80b2f746439c4b58efab788e00701d08759@changeid
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>