usb: xhci: add missing dma-mapping.h includes
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [usb] xhci: add missing dma-mapping.h includes (Don Zickus) [895641]
Rebuild_FUZZ: 94.12%
commit-author James Hogan <james.hogan@imgtec.com>
commit 008eb957dafea32bac993be5cbeaf4ca0ee8b0aa

A randconfig build hit the following build errors because xhci.c and
xhci-mem.c use dma mapping functions but don't include
<linux/dma-mapping.h>. Add the missing includes to fix the build errors.

drivers/usb/host/xhci.c In function 'xhci_gen_setup':
drivers/usb/host/xhci.c +4872 : error: implicit declaration of function 'dma_set_mask'
drivers/usb/host/xhci.c +4872 : error: implicit declaration of function 'DMA_BIT_MASK'

drivers/usb/host/xhci-mem.c In function 'xhci_free_stream_ctx':
drivers/usb/host/xhci-mem.c +435 : error: implicit declaration of function 'dma_free_coherent'
drivers/usb/host/xhci-mem.c In function 'xhci_alloc_stream_ctx':
drivers/usb/host/xhci-mem.c +463 : error: implicit declaration of function 'dma_alloc_coherent'

	Signed-off-by: James Hogan <james.hogan@imgtec.com>
	Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Cc: linux-usb@vger.kernel.org
	Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
(cherry picked from commit 008eb957dafea32bac993be5cbeaf4ca0ee8b0aa)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>