samples: bpf: Fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Matteo Croce <mcroce@redhat.com>
commit 23ad04669f81f958e9a4121b0266228d2eb3c357

GCC 10 is very strict about symbol clash, and lwt_len_hist_user contains
a symbol which clashes with libbpf:

/usr/bin/ld: samples/bpf/lwt_len_hist_user.o:(.bss+0x0): multiple definition of `bpf_log_buf'; samples/bpf/bpf_load.o:(.bss+0x8c0): first defined here
collect2: error: ld returned 1 exit status

bpf_log_buf here seems to be a leftover, so removing it.

	Signed-off-by: Matteo Croce <mcroce@redhat.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
	Acked-by: Yonghong Song <yhs@fb.com>
Link: https://lore.kernel.org/bpf/20200511113234.80722-1-mcroce@redhat.com
(cherry picked from commit 23ad04669f81f958e9a4121b0266228d2eb3c357)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>