HID: intel_ish-hid: fix potential uninitialized data usage
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [hid] intel_ish-hid: fix potential uninitialized data usage (Gopal Tiwari) [1475903]
Rebuild_FUZZ: 95.50%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 1260662fa3f293042fb0ae124c9a621f29f5bcab

gcc points out an uninialized pointer dereference that could happen
if we ever get to recv_ishtp_cl_msg_dma() or recv_ishtp_cl_msg()
with an empty &dev->read_list:

drivers/hid/intel-ish-hid/ishtp/client.c: In function 'recv_ishtp_cl_msg_dma':
drivers/hid/intel-ish-hid/ishtp/client.c:1049:3: error: 'cl' may be used uninitialized in this function [-Werror=maybe-uninitialized]

The warning only appeared in very few randconfig builds, as the
spinlocks tend to prevent gcc from tracing the variables. I only
saw it in configurations that had neither SMP nor LOCKDEP enabled.

As we can see, we only enter the case if 'complete_rb' is non-NULL,
and then 'cl' is known to point to complete_rb->cl. Adding another
initialization to the same pointer is harmless here and makes it
clear to the compiler that the behavior is well-defined.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
	Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit 1260662fa3f293042fb0ae124c9a621f29f5bcab)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>