perf config: Fix build with older toolchain.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [tools] perf config: Fix build with older toolchain (Jiri Olsa) [1373817]
Rebuild_FUZZ: 98.85%
commit-author Vinson Lee <vlee@freedesktop.org>
commit d8e28654f28de74951ab1b7e59d2bebb442972aa

Fix build error on Ubuntu 12.04.5 with GCC 4.6.3.

    CC       util/config.o
  util/config.c: In function ‘perf_buildid_config’:
  util/config.c:384:15: error: declaration of ‘dirname’ shadows a global declaration [-Werror=shadow]

	Signed-off-by: Vinson Lee <vlee@freedesktop.org>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Alexei Starovoitov <ast@plumgrid.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Josh Poimboeuf <jpoimboe@redhat.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Taeung Song <treeze.taeung@gmail.com>
	Cc: Wang Nan <wangnan0@huawei.com>
Fixes: 9cb5987c8227 ("perf config: Rework buildid_dir_command_config to perf_buildid_config")
Link: http://lkml.kernel.org/r/1459807659-9020-1-git-send-email-vlee@freedesktop.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit d8e28654f28de74951ab1b7e59d2bebb442972aa)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>