x86/paravirt: Fix a !PARAVIRT build warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2190342

commit dbf53a29b28b277fa952a000245b558536c6bdd7
Author: Borislav Petkov <bp@alien8.de>
Date:   Wed, 19 Oct 2022 18:59:45 +0200

    x86/paravirt: Fix a !PARAVIRT build warning

    Fix

      ./include/trace/events/xen.h:28:31: warning: ‘enum paravirt_lazy_mode’ \
        declared inside parameter list will not be visible outside of this definition or declaration

    which turns into a build error:

      ./include/trace/events/xen.h:28:50: error: parameter 1 (‘mode’) has incomplete type
         28 |                 TP_PROTO(enum paravirt_lazy_mode mode), \

    due to enum paravirt_lazy_mode being visible only under CONFIG_PARAVIRT.
    Just pull it up where it is unconditionally visible.

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lkml.kernel.org/r/Y1AtAXM8YjtBm2cj@zn.tnic

Signed-off-by: Waiman Long <longman@redhat.com>