perf evsel: Separate bpf_counter_list and bpf_filters, can be used at the same time
Bugzilla: https://bugzilla.redhat.com/2233483

upstream
========
commit c041d33bf7ec731bb71f47e4d45a7aec9e40b1b9
Author: Song Liu <song@kernel.org>
Date: Fri May 19 16:57:57 2023 -0700

description
===========
'struct evsel' uses a union for the two lists. This turned out to be
error prone.

For example:

  [root@quaco ~]# perf stat --bpf-prog 5246
  Error: cpu-clock event does not have sample flags 66c660
  failed to set filter "(null)" on event cpu-clock with 2 (No such file or directory)
  [root@quaco ~]# perf stat --bpf-prog 5246

Fix this issue by separating the two lists.

Fixes: 56ec9457a4a20c5e ("perf bpf filter: Implement event sample filtering")
    Signed-off-by: Song Liu <song@kernel.org>
    Acked-by: Namhyung Kim <namhyung@kernel.org>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: kernel-team@meta.com
    Link: https://lore.kernel.org/r/20230519235757.3613719-1-song@kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>