cfg80211: fix CFG80211_EXTRA_REGDB_KEYDIR typo
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 88230ef1f31bf2d8fcf42c20e5743ff4b3618a29
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/88230ef1.failed

The missing CONFIG_ prefix means this macro is never defined,
leading to a possible Kbuild warning:

net/wireless/reg.c:666:20: error: 'load_keys_from_buffer' defined but not used [-Werror=unused-function]
 static void __init load_keys_from_buffer(const u8 *p, unsigned int buflen)

When we use the correct symbol, the warning also goes away.

Fixes: 90a53e4432b1 ("cfg80211: implement regdb signature checking")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Johannes Berg <johannes.berg@intel.com>
(cherry picked from commit 88230ef1f31bf2d8fcf42c20e5743ff4b3618a29)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/wireless/reg.c