tpm: ftpm_tee: remove incorrect of_match_ptr annotation
JIRA: https://issues.redhat.com/browse/RHEL-72764

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit fb3bf46de6d9b00088965db6b3c56a6c18153c9f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 25 17:37:15 2025 +0100

    tpm: ftpm_tee: remove incorrect of_match_ptr annotation

    Building with W=1 shows a warning about of_ftpm_tee_ids being unused when
    CONFIG_OF is disabled:

        drivers/char/tpm/tpm_ftpm_tee.c:356:34: error: unused variable 'of_ftpm_tee_ids' [-Werror,-Wunused-const-variable]

    Drop the unnecessary of_match_ptr().

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Sumit Garg <sumit.garg@kernel.org>
    Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>

Signed-off-by: Štěpán Horáček <shoracek@redhat.com>