selftests/mm: fix guard-pages build
JIRA: https://issues.redhat.com/browse/RHEL-78135
Upstream Status: RHEL only

The tools/testing/selftests/mm/guard-pages.c build was br0ken in v6.13:

"""
guard-pages.c: In function ‘guard_pages_process_madvise’:
guard-pages.c:422:17: warning: implicit declaration of function ‘process_madvise’; did you mean ‘SYS_process_madvise’? [-Wimplicit-function-declaration]
  422 |         count = process_madvise(pidfd, vec, 6, MADV_GUARD_INSTALL, 0);
      |                 ^~~~~~~~~~~~~~~
      |                 SYS_process_madvise
/usr/bin/ld: /tmp/ccLfVeGh.o: in function `guard_pages_process_madvise':
guard-pages.c:(.text+0x5c54): undefined reference to `process_madvise'
/usr/bin/ld: guard-pages.c:(.text+0x629c): undefined reference to `process_madvise'
collect2: error: ld returned 1 exit status
make: *** [../lib.mk:222: /home/luizcap/src/linux/tools/testing/selftests/mm/guard-pages] Error 1
"""

This is fixed in upstream commit 19b65ffae985 ("selftests/mm: add fork
CoW guard page test"). Now, the problem is that that commit was merged
in v6.14-rc1 and it adds a new test too so I can't tell if the new test
is supported in v6.13. To be safe, do a partial backport of the build
fix only.

Signed-off-by: Luiz Capitulino <luizcap@redhat.com>