wifi: mt76: mt7915: fix an uninitialized variable bug
Bugzilla: https://bugzilla.redhat.com/2136124

commit b5ee771c84082b4e54cc39d9d9a2dd239e4f6b86
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Fri Jul 22 09:34:55 2022 +0300

    wifi: mt76: mt7915: fix an uninitialized variable bug
    
    Smatch complains that:
    
        drivers/net/wireless/mediatek/mt76/mt7915/mac.c:428 mt7915_mac_fill_rx()
        error: uninitialized symbol 'msta'.
    
    It looks like this was supposed to be initialized to NULL.
    
    Fixes: 0880d40871d1 ("mt76: connac: move mt76_connac2_reverse_frag0_hdr_trans in mt76-connac module")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>