tools/perf: Fix parallel-perf python script to replace new python syntax ":=" usage
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit 7d49ced808b169c8cb754da15a69ed0b2fb26567
Author: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
Date: Sun Jun 23 12:18:50 2024 +0530

description
===========
perf test "perf script tests" fails as below in systems
with python 3.6

	File "/home/athira/linux/tools/perf/tests/shell/../../scripts/python/parallel-perf.py", line 442
	if line := p.stdout.readline():
             ^
	SyntaxError: invalid syntax
	--- Cleaning up ---
	---- end(-1) ----
	92: perf script tests: FAILED!

This happens because ":=" is a new syntax that assigns values
to variables as part of a larger expression. This is introduced
from python 3.8 and hence fails in setup with python 3.6
Address this by splitting the large expression and check the
value in two steps:
Previous line: if line := p.stdout.readline():
Current change:
	line = p.stdout.readline()
	if line:

With patch

	./perf test "perf script tests"
	 93: perf script tests:  Ok

    Signed-off-by: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
    Acked-by: Adrian Hunter <adrian.hunter@intel.com>
    Cc: akanksha@linux.ibm.com
    Cc: kjain@linux.ibm.com
    Cc: maddy@linux.ibm.com
    Cc: disgoel@linux.vnet.ibm.com
    Cc: linuxppc-dev@lists.ozlabs.org
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>
    Link: https://lore.kernel.org/r/20240623064850.83720-3-atrajeev@linux.vnet.ibm.com

Signed-off-by: Michael Petlan <mpetlan@redhat.com>