scsi: qla2xxx: Remove unused variable 'status'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Bill Wendling <morbo@google.com>
commit cb51bcd5c34b0558ba2bb04963bcb1053375a8e4

Fix the clang build warning:

  drivers/scsi/qla2xxx/qla_nx.c:2209:6: error: variable 'status' set but not used [-Werror,-Wunused-but-set-variable]
        int status = 0;

Link: https://lore.kernel.org/r/20210726201924.3202278-4-morbo@google.com
	Reviewed-by: Nathan Chancellor <nathan@kernel.org>
	Signed-off-by: Bill Wendling <morbo@google.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit cb51bcd5c34b0558ba2bb04963bcb1053375a8e4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>