selftests/bpf: DENYLIST.aarch64: Skip fexit_sleep again
JIRA: https://issues.redhat.com/browse/RHEL-30774

commit 517125f6749402e579f715519147145944f12ad9
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Fri Jul 12 18:12:30 2024 +0200

    selftests/bpf: DENYLIST.aarch64: Skip fexit_sleep again
    
    Revert commit 90dc946059b7 ("selftests/bpf: DENYLIST.aarch64: Remove
    fexit_sleep") again. The fix in 19d3c179a377 ("bpf, arm64: Fix trampoline
    for BPF_TRAMP_F_CALL_ORIG") does not address all of the issues and BPF
    CI is still hanging and timing out:
    
       https://github.com/kernel-patches/bpf/actions/runs/9905842936/job/27366435436
    
       [...]
       #89/11   fexit_bpf2bpf/func_replace_global_func:OK
       #89/12   fexit_bpf2bpf/fentry_to_cgroup_bpf:OK
       #89/13   fexit_bpf2bpf/func_replace_progmap:OK
       #89      fexit_bpf2bpf:OK
       Error: The operation was canceled.
    
    Thus more investigation work & fixing is needed before the test can be put
    in place again.
    
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Cc: Puranjay Mohan <puranjay@kernel.org>
    Link: https://lore.kernel.org/bpf/20240705145009.32340-1-puranjay@kernel.org

Signed-off-by: Viktor Malik <vmalik@redhat.com>