objtool: Print bfd_vma as unsigned long long on ia32-x86_64 cross build
JIRA: https://redhat.atlassian.net/browse/RHEL-152189

commit fd4eeb30b9e30ca1118a618be0755287bcbb2da9
Author: Dmitry Safonov <0x7f454c46@gmail.com>
Date:   Mon Jan 26 04:57:35 2026 +0000

    objtool: Print bfd_vma as unsigned long long on ia32-x86_64 cross build

    When objtool is cross-compiled in ia32 container for x86_64 target it
    fails with the following errors:

    > disas.c: In function 'disas_print_addr_sym':
    > disas.c:173:38: error: format '%lx' expects argument of type 'long unsigned int', but argument 3 has type 'bfd_vma' {aka 'long long unsigned int'} [-Werror=format=]
    >   173 |                 DINFO_FPRINTF(dinfo, "0x%lx <%s>", addr, symstr);
    >       |                                      ^~~~~~~~~~~~  ~~~~
    >       |                                                    |
    >       |                                                    bfd_vma {aka long long unsigned int}

    Provide a correct printf-fmt depending on sizeof(bfd_vma).

    Fixes: 5d859dff266f ("objtool: Print symbol during disassembly")
    Signed-off-by: Dmitry Safonov <dima@arista.com>
    Reviewed-by: Alexandre Chartre <alexandre.chartre@oracle.com>
    Link: https://patch.msgid.link/20260126-objtool-ia32-v1-1-bb6feaf17566@arista.com
    Signed-off-by: Josh Poimboeuf <jpoimboe@kernel.org>

Signed-off-by: Yannick Cote <ycote@redhat.com>