ASoC: loongson: Fix build warning when !CONFIG_PCI
JIRA: https://issues.redhat.com/browse/RHEL-80676

commit 45b3605089b41b81ba36b231fbb97e3037a51beb
Author: Binbin Zhou <zhoubinbin@loongson.cn>
Date: Sat Oct 12 17:58:40 2024 +0800

    ASoC: loongson: Fix build warning when !CONFIG_PCI

    Fixes the below if kernel config disable PCI support:

    sound/soc/loongson/loongson_i2s_pci.c:157:1: warning: data definition has no type or storage class
         157 | module_pci_driver(loongson_i2s_driver);
             | ^~~~~~~~~~~~~~~~~
    sound/soc/loongson/loongson_i2s_pci.c:157:1: error: type defaults to 'int' in declaration of 'module_pci_driver' [-Wimplicit-int]
    sound/soc/loongson/loongson_i2s_pci.c:157:1: error: parameter names (without types) in function declaration [-Wdeclaration-missing-parameter-type]
    sound/soc/loongson/loongson_i2s_pci.c:149:26: warning: 'loongson_i2s_driver' defined but not used [-Wunused-variable]
         149 | static struct pci_driver loongson_i2s_driver = {
             |                          ^~~~~~~~~~~~~~~~~~~

    Add the appropriate Kconfig dependency.

    Fixes: ba4c5fad598c ("ASoC: loongson: Add I2S controller driver as platform device")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202410101647.o1lI37ou-lkp@intel.com/
    Closes: https://lore.kernel.org/oe-kbuild-all/202410101439.Tfn5aT6i-lkp@intel.com/
    Signed-off-by: Binbin Zhou <zhoubinbin@loongson.cn>
    Link: https://patch.msgid.link/20241012095840.965087-1-zhoubinbin@loongson.cn
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>