net: bridge: add support for host l2 mdb entries
Bugzilla: https://bugzilla.redhat.com/2184372

commit e65693b0179ebb1e58134e048b31781709380232
Author: Joachim Wiberg <troglobit@gmail.com>
Date:   Mon Apr 11 10:40:53 2022 +0200

    net: bridge: add support for host l2 mdb entries
    
    This patch expands on the earlier work on layer-2 mdb entries by adding
    support for host entries.  Due to the fact that host joined entries do
    not have any flag field, we infer the permanent flag when reporting the
    entries to userspace, which otherwise would be listed as 'temp'.
    
    Before patch:
    
        ~# bridge mdb add dev br0 port br0 grp 01:00:00:c0:ff:ee permanent
        Error: bridge: Flags are not allowed for host groups.
        ~# bridge mdb add dev br0 port br0 grp 01:00:00:c0:ff:ee
        Error: bridge: Only permanent L2 entries allowed.
    
    After patch:
    
        ~# bridge mdb add dev br0 port br0 grp 01:00:00:c0:ff:ee permanent
        ~# bridge mdb show
        dev br0 port br0 grp 01:00:00:c0:ff:ee permanent vid 1
    
    Signed-off-by: Joachim Wiberg <troglobit@gmail.com>
    Acked-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>