kselftest/vm: fix tests build with old libc
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-542.el8
commit-author Chengming Zhou <zhouchengming@bytedance.com>
commit b773827e361952b3f53ac6fa4c4e39ccd632102e

The error message when I build vm tests on debian10 (GLIBC 2.28):

    userfaultfd.c: In function `userfaultfd_pagemap_test':
    userfaultfd.c:1393:37: error: `MADV_PAGEOUT' undeclared (first use
    in this function); did you mean `MADV_RANDOM'?
      if (madvise(area_dst, test_pgsize, MADV_PAGEOUT))
                                         ^~~~~~~~~~~~
                                         MADV_RANDOM

This patch includes these newer definitions from UAPI linux/mman.h, is
useful to fix tests build on systems without these definitions in glibc
sys/mman.h.

Link: https://lkml.kernel.org/r/20220227055330.43087-2-zhouchengming@bytedance.com
	Signed-off-by: Chengming Zhou <zhouchengming@bytedance.com>
	Reviewed-by: Shuah Khan <skhan@linuxfoundation.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit b773827e361952b3f53ac6fa4c4e39ccd632102e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>