ASoC: rt1015: add missing header inclusion
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: rt1015: add missing header inclusion (Jaroslav Kysela) [1869536]
Rebuild_FUZZ: 93.33%
commit-author Tzung-Bi Shih <tzungbi@google.com>
commit 72ac4a4bef48e67bb26bc5a01d68c8163def013d

To fix compilation error:

error: implicit declaration of function 'ACPI_PTR'
[-Werror,-Wimplicit-function-declaration]
                .acpi_match_table = ACPI_PTR(rt1015_acpi_match),
		                    ^

Adds the missing header "acpi.h" inclusion and sorts in alphabetical.

	Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-4-tzungbi@google.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 72ac4a4bef48e67bb26bc5a01d68c8163def013d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>