ASoC: cs42l43: convert to SYSTEM_SLEEP_PM_OPS
JIRA: https://issues.redhat.com/browse/RHEL-80677

commit 658fb7fe8e7f4014ea17a4da0e0c1d9bc319fa35
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Mar 5 18:27:32 2025 +0100

    ASoC: cs42l43: convert to SYSTEM_SLEEP_PM_OPS

    The custom suspend function causes a build warning when CONFIG_PM_SLEEP
    is disabled:

    sound/soc/codecs/cs42l43.c:2405:12: error: unused function 'cs42l43_codec_runtime_force_suspend' [-Werror,-Wunused-function]

    Change SET_SYSTEM_SLEEP_PM_OPS() to the newer SYSTEM_SLEEP_PM_OPS(),
    to avoid this.

    Fixes: 164b7dd4546b ("ASoC: cs42l43: Add jack delay debounce after suspend")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Maciej Strozek <mstrozek@opensource.cirrus.com>
    Reviewed-by: Charles Keepax <ckeepax@opensource.cirrus.com>
    Link: https://patch.msgid.link/20250305172738.3437513-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>