bpf: Include linux/types.h for u32
JIRA: https://issues.redhat.com/browse/RHEL-30773

commit cfd3bfe9507b4aa39f7e86772e60b50b799e490e
Author: Dmitrii Bundin <dmitrii.bundin.a@gmail.com>
Date:   Sat Apr 20 07:24:57 2024 +0300

    bpf: Include linux/types.h for u32
    
    Inclusion of the header linux/btf_ids.h relies on indirect inclusion of
    the header linux/types.h. Including it directly on the top level helps
    to avoid potential problems if linux/types.h hasn't been included
    before.
    
    The main motivation to introduce this it is to avoid similar problems that
    have shown up in the bpftool where GNU libc indirectly pulls
    linux/types.h causing compile error of the form:
    
       error: unknown type name 'u32'
                                 u32 cnt;
                                 ^~~
    
    The bpftool compile error was fixed in
    62248b22d01e ("tools/resolve_btfids: fix build with musl libc").
    
    Signed-off-by: Dmitrii Bundin <dmitrii.bundin.a@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20240420042457.3198883-1-dmitrii.bundin.a@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>