perf tools: Fix a build error on arm64 with clang
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit a00b7e39d6b56e6f49cdd51a9ebf92627a19d877

Since clang's -Wmissing-field-initializers warns if a data
structure is initialized with a signle NULL as below,

 ----
 tools/perf $ make CC=clang LLVM=1
 ...
 arch/arm64/util/kvm-stat.c:74:9: error: missing field 'ops' initializer [-Werror,-Wmissing-field-initializers]
         { NULL },
                ^
 1 error generated.
 ----

add another field initializer expressly as same as other
arch's kvm-stat.c code.

	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Cc: Anders Roxell <anders.roxell@linaro.org>
	Cc: Leo Yan <leo.yan@linaro.org>
	Cc: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Link: http://lore.kernel.org/lkml/162037767540.94840.15758657049033010518.stgit@devnote2
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit a00b7e39d6b56e6f49cdd51a9ebf92627a19d877)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>