ata: ahci_xgene: Fix compilation warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2162218

When compiling with clang and W=1, the following warning is generated:

drivers/ata/ahci_xgene.c:788:14: error: cast to smaller integer type
'enum xgene_ahci_version' from 'const void *'
[-Werror,-Wvoid-pointer-to-enum-cast]
       version = (enum xgene_ahci_version) of_devid->data;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by using a cast to unsigned long to match the "void *" type
size of of_devid->data.

Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Acked-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit e8fbdf1855f7f31a8f37df60d7be44d8aabe6288)
Signed-off-by: Tomas Henzl <thenzl@redhat.com>