usb: gadget: avoid unusual inline assembly
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit e27bea459d5eaa485ba091e0e051bf4575614d4f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 14:38:20 2021 +0200

    usb: gadget: avoid unusual inline assembly

    clang does not understand the "mrc%?" syntax:

    drivers/usb/gadget/udc/pxa25x_udc.c:2330:11: error: invalid % escape in inline assembly string

    I don't understand it either, but removing the %? here gets it to build.
    This is probably wrong and someone else should do a proper patch.

    Any suggestions?

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20210927123830.1278953-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>