net: wwan: iosm: fix dma_alloc_coherent incompatible pointer type
Bugzilla: https://bugzilla.redhat.com/2123542

commit 4a99e3c8ed888577b947cbed97d88c9706896105
Author: M Chetan Kumar <m.chetan.kumar@linux.intel.com>
Date:   Thu Nov 24 16:08:03 2022 +0530

    net: wwan: iosm: fix dma_alloc_coherent incompatible pointer type
    
    Fix build error reported on armhf while preparing 6.1-rc5
    for Debian.
    
    iosm_ipc_protocol.c:244:36: error: passing argument 3 of
    'dma_alloc_coherent' from incompatible pointer type.
    
    Change phy_ap_shm type from phys_addr_t to dma_addr_t.
    
    Fixes: faed4c6f6f48 ("net: iosm: shared memory protocol")
    Reported-by: Bonaccorso Salvatore <carnil@debian.org>
    Signed-off-by: M Chetan Kumar <m.chetan.kumar@linux.intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>