soc: a64fx-diag: disable modular build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-502.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit f740949d41a7ff85aa23ce62c29d095066e5e6d4

The NMI infrastructure cannot currently be used in loadable modules:

ERROR: modpost: "free_nmi" [drivers/soc/fujitsu/a64fx-diag.ko] undefined!
ERROR: modpost: "request_nmi" [drivers/soc/fujitsu/a64fx-diag.ko] undefined!
ERROR: modpost: "enable_nmi" [drivers/soc/fujitsu/a64fx-diag.ko] undefined!

Disable this for now to make allmodconfig build again. We may revisit
this and export those symbols instead in the future.

	Reported-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit f740949d41a7ff85aa23ce62c29d095066e5e6d4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>