drm/display: Fix building with GCC 15
JIRA: https://issues.redhat.com/browse/RHEL-53571
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.12.5)

commit 07a4acea17f53f5c47fff3cce5aede962f969435
Author:     Brahmajit Das <brahmajit.xyz@gmail.com>
AuthorDate: Wed Oct  2 14:53:11 2024 +0530
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Sat Dec 14 20:03:45 2024 +0100

    [ Upstream commit a500f3751d3c861be7e4463c933cf467240cca5d ]

    GCC 15 enables -Werror=unterminated-string-initialization by default.
    This results in the following build error

    drivers/gpu/drm/display/drm_dp_dual_mode_helper.c: In function ‘is_hdmi_adaptor’:
    drivers/gpu/drm/display/drm_dp_dual_mode_helper.c:164:17: error: initializer-string for array of
     ‘char’ is too long [-Werror=unterminated-string-initialization]
      164 |                 "DP-HDMI ADAPTOR\x04";
          |                 ^~~~~~~~~~~~~~~~~~~~~

    After discussion with Ville, the fix was to increase the size of
    dp_dual_mode_hdmi_id array by one, so that it can accommodate the NULL
    line character. This should let us build the kernel with GCC 15.

    Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>
    Reviewed-by: Jani Nikula <jani.nikula@intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241002092311.942822-1-brahmajit.xyz@gmail.com
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>