x86/efi: Remove EFI PGD build time checks
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Borislav Petkov <bp@suse.de>
commit 816ef8d7a2c4182e19bc06ab65751cb9e3951e94

With CONFIG_X86_5LEVEL, CONFIG_UBSAN and CONFIG_UBSAN_UNSIGNED_OVERFLOW
enabled, clang fails the build with

  x86_64-linux-ld: arch/x86/platform/efi/efi_64.o: in function `efi_sync_low_kernel_mappings':
  efi_64.c:(.text+0x22c): undefined reference to `__compiletime_assert_354'

which happens due to -fsanitize=unsigned-integer-overflow being enabled:

  -fsanitize=unsigned-integer-overflow: Unsigned integer overflow, where
  the result of an unsigned integer computation cannot be represented
  in its type. Unlike signed integer overflow, this is not undefined
  behavior, but it is often unintentional. This sanitizer does not check
  for lossy implicit conversions performed before such a computation
  (see -fsanitize=implicit-conversion).

and that fires when the (intentional) EFI_VA_START/END defines overflow
an unsigned long, leading to the assertion expressions not getting
optimized away (on GCC they do)...

However, those checks are superfluous: the runtime services mapping
code already makes sure the ranges don't overshoot EFI_VA_END as the
EFI mapping range is hardcoded. On each runtime services call, it is
switched to the EFI-specific PGD and even if mappings manage to escape
that last PGD, this won't remain unnoticed for long.

So rip them out.

See https://github.com/ClangBuiltLinux/linux/issues/256 for more info.

	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Borislav Petkov <bp@suse.de>
	Reviewed-by: Nathan Chancellor <nathan@kernel.org>
	Acked-by: Ard Biesheuvel <ardb@kernel.org>
	Tested-by: Nick Desaulniers <ndesaulniers@google.com>
	Tested-by: Nathan Chancellor <nathan@kernel.org>
Link: http://lkml.kernel.org/r/20210107223424.4135538-1-arnd@kernel.org
(cherry picked from commit 816ef8d7a2c4182e19bc06ab65751cb9e3951e94)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>