modpost: check static EXPORT_SYMBOL* by modpost again
JIRA: https://issues.redhat.com/browse/RHEL-28063

Conflicts:
	- Only backport the scripts/mod/modpost.c portion as cs-9 never
	  backported the aborted check_local_export approach.

commit 6d62b1c46b1e6e1686a0cf6617c96c80d4ab5cd5
Author: Masahiro Yamada <masahiroy@kernel.org>
Date:   Mon Jun 12 00:50:54 2023 +0900

    modpost: check static EXPORT_SYMBOL* by modpost again

    Commit 31cb50b5590f ("kbuild: check static EXPORT_SYMBOL* by script
    instead of modpost") moved the static EXPORT_SYMBOL* check from the
    mostpost to a shell script because I thought it must be checked per
    compilation unit to avoid false negatives.

    I came up with an idea to do this in modpost, against combined ELF
    files. The relocation entries in ELF will find the correct exported
    symbol even if there exist symbols with the same name in different
    compilation units.

    Again, the same sample code.

      Makefile:

        obj-y += foo1.o foo2.o

      foo1.c:

        #include <linux/export.h>
        static void foo(void) {}
        EXPORT_SYMBOL(foo);

      foo2.c:

        void foo(void) {}

    Then, modpost can catch it correctly.

        MODPOST Module.symvers
      ERROR: modpost: vmlinux: local symbol 'foo' was exported

    Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>