perf genelf: Fix NO_LIBDW=1 build
JIRA: https://issues.redhat.com/browse/RHEL-78200

upstream
========
commit d4ae1620c6209661ced9244d058f3582d1847dca
Author: Ian Rogers <irogers@google.com>
Date: Wed Jul 2 10:54:02 2025 -0700

description
===========
With NO_LIBDW=1 a new unused-parameter warning/error has appeared:
```
util/genelf.c: In function ‘jit_write_elf’:
util/genelf.c:163:32: error: unused parameter ‘load_addr’ [-Werror=unused-parameter]
  163 | jit_write_elf(int fd, uint64_t load_addr, const char *sym,
```

Fixes: e3f612c1d8f3 ("perf genelf: Remove libcrypto dependency and use built-in sha1()")
    Signed-off-by: Ian Rogers <irogers@google.com>
    Tested-by: Namhyung Kim <namhyung@kernel.org>
    Link: https://lore.kernel.org/r/20250702175402.761818-1-irogers@google.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Anubhav Shelat <ashelat@redhat.com>