security: commoncap: fix -Wstringop-overread warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 82e5d8cc768b0c7b03c551a9ab1f8f3f68d5f83f

gcc-11 introdces a harmless warning for cap_inode_getsecurity:

security/commoncap.c: In function ‘cap_inode_getsecurity’:
security/commoncap.c:440:33: error: ‘memcpy’ reading 16 bytes from a region of size 0 [-Werror=stringop-overread]
  440 |                                 memcpy(&nscap->data, &cap->data, sizeof(__le32) * 2 * VFS_CAP_U32);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The problem here is that tmpbuf is initialized to NULL, so gcc assumes
it is not accessible unless it gets set by vfs_getxattr_alloc().  This is
a legitimate warning as far as I can tell, but the code is correct since
it correctly handles the error when that function fails.

Add a separate NULL check to tell gcc about it as well.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Christian Brauner <christian.brauner@ubuntu.com>
	Signed-off-by: James Morris <jamorris@linux.microsoft.com>
(cherry picked from commit 82e5d8cc768b0c7b03c551a9ab1f8f3f68d5f83f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>