mm/zswap.c: remove unnecessary parentheses
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [mm] zswap: remove unnecessary parentheses (Seth Jennings) [1141434]
Rebuild_FUZZ: 93.67%
commit-author SeongJae Park <sj38.park@gmail.com>
commit 5d2d42de185b77b4bc60b5ac77386c4099d71bf3

Fix following trivial checkpatch error:

  ERROR: return is not a function, parentheses are not required

	Signed-off-by: SeongJae Park <sj38.park@gmail.com>
	Acked-by: Seth Jennings <sjennings@variantweb.net>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 5d2d42de185b77b4bc60b5ac77386c4099d71bf3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>