objtool: Fix calloc call for new -Walloc-size
JIRA: https://issues.redhat.com/browse/RHEL-114921

commit e2e13630f93d942d02f3b3f98660228a3545c60e
Author: Sam James <sam@gentoo.org>
Date:   Tue Nov 7 20:55:00 2023 +0000

    objtool: Fix calloc call for new -Walloc-size

    GCC 14 introduces a new -Walloc-size included in -Wextra which errors out
    like:
    ```
    check.c: In function ‘cfi_alloc’:
    check.c:294:33: error: allocation of insufficient size ‘1’ for type ‘struct cfi_state’ with size ‘320’ [-Werror=alloc-size]
      294 |         struct cfi_state *cfi = calloc(sizeof(struct cfi_state), 1);
          |                                 ^~~~~~
    ```

    The calloc prototype is:
    ```
    void *calloc(size_t nmemb, size_t size);
    ```

    So, just swap the number of members and size arguments to match the prototype, as
    we're initialising 1 struct of size `sizeof(struct ...)`. GCC then sees we're not
    doing anything wrong.

    Signed-off-by: Sam James <sam@gentoo.org>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Josh Poimboeuf <jpoimboe@kernel.org>
    Link: https://lore.kernel.org/r/20231107205504.1470006-1-sam@gentoo.org

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>