ASoC: Intel: bytcr_wm5102: remove unused static variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 45468f2cfe9679eaeb7b7371b880548c5b74bede

make W=1 warning:

sound/soc/intel/boards/bytcr_wm5102.c:216:40: error:
‘byt_wm5102_dai_params’ defined but not used
[-Werror=unused-const-variable=]
  216 | static const struct snd_soc_pcm_stream byt_wm5102_dai_params = {
      |                                        ^~~~~~~~~~~~~~~~~~~~~

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20210302205926.49063-9-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 45468f2cfe9679eaeb7b7371b880548c5b74bede)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>