openvswitch: fix a compilation error when CONFIG_INET is not setW!
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [net] openvswitch: fix a compilation error when CONFIG_INET is not set (Jiri Benc) [1156461 1211348]
Rebuild_FUZZ: 98.46%
commit-author Andy Zhou <azhou@nicira.com>
commit 7c5df8fa1921450d2210db9928f43cf4f414982c

Fix a openvswitch compilation error when CONFIG_INET is not set:

=====================================================
   In file included from include/net/geneve.h:4:0,
                       from net/openvswitch/flow_netlink.c:45:
		          include/net/udp_tunnel.h: In function 'udp_tunnel_handle_offloads':
			  >> include/net/udp_tunnel.h:100:2: error: implicit declaration of function 'iptunnel_handle_offloads' [-Werror=implicit-function-declaration]
			  >>      return iptunnel_handle_offloads(skb, udp_csum, type);
			  >>           ^
			  >>           >> include/net/udp_tunnel.h:100:2: warning: return makes pointer from integer without a cast
			  >>           >>    cc1: some warnings being treated as errors

=====================================================

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Andy Zhou <azhou@nicira.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 7c5df8fa1921450d2210db9928f43cf4f414982c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>