PM: hibernate: Add stub for pm_hibernate_is_recovering()
JIRA: https://issues.redhat.com/browse/RHEL-113576

commit a6cfa4c8833944f8912c1fa7f95795753f6376ea
Author: Mario Limonciello <mario.limonciello@amd.com>
Date:   Sat Jul 12 18:37:12 2025 -0500

    PM: hibernate: Add stub for pm_hibernate_is_recovering()

    Randy reports that amdgpu fails to compile with the following error:
    ERROR: modpost: "pm_hibernate_is_recovering" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!

    This happens because pm_hibernate_is_recovering() is only compiled when
    CONFIG_PM_SLEEP is set.  Add a stub for it so that drivers don't need
    to depend upon CONFIG_PM.

    Cc: Samuel Zhang <guoqing.zhang@amd.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Closes: https://lore.kernel.org/dri-devel/CAJZ5v0h1CX+aTu7dFy6vB-9LM6t5J4rt7Su3qVnq1xx-BFAm=Q@mail.gmail.com/T/#m2b9fe212b35fde11d58fcbc4e0727bc02ebba7b0
    Fixes: c2aaddbd2dede ("PM: hibernate: add new api pm_hibernate_is_recovering()")
    Acked-by: Rafael J. Wysocki <rafael@kernel.org>
    Reviewed-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org>
    Link: https://lore.kernel.org/r/20250712233715.821424-1-superm1@kernel.org
    Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>

Signed-off-by: José Expósito <jexposit@redhat.com>