perf probe: Warn if given uprobe event accesses memory on older kernel
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Warn if given uprobe event accesses memory on older kernel (Jiri Olsa) [1222189]
Rebuild_FUZZ: 96.30%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 79702f614187f652a814061e8f5875ddcc9e732d

Warn if given uprobe event accesses memory on older kernel.

Until 3.14, uprobe event only supports accessing registers so this warns
to upgrade kernel if uprobe-event returns -EINVAL and an argument of the
event accesses memory ($stack, @+offset, and +|-offs() symtax).

With this patch (on 3.10.0-123.13.2.el7.x86_64);
  -----
  # ./perf probe -x ./perf warn_uprobe_event_compat stack=-0\(%sp\)
  Added new event:
  Failed to write event: Invalid argument
  Please upgrade your kernel to at least 3.14 to have access to feature -0(%sp)
    Error: Failed to add events.
  -----

	Suggested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
Link: http://lkml.kernel.org/r/20150228025329.32106.70581.stgit@localhost.localdomain
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 79702f614187f652a814061e8f5875ddcc9e732d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>