spi: falcon: mark falcon_sflash_xfer() as static
JIRA: https://issues.redhat.com/browse/RHEL-104570

commit 5fc2c383125c2b4b6037e02ad8796b776b25e6d0
Author: Shiji Yang <yangshiji66@outlook.com>
Date:   Wed Jun 18 22:53:29 2025 +0800

    spi: falcon: mark falcon_sflash_xfer() as static

    Fix the following missing-prototypes build warning:

    drivers/spi/spi-falcon.c:97:5: error: no previous prototype for 'falcon_sflash_xfer' [-Werror=missing-prototypes]
       97 | int falcon_sflash_xfer(struct spi_device *spi, struct spi_transfer *t,
          |     ^~~~~~~~~~~~~~~~~~

    Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
    Link: https://patch.msgid.link/OSBPR01MB16705BE87E549B6210CD6BCABC72A@OSBPR01MB1670.jpnprd01.prod.outlook.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Mattijs Korpershoek <mkorpershoek@redhat.com>