arm64: fix clang warning about TRAMP_VALIAS
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070169

commit 7f34b43e07cb512b28543fdcb9f35d1fbfda9ebc
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 16 Mar 2022 19:38:18 +0100

    The newly introduced TRAMP_VALIAS definition causes a build warning
    with clang-14:

    arch/arm64/include/asm/vectors.h:66:31: error: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Werror,-Wnull-pointer-arithmetic]
                    return (char *)TRAMP_VALIAS + SZ_2K * slot;

    Change the addition to something clang does not complain about.

    Fixes: bd09128d16fa ("arm64: Add percpu vectors for EL1")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: James Morse <james.morse@arm.com>
    Link: https://lore.kernel.org/r/20220316183833.1563139-1-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>