ALSA: hda/tegra - Fix build error and warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [alsa] hda/tegra - Fix build error and warning (Jaroslav Kysela) [1197064]
Rebuild_FUZZ: 92.86%
commit-author Takashi Iwai <tiwai@suse.de>
commit 4cfe99c7f9592573e85a9768cfb2a8d7a7962618
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/4cfe99c7.failed

I seem to have failed to run the build test properly...
   sound/pci/hda/hda_tegra.c: In function 'hda_tegra_dev_free':
   sound/pci/hda/hda_tegra.c:310:20: error: 'bus' undeclared (first use in this function)
         snd_hdac_bus_exit(bus);

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 4cfe99c7f9592573e85a9768cfb2a8d7a7962618)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	sound/pci/hda/hda_tegra.c