iommu/amd: Fix compilation error
JIRA: https://issues.redhat.com/browse/RHEL-28780
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/joro/iommu.git
            branch: next

commit bbe1e78ae23e7e474401880d0d496acc8cec6863
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Apr 29 14:17:07 2024 +0300

    iommu/amd: Fix compilation error

    With WERROR=y, which is default, clang is not happy:

    .../amd/pasid.c:168:3: error: call to undeclared function 'mmu_notifier_unregister'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    .../amd/pasid.c:191:8: error: call to undeclared function 'mmu_notifier_register'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    2 errors generated.

    Select missed dependency.

    Fixes: a5a91e54846d ("iommu/amd: Add SVA domain support")
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Link: https://lore.kernel.org/r/20240429111707.2795194-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit bbe1e78ae23e7e474401880d0d496acc8cec6863)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>