vfio: unhide vdev->debug_root
JIRA: https://issues.redhat.com/browse/RHEL-149504

commit 555aa178f8d22261d71da74df6267e6e6e97f95a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Mar 27 17:55:08 2026 +0100

    vfio: unhide vdev->debug_root

    When debugfs is disabled, the hisilicon driver now fails to build:

    drivers/vfio/pci/hisilicon/hisi_acc_vfio_pci.c: In function 'hisi_acc_vfio_debug_init':
    drivers/vfio/pci/hisilicon/hisi_acc_vfio_pci.c:1671:62: error: 'struct vfio_device' has no member named 'debug_root'
     1671 |         vfio_dev_migration = debugfs_lookup("migration", vdev->debug_root);
          |                                                              ^~

    The driver otherwise relies on dead-code elimination, but this reference
    fails. The single struct member is not going to make much of a difference
    for memory consumption, so just keep this visible unconditionally.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: b398f91779b8 ("hisi_acc_vfio_pci: register debugfs for hisilicon migration driver")
    Link: https://lore.kernel.org/r/20260327165521.3779707-1-arnd@kernel.org
    Signed-off-by: Alex Williamson <alex@shazbot.org>

Signed-off-by: Cédric Le Goater <clg@redhat.com>