perf stat: Avoid segfaults caused by negated options
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Michael Petlan <mpetlan@redhat.com>
commit 51433ead1460fb3f46e1c34f68bb22fd2dd0f5d0

Some 'perf stat' options do not make sense to be negated (event,
cgroup), some do not have negated path implemented (metrics). Due to
that, it is better to disable the "no-" prefix for them, since
otherwise, the later opt-parsing segfaults.

Before:

  $ perf stat --no-metrics -- ls
  Segmentation fault (core dumped)

After:

  $ perf stat --no-metrics -- ls
   Error: option `no-metrics' isn't available
   Usage: perf stat [<options>] [<command>]

	Signed-off-by: Michael Petlan <mpetlan@redhat.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
LPU-Reference: 1485912065.62416880.1544457604340.JavaMail.zimbra@redhat.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 51433ead1460fb3f46e1c34f68bb22fd2dd0f5d0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>