perf probe: Improve error message when %return is on inlined function
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [tools] perf probe: Improve error message when return is on inlined function (Jiri Olsa) [1308570]
Rebuild_FUZZ: 99.27%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 6cca13bdf5a5d561a855259689874e0c7266eec3

perf probe shows more precisely message when it finds given
%return target function is inlined.

Without this fix:
  ----
  # ./perf probe -V getname_flags%return
  Return probe must be on the head of a real function.
  Debuginfo analysis failed.
    Error: Failed to show vars.
  ----

With this fix:
  ----
  # ./perf probe -V getname_flags%return
  Failed to find "getname_flags%return",
   because getname_flags is an inlined function and has no return point.
  Debuginfo analysis failed.
    Error: Failed to show vars.
  ----

	Suggested-by: Arnaldo Carvalho de Melo <acme@kernel.org>
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/r/20150930164137.3733.55055.stgit@localhost.localdomain
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 6cca13bdf5a5d561a855259689874e0c7266eec3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>