powerpc/pseries: plpks: export plpks_wrapping_is_supported
JIRA: https://issues.redhat.com/browse/RHEL-191904

commit e2071f9ce42b6985a40feaf98d2f5f7ce0fca006
Author: Srish Srinivasan <ssrish@linux.ibm.com>
Date:   Sun Feb 1 22:23:44 2026 +0530

    powerpc/pseries: plpks: export plpks_wrapping_is_supported

    Building trusted-keys as a module fails modpost with:

    ERROR: modpost: "plpks_wrapping_is_supported" [security/keys/trusted-keys/
    trusted.ko] undefined!

    Export plpks_wrapping_is_supported() so trusted-keys links cleanly

    This patch is intended to be applied on top of the earlier "Extend "trusted
    " keys to support a new trust source named the PowerVM Key Wrapping Module
    (PKWM)" series (v5).
    Link: https://lore.kernel.org/all/20260127145228.48320-1-ssrish@linux.ibm.com/

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202602010724.1g9hbLKv-lkp@intel.com/
    Signed-off-by: Srish Srinivasan <ssrish@linux.ibm.com>
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://patch.msgid.link/20260201165344.950870-1-ssrish@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>