ext4: mark ctx_*_flags() with __maybe_unused
JIRA: https://issues.redhat.com/browse/RHEL-85400

commit 667de03a3b5eab4ccf532c6e399fe3488a1db58b
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Thu Sep 5 19:32:29 2024 +0300

    ext4: mark ctx_*_flags() with __maybe_unused

    When ctx_set_flags() is unused, it prevents kernel builds
    with clang, `make W=1` and CONFIG_WERROR=y:

    .../ext4/super.c:2120:1: error: unused function 'ctx_set_flags' [-Werror,-Wunused-function]
     2120 | EXT4_SET_CTX(flags); /* set only */
          | ^~~~~~~~~~~~~~~~~~~

    Fix this by marking ctx_*_flags() with __maybe_unused
    (mark both for the sake of symmetry).

    See also commit 6863f5643dd7 ("kbuild: allow Clang to find unused static
    inline functions for W=1 build").

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Link: https://patch.msgid.link/20240905163229.140522-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Theodore Ts'o <tytso@mit.edu>

Signed-off-by: Brian Foster <bfoster@redhat.com>