cgroup: Fix compilation issue due to cgroup_mutex not being exported
JIRA: https://issues.redhat.com/browse/RHEL-113305

commit 87c259a7a359e73e6c52c68fcbec79988999b4e6
Author: gaoxu <gaoxu2@honor.com>
Date:   Thu, 17 Apr 2025 07:30:00 +0000

    cgroup: Fix compilation issue due to cgroup_mutex not being exported

    When adding folio_memcg function call in the zram module for
    Android16-6.12, the following error occurs during compilation:
    ERROR: modpost: "cgroup_mutex" [../soc-repo/zram.ko] undefined!

    This error is caused by the indirect call to lockdep_is_held(&cgroup_mutex)
    within folio_memcg. The export setting for cgroup_mutex is controlled by
    the CONFIG_PROVE_RCU macro. If CONFIG_LOCKDEP is enabled while
    CONFIG_PROVE_RCU is not, this compilation error will occur.

    To resolve this issue, add a parallel macro CONFIG_LOCKDEP control to
    ensure cgroup_mutex is properly exported when needed.

    Signed-off-by: gao xu <gaoxu2@honor.com>
    Acked-by: Michal Koutný <mkoutny@suse.com>
    Signed-off-by: Tejun Heo <tj@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>