xfs: substitute spaces with tabs
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Thomas Bianchi <thomas.bianchi8@gmail.com>
commit c2b6e1591b6b15e1dcd9c1596b0371b6abc48fed

Inside xfs_attr_shortform_list removes spaces at the beginnig of the line
and replaces with tabs.
Issue found by checkpatch.

ERROR: code indent should use tabs where possible

	Signed-off-by: Thomas Bianchi <thomas.bianchi8@gmail.com>
	Reviewed-by: Bill O'Donnell <billodo@redhat.com>
	Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
	Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>
(cherry picked from commit c2b6e1591b6b15e1dcd9c1596b0371b6abc48fed)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>