printk: avoid -Wsometimes-uninitialized warning
Bugzilla: https://bugzilla.redhat.com/2117494

commit 5aa7eea9316ceb4b57175ce04b39e498105b7e92
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 28 11:34:33 2021 +0200

    printk: avoid -Wsometimes-uninitialized warning

    clang notices that the pi_get_entry() function would use
    uninitialized data if it was called with a non-NULL module
    pointer on a kernel that does not support modules:

    kernel/printk/index.c:32:6: error: variable 'nr_entries' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
            if (!mod) {
                ^~~~
    kernel/printk/index.c:38:13: note: uninitialized use occurs here
            if (pos >= nr_entries)
                       ^~~~~~~~~~
    kernel/printk/index.c:32:2: note: remove the 'if' if its condition is always true
            if (!mod) {

    Rework the condition to make it clear to the compiler that we are always
    in the second case. Unfortunately the #ifdef is still required as the
    definition of 'struct module' is hidden when modules are disabled.

    Fixes: 337015573718 ("printk: Userspace format indexing support")
    Suggested-by: Steven Rostedt <rostedt@goodmis.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Petr Mladek <pmladek@suse.com>
    Link: https://lore.kernel.org/r/20210928093456.2438109-1-arnd@kernel.org

Signed-off-by: David Arcari <darcari@redhat.com>