ethernet: ice: avoid gcc-9 integer overflow warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2153358

Upstream commit(s):
commit 8f5c5a790e3025d6eca96bf7ee5e3873dc92373f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 14 16:25:36 2023 +0100

    ethernet: ice: avoid gcc-9 integer overflow warning

    With older compilers like gcc-9, the calculation of the vlan
    priority field causes a false-positive warning from the byteswap:

    In file included from drivers/net/ethernet/intel/ice/ice_tc_lib.c:4:
    drivers/net/ethernet/intel/ice/ice_tc_lib.c: In function 'ice_parse_cls_flower':
    include/uapi/linux/swab.h:15:15: error: integer overflow in expression '(int)(short unsigned int)((int)match.key-><U67c8>.<U6698>.vlan_priority << 13) & 57344 & 255' of type 'int' results in '0' [-Werror=overflow]
       15 |  (((__u16)(x) & (__u16)0x00ffU) << 8) |   \
          |   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
    include/uapi/linux/swab.h:106:2: note: in expansion of macro '___constant_swab16'
      106 |  ___constant_swab16(x) :   \
          |  ^~~~~~~~~~~~~~~~~~
    include/uapi/linux/byteorder/little_endian.h:42:43: note: in expansion of macro '__swab16'
       42 | #define __cpu_to_be16(x) ((__force __be16)__swab16((x)))
          |                                           ^~~~~~~~
    include/linux/byteorder/generic.h:96:21: note: in expansion of macro '__cpu_to_be16'
       96 | #define cpu_to_be16 __cpu_to_be16
          |                     ^~~~~~~~~~~~~
    drivers/net/ethernet/intel/ice/ice_tc_lib.c:1458:5: note: in expansion of macro 'cpu_to_be16'
     1458 |     cpu_to_be16((match.key->vlan_priority <<
          |     ^~~~~~~~~~~

    After a change to be16_encode_bits(), the code becomes more
    readable to both people and compilers, which avoids the warning.

    Fixes: 34800178b302 ("ice: Add support for VLAN priority filters in switchdev")
    Suggested-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Alexander Lobakin <alexandr.lobakin@intel.com>
    Tested-by: Sujai Buvaneswaran <sujai.buvaneswaran@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Petr Oros <poros@redhat.com>