netfilter: nft_set_pipapo: don't return bogus extension pointer
jira KERNEL-1646
Rebuild_History Non-Buildable kernel-5.14.0-687.51.1.el9_8
commit-author Florian Westphal <fw@strlen.de>
commit c8a7c2c608180f3b4e51dc958b3861242dcdd76d

Dan Carpenter says:
Commit 17a20e09f086 ("netfilter: nft_set: remove one argument from
lookup and update functions") [..] leads to the following Smatch
static checker warning:

 net/netfilter/nft_set_pipapo_avx2.c:1269 nft_pipapo_avx2_lookup()
 error: uninitialized symbol 'ext'.

Fix this by initing ext to NULL and set it only once we've found
a match.

Fixes: 17a20e09f086 ("netfilter: nft_set: remove one argument from lookup and update functions")
	Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Closes: https://lore.kernel.org/netfilter-devel/aJBzc3V5wk-yPOnH@stanley.mountain/
	Signed-off-by: Florian Westphal <fw@strlen.de>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit c8a7c2c608180f3b4e51dc958b3861242dcdd76d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>