i40e: Add missing wordpart.h header
JIRA: https://redhat.atlassian.net/browse/RHEL-118536

commit b09621cc0dfd7d2ae8557ee9d0d7ca6dc75145e5
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Mar 2 10:18:31 2026 +0100

    i40e: Add missing wordpart.h header

    When cleaning up another header I have met this build error:

    drivers/net/ethernet/intel/i40e/i40e_hmc.h:105:22: error: implicit declaration of function 'upper_32_bits' [-Wimplicit-function-declaration]
      105 |         val1 = (u32)(upper_32_bits(pa));                                \

    This is due to missing header, add it to fix the possible issue.

    Reviewed-by: Paul Menzel <pmenzel@molgen.mpg.de>
    Reviewed-by: Aleksandr Loktionov <aleksandr.loktionov@intel.com>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>