RDMA/uverbs: select CONFIG_DMA_SHARED_BUFFER
JIRA: https://redhat.atlassian.net/browse/RHEL-163515

commit 16cb1a64dce56708a1684bf755ad52fb52c41f87
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 16 13:12:00 2026 +0100

    RDMA/uverbs: select CONFIG_DMA_SHARED_BUFFER

    The addition of dmabuf support in uverbs means that it is no
    longer possible to build infiniband support if that is disabled:

    arm-linux-gnueabi-ld: drivers/infiniband/core/ib_core_uverbs.o: in function `rdma_user_mmap_entry_remove.part.0':
    ib_core_uverbs.c:(.text+0x508): undefined reference to `dma_buf_move_notify'
    (dma_buf_move_notify): Unknown destination type (ARM/Thumb) in drivers/infiniband/core/ib_core_uverbs.o
    ib_core_uverbs.c:(.text+0x518): undefined reference to `dma_resv_wait_timeout'
    (dma_resv_wait_timeout): Unknown destination type (ARM/Thumb) in drivers/infiniband/core/ib_core_uverbs.o

    Select this from Kconfig, as we do for the other users.

    Fixes: 0ac6f4056c4a ("RDMA/uverbs: Add DMABUF object type and operations")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260216121213.2088910-1-arnd@kernel.org
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>