doc/netlink/specs: Add vlan attr in rt_link spec
JIRA: https://issues.redhat.com/browse/RHEL-57756

Upstream commit(s):
commit 782c1084b9fa5bc96c7c1ab5b770dec30834517b
Author: Hangbin Liu <liuhangbin@gmail.com>
Date:   Wed Mar 27 20:31:29 2024 +0800

    doc/netlink/specs: Add vlan attr in rt_link spec

    With command:
     # ./tools/net/ynl/cli.py \
     --spec Documentation/netlink/specs/rt_link.yaml \
     --do getlink --json '{"ifname": "eno1.2"}' --output-json | \
     jq -C '.linkinfo'

    Before:
    Exception: No message format for 'vlan' in sub-message spec 'linkinfo-data-msg'

    After:
     {
       "kind": "vlan",
       "data": {
         "protocol": "8021q",
         "id": 2,
         "flag": {
           "flags": [
             "reorder-hdr"
           ],
           "mask": "0xffffffff"
         },
         "egress-qos": {
           "mapping": [
             {
               "from": 1,
               "to": 2
             },
             {
               "from": 4,
               "to": 4
             }
           ]
         }
       }
     }

    Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
    Reviewed-by: Donald Hunter <donald.hunter@gmail.com>
    Link: https://lore.kernel.org/r/20240327123130.1322921-3-liuhangbin@gmail.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>