net: ethernet: ti: am65-cpsw: Fix build error without PHYLINK
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit bfa323c659b1016c8e896920ba08cd6914cc3b0c
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Sat Apr 9 18:59:31 2022 +0800

    net: ethernet: ti: am65-cpsw: Fix build error without PHYLINK

    If PHYLINK is n, build fails:

    drivers/net/ethernet/ti/am65-cpsw-ethtool.o: In function `am65_cpsw_set_link_ksettings':
    am65-cpsw-ethtool.c:(.text+0x118): undefined reference to `phylink_ethtool_ksettings_set'
    drivers/net/ethernet/ti/am65-cpsw-ethtool.o: In function `am65_cpsw_get_link_ksettings':
    am65-cpsw-ethtool.c:(.text+0x138): undefined reference to `phylink_ethtool_ksettings_get'
    drivers/net/ethernet/ti/am65-cpsw-ethtool.o: In function `am65_cpsw_set_eee':
    am65-cpsw-ethtool.c:(.text+0x158): undefined reference to `phylink_ethtool_set_eee'

    Select PHYLINK for TI_K3_AM65_CPSW_NUSS to fix this.

    Fixes: e8609e69470f ("net: ethernet: ti: am65-cpsw: Convert to PHYLINK")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Russell King (Oracle) <rmk+kernel@armlinux.org.uk>
    Link: https://lore.kernel.org/r/20220409105931.9080-1-yuehaibing@huawei.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>