x86/speculation: Add cpu_show_gds() prototype
jira LE-1907
cve CVE-2023-20569
Rebuild_History Non-Buildable kernel-4.18.0-521.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit a57c27c7ad85c420b7de44c6ee56692d51709dda
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-521.el8/a57c27c7.failed

The newly added function has two definitions but no prototypes:

drivers/base/cpu.c:605:16: error: no previous prototype for 'cpu_show_gds' [-Werror=missing-prototypes]

Add a declaration next to the other ones for this file to avoid the
warning.

Fixes: 8974eb588283b ("x86/speculation: Add Gather Data Sampling mitigation")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
	Tested-by: Daniel Sneddon <daniel.sneddon@linux.intel.com>
	Cc: stable@kernel.org
Link: https://lore.kernel.org/all/20230809130530.1913368-1-arnd%40kernel.org
(cherry picked from commit a57c27c7ad85c420b7de44c6ee56692d51709dda)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/linux/cpu.h