ASoC: SOF: topology: simplify code to prevent static analysis warnings
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 55cb3dc271d81f1982c949a2ac483a6daf613b92
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Mon Jul 31 16:37:43 2023 -0500

    ASoC: SOF: topology: simplify code to prevent static analysis warnings

    make KCFLAGS='-fanalyzer' sound/soc/sof/intel/ reports a possible NULL
    pointer dereference.

    sound/soc/sof/topology.c:1136:21: error: dereference of NULL ‘w’
    [CWE-476] [-Werror=analyzer-null-dereference]

     1136 |     strcmp(w->sname, rtd->dai_link->stream_name))

    The code is rather confusing and can be simplified to make static
    analysis happy. No functionality change.

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Reviewed-by: Rander Wang <rander.wang@intel.com>
    Reviewed-by: Daniel Baluta <daniel.baluta@nxp.com>
    Reviewed-by: Yaochun Hung <yc.hung@mediatek.com>
    Link: https://lore.kernel.org/r/20230731213748.440285-4-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>