x86, tools: Fix up compiler warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [x86] tools: Fix up compiler warnings (Lenny Szubowicz) [1310154]
Rebuild_FUZZ: 92.54%
commit-author Matt Fleming <matt.fleming@intel.com>
commit b663a685831905066e3efcb4c173cd8b3f46228b

The kbuild test robot reported the following errors that were introduced
with commit 993c30a04e20 ("x86, tools: Consolidate #ifdef code"),

  arch/x86/boot/tools/build.c: In function 'update_pecoff_setup_and_reloc':
>> arch/x86/boot/tools/build.c:252:1: error: parameter name omitted
    static inline void update_pecoff_setup_and_reloc(unsigned int) {}
    ^
  arch/x86/boot/tools/build.c: In function 'update_pecoff_text':
>> arch/x86/boot/tools/build.c:253:1: error: parameter name omitted
    static inline void update_pecoff_text(unsigned int, unsigned int) {}
    ^
>> arch/x86/boot/tools/build.c:253:1: error: parameter name omitted

   arch/x86/boot/tools/build.c: In function 'main':
>> arch/x86/boot/tools/build.c:372:2: warning: implicit declaration of function 'efi_stub_entry_update' [-Wimplicit-function-declaration]
    efi_stub_entry_update();
    ^
	Signed-off-by: Matt Fleming <matt.fleming@intel.com>

(cherry picked from commit b663a685831905066e3efcb4c173cd8b3f46228b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>