mmc: MMC_SH_MMCIF should depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] MMC_SH_MMCIF should depend on HAS_DMA (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 93.67%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 0e7d43786886b0f8419012800f4f1237ae409170

If NO_DMA=y:

    drivers/built-in.o: In function `sh_mmcif_start_dma_tx':
    sh_mmcif.c:(.text+0x5a3286): undefined reference to `dma_map_sg'
    drivers/built-in.o: In function `sh_mmcif_start_dma_rx':
    sh_mmcif.c:(.text+0x5a33fc): undefined reference to `dma_map_sg'
    drivers/built-in.o: In function `sh_mmcif_end_cmd':
    sh_mmcif.c:(.text+0x5a3668): undefined reference to `dma_unmap_sg'

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Acked-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
(cherry picked from commit 0e7d43786886b0f8419012800f4f1237ae409170)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>