mmc: rtsx: fix possible linking error if built-in
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] rtsx: fix possible linking error if built-in (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 94.62%
commit-author Arnd Bergmann <arnd@arndb.de>
commit b677b8850322b210a81b72ffcc7de85a3df395c5

rtsx_usb_sdmmc module uses the LED classdev if available, but the code
failed to consider the situation that it is built-in and the LED classdev is a
module, leading to following linking error:

   LD      init/built-in.o
drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_remove':
rtsx_usb_sdmmc.c:(.text+0x2a018e): undefined reference to
`led_classdev_unregister'
drivers/built-in.o: In function `rtsx_usb_sdmmc_drv_probe':
rtsx_usb_sdmmc.c:(.text+0x2a197e): undefined reference to
`led_classdev_register'

Fix by excluding such condition when defining macro RTSX_USB_USE_LEDS_CLASS.

	Signed-off-by: Roger Tseng <rogerable@realtek.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
	Signed-off-by: Chris Ball <chris@printf.net>
(cherry picked from commit b677b8850322b210a81b72ffcc7de85a3df395c5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>