libbpf: Avoid possible use of uninitialized mod_len
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit 13cb75730b7a8b2dc8fe32874e159b2c7b75efde
Author: Achill Gilgenast <fossdd@pwned.life>
Date:   Tue Jul 29 11:45:53 2025 +0200

    libbpf: Avoid possible use of uninitialized mod_len

    Though mod_len is only read when mod_name != NULL and both are initialized
    together, gcc15 produces a warning with -Werror=maybe-uninitialized:

    libbpf.c: In function 'find_kernel_btf_id.constprop':
    libbpf.c:10100:33: error: 'mod_len' may be used uninitialized [-Werror=maybe-uninitialized]
    10100 |                 if (mod_name && strncmp(mod->name, mod_name, mod_len) != 0)
          |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    libbpf.c:10070:21: note: 'mod_len' was declared here
    10070 |         int ret, i, mod_len;
          |                     ^~~~~~~

    Silence the false positive.

    Signed-off-by: Achill Gilgenast <fossdd@pwned.life>
    Acked-by: Yonghong Song <yonghong.song@linux.dev>
    Acked-by: Eduard Zingerman <eddyz87@gmail.com>
    Link: https://lore.kernel.org/r/20250729094611.2065713-1-fossdd@pwned.life
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>