usb: typec: tipd: remove unused tps6598x_write16,32 functions
JIRA: https://issues.redhat.com/browse/RHEL-13058

commit 766eae980611f5377ee54518f58da11b4d866f59
Author: Tom Rix <trix@redhat.com>
Date: Sun, 19 Mar 2023 09:37:32 -0400

  clang with W=1 reports
  drivers/usb/typec/tipd/core.c:180:19: error: unused function
    'tps6598x_write16' [-Werror,-Wunused-function]
  static inline int tps6598x_write16(struct tps6598x *tps, u8 reg, u16 val)
                    ^
  drivers/usb/typec/tipd/core.c:185:19: error: unused function
    'tps6598x_write32' [-Werror,-Wunused-function]
  static inline int tps6598x_write32(struct tps6598x *tps, u8 reg, u32 val)
                    ^
  These static functions are not used, so remove them.

  Signed-off-by: Tom Rix <trix@redhat.com>
  Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
  Reviewed-by: Jun Nie <jun.nie@linaro.org>
  Link: https://lore.kernel.org/r/20230319133732.1702841-1-trix@redhat.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>