objtool: Fix compile failure when using the x32 compiler
JIRA: https://issues.redhat.com/browse/RHEL-114921

commit 6205125bd326ed0153e5f9da3c4689fe60ae885a
Author: Mikulas Patocka <mpatocka@redhat.com>
Date:   Sat Mar 30 20:23:08 2024 +0100

    objtool: Fix compile failure when using the x32 compiler

    When compiling the v6.9-rc1 kernel with the x32 compiler, the following
    errors are reported. The reason is that we take an "unsigned long"
    variable and print it using "PRIx64" format string.

            In file included from check.c:16:
            check.c: In function ‘add_dead_ends’:
            /usr/src/git/linux-2.6/tools/objtool/include/objtool/warn.h:46:17: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘long unsigned int’ [-Werror=format=]
               46 |                 "%s: warning: objtool: " format "\n",   \
                  |                 ^~~~~~~~~~~~~~~~~~~~~~~~
            check.c:613:33: note: in expansion of macro ‘WARN’
              613 |                                 WARN("can't find unreachable insn at %s+0x%" PRIx64,
                  |                                 ^~~~
            ...

    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Cc: Josh Poimboeuf <jpoimboe@redhat.com>
    Cc: linux-kernel@vger.kernel.org

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>