ASoC: cs35l41: Fix undefined reference to core functions
Auto select core driver if i2c or spi bus drivers are
selected

    Fixes: a5e0091d62ab ("ASoC: cs35l41: Fix link problem")

    Signed-off-by: Lucas Tanure <tanureal@opensource.cirrus.com>
    Reported-by: kernel test robot <lkp@intel.com>
    Link: https://lore.kernel.org/r/20211201180004.1402156-2-tanureal@opensource.cirrus.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Lucas Tanure <tanureal@opensource.cirrus.com>
Date: Wed Dec 1 18:00:04 2021 +0000

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 0695ad92fe1a0bb7697eb92c6a145a73c5ab0e24)
Bugzilla: https://bugzilla.redhat.com/2065572