MIPS: ftrace: Declare ftrace_get_parent_ra_addr() as static
JIRA: https://issues.redhat.com/browse/RHEL-86682

commit ddd068d81445b17ac0bed084dfeb9e58b4df3ddd
Author: WangYuli <wangyuli@uniontech.com>
Date:   Sat Jan 4 22:47:08 2025 +0800

    MIPS: ftrace: Declare ftrace_get_parent_ra_addr() as static

    Declare ftrace_get_parent_ra_addr() as static to suppress clang
    compiler warning that 'no previous prototype'. This function is
    not intended to be called from other parts.

    Fix follow error with clang-19:

    arch/mips/kernel/ftrace.c:251:15: error: no previous prototype for function 'ftrace_get_parent_ra_addr' [-Werror,-Wmissing-prototypes]
      251 | unsigned long ftrace_get_parent_ra_addr(unsigned long self_ra, unsigned long
          |               ^
    arch/mips/kernel/ftrace.c:251:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
      251 | unsigned long ftrace_get_parent_ra_addr(unsigned long self_ra, unsigned long
          | ^
          | static
    1 error generated.

    Signed-off-by: WangYuli <wangyuli@uniontech.com>
    Acked-by: Masami Hiramatsu (Google) <mhiramat@kernel.org>
    Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
    Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>