perf probe: Improve detection of file/function name in the probe pattern
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Improve detection of file/function name in the probe: pattern (Gustavo Duarte) [1223850]
Rebuild_FUZZ: 95.71%
commit-author Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
commit 3099c026002e97b8c173d9d0bbdfc39257d14402

Currently, perf probe considers patterns including a '.' to be a file.
However, this causes problems on powerpc ABIv1 where all functions have
a leading '.':

  $ perf probe -F | grep schedule_timeout_interruptible
  .schedule_timeout_interruptible
  $ perf probe .schedule_timeout_interruptible
  Semantic error :File always requires line number or lazy pattern.
    Error: Command Parse Error.

Fix this:
- by checking the probe pattern in more detail, and
- skipping leading dot if one exists when creating/deleting events.

	Signed-off-by: Naveen N. Rao <naveen.n.rao@linux.vnet.ibm.com>
	Reviewed-by: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
	Acked-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Cc: Ananth N Mavinakayanahalli <ananth@in.ibm.com>
	Cc: Michael Ellerman <mpe@ellerman.id.au>
	Cc: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
	Cc: Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>
	Cc: linuxppc-dev@lists.ozlabs.org
Link: http://lkml.kernel.org/r/db680f7cb11c4452b632f908e67151f3aa0f4602.1430217967.git.naveen.n.rao@linux.vnet.ibm.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 3099c026002e97b8c173d9d0bbdfc39257d14402)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>