octeontx2-af: fix build regression without CONFIG_DCB
JIRA: https://issues.redhat.com/browse/RHEL-127305

commit 410cd938511ff18a13bea39e1af80e4821dca14a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Dec 13 09:32:18 2024 +0100

    octeontx2-af: fix build regression without CONFIG_DCB

    When DCB is disabled, the pfc_en struct member cannot be accessed:

    drivers/net/ethernet/marvell/octeontx2/nic/otx2_common.c: In function 'otx2_is_pfc_enabled':
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_common.c:22:48: error: 'struct otx2_nic' has no member named 'pfc_en'
       22 |         return IS_ENABLED(CONFIG_DCB) && !!pfvf->pfc_en;
          |                                                ^~
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_common.c: In function 'otx2_nix_config_bp':
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_common.c:1755:33: error: 'IEEE_8021QAZ_MAX_TCS' undeclared (first use in this function)
     1755 |                 req->chan_cnt = IEEE_8021QAZ_MAX_TCS;
          |                                 ^~~~~~~~~~~~~~~~~~~~

    Move the member out of the #ifdef block to avoid putting back another
    check in the source file and add the missing include file unconditionally.

    Fixes: a7ef63dbd588 ("octeontx2-af: Disable backpressure between CPT and NIX")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Link: https://patch.msgid.link/20241213083228.2645757-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>