i40evf: fix s390 build failure due to implicit prefetch.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
commit-author Paul Gortmaker <paul.gortmaker@windriver.com>
commit 7ed3f5f0105d1e7f27551e6bc32413cc744c7b9f

As of commit 7f12ad741a4870b8b6e3aafbcd868d0191770802 ("i40evf: transmit
and receive functionality") the s390 builds (allyesconfig) fail with:

drivers/net/ethernet/intel/i40evf/i40e_txrx.c: In function 'i40e_clean_rx_irq':
drivers/net/ethernet/intel/i40evf/i40e_txrx.c:818:3: error: implicit declaration of function 'prefetch'
make[5]: *** [drivers/net/ethernet/intel/i40evf/i40e_txrx.o] Error 1

due to an implicit assumption that the prototype from linux/prefetch.h
will be present.

	Cc: Mitch Williams <mitch.a.williams@intel.com>
	Cc: Greg Rose <gregory.v.rose@intel.com>
	Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
	Acked-by: Shannon Nelson <shannon.nelson@intel.com>
	Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
(cherry picked from commit 7ed3f5f0105d1e7f27551e6bc32413cc744c7b9f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>