ext4: fix build error when DX_DEBUG is defined
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Gabriel Krisman Bertazi <krisman@collabora.co.uk>
commit 799578ab16e86b074c184ec5abbda0bc698c7b0b

Enabling DX_DEBUG triggers the build error below.  info is an attribute
of  the dxroot structure.

linux/fs/ext4/namei.c:2264:12: error: ‘info’
undeclared (first use in this function); did you mean ‘insl’?
	   	  info->indirect_levels));

Fixes: e08ac99fa2a2 ("ext4: add largedir feature")
	Signed-off-by: Gabriel Krisman Bertazi <krisman@collabora.co.uk>
	Signed-off-by: Theodore Ts'o <tytso@mit.edu>
	Reviewed-by: Lukas Czerner <lczerner@redhat.com>
(cherry picked from commit 799578ab16e86b074c184ec5abbda0bc698c7b0b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>