accel/amdxdna: use modern PM helpers
JIRA: https://redhat.atlassian.net/browse/RHEL-222546
Upstream Status: v6.14-rc1

commit e5a8f19c39d769c2e4c0a4624576997ac41819bc
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Fri Dec 13 10:02:54 2024 +0100
Commit:     Jeffrey Hugo <quic_jhugo@quicinc.com>
CommitDate: Fri Dec 13 11:09:42 2024 -0700
    
    The old SET_SYSTEM_SLEEP_PM_OPS and SET_RUNTIME_PM_OPS macros cause a build
    warning when CONFIG_PM is disabled:
    
    drivers/accel/amdxdna/amdxdna_pci_drv.c:343:12: error: 'amdxdna_pmops_resume' defined but not used [-Werror=unused-function]
      343 | static int amdxdna_pmops_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~
    drivers/accel/amdxdna/amdxdna_pci_drv.c:328:12: error: 'amdxdna_pmops_suspend' defined but not used [-Werror=unused-function]
      328 | static int amdxdna_pmops_suspend(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~~~
    
    Change these to the modern replacements.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Lizhi Hou <lizhi.hou@amd.com>
    Tested-by: Lizhi Hou <lizhi.hou@amd.com>
    Signed-off-by: Jeffrey Hugo <quic_jhugo@quicinc.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241213090259.68492-1-arnd@kernel.org

Signed-off-by: Peter Colberg <pcolberg@redhat.com>