console/font: Refactor font support code selection logic
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit d1e183c8dd38bfdd07e38a79577fe78124e63ab1
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/d1e183c8.failed

The current Makefile rules to build font support are messy and buggy.
Replace them by Kconfig rules:
  - Introduce CONFIG_FONT_SUPPORT, which controls the building of all font
    code,
  - Select CONFIG_FONT_SUPPORT for all drivers that use fonts,
  - Select CONFIG_FONT_8x16 for all drivers that default to the VGA8x16
    font,
  - Drop the bogus console dependency for CONFIG_VIDEO_VIVI,
  - Always process drivers/video/console/Makefile, as some drivers need
    fonts even if CONFIG_VT is not set.

This fixes (if CONFIG_SOLO6X10=y and there are no built-in console
drivers):

drivers/built-in.o: In function `solo_osd_print':
drivers/staging/media/solo6x10/solo6x10-enc.c:144: undefined reference to `.find_font'

This fixes (if CONFIG_VT=n):

drivers/built-in.o: In function `vivi_init':
vivi.c:(.init.text+0x1a3da): undefined reference to `find_font'

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Acked-by: Hans Verkuil <hans.verkuil@cisco.com> [original part]
	Acked-by: Randy Dunlap <rdunlap@infradead.org> [drivers/video/Makefile]
(cherry picked from commit d1e183c8dd38bfdd07e38a79577fe78124e63ab1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/staging/media/solo6x10/Kconfig
#	drivers/video/console/Makefile