dmaengine: tegra210-adma: Use div_u64 for 64 bit division
JIRA: https://issues.redhat.com/browse/RHEL-109772

commit 17987453a9d997c4d0749abc52f047bfa275427a
Author: Mohan Kumar D <mkumard@nvidia.com>
Date: Mon, 10 Feb 2025 19:24:12 +0530

    The ADMA base and page address are represented using a 64-bit variable.
    To accurately derive the exact ADMA page number provided from the DT
    properties, use the div_u64() to divide the address difference between
    adma page and base address by the page offset.

    This change fixes the below error
       "ERROR: modpost: "__udivdi3" [drivers/dma/tegra210-adma.ko] undefined!
        ld: drivers/dma/tegra210-adma.o: in function `tegra_adma_probe':
        tegra210-adma.c:(.text+0x12cf): undefined reference to `__udivdi3'"

    Fixes: 68811c928f88 ("dmaengine: tegra210-adma: Support channel page")
    Cc: stable@vger.kernel.org
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202412250204.GCQhdKe3-lkp@intel.com/
    Signed-off-by: Mohan Kumar D <mkumard@nvidia.com>
    Reviewed-by: Jon Hunter <jonathanh@nvidia.com>
    Acked-by: Thierry Reding <treding@nvidia.com>
    Link: https://lore.kernel.org/r/20250210135413.2504272-2-mkumard@nvidia.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Marcin Juszkiewicz <mjuszkiewicz@redhat.com>