bna: Replace large udelay() with mdelay()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Ben Hutchings <ben@decadent.org.uk>
commit bc48bc806442114ea44f61d6b18e02c2bd6236fd

udelay() does not work on some architectures for values above
2000, in particular on ARM:

ERROR: "__bad_udelay" [drivers/net/ethernet/brocade/bna/bna.ko] undefined!

	Reported-by: Vagrant Cascadian <vagrant@debian.org>
	Signed-off-by: Ben Hutchings <ben@decadent.org.uk>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit bc48bc806442114ea44f61d6b18e02c2bd6236fd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>