ASoC: sdm845: add rt5663 codec select
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: sdm845: add rt5663 codec select (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 92.50%
commit-author Arnd Bergmann <arnd@arndb.de>
commit e9dc919043c56dccedce93fe402e6c94423a70b0

Calling into the codec driver adds a dependency on that being reachable
from the module:

ERROR: "rt5663_sel_asrc_clk_src" [sound/soc/qcom/snd-soc-sdm845.ko]
undefined!

Add the corresponding select statement, as it is done in the other user
(Intel).

Fixes: f7485875a687 ("ASoC: sdm845: Add configuration for headset codec")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit e9dc919043c56dccedce93fe402e6c94423a70b0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>