ALSA: hda: cs35l41: mark cs35l41_verify_id() static
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-536.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit f71e0be5d297b25453fdf4c1757b3e83e94b5f98

The newly introduced function is global but only called in this one
file and has no extern prototype, so it should probably be static:

sound/pci/hda/cs35l41_hda.c:733:5: error: no previous prototype for 'cs35l41_verify_id' [-Werror=missing-prototypes]
  733 | int cs35l41_verify_id(struct cs35l41_hda *cs35l41, unsigned int *regid, unsigned int *reg_revid)

Fixes: 881b7bce0c25 ("ALSA: hda: cs35l41: Run boot process during resume callbacks")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20231027152515.482411-1-arnd@kernel.org
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit f71e0be5d297b25453fdf4c1757b3e83e94b5f98)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>