ASoC: codecs: nau8325: Silence uninitialized variables warnings
JIRA: https://issues.redhat.com/browse/RHEL-118911

commit 2c7e5e17c05f1d5e10e63e1baff2b362cd08dcd6
Author: Krzysztof Kozlowski <krzysztof.kozlowski@oss.qualcomm.com>
Date: Wed Dec 3 15:06:12 2025 +0100

    ASoC: codecs: nau8325: Silence uninitialized variables warnings

    clang W=1 builds warn:

      nau8325.c:430:13: error: variable 'n2_max' is uninitialized when used here [-Werror,-Wuninitialized]

    which are false positive, because the variables will be always
    initialized when used (guarded by mclk_max!=0 check).  However
    initializing them upfront makes the code more obvious and easier, plus
    it silences the warning.

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@oss.qualcomm.com>
    Link: https://patch.msgid.link/20251203140611.87191-2-krzysztof.kozlowski@oss.qualcomm.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>