selftests/x86: Fix error: variably modified 'altstack_data' at file scope
JIRA: https://issues.redhat.com/browse/RHEL-115163

commit a051b2e56f2aa287b37ab0134a8af852f84e3f8e
Author: Jun Miao <jun.miao@windriver.com>
Date:   Tue Aug 24 10:43:58 2021 +0800

    selftests/x86: Fix error: variably modified 'altstack_data' at file scope

    A glibc 2.34 feature adds support for variable MINSIGSTKSZ and SIGSTKSZ.
    When _DYNAMIC_STACK_SIZE_SOURCE or _GNU_SOURCE are defined, MINSIGSTKSZ
    and SIGSTKSZ are no longer constant on Linux. glibc 2.34 flags code paths
    assuming MINSIGSTKSZ or SIGSTKSZ are constant. Fix these error in x86 test.

    Feature description and build error:

    NEWS for version 2.34
    =====================
    Major new features:
     * Add _SC_MINSIGSTKSZ and _SC_SIGSTKSZ.  When _DYNAMIC_STACK_SIZE_SOURCE
       or _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ are no longer
       constant on Linux.  MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ)
       and SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ).  This supports
       dynamic sized register sets for modern architectural features like
       Arm SVE.
    =====================

    If _SC_SIGSTKSZ_SOURCE or _GNU_SOURCE are defined, MINSIGSTKSZ and SIGSTKSZ
    are redefined as:

    /* Default stack size for a signal handler: sysconf (SC_SIGSTKSZ).  */
     # undef SIGSTKSZ
     # define SIGSTKSZ sysconf (_SC_SIGSTKSZ)

    /* Minimum stack size for a signal handler: SIGSTKSZ.  */
     # undef MINSIGSTKSZ
     # define MINSIGSTKSZ SIGSTKSZ

    Compilation will fail if the source assumes constant MINSIGSTKSZ or
    SIGSTKSZ.

    Build error with the GNU C Library 2.34:
    DEBUG:	| sigreturn.c:150:13: error: variably modified 'altstack_data' at file scope
    | sigreturn.c:150:13: error: variably modified 'altstack_data' at file scope
    DEBUG:	|   150 | static char altstack_data[SIGSTKSZ];
    |   150 | static char altstack_data[SIGSTKSZ];
    DEBUG:	|       |             ^~~~~~~~~~~~~

    DEBUG:  | single_step_syscall.c:60:22: error: variably modified 'altstack_data' at file scope
    DEBUG:  |   60 | static unsigned char altstack_data[SIGSTKSZ];
    DEBUG:  |      |                      ^~~~~~~~~~~~~

    Fixed commit log to improve formatting and clarity:
    Shuah Khan <skhan@linuxfoundation.org>

    Link: https://sourceware.org/pipermail/libc-alpha/2021-January/121996.html
    Link: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html
    Suggested-by: Jianwei Hu <jianwei.hu@windriver.com>
    Signed-off-by: Jun Miao <jun.miao@windriver.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

(cherry picked from commit a051b2e56f2aa287b37ab0134a8af852f84e3f8e)
Assisted-by: Patchpal
Signed-off-by: David Arcari <darcari@redhat.com>