ASoC: Intel: boards: Fix compile-testing RT1011/RT5682
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: Intel: boards: Fix compile-testing RT1011/RT5682 (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.74%
commit-author Arnd Bergmann <arnd@arndb.de>
commit ff3b57417012fcc963ec281f5705bed837e4b1ac

On non-x86, the new driver results in a build failure:

sound/soc/intel/boards/cml_rt1011_rt5682.c:14:10: fatal error: asm/cpu_device_id.h: No such file or directory

The asm/cpu_device_id.h header is not actually needed here,
so don't include it.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20200102135322.1841053-1-arnd@arndb.de
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ff3b57417012fcc963ec281f5705bed837e4b1ac)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>