drm/panel: ilitek-ili9882t: Select DRM_DISPLAY_DSC_HELPER
JIRA: https://redhat.atlassian.net/browse/RHEL-180328

commit eaa8457e12df1ad002dbe9bca65ae16573268052
Author: Maíra Canal <mcanal@igalia.com>
Date:   Thu Jan 15 09:50:48 2026 -0300

    drm/panel: ilitek-ili9882t: Select DRM_DISPLAY_DSC_HELPER

    [ Upstream commit 68e28facbc8ab3e701e1814323d397a75b400865 ]

    The panel-ilitek-ili9882t driver uses drm_dsc_pps_payload_pack() which
    is provided by the DRM_DISPLAY_DSC_HELPER. Add the missing Kconfig
    select to fix the following build error:

      ERROR: modpost: "drm_dsc_pps_payload_pack" [drivers/gpu/drm/panel/panel-ilitek-ili9882t.ko] undefined!

    Fixes: 65ce1f5834e9 ("drm/panel: ilitek-ili9882t: Switch Tianma TL121BVMS07 to DSC 120Hz mode")
    Reviewed-by: Neil Armstrong <neil.armstrong@linaro.org>
    Tested-by: Nicolas Frattaroli <nicolas.frattaroli@collabora.com>
    Reviewed-by: Nicolas Frattaroli <nicolas.frattaroli@collabora.com>
    Link: https://patch.msgid.link/20260115125136.64866-1-mcanal@igalia.com
    Signed-off-by: Maíra Canal <mcanal@igalia.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Karol Herbst <kherbst@redhat.com>