bnxt_en: Fix compile error without CONFIG_RFS_ACCEL
JIRA: https://issues.redhat.com/browse/RHEL-54645

commit 0f2b21477988634ba7d813539f034d595f9501d7
Author: Michael Chan <michael.chan@broadcom.com>
Date:   Wed Jan 3 17:01:08 2024 -0800

    bnxt_en: Fix compile error without CONFIG_RFS_ACCEL

    Fix the following compile error:

    .../bnxt.c: In function 'bnxt_cfg_ntp_filters':
    .../bnxt.c:14077:37: error: implicit declaration of function 'rps_may_expire_flow' [-Werror=implicit-function-declaration]
    14077 |                                 if (rps_may_expire_flow(bp->dev, fltr->base.rxq,
          |                                     ^~~~~~~~~~~~~~~~~~~

    bnxt_cfg_ntp_filters() is only used when CONFIG_RFS_ACCEL is enabled.
    User configured ntuple filters are directly added and will not go through
    this function.  Wrap the body of bnxt_cfg_ntp_filters() with
    CONFIG_RFS_ACCEL.

    Fixes: 59cde76f33fa ("bnxt_en: Refactor filter insertion logic in bnxt_rx_flow_steer().")
    Reported-by: Arnd Bergmann <arnd@kernel.org>
    Link: https://lore.kernel.org/netdev/20240103102332.3642417-1-arnd@kernel.org/
    Reported-by: kernel test robot <lkp@intel.com>
    Reviewed-by: Andy Gospodarek <andrew.gospodarek@broadcom.com>
    Signed-off-by: Michael Chan <michael.chan@broadcom.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>

Conflicts:
	drivers/net/ethernet/broadcom/bnxt/bnxt.c
	- Upstream conflict resolved in merge commit e63c1822ac32
	  ("Merge git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net")