dmaengine: tegra-apb: remove unused tdma_read function
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2215342

commit a747051efa16d4304aacaf44fa0771667e28ca54
Author: Tom Rix <trix@redhat.com>
Date: Wed, 22 Mar 2023 08:10:01 -0400

    clang with W=1 reports
    drivers/dma/tegra20-apb-dma.c:236:19: error: unused function
      'tdma_read' [-Werror,-Wunused-function]
    static inline u32 tdma_read(struct tegra_dma *tdma, u32 reg)
                      ^
    This function is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Jon Hunter <jonathanh@nvidia.com>
    Link: https://lore.kernel.org/r/20230322121001.2569909-1-trix@redhat.com
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>