net/mlx5e: Allow dissector meta key in tc flower
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [netdrv] mlx5e: Allow dissector meta key in tc flower (Ivan Vecera) [1762861]
Rebuild_FUZZ: 95.65%
commit-author Vlad Buslov <vladbu@mellanox.com>
commit 3d144578c91a2db417923ba905ce7a84ce0c274b

Recently, fl_flow_key->indev_ifindex int field was refactored into
flow_dissector_key_meta field. With this, flower classifier also sets
FLOW_DISSECTOR_KEY_META flow dissector key. However, mlx5 flower dissector
validation code rejects filters that use flow dissector keys that are not
supported. Add FLOW_DISSECTOR_KEY_META to the list of allowed dissector
keys in __parse_cls_flower() to prevent following error when offloading
flower classifier to mlx5:

Error: mlx5_core: Unsupported key.

Fixes: 8212ed777f40 ("net: sched: cls_flower: use flow_dissector for ingress ifindex")
	Signed-off-by: Vlad Buslov <vladbu@mellanox.com>
	Reviewed-by: Roi Dayan <roid@mellanox.com>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit 3d144578c91a2db417923ba905ce7a84ce0c274b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>