net: sunrpc: fix build errors when linux/phy*.h is removed from net/dsa.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [infiniband] sunrpc: fix build errors when linux/phy*.h is removed from sa.h (Don Dutile) [1385309 1385649 1386645 1409099 1456667 1456687]
Rebuild_FUZZ: 92.65%
commit-author Russell King <rmk+kernel@armlinux.org.uk>
commit f39b2dde4886450b965ccd0a6defe8bc33fcc938

Removing linux/phy.h from net/dsa.h reveals a build error in the sunrpc
code:

net/sunrpc/xprtrdma/svc_rdma_backchannel.c: In function 'xprt_rdma_bc_put':
net/sunrpc/xprtrdma/svc_rdma_backchannel.c:277:2: error: implicit declaration of function 'module_put' [-Werror=implicit-function-declaration]
net/sunrpc/xprtrdma/svc_rdma_backchannel.c: In function 'xprt_setup_rdma_bc':
net/sunrpc/xprtrdma/svc_rdma_backchannel.c:348:7: error: implicit declaration of function 'try_module_get' [-Werror=implicit-function-declaration]

Fix this by adding linux/module.h to svc_rdma_backchannel.c

	Signed-off-by: Russell King <rmk+kernel@armlinux.org.uk>
	Acked-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit f39b2dde4886450b965ccd0a6defe8bc33fcc938)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>