nvmet: include <linux/scatterlist.h>
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Enrico Weigelt, metux IT consult <info@metux.net>
commit a5dffbb66d250a7ef07e27a2e75b8d9d7af2ab41

Build breaks:

    drivers/nvme/target/core.c: In function 'nvmet_req_alloc_sgl':
    drivers/nvme/target/core.c:939:12: error: implicit declaration of \
function 'sgl_alloc'; did you mean 'bio_alloc'? \
[-Werror=implicit-function-declaration]
      req->sg = sgl_alloc(req->transfer_len, GFP_KERNEL, &req->sg_cnt);
                ^~~~~~~~~
                bio_alloc
    drivers/nvme/target/core.c:939:10: warning: assignment makes pointer \
from integer without a cast [-Wint-conversion]
      req->sg = sgl_alloc(req->transfer_len, GFP_KERNEL, &req->sg_cnt);
              ^
    drivers/nvme/target/core.c: In function 'nvmet_req_free_sgl':
    drivers/nvme/target/core.c:952:3: error: implicit declaration of \
function 'sgl_free'; did you mean 'ida_free'? [-Werror=implicit-function-declaration]
       sgl_free(req->sg);
       ^~~~~~~~
       ida_free

Cause:

    1. missing include to <linux/scatterlist.h>
    2. SGL_ALLOC needs to be enabled

Therefore adding the missing include, as well as Kconfig dependency.

	Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
	Reviewed-by: Sagi Grimberg <sagi@grimberg.me>
	Reviewed-by: Minwoo Im <minwoo.im@samsung.com>
	Reviewed-by: Chaitanya Kulkarni <chaitanya.kulkarni@wdc.com>
	Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit a5dffbb66d250a7ef07e27a2e75b8d9d7af2ab41)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>