ice: dpll: Fix compilation warning
jira KERNEL-1636
Rebuild_History Non-Buildable kernel-5.14.0-687.50.1.el9_8
commit-author Przemyslaw Korba <przemyslaw.korba@intel.com>
commit 586483cb41f40eab03ca65ceedeae623b379783a

Introduced by commit ad1df4f2d591 ("ice: dpll: Support E825-C SyncE and
dynamic pin discovery"):

ice_dpll.c: In function ‘ice_dpll_init’:
ice_dpll.c:3588:59: error: ‘%u’ directive output may be truncated
writing between 1 and 10 bytes into a region of size 4
[-Werror=format-truncation=] snprintf(pin_name, sizeof(pin_name),
"rclk%u", i);

	Reviewed-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
	Signed-off-by: Przemyslaw Korba <przemyslaw.korba@intel.com>
	Reviewed-by: Aleksandr Loktionov <aleksandr.loktionov@intel.com>
	Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
Link: https://patch.msgid.link/20260430-jk-iwl-net-next-2026-04-30-v1-13-6f27ae1cd073@intel.com
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 586483cb41f40eab03ca65ceedeae623b379783a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>