ALSA: usb-audio: Fix undefined behavior due to shift overflowing the constant
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Borislav Petkov <bp@suse.de>
commit 1ef8715975de8bd481abbd0839ed4f49d9e5b0ff

Fix:

  sound/usb/midi.c: In function ‘snd_usbmidi_out_endpoint_create’:
  sound/usb/midi.c:1389:2: error: case label does not reduce to an integer constant
    case USB_ID(0xfc08, 0x0101): /* Unknown vendor Cable */
    ^~~~

See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
details as to why it triggers with older gccs only.

[ A slight correction with parentheses around the argument by tiwai ]

	Signed-off-by: Borislav Petkov <bp@suse.de>
Link: https://lore.kernel.org/r/20220405151517.29753-3-bp@alien8.de
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 1ef8715975de8bd481abbd0839ed4f49d9e5b0ff)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>