ACPI/IORT: Fix build error implicit-function-declaration
Bugzilla: https://bugzilla.redhat.com/2112024
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit de0269765b268717b70f16f809560e83d5a8d0e7
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Tue Jul 26 11:35:20 2022 +0800

    ACPI/IORT: Fix build error implicit-function-declaration

    If CONFIG_ACPI_IORT=y and CONFIG_IOMMU_API is not set,
    make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-,
    will be failed, like this:

    drivers/acpi/arm64/iort.c: In function ‘iort_get_rmr_sids’:
    drivers/acpi/arm64/iort.c:1406:2: error: implicit declaration of function ‘iort_iommu_rmr_get_resv_regions’; did you mean ‘iort_iommu_get_resv_regions’? [-Werror=implicit-function-declaration]
      iort_iommu_rmr_get_resv_regions(iommu_fwnode, NULL, head);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      iort_iommu_get_resv_regions
    cc1: some warnings being treated as errors
    make[3]: *** [drivers/acpi/arm64/iort.o] Error 1

    The function iort_iommu_rmr_get_resv_regions()
    is declared under CONFIG_IOMMU_API,
    and the callers of iort_get_rmr_sids() and iort_put_rmr_sids()
    would select IOMMU_API.

    To fix this error, move the definitions to #ifdef CONFIG_IOMMU_API.

    Fixes: e302eea8f497 ("ACPI/IORT: Add a helper to retrieve RMR info directly")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Acked-by: Hanjun Guo <guohanjun@huawei.com>
    Link: https://lore.kernel.org/r/20220726033520.47865-1-renzhijie2@huawei.com
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit de0269765b268717b70f16f809560e83d5a8d0e7)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>