drm/i915/mtl: avoid stringop-overflow warning
JIRA: https://issues.redhat.com/browse/RHEL-1350
Upstream Status: v6.7-rc1

commit 390001d648ffa027b750b7dceb5d43f4c1d1a39e
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Mon Oct 16 22:10:04 2023 +0200
Commit:     Jani Nikula <jani.nikula@intel.com>
CommitDate: Mon Oct 30 13:48:32 2023 +0200

    The newly added memset() causes a warning for some reason I could not
    figure out:

    In file included from arch/x86/include/asm/string.h:3,
                     from drivers/gpu/drm/i915/gt/intel_rc6.c:6:
    In function 'rc6_res_reg_init',
        inlined from 'intel_rc6_init' at drivers/gpu/drm/i915/gt/intel_rc6.c:610:2:
    arch/x86/include/asm/string_32.h:195:29: error: '__builtin_memset' writing 16 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
      195 | #define memset(s, c, count) __builtin_memset(s, c, count)
          |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/i915/gt/intel_rc6.c:584:9: note: in expansion of macro 'memset'
      584 |         memset(rc6->res_reg, INVALID_MMIO_REG.reg, sizeof(rc6->res_reg));
          |         ^~~~~~
    In function 'intel_rc6_init':

    Change it to an normal initializer and an added memcpy() that does not have
    this problem.

    Fixes: 4bb9ca7ee074 ("drm/i915/mtl: C6 residency and C state type for MTL SAMedia")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jani Nikula <jani.nikula@intel.com>
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20231016201012.1022812-1-arnd@kernel.org
    (cherry picked from commit 0520b30b219053cd789909bca45b3c486ef3ee09)
    Signed-off-by: Jani Nikula <jani.nikula@intel.com>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>