wifi: ath12k: Fix uninitialized use of ret in ath12k_mac_allocate()
JIRA: https://issues.redhat.com/browse/RHEL-34696

commit 04edb5dc68f4356fd8df44c04547a729dc44f43e
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Feb 5 12:49:53 2024 -0700

    wifi: ath12k: Fix uninitialized use of ret in ath12k_mac_allocate()
    
    Clang warns (or errors with CONFIG_WERROR=y):
    
      drivers/net/wireless/ath/ath12k/mac.c:8060:9: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
       8060 |         return ret;
            |                ^~~
      drivers/net/wireless/ath/ath12k/mac.c:8022:9: note: initialize the variable 'ret' to silence this warning
       8022 |         int ret, i, j;
            |                ^
            |                 = 0
      1 error generated.
    
    Commit 6db6e70a17f6 ("wifi: ath12k: Introduce the container for mac80211
    hw") added a completely uninitialized use of ret. Prior to that change,
    -ENOMEM was returned to the callers of ath12k_mac_allocate() whenever
    ath12k_mac_hw_allocate() failed. Assign that value to ret to make sure
    it is always initialized when used and clear up the warning.
    
    Closes: https://github.com/ClangBuiltLinux/linux/issues/1989i
    Fixes: 6db6e70a17f6 ("wifi: ath12k: Introduce the container for mac80211 hw")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://msgid.link/20240205-ath12k-mac-wuninitialized-v1-1-3fda7b17357f@kernel.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>