Documentation: KUnit: Fix example with compilation error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-528.el8
commit-author Maíra Canal <mairacanal@riseup.net>
commit 4c392516accfe51a1aaf80ed163517646f8f0476

The Parameterized Testing example contains a compilation error, as the
signature for the description helper function is void(*)(const struct
sha1_test_case *, char *), and the struct is non-const. This is
warned by Clang:

error: initialization of ‘void (*)(struct sha1_test_case *, char *)’
from incompatible pointer type ‘void (*)(const struct sha1_test_case *,
char *)’ [-Werror=incompatible-pointer-types]
33 | KUNIT_ARRAY_PARAM(sha1, cases, case_to_desc);
   |                                ^~~~~~~~~~~~
../include/kunit/test.h:1339:70: note: in definition of macro
‘KUNIT_ARRAY_PARAM’
1339 |                         void
   (*__get_desc)(typeof(__next), char *) = get_desc; \

	Signed-off-by: Maíra Canal <mairacanal@riseup.net>
	Reviewed-by: Daniel Latypov <dlatypov@google.com>
	Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit 4c392516accfe51a1aaf80ed163517646f8f0476)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>