kallsyms, bpf: Move find_kallsyms_symbol_value out of internal header
Bugzilla: https://bugzilla.redhat.com/2221599

Conflicts: missing kernel/module/internal.h

commit bd5314f8dd2d41330eecb60f0490c3fcfe1fc99d
Author: Viktor Malik <vmalik@redhat.com>
Date:   Fri Mar 17 10:56:01 2023 +0100

    kallsyms, bpf: Move find_kallsyms_symbol_value out of internal header

    Moving find_kallsyms_symbol_value from kernel/module/internal.h to
    include/linux/module.h. The reason is that internal.h is not prepared to
    be included when CONFIG_MODULES=n. find_kallsyms_symbol_value is used by
    kernel/bpf/verifier.c and including internal.h from it (without modules)
    leads into a compilation error:

      In file included from ../include/linux/container_of.h:5,
                       from ../include/linux/list.h:5,
                       from ../include/linux/timer.h:5,
                       from ../include/linux/workqueue.h:9,
                       from ../include/linux/bpf.h:10,
                       from ../include/linux/bpf-cgroup.h:5,
                       from ../kernel/bpf/verifier.c:7:
      ../kernel/bpf/../module/internal.h: In function 'mod_find':
      ../include/linux/container_of.h:20:54: error: invalid use of undefined type 'struct module'
         20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
            |                                                      ^~
      [...]

    This patch fixes the above error.

    Fixes: 31bf1dbccfb0 ("bpf: Fix attaching fentry/fexit/fmod_ret/lsm to modules")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Viktor Malik <vmalik@redhat.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/oe-kbuild-all/202303161404.OrmfCy09-lkp@intel.com/
    Link: https://lore.kernel.org/bpf/20230317095601.386738-1-vmalik@redhat.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>