regulator: tps65219: Fix matching interrupts for their regulators
JIRA: https://issues.redhat.com/browse/RHEL-46714

commit f050e56de80591fee55bedbdf5b6b998c740cd0c
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sun May 7 16:46:56 2023 +0200

    regulator: tps65219: Fix matching interrupts for their regulators

    The driver's probe() first registers regulators in a loop and then in a
    second loop passes them as irq data to the interrupt handlers.  However
    the function to get the regulator for given name
    tps65219_get_rdev_by_name() was a no-op due to argument passed by value,
    not pointer, thus the second loop assigned always same value - from
    previous loop.  The interrupts, when fired, where executed with wrong
    data.  Compiler also noticed it:

      drivers/regulator/tps65219-regulator.c: In function ‘tps65219_get_rdev_by_name’:
      drivers/regulator/tps65219-regulator.c:292:60: error: parameter ‘dev’ set but not used [-Werror=unused-but-set-parameter]

    Fixes: c12ac5fc3e0a ("regulator: drivers: Add TI TPS65219 PMIC regulators support")
    Cc: <stable@vger.kernel.org
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org
    Reviewed-by: Markus Schneider-Pargmann <msp@baylibre.com
    Link: https://lore.kernel.org/r/20230507144656.192800-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org

Signed-off-by: Enric Balletbo i Serra <eballetbo@redhat.com>