ASoC: amd: fix for soundwire build dependencies for legacy stack
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit 56437a561fefab2be708dfebf80e31c4715eb52e
Author: Vijendar Mukunda <Vijendar.Mukunda@amd.com>
Date: Mon Apr 8 23:32:26 2024 +0530

    ASoC: amd: fix for soundwire build dependencies for legacy stack

    The SND_SOC_AMD_SOUNDWIRE Kconfig symbol has build dependency on
    SOUNDWIRE_AMD. It gets it wrong for a configuration involving
    SND_SOC_AMD_SOUNDWIRE_LINK_BASELINE=y,SND_SOC_AMD_PS=y and SOUNDWIRE_AMD=m,
    which results in a link failure:

    ld: vmlinux.o: in function `amd_sdw_probe':
    >> sound/soc/amd/ps/pci-ps.c:271:(.text+0x1d51eff):
    	undefined reference to `sdw_amd_probe'
    ld: vmlinux.o: in function `acp63_sdw_machine_select':
    >> sound/soc/amd/ps/pci-ps.c:294:(.text+0x1d525d5):
    	undefined reference to `sdw_amd_get_slave_info'
    ld: vmlinux.o: in function `amd_sdw_exit':
    >> sound/soc/amd/ps/pci-ps.c:280:(.text+0x1d538ce):
    	undefined reference to `sdw_amd_exit'

    Add a top level check config that forbids any of the AMD ACP drivers
    with version >= 6.3 from being built-in with CONFIG_SOUNDWIRE_AMD=m.
    Move SND_AMD_ACP_CONFIG common dependency config to
    SND_SOC_AMD_ACP63_TOPLEVEL config.

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202404061257.khJml82D-lkp@intel.com/
    Fixes: a806793f231e ("ASoC: amd: simplify soundwire dependencies for legacy stack")
    Signed-off-by: Vijendar Mukunda <Vijendar.Mukunda@amd.com>
    Link: https://msgid.link/r/20240408180229.3287220-1-Vijendar.Mukunda@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>