rtnl: allocate more attr tables on the heap
JIRA: https://issues.redhat.com/browse/RHEL-30344

commit c92bf26ccebc8501863b38c4a4f65b8fef28ce5e
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Fri Apr 29 16:55:06 2022 -0700

    rtnl: allocate more attr tables on the heap

    Commit a293974590cf ("rtnetlink: avoid frame size warning in rtnl_newlink()")
    moved to allocating the largest attribute array of rtnl_newlink()
    on the heap. Kalle reports the stack has grown above 1k again:

      net/core/rtnetlink.c:3557:1: error: the frame size of 1104 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Move more attrs to the heap, wrap them in a struct.
    Don't bother with linkinfo, it's referenced a lot and we take
    its size so it's awkward to move, plus it's small (6 elements).

    Reported-by: Kalle Valo <kvalo@kernel.org>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>
    Tested-by: Kalle Valo <kvalo@kernel.org>
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>