iommu/amd: Fix compile error for unused function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-537.el8
commit-author Joerg Roedel <jroedel@suse.de>
commit 1ce018df87640adb139c8418785ad3b6e4376bd3

Recent changes introduced a compile error:

drivers/iommu/amd/iommu.c:1285:13: error: ‘iommu_flush_irt_and_complete’ defined but not used [-Werror=unused-function]
 1285 | static void iommu_flush_irt_and_complete(struct amd_iommu *iommu, u16 devid)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

This happens with defconfig-x86_64 because AMD IOMMU is enabled but
CONFIG_IRQ_REMAP is disabled. Move the function under #ifdef
CONFIG_IRQ_REMAP to fix the error.

	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 1ce018df87640adb139c8418785ad3b6e4376bd3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>