soc: ti: fix wkup_m3_rproc_boot_thread return type
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071830
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2071840
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  At this stage, this
 has been tested by ensuring we can survive the CI/CD loop -- i.e.,
 that we have not broken anything else, and a simple boot test.  When
 sufficient drivers have been brought in for i.MX8M, we will be able
 to run further tests.

commit f91140e4553408cacd326624cd50fc367725e04a
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 5 Nov 2021 08:51:12 +0100

    soc: ti: fix wkup_m3_rproc_boot_thread return type

    The wkup_m3_rproc_boot_thread() function uses a nonstandard prototype,
    which broke after Eric's recent cleanup:

    drivers/soc/ti/wkup_m3_ipc.c: In function 'wkup_m3_rproc_boot_thread':
    drivers/soc/ti/wkup_m3_ipc.c:429:16: error: 'return' with a value, in function returning void [-Werror=return-type]
      429 |         return 0;
          |                ^
    drivers/soc/ti/wkup_m3_ipc.c:416:13: note: declared here
      416 | static void wkup_m3_rproc_boot_thread(struct wkup_m3_ipc *m3_ipc)
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~

    Change it to the normal prototype as it should have been from the
    start.

    Fixes: 111e70490d2a ("exit/kthread: Have kernel threads return instead of calling do_exit")
    Fixes: cdd5de500b2c ("soc: ti: Add wkup_m3_ipc driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lkml.kernel.org/r/20211105075119.2327190-1-arnd@kernel.org
    Acked-by: Santosh Shilimkar <ssantosh@kernel.org>
    Acked-by: Tony Lindgren <tony@atomide.com>
    Signed-off-by: Eric W. Biederman <ebiederm@xmission.com>
    (cherry picked from commit f91140e4553408cacd326624cd50fc367725e04a)

Signed-off-by: Al Stone <ahs3@redhat.com>