x86/msr: Rename the WRMSRNS opcode macro to ASM_WRMSRNS (for KVM)
JIRA: https://issues.redhat.com/browse/RHEL-120168

commit 3fa0fc95db6df904dc812fa806a55ea6bafa65c1
Author: Sean Christopherson <seanjc@google.com>
Date:   Wed Feb 26 17:01:10 2025 -0800

    x86/msr: Rename the WRMSRNS opcode macro to ASM_WRMSRNS (for KVM)

    Rename the WRMSRNS instruction opcode macro so that it doesn't collide
    with X86_FEATURE_WRMSRNS when using token pasting to generate references
    to X86_FEATURE_WRMSRNS.  KVM heavily uses token pasting to generate KVM's
    set of support feature bits, and adding WRMSRNS support in KVM will run
    will run afoul of the opcode macro.

      arch/x86/kvm/cpuid.c:719:37: error: pasting "X86_FEATURE_" and "" "" does not
                                          give a valid preprocessing token
      719 |         u32 __leaf = __feature_leaf(X86_FEATURE_##name);                \
          |                                     ^~~~~~~~~~~~

    KVM has worked around one such collision in the past by #undef'ing the
    problematic macro in order to avoid blocking a KVM rework, but such games
    are generally undesirable, e.g. requires bleeding macro details into KVM,
    risks weird behavior if what KVM is #undef'ing changes, etc.

    Reviewed-by: Xin Li (Intel) <xin@zytor.com>
    Link: https://lore.kernel.org/r/20250227010111.3222742-2-seanjc@google.com
    Signed-off-by: Sean Christopherson <seanjc@google.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>