usb: chipidea: core: wrap ci_handle_power_lost() with CONFIG_PM_SLEEP
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2190250
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dced88922c1179dfa2664690318d4cba57ebffb5

commit dced88922c1179dfa2664690318d4cba57ebffb5
Author: Xu Yang <xu.yang_2@nxp.com>
Date: Wed, 26 Oct 2022 20:11:57 +0800

  If CONFIG_PM_SLEEP is not set, the following error will be shown up
  when build kernel:
      error: 'ci_handle_power_lost' defined but not used.

  This will move ci_handle_power_lost() to an area wrapped by
  CONFIG_PM_SLEEP.

  Signed-off-by: Xu Yang <xu.yang_2@nxp.com>
  Fixes: 74494b33211d ("usb: chipidea: core: add controller resume support when controller is powered off")
  Reported-by: Conor Dooley <conor.dooley@microchip.com>
  Tested-by: Conor Dooley <conor.dooley@microchip.com>
  Link: https://lore.kernel.org/r/20221026121157.1491302-1-xu.yang_2@nxp.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>