usb: typec: tps6598x: Fix build error without CONFIG_REGMAP_I2C
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author YueHaibing <yuehaibing@huawei.com>
commit 35af2445dc306403254a181507b390ec9eb725d5

If CONFIG_REGMAP_I2C is not set, building fails:

drivers/usb/typec/tps6598x.o: In function `tps6598x_probe':
tps6598x.c:(.text+0x5f0): undefined reference to `__devm_regmap_init_i2c'

Select REGMAP_I2C to fix this.

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 0a4c005bd171 ("usb: typec: driver for TI TPS6598x USB Power Delivery controllers")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Link: https://lore.kernel.org/r/20190903121026.22148-1-yuehaibing@huawei.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 35af2445dc306403254a181507b390ec9eb725d5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>