ipv4/route: avoid unused-but-set-variable warning
JIRA: https://issues.redhat.com/browse/RHEL-116117
Upstream Status: linux.git

commit cf1b7201df59fb936f40f4a807433fe3f2ce310a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Apr 8 09:42:03 2024 +0200

    ipv4/route: avoid unused-but-set-variable warning

    The log_martians variable is only used in an #ifdef, causing a 'make W=1'
    warning with gcc:

    net/ipv4/route.c: In function 'ip_rt_send_redirect':
    net/ipv4/route.c:880:13: error: variable 'log_martians' set but not used [-Werror=unused-but-set-variable]

    Change the #ifdef to an equivalent IS_ENABLED() to let the compiler
    see where the variable is used.

    Fixes: 30038fc61adf ("net: ip_rt_send_redirect() optimization")
    Reviewed-by: David Ahern <dsahern@kernel.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Eric Dumazet <edumazet@google.com>
    Link: https://lore.kernel.org/r/20240408074219.3030256-2-arnd@kernel.org
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Guillaume Nault <gnault@redhat.com>