perf clang: Fixes for more recent LLVM/clang
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit 32f7aa2731b24ad8393f26d63df959d74844345f
Author: Ian Rogers <irogers@google.com>
Date: Mon Oct 11 19:13:21 2021 -0700

description
===========
The parameters to two functions and the location of a variable have
changed in more recent LLVM/clang releases.

Remove the unneecessary -fmessage-length and -ferror-limit flags, the
former causes failures like:

  58: builtin clang support                                           :
  58.1: builtin clang compile C source to IR                          :
  --- start ---
  test child forked, pid 279307
  error: unknown argument: '-fmessage-length'
  1 error generated.
  test child finished with -1

Tested with LLVM 6, 8, 9, 10 and 11.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>