revert bus: Make remove callback return void
Description: This reverts RHEL 9.1 commit 67a522698e287818a2bafa69f05458ab529ac6fc

The above commit caused the following error on the automotive build

The following build error:

drivers/rpmsg/rpmsg_core.c:592:27: error: initialization of 'int (*)(struct device *)'
from incompatible pointer type 'void (*)(struct device *)'
[-Werror=incompatible-pointer-types]
  592 |         .remove         = rpmsg_dev_remove,
      |                           ^~~~~~~~~~~~~~~~

Bugzilla: http://bugzilla.redhat.com/2097921

Upstream status: RHEL only

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46030617

Tested: testing with the automotive configs on

CONFIG_RPMSG_QCOM_GLINK_RPM=m
CONFIG_RPMSG_QCOM_GLINK_SMEM=m
CONFIG_RPMSG_QCOM_SMD=m

the above modules build and I was able to sanity testing each module listed
below.

[root@ampere-hr350a-05 rpmsg]# ls
qcom_glink.ko.xz  qcom_glink_rpm.ko.xz    rpmsg_core.ko.xz

Conflicts: Only take drivers/rpmsg hunk

commit fc7a6209d5710618eb4f72a77cd81b8d694ecf89
Author: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Date:   Tue Jul 13 21:35:22 2021 +0200

    bus: Make remove callback return void

    The driver core ignores the return value of this callback because there
    is only little it can do when a device disappears.

    This is the final bit of a long lasting cleanup quest where several
    buses were converted to also return void from their remove callback.
    Additionally some resource leaks were fixed that were caused by drivers
    returning an error code in the expectation that the driver won't go
    away.

    With struct bus_type::remove returning void it's prevented that newly
    implemented buses return an ignored error code and so don't anticipate
    wrong expectations for driver authors.

    Reviewed-by: Tom Rix <trix@redhat.com> (For fpga)
    Reviewed-by: Mathieu Poirier <mathieu.poirier@linaro.org>
    Reviewed-by: Cornelia Huck <cohuck@redhat.com> (For drivers/s390 and drivers/vfio)
    Acked-by: Russell King (Oracle) <rmk+kernel@armlinux.org.uk> (For ARM, Amba and related parts)
    Acked-by: Mark Brown <broonie@kernel.org>
    Acked-by: Chen-Yu Tsai <wens@csie.org> (for sunxi-rsb)
    Acked-by: Pali Rohár <pali@kernel.org>
    Acked-by: Mauro Carvalho Chehab <mchehab@kernel.org> (for media)
    Acked-by: Hans de Goede <hdegoede@redhat.com> (For drivers/platform)
    Acked-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
    Acked-By: Vinod Koul <vkoul@kernel.org>
    Acked-by: Juergen Gross <jgross@suse.com> (For xen)
    Acked-by: Lee Jones <lee.jones@linaro.org> (For mfd)
    Acked-by: Johannes Thumshirn <jth@kernel.org> (For mcb)
    Acked-by: Johan Hovold <johan@kernel.org>
    Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org> (For slimbus)
    Acked-by: Kirti Wankhede <kwankhede@nvidia.com> (For vfio)
    Acked-by: Maximilian Luz <luzmaximilian@gmail.com>
    Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com> (For ulpi and typec)
    Acked-by: Samuel Iglesias Gonsálvez <siglesias@igalia.com> (For ipack)
    Acked-by: Geoff Levand <geoff@infradead.org> (For ps3)
    Acked-by: Yehezkel Bernat <YehezkelShB@gmail.com> (For thunderbolt)
    Acked-by: Alexander Shishkin <alexander.shishkin@linux.intel.com> (For intel_th)
    Acked-by: Dominik Brodowski <linux@dominikbrodowski.net> (For pcmcia)
    Acked-by: Rafael J. Wysocki <rafael@kernel.org> (For ACPI)
    Acked-by: Bjorn Andersson <bjorn.andersson@linaro.org> (rpmsg and apr)
    Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com> (For intel-ish-hid)
    Acked-by: Dan Williams <dan.j.williams@intel.com> (For CXL, DAX, and NVDIMM)
    Acked-by: William Breathitt Gray <vilhelm.gray@gmail.com> (For isa)
    Acked-by: Stefan Richter <stefanr@s5r6.in-berlin.de> (For firewire)
    Acked-by: Benjamin Tissoires <benjamin.tissoires@redhat.com> (For hid)
    Acked-by: Thorsten Scherer <t.scherer@eckelmann.de> (For siox)
    Acked-by: Sven Van Asbroeck <TheSven73@gmail.com> (For anybuss)
    Acked-by: Ulf Hansson <ulf.hansson@linaro.org> (For MMC)
    Acked-by: Wolfram Sang <wsa@kernel.org> # for I2C
    Acked-by: Sudeep Holla <sudeep.holla@arm.com>
    Acked-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Acked-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Acked-by: Finn Thain <fthain@linux-m68k.org>
    Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
    Link: https://lore.kernel.org/r/20210713193522.1770306-6-u.kleine-koenig@pengutronix.de
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Steve Best <sbest@redhat.com>