s390/cert_store: select CRYPTO_LIB_SHA256
JIRA: https://issues.redhat.com/browse/RHEL-54248

commit 481daa505bc3eb4ac7991e2e7a981506639935fd
Author: Sven Schnelle <svens@linux.ibm.com>
Date:   Fri Jul 28 12:04:30 2023 +0200

    s390/cert_store: select CRYPTO_LIB_SHA256

    A build failure was reported when sha256() is not present:

    gcc-13.1.0-nolibc/s390-linux/bin/s390-linux-ld: arch/s390/kernel/cert_store.o: in function `check_certificate_hash':
    arch/s390/kernel/cert_store.c:267: undefined reference to `sha256'

    Therefore make CONFIG_CERT_STORE select CRYPTO_LIB_SHA256.

    Fixes: 8cf57d7217c3 ("s390: add support for user-defined certificates")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Closes: https://lore.kernel.org/all/8ecb57fb-4560-bdfc-9e55-63e3b0937132@infradead.org/
    Signed-off-by: Sven Schnelle <svens@linux.ibm.com>
    Tested-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Link: https://lore.kernel.org/r/20230728100430.1567328-1-svens@linux.ibm.com
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>