sunvnet: fix sparc64 build error after gso code split
JIRA: https://issues.redhat.com/browse/RHEL-12679

commit d9ffa069e006fa2873b94fbf2387546942d4f85b
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Tue Jun 13 16:46:39 2023 +1000

    sunvnet: fix sparc64 build error after gso code split

    After merging the net-next tree, today's linux-next build (sparc64
    defconfig) failed like this:

    drivers/net/ethernet/sun/sunvnet_common.c: In function 'vnet_handle_offloads':
    drivers/net/ethernet/sun/sunvnet_common.c:1277:16: error: implicit declaration of function 'skb_gso_segment'; did you mean 'skb_gso_reset'? [-Werror=implicit-function-declaration]
     1277 |         segs = skb_gso_segment(skb, dev->features & ~NETIF_F_TSO);
          |                ^~~~~~~~~~~~~~~
          |                skb_gso_reset
    drivers/net/ethernet/sun/sunvnet_common.c:1277:14: warning: assignment to 'struct sk_buff *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     1277 |         segs = skb_gso_segment(skb, dev->features & ~NETIF_F_TSO);
          |              ^

    Fixes: d457a0e329b0 ("net: move gso declarations and functions to their own files")
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Link: https://lore.kernel.org/r/20230613164639.164b2991@canb.auug.org.au
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>