ASoc: amd: acp3x: Add missing include <linux/io.h>
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoc: amd: acp3x: Add missing include <linux/io.h> (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 94.34%
commit-author YueHaibing <yuehaibing@huawei.com>
commit 14beaccc36dc9c1afbe6da627b873bf1d6849234

gcc 7.4.0 build fails:

In file included from sound/soc/amd/acp3x-rt5682-max9836.c:20:0:
sound/soc/amd/raven/acp3x.h: In function rv_readl:
sound/soc/amd/raven/acp3x.h:113:9: error: implicit declaration of function readl; did you mean rv_readl? [-Werror=implicit-function-declaration]
  return readl(base_addr - ACP3x_PHY_BASE_ADDRESS);
         ^~~~~
         rv_readl
sound/soc/amd/raven/acp3x.h: In function rv_writel:
sound/soc/amd/raven/acp3x.h:118:2: error: implicit declaration of function writel; did you mean rv_writel? [-Werror=implicit-function-declaration]
  writel(val, base_addr - ACP3x_PHY_BASE_ADDRESS);
  ^~~~~~
  rv_writel

Add <linux/io.h> to fix this.

Fixes: 6b8e4e7db3cd ("ASoC: amd: Add machine driver for Raven based platform")
	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Message-Id: <20200304084057.44764-1-yuehaibing@huawei.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 14beaccc36dc9c1afbe6da627b873bf1d6849234)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>