net_sched: sch_sfq: reject invalid perturb period
JIRA: https://issues.redhat.com/browse/RHEL-96604
CVE: CVE-2025-38193
Upstream Status: net-next.git commit 7ca52541c05c832d32b112274f81a985101f9ba8

commit 7ca52541c05c832d32b112274f81a985101f9ba8
Author: Eric Dumazet <edumazet@google.com>
Date:   Wed Jun 11 08:35:01 2025 +0000

    net_sched: sch_sfq: reject invalid perturb period

    Gerrard Tai reported that SFQ perturb_period has no range check yet,
    and this can be used to trigger a race condition fixed in a separate patch.

    We want to make sure ctl->perturb_period * HZ will not overflow
    and is positive.

    Tested:

    tc qd add dev lo root sfq perturb -10   # negative value : error
    Error: sch_sfq: invalid perturb period.

    tc qd add dev lo root sfq perturb 1000000000 # too big : error
    Error: sch_sfq: invalid perturb period.

    tc qd add dev lo root sfq perturb 2000000 # acceptable value
    tc -s -d qd sh dev lo
    qdisc sfq 8005: root refcnt 2 limit 127p quantum 64Kb depth 127 flows 128 divisor 1024 perturb 2000000sec
     Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
     backlog 0b 0p requeues 0

    Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
    Reported-by: Gerrard Tai <gerrard.tai@starlabs.sg>
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Cc: stable@vger.kernel.org
    Link: https://patch.msgid.link/20250611083501.1810459-1-edumazet@google.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>