wifi: ipw2x00: remove unused _ipw_read16 function
Bugzilla: https://bugzilla.redhat.com/2196821

commit c7e39d70613c113b5ac667beeb3cacb242c6a4cb
Author: Tom Rix <trix@redhat.com>
Date:   Sun Mar 19 09:54:18 2023 -0400

    wifi: ipw2x00: remove unused _ipw_read16 function
    
    clang with W=1 reports
    drivers/net/wireless/intel/ipw2x00/ipw2200.c:381:19: error:
      unused function '_ipw_read16' [-Werror,-Wunused-function]
    static inline u16 _ipw_read16(struct ipw_priv *ipw, unsigned long ofs)
                      ^
    This function and its wrapping marco are not used, so remove them.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230319135418.1703380-1-trix@redhat.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>