scsi: qla2xxx: Simplify the functions for dumping firmware
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Bart Van Assche <bvanassche@acm.org>
commit 8ae178760b23e2055aecf8b8a54629cec7ccc58e

Instead of passing an argument to the firmware dumping functions that tells
these functions whether or not to obtain the hardware lock, obtain that
lock before calling these functions. This patch fixes the following
recently introduced C=2 build error:

  CHECK   drivers/scsi/qla2xxx/qla_tmpl.c
drivers/scsi/qla2xxx/qla_tmpl.c:1133:1: error: Expected ; at end of statement
drivers/scsi/qla2xxx/qla_tmpl.c:1133:1: error: got }
drivers/scsi/qla2xxx/qla_tmpl.h:247:0: error: Expected } at end of function
drivers/scsi/qla2xxx/qla_tmpl.h:247:0: error: got end-of-input

Link: https://lore.kernel.org/r/20200518211712.11395-4-bvanassche@acm.org
Fixes: cbb01c2f2f63 ("scsi: qla2xxx: Fix MPI failure AEN (8200) handling")
	Cc: Arun Easi <aeasi@marvell.com>
	Cc: Nilesh Javali <njavali@marvell.com>
	Cc: Himanshu Madhani <himanshu.madhani@oracle.com>
	Cc: Martin Wilck <mwilck@suse.com>
	Cc: Roman Bolshakov <r.bolshakov@yadro.com>
	Reviewed-by: Hannes Reinecke <hare@suse.de>
	Reviewed-by: Daniel Wagner <dwagner@suse.de>
	Signed-off-by: Bart Van Assche <bvanassche@acm.org>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 8ae178760b23e2055aecf8b8a54629cec7ccc58e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>