ASoC: codecs: adau1977-spi: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2179848

commit a9048d64fb9605eb68c9912724e4a1346db8ba1a
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Fri Mar 10 22:43:29 2023 +0100

    ASoC: codecs: adau1977-spi: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      sound/soc/codecs/adau1977-spi.c:58:34: error: ‘adau1977_spi_of_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214333.274903-6-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>