accel/amdxdna: Return error when setting clock failed for npu1
JIRA: https://redhat.atlassian.net/browse/RHEL-222546
Upstream Status: v6.15-rc1

commit 0c2768bf818904db705ff18674f771c3c4d8bbca
Author:     Lizhi Hou <lizhi.hou@amd.com>
AuthorDate: Thu Jan  9 11:48:11 2025 -0800
Commit:     Mario Limonciello <mario.limonciello@amd.com>
CommitDate: Thu Jan  9 13:53:22 2025 -0600
    
    Due to miss returning error when setting clock, the smatch static
    checker reports warning:
      drivers/accel/amdxdna/aie2_smu.c:68 npu1_set_dpm()
      error: uninitialized symbol 'freq'.
    
    Fixes: f4d7b8a6bc8c ("accel/amdxdna: Enhance power management settings")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/dri-devel/202267d0-882e-4593-b58d-be9274592f9b@stanley.mountain/
    Signed-off-by: Lizhi Hou <lizhi.hou@amd.com>
    Reviewed-by: Mario Limonciello <mario.limonciello@amd.com>
    Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20250109194811.499505-1-lizhi.hou@amd.com

Signed-off-by: Peter Colberg <pcolberg@redhat.com>