Revert "ice: Fix ice VF reset during iavf initialization"
JIRA: https://issues.redhat.com/browse/RHEL-141485

commit 0ecff05e6c59dd82dbcb9706db911f7fd9f40fb8
Author: Petr Oros <poros@redhat.com>
Date:   Fri Aug 11 10:07:01 2023 +0200

    Revert "ice: Fix ice VF reset during iavf initialization"

    This reverts commit 7255355a0636b4eff08d5e8139c77d98f151c4fc.

    After this commit we are not able to attach VF to VM:
    virsh attach-interface v0 hostdev --managed 0000:41:01.0 --mac 52:52:52:52:52:52
    error: Failed to attach interface
    error: Cannot set interface MAC to 52:52:52:52:52:52 for ifname enp65s0f0np0 vf 0: Resource temporarily unavailable

    ice_check_vf_ready_for_cfg() already contain waiting for reset.
    New condition in ice_check_vf_ready_for_reset() causing only problems.

    Fixes: 7255355a0636 ("ice: Fix ice VF reset during iavf initialization")
    Signed-off-by: Petr Oros <poros@redhat.com>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Reviewed-by: Przemek Kitszel <przemyslaw.kitszel@intel.com>
    Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>
    Tested-by: Rafal Romanowski <rafal.romanowski@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>