misc: rtsx: conditionally build rtsx_pm_power_saving()
Bugzilla: http://bugzilla.redhat.com/2120778

commit 2c9ae453543c9a3c08840cc4a51a054ebc4e75bf
Author: Tom Rix <trix@redhat.com>
Date:   Sun Feb 13 09:19:07 2022 -0800

    misc: rtsx: conditionally build rtsx_pm_power_saving()

    On s390 allyesconfig, there is this build error
    rtsx_pcr.c:1084:13: error: 'rtsx_pm_power_saving'
      defined but not used
     1084 | static void rtsx_pm_power_saving(struct rtsx_pcr *pcr)
          |             ^~~~~~~~~~~~~~~~~~~~

    rtsx_pm_power_saving() is only used by rtsx_pci_runtime_idle()
    which is conditional on CONFIG_PM.  So conditionally build
    rtsx_pm_power_saving() and the similar
    rtsx_comm_pm_power_saving() and rtsx_enable_aspm().

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20220213171907.2786442-1-trix@redhat.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Mark Pearson <mapearso@redhat.com>