iommu/mediatek: Fix MTK_IOMMU dependencies
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit d1dcb7255c2b0ae77fbe297e4543c6cfff54e9b9
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/d1dcb725.failed

If NO_DMA=y (e.g. Sun-3 all{mod,yes}-config):

    drivers/iommu/dma-iommu.o: In function `iommu_dma_mmap':
    dma-iommu.c:(.text+0x836): undefined reference to `dma_pgprot'

IOMMU_DMA must not be selected, unless HAS_DMA=y.

Hence fix this by making MTK_IOMMU depend on HAS_DMA.
While at it, remove the dependency on ARM || ARM64, as that is already
implied by the dependency on ARCH_MEDIATEK.

Fixes: e93a1695d7fb5513 ("iommu: Enable compile testing for some of drivers")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/r/20200410143047.19691-1-geert@linux-m68k.org
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit d1dcb7255c2b0ae77fbe297e4543c6cfff54e9b9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/iommu/Kconfig