ASoC: qcom: SND_SOC_SC7180 optionally depends on SOUNDWIRE
Bugzilla: https://bugzilla.redhat.com/2179848

commit 9a7f2c9e7a19b16b4409f372cf2e16e4334cdca2
Author: Randy Dunlap <rdunlap@infradead.org>
Date: Fri Oct 14 17:12:28 2022 -0700

    ASoC: qcom: SND_SOC_SC7180 optionally depends on SOUNDWIRE

    If SOUNDWIRE is enabled, then SND_SOC_SC7180 should depend on
    SOUNDWIRE to prevent SOUNDWIRE=m and SND_SOC_SC7180=y, which causes
    build errors:

    s390-linux-ld: sound/soc/qcom/common.o: in function `qcom_snd_sdw_prepare':
    common.c:(.text+0x140): undefined reference to `sdw_disable_stream'
    s390-linux-ld: common.c:(.text+0x14a): undefined reference to `sdw_deprepare_stream'
    s390-linux-ld: common.c:(.text+0x158): undefined reference to `sdw_prepare_stream'
    s390-linux-ld: common.c:(.text+0x16a): undefined reference to `sdw_enable_stream'
    s390-linux-ld: common.c:(.text+0x17c): undefined reference to `sdw_deprepare_stream'
    s390-linux-ld: sound/soc/qcom/common.o: in function `qcom_snd_sdw_hw_free':
    common.c:(.text+0x344): undefined reference to `sdw_disable_stream'
    s390-linux-ld: common.c:(.text+0x34e): undefined reference to `sdw_deprepare_stream'

    Fixes: 3bd975f3ae0a ("ASoC: qcom: sm8250: move some code to common")
    Fixes: 9e3ecb5b1681 ("ASoC: qcom: sc7180: Add machine driver for sound card registration")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
    Cc: Banajit Goswami <bgoswami@quicinc.com>
    Cc: Mark Brown <broonie@kernel.org>
    Cc: Liam Girdwood <lgirdwood@gmail.com>
    Cc: Ajit Pandey <ajitp@codeaurora.org>
    Cc: Cheng-Yi Chiang <cychiang@chromium.org>
    Cc: Jaroslav Kysela <perex@perex.cz>
    Cc: Takashi Iwai <tiwai@suse.com>
    Cc: stable@vger.kernel.org
    Cc: alsa-devel@alsa-project.org
    Link: https://lore.kernel.org/r/20221015001228.18990-1-rdunlap@infradead.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>