wifi: ath11k: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 6763ef191d672ff3c2db0622652d49b0c0a60c4a
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Thu Aug 10 11:12:23 2023 +0200

    wifi: ath11k: fix Wvoid-pointer-to-enum-cast warning
    
    'hw_rev' is an enum, thus cast of pointer on 64-bit compile test with W=1
    causes:
    
      h11k/ahb.c:1124:11: error: cast to smaller integer type 'enum ath11k_hw_rev' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]
    
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Acked-by: Jeff Johnson <quic_jjohnson@quicinc.com>
    Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
    Link: https://lore.kernel.org/r/20230810091224.70088-1-krzysztof.kozlowski@linaro.org

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>