media: pvrusb2: VIDEO_PVRUSB2 depends on DVB_CORE to use dvb_* symbols
JIRA: https://issues.redhat.com/browse/RHEL-13058
Conflicts:
* Avoiding treewide commit <9958d30f38b9> ("media: Kconfig: cleanup
  VIDEO_DEV dependencies")

commit 1107283b3351bef138cd12dbda1f999891cab7db
Author: Tom Rix <trix@redhat.com>
Date: Sat, 11 Mar 2023 14:48:47 +0100

  A rand config causes this link error
  vmlinux.o: In function `pvr2_dvb_create':
  (.text+0x8af1d2): undefined reference to `dvb_register_adapter'

  The rand config has
  CONFIG_VIDEO_PVRUSB2=y
  CONFIG_VIDEO_DEV=y
  CONFIG_DVB_CORE=m

  VIDEO_PVRUSB2 should also depend on DVB_CORE.

  Signed-off-by: Tom Rix <trix@redhat.com>
  Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
  Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>