x86/fpu: Include asm/fpu/regset.h
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 16db7e9c6e974a0935494cd31179c819d4cbf86e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:35 2023 +0200

    x86/fpu: Include asm/fpu/regset.h

    The fpregs_soft_set/fpregs_soft_get functions are declared in a
    header that is not included in the file that defines them, causing
    a W=1 warning:

    /home/arnd/arm-soc/arch/x86/math-emu/fpu_entry.c:638:5: error: no previous prototype for 'fpregs_soft_set' [-Werror=missing-prototypes]
      638 | int fpregs_soft_set(struct task_struct *target,
          |     ^~~~~~~~~~~~~~~
    /home/arnd/arm-soc/arch/x86/math-emu/fpu_entry.c:690:5: error: no previous prototype for 'fpregs_soft_get' [-Werror=missing-prototypes]
      690 | int fpregs_soft_get(struct task_struct *target,

    Include the file here to avoid the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-7-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>