genirq: Export handle_bad_irq
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 9d67dc5da59d63f746aad8f6ec4fbb86d6486f76

A cleanup of the omap gpio driver introduced a use of the
handle_bad_irq() function in a device driver that can be
a loadable module.

This broke the ARM allmodconfig build:

ERROR: "handle_bad_irq" [drivers/gpio/gpio-omap.ko] undefined!

This patch exports the handle_bad_irq symbol in order to
allow the use in modules.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Cc: Grygorii Strashko <grygorii.strashko@ti.com>
	Cc: Santosh Shilimkar <ssantosh@kernel.org>
	Cc: Linus Walleij <linus.walleij@linaro.org>
	Cc: Austin Schuh <austin@peloton-tech.com>
	Cc: Tony Lindgren <tony@atomide.com>
	Cc: linux-arm-kernel@lists.infradead.org
Link: http://lkml.kernel.org/r/5847725.4IBopItaOr@wuerfel
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

(cherry picked from commit 9d67dc5da59d63f746aad8f6ec4fbb86d6486f76)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>