crypto: ccp - Fix dereferencing uninitialized error pointer
jira KERNEL-318
Rebuild_History Non-Buildable kernel-6.12.0-124.20.1.el10_1
commit-author Ashish Kalra <ashish.kalra@amd.com>
commit 0fa766726c091ff0ec7d26874f6e4724d23ecb0e

Fix below smatch warnings:
drivers/crypto/ccp/sev-dev.c:1312 __sev_platform_init_locked()
error: we previously assumed 'error' could be null

Fixes: 9770b428b1a2 ("crypto: ccp - Move dev_info/err messages for SEV/SNP init and shutdown")
	Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Closes: https://lore.kernel.org/r/202505071746.eWOx5QgC-lkp@intel.com/
	Signed-off-by: Ashish Kalra <ashish.kalra@amd.com>
	Reviewed-by: Tom Lendacky <thomas.lendacky@amd.com>
	Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 0fa766726c091ff0ec7d26874f6e4724d23ecb0e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>