ASoC: SOF: Intel: fix build issue related to CODEC_PROBE_ENTRIES
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-372.9.1.el8
commit-author Kai Vehmanen <kai.vehmanen@linux.intel.com>
commit 9a83dfcc5ae8230fbf12b63e281d5bb8450ec0e7

Fix following error:
sound/soc/sof/intel/hda-codec.c:132:35: error: use of undeclared identifier 'CODEC_PROBE_RETRIES'

Found with config: i386-randconfig-r033-20211202
(https://download.01.org/0day-ci/archive/20211203/202112031943.Twg19fWT-lkp@intel.com/config)

Fixes: 046aede2f847 ("ASoC: SOF: Intel: Retry codec probing if it fails")
	Reported-by: kernel test robot <lkp@intel.com>
	Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Link: https://lore.kernel.org/r/20211203154721.923496-1-kai.vehmanen@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9a83dfcc5ae8230fbf12b63e281d5bb8450ec0e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>