kunit: tool: show list of valid --arch options when invalid
commit fe678fed2cda4c74d016171dce290b792b036663
Author: Daniel Latypov <dlatypov@google.com>
Date:   Wed Sep 29 16:25:34 2021 -0700

    kunit: tool: show list of valid --arch options when invalid

    Consider this attempt to run KUnit in QEMU:
    $ ./tools/testing/kunit/kunit.py run --arch=x86

    Before you'd get this error message:
    kunit_kernel.ConfigError: x86 is not a valid arch

    After:
    kunit_kernel.ConfigError: x86 is not a valid arch, options are ['alpha', 'arm', 'arm64', 'i386', 'powerpc', 'riscv', 's390', 'sparc', 'x86_64']

    This should make it a bit easier for people to notice when they make
    typos, etc. Currently, one would have to dive into the python code to
    figure out what the valid set is.

    Signed-off-by: Daniel Latypov <dlatypov@google.com>
    Reviewed-by: David Gow <davidgow@google.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2168378
Signed-off-by: Nico Pache <npache@redhat.com>