wifi: ath12k: fix one more memcpy size error
JIRA: https://issues.redhat.com/browse/RHEL-73819

commit 19c23eb61fa4c802e6e0aaf74d6f7dcbe99f0ba3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Oct 4 09:54:13 2024 +0000

    wifi: ath12k: fix one more memcpy size error
    
    A previous patch addressed a fortified-memcpy warning on older compilers,
    but there is still a warning on gcc-14 in some configurations:
    
    In file included from include/linux/string.h:390,
                     from drivers/net/wireless/ath/ath12k/wow.c:7:
    drivers/net/wireless/ath/ath12k/wow.c: In function 'ath12k_wow_convert_8023_to_80211.isra':
    include/linux/fortify-string.h:114:33: error: '__builtin_memcpy' accessing 18446744073709551610 or more bytes at offsets 0 and 0 overlaps 9223372036854775797 bytes at offset -9223372036854775803 [-Werror=restrict]
    include/linux/fortify-string.h:679:26: note: in expansion of macro '__fortify_memcpy_chk'
      679 | #define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                  \
          |                          ^~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/ath/ath12k/wow.c:199:25: note: in expansion of macro 'memcpy'
      199 |                         memcpy(pat + a3_ofs - pkt_ofs,
          |                         ^~~~~~
    
    Address this the same way as the other two, using size_add().
    
    Fixes: b49991d83bba ("wifi: ath12k: fix build vs old compiler")
    Fixes: 4a3c212eee0e ("wifi: ath12k: add basic WoW functionalities")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Kalle Valo <kvalo@kernel.org>
    Link: https://patch.msgid.link/20241004095420.637091-1-arnd@kernel.org
    Signed-off-by: Jeff Johnson <quic_jjohnson@quicinc.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>