mei: amthif: fix checkpatch error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Tomas Winkler <tomas.winkler@intel.com>
commit 34e267d0f49ef4c54eb7b2abbb1b001fa6f26f0e

ERROR: else should follow close brace '}'
+	}
+	else {

	Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 34e267d0f49ef4c54eb7b2abbb1b001fa6f26f0e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>