vsock/uapi: fix linux/vm_sockets.h userspace compilation errors
JIRA: https://issues.redhat.com/browse/RHEL-185312

commit 22bbc1dcd0d6785fb390c41f0dd5b5e218d23bdd
Author: Stefano Garzarella <sgarzare@redhat.com>
Date:   Mon Jun 23 12:00:53 2025 +0200

    vsock/uapi: fix linux/vm_sockets.h userspace compilation errors

    If a userspace application just include <linux/vm_sockets.h> will fail
    to build with the following errors:

        /usr/include/linux/vm_sockets.h:182:39: error: invalid application of ‘sizeof’ to incomplete type ‘struct sockaddr’
          182 |         unsigned char svm_zero[sizeof(struct sockaddr) -
              |                                       ^~~~~~
        /usr/include/linux/vm_sockets.h:183:39: error: ‘sa_family_t’ undeclared here (not in a function)
          183 |                                sizeof(sa_family_t) -
              |

    Include <sys/socket.h> for userspace (guarded by ifndef __KERNEL__)
    where `struct sockaddr` and `sa_family_t` are defined.
    We already do something similar in <linux/mptcp.h> and <linux/if.h>.

    Fixes: d021c344051a ("VSOCK: Introduce VM Sockets")
    Reported-by: Daan De Meyer <daan.j.demeyer@gmail.com>
    Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
    Link: https://patch.msgid.link/20250623100053.40979-1-sgarzare@redhat.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>