dma-mapping: move arch_dma_set_mask() declaration to header
JIRA: https://issues.redhat.com/browse/RHEL-10094
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 3d6f126b15d9fd8435455fffc912d976973a7a09
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jul 27 14:25:42 2023 +0200

    dma-mapping: move arch_dma_set_mask() declaration to header

    This function has a __weak definition and an override that is only used on
    freescale powerpc chips. The powerpc definition however does not see the
    declaration that is in a .c file:

    arch/powerpc/kernel/dma-mask.c:7:6: error: no previous prototype for 'arch_dma_set_mask' [-Werror=missing-prototypes]

    Move it into the linux/dma-map-ops.h header where the other arch_dma_* functions
    are declared.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Christoph Hellwig <hch@lst.de>

(cherry picked from commit 3d6f126b15d9fd8435455fffc912d976973a7a09)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>