x86/pci: Mark local functions as 'static'
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 0253b04d5b2683f5a4fdcf655b1cae6739d5ab30
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 21:35:31 2023 +0200

    x86/pci: Mark local functions as 'static'

    Two functions in this file are global but have no prototype in
    a header and are not called from elsewhere, so they should
    be static:

    arch/x86/pci/ce4100.c:86:6: error: no previous prototype for 'sata_revid_init' [-Werror=missing-prototypes]
    arch/x86/pci/ce4100.c:175:5: error: no previous prototype for 'bridge_read' [-Werror=missing-prototypes]

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
    Reviewed-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://lore.kernel.org/all/20230516193549.544673-3-arnd%40kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>