nbd: use shifts rather than multiplies
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2018403

commit 41e76c6a3c83c85e849f10754b8632ea763d9be4
Author: Nick Desaulniers <ndesaulniers@google.com>
Date:   Mon Sep 20 16:25:33 2021 -0700

    nbd: use shifts rather than multiplies

    commit fad7cd3310db ("nbd: add the check to prevent overflow in
    __nbd_ioctl()") raised an issue from the fallback helpers added in
    commit f0907827a8a9 ("compiler.h: enable builtin overflow checkers and
    add fallback code")

    ERROR: modpost: "__divdi3" [drivers/block/nbd.ko] undefined!

    As Stephen Rothwell notes:
      The added check_mul_overflow() call is being passed 64 bit values.
      COMPILER_HAS_GENERIC_BUILTIN_OVERFLOW is not set for this build (see
      include/linux/overflow.h).

    Specifically, the helpers for checking whether the results of a
    multiplication overflowed (__unsigned_mul_overflow,
    __signed_add_overflow) use the division operator when
    !COMPILER_HAS_GENERIC_BUILTIN_OVERFLOW.  This is problematic for 64b
    operands on 32b hosts.

    This was fixed upstream by
    commit 76ae847497bc ("Documentation: raise minimum supported version of
    GCC to 5.1")
    which is not suitable to be backported to stable.

    Further, __builtin_mul_overflow() would emit a libcall to a
    compiler-rt-only symbol when compiling with clang < 14 for 32b targets.

    ld.lld: error: undefined symbol: __mulodi4

    In order to keep stable buildable with GCC 4.9 and clang < 14, modify
    struct nbd_config to instead track the number of bits of the block size;
    reconstructing the block size using runtime checked shifts that are not
    problematic for those compilers and in a ways that can be backported to
    stable.

    In nbd_set_size, we do validate that the value of blksize must be a
    power of two (POT) and is in the range of [512, PAGE_SIZE] (both
    inclusive).

    This does modify the debugfs interface.

    Cc: stable@vger.kernel.org
    Cc: Arnd Bergmann <arnd@kernel.org>
    Cc: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Link: https://github.com/ClangBuiltLinux/linux/issues/1438
    Link: https://lore.kernel.org/all/20210909182525.372ee687@canb.auug.org.au/
    Link: https://lore.kernel.org/stable/CAHk-=whiQBofgis_rkniz8GBP9wZtSZdcDEffgSLO62BUGV3gg@mail.gmail.com/
    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Suggested-by: Kees Cook <keescook@chromium.org>
    Suggested-by: Linus Torvalds <torvalds@linux-foundation.org>
    Suggested-by: Pavel Machek <pavel@ucw.cz>
    Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
    Reviewed-by: Josef Bacik <josef@toxicpanda.com>
    Link: https://lore.kernel.org/r/20210920232533.4092046-1-ndesaulniers@google.com
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>