net: fixed_phy: Add forward declaration for struct gpio_desc;
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [kernel] fixed_phy: Add forward declaration for struct gpio_desc; (Petr Oros) [1772010]
Rebuild_FUZZ: 95.73%
commit-author Moritz Fischer <mdf@kernel.org>
commit ebe26aca98fcf9fbe5017b5cbe216413cee69df5

Add forward declaration for struct gpio_desc in order to address
the following:

./include/linux/phy_fixed.h:48:17: error: 'struct gpio_desc' declared inside parameter list [-Werror]
./include/linux/phy_fixed.h:48:17: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]

Fixes: 71bd106d2567 ("net: fixed-phy: Add fixed_phy_register_with_gpiod() API")
	Signed-off-by: Moritz Fischer <mdf@kernel.org>
	Reviewed-by: Florian Fainelli <f.fainelli@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ebe26aca98fcf9fbe5017b5cbe216413cee69df5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>