IB/core: Fix sparse warnings about redeclared functions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [infiniband] core: Fix sparse warnings about redeclared functions (Amir Vadai) [1107617 1107618 1107619 1107620]
Rebuild_FUZZ: 97.20%
commit-author Roland Dreier <roland@purestorage.com>
commit 8385fd841468868e0b37a722530d75b0e8bfc5a8

Fix a few functions that are declared with __attribute_const__ in the
ib_verbs.h header file but defined without it in verbs.c.  This gets rid
of the following sparse warnings:

    drivers/infiniband/core/verbs.c:51:5: error: symbol 'ib_rate_to_mult' redeclared with different type (originally declared at include/rdma/ib_verbs.h:469) - different modifiers
    drivers/infiniband/core/verbs.c:68:14: error: symbol 'mult_to_ib_rate' redeclared with different type (originally declared at include/rdma/ib_verbs.h:607) - different modifiers
    drivers/infiniband/core/verbs.c:85:5: error: symbol 'ib_rate_to_mbps' redeclared with different type (originally declared at include/rdma/ib_verbs.h:476) - different modifiers
    drivers/infiniband/core/verbs.c:111:1: error: symbol 'rdma_node_get_transport' redeclared with different type (originally declared at include/rdma/ib_verbs.h:84) - different modifiers

	Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit 8385fd841468868e0b37a722530d75b0e8bfc5a8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>