perf/imx_ddr: Fix undefined behavior due to shift overflowing the constant
Bugzilla: http://bugzilla.redhat.com/2184607

commit d02b4dd84e1a90f7f1444d027c0289bf355b0d5a
Author: Borislav Petkov <bp@suse.de>
Date:   Tue Apr 5 17:15:15 2022 +0200

    perf/imx_ddr: Fix undefined behavior due to shift overflowing the constant

    Fix:

      In file included from <command-line>:0:0:
      In function ‘ddr_perf_counter_enable’,
          inlined from ‘ddr_perf_irq_handler’ at drivers/perf/fsl_imx8_ddr_perf.c:651:2:
      ././include/linux/compiler_types.h:352:38: error: call to ‘__compiletime_assert_729’ \
            declared with attribute error: FIELD_PREP: mask is not constant
        _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
    ...

    See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
    details as to why it triggers with older gccs only.

    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Frank Li <Frank.li@nxp.com>
    Cc: Will Deacon <will@kernel.org>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Shawn Guo <shawnguo@kernel.org>
    Cc: Sascha Hauer <s.hauer@pengutronix.de>
    Cc: Pengutronix Kernel Team <kernel@pengutronix.de>
    Cc: Fabio Estevam <festevam@gmail.com>
    Cc: NXP Linux Team <linux-imx@nxp.com>
    Cc: linux-arm-kernel@lists.infradead.org
    Acked-by: Will Deacon <will@kernel.org>
    Link: https://lore.kernel.org/r/20220405151517.29753-10-bp@alien8.de
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Steve Best <sbest@redhat.com>