ASoC: SOF: ops: don't return void value
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 4f50f16e9414ea41d5c142fd880faab060472a6b

Sparse throws the following warning:

sound/soc/sof/ops.h:247:17: error: returning void-valued expression

Remove the useless returns.

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
	Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
	Reviewed-by: Rander Wang <rander.wang@intel.com>
	Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>
Link: https://lore.kernel.org/r/20210521092804.3721324-7-kai.vehmanen@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 4f50f16e9414ea41d5c142fd880faab060472a6b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>