geneve: Initialize addr6 with memset
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 8a962c4aa1e6c0836985a5843f44d74fe3cced12

Clang warns:

drivers/net/geneve.c:428:29: error: suggest braces around initialization
of subobject [-Werror,-Wmissing-braces]
                struct in6_addr addr6 = { 0 };
                                          ^
                                          {}

Rather than trying to appease the various compilers that support the
kernel, use memset, which is unambiguous.

Fixes: a07966447f39 ("geneve: ICMP error lookup handler")
	Suggested-by: David S. Miller <davem@davemloft.net>
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8a962c4aa1e6c0836985a5843f44d74fe3cced12)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>