ASoC: fsl_rpmsg: update Kconfig dependencies
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 9cce9c4806a89439ea34aad2e382150d68c7ea95
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Nov 29 12:31:17 2023 +0100

    ASoC: fsl_rpmsg: update Kconfig dependencies

    SND_SOC_IMX_RPMSG gained a new dependency and gets selected by SND_SOC_FSL_RPMSG,
    which as a result needs to have the same dependency, or produce a build failure
    based on that:

    WARNING: unmet direct dependencies detected for SND_SOC_IMX_RPMSG
      Depends on [n]: SOUND [=y] && SND [=y] && SND_SOC [=y] && SND_IMX_SOC [=y] && RPMSG [=y] && OF [=y] && I2C [=n]
      Selected by [y]:
      - SND_SOC_FSL_RPMSG [=y] && SOUND [=y] && SND [=y] && SND_SOC [=y] && COMMON_CLK [=y] && RPMSG [=y] && (SND_IMX_SOC [=y] || SND_IMX_SOC [=y]=n) && SND_IMX_SOC [=y]!=n
    x86_64-linux-ld: sound/soc/fsl/imx-rpmsg.o: in function `imx_rpmsg_late_probe':
    imx-rpmsg.c:(.text+0x11e): undefined reference to `i2c_find_device_by_fwnode'

    Fixes: f83d38def6b1 ("ASoC: imx-rpmsg: SND_SOC_IMX_RPMSG should depend on OF and I2C")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231129113204.2869356-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>