net/mlx5e: Restore destroying state bit after profile cleanup
JIRA: https://issues.redhat.com/browse/RHEL-98257

commit 5629f8859dca7ef74d7314b60de6a957f23166c0
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Thu Jan 8 13:26:57 2026 -0800

    net/mlx5e: Restore destroying state bit after profile cleanup

    Profile rollback can fail in mlx5e_netdev_change_profile() and we will
    end up with invalid mlx5e_priv memset to 0, we must maintain the
    'destroying' bit in order to gracefully shutdown even if the
    profile/priv are not valid.

    This patch maintains the previous state of the 'destroying' state of
    mlx5e_priv after priv cleanup, to allow the remove flow to cleanup
    common resources from mlx5_core to avoid FW fatal errors as seen below:

    $ devlink dev eswitch set pci/0000:00:03.0 mode switchdev
        Error: mlx5_core: Failed setting eswitch to offloads.
    dmesg: mlx5_core 0000:00:03.0 enp0s3np0: failed to rollback to orig profile, ...

    $ devlink dev reload pci/0000:00:03.0

    mlx5_core 0000:00:03.0: E-Switch: Disable: mode(LEGACY), nvfs(0), necvfs(0), active vports(0)
    mlx5_core 0000:00:03.0: poll_health:803:(pid 519): Fatal error 3 detected
    mlx5_core 0000:00:03.0: firmware version: 28.41.1000
    mlx5_core 0000:00:03.0: 0.000 Gb/s available PCIe bandwidth (Unknown x255 link)
    mlx5_core 0000:00:03.0: mlx5_function_enable:1200:(pid 519): enable hca failed
    mlx5_core 0000:00:03.0: mlx5_function_enable:1200:(pid 519): enable hca failed
    mlx5_core 0000:00:03.0: mlx5_health_try_recover:340:(pid 141): handling bad device here
    mlx5_core 0000:00:03.0: mlx5_handle_bad_state:285:(pid 141): Expected to see disabled NIC but it is full driver
    mlx5_core 0000:00:03.0: mlx5_error_sw_reset:236:(pid 141): start
    mlx5_core 0000:00:03.0: NIC IFC still 0 after 4000ms.

    Fixes: c4d7eb57687f ("net/mxl5e: Add change profile method")
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
    Link: https://patch.msgid.link/20260108212657.25090-5-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>