selftests/tcp_ao: Printing fixes to confirm with format-security
JIRA: https://redhat.atlassian.net/browse/RHEL-142637
Upstream Status: net.git commit b476c93654d748c13624f7c7d0ba191c56a8092e

commit b476c93654d748c13624f7c7d0ba191c56a8092e
Author: Dmitry Safonov <0x7f454c46@gmail.com>
Date:   Sat Apr 13 02:42:55 2024 +0100

    selftests/tcp_ao: Printing fixes to confirm with format-security

    On my new laptop with packages from nixos-unstable, gcc 12.3.0 produces
    > lib/setup.c: In function ‘__test_msg’:
    > lib/setup.c:20:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    20 |         ksft_print_msg(buf);
    >       |         ^~~~~~~~~~~~~~
    > lib/setup.c: In function ‘__test_ok’:
    > lib/setup.c:26:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    26 |         ksft_test_result_pass(buf);
    >       |         ^~~~~~~~~~~~~~~~~~~~~
    > lib/setup.c: In function ‘__test_fail’:
    > lib/setup.c:32:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    32 |         ksft_test_result_fail(buf);
    >       |         ^~~~~~~~~~~~~~~~~~~~~
    > lib/setup.c: In function ‘__test_xfail’:
    > lib/setup.c:38:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    38 |         ksft_test_result_xfail(buf);
    >       |         ^~~~~~~~~~~~~~~~~~~~~~
    > lib/setup.c: In function ‘__test_error’:
    > lib/setup.c:44:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    44 |         ksft_test_result_error(buf);
    >       |         ^~~~~~~~~~~~~~~~~~~~~~
    > lib/setup.c: In function ‘__test_skip’:
    > lib/setup.c:50:9: error: format not a string literal and no format arguments [-Werror=format-security]
    >    50 |         ksft_test_result_skip(buf);
    >       |         ^~~~~~~~~~~~~~~~~~~~~
    > cc1: some warnings being treated as errors

    As the buffer was already pre-printed into, print it as a string
    rather than a format-string.

    Fixes: cfbab37b3da0 ("selftests/net: Add TCP-AO library")
    Signed-off-by: Dmitry Safonov <0x7f454c46@gmail.com>
    Reported-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
    Signed-off-by: Paolo Abeni <pabeni@redhat.com>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>