crypto: qat - fix error path in add_update_sla()
JIRA: https://issues.redhat.com/browse/RHEL-19122
Upstream Status: merged into herbert/cryptodev-2.6.git

commit 6627f03c21cb7001ae4dbbfb7a8514516d02331c
Author: Damian Muszynski <damian.muszynski@intel.com>
Date:   Tue Nov 28 18:37:32 2023 +0100

    crypto: qat - fix error path in add_update_sla()

    The input argument `sla_in` is a pointer to a structure that contains
    the parameters of the SLA which is being added or updated.
    If this pointer is NULL, the function should return an error as
    the data required for the algorithm is not available.
    By mistake, the logic jumps to the error path which dereferences
    the pointer.

    This results in a warnings reported by the static analyzer Smatch when
    executed without a database:

        drivers/crypto/intel/qat/qat_common/adf_rl.c:871 add_update_sla()
        error: we previously assumed 'sla_in' could be null (see line 812)

    This issue was not found in internal testing as the pointer cannot be
    NULL. The function add_update_sla() is only called (indirectly) by
    the rate limiting sysfs interface implementation in adf_sysfs_rl.c
    which ensures that the data structure is allocated and valid. This is
    also proven by the fact that Smatch executed with a database does not
    report such error.

    Fix it by returning with error if the pointer `sla_in` is NULL.

    Fixes: d9fb8408376e ("crypto: qat - add rate limiting feature to qat_4xxx")
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Damian Muszynski <damian.muszynski@intel.com>
    Reviewed-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>