ALSA: timer: Adjust a condition check in snd_timer_resolution()
jira LE-1907
cve CVE-2017-1000380
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Markus Elfring <elfring@users.sourceforge.net>
commit dd1f7ab8a88ddc8fbb304aaca25f549e26fa8529

The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code place.

	Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit dd1f7ab8a88ddc8fbb304aaca25f549e26fa8529)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>