sfc: use IS_ENABLED() checks for CONFIG_SFC_SRIOV
Bugzilla: https://bugzilla.redhat.com/2159241

commit a59f832a71c938779b8abdb022d6d39903e635c3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Feb 17 10:56:39 2023 +0100

    sfc: use IS_ENABLED() checks for CONFIG_SFC_SRIOV
    
    One local variable has become unused after a recent change:
    
    drivers/net/ethernet/sfc/ef100_nic.c: In function 'ef100_probe_netdev_pf':
    drivers/net/ethernet/sfc/ef100_nic.c:1155:21: error: unused variable 'net_dev' [-Werror=unused-variable]
      struct net_device *net_dev = efx->net_dev;
                         ^~~~~~~
    
    The variable is still used in an #ifdef. Replace the #ifdef with
    an if(IS_ENABLED()) check that lets the compiler see where it is
    used, rather than adding another #ifdef.
    
    This also fixes an uninitialized return value in ef100_probe_netdev_pf()
    that gcc did not spot.
    
    Fixes: 7e056e2360d9 ("sfc: obtain device mac address based on firmware handle for ef100")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>