ASoc: fix sound/soc/intel/skylake/slk-ssp-clk.c build error on IA64
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoc: fix sound/soc/intel/skylake/slk-ssp-clk.c build error on IA64 (Jaroslav Kysela) [1738610]
Rebuild_FUZZ: 95.71%
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 2c79eeb1aaf2bf0a6d9bb4732596f7dc147cab4d

skl-ssp-clk.c does not build on IA64 because the driver
uses the common clock interface, so make the driver depend
on COMMON_CLK.

Fixes this build error:
../sound/soc/intel/skylake/skl-ssp-clk.c:26:16: error: field 'hw' has incomplete type
  struct clk_hw hw;
                ^~
[Corrections for SKL support by Pierre Bossart]

	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: Liam Girdwood <liam.r.girdwood@linux.intel.com>
	Cc: Jie Yang <yang.jie@linux.intel.com>
	Cc: alsa-devel@alsa-project.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2c79eeb1aaf2bf0a6d9bb4732596f7dc147cab4d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>