ASoC: SOF: sof-client: fix build when only IPC4 is selected
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit d65d4a2c3867a04ee4ae9c99747a6398b58e269b
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date: Fri Oct 6 11:40:41 2023 +0300

    ASoC: SOF: sof-client: fix build when only IPC4 is selected

    When IPC3 is not selected, sof-client.c still makes a hard-coded
    reference to an IPC3-specific function:

    ERROR: modpost: "sof_ipc3_do_rx_work" [sound/soc/sof/snd-sof.ko]
    undefined!

    Fix by making the code conditional.

    Closes: https://github.com/thesofproject/linux/issues/4581
    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
    Reviewed-by: Péter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Reviewed-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
    Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Link: https://lore.kernel.org/r/20231006084041.18100-1-peter.ujfalusi@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>