io_uring: fix missing kmap() declaration on powerpc
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Jens Axboe <axboe@kernel.dk>
commit aa4c3967756c6c576a38a23ac511be211462a6b7

Christophe reports that current master fails building on powerpc with
this error:

   CC      fs/io_uring.o
fs/io_uring.c: In function ‘loop_rw_iter’:
fs/io_uring.c:1628:21: error: implicit declaration of function ‘kmap’
[-Werror=implicit-function-declaration]
     iovec.iov_base = kmap(iter->bvec->bv_page)
                      ^
fs/io_uring.c:1628:19: warning: assignment makes pointer from integer
without a cast [-Wint-conversion]
     iovec.iov_base = kmap(iter->bvec->bv_page)
                    ^
fs/io_uring.c:1643:4: error: implicit declaration of function ‘kunmap’
[-Werror=implicit-function-declaration]
     kunmap(iter->bvec->bv_page);
     ^

which is caused by a missing highmem.h include. Fix it by including
it.

Fixes: 311ae9e159d8 ("io_uring: fix dead-hung for non-iter fixed rw")
	Reported-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Tested-by: Christophe Leroy <christophe.leroy@c-s.fr>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit aa4c3967756c6c576a38a23ac511be211462a6b7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>