accel/amdxdna: Add missing include linux/slab.h
JIRA: https://redhat.atlassian.net/browse/RHEL-222546
Upstream Status: v6.14-rc4

commit 838c17fd077e611b12c78feb0feee1b30ed09b63
Author:     Su Hui <suhui@nfschina.com>
AuthorDate: Tue Feb 11 09:53:55 2025 +0800
Commit:     Lizhi Hou <lizhi.hou@amd.com>
CommitDate: Wed Feb 19 09:42:17 2025 -0800
    
    When compiling without CONFIG_IA32_EMULATION, there can be some errors:
    
    drivers/accel/amdxdna/amdxdna_mailbox.c: In function ‘mailbox_release_msg’:
    drivers/accel/amdxdna/amdxdna_mailbox.c:197:2: error: implicit declaration
    of function ‘kfree’.
      197 |  kfree(mb_msg);
          |  ^~~~~
    drivers/accel/amdxdna/amdxdna_mailbox.c: In function ‘xdna_mailbox_send_msg’:
    drivers/accel/amdxdna/amdxdna_mailbox.c:418:11: error:implicit declaration
    of function ‘kzalloc’.
      418 |  mb_msg = kzalloc(sizeof(*mb_msg) + pkg_size, GFP_KERNEL);
          |           ^~~~~~~
    
    Add the missing include.
    
    Fixes: b87f920b9344 ("accel/amdxdna: Support hardware mailbox")
    Signed-off-by: Su Hui <suhui@nfschina.com>
    Reviewed-by: Lizhi Hou <lizhi.hou@amd.com>
    Reviewed-by: Jeffrey Hugo <quic_jhugo@quicinc.com>
    Signed-off-by: Lizhi Hou <lizhi.hou@amd.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20250211015354.3388171-1-suhui@nfschina.com

Signed-off-by: Peter Colberg <pcolberg@redhat.com>