ASoC: SOF: ipc4-topology: Allocate ref_params on stack
JIRA: https://issues.redhat.com/browse/RHEL-80657

commit a935b3f981809272d2649ad9c27a751685137846
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date: Wed Mar 12 18:05:16 2025 +0200

    ASoC: SOF: ipc4-topology: Allocate ref_params on stack

    Currently the compiler (clang 19.1.7) is not happy about the size of
    the stack frame in sof_ipc4_prepare_copier_module:

    sound/soc/sof/ipc4-topology.c:1800:1: error: stack frame size (1288) exceeds limit (1024) in 'sof_ipc4_prepare_copier_module' [-Werror,-Wframe-larger-than]
     1800 | sof_ipc4_prepare_copier_module(struct snd_sof_widget *swidget,
          | ^

    Work around this by allocating ref_params on stack, as it looks the biggest
    variable on stack right now.

    Note, this only happens when compile for 32-bit machines (x86_32 in my case).

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Acked-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Link: https://patch.msgid.link/20250312160516.3864295-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>