tools/power turbostat: Fix file pointer leak
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Colin Ian King <colin.i.king@gmail.com>
commit 5e5fd36c58d6c820f7292ee492c3731c9a104a41

Currently if a fscanf fails then an early return leaks an open
file pointer. Fix this by fclosing the file before the return.
Detected using static analysis with cppcheck:

tools/power/x86/turbostat/turbostat.c:2039:3: error: Resource leak: fp [resourceLeak]

Fixes: eae97e053fe3 ("tools/power turbostat: Support thermal throttle count print")
	Signed-off-by: Colin Ian King <colin.i.king@gmail.com>
	Acked-by: Chen Yu <yu.c.chen@intel.com>
	Reviewed-by: Tom Rix <trix@redhat.com>
	Signed-off-by: Len Brown <len.brown@intel.com>
(cherry picked from commit 5e5fd36c58d6c820f7292ee492c3731c9a104a41)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>