thunderbolt: Use correct type in tb_port_is_clx_enabled() prototype
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-504.el8
commit-author Jiri Slaby (SUSE) <jirislaby@kernel.org>
commit d31137619776f9c173a46a79bc7733a2b106061f

tb_port_is_clx_enabled() generates a valid warning with gcc-13:
  drivers/thunderbolt/switch.c:1286:6: error: conflicting types for 'tb_port_is_clx_enabled' due to enum/integer mismatch; have 'bool(struct tb_port *, unsigned int)' ...
  drivers/thunderbolt/tb.h:1050:6: note: previous declaration of 'tb_port_is_clx_enabled' with type 'bool(struct tb_port *, enum tb_clx)' ...

I.e. the type of the 2nd parameter of tb_port_is_clx_enabled() in the
declaration is unsigned int, while the definition spells enum tb_clx.
Synchronize them to the former as the parameter is in fact a mask of the
enum values.

	Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
	Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
(cherry picked from commit d31137619776f9c173a46a79bc7733a2b106061f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>