sound/oss/dmasound: fix build when drivers are mixed =y/=m
When CONFIG_DMASOUND_ATARI=m and CONFIG_DMASOUND_Q40=y (or vice versa),
dmasound_core.o can be built without dmasound_deinit() being defined,
causing a build error:

ERROR: modpost: "dmasound_deinit" [sound/oss/dmasound/dmasound_atari.ko] undefined!

Modify dmasound_core.c and dmasound.h so that dmasound_deinit() is
always available.

The mixed modes (=y/=m) also mean that several variables and structs
have to be declared in all cases.

    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Suggested-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Link: lore.kernel.org/r/202204032138.EFT9qGEd-lkp@intel.com
    Cc: Geert Uytterhoeven <geert@linux-m68k.org>
    Cc: Jaroslav Kysela <perex@perex.cz>
    Cc: Takashi Iwai <tiwai@suse.com>
    Cc: alsa-devel@alsa-project.org
    Link: https://lore.kernel.org/r/20220405234118.24830-1-rdunlap@infradead.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Randy Dunlap <rdunlap@infradead.org>
Date: Tue Apr 5 16:41:18 2022 -0700

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 9dd7c46346ca4390f84a7ea9933005eb1b175c15)
Bugzilla: https://bugzilla.redhat.com/2065572