xfrm: lwtunnel: squelch kernel warning in case XFRM encap type is not available
Bugzilla: https://bugzilla.redhat.com/2177177

Conflicts: different context because of missing LWTUNNEL_ENCAP_IOAM6.

commit d83f7040e18489265b4b121f33f99b02e52dabda
Author: Eyal Birger <eyal.birger@gmail.com>
Date:   Tue Oct 11 11:01:37 2022 +0300

    xfrm: lwtunnel: squelch kernel warning in case XFRM encap type is not available

    Ido reported that a kernel warning [1] can be triggered from
    user space when the kernel is compiled with CONFIG_MODULES=y and
    CONFIG_XFRM=n when adding an xfrm encap type route, e.g:

    $ ip route add 198.51.100.0/24 dev dummy1 encap xfrm if_id 1
    Error: lwt encapsulation type not supported.

    The reason for the warning is that the LWT infrastructure has an
    autoloading feature which is meant only for encap types that don't
    use a net device,  which is not the case in xfrm encap.

    Mute this warning for xfrm encap as there's no encap module to autoload
    in this case.

    [1]
     WARNING: CPU: 3 PID: 2746262 at net/core/lwtunnel.c:57 lwtunnel_valid_encap_type+0x4f/0x120
    [...]
     Call Trace:
      <TASK>
      rtm_to_fib_config+0x211/0x350
      inet_rtm_newroute+0x3a/0xa0
      rtnetlink_rcv_msg+0x154/0x3c0
      netlink_rcv_skb+0x49/0xf0
      netlink_unicast+0x22f/0x350
      netlink_sendmsg+0x208/0x440
      ____sys_sendmsg+0x21f/0x250
      ___sys_sendmsg+0x83/0xd0
      __sys_sendmsg+0x54/0xa0
      do_syscall_64+0x35/0x80
      entry_SYSCALL_64_after_hwframe+0x63/0xcd

    Reported-by: Ido Schimmel <idosch@idosch.org>
    Fixes: 2c2493b9da91 ("xfrm: lwtunnel: add lwtunnel support for xfrm interfaces in collect_md mode")
    Signed-off-by: Eyal Birger <eyal.birger@gmail.com>
    Tested-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

Signed-off-by: Jiri Benc <jbenc@redhat.com>