wifi: ath10k: remove unused ath10k_get_ring_byte function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit 9fc093b756f64788ce33e3484f6f59a169704759

clang with W=1 reports:

drivers/net/wireless/ath/ath10k/ce.c:88:1: error:
  unused function 'ath10k_get_ring_byte' [-Werror,-Wunused-function]
ath10k_get_ring_byte(unsigned int offset,
^
This function is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20230322122855.2570417-1-trix@redhat.com
(cherry picked from commit 9fc093b756f64788ce33e3484f6f59a169704759)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>