ASoC: Intel: fix unused-variable warning in probe_codec
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Gaosheng Cui <cuigaosheng1@huawei.com>
commit a74bfc9eaa497951effddefbcb18f1c7ab56fb35

In configurations with CONFIG_SND_SOC_INTEL_SKYLAKE_HDAUDIO_CODEC=n,
gcc warns about an unused variable:

sound/soc/intel/skylake/skl.c: In function ‘probe_codec’:
sound/soc/intel/skylake/skl.c:729:18: error: unused variable ‘skl’ [-Werror=unused-variable]
  struct skl_dev *skl = bus_to_skl(bus);
                  ^~~
cc1: all warnings being treated as errors

Fixes: 3fd63658caed9 ("ASoC: Intel: Drop hdac_ext usage for codec device creation")
	Signed-off-by: Gaosheng Cui <cuigaosheng1@huawei.com>
	Acked-by: Cezary Rojewski <cezary.rojewski@intel.com>
Link: https://lore.kernel.org/r/20220822035133.2147381-1-cuigaosheng1@huawei.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit a74bfc9eaa497951effddefbcb18f1c7ab56fb35)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>