ALSA: ac97: fix build regression
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit f90dffdce70ff724f9ee8b0bcc711e86e6663896
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Jan 3 11:25:38 2024 +0100

    ALSA: ac97: fix build regression

    The ac97_bus_type structure is no longer declared in this file:

    sound/ac97/bus.c: In function 'ac97_codec_add':
    sound/ac97/bus.c:112:27: error: 'ac97_bus_type' undeclared (first use in this function); did you mean 'bus_type'?
      112 |         codec->dev.bus = &ac97_bus_type;
          |                           ^~~~~~~~~~~~~
          |                           bus_type
    sound/ac97/bus.c:112:27: note: each undeclared identifier is reported only once for each function it appears in
    sound/ac97/bus.c: In function 'snd_ac97_codec_driver_register':
    sound/ac97/bus.c:191:28: error: 'ac97_bus_type' undeclared (first use in this function); did you mean 'ac97_bus_reset'?
      191 |         drv->driver.bus = &ac97_bus_type;

    Include the header that contains the declaration and make sure the definition
    is const but not static.

    Fixes: 66e82d219924 ("ALSA: mark all struct bus_type as const")
    Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240103102544.3715055-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>