rtc: rv8803: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-72448

commit fbbeae0af551b8e5fba6ba128d2190c2a29dce90
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Thu, 10 Aug 2023 12:39:00 +0200

    rtc: rv8803: fix Wvoid-pointer-to-enum-cast warning

    'type' is an enum, thus cast of pointer on 64-bit compile test with W=1
    causes:

      rtc-rv8803.c:648:18: error: cast to smaller integer type 'enum rv8803_type' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230810103902.151145-2-krzysztof.kozlowski@linaro.org
    Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>

Signed-off-by: Waiman Long <longman@redhat.com>