cpumask: Add helper cpumask_available()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit f7e30f01a9e221067bb4b579e3cfc25cd2617467

With CONFIG_CPUMASK_OFFSTACK=y cpumask_var_t is a struct cpumask
pointer, otherwise a struct cpumask array with a single element.

Some code dealing with cpumasks needs to validate that a cpumask_var_t
is not a NULL pointer when CONFIG_CPUMASK_OFFSTACK=y. This is typically
done by performing the check always, regardless of the underlying type
of cpumask_var_t. This works in both cases, however clang raises a
warning like this when CONFIG_CPUMASK_OFFSTACK=n:

kernel/irq/manage.c:839:28: error: address of array
'desc->irq_common_data.affinity' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]

Add the inline helper cpumask_available() which only performs the
pointer check if CONFIG_CPUMASK_OFFSTACK=y.

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Cc: Grant Grundler <grundler@chromium.org>
	Cc: Rusty Russell <rusty@rustcorp.com.au>
	Cc: Greg Hackmann <ghackmann@google.com>
	Cc: Michael Davidson <md@google.com>
	Cc: Andrew Morton <akpm@linux-foundation.org>
Link: http://lkml.kernel.org/r/20170412182030.83657-1-mka@chromium.org
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

(cherry picked from commit f7e30f01a9e221067bb4b579e3cfc25cd2617467)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>