sfc: fix uninitialized variable use
JIRA: https://issues.redhat.com/browse/RHEL-11017

commit f61d2d5cf142436cd1a02ddc78425e91116b8b0d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 19 11:12:10 2023 +0200

    sfc: fix uninitialized variable use

    The new efx_bind_neigh() function contains a broken code path when IPV6 is
    disabled:

    drivers/net/ethernet/sfc/tc_encap_actions.c:144:7: error: variable 'n' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
                    if (encap->type & EFX_ENCAP_FLAG_IPV6) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/sfc/tc_encap_actions.c:184:8: note: uninitialized use occurs here
                    if (!n) {
                         ^
    drivers/net/ethernet/sfc/tc_encap_actions.c:144:3: note: remove the 'if' if its condition is always false
                    if (encap->type & EFX_ENCAP_FLAG_IPV6) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/sfc/tc_encap_actions.c:141:22: note: initialize the variable 'n' to silence this warning
                    struct neighbour *n;
                                       ^
                                        = NULL

    Change it to use the existing error handling path here.

    Fixes: 7e5e7d800011a ("sfc: neighbour lookup for TC encap action offload")
    Suggested-by: Edward Cree <ecree.xilinx@gmail.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Edward Cree <ecree.xilinx@gmail.com>
    Link: https://lore.kernel.org/r/20230619091215.2731541-2-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>