perf tools: Fix errors under optimization level '-Og'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Changbin Du <changbin.du@gmail.com>
commit 11c1ea6f1a9bc97bf857fd12f72eacb6c69794e2

Optimization level '-Og' offers a reasonable level of optimization while
maintaining fast compilation and a good debugging experience. This patch
tries to make it work.

  $ make DEBUG=1 EXTRA_CFLAGS='-Og'
  bench/epoll-ctl.c: In function ‘do_threads’:
  bench/epoll-ctl.c:274:9: error: ‘ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    return ret;
           ^~~
  ...

	Signed-off-by: Changbin Du <changbin.du@gmail.com>
	Reviewed-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Alexei Starovoitov <ast@kernel.org>
	Cc: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Steven Rostedt (VMware) <rostedt@goodmis.org>
Link: http://lkml.kernel.org/r/20190316080556.3075-4-changbin.du@gmail.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 11c1ea6f1a9bc97bf857fd12f72eacb6c69794e2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>