perf tools: Fix build breakage on arm64 targets
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [tools] perf: Fix build breakage on arm64 targets (Jiri Olsa) [1169436]
Rebuild_FUZZ: 93.18%
commit-author Will Deacon <will.deacon@arm.com>
commit 660d13296bbbe79635d1d9d700080b88061faffb

Attempting to build the perf tool for an arm64 target results in the
following failure:

  arch/arm64/util/unwind-libunwind.c: In function 'libunwind__arch_reg_id':
  arch/arm64/util/unwind-libunwind.c:77:3: error: implicit declaration of function 'pr_err'
     pr_err("unwind: invalid reg id %d\n", regnum);
     ^
  arch/arm64/util/unwind-libunwind.c:77:3: error: nested extern declaration of 'pr_err'

This is due to commit 84f5d36f4866 ("perf tools: Move pr_* debug macros
into debug object") moving the pr_* macros into a new header file, but
failing to update architectures other than x86.

This patch adds the missing include, and fixes the build again.

	Signed-off-by: Will Deacon <will.deacon@arm.com>
	Cc: Jean Pihet <jean.pihet@linaro.org>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: linux-arm-kernel@lists.infradead.org
Link: http://lkml.kernel.org/r/1412076432-22045-1-git-send-email-will.deacon@arm.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 660d13296bbbe79635d1d9d700080b88061faffb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>