misc: rtsx: Fix clang -Wsometimes-uninitialized in rts5261_init_from_hw()
JIRA: https://issues.redhat.com/browse/RHEL-28810

commit bd476c1306ea989d6d9eb65295572e98d93edeb6
Author: Nathan Chancellor <nathan@kernel.org>
Date: Mon, 23 May 2022 08:05:22 -0700

  Clang warns:

    drivers/misc/cardreader/rts5261.c:406:13: error: variable 'setting_reg2' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
            } else if (efuse_valid == 0) {
                       ^~~~~~~~~~~~~~~~
    drivers/misc/cardreader/rts5261.c:412:30: note: uninitialized use occurs here
            pci_read_config_dword(pdev, setting_reg2, &lval2);
                                        ^~~~~~~~~~~~

  efuse_valid == 1 is not a valid value so just return early from the
  function to avoid using setting_reg2 uninitialized.

  Fixes: b1c5f3085149 ("misc: rtsx: add rts5261 efuse function")
  Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
  Reported-by: kernel test robot <lkp@intel.com>
  Reported-by: Tom Rix <trix@redhat.com>
  Suggested-by: Ricky WU <ricky_wu@realtek.com>
  Acked-by: Arnd Bergmann <arnd@arndb.de>
  Signed-off-by: Nathan Chancellor <nathan@kernel.org>
  Link: https://lore.kernel.org/r/20220523150521.2947108-1-nathan@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>