ACPI: blacklist: fix clang warning for unused DMI table
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit b80d6a42bdc97bdb6139107d6034222e9843c6e2

When CONFIG_DMI is disabled, we only have a tentative declaration,
which causes a warning from clang:

drivers/acpi/blacklist.c:20:35: error: tentative array definition assumed to have one element [-Werror]
static const struct dmi_system_id acpi_rev_dmi_table[] __initconst;

As the variable is not actually used here, hide it entirely
in an #ifdef to shut up the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit b80d6a42bdc97bdb6139107d6034222e9843c6e2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>