iommu/arm-smmu-v3: Fix build error without CONFIG_PCI_ATS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [iommu] arm-smmu-v3: Fix build error without CONFIG_PCI_ATS (Jerry Snitselaar) [1729845]
Rebuild_FUZZ: 94.44%
commit-author YueHaibing <yuehaibing@huawei.com>
commit 097a7df2e3af1b716cd39ce90001a2c372488e58

If CONFIG_PCI_ATS is not set, building fails:

drivers/iommu/arm-smmu-v3.c: In function arm_smmu_ats_supported:
drivers/iommu/arm-smmu-v3.c:2325:35: error: struct pci_dev has no member named ats_cap; did you mean msi_cap?
  return !pdev->untrusted && pdev->ats_cap;
                                   ^~~~~~~

ats_cap should only used when CONFIG_PCI_ATS is defined,
so use #ifdef block to guard this.

Fixes: bfff88ec1afe ("iommu/arm-smmu-v3: Rework enabling/disabling of ATS for PCI masters")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 097a7df2e3af1b716cd39ce90001a2c372488e58)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>