usb: add HAS_IOMEM dependency to USB_XHCI_MVEBU
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] add HAS_IOMEM dependency to USB_XHCI_MVEBU (Torez Smith) [1332712]
Rebuild_FUZZ: 94.38%
commit-author Vegard Nossum <vegard.nossum@oracle.com>
commit 828638e91915e347f0721ae2a2cb137c910dc592
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/828638e9.failed

drivers/usb/host/xhci-mvebu.c: In function ‘xhci_mvebu_mbus_init_quirk’:
drivers/usb/host/xhci-mvebu.c:58:2: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]
  base = ioremap(res->start, resource_size(res));
  ^
drivers/usb/host/xhci-mvebu.c:58:7: warning: assignment makes pointer from integer without a cast [enabled by default]
  base = ioremap(res->start, resource_size(res));
       ^
drivers/usb/host/xhci-mvebu.c:69:2: error: implicit declaration of function ‘iounmap’ [-Werror=implicit-function-declaration]
  iounmap(base);
  ^

	Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
	Acked-by: Gregory CLEMENT <gregory.clement@free-electrons.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 828638e91915e347f0721ae2a2cb137c910dc592)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/usb/host/Kconfig