EDAC, pnd2_edac: Fix !EDAC_DEBUG build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [edac] pnd2_edac: Fix !EDAC_DEBUG build (Aristeu Rozanski) [1479627 1273769]
Rebuild_FUZZ: 91.43%
commit-author Borislav Petkov <bp@suse.de>
commit cd1be315ac9766fe83e4fb788d5d9fe032a9b877
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/cd1be315.failed

Provide debugfs function stubs when EDAC_DEBUG is not enabled so that we
don't fail the build:

  drivers/edac/pnd2_edac.c: In function ‘pnd2_init’:
  drivers/edac/pnd2_edac.c:1521:2: error: implicit declaration of function ‘setup_pnd2_debug’ [-Werror=implicit-function-declaration]
    setup_pnd2_debug();
    ^
  drivers/edac/pnd2_edac.c: In function ‘pnd2_exit’:
  drivers/edac/pnd2_edac.c:1529:2: error: implicit declaration of function ‘teardown_pnd2_debug’ [-Werror=implicit-function-declaration]
    teardown_pnd2_debug();
    ^

	Signed-off-by: Borislav Petkov <bp@suse.de>
(cherry picked from commit cd1be315ac9766fe83e4fb788d5d9fe032a9b877)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/edac/pnd2_edac.c