dm raid: remove unused d variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author Tom Rix <trix@redhat.com>
commit 306fbc2e041c227be7c934efe8a49ddb87bd31f1

clang with W=1 reports
drivers/md/dm-raid.c:2212:15: error: variable
  'd' set but not used [-Werror,-Wunused-but-set-variable]
        unsigned int d;
                     ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Signed-off-by: Mike Snitzer <snitzer@kernel.org>
(cherry picked from commit 306fbc2e041c227be7c934efe8a49ddb87bd31f1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>