mfd: intel-lpss: Hide suspend/resume functions in #ifdef
JIRA: https://issues.redhat.com/browse/RHEL-20053

commit 9ef18aa8c0ab5f7824b8380536501859af61265d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 16 22:27:42 2023 +0200

    mfd: intel-lpss: Hide suspend/resume functions in #ifdef

    When CONFIG_PM is disabled, the prototypes for these two functions
    are not visible:

    drivers/mfd/intel-lpss.c:482:5: error: no previous prototype for 'intel_lpss_suspend' [-Werror=missing-prototypes]
      482 | int intel_lpss_suspend(struct device *dev)
          |     ^~~~~~~~~~~~~~~~~~
    drivers/mfd/intel-lpss.c:503:5: error: no previous prototype for 'intel_lpss_resume' [-Werror=missing-prototypes]
      503 | int intel_lpss_resume(struct device *dev)

    Add the same #ifdef around the definition of the unused functions,
    which avoids the warning and slightly reduces the code size.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230516202746.561111-1-arnd@kernel.org
    Signed-off-by: Lee Jones <lee@kernel.org>

Signed-off-by: David Arcari <darcari@redhat.com>