hinic: Fix l4_type parameter in hinic_task_set_tunnel_l4
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Nathan Chancellor <natechancellor@gmail.com>
commit 6e29464b8a72e74ec7c3f816f53bfe46a43601bc

Clang warns:

drivers/net/ethernet/huawei/hinic/hinic_tx.c:392:34: error: implicit
conversion from enumeration type 'enum hinic_l4_tunnel_type' to
different enumeration type 'enum hinic_l4_offload_type'
[-Werror,-Wenum-conversion]
                hinic_task_set_tunnel_l4(task, TUNNEL_UDP_NO_CSUM,
                ~~~~~~~~~~~~~~~~~~~~~~~~       ^~~~~~~~~~~~~~~~~~
1 error generated.

It seems that hinic_task_set_tunnel_l4 was meant to take an enum of type
hinic_l4_tunnel_type, not hinic_l4_offload_type, given both the name of
the functions and the values used.

Fixes: cc18a7543d2f ("net-next/hinic: add checksum offload and TSO support")
	Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
	Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 6e29464b8a72e74ec7c3f816f53bfe46a43601bc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>