octeontx2: hide unused label
JIRA: https://issues.redhat.com/browse/RHEL-127305

commit ca57d1c56f4015d83fe7840b41d74783ee900b28
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Feb 19 17:21:14 2025 +0100

    octeontx2: hide unused label

    A previous patch introduces a build-time warning when CONFIG_DCB
    is disabled:

    drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c: In function 'otx2_probe':
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.c:3217:1: error: label 'err_free_zc_bmap' defined but not used [-Werror=unused-label]
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_vf.c: In function 'otx2vf_probe':
    drivers/net/ethernet/marvell/octeontx2/nic/otx2_vf.c:740:1: error: label 'err_free_zc_bmap' defined but not used [-Werror=unused-label]

    Add the same #ifdef check around it.

    Fixes: efabce290151 ("octeontx2-pf: AF_XDP zero copy receive support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Suman Ghosh <sumang@marvell.com>
    Link: https://patch.msgid.link/20250219162239.1376865-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>