perf pmu: Fix misleadingly indented assignment (whitespace)
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Markus Trippelsdorf <markus@trippelsdorf.de>
commit d85ce830eef6c10d1e9617172dea4681f02b8424

One line in perf_pmu__parse_unit() is indented wrongly, leading to a
warning (=> error) from gcc 6:

  util/pmu.c:156:3: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]

    sret = read(fd, alias->unit, UNIT_MAX_LEN);
    ^~~~

  util/pmu.c:153:2: note: ...this 'if' clause, but it is not
    if (fd == -1)
    ^~

	Signed-off-by: Markus Trippelsdorf <markus@trippelsdorf.de>
	Acked-by: Ingo Molnar <mingo@kernel.org>
	Cc: Ben Hutchings <ben@decadent.org.uk>
	Cc: Matt Fleming <matt@codeblueprint.co.uk>
	Cc: Peter Zijlstra <peterz@infradead.org>
Fixes: 410136f5dd96 ("tools/perf/stat: Add event unit and scale support")
Link: http://lkml.kernel.org/r/20151214154440.GC1409@x4
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit d85ce830eef6c10d1e9617172dea4681f02b8424)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>