module: Fix ERRORs reported by checkpatch.pl
JIRA: https://issues.redhat.com/browse/RHEL-28063

Conflicts:
  Minor source diff due to RHEL9 3bade5d33 backport out of order
  to upstream.

commit ecc726f1458e7aa50e120ff334f0a3be5cccd94c
Author: Christophe Leroy <christophe.leroy@csgroup.eu>
Date:   Mon Jun 13 08:02:01 2022 +0200

    module: Fix ERRORs reported by checkpatch.pl

    Checkpatch reports following errors:

    ERROR: do not use assignment in if condition
    +       if ((colon = strnchr(name, MODULE_NAME_LEN, ':')) != NULL) {

    ERROR: do not use assignment in if condition
    +               if ((mod = find_module_all(name, colon - name, false)) != NULL)

    ERROR: do not use assignment in if condition
    +                       if ((ret = find_kallsyms_symbol_value(mod, name)) != 0)

    ERROR: do not initialise globals to 0
    +int modules_disabled = 0;

    Fix them.

    The following one has to remain, because the condition has to be evaluated
    multiple times by the macro wait_event_interruptible_timeout().

    ERROR: do not use assignment in if condition
    +       if (wait_event_interruptible_timeout(module_wq,

    Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>