ALSA: hda: cs35l41: fix building without CONFIG_SPI
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 8c14dbf36424eb751d70c15f9a671549390057b2
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed Jan 3 11:25:59 2024 +0100

    ALSA: hda: cs35l41: fix building without CONFIG_SPI

    When CONFIG_SPI is disabled, the driver produces unused-variable warning:

    sound/pci/hda/cs35l41_hda_property.c: In function 'generic_dsd_config':
    sound/pci/hda/cs35l41_hda_property.c:181:28: error: unused variable 'spi' [-Werror=unused-variable]
      181 |         struct spi_device *spi;
          |                            ^~~
    sound/pci/hda/cs35l41_hda_property.c:180:27: error: unused variable 'cs_gpiod' [-Werror=unused-variable]
      180 |         struct gpio_desc *cs_gpiod;
          |                           ^~~~~~~~

    Avoid these by turning the preprocessor contionals into equivalent C code,
    which also helps readability.

    Fixes: 916d051730ae ("ALSA: hda: cs35l41: Only add SPI CS GPIO if SPI is enabled in kernel")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240103102606.3742476-1-arnd@kernel.org
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>