ASoC: Intel: Skylake: Fix Kconfig dependency
Bugzilla: https://bugzilla.redhat.com/2179848

commit e5d4d2b23aed20a7815d1b500dbcd50af1da0023
Author: Lili Li <lili.li@intel.com>
Date: Mon Nov 21 18:47:42 2022 +0800

    ASoC: Intel: Skylake: Fix Kconfig dependency

    Commit e4746d94d00c ("ASoC: Intel: Skylake: Introduce HDA codec init and
    exit routines") introduced HDA codec init routine which depends on SND_HDA.
    Select SND_SOC_HDAC_HDA unconditionally to fix following compile error:
    ERROR: modpost: "snd_hda_codec_device_init" [sound/soc/intel/skylake/snd-soc-skl.ko] undefined!

    Fixes: e4746d94d00c ("ASoC: Intel: Skylake: Introduce HDA codec init and exit routines")
    Reviewed-by: Junxiao Chang <junxiao.chang@intel.com>
    Suggested-by: Cezary Rojewski <cezary.rojewski@intel.com>
    Signed-off-by: Lili Li <lili.li@intel.com>
    Reviewed-by: Cezary Rojewski <cezary.rojewski@intel.com>
    Link: https://lore.kernel.org/r/20221121104742.1007486-1-lili.li@intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>