x86/cpu: Fix amd_check_microcode() declaration
JIRA: https://issues.redhat.com/browse/RHEL-8594
CVE: CVE-2023-20569
Conflicts: A merge conflict in arch/x86/include/asm/processor.h
	   due to upstream merge conflict with commit fb3bd914b3ec
	   ("x86/srso: Add a Speculative RAS Overflow mitigation")
	   and commit 77245f1c3c64 ("x86/CPU/AMD: Do not leak quotient
	   data after a division by 0") as resolved by upstream merge
	   commit 97efd28334e2 ("Merge tag 'x86-cleanups-2023-08-28'
	   of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip").

commit 566ffa3ae9649f7aa1debcf559ee7e26ed4a110f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue, 25 Jul 2023 14:17:39 +0200

    x86/cpu: Fix amd_check_microcode() declaration

    The newly added amd_check_microcode() function has two conflicting definitions
    if CONFIG_CPU_SUP_AMD is enabled and CONFIG_MICROCODE_AMD is disabled. Since
    the header with the stub definition is not included in cpu/amd.c, this only
    causes a -Wmissing-prototype warning with W=1:

      arch/x86/kernel/cpu/amd.c:1289:6: error: no previous prototype for 'amd_check_microcode' [-Werror=missing-prototypes]

    Adding the missing #include shows the other problem:

      arch/x86/kernel/cpu/amd.c:1290:6: error: redefinition of 'amd_check_microcode'
      arch/x86/include/asm/microcode_amd.h:58:20: note: previous definition of 'amd_check_microcode' with type 'void(void)'

    Move the declaration into a more appropriate header that is already
    included, with the #ifdef check changed to match the definition's.

    Fixes: 522b1d69219d8 ("x86/cpu/amd: Add a Zenbleed fix")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230725121751.2007665-1-arnd@kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>