KVM: SEV-ES: reduce ghcb_sa_len to 32 bits
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Paolo Bonzini <pbonzini@redhat.com>
commit 9f1ee7b169afbd10c3ad254220d1b37beb5798aa

The size of the GHCB scratch area is limited to 16 KiB (GHCB_SCRATCH_AREA_LIMIT),
so there is no need for it to be a u64.  This fixes a build error on 32-bit
systems:

i686-linux-gnu-ld: arch/x86/kvm/svm/sev.o: in function `sev_es_string_io:
sev.c:(.text+0x110f): undefined reference to `__udivdi3'

	Cc: stable@vger.kernel.org
Fixes: 019057bd73d1 ("KVM: SEV-ES: fix length of string I/O")
	Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 9f1ee7b169afbd10c3ad254220d1b37beb5798aa)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>