selftests: KVM: Fix non-x86 compiling
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2074832

commit 577e022b7b41854911dcfb03678d8d2b930e8a3f
Author: Andrew Jones <drjones@redhat.com>
Date:   Tue Dec 14 16:18:42 2021 +0100

    selftests: KVM: Fix non-x86 compiling

    Attempting to compile on a non-x86 architecture fails with

    include/kvm_util.h: In function â€˜vm_compute_max_gfnâ€™:
    include/kvm_util.h:79:21: error: dereferencing pointer to incomplete type â€˜struct kvm_vmâ€™
      return ((1ULL << vm->pa_bits) >> vm->page_shift) - 1;
                         ^~

    This is because the declaration of struct kvm_vm is in
    lib/kvm_util_internal.h as an effort to make it private to
    the test lib code. We can still provide arch specific functions,
    though, by making the generic function symbols weak. Do that to
    fix the compile error.

    Fixes: c8cc43c1eae2 ("selftests: KVM: avoid failures due to reserved HyperTransport region")
    Cc: stable@vger.kernel.org
    Signed-off-by: Andrew Jones <drjones@redhat.com>
    Message-Id: <20211214151842.848314-1-drjones@redhat.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Conflicts:
       tools/testing/selftests/kvm/include/kvm_util.h (out of order
       7d9a662ed9f0 backport, functions are already defined in
       kvm_util_base.h)

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>