btrfs: Reset IO error counters before start of device replacing
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Yauhen Kharuzhy <yauhen.kharuzhy@zavadatar.com>
commit 7ccefb98ce3e5c4493cd213cd03714b7149cf0cb

If device replace entry was found on disk at mounting and its num_write_errors
stats counter has non-NULL value, then replace operation will never be
finished and -EIO error will be reported by btrfs_scrub_dev() because
this counter is never reset.

 # mount -o degraded /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
 # btrfs replace status /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
 Started on 25.Mar 07:28:00, canceled on 25.Mar 07:28:01 at 0.0%, 40 write errs, 0 uncorr. read errs
 # btrfs replace start -B 4 /dev/sdg /media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/
 ERROR: ioctl(DEV_REPLACE_START) failed on "/media/a4fb5c0a-21c5-4fe7-8d0e-fdd87d5f71ee/": Input/output error, no error

Reset num_write_errors and num_uncorrectable_read_errors counters in the
dev_replace structure before start of replacing.

	Signed-off-by: Yauhen Kharuzhy <yauhen.kharuzhy@zavadatar.com>
	Reviewed-by: David Sterba <dsterba@suse.com>
	Signed-off-by: David Sterba <dsterba@suse.com>
(cherry picked from commit 7ccefb98ce3e5c4493cd213cd03714b7149cf0cb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>