sctp: fix checkpatch errors with open brace '{' and trailing statements
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author wangweidong <wangweidong1@huawei.com>
commit 8d72651d86e9c702d37dd9ef9f084ce027af90a7

fix checkpatch errors below:
ERROR: that open brace { should be on the previous line
ERROR: open brace '{' following function declarations go on the next line
ERROR: trailing statements should be on next line

	Signed-off-by: Wang Weidong <wangweidong1@huawei.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8d72651d86e9c702d37dd9ef9f084ce027af90a7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>