phy: broadcom: sata: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-34114

commit d35c12b7db15e2c1316c32bad24dea2255c5f7b3
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Thu, 10 Aug 2023 13:19:55 +0200

  'version' is an enum, thus cast of pointer on 64-bit compile test with
  W=1 causes:

    phy-brcm-sata.c:775:19: error: cast to smaller integer type 'enum brcm_sata_phy_version' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

  Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
  Link: https://lore.kernel.org/r/20230810111958.205705-1-krzysztof.kozlowski@linaro.org
  Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>