ACPI: OSL: add __printf format attribute to acpi_os_vprintf()
JIRA: https://issues.redhat.com/browse/RHEL-26871

commit 83f5ad58daf1576640bec3aa2f81f003f8e6c48b
Author: Su Hui <suhui@nfschina.com>
Date: Thu, 21 Sep 2023 20:51:27 +0000

With gcc and W=1 option to compile the kernel, warning occurs:

drivers/acpi/osl.c:156:2: error:
function ‘acpi_os_vprintf’ might be a candidate for ‘gnu_printf’
format attribute [-Werror=suggest-attribute=format].

Allow the compiler to recognize and check format strings is safer.

Signed-off-by: Su Hui <suhui@nfschina.com>
[ rjw: Subject and changelog edits ]
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>