mmc: test: reduce stack usage in mmc_test_nonblock_transfer
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [mmc] test: reduce stack usage in mmc_test_nonblock_transfer (Gopal Tiwari) [1456570]
Rebuild_FUZZ: 95.58%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 098dc66adeba4aaa8797124c10c2a77fd2e89584

The new lockdep annotations for completions cause a warning in the
mmc test module, in a function that now has four 150 byte structures
on the stack:

drivers/mmc/core/mmc_test.c: In function 'mmc_test_nonblock_transfer.constprop':
drivers/mmc/core/mmc_test.c:892:1: error: the frame size of 1360 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

The mmc_test_ongoing_transfer function evidently had a similar problem,
and worked around it by using dynamic allocation.

This generalizes the approach used by mmc_test_ongoing_transfer() and
applies it to mmc_test_nonblock_transfer() as well.

Fixes: cd8084f91c02 ("locking/lockdep: Apply crossrelease to completions")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Adrian Hunter <adrian.hunter@intel.com>
	Tested-by: Adrian Hunter <adrian.hunter@intel.com>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
(cherry picked from commit 098dc66adeba4aaa8797124c10c2a77fd2e89584)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>