gcc-15: work around sequence-point warning
JIRA: https://issues.redhat.com/browse/RHEL-89168

commit ac71fabf15679fc7bc56c51bc92bd4b626564c37
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Apr 20 11:30:11 2025 -0700

    gcc-15: work around sequence-point warning
    
    The C sequence points are complicated things, and gcc-15 has apparently
    added a warning for the case where an object is both used and modified
    multiple times within the same sequence point.
    
    That's a great warning.
    
    Or rather, it would be a great warning, except gcc-15 seems to not
    really be very exact about it, and doesn't notice that the modification
    are to two entirely different members of the same object: the array
    counter and the array entries.
    
    So that seems kind of silly.
    
    That said, the code that gcc complains about is unnecessarily
    complicated, so moving the array counter update into a separate
    statement seems like the most straightforward fix for these warnings:
    
      drivers/net/wireless/intel/iwlwifi/mld/d3.c: In function ‘iwl_mld_set_netdetect_info’:
      drivers/net/wireless/intel/iwlwifi/mld/d3.c:1102:66: error: operation on ‘netdetect_info->n_matches’ may be undefined [-Werror=sequence-point]
       1102 |                 netdetect_info->matches[netdetect_info->n_matches++] = match;
            |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~^~
    
      drivers/net/wireless/intel/iwlwifi/mld/d3.c:1120:58: error: operation on ‘match->n_channels’ may be undefined [-Werror=sequence-point]
       1120 |                         match->channels[match->n_channels++] =
            |                                         ~~~~~~~~~~~~~~~~~^~
    
    side note: the code at that second warning is actively buggy, and only
    works on little-endian machines that don't do strict alignment checks.
    
    The code casts an array of integers into an array of unsigned long in
    order to use our bitmap iterators.  That happens to work fine on any
    sane architecture, but it's still wrong.
    
    This does *not* fix that more serious problem.  This only splits the two
    assignments into two statements and fixes the compiler warning.  I need
    to get rid of the new warnings in order to be able to actually do any
    build testing.
    
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>