selftests/bpf: Close the file descriptor to avoid resource leaks
JIRA: https://issues.redhat.com/browse/RHEL-78203

commit be2fea9c07d40a0a897580166e3d43c53ef3b75b
Author: Malaya Kumar Rout <malayarout91@gmail.com>
Date:   Mon Apr 21 23:14:05 2025 +0530

    selftests/bpf: Close the file descriptor to avoid resource leaks
    
    Static analysis found an issue in bench_htab_mem.c and sk_assign.c
    
    cppcheck output before this patch:
    tools/testing/selftests/bpf/benchs/bench_htab_mem.c:284:3: error: Resource leak: fd [resourceLeak]
    tools/testing/selftests/bpf/prog_tests/sk_assign.c:41:3: error: Resource leak: tc [resourceLeak]
    
    cppcheck output after this patch:
    No resource leaks found
    
    Fix the issue by closing the file descriptors fd and tc.
    
    Signed-off-by: Malaya Kumar Rout <malayarout91@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20250421174405.26080-1-malayarout91@gmail.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>