net: xgbe: remove extraneous #ifdef checks
JIRA: https://issues.redhat.com/browse/RHEL-62004

commit 0ef416e045ad7083933b469b6ca7968d1cc0eb80
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 3 10:06:46 2024 +0200

    net: xgbe: remove extraneous #ifdef checks

    When both ACPI and OF are disabled, xgbe_v1 is unused and
    causes a W=1 warning:

    drivers/net/ethernet/amd/xgbe/xgbe-platform.c:533:39: error: unused variable 'xgbe_v1' [-Werror,-Wunused-const-variable]
    static const struct xgbe_version_data xgbe_v1 = {

    There is no real point in trying to save a few bytes for the match
    tables, so just make them always visible.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20240403080702.3509288-29-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>