scsi: qedf: Use designated initializer for struct qed_fcoe_cb_ops
JIRA: https://issues.redhat.com/browse/RHEL-96459

commit d8720235d5b5cad86c1f07f65117ef2a96f8bec7
Author: Kees Cook <kees@kernel.org>
Date:   Fri May 2 15:41:57 2025 -0700

    scsi: qedf: Use designated initializer for struct qed_fcoe_cb_ops

    Recent fixes to the randstruct GCC plugin allowed it to notice
    that this structure is entirely function pointers and is therefore
    subject to randomization, but doing so requires that it always use
    designated initializers. Explicitly specify the "common" member as being
    initialized. Silences:

    drivers/scsi/qedf/qedf_main.c:702:9: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
      702 |         {
          |         ^

    Fixes: 035f7f87b729 ("randstruct: Enable Clang support")
    Link: https://lore.kernel.org/r/20250502224156.work.617-kees@kernel.org
    Signed-off-by: Kees Cook <kees@kernel.org>

Signed-off-by: John Meneghini <jmeneghi@redhat.com>