eth: mlx4: select PAGE_POOL
JIRA: https://issues.redhat.com/browse/RHEL-72015
JIRA: https://issues.redhat.com/browse/RHEL-72020
JIRA: https://issues.redhat.com/browse/RHEL-72224
JIRA: https://issues.redhat.com/browse/RHEL-73519
Upstream-status: v6.15-rc1

commit d3210dabda8dd0477f3a6301dcaf9ed44aeccd3c
Author: Greg Thelen <gthelen@google.com>
Date:   Mon Mar 31 18:53:15 2025 -0700

    eth: mlx4: select PAGE_POOL

    With commit 8533b14b3d65 ("eth: mlx4: create a page pool for Rx") mlx4
    started using functions guarded by PAGE_POOL. This change introduced
    build errors when CONFIG_MLX4_EN is set but CONFIG_PAGE_POOL is not:

      ld: vmlinux.o: in function `mlx4_en_alloc_frags':
      en_rx.c:(.text+0xa5eaf9): undefined reference to `page_pool_alloc_pages'
      ld: vmlinux.o: in function `mlx4_en_create_rx_ring':
      (.text+0xa5ee91): undefined reference to `page_pool_create'

    Make MLX4_EN select PAGE_POOL to fix the ml;x4 build errors.

    Fixes: 8533b14b3d65 ("eth: mlx4: create a page pool for Rx")
    Signed-off-by: Greg Thelen <gthelen@google.com>
    Reviewed-by: Joe Damato <jdamato@fastly.com>
    Link: https://patch.msgid.link/20250401015315.2306092-1-gthelen@google.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Benjamin Poirier <bpoirier@redhat.com>