x86/cfi: Only define poison_cfi() if CONFIG_X86_KERNEL_IBT=y
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 535d0ae39185a266536a1e97ff9a8956d7fbb9df
Author: Ingo Molnar <mingo@kernel.org>
Date:   Tue Jul 11 10:10:40 2023 +0200

    x86/cfi: Only define poison_cfi() if CONFIG_X86_KERNEL_IBT=y

    poison_cfi() was introduced in:

      9831c6253ace ("x86/cfi: Extend ENDBR sealing to kCFI")

    ... but it's only ever used under CONFIG_X86_KERNEL_IBT=y,
    and if that option is disabled, we get:

      arch/x86/kernel/alternative.c:1243:13: error: ‘poison_cfi’ defined but not used [-Werror=unused-function]

    Guard the definition with CONFIG_X86_KERNEL_IBT.

    Cc: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Kees Cook <keescook@chromium.org>
    Cc: Sami Tolvanen <samitolvanen@google.com>
    Cc: linux-kernel@vger.kernel.org
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>