md/raid10: fix set but not used variable in sync_request_write()
JIRA: https://issues.redhat.com/browse/RHEL-112997

commit bc1c2f0ae355f7e30b5baecdfb89d2b148aa0515
Author: John Garry <john.g.garry@oracle.com>
Date:   Wed Jul 9 10:48:14 2025 +0000

    md/raid10: fix set but not used variable in sync_request_write()

    Building with W=1 reports the following:

    drivers/md/raid10.c: In function ‘sync_request_write’:
    drivers/md/raid10.c:2441:21: error: variable ‘d’ set but not used [-Werror=unused-but-set-variable]
     2441 |                 int d;
          |                     ^
    cc1: all warnings being treated as errors

    Remove the usage of that variable.

    Fixes: 752d0464b78a ("md: clean up accounting for issued sync IO")
    Signed-off-by: John Garry <john.g.garry@oracle.com>
    Link: https://lore.kernel.org/linux-raid/20250709104814.2307276-1-john.g.garry@oracle.com
    Signed-off-by: Yu Kuai <yukuai@kernel.org>

Signed-off-by: Ming Lei <ming.lei@redhat.com>