mmc: sdricoh_cs: remove unused sdricoh_readw function
JIRA: https://issues.redhat.com/browse/RHEL-41085

commit cc47d2cf6795c545a257a2e5eda17a00a59da199
Author: Tom Rix <trix@redhat.com>
Date:   Sun Mar 19 12:47:44 2023 -0400

    mmc: sdricoh_cs: remove unused sdricoh_readw function

    clang with W=1 reports
    drivers/mmc/host/sdricoh_cs.c:104:28: error: unused function
      'sdricoh_readw' [-Werror,-Wunused-function]
    static inline unsigned int sdricoh_readw(struct sdricoh_host *host,
                               ^
    This function is not used, so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230319164744.1707169-1-trix@redhat.com
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>