s390/perf: fix compile error (undefined reference sie_exit)
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [s390] perf: fix compile error (undefined reference sie_exit) (Hendrik Brueckner) [1035261]
Rebuild_FUZZ: 95.58%
commit-author Heiko Carstens <heiko.carstens@de.ibm.com>
commit 198b1bf8c3a06de42a88ad7f9d664f18d740a418

The perf_event code references sie_exit even if KVM is not available.
So add proper ifdefs to fix this one:

arch/s390/built-in.o: In function `sys_call_table_emu':
(.rodata+0x2b98): undefined reference to `sie_exit'
arch/s390/built-in.o: In function `sys_call_table_emu':
(.rodata+0x2ba0): undefined reference to `sie_exit'
make: *** [vmlinux] Error 1

	Reported-by: Zhouping Liu <zliu@redhat.com>
	Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
	Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
(cherry picked from commit 198b1bf8c3a06de42a88ad7f9d664f18d740a418)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>