mlx4_en: Select PTP_1588_CLOCK
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [ethernet] mlx4: Select PTP_1588_CLOCK (Amir Vadai) [1107617 1107618 1107619 1107620]
Rebuild_FUZZ: 94.74%
commit-author Shawn Bohrer <sbohrer@rgmadvisors.com>
commit 74b9c3ea847f060c784e86453f1ad77dd05a7a8f

Now that mlx4_en includes a PHC driver it must select PTP_1588_CLOCK.

   drivers/built-in.o: In function `mlx4_en_get_ts_info':
>> en_ethtool.c:(.text+0x391a11): undefined reference to `ptp_clock_index'
   drivers/built-in.o: In function `mlx4_en_remove_timestamp':
>> (.text+0x397913): undefined reference to `ptp_clock_unregister'
   drivers/built-in.o: In function `mlx4_en_init_timestamp':
>> (.text+0x397b20): undefined reference to `ptp_clock_register'

Fixes: ad7d4eaed995d ("mlx4_en: Add PTP hardware clock")
	Signed-off-by: Shawn Bohrer <sbohrer@rgmadvisors.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 74b9c3ea847f060c784e86453f1ad77dd05a7a8f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>