ASoC: nau8810: fix the issue of 64 bits division
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: nau8810: fix the issue of 64 bits division (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.12%
commit-author John Hsu <KCHSU0@nuvoton.com>
commit 3a9ce0f1b2961f6c3ad2a49dcf85449784c18bb5

Do division with div_u64 for the PLL calculation.
These errors are fixed and list as follows:
1."__udivdi3" [sound/soc/codecs/snd-soc-nau8810.ko] undefined!
2."__aeabi_uldivmod" [sound/soc/codecs/snd-soc-nau8810.ko] undefined!
3. nau8810.c:(.text.nau8810_calc_pll+0xd8): undefined reference to
`__udivdi3'

	Signed-off-by: John Hsu <KCHSU0@nuvoton.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 3a9ce0f1b2961f6c3ad2a49dcf85449784c18bb5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>