usb: usblp: clean up assignment inside if conditions
JIRA: https://issues.redhat.com/browse/RHEL-122019

commit d8e1ecffb4a282791be1b3d81a05541749b0db64
Author: Darshan Rathod <darshan.rathod@siqol.com>
Date: Fri, 18 Jul 2025 14:40:45 +0530

  This patch cleans up a few cases where assignments were made
  inside of if conditions, like

  if ((rv = func()) < 0)

  into two lines, to improve readability and be more in-line with
  Linux kernel coding style. It also cleans up checkpatch warnings
  like:

  ERROR: do not use assignment in if condition

  No functional change, just a style and maintainability fix.

  Signed-off-by: Darshan Rathod <darshan.rathod@siqol.com>
  Link: https://lore.kernel.org/r/20250718091045.264129-1-darshan.rathod@siqol.com
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>