bpf: Fix 'dubious one-bit signed bitfield' warnings
Bugzilla: https://bugzilla.redhat.com/2137876

commit f16214c102f0f64b2f3546e989498525bd7b7708
Author: Matthieu Baerts <matthieu.baerts@tessares.net>
Date:   Mon Jul 11 10:12:00 2022 +0200

    bpf: Fix 'dubious one-bit signed bitfield' warnings
    
    Our CI[1] reported these warnings when using Sparse:
    
      $ touch net/mptcp/bpf.c
      $ make C=1 net/mptcp/bpf.o
      net/mptcp/bpf.c: note: in included file:
      include/linux/bpf_verifier.h:348:26: error: dubious one-bit signed bitfield
      include/linux/bpf_verifier.h:349:29: error: dubious one-bit signed bitfield
    
    Set them as 'unsigned' to avoid warnings.
    
    [1] https://github.com/multipath-tcp/mptcp_net-next/actions/runs/2643588487
    
    Fixes: 1ade23711971 ("bpf: Inline calls to bpf_loop when callback is known")
    Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20220711081200.2081262-1-matthieu.baerts@tessares.net

Signed-off-by: Artem Savkov <asavkov@redhat.com>