net/mpls: Implement handler for strict data checking on dumps
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [net] mpls: Implement handler for strict data checking on dumps (Petr Oros) [1700306]
Rebuild_FUZZ: 96.61%
commit-author David Ahern <dsahern@gmail.com>
commit d8a66aa25405e4e3015e4e4e856ef716585d59df

Without CONFIG_INET enabled compiles fail with:

net/mpls/af_mpls.o: In function `mpls_dump_routes':
af_mpls.c:(.text+0xed0): undefined reference to `ip_valid_fib_dump_req'

The preference is for MPLS to use the same handler as ipv4 and ipv6
to allow consistency when doing a dump for AF_UNSPEC which walks
all address families invoking the route dump handler. If INET is
disabled then fallback to an MPLS version which can be tighter on
the data checks.

Fixes: e8ba330ac0c5 ("rtnetlink: Update fib dumps for strict data checking")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Reported-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit d8a66aa25405e4e3015e4e4e856ef716585d59df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>