dax, xfs, ext4: compile out iomap-dax paths in the FS_DAX=n case
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Dan Williams <dan.j.williams@intel.com>
commit f5705aa8cfed142d980ecac12bee0d81b756479e
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/f5705aa8.failed

Tetsuo reports:

  fs/built-in.o: In function `xfs_file_iomap_end':
  xfs_iomap.c:(.text+0xe0ef9): undefined reference to `put_dax'
  fs/built-in.o: In function `xfs_file_iomap_begin':
  xfs_iomap.c:(.text+0xe1a7f): undefined reference to `dax_get_by_host'
  make: *** [vmlinux] Error 1
  $ grep DAX .config
  CONFIG_DAX=m
  # CONFIG_DEV_DAX is not set
  # CONFIG_FS_DAX is not set

When FS_DAX=n we can/must throw away the dax code in filesystems.
Implement 'fs_' versions of dax_get_by_host() and put_dax() that are
nops in the FS_DAX=n case.

	Cc: <linux-xfs@vger.kernel.org>
	Cc: <linux-ext4@vger.kernel.org>
	Cc: Jan Kara <jack@suse.com>
	Cc: "Theodore Ts'o" <tytso@mit.edu>
	Cc: "Darrick J. Wong" <darrick.wong@oracle.com>
	Cc: Ross Zwisler <ross.zwisler@linux.intel.com>
	Tested-by: Tony Luck <tony.luck@intel.com>
Fixes: ef51042472f5 ("block, dax: move 'select DAX' from BLOCK to FS_DAX")
	Reported-by: Tetsuo Handa <penguin-kernel@i-love.sakura.ne.jp>
	Signed-off-by: Dan Williams <dan.j.williams@intel.com>
(cherry picked from commit f5705aa8cfed142d980ecac12bee0d81b756479e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	fs/ext2/inode.c