perf probe: Accept the instance number of kretprobe event
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Masami Hiramatsu <mhiramat@kernel.org>
commit c6aab66a728b6518772c74bd9dff66e1a1c652fd

Since the commit 6a13a0d7b4d1 ("ftrace/kprobe: Show the maxactive number
on kprobe_events") introduced to show the instance number of kretprobe
events, the length of the 1st format of the kprobe event will not 1, but
it can be longer.  This caused a parser error in perf-probe.

Skip the length check the 1st format of the kprobe event to accept this
instance number.

Without this fix:

  # perf probe -a vfs_read%return
  Added new event:
    probe:vfs_read__return (on vfs_read%return)

  You can now use it in all perf tools, such as:

  	perf record -e probe:vfs_read__return -aR sleep 1

  # perf probe -l
  Semantic error :Failed to parse event name: r16:probe/vfs_read__return
    Error: Failed to show event list.

And with this fixes:

  # perf probe -a vfs_read%return
  ...
  # perf probe -l
    probe:vfs_read__return (on vfs_read%return)

Fixes: 6a13a0d7b4d1 ("ftrace/kprobe: Show the maxactive number on kprobe_events")
	Reported-by: Yuxuan Shui <yshuiv7@gmail.com>
	Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
	Tested-by: Yuxuan Shui <yshuiv7@gmail.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: stable@vger.kernel.org
Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=207587
Link: http://lore.kernel.org/lkml/158877535215.26469.1113127926699134067.stgit@devnote2
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit c6aab66a728b6518772c74bd9dff66e1a1c652fd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>