scsi: mpt3sas: Drop unused variable in mpt3sas_send_mctp_passthru_req()
JIRA: https://issues.redhat.com/browse/RHEL-101342

With W=1, gcc complains correctly:

    mpt3sas_ctl.c: In function ‘mpt3sas_send_mctp_passthru_req’:
    mpt3sas_ctl.c:2917:29: error: variable ‘mpi_reply’ set but not used [-Werror=unused-but-set-variable]
     2917 |         MPI2DefaultReply_t *mpi_reply;
          |                             ^~~~~~~~~

Drop the unused assignment and variable.

Signed-off-by: André Draszik <andre.draszik@linaro.org>
Link: https://lore.kernel.org/r/20250606-mpt3sas-v1-1-906ffe49fb6b@linaro.org
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 0ec996edf4fdb727340ec9f50e2795042c23cd86)
Signed-off-by: Chandrakanth Patil <chanpati@redhat.com>