net/sched/sch_red.c: work around gcc-4.4.4 anon union initializer issue
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [net] sched: red: work around gcc-4.4.4 anon union initializer issue (Ivan Vecera) [1583702]
Rebuild_FUZZ: 90.23%
commit-author Andrew Morton <akpm@linux-foundation.org>
commit ee9d3429c0e47a57e3e73b638785cafa33773639
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/ee9d3429.failed

gcc-4.4.4 (at lest) has issues with initializers and anonymous unions:

net/sched/sch_red.c: In function 'red_dump_offload':
net/sched/sch_red.c:282: error: unknown field 'stats' specified in initializer
net/sched/sch_red.c:282: warning: initialization makes integer from pointer without a cast
net/sched/sch_red.c:283: error: unknown field 'stats' specified in initializer
net/sched/sch_red.c:283: warning: initialization makes integer from pointer without a cast
net/sched/sch_red.c: In function 'red_dump_stats':
net/sched/sch_red.c:352: error: unknown field 'xstats' specified in initializer
net/sched/sch_red.c:352: warning: initialization makes integer from pointer without a cast

Work around this.

Fixes: 602f3baf2218 ("net_sch: red: Add offload ability to RED qdisc")
	Cc: Nogah Frankel <nogahf@mellanox.com>
	Cc: Jiri Pirko <jiri@mellanox.com>
	Cc: Simon Horman <simon.horman@netronome.com>
	Cc: David S. Miller <davem@davemloft.net>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit ee9d3429c0e47a57e3e73b638785cafa33773639)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	net/sched/sch_red.c