selftests/bpf: Fix error compiling cgroup_ancestor.c with musl libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 60f802e2d6e10df609a80962b13558b7455ab32b
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Tue Oct 8 16:12:32 2024 -0700

    selftests/bpf: Fix error compiling cgroup_ancestor.c with musl libc

    Existing code calls connect() with a 'struct sockaddr_in6 *' argument
    where a 'struct sockaddr *' argument is declared, yielding compile errors
    when building for mips64el/musl-libc:

    In file included from cgroup_ancestor.c:3:
    cgroup_ancestor.c: In function 'send_datagram':
    cgroup_ancestor.c:38:38: error: passing argument 2 of 'connect' from incompatible pointer type [-Werror=incompatible-pointer-types]
       38 |         if (!ASSERT_OK(connect(sock, &addr, sizeof(addr)), "connect")) {
          |                                      ^~~~~
          |                                      |
          |                                      struct sockaddr_in6 *
    ./test_progs.h:343:29: note: in definition of macro 'ASSERT_OK'
      343 |         long long ___res = (res);                                       \
          |                             ^~~
    In file included from .../netinet/in.h:10,
                     from .../arpa/inet.h:9,
                     from ./test_progs.h:17:
    .../sys/socket.h:386:19: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_in6 *'
      386 | int connect (int, const struct sockaddr *, socklen_t);
          |                   ^~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    This only compiles because of a glibc extension allowing declaration of the
    argument as a "transparent union" which includes both types above.

    Explicitly cast the argument to allow compiling for both musl and glibc.

    Cc: Alexis Lothoré (eBPF Foundation) <alexis.lothore@bootlin.com>
    Fixes: f957c230e173 ("selftests/bpf: convert test_skb_cgroup_id_user to test_progs")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Reviewed-by: Alexis Lothoré <alexis.lothore@bootlin.com>
    Link: https://lore.kernel.org/r/20241008231232.634047-1-tony.ambardar@gmail.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>