drm: bridge: for GENERIC_PHY_MIPI_DPHY also select GENERIC_PHY
JIRA: https://issues.redhat.com/browse/RHEL-1351
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.6.2)

commit b86ec59f7dae621725a1860ebbd8f0e2e9bc1eec
Author:     Randy Dunlap <rdunlap@infradead.org>
AuthorDate: Thu Aug  3 20:01:37 2023 -0700
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Mon Nov 20 11:59:08 2023 +0100

    [ Upstream commit 96413b355a49fd684430a230479bd231d977894f ]

    Three DRM bridge drivers select GENERIC_PHY_MIPI_DPHY when GENERIC_PHY
    might not be set.  This causes Kconfig warnings and a build error.

    WARNING: unmet direct dependencies detected for GENERIC_PHY_MIPI_DPHY
      Depends on [n]: GENERIC_PHY [=n]
      Selected by [y]:
      - DRM_NWL_MIPI_DSI [=y] && DRM_BRIDGE [=y] && DRM [=y] && COMMON_CLK [=y] && OF [=y] && HAS_IOMEM [=y]
      - DRM_SAMSUNG_DSIM [=y] && DRM [=y] && DRM_BRIDGE [=y] && COMMON_CLK [=y] && OF [=y] && HAS_IOMEM [=y]

    (drm/bridge/cadence/Kconfig was found by inspection.)

    aarch64-linux-ld: drivers/gpu/drm/bridge/samsung-dsim.o: in function `samsung_dsim_set_phy_ctrl':
    drivers/gpu/drm/bridge/samsung-dsim.c:731: undefined reference to `phy_mipi_dphy_get_default_config_for_hsclk'

    Prevent these warnings and build error by also selecting GENERIC_PHY
    whenever selecting GENERIC_PHY_MIPI_DPHY.

    Fixes: fced5a364dee ("drm/bridge: cdns: Convert to phy framework")
    Fixes: 44cfc6233447 ("drm/bridge: Add NWL MIPI DSI host controller support")
    Fixes: 171b3b1e0f8b ("drm: bridge: samsung-dsim: Select GENERIC_PHY_MIPI_DPHY")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Aleksandr Nogikh <nogikh@google.com>
    Link: lore.kernel.org/r/20230803144227.2187749-1-nogikh@google.com
    Cc: Adam Ford <aford173@gmail.com>
    Cc: Maxime Ripard <maxime.ripard@bootlin.com>
    Cc: Guido Günther <agx@sigxcpu.org>
    Cc: Robert Chiras <robert.chiras@nxp.com>
    Cc: Sam Ravnborg <sam@ravnborg.org>
    Cc: Neil Armstrong <neil.armstrong@linaro.org>
    Cc: Andrzej Hajda <andrzej.hajda@intel.com>
    Cc: Robert Foss <rfoss@kernel.org>
    Cc: David Airlie <airlied@gmail.com>
    Cc: Daniel Vetter <daniel@ffwll.ch>
    Cc: dri-devel@lists.freedesktop.org
    Reviewed-by: Adam Ford <aford173@gmail.com>
    Tested-by: Aleksandr Nogikh <nogikh@google.com>
    Reviewed-by: Guido Günther <agx@sigxcpu.org>
    Signed-off-by: Robert Foss <rfoss@kernel.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20230804030140.21395-1-rdunlap@infradead.org
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>