firmware: qcom: qcm: fix unused qcom_scm_qseecom_allowlist
JIRA: https://issues.redhat.com/browse/RHEL-73299

commit e478c5fb6aa10af7b7edbff69bc8aef6fbb5f0ed
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Mon Nov 20 19:56:23 2023 +0100

    firmware: qcom: qcm: fix unused qcom_scm_qseecom_allowlist

    For !OF builds, the qcom_scm_qseecom_allowlist is unused:

      drivers/firmware/qcom/qcom_scm.c:1652:34: error: ‘qcom_scm_qseecom_allowlist’ defined but not used [-Werror=unused-const-variable=]

    Fixes: 00b1248606ba ("firmware: qcom_scm: Add support for Qualcomm Secure Execution Environment SCM interface")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202311191654.S4wlVUrz-lkp@intel.com/
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Acked-by: Maximilian Luz <luzmaximilian@gmail.com>
    Link: https://lore.kernel.org/r/20231120185623.338608-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Bjorn Andersson <andersson@kernel.org>

Signed-off-by: Jennifer Berringer <jberring@redhat.com>