ASoC: rt1320: fix size_t format string
JIRA: https://issues.redhat.com/browse/RHEL-168091

commit 284853affe73fe1ca9786bd52b934eb9d420a942
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue Dec 23 22:53:19 2025 +0100

    ASoC: rt1320: fix size_t format string

    Printing a size_t portably requires the use of %z instead of %l:

    sound/soc/codecs/rt1320-sdw.c:1494:30: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
     1494 |                 dev_dbg(dev, "%s, rae_fw size=0x%lx\n", __func__, rae_fw->size);
          |                              ^~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: 22937af75abb ("ASoC: rt1320: support RAE parameters loading")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20251223215322.694265-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>