platform/x86/amd/hsmp: fix building with CONFIG_HWMON=m
JIRA: https://issues.redhat.com/browse/RHEL-102859

commit 69157b00b526c31522a00b9908bfd53fa21b47f2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu May 22 16:38:49 2025 +0200

    platform/x86/amd/hsmp: fix building with CONFIG_HWMON=m

    When CONFIG_HWMON is built as a loadable module, the HSMP drivers
    cannot be built-in:

    ERROR: modpost: "hsmp_create_sensor" [drivers/platform/x86/amd/hsmp/amd_hsmp.ko] undefined!
    ERROR: modpost: "hsmp_create_sensor" [drivers/platform/x86/amd/hsmp/hsmp_acpi.ko] undefined!

    Enforce that through the usual Kconfig dependnecy trick.

    Fixes: 92c025db52bb ("platform/x86/amd/hsmp: Report power via hwmon sensors")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250522144422.2824083-1-arnd@kernel.org
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>