audit: Add __rcu annotation to RCU pointer
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Amol Grover <frextrite@gmail.com>
commit cb5172d96d16df72db8b55146b0ec00bfd97f079

Add __rcu annotation to RCU-protected global pointer auditd_conn.

auditd_conn is an RCU-protected global pointer,i.e., accessed
via RCU methods rcu_dereference() and rcu_assign_pointer(),
hence it must be annotated with __rcu for sparse to report
warnings/errors correctly.

Fix multiple instances of the sparse error:
error: incompatible types in comparison expression
(different address spaces)

	Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
	Signed-off-by: Amol Grover <frextrite@gmail.com>
[PM: tweak subject line]
	Signed-off-by: Paul Moore <paul@paul-moore.com>
(cherry picked from commit cb5172d96d16df72db8b55146b0ec00bfd97f079)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>