selftests: net: fix error message in bpf_offload
jira LE-4076
Rebuild_History Non-Buildable kernel-6.12.0-55.29.1.el10_0
commit-author Jakub Kicinski <kuba@kernel.org>
commit f9d2f5ddd47cd4e8092b0dc1d4cc488d27e5e191

We hit a following exception on timeout, nmaps is never set:

    Test bpftool bound info reporting (own ns)...
    Traceback (most recent call last):
      File "/home/virtme/testing-1/tools/testing/selftests/net/./bpf_offload.py", line 1128, in <module>
        check_dev_info(False, "")
      File "/home/virtme/testing-1/tools/testing/selftests/net/./bpf_offload.py", line 583, in check_dev_info
        maps = bpftool_map_list_wait(expected=2, ns=ns)
      File "/home/virtme/testing-1/tools/testing/selftests/net/./bpf_offload.py", line 215, in bpftool_map_list_wait
        raise Exception("Time out waiting for map counts to stabilize want %d, have %d" % (expected, nmaps))
    NameError: name 'nmaps' is not defined

	Acked-by: Stanislav Fomichev <sdf@fomichev.me>
Link: https://patch.msgid.link/20250304233204.1139251-1-kuba@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit f9d2f5ddd47cd4e8092b0dc1d4cc488d27e5e191)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>