ASoC: cs35l41: Fix undefined reference to core functions
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Lucas Tanure <tanureal@opensource.cirrus.com>
commit 0695ad92fe1a0bb7697eb92c6a145a73c5ab0e24

Auto select core driver if i2c or spi bus drivers are
selected

Fixes: a5e0091d62ab ("ASoC: cs35l41: Fix link problem")

	Signed-off-by: Lucas Tanure <tanureal@opensource.cirrus.com>
	Reported-by: kernel test robot <lkp@intel.com>
Link: https://lore.kernel.org/r/20211201180004.1402156-2-tanureal@opensource.cirrus.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0695ad92fe1a0bb7697eb92c6a145a73c5ab0e24)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>