drm/tegra: Mark nvdec PM functions as __maybe_unused
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2154295
Upstream Status: v5.17-rc1

commit e1189fafa5a1c49407a1bc01d850cc6dd52c058d
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Wed Oct 13 16:41:36 2021 +0200
Commit:     Thierry Reding <treding@nvidia.com>
CommitDate: Thu Dec 16 14:07:07 2021 +0100

    The resume helper is called conditionally and causes a harmless warning
    when stubbed out:

    drivers/gpu/drm/tegra/nvdec.c:240:12: error: 'nvdec_runtime_resume' defined but not used [-Werror=unused-function]
      240 | static int nvdec_runtime_resume(struct device *dev)

    Mark both suspend and resume as __maybe_unused for consistency to avoid
    this warning.

    Fixes: e76599df354d ("drm/tegra: Add NVDEC driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thierry Reding <treding@nvidia.com>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>