enic: Fix 64 bit divide on 32bit system
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Govindarajulu Varadarajan <_govind@gmx.com>
commit 958c492c55bff6fa0b3430e9824dc83597c88aa6

Division of a 32 bit number by a 64 bit number causes the following link
error introduced by
7c2ce6e60f703 "enic: Add support for adaptive interrupt coalescing"

drivers/built-in.o: In function `enic_poll_msix':
enic_main.c:(.text+0x48710a): undefined reference to `__udivdi3'
make: *** [vmlinux] Error 1

Since numerator is 32 bit, convert denominator to 32 bit accordingly.

Fixes: 7c2ce6e60f703 ("enic: Add support for adaptive interrupt coalescing")
	Reported-by: Jim Davis <jim.epost@gmail.com>
	Cc: Christian Benvenuti <benve@cisco.com>
	Cc: Sujith Sankar <ssujith@cisco.com>
	Cc: Neel Patel <neepatel@cisco.com>
	Signed-off-by: Govindarajulu Varadarajan <_govind@gmx.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 958c492c55bff6fa0b3430e9824dc83597c88aa6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>