fbdev: au1100fb: Fix build on MIPS64
JIRA: https://redhat.atlassian.net/browse/RHEL-135265

commit e31a374a99f5026df6ebff2a1c49492276e776fd
Author: Helge Deller <deller@gmx.de>
Date:   Wed Mar 4 19:15:48 2026 +0100

    fbdev: au1100fb: Fix build on MIPS64

    Fix an error reported by the kernel test robot:
     au1100fb.c: error: implicit declaration of function 'KSEG1ADDR'; did you mean 'CKSEG1ADDR'?

    arch/mips/include/asm/addrspace.h defines KSEG1ADDR only for 32 bit
    configurations. So provide its compile-test stub also for 64bit mips builds.

    Fixes: 6f366e86481a ("fbdev: au1100fb: Make driver compilable on non-mips platforms")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202603042127.PT6LuKqi-lkp@intel.com/
    Signed-off-by: Helge Deller <deller@gmx.de>
    Acked-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>