perf bpf: Defer freeing string after possible strlen() on it
Bugzilla: https://bugzilla.redhat.com/2069073

upstream
========
commit 31ded1535e3182778a1d0e5c32711f55da3bc512
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Feb 16 16:01:00 2022 -0300

description
===========
This was detected by the gcc in Fedora Rawhide's gcc:

  50    11.01 fedora:rawhide                : FAIL gcc version 12.0.1 20220205 (Red Hat 12.0.1-0) (GCC)
        inlined from 'bpf__config_obj' at util/bpf-loader.c:1242:9:
    util/bpf-loader.c:1225:34: error: pointer 'map_opt' may be used after 'free' [-Werror=use-after-free]
     1225 |                 *key_scan_pos += strlen(map_opt);
          |                                  ^~~~~~~~~~~~~~~
    util/bpf-loader.c:1223:9: note: call to 'free' here
     1223 |         free(map_name);
          |         ^~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

So do the calculations on the pointer before freeing it.

Fixes: 04f9bf2bac72480c ("perf bpf-loader: Add missing '*' for key_scan_pos")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>