perf probe: Check kprobes blacklist when adding new events
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Check kprobes blacklist when adding new events (Jiri Olsa) [1222189]
Rebuild_FUZZ: 95.50%
commit-author Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
commit 9aaf5a5f479bd68699f2e6f6e5e5f1253377b6da

Recent linux kernel provides a blacklist of the functions which can not
be probed. perf probe can now check this blacklist before setting new
events and indicate better error message for users.

Without this patch,
  ----
  # perf probe --add vmalloc_fault
  Added new event:
  Failed to write event: Invalid argument
    Error: Failed to add events.
  ----
With this patch
  ----
  # perf probe --add vmalloc_fault
  Added new event:
  Warning: Skipped probing on blacklisted function: vmalloc_fault
  ----

	Reported-by: Arnaldo Carvalho de Melo <acme@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/20150219143113.14434.5387.stgit@localhost.localdomain
	Signed-off-by: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 9aaf5a5f479bd68699f2e6f6e5e5f1253377b6da)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>