scsi: qla2xxx: Silence a static checker warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-527.el8
commit-author Dan Carpenter <dan.carpenter@linaro.org>
commit 134f66959cd0bc90a745f2eed4c10a0519d455c4

Smatch and Clang both complain that LOGIN_TEMPLATE_SIZE is more than
sizeof(ha->plogi_els_payld.fl_csp).

Smatch warning:
    drivers/scsi/qla2xxx/qla_iocb.c:3075 qla24xx_els_dcmd2_iocb()
    warn: '&ha->plogi_els_payld.fl_csp' sometimes too small '16' size = 112

Clang warning:
    include/linux/fortify-string.h:592:4: error: call to
    '__read_overflow2_field' declared with 'warning' attribute: detected
    read beyond size of field (2nd parameter); maybe use struct_group()?
    [-Werror,-Wattribute-warning]
                        __read_overflow2_field(q_size_field, size);

When I was reading this code I assumed the "- 4" meant that we were
skipping the last 4 bytes but actually it turned out that we are
skipping the first four bytes.

I have re-written it remove the magic numbers, be more clear and
silence the static checker warnings.

	Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
Link: https://lore.kernel.org/r/4aa0485e-766f-4b02-8d5d-c6781ea8f511@moroto.mountain
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 134f66959cd0bc90a745f2eed4c10a0519d455c4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>