net/mlx5e: Fix build error in fec_set_block_stats()
Bugzilla: https://bugzilla.redhat.com/2049450
Upstream-status: v5.17-rc1

commit 342402c426902c59491b43d3056a1039e5ca02db
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Sun Jan 9 13:33:21 2022 -0800

    net/mlx5e: Fix build error in fec_set_block_stats()

    Build bot reports:

    drivers/net/ethernet/mellanox/mlx5/core/en_stats.c: In function 'fec_set_block_stats':
    drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:1235:48: error: 'outl' undeclared (first use in this function); did you mean 'out'?
        1235 |         if (mlx5_core_access_reg(mdev, in, sz, outl, sz, MLX5_REG_PPCNT, 0, 0))
             |                                                ^~~~
             |                                                out

    Reported-by: kernel test robot <lkp@intel.com>
    Suggested-by: Leon Romanovsky <leon@kernel.org>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>
    Link: https://lore.kernel.org/r/20220109213321.2292830-1-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>