powerpc: move arch_trigger_cpumask_backtrace from nmi.h to irq.h
JIRA: https://issues.redhat.com/browse/RHEL-143910

commit df8b78e1630fa6cff82fdc33ce04000e3ed065f7
Author: Douglas Anderson <dianders@chromium.org>
Date:   Wed, 21 Jun 2023 16:48:19 -0700

    powerpc: move arch_trigger_cpumask_backtrace from nmi.h to irq.h

    The powerpc architecture was the only one that defined
    arch_trigger_cpumask_backtrace() in asm/nmi.h instead of
    asm/irq.h. Move it to be consistent.

    This fixes compile time errors introduced by commit 7ca8fe94aa92
    ("watchdog/hardlockup: define HARDLOCKUP_DETECTOR_ARCH"). That commit
    caused <asm/nmi.h> to stop being included if the hardlockup detector
    wasn't enabled. The specific errors were:
      error: implicit declaration of function `nmi_cpu_backtrace'
      error: implicit declaration of function `nmi_trigger_cpumask_backtrace'

    NOTE: when moving this into irq.h, we also change the guards from just
    checking if "CONFIG_NMI_IPI" is defined to also checking if
    "CONFIG_PPC_BOOK3S_64" is defined. This matches the code in
    arch/powerpc/kernel/stacktrace.c. Previously this worked because
    <asm.nmi.h> was included if "CONFIG_HAVE_HARDLOCKUP_DETECTOR_ARCH" was
    defined. For powerpc that's only selected if "CONFIG_PPC_BOOK3S_64" is
    defined.

    [dianders@chromium.org: change the guards to include CONFIG_PPC_BOOK3S_64]
      Link: https://lkml.kernel.org/r/20230622202816.v2.1.Ice67126857506712559078e7de26d32d26e64631@changeid
    Link: https://lkml.kernel.org/r/20230621164809.1.Ice67126857506712559078e7de26d32d26e64631@changeid
    Fixes: 7ca8fe94aa92 ("watchdog/hardlockup: define HARDLOCKUP_DETECTOR_ARCH")
    Signed-off-by: Douglas Anderson <dianders@chromium.org>
    Reported-by: Michael Ellerman <mpe@ellerman.id.au>
    Closes: https://lore.kernel.org/r/871qi5otdh.fsf@mail.lhotse
    Reviewed-by: Petr Mladek <pmladek@suse.com>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Cc: Christophe Leroy <christophe.leroy@csgroup.eu>
    Cc: Douglas Anderson <dianders@chromium.org>
    Cc: Laurent Dufour <ldufour@linux.ibm.com>
    Cc: Nicholas Piggin <npiggin@gmail.com>
    Cc: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Tom Rix <trix@redhat.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>