coresight: syscfg: Fix compiler warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2055405

commit 212b5d2d3ed9d7db2702e4805f36a346c3985e1d
Author: Jian Cai <jiancai@google.com>
Date:   Mon Sep 13 10:46:13 2021 -0600

    coresight: syscfg: Fix compiler warning

    This fixes warnings with -Wimplicit-function-declaration, e.g.

    drivers/hwtracing/coresight/coresight-syscfg.c:455:15: error:
    implicit declaration of function 'kzalloc' [-Werror,
    -Wimplicit-function-declaration]
            csdev_item = kzalloc(sizeof(struct cscfg_registered_csdev),
                                 GFP_KERNEL);

    Link: https://lore.kernel.org/r/20210830172820.2840433-1-jiancai@google.com
    Fixes: 85e2414c518a ("coresight: syscfg: Initial coresight system configuration")
    Reviewed-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Jian Cai <jiancai@google.com>
    Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>
    Link: https://lore.kernel.org/r/20210913164613.1675791-2-mathieu.poirier@linaro.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jeremy Linton <jlinton@redhat.com>