ASoC: codecs: wcd934x: add Slimbus dependency
Bugzilla: https://bugzilla.redhat.com/2179848

commit 9815746c48ebbd38d32a7a1dade7fa1e3948c54d
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Thu Sep 1 13:14:57 2022 +0300

    ASoC: codecs: wcd934x: add Slimbus dependency

    The WCD934X codec is a Slimbus driver, so it must depend on SLIMBUS,
    also for compile tests:

      ERROR: modpost: "slim_stream_prepare" [sound/soc/codecs/snd-soc-wcd934x.ko] undefined!

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: 5b7f4e5de61b ("ASoC: codecs: allow compile testing without MFD drivers")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20220901101458.365354-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>