scsi: qla2xxx: Fix code indentation for qla27xx_fwdt_entry
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Himanshu Madhani <hmadhani@marvell.com>
commit 5241f7ca62b35e582c3b94aea62a0ac42df369c7

This patch fixes following checkpatch ERROR

 ERROR: space prohibited before that ',' (ctx:WxW)

No change is functionality due to this patch.

	Signed-off-by: Himanshu Madhani <hmadhani@marvell.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 5241f7ca62b35e582c3b94aea62a0ac42df369c7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>