net: ena: removed unused tx_bytes variable
JIRA: https://issues.redhat.com/browse/RHEL-28811

commit c5370374bb1bf692167c7276be8b56c02565d535
Author: Simon Horman <horms@kernel.org>
Date:   Tue Mar 28 17:19:58 2023 +0200

    net: ena: removed unused tx_bytes variable

    clang 16.0.0 with W=1 reports:

    drivers/net/ethernet/amazon/ena/ena_netdev.c:1901:6: error: variable 'tx_bytes' set but not used [-Werror,-Wunused-but-set-variable]
            u32 tx_bytes = 0;

    The variable is not used so remove it.

    Signed-off-by: Simon Horman <horms@kernel.org>
    Acked-by: Shay Agroskin <shayagr@amazon.com>
    Link: https://lore.kernel.org/r/20230328151958.410687-1-horms@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>