ASoC: mediatek: mt8195: silence uninitialized variable warning
Smatch complains that we might hit the continue path on every iteration
through the loop.

    sound/soc/mediatek/mt8195/mt8195-mt6359-rt1019-rt5682.c:831
      mt8195_mt6359_rt1019_rt5682_card_late_probe()
    error: uninitialized symbol 'sof_comp'.

Initialize "sof_comp" to NULL to silence this warning.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Link: https://lore.kernel.org/r/20211208151145.GA29257@kili
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Dan Carpenter <dan.carpenter@oracle.com>
Date: Wed Dec 8 18:11:45 2021 +0300

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 9abc21c966619d6ead27fd48481966014fdc680f)
Bugzilla: https://bugzilla.redhat.com/2065572