efi/cper: Adjust infopfx size to accept an extra space
JIRA: https://redhat.atlassian.net/browse/RHEL-168822

commit 8ad2c72e21efb3dc76c5b14089fa7984cdd87898
Author: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
Date:   Thu Aug 14 09:52:53 2025 -0700

    efi/cper: Adjust infopfx size to accept an extra space

    Compiling with W=1 with werror enabled produces an error:

    drivers/firmware/efi/cper-arm.c: In function ‘cper_print_proc_arm’:
    drivers/firmware/efi/cper-arm.c:298:64: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
      298 |                         snprintf(infopfx, sizeof(infopfx), "%s ", newpfx);
          |                                                                ^
    drivers/firmware/efi/cper-arm.c:298:25: note: ‘snprintf’ output between 2 and 65 bytes into a destination of size 64
      298 |                         snprintf(infopfx, sizeof(infopfx), "%s ", newpfx);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    As the logic there adds an space at the end of infopx buffer.
    Add an extra space to avoid such warning.

    Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
    Reviewed-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Acked-by: Borislav Petkov (AMD) <bp@alien8.de>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

Signed-off-by: Thomas Huth <thuth@redhat.com>