rcu: Export init_rcu_head() and destroy_rcu_head() to GPL modules
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
commit-author Paul E. McKenney <paulmck@linux.vnet.ibm.com>
commit 156baec39732f025dc778e00da95fc10d6e45885
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1062.el7/156baec3.failed

Use of init_rcu_head() and destroy_rcu_head() from modules results in
the following build-time error with CONFIG_DEBUG_OBJECTS_RCU_HEAD=y:

	ERROR: "init_rcu_head" [drivers/scsi/scsi_mod.ko] undefined!
	ERROR: "destroy_rcu_head" [drivers/scsi/scsi_mod.ko] undefined!

This commit therefore adds EXPORT_SYMBOL_GPL() for each to allow them to
be used by GPL-licensed kernel modules.

	Reported-by: Bart Van Assche <Bart.VanAssche@wdc.com>
	Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 156baec39732f025dc778e00da95fc10d6e45885)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	kernel/rcu/update.c