uapi: fix linux/tls.h userspace compilation error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [uapi] fix linux/tls.h userspace compilation error (Ivan Vecera) [1653376]
Rebuild_FUZZ: 93.48%
commit-author Dmitry V. Levin <ldv@altlinux.org>
commit b9f3eb499d84f8d4adcb2f9212ec655700b28228
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1062.el7/b9f3eb49.failed

Move inclusion of a private kernel header <net/tcp.h>
from uapi/linux/tls.h to its only user - net/tls.h,
to fix the following linux/tls.h userspace compilation error:

/usr/include/linux/tls.h:41:21: fatal error: net/tcp.h: No such file or directory

As to this point uapi/linux/tls.h was totaly unusuable for userspace,
cleanup this header file further by moving other redundant includes
to net/tls.h.

Fixes: 3c4d7559159b ("tls: kernel TLS support")
	Cc: <stable@vger.kernel.org> # v4.13+
	Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b9f3eb499d84f8d4adcb2f9212ec655700b28228)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	include/net/tls.h