ALSA: ymfpci: remove unused snd_ymfpci_readb function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Tom Rix <trix@redhat.com>
commit 0b40261256a71184c6bca487b91e6b748b077709

clang with W=1 reports
sound/pci/ymfpci/ymfpci_main.c:34:18: error:
  unused function 'snd_ymfpci_readb' [-Werror,-Wunused-function]
static inline u8 snd_ymfpci_readb(struct snd_ymfpci *chip, u32 offset)
                 ^
This static function is not used, so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230318132708.1684504-1-trix@redhat.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 0b40261256a71184c6bca487b91e6b748b077709)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>