x86/hyperv: Add missing 'inline' to hv_snp_boot_ap() stub
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2176350

commit f0a3d1de89876f4ca54fccb4103b504d50a8347f
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Tue Aug 22 11:25:49 2023 -0700

    x86/hyperv: Add missing 'inline' to hv_snp_boot_ap() stub

    When building without CONFIG_AMD_MEM_ENCRYPT, there are several
    repeated instances of -Wunused-function due to missing 'inline' on
    the stub of hy_snp_boot_ap():

      In file included from drivers/hv/hv_common.c:29:
      ./arch/x86/include/asm/mshyperv.h:272:12: error: 'hv_snp_boot_ap' defined but not used [-Werror=unused-function]
        272 | static int hv_snp_boot_ap(int cpu, unsigned long start_ip) { return 0; }
            |            ^~~~~~~~~~~~~~
      cc1: all warnings being treated as errors

    Add 'inline' to fix the warnings.

    Fixes: 44676bb9d566 ("x86/hyperv: Add smp support for SEV-SNP guest")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Dexuan Cui <decui@microsoft.com>
    Signed-off-by: Wei Liu <wei.liu@kernel.org>
    Link: https://lore.kernel.org/r/20230822-hv_snp_boot_ap-missing-inline-v1-1-e712dcb2da0f@kernel.org

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>