scsi_error: should not get sense for timeout IO in scsi error handler
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author jiang.biao2@zte.com.cn <jiang.biao2@zte.com.cn>
commit 709c75b5a2411c31e5a649a2cd6d4866dd11f456

scsi_error: should not get sense for timeout IO in scsi error handler

When an IO timeout occurs, the IO will be aborted in
scsi_abort_command() and SCSI_EH_ABORT_SCHEDULED will be set. Because
of that, the SCSI_EH_CANCEL_CMD will be clear in scsi_eh_scmd_add().
So when scsi error handler starts, it will get sense for this
timeout IO and the scmd of the IO request will be reused. In that
case, the scmd may be double released when racing with io_done(),
which will result in crash.
SO SCSI_EH_ABORT_SCHEDULED should also be checked when getting sense.
The bug maybe reproduced when the link between host and disk is
unstable.

	Signed-off-by: Jiang Biao <jiang.biao2@zte.com.cn>
	Signed-off-by: Long Chun <long.chun@zte.com.cn>
	Reviewed-by: Tan Hu <tan.hu@zte.com.cn>
	Reviewed-by: Chen Donghai <chen.donghai@zte.com.cn>
	Reviewed-by: Cai Qu <cai.qu@zte.com.cn>
	Signed-off-by: James Bottomley <JBottomley@Odin.com>
(cherry picked from commit 709c75b5a2411c31e5a649a2cd6d4866dd11f456)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>