thunderbolt: build kunit tests without structleak plugin
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author Brendan Higgins <brendanhiggins@google.com>
commit 33d4951e021bb67ebd6bdb01f3d437c0f45b3c0c

The structleak plugin causes the stack frame size to grow immensely when
used with KUnit:

drivers/thunderbolt/test.c:1529:1: error: the frame size of 1176 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

Linus already split up tests in this file, so this change *should* be
redundant now.

	Signed-off-by: Brendan Higgins <brendanhiggins@google.com>
	Suggested-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Mika Westerberg <mika.westerberg@linux.intel.com>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit 33d4951e021bb67ebd6bdb01f3d437c0f45b3c0c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>