net/mlx5e: reduce stack usage in mlx5_eswitch_termtbl_create
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1127.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit 5233794b179136d597b84188c1285148f07012e6
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1127.el7/5233794b.failed

Putting an empty 'mlx5_flow_spec' structure on the stack is a bit
wasteful and causes a warning on 32-bit architectures when building
with clang -fsanitize-coverage:

drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads_termtbl.c: In function 'mlx5_eswitch_termtbl_create':
drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads_termtbl.c:90:1: error: the frame size of 1032 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Since the structure is never written to, we can statically allocate
it to avoid the stack usage. To be on the safe side, mark all
subsequent function arguments that we pass it into as 'const'
as well.

Fixes: 10caabdaad5a ("net/mlx5e: Use termination table for VLAN push actions")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Saeed Mahameed <saeedm@mellanox.com>
	Acked-by: Mark Bloch <markb@mellanox.com>
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
(cherry picked from commit 5233794b179136d597b84188c1285148f07012e6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads_termtbl.c
#	drivers/net/ethernet/mellanox/mlx5/core/fs_core.c