selftests: netfilter: nft_nat.sh: add test for reverse clash with nat
JIRA: https://issues.redhat.com/browse/RHEL-99656

commit 3c3c3248496a3a1848ec5d923f2eee0edf60226e
Author: Florian Westphal <fw@strlen.de>
Date:   Fri May 30 12:34:03 2025 +0200

    selftests: netfilter: nft_nat.sh: add test for reverse clash with nat

    This will fail without the previous bug fix because we erronously
    believe that the clashing entry went way.

    However, the clash exists in the opposite direction due to an
    existing nat mapping:
     PASS: IP statless for ns2-LgTIuS
     ERROR: failed to test udp ns1-x4iyOW to ns2-LgTIuS with dnat rule step 2, result: ""

    This is partially adapted from test instructions from the below
    ubuntu tracker.

    Link: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2109889
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Tested-by: Shaun Brady <brady.1345@gmail.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: CKI Backport Bot <cki-ci-bot+cki-gitlab-backport-bot@redhat.com>