usb: dwc3: qcom: use modern PM macros
JIRA: https://issues.redhat.com/browse/RHEL-116007

commit 45ebb7baf2356c3d9118c40216ad5b3d0d516b15
Author: Arnd Bergmann <arnd@arndb.de>
Date: Wed, 23 Apr 2025 18:26:09 +0200

  The use of the old SET_SYSTEM_SLEEP_PM_OPS/SET_RUNTIME_PM_OPS macros
  without __maybe_unused annotations causes warnings when build testing
  without CONFIG_PM:

  drivers/usb/dwc3/dwc3-qcom.c:421:12: error: unused function 'dwc3_qcom_suspend' [-Werror,-Wunused-function]
    421 | static int dwc3_qcom_suspend(struct dwc3_qcom *qcom, bool wakeup)
        |            ^~~~~~~~~~~~~~~~~
  drivers/usb/dwc3/dwc3-qcom.c:457:12: error: unused function 'dwc3_qcom_resume' [-Werror,-Wunused-function]
    457 | static int dwc3_qcom_resume(struct dwc3_qcom *qcom, bool wakeup)

  Change these to the modern SYSTEM_SLEEP_PM_OPS/RUNTIME_PM_OPS/pm_ptr
  macros, which avoids the warnings and improves readability at the same
  time.

  Fixes: 1881a32fe14d ("usb: dwc3: qcom: Transition to flattened model")
  Signed-off-by: Arnd Bergmann <arnd@arndb.de>
  Reviewed-by: Abel Vesa <abel.vesa@linaro.org>
  Acked-by: Thinh Nguyen <Thinh.Nguyen@synopsys.com>
  Link: https://lore.kernel.org/r/20250423162613.2082417-1-arnd@kernel.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>