locking/seqlocks: Fix kernel-doc warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
commit ed3e453798d4f81c99056aa09fcd79d0874a60fd

Right now, seqlock.h produces kernel-doc warnings:

	./include/linux/seqlock.h:181: error: Cannot parse typedef!

Convert it to a plain comment to avoid confusing kernel-doc.

Fixes: a8772dccb2ec ("seqlock: Fold seqcount_LOCKNAME_t definition")
	Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lore.kernel.org/r/a59144cdaadf7fdf1fe5d55d0e1575abbf1c0cb3.1602590106.git.mchehab+huawei@kernel.org
(cherry picked from commit ed3e453798d4f81c99056aa09fcd79d0874a60fd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>