wifi: brcmsmac: remove unused has_5g variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-512.el8
commit-author Tom Rix <trix@redhat.com>
commit 5aeb763a27c2b444928639d35cbe94520c405969

clang with W=1 reports
drivers/net/wireless/broadcom/brcm80211/brcmsmac/mac80211_if.c:1051:6: error:
  variable 'has_5g' set but not used [-Werror,-Wunused-but-set-variable]
        int has_5g = 0;
            ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Simon Horman <simon.horman@corigine.com>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230325130343.1334209-1-trix@redhat.com
(cherry picked from commit 5aeb763a27c2b444928639d35cbe94520c405969)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>