ata: ahci_imx: Fix compilation warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2162218

When compiling with clang and W=1, the following warning is generated:

drivers/ata/ahci_imx.c:1070:18: error: cast to smaller integer type
'enum ahci_imx_type' from 'const void *'
[-Werror,-Wvoid-pointer-to-enum-cast]
        imxpriv->type = (enum ahci_imx_type)of_id->data;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by using a cast to unsigned long to match the "void *" type
size of of_id->data.

Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Acked-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit 26d9f48d9981205a7e229e21e183dbf1f13de83e)
Signed-off-by: Tomas Henzl <thenzl@redhat.com>