tools: ynl: don't access uninitialized attr_space variable
JIRA: https://issues.redhat.com/browse/RHEL-57755

Upstream commit(s):
commit d0bcc15cbae806cad7d1d90003c82ecb5833b533
Author: Jiri Pirko <jiri@nvidia.com>
Date:   Thu Feb 15 13:27:26 2024 +0100

    tools: ynl: don't access uninitialized attr_space variable

    If message contains unknown attribute and user passes
    "--process-unknown" command line option, _decode() gets called with space
    arg set to None. In that case, attr_space variable is not initialized
    used which leads to following trace:

    Traceback (most recent call last):
      File "./tools/net/ynl/cli.py", line 77, in <module>
        main()
      File "./tools/net/ynl/cli.py", line 68, in main
        reply = ynl.dump(args.dump, attrs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tools/net/ynl/lib/ynl.py", line 909, in dump
        return self._op(method, vals, [], dump=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tools/net/ynl/lib/ynl.py", line 894, in _op
        rsp_msg = self._decode(decoded.raw_attrs, op.attr_set.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tools/net/ynl/lib/ynl.py", line 639, in _decode
        self._rsp_add(rsp, attr_name, None, self._decode_unknown(attr))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tools/net/ynl/lib/ynl.py", line 569, in _decode_unknown
        return self._decode(NlAttrs(attr.raw), None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tools/net/ynl/lib/ynl.py", line 630, in _decode
        search_attrs = SpaceAttrs(attr_space, rsp, outer_attrs)
                                  ^^^^^^^^^^
    UnboundLocalError: cannot access local variable 'attr_space' where it is not associated with a value

    Fix this by moving search_attrs assignment under the if statement
    above it to make sure attr_space is initialized.

    Fixes: bf8b832374fb ("tools/net/ynl: Support sub-messages in nested attribute spaces")
    Signed-off-by: Jiri Pirko <jiri@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>