ALSA: pcm: Adjust nine function calls together with a variable assignment
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Markus Elfring <elfring@users.sourceforge.net>
commit c8da9be4a75f1f63024a16b976c5be47405c13dc

The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code places.

	Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit c8da9be4a75f1f63024a16b976c5be47405c13dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>