net: tcp: remove call to obsolete crypto_ahash_alignmask()
JIRA: https://redhat.atlassian.net/browse/RHEL-142637
Upstream Status: net.git commit f2fbb908112311423b09cd0d2b4978f174b99585

commit f2fbb908112311423b09cd0d2b4978f174b99585
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Mon Oct 30 16:09:53 2023 +1100

    net: tcp: remove call to obsolete crypto_ahash_alignmask()

    linux-next hit the following build error:

    net/ipv4/tcp_ao.c: In function 'tcp_ao_key_alloc':
    net/ipv4/tcp_ao.c:1536:13: error: implicit declaration of function 'crypto_ahash_alignmask'; did you mean 'crypto_ahash_alg_name'? [-Werror=implicit-function-declaration]
     1536 |         if (crypto_ahash_alignmask(tfm) > TCP_AO_KEY_ALIGN) {
          |             ^~~~~~~~~~~~~~~~~~~~~~
          |             crypto_ahash_alg_name

    Caused by commit from the crypto tree

      0f8660c82b79 ("crypto: ahash - remove crypto_ahash_alignmask")

    interacting with commit

      4954f17ddefc ("net/tcp: Introduce TCP_AO setsockopt()s")

    from networking. crypto_ahash_alignmask() has been phased out
    by the former commit, drop the call in networking.
    Eric confirms that the check is safe to remove and was questionable
    here in the first place.

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Acked-by: Herbert Xu <herbert@gondor.apana.org.au>
    Reviewed-by: Dmitry Safonov <dima@arista.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>