selinux: declare name parameter of hash_eval const
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2083580

commit d3b1161f29cf479b86d4c3c6f200a8eb27254877
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Tue Jan 25 15:14:13 2022 +0100

    selinux: declare name parameter of hash_eval const

    String literals are passed as second argument to hash_eval(). Also the
    parameter is already declared const in the DEBUG_HASHES configuration.

    Reported by clang [-Wwrite-strings]:

        security/selinux/ss/policydb.c:1881:26: error: passing
          'const char [8]' to parameter of type 'char *' discards
          qualifiers
                hash_eval(&p->range_tr, rangetr);
                                        ^~~~~~~~~
        security/selinux/ss/policydb.c:707:55: note: passing argument to
          parameter 'hash_name' here
        static inline void hash_eval(struct hashtab *h, char *hash_name)
                                                              ^
        security/selinux/ss/policydb.c:2099:32: error: passing
          'const char [11]' to parameter of type 'char *' discards
          qualifiers
                hash_eval(&p->filename_trans, filenametr);
                                              ^~~~~~~~~~~~
        security/selinux/ss/policydb.c:707:55: note: passing argument to
          parameter 'hash_name' here
        static inline void hash_eval(struct hashtab *h, char *hash_name)
                                                              ^

    Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
    [PM: line wrapping in description]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>