mt76: Fix undefined behavior due to shift overflowing the constant
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Borislav Petkov <bp@suse.de>
commit dbc2b1764734857d68425468ffa8486e97ab89df

Fix:

  drivers/net/wireless/mediatek/mt76/mt76x2/pci.c: In function ‘mt76x2e_probe’:
  ././include/linux/compiler_types.h:352:38: error: call to ‘__compiletime_assert_946’ \
	declared with attribute error: FIELD_PREP: mask is not constant
    _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)

See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
details as to why it triggers with older gccs only.

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Felix Fietkau <nbd@nbd.name>
	Cc: Lorenzo Bianconi <lorenzo.bianconi83@gmail.com>
	Cc: Ryder Lee <ryder.lee@mediatek.com>
	Cc: Shayne Chen <shayne.chen@mediatek.com>
	Cc: Sean Wang <sean.wang@mediatek.com>
	Cc: Kalle Valo <kvalo@kernel.org>
	Cc: "David S. Miller" <davem@davemloft.net>
	Cc: Jakub Kicinski <kuba@kernel.org>
	Cc: linux-wireless@vger.kernel.org
	Cc: netdev@vger.kernel.org
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20220405151517.29753-9-bp@alien8.de
(cherry picked from commit dbc2b1764734857d68425468ffa8486e97ab89df)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>