scsi: qla2xxx: Fix smatch warning in qla25xx_delete_{rsp|req}_que
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [scsi] qla2xxx: Fix smatch warning in qla25xx_delete_ rsp|req _que (Himanshu Madhani) [1547714]
Rebuild_FUZZ: 91.94%
commit-author Himanshu Madhani <himanshu.madhani@cavium.com>
commit 62aa281470fdb7c0796d63a1cc918a8c1f02dde2

This patch fixes following warnings reported by smatch:

drivers/scsi/qla2xxx/qla_mid.c:586 qla25xx_delete_req_que()
error: we previously assumed 'req' could be null (see line 580)

drivers/scsi/qla2xxx/qla_mid.c:602 qla25xx_delete_rsp_que()
error: we previously assumed 'rsp' could be null (see line 596)

Fixes: 7867b98dceb7 ("scsi: qla2xxx: Fix memory leak in dual/target mode")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Himanshu Madhani <himanshu.madhani@cavium.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 62aa281470fdb7c0796d63a1cc918a8c1f02dde2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>