RDMA/qedr: fix build error without ipv6
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit bd491d2ad3c071fb77f487a471aa66f205e2e7f2

When CONFIG_IPV6 disabled, we run into a link error:

drivers/infiniband/hw/qedr/qedr_iw_cm.o: In function `qedr_addr6_resolve.isra.3':
qedr_iw_cm.c:(.text+0x4e0): undefined reference to `ip6_route_output_flags'

The ipv6 handling code is obviously not needed here, so this
adds a compile-time check for the Kconfig symbol in all three
places in the code that decide between ipv4 and ipv6.

We don't have to worry about a link error wtih QEDR=y/IPV6=m, as
that configuration is already prohibited by CONFIG_INFINIBAND
depending on "m || IPV6 != m".

Fixes: e411e0587e0d ("RDMA/qedr: Add iWARP connection management functions")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Michal Kalderon <michal.kalderon@cavium.com>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit bd491d2ad3c071fb77f487a471aa66f205e2e7f2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>