ASoC: nau8825: fix bounds check for adc_delay
Bugzilla: https://bugzilla.redhat.com/2179848

commit 5f3d94eb7ae877430d9fe6a9aae7dcef6c3e5fea
Author: Tom Rix <trix@redhat.com>
Date: Tue Apr 18 08:09:55 2023 -0400

    ASoC: nau8825: fix bounds check for adc_delay

    clang build reports
    sound/soc/codecs/nau8825.c:2826:31: error: overlapping comparisons
      always evaluate to false [-Werror,-Wtautological-overlap-compare]
            if (nau8825->adc_delay < 125 && nau8825->adc_delay > 500)
                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

    This is a bug, a logical-or should have been used.

    Fixes: fc0b096c9291 ("ASoC: nau8825: Add delay control for input path")
    Signed-off-by: Tom Rix <trix@redhat.com>
    Acked-by: David Lin <CTLIN0@nuvoton.com>
    Link: https://lore.kernel.org/r/20230418120955.3230705-1-trix@redhat.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>