tools: ynl: print some information about attribute we can't parse
JIRA: https://issues.redhat.com/browse/RHEL-123090
Upstream Status: net.git commit 7aae6505351e

Conflicts: we have backported ab88c2b3739a ("tools: ynl: move python code
to separate sub-directory").

commit 7aae6505351e4c9fc2f3108d16fd06ce76f4b475
Author: Jakub Kicinski <kuba@kernel.org>
Date:   Mon Jan 6 18:28:19 2025 -0800

    tools: ynl: print some information about attribute we can't parse

    When parsing throws an exception one often has to figure out which
    attribute couldn't be parsed from first principles. For families
    with large message parsing trees like rtnetlink guessing the
    attribute can be hard.

    Print a bit of information as the exception travels out, e.g.:

      # when dumping rt links
      Error decoding 'flags' from 'linkinfo-ip6tnl-attrs'
      Error decoding 'data' from 'linkinfo-attrs'
      Error decoding 'linkinfo' from 'link-attrs'
      Traceback (most recent call last):
        File "/home/kicinski/linux/./tools/net/ynl/cli.py", line 119, in <module>
          main()
        File "/home/kicinski/linux/./tools/net/ynl/cli.py", line 100, in main
          reply = ynl.dump(args.dump, attrs)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 1064, in dump
          return self._op(method, vals, dump=True)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 1058, in _op
          return self._ops(ops)[0]
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 1045, in _ops
          rsp_msg = self._decode(decoded.raw_attrs, op.attr_set.name)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 738, in _decode
          subdict = self._decode(NlAttrs(attr.raw), attr_spec['nested-attributes'], search_attrs)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 763, in _decode
          decoded = self._decode_sub_msg(attr, attr_spec, search_attrs)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 714, in _decode_sub_msg
          subdict = self._decode(NlAttrs(attr.raw, offset), msg_format.attr_set)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 749, in _decode
          decoded = attr.as_scalar(attr_spec['type'], attr_spec.byte_order)
        File "/home/kicinski/linux/tools/net/ynl/lib/ynl.py", line 147, in as_scalar
          return format.unpack(self.raw)[0]
      struct.error: unpack requires a buffer of 2 bytes

    The Traceback is what we would previously see, the "Error..."
    messages are new. We print a message per level (in the stack
    order). Printing single combined message gets tricky quickly
    given sub-messages etc.

    Reviewed-by: Donald Hunter <donald.hunter@gmail.com>
    Acked-by: Stanislav Fomichev <sdf@fomichev.me>
    Link: https://patch.msgid.link/20250107022820.2087101-3-kuba@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>