mt76: mt76x02: fix some checkpatch warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Ryder Lee <ryder.lee@mediatek.com>
commit ff97c52a3a0a552e5c77653a147c377d4b676426

This fixes the following checkpatch warnings:

ERROR: code indent should use tabs where possible
CHECK: Alignment should match open parenthesis
CHECK: No space is necessary after a cast
CHECK: Please don't use multiple blank lines
CHECK: Avoid precedence issues in macro
WARNING: Statements should start on a tabstop
WARNING: Unnecessary space before function pointer arguments

	Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
	Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit ff97c52a3a0a552e5c77653a147c377d4b676426)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>