audit: add space before parenthesis and around '=', "==", and '<'
JIRA: https://issues.redhat.com/browse/RHEL-9127

This patch is a backport of the following upstream commit:
commit 62acadda115a94bffd1f6b36acbb67e3f04811be
Author: Atul Kumar Pant <atulpant.linux@gmail.com>
Date:   Wed Aug 16 02:15:53 2023 +0530

    audit: add space before parenthesis and around '=', "==", and '<'

    Fixes following checkpatch.pl issue:
    ERROR: space required before the open parenthesis '('
    ERROR: spaces required around that '='
    ERROR: spaces required around that '<'
    ERROR: spaces required around that '=='

    Signed-off-by: Atul Kumar Pant <atulpant.linux@gmail.com>
    [PM: subject line tweaks]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ricardo Robaina <rrobaina@redhat.com>