gpiolib: include gpio/consumer.h in of_gpio.h for desc_to_gpio()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Stephen Rothwell <sfr@canb.auug.org.au>
commit 335d7a7d63aa3a6da4d4903ef6e64de4a88f27da

Fixes this build error on sparc:

In file included from drivers/spi/spi.c:33:0:
include/linux/of_gpio.h: In function 'of_get_named_gpio_flags':
include/linux/of_gpio.h:93:3: error: implicit declaration of function 'desc_to_gpio' [-Werror=implicit-function-declaration]

	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit 335d7a7d63aa3a6da4d4903ef6e64de4a88f27da)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>