perf clang: Fix header include for LLVM >= 14
Bugzilla: https://bugzilla.redhat.com/2123231

upstream
========
commit d22588d73b18fd12fd971e2dab7fa5ddf978e496
Author: Guilherme Amadio <amadio@gentoo.org>
Date: Sat Apr 16 09:45:55 2022 +0200

description
===========
The header TargetRegistry.h has moved in LLVM/clang 14.

Committer notes:

The problem as noticed when building in ubuntu:22.04:

    90    98.61 ubuntu:22.04                  : FAIL gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
      util/c++/clang.cpp:23:10: fatal error: llvm/Support/TargetRegistry.h: No such file or directory
         23 | #include "llvm/Support/TargetRegistry.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.

Fixed after applying this patch.

Link: https://twitter.com/GuilhermeAmadio/status/1514970524232921088

Signed-off-by: Michael Petlan <mpetlan@redhat.com>