ASoC: fix SND_SOC_WCD939X dependencies
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit b4956275bf88a5708200713707c6c293648d39a9
Author: Arnd Bergmann <arnd@arndb.de>
Date: Sun Feb 4 22:22:02 2024 +0100

    ASoC: fix SND_SOC_WCD939X dependencies

    SND_SOC_WCD939X has an optional dependency on TYPEC, so the newly added
    SND_SOC_WCD939X_SDW option that selects it needs the same dependency, otherwise
    it can fail randconfig builds like:

    WARNING: unmet direct dependencies detected for SND_SOC_WCD939X
      Depends on [m]: SOUND [=y] && SND [=y] && SND_SOC [=y] && SND_SOC_WCD939X_SDW [=y] && (SOUNDWIRE [=y] || !SOUNDWIRE [=y]) && (TYPEC [=m]
     || !TYPEC [=m])
      Selected by [y]:
      - SND_SOC_WCD939X_SDW [=y] && SOUND [=y] && SND [=y] && SND_SOC [=y] && SOUNDWIRE [=y]
    arm-linux-gnueabi-ld: sound/soc/codecs/wcd939x.o: in function `wcd939x_soc_codec_remove':
    wcd939x.c:(.text+0x1950): undefined reference to `wcd_clsh_ctrl_free'
    arm-linux-gnueabi-ld: sound/soc/codecs/wcd939x.o: in function `wcd939x_codec_ear_dac_event':
    wcd939x.c:(.text+0x35d8): undefined reference to `wcd_clsh_ctrl_set_state'
    arm-linux-gnueabi-ld: sound/soc/codecs/wcd939x.o: in function `wcd939x_codec_enable_hphr_pa':
    wcd939x.c:(.text+0x39b0): undefined reference to `wcd_clsh_ctrl_set_state'
    arm-linux-gnueabi-ld: wcd939x.c:(.text+0x39dc): undefined reference to `wcd_clsh_set_hph_mode'
    arm-linux-gnueabi-ld: wcd939x.c:(.text+0x3bc0): undefined reference to `wcd_clsh_ctrl_set_state'

    Fixes: be2af391cea0 ("ASoC: codecs: Add WCD939x Soundwire devices driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Neil Armstrong <neil.armstrong@linaro.org>
    Link: https://lore.kernel.org/r/20240204212207.3158914-2-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>