libbpf: Fix build by renaming variables
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Prashant Bhole <prashantbhole.linux@gmail.com>
commit a79ac2d1036a824abba982c33e938b717d1b659f
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-240.el8/a79ac2d1.failed

In btf__align_of() variable name 't' is shadowed by inner block
declaration of another variable with same name. Patch renames
variables in order to fix it.

  CC       sharedobjs/btf.o
btf.c: In function ‘btf__align_of’:
btf.c:303:21: error: declaration of ‘t’ shadows a previous local [-Werror=shadow]
  303 |   int i, align = 1, t;
      |                     ^
btf.c:283:25: note: shadowed declaration is here
  283 |  const struct btf_type *t = btf__type_by_id(btf, id);
      |

Fixes: 3d208f4ca111 ("libbpf: Expose btf__align_of() API")
	Signed-off-by: Prashant Bhole <prashantbhole.linux@gmail.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Tested-by: Toke Høiland-Jørgensen <toke@redhat.com>
Link: https://lore.kernel.org/bpf/20191216082738.28421-1-prashantbhole.linux@gmail.com
(cherry picked from commit a79ac2d1036a824abba982c33e938b717d1b659f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/lib/bpf/btf.c