af_unix: Pass struct sock to unix_autobind().
Bugzilla: https://bugzilla.redhat.com/2120966

commit f7ed31f4615f4e1d97c0e4325c5b8a240e10073c
Author: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Date:   Wed Nov 24 11:14:20 2021 +0900

    af_unix: Pass struct sock to unix_autobind().

    We do not use struct socket in unix_autobind() and pass struct sock to
    unix_bind_bsd() and unix_bind_abstract().  Let's pass it to unix_autobind()
    as well.

    Also, this patch fixes these errors by checkpatch.pl.

      ERROR: do not use assignment in if condition
      #1795: FILE: net/unix/af_unix.c:1795:
      +     if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr

      CHECK: Logical continuations should be on the previous line
      #1796: FILE: net/unix/af_unix.c:1796:
      +     if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr
      +         && (err = unix_autobind(sock)) != 0)

    Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>