ASoC: fsl: Fix SND_SOC_EUKREA_TLV320 build error on i.MX8M
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: fsl: Fix SND_SOC_EUKREA_TLV320 build error on i.MX8M (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 95.08%
commit-author Fabio Estevam <festevam@gmail.com>
commit add6883619a9e3bf9658eaff1a547354131bbcd9

eukrea-tlv320.c machine driver runs on non-DT platforms
and include <asm/mach-types.h> header file in order to be able
to use some machine_is_eukrea_xxx() macros.

Building it for ARM64 causes the following build error:

sound/soc/fsl/eukrea-tlv320.c:28:10: fatal error: asm/mach-types.h: No such file or directory

Avoid this error by not allowing to build the SND_SOC_EUKREA_TLV320
driver when ARM64 is selected.

This is needed in preparation for the i.MX8M support.

	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Fabio Estevam <festevam@gmail.com>
	Acked-by: Shawn Guo <shawnguo@kernel.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit add6883619a9e3bf9658eaff1a547354131bbcd9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>