ataflop: Add missing semicolon to return statement
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2018403

commit 38987a872b313e72f7a64e91ec0b8084eaec0f10
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Sat Nov 6 19:55:49 2021 +0100

    ataflop: Add missing semicolon to return statement

        drivers/block/ataflop.c: In function ‘ataflop_probe’:
        drivers/block/ataflop.c:2023:2: error: expected expression before ‘if’
         2023 |  if (ataflop_alloc_disk(drive, type))
              |  ^~
        drivers/block/ataflop.c:2023:2: error: ‘return’ with a value, in function returning void [-Werror=return-type]
        drivers/block/ataflop.c:2011:13: note: declared here
         2011 | static void ataflop_probe(dev_t dev)
              |             ^~~~~~~~~~~~~

    Fixes: 46a7db492e7a2740 ("ataflop: address add_disk() error handling on probe")
    Reported-by: noreply@ellerman.id.au
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Link: https://lore.kernel.org/r/20211106185549.1578444-1-geert@linux-m68k.org
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>