net: stmmac: generic: drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-6297

commit e6512465838bf634d147399c8c96612d3cb419b9
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Fri Mar 10 22:46:29 2023 +0100

    net: stmmac: generic: drop of_match_ptr for ID table

    The driver can match only via the DT table so the table should be always
    used and the of_match_ptr does not have any sense (this also allows ACPI
    matching via PRP0001, even though it is not relevant here).

      drivers/net/ethernet/stmicro/stmmac/dwmac-generic.c:72:34: error: ‘dwmac_generic_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>