usb: mtu3: fix up undefined reference to usb_debug_root
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Chunfeng Yun <chunfeng.yun@mediatek.com>
commit 9610450ea31eb061b9914de2bf6ced424956182d

When CONFIG_USB is not set, and CONFIG_USB_GADGET is set,
there is an issue:

ld:
drivers/usb/mtu3/mtu3_debugfs.o: in function 'ssusb_debugfs_create_root':
mtu3_debugfs.c:(.text+0xba3): undefined reference to 'usb_debug_root'

usb_debug_root is only built when CONFIG_USB is enabled, so here drop it
and use NULL instead.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Chunfeng Yun <chunfeng.yun@mediatek.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 9610450ea31eb061b9914de2bf6ced424956182d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>