hid: intel-ish-hid: Fix uninitialized variable 'rv' in ish_fw_xfer_direct_dma
JIRA: https://issues.redhat.com/browse/RHEL-65221
Upstream status: v6.12-rc7

commit d41bff05a61fb539f21e9bf0d39fac77f457434e
Author: SurajSonawane2415 <surajsonawane0215@gmail.com>
Date:   Fri Oct 4 13:29:44 2024 +0530

    hid: intel-ish-hid: Fix uninitialized variable 'rv' in ish_fw_xfer_direct_dma

    Fix the uninitialized symbol 'rv' in the function ish_fw_xfer_direct_dma
    to resolve the following warning from the smatch tool:
    drivers/hid/intel-ish-hid/ishtp-fw-loader.c:714 ish_fw_xfer_direct_dma()
    error: uninitialized symbol 'rv'.
    Initialize 'rv' to 0 to prevent undefined behavior from uninitialized
    access.

    Cc: stable@vger.kernel.org
    Fixes: 91b228107da3 ("HID: intel-ish-hid: ISH firmware loader client driver")
    Signed-off-by: SurajSonawane2415 <surajsonawane0215@gmail.com>
    Link: https://patch.msgid.link/20241004075944.44932-1-surajsonawane0215@gmail.com
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>