perf trace: Avoid compile error wrt redefining bool
JIRA: https://issues.redhat.com/browse/RHEL-15009

upstream
========
commit 33b725ce7b9887569749fbbcdafc4ab089a09741
Author: Ian Rogers <irogers@google.com>
Date: Wed Sep 13 11:49:57 2023 -0700

description
===========
Make part of an existing TODO conditional to avoid the following build
error:
```
tools/perf/util/bpf_skel/augmented_raw_syscalls.bpf.c:26:14: error: cannot combine with previous 'char' declaration specifier
   26 | typedef char bool;
      |              ^
include/stdbool.h:20:14: note: expanded from macro 'bool'
   20 | #define bool _Bool
      |              ^
tools/perf/util/bpf_skel/augmented_raw_syscalls.bpf.c:26:1: error: typedef requires a name [-Werror,-Wmissing-declarations]
   26 | typedef char bool;
      | ^~~~~~~~~~~~~~~~~
2 errors generated.
```

    Signed-off-by: Ian Rogers <irogers@google.com>
    Cc: Leo Yan <leo.yan@linaro.org>
    Cc: bpf@vger.kernel.org
    Link: https://lore.kernel.org/r/20230913184957.230076-1-irogers@google.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>