perf arm-spe: Fill address info for samples
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Leo Yan <leo.yan@linaro.org>
commit 54f7815efef7fad935fdf73dfd8b3116568f2f35

To properly handle memory and branch samples, this patch divides into
two functions for generating samples: arm_spe__synth_mem_sample() is for
synthesizing memory and TLB samples; arm_spe__synth_branch_sample() is
to synthesize branch samples.

Arm SPE backend decoder has passed virtual and physical address through
packets, the address info is stored into the synthesize samples in the
function arm_spe__synth_mem_sample().

Committer notes:

Fixed this:

  36    46.77 fedora:27                     : FAIL clang version 5.0.2 (tags/RELEASE_502/final)

    util/arm-spe.c:269:34: error: missing field 'pid' initializer [-Werror,-Wmissing-field-initializers]
            struct perf_sample sample = { 0 };
                                            ^
    util/arm-spe.c:288:34: error: missing field 'pid' initializer [-Werror,-Wmissing-field-initializers]
            struct perf_sample sample = { 0 };

By using = { .ip = 0, };

	Signed-off-by: Leo Yan <leo.yan@linaro.org>
	Reviewed-by: James Clark <james.clark@arm.com>
	Tested-by: James Clark <james.clark@arm.com>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Al Grant <al.grant@arm.com>
	Cc: Andre Przywara <andre.przywara@arm.com>
	Cc: Ingo Molnar <mingo@redhat.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: John Garry <john.garry@huawei.com>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Mathieu Poirier <mathieu.poirier@linaro.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Wei Li <liwei391@huawei.com>
	Cc: Will Deacon <will@kernel.org>
	Signed-off-by: James Clark <james.clark@arm.com>
Link: https://lore.kernel.org/r/20210211133856.2137-4-james.clark@arm.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 54f7815efef7fad935fdf73dfd8b3116568f2f35)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>