usb: typec: tcpci_mt6360: remove unused mt6360_tcpc_read16 function
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-526.el8
commit-author Tom Rix <trix@redhat.com>
commit 2271b2727aeca2e09d07f63bc61dc9757c3a5a3c

clang with W=1 reports
drivers/usb/typec/tcpm/tcpci_mt6360.c:46:19: error: unused function
  'mt6360_tcpc_read16' [-Werror,-Wunused-function]
static inline int mt6360_tcpc_read16(struct regmap *regmap,
                  ^
This function is not used, so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
	Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Link: https://lore.kernel.org/r/20230319141053.1703937-1-trix@redhat.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 2271b2727aeca2e09d07f63bc61dc9757c3a5a3c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>