ASoC: Intel: fix unused-variable warning in probe_codec
Bugzilla: https://bugzilla.redhat.com/2179848

commit 515626a33a194c4caaf2879dbf9e00e882582af0
Author: Gaosheng Cui <cuigaosheng1@huawei.com>
Date: Mon Aug 22 11:51:33 2022 +0800

    ASoC: Intel: fix unused-variable warning in probe_codec

    In configurations with CONFIG_SND_SOC_INTEL_SKYLAKE_HDAUDIO_CODEC=n,
    gcc warns about an unused variable:

    sound/soc/intel/skylake/skl.c: In function ‘probe_codec’:
    sound/soc/intel/skylake/skl.c:729:18: error: unused variable ‘skl’ [-Werror=unused-variable]
      struct skl_dev *skl = bus_to_skl(bus);
                      ^~~
    cc1: all warnings being treated as errors

    Fixes: 3fd63658caed9 ("ASoC: Intel: Drop hdac_ext usage for codec device creation")
    Signed-off-by: Gaosheng Cui <cuigaosheng1@huawei.com>
    Acked-by: Cezary Rojewski <cezary.rojewski@intel.com>
    Link: https://lore.kernel.org/r/20220822035133.2147381-1-cuigaosheng1@huawei.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>