bpf: Print error message for bpftool cgroup show
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
commit-author Hechao Li <hechaol@fb.com>
commit 1162f844030ac1ac7321b5e8f6c9badc7a11428f

Currently, when bpftool cgroup show <path> has an error, no error
message is printed. This is confusing because the user may think the
result is empty.

Before the change:

$ bpftool cgroup show /sys/fs/cgroup
ID       AttachType      AttachFlags     Name
$ echo $?
255

After the change:
$ ./bpftool cgroup show /sys/fs/cgroup
Error: can't query bpf programs attached to /sys/fs/cgroup: Operation
not permitted

v2: Rename check_query_cgroup_progs to cgroup_has_attached_progs

	Signed-off-by: Hechao Li <hechaol@fb.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Link: https://lore.kernel.org/bpf/20191224011742.3714301-1-hechaol@fb.com
(cherry picked from commit 1162f844030ac1ac7321b5e8f6c9badc7a11428f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>