net: aquantia: fix undefined devm_hwmon_device_register_with_info reference
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Kefeng Wang <wangkefeng.wang@huawei.com>
commit 70610c922bae2f3f974eef955ef254defb7755ce

drivers/net/ethernet/aquantia/atlantic/aq_drvinfo.o: In function `aq_drvinfo_init':
aq_drvinfo.c:(.text+0xe8): undefined reference to `devm_hwmon_device_register_with_info'

Fix it by using #if IS_REACHABLE(CONFIG_HWMON).

	Reported-by: Hulk Robot <hulkci@huawei.com>
	Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 70610c922bae2f3f974eef955ef254defb7755ce)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>