Bluetooth: btmtkuart: fix error handling in mtk_hci_wmt_sync()
Bugzilla: http://bugzilla.redhat.com/2124521

commit a76d269a4e86cfd7d4441e40adccfa67808fe6fa
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Thu Mar 17 10:57:40 2022 +0300

    Bluetooth: btmtkuart: fix error handling in mtk_hci_wmt_sync()

    This code has an uninitialized variable warning:

        drivers/bluetooth/btmtkuart.c:184 mtk_hci_wmt_sync()
        error: uninitialized symbol 'wc'.

    But it also has error paths which have memory leaks.

    Fixes: 8f550f55b155 ("Bluetooth: btmtkuart: rely on BT_MTK module")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>