dma-buf: Fix __dma_buf_debugfs_list_del argument for !CONFIG_DEBUG_FS
JIRA: https://issues.redhat.com/browse/RHEL-53571
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.12.7)

commit c8395bfcd0e3b3d7c8576dca33ec8f64bf9c3c17
Author:     T.J. Mercier <tjmercier@google.com>
AuthorDate: Sun Nov 17 17:03:25 2024 +0000
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Fri Dec 27 14:02:10 2024 +0100

    [ Upstream commit 0cff90dec63da908fb16d9ea2872ebbcd2d18e6a ]

    The arguments for __dma_buf_debugfs_list_del do not match for both the
    CONFIG_DEBUG_FS case and the !CONFIG_DEBUG_FS case. The !CONFIG_DEBUG_FS
    case should take a struct dma_buf *, but it's currently struct file *.
    This can lead to the build error:

    error: passing argument 1 of ‘__dma_buf_debugfs_list_del’ from
    incompatible pointer type [-Werror=incompatible-pointer-types]

    dma-buf.c:63:53: note: expected ‘struct file *’ but argument is of
    type ‘struct dma_buf *’
       63 | static void __dma_buf_debugfs_list_del(struct file *file)

    Fixes: bfc7bc539392 ("dma-buf: Do not build debugfs related code when !CONFIG_DEBUG_FS")
    Signed-off-by: T.J. Mercier <tjmercier@google.com>
    Reviewed-by: Tvrtko Ursulin <tvrtko.ursulin@igalia.com>
    Signed-off-by: Sumit Semwal <sumit.semwal@linaro.org>
    Link: https://patchwork.freedesktop.org/patch/msgid/20241117170326.1971113-1-tjmercier@google.com
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>