ALSA: pcm: avoid nused-but-set-variable warning
Bugzilla: https://bugzilla.redhat.com/2179848

commit 3827597a89f85de0e136c67bf38677f2b2fda566
Author: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Date: Wed Nov 16 00:12:39 2022 +0000

    ALSA: pcm: avoid nused-but-set-variable warning

    It will indicate below warning if W=1 was added and CONFIG_SND_DEBUG
    was not set. This patch adds __maybe_unused and avoid it.

    	${LINUX}/sound/core/pcm_native.c: In function 'constrain_mask_params':
    	${LINUX}/sound/core/pcm_native.c:291:25: error: variable 'old_mask' set but not used [-Werror=unused-but-set-variable]
    	  291 |         struct snd_mask old_mask;
    	      |                         ^~~~~~~~
    	${LINUX}/sound/core/pcm_native.c: In function 'constrain_interval_params':
    	${LINUX}/sound/core/pcm_native.c:327:29: error: variable 'old_interval' set but not used [-Werror=unused-but-set-variable]
    	  327 |         struct snd_interval old_interval;
    	      |                             ^~~~~~~~~~~~
    	${LINUX}/sound/core/pcm_native.c: In function 'constrain_params_by_rules':
    	${LINUX}/sound/core/pcm_native.c:368:29: error: variable 'old_interval' set but not used [-Werror=unused-but-set-variable]
    	  368 |         struct snd_interval old_interval;
    	      |                             ^~~~~~~~~~~~
    	${LINUX}/sound/core/pcm_native.c:367:25: error: variable 'old_mask' set but not used [-Werror=unused-but-set-variable]
    	  367 |         struct snd_mask old_mask;
    	      |                         ^~~~~~~~
    	${LINUX}/sound/core/pcm_native.c: In function 'snd_pcm_hw_params_choose':
    	${LINUX}/sound/core/pcm_native.c:652:29: error: variable 'old_interval' set but not used [-Werror=unused-but-set-variable]
    	  652 |         struct snd_interval old_interval;
    	      |                             ^~~~~~~~~~~~
    	${LINUX}/sound/core/pcm_native.c:651:25: error: variable 'old_mask' set but not used [-Werror=unused-but-set-variable]
    	  651 |         struct snd_mask old_mask;
    	      |                         ^~~~~~~~
    	cc1: all warnings being treated as errors
    	make[3]: *** [${LINUX}/scripts/Makefile.build:250: sound/core/pcm_native.o] error 1

    Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
    Reviewed-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
    Tested-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
    Link: https://lore.kernel.org/r/874juzg3kd.wl-kuninori.morimoto.gx@renesas.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>