libbpf: Prevent compiler warnings/errors
JIRA: https://issues.redhat.com/browse/RHEL-77939

commit 7f4ec77f3fee41dd6a41f03a40703889e6e8f7b2
Author: Eder Zulian <ezulian@redhat.com>
Date:   Tue Oct 22 19:23:28 2024 +0200

    libbpf: Prevent compiler warnings/errors

    Initialize 'new_off' and 'pad_bits' to 0 and 'pad_type' to  NULL in
    btf_dump_emit_bit_padding to prevent compiler warnings/errors which are
    observed when compiling with 'EXTRA_CFLAGS=-g -Og' options, but do not
    happen when compiling with current default options.

    For example, when compiling libbpf with

      $ make "EXTRA_CFLAGS=-g -Og" -C tools/lib/bpf/ clean all

    Clang version 17.0.6 and GCC 13.3.1 fail to compile btf_dump.c due to
    following errors:

      btf_dump.c: In function ‘btf_dump_emit_bit_padding’:
      btf_dump.c:903:42: error: ‘new_off’ may be used uninitialized [-Werror=maybe-uninitialized]
        903 |         if (new_off > cur_off && new_off <= next_off) {
            |                                  ~~~~~~~~^~~~~~~~~~~
      btf_dump.c:870:13: note: ‘new_off’ was declared here
        870 |         int new_off, pad_bits, bits, i;
            |             ^~~~~~~
      btf_dump.c:917:25: error: ‘pad_type’ may be used uninitialized [-Werror=maybe-uninitialized]
        917 |                         btf_dump_printf(d, "\n%s%s: %d;", pfx(lvl), pad_type,
            |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        918 |                                         in_bitfield ? new_off - cur_off : 0);
            |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      btf_dump.c:871:21: note: ‘pad_type’ was declared here
        871 |         const char *pad_type;
            |                     ^~~~~~~~
      btf_dump.c:930:20: error: ‘pad_bits’ may be used uninitialized [-Werror=maybe-uninitialized]
        930 |                 if (bits == pad_bits) {
            |                    ^
      btf_dump.c:870:22: note: ‘pad_bits’ was declared here
        870 |         int new_off, pad_bits, bits, i;
            |                      ^~~~~~~~
      cc1: all warnings being treated as errors

    Signed-off-by: Eder Zulian <ezulian@redhat.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Jiri Olsa <jolsa@kernel.org>
    Link: https://lore.kernel.org/bpf/20241022172329.3871958-3-ezulian@redhat.com

Signed-off-by: Viktor Malik <vmalik@redhat.com>