RDMA/mlx5: Remove unused num_alloc_xa_entries variable
JIRA: https://issues.redhat.com/browse/RHEL-882
Upstream-status: v6.4-rc1

commit 081c27b3bcdbfad6fa3c16975e02e33073f1267d
Author: Tom Rix <trix@redhat.com>
Date:   Thu Mar 30 11:36:07 2023 -0400

    RDMA/mlx5: Remove unused num_alloc_xa_entries variable

    clang with W=1 reports
    drivers/infiniband/hw/mlx5/devx.c:1996:6: error: variable
      'num_alloc_xa_entries' set but not used [-Werror,-Wunused-but-set-variable]
            int num_alloc_xa_entries = 0;
                ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Link: https://lore.kernel.org/r/20230330153607.1838750-1-trix@redhat.com
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>