idpf: remove redundant 'req_vec_chunks' NULL check
JIRA: https://issues.redhat.com/browse/RHEL-50916

commit 795b1aa8f37e38cf1a6202d274960bdd9c2ac44a
Author: Pavan Kumar Linga <pavan.kumar.linga@intel.com>
Date:   Wed Aug 14 10:59:02 2024 -0700

    idpf: remove redundant 'req_vec_chunks' NULL check

    'req_vec_chunks' is used to store the vector info received
    from the device control plane. The memory for it is allocated
    in idpf_send_alloc_vectors_msg and returns an error if the memory
    allocation fails.

    'req_vec_chunks' cannot be NULL in the later code flow. So remove
    the conditional check to extract the vector ids received from
    the device control plane.

    Smatch static checker warning:

    drivers/net/ethernet/intel/idpf/idpf_lib.c:417 idpf_intr_req()
    error: we previously assumed 'adapter->req_vec_chunks'
    could be null (see line 360)

    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/intel-wired-lan/a355ae8a-9011-4a85-a4d1-5b2793bb5f7b@stanley.mountain/
    Reviewed-by: Dan Carpenter <dan.carpenter@linaro.org>
    Signed-off-by: Pavan Kumar Linga <pavan.kumar.linga@intel.com>
    Tested-by: Krishneil Singh <krishneil.k.singh@intel.com>
    Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
    Link: https://patch.msgid.link/20240814175903.4166390-1-anthony.l.nguyen@intel.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>