maple_tree: reduce stack usage with gcc-9 and earlier
commit 44081c77e8a4aac9c5a010ed0d9ccdcf684041e1
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Feb 14 11:30:24 2023 +0100

    maple_tree: reduce stack usage with gcc-9 and earlier

    gcc-10 changed the way inlining works to be less aggressive, but older
    versions run into an oversized stack frame warning whenever
    CONFIG_KASAN_STACK is enabled, as that forces variables from inlined
    callees to be non-overlapping:

    lib/maple_tree.c: In function 'mas_wr_bnode':
    lib/maple_tree.c:4320:1: error: the frame size of 1424 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Change the annotations on mas_store_b_node() and mas_commit_b_node()
    to explicitly forbid inlining in this configuration, which is
    the same behavior that newer versions already have.

    Link: https://lkml.kernel.org/r/20230214103030.1051950-1-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: David Hildenbrand <david@redhat.com>
    Reviewed-by: Liam R. Howlett <Liam.Howlett@oracle.com>
    Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
    Cc: Alexander Potapenko <glider@google.com>
    Cc: Andrey Konovalov <andreyknvl@gmail.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Cc: Vernon Yang <vernon2gm@gmail.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2166668
Signed-off-by: Nico Pache <npache@redhat.com>