selftests/bpf: Fix conflicts with built-in functions in bpf_iter_ksym
Bugzilla: https://bugzilla.redhat.com/2177177

commit ab0350c743d5c93fd88742f02b3dff12168ab435
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Fri Dec 2 18:08:44 2022 -0700

    selftests/bpf: Fix conflicts with built-in functions in bpf_iter_ksym
    
    Both tolower and toupper are built in c functions, we should not
    redefine them as this can result in a build error.
    
    Fixes the following errors:
    progs/bpf_iter_ksym.c:10:20: error: conflicting types for built-in function 'tolower'; expected 'int(int)' [-Werror=builtin-declaration-mismatch]
       10 | static inline char tolower(char c)
          |                    ^~~~~~~
    progs/bpf_iter_ksym.c:5:1: note: 'tolower' is declared in header '<ctype.h>'
        4 | #include <bpf/bpf_helpers.h>
      +++ |+#include <ctype.h>
        5 |
    progs/bpf_iter_ksym.c:17:20: error: conflicting types for built-in function 'toupper'; expected 'int(int)' [-Werror=builtin-declaration-mismatch]
       17 | static inline char toupper(char c)
          |                    ^~~~~~~
    progs/bpf_iter_ksym.c:17:20: note: 'toupper' is declared in header '<ctype.h>'
    
    See background on this sort of issue:
    https://stackoverflow.com/a/20582607
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=12213
    
    (C99, 7.1.3p1) "All identifiers with external linkage in any of the
    following subclauses (including the future library directions) are
    always reserved for use as identifiers with external linkage."
    
    This is documented behavior in GCC:
    https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-std-2
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Acked-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/r/20221203010847.2191265-1-james.hilliard1@gmail.com
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>