net: psp: select CONFIG_SKB_EXTENSIONS
JIRA: https://redhat.atlassian.net/browse/RHEL-185448

commit 6e980df452169f82674f2e650079c1fe0aee343d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Feb 16 11:54:54 2026 +0100

    net: psp: select CONFIG_SKB_EXTENSIONS

    psp now uses skb extensions, failing to build when that is disabled:

    In file included from include/net/psp.h:7,
                     from net/psp/psp_sock.c:9:
    include/net/psp/functions.h: In function '__psp_skb_coalesce_diff':
    include/net/psp/functions.h:60:13: error: implicit declaration of function 'skb_ext_find'; did you mean 'skb_ext_copy'? [-Wimplicit-function-declaration]
       60 |         a = skb_ext_find(one, SKB_EXT_PSP);
          |             ^~~~~~~~~~~~
          |             skb_ext_copy
    include/net/psp/functions.h:60:31: error: 'SKB_EXT_PSP' undeclared (first use in this function)
       60 |         a = skb_ext_find(one, SKB_EXT_PSP);
          |                               ^~~~~~~~~~~
    include/net/psp/functions.h:60:31: note: each undeclared identifier is reported only once for each function it appears in
    include/net/psp/functions.h: In function '__psp_sk_rx_policy_check':
    include/net/psp/functions.h:94:53: error: 'SKB_EXT_PSP' undeclared (first use in this function)
       94 |         struct psp_skb_ext *pse = skb_ext_find(skb, SKB_EXT_PSP);
          |                                                     ^~~~~~~~~~~
    net/psp/psp_sock.c: In function 'psp_sock_recv_queue_check':
    net/psp/psp_sock.c:164:41: error: 'SKB_EXT_PSP' undeclared (first use in this function)
      164 |                 pse = skb_ext_find(skb, SKB_EXT_PSP);
          |                                         ^~~~~~~~~~~

    Select the Kconfig symbol as we do from its other users.

    Fixes: 6b46ca260e22 ("net: psp: add socket security association code")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Simon Horman <horms@kernel.org>
    Reviewed-by: Daniel Zahka <daniel.zahka@gmail.com>
    Link: https://patch.msgid.link/20260216105500.2382181-1-arnd@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

(cherry picked from commit 6e980df452169f82674f2e650079c1fe0aee343d)
Assisted-by: Patchpal
Signed-off-by: Ivan Vecera <ivecera@redhat.com>