Bluetooth: coredump: fix building with coredump disabled
JIRA: https://issues.redhat.com/browse/RHEL-2530

commit 6910e2eb39254d279bce5bc0f8eb6af45b59357c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 3 13:30:48 2023 +0200

    Bluetooth: coredump: fix building with coredump disabled

    The btmtk driver uses an IS_ENABLED() check to conditionally compile
    the coredump support, but this fails to build because the hdev->dump
    member is in an #ifdef:

    drivers/bluetooth/btmtk.c: In function 'btmtk_process_coredump':
    drivers/bluetooth/btmtk.c:386:30: error: 'struct hci_dev' has no member named 'dump'
      386 |   schedule_delayed_work(&hdev->dump.dump_timeout,
          |                              ^~

    The struct member doesn't really make a huge difference in the total size,
    so just remove the #ifdef around it to avoid adding similar checks
    around each user.

    Fixes: 872f8c253cb9e ("Bluetooth: btusb: mediatek: add MediaTek devcoredump support")
    Fixes: 9695ef876fd12 ("Bluetooth: Add support for hci devcoredump")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Signed-off-by: Bastien Nocera <bnocera@redhat.com>