ASoC: ams-delta: remove duplicate 'const'
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: ams-delta: remove duplicate 'const' (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 93.18%
commit-author Arnd Bergmann <arnd@arndb.de>
commit c9fbc1c02ec881c8bb037f87efb706d22589fdab

clang points out that SOC_ENUM_SINGLE_EXT_DECL() contains a 'const'
modifier already, so adding another one does not make it more const:

sound/soc/ti/ams-delta.c:203:14: error: duplicate 'const' declaration specifier [-Werror,-Wduplicate-decl-specifier]
static const SOC_ENUM_SINGLE_EXT_DECL(ams_delta_audio_enum,
             ^
include/sound/soc.h:351:2: note: expanded from macro 'SOC_ENUM_SINGLE_EXT_DECL'
        const struct soc_enum name = SOC_ENUM_SINGLE_EXT(ARRAY_SIZE(xtexts), xtexts)

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit c9fbc1c02ec881c8bb037f87efb706d22589fdab)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>