um: include linux/stddef.h for __always_inline
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 7ac73fbb54d99486755910eaeccb070735908907
Author: Jason A. Donenfeld <Jason@zx2c4.com>
Date:   Wed Jul 13 12:54:06 2022 +0200

    um: include linux/stddef.h for __always_inline

    When compiling against musl, their shipped <stddef.h> doesn't have
    __always_inline. So instead explicitly include the kernel uapi header,
    <linux/stddef.h>, which does.

    This prevents the following build error:

    In file included from arch/x86/um/shared/sysdep/stub.h:11,
                     from arch/um/kernel/skas/clone.c:14:
    arch/x86/um/shared/sysdep/stub_64.h:111:23: error: expected ‘;’ before ‘void’
      111 | static __always_inline void *get_stub_page(void)
          |                       ^~~~~
          |                       ;
    make[4]: *** [scripts/Makefile.build:249: arch/um/kernel/skas/clone.o] Error 1

    Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
    Signed-off-by: Richard Weinberger <richard@nod.at>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>