virtio-mmio: Add explicit include for of.h
JIRA: https://issues.redhat.com/browse/RHEL-346

commit c5111a5b1a603cbad4bb3b49ae9a77dbc2252a59
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 5 15:27:21 2023 -0500

    virtio-mmio: Add explicit include for of.h

    With linux/acpi.h no longer implicitly including of.h, add an explicit
    include of of.h to fix the following error:

    drivers/virtio/virtio_mmio.c:492:13: error: implicit declaration of function 'of_property_read_bool'; did you mean 'fwnode_property_read_bool'? [-Werror=implicit-function-declaration]

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Laurent Vivier <lvivier@redhat.com>