bcma: remove unused mips_read32 function
JIRA: https://issues.redhat.com/browse/RHEL-2907

commit 21898a40b2f84deb9438c2ef63f7a5072d6ab2af
Author: Tom Rix <trix@redhat.com>
Date:   Fri Mar 24 15:06:47 2023 -0400

    bcma: remove unused mips_read32 function
    
    clang with W=1 reports
    drivers/bcma/driver_mips.c:49:19: error: unused function
      'mips_read32' [-Werror,-Wunused-function]
    static inline u32 mips_read32(struct bcma_drv_mips *mcore,
                      ^
    This function is not used so remove it.
    
    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20230324190647.2654293-1-trix@redhat.com

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>