ASoC: rt5682s: use 'static' qualifier
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
commit 49ba5e936e1512d4c7812d433048f8909234fca0

Sparse reports the following warnings:

sound/soc/codecs/rt5682s.c:44:12: error: symbol 'rt5682s_supply_names'
was not declared. Should it be static?

sound/soc/codecs/rt5682s.c:74:26: error: symbol 'rt5682s_reg' was not
declared. Should it be static?

sound/soc/codecs/rt5682s.c:2841:30: error: symbol
'rt5682s_aif1_dai_ops' was not declared. Should it be static?

	Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20211025185933.144327-3-pierre-louis.bossart@linux.intel.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 49ba5e936e1512d4c7812d433048f8909234fca0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>