iommu/amd: Fix type of type parameter to amd_iommufd_hw_info()
JIRA: https://issues.redhat.com/browse/RHEL-147902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 5b0530bb16ec5af3cc96fc25891d6a860fd37a8c
Author: Nathan Chancellor <nathan@kernel.org>
Date: Thu Jan 22 14:42:38 2026 -0700

    iommu/amd: Fix type of type parameter to amd_iommufd_hw_info()

    When building with -Wincompatible-function-pointer-types-strict, a
    warning designed to catch kernel control flow integrity (kCFI) issues at
    build time, there is an instance around amd_iommufd_hw_info():

      drivers/iommu/amd/iommu.c:3141:13: error: incompatible function pointer types initializing 'void *(*)(struct device *, u32 *, enum iommu_hw_info_type *)' (aka 'void *(*)(struct device *, unsigned int *, enum iommu_hw_info_type *)') with an expression of type 'void *(struct device *, u32 *, u32 *)' (aka 'void *(struct device *, unsigned int *, unsigned int *)') [-Werror,-Wincompatible-function-pointer-types-strict]
       3141 |         .hw_info = amd_iommufd_hw_info,
	    |                    ^~~~~~~~~~~~~~~~~~~

    While 'u32 *' and 'enum iommu_hw_info_type *' are ABI compatible, hence
    no regular warning from -Wincompatible-function-pointer-types, the
    mismatch will trigger a kCFI violation when amd_iommufd_hw_info() is
    called indirectly.

    Update the type parameter of amd_iommufd_hw_info() to be
    'enum iommu_hw_info_type *' to match the prototype in
    'struct iommu_ops', clearing up the warning and kCFI violation.

    Fixes: 7d8b06ecc45b ("iommu/amd: Add support for hw_info for iommu capability query")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Vasant Hegde <vasant.hegde@amd.com>
    Reviewed-by: Nicolin Chen <nicolinc@nvidia.com>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Signed-off-by: Joerg Roedel <joerg.roedel@amd.com>

(cherry picked from commit 5b0530bb16ec5af3cc96fc25891d6a860fd37a8c)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>