x86/asm: Fix SETZ size enqcmds() build failure
Bugzilla: https://bugzilla.redhat.com/2159445

commit d81ff5fe14a950f53e2833cfa196e7bb3fd5d4e3
Author: Kees Cook <keescook@chromium.org>
Date:   Fri Sep 10 15:33:32 2021 -0700

    x86/asm: Fix SETZ size enqcmds() build failure

    When building under GCC 4.9 and 5.5:

      arch/x86/include/asm/special_insns.h: Assembler messages:
      arch/x86/include/asm/special_insns.h:286: Error: operand size mismatch for `setz'

    Change the type to "bool" for condition code arguments, as documented.

    Fixes: 7f5933f81bd8 ("x86/asm: Add an enqcmds() wrapper for the ENQCMDS instruction")
    Co-developed-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20210910223332.3224851-1-keescook@chromium.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>