ALSA: oss: fix compile error when OSS_DEBUG is enabled
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-373.el8
commit-author Bixuan Cui <cuibixuan@linux.alibaba.com>
commit 8e7daf318d97f25e18b2fc7eb5909e34cd903575

Fix compile error when OSS_DEBUG is enabled:
    sound/core/oss/pcm_oss.c: In function 'snd_pcm_oss_set_trigger':
    sound/core/oss/pcm_oss.c:2055:10: error: 'substream' undeclared (first
    use in this function); did you mean 'csubstream'?
      pcm_dbg(substream->pcm, "pcm_oss: trigger = 0x%x\n", trigger);
              ^

Fixes: 61efcee8608c ("ALSA: oss: Use standard printk helpers")
	Signed-off-by: Bixuan Cui <cuibixuan@linux.alibaba.com>
Link: https://lore.kernel.org/r/1638349134-110369-1-git-send-email-cuibixuan@linux.alibaba.com
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 8e7daf318d97f25e18b2fc7eb5909e34cd903575)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>