selftests/bpf: Declare subprog_noise as static in tailcall_bpf2bpf4
Bugzilla: https://bugzilla.redhat.com/2166911

commit b05d64efbb21ad231516b44317af34d2b586cfc4
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Thu Aug 25 21:51:39 2022 -0600

    selftests/bpf: Declare subprog_noise as static in tailcall_bpf2bpf4
    
    Due to bpf_map_lookup_elem being declared static we need to also
    declare subprog_noise as static.
    
    Fixes the following error:
    progs/tailcall_bpf2bpf4.c:26:9: error: 'bpf_map_lookup_elem' is static but used in inline function 'subprog_noise' which is not static [-Werror]
       26 |         bpf_map_lookup_elem(&nop_table, &key);
          |         ^~~~~~~~~~~~~~~~~~~
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Song Liu <song@kernel.org>
    Link: https://lore.kernel.org/bpf/20220826035141.737919-1-james.hilliard1@gmail.com

Signed-off-by: Artem Savkov <asavkov@redhat.com>