usb: hub: remove assignment from if condition
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] hub: remove assignment from if condition (Torez Smith) [1303955]
Rebuild_FUZZ: 94.12%
commit-author Kris Borer <kborer@gmail.com>
commit 088a3daeadf6f4123f54d5208b0ec7cbbfc8853f

Fix one occurrence of the checkpatch.pl error:

ERROR: do not use assignment in if condition

The semantic patch that makes this change is:

// <smpl>
@@
identifier i;
expression E, E2, E3;
statement S1, S2;
binary operator b;
@@

+ i = E;
  if (
- (i = E)
+ i
  b
  ... && E2 && E3 ) S1 else S2
// </smpl>

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 088a3daeadf6f4123f54d5208b0ec7cbbfc8853f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>