platform/x86/intel/tpmi/plr: Fix output in plr_print_bits()
JIRA: https://issues.redhat.com/browse/RHEL-46074

commit 182c6941c55347c735e70ffca77741cd000cbec7
Author: Dan Carpenter <dan.carpenter@linaro.org>
Date:   Mon Jul 15 15:22:55 2024 -0500

    platform/x86/intel/tpmi/plr: Fix output in plr_print_bits()

    Smatch complains that 'str' can be used without being initialized:

        drivers/platform/x86/intel/intel_plr_tpmi.c:178 plr_print_bits()
        error: uninitialized symbol 'str'.

    In this loop, we iterate over all the set bits and print the name of the
    bit.  The intention is that if there is a bit which is between 0-31 we
    look for the name in the first array plr_coarse_reasons[] which has 10
    elements.  If the bit is in the 32-63 range we look for it in the
    plr_fine_reasons[] array which has 30 elements.  If the bit is in the
    invalid ranges, 10-31 or 62-63, then we should print "UNKNOWN(%d)".

    The problem is that 'str' needs to be initialized at the start of each
    iteration, otherwise if we can't find the string then instead of printing
    "UNKNOWN(%d)", we will re-print whatever the previous bit was.

    Fixes: 9e9397a41b7b ("platform/x86/intel/tpmi/plr: Add support for the plr mailbox")
    Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
    Link: https://lore.kernel.org/r/b0084e70-4144-445a-9b89-fb19f6b8336a@stanley.mountain
    Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
    Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>