drm/tegra: vic: Fix unused-function warnings
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2154295
Upstream Status: v5.19-rc1

commit 42457494b8d6ef90e9c63e66bf2df7fa53406d6b
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Wed Mar 16 19:36:47 2022 +0100
Commit:     Thierry Reding <treding@nvidia.com>
CommitDate: Wed Apr  6 15:33:57 2022 +0200

    The use of the old-style SET_RUNTIME_PM_OPS() and
    SET_SYSTEM_SLEEP_PM_OPS() macros requires function definitions
    to be hidden to avoid

    drivers/gpu/drm/tegra/vic.c:326:12: error: 'vic_runtime_suspend' defined but not used [-Werror=unused-function]
      326 | static int vic_runtime_suspend(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/tegra/vic.c:292:12: error: 'vic_runtime_resume' defined but not used [-Werror=unused-function]
      292 | static int vic_runtime_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~~~~~

    Use the new-style SYSTEM_SLEEP_PM_OPS() and RUNTIME_PM_OPS() instead.

    Fixes: 1e15f5b911d6 ("drm/tegra: vic: Stop channel on suspend")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thierry Reding <treding@nvidia.com>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>