ASoC: cs42l42: Fix missing include of gpio/consumer.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-536.el8
commit-author Richard Fitzgerald <rf@opensource.cirrus.com>
commit d6cbc6a3a856a7d8047316d81e2e039e44432acb

The call to gpiod_set_value_cansleep() in cs42l42_sdw_update_status()
needs the header file gpio/consumer.h to be included.

This was introduced by commit 2d066c6a7865 ("ASoC: cs42l42: Avoid stale
SoundWire ATTACH after hard reset")

and caused error:
    sound/soc/codecs/cs42l42-sdw.c:374:4: error: implicit declaration of
    function ‘gpiod_set_value_cansleep’;
    did you mean gpio_set_value_cansleep’?

	Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
Fixes: 2d066c6a7865 ("ASoC: cs42l42: Avoid stale SoundWire ATTACH after hard reset")
Link: https://lore.kernel.org/r/20231011134853.20059-1-rf@opensource.cirrus.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit d6cbc6a3a856a7d8047316d81e2e039e44432acb)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>