sched/fair: Mark m*_vruntime() with __maybe_unused
JIRA: https://issues.redhat.com/browse/RHEL-78821

commit 95d9fed3a2aea85fe9551c2f007e186d4abb4a2a
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Mon Dec 2 19:35:30 2024 +0200

    sched/fair: Mark m*_vruntime() with __maybe_unused

    When max_vruntime() is unused, it prevents kernel builds with clang,
    `make W=1` and CONFIG_WERROR=y:

    kernel/sched/fair.c:526:19: error: unused function 'max_vruntime' [-Werror,-Wunused-function]
      526 | static inline u64 max_vruntime(u64 max_vruntime, u64 vruntime)
          |                   ^~~~~~~~~~~~

    Fix this by marking them with __maybe_unused (all cases for the sake of
    symmetry).

    See also commit 6863f5643dd7 ("kbuild: allow Clang to find unused static
    inline functions for W=1 build").

    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lkml.kernel.org/r/20241202173546.634433-1-andriy.shevchenko@linux.intel.com

Signed-off-by: Phil Auld <pauld@redhat.com>