scsi: qedf: fix LTO-enabled build
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [scsi] qedf: fix LTO-enabled build (Chad Dupuis) [1566547]
Rebuild_FUZZ: 90.00%
commit-author Arnd Bergmann <arnd@arndb.de>
commit d9ea463a1cc7f0a6254cbd8228e1948c345a4acd

The prototype for qedf_dbg_fops/qedf_debugfs_ops doesn't match the definition,
which causes the final link to fail with link-time optimizations:

drivers/scsi/qedf/qedf_main.c:34: error: type of 'qedf_dbg_fops' does not match original declaration [-Werror=lto-type-mismatch]
 extern struct file_operations qedf_dbg_fops;

drivers/scsi/qedf/qedf_debugfs.c:443: note: 'qedf_dbg_fops' was previously declared here
 const struct file_operations qedf_dbg_fops[] = {

drivers/scsi/qedf/qedf_main.c:33: error: type of 'qedf_debugfs_ops' does not match original declaration [-Werror=lto-type-mismatch]
 extern struct qedf_debugfs_ops qedf_debugfs_ops;

drivers/scsi/qedf/qedf_debugfs.c:102: note: 'qedf_debugfs_ops' was previously declared here
 struct qedf_debugfs_ops qedf_debugfs_ops[] = {

This corrects the prototype and moves it into a shared header file where it
belongs. The file operations can also be marked 'const' like the
qedf_debugfs_ops.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Chad Dupuis <chad.dupuis@cavium.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit d9ea463a1cc7f0a6254cbd8228e1948c345a4acd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>