openvswitch: fix compilation when vxlan is a module
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Nicolas Dichtel <nicolas.dichtel@6wind.com>
commit 2661371ace963280f34fe583d4a6697afecd87d5

With CONFIG_VXLAN=m and CONFIG_OPENVSWITCH=y, there was the following
compilation error:
  LD      init/built-in.o
  net/built-in.o: In function `vxlan_tnl_create':
  .../net/openvswitch/vport-netdev.c:322: undefined reference to `vxlan_dev_create'
  make: *** [vmlinux] Error 1

CC: Thomas Graf <tgraf@suug.ch>
Fixes: 614732eaa12d ("openvswitch: Use regular VXLAN net_device device")
	Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
	Acked-by: Thomas Graf <tgraf@suug.ch>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 2661371ace963280f34fe583d4a6697afecd87d5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>