ASoC: zl38060 add gpiolib dependency
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 0de2cc3707b6b6e2ad40bd24ce09a5c1f65d01e1

Without gpiolib, this driver fails to link:

arm-linux-gnueabi-ld: sound/soc/codecs/zl38060.o: in function `chip_gpio_get':
zl38060.c:(.text+0x30): undefined reference to `gpiochip_get_data'
arm-linux-gnueabi-ld: sound/soc/codecs/zl38060.o: in function `zl38_spi_probe':
zl38060.c:(.text+0xa18): undefined reference to `devm_gpiochip_add_data_with_key'

This appears to have been in the driver since the start, but is hard to
hit in randconfig testing since gpiolib is almost always selected by something
else.

Fixes: 52e8a94baf90 ("ASoC: Add initial ZL38060 driver")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20230227085850.2503725-1-arnd@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0de2cc3707b6b6e2ad40bd24ce09a5c1f65d01e1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>