x86/asm: Avoid unneeded __div64_32 function definition
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 65412c8d72741cc6e6b082b478b8957d7e7c0480
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 3 10:26:15 2023 +0200

    x86/asm: Avoid unneeded __div64_32 function definition

    The __div64_32() function is provided for 32-bit architectures that
    don't have a custom do_div() implementation. x86_32 has one, and
    does not use the header file that declares the function prototype,
    so the definition causes a W=1 warning:

      lib/math/div64.c:31:32: error: no previous prototype for '__div64_32' [-Werror=missing-prototypes]

    Define an empty macro to prevent the function definition from getting
    built, which avoids the warning and saves a little .text space.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
    Link: https://lore.kernel.org/r/20230803082619.1369127-4-arnd@kernel.org

Signed-off-by: Prarit Bhargava <prarit@redhat.com>