perf tools: Provide stub for missing pthread_attr_setaffinity_np
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] tools: Provide stub for missing pthread_attr_setaffinity_np (Jiri Olsa) [1209607]
Rebuild_FUZZ: 95.93%
commit-author Vineet Gupta <Vineet.Gupta1@synopsys.com>
commit 459a3df76c99124fd222586be7f10f862547e7a9

uClibc Linuxthreads.old doesn't support the pthread_attr_setaffinity_np()
functioo:

   ----------------->8-----------------------
  CC       bench/futex-hash.o
  CC       bench/futex-wake.o
bench/futex-hash.c: In function 'bench_futex_hash':
bench/futex-hash.c:161:3: error: implicit declaration of function
'pthread_attr_setaffinity_np' [-Werror=implicit-function-declaration]
   ret = pthread_attr_setaffinity_np(&thread_attr, sizeof(cpu_set_t),
&cpu);
   ^
bench/futex-hash.c:161:3: error: nested extern declaration of
'pthread_attr_setaffinity_np' [-Werror=nested-externs]
   ----------------->8-----------------------

So introduce a test to check that and if not available provide a stub.

	Signed-off-by: Vineet Gupta <vgupta@synopsys.com>
	Acked-by: Jiri Olsa <jolsa@kernel.org>
	Cc: Alexey Brodkin <Alexey.Brodkin@synopsys.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
Link: http://lkml.kernel.org/r/1421156604-30603-6-git-send-email-vgupta@synopsys.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 459a3df76c99124fd222586be7f10f862547e7a9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>