udp_tunnel: Only build ip6_udp_tunnel.c when IPV6 is selected
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Andy Zhou <azhou@nicira.com>
commit 6d967f8789249628a6388a3a4314c5fef423f36a

Functions supplied in ip6_udp_tunnel.c are only needed when IPV6 is
selected. When IPV6 is not selected, those functions are stubbed out
in udp_tunnel.h.

==================================================================
 net/ipv6/ip6_udp_tunnel.c:15:5: error: redefinition of 'udp_sock_create6'
     int udp_sock_create6(struct net *net, struct udp_port_cfg *cfg,
 In file included from net/ipv6/ip6_udp_tunnel.c:9:0:
      include/net/udp_tunnel.h:36:19: note: previous definition of 'udp_sock_create6' was here
       static inline int udp_sock_create6(struct net *net, struct udp_port_cfg *cfg,
==================================================================

Fixes:  fd384412e udp_tunnel: Seperate ipv6 functions into its own file
	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Andy Zhou <azhou@nicira.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 6d967f8789249628a6388a3a4314c5fef423f36a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>