include/linux/mm: fix release_pages_arg kernel doc comment
JIRA: https://issues.redhat.com/browse/RHEL-48221

This patch is a backport of the following upstream commit:
commit 0411d6ee50e3b74a793848e4f41f45860163f5cc
Author: SeongJae Park <sj@kernel.org>
Date:   Fri Jan 6 20:33:31 2023 +0000

    include/linux/mm: fix release_pages_arg kernel doc comment

    Commit 449c796768c9 ("mm: teach release_pages() to take an array of
    encoded page pointers too") added the kernel doc comment for
    release_pages() on top of 'union release_pages_arg', so making 'make
    htmldocs' complains as below:

        ./include/linux/mm.h:1268: warning: cannot understand function prototype: 'typedef union '

    The kernel doc comment for the function is already on top of the
    function's definition in mm/swap.c, and the new comment is actually not
    for the function but indeed release_pages_arg.  Fixing the comment to
    reflect the intent would be one option.  But, kernel doc cannot parse
    the union as below due to the attribute.

        ./include/linux/mm.h:1272: error: Cannot parse struct or union!

    Modify the comment to reflect the intent but do not mark it as a kernel
    doc comment.

    Link: https://lkml.kernel.org/r/20230106203331.127532-1-sj@kernel.org
    Fixes: 449c796768c9 ("mm: teach release_pages() to take an array of encoded page pointers too")
    Signed-off-by: SeongJae Park <sj@kernel.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>