iwlwifi: work around reverse dependency on MEI
Bugzilla: https://bugzilla.redhat.com/2059999

commit 977df8bd5844c9370c26a9477418165b870da27c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 7 16:14:36 2021 +0100

    iwlwifi: work around reverse dependency on MEI
    
    If the iwlmei code is a loadable module, the main iwlwifi driver
    cannot be built-in:
    
    x86_64-linux-ld: drivers/net/wireless/intel/iwlwifi/pcie/trans.o: in function `iwl_pcie_prepare_card_hw':
    trans.c:(.text+0x4158): undefined reference to `iwl_mei_is_connected'
    
    Unfortunately, Kconfig enforces the opposite, forcing the MEI driver to
    not be built-in if iwlwifi is a module.
    
    To work around this, decouple iwlmei from iwlwifi and add the
    dependency in the other direction.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20211207151447.3338818-1-arnd@kernel.org
    Signed-off-by: Luca Coelho <luciano.coelho@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>