kasan: always respect CONFIG_KASAN_STACK
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2028891

This patch is a backport of the following upstream commit:
commit 19532869feb9b0a97d17ddc14609d1e53a5b60db
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Fri Sep 24 15:44:00 2021 -0700

    kasan: always respect CONFIG_KASAN_STACK

    Currently, the asan-stack parameter is only passed along if
    CFLAGS_KASAN_SHADOW is not empty, which requires KASAN_SHADOW_OFFSET to
    be defined in Kconfig so that the value can be checked.  In RISC-V's
    case, KASAN_SHADOW_OFFSET is not defined in Kconfig, which means that
    asan-stack does not get disabled with clang even when CONFIG_KASAN_STACK
    is disabled, resulting in large stack warnings with allmodconfig:

      drivers/video/fbdev/omap2/omapfb/displays/panel-lgphilips-lb035q02.c:117:12: error: stack frame size (14400) exceeds limit (2048) in function 'lb035q02_connect' [-Werror,-Wframe-larger-than]
      static int lb035q02_connect(struct omap_dss_device *dssdev)
                 ^
      1 error generated.

    Ensure that the value of CONFIG_KASAN_STACK is always passed along to
    the compiler so that these warnings do not happen when
    CONFIG_KASAN_STACK is disabled.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1453
    References: 6baec880d7a5 ("kasan: turn off asan-stack for clang-8 and earlier")
    Link: https://lkml.kernel.org/r/20210922205525.570068-1-nathan@kernel.org
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Marco Elver <elver@google.com>
    Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
    Cc: Alexander Potapenko <glider@google.com>
    Cc: Andrey Konovalov <andreyknvl@gmail.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: Nick Desaulniers <ndesaulniers@google.com>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Rafael Aquini <aquini@redhat.com>