enic: fix build warning without CONFIG_CPUMASK_OFFSTACK
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 43d281662fdb46750d49417559b71069f435298d

The enic driver relies on the CONFIG_CPUMASK_OFFSTACK feature to
dynamically allocate a struct member, but this is normally intended for
local variables.

Building with clang, I get a warning for a few locations that check the
address of the cpumask_var_t:

drivers/net/ethernet/cisco/enic/enic_main.c:122:22: error: address of array 'enic->msix[i].affinity_mask' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]

As far as I can tell, the code is still correct, as the truth value of
the pointer is what we need in this configuration. To get rid of
the warning, use cpumask_available() instead of checking the
pointer directly.

Fixes: 322cf7e3a4e8 ("enic: assign affinity hint to interrupts")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 43d281662fdb46750d49417559b71069f435298d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>