ASoC: nau8825: fix bounds check for adc_delay
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Tom Rix <trix@redhat.com>
commit 5f3d94eb7ae877430d9fe6a9aae7dcef6c3e5fea

clang build reports
sound/soc/codecs/nau8825.c:2826:31: error: overlapping comparisons
  always evaluate to false [-Werror,-Wtautological-overlap-compare]
        if (nau8825->adc_delay < 125 && nau8825->adc_delay > 500)
            ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

This is a bug, a logical-or should have been used.

Fixes: fc0b096c9291 ("ASoC: nau8825: Add delay control for input path")
	Signed-off-by: Tom Rix <trix@redhat.com>
	Acked-by: David Lin <CTLIN0@nuvoton.com>
Link: https://lore.kernel.org/r/20230418120955.3230705-1-trix@redhat.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 5f3d94eb7ae877430d9fe6a9aae7dcef6c3e5fea)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>