bpf: Hide unused bpf_patch_call_args
JIRA: https://issues.redhat.com/browse/RHEL-9957

commit ba49f976885869835a1783863376221dc24f1817
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 2 15:50:18 2023 +0200

    bpf: Hide unused bpf_patch_call_args
    
    This function is only used when CONFIG_BPF_JIT_ALWAYS_ON is disabled, but
    CONFIG_BPF_SYSCALL is enabled. When both are turned off, the prototype is
    missing but the unused function is still compiled, as seen from this W=1
    warning:
    
      [...]
      kernel/bpf/core.c:2075:6: error: no previous prototype for 'bpf_patch_call_args' [-Werror=missing-prototypes]
      [...]
    
    Add a matching #ifdef for the definition to leave it out.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20230602135128.1498362-1-arnd@kernel.org

Signed-off-by: Viktor Malik <vmalik@redhat.com>