selinux: resolve checkpatch errors
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181134

commit ede17552b1e70d4435decba026b86e137b516248
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Mon May 2 15:48:48 2022 +0200

    selinux: resolve checkpatch errors

    Reported by checkpatch:

        security/selinux/nlmsgtab.c
        ---------------------------
        ERROR: that open brace { should be on the previous line
        #29: FILE: security/selinux/nlmsgtab.c:29:
        +static const struct nlmsg_perm nlmsg_route_perms[] =
        +{

        ERROR: that open brace { should be on the previous line
        #97: FILE: security/selinux/nlmsgtab.c:97:
        +static const struct nlmsg_perm nlmsg_tcpdiag_perms[] =
        +{

        ERROR: that open brace { should be on the previous line
        #105: FILE: security/selinux/nlmsgtab.c:105:
        +static const struct nlmsg_perm nlmsg_xfrm_perms[] =
        +{

        ERROR: that open brace { should be on the previous line
        #134: FILE: security/selinux/nlmsgtab.c:134:
        +static const struct nlmsg_perm nlmsg_audit_perms[] =
        +{

        security/selinux/ss/policydb.c
        ------------------------------
        ERROR: that open brace { should be on the previous line
        #318: FILE: security/selinux/ss/policydb.c:318:
        +static int (*destroy_f[SYM_NUM]) (void *key, void *datum, void *datap) =
        +{

        ERROR: that open brace { should be on the previous line
        #674: FILE: security/selinux/ss/policydb.c:674:
        +static int (*index_f[SYM_NUM]) (void *key, void *datum, void *datap) =
        +{

        ERROR: that open brace { should be on the previous line
        #1643: FILE: security/selinux/ss/policydb.c:1643:
        +static int (*read_f[SYM_NUM]) (struct policydb *p, struct symtab *s, void *fp) =
        +{

        ERROR: that open brace { should be on the previous line
        #3246: FILE: security/selinux/ss/policydb.c:3246:
        +                               void *datap) =
        +{

    Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Juraj Marcin <jmarcin@redhat.com>