perf daemon: Fix the build on 32-bit architectures
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit 4bbe6002931954bbe82b25f25990b987b0392e18
Author: Arnaldo Carvalho de Melo <arnaldo.melo@gmail.com>
Date: Thu Jul 18 16:38:07 2024 -0300

description
===========
Noticed with:

   1     6.22 debian:experimental-x-mipsel  : FAIL gcc version 13.2.0 (Debian 13.2.0-25)
    builtin-daemon.c: In function 'cmd_session_list':
    builtin-daemon.c:691:35: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'time_t' {aka 'long long int'} [-Werror=format=]

Use inttypes.h's PRIu64 to deal with that.

    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Link: https://lore.kernel.org/r/ZplvH21aQ8pzmza_@x1
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>