md: fix build failure for !MODULE
Bugzilla: https://bugzilla.redhat.com/2113822

commit 2198c51a08349eb176cb9789bef6f7243b8699f8
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Thu Jul 21 13:11:32 2022 +1000

    md: fix build failure for !MODULE

    After merging the block tree, today's linux-next build (x86_64
    allmodconfig) failed like this:

    drivers/md/md.c:717:22: error: 'mddev_find' defined but not used [-Werror=unused-function]
      717 | static struct mddev *mddev_find(dev_t unit)
          |                      ^~~~~~~~~~
    cc1: all warnings being treated as errors

    Caused by commit

      4500d5c17910 ("md: simplify md_open")

    Make mddev_find() available only for non-modular builds.

    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Link: https://lore.kernel.org/r/20220721131132.070be166@canb.auug.org.au
    Signed-off-by: Jens Axboe <axboe@kernel.dk>
Signed-off-by: Nigel Croxon <ncroxon@redhat.com>