drm/tegra: vic: Fix build warning when CONFIG_PM=n
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2154295
Upstream Status: v6.0-rc1

commit b5d5288a46876f6767950449aea310f71ac86277
Author:     YueHaibing <yuehaibing@huawei.com>
AuthorDate: Sat Mar  5 20:32:00 2022 +0800
Commit:     Thierry Reding <treding@nvidia.com>
CommitDate: Fri Jul  8 16:39:19 2022 +0200

    drivers/gpu/drm/tegra/vic.c:326:12: error: ‘vic_runtime_suspend’ defined but not used [-Werror=unused-function]
     static int vic_runtime_suspend(struct device *dev)
                ^~~~~~~~~~~~~~~~~~~
    drivers/gpu/drm/tegra/vic.c:292:12: error: ‘vic_runtime_resume’ defined but not used [-Werror=unused-function]
     static int vic_runtime_resume(struct device *dev)
                ^~~~~~~~~~~~~~~~~~

    Mark it as __maybe_unused.

    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Thierry Reding <treding@nvidia.com>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>