rtw88: fix uninitialized 'tim_offset' warning
Bugzilla: https://bugzilla.redhat.com/2136122

commit 9cbdadf0097fc4a77071c61ed28a07eaac97f8f6
Author: Po-Hao Huang <phhuang@realtek.com>
Date:   Wed Apr 20 17:30:57 2022 +0800

    rtw88: fix uninitialized 'tim_offset' warning
    
    This avoids below warning and makes compiler happy.
    error: uninitialized symbol 'tim_offset'
    
    Signed-off-by: Po-Hao Huang <phhuang@realtek.com>
    Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20220420093058.31646-1-pkshih@realtek.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>