objtool: Fix truncated string warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2090231

commit 82880283d7fcd0a1d20964a56d6d1a5cc0df0713
Author: Sergei Trofimovich <slyich@gmail.com>
Date:   Thu, 20 Jan 2022 23:37:48 +0000

    objtool: Fix truncated string warning

    On GCC 12, the build fails due to a possible truncated string:

        check.c: In function 'validate_call':
        check.c:2865:58: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
         2865 |                 snprintf(pvname, sizeof(pvname), "pv_ops[%d]", idx);
              |                                                          ^~

    In theory it's a valid bug:

        static char pvname[16];
        int idx;
        ...
        idx = (rel->addend / sizeof(void *));
        snprintf(pvname, sizeof(pvname), "pv_ops[%d]", idx);

    There are only 7 chars for %d while it could take up to 9, so the
    printed "pv_ops[%d]" string could get truncated.

    In reality the bug should never happen, because pv_ops only has ~80
    entries, so 7 chars for the integer is more than enough.  Still, it's
    worth fixing.  Bump the buffer size by 2 bytes to silence the warning.

    [ jpoimboe: changed size to 19; massaged changelog ]

    Fixes: db2b0c5d7b6f ("objtool: Support pv_opsindirect calls for noinstr")
    Reported-by: Adam Borowski <kilobyte@angband.pl>
    Reported-by: Martin Liška <mliska@suse.cz>
    Signed-off-by: Sergei Trofimovich <slyich@gmail.com>
    Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
    Link: https://lore.kernel.org/r/20220120233748.2062559-1-slyich@gmail.com

Signed-off-by: Waiman Long <longman@redhat.com>