objtool: Use HOSTCFLAGS for HAVE_XXHASH test
JIRA: https://redhat.atlassian.net/browse/RHEL-152189

commit 32234049107d012703d50547e815f198f147968b
Author: HONG Yifan <elsk@google.com>
Date:   Tue Mar 3 01:03:39 2026 +0000

    objtool: Use HOSTCFLAGS for HAVE_XXHASH test

    Previously, HAVE_XXHASH is tested by invoking HOSTCC without HOSTCFLAGS.

    Consider the following scenario:

    - The host machine has libxxhash installed
    - We build the kernel with HOSTCFLAGS containing a --sysroot that does
      not have xxhash.h (for hermetic builds)

    In this case, HAVE_XXHASH is set to y, but when it builds objtool with
    HOSTCFLAGS, because the --sysroot does not contain xxhash.h, the
    following error is raised:

    <...>/common/tools/objtool/include/objtool/checksum_types.h:12:10: fatal error: 'xxhash.h' file not found
       12 | #include <xxhash.h>
          |          ^~~~~~~~~~

    To resolve the error, we test HAVE_XXHASH by invoking HOSTCC with
    HOSTCFLAGS.

    Signed-off-by: HONG Yifan <elsk@google.com>
    Reviewed-by: Carlos Llamas <cmllamas@google.com>
    Link: https://patch.msgid.link/20260303010340.306164-1-elsk@google.com
    Signed-off-by: Josh Poimboeuf <jpoimboe@kernel.org>

Signed-off-by: Yannick Cote <ycote@redhat.com>