scsi: qla2xxx: check for kstrtol() failure
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1127.el7
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit b8870ec63676aba1d823f0b36c5f7e9929e57d23

The error handling was unintentionally left out so it introduces a Smatch
static checker warning:

    drivers/scsi/qla2xxx/qla_attr.c:1655 qla2x00_port_speed_store()
    error: uninitialized symbol 'type'.

Fixes: a7b9ca7fc87a ("scsi: qla2xxx: Add support for setting port speed")
	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit b8870ec63676aba1d823f0b36c5f7e9929e57d23)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>