libceph: use BUG() instead of BUG_ON(1)
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Arnd Bergmann <arnd@arndb.de>
commit d24cdcd3e40a6825135498e11c20c7976b9bf545

I ran into this compile warning, which is the result of BUG_ON(1)
not always leading to the compiler treating the code path as
unreachable:

    include/linux/ceph/osdmap.h: In function 'ceph_can_shift_osds':
    include/linux/ceph/osdmap.h:62:1: error: control reaches end of non-void function [-Werror=return-type]

Using BUG() here avoids the warning.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit d24cdcd3e40a6825135498e11c20c7976b9bf545)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>