rfkill: define rfill_soft_blocked() if !RFKILL
Bugzilla: https://bugzilla.redhat.com/2059999

commit 50bb467c9e76743fbc8441d29113cdad62dbc4fe
Author: Ben Dooks <ben.dooks@codethink.co.uk>
Date:   Fri Feb 18 09:38:58 2022 +0000

    rfkill: define rfill_soft_blocked() if !RFKILL
    
    If CONFIG_RFKILL is not set, the Intel WiFi driver will not build
    the iw_mvm driver part due to the missing rfill_soft_blocked()
    call. Adding a inline declaration of rfill_soft_blocked() if
    CONFIG_RFKILL=n fixes the following error:
    
    drivers/net/wireless/intel/iwlwifi/mvm/mvm.h: In function 'iwl_mvm_mei_set_sw_rfkill_state':
    drivers/net/wireless/intel/iwlwifi/mvm/mvm.h:2215:38: error: implicit declaration of function 'rfkill_soft_blocked'; did you mean 'rfkill_blocked'? [-Werror=implicit-function-declaration]
     2215 |                 mvm->hw_registered ? rfkill_soft_blocked(mvm->hw->wiphy->rfkill) : false;
          |                                      ^~~~~~~~~~~~~~~~~~~
          |                                      rfkill_blocked
    
    Signed-off-by: Ben Dooks <ben.dooks@codethink.co.uk>
    Reported-by: Neill Whillans <neill.whillans@codethink.co.uk>
    Fixes: 5bc9a9dd7535 ("rfkill: allow to get the software rfkill state")
    Link: https://lore.kernel.org/r/20220218093858.1245677-1-ben.dooks@codethink.co.uk
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>