iio: always select ANON_INODES
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [vfio] always select ANON_INODES (Alex Williamson) [1206275]
Rebuild_FUZZ: 90.91%
commit-author Arnd Bergmann <arnd@arndb.de>
commit cc8b49fa26f57cc0096e702d3e7c3f7c3e263300
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/cc8b49fa.failed

Without ANON_INODES, we get this build error:

drivers/built-in.o: In function `iio_event_getfd':
:(.text+0x14bf18): undefined reference to `anon_inode_getfd'

All other users explicitly select this symbol, so we should
do the same thing here.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Cc: Jonathan Cameron <jic23@kernel.org>
	Cc: linux-iio@vger.kernel.org
	Signed-off-by: Jonathan Cameron <jic23@kernel.org>
(cherry picked from commit cc8b49fa26f57cc0096e702d3e7c3f7c3e263300)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/iio/Kconfig