btrfs: fix static checker warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
commit-author Jeff Mahoney <jeffm@suse.com>
commit 1b8e5df6d9b676f6d31fb098ffdc7d18732729d7

This patch fixes the following warnings:
fs/btrfs/extent-tree.c:6201:12: sparse: symbol 'get_raid_name' was not declared. Should it be static?
fs/btrfs/extent-tree.c:8430:9: error: format not a string literal and no format arguments [-Werror=format-security] get_raid_name(index));

	Signed-off-by: Jeff Mahoney <jeffm@suse.com>
	Reviewed-by: Kees Cook <keescook@chromium.org>
	Signed-off-by: Josef Bacik <jbacik@fb.com>
	Signed-off-by: Chris Mason <clm@fb.com>
(cherry picked from commit 1b8e5df6d9b676f6d31fb098ffdc7d18732729d7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>