kmsan: fix missed kmsan_handle_dma() signature conversion
JIRA: https://issues.redhat.com/browse/RHEL-116969

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit ef3d979b3e270b6a41b6f306bfc442253c41a4cd
Author: Leon Romanovsky <leon@kernel.org>
Date:   Wed Sep 17 09:37:36 2025 +0300

    kmsan: fix missed kmsan_handle_dma() signature conversion

    kmsan_handle_dma_sg() has call to kmsan_handle_dma() function which was
    missed during conversion to physical addresses. Update that caller too
    and fix the following compilation error:

    mm/kmsan/hooks.c:372:6: error: too many arguments to function call, expected 3, have 4
      371 |                 kmsan_handle_dma(sg_page(item), item->offset, item->length,
          |                 ~~~~~~~~~~~~~~~~
      372 |                                  dir);
          |                                  ^~~
    mm/kmsan/hooks.c:362:19: note: 'kmsan_handle_dma' declared here
      362 | EXPORT_SYMBOL_GPL(kmsan_handle_dma);

    Fixes: 6eb1e769b2c1 ("kmsan: convert kmsan_handle_dma to use physical addresses")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202509170638.AMGNCMEE-lkp@intel.com/
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
    Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
    Reviewed-by: Alexander Potapenko <glider@google.com>
    Signed-off-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Link: https://lore.kernel.org/r/4b2d7d0175b30177733bbbd42bf979d77eb73c29.1758090947.git.leon@kernel.org

Signed-off-by: Cédric Le Goater <clg@redhat.com>