gpio: vf610: fix compilation error
Bugzilla: http://bugzilla.redhat.com/2137977

commit 8af3a0b23818af59971f538bf258c15e1033ea55
Author: Leon Romanovsky <leonro@nvidia.com>
Date:   Tue Jul 5 13:21:14 2022 +0300

    gpio: vf610: fix compilation error

    Fix compilation error by explicitly adding the missing include.

    drivers/gpio/gpio-vf610.c: In function ‘vf610_gpio_direction_input’:
    drivers/gpio/gpio-vf610.c:120:9: error: implicit declaration of function ‘pinctrl_gpio_direction_input’; did you mean ‘vf610_gpio_direction_input’? [-Werror=implicit-function-declaration]
      120 |  return pinctrl_gpio_direction_input(chip->base + gpio);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |         vf610_gpio_direction_input

    Fixes: 30a35c07d9e9 ("gpio: vf610: drop the SOC_VF610 dependency for GPIO_VF610")
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
    Signed-off-by: Tariq Toukan <tariqt@nvidia.com>
    Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    Signed-off-by: Bartosz Golaszewski <brgl@bgdev.pl>

Signed-off-by: Steve Best <sbest@redhat.com>