x86: Clean up names/macros conflicting with ptrace-abi.h
JIRA: https://redhat.atlassian.net/browse/RHEL-230497
Upstream Status: RHEL only

With the upcoming merging of commit 7e7f81cf6f5c ("x86/bugs: Make
Safe-RET robust against interrupt injection"), the nospec-branch.h header
will include the "<asm/ptrace-abi.h>" header which defines uppercase
macros for all the x86 register names. If the affected files contain
x86 assembly code that uses uppercase register names or macros that
matches those names, it can casue compilation error or warning.

Unfortunately, arch/x86/crypto/aesni-intel_asm.S in centos-stream-9
includes nospec-branch.h and 2 "%RIP" references.  This cause compilation
errors like:

  arch/x86/crypto/aesni-intel_asm.S:1594: Error: bad register name `%128)'

The affected assembly code was removed upstream in commit e6e758fa6443
("crypto: x86/aes-gcm - rewrite the AES-NI optimized AES-GCM"). So
upstream isn't affected.

Fix it by changing them to "%rip" which has no functional impact as
register names are case insensitive in x86 assembly code.

arch/x86/kernel/relocate_kernel_64.S also includes nospec-branch.h and
defines its own RSP macro. This causes compilation warning. Fix it by
un-defining the RSP macro before hand.

The upstream kernel has commit 8dbec5c77bc3 ("x86/kexec: Add data
section to relocate_kernel") which removes the RSP macro.

Signed-off-by: Waiman Long <longman@redhat.com>