wifi: ath11k: synchronize ath11k_mac_he_gi_to_nl80211_he_gi()'s return type
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-496.el8
commit-author Jiri Slaby (SUSE) <jirislaby@kernel.org>
commit dd1c2322694522f674c874f5fa02ac5ae39135dd

ath11k_mac_he_gi_to_nl80211_he_gi() generates a valid warning with gcc-13:
  drivers/net/wireless/ath/ath11k/mac.c:321:20: error: conflicting types for 'ath11k_mac_he_gi_to_nl80211_he_gi' due to enum/integer mismatch; have 'enum nl80211_he_gi(u8)'
  drivers/net/wireless/ath/ath11k/mac.h:166:5: note: previous declaration of 'ath11k_mac_he_gi_to_nl80211_he_gi' with type 'u32(u8)'

I.e. the type of the return value ath11k_mac_he_gi_to_nl80211_he_gi() in
the declaration is u32, while the definition spells enum nl80211_he_gi.
Synchronize them to the latter.

	Cc: Martin Liska <mliska@suse.cz>
	Cc: Kalle Valo <kvalo@kernel.org>
	Cc: "David S. Miller" <davem@davemloft.net>
	Cc: Eric Dumazet <edumazet@google.com>
	Cc: Jakub Kicinski <kuba@kernel.org>
	Cc: Paolo Abeni <pabeni@redhat.com>
	Cc: ath11k@lists.infradead.org
	Cc: linux-wireless@vger.kernel.org
	Cc: netdev@vger.kernel.org
	Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
	Reviewed-by: Jeff Johnson <quic_jjohnson@quicinc.com>
	Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/20221031114341.10377-1-jirislaby@kernel.org
(cherry picked from commit dd1c2322694522f674c874f5fa02ac5ae39135dd)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>