x86/boot/64: Fix spurious undefined reference when CONFIG_X86_5LEVEL=n, on GCC-12
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 35aafa1d41cee0d3d50164561bca34befc1d9ce3
Author: Ard Biesheuvel <ardb@kernel.org>
Date:   Mon Dec 9 10:41:06 2024 +0100

    x86/boot/64: Fix spurious undefined reference when CONFIG_X86_5LEVEL=n, on GCC-12

    In __startup_64(), the bool 'la57' can only assume the 'true' value if
    CONFIG_X86_5LEVEL is enabled in the build, and generally, the compiler
    can make this inference at build time, and elide any references to the
    symbol 'level4_kernel_pgt', which may be undefined if 'la57' is false.

    As it turns out, GCC 12 gets this wrong sometimes, and gives up with a
    build error:

       ld: arch/x86/kernel/head64.o: in function `__startup_64':
       head64.c:(.head.text+0xbd): undefined reference to `level4_kernel_pgt'

    even though the reference is in unreachable code. Fix this by
    duplicating the IS_ENABLED(CONFIG_X86_5LEVEL) in the conditional that
    tests the value of 'la57'.

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20241209094105.762857-2-ardb+git@google.com
    Closes: https://lore.kernel.org/oe-kbuild-all/202412060403.efD8Kgb7-lkp@intel.com/

Signed-off-by: Rafael Aquini <raquini@redhat.com>