selftests/bpf: Workaround for older vm_sockets.h.
Bugzilla: https://bugzilla.redhat.com/2221599

Conflicts: missing d61bd8c1fd02c selftests/bpf: add a
test case for vsock sockmap

commit 75860b52019cf93662c31596254599bf5f8df900
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Thu Apr 13 19:54:17 2023 -0700

    selftests/bpf: Workaround for older vm_sockets.h.

    Some distros ship with older vm_sockets.h that doesn't have VMADDR_CID_LOCAL
    which causes selftests build to fail:
    /tmp/work/bpf/bpf/tools/testing/selftests/bpf/prog_tests/sockmap_listen.c:261:18: error: ‘VMADDR_CID_LOCAL’ undeclared (first use in this function); did you mean ‘VMADDR_CID_HOST’?
        261 |  addr->svm_cid = VMADDR_CID_LOCAL;
            |                  ^~~~~~~~~~~~~~~~
            |                  VMADDR_CID_HOST

    Workaround this issue by defining it on demand.

    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Artem Savkov <asavkov@redhat.com>