ata: brcm: mark PM functions as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit ed87ad196dab6a757352d39c4c3fbc599340fe2c

The new shutdown callback causes a link failure:

drivers/ata/ahci_brcm.c: In function 'brcm_ahci_shutdown':
drivers/ata/ahci_brcm.c:552:8: error: implicit declaration of function 'brcm_ahci_suspend'; did you mean 'brcm_ahci_shutdown'? [-Werror=implicit-function-declaration]
  ret = brcm_ahci_suspend(&pdev->dev);
        ^~~~~~~~~~~~~~~~~

Remove the incorrect #ifdef and use __maybe_unused annotations
instead to make this more robust.

Fixes: 7de9b1688c1d ("ata: ahci_brcm: Add a shutdown callback")
	Acked-by: Florian Fainelli <f.fainelli@gmail.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Jens Axboe <axboe@kernel.dk>
(cherry picked from commit ed87ad196dab6a757352d39c4c3fbc599340fe2c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>