net: fix cdc-phonet.c dependency and build error
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 37d2dbcdcca88e392009d7cbe8617d5af0ebcb32

Fix build error caused by missing Kconfig dependency:

ERROR: "cdc_parse_cdc_header" [drivers/net/usb/cdc-phonet.ko] undefined!

	Reported-by: Fengguang Wu <fengguang.wu@intel.com>
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 37d2dbcdcca88e392009d7cbe8617d5af0ebcb32)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>