arm64/mm: fix page table check compile error for CONFIG_PGTABLE_LEVELS=2
JIRA: https://issues.redhat.com/browse/RHEL-40604

commit ed928a3402d8a24a70c242c63109c069a7b1f3ab
Author: Tong Tiangen <tongtiangen@huawei.com>
Date: Tue, 17 May 2022 07:45:48 +0000

    If CONFIG_PGTABLE_LEVELS=2 and CONFIG_ARCH_SUPPORTS_PAGE_TABLE_CHECK=y,
    then we trigger a compile error:

      error: implicit declaration of function 'pte_user_accessible_page'

    Move the definition of page table check helper out of branch
    CONFIG_PGTABLE_LEVELS > 2

    Link: https://lkml.kernel.org/r/20220517074548.2227779-3-tongtiangen@huawei.com
    Fixes: daf214c14dbe ("arm64/mm: enable ARCH_SUPPORTS_PAGE_TABLE_CHECK")
    Signed-off-by: Tong Tiangen <tongtiangen@huawei.com>
    Acked-by: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Anshuman Khandual <anshuman.khandual@arm.com>
    Cc: Pasha Tatashin <pasha.tatashin@soleen.com>
    Cc: Anshuman Khandual <anshuman.khandual@arm.com>
    Cc: Will Deacon <will@kernel.org>
    Cc: Paul Walmsley <paul.walmsley@sifive.com>
    Cc: Palmer Dabbelt <palmer@dabbelt.com>
    Cc: Albert Ou <aou@eecs.berkeley.edu>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Cc: Guohanjun <guohanjun@huawei.com>
    Cc: Xie XiuQi <xiexiuqi@huawei.com>
    Cc: kernel test robot <lkp@intel.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Mark Salter <msalter@redhat.com>