ASoC: Mediatek: MT8183: TS3A227: fix build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: Mediatek: MT8183: TS3A227: fix build error (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 94.12%
commit-author Anders Roxell <anders.roxell@linaro.org>
commit 2b7bcdad3af9fbd104d5f300dbb90f684c36aa09

When building CONFIG_SND_SOC_MT8183_MT6358_TS3A227E_MAX98357A=m the
following error pops up:

../sound/soc/mediatek/mt8183/mt8183-mt6358-ts3a227-max98357.c: In function ‘mt8183_mt6358_ts3a227_max98357_dev_probe’:
../sound/soc/mediatek/mt8183/mt8183-mt6358-ts3a227-max98357.c:325:13: error: ‘struct snd_soc_dai_link’ has no member named ‘platform’; did you mean ‘platforms’?
   dai_link->platform = NULL;
             ^~~~~~~~
             platforms

Rework to use 'dai_link->platforms' instead of 'dai_link->platform'.

Fixes: 11c0269017b2 ("ASoC: Mediatek: MT8183: Add machine driver with TS3A227")
	Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 2b7bcdad3af9fbd104d5f300dbb90f684c36aa09)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>