ALSA: hda/realtek: fix bad indentation for alc269
JIRA: https://issues.redhat.com/browse/RHEL-183295

commit c1258a2924d3a2453a6e7a6581acd8d6e5c6ba70
Author: Lei Huang <huanglei@kylinos.cn>
Date: Tue Mar 31 10:40:36 2026 +0800

    ALSA: hda/realtek: fix bad indentation for alc269

    Mention complains about this coding style:

      ERROR: code indent should use tabs where possible
      #6640: FILE: sound/hda/codecs/realtek/alc269.c:6640:
      +        [ALC233_FIXUP_LENOVO_GPIO2_MIC_HOTKEY] = {$

    fix it up.

    Fixes: 5de5db35350d ("ALSA: hda/realtek - Enable Mute LED for Lenovo platform")
    Signed-off-by: Lei Huang <huanglei@kylinos.cn>
    Link: https://patch.msgid.link/20260331024036.30782-1-huanglei814@163.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>