bridge: vlan: Allow setting VLAN neighbor suppression state
JIRA: https://issues.redhat.com/browse/RHEL-862

commit 83f6d600796c65ab34b08dbddb5795099dfda4d1
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Wed Apr 19 18:34:58 2023 +0300

    bridge: vlan: Allow setting VLAN neighbor suppression state

    Add a new VLAN attribute that allows user space to set the neighbor
    suppression state of the port VLAN. Example:

     # bridge -d -j -p vlan show dev swp1 vid 10 | jq '.[]["vlans"][]["neigh_suppress"]'
     false
     # bridge vlan set vid 10 dev swp1 neigh_suppress on
     # bridge -d -j -p vlan show dev swp1 vid 10 | jq '.[]["vlans"][]["neigh_suppress"]'
     true
     # bridge vlan set vid 10 dev swp1 neigh_suppress off
     # bridge -d -j -p vlan show dev swp1 vid 10 | jq '.[]["vlans"][]["neigh_suppress"]'
     false

     # bridge vlan set vid 10 dev br0 neigh_suppress on
     Error: bridge: Can't set neigh_suppress for non-port vlans.

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Acked-by: Nikolay Aleksandrov <razor@blackwall.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>