ACPI: Silence missing prototype warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-529.el8
commit-author Ammar Faizi <ammarfaizi2@gnuweeb.org>
commit 446c85af665cf6d911c4821ac9507c8ba0cc7e75

Compiling with clang-16:

  drivers/acpi/acpi_lpit.c:142:6: error: no previous prototype \
  for function 'acpi_init_lpit' [-Werror,-Wmissing-prototypes]

  drivers/acpi/ioapic.c:212:6: error: no previous prototype \
  for function 'pci_ioapic_remove' [-Werror,-Wmissing-prototypes]

  drivers/acpi/ioapic.c:229:5: error: no previous prototype \
  for function 'acpi_ioapic_remove' [-Werror,-Wmissing-prototypes]

Include "internal.h" to silence them.

	Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 446c85af665cf6d911c4821ac9507c8ba0cc7e75)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>