xfs: Fix 64-bit division on 32-bit in xlog_state_switch_iclogs()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 18842e0a4f48564bbed541947abd8131fd0e9734

On 32-bit (e.g. m68k):

    ERROR: modpost: "__udivdi3" [fs/xfs/xfs.ko] undefined!

Fix this by using a uint32_t intermediate, like before.

	Reported-by: noreply@ellerman.id.au
Fixes: 7660a5b48fbef958 ("xfs: log stripe roundoff is a property of the log")
	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Reviewed-by: Dave Chinner <dchinner@redhat.com>
	Reviewed-by: Darrick J. Wong <djwong@kernel.org>
	Signed-off-by: Darrick J. Wong <djwong@kernel.org>
(cherry picked from commit 18842e0a4f48564bbed541947abd8131fd0e9734)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>