hte: tegra: fix 'struct of_device_id' build error
Bugzilla: https://bugzilla.redhat.com/2183344

commit 6680c835ada1b34e882d0a32612f7294c62e27e0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Dec 15 17:46:19 2022 +0100

    hte: tegra: fix 'struct of_device_id' build error

    Without the extra #include, this driver produces a build failure
    in some configurations.

    drivers/hte/hte-tegra194-test.c:96:34: error: array type has incomplete element type 'struct of_device_id'
       96 | static const struct of_device_id tegra_hte_test_of_match[] = {

    Fixes: 9a75a7cd03c9 ("hte: Add Tegra HTE test driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Dipen Patel <dipenp@nvidia.com>
    Signed-off-by: Dipen Patel <dipenp@nvidia.com>

Signed-off-by: Shaoqin Huang <shahuang@redhat.com>