gfs2: Set .migrate_folio in gfs2_{rgrp,meta}_aops
JIRA: https://redhat.atlassian.net/browse/RHEL-145694
CVE: CVE-2025-39753

commit 5c8f12cf1e64e0e8e6cb80b0c935389973e8be8d
Author: Andrew Price <anprice@redhat.com>
Date:   Mon Jul 14 16:21:15 2025 +0100

    gfs2: Set .migrate_folio in gfs2_{rgrp,meta}_aops

    Clears up the warning added in 7ee3647243e5 ("migrate: Remove call to
    ->writepage") that occurs in various xfstests, causing "something found
    in dmesg" failures.

    [  341.136573] gfs2_meta_aops does not implement migrate_folio
    [  341.136953] WARNING: CPU: 1 PID: 36 at mm/migrate.c:944 move_to_new_folio+0x2f8/0x300

    Signed-off-by: Andrew Price <anprice@redhat.com>
    Signed-off-by: Andreas Gruenbacher <agruenba@redhat.com>

Signed-off-by: Rafael Aquini <raquini@redhat.com>