kvm: selftests: use -pthread instead of -lpthread
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Lei Yang <Lei.Yang@windriver.com>
commit 6bd317d3c865ebcddcb287a424093fe4758c40ef

I run into the following error

testing/selftests/kvm/dirty_log_test.c:285: undefined reference to `pthread_create'
testing/selftests/kvm/dirty_log_test.c:297: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

my gcc version is gcc version 4.8.4
"-pthread" would work everywhere

	Signed-off-by: Lei Yang <Lei.Yang@windriver.com>
	Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 6bd317d3c865ebcddcb287a424093fe4758c40ef)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>