ALSA: uapi: #include <time.h> in asound.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Daniel Mentz <danielmentz@google.com>
commit b5bdbb6ccd1117896bf4fba6bff75336ca423e8c

The uapi header asound.h defines types based on struct timespec. We need
to #include <time.h> to get access to the definition of this struct.

Previously, we encountered the following error message when building
applications with a clang/bionic toolchain:

kernel-headers/sound/asound.h:350:19: error: field has incomplete type 'struct timespec'
  struct timespec trigger_tstamp;
                  ^

The absence of the time.h #include statement does not cause build errors
with glibc, because its version of stdlib.h indirectly includes time.h.

	Signed-off-by: Daniel Mentz <danielmentz@google.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit b5bdbb6ccd1117896bf4fba6bff75336ca423e8c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>