iwlwifi: fix build error for IWLMEI
Bugzilla: https://bugzilla.redhat.com/2059999

commit 875ad06015329314c594d3302ac2bbea37774543
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Sun Feb 27 12:00:51 2022 -0800

    iwlwifi: fix build error for IWLMEI
    
    When CONFIG_IWLWIFI=m and CONFIG_IWLMEI=y, the kernel build system
    must be told to build the iwlwifi/ subdirectory for both IWLWIFI and
    IWLMEI so that builds for both =y and =m are done.
    
    This resolves an undefined reference build error:
    
    ERROR: modpost: "iwl_mei_is_connected" [drivers/net/wireless/intel/iwlwifi/iwlwifi.ko] undefined!
    
    Fixes: 977df8bd5844 ("wlwifi: work around reverse dependency on MEI")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Arnd Bergmann <arnd@arndb.de>
    Cc: Luca Coelho <luciano.coelho@intel.com>
    Cc: linux-wireless@vger.kernel.org
    Link: https://lore.kernel.org/r/20220227200051.7176-1-rdunlap@infradead.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>