powerpc/powernv: Replace CONFIG_POWERNV_MSI with just CONFIG_PPC_POWERNV
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [powerpc] powernv: Replace CONFIG_POWERNV_MSI with just CONFIG_PPC_POWERNV (Don Zickus) [1127366]
Rebuild_FUZZ: 94.12%
commit-author Michael Ellerman <michael@ellerman.id.au>
commit 66c29da6782b9861b17f9fc81746e30315e039c2

We currently have a user visible CONFIG_POWERNV_MSI option, but it
doesn't actually disable MSI for powernv. The MSI code is always built,
what it does disable is the inclusion of the MSI bitmap code, which
leads to a build error.

eg, with PPC_POWERNV=y and POWERNV_MSI=n we get:

  arch/powerpc/platforms/built-in.o: In function `.pnv_teardown_msi_irqs':
  pci.c:(.text+0x3558): undefined reference to `.msi_bitmap_free_hwirqs'

We don't really need a POWERNV_MSI symbol, just have the MSI bitmap code
depend directly on PPC_POWERNV.

	Signed-off-by: Michael Ellerman <michael@ellerman.id.au>
	Reviewed-by: Gavin Shan <shangw@linux.vnet.ibm.com>
	Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
(cherry picked from commit 66c29da6782b9861b17f9fc81746e30315e039c2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>