samples/bpf: tracex4: Fix failed to create kretprobe 'kmem_cache_alloc_node+0x0'
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit d205d4af3a5ee840edecfa5f6b389d7d03b0786d
Author: Rong Tao <rongtao@cestc.cn>
Date:   Tue Aug 27 12:30:30 2024 +0800

    samples/bpf: tracex4: Fix failed to create kretprobe 'kmem_cache_alloc_node+0x0'

    commit 7bd230a26648 ("mm/slab: enable slab allocation tagging for kmalloc
    and friends") [1] swap kmem_cache_alloc_node() to
    kmem_cache_alloc_node_noprof().

        linux/samples/bpf$ sudo ./tracex4
        libbpf: prog 'bpf_prog2': failed to create kretprobe
        'kmem_cache_alloc_node+0x0' perf event: No such file or directory
        ERROR: bpf_program__attach failed

    Signed-off-by: Rong Tao <rongtao@cestc.cn>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://github.com/torvalds/linux/commit/7bd230a26648ac68ab3731ebbc449090f0ac6a37
    Link: https://lore.kernel.org/bpf/tencent_34E5BCCAC5ABF3E81222AD81B1D05F16DE06@qq.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>