ASoC: SOF: Intel: Initialize chip in hda_sdw_check_wakeen_irq()
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 9c28423d3caae63e665e2b8d704fa41ac823b2a6
Author: Nathan Chancellor <nathan@kernel.org>
Date: Wed Aug 9 11:12:07 2023 -0700

    ASoC: SOF: Intel: Initialize chip in hda_sdw_check_wakeen_irq()

    Clang warns (or errors with CONFIG_WERROR):

      sound/soc/sof/intel/hda.c:423:6: error: variable 'chip' is uninitialized when used here [-Werror,-Wuninitialized]
        423 |         if (chip && chip->check_sdw_wakeen_irq)
            |             ^~~~
      sound/soc/sof/intel/hda.c:418:39: note: initialize the variable 'chip' to silence this warning
        418 |         const struct sof_intel_dsp_desc *chip;
            |                                              ^
            |                                               = NULL
      1 error generated.

    Add the missing initialization, following the pattern of the other irq
    functions.

    Fixes: 9362ab78f175 ("ASoC: SOF: Intel: add abstraction for SoundWire wake-ups")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://lore.kernel.org/r/20230809-intel-hda-missing-chip-init-v1-1-61557ca6fa8a@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>