of: fdt: Rename reserve_elfcorehdr() to fdt_reserve_elfcorehdr()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2091852
Upstream Status: https://github.com/torvalds/linux.git
Tested: on ampere-mtsnow-altra-11.khw4.lab.eng.bos.redhat.com
Build-info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46106617
Conflicts: none

commit 2fcf9a178ba1f2d4f2bf715312b84508850701d2
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Wed Aug 25 11:40:40 2021 +0200

    of: fdt: Rename reserve_elfcorehdr() to fdt_reserve_elfcorehdr()

    On ia64/allmodconfig:

        drivers/of/fdt.c:609:20: error: conflicting types for 'reserve_elfcorehdr'; have 'void(void)'
          609 | static void __init reserve_elfcorehdr(void)
              |                    ^~~~~~~~~~~~~~~~~~
        arch/ia64/include/asm/meminit.h:43:12: note: previous declaration of 'reserve_elfcorehdr' with type 'int(u64 *, u64 *)' {aka 'int(long long unsigned int *, long long unsigned int *)'}
           43 | extern int reserve_elfcorehdr(u64 *start, u64 *end);
              |            ^~~~~~~~~~~~~~~~~~

    Fix this by prefixing the FDT function name with "fdt_".

    Fixes: f7e7ce93aac13118 ("of: fdt: Add generic support for handling elf core headers property")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Link: https://lore.kernel.org/r/f6eabbbce0fba6da3da0264c1e1cf23c01173999.1629884393.git.geert+renesas@glider.be
    Signed-off-by: Rob Herring <robh@kernel.org>

Signed-off-by: Pingfan Liu <piliu@redhat.com>