ASoC: codecs: lpass-wsa-macro: add missing select of common code
JIRA: https://issues.redhat.com/browse/RHEL-60915

commit 36ac1e29f49ff4cbf1500465db311b17d8ba9213
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Thu Jun 27 14:52:03 2024 +0200

    ASoC: codecs: lpass-wsa-macro: add missing select of common code

    The Qualcomm LPASS WSA macro codec driver uses now parts of common
    module, so it has to select SND_SOC_LPASS_MACRO_COMMON.

      sound/soc/codecs/lpass-wsa-macro.o: in function `wsa_macro_probe':
      sound/soc/codecs/lpass-wsa-macro.c:2767:(.text+0x1c9c): undefined reference to `lpass_macro_get_codec_version'

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202406272231.th1LtuLk-lkp@intel.com/
    Fixes: 5dcf442bbbca ("ASoC: codecs: lpass-wsa-macro: Prepare to accommodate new codec versions")
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://patch.msgid.link/20240627125203.171048-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>