perf cs-etm: Add proper header file for symbols
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Mathieu Poirier <mathieu.poirier@linaro.org>
commit 859dcf64389c93a647f230a7cfd206d30bc9d286

After 'commit e22c1c751140 ("perf thread: Don't include symbol.h,
symbol_conf.h is enough")'

Compilation of the perf tools is broken when using the functionality
provided by the openCSD library:

[...]

...                       timerfd: [ on  ]
...                  sched_getcpu: [ on  ]
...                           sdt: [ OFF ]
...                         setns: [ on  ]
...                    libopencsd: [ on  ]

[...]

  CC       util/arm-spe.o
  CC       util/arm-spe-pkt-decoder.o
  CC       util/s390-cpumsf.o
  CC       util/cs-etm.o
  CC       util/parse-branch-options.o
util/cs-etm.c: In function ‘cs_etm__mem_access’:
util/cs-etm.c:297:24: error: storage size of ‘al’ isn’t known
  struct  addr_location al;

And rightly so since file cs-etm.c doesn't include symbol.h, something
that is rectified in this patch.

	Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Suzuki K Poulouse <suzuki.poulose@arm.com>
	Cc: linux-arm-kernel@lists.infradead.org
Link: http://lkml.kernel.org/r/20190208223543.31836-1-mathieu.poirier@linaro.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 859dcf64389c93a647f230a7cfd206d30bc9d286)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>