ALSA: hdac: Explicitly add io.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Vinod Koul <vinod.koul@intel.com>
commit 42f2bb1c494543084b764e1ca253c73db910daf2

Compiling the hdac extended core on arm fails with below error:

  sound/hda/ext/hdac_ext_bus.c: In function 'hdac_ext_writel':
>> sound/hda/ext/hdac_ext_bus.c:29:2: error: implicit declaration of
>> function
+'writel' [-Werror=implicit-function-declaration]
     writel(value, addr);
     ^
   sound/hda/ext/hdac_ext_bus.c: In function 'hdac_ext_readl':
>> sound/hda/ext/hdac_ext_bus.c:34:2: error: implicit declaration of
>> function
+'readl' [-Werror=implicit-function-declaration]
     return readl(addr);

This is fixed by explicitly including io.h

Fixes: 99463b3a3994 - ('ALSA: hda: provide default bus io ops extended hdac')
	Reported-by: kbuild test robot <lkp@intel.com>
	Suggested-by: Mark Brown <broonie@kernel.org>
	Signed-off-by: Vinod Koul <vinod.koul@intel.com>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 42f2bb1c494543084b764e1ca253c73db910daf2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>