x86/mce: Add notifier_block forward declaration
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 704ae091b061082b37a9968621af4c290c641d50

Without linux/irq.h, there is no declaration of notifier_block, leading to
a build warning:

In file included from arch/x86/kernel/cpu/mcheck/threshold.c:10:
arch/x86/include/asm/mce.h:151:46: error: 'struct notifier_block' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

It's sufficient to declare the struct tag here, which avoids pulling in
more header files.

Fixes: 447ae3166702 ("x86: Don't include linux/irq.h from asm/hardirq.h")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
	Cc: Nicolai Stange <nstange@suse.de>
	Cc: "H. Peter Anvin" <hpa@zytor.com>
	Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Cc: Borislav Petkov <bp@suse.de>
Link: https://lkml.kernel.org/r/20180817100156.3009043-1-arnd@arndb.de

(cherry picked from commit 704ae091b061082b37a9968621af4c290c641d50)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>