perf build: Always disable stack protection for BPF skeleton objects
JIRA: https://issues.redhat.com/browse/RHEL-78200

upstream
========
commit e9fdf0d2ecc095ce9f078588c7ce06967e0138b2
Author: Federico Pellegrin <fede@evolware.org>
Date: Fri Jul 18 06:12:24 2025 +0200

description
===========
When the clang toolchain has stack protection enabled, the bpf
skeletons build fails with:

error: A call to built-in function '__stack_chk_fail' is not supported.

Since stack-protector makes no sense for the BPF bits, just unconditionally
disable it.

See also similar case at 878625e1c7a10dfbb1fdaaaae2c4d2a58fbce627

    Signed-off-by: Federico Pellegrin <fede@evolware.org>
    Link: https://lore.kernel.org/r/20250718041224.12389-1-fede@evolware.org
[ rearrange long lines ]
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Anubhav Shelat <ashelat@redhat.com>