x86/cyrix: include header linux/isa-dma.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2124638
Upstream Status: d63ed7fe85eed2e70bdb16610f327edc765f4c44

commit d63ed7fe85eed2e70bdb16610f327edc765f4c44
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Mon Jul 25 13:22:24 2022 -0700

    x86/cyrix: include header linux/isa-dma.h

    x86/kernel/cpu/cyrix.c now needs to include <linux/isa-dma.h> since the
    'isa_dma_bridge_buggy' variable was moved to it.

    Fixes this build error:

      ../arch/x86/kernel/cpu/cyrix.c: In function ‘init_cyrix’:
      ../arch/x86/kernel/cpu/cyrix.c:277:17: error: ‘isa_dma_bridge_buggy’ undeclared (first use in this function)
        277 |                 isa_dma_bridge_buggy = 2;

    Fixes: abb4970ac335 ("PCI: Move isa_dma_bridge_buggy out of asm/dma.h")
    Link: https://lore.kernel.org/r/20220725202224.29269-1-rdunlap@infradead.org
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Acked-by: Stafford Horne <shorne@gmail.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>
    Cc: x86@kernel.org

Signed-off-by: Myron Stowe <mstowe@redhat.com>