nfp: bpf: silence bitwise vs. logical OR warning
Bugzilla: https://bugzilla.redhat.com/2124279
Upstream Status: kernel/git/davem/net-next.git
Conflicts: none

commit 8a64ef042eab8a6cec04a6c79d44d1af79b628ca
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon Oct 18 12:31:01 2021 -0700

    nfp: bpf: silence bitwise vs. logical OR warning

    A new warning in clang points out two places in this driver where
    boolean expressions are being used with a bitwise OR instead of a
    logical one:

    drivers/net/ethernet/netronome/nfp/nfp_asm.c:199:20: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
            reg->src_lmextn = swreg_lmextn(lreg) | swreg_lmextn(rreg);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 ||
    drivers/net/ethernet/netronome/nfp/nfp_asm.c:199:20: note: cast one or both operands to int to silence this warning
    drivers/net/ethernet/netronome/nfp/nfp_asm.c:280:20: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
            reg->src_lmextn = swreg_lmextn(lreg) | swreg_lmextn(rreg);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 ||
    drivers/net/ethernet/netronome/nfp/nfp_asm.c:280:20: note: cast one or both operands to int to silence this warning
    2 errors generated.

    The motivation for the warning is that logical operations short circuit
    while bitwise operations do not. In this case, it does not seem like
    short circuiting is harmful so implement the suggested fix of changing
    to a logical operation to fix the warning.

    Link: https://github.com/ClangBuiltLinux/linux/issues/1479
    Reported-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Link: https://lore.kernel.org/r/20211018193101.2340261-1-nathan@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Stefan Assmann <sassmann@redhat.com>