block: restore the old set_task_ioprio() behaviour wrt PF_EXITING
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2066297

commit 15583a563cd5a7358e975599b7de7caacd9e9ce9
Author: Jiri Slaby <jirislaby@kernel.org>
Date:   Mon Mar 28 10:59:28 2022 +0200

    block: restore the old set_task_ioprio() behaviour wrt PF_EXITING

    PF_EXITING tasks were silently ignored before the below commits.
    Continue doing so. Otherwise python-psutil tests fail:
      ERROR: psutil.tests.test_process.TestProcess.test_zombie_process
      ----------------------------------------------------------------------
      Traceback (most recent call last):
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/build/lib.linux-x86_64-3.9/psutil/_pslinux.py", line 1661, in wrapper
          return fun(self, *args, **kwargs)
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/build/lib.linux-x86_64-3.9/psutil/_pslinux.py", line 2133, in ionice_set
          return cext.proc_ioprio_set(self.pid, ioclass, value)
      ProcessLookupError: [Errno 3] No such process

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/psutil/tests/test_process.py", line 1313, in test_zombie_process
          succeed_or_zombie_p_exc(fun)
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/psutil/tests/test_process.py", line 1288, in succeed_or_zombie_p_exc
          return fun()
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/build/lib.linux-x86_64-3.9/psutil/__init__.py", line 792, in ionice
          return self._proc.ionice_set(ioclass, value)
        File "/home/abuild/rpmbuild/BUILD/psutil-5.9.0/build/lib.linux-x86_64-3.9/psutil/_pslinux.py", line 1665, in wrapper
          raise NoSuchProcess(self.pid, self._name)
      psutil.NoSuchProcess: process no longer exists (pid=2057)

    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Jan Kara <jack@suse.cz>
    Cc: Jens Axboe <axboe@kernel.dk>
    Fixes: 5fc11eebb4 (block: open code create_task_io_context in set_task_ioprio)
    Fixes: a957b61254 (block: fix error in handling dead task for ioprio setting)
    Signed-off-by: Jiri Slaby <jslaby@suse.cz>
    Reviewed-by: Jan Kara <jack@suse.cz>
    Link: https://lore.kernel.org/r/20220328085928.7899-1-jslaby@suse.cz
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>