Revert "Merge: kernel/futex: backport new futex_waitv(2) system call"
This reverts commit 54e20a629aa1a3c8ae37922c4b36d1b6309970d4, reversing
changes made to b111b5d5504952ea2956e7d125d55c1fa85922bf.

The futex changes break PREEMPT_RT builds with:

kernel/futex/futex.h:109:24: error: field ‘requeue_wait’ has incomplete type
	109 |         struct rcuwait requeue_wait;
	    |                        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:271: kernel/futex/pi.o] Error 1
make[1]: *** [scripts/Makefile.build:514: kernel/futex] Error 2

Signed-off-by: Fernando Pacheco <fpacheco@redhat.com>