memory: tegra: fix unused-function warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2135064

commit eaf89f1cd38cf7256ab64424fe94014632044d57
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu, 22 Jul 2021 11:07:43 +0200

    The tegra186_mc_client_sid_override() is only called from
    an #ifdef block:

    drivers/memory/tegra/tegra186.c:74:13: error: 'tegra186_mc_client_sid_override' defined but not used [-Werror=unused-function]
       74 | static void tegra186_mc_client_sid_override(struct tegra_mc *mc,
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Add another #ifdef around the called function.

    Fixes: 393d66fd2cac ("memory: tegra: Implement SID override programming")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Jon Hunter <jonathanh@nvidia.com>
    Link: https://lore.kernel.org/r/20210722090748.1157470-1-arnd@kernel.org
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>

Signed-off-by: Mark Salter <msalter@redhat.com>