gpiolib: avoid format string weakness in workqueue interface
JIRA: https://issues.redhat.com/browse/RHEL-75590

commit a22c9dc26d6fc522357b73858b13e29c58f49d64
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 28 14:21:46 2024 +0000

    gpiolib: avoid format string weakness in workqueue interface

    Using a string literal as a format string is a possible bug when the
    string contains '%' characters:

    drivers/gpio/gpiolib-cdev.c:2813:48: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
     2813 |         gdev->line_state_wq = alloc_ordered_workqueue(dev_name(&gdev->dev),
          |                                                       ^~~~~~~~~~~~~~~~~~~~
    drivers/gpio/gpiolib-cdev.c:2813:48: note: treat the string as an argument to avoid this
     2813 |         gdev->line_state_wq = alloc_ordered_workqueue(dev_name(&gdev->dev),
          |                                                       ^
          |                                                       "%s",

    Do as clang suggests and use a trivial "%s" format string.

    Fixes: 7b9b77a8bba9 ("gpiolib: add a per-gpio_device line state notification workqueue")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20241028142152.750650-1-arnd@kernel.org
    Signed-off-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>

Signed-off-by: Izabela Bakollari <ibakolla@redhat.com>