ASoC: lochnagar: Fix unused lochnagar_of_match warning
Bugzilla: https://bugzilla.redhat.com/2179848

commit a12a383e59ce486abd719b6bda33c353a3b385e7
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Thu Dec 15 14:43:37 2022 +0100

    ASoC: lochnagar: Fix unused lochnagar_of_match warning

    lochnagar_of_match is used unconditionally, so COMPILE_TEST builds
    without OF warn:

      sound/soc/codecs/lochnagar-sc.c:247:34: error: ‘lochnagar_of_match’ defined but not used [-Werror=unused-const-variable=]

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20221215134337.77944-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>