wifi: wilc1000: fix spurious inline in wilc_handle_disconnect()
Bugzilla: https://bugzilla.redhat.com/2136122

commit f01272ee3856e62e8a0f8211e8edf1876a6f5e38
Author: Kalle Valo <kvalo@kernel.org>
Date:   Mon Aug 1 14:04:40 2022 +0300

    wifi: wilc1000: fix spurious inline in wilc_handle_disconnect()
    
    Sparse warns:
    
    drivers/net/wireless/microchip/wilc1000/hif.h:218:35: error: marked inline, but without a definition
    
    Remove the inline, it's not needed.
    
    Reported-by: Jakub Kicinski <kuba@kernel.org>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Acked-by: Ajay Singh <ajay.kathat@microchip.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20220801110440.13144-1-kvalo@kernel.org

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>