ALSA: line6: snd-usb-line6 depends on CONFIG_SND_HWDEP
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
commit-author Valdis Kletnieks <Valdis.Kletnieks@vt.edu>
commit 0da325afbdb80098e014b83937372e3eef6872d5

ERROR: "snd_hwdep_new" [sound/usb/line6/snd-usb-line6.ko] undefined!
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1

Fixes: a16039cbf1a1 ('ALSA: line6: Add hwdep interface to access the POD control messages')
	Signed-off-by: Valdis Kletnieks <valdis.kletnieks@vt.edu>
	Reviewed-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 0da325afbdb80098e014b83937372e3eef6872d5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>