jfs: implement migrate_folio for jfs_metapage_aops
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 906d7ce3b59d62cf017ca602a0dfcb29413b8872
Author: Shivank Garg <shivankg@amd.com>
Date:   Wed Apr 30 10:01:52 2025 +0000

    jfs: implement migrate_folio for jfs_metapage_aops

    Add the missing migrate_folio operation to jfs_metapage_aops to fix
    warnings during memory compaction.  These warnings were introduced by
    commit 7ee3647243e5 ("migrate: Remove call to ->writepage") which added
    explicit warnings when filesystems don't implement migrate_folio.

    System reports following warnings:
      jfs_metapage_aops does not implement migrate_folio
      WARNING: CPU: 0 PID: 6870 at mm/migrate.c:955 fallback_migrate_folio mm/migrate.c:953 [inline]
      WARNING: CPU: 0 PID: 6870 at mm/migrate.c:955 move_to_new_folio+0x70e/0x840 mm/migrate.c:1007

    Implement metapage_migrate_folio() which handles both single and multiple
    metapages per page configurations.

    [shivankg@amd.com: change comment style]
      Link: https://lkml.kernel.org/r/1967593d-8084-4a4a-b384-35d5adc54eb4@amd.com
    [akpm@linux-foundation.org: fix build]
    [shivankg@amd.com: remove redundant NULL check in __metapage_migrate_folio()]
      Link: https://lkml.kernel.org/r/a67db238-0ca6-4725-abb2-dc092de87e1b@amd.com
    Link: https://lkml.kernel.org/r/20250430100150.279751-3-shivankg@amd.com
    Fixes: 35474d52c605 ("jfs: Convert metapage_writepage to metapage_write_folio")
    Signed-off-by: Shivank Garg <shivankg@amd.com>
    Reported-by: syzbot+8bb6fd945af4e0ad9299@syzkaller.appspotmail.com
    Closes: https://lore.kernel.org/all/67faff52.050a0220.379d84.001b.GAE@google.com
    Tested-by: syzbot+8bb6fd945af4e0ad9299@syzkaller.appspotmail.com
    Cc: Alistair Popple <apopple@nvidia.com>
    Cc: Dave Kleikamp <shaggy@kernel.org>
    Cc: David Hildenbrand <david@redhat.com>
    Cc: Donet Tom <donettom@linux.ibm.com>
    Cc: Jane Chu <jane.chu@oracle.com>
    Cc: Kefeng Wang <wangkefeng.wang@huawei.com>
    Cc: Matthew Wilcox <willy@infradead.org>
    Cc: Zi Yan <ziy@nvidia.com>
    Cc: Dan Carpenter <dan.carpenter@linaro.org>
    Cc: kernel test robot <lkp@intel.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>