ASoC: ti: remove compat dma probing
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: ti: remove compat dma probing (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 92.11%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 642aafea8889b712fe8e57aaa706d6c05d295059

After running into a link error:

sound/soc/ti/edma-pcm.o:(.rodata+0x18): undefined reference to `edma_filter_fn'

I checked all users of this, and they have new-style 'dma_slave_map' tables,
so none of them should still need it. Removing the associated lines
simplifies the code and avoids the build-time dependency on the
respective dmaengine drivers.

	Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 642aafea8889b712fe8e57aaa706d6c05d295059)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>