ASoC: fsl: fsl_dma: fix build failure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-240.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: fsl: fsl_dma: fix build failure (Jaroslav Kysela) [1797509]
Rebuild_FUZZ: 92.50%
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit d3de1eb461e5bac0b07f5c785e6e0d959915df96

Commit 4ac85de9977e ("ASoC: fsl: fsl_dma: remove snd_pcm_ops") removed
fsl_dma_ops but left a usage, leading to a build error for some
configs, eg. mpc85xx_defconfig:

  sound/soc/fsl/fsl_dma.c: In function ‘fsl_soc_dma_probe’:
  sound/soc/fsl/fsl_dma.c:905:18: error: ‘fsl_dma_ops’ undeclared (first use in this function)
    dma->dai.ops = &fsl_dma_ops;
                    ^~~~~~~~~~~

Remove the usage to fix the build.

Fixes: 4ac85de9977e ("ASoC: fsl: fsl_dma: remove snd_pcm_ops")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20191025051353.2878-1-mpe@ellerman.id.au
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit d3de1eb461e5bac0b07f5c785e6e0d959915df96)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>