net/mlx5: Add esw assignment back in mlx5e_tc_sample_unoffload()
Bugzilla: https://bugzilla.redhat.com/2049449
Upstream-status: v5.16-rc1

commit 1aec85974ab79903aaaab7d1f7fffe3d1ad1eee2
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Oct 27 08:31:22 2021 -0700

    net/mlx5: Add esw assignment back in mlx5e_tc_sample_unoffload()

    Clang warns:

    drivers/net/ethernet/mellanox/mlx5/core/en/tc/sample.c:635:34: error: variable 'esw' is uninitialized when used here [-Werror,-Wuninitialized]
            mlx5_eswitch_del_offloaded_rule(esw, sample_flow->pre_rule, sample_flow->pre_attr);
                                            ^~~
    drivers/net/ethernet/mellanox/mlx5/core/en/tc/sample.c:626:26: note: initialize the variable 'esw' to silence this warning
            struct mlx5_eswitch *esw;
                                    ^
                                     = NULL
    1 error generated.

    It appears that the assignment should have been shuffled instead of
    removed outright like in mlx5e_tc_sample_offload(). Add it back so there
    is no use of esw uninitialized.

    Fixes: a64c5edbd20e ("net/mlx5: Remove unnecessary checks for slow path flag")
    Link: https://github.com/ClangBuiltLinux/linux/issues/1494
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>