xfs: Clear W=1 warning in xfs_iwalk_run_callbacks()
JIRA: https://issues.redhat.com/browse/RHEL-85589

commit d7ba701da636afae17d8e1243b3d12eed149abcb
Author: John Garry <john.g.garry@oracle.com>
Date:   Thu May 2 10:08:25 2024 +0000

    xfs: Clear W=1 warning in xfs_iwalk_run_callbacks()

    For CONFIG_XFS_DEBUG unset, xfs_iwalk_run_callbacks() generates the
    following warning for when building with W=1:

    fs/xfs/xfs_iwalk.c: In function ‘xfs_iwalk_run_callbacks’:
    fs/xfs/xfs_iwalk.c:354:42: error: variable ‘irec’ set but not used [-Werror=unused-but-set-variable]
      354 |         struct xfs_inobt_rec_incore     *irec;
          |                                          ^~~~
    cc1: all warnings being treated as errors

    Drop @irec, as it is only an intermediate variable.

    Suggested-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: John Garry <john.g.garry@oracle.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Chandan Babu R <chandanbabu@kernel.org>

Signed-off-by: Bill O'Donnell <bodonnel@redhat.com>