redhat/configs: disable CONFIG_ARCH_BCM2835 temporary
Bugzilla: INTERNAL
Upstream Status: RHEL-only

The commit 8a697fea removed the handle_domain_{irq,nmi} because they are
not being used by RHEL. But, there are other occurences in other
drivers. Once we pulled from merge 203b5a91, we have started to see
compilation errors related to BCM2835 driver. For further information,
see the error below:

drivers/irqchip/irq-bcm2835.c: In function ‘bcm2835_handle_irq’:
drivers/irqchip/irq-bcm2835.c:249:17: error: implicit declaration of function ‘handle_domain_irq’; did you mean ‘handle_bad_irq’? [-Werror=implicit-function-declaration]
  249 |                 handle_domain_irq(intc.domain, hwirq, regs);
      |                 ^~~~~~~~~~~~~~~~~
      |                 handle_bad_irq
drivers/irqchip/irq-bcm2836.c: In function ‘bcm2836_arm_irqchip_handle_irq’:
drivers/irqchip/irq-bcm2836.c:146:17: error: implicit declaration of function ‘handle_domain_irq’; did you mean ‘handle_bad_irq’? [-Werror=implicit-function-declaration]
  146 |                 handle_domain_irq(intc.domain, hwirq, regs);
      |                 ^~~~~~~~~~~~~~~~~
      |                 handle_bad_irq
cc1: some warnings being treated as errors

Signed-off-by: Julio Faracco <jfaracco@redhat.com>