ALSA: core: avoid -Wempty-body warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 940ba1f5e18d4411c4e87ef902dc811a10d341d0

Building with 'make W=1' shows some warnings about empty function-style
macros:

sound/core/pcm_memory.c: In function 'preallocate_pages':
sound/core/pcm_memory.c:236:49: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  236 |                 preallocate_info_init(substream);

sound/core/seq_device.c: In function 'snd_seq_device_dev_register':
sound/core/seq_device.c:163:41: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  163 |                 queue_autoload_drivers();

Change them to empty inline functions, which are more robust here.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20210322103128.547199-1-arnd@kernel.org
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 940ba1f5e18d4411c4e87ef902dc811a10d341d0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>