iommupt: Make pt_feature() always_inline
JIRA: https://issues.redhat.com/browse/RHEL-147902
Upstream-Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 6a3d5fda2ce464a80a9af9e358dfbab6a989ab5d
Author: Jason Gunthorpe <jgg@nvidia.com>
Date: Fri Jan 9 10:29:52 2026 -0400

    iommupt: Make pt_feature() always_inline

    gcc 8.5 on powerpc does not automatically inline these functions even
    though they evaluate to constants in key cases. Since the constant
    propagation is essential for some code elimination and built-time checks
    this causes a build failure:

     ERROR: modpost: "__pt_no_sw_bit" [drivers/iommu/generic_pt/fmt/iommu_amdv1.ko] undefined!

    Caused by this:

	    if (pts_feature(&pts, PT_FEAT_DMA_INCOHERENT) &&
		!pt_test_sw_bit_acquire(&pts,
					SW_BIT_CACHE_FLUSH_DONE))
		    flush_writes_item(&pts);

    Where pts_feature() evaluates to a constant false. Mark them as
    __always_inline to force it to evaluate to a constant and trigger the code
    elimination.

    Fixes: 7c5b184db714 ("genpt: Generic Page Table base API")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202512230720.9y9DtWIo-lkp@intel.com/
    Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

(cherry picked from commit 6a3d5fda2ce464a80a9af9e358dfbab6a989ab5d)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>