perf tools: Fix build break on powerpc
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>
commit 379649cfeafef29b77d29860741f4d1c5870b65f
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-514.el7/379649cf.failed

Commit 531d2410635c ("perf tools: Do not include stringify.h from the
kernel sources") seems to have accidentially removed the inclusion of
"util/header.h" from "arch/powerpc/util/header.c".

"util/header.h" provides the prototype for get_cpuid() and is needed to
build perf on Powerpc:

	arch/powerpc/util/header.c:17:1: error: no previous prototype for 'get_cpuid' [-Werror=missing-prototypes]

	Reported-by: Michael Ellerman <mpe@ellerman.id.au>
	Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
	Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Fixes: 531d2410635c ("perf tools: Do not include stringify.h from the kernel sources")
	Signed-off-by: Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>
[ Included "util.h" too, to get the scnprintf() prototype ]
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 379649cfeafef29b77d29860741f4d1c5870b65f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/perf/arch/powerpc/util/header.c