x86/alternative: Remove noinline from __ibt_endbr_seal[_end]() stubs
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 023e59d4cee91dd3ca811eb01db2c5fb9f783dc2
Author: Miaohe Lin <linmiaohe@huawei.com>
Date:   Tue Oct 11 19:38:03 2022 +0800

    x86/alternative: Remove noinline from __ibt_endbr_seal[_end]() stubs

    Due to the explicit 'noinline' GCC-7.3 is not able to optimize away the
    argument setup of:

            apply_ibt_endbr(__ibt_endbr_seal, __ibt_enbr_seal_end);

    even when X86_KERNEL_IBT=n and the function is an empty stub, which leads
    to link errors due to missing __ibt_endbr_seal* symbols:

    ld: arch/x86/kernel/alternative.o: in function `alternative_instructions':
    alternative.c:(.init.text+0x15d): undefined reference to `__ibt_endbr_seal_end'
    ld: alternative.c:(.init.text+0x164): undefined reference to `__ibt_endbr_seal'

    Remove the explicit 'noinline' to help gcc optimize them away.

    Signed-off-by: Miaohe Lin <linmiaohe@huawei.com>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Link: https://lore.kernel.org/r/20221011113803.956808-1-linmiaohe@huawei.com

Signed-off-by: Prarit Bhargava <prarit@redhat.com>