selftests/bpf: Use pid_t consistently in test_progs.c
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit ec4fe2f0fa12fd2d0115df7e58414dc26899cc5e
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:28 2024 -0700

    selftests/bpf: Use pid_t consistently in test_progs.c

    Use pid_t rather than __pid_t when allocating memory for 'worker_pids' in
    'struct test_env', as this is its declared type and also avoids compile
    errors seen building against musl libc on mipsel64:

      test_progs.c:1738:49: error: '__pid_t' undeclared (first use in this function); did you mean 'pid_t'?
       1738 |                 env.worker_pids = calloc(sizeof(__pid_t), env.workers);
            |                                                 ^~~~~~~
            |                                                 pid_t
      test_progs.c:1738:49: note: each undeclared identifier is reported only once for each function it appears in

    Fixes: 91b2c0afd00c ("selftests/bpf: Add parallelism to test_progs")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Geliang Tang <geliang@kernel.org>
    Link: https://lore.kernel.org/bpf/c6447da51a94babc1931711a43e2ceecb135c93d.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>