selftest: hid: add the missing tests directory
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.11.5
Tested: with the hid-tools test suite and some hardware

commit 460ef7da3db3604d0f0d0288c48847aa389f4151
Author: Yun Lu <luyun@kylinos.cn>
Date:   Tue Oct 15 17:15:20 2024 +0800

    selftest: hid: add the missing tests directory

    commit fe05c40ca9c18cfdb003f639a30fc78a7ab49519 upstream.

    Commit 160c826b4dd0 ("selftest: hid: add missing run-hid-tools-tests.sh")
    has added the run-hid-tools-tests.sh script for it to be installed, but
    I forgot to add the tests directory together.

    If running the test case without the tests directory,  will results in
    the following error message:

        make -C tools/testing/selftests/ TARGETS=hid install \
                INSTALL_PATH=$KSFT_INSTALL_PATH
        cd $KSFT_INSTALL_PATH
        ./run_kselftest.sh -t hid:hid-core.sh

      /usr/lib/python3.11/site-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
      Plugin: helpconfig, Hook: pytest_cmdline_parse
      UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
      __main__.py: error: unrecognized arguments: --udevd
        inifile: None
        rootdir: /root/linux/kselftest_install/hid

    In fact, the run-hid-tools-tests.sh script uses the scripts in the tests
    directory to run tests. The tests directory also needs to be added to be
    installed.

    Fixes: ffb85d5c9e80 ("selftests: hid: import hid-tools hid-core tests")
    Cc: stable@vger.kernel.org
    Signed-off-by: Yun Lu <luyun@kylinos.cn>
    Acked-by: Benjamin Tissoires <bentiss@kernel.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>