net/mlx5e: Use unsigned for mlx5e_get_max_num_channels
JIRA: https://redhat.atlassian.net/browse/RHEL-169055

commit 57a94d4b22b0c6cc5d601e6b6238d78fb923d991
Author: Cosmin Ratiu <cratiu@nvidia.com>
Date:   Wed Feb 18 09:29:04 2026 +0200

    net/mlx5e: Use unsigned for mlx5e_get_max_num_channels

    The max number of channels is always an unsigned int, use the correct
    type to fix compilation errors done with strict type checking, e.g.:

    error: call to ‘__compiletime_assert_1110’ declared with attribute
      error: min(mlx5e_get_devlink_param_num_doorbells(mdev),
      mlx5e_get_max_num_channels(mdev)) signedness error

    Fixes: 74a8dadac17e ("net/mlx5e: Preparations for supporting larger number of channels")
    Signed-off-by: Cosmin Ratiu <cratiu@nvidia.com>
    Reviewed-by: Dragos Tatulea <dtatulea@nvidia.com>
    Signed-off-by: Tariq Toukan <tariqt@nvidia.com>
    Reviewed-by: Jacob Keller <Jacob.e.keller@intel.com>
    Link: https://patch.msgid.link/20260218072904.1764634-7-tariqt@nvidia.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Kamal Heib <kheib@redhat.com>