qed: remove unused num_ooo_add_to_peninsula variable
JIRA: https://issues.redhat.com/browse/RHEL-52263

commit 2bcc74ffd21a748fb310135175a1f6b271397e0f
Author: Tom Rix <trix@redhat.com>
Date:   Sat Mar 25 20:17:33 2023 -0400

    qed: remove unused num_ooo_add_to_peninsula variable

    clang with W=1 reports
    drivers/net/ethernet/qlogic/qed/qed_ll2.c:649:6: error: variable
      'num_ooo_add_to_peninsula' set but not used [-Werror,-Wunused-but-set-variable]
            u32 num_ooo_add_to_peninsula = 0, cid;
                ^
    This variable is not used so remove it.

    Signed-off-by: Tom Rix <trix@redhat.com>
    Reviewed-by: Simon Horman <simon.horman@corigine.com>
    Link: https://lore.kernel.org/r/20230326001733.1343274-1-trix@redhat.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>