scsi: hpsa: select CONFIG_SCSI_SAS_ATTR
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [scsi] hpsa: select CONFIG_SCSI_SAS_ATTR (Joseph Szczypek) [1274467]
Rebuild_FUZZ: 91.67%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 653cfb85fbe73be44fda14bb67f1b95818bfc37f

The hpsa driver recently started using the sas transport class, but it
does not ensure that the corresponding code is actually built, which
may lead to a link error:

drivers/built-in.o: In function `hpsa_free_sas_phy':
(.text+0x1ce874): undefined reference to `sas_port_delete_phy'
(.text+0x1ce87c): undefined reference to `sas_phy_free'
drivers/built-in.o: In function `hpsa_alloc_sas_port':
(.text+0x1ceb9c): undefined reference to `sas_port_alloc_num'
(.text+0x1ceba8): undefined reference to `sas_port_add'
drivers/built-in.o: In function `hpsa_init':
(.init.text+0x8838): undefined reference to `sas_attach_transport'
(.init.text+0x8868): undefined reference to `sas_release_transport

This adds 'select SCSI_SAS_ATTR' in the Kconfig entry, just like we do
for all other drivers using those functions.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: d04e62b9d63a ("hpsa: add in sas transport class")
	Reviewed-by: Christoph Hellwig <hch@lst.de>
	Acked-by: Don Brace <don.brace@pmcs.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 653cfb85fbe73be44fda14bb67f1b95818bfc37f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>