vdpa: fix improper error message when adding vdpa dev
JIRA: https://issues.redhat.com/browse/RHEL-806

commit 275487b4be8969fdb15fd2d47510d358963629d6
Author: Si-Wei Liu <si-wei.liu@oracle.com>
Date:   Mon Feb 6 15:11:59 2023 -0800

    vdpa: fix improper error message when adding vdpa dev

    In below example, before the fix, mtu attribute is supported
    by the parent mgmtdev, but the error message showing "All
    provided are not supported" is just misleading.

    $ vdpa mgmtdev show
    vdpasim_net:
      supported_classes net
      max_supported_vqs 3
      dev_features MTU MAC CTRL_VQ CTRL_MAC_ADDR ANY_LAYOUT VERSION_1 ACCESS_PLATFORM

    $ vdpa dev add mgmtdev vdpasim_net name vdpasim0 mtu 5000 max_vqp 2
    Error: vdpa: All provided attributes are not supported.
    kernel answers: Operation not supported

    After fix, the relevant error message will be like:

    $ vdpa dev add mgmtdev vdpasim_net name vdpasim0 mtu 5000 max_vqp 2
    Error: vdpa: Some provided attributes are not supported: 0x1000.
    kernel answers: Operation not supported

    Fixes: d8ca2fa5be1b ("vdpa: Enable user to set mac and mtu of vdpa device")
    Signed-off-by: Si-Wei Liu <si-wei.liu@oracle.com>
    Reviewed-by: Parav Pandit <parav@nvidia.com>
    Reviewed-by: Eli Cohen <elic@nvidia.com>
    Message-Id: <1675725124-7375-2-git-send-email-si-wei.liu@oracle.com>
    Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

Signed-off-by: Laurent Vivier <lvivier@redhat.com>