selftests/bpf: Fix RELEASE build failure with gcc14
JIRA: https://issues.redhat.com/browse/RHEL-78204

commit a633dab4b4d2f06c0fcb3caa6f110efabdf889f9
Author: Yonghong Song <yonghong.song@linux.dev>
Date:   Mon Jun 16 21:49:56 2025 -0700

    selftests/bpf: Fix RELEASE build failure with gcc14
    
    With gcc14, when building with RELEASE=1, I hit four below compilation
    failure:
    
    Error 1:
      In file included from test_loader.c:6:
      test_loader.c: In function ‘run_subtest’: test_progs.h:194:17:
          error: ‘retval’ may be used uninitialized in this function
       [-Werror=maybe-uninitialized]
        194 |                 fprintf(stdout, ##format);           \
            |                 ^~~~~~~
      test_loader.c:958:13: note: ‘retval’ was declared here
        958 |         int retval, err, i;
            |             ^~~~~~
    
      The uninitialized var 'retval' actually could cause incorrect result.
    
    Error 2:
      In function ‘test_fd_array_cnt’:
      prog_tests/fd_array.c:71:14: error: ‘btf_id’ may be used uninitialized in this
          function [-Werror=maybe-uninitialized]
         71 |         fd = bpf_btf_get_fd_by_id(id);
            |              ^~~~~~~~~~~~~~~~~~~~~~~~
      prog_tests/fd_array.c:302:15: note: ‘btf_id’ was declared here
        302 |         __u32 btf_id;
            |               ^~~~~~
    
      Changing ASSERT_GE to ASSERT_EQ can fix the compilation error. Otherwise,
      there is no functionality change.
    
    Error 3:
      prog_tests/tailcalls.c: In function ‘test_tailcall_hierarchy_count’:
      prog_tests/tailcalls.c:1402:23: error: ‘fentry_data_fd’ may be used uninitialized
          in this function [-Werror=maybe-uninitialized]
         1402 |                 err = bpf_map_lookup_elem(fentry_data_fd, &i, &val);
              |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      The code is correct. The change intends to silence gcc errors.
    
    Error 4: (this error only happens on arm64)
      In file included from prog_tests/log_buf.c:4:
      prog_tests/log_buf.c: In function ‘bpf_prog_load_log_buf’:
      ./test_progs.h:390:22: error: ‘log_buf’ may be used uninitialized [-Werror=maybe-uninitialized]
        390 |         int ___err = libbpf_get_error(___res);             \
            |                      ^~~~~~~~~~~~~~~~~~~~~~~~
      prog_tests/log_buf.c:158:14: note: in expansion of macro ‘ASSERT_OK_PTR’
        158 |         if (!ASSERT_OK_PTR(log_buf, "log_buf_alloc"))
            |              ^~~~~~~~~~~~~
      In file included from selftests/bpf/tools/include/bpf/bpf.h:32,
                     from ./test_progs.h:36:
      selftests/bpf/tools/include/bpf/libbpf_legacy.h:113:17:
        note: by argument 1 of type ‘const void *’ to ‘libbpf_get_error’ declared here
        113 | LIBBPF_API long libbpf_get_error(const void *ptr);
            |                 ^~~~~~~~~~~~~~~~
    
      Adding a pragma to disable maybe-uninitialized fixed the issue.
    
    Signed-off-by: Yonghong Song <yonghong.song@linux.dev>
    Link: https://lore.kernel.org/r/20250617044956.2686668-1-yonghong.song@linux.dev
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>