perf bench: Fix two warnings
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [tools] perf/bench: Fix two warnings (Jiri Olsa) [1131394]
Rebuild_FUZZ: 96.43%
commit-author Wei Yang <weiyang@linux.vnet.ibm.com>
commit 32bf5bd181026fc99c0e15045abe409167285ba8
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-229.el7/32bf5bd1.failed

There are two warnings in bench/numa, when building this on 32-bit
machine.

The warning output is attached:

bench/numa.c:1113:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
bench/numa.c:1161:6: error: format ‘%lx’ expects argument of t'long unsigned int’, but argument 5 has type ‘u64’ [-Werror=format]

This patch fixes these two warnings.

	Signed-off-by: Wei Yang <weiyang@linux.vnet.ibm.com>
	Acked-by: Ingo Molnar <mingo@kernel.org>
	Cc: Ingo Molnar <mingo@redhat.com>
Link: http://lkml.kernel.org/r/1379839764-9245-1-git-send-email-weiyang@linux.vnet.ibm.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 32bf5bd181026fc99c0e15045abe409167285ba8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	tools/perf/bench/numa.c