libbpf: Fix uninitialized warning in btf_dump_dump_type_data
Bugzilla: https://bugzilla.redhat.com/2177177

commit dfd0afbf151d85411b371e841f62b81ee5d1ca54
Author: David Michael <fedora.dm0@gmail.com>
Date:   Sun Nov 13 15:52:17 2022 -0500

    libbpf: Fix uninitialized warning in btf_dump_dump_type_data

    GCC 11.3.0 fails to compile btf_dump.c due to the following error,
    which seems to originate in btf_dump_struct_data where the returned
    value would be uninitialized if btf_vlen returns zero.

    btf_dump.c: In function ‘btf_dump_dump_type_data’:
    btf_dump.c:2363:12: error: ‘err’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     2363 |         if (err < 0)
          |            ^

    Fixes: 920d16af9b42 ("libbpf: BTF dumper support for typed data")
    Signed-off-by: David Michael <fedora.dm0@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Stanislav Fomichev <sdf@google.com>
    Acked-by: Alan Maguire <alan.maguire@oracle.com>
    Link: https://lore.kernel.org/bpf/87zgcu60hq.fsf@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>