RISC-V: Remove unnecessary include from compat.h
JIRA: https://issues.redhat.com/browse/RHEL-101827

commit 8d4f1e05ff821a5d59116ab8c3a30fcae81d8597
Author: Palmer Dabbelt <palmer@rivosinc.com>
Date: Tue, 26 Nov 2024 06:32:50 -0800

    Without this I get a bunch of build errors like

        In file included from ./include/linux/sched/task_stack.h:12,
                         from ./arch/riscv/include/asm/compat.h:12,
                         from ./arch/riscv/include/asm/pgtable.h:115,
                         from ./include/linux/pgtable.h:6,
                         from ./include/linux/mm.h:30,
                         from arch/riscv/kernel/asm-offsets.c:8:
        ./include/linux/kasan.h:50:37: error: ‘MAX_PTRS_PER_PTE’ undeclared here (not in a function); did you mean ‘PTRS_PER_PTE’?
           50 | extern pte_t kasan_early_shadow_pte[MAX_PTRS_PER_PTE + PTE_HWTABLE_PTRS];
              |                                     ^~~~~~~~~~~~~~~~
              |                                     PTRS_PER_PTE
        ./include/linux/kasan.h:51:8: error: unknown type name ‘pmd_t’; did you mean ‘pgd_t’?
           51 | extern pmd_t kasan_early_shadow_pmd[MAX_PTRS_PER_PMD];
              |        ^~~~~
              |        pgd_t
        ./include/linux/kasan.h:51:37: error: ‘MAX_PTRS_PER_PMD’ undeclared here (not in a function); did you mean ‘PTRS_PER_PGD’?
           51 | extern pmd_t kasan_early_shadow_pmd[MAX_PTRS_PER_PMD];
              |                                     ^~~~~~~~~~~~~~~~
              |                                     PTRS_PER_PGD
        ./include/linux/kasan.h:52:8: error: unknown type name ‘pud_t’; did you mean ‘pgd_t’?
           52 | extern pud_t kasan_early_shadow_pud[MAX_PTRS_PER_PUD];
              |        ^~~~~
              |        pgd_t
        ./include/linux/kasan.h:52:37: error: ‘MAX_PTRS_PER_PUD’ undeclared here (not in a function); did you mean ‘PTRS_PER_PGD’?
           52 | extern pud_t kasan_early_shadow_pud[MAX_PTRS_PER_PUD];
              |                                     ^~~~~~~~~~~~~~~~
              |                                     PTRS_PER_PGD
        ./include/linux/kasan.h:53:8: error: unknown type name ‘p4d_t’; did you mean ‘pgd_t’?
           53 | extern p4d_t kasan_early_shadow_p4d[MAX_PTRS_PER_P4D];
              |        ^~~~~
              |        pgd_t
        ./include/linux/kasan.h:53:37: error: ‘MAX_PTRS_PER_P4D’ undeclared here (not in a function); did you mean ‘PTRS_PER_PGD’?
           53 | extern p4d_t kasan_early_shadow_p4d[MAX_PTRS_PER_P4D];
              |                                     ^~~~~~~~~~~~~~~~
              |                                     PTRS_PER_PGD

    Link: https://lore.kernel.org/r/20241126143250.29708-1-palmer@rivosinc.com
    Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>

Signed-off-by: Charles Mirabile <cmirabil@redhat.com>