audit: avoid -Wempty-body warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit d4ceb1d6e732b11d7226ff6d51adf2418bb1f60f

gcc warns about an empty statement when audit_remove_mark is defined to
nothing:

kernel/auditfilter.c: In function 'audit_data_to_entry':
kernel/auditfilter.c:609:51: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  609 |                 audit_remove_mark(entry->rule.exe); /* that's the template one */
      |                                                   ^

Change the macros to use the usual "do { } while (0)" instead, and change a
few more that were (void)0, for consistency.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Richard Guy Briggs <rgb@redhat.com>
	Signed-off-by: Paul Moore <paul@paul-moore.com>
(cherry picked from commit d4ceb1d6e732b11d7226ff6d51adf2418bb1f60f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>