gve: DQO: avoid unused variable warnings
Bugzilla: https://bugzilla.redhat.com/2022916

commit 1e0083bd0777e4a418a6710d9ee04b979cdbe5cc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 28 16:15:13 2021 +0200

    gve: DQO: avoid unused variable warnings

    The use of dma_unmap_addr()/dma_unmap_len() in the driver causes
    multiple warnings when these macros are defined as empty, e.g.
    in an ARCH=i386 allmodconfig build:

    drivers/net/ethernet/google/gve/gve_tx_dqo.c: In function 'gve_tx_add_skb_no_copy_dqo':
    drivers/net/ethernet/google/gve/gve_tx_dqo.c:494:40: error: unused variable 'buf' [-Werror=unused-variable]
      494 |                 struct gve_tx_dma_buf *buf =

    This is not how the NEED_DMA_MAP_STATE macros are meant to work,
    as they rely on never using local variables or a temporary structure
    like gve_tx_dma_buf.

    Remote the gve_tx_dma_buf definition and open-code the contents
    in all places to avoid the warning. This causes some rather long
    lines but otherwise ends up making the driver slightly smaller.

    Fixes: a57e5de476be ("gve: DQO: Add TX path")
    Link: https://lore.kernel.org/netdev/20210723231957.1113800-1-bcf@google.com/
    Link: https://lore.kernel.org/netdev/20210721151100.2042139-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jordan Kimbrough <jokimbro@redhat.com>