kexec_file: Fix kexec_file.c build error for riscv platform
Bugzilla: https://bugzilla.redhat.com/2119002
Upstream Status: Linus's tree
Conflict:
  There's conflict in include/linux/kexec.h because the commit commit
  3e35142ef99f ("kexec_file: drop weak attribute from
  arch_kexec_apply_relocations[_add]") has been back ported earlier.

commit 4853f68d158ac59b05985a6af5b7da7ccdbc14c8
Author: Liao Chang <liaochang1@huawei.com>
Date:   Fri Apr 8 18:09:09 2022 +0800

    kexec_file: Fix kexec_file.c build error for riscv platform

    When CONFIG_KEXEC_FILE is set for riscv platform, the compilation of
    kernel/kexec_file.c generate build error:

    kernel/kexec_file.c: In function 'crash_prepare_elf64_headers':
    ./arch/riscv/include/asm/page.h:110:71: error: request for member 'virt_addr' in something not a structure or union
      110 |  ((x) >= PAGE_OFFSET && (!IS_ENABLED(CONFIG_64BIT) || (x) < kernel_map.virt_addr))
          |                                                                       ^
    ./arch/riscv/include/asm/page.h:131:2: note: in expansion of macro 'is_linear_mapping'
      131 |  is_linear_mapping(_x) ?       \
          |  ^~~~~~~~~~~~~~~~~
    ./arch/riscv/include/asm/page.h:140:31: note: in expansion of macro '__va_to_pa_nodebug'
      140 | #define __phys_addr_symbol(x) __va_to_pa_nodebug(x)
          |                               ^~~~~~~~~~~~~~~~~~
    ./arch/riscv/include/asm/page.h:143:24: note: in expansion of macro '__phys_addr_symbol'
      143 | #define __pa_symbol(x) __phys_addr_symbol(RELOC_HIDE((unsigned long)(x), 0))
          |                        ^~~~~~~~~~~~~~~~~~
    kernel/kexec_file.c:1327:36: note: in expansion of macro '__pa_symbol'
     1327 |   phdr->p_offset = phdr->p_paddr = __pa_symbol(_text);

    This occurs is because the "kernel_map" referenced in macro
    is_linear_mapping()  is suppose to be the one of struct kernel_mapping
    defined in arch/riscv/mm/init.c, but the 2nd argument of
    crash_prepare_elf64_header() has same symbol name, in expansion of macro
    is_linear_mapping in function crash_prepare_elf64_header(), "kernel_map"
    actually is the local variable.

    Signed-off-by: Liao Chang <liaochang1@huawei.com>
    Link: https://lore.kernel.org/r/20220408100914.150110-2-lizhengyu3@huawei.com
    Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>
Signed-off-by: Baoquan He <bhe@redhat.com>