net/sched: act_mpls: Add extack messages for offload failure
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit bca3821d19d9aa05cd8164e4f716150d6ef7e5a5
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:25 2022 +0300

    net/sched: act_mpls: Add extack messages for offload failure

    For better error reporting to user space, add extack messages when mpls
    action offload fails.

    Example:

     # echo 1 > /sys/kernel/tracing/events/netlink/netlink_extack/enable

     # tc filter add dev dummy0 ingress pref 1 proto all matchall skip_sw action mpls dec_ttl
     Error: cls_matchall: Failed to setup flow action.
     We have an error talking to the kernel

     # cat /sys/kernel/tracing/trace_pipe
           tc-182     [000] b..1.    18.693915: netlink_extack: msg=act_mpls: Offload not supported when "dec_ttl" option is used
           tc-182     [000] .....    18.693921: netlink_extack: msg=cls_matchall: Failed to setup flow action

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>