igc: Fix static checker warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Sasha Neftin <sasha.neftin@intel.com>
commit 360d749e0c8e689414d9a583102a59f795a6892d

drivers/net/ethernet/intel/igc/igc_mac.c:424 igc_check_for_copper_link()
error: uninitialized symbol 'link'.
This patch come to fix this warning and initialize the 'link' symbol.

	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Fixes: 707abf069548 ("igc: Add initial LTR support")
	Signed-off-by: Sasha Neftin <sasha.neftin@intel.com>
	Tested-by: Aaron Brown <aaron.f.brown@intel.com>
	Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
(cherry picked from commit 360d749e0c8e689414d9a583102a59f795a6892d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>