PCI: Drop of_match_ptr() to avoid unused variables
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2166398
Upstream Status: 8610e98f0b48a7f9974cb12c5f501433c4afa958

commit 8610e98f0b48a7f9974cb12c5f501433c4afa958
Author: Bjorn Helgaas <bhelgaas@google.com>
Date:   Wed Nov 16 14:50:59 2022 -0600

    PCI: Drop of_match_ptr() to avoid unused variables

    We have stubs for most OF interfaces even when CONFIG_OF is not set, so we
    allow building of most controller drivers in that case for compile testing.

    When CONFIG_OF is not set, "of_match_ptr(<match_table>)" compiles to NULL,
    which leaves <match_table> unused, resulting in errors like this:

      $ make W=1
      drivers/pci/controller/pci-xgene.c:636:34: error: ‘xgene_pcie_match_table’ defined but not used [-Werror=unused-const-variable=]

    Drop of_match_ptr() to avoid the unused variable warning.

    See also 1dff012f636d ("PCI: Drop of_match_ptr() to avoid unused
    variables").

    Link: https://lore.kernel.org/r/20221025191339.667614-2-helgaas@kernel.org
    Link: https://lore.kernel.org/r/20221116205100.1136224-2-helgaas@kernel.org
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>