perf report: Use parse_options_usage() for -s option failure
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [tools] perf/report: Use parse_options_usage() for -s option failure (Jiri Olsa) [1131394]
Rebuild_FUZZ: 98.33%
commit-author Namhyung Kim <namhyung.kim@lge.com>
commit 91aba0a62e24ff7a567e13e1d88deab711df6f0f

The -s (--sort) option was processed after normal option parsing so that
it cannot call the parse_options_usage() automatically.  Currently it
calls usage_with_options() which shows entire help messages for event
option.  Fix it by showing just -s options.

  $ perf report -s help
    Error: Unknown --sort key: `help'

   usage: perf report [<options>]

      -s, --sort <key[,key2...]>
                            sort by key(s): pid, comm, dso, symbol, ...

	Signed-off-by: Namhyung Kim <namhyung@kernel.org>
	Acked-by: Ingo Molnar <mingo@kernel.org>
	Reviewed-by: Ingo Molnar <mingo@kernel.org>
Enthusiastically-Supported-by: Ingo Molnar <mingo@kernel.org>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Ingo Molnar <mingo@kernel.org>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: http://lkml.kernel.org/r/1383291195-24386-4-git-send-email-namhyung@kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 91aba0a62e24ff7a567e13e1d88deab711df6f0f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>