ASoC: Intel: Skylake: Re-order some code to silence a warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: skylake: Re-order some code to silence a warning (Jaroslav Kysela) [1535427]
Rebuild_FUZZ: 95.31%
commit-author Dan Carpenter <dan.carpenter@oracle.com>
commit 87684d338a22d15e47b16ee68f569d74ad1d076e

I get a Smatch warning here:

    sound/soc/intel/skylake/skl-nhlt.c:335 skl_get_ssp_clks()
    error: testing array offset 'j' after use.

The code is harmless, but the checker is right that we should swap these
two conditions so we verify that the offset is within bounds before we
use it.

	Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
	Reviewed-by: Sriram Periyasamy <sriramx.periyasamy@intel.com>
Acked-By: Vinod Koul <vinod.koul@intel.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 87684d338a22d15e47b16ee68f569d74ad1d076e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>