perf python: Stop using deprecated PyUnicode_AsString()
JIRA: https://issues.redhat.com/browse/RHEL-78200

upstream
========
commit 59edbec7a5c70af6c0058e32eb3750bfb8928d7b
Author: Arnaldo Carvalho de Melo <acme@kernel.org>
Date: Wed Jul 30 10:34:20 2025 -0300

description
===========
As noticed while building for Fedora 43:

    GEN     /tmp/build/perf/python/perf.cpython-314-x86_64-linux-gnu.so
  /git/perf-6.16.0-rc3/tools/perf/util/python.c: In function ‘get_tracepoint_field’:
  /git/perf-6.16.0-rc3/tools/perf/util/python.c:340:9: error: ‘_PyUnicode_AsString’ is deprecated [-Werror=deprecated-declarations]
    340 |         const char *str = _PyUnicode_AsString(PyObject_Str(attr_name));
        |         ^~~~~
  In file included from /usr/include/python3.14/unicodeobject.h:1022,
                   from /usr/include/python3.14/Python.h:89,
                   from /git/perf-6.16.0-rc3/tools/perf/util/python.c:2:
  /usr/include/python3.14/cpython/unicodeobject.h:648:1: note: declared here
    648 | _PyUnicode_AsString(PyObject *unicode)
        | ^~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  error: command '/usr/bin/gcc' failed with exit code 1

Use PyUnicode_AsUTF8() instead and also check if PyObject_Str() fails
before doing so.

    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Link: https://lore.kernel.org/r/aIofXNK8QLtLIaI3@x1
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Anubhav Shelat <ashelat@redhat.com>