dm writecache: remove BUG() and fail gracefully instead
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Mike Snitzer <snitzer@redhat.com>
commit 857c4c0a8b2888d806f4308c58f59a6a81a1dee9

Building on arch/s390/ results in this build error:

cc1: some warnings being treated as errors
../drivers/md/dm-writecache.c: In function 'persistent_memory_claim':
../drivers/md/dm-writecache.c:323:1: error: no return statement in function returning non-void [-Werror=return-type]

Fix this by replacing the BUG() with an -EOPNOTSUPP return.

Fixes: 48debafe4f2f ("dm: add writecache target")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Mike Snitzer <snitzer@redhat.com>
(cherry picked from commit 857c4c0a8b2888d806f4308c58f59a6a81a1dee9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>