mmc: MMC_USDHI6ROL0 should depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [mmc] MMC_USDHI6ROL0 should depend on HAS_DMA (Don Zickus) [1127975 1277866 1280133 1286932 1297039]
Rebuild_FUZZ: 93.98%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 1ef94740483da84fd7de0b52442514cf6bf8c2e8

If NO_DMA=y:

    drivers/built-in.o: In function `usdhi6_dma_setup':
    usdhi6rol0.c:(.text+0x5c35fc): undefined reference to `dma_map_sg'
    drivers/built-in.o: In function `usdhi6_dma_stop_unmap':
    usdhi6rol0.c:(.text+0x5c3738): undefined reference to `dma_unmap_sg'

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
(cherry picked from commit 1ef94740483da84fd7de0b52442514cf6bf8c2e8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>