thermal: int340x: Limit Kconfig to 64-bit
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-394.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 994a04a20b03128838ec0250a0e266aab24d23f1

32-bit processors cannot generally access 64-bit MMIO registers
atomically, and it is unknown in which order the two halves of
this registers would need to be read:

drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c: In function 'send_mbox_cmd':
drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c:79:37: error: implicit declaration of function 'readq'; did you mean 'readl'? [-Werror=implicit-function-declaration]
   79 |                         *cmd_resp = readq((void __iomem *) (proc_priv->mmio_base + MBOX_OFFSET_DATA));
      |                                     ^~~~~
      |                                     readl

The driver already does not build for anything other than x86,
so limit it further to x86-64.

Fixes: aeb58c860dc5 ("thermal/drivers/int340x: processor_thermal: Suppot 64 bit RFIM responses")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
	Reviewed-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 994a04a20b03128838ec0250a0e266aab24d23f1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>