powerpc/47x: Add prototype for mmu_init_secondary()
JIRA: https://issues.redhat.com/browse/RHEL-55462

This patch is a backport of the following upstream commit:
commit b27c1a0a4e62af1fd9d2688bf8156a5d546e4227
Author: Christophe Leroy <christophe.leroy@csgroup.eu>
Date:   Thu Aug 17 16:25:49 2023 +0200

    powerpc/47x: Add prototype for mmu_init_secondary()

    A W=1 build of 44x/iss476-smp_defconfig gives:

    arch/powerpc/mm/nohash/44x.c:220:13: error: no previous prototype for 'mmu_init_secondary' [-Werror=missing-prototypes]
      220 | void __init mmu_init_secondary(int cpu)
          |             ^~~~~~~~~~~~~~~~~~

    That function is called from head_4xx.S

    Add a prototype in mmu_decl.h

    Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://msgid.link/e89d9927c926044e54fd056a849785f526c6414f.1692282340.git.christophe.leroy@csgroup.eu

Signed-off-by: Audra Mitchell <audra@redhat.com>