arch, crash: move arch_crash_save_vmcoreinfo() out to file vmcore_info.c
JIRA: https://issues.redhat.com/browse/RHEL-58641

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

Conflicts: Discard SuperH related changes to avoid conflict.

commit 199da8714c8f4c45f46509c5eb188f5551404574
Author: Baoquan He <bhe@redhat.com>
Date:   Mon Jan 29 21:50:33 2024 +0800

    arch, crash: move arch_crash_save_vmcoreinfo() out to file vmcore_info.c

    Nathan reported below building error:

    =====
    $ curl -LSso .config https://git.alpinelinux.org/aports/plain/community/linux-edge/config-edge.armv7
    $ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- olddefconfig all
    ..
    arm-linux-gnueabi-ld: arch/arm/kernel/machine_kexec.o: in function `arch_crash_save_vmcoreinfo':
    machine_kexec.c:(.text+0x488): undefined reference to `vmcoreinfo_append_str'
    ====

    On architecutres, like arm, s390, ppc, sh, function
    arch_crash_save_vmcoreinfo() is located in machine_kexec.c and it can
    only be compiled in when CONFIG_KEXEC_CORE=y.

    That's not right because arch_crash_save_vmcoreinfo() is used to export
    arch specific vmcoreinfo. CONFIG_VMCORE_INFO is supposed to control its
    compiling in. However, CONFIG_VMVCORE_INFO could be independent of
    CONFIG_KEXEC_CORE, e.g CONFIG_PROC_KCORE=y will select CONFIG_VMVCORE_INFO.
    Or CONFIG_KEXEC/CONFIG_KEXEC_FILE is set while CONFIG_CRASH_DUMP is
    not set, it will report linking error.

    So, on arm, s390, ppc and sh, move arch_crash_save_vmcoreinfo out to
    a new file vmcore_info.c. Let CONFIG_VMCORE_INFO decide if compiling in
    arch_crash_save_vmcoreinfo().

    [akpm@linux-foundation.org: remove stray newlines at eof]
    Link: https://lkml.kernel.org/r/20240129135033.157195-3-bhe@redhat.com
    Signed-off-by: Baoquan He <bhe@redhat.com>
    Reported-by: Nathan Chancellor <nathan@kernel.org>
    Closes: https://lore.kernel.org/all/20240126045551.GA126645@dev-arch.thelio-3990X/T/#u
    Cc: Al Viro <viro@zeniv.linux.org.uk>
    Cc: Eric W. Biederman <ebiederm@xmission.com>
    Cc: Hari Bathini <hbathini@linux.ibm.com>
    Cc: Klara Modin <klarasmodin@gmail.com>
    Cc: Michael Kelley <mhklinux@outlook.com>
    Cc: Pingfan Liu <piliu@redhat.com>
    Cc: Stephen Rothwell <sfr@canb.auug.org.au>
    Cc: Yang Li <yang.lee@linux.alibaba.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Baoquan He <bhe@redhat.com>