powerpc/pseries: Add empty update_numa_cpu_lookup_table() for NUMA=n
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [powerpc] pseries: Add empty update_numa_cpu_lookup_table() for NUMA=n (Gustavo Duarte) [1544437]
Rebuild_FUZZ: 93.75%
commit-author Corentin Labbe <clabbe@baylibre.com>
commit c1e150ceb61e4a585bad156da15c33bfe89f5858
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-957.el7/c1e150ce.failed

When CONFIG_NUMA is not set, the build fails with:

  arch/powerpc/platforms/pseries/hotplug-cpu.c:335:4:
  error: déclaration implicite de la fonction « update_numa_cpu_lookup_table »

So we have to add update_numa_cpu_lookup_table() as an empty function
when CONFIG_NUMA is not set.

Fixes: 1d9a090783be ("powerpc/numa: Invalidate numa_cpu_lookup_table on cpu remove")
	Signed-off-by: Corentin Labbe <clabbe@baylibre.com>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit c1e150ceb61e4a585bad156da15c33bfe89f5858)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/include/asm/topology.h