octeontx2-af: fix array bound error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2040643

commit 5f7dc7d48c9402dacc009e163ae7e342556ffbc4
Author: Hariprasad Kelam <hkelam@marvell.com>
Date:   Fri Feb 11 21:25:39 2022 +0530

    octeontx2-af: fix array bound error

    This patch fixes below error by using proper data type.

    drivers/net/ethernet/marvell/octeontx2/af/rpm.c: In function
    'rpm_cfg_pfc_quanta_thresh':
    include/linux/find.h:40:23: error: array subscript 'long unsigned
    int[0]' is partly outside array bounds of 'u16[1]' {aka 'short unsigned
    int[1]'} [-Werror=array-bounds]
       40 |                 val = *addr & GENMASK(size - 1, offset);

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Hariprasad Kelam <hkelam@marvell.com>
    Link: https://lore.kernel.org/r/20220211155539.13931-1-hkelam@marvell.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>