ASoC: Intel: Skylake: fix uninitialized pointer use
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
Rebuild_CHGLOG: - [sound] alsa: asoc: intel: skylake: fix uninitialized pointer use (Jaroslav Kysela) [1463624]
Rebuild_FUZZ: 94.44%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 351d74e4d7eacaab2ed0092b855355d5e2907117

The error handling in bxt_sst_dsp_init() got changed in a way that
it now derefences an uninitialized pointer when printing a warning
about the device not being found:

sound/soc/intel/skylake/bxt-sst.c: In function 'bxt_sst_dsp_init':
sound/soc/intel/skylake/bxt-sst.c:567:14: error: 'skl' may be used uninitialized in this function [-Werror=maybe-uninitialized]

As we do have a valid device pointer available at the call site,
let's use that instead.

Fixes: 9fe9c7119283 ("ASoC: Intel: Skylake: Move sst common initialization to a helper function")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 351d74e4d7eacaab2ed0092b855355d5e2907117)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>