iio: common: hid-sensors: use tab for indention
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author Slawomir Stepien <sst@poczta.fm>
commit d23057e0cadc465911968a4d3f8b0b556f545b6e
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-862.el7/d23057e0.failed

This fixes the error reported by checkpatch.pl:

ERROR: code indent should use tabs where possible

	Signed-off-by: Slawomir Stepien <sst@poczta.fm>
	Signed-off-by: Jonathan Cameron <jic23@kernel.org>
(cherry picked from commit d23057e0cadc465911968a4d3f8b0b556f545b6e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/iio/common/hid-sensors/hid-sensor-trigger.c