soc: qcom: Select REMAP_MMIO for ICC_BWMON driver
Bugzilla: https://bugzilla.redhat.com/2158216

commit a84160fbf4f2c8c5ffa588e19ea8f92eabd7ad17
Author: Manivannan Sadhasivam <mani@kernel.org>
Date:   Tue Nov 29 12:50:22 2022 +0530

    soc: qcom: Select REMAP_MMIO for ICC_BWMON driver

    ICC_BWMON driver uses REGMAP_MMIO for accessing the hardware registers.
    So select the dependency in Kconfig. Without this, there will be errors
    while building the driver with COMPILE_TEST only:

    ERROR: modpost: "__devm_regmap_init_mmio_clk" [drivers/soc/qcom/icc-bwmon.ko] undefined!
    make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
    make: *** [Makefile:1944: modpost] Error 2

    Cc: <stable@vger.kernel.org> # 6.0
    Cc: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Fixes: b9c2ae6cac40 ("soc: qcom: icc-bwmon: Add bandwidth monitoring driver")
    Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
    Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: Bjorn Andersson <andersson@kernel.org>
    Link: https://lore.kernel.org/r/20221129072022.41962-1-manivannan.sadhasivam@linaro.org

Signed-off-by: Brian Masney <bmasney@redhat.com>