objtool: Fix failure when being compiled on x32 system
JIRA: https://issues.redhat.com/browse/RHEL-114916

commit 49c98f30f4021b560676a336f8a46a4f642eee2b
Author: Mikulas Patocka <mpatocka@redhat.com>
Date:   Mon Oct 20 14:23:58 2025 +0200

    objtool: Fix failure when being compiled on x32 system

    Fix compilation failure when compiling the kernel with the x32 toolchain.

    In file included from check.c:16:
    check.c: In function ¡check_abs_references¢:
    /usr/src/git/linux-2.6/tools/objtool/include/objtool/warn.h:47:17: error: format ¡%lx¢ expects argument of type ¡long unsigned int¢, but argument 7 has type ¡u64¢ {aka ¡long
    long unsigned int¢} [-Werror=format=]
       47 |                 "%s%s%s: objtool" extra ": " format "\n",               \
          |                 ^~~~~~~~~~~~~~~~~
    /usr/src/git/linux-2.6/tools/objtool/include/objtool/warn.h:54:9: note: in expansion of macro ¡___WARN¢
       54 |         ___WARN(severity, "", format, ##__VA_ARGS__)
          |         ^~~~~~~
    /usr/src/git/linux-2.6/tools/objtool/include/objtool/warn.h:74:27: note: in expansion of macro ¡__WARN¢
       74 | #define WARN(format, ...) __WARN(WARN_STR, format, ##__VA_ARGS__)
          |                           ^~~~~~
    check.c:4713:33: note: in expansion of macro ¡WARN¢
     4713 |                                 WARN("section %s has absolute relocation at offset 0x%lx",
          |                                 ^~~~

    Fixes: 0d6e4563fc03 ("objtool: Add action to check for absence of absolute relocations")
    Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://patch.msgid.link/1ac32fff-2e67-5155-f570-69aad5bf5412@redhat.com

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>