tpm/tpm_tis: Add missing ifdef CONFIG_ACPI for pnp_acpi_device
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
commit-author Peter Huewe <peterhuewe@gmx.de>
commit 961be7ef6963806cb978ccd6acf6bf84b0c63346
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-327.el7/961be7ef.failed

This fixes a build failure if CONFIG_PNP is set but CONFIG_ACPI is not:
drivers/char/tpm/tpm_tis.c: In function ?tpm_tis_pnp_init?:
drivers/char/tpm/tpm_tis.c:912:45: error: invalid type argument of
?->? (have ?int?)
   acpi_dev_handle = pnp_acpi_device(pnp_dev)->handle;

If CONFIG_PNPACPI is not set pnp_acpi_device is defined as 0 and thus
accesing the handle is not possible.

Fixes: 0dc553652102 ("tpm: fix raciness of PPI interface lookup")
	Reported-by: Jim Davis <jim.epost@gmail.com>
	Signed-off-by: Peter Huewe <peterhuewe@gmx.de>
	Signed-off-by: James Morris <james.l.morris@oracle.com>
(cherry picked from commit 961be7ef6963806cb978ccd6acf6bf84b0c63346)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/char/tpm/tpm_tis.c