lib/ubsan.c: don't mark __ubsan_handle_builtin_unreachable as noreturn
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 1c23b4108d716cc848b38532063a8aca4f86add8

gcc-8 complains about the prototype for this function:

  lib/ubsan.c:432:1: error: ignoring attribute 'noreturn' in declaration of a built-in function '__ubsan_handle_builtin_unreachable' because it conflicts with attribute 'const' [-Werror=attributes]

This is actually a GCC's bug. In GCC internals
__ubsan_handle_builtin_unreachable() declared with both 'noreturn' and
'const' attributes instead of only 'noreturn':

   https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84210

Workaround this by removing the noreturn attribute.

[aryabinin: add information about GCC bug in changelog]
Link: http://lkml.kernel.org/r/20181107144516.4587-1-aryabinin@virtuozzo.com
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>
	Acked-by: Olof Johansson <olof@lixom.net>
	Cc: <stable@vger.kernel.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 1c23b4108d716cc848b38532063a8aca4f86add8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>