net/mlx5e: Fix build break when CONFIG_XPS is not set
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Saeed Mahameed <saeedm@mellanox.com>
commit 8b5ec43d73dbdb427651caac5b76610ec0f5f298
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/8b5ec43d.failed

mlx5e_accel_sk_get_rxq is only used in ktls_rx.c file which already
depends on XPS to be compiled, move it from the generic en_accel.h
header to be local in ktls_rx.c, to fix the below build break

In file included from
../drivers/net/ethernet/mellanox/mlx5/core/en_main.c:49:0:
../drivers/net/ethernet/mellanox/mlx5/core/en_accel/en_accel.h:
In function ‘mlx5e_accel_sk_get_rxq’:
../drivers/net/ethernet/mellanox/mlx5/core/en_accel/en_accel.h:153:12:
error: implicit declaration of function ‘sk_rx_queue_get’ ...
  int rxq = sk_rx_queue_get(sk);
            ^~~~~~~~~~~~~~~

Fixes: 1182f3659357 ("net/mlx5e: kTLS, Add kTLS RX HW offload support")
	Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
(cherry picked from commit 8b5ec43d73dbdb427651caac5b76610ec0f5f298)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/net/ethernet/mellanox/mlx5/core/en_accel/en_accel.h
#	drivers/net/ethernet/mellanox/mlx5/core/en_accel/ktls_rx.c