md/raid5: Increase r5conf.cache_name size
JIRA: https://issues.redhat.com/browse/RHEL-73721

commit ea90d270349d51086d0dddc55821a782040d68f5
Author: John Garry <john.g.garry@oracle.com>
Date:   Tue Nov 12 16:10:18 2024 +0000

    md/raid5: Increase r5conf.cache_name size

    For compiling with W=1, the following warning can be seen:

    drivers/md/raid5.c: In function ‘setup_conf’:
    drivers/md/raid5.c:2423:12: error: ‘%s’ directive output may be truncated writing up to 31 bytes into a region of size between 16 and 26 [-Werror=format-truncation=]
        "raid%d-%s", conf->level, mdname(conf->mddev));
                ^~
    drivers/md/raid5.c:2422:3: note: ‘snprintf’ output between 7 and 48 bytes into a destination of size 32
       snprintf(conf->cache_name[0], namelen,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        "raid%d-%s", conf->level, mdname(conf->mddev));
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    Increase the array size to avoid this warning.

    Signed-off-by: John Garry <john.g.garry@oracle.com>
    Link: https://lore.kernel.org/r/20241112161019.4154616-2-john.g.garry@oracle.com
    Signed-off-by: Song Liu <song@kernel.org>

Signed-off-by: Nigel Croxon <ncroxon@redhat.com>