PCI: mt7621: Fix string truncation in mt7621_pcie_parse_port()
JIRA: https://issues.redhat.com/browse/RHEL-50255
Upstream Status: fd6eb49a84a85150d5e9ffbd85d3b102303f9470

commit fd6eb49a84a85150d5e9ffbd85d3b102303f9470
Author: Sergio Paracuellos <sergio.paracuellos@gmail.com>
Date:   Thu Jan 11 09:27:04 2024 +0100

    PCI: mt7621: Fix string truncation in mt7621_pcie_parse_port()

    The following warning appears when driver is compiled with W=1.

    CC      drivers/pci/controller/pcie-mt7621.o
    drivers/pci/controller/pcie-mt7621.c: In function ‘mt7621_pcie_probe’:
    drivers/pci/controller/pcie-mt7621.c:228:49: error: ‘snprintf’ output may
    be truncated before the last format character [-Werror=format-truncation=]
    228 |         snprintf(name, sizeof(name), "pcie-phy%d", slot);
        |                                                 ^
    drivers/pci/controller/pcie-mt7621.c:228:9: note: ‘snprintf’ output between
    10 and 11 bytes into a destination of size 10
    228 |         snprintf(name, sizeof(name), "pcie-phy%d", slot);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Clean this up increasing destination buffer one byte.

    [kwilczynski: commit log]
    Closes: https://lore.kernel.org/linux-pci/20240110212302.GA2123146@bhelgaas/T/#t
    Link: https://lore.kernel.org/linux-pci/20240111082704.2259450-1-sergio.paracuellos@gmail.com
    Reported-by: Bjorn Helgaas <helgaas@kernel.org>
    Signed-off-by: Sergio Paracuellos <sergio.paracuellos@gmail.com>
    Signed-off-by: Krzysztof Wilczyński <kwilczynski@kernel.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>