mm/kasan/common.c: fix compile error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author zhong jiang <zhongjiang@huawei.com>
commit 2e7d31704c7fe9141b0b27ec1ece254d9993fe2d
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/2e7d3170.failed

I hit the following compile error in arch/x86/

   mm/kasan/common.c: In function kasan_populate_vmalloc:
   mm/kasan/common.c:797:2: error: implicit declaration of function flush_cache_vmap; did you mean flush_rcu_work? [-Werror=implicit-function-declaration]
     flush_cache_vmap(shadow_start, shadow_end);
     ^~~~~~~~~~~~~~~~
     flush_rcu_work
   cc1: some warnings being treated as errors

Link: http://lkml.kernel.org/r/1575363013-43761-1-git-send-email-zhongjiang@huawei.com
Fixes: 3c5c3cfb9ef4 ("kasan: support backing vmalloc space with real shadow memory")
	Signed-off-by: zhong jiang <zhongjiang@huawei.com>
	Reviewed-by: Andrew Morton <akpm@linux-foundation.org>
	Reviewed-by: Daniel Axtens <dja@axtens.net>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Mark Rutland <mark.rutland@arm.com>
	Cc: Vasily Gorbik <gor@linux.ibm.com>
	Cc: Andrey Ryabinin <aryabinin@virtuozzo.com>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 2e7d31704c7fe9141b0b27ec1ece254d9993fe2d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	mm/kasan/common.c