selftests: kvm: move declaration at the beginning of main()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2177720

commit 50aa870ba2f7735f556e52d15f61cd0f359c4c0b
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Sun Jan 22 04:04:50 2023 -0500

    selftests: kvm: move declaration at the beginning of main()

    Placing a declaration of evt_reset is pedantically invalid
    according to the C standard.  While GCC does not really care
    and only warns with -Wpedantic, clang ignores the declaration
    altogether with an error:

    x86_64/xen_shinfo_test.c:965:2: error: expected expression
            struct kvm_xen_hvm_attr evt_reset = {
            ^
    x86_64/xen_shinfo_test.c:969:38: error: use of undeclared identifier evt_reset
            vm_ioctl(vm, KVM_XEN_HVM_SET_ATTR, &evt_reset);
                                                ^

    Reported-by: Yu Zhang <yu.c.zhang@linux.intel.com>
    Reported-by: Sean Christopherson <seanjc@google.com>
    Fixes: a79b53aaaab5 ("KVM: x86: fix deadlock for KVM_XEN_EVTCHN_RESET", 2022-12-28)
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Maxim Levitsky <mlevitsk@redhat.com>