ASoC: ti: fix davinci_mcasp_probe dependencies
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: ti: fix davinci_mcasp_probe dependencies (Jaroslav Kysela) [1683051]
Rebuild_FUZZ: 93.88%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 7d7b25d05ef1c5a1a9320190e1eeb55534847558

The SND_SOC_DAVINCI_MCASP driver can use either edma or sdma as
a back-end, and it takes the presence of the respective dma engine
drivers in the configuration as an indication to which ones should be
built. However, this is flawed in multiple ways:

- With CONFIG_TI_EDMA=m and CONFIG_SND_SOC_DAVINCI_MCASP=y,
  is enabled as =m, and we get a link error:
  sound/soc/ti/davinci-mcasp.o: In function `davinci_mcasp_probe':
  davinci-mcasp.c:(.text+0x930): undefined reference to `edma_pcm_platform_register'

- When CONFIG_SND_SOC_DAVINCI_MCASP=m has already been selected by
  another driver, the same link error appears even if CONFIG_TI_EDMA
  is disabled

There are possibly other issues here, but it seems that the only reasonable
solution is to always build both SND_SOC_TI_EDMA_PCM and
SND_SOC_TI_SDMA_PCM as a dependency here. Both are fairly small and
do not have any other compile-time dependencies, so the cost is
very small, and makes the configuration stage much more consistent.

Fixes: f2055e145f29 ("ASoC: ti: Merge davinci and omap directories")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 7d7b25d05ef1c5a1a9320190e1eeb55534847558)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>