ASoC: codecs: rt1019: Mark OF related data as maybe unused
Bugzilla: https://bugzilla.redhat.com/2179848

commit 0e8599a35823f05e90513918ff1201f8d210e315
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Fri Mar 10 22:43:31 2023 +0100

    ASoC: codecs: rt1019: Mark OF related data as maybe unused

    The driver can be compile tested with !CONFIG_OF making certain data
    unused:

      sound/soc/codecs/rt1019.c:549:34: error: ‘rt1019_of_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230310214333.274903-8-krzysztof.kozlowski@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>