s390/uaccess: fix compile error
Bugzilla: http://bugzilla.redhat.com/2044357

commit 3d787b392d169d4a2e3aee6ac6dfd6ec39722cf2
Author: Heiko Carstens <hca@linux.ibm.com>
Date:   Sat Jan 22 10:24:31 2022 +0100

    s390/uaccess: fix compile error

    Compiling with e.g MARCH=z900 results in compile errors:

       arch/s390/lib/uaccess.c: In function 'copy_from_user_mvcos':
    >> arch/s390/lib/uaccess.c:65:15: error: variable 'spec' has initializer but incomplete type
          65 |         union oac spec = {

    Therefore make definition of union oac visible for all MARCHs.

    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Nico Boehr <nrb@linux.ibm.com>
    Cc: Janis Schoetterl-Glausch <scgl@linux.ibm.com>
    Fixes: 012a224e1fa3 ("s390/uaccess: introduce bit field for OAC specifier")
    Signed-off-by: Heiko Carstens <hca@linux.ibm.com>

Signed-off-by: Thomas Huth <thuth@redhat.com>