wifi: mt76: mt7996: fix uninitialized symbol warning
JIRA: https://issues.redhat.com/browse/RHEL-122256

commit 187de25110c8ac8d52e24f8c596ebdcbcd55bbbf
Author: sunliming <sunliming@kylinos.cn>
Date:   Sat Apr 19 11:15:28 2025 +0800

    wifi: mt76: mt7996: fix uninitialized symbol warning
    
    Fix below smatch warnings:
    drivers/net/wireless/mediatek/mt76/mt7996/main.c:952 mt7996_mac_sta_add_links()
    error: uninitialized symbol 'err'.
    drivers/net/wireless/mediatek/mt76/mt7996/main.c:1133 mt7996_set_rts_threshold()
    error: uninitialized symbol 'ret'.
    
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Dan Carpenter <error27@gmail.com>
    Closes: https://lore.kernel.org/r/202504101051.1ya4Z4va-lkp@intel.com/
    Signed-off-by: sunliming <sunliming@kylinos.cn>
    Link: https://patch.msgid.link/20250419031528.2073892-1-sunliming@linux.dev
    Signed-off-by: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>