rtnl: allocate more attr tables on the heap
jira KERNEL-1421
cve CVE-2026-31692
Rebuild_History Non-Buildable kernel-4.18.0-553.150.1.el8_10
commit-author Jakub Kicinski <kuba@kernel.org>
commit c92bf26ccebc8501863b38c4a4f65b8fef28ce5e

Commit a293974590cf ("rtnetlink: avoid frame size warning in rtnl_newlink()")
moved to allocating the largest attribute array of rtnl_newlink()
on the heap. Kalle reports the stack has grown above 1k again:

  net/core/rtnetlink.c:3557:1: error: the frame size of 1104 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Move more attrs to the heap, wrap them in a struct.
Don't bother with linkinfo, it's referenced a lot and we take
its size so it's awkward to move, plus it's small (6 elements).

	Reported-by: Kalle Valo <kvalo@kernel.org>
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
	Tested-by: Kalle Valo <kvalo@kernel.org>
	Signed-off-by: Paolo Abeni <pabeni@redhat.com>
(cherry picked from commit c92bf26ccebc8501863b38c4a4f65b8fef28ce5e)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>