usb/usbip: Fix v_recv_cmd_submit() to use PIPE_BULK define
JIRA: https://issues.redhat.com/browse/RHEL-56984

commit dd65a243a915ca319ed5fee9161a168c836fa2f2
Author: Shuah Khan <skhan@linuxfoundation.org>
Date:   Thu Nov 10 12:47:38 2022 -0700

    usb/usbip: Fix v_recv_cmd_submit() to use PIPE_BULK define
    
    Fix v_recv_cmd_submit() to use PIPE_BULK define instead of hard coded
    values. This also fixes the following signed integer overflow error
    reported by cppcheck. This is not an issue since pipe is unsigned int.
    However, this change improves the code to use proper define.
    
    drivers/usb/usbip/vudc_rx.c:152:26: error: Signed integer overflow for expression '3<<30'. [integerOverflow]
     urb_p->urb->pipe &= ~(3 << 30);
    
    In addition, add a build time check for PIPE_BULK != 3 as the code path
    depends on PIPE_BULK = 3.
    
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
    Link: https://lore.kernel.org/r/20221110194738.38514-1-skhan@linuxfoundation.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>