HID: nvidia-shield: add LEDS_CLASS dependency
JIRA: https://issues.redhat.com/browse/RHEL-1259
Upstream Status: since Not upstream
Tested: with the hid-tools test suite and some hardware

commit 058574879853260a22bbec1f94221dfc5149d85c
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Sep 13 17:05:17 2023 -0700

    HID: nvidia-shield: add LEDS_CLASS dependency

    The hid-nvidia-shield driver uses functions that are built
    only when LEDS_CLASS is set, so make the driver depend on that
    symbol to prevent build errors.

    riscv32-linux-ld: drivers/hid/hid-nvidia-shield.o: in function `.L11':
    hid-nvidia-shield.c:(.text+0x192): undefined reference to `led_classdev_unregister'
    riscv32-linux-ld: drivers/hid/hid-nvidia-shield.o: in function `.L113':
    hid-nvidia-shield.c:(.text+0xfa4): undefined reference to `led_classdev_register_ext'

    Fixes: 09308562d4af ("HID: nvidia-shield: Initial driver implementation with Thunderstrike support")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Rahul Rameshbabu <rrameshbabu@nvidia.com>
    Cc: Jiri Kosina <jkosina@suse.cz>
    Cc: Benjamin Tissoires <benjamin.tissoires@redhat.com>
    Cc: linux-input@vger.kernel.org
    Reviewed-by: Rahul Rameshbabu <rrameshbabu@nvidia.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>