rtc: sunplus: fix format string for printing resource
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2183349

commit 08279468a294d8c996a657ecc9e51bd5c084c75d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 17 18:24:44 2023 +0100

    rtc: sunplus: fix format string for printing resource

    On 32-bit architectures with 64-bit resource_size_t, sp_rtc_probe()
    causes a compiler warning:

    drivers/rtc/rtc-sunplus.c: In function 'sp_rtc_probe':
    drivers/rtc/rtc-sunplus.c:243:33: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'resource_size_t' {aka 'long long unsigned int'} [-Werror=format=]
      243 |         dev_dbg(&plat_dev->dev, "res = 0x%x, reg_base = 0x%lx\n",
          |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    The best way to print a resource is the special %pR format string,
    and similarly to print a pointer we can use %p and avoid the cast.

    Fixes: fad6cbe9b2b4 ("rtc: Add driver for RTC in Sunplus SP7021")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230117172450.2938962-1-arnd@kernel.org
    Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
    (cherry picked from commit 08279468a294d8c996a657ecc9e51bd5c084c75d)

Signed-off-by: Gavin Shan <gshan@redhat.com>