ASoC: bcm63xx-pcm-whistler: fix uninit-value in i2s_dma_isr
JIRA: https://issues.redhat.com/browse/RHEL-80676

commit 28f7aa0c015036db260adbec37891984a31ed4c2
Author: Suraj Sonawane <surajsonawane0215@gmail.com>
Date: Sat Nov 2 18:06:30 2024 +0530

    ASoC: bcm63xx-pcm-whistler: fix uninit-value in i2s_dma_isr

    Fix an issue detected by the Smatch tool:

    sound/soc/bcm/bcm63xx-pcm-whistler.c:264 i2s_dma_isr()
    error: uninitialized symbol 'val_1'.
    sound/soc/bcm/bcm63xx-pcm-whistler.c:264 i2s_dma_isr()
    error: uninitialized symbol 'val_2'.

    These errors were triggered because the variables 'val_1' and 'val_2'
    could remain uninitialized if 'offlevel' is zero, meaning the loop
    that assigns values to them does not execute. In this case,
    'dma_addr_next' would use uninitialized data, potentially leading
    to undefined behavior.

    To resolve this, a conditional update for 'dma_addr_next' is added,
    ensuring it is assigned only when 'val_1' and 'val_2' are read.
    A new boolean variable 'val_read' flags when the values have been
    retrieved, setting 'dma_addr_next' only if valid data is available.

    This solution prevents the use of uninitialized data, maintaining
    defined behavior for 'dma_addr_next' in all cases, and aligns with
    expected usage of I2S RX descriptor data.

    Signed-off-by: Suraj Sonawane <surajsonawane0215@gmail.com>
    Link: https://patch.msgid.link/20241102123630.25446-1-surajsonawane0215@gmail.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>