mm: add printf attribute to shrinker_debugfs_name_alloc
JIRA: https://issues.redhat.com/browse/RHEL-27743

This patch is a backport of the following upstream commit:
commit f04eba134e598d4a5af2eeecff0562df5042cbfc
Author: Lucy Mielke <lucymielke@icloud.com>
Date:   Fri Oct 6 22:30:51 2023 +0200

    mm: add printf attribute to shrinker_debugfs_name_alloc

    This fixes a compiler warning when compiling an allyesconfig with W=1:

    mm/internal.h:1235:9: error: function might be a candidate for `gnu_printf'
    format attribute [-Werror=suggest-attribute=format]

    [akpm@linux-foundation.org: fix shrinker_alloc() as welll per Qi Zheng]
      Link: https://lkml.kernel.org/r/822387b7-4895-4e64-5806-0f56b5d6c447@bytedance.com
    Link: https://lkml.kernel.org/r/ZSBue-3kM6gI6jCr@mainframe
    Fixes: c42d50aefd17 ("mm: shrinker: add infrastructure for dynamically allocating shrinker")
    Signed-off-by: Lucy Mielke <lucymielke@icloud.com>
    Cc: Qi Zheng <zhengqi.arch@bytedance.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Rafael Aquini <raquini@redhat.com>