remoteproc: qcom: q6v5: fix service routines build errors
Bugzilla: http://bugzilla.redhat.com/2071773

commit eee412e968f7b950564880bc6a7a9f00f49034da
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Fri Jan 14 17:13:38 2022 -0800

    remoteproc: qcom: q6v5: fix service routines build errors

    When CONFIG_QCOM_AOSS_QMP=m and CONFIG_QCOM_Q6V5_MSS=y, the builtin
    driver cannot call into the loadable module's low-level service
    functions. Trying to build with that config combo causes linker errors.

    There are two problems here. First, drivers/remoteproc/qcom_q6v5.c
    should #include <linux/soc/qcom/qcom_aoss.h> for the definitions of
    the service functions, depending on whether CONFIG_QCOM_AOSS_QMP is
    set/enabled or not. Second, the qcom remoteproc drivers should depend
    on QCOM_AOSS_QMP iff it is enabled (=y or =m) so that the qcom
    remoteproc drivers can be built properly.

    This prevents these build errors:

    aarch64-linux-ld: drivers/remoteproc/qcom_q6v5.o: in function `q6v5_load_state_toggle':
    qcom_q6v5.c:(.text+0xc4): undefined reference to `qmp_send'
    aarch64-linux-ld: drivers/remoteproc/qcom_q6v5.o: in function `qcom_q6v5_deinit':
    (.text+0x2e4): undefined reference to `qmp_put'
    aarch64-linux-ld: drivers/remoteproc/qcom_q6v5.o: in function `qcom_q6v5_init':
    (.text+0x778): undefined reference to `qmp_get'
    aarch64-linux-ld: (.text+0x7d8): undefined reference to `qmp_put'

    Fixes: c1fe10d238c0 ("remoteproc: qcom: q6v5: Use qmp_send to update co-processor load state")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Bjorn Andersson <bjorn.andersson@linaro.org>
    Cc: Mathieu Poirier <mathieu.poirier@linaro.org>
    Cc: linux-remoteproc@vger.kernel.org
    Cc: Sibi Sankar <sibis@codeaurora.org>
    Cc: Stephen Boyd <swboyd@chromium.org>
    Reviewed-by: Stephen Boyd <swboyd@chromium.org>
    Reviewed-by: Bjorn Andersson <bjorn.andersson@linaro.org>
    Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
    Link: https://lore.kernel.org/r/20220115011338.2973-1-rdunlap@infradead.org

Signed-off-by: Steve Best <sbest@redhat.com>