wifi: rt2x00: fix CRC_CCITT dependency
JIRA: https://issues.redhat.com/browse/RHEL-114891

commit f64768bec0d57988782d26d1ea7ae21f959309dd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jul 31 09:58:33 2025 +0200

    wifi: rt2x00: fix CRC_CCITT dependency
    
    Compile-testing this driver on Arm platforms shows a link failure
    when the CRC functions are not part of the kernel:
    
    x86_64-linux-ld: drivers/net/wireless/ralink/rt2x00/rt2800lib.o: in function `rt2800_check_firmware':
    rt2800lib.c:(.text+0x20e5): undefined reference to `crc_ccitt'
    
    Move the select statement to the correct Kconfig symbol to match
    the call site.
    
    Fixes: 311b05e235cf ("wifi: rt2x00: add COMPILE_TEST")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Stanislaw Gruszka <stf_xl@wp.pl>
    Reviewed-by: Sergio Paracuellos <sergio.paracuellos@gmail.com>
    Link: https://patch.msgid.link/20250731075837.1969136-1-arnd@kernel.org
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jose Ignacio Tornos Martinez <jtornosm@redhat.com>