perf tests x86: Move insn.h include to make sure it finds stddef.h
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-326.el8
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit c1f272df510c6b1db68ca6597724d17b557d1407

In some versions of alpine Linux the perf build is broken since commit
1d509f2a6ebca1ae ("x86/insn: Support big endian cross-compiles"):

  In file included from /usr/include/linux/byteorder/little_endian.h:13,
                   from /usr/include/asm/byteorder.h:5,
                   from arch/x86/util/../../../../arch/x86/include/asm/insn.h:10,
                   from arch/x86/util/archinsn.c:2:
  /usr/include/linux/swab.h:161:8: error: unknown type name '__always_inline'
   static __always_inline __u16 __swab16p(const __u16 *p)

So move the inclusion of arch/x86/include/asm/insn.h to later in the
places where linux/stddef.h (that conditionally defines
__always_inline) to workaround this problem on Alpine Linux 3.9 to 3.11,
3.12 onwards works.

	Cc: Josh Poimboeuf <jpoimboe@redhat.com>
	Cc: Martin Schwidefsky <schwidefsky@de.ibm.com>
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit c1f272df510c6b1db68ca6597724d17b557d1407)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>