bpf, powerpc: Fix misuse of fallthrough in bpf_jit_comp()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author He Zhe <zhe.he@windriver.com>
commit 9cf51446e68607136e42a4e531a30c888c472463
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-294.el8/9cf51446.failed

The user defined label following "fallthrough" is not considered by GCC
and causes build failure.

kernel-source/include/linux/compiler_attributes.h:208:41: error: attribute
'fallthrough' not preceding a case label or default label [-Werror]
 208   define fallthrough _attribute((fallthrough_))
                          ^~~~~~~~~~~~~

Fixes: df561f6688fe ("treewide: Use fallthrough pseudo-keyword")
	Signed-off-by: He Zhe <zhe.he@windriver.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
	Cc: Gustavo A. R. Silva <gustavoars@kernel.org>
Link: https://lore.kernel.org/bpf/20200928090023.38117-1-zhe.he@windriver.com
(cherry picked from commit 9cf51446e68607136e42a4e531a30c888c472463)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	arch/powerpc/net/bpf_jit_comp.c