xdrm/nouveau: dispnv50: fix missing-prototypes warning
JIRA: https://issues.redhat.com/browse/RHEL-846
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.3.13)

commit 94b9941bc2c4211b0bd36747fad204e69c88ca02
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Mon Apr 17 23:03:23 2023 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Tue Jul 11 19:39:36 2023 +0200

    [ Upstream commit 504e72ed3a1b1c0d4450712a42ae6070d3a05a8e ]

    nv50_display_create() is declared in another header, along with
    a couple of declarations that are now outdated:

    drivers/gpu/drm/nouveau/dispnv50/disp.c:2517:1: error: no previous prototype for 'nv50_display_create'

    Fixes: ba801ef068c1 ("drm/nouveau/kms: display destroy/init/fini hooks can be static")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Karol Herbst <kherbst@redhat.com>
    Signed-off-by: Karol Herbst <kherbst@redhat.com>
    Link: https://patchwork.freedesktop.org/patch/msgid/20230417210329.2469722-1-arnd@kernel.org
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>