ASoC: core: move definition of enum snd_soc_bias_level
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: core: move definition of enum snd_soc_bias_level (Jaroslav Kysela) [1869536]
Rebuild_FUZZ: 94.74%
commit-author Tzung-Bi Shih <tzungbi@google.com>
commit 10e834099d38dd2c02bf2bd5feaa3997cfcf139f

To fix compilation error:

- error: field 'XXX' has incomplete type

Moves definition of enum snd_soc_bias_level from soc.h to soc-dapm.h.

	Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-2-tzungbi@google.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 10e834099d38dd2c02bf2bd5feaa3997cfcf139f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>