platform/x86/amd: pmc: add CONFIG_SERIO dependency
Bugzilla: https://bugzilla.redhat.com/2162507

commit abce209d18fd26e865b2406cc68819289db973f9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jan 27 10:39:44 2023 +0100

    platform/x86/amd: pmc: add CONFIG_SERIO dependency

    Using the serio subsystem now requires the code to be reachable:

    x86_64-linux-ld: drivers/platform/x86/amd/pmc.o: in function `amd_pmc_suspend_handler':
    pmc.c:(.text+0x86c): undefined reference to `serio_bus'

    Add the usual dependency: as other users of serio use 'select'
    rather than 'depends on', use the same here.

    Fixes: 8e60615e8932 ("platform/x86/amd: pmc: Disable IRQ1 wakeup for RN/CZN")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230127093950.2368575-1-arnd@kernel.org
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>