ACPI/processor_idle: Export acpi_processor_ffh_play_dead()
JIRA: https://issues.redhat.com/browse/RHEL-89362

commit 64aad4749d7911f8c5e69d93a929a269605dd3cb
Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Date: Fri, 21 Feb 2025 15:17:07 +0000

The kernel test robot reported the following build error:

  >> ERROR: modpost: "acpi_processor_ffh_play_dead" [drivers/acpi/processor.ko] undefined!

Caused by this recently merged commit:

  541ddf31e300 ("ACPI/processor_idle: Add FFH state handling")

The build failure is due to an oversight in the 'CONFIG_ACPI_PROCESSOR=m' case,
the function export is missing. Add it.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202502151207.FA9UO1iX-lkp@intel.com/
Fixes: 541ddf31e300 ("ACPI/processor_idle: Add FFH state handling")
Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Cc: Dave Hansen <dave.hansen@linux.intel.com>
Link: https://lore.kernel.org/r/de5bf4f116779efde315782a15146fdc77a4a044.camel@linux.intel.com
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>