net/mlx5e: Don't store mlx5e_priv in mlx5e_dev devlink priv
JIRA: https://issues.redhat.com/browse/RHEL-98257

commit 123eda2e5b1638e298e3a66bb1e64a8da92de5e1
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Thu Jan 8 13:26:55 2026 -0800

    net/mlx5e: Don't store mlx5e_priv in mlx5e_dev devlink priv

    mlx5e_priv is an unstable structure that can be memset(0) if profile
    attaching fails, mlx5e_priv in mlx5e_dev devlink private is used to
    reference the netdev and mdev associated with that struct. Instead,
    store netdev directly into mlx5e_dev and get mdev from the containing
    mlx5_adev aux device structure.

    This fixes a kernel oops in mlx5e_remove when switchdev mode fails due
    to change profile failure.

    $ devlink dev eswitch set pci/0000:00:03.0 mode switchdev
    Error: mlx5_core: Failed setting eswitch to offloads.
    dmesg:
    workqueue: Failed to create a rescuer kthread for wq "mlx5e": -EINTR
    mlx5_core 0012:03:00.1: mlx5e_netdev_init_profile:6214:(pid 37199): mlx5e_priv_init failed, err=-12
    mlx5_core 0012:03:00.1 gpu3rdma1: mlx5e_netdev_change_profile: new profile init failed, -12
    workqueue: Failed to create a rescuer kthread for wq "mlx5e": -EINTR
    mlx5_core 0012:03:00.1: mlx5e_netdev_init_profile:6214:(pid 37199): mlx5e_priv_init failed, err=-12
    mlx5_core 0012:03:00.1 gpu3rdma1: mlx5e_netdev_change_profile: failed to rollback to orig profile, -12

    $ devlink dev reload pci/0000:00:03.0 ==> oops

    BUG: kernel NULL pointer dereference, address: 0000000000000520
     #PF: supervisor read access in kernel mode
     #PF: error_code(0x0000) - not-present page
    PGD 0 P4D 0
    Oops: Oops: 0000 [#1] SMP NOPTI
    CPU: 3 UID: 0 PID: 521 Comm: devlink Not tainted 6.18.0-rc5+ #117 PREEMPT(voluntary)
    Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.3-2.fc40 04/01/2014
    RIP: 0010:mlx5e_remove+0x68/0x130
    RSP: 0018:ffffc900034838f0 EFLAGS: 00010246
    RAX: ffff88810283c380 RBX: ffff888101874400 RCX: ffffffff826ffc45
    RDX: 0000000000000000 RSI: 0000000000000001 RDI: 0000000000000000
    RBP: ffff888102d789c0 R08: ffff8881007137f0 R09: ffff888100264e10
    R10: ffffc90003483898 R11: ffffc900034838a0 R12: ffff888100d261a0
    R13: ffff888100d261a0 R14: ffff8881018749a0 R15: ffff888101874400
    FS:  00007f8565fea740(0000) GS:ffff88856a759000(0000) knlGS:0000000000000000
    CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
    CR2: 0000000000000520 CR3: 000000010b11a004 CR4: 0000000000370ef0
    Call Trace:
     <TASK>
     device_release_driver_internal+0x19c/0x200
     bus_remove_device+0xc6/0x130
     device_del+0x160/0x3d0
     ? devl_param_driverinit_value_get+0x2d/0x90
     mlx5_detach_device+0x89/0xe0
     mlx5_unload_one_devl_locked+0x3a/0x70
     mlx5_devlink_reload_down+0xc8/0x220
     devlink_reload+0x7d/0x260
     devlink_nl_reload_doit+0x45b/0x5a0
     genl_family_rcv_msg_doit+0xe8/0x140

    Fixes: ee75f1fc44dd ("net/mlx5e: Create separate devlink instance for ethernet auxiliary device")
    Fixes: c4d7eb57687f ("net/mxl5e: Add change profile method")
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Link: https://patch.msgid.link/20260108212657.25090-3-saeed@kernel.org
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>