sfc: avoid an unused-variable warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [net] sched: avoid unused variable warning (Jonathan Toppins) [1393375]
Rebuild_FUZZ: 87.67%
commit-author Arnd Bergmann <arnd@arndb.de>
commit b113cabd4378ddd98dccdd7748a16f9f1f094ef0

'nic_data' is no longer used outside of the #ifdef block
in efx_ef10_set_mac_address:

drivers/net/ethernet/sfc/ef10.c:3231:28: error: unused variable 'nic_data' [-Werror,-Wunused-variable]
        struct efx_ef10_nic_data *nic_data = efx->nic_data;

Move the variable into a local scope.

Fixes: dfcabb078847 ("sfc: move vport_id to struct efx_nic")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit b113cabd4378ddd98dccdd7748a16f9f1f094ef0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>