arm64: asm/perf_regs.h: Avoid C++-style comment in UAPI header
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2167398

commit aa3e49b606e0796aa766ded2fb7b8c2d36d7cf2f
Author: Will Deacon <will@kernel.org>
Date: Thu, 22 Sep 2022 22:11:10 +0100

    An arm64 'allmodconfig' build fails with GCC due to use of a C++-style
    comment for the new SVE vector granule 'enum perf_event_arm_regs' entry:

      | /usr/include/asm/perf_regs.h:42:26: error: C++ style comments are not allowed in ISO C90

    Use good ol' /* */ comment syntax to keep things rosey.

    Link: https://lore.kernel.org/r/632cceb2.170a0220.599ec.0a3a@mx.google.com
    Fixes: cbb0c02caf4b ("perf: arm64: Add SVE vector granule register to user regs")
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>