locking/pvqspinlock: Correct the type of "old" variable in pv_kick_node()
JIRA: https://issues.redhat.com/browse/RHEL-60306

commit 6623b0217d0c9bed80bfa43b778ce1c0eb03b497
Author: Uros Bizjak <ubizjak@gmail.com>
Date: Sun, 21 Jul 2024 18:45:41 +0200

    "enum vcpu_state" is not compatible with "u8" type for all targets,
    resulting in:

    error: initialization of 'u8 *' {aka 'unsigned char *'} from incompatible pointer type 'enum vcpu_state *'

    for LoongArch. Correct the type of "old" variable to "u8".

    Fixes: fea0e1820b51 ("locking/pvqspinlock: Use try_cmpxchg() in qspinlock_paravirt.h")
    Closes: https://lore.kernel.org/lkml/20240719024010.3296488-1-maobibo@loongson.cn/
    Reported-by: Bibo Mao <maobibo@loongson.cn>
    Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Waiman Long <longman@redhat.com>
    Link: https://lore.kernel.org/r/20240721164552.50175-1-ubizjak@gmail.com

Signed-off-by: Čestmír Kalina <ckalina@redhat.com>