perf symbols: Define STT_GNU_IFUNC for glibc 2.9 and older.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] symbols: Define STT_GNU_IFUNC for glibc 2.9 and older (Jiri Olsa) [1222189]
Rebuild_FUZZ: 94.64%
commit-author Vinson Lee <vlee@twitter.com>
commit 4e31050f482c02c822b150d71cf1ea5be7c9d6e4

The token STT_GNU_IFUNC is not available with glibc 2.9 and older.
Define this token if it is not already defined.

This patch fixes this build errors with older versions of glibc.

  CC       util/symbol-elf.o
util/symbol-elf.c: In function ‘elf_sym__is_function’:
util/symbol-elf.c:75: error: ‘STT_GNU_IFUNC’ undeclared (first use in this function)
util/symbol-elf.c:75: error: (Each undeclared identifier is reported only once
util/symbol-elf.c:75: error: for each function it appears in.)
make: *** [util/symbol-elf.o] Error 1

	Signed-off-by: Vinson Lee <vlee@twitter.com>
	Acked-by: Namhyung Kim <namhyung@kernel.org>
	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: Anton Blanchard <anton@samba.org>
	Cc: Avi Kivity <avi@cloudius-systems.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Paul Mackerras <paulus@samba.org>
	Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
	Cc: Stephane Eranian <eranian@google.com>
	Cc: Waiman Long <Waiman.Long@hp.com>
	Cc: stable@vger.kernel.org # 3.17+
Link: http://lkml.kernel.org/r/1423528286-13630-1-git-send-email-vlee@twopensource.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 4e31050f482c02c822b150d71cf1ea5be7c9d6e4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>