gpio: rcar: drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-78506

commit 072de5a412cc0601c4802e0ed62cbc5ed781d68c
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 12:13:02 2023 +0100

    gpio: rcar: drop of_match_ptr for ID table

    The driver can match only via the DT table so the table should be always
    used and the of_match_ptr does not have any sense (this also allows ACPI
    matching via PRP0001, even though it might not be relevant here).

      drivers/gpio/gpio-rcar.c:435:34: error: ‘gpio_rcar_of_table’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Reviewed-by: Linus Walleij <linus.walleij@linaro.org>
    Signed-off-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>

Signed-off-by: Radu Rendec <rrendec@redhat.com>