ASoC: tas2781: fix unused-const-variable warning
JIRA: https://issues.redhat.com/browse/RHEL-183295

commit bc9b1ebaa7624edde54d4ae842d11cebb26db09b
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Apr 13 09:00:45 2026 +0200

    ASoC: tas2781: fix unused-const-variable warning

    When both CONFIG_OF and CONFIG_ACPI are disabled, the ID table is not
    referenced any more:

    sound/soc/codecs/tas2781-i2c.c:102:35: error: 'tasdevice_id' defined but not used [-Werror=unused-const-variable=]
      102 | static const struct i2c_device_id tasdevice_id[] = {
          |                                   ^~~~~~~~~~~~

    Remove the #ifdef checks and just include the ID tables unconditionally
    to get a clean build in all configurations. The code already uses
    IS_ENABLED() checks for both to benefit from dead code elimination
    and the ID tables are small enough that they can just be included
    all the time.

    Fixes: 9a52d1b7cb4a ("ASoC: tas2781: Explicit association of Device, Device Name, and Device ID")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/20260413070059.3828364-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>