powerpc/mm: Fix build break with BOOK3S_64=n and MEMORY_HOTPLUG=y
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [powerpc] mm: Fix build break with BOOK3S_64=n and MEMORY_HOTPLUG=y (Laurent Vivier) [1693046]
Rebuild_FUZZ: 93.44%
commit-author Michael Ellerman <mpe@ellerman.id.au>
commit 36b390fd624a7f3a64bda5de54fa58ebcf956ffc

The recently merged HPT (Hash Page Table) resize support broke the build
when BOOK3S_64=n (ie. 32-bit or 64-bit Book3E) and MEMORY_HOTPLUG=y:

  arch/powerpc/mm/mem.o: In function `.arch_add_memory':
  (.text+0x4e4): undefined reference to `.resize_hpt_for_hotplug'

Fix it by adding a dummy version.

Fixes: 438cc81a41e8 ("powerpc/pseries: Automatically resize HPT for memory hot add/remove")
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 36b390fd624a7f3a64bda5de54fa58ebcf956ffc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>