ASoC: codecs: aw88399: fix typo in Kconfig select
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit cf046ecbcd1cd0ef1d762b3365b9918175e121ab
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Oct 27 17:23:53 2023 +0200

    ASoC: codecs: aw88399: fix typo in Kconfig select

    The aw88395_lib module is shared by all the aw883* drivers that
    need to select the corresponding Kconfig symbol. The newly added
    aw88399 incorrectly selects SND_SOC_AW88399_LIB instead, which
    is not defined anywhere in the kernel, causing a link failure when
    the actual one is missing:

    arm-linux-gnueabi-ld: sound/soc/codecs/aw88399.o: in function `aw88399_codec_probe':
    aw88399.c:(.text+0xbc6): undefined reference to `aw88395_dev_load_acf_check'
    arm-linux-gnueabi-ld: aw88399.c:(.text+0xbea): undefined reference to `aw88395_dev_cfg_load'

    Fixes: 8ade6cc7e261 ("ASoC: codecs: Add aw88399 amplifier driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231027152403.386257-2-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>