security: declare member holding string literal const
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2181134

commit 1af0e4a0233fea7e8226cb977d379dc20f9bbe11
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Thu Feb 17 15:18:57 2022 +0100

    security: declare member holding string literal const

    The struct security_hook_list member lsm is assigned in
    security_add_hooks() with string literals passed from the individual
    security modules.  Declare the function parameter and the struct member
    const to signal their immutability.

    Reported by Clang [-Wwrite-strings]:

        security/selinux/hooks.c:7388:63: error: passing 'const char [8]'
          to parameter of type 'char *' discards qualifiers
          [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                security_add_hooks(selinux_hooks,
                                   ARRAY_SIZE(selinux_hooks), selinux);
                                                              ^~~~~~~~~
        ./include/linux/lsm_hooks.h:1629:11: note: passing argument to
          parameter 'lsm' here
                                        char *lsm);
                                              ^

    Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
    Reviewed-by: Paul Moore <paul@paul-moore.com>
    Reviewed-by: Casey Schaufler <casey@schaufler-ca.com>
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Juraj Marcin <jmarcin@redhat.com>