crypto: certs: fix FIPS selftest dependency
jira LE-12345
Rebuild_History Non-Buildable kernel-5.14.0-570.16.1.el9_6
commit-author Arnd Bergmann <arnd@arndb.de>
commit 0f5d4a0b995faa6537c4de79973817a4f8da206a

The selftest code is built into the x509_key_parser module, and depends
on the pkcs7_message_parser module, which in turn has a dependency on
the key parser, creating a dependency loop and a resulting link
failure when the pkcs7 code is a loadable module:

ld: crypto/asymmetric_keys/selftest.o: in function `fips_signature_selftest':
crypto/asymmetric_keys/selftest.c:205: undefined reference to `pkcs7_parse_message'
ld: crypto/asymmetric_keys/selftest.c:209: undefined reference to `pkcs7_supply_detached_data'
ld: crypto/asymmetric_keys/selftest.c:211: undefined reference to `pkcs7_verify'
ld: crypto/asymmetric_keys/selftest.c:215: undefined reference to `pkcs7_validate_trust'
ld: crypto/asymmetric_keys/selftest.c:219: undefined reference to `pkcs7_free_message'

Avoid this by only allowing the selftest to be enabled when either
both parts are loadable modules, or both are built-in.

	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
	Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>
(cherry picked from commit 0f5d4a0b995faa6537c4de79973817a4f8da206a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>