am65-cpsw: avoid null pointer arithmetic
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit 861f40fa0edfe38806a2a6e7201bfed821906d2d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 11:37:57 2021 +0200

    am65-cpsw: avoid null pointer arithmetic

    clang warns about arithmetic on NULL pointers:

    drivers/net/ethernet/ti/am65-cpsw-ethtool.c:71:2: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
            AM65_CPSW_REGDUMP_REC(AM65_CPSW_REGDUMP_MOD_NUSS, 0x0, 0x1c),
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/ethernet/ti/am65-cpsw-ethtool.c:64:29: note: expanded from macro 'AM65_CPSW_REGDUMP_REC'
            .hdr.len = (((u32 *)(end)) - ((u32 *)(start)) + 1) * sizeof(u32) * 2 + \
                                       ^ ~~~~~~~~~~~~~~~~

    The expression here is easily changed to a calculation based on integers
    that is no less readable.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>