selftests/bpf: use proper type when passing prog_type
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Stanislav Fomichev <sdf@google.com>
commit aca1a80ebe3e4d49adaf6516c61a6786b1ee7dad

Use bpf_prog_type instead of bpf_map_type when passing prog_type.

-Wenum-conversion might be unhappy about it:
	error: implicit conversion from enumeration type
	'enum bpf_map_type' to different enumeration type
	'enum bpf_prog_type'

	Signed-off-by: Stanislav Fomichev <sdf@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit aca1a80ebe3e4d49adaf6516c61a6786b1ee7dad)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>