ASoC: cx2072x: mark PM function as __maybe_unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: cx2072x: mark PM function as __maybe_unused (Jaroslav Kysela) [1738610]
Rebuild_FUZZ: 94.23%
commit-author Arnd Bergmann <arnd@arndb.de>
commit 83ee240aad9147ed5dac5a7c7b4c559d134072e7

While the suspend function is already marked __maybe_unused,
the resume function is not, which leads to a warning when
CONFIG_PM is disabled:

sound/soc/codecs/cx2072x.c:1625:12: error: unused function 'cx2072x_runtime_resume' [-Werror,-Wunused-function]

Mark this one like the other one.

Fixes: a497a4363706 ("ASoC: Add support for Conexant CX2072X CODEC")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 83ee240aad9147ed5dac5a7c7b4c559d134072e7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>