bpftool: make key optional in lookup command
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [tools] tool: make key optional in lookup command (Yauheni Kaliuta) [1747341]
Rebuild_FUZZ: 96.47%
commit-author Stanislav Fomichev <sdf@google.com>
commit 8a89fff60a7ef63a23b112bdfa76d7ba160a4a68

Bpftool expects key for 'lookup' operations. For some map types, key should
not be specified. Support looking up those map types.

Before:
bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
bpftool map lookup pinned /sys/fs/bpf/q
Error: did not find key

After:
bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
bpftool map lookup pinned /sys/fs/bpf/q
key:   value: 00 01 02 03

	Signed-off-by: Stanislav Fomichev <sdf@google.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
(cherry picked from commit 8a89fff60a7ef63a23b112bdfa76d7ba160a4a68)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>