selftests dma: fix compile error for dma_map_benchmark
Bugzilla: https://bugzilla.redhat.com/2112024
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 12a29115be72dfc72372af9ded4bc4ae7113a729
Author: Yu Liao <liaoyu15@huawei.com>
Date:   Tue Jun 14 20:02:35 2022 +0800

    selftests dma: fix compile error for dma_map_benchmark

    When building selftests/dma:
    $ make -C tools/testing/selftests TARGETS=dma
    I hit the following compilation error:

    dma_map_benchmark.c:13:10: fatal error: linux/map_benchmark.h: No such file or directory
     #include <linux/map_benchmark.h>
	      ^~~~~~~~~~~~~~~~~~~~~~~

    dma/Makefile does not include the map_benchmark.h path, so add
    more including path, and fix include order in dma_map_benchmark.c

    Fixes: 8ddde07a3d28 ("dma-mapping: benchmark: extract a common header file for map_benchmark definition")
    Signed-off-by: Yu Liao <liaoyu15@huawei.com>
    Tested-by: Shuah Khan <skhan@linuxfoundation.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

(cherry picked from commit 12a29115be72dfc72372af9ded4bc4ae7113a729)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>