tools/net/ynl: Add extack policy attribute decoding
JIRA: https://issues.redhat.com/browse/RHEL-57756

Upstream commit(s):
commit bd3ce405fecc6f2f9ce09c789386e326346899a0
Author: Donald Hunter <donald.hunter@gmail.com>
Date:   Thu Mar 28 15:56:36 2024 +0000

    tools/net/ynl: Add extack policy attribute decoding

    The NLMSGERR_ATTR_POLICY extack attribute has been ignored by ynl up to
    now. Extend extack decoding to include _POLICY and the nested
    NL_POLICY_TYPE_ATTR_* attributes.

    For example:

    ./tools/net/ynl/cli.py \
      --spec Documentation/netlink/specs/rt_link.yaml \
      --create --do newlink --json '{
        "ifname": "12345678901234567890",
        "linkinfo": {"kind": "bridge"}
        }'
    Netlink error: Numerical result out of range
    nl_len = 104 (88) nl_flags = 0x300 nl_type = 2
            error: -34      extack: {'msg': 'Attribute failed policy validation',
    'policy': {'max-length': 15, 'type': 'string'}, 'bad-attr': '.ifname'}

    Signed-off-by: Donald Hunter <donald.hunter@gmail.com>
    Link: https://lore.kernel.org/r/20240328155636.64688-1-donald.hunter@gmail.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Petr Oros <poros@redhat.com>