octeontx2-pf: fix build error when CONFIG_OCTEONTX2_PF=y
JIRA: https://issues.redhat.com/browse/RHEL-23617

commit 02f5999e652952d69c341a03d4313310703fd7f1
Author: Yang Yingliang <yangyingliang@huawei.com>
Date:   Sat Nov 5 14:34:42 2022 +0800

    octeontx2-pf: fix build error when CONFIG_OCTEONTX2_PF=y

    If CONFIG_MACSEC=m and CONFIG_OCTEONTX2_PF=y, it leads a build error:

      ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_pfaf_mbox_up_handler':
      otx2_pf.c:(.text+0x181c): undefined reference to `cn10k_handle_mcs_event'
      ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_probe':
      otx2_pf.c:(.text+0x437e): undefined reference to `cn10k_mcs_init'
      ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_remove':
      otx2_pf.c:(.text+0x5031): undefined reference to `cn10k_mcs_free'
      ld: drivers/net/ethernet/marvell/octeontx2/nic/otx2_pf.o: in function `otx2_mbox_up_handler_mcs_intr_notify':
      otx2_pf.c:(.text+0x5f11): undefined reference to `cn10k_handle_mcs_event'

    Make CONFIG_OCTEONTX2_PF depends on CONFIG_MACSEC to fix it. Because
    it has empty stub functions of cn10k, CONFIG_OCTEONTX2_PF can be enabled
    if CONFIG_MACSEC is disabled

    Fixes: c54ffc73601c ("octeontx2-pf: mcs: Introduce MACSEC hardware offloading")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>
    Link: https://lore.kernel.org/r/20221105063442.2013981-1-yangyingliang@huawei.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Sai Krishna <sgajula@redhat.com>