cpufreq/amd-pstate: Avoid shadowing ret in amd_pstate_ut_check_driver()
JIRA: https://issues.redhat.com/browse/RHEL-104550

commit f6b1eebbdbc75377f98fc9774bb86ffc270dae8e
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Mon May 12 23:28:55 2025 +0200

    cpufreq/amd-pstate: Avoid shadowing ret in amd_pstate_ut_check_driver()

    Clang warns (or errors with CONFIG_WERROR=y):

      drivers/cpufreq/amd-pstate-ut.c:262:6: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
        262 |         if (ret)
            |             ^~~

    ret is declared at the top of the function and in the for loop so the
    initialization of ret is local to the loop. Remove the declaration in
    the for loop so that ret is always used initialized.

    Fixes: d26d16438bc5 ("amd-pstate-ut: Reset amd-pstate driver mode after running selftests")
    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202505072226.g2QclhaR-lkp@intel.com/
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Acked-by: Mario Limonciello <mario.limonciello@amd.com>
    Link: https://lore.kernel.org/r/20250512-amd-pstate-ut-uninit-ret-v1-1-fcb4104f502e@kernel.org
    Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>

Signed-off-by: Steve Best <sbest@redhat.com>