ALSA: hda: controller code - do not export static functions
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [alsa] hda: controller code - do not export static functions (Jaroslav Kysela) [1197064]
Rebuild_FUZZ: 94.64%
commit-author Jaroslav Kysela <perex@perex.cz>
commit 37ed398839fa3e0d2de77925097db7a370abb096

It is a bad idea to export static functions. GCC for some platforms
shows errors like:

  error: __ksymtab_azx_get_response causes a section type conflict

	Signed-off-by: Jaroslav Kysela <perex@perex.cz>
	Cc: <stable@vger.kernel.org> # v3.15+
	Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 37ed398839fa3e0d2de77925097db7a370abb096)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>