dm zoned: select CONFIG_CRC32
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit b690bd546b227c32b860dae985a18bed8aa946fe
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-4.18.0-310.el8/b690bd54.failed

Without crc32 support, this driver fails to link:

arm-linux-gnueabi-ld: drivers/md/dm-zoned-metadata.o: in function `dmz_write_sb':
dm-zoned-metadata.c:(.text+0xe98): undefined reference to `crc32_le'
arm-linux-gnueabi-ld: drivers/md/dm-zoned-metadata.o: in function `dmz_check_sb':
dm-zoned-metadata.c:(.text+0x7978): undefined reference to `crc32_le'

Fixes: 3b1a94c88b79 ("dm zoned: drive-managed zoned block device target")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Damien Le Moal <damien.lemoal@wdc.com>
	Signed-off-by: Mike Snitzer <snitzer@redhat.com>
(cherry picked from commit b690bd546b227c32b860dae985a18bed8aa946fe)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/md/Kconfig