selftests/bpf: Fix compiling core_reloc.c with musl-libc
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit debfa4f628f271f72933bf38d581cc53cfe1def5
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:42 2024 -0700

    selftests/bpf: Fix compiling core_reloc.c with musl-libc

    The type 'loff_t' is a GNU extension and not exposed by the musl 'fcntl.h'
    header unless _GNU_SOURCE is defined. Add this definition to fix errors
    seen compiling for mips64el/musl-libc:

      In file included from tools/testing/selftests/bpf/prog_tests/core_reloc.c:4:
      ./bpf_testmod/bpf_testmod.h:10:9: error: unknown type name 'loff_t'
         10 |         loff_t off;
            |         ^~~~~~
      ./bpf_testmod/bpf_testmod.h:16:9: error: unknown type name 'loff_t'
         16 |         loff_t off;
            |         ^~~~~~

    Fixes: 6bcd39d366b6 ("selftests/bpf: Add CO-RE relocs selftest relying on kernel module BTF")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/11c3af75a7eb6bcb7ad9acfae6a6f470c572eb82.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>