tools lib traceevent: Fix use of multiple options in processing field
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-229.el7
Rebuild_CHGLOG: - [tools] perf/traceevent: Fix use of multiple options in processing field (Jiri Olsa) [1131394]
Rebuild_FUZZ: 88.72%
commit-author Steven Rostedt <rostedt@goodmis.org>
commit eff2c92f86c2ac2a0eab3749d58be39592293c3a

Jiri Olsa reported that the scsi_dispatch_cmd_done event failed to parse
with:

  Error: expected type 5 but read 4
  Error: expected type 5 but read 4

The problem is with this part of the print_fmt:

  __print_symbolic(((REC->result) >> 24) & 0xff, ...

The __print_symbolic() helper function's first parameter is the field to
use to determine what symbol to print based on the value of the result.
The parser can handle one operation, but it can not handle multiple
operations ('>>' and '&').

Add code to process all operations for the field argument for
__print_symbolic() as well as __print_flags().

	Reported-by: Jiri Olsa <jolsa@redhat.com>
	Signed-off-by: Steven Rostedt <rostedt@goodmis.org>
	Cc: Frederic Weisbecker <fweisbec@gmail.com>
	Cc: Ingo Molnar <mingo@kernel.org>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
Link: http://lkml.kernel.org/r/20131118142314.27ca334b@gandalf.local.home
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit eff2c92f86c2ac2a0eab3749d58be39592293c3a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>