ASoC: codecs: pcm179x-spi: Mark OF related data as maybe unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
commit 413beba1a336e6068119f31a4441c51a7aeb1b55

The driver can be compile tested with !CONFIG_OF making certain data
unused:

  sound/soc/codecs/pcm179x-spi.c:32:34: error: ‘pcm179x_of_match’ defined but not used [-Werror=unused-const-variable=]

	Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230310214333.274903-7-krzysztof.kozlowski@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 413beba1a336e6068119f31a4441c51a7aeb1b55)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>