intel_th: INTEL_TH should depend on HAS_DMA
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1127.el7
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit 8d0439369d98aa23c8e20a49b69d90b1efab2797
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-3.10.0-1127.el7/8d043936.failed

If NO_DMA=y:

    ERROR: "dma_free_coherent" [drivers/hwtracing/intel_th/intel_th_msu.ko] undefined!
    ERROR: "dma_alloc_coherent" [drivers/hwtracing/intel_th/intel_th_msu.ko] undefined!
    ERROR: "dma_supported" [drivers/hwtracing/intel_th/intel_th.ko] undefined!

Add a dependency on HAS_DMA to fix this.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 8d0439369d98aa23c8e20a49b69d90b1efab2797)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/hwtracing/intel_th/Kconfig