hv_netvsc: rndis_filter needs to select NLS
jira LE-1907
Rebuild_History Non-Buildable kernel-rt-4.18.0-553.16.1.rt7.357.el8_10
commit-author Randy Dunlap <rdunlap@infradead.org>
commit 6c89f49964375c904cea33c0247467873f4daf2c

rndis_filter uses utf8s_to_utf16s() which is provided by setting
NLS, so select NLS to fix the build error:

ERROR: modpost: "utf8s_to_utf16s" [drivers/net/hyperv/hv_netvsc.ko] undefined!

Fixes: 1ce09e899d28 ("hyperv: Add support for setting MAC from within guests")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Cc: Haiyang Zhang <haiyangz@microsoft.com>
	Cc: K. Y. Srinivasan <kys@microsoft.com>
	Cc: Wei Liu <wei.liu@kernel.org>
	Cc: Dexuan Cui <decui@microsoft.com>
	Reviewed-by: Simon Horman <horms@kernel.org>
	Tested-by: Simon Horman <horms@kernel.org> # build-tested
	Reviewed-by: Michael Kelley <mikelley@microsoft.com>
Link: https://lore.kernel.org/r/20231130055853.19069-1-rdunlap@infradead.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 6c89f49964375c904cea33c0247467873f4daf2c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>