iommu: Fix integer truncation
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 29fcea8ce7f3c16ebd267f8cb2f4a07887530aa9

On 32-bit architectures, phys_addr_t may be different from dma_add_t,
both smaller and bigger. This can lead to an overflow during an assignment
that clang warns about:

drivers/iommu/dma-iommu.c:230:10: error: implicit conversion from 'dma_addr_t' (aka 'unsigned long long') to
      'phys_addr_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]

Use phys_addr_t here because that is the type that the variable was
declared as.

Fixes: aadad097cd46 ("iommu/dma: Reserve IOVA for PCIe inaccessible DMA address")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 29fcea8ce7f3c16ebd267f8cb2f4a07887530aa9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>