MIPS/asm/printk: Fix build failure caused by printk
Bugzilla: https://bugzilla.redhat.com/2117494

commit 86ce91d5568de02f92ab9d4fb507683f8429a3e2
Author: Petr Mladek <pmladek@suse.com>
Date:   Fri Jul 23 09:25:30 2021 +0200

    MIPS/asm/printk: Fix build failure caused by printk

    The commit 337015573718b161 ("printk: Userspace format indexing support")
    caused the following build failure:

    arch/mips/kernel/genex.o: In function `handle_mcheck_int':
    (.text+0x190c): undefined reference to `printk'
    arch/mips/kernel/genex.o: In function `handle_reserved_int':
    (.text+0x1c8c): undefined reference to `printk'

    Fixes: 337015573718b161 ("printk: Userspace format indexing support")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Suggested-by: Chris Down <chris@chrisdown.name>
    Signed-off-by: Petr Mladek <pmladek@suse.com>
    Link: https://lore.kernel.org/r/YPbBfdz9srIpI+bb@chrisdown.name

Signed-off-by: David Arcari <darcari@redhat.com>