scsi: lpfc: resolve static checker warning in lpfc_sli4_hba_unset
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author James Smart <jsmart2021@gmail.com>
commit 1ffdd2c0440dfda533ca9477a89550c9f48f4b35

The patch that replaced io channels for hdw_queues now reports the
following static checker warning:

drivers/scsi/lpfc/lpfc_init.c:11136 lpfc_sli4_hba_unset()
 error: we previously assumed 'phba->pport' could be null (see line 11074)

Resolve by adding a pport NULL check.

[mkp: tag tweak]

Fixes: cdb42becdd40 ("scsi: lpfc: Replace io_channels for nvme and fcp with general hdw_queues per cpu"_
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Dick Kennedy <dick.kennedy@broadcom.com>
	Signed-off-by: James Smart <jsmart2021@gmail.com>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 1ffdd2c0440dfda533ca9477a89550c9f48f4b35)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>