firmware: cs_dsp: avoid large local variables
JIRA: https://issues.redhat.com/browse/RHEL-80677

commit b0e4e2030b18b4e8a6820fc7c9da00e120c89338
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon Dec 16 13:15:35 2024 +0100

    firmware: cs_dsp: avoid large local variables

    Having 1280 bytes of local variables on the stack exceeds the limit
    on 32-bit architectures:

    drivers/firmware/cirrus/test/cs_dsp_test_bin.c: In function 'bin_patch_mixed_packed_unpacked_random':
    drivers/firmware/cirrus/test/cs_dsp_test_bin.c:2097:1: error: the frame size of 1784 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Use dynamic allocation for the largest two here.

    Fixes: dd0b6b1f29b9 ("firmware: cs_dsp: Add KUnit testing of bin file download")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Richard Fitzgerald <rf@opensource.cirrus.com>
    Link: https://patch.msgid.link/20241216121541.3455880-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>