PCI/sysfs: Move declarations to linux/pci.h
JIRA: https://issues.redhat.com/browse/RHEL-15044
Upstream Status: 87382eaddeed3d32afc9e4524f9488eb1bc999c2

commit 87382eaddeed3d32afc9e4524f9488eb1bc999c2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Aug 10 16:19:22 2023 +0200

    PCI/sysfs: Move declarations to linux/pci.h

    A couple of architectures build the __weak versions of
    pci_create_resource_files() and pci_remove_resource_files() but don't
    have prototypes for these, which causes warnings:

      drivers/pci/pci-sysfs.c:1253:12: error: no previous prototype for 'pci_create_resource_files' [-Werror=missing-prototypes]
       1253 | int __weak pci_create_resource_files(struct pci_dev *dev) { return 0; }
      drivers/pci/pci-sysfs.c:1254:13: error: no previous prototype for 'pci_remove_resource_files' [-Werror=missing-prototypes]
       1254 | void __weak pci_remove_resource_files(struct pci_dev *dev) { return; }

    Move the prototypes from alpha architecture into the global header to avoid
    these warnings for all of them.

    Link: https://lore.kernel.org/r/20230810141947.1236730-5-arnd@kernel.org
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>