xen: xen_debug_interrupt prototype to global header
JIRA: https://issues.redhat.com/browse/RHEL-25415

commit 04d684875b30393c3e5cd0daf2fa737b562a7ad9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 14:45:07 2023 +0200

    xen: xen_debug_interrupt prototype to global header

    The xen_debug_interrupt() function is only called on x86, which has a
    prototype in an architecture specific header, but the definition also
    exists on others, where the lack of a prototype causes a W=1 warning:

    drivers/xen/events/events_2l.c:264:13: error: no previous prototype for 'xen_debug_interrupt' [-Werror=missing-prototypes]

    Move the prototype into a global header instead to avoid this warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Stefano Stabellini <sstabellini@kernel.org>
    Link: https://lore.kernel.org/r/20230517124525.929201-1-arnd@kernel.org
    Signed-off-by: Juergen Gross <jgross@suse.com>

Signed-off-by: Prarit Bhargava <prarit@redhat.com>