KVM: PPC: Book3S HV: Fix build failure without IOMMU support
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Jordan Niethe <jniethe5@gmail.com>
commit e40542aff909ac34d2c24712c5c0769c8f77f895

Currently trying to build without IOMMU support will fail:

  (.text+0x1380): undefined reference to `kvmppc_h_get_tce'
  (.text+0x1384): undefined reference to `kvmppc_rm_h_put_tce'
  (.text+0x149c): undefined reference to `kvmppc_rm_h_stuff_tce'
  (.text+0x14a0): undefined reference to `kvmppc_rm_h_put_tce_indirect'

This happens because turning off IOMMU support will prevent
book3s_64_vio_hv.c from being built because it is only built when
SPAPR_TCE_IOMMU is set, which depends on IOMMU support.

Fix it using ifdefs for the undefined references.

Fixes: 76d837a4c0f9 ("KVM: PPC: Book3S PR: Don't include SPAPR TCE code on non-pseries platforms")
	Signed-off-by: Jordan Niethe <jniethe5@gmail.com>
	Signed-off-by: Paul Mackerras <paulus@ozlabs.org>
(cherry picked from commit e40542aff909ac34d2c24712c5c0769c8f77f895)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>