bpftool: Fix linkage with statically built libllvm
Bugzilla: https://bugzilla.redhat.com/2177177

commit 55171f2930be98c8a49991435cdf3a8b574353b6
Author: Anton Protopopov <aspsk@isovalent.com>
Date:   Thu Dec 22 10:26:27 2022 +0000

    bpftool: Fix linkage with statically built libllvm

    Since the commit eb9d1acf634b ("bpftool: Add LLVM as default library for
    disassembling JIT-ed programs") we might link the bpftool program with the
    libllvm library. This works fine when a shared libllvm library is available,
    but fails if we want to link bpftool with a statically built LLVM:

      [...]
      /usr/bin/ld: /usr/local/lib/libLLVMSupport.a(CrashRecoveryContext.cpp.o): in function `llvm::CrashRecoveryContextCleanup::~CrashRecoveryContextCleanup()':
      CrashRecoveryContext.cpp:(.text._ZN4llvm27CrashRecoveryContextCleanupD0Ev+0x17): undefined reference to `operator delete(void*, unsigned long)'
      /usr/bin/ld: /usr/local/lib/libLLVMSupport.a(CrashRecoveryContext.cpp.o): in function `llvm::CrashRecoveryContext::~CrashRecoveryContext()':
      CrashRecoveryContext.cpp:(.text._ZN4llvm20CrashRecoveryContextD2Ev+0xc8): undefined reference to `operator delete(void*, unsigned long)'
      [...]

    So in the case of static libllvm we need to explicitly link bpftool with
    required libraries, namely, libstdc++ and those provided by the `llvm-config
    --system-libs` command. We can distinguish between the shared and static cases
    by using the `llvm-config --shared-mode` command.

    Fixes: eb9d1acf634b ("bpftool: Add LLVM as default library for disassembling JIT-ed programs")
    Signed-off-by: Anton Protopopov <aspsk@isovalent.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Stanislav Fomichev <sdf@google.com>
    Link: https://lore.kernel.org/bpf/20221222102627.1643709-1-aspsk@isovalent.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>