ASoC: amd: acp: Add new cpu dai's in machine driver
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
commit 099b923fc15d8faa91c5fc1b46cbc483d034f5dc

when using same cpu dai for 2 different dai links
below error is reported.
error: can't find BE for DAI ACPHS_VIRTUAL1.OUT

To avoid this error add new cpu dai.

	Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Link: https://lore.kernel.org/r/20230109132104.1259479-2-venkataprasad.potturu@amd.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 099b923fc15d8faa91c5fc1b46cbc483d034f5dc)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>