usb: dwc2: add parenthess and space around *
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Tian Tao <tiantao6@hisilicon.com>
commit d21446eafa3a5cb238fe9eb79f49932cdb417d40

Just fix the following checkpatch error:
ERROR: Macros with complex values should be enclosed in parentheses.

	Signed-off-by: Tian Tao <tiantao6@hisilicon.com>
	Signed-off-by: Zeng Tao <prime.zeng@hisilicon.com>
Link: https://lore.kernel.org/r/1617001556-61868-1-git-send-email-tiantao6@hisilicon.com
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit d21446eafa3a5cb238fe9eb79f49932cdb417d40)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>