net: phy: ks8995: drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-2799

commit b0b7d1b6260b3acb9f3f3bc7f3ca88a8898e95b1
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Sat Mar 11 18:32:57 2023 +0100

    net: phy: ks8995: drop of_match_ptr for ID table

    The driver will match mostly by DT table (even thought there is regular
    ID table) so there is little benefit in of_match_ptr (this also allows
    ACPI matching via PRP0001, even though it might not be relevant here).

      drivers/net/phy/spi_ks8995.c:156:34: error: ‘ks8895_spi_of_match’ defined but not used [-Werror=unused-const-variable=]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Adrien Thierry <athierry@redhat.com>