rtw88: fix uninitialized 'tim_offset' warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Po-Hao Huang <phhuang@realtek.com>
commit 9cbdadf0097fc4a77071c61ed28a07eaac97f8f6

This avoids below warning and makes compiler happy.
error: uninitialized symbol 'tim_offset'

	Signed-off-by: Po-Hao Huang <phhuang@realtek.com>
	Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20220420093058.31646-1-pkshih@realtek.com
(cherry picked from commit 9cbdadf0097fc4a77071c61ed28a07eaac97f8f6)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>