kunit: tool: Import missing importlib.abc
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-494.el8
commit-author Michał Winiarski <michal.winiarski@intel.com>
commit 235528072f28b3b0a1446279b7eaddda36dbf743

Python 3.10.0 contains:
9e09849d20 ("bpo-41006: importlib.util no longer imports typing (GH-20938)")

It causes importlib.util to no longer import importlib.abs, which leads
to the following error when trying to use kunit with qemu:
AttributeError: module 'importlib' has no attribute 'abc'. Did you mean: '_abc'?

Add the missing import.

	Signed-off-by: Michał Winiarski <michal.winiarski@intel.com>
	Reviewed-by: Daniel Latypov <dlatypov@google.com>
	Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
	Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
(cherry picked from commit 235528072f28b3b0a1446279b7eaddda36dbf743)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>