x86/boot: Fix cmdline_find_option() prototype visibility
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Borislav Petkov <bp@suse.de>
commit 82f9ed3a93307089242ff8a5c694e82c8c93f522

  ac09c5f43cf6 ("x86/boot: Build the command line parsing code unconditionally")

enabled building the command line parsing code unconditionally but it
forgot to remove the respective ifdeffery around the prototypes in the
misc.h header, leading to

  arch/x86/boot/compressed/acpi.c: In function ‘get_acpi_rsdp’:
  arch/x86/boot/compressed/acpi.c:37:8: warning: implicit declaration of function \
	  ‘cmdline_find_option’ [-Wimplicit-function-declaration]
    ret = cmdline_find_option("acpi_rsdp", val, MAX_ADDR_LEN);
          ^~~~~~~~~~~~~~~~~~~

for configs where neither CONFIG_EARLY_PRINTK nor CONFIG_RANDOMIZE_BASE
was defined.

Drop the ifdeffery in the header too.

Fixes: ac09c5f43cf6 ("x86/boot: Build the command line parsing code unconditionally")
	Reported-by: kbuild test robot <lkp@intel.com>
	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Chao Fan <fanc.fnst@cn.fujitsu.com>
	Cc: x86@kernel.org
Link: https://lkml.kernel.org/r/5c51daf0.83pQEkvDZILqoSYW%lkp@intel.com
Link: https://lkml.kernel.org/r/20190205131352.GA27396@zn.tnic
(cherry picked from commit 82f9ed3a93307089242ff8a5c694e82c8c93f522)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>