eth: octeon: fix build after netif_napi_add() changes
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-481.el8
commit-author Jakub Kicinski <kuba@kernel.org>
commit 899b8cd0d3922f57176f5a7f552ce93d8a5cd90b

Guenter reports I missed a netif_napi_add() call
in one of the platform-specific drivers:

drivers/net/ethernet/cavium/octeon/octeon_mgmt.c: In function 'octeon_mgmt_probe':
drivers/net/ethernet/cavium/octeon/octeon_mgmt.c:1399:9: error: too many arguments to function 'netif_napi_add'
 1399 |         netif_napi_add(netdev, &p->napi, octeon_mgmt_napi_poll,
      |         ^~~~~~~~~~~~~~

	Reported-by: Guenter Roeck <linux@roeck-us.net>
Fixes: b48b89f9c189 ("net: drop the weight argument from netif_napi_add")
Link: https://lore.kernel.org/r/20221002175650.1491124-1-kuba@kernel.org
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 899b8cd0d3922f57176f5a7f552ce93d8a5cd90b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>