blk-crypto: Add a missing include directive
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2175212

commit 85168d416e5d3184b77dbec8fee75c9439894afa
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Wed Nov 23 09:29:23 2022 -0800

    blk-crypto: Add a missing include directive

    Allow the compiler to verify consistency of function declarations and
    function definitions. This patch fixes the following sparse errors:

    block/blk-crypto-profile.c:241:14: error: no previous prototype for ‘blk_crypto_get_keyslot’ [-Werror=missing-prototypes]
      241 | blk_status_t blk_crypto_get_keyslot(struct blk_crypto_profile *profile,
          |              ^~~~~~~~~~~~~~~~~~~~~~
    block/blk-crypto-profile.c:318:6: error: no previous prototype for ‘blk_crypto_put_keyslot’ [-Werror=missing-prototypes]
      318 | void blk_crypto_put_keyslot(struct blk_crypto_keyslot *slot)
          |      ^~~~~~~~~~~~~~~~~~~~~~
    block/blk-crypto-profile.c:344:6: error: no previous prototype for ‘__blk_crypto_cfg_supported’ [-Werror=missing-prototypes]
      344 | bool __blk_crypto_cfg_supported(struct blk_crypto_profile *profile,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
    block/blk-crypto-profile.c:373:5: error: no previous prototype for ‘__blk_crypto_evict_key’ [-Werror=missing-prototypes]
      373 | int __blk_crypto_evict_key(struct blk_crypto_profile *profile,
          |     ^~~~~~~~~~~~~~~~~~~~~~

    Cc: Eric Biggers <ebiggers@google.com>
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Link: https://lore.kernel.org/r/20221123172923.434339-1-bvanassche@acm.org
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>