kselftests/mm: fix khugepaged build broken
JIRA: https://issues.redhat.com/browse/RHEL-112084
Upstream Status: RHEL-only

selftests/mm/khugepaged.c build is broken as no 'KSFT_SKIP' definition
since commit 58e87206ab38 ("ksm_tests: skip hugepage test when Transparent
Hugepages are disabled") which requires KSFT_SKIP macro:

"""
  khugepaged.c:1195:24: error: ‘KSFT_SKIP’ undeclared (first use in this function)
"""

The KSFT_SKIP macro is defined in kselftest.h, kselftest.h is included by
vm_util.h and vm_util.h is included by khugepaged.c, this is the upstream
status and upstream doesn't have this issue.

While in rhel10, kselftest.h is not included in vm_util.h since lacking the
commit d8a866c766eb ("selftests/mm: add commentary about 9pfs bugs") and
its dependencies.

Instead of backporting the series in the late phase to introduce uncertain
of the test stability, and keep the maintainance easier in the future, here
we simply add a kselfetst.h include in khugepaged.c, this is a rhelonly
patch, but it's easy to be reverted in the future rebase.

Fixes: 58e87206ab38 ("ksm_tests: skip hugepage test when Transparent Hugepages are disabled")
Signed-off-by: Chunyu Hu <chuhu@redhat.com>