perf python: include "util/sample.h"
JIRA: https://issues.redhat.com/browse/RHEL-29795

upstream
========
commit aee1d55922977bf9282398283a72d38fc5514540
Author: Xu Yang <xu.yang_2@nxp.com>
Date: Mon Aug 19 10:34:03 2024 +0800

description
===========
The 32-bit arm build system will complain:

tools/perf/util/python.c:75:28: error: field ‘sample’ has incomplete type
   75 |         struct perf_sample sample;

However, arm64 build system doesn't complain this.

The root cause is arm64 define "HAVE_KVM_STAT_SUPPORT := 1" in
tools/perf/arch/arm64/Makefile, but arm arch doesn't define this.
This will lead to kvm-stat.h include other header files on arm64 build
system, especially "util/sample.h" for util/python.c.

This will try to directly include "util/sample.h" for "util/python.c" to
avoid such build issue on arm platform.

    Signed-off-by: Xu Yang <xu.yang_2@nxp.com>
    Cc: imx@lists.linux.dev
    Link: https://lore.kernel.org/r/20240819023403.201324-1-xu.yang_2@nxp.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Michael Petlan <mpetlan@redhat.com>