RDMA/ocrdma: Fix compiler warning
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [infiniband] ocrdma: Fix compiler warning (Prarit Bhargava) [1006333]
Rebuild_FUZZ: 91.80%
commit-author Prarit Bhargava <prarit@redhat.com>
commit bc1b04ab34a1485339571242cb0fbad823835685

drivers/infiniband/hw/ocrdma/ocrdma_verbs.c: In function ‘_ocrdma_modify_qp’:
drivers/infiniband/hw/ocrdma/ocrdma_verbs.c:1299:31: error: ‘old_qps’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  status = ocrdma_mbx_modify_qp(dev, qp, attr, attr_mask, old_qps);

ocrdma_mbx_modify_qp() (and subsequent calls) doesn't appear to use old_qps
so it doesn't need to be passed on.  Removing the variable results in the
warning going away.

	Signed-off-by: Prarit Bhargava <prarit@redhat.com>
	Acked-by: Devesh Sharma (Devesh.sharma@emulex.com)
	Signed-off-by: Roland Dreier <roland@purestorage.com>
(cherry picked from commit bc1b04ab34a1485339571242cb0fbad823835685)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>