dmaengine: qcom: fix Wvoid-pointer-to-enum-cast warning
JIRA: https://issues.redhat.com/browse/RHEL-28792
Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit 9a2136b60cc1a5ba9c5878f08a41f41271c4cd17
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Thu Aug 10 11:59:59 2023 +0200

    dmaengine: qcom: fix Wvoid-pointer-to-enum-cast warning

    'cap' is an enum, thus cast of pointer on 64-bit compile test with W=1
    causes:

      hidma.c:748:8: error: cast to smaller integer type 'enum hidma_cap' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Link: https://lore.kernel.org/r/20230810100000.123515-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>

(cherry picked from commit 9a2136b60cc1a5ba9c5878f08a41f41271c4cd17)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>