KVM: arm64: fix __kvm_host_psci_cpu_entry() prototype
JIRA: https://issues.redhat.com/browse/RHEL-1760

commit 01b94b0f3922039f7d3e0d1eeb33b8891746b65f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 24 14:18:42 2023 +0200

    KVM: arm64: fix __kvm_host_psci_cpu_entry() prototype

    The kvm_host_psci_cpu_entry() function was renamed in order to add a wrapper around
    it, but the prototype did not change, so now the missing-prototype warning came
    back in W=1 builds:

    arch/arm64/kvm/hyp/nvhe/psci-relay.c:203:28: error: no previous prototype for function '__kvm_host_psci_cpu_entry' [-Werror,-Wmissing-prototypes]
    asmlinkage void __noreturn __kvm_host_psci_cpu_entry(bool is_cpu_on)

    Fixes: dcf89d1111995 ("KVM: arm64: Add missing BTI instructions")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Marc Zyngier <maz@kernel.org>
    Link: https://lore.kernel.org/r/20230724121850.1386668-1-arnd@kernel.org
    Signed-off-by: Oliver Upton <oliver.upton@linux.dev>

Signed-off-by: Shaoqin Huang <shahuang@redhat.com>