selftests/bpf: Fix include of <sys/fcntl.h>
JIRA: https://issues.redhat.com/browse/RHEL-63880

commit 21f0b0af977203220ad58aff95e372151288ec47
Author: Tony Ambardar <tony.ambardar@gmail.com>
Date:   Mon Jul 22 22:54:37 2024 -0700

    selftests/bpf: Fix include of <sys/fcntl.h>

    Update ns_current_pid_tgid.c to use '#include <fcntl.h>' and avoid compile
    error against mips64el/musl libc:

      In file included from .../prog_tests/ns_current_pid_tgid.c:14:
      .../include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
          1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
            |  ^~~~~~~
      cc1: all warnings being treated as errors

    Fixes: 09c02d553c49 ("bpf, selftests: Fold test_current_pid_tgid_new_ns into test_progs.")
    Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/8bdc869749177b575025bf69600a4ce591822609.1721713597.git.tony.ambardar@gmail.com

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>