ASoC: amd: acp: add ACPI dependency
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 0b38362018c79bc6cf9d8ba4ee9a2a3827ba6328
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri Oct 27 17:23:52 2023 +0200

    ASoC: amd: acp: add ACPI dependency

    A newly added function requires CONFIG_ACPI to avoid a build error:

    sound/soc/amd/acp/acp-legacy-common.c: In function 'check_acp_pdm':
    sound/soc/amd/acp/acp-legacy-common.c:401:19: error: implicit declaration of function 'acpi_find_child_device'; did you mean 'acpi_match_device'? [-Werror=implicit-function-declaration]
      401 |         pdm_dev = acpi_find_child_device(ACPI_COMPANION(&pci->dev), pdm_addr, 0);
          |                   ^~~~~~~~~~~~~~~~~~~~~~
          |                   acpi_match_device

    The acp drivers really only work when ACPI is enabled already, so just
    avoid the build failure with hard dependency in everything that
    enables the acp-legacy-common portion.

    Fixes: 3a94c8ad0aae ("ASoC: amd: acp: add code for scanning acp pdm controller")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231027152403.386257-1-arnd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>