ACPI: tools: fix compilation error
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2072020
Upstream Status: v5.15-rc7

commit 136f282028dae7d9dd68469b197aa2b36b410992
Author:     Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
AuthorDate: Wed Oct  6 00:13:18 2021 -0500
Commit:     Rafael J. Wysocki <rafael.j.wysocki@intel.com>
CommitDate: Thu Oct  7 19:18:19 2021 +0200

    When ACPI tools are compiled, the following error is showed:

       $ cd tools/power/acpi
       $ make
         DESCEND tools/acpidbg
         MKDIR    include
         CP       include
         CC       tools/acpidbg/acpidbg.o
       In file included from /home/linux/tools/power/acpi/include/acpi/platform/acenv.h:152,
                        from /home/linux/tools/power/acpi/include/acpi/acpi.h:22,
                        from acpidbg.c:9:
       /home/linux/tools/power/acpi/include/acpi/platform/acgcc.h:25:10: fatal error: linux/stdarg.h: No such file or directory
          29 | #include <linux/stdarg.h>
             |          ^~~~~~~~~~~~~~~~
       compilation terminated.

    Use the ACPICA logic: just identify when it is used inside the kernel
    or by an ACPI tool.

    Fixes: c0891ac15f04 ("isystem: ship and use stdarg.h")
    Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
    [ rjw: Changelog edits ]
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Karol Herbst <kherbst@redhat.com>