kasan: test: silence intentional read overflow warnings
commit cab71f7495f7aa639ca4b8508f4c3e426e9cb2f7
Author: Kees Cook <keescook@chromium.org>
Date:   Fri Nov 19 16:43:46 2021 -0800

    kasan: test: silence intentional read overflow warnings

    As done in commit d73dad4eb5ad ("kasan: test: bypass __alloc_size
    checks") for __write_overflow warnings, also silence some more cases
    that trip the __read_overflow warnings seen in 5.16-rc1[1]:

      In file included from include/linux/string.h:253,
                       from include/linux/bitmap.h:10,
                       from include/linux/cpumask.h:12,
                       from include/linux/mm_types_task.h:14,
                       from include/linux/mm_types.h:5,
                       from include/linux/page-flags.h:13,
                       from arch/arm64/include/asm/mte.h:14,
                       from arch/arm64/include/asm/pgtable.h:12,
                       from include/linux/pgtable.h:6,
                       from include/linux/kasan.h:29,
                       from lib/test_kasan.c:10:
      In function 'memcmp',
          inlined from 'kasan_memcmp' at lib/test_kasan.c:897:2:
      include/linux/fortify-string.h:263:25: error: call to '__read_overflow' declared with attribute error: detected read beyond size of object (1st parameter)
        263 |                         __read_overflow();
            |                         ^~~~~~~~~~~~~~~~~
      In function 'memchr',
          inlined from 'kasan_memchr' at lib/test_kasan.c:872:2:
      include/linux/fortify-string.h:277:17: error: call to '__read_overflow' declared with attribute error: detected read beyond size of object (1st parameter)
        277 |                 __read_overflow();
            |                 ^~~~~~~~~~~~~~~~~

    [1] http://kisskb.ellerman.id.au/kisskb/buildresult/14660585/log/

    Link: https://lkml.kernel.org/r/20211116004111.3171781-1-keescook@chromium.org
    Fixes: d73dad4eb5ad ("kasan: test: bypass __alloc_size checks")
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Reviewed-by: Andrey Konovalov <andreyknvl@gmail.com>
    Acked-by: Marco Elver <elver@google.com>
    Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
    Cc: Alexander Potapenko <glider@google.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2048326
Signed-off-by: Nico Pache <npache@redhat.com>