sound: core: remove initialise static variables to 0
Initializing the static variable to 0 causes the following error
when exec checkpatch:

ERROR: do not initialise statics to 0
FILE: sound/sound_core.c:142:
static int preclaim_oss = 0;

In addition, considering the following way of writing
139: #ifdef config_sound_oss_core_preclaim
140: Static int preclaim_oss = 1;
141: #ELSE
142: Static int preclaim_oss = 0;
143: #ENDIF
We can optimize it by IS_ENABLED(CONFIG_SOUND_OSS_CORE_PRECLAIM),
so modified it to
static int preclaim_oss = IS_ENABLED(CONFIG_SOUND_OSS_CORE_PRECLAIM);

    Signed-off-by: Meng Tang <tangmeng@uniontech.com>
    Link: https://lore.kernel.org/r/20220228050253.1649-1-tangmeng@uniontech.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Author: Meng Tang <tangmeng@uniontech.com>
Date: Mon Feb 28 13:02:52 2022 +0800

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit d248b2771f543417dea7f9af8be05190594e0621)
Bugzilla: https://bugzilla.redhat.com/2065572