gpio_msm: Fix build error due to missing err.h
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
commit-author Stephen Boyd <sboyd@codeaurora.org>
commit 011b2039dfd46fa030138b2e2ed3c55c8341151d

drivers/gpio/gpio-msm-v1.c: In function 'gpio_msm_v1_probe':
drivers/gpio/gpio-msm-v1.c:656:2:
error: implicit declaration of function 'IS_ERR'
[-Werror=implicit-function-declaration]
drivers/gpio/gpio-msm-v1.c:657:3:
error: implicit declaration of function 'PTR_ERR'
[-Werror=implicit-function-declaration]

This driver failed to compile after commit 68515bb
(gpio_msm: Convert to use devm_ioremap_resource,
2013-06-10).

	Acked-by: Tushar Behera <tushar.behera@linaro.org>
	Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>
	Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit 011b2039dfd46fa030138b2e2ed3c55c8341151d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>