net/mlx4_en: add a missing <net/ip.h> include
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Eric Dumazet <edumazet@google.com>
commit 3aa8029e1ac4faea2967e36281d93f5d099ed6a9

Abdul Haleem reported a build error on ppc :

drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: `struct
iphdr` declared inside parameter list [enabled by default]
           struct iphdr *iph)
                  ^
drivers/net/ethernet/mellanox/mlx4/en_rx.c:582:18: warning: its scope is
only this definition or declaration, which is probably not what you want
[enabled by default]
drivers/net/ethernet/mellanox/mlx4/en_rx.c: In function
get_fixed_ipv4_csum:
drivers/net/ethernet/mellanox/mlx4/en_rx.c:586:20: error: dereferencing
pointer to incomplete type
  __u8 ipproto = iph->protocol;
                    ^

Fixes: 55469bc6b577 ("drivers: net: remove <net/busy_poll.h> inclusion when not needed")
	Signed-off-by: Eric Dumazet <edumazet@google.com>
	Reported-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 3aa8029e1ac4faea2967e36281d93f5d099ed6a9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>