hid: bpf: add BPF_JIT dependency
JIRA: https://issues.redhat.com/browse/RHEL-53898
Upstream Status: since v6.11
Tested: with the hid-tools test suite and some hardware

commit bacc15e010fc5a235fb2020b06a29a9961b5db82
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 19 11:51:07 2024 +0200

    hid: bpf: add BPF_JIT dependency

    The module does not do anything when the JIT is disabled, but instead
    causes a warning:

    In file included from include/linux/bpf_verifier.h:7,
                     from drivers/hid/bpf/hid_bpf_struct_ops.c:10:
    drivers/hid/bpf/hid_bpf_struct_ops.c: In function 'hid_bpf_struct_ops_init':
    include/linux/bpf.h:1853:50: error: statement with no effect [-Werror=unused-value]
     1853 | #define register_bpf_struct_ops(st_ops, type) ({ (void *)(st_ops); 0; })
          |                                                  ^~~~~~~~~~~~~~~~
    drivers/hid/bpf/hid_bpf_struct_ops.c:305:16: note: in expansion of macro 'register_bpf_struct_ops'
      305 |         return register_bpf_struct_ops(&bpf_hid_bpf_ops, hid_bpf_ops);
          |                ^~~~~~~~~~~~~~~~~~~~~~~

    Add a Kconfig dependency to only allow building the HID-BPF support
    when a JIT is enabled.

    Fixes: ebc0d8093e8c ("HID: bpf: implement HID-BPF through bpf_struct_ops")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://patch.msgid.link/96a00b6f-eb81-4c67-8c4b-6b1f3f045034@app.fastmail.com
    Signed-off-by: Benjamin Tissoires <bentiss@kernel.org>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>