bnx2x: Fix undefined behavior due to shift overflowing the constant
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Borislav Petkov <bp@suse.de>
commit 8dd7cdb0f473407fdcd231c3eccef07371fd5e58

Fix:

  drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c: In function ‘bnx2x_check_blocks_with_parity3’:
  drivers/net/ethernet/broadcom/bnx2x/bnx2x_main.c:4917:4: error: case label does not reduce to an integer constant
      case AEU_INPUTS_ATTN_BITS_MCP_LATCHED_SCPAD_PARITY:
      ^~~~

See https://lore.kernel.org/r/YkwQ6%2BtIH8GQpuct@zn.tnic for the gory
details as to why it triggers with older gccs only.

	Signed-off-by: Borislav Petkov <bp@suse.de>
	Cc: Ariel Elior <aelior@marvell.com>
	Cc: Sudarsana Kalluru <skalluru@marvell.com>
	Cc: Manish Chopra <manishc@marvell.com>
	Cc: Paolo Abeni <pabeni@redhat.com>
Link: https://lore.kernel.org/r/20220405151517.29753-4-bp@alien8.de
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 8dd7cdb0f473407fdcd231c3eccef07371fd5e58)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>