perf bench evlist-open-close: Use PRIu64 with u64 to fix build on 32-bit architectures
Bugzilla: https://bugzilla.redhat.com/2069070

upstream
========
commit a32762b864f889cff884249c1273819bb79a05bb
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Aug 30 15:42:57 2021 -0300

description
===========
  73     9.00 ubuntu:18.04-x-powerpc        : FAIL gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
    bench/evlist-open-close.c: In function 'bench_evlist_open_close__run':
    bench/evlist-open-close.c:173:12: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'u64 {aka long long unsigned int}' [-Werror=format=]
       pr_debug("Iteration %d took:\t%ldus\n", i, runtime_us);
                ^
    bench/../util/debug.h:18:21: note: in definition of macro 'pr_fmt'
     #define pr_fmt(fmt) fmt
                         ^~~
    bench/evlist-open-close.c:173:3: note: in expansion of macro 'pr_debug'
       pr_debug("Iteration %d took:\t%ldus\n", i, runtime_us);
       ^~~~~~~~
    cc1: all warnings being treated as errors
    /git/perf-5.14.0/tools/build/Makefile.build:139: recipe for target 'bench' failed

Fixes: 4241eabf59d5b7e9 ("perf bench: Add benchmark for evlist open/close operations")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>