net/ipv4: avoid compile error in fib_info_nh_uses_dev
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
Rebuild_CHGLOG: - [net] ipv4: avoid compile error in fib_info_nh_uses_dev (Petr Oros) [1714656]
Rebuild_FUZZ: 96.08%
commit-author Eric Dumazet <edumazet@google.com>
commit 075e264fa33e7838680802ba514a8d67433e48d1

net/ipv4/fib_frontend.c: In function 'fib_info_nh_uses_dev':
net/ipv4/fib_frontend.c:322:6: error: unused variable 'ret' [-Werror=unused-variable]
cc1: all warnings being treated as errors

Fixes: 78f2756c5fc0 ("net/ipv4: Move device validation to helper")
	Signed-off-by: Eric Dumazet <edumazet@google.com>
	Cc: David Ahern <dsahern@gmail.com>
	Reviewed-by: David Ahern <dsahern@gmail.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 075e264fa33e7838680802ba514a8d67433e48d1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>