sunrpc: avoid -Wformat-security warning
JIRA: https://issues.redhat.com/browse/RHEL-59704

commit 785280973472dbdee2c31cb740633c4b6460a8ee
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 19 12:54:22 2024 +0200

    sunrpc: avoid -Wformat-security warning

    Using a non-constant string as an sprintf-style is potentially dangerous:

    net/sunrpc/svc.c: In function 'param_get_pool_mode':
    net/sunrpc/svc.c:164:32: error: format not a string literal and no format arguments [-Werror=format-security]

    Use a literal "%s" format instead.

    Fixes: 5f71f3c32553 ("sunrpc: refactor pool_mode setting code")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Signed-off-by: Chuck Lever <chuck.lever@oracle.com>

Signed-off-by: Scott Mayhew <smayhew@redhat.com>