ACPI/IORT: Fix build when CONFIG_IOMMU_API=n
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
commit-author Qian Cai <cai@lca.pw>
commit 6b68835b5af4feb2a3f31592a52a1a68d7c1b1f3

Commit 8097e53eaba2 ("ACPI/IORT: Use helper functions to access
dev->iommu_fwspec") changed by mistake the iort_fwspec_iommu_ops() stub
definition (compiled in when CONFIG_IOMMU_API=n), that caused the
following compilation failure:

drivers/acpi/arm64/iort.c:880:1: error: expected identifier or
'(' before '{' token
 { return NULL; }
 ^
drivers/acpi/arm64/iort.c:879:39: warning: 'iort_fwspec_iommu_ops'
used but never defined
 static inline const struct iommu_ops *iort_fwspec_iommu_ops(struct device *dev);
                                       ^~~~~~~~~~~~~~~~~~~~~

Fix it.

Fixes: 8097e53eaba2 ("ACPI/IORT: Use helper functions to access dev->iommu_fwspec")
	Signed-off-by: Qian Cai <cai@lca.pw>
[lorenzo.pieralisi@arm.com: updated tags and log]
	Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
	Acked-by: Hanjun Guo <hanjun.guo@linaro.org>
	Cc: Will Deacon <will.deacon@arm.com>
	Cc: Sudeep Holla <sudeep.holla@arm.com>
	Cc: Catalin Marinas <catalin.marinas@arm.com>
	Cc: Joerg Roedel <jroedel@suse.de>
	Signed-off-by: Will Deacon <will.deacon@arm.com>
(cherry picked from commit 6b68835b5af4feb2a3f31592a52a1a68d7c1b1f3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>