net/sched: flower: Avoid overwriting error messages
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit fd23e0e250c6a7a7fd8a2ec9ab4253299471c163
Author: Ido Schimmel <idosch@nvidia.com>
Date:   Thu Apr 7 10:35:33 2022 +0300

    net/sched: flower: Avoid overwriting error messages

    The various error paths of tc_setup_offload_action() now report specific
    error messages. Remove the generic messages to avoid overwriting the
    more specific ones.

    Before:

     # tc filter add dev dummy0 ingress pref 1 proto ip flower skip_sw dst_ip 198.51.100.1 action police rate 100Mbit burst 10000
     Error: cls_flower: Failed to setup flow action.
     We have an error talking to the kernel

    After:

     # tc filter add dev dummy0 ingress pref 1 proto ip flower skip_sw dst_ip 198.51.100.1 action police rate 100Mbit burst 10000
     Error: act_police: Offload not supported when conform/exceed action is "reclassify".
     We have an error talking to the kernel

    Signed-off-by: Ido Schimmel <idosch@nvidia.com>
    Reviewed-by: Petr Machata <petrm@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>