wifi: iwlwifi: mvm: fix clang -Wformat warnings
Bugzilla: https://bugzilla.redhat.com/2136122

commit 7819b3d1dab585602905b7a213ad17ec6de6b005
Author: Justin Stitt <justinstitt@google.com>
Date:   Mon Jul 11 15:29:19 2022 -0700

    wifi: iwlwifi: mvm: fix clang -Wformat warnings
    
    When building with Clang we encounter these warnings:
    | drivers/net/wireless/intel/iwlwifi/mvm/ftm-initiator.c:1108:47: error:
    | format specifies type 'unsigned char' but the argument has type 's16'
    | (aka 'short') [-Werror,-Wformat] IWL_DEBUG_INFO(mvm, "\tburst index:
    | %hhu\n", res->ftm.burst_index);
    -
    | drivers/net/wireless/intel/iwlwifi/mvm/ftm-initiator.c:1111:47: error:
    | format specifies type 'unsigned char' but the argument has type 's32'
    | (aka 'int') [-Werror,-Wformat] IWL_DEBUG_INFO(mvm, "\trssi spread:
    | %hhu\n", res->ftm.rssi_spread);
    
    The previous format specifier `%hhu` describes a u8 but our arguments
    are wider than this which means bits are potentially being lost.
    
    Variadic functions (printf-like) undergo default argument promotion.
    Documentation/core-api/printk-formats.rst specifically recommends using
    the promoted-to-type's format flag.
    
    As per C11 6.3.1.1:
    (https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf) `If an int
    can represent all values of the original type ..., the value is
    converted to an int; otherwise, it is converted to an unsigned int.
    These are called the integer promotions.` Thus it makes sense to change
    `%hhu` to `%d` for both instances of the warning.
    
    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Kalle Valo <kvalo@kernel.org>
    Link: https://lore.kernel.org/r/20220711222919.2043613-1-justinstitt@google.com

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>