KVM: selftests: Fix KVM_EXCEPTION_MAGIC build with Clang
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2119111

commit 67ef8664cc5b113f6c49b01d2a0e4cbc589623dd
Author: David Matlack <dmatlack@google.com>
Date:   Fri Jul 22 23:48:37 2022 +0000

    KVM: selftests: Fix KVM_EXCEPTION_MAGIC build with Clang

    Change KVM_EXCEPTION_MAGIC to use the all-caps "ULL", rather than lower
    case. This fixes a build failure with Clang:

      In file included from x86_64/hyperv_features.c:13:
      include/x86_64/processor.h:825:9: error: unexpected token in argument list
              return kvm_asm_safe("wrmsr", "a"(val & -1u), "d"(val >> 32), "c"(msr));
                     ^
      include/x86_64/processor.h:802:15: note: expanded from macro 'kvm_asm_safe'
              asm volatile(KVM_ASM_SAFE(insn)                 \
                           ^
      include/x86_64/processor.h:785:2: note: expanded from macro 'KVM_ASM_SAFE'
              "mov $" __stringify(KVM_EXCEPTION_MAGIC) ", %%r9\n\t"   \
              ^
      <inline asm>:1:18: note: instantiated into assembly here
              mov $0xabacadabaull, %r9
                              ^

    Fixes: 3b23054cd3f5 ("KVM: selftests: Add x86-64 support for exception fixup")
    Signed-off-by: David Matlack <dmatlack@google.com>
    Reviewed-by: Sean Christopherson <seanjc@google.com>
    Message-Id: <20220722234838.2160385-2-dmatlack@google.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>