ipv6: remove dependency of nf_defrag_ipv6 on ipv6 module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Florian Westphal <fw@strlen.de>
commit 70b095c84326640eeacfd69a411db8fc36e8ab1a

IPV6=m
DEFRAG_IPV6=m
CONNTRACK=y yields:

net/netfilter/nf_conntrack_proto.o: In function `nf_ct_netns_do_get':
net/netfilter/nf_conntrack_proto.c:802: undefined reference to `nf_defrag_ipv6_enable'
net/netfilter/nf_conntrack_proto.o:(.rodata+0x640): undefined reference to `nf_conntrack_l4proto_icmpv6'

Setting DEFRAG_IPV6=y causes undefined references to ip6_rhash_params
ip6_frag_init and ip6_expire_frag_queue so it would be needed to force
IPV6=y too.

This patch gets rid of the 'followup linker error' by removing
the dependency of ipv6.ko symbols from netfilter ipv6 defrag.

Shared code is placed into a header, then used from both.

	Signed-off-by: Florian Westphal <fw@strlen.de>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit 70b095c84326640eeacfd69a411db8fc36e8ab1a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>