tools/sched_ext: fix scx_show_state.py for scx_root change
JIRA: https://issues.redhat.com/browse/RHEL-151616

commit f92ff79ba2640fc482bf2bfb5b42e33957f90caf
Author: Kohei Enju <enjuk@amazon.com>
Date:   Fri Dec 26 17:46:49 2025 +0900

    tools/sched_ext: fix scx_show_state.py for scx_root change

    Commit 48e126777386 ("sched_ext: Introduce scx_sched") introduced
    scx_root and removed scx_ops, causing scx_show_state.py to fail when
    searching for the 'scx_ops' object. [1]

    Fix by using 'scx_root' instead, with NULL pointer handling.

    [1]
     # drgn -s vmlinux ./tools/sched_ext/scx_show_state.py
     Traceback (most recent call last):
       File "/root/.venv/bin/drgn", line 8, in <module>
         sys.exit(_main())
                  ~~~~~^^
       File "/root/.venv/lib64/python3.14/site-packages/drgn/cli.py", line 625, in _main
         runpy.run_path(
         ~~~~~~~~~~~~~~^
             script_path, init_globals={"prog": prog}, run_name="__main__"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         )
         ^
       File "<frozen runpy>", line 287, in run_path
       File "<frozen runpy>", line 98, in _run_module_code
       File "<frozen runpy>", line 88, in _run_code
       File "./tools/sched_ext/scx_show_state.py", line 30, in <module>
         ops = prog['scx_ops']
               ~~~~^^^^^^^^^^^
     _drgn.ObjectNotFoundError: could not find 'scx_ops'

    Fixes: 48e126777386 ("sched_ext: Introduce scx_sched")
    Signed-off-by: Kohei Enju <enjuk@amazon.com>
    Reviewed-by: Emil Tsalapatis <emil@etsalapatis.com>
    Signed-off-by: Tejun Heo <tj@kernel.org>

Signed-off-by: Phil Auld <pauld@redhat.com>