qed: Fix static checker warning
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Rahul Verma <Rahul.Verma@cavium.com>
commit 68203a67a7024c5d0b8e545d3d370b1fec971551

	Static Checker Warnings:
	drivers/net/ethernet/qlogic/qed/qed_main.c:1510 qed_fill_link_capability()
	error: uninitialized symbol 'tcvr_state'.
	drivers/net/ethernet/qlogic/qed/qed_mcp.c:1951 qed_mcp_trans_speed_mask()
	error: uninitialized symbol 'transceiver_state'.
	drivers/net/ethernet/qlogic/qed/qed_mcp.c:1951 qed_mcp_trans_speed_mask()
	error: uninitialized symbol 'transceiver_type'.

	Symbols tcvr_state, transceiver_state and transceiver_type
	are initialized with respective default state.

Fixes: c56a8be7e7aa ("qed: Add supported link and advertise link to display in ethtool.")
	Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
	Signed-off-by: Rahul Verma <Rahul.Verma@cavium.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 68203a67a7024c5d0b8e545d3d370b1fec971551)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>