s390/lcs: add braces around empty function body
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-408.el8
commit-author Heiko Carstens <hca@linux.ibm.com>
commit 09ae598271f8cfe46148cece8e03509b9da16334

Fix allmodconfig + W=1 compile breakage:

drivers/s390/net/lcs.c: In function ‘lcs_get_frames_cb’:
drivers/s390/net/lcs.c:1823:25: error: suggest braces around empty body in an ‘else’ statement [-Werror=empty-body]
 1823 |                         ; // FIXME: error message ?
      |                         ^

	Acked-by: Julian Wiedmann <jwi@linux.ibm.com>
	Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
	Signed-off-by: Karsten Graul <kgraul@linux.ibm.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 09ae598271f8cfe46148cece8e03509b9da16334)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>