scsi: target: sbitmap: add seq_file forward declaration
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 14b470b56840dbb093abd71f214e9d63770c87b8

The target core runs into a warning in the linux/sbitmap.h
file in some configurations:

In file included from include/target/target_core_base.h:7,
                 from drivers/target/target_core_fabric_lib.c:41:
include/linux/sbitmap.h:331:46: error: 'struct seq_file' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 void sbitmap_show(struct sbitmap *sb, struct seq_file *m);
                                              ^~~~~~~~

In general, headers should not depend on others being included first,
so this fixes it with a forward declaration for that struct name, but
we probably want to merge the patch through the scsi tree to help
bisection.

Fixes: 10e9cbb6b531 ("scsi: target: Convert target drivers to use sbitmap")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Reviewed-by: Bart Van Assche <bart.vanassche@wdc.com>
	Reviewed-by: Omar Sandoval <osandov@fb.com>
	Reviewed-by: Jens Axboe <axboe@kernel.dk>
	Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit 14b470b56840dbb093abd71f214e9d63770c87b8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>