kasan: arm64: fix pcpu_page_first_chunk crash with KASAN_VMALLOC
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2076088

commit 3252b1d8309ea42bc6329d9341072ecf1c9505c0
Author: Kefeng Wang <wangkefeng.wang@huawei.com>
Date: Fri, 5 Nov 2021 13:39:47 -0700

    With KASAN_VMALLOC and NEED_PER_CPU_PAGE_FIRST_CHUNK the kernel crashes:

      Unable to handle kernel paging request at virtual address ffff7000028f2000
      ...
      swapper pgtable: 64k pages, 48-bit VAs, pgdp=0000000042440000
      [ffff7000028f2000] pgd=000000063e7c0003, p4d=000000063e7c0003, pud=000000063e7c0003, pmd=000000063e7b0003, pte=0000000000000000
      Internal error: Oops: 96000007 [#1] PREEMPT SMP
      Modules linked in:
      CPU: 0 PID: 0 Comm: swapper Not tainted 5.13.0-rc4-00003-gc6e6e28f3f30-dirty #62
      Hardware name: linux,dummy-virt (DT)
      pstate: 200000c5 (nzCv daIF -PAN -UAO -TCO BTYPE=--)
      pc : kasan_check_range+0x90/0x1a0
      lr : memcpy+0x88/0xf4
      sp : ffff80001378fe20
      ...
      Call trace:
       kasan_check_range+0x90/0x1a0
       pcpu_page_first_chunk+0x3f0/0x568
       setup_per_cpu_areas+0xb8/0x184
       start_kernel+0x8c/0x328

    The vm area used in vm_area_register_early() has no kasan shadow memory,
    Let's add a new kasan_populate_early_vm_area_shadow() function to
    populate the vm area shadow memory to fix the issue.

    [wangkefeng.wang@huawei.com: fix redefinition of 'kasan_populate_early_vm_area_shadow']
      Link: https://lkml.kernel.org/r/20211011123211.3936196-1-wangkefeng.wang@huawei.com

    Link: https://lkml.kernel.org/r/20210910053354.26721-4-wangkefeng.wang@huawei.com
    Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
    Acked-by: Marco Elver <elver@google.com>		[KASAN]
    Acked-by: Andrey Konovalov <andreyknvl@gmail.com>	[KASAN]
    Acked-by: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Will Deacon <will@kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Mark Salter <msalter@redhat.com>