wifi: ath9k: use proper statements in conditionals
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-477.10.1.el8_8
commit-author Arnd Bergmann <arnd@arndb.de>
commit b7dc753fe33a707379e2254317794a4dad6c0fe2

A previous cleanup patch accidentally broke some conditional
expressions by replacing the safe "do {} while (0)" constructs
with empty macros. gcc points this out when extra warnings
are enabled:

drivers/net/wireless/ath/ath9k/hif_usb.c: In function 'ath9k_skb_queue_complete':
drivers/net/wireless/ath/ath9k/hif_usb.c:251:57: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
  251 |                         TX_STAT_INC(hif_dev, skb_failed);

Make both sets of macros proper expressions again.

Fixes: d7fc76039b74 ("ath9k: htc: clean up statistics macros")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
	Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20221215165553.1950307-1-arnd@kernel.org
(cherry picked from commit b7dc753fe33a707379e2254317794a4dad6c0fe2)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>