ALSA: core: Use dev_name of card_dev as debugfs directory name
JIRA: https://issues.redhat.com/browse/RHEL-13724

commit 091c2848b0f7643eeb44abc1e7ba8f9ef5eb366f
Author: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Date: Tue Sep 12 14:01:13 2023 +0300

    ALSA: core: Use dev_name of card_dev as debugfs directory name

    There is no need to use temporary string for the debugfs directory name as
    we can use the device name of the card.

    This change will also fixes the following compiler warning/error (W=1):

    sound/core/init.c: In function ‘snd_card_init’:
    sound/core/init.c:367:28: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 4 [-Werror=format-overflow=]
      367 |         sprintf(name, "card%d", idx);
          |                            ^~
    sound/core/init.c:367:23: note: directive argument in the range [0, 2147483646]
      367 |         sprintf(name, "card%d", idx);
          |                       ^~~~~~~~
    sound/core/init.c:367:9: note: ‘sprintf’ output between 6 and 15 bytes into a destination of size 8
      367 |         sprintf(name, "card%d", idx);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

    The idx is guarantied to be less than SNDRV_CARDS (max 256 or 8) by the
    code in snd_card_init(), however the compiler does not see that.

    The warnings got brought to light by a recent patch upstream:
    commit 6d4ab2e97dcf ("extrawarn: enable format and stringop overflow warnings in W=1")

    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Suggested-by: Takashi Iwai <tiwai@suse.de>
    Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Link: https://lore.kernel.org/r/20230912110113.3166-1-peter.ujfalusi@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>