device property: Define type of PROPERTY_ENRTY_*() macros
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Andy Shevchenko <andriy.shevchenko@linux.intel.com>
commit c505cbd45f6e9c539d57dd171d95ec7e5e9f9cd0

Some of the drivers may use the macro at runtime flow, like

  struct property_entry p[10];
...
  p[index++] = PROPERTY_ENTRY_U8("u8 property", u8_data);

In that case and absence of the data type compiler fails the build:

drivers/char/ipmi/ipmi_dmi.c:79:29: error: Expected ; at end of statement
drivers/char/ipmi/ipmi_dmi.c:79:29: error: got {

	Acked-by: Corey Minyard <cminyard@mvista.com>
	Cc: Corey Minyard <minyard@acm.org>
	Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit c505cbd45f6e9c539d57dd171d95ec7e5e9f9cd0)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>