perf tools: Be consistent on the type of map->symbols[] interator
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-693.el7
Rebuild_CHGLOG: - [perf] tools: Be consistent on the type of map->symbols[] interator (Jiri Olsa) [1140522]
Rebuild_FUZZ: 93.44%
commit-author Arnaldo Carvalho de Melo <acme@redhat.com>
commit a0b2f5af4c99d3da7ce9bc2b3b4641c8ffd22615

In a few cases we were using 'enum map_type' and that triggered this
warning when using clang:

  util/session.c:1923:16: error: comparison of constant 2 with expression of type 'enum map_type' is always true
      [-Werror,-Wtautological-constant-out-of-range-compare]
        for (i = 0; i < MAP__NR_TYPES; ++i) {

	Cc: Adrian Hunter <adrian.hunter@intel.com>
	Cc: David Ahern <dsahern@gmail.com>
	Cc: Jiri Olsa <jolsa@kernel.org>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Wang Nan <wangnan0@huawei.com>
Link: http://lkml.kernel.org/n/tip-i6uyo6bsopa2dghnx8qo7rri@git.kernel.org
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit a0b2f5af4c99d3da7ce9bc2b3b4641c8ffd22615)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>