vfio-mdev: add back CONFIG_VFIO dependency
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2188088

commit de858a05c9d8cecfb294d3cb89e491a36b8688fd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jan 26 22:08:31 2023 +0100

    vfio-mdev: add back CONFIG_VFIO dependency

    CONFIG_VFIO_MDEV cannot be selected when VFIO itself is
    disabled, otherwise we get a link failure:

    WARNING: unmet direct dependencies detected for VFIO_MDEV
      Depends on [n]: VFIO [=n]
      Selected by [y]:
      - SAMPLE_VFIO_MDEV_MTTY [=y] && SAMPLES [=y]
      - SAMPLE_VFIO_MDEV_MDPY [=y] && SAMPLES [=y]
      - SAMPLE_VFIO_MDEV_MBOCHS [=y] && SAMPLES [=y]
    /home/arnd/cross/arm64/gcc-13.0.1-nolibc/x86_64-linux/bin/x86_64-linux-ld: samples/vfio-mdev/mdpy.o: in function `mdpy_remove':
    mdpy.c:(.text+0x1e1): undefined reference to `vfio_unregister_group_dev'
    /home/arnd/cross/arm64/gcc-13.0.1-nolibc/x86_64-linux/bin/x86_64-linux-ld: samples/vfio-mdev/mdpy.o: in function `mdpy_probe':
    mdpy.c:(.text+0x149e): undefined reference to `_vfio_alloc_device'

    Fixes: 8bf8c5ee1f38 ("vfio-mdev: turn VFIO_MDEV into a selectable symbol")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20230126211211.1762319-1-arnd@kernel.org
    Signed-off-by: Alex Williamson <alex.williamson@redhat.com>

Signed-off-by: Alex Williamson <alex.williamson@redhat.com>