netfilter: conntrack: use correct format characters
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2111270
Upstream Status: commit b8acd43148c0

commit b8acd43148c067376f76faed9be138aa0e25414c
Author: Bill Wendling <isanbard@gmail.com>
Date:   Thu Jun 9 22:16:31 2022 +0000

    netfilter: conntrack: use correct format characters

    When compiling with -Wformat, clang emits the following warnings:

    net/netfilter/nf_conntrack_helper.c:168:18: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
                    request_module(mod_name);
                                   ^~~~~~~~

    Use a string literal for the format string.

    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Signed-off-by: Bill Wendling <isanbard@gmail.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>