usb: typec: hd3ss3220: Drop of_match_ptr for ID table
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-526.el8
commit-author Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
commit 45e7c9e448e345f27c4329d0395946f4a9cfd8c3

The driver can match only via the DT table so the table should be always
used and the of_match_ptr does not have any sense (this also allows ACPI
matching via PRP0001, even though it is not relevant here).

  drivers/usb/typec/hd3ss3220.c:284:34: error: ‘dev_ids’ defined but not used [-Werror=unused-const-variable=]

	Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
	Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
	Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/20230310222937.315773-1-krzysztof.kozlowski@linaro.org
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 45e7c9e448e345f27c4329d0395946f4a9cfd8c3)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>