RDMA/ionic: Fix build failure on SPARC due to xchg() operand size
JIRA: https://issues.redhat.com/browse/RHEL-121486

commit ed9836c040bac2823dffd4e10c107206d88ac548
Author: Abhijit Gangurde <abhijit.gangurde@amd.com>
Date:   Fri Sep 19 17:43:00 2025 +0530

    RDMA/ionic: Fix build failure on SPARC due to xchg() operand size

    xchg() is used to safely handle the event queue arming.
    However SPARC xchg operates only 4B of variable.
    Change variable type from bool to int.

    Unverified Error/Warning (likely false positive, kindly check if interested):

        ERROR: modpost: "__xchg_called_with_bad_pointer" [drivers/infiniband/hw/ionic/ionic_rdma.ko] undefined!

    Error/Warning ids grouped by kconfigs:

    recent_errors
    `-- sparc-allmodconfig
        `-- ERROR:__xchg_called_with_bad_pointer-drivers-infiniband-hw-ionic-ionic_rdma.ko-undefined

    Fixes: f3bdbd42702c ("RDMA/ionic: Create device queues to support admin operations")
    Reported-by: Leon Romanovsky <leon@kernel.org>
    Closes: https://lore.kernel.org/lkml/20250918180750.GA135135@unreal/
    Signed-off-by: Abhijit Gangurde <abhijit.gangurde@amd.com>
    Link: https://patch.msgid.link/20250919121301.1113759-1-abhijit.gangurde@amd.com
    Signed-off-by: Leon Romanovsky <leon@kernel.org>

Signed-off-by: Jakub Ramaseuski <jramaseu@redhat.com>