HID: ft260: fix a NULL pointer dereference in ft260_i2c_write
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2166610
Upstream Status: since v6.2
Tested: with the hid-tools test suite and some hardware

commit c2500bdffe5a95fbd0aecdd5be3d2f175ad22f92
Author: Michael Zaidman <michael.zaidman@gmail.com>
Date:   Sat Nov 5 23:11:49 2022 +0200

    HID: ft260: fix a NULL pointer dereference in ft260_i2c_write

    The zero-length passed into the ft260_i2c_write() triggered the
    NULL pointer dereference in the debug message on data[0] access.
    Since the controller does not support a write of zero length,
    let's not allow it.

    Before:

    $ sudo i2ctransfer -y 13 w0@0x51
    Killed

    After:

    $ sudo i2ctransfer -y 13 w0@0x51
    Error: Sending messages failed: Invalid argument

    Reported-by: Enrik Berkhan <Enrik.Berkhan@inka.de>
    Signed-off-by: Michael Zaidman <michael.zaidman@gmail.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>