crashdump: add CONFIG_KEYS dependency
JIRA: https://issues.redhat.com/browse/RHEL-29040

Upstream Status: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

commit b6f5e748587063d4ad3294d07ca29886851d9cd7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 20 13:21:22 2025 +0200

    crashdump: add CONFIG_KEYS dependency

    The dm_crypt code fails to build without CONFIG_KEYS:

    kernel/crash_dump_dm_crypt.c: In function 'restore_dm_crypt_keys_to_thread_keyring':
    kernel/crash_dump_dm_crypt.c:105:9: error: unknown type name 'key_ref_t'; did you mean 'key_ref_put'?

    There is a mix of 'select KEYS' and 'depends on KEYS' in Kconfig,
    so there is no single obvious solution here, but generally using 'depends on'
    makes more sense and is less likely to cause dependency loops.

    Link: https://lkml.kernel.org/r/20250620112140.3396316-1-arnd@kernel.org
    Fixes: 62f17d9df692 ("crash_dump: retrieve dm crypt keys in kdump kernel")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: Alexander Graf <graf@amazon.com>
    Cc: Baoquan He <bhe@redhat.com>
    Cc: Coiby Xu <coxu@redhat.com>
    Cc: Dave Vasilevsky <dave@vasilevsky.ca>
    Cc: Eric Biggers <ebiggers@google.com>
    Cc: Michael Ellerman <mpe@ellerman.id.au>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Signed-off-by: Coiby Xu <coxu@redhat.com>