pinctrl: core: Fix a bunch of kerneldoc issues
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Lee Jones <lee.jones@linaro.org>
commit 9c340bbbf7203ebaa7286eb2cd3b21b5e142ed3b

Most are likely due to bitrot/API slip.  Some are formatting issues.

Fixes the following W=1 kernel build warning(s):

 drivers/pinctrl/core.c:167: warning: Function parameter or member 'pin' not described in 'pin_get_name'
 drivers/pinctrl/core.c:167: warning: Excess function parameter 'name' description in 'pin_get_name'
 drivers/pinctrl/core.c:584: warning: Function parameter or member 'selector' not described in 'pinctrl_generic_get_group'
 drivers/pinctrl/core.c:584: warning: Excess function parameter 'gselector' description in 'pinctrl_generic_get_group'
 drivers/pinctrl/core.c:1356: error: Cannot parse struct or union!
 drivers/pinctrl/core.c:1458: warning: Function parameter or member 'map' not described in 'pinctrl_unregister_mappings'
 drivers/pinctrl/core.c:1458: warning: Excess function parameter 'maps' description in 'pinctrl_unregister_mappings'
 drivers/pinctrl/core.c:2239: warning: Function parameter or member 'pctldev' not described in 'devm_pinctrl_register_and_init'

	Signed-off-by: Lee Jones <lee.jones@linaro.org>
Link: https://lore.kernel.org/r/20200713144930.1034632-12-lee.jones@linaro.org
	Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit 9c340bbbf7203ebaa7286eb2cd3b21b5e142ed3b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>