usb: host: xhci-rcar: drop of_match_ptr for ID table
JIRA: https://issues.redhat.com/browse/RHEL-15948

commit d6cfb252107d36fdddb66891c16d34a346882c36
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date: Sat, 11 Mar 2023 18:36:18 +0100

  The driver can match only via the DT table so the table should be always
  used and the of_match_ptr does not have any sense (this also allows ACPI
  matching via PRP0001, even though it might not be relevant here).

    drivers/usb/host/xhci-rcar.c:269:34: error: ‘usb_xhci_of_match’ defined but not used [-Werror=unused-const-variable=]

  Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
  Link: https://lore.kernel.org/r/20230311173624.263189-1-krzysztof.kozlowski@linaro.org
  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Desnes Nunes <desnesn@redhat.com>