drm/amd/display: shrink struct members
JIRA: https://issues.redhat.com/browse/RHEL-135337

commit f1ae589310e1aa58255e8b02c87a6ae97443ccb3
Author: Rosen Penev <rosenp@gmail.com>
Date:   Sat Nov 8 09:40:47 2025 -0800

    drm/amd/display: shrink struct members

    [ Upstream commit 7329417fc9ac128729c3a092b006c8f1fd0d04a6 ]

    On a 32-bit ARM system, the audio_decoder struct ends up being too large
    for dp_retrain_link_dp_test.

    link_dp_cts.c:157:1: error: the frame size of 1328 bytes is larger than
    1280 bytes [-Werror=frame-larger-than=]

    This is mitigated by shrinking the members of the struct and avoids
    having to deal with dynamic allocation.

    feed_back_divider is assigned but otherwise unused. Remove both.

    pixel_repetition looks like it should be a bool since it's only ever
    assigned to 1. But there are checks for 2 and 4. Reduce to uint8_t.

    Remove ss_percentage_divider. Unused.

    Shrink refresh_rate as it gets assigned to at most a 3 digit integer
    value.

    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    Reviewed-by: Alex Hung <alex.hung@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    (cherry picked from commit 3849efdc7888d537f09c3dcfaea4b3cd377a102e)
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: José Expósito <jexposit@redhat.com>