amd-xgbe: fix clang -Wformat warnings
JIRA: https://issues.redhat.com/browse/RHEL-62004

commit 2afe46474ba3fd3ae6e016bab57efd73f4b96175
Author: Justin Stitt <justinstitt@google.com>
Date:   Fri Jul 8 16:26:53 2022 -0700

    amd-xgbe: fix clang -Wformat warnings

    When building with Clang we encounter the following warning:
    | drivers/net/ethernet/amd/xgbe/xgbe-dcb.c:234:42: error: format specifies
    | type 'unsigned char' but the argument has type '__u16' (aka 'unsigned
    | short') [-Werror,-Wformat] pfc->pfc_cap, pfc->pfc_en, pfc->mbc,
    | pfc->delay);

    pfc->pfc_cap , pfc->pfc_cn, pfc->mbc are all of type `u8` while pfc->delay is
    of type `u16`. The correct format specifiers `%hh[u|x]` were used for
    the first three but not for pfc->delay, which is causing the warning
    above.

    Variadic functions (printf-like) undergo default argument promotion.
    Documentation/core-api/printk-formats.rst specifically recommends using
    the promoted-to-type's format flag. In this case `%d` (or `%x` to
    maintain hex representation) should be used since both u8's and u16's
    are fully representable by an int.

    Moreover, C11 6.3.1.1 states:
    (https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf) `If an int
    can represent all values of the original type ..., the value is
    converted to an int; otherwise, it is converted to an unsigned int.
    These are called the integer promotions.`

    Link: https://github.com/ClangBuiltLinux/linux/issues/378
    Signed-off-by: Justin Stitt <justinstitt@google.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Tested-by: Nick Desaulniers <ndesaulniers@google.com>
    Link: https://lore.kernel.org/r/20220708232653.556488-1-justinstitt@google.com
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>