scripts/bpf: Emit an #error directive known types list needs updating
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [scripts] bpf: Emit an #error directive known types list needs updating (Yauheni Kaliuta) [1772081]
Rebuild_FUZZ: 93.85%
commit-author Jakub Sitnicki <jakub@cloudflare.com>
commit 456a513bb5d494f169271b16334049d50c7e630b

Make the compiler report a clear error when bpf_helpers_doc.py needs
updating rather than rely on the fact that Clang fails to compile
English:

../../../lib/bpf/bpf_helper_defs.h:2707:1: error: unknown type name 'Unrecognized'
Unrecognized type 'struct bpf_inet_lookup', please add it to known types!

	Signed-off-by: Jakub Sitnicki <jakub@cloudflare.com>
	Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Link: https://lore.kernel.org/bpf/20191016085811.11700-1-jakub@cloudflare.com
(cherry picked from commit 456a513bb5d494f169271b16334049d50c7e630b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>