perf/core: Remove unused perf_cgroup_event_cgrp_time() function
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Matthias Kaehlcke <mka@chromium.org>
commit d0fabd1cb8b70073a0f44f1cf8b663b5e7241c74

The function was added by commit e5d1367f17ba ("perf: Add cgroup
support") in 2011 and hasn't been used since then. Removing it fixes the
following warning when building with Clang:

    kernel/events/core.c:696:19: error: unused function 'perf_cgroup_event_cgrp_time' [-Werror,-Wunused-function]

	Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Arnaldo Carvalho de Melo <acme@kernel.org>
	Cc: Douglas Anderson <dianders@chromium.org>
	Cc: Linus Torvalds <torvalds@linux-foundation.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Cc: Thomas Gleixner <tglx@linutronix.de>
Link: http://lkml.kernel.org/r/20170523215132.189049-1-mka@chromium.org
	Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit d0fabd1cb8b70073a0f44f1cf8b663b5e7241c74)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>