drm/amd/display: fix is_timing_changed() prototype
JIRA: https://issues.redhat.com/browse/RHEL-846
Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (v6.3.13)

commit b8fdee2f0ed8dd0e3fca8e9ff1fc7d670dd51ac5
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Tue Apr 18 00:07:18 2023 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Tue Jul 11 19:39:32 2023 +0200

    [ Upstream commit 3306ba4b60b2f3d9ac6bddc587a4d702e1ba2224 ]

    Three functions in the amdgpu display driver cause -Wmissing-prototype
    warnings:

    drivers/gpu/drm/amd/amdgpu/../display/dc/core/dc_resource.c:1858:6: error: no previous prototype for 'is_timing_changed' [-Werror=missing-prototypes]

    is_timing_changed() is actually meant to be a global symbol, but needs
    a proper name and prototype.

    Fixes: 17ce8a6907f7 ("drm/amd/display: Add dsc pre-validation in atomic check")
    Reviewed-by: Aurabindo Pillai <aurabindo.pillai@amd.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: Mika Penttilä <mpenttil@redhat.com>