PCI: mt7621: Convert driver into 'bool'
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2052155
Upstream Status: aa50faff4416c869b52dff68a937c84d29e12f4b

commit aa50faff4416c869b52dff68a937c84d29e12f4b
Author: Sergio Paracuellos <sergio.paracuellos@gmail.com>
Date:   Wed Dec 1 22:34:02 2021 +0100

    PCI: mt7621: Convert driver into 'bool'

    The driver is not ready yet to be compiled as a module since it depends
    on some symbols not exported on MIPS.  We have the following current
    problems:

      Building mips:allmodconfig ... failed
      --------------
      Error log:
      ERROR: modpost: missing MODULE_LICENSE() in drivers/pci/controller/pcie-mt7621.o
      ERROR: modpost: "mips_cm_unlock_other" [drivers/pci/controller/pcie-mt7621.ko] undefined!
      ERROR: modpost: "mips_cpc_base" [drivers/pci/controller/pcie-mt7621.ko] undefined!
      ERROR: modpost: "mips_cm_lock_other" [drivers/pci/controller/pcie-mt7621.ko] undefined!
      ERROR: modpost: "mips_cm_is64" [drivers/pci/controller/pcie-mt7621.ko] undefined!
      ERROR: modpost: "mips_gcr_base" [drivers/pci/controller/pcie-mt7621.ko] undefined!

    Temporarily move from 'tristate' to 'bool' until a better solution is
    ready.

    Also RALINK is redundant because SOC_MT7621 already depends on it.
    Hence, simplify condition.

    Fixes: 2bdd5238e756 ("PCI: mt7621: Add MediaTek MT7621 PCIe host controller driver").
    Signed-off-by: Sergio Paracuellos <sergio.paracuellos@gmail.com>
    Reviewed-and-Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Myron Stowe <mstowe@redhat.com>