tracing: Annotate ftrace_graph_hash pointer with __rcu
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Amol Grover <frextrite@gmail.com>
commit 24a9729f831462b1d9d61dc85ecc91c59037243f

Fix following instances of sparse error
kernel/trace/ftrace.c:5664:29: error: incompatible types in comparison
kernel/trace/ftrace.c:5785:21: error: incompatible types in comparison
kernel/trace/ftrace.c:5864:36: error: incompatible types in comparison
kernel/trace/ftrace.c:5866:25: error: incompatible types in comparison

Use rcu_dereference_protected to access the __rcu annotated pointer.

Link: http://lkml.kernel.org/r/20200201072703.17330-1-frextrite@gmail.com

	Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
	Signed-off-by: Amol Grover <frextrite@gmail.com>
	Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
(cherry picked from commit 24a9729f831462b1d9d61dc85ecc91c59037243f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>