perf probe: Fix compiles due to declarations using perf_probe_point
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-327.el7
Rebuild_CHGLOG: - [perf] probe: Fix compiles due to declarations using perf_probe_point (Jiri Olsa) [1222189]
Rebuild_FUZZ: 96.12%
commit-author David Ahern <david.ahern@oracle.com>
commit 6d4a48968bfb5c67002f253fbaeb5acd41d7897a

perf fails to build with gcc "(GCC) 4.4.7 20120313 (Red Hat
4.4.7-4.0.9)" (a.k.a., RHEL6 / CentOS 6 / OL 6):

  cc1: warnings being treated as errors
  util/probe-event.c: In function ‘get_alternative_line_range’:
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for ‘pp.file’)
  util/probe-event.c:359: error: missing initializer
  util/probe-event.c:359: error: (near initialization for ‘result.function’)

Fix by bringing in initializers to declaration.

	Signed-off-by: David Ahern <david.ahern@oracle.com>
	Cc: Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
Link: http://lkml.kernel.org/r/1426084580-60780-1-git-send-email-david.ahern@oracle.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 6d4a48968bfb5c67002f253fbaeb5acd41d7897a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>