ACPI: processor: Remove initialization of static variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Tian Tao <tiantao6@hisilicon.com>
commit 41103b3bbe37bbefe78562f915f799598e2b560c

Address the following checkpatch error:

ERROR: do not initialise statics to false

	Signed-off-by: Tian Tao <tiantao6@hisilicon.com>
[ rjw: Subject and changelog edits ]
	Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 41103b3bbe37bbefe78562f915f799598e2b560c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>