powerpc/mm: fix "section_base" set but not used
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-486.el8
commit-author Qian Cai <cai@lca.pw>
commit c38ca265525a00d635219450e8fcc858082ff630

The commit 24b6d4164348 ("mm: pass the vmem_altmap to vmemmap_free")
removed a line in vmemmap_free(),

altmap = to_vmem_altmap((unsigned long) section_base);

but left a variable no longer used.

arch/powerpc/mm/init_64.c: In function 'vmemmap_free':
arch/powerpc/mm/init_64.c:277:16: error: variable 'section_base' set but
not used [-Werror=unused-but-set-variable]

	Signed-off-by: Qian Cai <cai@lca.pw>
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit c38ca265525a00d635219450e8fcc858082ff630)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>