bpf: Fix BPF_INTERNAL namespace import
JIRA: https://issues.redhat.com/browse/RHEL-110269

Upstream status: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.12.y

commit 92c6f8c577a0ca52d779d3a4d42465bd81f854a1
Author: Xi Ruoyao <xry111@xry111.site>
Date:   Sat May 3 16:50:31 2025 +0800

    bpf: Fix BPF_INTERNAL namespace import

    The commit cdd30ebb1b9f ("module: Convert symbol namespace to string
    literal") makes the grammar of MODULE_IMPORT_NS and EXPORT_SYMBOL_NS
    different between the stable branches and the mainline.  But when
    the commit 955f9ede52b8 ("bpf: Add namespace to BPF internal symbols")
    was backported from mainline, only EXPORT_SYMBOL_NS instances are
    adapted, leaving the MODULE_IMPORT_NS instance with the "new" grammar
    and causing the module fails to build:

        ERROR: modpost: module bpf_preload uses symbol bpf_link_get_from_fd from namespace BPF_INTERNAL, but does not import it.
        ERROR: modpost: module bpf_preload uses symbol kern_sys_bpf from namespace BPF_INTERNAL, but does not import it.

    Reported-by: Mingcong Bai <jeffbai@aosc.io>
    Reported-by: Alex Davis <alex47794@gmail.com>
    Closes: https://lore.kernel.org/all/CADiockBKBQTVqjA5G+RJ9LBwnEnZ8o0odYnL=LBZ_7QN=_SZ7A@mail.gmail.com/
    Fixes: 955f9ede52b8 ("bpf: Add namespace to BPF internal symbols")
    Signed-off-by: Xi Ruoyao <xry111@xry111.site>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Gregory Bell <grbell@redhat.com>