libeth: xdp: Disable generic kCFI pass for libeth_xdp_tx_xmit_bulk()
JIRA: https://issues.redhat.com/browse/RHEL-130763
Upstream Status: net-next.git commit c57f5fee54dfc83ee1d7f70f7beb9410b8466e9e

commit c57f5fee54dfc83ee1d7f70f7beb9410b8466e9e
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Sat Oct 25 21:53:20 2025 +0100

    libeth: xdp: Disable generic kCFI pass for libeth_xdp_tx_xmit_bulk()

    When building drivers/net/ethernet/intel/idpf/xsk.c for ARCH=arm with
    CONFIG_CFI=y using a version of LLVM prior to 22.0.0, there is a
    BUILD_BUG_ON failure:

      $ cat arch/arm/configs/repro.config
      CONFIG_BPF_SYSCALL=y
      CONFIG_CFI=y
      CONFIG_IDPF=y
      CONFIG_XDP_SOCKETS=y

      $ make -skj"$(nproc)" ARCH=arm LLVM=1 clean defconfig repro.config drivers/net/ethernet/intel/idpf/xsk.o
      In file included from drivers/net/ethernet/intel/idpf/xsk.c:4:
      include/net/libeth/xsk.h:205:2: error: call to '__compiletime_assert_728' declared with 'error' attribute: BUILD_BUG_ON failed: !__builtin_constant_p(tmo == libeth_xsktmo)
        205 |         BUILD_BUG_ON(!__builtin_constant_p(tmo == libeth_xsktmo));
            |         ^
      ...

    libeth_xdp_tx_xmit_bulk() indirectly calls libeth_xsk_xmit_fill_buf()
    but these functions are marked as __always_inline so that the compiler
    can turn these indirect calls into direct ones and see that the tmo
    parameter to __libeth_xsk_xmit_fill_buf_md() is ultimately libeth_xsktmo
    from idpf_xsk_xmit().

    Unfortunately, the generic kCFI pass in LLVM expands the kCFI bundles
    from the indirect calls in libeth_xdp_tx_xmit_bulk() in such a way that
    later optimizations cannot turn these calls into direct ones, making the
    BUILD_BUG_ON fail because it cannot be proved at compile time that tmo
    is libeth_xsktmo.

    Disable the generic kCFI pass for libeth_xdp_tx_xmit_bulk() to ensure
    these indirect calls can always be turned into direct calls to avoid
    this error.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/2124
    Fixes: 9705d6552f58 ("idpf: implement Rx path for AF_XDP")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Aleksandr Loktionov <aleksandr.loktionov@intel.com>
    Acked-by: Alexander Lobakin <aleksander.lobakin@intel.com>
    Link: https://patch.msgid.link/20251025-idpf-fix-arm-kcfi-build-error-v1-3-ec57221153ae@kernel.org
    Signed-off-by: Kees Cook <kees@kernel.org>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>