drm/amd/display: fix is_timing_changed() prototype
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-511.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 3306ba4b60b2f3d9ac6bddc587a4d702e1ba2224

Three functions in the amdgpu display driver cause -Wmissing-prototype
warnings:

drivers/gpu/drm/amd/amdgpu/../display/dc/core/dc_resource.c:1858:6: error: no previous prototype for 'is_timing_changed' [-Werror=missing-prototypes]

is_timing_changed() is actually meant to be a global symbol, but needs
a proper name and prototype.

Fixes: 17ce8a6907f7 ("drm/amd/display: Add dsc pre-validation in atomic check")
	Reviewed-by: Aurabindo Pillai <aurabindo.pillai@amd.com>
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
	Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 3306ba4b60b2f3d9ac6bddc587a4d702e1ba2224)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>