ASoC: qdsp6: fix compile-testing without CONFIG_OF
JIRA: https://issues.redhat.com/browse/RHEL-112757

Omitted-fix: 662a9ece32add94469138ae66999ee16cb37a531
             usb: misc: onboard_usb_dev: fix build warning for CONFIG_USB_ONBOARD_DEV_USB5744=n
             outside sound/ tree

commit e2d8ae899760ff71168d08047962caae07ab36a1
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri May 23 14:11:47 2025 +0200

    ASoC: qdsp6: fix compile-testing without CONFIG_OF

    The driver builds cleanly only when CONFIG_OF is enabled, otherwise the
    compiler notices an unused symbol:

    sound/soc/qcom/qdsp6/q6usb.c:401:34: error: 'q6usb_dai_device_id' defined but not used [-Werror=unused-const-variable=]

    The driver does not support legacy board files, so the of_match_ptr()
    annotation has no use here and can be removed to avoid the warning.

    Fixes: e0dd9240f13a ("ASoC: qcom: qdsp6: Fetch USB offload mapped card and PCM device")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20250523121152.2292574-1-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>