filemap: Fix errors in file.c
JIRA: https://issues.redhat.com/browse/RHEL-7936

commit a841c9cb9b04b05525f0928633e84e95921ab298
Author: huzhi001@208suo.com <huzhi001@208suo.com>
Date:   Wed Jul 19 19:00:38 2023 +0800

    filemap: Fix errors in file.c

    The following checkpatch errors are removed:
    ERROR: "foo * bar" should be "foo *bar"
    "foo * bar" should be "foo *bar"

    Signed-off-by: ZhiHu <huzhi001@208suo.com>
    Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>

Signed-off-by: Jeffrey Layton <jlayton@redhat.com>