perf tools: Fix maps__find_symbol_by_name()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Adrian Hunter <adrian.hunter@intel.com>
commit 03db8b583d1c3c84963e08e2abf6c79081da5c31

Commit 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry
trampolines") revealed a problem with maps__find_symbol_by_name() that
resulted in probes not being found e.g.

	$ sudo perf probe xsk_mmap
	xsk_mmap is out of .text, skip it.
	Probe point 'xsk_mmap' not found.
	   Error: Failed to add events.

maps__find_symbol_by_name() can optionally return the map of the found
symbol. It can get the map wrong because, in fact, the symbol is found
on the map's dso, not allowing for the possibility that the dso has more
than one map. Fix by always checking the map contains the symbol.

	Reported-by: Björn Töpel <bjorn.topel@intel.com>
	Signed-off-by: Adrian Hunter <adrian.hunter@intel.com>
	Tested-by: Björn Töpel <bjorn.topel@intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: stable@vger.kernel.org
Fixes: 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry trampolines")
Link: http://lkml.kernel.org/r/20180907085116.25782-1-adrian.hunter@intel.com
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
(cherry picked from commit 03db8b583d1c3c84963e08e2abf6c79081da5c31)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>