ASoC: mediatek: mt6358: add missing EXPORT_SYMBOLs
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Jiaxin Yu <jiaxin.yu@mediatek.com>
commit a7663c89f4193dbf717572e46e5a3251940dbdc8

Fixes the following build errors when mt6358 is configured as module:

>> ERROR: modpost: "mt6358_set_mtkaif_protocol"
>> [sound/soc/mediatek/mt8186/mt8186-mt6366-rt1019-rt5682s.ko] undefined!
>> ERROR: modpost: "mt6358_set_mtkaif_protocol"
>> [sound/soc/mediatek/mt8186/mt8186-mt6366-da7219-max98357.ko] undefined!

Fixes: 6a8d4198ca80 ("ASoC: mediatek: mt6358: add codec driver")
	Signed-off-by: Jiaxin Yu <jiaxin.yu@mediatek.com>
	Reviewed-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>
Link: https://lore.kernel.org/r/20220319120325.11882-1-jiaxin.yu@mediatek.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit a7663c89f4193dbf717572e46e5a3251940dbdc8)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>