firmware: arm_ffa: Avoid string-fortify warning in export_uuid()
JIRA: https://issues.redhat.com/browse/RHEL-102691

commit 629253b2f6d74e7bf9e7e3134ed6c8355a3c8619
Author: Arnd Bergmann <arnd@arndb.de>
Date: Mon, 9 Sep 2024 11:09:24 +0000

    Copying to a 16 byte structure into an 8-byte struct member
    causes a compile-time warning:

     | In file included from drivers/firmware/arm_ffa/driver.c:25:
     | In function 'fortify_memcpy_chk',
     |    inlined from 'export_uuid' at include/linux/uuid.h:88:2,
     |    inlined from 'ffa_msg_send_direct_req2' at drivers/firmware/arm_ffa/driver.c:488:2:
     | include/linux/fortify-string.h:571:25: error: call to '__write_overflow_field'
     |   declared with attribute warning: detected write beyond size of field
     |   (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
     |                         __write_overflow_field(p_size_field, size);

    Use a union for the conversion instead and make sure the byte order
    is fixed in the process.

    Fixes: aaef3bc98129 ("firmware: arm_ffa: Add support for FFA_MSG_SEND_DIRECT_{REQ,RESP}2")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Message-Id: <20240909110938.247976-1-arnd@kernel.org>
    Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>

Signed-off-by: Marcin Juszkiewicz <mjuszkiewicz@redhat.com>