RDMA/mlx5: Remove unused num_alloc_xa_entries variable
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-537.el8
commit-author Tom Rix <trix@redhat.com>
commit 081c27b3bcdbfad6fa3c16975e02e33073f1267d

clang with W=1 reports
drivers/infiniband/hw/mlx5/devx.c:1996:6: error: variable
  'num_alloc_xa_entries' set but not used [-Werror,-Wunused-but-set-variable]
        int num_alloc_xa_entries = 0;
            ^
This variable is not used so remove it.

	Signed-off-by: Tom Rix <trix@redhat.com>
Link: https://lore.kernel.org/r/20230330153607.1838750-1-trix@redhat.com
	Signed-off-by: Leon Romanovsky <leon@kernel.org>
(cherry picked from commit 081c27b3bcdbfad6fa3c16975e02e33073f1267d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>