ASoC: SOF: Fix randbuild error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-193.el8
Rebuild_CHGLOG: - [sound] ALSA: ASoC: SOF: Fix randbuild error (Jaroslav Kysela) [1710702]
Rebuild_FUZZ: 90.91%
commit-author YueHaibing <yuehaibing@huawei.com>
commit 9899a7a869935c4c93247b290ac7a70e0deab202

When LEDS_TRIGGER_AUDIO is m and SND_SOC_SOF is y,

sound/soc/sof/control.o: In function `snd_sof_switch_put':
control.c:(.text+0x587): undefined reference to `ledtrig_audio_set'
control.c:(.text+0x593): undefined reference to `ledtrig_audio_set'

	Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 5d43001ae436 ("ASoC: SOF: acpi led support for switch controls")
	Signed-off-by: YueHaibing <yuehaibing@huawei.com>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20191014091308.23688-1-yuehaibing@huawei.com
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9899a7a869935c4c93247b290ac7a70e0deab202)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>