sch_mqprio: Fix build with older gcc.
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-862.el7
commit-author David S. Miller <davem@davemloft.net>
commit 241deec94425b5e962e2bf8a929d563afda045f7

  CC [M]  net/sched/sch_mqprio.o
net/sched/sch_mqprio.c: In function ?mqprio_init?:
net/sched/sch_mqprio.c:145: error: unknown field ?tc? specified in initializer
net/sched/sch_mqprio.c:145: warning: missing braces around initializer
net/sched/sch_mqprio.c:145: warning: (near initialization for ?tc.<anonymous>?)
make[2]: *** [net/sched/sch_mqprio.o] Error 1
make[1]: *** [net/sched] Error 2
make: *** [net] Error 2

Several people reported this, surround the unnamed union
member initialization with braces to fix.

	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 241deec94425b5e962e2bf8a929d563afda045f7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>