selftest/powerpc/mm/pkey: fix build-break introduced by commit 00894c3fc917
JIRA: https://redhat.atlassian.net/browse/RHEL-145694

commit 73276cee1a25c4a56266faf6cf0f33e88bb63859
Author: Madhavan Srinivasan <maddy@linux.ibm.com>
Date:   Tue Mar 11 14:11:29 2025 +0530

    selftest/powerpc/mm/pkey: fix build-break introduced by commit 00894c3fc917

    Build break was reported in the powerpc mailing list for next-20250218 with below errors

    make[1]: Nothing to be done for 'all'.
    BUILD_TARGET=/root/venkat/linux-next/tools/testing/selftests/powerpc/mm; mkdir -p $BUILD_TARGET; make OUTPUT=$BUILD_TARGET -k -C mm all
      CC       pkey_exec_prot
    In file included from pkey_exec_prot.c:18:
    /root/venkat/linux-next/tools/testing/selftests/powerpc/include/pkeys.h: In function ‘pkeys_unsupported’:
    /root/venkat/linux-next/tools/testing/selftests/powerpc/include/pkeys.h:96:34: error: ‘PKEY_UNRESTRICTED’ undeclared (first use in this function)
       96 |         pkey = sys_pkey_alloc(0, PKEY_UNRESTRICTED);
          |                                  ^~~~~~~~~~~~~~~~~

    https://lore.kernel.org/all/20250113170619.484698-2-yury.khrustalev@arm.com/ patchset
    has been queued to arm64/for-next/pkey_unrestricted which is causing a build break
    in the selftest/powerpc builds.

    Commit 6d61527d931ba ("mm/pkey: Add PKEY_UNRESTRICTED macro") added a macro
    PKEY_UNRESTRICTED to handle implicit literal value of 0x0 (which is "unrestricted").
    Add the same to selftest/powerpc/pkeys.h to fix the reported build break.

    Fixes: 00894c3fc917 ("selftests/powerpc: Use PKEY_UNRESTRICTED macro")
    Reported-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Closes: https://lore.kernel.org/lkml/3267ea6e-5a1a-4752-96ef-8351c912d386@linux.ibm.com/T/
    Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://lore.kernel.org/r/20250311084129.39308-1-maddy@linux.ibm.com
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Rafael Aquini <raquini@redhat.com>