ASoC: Intel: sof_sdw: Move get_codec_dai_by_name() into sof_sdw itself
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit 0703329606a237c3604230603d58254a8bdf4b81
Author: Charles Keepax <ckeepax@opensource.cirrus.com>
Date: Tue Mar 26 11:04:01 2024 -0500

    ASoC: Intel: sof_sdw: Move get_codec_dai_by_name() into sof_sdw itself

    Currently sof_sdw relies on sof_board_helpers to provide
    get_codec_dai_by_name(), but that is the only function from
    sof_board_helpers it uses and no other machine driver requires
    that function. There is no reason for sof_sdw to select SSP_COMMON
    but more and more functions in sof_board_helpers are gaining
    dependencies on functions that would require stubs for sof_sdw to
    build without it.  Firstly it was sof_ssp_get_codec_name(), as was
    fixed in commit c1469c3a8a30 ("ASoC: Intel: ssp-common: Add stub for
    sof_ssp_get_codec_name"), now it is:

    ERROR: modpost: "sof_ssp_detect_amp_type"
    [sound/soc/intel/boards/snd-soc-intel-sof-board-helpers.ko] undefined!
    ERROR: modpost: "sof_ssp_detect_codec_type"
    [sound/soc/intel/boards/snd-soc-intel-sof-board-helpers.ko] undefined!

    Rather than adding more stubs, simply move the affected function
    to the sof_sdw machine driver itself and no longer select
    SND_SOC_INTEL_SOF_BOARD_HELPERS at all. This should allow work on
    SSP_COMMON to progress without affecting sof_sdw.

    Reviewed-by: Bard Liao <yung-chuan.liao@linux.intel.com>
    Signed-off-by: Charles Keepax <ckeepax@opensource.cirrus.com>
    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
    Link: https://msgid.link/r/20240326160429.13560-7-pierre-louis.bossart@linux.intel.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>