PCI: endpoint: Fix Kconfig dependency
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2166398
Upstream Status: 556a2c7dca337954040ffdf0c544aa8bbb75583b

commit 556a2c7dca337954040ffdf0c544aa8bbb75583b
Author: Ren Zhijie <renzhijie2@huawei.com>
Date:   Fri Jun 24 09:19:11 2022 +0800

    PCI: endpoint: Fix Kconfig dependency

    If CONFIG_NTB is not set and CONFIG_PCI_EPF_VNTB is y.

    make ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-, will be failed, like this:

    drivers/pci/endpoint/functions/pci-epf-vntb.o: In function `epf_ntb_cmd_handler':
    pci-epf-vntb.c:(.text+0x95e): undefined reference to `ntb_db_event'
    pci-epf-vntb.c:(.text+0xa1f): undefined reference to `ntb_link_event'
    pci-epf-vntb.c:(.text+0xa42): undefined reference to `ntb_link_event'
    drivers/pci/endpoint/functions/pci-epf-vntb.o: In function `pci_vntb_probe':
    pci-epf-vntb.c:(.text+0x1250): undefined reference to `ntb_register_device'

    The functions ntb_*() are defined in drivers/ntb/core.c, which need CONFIG_NTB setting y to be build-in.
    To fix this build error, add depends on NTB.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: ff32fac00d97("NTB: EPF: support NTB transfer between PCI RC and EP connection")
    Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
    Acked-by: Frank Li <frank.li@nxp.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Tested-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

Signed-off-by: Myron Stowe <mstowe@redhat.com>