netfilter: Fix build errors with xt_socket.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
commit-author David S. Miller <davem@davemloft.net>
commit 1a5bbfc3d6b700178b75743a2ba1fd2e58a8f36f

As reported by Randy Dunlap:

====================
when CONFIG_IPV6=m
and CONFIG_NETFILTER_XT_MATCH_SOCKET=y:

net/built-in.o: In function `socket_mt6_v1_v2':
xt_socket.c:(.text+0x51b55): undefined reference to `udp6_lib_lookup'
net/built-in.o: In function `socket_mt_init':
xt_socket.c:(.init.text+0x1ef8): undefined reference to `nf_defrag_ipv6_enable'
====================

Like several other modules under net/netfilter/ we have to
have a dependency "IPV6 disabled or set compatibly with this
module" clause.

	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 1a5bbfc3d6b700178b75743a2ba1fd2e58a8f36f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>