powerpc/pseries: Fix build break due to pnv_npu2_init()
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-147.el8
commit-author Jason A. Donenfeld <Jason@zx2c4.com>
commit da727097a482a93645ba5beea8d389ebab11fc64

Commit 3be2df00e299 ("powerpc/pseries/npu: Enable platform support")
added a call to pnv_npu2_init() in pseries code. This causes a build
break if we build with CONFIG_PPC_PSERIES && !CONFIG_PPC_POWERNV:

  powerpc64le-pc-linux-gnu-ld: arch/powerpc/platforms/pseries/pci.o: in function `pSeries_final_fixup':
  pci.c:(.init.text+0x1b0): undefined reference to `pnv_npu2_init'

This commit therefore wraps that line in an ifdef, so that pseries
builds without powernv.

Fixes: 3be2df00e299 ("powerpc/pseries/npu: Enable platform support")
	Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
	Reviewed-by: Alexey Kardashevskiy <aik@ozlabs.ru>
[mpe: Frob change log a bit to blame a different commit]
	Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit da727097a482a93645ba5beea8d389ebab11fc64)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>