thunderbolt: build kunit tests without structleak plugin
Bugzilla: http://bugzilla.redhat.com/2061784
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45014530
Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop

commit 33d4951e021bb67ebd6bdb01f3d437c0f45b3c0c
Author: Brendan Higgins <brendanhiggins@google.com>
Date:   Wed Sep 29 14:27:12 2021 -0700

    thunderbolt: build kunit tests without structleak plugin

    The structleak plugin causes the stack frame size to grow immensely when
    used with KUnit:

    drivers/thunderbolt/test.c:1529:1: error: the frame size of 1176 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Turn it off in this file.

    Linus already split up tests in this file, so this change *should* be
    redundant now.

    Signed-off-by: Brendan Higgins <brendanhiggins@google.com>
    Suggested-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Mika Westerberg <mika.westerberg@linux.intel.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>