spi: export tracepoint symbols to modules
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-425.3.1.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit ca1438dcb34c7fcad63b6ce14ea63a870b92a69b

The newly added tracepoints in the spi-mxs driver cause a link
error when the driver is a loadable module:

ERROR: "__tracepoint_spi_transfer_stop" [drivers/spi/spi-mxs.ko] undefined!
ERROR: "__tracepoint_spi_transfer_start" [drivers/spi/spi-mxs.ko] undefined!

I'm not quite sure where to put the export statements, but
directly after the inclusion of the header seems as good as
any other place.

Fixes: f3fdea3af405 ("spi: mxs: add tracing to custom .transfer_one_message callback")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ca1438dcb34c7fcad63b6ce14ea63a870b92a69b)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>