net_sched: cls_route: disallow handle of 0
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139170

commit 02799571714dc5dd6948824b9d080b44a295f695
Author: Jamal Hadi Salim <jhs@mojatatu.com>
Date:   Sun Aug 14 11:27:58 2022 +0000

    net_sched: cls_route: disallow handle of 0

    Follows up on:
    https://lore.kernel.org/all/20220809170518.164662-1-cascardo@canonical.com/

    handle of 0 implies from/to of universe realm which is not very
    sensible.

    Lets see what this patch will do:
    $sudo tc qdisc add dev $DEV root handle 1:0 prio

    //lets manufacture a way to insert handle of 0
    $sudo tc filter add dev $DEV parent 1:0 protocol ip prio 100 \
    route to 0 from 0 classid 1:10 action ok

    //gets rejected...
    Error: handle of 0 is not valid.
    We have an error talking to the kernel, -1

    //lets create a legit entry..
    sudo tc filter add dev $DEV parent 1:0 protocol ip prio 100 route from 10 \
    classid 1:10 action ok

    //what did the kernel insert?
    $sudo tc filter ls dev $DEV parent 1:0
    filter protocol ip pref 100 route chain 0
    filter protocol ip pref 100 route chain 0 fh 0x000a8000 flowid 1:10 from 10
            action order 1: gact action pass
             random type none pass val 0
             index 1 ref 1 bind 1

    //Lets try to replace that legit entry with a handle of 0
    $ sudo tc filter replace dev $DEV parent 1:0 protocol ip prio 100 \
    handle 0x000a8000 route to 0 from 0 classid 1:10 action drop

    Error: Replacing with handle of 0 is invalid.
    We have an error talking to the kernel, -1

    And last, lets run Cascardo's POC:
    $ ./poc
    0
    0
    -22
    -22
    -22

    Signed-off-by: Jamal Hadi Salim <jhs@mojatatu.com>
    Acked-by: Stephen Hemminger <stephen@networkplumber.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>