module: remove use of uninitialized variable len
JIRA: https://issues.redhat.com/browse/RHEL-28063

commit 9f5cab173e19201eebeaca853ff664a9a269fed0
Author: Tom Rix <trix@redhat.com>
Date:   Mon Apr 17 19:09:57 2023 -0400

    module: remove use of uninitialized variable len

    clang build reports
    kernel/module/stats.c:307:34: error: variable
      'len' is uninitialized when used here [-Werror,-Wuninitialized]
            len = scnprintf(buf + 0, size - len,
                                            ^~~
    At the start of this sequence, neither the '+ 0', nor the '- len' are needed.
    So remove them and fix using 'len' uninitalized.

    Fixes: df3e764d8e5c ("module: add debug stats to help identify memory pressure")
    Signed-off-by: Tom Rix <trix@redhat.com>
    Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>