Revert "Merge: remoteproc: updates"
Bugzilla: INTERNAL
Upstream Status: RHEL-only

MR!911 [1] is being reverted due to the following build error:

drivers/soc/qcom/mdt_loader.c:129:23: error: implicit declaration of function 'mdt_load_split_segment' [-Werror=implicit-function-declaration]
  129 |                 ret = mdt_load_split_segment(data + ehdr_size, phdrs, 1, fw_name, dev);
      |                       ^~~~~~~~~~~~~~~~~~~~~~

The automotive kernel sets CONFIG_QCOM_IPA=m that selects
CONFIG_QCOM_MDT_LOADER=m which is why this issue was not seen in the
original MR.

[1] https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/911

This reverts commit 37e52664d10445af105aacf23a0b51870cd93632, reversing
changes made to 546d365c10b973bf15238afed9c1bcb195e12fcc.

Signed-off-by: Scott Weaver <scweaver@redhat.com>