usb: get rid of some ReST doc build errors
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
Rebuild_CHGLOG: - [usb] get rid of some ReST doc build errors (Torez Smith) [1540721]
Rebuild_FUZZ: 93.67%
commit-author Mauro Carvalho Chehab <mchehab@s-opensource.com>
commit e0c34e900611a58c93adf463d096c5843eb1967a

We need an space before a numbered list to avoid those warnings:

./drivers/usb/core/message.c:478: ERROR: Unexpected indentation.
./drivers/usb/core/message.c:479: WARNING: Block quote ends without a blank line; unexpected unindent.
./include/linux/usb/composite.h:455: ERROR: Unexpected indentation.
./include/linux/usb/composite.h:456: WARNING: Block quote ends without a blank line; unexpected unindent.

	Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>
	Acked-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
	Signed-off-by: Jonathan Corbet <corbet@lwn.net>
(cherry picked from commit e0c34e900611a58c93adf463d096c5843eb1967a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>