soc: qcom: Rename ice to qcom_ice to avoid module name conflict
JIRA: https://issues.redhat.com/browse/RHEL-10197

commit 47820d3263a4a7ba258fe2efe26ae5afb5b83036
Author: Abel Vesa <abel.vesa@linaro.org>
Date:   Tue May 16 11:28:56 2023 +0300

    soc: qcom: Rename ice to qcom_ice to avoid module name conflict

    The following error was reported when building x86_64 allmodconfig:

    error: the following would cause module name conflict:
      drivers/soc/qcom/ice.ko
      drivers/net/ethernet/intel/ice/ice.ko

    Seems the 'ice' module name is already used by some Intel ethernet
    driver, so lets rename the Qualcomm Inline Crypto Engine (ICE) module
    from 'ice' to 'qcom_ice' to avoid any kind of errors/confusions.

    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Fixes: 2afbf43a4aec ("soc: qcom: Make the Qualcomm UFS/SDCC ICE a dedicated driver")
    Acked-by: Mukesh Ojha <quic_mojha@quicinc.com>
    Signed-off-by: Abel Vesa <abel.vesa@linaro.org>
    Signed-off-by: Bjorn Andersson <andersson@kernel.org>
    Link: https://lore.kernel.org/r/20230516082856.150214-1-abel.vesa@linaro.org

Signed-off-by: Alessandro Carminati <acarmina@redhat.com>