net: Provide stub for __netif_set_xps_queue if there is no CONFIG_XPS
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-80.el8
Rebuild_CHGLOG: - [net] Provide stub for __netif_set_xps_queue if there is no CONFIG_XPS (Ivan Vecera) [1651781]
Rebuild_FUZZ: 96.24%
commit-author Krzysztof Kozlowski <krzk@kernel.org>
commit c9fbb2d25295a566b97d62e6904741e8e1702d83

Building virtio_net driver without CONFIG_XPS fails with:

    drivers/net/virtio_net.c: In function ‘virtnet_set_affinity’:
    drivers/net/virtio_net.c:1910:3: error: implicit declaration of function ‘__netif_set_xps_queue’ [-Werror=implicit-function-declaration]
       __netif_set_xps_queue(vi->dev, mask, i, false);
       ^
Fixes: 4d99f6602cb5 ("net: allow to call netif_reset_xps_queues() under cpus_read_lock")
	Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit c9fbb2d25295a566b97d62e6904741e8e1702d83)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>