selftests/bpf: add missing header include for htons
JIRA: https://issues.redhat.com/browse/RHEL-82844
Upstream Status: net.git commit bc9b3fb827fc

commit bc9b3fb827fceec4e05564d6e668280f4470ab5b
Author: Alexis Lothoré (eBPF Foundation) <alexis.lothore@bootlin.com>
Date:   Tue Oct 8 16:50:57 2024 +0200

    selftests/bpf: add missing header include for htons

    Including the network_helpers.h header in tests can lead to the following
    build error:

    ./network_helpers.h: In function ‘csum_tcpudp_magic’:
    ./network_helpers.h:116:14: error: implicit declaration of function \
      ‘htons’ [-Werror=implicit-function-declaration]
      116 |         s += htons(proto + len);

    The error is avoided in many cases thanks to some other headers included
    earlier and bringing in arpa/inet.h (ie: test_progs.h).

    Make sure that test_progs build success does not depend on header ordering
    by adding the missing header include in network_helpers.h

    Fixes: f6642de0c3e9 ("selftests/bpf: Add csum helpers")
    Signed-off-by: Alexis Lothoré (eBPF Foundation) <alexis.lothore@bootlin.com>
    Link: https://lore.kernel.org/r/20241008-network_helpers_fix-v1-1-2c2ae03df7ef@bootlin.com
    Signed-off-by: Martin KaFai Lau <martin.lau@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>