usb: otg_whitelist: remove whitespace
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] otg_whitelist: remove whitespace (Torez Smith) [1303955]
Rebuild_FUZZ: 92.75%
commit-author Kris Borer <kborer@gmail.com>
commit 31b92d81e5d4574eb3d038642c7ba6ec66ea7db1

Fix one occurrence of the checkpatch error:

ERROR: space prohibited before open square bracket '['

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 31b92d81e5d4574eb3d038642c7ba6ec66ea7db1)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>