ASoC: codecs: adau1977-spi: Mark OF related data as maybe unused
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
commit a9048d64fb9605eb68c9912724e4a1346db8ba1a

The driver can be compile tested with !CONFIG_OF making certain data
unused:

  sound/soc/codecs/adau1977-spi.c:58:34: error: ‘adau1977_spi_of_match’ defined but not used [-Werror=unused-const-variable=]

	Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230310214333.274903-6-krzysztof.kozlowski@linaro.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit a9048d64fb9605eb68c9912724e4a1346db8ba1a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>