cdrom/gdrom: Fix build error
JIRA: https://issues.redhat.com/browse/RHEL-1516

commit a587b046ce921cc1805de6f0f000209b3644cadd
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Thu Jun 29 01:30:47 2023 -0700

    cdrom/gdrom: Fix build error

    Commit 7ae24fcee992 ("cdrom: remove the unused mode argument to
    cdrom_release") was supposed to remove an unused argument from
    cdrom_release(). but instead removed a used argument from
    cdrom_open(). This results in the following build error.

    drivers/cdrom/gdrom.c: In function 'gdrom_bdops_open':
    drivers/cdrom/gdrom.c:484:15: error: too few arguments to function 'cdrom_open'

    drivers/cdrom/gdrom.c: In function 'gdrom_bdops_release':
    drivers/cdrom/gdrom.c:492:35: error: 'mode' undeclared

    Fix it up.

    Fixes: 7ae24fcee992 ("cdrom: remove the unused mode argument to cdrom_release")
    Cc: Christoph Hellwig <hch@lst.de>
    Cc: Phillip Potter <phil@philpotter.co.uk>
    Cc: Hannes Reinecke <hare@suse.de>
    Cc: Christian Brauner <brauner@kernel.org>
    Cc: Jens Axboe <axboe@kernel.dk>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Link: https://lore.kernel.org/r/20230629083047.3487172-1-linux@roeck-us.net
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>