x86/l1tf: Fix build error seen if CONFIG_KVM_INTEL is disabled
jira LE-1907
cve CVE-2022-23825
cve CVE-2022-29901
cve CVE-2022-29900
cve CVE-2022-23816
Rebuild_History Non-Buildable kernel-rt-4.18.0-372.32.1.rt7.189.el8_6
commit-author Guenter Roeck <linux@roeck-us.net>
commit 1eb46908b35dfbac0ec1848d4b1e39667e0187e9

allmodconfig+CONFIG_INTEL_KVM=n results in the following build error.

  ERROR: "l1tf_vmx_mitigation" [arch/x86/kvm/kvm.ko] undefined!

Fixes: 5b76a3cff011 ("KVM: VMX: Tell the nested hypervisor to skip L1D flush on vmentry")
	Reported-by: Meelis Roos <mroos@linux.ee>
	Cc: Meelis Roos <mroos@linux.ee>
	Cc: Paolo Bonzini <pbonzini@redhat.com>
	Cc: Thomas Gleixner <tglx@linutronix.de>
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 1eb46908b35dfbac0ec1848d4b1e39667e0187e9)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>