arm64: avoid prototype warnings for syscalls
JIRA: https://issues.redhat.com/browse/RHEL-2421

commit 6ac19f96515e1f5198503701d3aecf60d5bc83e5
Author: Arnd Bergmann <arnd@arndb.de>
Date: Tue, 16 May 2023 18:06:30 +0200

    With W=1 warnings enabled, there are lots of complaints about
    missing prototypes for system calls, plus a few other related
    ones:

    arch/arm64/kernel/sys_compat.c:68:6: error: no previous prototype for 'compat_arm_syscall' [-Werror=missing-prototypes]
    arch/arm64/include/asm/syscall_wrapper.h:76:32: error: no previous prototype for '__arm64_sys_io_setup' [-Werror=missing-prototypes]
    arch/arm64/include/asm/syscall_wrapper.h:41:32: error: no previous prototype for '__arm64_compat_sys_io_setup' [-Werror=missing-prototypes]
    arch/arm64/include/asm/syscall_wrapper.h:76:32: error: no previous prototype for '__arm64_sys_io_destroy' [-Werror=missing-prototypes]
    arch/arm64/include/asm/syscall_wrapper.h:76:32: error: no previous prototype for '__arm64_sys_io_submit' [-Werror=missing-prototypes]

    Add declarations to the syscall macros to avoid all of these, plus
    one for the compat syscall entry.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Acked-by: Ard Biesheuvel <ardb@kernel.org>
    Link: https://lore.kernel.org/r/20230516160642.523862-4-arnd@kernel.org
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Signed-off-by: Mark Salter <msalter@redhat.com>