cpufreq: vexpress: Drop unused variable
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2072976

commit 45b2bb66209c723121158bd497e25645ee6197de
Author: Guenter Roeck <linux@roeck-us.net>
Date: Thu, 9 Sep 2021 11:47:14 -0700

arm:allmodconfig fails to build with the following error.

drivers/cpufreq/vexpress-spc-cpufreq.c:454:13: error:
					unused variable 'cur_cluster'

Remove the unused variable.

Fixes: bb8c26d9387f ("cpufreq: vexpress: Set CPUFREQ_IS_COOLING_DEV flag")
Cc: Viresh Kumar <viresh.kumar@linaro.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Reviewed-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>