HID: playstation: fix return from dualsense_player_led_set_brightness()
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2070873
Upstream Status: since v5.16
Tested: with the hid-tools test suite and some hardware

commit 3c92cb4cb60c71b574e47108ead8b6f0470850db
Author: Jiri Kosina <jkosina@suse.cz>
Date:   Wed Oct 27 10:04:10 2021 +0200

    HID: playstation: fix return from dualsense_player_led_set_brightness()

    brightness_set_blocking() callback expects function returning int. This fixes
    the follwoing build failure:

    drivers/hid/hid-playstation.c: In function ‘dualsense_player_led_set_brightness’:
    drivers/hid/hid-playstation.c:885:1: error: no return statement in function returning non-void [-Werror=return-type]
     }
     ^

    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>