vdpasim: fix "mac_pton" undefined error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-310.el8
commit-author Laurent Vivier <lvivier@redhat.com>
commit a312db697cb05dfa781848afe8585a1e1f2a5a99

   ERROR: modpost: "mac_pton" [drivers/vdpa/vdpa_sim/vdpa_sim.ko] undefined!

mac_pton() is defined in lib/net_utils.c and is not built if NET is not set.

Select GENERIC_NET_UTILS as vdpasim doesn't depend on NET.

	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Laurent Vivier <lvivier@redhat.com>
Link: https://lore.kernel.org/r/20201113155706.599434-1-lvivier@redhat.com
	Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
(cherry picked from commit a312db697cb05dfa781848afe8585a1e1f2a5a99)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>