ASoC: max98390: use linux/gpio/consumer.h to fix build
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-448.el8
commit-author Randy Dunlap <rdunlap@infradead.org>
commit aa7407f807b250eca7697e5fe9a699bc6c2fab71

Change the header file to fix build errors in max98390.c:

../sound/soc/codecs/max98390.c: In function 'max98390_i2c_probe':
../sound/soc/codecs/max98390.c:1076:22: error: implicit declaration of function 'devm_gpiod_get_optional'; did you mean 'devm_regulator_get_optional'? [-Werror=implicit-function-declaration]
 1076 |         reset_gpio = devm_gpiod_get_optional(&i2c->dev,
../sound/soc/codecs/max98390.c:1077:55: error: 'GPIOD_OUT_HIGH' undeclared (first use in this function); did you mean 'GPIOF_INIT_HIGH'?
 1077 |                                              "reset", GPIOD_OUT_HIGH);
../sound/soc/codecs/max98390.c:1077:55: note: each undeclared identifier is reported only once for each function it appears in
../sound/soc/codecs/max98390.c:1083:17: error: implicit declaration of function 'gpiod_set_value_cansleep'; did you mean 'gpio_set_value_cansleep'? [-Werror=implicit-function-declaration]
 1083 |                 gpiod_set_value_cansleep(reset_gpio, 0);

Fixes: 397ff0249606 ("ASoC: max98390: Add reset gpio control")
	Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
	Reported-by: kernel test robot <lkp@intel.com>
	Cc: Steve Lee <steve.lee.analog@gmail.com>
	Cc: Mark Brown <broonie@kernel.org>
	Cc: Liam Girdwood <lgirdwood@gmail.com>
	Cc: Jaroslav Kysela <perex@perex.cz>
	Cc: Takashi Iwai <tiwai@suse.com>
	Cc: alsa-devel@alsa-project.org
Link: https://lore.kernel.org/r/20220605163123.23537-1-rdunlap@infradead.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit aa7407f807b250eca7697e5fe9a699bc6c2fab71)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>