phy: freescale: pcie: explicitly add bitfield.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071844
Depends: https://bugzilla.redhat.com/show_bug.cgi?id=2121508
Tested: This is one of a series of patch sets to enable Arm SystemReady IR
 support in the kernel for NXP i.MX8 platforms.  This set cleans up
 PHY handling for imx8m (and Tegra) in drivers/phy.  This set has been
 tested via simple boot tests, and of course the CI loop.  If the PHYs
 are not working, their devices aren't; everything appears to be
 working just fine.

commit c8d09c7ebcffcbc734eee45c92f11d6ec8884b92
Author: Vinod Koul <vkoul@kernel.org>
Date:   Wed Dec 15 11:38:34 2021 +0530

    phy: freescale: pcie: explicitly add bitfield.h

    kernel test robot complains about missing FIELD_PREP, so include
    bitfield.h for that

    drivers/phy/freescale/phy-fsl-imx8m-pcie.c:41:37: error: implicit declaration of function 'FIELD_PREP' [-Werror=implicit-function-declaration]
    drivers/phy/freescale/phy-fsl-imx8m-pcie.c:41:41: error: implicit declaration of function 'FIELD_PREP' [-Werror=implicit-function-declaration]

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: 1aa97b002258 ("phy: freescale: pcie: Initialize the imx8 pcie standalone phy driver")
    Signed-off-by: Vinod Koul <vkoul@kernel.org>
    Reviewed-by: Richard Zhu <hongxing.zhu@nxp.com>
    Link: https://lore.kernel.org/r/20211215060834.921617-1-vkoul@kernel.org
    Signed-off-by: Vinod Koul <vkoul@kernel.org>
    (cherry picked from commit c8d09c7ebcffcbc734eee45c92f11d6ec8884b92)

Signed-off-by: Al Stone <ahs3@redhat.com>