firmware: tegra: Reduce stack usage
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2122349
Tested: This set has been tested on NXP imx8m and NVIDIA Jetson Xavier NX with
 simple boot tests, along with the CI loop.  NB: this patch set alone is
 insufficient to boot Orin, so sanity tests are in order.

commit 06c2d9a078abe784fd9fd0f1534e318e827712b4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Sep 27 14:41:40 2021 +0200

    firmware: tegra: Reduce stack usage

    Building the bpmp-debugfs driver for Arm results in a warning for stack usage:

    drivers/firmware/tegra/bpmp-debugfs.c:321:16: error: stack frame size of 1224 bytes in function 'bpmp_debug_store' [-Werror,-Wframe-larger-than=]
    static ssize_t bpmp_debug_store(struct file *file, const char __user *buf,

    It should be possible to rearrange the code to not require two separate
    buffers for the file name, but the easiest workaround is to use dynamic
    allocation.

    Fixes: 5e37b9c137ee ("firmware: tegra: Add support for in-band debug")
    Link: https://lore.kernel.org/all/20201204193714.3134651-1-arnd@kernel.org/
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    [treding@nvidia.com: consistently return NULL on failure]
    Signed-off-by: Thierry Reding <treding@nvidia.com>
    (cherry picked from commit 06c2d9a078abe784fd9fd0f1534e318e827712b4)

Signed-off-by: Al Stone <ahs3@redhat.com>