libperf test evsel: Fix build error on !x86 architectures
Bugzilla: https://bugzilla.redhat.com/2069070

upstream
========
commit f304c8d949f9adc2ef51304b63e49d5ea1c2d288
Author: Shunsuke Nakamura <nakamura.shun@fujitsu.com>
Date: Wed Oct 6 18:57:03 2021 +0900

description
===========
In test_stat_user_read, following build error occurs except i386 and
x86_64 architectures:

tests/test-evsel.c:129:31: error: variable 'pc' set but not used [-Werror=unused-but-set-variable]
  struct perf_event_mmap_page *pc;

Fix build error.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>