mei: late_bind: Fix -Wincompatible-function-pointer-types-strict
JIRA: https://issues.redhat.com/browse/RHEL-117354

commit 98718e80af0bb1cd80f4bfe565dd60c57debad51
Author: Nathan Chancellor <nathan@kernel.org>
Date: Sat, 20 Sep 2025 16:17:50 -0700

    When building with -Wincompatible-function-pointer-types-strict, a
    warning designed to catch kernel control flow integrity (kCFI) issues at
    build time, there is an instance in the new mei late binding code
    originating from the type parameter of mei_lb_push_payload():

      drivers/misc/mei/mei_lb.c:211:18: error: incompatible function pointer types initializing 'int (*)(struct device *, u32, u32, const void *, size_t)' (aka 'int (*)(struct device *, unsigned int, unsigned int, const void *, unsigned long)') with an expression of type 'int (struct device *, enum intel_lb_type, u32, const void *, size_t)' (aka 'int (struct device *, enum intel_lb_type, unsigned int, const void *, unsigned long)') [-Werror,-Wincompatible-function-pointer-types-strict]
        211 |         .push_payload = mei_lb_push_payload,
            |                         ^~~~~~~~~~~~~~~~~~~

    While 'unsigned int' and 'enum intel_lb_type' are ABI compatible, hence
    no regular warning from -Wincompatible-function-pointer-types, the
    mismatch will trigger a kCFI violation when mei_lb_push_payload() is
    called indirectly.

    Update the type parameter of mei_lb_push_payload() to be 'u32' to match
    the prototype in 'struct intel_lb_component_ops', clearing up the
    warning and kCFI violation.

    Fixes: 741eeabb7c78 ("mei: late_bind: add late binding component driver")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Link: https://patch.msgid.link/20250920-drm-xe-fix-wifpts-v1-1-c89b5357c7ba@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Krzysztof Pawlinski <kpawlins@redhat.com>