net: ti: icssg-prueth: add PTP dependency
JIRA: https://issues.redhat.com/browse/RHEL-29244

commit a8f367f7e131e76713b2949b168ac97f671fce7a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Sep 12 20:54:51 2023 +0200

    net: ti: icssg-prueth: add PTP dependency

    The driver can now use PTP if enabled but fails to link built-in
    if PTP is a loadable module:

    aarch64-linux-ld: drivers/net/ethernet/ti/icssg/icss_iep.o: in function `icss_iep_get_ptp_clock_idx':
    icss_iep.c:(.text+0x200): undefined reference to `ptp_clock_index'

    Add the usual dependency to avoid this.

    Fixes: 186734c158865 ("net: ti: icssg-prueth: add packet timestamping and ptp support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: MD Danish Anwar <danishanwar@ti.com>
    Reviewed-by: Jiri Pirko <jiri@nvidia.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>