selftests: drivers/dma-buf: Fix implicit declaration warns
JIRA: https://issues.redhat.com/browse/RHEL-89519

commit 2f9602870886af74d97bac23ee6db5f5466d0a49
Author: Shuah Khan <skhan@linuxfoundation.org>
Date:   Fri, 17 Sep 2021 17:58:13 -0600

    selftests: drivers/dma-buf: Fix implicit declaration warns

    udmabuf has the following implicit declaration warns:

    udmabuf.c:30:10: warning: implicit declaration of function 'open';
    udmabuf.c:42:8: warning: implicit declaration of function 'fcntl'

    These are caused due to not including fcntl.h and including just
    linux/fcntl.h. Fix it to include fcntl.h which will bring in the
    linux/fcntl.h. In addition, define __EXPORTED_HEADERS__ to bring in
    F_ADD_SEALS and F_SEAL_SHRINK defines and fix the following error
    that show up when just fcntl.h is included.

    udmabuf.c:45:21: error: 'F_ADD_SEALS' undeclared
       45 |  ret = fcntl(memfd, F_ADD_SEALS, F_SEAL_SHRINK);
          |                     ^~~~~~~~~~~
    udmabuf.c:45:34: error: 'F_SEAL_SHRINK' undeclared
       45 |  ret = fcntl(memfd, F_ADD_SEALS, F_SEAL_SHRINK);
          |                                  ^~~~~~~~~~~~~

    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>