{xfrm,pktgen} Fix compiling error when CONFIG_XFRM is not set
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [net] {xfrm, pktgen} Fix compiling error when CONFIG_XFRM is not set (Ivan Vecera) [1680139]
Rebuild_FUZZ: 99.19%
commit-author Fan Du <fan.du@windriver.com>
commit 6bae919003602729d6f5920315bf71ca78bd9e48

0-DAY kernel build testing backend reported below error:
All error/warnings:

   net/core/pktgen.c: In function 'pktgen_if_write':
>> >> net/core/pktgen.c:1487:10: error: 'struct pktgen_dev' has no member named 'spi'
>> >> net/core/pktgen.c:1488:43: error: 'struct pktgen_dev' has no member named 'spi'

Fix this by encapuslating the code with CONFIG_XFRM.

	Cc: Fengguang Wu <fengguang.wu@intel.com>
	Signed-off-by: Fan Du <fan.du@windriver.com>
	Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>
(cherry picked from commit 6bae919003602729d6f5920315bf71ca78bd9e48)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>