netfilter: ipset: Fix static checker warning in ip_set_core.c
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-957.el7
commit-author Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
commit 73e64e1813e9ea45885419d0fff1e628a6ab95d4

Dan Carpenter reported the following static checker warning:

        net/netfilter/ipset/ip_set_core.c:1414 call_ad()
        error: 'nlh->nlmsg_len' from user is not capped properly

The payload size is limited now by the max size of size_t.

	Signed-off-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
(cherry picked from commit 73e64e1813e9ea45885419d0fff1e628a6ab95d4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>