RDMA/bnxt_re: Remove always true dattr validity check
JIRA: https://issues.redhat.com/browse/RHEL-22876

commit eb867d797d294a00a092b5027d08439da68940b2
Author: Leon Romanovsky <leon@kernel.org>
Date:   Tue Nov 26 15:10:31 2024 +0200

    RDMA/bnxt_re: Remove always true dattr validity check

    res->dattr is always valid at this point as it was initialized
    during device addition in bnxt_re_add_device().

    This change is fixing the following smatch error:
    drivers/infiniband/hw/bnxt_re/qplib_fp.c:1090 bnxt_qplib_create_qp()
         error: we previously assumed 'res->dattr' could be null (see line 985)

    Fixes: 07f830ae4913 ("RDMA/bnxt_re: Adds MSN table capability for Gen P7 adapters")
    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
    Closes: https://lore.kernel.org/r/202411222329.YTrwonWi-lkp@intel.com/
    Link: https://patch.msgid.link/be0d8836b64cba3e479fbcbca717acad04aae02e.1732626579.git.leonro@nvidia.com
    Acked-by: Selvin Xavier <selvin.xavier@broadcom.com>
    Signed-off-by: Leon Romanovsky <leonro@nvidia.com>

Signed-off-by: Mohammad Heib <mheib@redhat.com>