ipv6: Remove dependency of ipv6_frag_thdr_truncated on ipv6 module
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-502.el8
commit-author Georg Kohmann <geokohma@cisco.com>
commit 2d8f6481c17db9fa5238b277cdbc392084060b09

IPV6=m
NF_DEFRAG_IPV6=y

ld: net/ipv6/netfilter/nf_conntrack_reasm.o: in function
`nf_ct_frag6_gather':
net/ipv6/netfilter/nf_conntrack_reasm.c:462: undefined reference to
`ipv6_frag_thdr_truncated'

Netfilter is depending on ipv6 symbol ipv6_frag_thdr_truncated. This
dependency is forcing IPV6=y.

Remove this dependency by moving ipv6_frag_thdr_truncated out of ipv6. This
is the same solution as used with a similar issues: Referring to
commit 70b095c843266 ("ipv6: remove dependency of nf_defrag_ipv6 on ipv6
module")

Fixes: 9d9e937b1c8b ("ipv6/netfilter: Discard first fragment not including all headers")
	Reported-by: Randy Dunlap <rdunlap@infradead.org>
	Reported-by: kernel test robot <lkp@intel.com>
	Signed-off-by: Georg Kohmann <geokohma@cisco.com>
	Acked-by: Pablo Neira Ayuso <pablo@netfilter.org>
	Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
Link: https://lore.kernel.org/r/20201119095833.8409-1-geokohma@cisco.com
	Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 2d8f6481c17db9fa5238b277cdbc392084060b09)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>