sched/fair: Remove CONFIG_CFS_BANDWIDTH=n definition of cfs_bandwidth_used()
JIRA: https://issues.redhat.com/browse/RHEL-78822

commit a76328d44c7ab7d1001a97cb2e84506dde7822d4
Author: Valentin Schneider <vschneid@redhat.com>
Date:   Wed Nov 27 17:55:01 2024 +0100

    sched/fair: Remove CONFIG_CFS_BANDWIDTH=n definition of cfs_bandwidth_used()

    Andy reported that clang gets upset with CONFIG_CFS_BANDWIDTH=n:

      kernel/sched/fair.c:6580:20: error: unused function 'cfs_bandwidth_used' [-Werror,-Wunused-function]
       6580 | static inline bool cfs_bandwidth_used(void)
            |                    ^~~~~~~~~~~~~~~~~~

    Indeed, cfs_bandwidth_used() is only used within functions defined under
    CONFIG_CFS_BANDWIDTH=y. Remove its CONFIG_CFS_BANDWIDTH=n declaration &
    definition.

    Reported-by: Andy Shevchenko <andy.shevchenko@gmail.com>
    Signed-off-by: Valentin Schneider <vschneid@redhat.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
    Link: https://lore.kernel.org/r/20241127165501.160004-1-vschneid@redhat.com

Signed-off-by: Phil Auld <pauld@redhat.com>