rxrpc: replace zero-lenth array with DECLARE_FLEX_ARRAY() helper
JIRA: https://issues.redhat.com/browse/RHEL-40250

commit b2ba00c2a51793d916b662cb049b8f01c55d9e82
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Thu Jan 5 12:05:50 2023 -0800

    rxrpc: replace zero-lenth array with DECLARE_FLEX_ARRAY() helper

    0-length arrays are deprecated, and cause problems with bounds checking.
    Replace with a flexible array:

    In file included from include/linux/string.h:253,
                     from include/linux/bitmap.h:11,
                     from include/linux/cpumask.h:12,
                     from arch/x86/include/asm/paravirt.h:17,
                     from arch/x86/include/asm/cpuid.h:62,
                     from arch/x86/include/asm/processor.h:19,
                     from arch/x86/include/asm/cpufeature.h:5,
                     from arch/x86/include/asm/thread_info.h:53,
                     from include/linux/thread_info.h:60,
                     from arch/x86/include/asm/preempt.h:9,
                     from include/linux/preempt.h:78,
                     from include/linux/percpu.h:6,
                     from include/linux/prandom.h:13,
                     from include/linux/random.h:153,
                     from include/linux/net.h:18,
                     from net/rxrpc/output.c:10:
    In function 'fortify_memcpy_chk',
        inlined from 'rxrpc_fill_out_ack' at net/rxrpc/output.c:158:2:
    include/linux/fortify-string.h:520:25: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()?  [-Werror=attribute-warning]
      520 |                         __write_overflow_field(p_size_field, size);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Link: https://lore.kernel.org/linux-next/20230105132535.0d65378f@canb.auug.org.au/
    Cc: David Howells <dhowells@redhat.com>
    Cc: Marc Dionne <marc.dionne@auristor.com>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: Eric Dumazet <edumazet@google.com>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: Paolo Abeni <pabeni@redhat.com>
    Cc: linux-afs@lists.infradead.org
    Cc: netdev@vger.kernel.org
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Kees Cook <keescook@chromium.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>