bpf: tcp: Remove comma which is causing build error
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-365.el8
commit-author Atul Gopinathan <atulgopinathan@gmail.com>
commit 7e32a09fdcb38d97f148f72bf78a3b49e8d1612d

Currently, building the bpf-next source with the CONFIG_BPF_SYSCALL
enabled is causing a compilation error:

"net/ipv4/bpf_tcp_ca.c:209:28: error: expected identifier or '(' before
',' token"

Fix this by removing an unnecessary comma.

Fixes: e78aea8b2170 ("bpf: tcp: Put some tcp cong functions in allowlist for bpf-tcp-cc")
	Reported-by: syzbot+0b74d8ec3bf0cc4e4209@syzkaller.appspotmail.com
	Signed-off-by: Atul Gopinathan <atulgopinathan@gmail.com>
	Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Link: https://lore.kernel.org/bpf/20210328120515.113895-1-atulgopinathan@gmail.com
(cherry picked from commit 7e32a09fdcb38d97f148f72bf78a3b49e8d1612d)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>