ASoC: Intel: fix sof-nau8825 link failure
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-499.el8
commit-author Arnd Bergmann <arnd@arndb.de>
commit 63f3d99b7efe4c5404a9388c05780917099cecf4

The snd-soc-sof_nau8825.ko module fails to link unless the
sof_realtek_common support is also enabled:

ERROR: modpost: "sof_rt1015p_codec_conf" [sound/soc/intel/boards/snd-soc-sof_nau8825.ko] undefined!
ERROR: modpost: "sof_rt1015p_dai_link" [sound/soc/intel/boards/snd-soc-sof_nau8825.ko] undefined!

Fixes: 8d0872f6239f ("ASoC: Intel: add sof-nau8825 machine driver")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20221221132559.2402341-1-arnd@kernel.org
	Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 63f3d99b7efe4c5404a9388c05780917099cecf4)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>