x86: i8259: Add missing include file
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-294.el8
commit-author Guenter Roeck <linux@roeck-us.net>
commit 0a957467c5fd46142bc9c52758ffc552d4c5e2f7

i8259.h uses inb/outb and thus needs to include asm/io.h to avoid the
following build error, as seen with x86_64:defconfig and CONFIG_SMP=n.

  In file included from drivers/rtc/rtc-cmos.c:45:0:
  arch/x86/include/asm/i8259.h: In function 'inb_pic':
  arch/x86/include/asm/i8259.h:32:24: error:
	implicit declaration of function 'inb'

  arch/x86/include/asm/i8259.h: In function 'outb_pic':
  arch/x86/include/asm/i8259.h:45:2: error:
	implicit declaration of function 'outb'

	Reported-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>
	Suggested-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>
Fixes: 447ae3166702 ("x86: Don't include linux/irq.h from asm/hardirq.h")
	Signed-off-by: Guenter Roeck <linux@roeck-us.net>
	Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 0a957467c5fd46142bc9c52758ffc552d4c5e2f7)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>