ASoC: codecs: aw88399: Fix -Wuninitialized in aw_dev_set_vcalb()
JIRA: https://issues.redhat.com/browse/RHEL-27515

commit cba4590036855f4e3110d43c14385d2401080dbb
Author: Nathan Chancellor <nathan@kernel.org>
Date: Fri Oct 27 09:54:25 2023 -0700

    ASoC: codecs: aw88399: Fix -Wuninitialized in aw_dev_set_vcalb()

    Clang warns (or errors with CONFIG_WERROR=y):

      sound/soc/codecs/aw88399.c:441:18: error: variable 'vsense_select' is uninitialized when used here [-Werror,-Wuninitialized]
        441 |         vsense_select = vsense_select & (~AW88399_VDSEL_MASK);
            |                         ^~~~~~~~~~~~~
      sound/soc/codecs/aw88399.c:431:28: note: initialize the variable 'vsense_select' to silence this warning
        431 |         unsigned int vsense_select, vsense_value;
            |                                   ^
            |                                    = 0
      1 error generated.

    This clearly should have been using the value received from
    regmap_read(). Use the correct variable to resolve the warning.

    Closes: https://github.com/ClangBuiltLinux/linux/issues/1952
    Fixes: 8ade6cc7e261 ("ASoC: codecs: Add aw88399 amplifier driver")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Weidong Wang <wangweidong.a@awinic.com>
    Link: https://lore.kernel.org/r/20231027-asoc-aw88399-fix-wuninitialized-v1-1-b1044493e4cd@kernel.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>