net/mlx5: Fix format-security build warnings
Bugzilla: https://bugzilla.redhat.com/2049450
Bugzilla: http://bugzilla.redhat.com/2049844
Upstream-status: v5.17-rc1

commit aef0f8c67d752ed68cc18582711ac6accf0ad9b6
Author: Saeed Mahameed <saeedm@nvidia.com>
Date:   Wed Nov 3 14:01:05 2021 -0700

    net/mlx5: Fix format-security build warnings

    Treat the string as an argument to avoid this.

    drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:482:5:
    error: format string is not a string literal (potentially insecure)
                             name);
                             ^~~~
    drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:2079:4:
    error: format string is not a string literal (potentially insecure)
                            ptp_ch_stats_desc[i].format);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Reviewed-by: Shay Drory <shayd@nvidia.com>
    Reviewed-by: Moshe Shemesh <moshe@nvidia.com>

Signed-off-by: Mohammad Kabat <mkabat@redhat.com>