smb: smbdirect: introduce smbdirect_public.h with prototypes
JIRA: https://issues.redhat.com/browse/RHEL-190706
Conflicts:
	- Code difference due to missing upstream commit
          6d3c3ca4c77e93660cce5819bf707f75df03e0c8.

commit b2261ceedd4a4831957732ebae5ad33bf5c7fc80
Author: Stefan Metzmacher <metze@samba.org>
Date:   Mon Oct 27 16:57:39 2025 +0100

    smb: smbdirect: introduce smbdirect_public.h with prototypes

    smbdirect_public.h contains functions which will be still be
    eported when we move to an smbdirect.ko.

    For now this uses the SMBDIRECT_USE_INLINE_C_FILES code path
    and marks all function as '__maybe_unused static',
    but this will make further changes easier.

    Note this generates the following things from checkpatch.pl,
    so I passed --ignore=FILE_PATH_CHANGES,EXPORT_SYMBOL,COMPLEX_MACRO

     ERROR: Macros with complex values should be enclosed in parentheses
     #514: FILE: fs/smb/common/smbdirect/smbdirect_public.h:18:
     +#define __SMBDIRECT_PUBLIC__ __maybe_unused static

     WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
     #515: FILE: fs/smb/common/smbdirect/smbdirect_public.h:19:
     +#define __SMBDIRECT_EXPORT_SYMBOL__(__sym)

     WARNING: EXPORT_SYMBOL(foo); should immediately follow its function/variable
     #518: FILE: fs/smb/common/smbdirect/smbdirect_public.h:22:
     +#define __SMBDIRECT_EXPORT_SYMBOL__(__sym) EXPORT_SYMBOL_FOR_MODULES(__sym, "cifs,ksmbd")

    This is exactly what we want here, so we should ignore the
    checkpatch.pl problems.

    Cc: Steve French <smfrench@gmail.com>
    Cc: Tom Talpey <tom@talpey.com>
    Cc: Long Li <longli@microsoft.com>
    Cc: Namjae Jeon <linkinjeon@kernel.org>
    Cc: linux-cifs@vger.kernel.org
    Cc: samba-technical@lists.samba.org
    Signed-off-by: Stefan Metzmacher <metze@samba.org>
    Acked-by: Namjae Jeon <linkinjeon@kernel.org>
    Signed-off-by: Steve French <stfrench@microsoft.com>

Signed-off-by: Paulo Alcantara <paalcant@redhat.com>