drivers/infiniband/ulp/srpt/ib_srpt.c: fix build with gcc-4.4.4
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-1062.el7
Rebuild_CHGLOG: - [infiniband] infiniband/ulp/srpt/ib_srpt.c: fix build with gcc-4.4.4 (Kamal Heib) [1641363]
Rebuild_FUZZ: 93.22%
commit-author Andrew Morton <akpm@linux-foundation.org>
commit 06892cc190550807d332c95a0114c7e175584012

gcc-4.4.4 has issues with initialization of anonymous unions:

drivers/infiniband/ulp/srpt/ib_srpt.c: In function 'srpt_zerolength_write':
drivers/infiniband/ulp/srpt/ib_srpt.c:854: error: unknown field 'wr_cqe' specified in initializer
drivers/infiniband/ulp/srpt/ib_srpt.c:854: warning: initialization makes integer from pointer without a cast

Work aound this.

Fixes: 2a78cb4db487 ("IB/srpt: Fix an out-of-bounds stack access in srpt_zerolength_write()")
	Cc: Bart Van Assche <bart.vanassche@wdc.com>
	Cc: Christoph Hellwig <hch@lst.de>
	Cc: Jason Gunthorpe <jgg@mellanox.com>
	Cc: <stable@vger.kernel.org>
	Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
	Signed-off-by: Doug Ledford <dledford@redhat.com>
(cherry picked from commit 06892cc190550807d332c95a0114c7e175584012)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>