dm cache: avoid conflicting remove_mapping() in mq policy
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
Rebuild_CHGLOG: - [md] dm-cache: avoid conflicting remove_mapping() in mq policy (Mike Snitzer) [1010437]
Rebuild_FUZZ: 98.25%
commit-author Geert Uytterhoeven <geert@linux-m68k.org>
commit b936bf8b785f0fbe083d203049e4da1c56ec788f

On sparc32, which includes <linux/swap.h> from <asm/pgtable_32.h>:

drivers/md/dm-cache-policy-mq.c:962:13: error: conflicting types for 'remove_mapping'
include/linux/swap.h:285:12: note: previous declaration of 'remove_mapping' was here

As mq_remove_mapping() already exists, and the local remove_mapping() is
used only once, inline it manually to avoid the conflict.

	Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
	Signed-off-by: Mike Snitzer <snitzer@redhat.com>
	Signed-off-by: Alasdair Kergon <agk@redhat.com>
	Acked-by: Joe Thornber <ejt@redhat.com>
(cherry picked from commit b936bf8b785f0fbe083d203049e4da1c56ec788f)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>