vxlan: include net/ip6_checksum.h for csum_ipv6_magic()
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-123.el7
commit-author Cong Wang <amwang@redhat.com>
commit 660d98cae0a474887bb5d66e60422addb4c6532c

Fengguang reported a compile warning:

   drivers/net/vxlan.c: In function 'vxlan6_xmit_skb':
   drivers/net/vxlan.c:1352:3: error: implicit declaration of function 'csum_ipv6_magic' [-Werror=implicit-function-declaration]
   cc1: some warnings being treated as errors

this patch fixes it.

	Reported-by: kbuild test robot <fengguang.wu@intel.com>
	Signed-off-by: Cong Wang <amwang@redhat.com>
	Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 660d98cae0a474887bb5d66e60422addb4c6532c)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>