bridge: only include nf_queue.h if needed
jira LE-1907
Rebuild_History Non-Buildable kernel-4.18.0-358.el8
commit-author Stephen Rothwell <sfr@canb.auug.org.au>
commit dc2f4189dcd2c87e211d30d9524ae8ebe19af577

After merging the netfilter-next tree, today's linux-next build (powerpc
ppc44x_defconfig) failed like this:

In file included from net/bridge/br_input.c:19:
include/net/netfilter/nf_queue.h:16:23: error: field 'state' has incomplete type
  struct nf_hook_state state;
                       ^~~~~

Fixes: 971502d77faa ("bridge: netfilter: unroll NF_HOOK helper in bridge input path")
	Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
	Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit dc2f4189dcd2c87e211d30d9524ae8ebe19af577)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>