iwlwifi: pcie: fix constant-conversion warning
Bugzilla: http://bugzilla.redhat.com/2043454

commit fe785f56ad5886c08d1cadd9e8b4e1ff6a1866f6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Nov 18 15:21:02 2021 +0100

    iwlwifi: pcie: fix constant-conversion warning
    
    Both gcc-11 and clang point out a potential issue with integer overflow when
    the iwl_dev_info_table[] array is empty. This is what clang warns:
    
    drivers/net/wireless/intel/iwlwifi/pcie/drv.c:1344:42: error: implicit conversion from 'unsigned long' to 'int' changes value from 18446744073709551615 to -1 [-Werror,-Wconstant-conversion]
            for (i = ARRAY_SIZE(iwl_dev_info_table) - 1; i >= 0; i--) {
                   ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    
    This is still harmless, as the loop correctly terminates, but adding
    an extra range check makes that obvious to both readers and to the
    compiler.
    
    Fixes: 3f7320428fa4 ("iwlwifi: pcie: simplify iwl_pci_find_dev_info()")
    Reported-by: kernel test robot <lkp@intel.com>
    Cc: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <nathan@kernel.org>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20211118142124.526901-1-arnd@kernel.org

Signed-off-by: Íñigo Huguet <ihuguet@redhat.com>