arm64: move smp_send_stop() cpu mask off stack
JIRA: https://issues.redhat.com/browse/RHEL-101059

commit 6c66bb655ca3fd5e9304163cf70796d08de512ed
Author: Arnd Bergmann <arnd@arndb.de>
Date: Fri, 20 Jun 2025 13:10:41 +0200

    For really large values of CONFIG_NR_CPUS, a CPU mask value should
    not be put on the stack:

    arch/arm64/kernel/smp.c:1188:1: error: the frame size of 8544 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

    This could be achieved using alloc_cpumask_var(), which makes it
    depend on CONFIG_CPUMASK_OFFSTACK, but as this function is already
    serialized and can only run on one CPU, making the variable 'static'
    is easier.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
    Link: https://lore.kernel.org/r/20250620111045.3364827-1-arnd@kernel.org
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Mark Salter <msalter@redhat.com>