ALSA: compress_offload: Use runtime pointer in snd_compr_poll()
JIRA: https://issues.redhat.com/browse/RHEL-80681

commit 9e096b3cbbecfeecb544ec5a94dbd6e10df2219b
Author: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
Date: Wed Nov 6 09:53:12 2024 +0200

    ALSA: compress_offload: Use runtime pointer in snd_compr_poll()

    runtime is not used as seen with W=1 :
    sound/core/compress_offload.c: In function ‘snd_compr_poll’:
    sound/core/compress_offload.c:409:35: error: variable ‘runtime’ set but not used [-Werror=unused-but-set-variable]
      409 |         struct snd_compr_runtime *runtime;
          |                                   ^~~~~~~

    Instead of dropping the runtime, use it in the function in place of
    stream->runtime

    Fixes: 04177158cf98 ("ALSA: compress_offload: introduce accel operation mode")
    Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>
    Reviewed-by: Jaroslav Kysela <perex@perex.cz>
    Link: https://patch.msgid.link/20241106075312.15601-1-peter.ujfalusi@linux.intel.com
    Signed-off-by: Takashi Iwai <tiwai@suse.de>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>