locking/rwsem: Move is_rwsem_reader_owned() and rwsem_owner() under  CONFIG_DEBUG_RWSEMS
JIRA: https://issues.redhat.com/browse/RHEL-79880

commit d00b83d416e73bc3fa4d21b14bec920e88b70ce6
Author: Waiman Long <longman@redhat.com>
Date:   Mon Sep 9 14:29:05 2024 -0400

	Both is_rwsem_reader_owned() and rwsem_owner() are currently only used when
	CONFIG_DEBUG_RWSEMS is defined. This causes a compilation error with clang
	when `make W=1` and CONFIG_WERROR=y:

	kernel/locking/rwsem.c:187:20: error: unused function 'is_rwsem_reader_owned' [-Werror,-Wunused-function]
	  187 | static inline bool is_rwsem_reader_owned(struct rw_semaphore *sem)
	      |                    ^~~~~~~~~~~~~~~~~~~~~
	kernel/locking/rwsem.c:271:35: error: unused function 'rwsem_owner' [-Werror,-Wunused-function]
	  271 | static inline struct task_struct *rwsem_owner(struct rw_semaphore *sem)
	      |                                   ^~~~~~~~~~~

	Fix this by moving these two functions under the CONFIG_DEBUG_RWSEMS define.

	Reported-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Signed-off-by: Waiman Long <longman@redhat.com>
	Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
	Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Tested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
	Link: https://lore.kernel.org/r/20240909182905.161156-1-longman@redhat.com

Signed-off-by: Čestmír Kalina <ckalina@redhat.com>