platform/x86/amd/pmf: Fix undefined reference to platform_profile
JIRA: https://issues.redhat.com/browse/RHEL-2037

commit c2f7edf81a82db20d91974ba2cf50a4c90c2dbe3
Author: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
Date:   Fri Aug 19 14:08:58 2022 +0530

    platform/x86/amd/pmf: Fix undefined reference to platform_profile

    Its reported that amd-pmf driver when built with config which does not
    have ACPI_PLATFORM_PROFILE set/enabled throws a undefined references to
    symbols used.

    ld: vmlinux.o: in function `amd_pmf_init_sps':
    drivers/platform/x86/amd/pmf/sps.c:132: undefined reference to `platform_profile_register'
    ld: vmlinux.o: in function `amd_pmf_deinit_sps':
    drivers/platform/x86/amd/pmf/sps.c:142: undefined reference to `platform_profile_remove'

    Fix it by adding a "select" to the Kconfig.

    Fixes: da5ce22df5fe ("platform/x86/amd/pmf: Add support for PMF core layer")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Shyam Sundar S K <Shyam-sundar.S-k@amd.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Link: https://lore.kernel.org/r/20220819083858.3987590-1-Shyam-sundar.S-k@amd.com
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

Signed-off-by: David Arcari <darcari@redhat.com>