crypto: ccp - Fix __sev_snp_shutdown_locked
jira KERNEL-393
Rebuild_History Non-Buildable kernel-5.14.0-611.16.1.el9_7
commit-author Ashish Kalra <ashish.kalra@amd.com>
commit 9af6339a65426b0b4850b07ff3b6959497bfcac5

Fix smatch warning:
	drivers/crypto/ccp/sev-dev.c:1755 __sev_snp_shutdown_locked()
	error: uninitialized symbol 'dfflush_error'.

Fixes: 9770b428b1a2 ("crypto: ccp - Move dev_info/err messages for SEV/SNP init and shutdown")
	Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Closes: https://lore.kernel.org/linux-crypto/d9c2e79c-e26e-47b7-8243-ff6e7b101ec3@stanley.mountain/
	Signed-off-by: Ashish Kalra <ashish.kalra@amd.com>
	Acked-by: Tom Lendacky <thomas.lendacky@amd.com>
	Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
(cherry picked from commit 9af6339a65426b0b4850b07ff3b6959497bfcac5)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>