perf tools: Disable BPF skeleton if no libopenssl found
JIRA: https://redhat.atlassian.net/browse/RHEL-140195

upstream
========
commit 800ad1f0e27792cddf5928f590d3f2d4ab3c68ee
Author: Namhyung Kim <namhyung@kernel.org>
Date: Wed Dec 3 15:29:24 2025 -0800

description
===========
The libopenssl is required by bpftool which is needed to generate BPF
skeleton.  Disable it by setting BUILD_BPF_SKEL to 0 otherwise it'll see
build errors like below:

    CC      /build/util/bpf_skel/.tmp/bootstrap/sign.o
  sign.c:16:10: fatal error: openssl/opensslv.h: No such file or directory
     16 | #include <openssl/opensslv.h>
        |          ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make[3]: *** [Makefile:256: /build/util/bpf_skel/.tmp/bootstrap/sign.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[2]: *** [Makefile.perf:1211: /build/util/bpf_skel/.tmp/bootstrap/bpftool] Error 2
  make[1]: *** [Makefile.perf:287: sub-make] Error 2
  make: *** [Makefile:76: all] Error 2

Now it'll skip the build with the following message:

  Makefile.config:729: Warning: Disabled BPF skeletons as libopenssl is required

Closes: https://lore.kernel.org/r/aP7uq6eVieG8v_v4@google.com
    Signed-off-by: Namhyung Kim <namhyung@kernel.org>

Signed-off-by: Trevor Allison <tallison@redhat.com>