ASoC: amd: acp: Fix acp_resource duplicate symbol error
JIRA: https://issues.redhat.com/browse/RHEL-80657

Conflicts: module stringify upstream changes

commit 09dc8031f4a84103f4ba8f704ec21f1926b04366
Author: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
Date: Mon Mar 17 12:54:08 2025 +0530

    ASoC: amd: acp: Fix acp_resource duplicate symbol error

    Fix acp_resource structure duplicate defination error by adding
    export symbol and extern keyword in header file.

    ld.lld: error: duplicate symbol: acp63_rsrc
    ld.lld: error: duplicate symbol: acp70_rsrc

    Fixes: f8b4f3f525e8 ("ASoC: amd: acp: Refactor acp70 platform resource structure")

    Reported-by: kernel test robot <lkp@intel.com>
    Closes: https://lore.kernel.org/oe-kbuild-all/202503160801.yExt0K2E-lkp@intel.com/
    Signed-off-by: Venkata Prasad Potturu <venkataprasad.potturu@amd.com>
    Link: https://patch.msgid.link/20250317072413.88971-2-venkataprasad.potturu@amd.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>