console: fix up ARM screen_info reference
JIRA: https://issues.redhat.com/browse/RHEL-23295
Upstream Status: v6.7-rc1

Conflicts:
        arch/arm/kernel/setup.c

commit 0059bc9a29e02853dbbaa0f6d0635a687c8b9835
Author:     Arnd Bergmann <arnd@arndb.de>
AuthorDate: Tue Oct 17 11:39:47 2023 +0200
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Tue Oct 17 16:34:02 2023 +0200

    Separating the VGA console screen_info from the EFI one unfortunately
    caused a build failure for footbridge that I had never caught
    with randconfig builds:

    arch/arm/kernel/setup.c:932:27: error: static declaration of 'vgacon_screen_info' follows non-static declaration
      932 | static struct screen_info vgacon_screen_info = {
          |                           ^~~~~~~~~~~~~~~~~~
    In file included from arch/arm/kernel/setup.c:44:
    arch/arm/include/asm/setup.h:40:27: note: previous declaration of 'vgacon_screen_info' with type 'struct screen_info'
       40 | extern struct screen_info vgacon_screen_info;
          |                           ^~~~~~~~~~~~~~~~~~
    arm-linux-gnueabi-ld: drivers/video/console/dummycon.o: in function `dummycon_init':
    dummycon.c:(.text+0xe4): undefined reference to `screen_info'

    Make sure the variable is global to avoid the conflict with the extern
    declaration, and make it work in dummycon.c

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20231017093947.3627976-2-arnd@kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jocelyn Falempe <jfalempe@redhat.com>