n64cart: convert bi_disk to bi_bdev->bd_disk fix build
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2083917

commit b2479de38d8fc7ef13d5c78ff5ded6e5a1a4eac0
Author: Jackie Liu <liuyun01@kylinos.cn>
Date:   Mon Mar 21 15:12:16 2022 +0800

    n64cart: convert bi_disk to bi_bdev->bd_disk fix build

    My kernel robot report below:

      drivers/block/n64cart.c: In function ‘n64cart_submit_bio’:
      drivers/block/n64cart.c:91:26: error: ‘struct bio’ has no member named ‘bi_disk’
         91 |  struct device *dev = bio->bi_disk->private_data;
            |                          ^~
        CC      drivers/slimbus/qcom-ctrl.o
        CC      drivers/auxdisplay/hd44780.o
        CC      drivers/watchdog/watchdog_core.o
        CC      drivers/nvme/host/fault_inject.o
        AR      drivers/accessibility/braille/built-in.a
      make[2]: *** [scripts/Makefile.build:288: drivers/block/n64cart.o] Error 1

    Fixes: 309dca309fc3 ("block: store a block_device pointer in struct bio");
    Reported-by: k2ci <kernel-bot@kylinos.cn>
    Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
    Reviewed-by: Chaitanya Kulkarni <kch@nvidia.com>
    Link: https://lore.kernel.org/r/20220321071216.1549596-1-liu.yun@linux.dev
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>