cpufreq: intel_pstate: hide unused intel_pstate_cpu_oob_ids[]
JIRA: https://issues.redhat.com/browse/RHEL-39731

commit 8c556541a53848d6611ff8b5f9bf52e96c56f48e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 3 10:06:45 2024 +0200

    cpufreq: intel_pstate: hide unused intel_pstate_cpu_oob_ids[]

    The reference to this variable is hidden in an #ifdef:

    drivers/cpufreq/intel_pstate.c:2440:32: error: 'intel_pstate_cpu_oob_ids' defined but not used [-Werror=unused-const-variable=]

    Use the same check around the definition.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>