mmc: sdhci: drop useless sdhci_get_compatibility() !OF stub
JIRA: https://issues.redhat.com/browse/RHEL-41085

commit 6fb11c1812d337e2cc0dd482ffd99fce1b3f88e0
Author: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Date:   Tue Mar 14 21:39:01 2023 +0100

    mmc: sdhci: drop useless sdhci_get_compatibility() !OF stub

    The sdhci_get_compatibility() uses OF functions which have stubs for !OF
    case, thus entire CONFIG_OF ifdef can be dropped.  This also fixes
    !CONFIG_OF W=1 warning:

      drivers/mmc/host/sdhci-pltfm.c:76:6: error: no previous prototype for ‘sdhci_get_compatibility’ [-Werror=missing-prototypes]

    Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
    Acked-by: Adrian Hunter <adrian.hunter@intel.com>
    Link: https://lore.kernel.org/r/20230314203901.20803-1-krzysztof.kozlowski@linaro.org
    Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>

Signed-off-by: Lucas Karpinski <lkarpins@redhat.com>