usb: move assignment out of if condition
jira LE-1907
Rebuild_History Non-Buildable kernel-3.10.0-514.el7
Rebuild_CHGLOG: - [usb] move assignment out of if condition (Torez Smith) [1303955]
Rebuild_FUZZ: 93.33%
commit-author Kris Borer <kborer@gmail.com>
commit 0faaad461547e2412e9b519cd757a99b3ebc1302

Fix four occurrences of checkpatch.pl error:

ERROR: do not use assignment in if condition

The semantic patch that makes this change is:

// <smpl>
@@
identifier i;
expression E;
statement S;
constant c;
binary operator b;
@@

+ i = E;
  if (
- (i = E)
+ i
  b
  c ) S

@@
identifier i, i2;
expression E1, E2;
constant c;
@@

+ if( E1->i ) {
+  	i2 = E2;
+ 	if (i2 < c) {
- if( E1->i && (i2 = E2) < c ) {
  ...
- }
+ 	}
+ }
// </smpl>

	Signed-off-by: Kris Borer <kborer@gmail.com>
	Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 0faaad461547e2412e9b519cd757a99b3ebc1302)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>