dpll: zl3073x: Increase maximum size of flash utility
jira KERNEL-311
Rebuild_History Non-Buildable kernel-5.14.0-611.13.1.el9_7
commit-author Ivan Vecera <ivecera@redhat.com>
commit f3426ac54c42c3260096ddc50b5470eb179fb06a
Empty-Commit: Cherry-Pick Conflicts during history rebuild.
Will be included in final tarball splat. Ref for failed cherry-pick at:
ciq/ciq_backports/kernel-5.14.0-611.13.1.el9_7/f3426ac5.failed

Newer firmware bundles contain a flash utility whose size exceeds
the currently allowed limit. Increase the maximum allowed size
to accommodate the newer utility version.

Without this patch:
 # devlink dev flash i2c/1-0070 file fw_nosplit_v3.hex
 Failed to load firmware
 Flashing failed
 Error: zl3073x: FW load failed: [utility] component is too big (11000 bytes)

Fixes: ca017409da694 ("dpll: zl3073x: Add firmware loading functionality")
	Suggested-by: Prathosh Satish <Prathosh.Satish@microchip.com>
	Signed-off-by: Ivan Vecera <ivecera@redhat.com>
	Reviewed-by: Vadim Fedorenko <vadim.fedorenko@linux.dev>
Link: https://patch.msgid.link/20251008141418.841053-1-ivecera@redhat.com
	Signed-off-by: Paolo Abeni <pabeni@redhat.com>

(cherry picked from commit f3426ac54c42c3260096ddc50b5470eb179fb06a)
	Signed-off-by: Jonathan Maple <jmaple@ciq.com>

# Conflicts:
#	drivers/dpll/zl3073x/fw.c